// Person cards for event-1941.js (the Baltic states under German occupation,
// 1941–1944), see lib.js person().
const { W, person } = require('./lib');

const E = t => W(encodeURI(t));
const L = (lang, t) => `https://${lang}.wikipedia.org/wiki/` + encodeURI(t);
const S = {
    rosenberg: E('Alfred_Rosenberg'),
    ostland: E('Reichskommissariat_Ostland'),
    lohse: E('Hinrich_Lohse'),
    deLohse: L('de', 'Hinrich_Lohse'),
    stahlecker: E('Walter_Stahlecker'),
    kaunas: E('Kaunas_pogrom'),
    arajsK: E('Arajs_Kommando'),
    jager: E('Karl_Jäger'),
    jagerReport: E('Jäger_Report'),
    arajs: E('Viktors_Arājs'),
    mae: E('Hjalmar_Mäe'),
    etMae: L('et', 'Hjalmar_Mäe'),
    deMae: L('de', 'Hjalmar_Mäe'),
    lipke: E('Žanis_Lipke'),
    lvLipke: L('lv', 'Žanis_Lipke'),
    skirpa: E('Kazys_Škirpa'),
    uluots: E('Jüri_Uluots'),
    eeOcc: E('German_occupation_of_Estonia_during_World_War_II'),
};

// person() marks every activity confirmed; one with no catalog affiliation
// (the Self-Administration, the LAF, a rescue network, a university) must be
// unresolved instead, as in hungary-interwar-20261001/event-horthy.js.
const unaffiliated = card => ({
    ...card,
    activities: card.activities.map(a => (a.affiliationId ? a : { ...a, affiliationStatus: 'unresolved', relation: 'unresolved' })),
});

module.exports = [
    person({
        id: 'alfred-rosenberg',
        given: ['알프레트', 'Alfred'], family: ['로젠베르크', 'Rosenberg'], nativeName: 'Alfred Rosenberg', years: '1893–1946',
        citizenship: 'germany', origin: { code: 'germany', label: { ko: '발트 독일인', en: 'Baltic German' } },
        epithet: ['나치 인종 이론가로서 1941~1945년 동부 점령지 장관을 지낸 레발 태생의 발트 독일인',
            'Baltic German Nazi ideologue from Reval who served as Reich Minister for the Occupied Eastern Territories in 1941–1945'],
        bio: ['1893년 러시아 제국 에스토니아현의 레발(탈린)에서 태어나 리가 공과대학에서 건축을 공부했다. 1918년 물러가는 독일군과 함께 독일로 건너가 1919년 1월 히틀러보다 먼저 독일노동자당에 들어갔고, 1923년 당 기관지 『푈키셔 베오바흐터』의 편집장이 되었다. 1930년 인종 이론서 『20세기의 신화』를 냈고, 히틀러에게 「시온 장로 의정서」를 소개해 유대인 음모론을 심었다. 1941년 7월 17일 동부 점령지 장관이 되어 힌리히 로제를 오스트란트 국가판무관으로 두었으나 실권은 크게 제한되었다. 발트 지역을 독일의 「생존 공간」으로 보았다. 뉘른베르크 재판에서 네 죄목 모두 유죄를 받고 1946년 10월 16일 교수형에 처해졌다.',
            'Born in 1893 in Reval (Tallinn), in the Governorate of Estonia of the Russian Empire, he studied architecture at the Riga Polytechnical Institute. In 1918 he left for Germany with the retreating German army and in January 1919 joined the German Workers’ Party, eight months before Hitler; in 1923 he became editor of the party newspaper Völkischer Beobachter. In 1930 he published his racial treatise The Myth of the Twentieth Century, and he fed Hitler’s belief in Jewish conspiracies by introducing him to The Protocols of the Elders of Zion. Appointed Reich Minister for the Occupied Eastern Territories on 17 July 1941, he had Hinrich Lohse installed as Reichskommissar for Ostland, though his own authority was severely limited. He saw the Baltic lands as German “Lebensraum”. Found guilty on all four counts at Nuremberg, he was hanged on 16 October 1946.'],
        fate: ['executed', '처형(교수형)', 'Executed by hanging'],
        aliases: { ko: ['알프레트 에른스트 로젠베르크'], en: ['Alfred Rosenberg', 'Alfred Ernst Rosenberg'] },
        sources: [S.rosenberg, S.ostland],
        facts: {
            years: { claim: '1893–1946', locator: 'lead', excerpt: '12 January 1893 [O.S. 31 December 1892] – 16 October 1946' },
            citizenship: { claim: 'held posts in the Nazi German government', locator: 'lead', excerpt: 'he held several important posts in the Nazi government' },
            nationalOrigin: { claim: 'Baltic German', locator: 'lead', excerpt: 'was a Baltic German Nazi philosopher and convicted war criminal' },
            bio: [
                { claim: 'born in Reval, Governorate of Estonia, 1893', locator: 'Family', excerpt: 'Rosenberg was born on 12 January 1893 in Reval (now Tallinn, Estonia), then in the Governorate of Estonia of the Russian Empire.' },
                { claim: 'architecture at the Riga Polytechnical Institute', locator: 'Education and early career', excerpt: 'enrolled in architecture studies at the Riga Polytechnical Institute in the autumn of 1910' },
                { claim: 'left with the retreating German army', locator: 'Education and early career', excerpt: 'He emigrated to Germany with the retreating Imperial German army' },
                { claim: 'joined the party in January 1919, before Hitler', locator: 'Education and early career', excerpt: 'joining in January 1919, eight months before Adolf Hitler joined in September' },
                { claim: 'editor of the Völkischer Beobachter from 1923', locator: 'Education and early career', excerpt: 'Eckart was its first editor and after his bout with alcoholism, Rosenberg became its editor in 1923.' },
                { claim: 'The Myth of the Twentieth Century, 1930', locator: 'Pre-war years', excerpt: 'In 1930, he published his philosophical book of racial theory The Myth of the Twentieth Century' },
                { claim: 'introduced Hitler to the Protocols', locator: 'Pre-war years', excerpt: "Rosenberg also played a key role in developing Hitler's belief in Jewish conspiracies by introducing him to The Protocols of the Elders of Zion." },
                { claim: 'Reich Minister for the Occupied Eastern Territories, 17 July 1941', locator: 'Reich Minister for the Occupied Eastern Territories', excerpt: 'Rosenberg was appointed head of the Reich Ministry for the Occupied Eastern Territories (Reichsministerium für die besetzten Ostgebiete) on 17 July 1941.' },
                { claim: 'Ostland under Lohse', locator: 'Reich Minister for the Occupied Eastern Territories', excerpt: 'they immediately implemented the first of the proposed Reichskommissariate of Ostland and Ukraine, under the leadership of Hinrich Lohse and Erich Koch, respectively' },
                { claim: 'authority severely limited', source: S.ostland, locator: 'After Operation Barbarossa', excerpt: "Rosenberg's ministerial authority was, in practice, severely limited." },
                { claim: 'Baltic lands as Lebensraum', source: S.ostland, locator: 'German plans', excerpt: 'should therefore provide Germany with "Lebensraum"' },
                { claim: 'guilty on all four counts at Nuremberg', locator: 'Trial and execution', excerpt: 'He was tried at Nuremberg and found guilty of all four counts' },
                { claim: 'executed 16 October 1946', locator: 'Trial and execution', excerpt: 'He was sentenced to death and executed with other condemned co-defendants at Nuremberg Prison on the morning of 16 October 1946.' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-germany', startYear: 1941, endYear: 1945, primary: true, claim: '동부 점령지 장관', locator: 'lead', excerpt: 'During World War II, Rosenberg was the head of the Reich Ministry for the Occupied Eastern Territories (1941–1945).' },
            { functionId: 'propaganda', affiliationId: 'german-nazi', startYear: 1923, endYear: 1945, claim: '나치 이론가, 『푈키셔 베오바흐터』 편집장', locator: 'lead', excerpt: 'He also served as the editor of the Nazi Party newspaper Völkischer Beobachter.' },
        ],
        career: [
            ['1919', '독일노동자당 입당', 'Joined the German Workers’ Party'],
            ['1923', '『푈키셔 베오바흐터』 편집장', 'Editor of the Völkischer Beobachter'],
            ['1930', '『20세기의 신화』 출간', 'Published The Myth of the Twentieth Century'],
            ['1941–1945', '동부 점령지 장관', 'Reich Minister for the Occupied Eastern Territories'],
            ['1946', '뉘른베르크 재판 사형 선고, 처형', 'Sentenced to death at Nuremberg and executed'],
        ],
    }),
    person({
        id: 'hinrich-lohse',
        given: ['힌리히', 'Hinrich'], family: ['로제', 'Lohse'], nativeName: 'Hinrich Lohse', years: '1896–1964',
        citizenship: 'germany', origin: 'germany',
        epithet: ['1941~1944년 오스트란트 국가판무관으로서 발트 유대인의 게토 수용과 재산 몰수를 명령한 나치 대관구장',
            'Nazi Gauleiter of Schleswig-Holstein who, as Reichskommissar for Ostland in 1941–1944, ordered the ghettoisation and expropriation of Jews'],
        bio: ['슐레스비히홀슈타인의 농가에서 태어나 제1차 세계대전에서 중상을 입었다. 1923년 나치당에 들어가 1925년 슐레스비히홀슈타인 대관구장이 되었고, 1933년 이 주의 주지사를 겸했다. 1941년 7월 25일 오스트란트 국가판무관에 임명되어 리가와 킬을 오갔고, 7월 27일 포고로 유대인 명부 작성, 노란 별 착용, 재산 몰수와 게토 수용을 명령했다. 리에파야의 유대인 처형을 막은 일로 해명을 요구받자 11월 15일 경제적 이해와 상관없이 모든 유대인을 없애라는 것인지 물었으나, 이후 3년 동안 자리를 지켰다. 1944년 8월 13일 허가 없이 오스트란트를 떠나 해임되었다. 1948년 징역 10년을 선고받았으나 1951년 건강 문제로 풀려났고 1964년 고향에서 숨졌다.',
            'Born into a peasant family in Schleswig-Holstein, he was severely wounded in the First World War. He joined the Nazi Party in 1923, became Gauleiter of Schleswig-Holstein in 1925 and in 1933 also Oberpräsident of the province. Appointed Reichskommissar for Ostland on 25 July 1941, he shuttled between Riga and Kiel; his decree of 27 July ordered lists of Jews, the yellow badge, the confiscation of their property and their concentration in ghettos. Asked to explain his order forbidding the execution of Jews in Libau (Liepāja), he wrote on 15 November asking whether all Jews were to be liquidated regardless of economic interests, yet he stayed at his post for three more years. He fled Ostland without authorisation on 13 August 1944 and was removed. Sentenced in 1948 to ten years, he was released for ill health in 1951 and died in his home village in 1964.'],
        fate: ['natural', '고향에서 사망', 'Died in his home village'],
        aliases: { ko: [], en: ['Hinrich Lohse'] },
        sources: [S.lohse, S.deLohse],
        facts: {
            years: { claim: '1896–1964', locator: 'lead', excerpt: '2 September 1896 – 25 February 1964' },
            citizenship: { claim: 'German Nazi Party official', locator: 'lead', excerpt: 'was a German Nazi Party official, politician and convicted war criminal' },
            nationalOrigin: { claim: 'German merchant and politician', source: S.deLohse, locator: 'Einleitung', excerpt: 'war ein deutscher Kaufmann, Bankangestellter und nationalsozialistischer Politiker' },
            bio: [
                { claim: 'peasant family in Schleswig-Holstein', locator: 'Early life', excerpt: 'Hinrich Lohse was born into a peasant family in the town of Mühlenbarbek in the Province of Schleswig-Holstein.' },
                { claim: 'severely wounded in 1916', locator: 'Early life', excerpt: 'He served in combat on the western front with Reserve Infantry Regiment 94 until he was severely wounded on 9 August 1916.' },
                { claim: 'joined the Nazi Party 1923, Gauleiter 1925', locator: 'Nazi Party career in Schleswig-Holstein', excerpt: "In the Spring of that year, he joined the Nazi Party (membership number 7,522) and was appointed the Party's Gauleiter for Schleswig-Holstein on 27 March 1925." },
                { claim: 'Oberpräsident from 1933', locator: 'Nazi Party career in Schleswig-Holstein', excerpt: 'Shortly after the Nazi seizure of power he was appointed as Oberpräsident (high president) of the province of Schleswig-Holstein on 25 March 1933.' },
                { claim: 'Reichskommissar for Ostland, 25 July 1941', locator: 'Reichskommissar in the Baltics and Holocaust involvement', excerpt: 'On 25 July 1941, following the German conquest of the Baltic states from the Soviet Union, Lohse was appointed Reichskommissar' },
                { claim: 'shuttled between Riga and Kiel', locator: 'Reichskommissar in the Baltics and Holocaust involvement', excerpt: 'Lohse retained his functions in Schleswig-Holstein and shuttled between his two seats of Riga and Kiel.' },
                { claim: 'decree of 27 July 1941', locator: 'Reichskommissar in the Baltics and Holocaust involvement', excerpt: 'These measures, first put forth in his decree of 27 July 1941, included compiling lists of Jews, mandating that they must wear the yellow badge, confiscating their property' },
                { claim: 'ghettos', locator: 'Reichskommissar in the Baltics and Holocaust involvement', excerpt: 'They were to be gathered together in ghettos' },
                { claim: 'asked to explain his order forbidding executions in Libau', locator: 'Reichskommissar in the Baltics and Holocaust involvement', excerpt: 'requesting an explanation for his order forbidding the execution of Jews in Libau' },
                { claim: 'reply of 15 November', locator: 'Reichskommissar in the Baltics and Holocaust involvement', excerpt: 'without regard to age and sex and economic interests' },
                { claim: 'stayed three more years', locator: 'Reichskommissar in the Baltics and Holocaust involvement', excerpt: 'he continued to remain in his post for the next three years while Holocaust-related murders continued' },
                { claim: 'fled on 13 August 1944 and removed', locator: 'Reichskommissar in the Baltics and Holocaust involvement', excerpt: 'Lohse fled the Reichskommissariat Ostland without authorization on 13 August 1944 in the face of the Red Army advance, and he was immediately removed as Reichskommissar.' },
                { claim: 'ten years, trial ending January 1948', locator: 'Postwar trial and life', excerpt: 'He was tried by the court in Bielefeld between October 1947 and January 1948, and was sentenced to 10 years in prison' },
                { claim: 'released 1951 for ill health', locator: 'Postwar trial and life', excerpt: 'until he was released in March 1951 due to ill health (thrombosis)' },
                { claim: 'died in his hometown 1964', locator: 'Postwar trial and life', excerpt: 'Lohse spent his later years in his hometown of Mühlenbarbek, where he died in February 1964.' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-germany', startYear: 1941, endYear: 1944, primary: true, claim: '오스트란트 국가판무관', locator: 'lead', excerpt: 'He is best known for his rule of the Reichskommissariat Ostland, during the Second World War.' },
            { functionId: 'political-leadership', affiliationId: 'german-nazi', startYear: 1925, endYear: 1945, claim: '나치당 슐레스비히홀슈타인 대관구장', locator: 'lead', excerpt: 'He served as the Gauleiter and Oberpräsident of Schleswig-Holstein' },
        ],
        career: [
            ['1923', '나치당 입당', 'Joined the Nazi Party'],
            ['1925', '슐레스비히홀슈타인 대관구장', 'Gauleiter of Schleswig-Holstein'],
            ['1933', '슐레스비히홀슈타인 주지사', 'Oberpräsident of Schleswig-Holstein'],
            ['1941–1944', '오스트란트 국가판무관', 'Reichskommissar for Ostland'],
            ['1948–1951', '징역 10년 선고, 1951년 석방', 'Sentenced to ten years; released 1951'],
        ],
    }),
    person({
        id: 'walter-stahlecker',
        given: ['발터', 'Walter'], family: ['슈탈레커', 'Stahlecker'], nativeName: 'Walter Stahlecker', years: '1900–1942',
        citizenship: 'germany', origin: 'germany',
        epithet: ['1941년 특수작전집단 A를 이끌며 카우나스 포그롬을 부추기고 발트 유대인 살해를 지휘한 친위대 장교',
            'SS officer who led Einsatzgruppe A in 1941, instigating the Kaunas pogrom and directing the murder of Baltic Jews'],
        bio: ['슈테르넨펠스의 목사 집안에서 태어나 튀빙겐 대학에서 법학 박사가 되었다. 1932년 나치당과 친위대에 들어가 뷔르템베르크와 브레슬라우의 게슈타포를 이끌었고, 1938년 빈의 유대인 이주 중앙청 공식 수장이 되었다. 1941년 2월 특수작전집단 A 사령관이 되어 6월 북부집단군을 따라 발트 3국에 들어갔다. 카우나스에서는 클리마이티스에게 포그롬을 시키고 리가에서는 아라이스에게 부대를 꾸리게 하는 등, 학살을 현지인의 「자기 정화」처럼 꾸몄다. 1941년 겨울까지 유대인 24만 9,420명을 죽였다고 보고했고, 11월 말 오스트란트 보안경찰·정보부(SD) 사령관이 되었다. 1942년 3월 러시아 크라스노그바르데이스크 근처에서 소련 파르티잔에게 치명상을 입었다.',
            'Born into a pastor’s family in Sternenfels, he took a doctorate in law at Tübingen. He joined the Nazi Party and the SS in 1932, headed the Gestapo in Württemberg and then Breslau, and in 1938 became formal head of the Central Agency for Jewish Emigration in Vienna. Given command of Einsatzgruppe A in February 1941, he followed Army Group North into the Baltic states in June. He had Klimaitis start a pogrom in Kaunas and Arājs raise a unit in Riga, staging the killings as the “self-cleansing” of the local population. By the winter of 1941 he reported that Einsatzgruppe A had murdered some 249,420 Jews, and at the end of November he became commander of the Security Police and SD for Ostland. He was fatally wounded by Soviet partisans near Krasnogvardeysk, Russia, in March 1942.'],
        fate: ['killed', '파르티잔과 싸우다 치명상', 'Fatally wounded by Soviet partisans'],
        aliases: { ko: ['프란츠 발터 슈탈레커'], en: ['Franz Walter Stahlecker', 'Walter Stahlecker'] },
        sources: [S.stahlecker, S.kaunas, S.arajsK],
        facts: {
            years: { claim: '1900–1942', locator: 'lead', excerpt: '10 October 1900 – 23 March 1942' },
            citizenship: { claim: 'born in Germany', locator: 'Early life', excerpt: 'Stahlecker was born into a wealthy family in Sternenfels, Germany on 10 October 1900.' },
            nationalOrigin: { claim: 'son of a German pastor', locator: 'Early life', excerpt: 'He was the second of three sons of the pastor and director of studies Eugen Stahlecker' },
            bio: [
                { claim: 'doctorate in law, Tübingen', locator: 'Early life', excerpt: 'He studied at the University of Tübingen, where he obtained a doctorate of law in 1927.' },
                { claim: 'Nazi Party and SS, 1932', locator: 'Early Nazi career', excerpt: 'On 1 May 1932, Stahlecker joined the Nazi Party (no. 3,219,015) as well as the Schutzstaffel (SS no. 73,041).' },
                { claim: 'Gestapo Württemberg', locator: 'Early Nazi career', excerpt: 'In 1934, he was appointed head of the Gestapo in the German state of Württemberg' },
                { claim: 'Gestapo Breslau', locator: 'Early Nazi career', excerpt: 'On 11 May 1937, he became head of the Gestapo in Breslau.' },
                { claim: 'Central Agency for Jewish Emigration in Vienna', locator: 'Early Nazi career', excerpt: 'As of 20 August 1938, Stahlecker was the formal head of the Central Agency for Jewish Emigration in Vienna' },
                { claim: 'Einsatzgruppe A from February 1941', locator: 'Einsatzgruppe A', excerpt: 'On 6 February 1941 Stahlecker was promoted to SS-Brigadeführer and Generalmajor der Polizei and took over as commanding officer of Einsatzgruppe A' },
                { claim: 'followed Army Group North into the Baltic states', locator: 'Einsatzgruppe A', excerpt: 'In June 1941, Einsatzgruppe A followed Army Group North and operated in Lithuania, Latvia, Estonia and areas of Russia up to Leningrad.' },
                { claim: 'asked Klimaitis to start pogroms in Kaunas', source: S.kaunas, locator: 'Background', excerpt: 'so he asked Algirdas Klimaitis to initiate pogroms' },
                { claim: 'had Arājs set up a unit in Riga', source: S.arajsK, locator: 'Formation', excerpt: 'Stahlecker was impressed by Arājs and instructed him to set up a temporary paramilitary unit' },
                { claim: 'self-cleansing staged', locator: 'Einsatzgruppe A', excerpt: 'It was the duty of the Security Police to set in motion these self-cleansing movements' },
                { claim: '249,420 Jews reported', locator: 'Einsatzgruppe A', excerpt: 'By winter 1941, Stahlecker reported to the German government that Einsatzgruppe A had murdered some 249,420 Jews.' },
                { claim: 'BdS Ostland end of November 1941', locator: 'Einsatzgruppe A', excerpt: 'He was made Commander of the Security Police and the SD (Befehlshaber der Sicherheitspolizei und des SD) of Reichskommissariat Ostland' },
                { claim: 'fatally wounded by partisans, March 1942', locator: 'Einsatzgruppe A', excerpt: 'Stahlecker was fatally wounded in action on 22 March 1942, by Soviet partisans near Krasnogvardeysk, Russia.' },
            ],
        },
        activities: [
            { functionId: 'security', affiliationId: 'german-nazi', startYear: 1932, endYear: 1942, primary: true, claim: '게슈타포·보안경찰 간부, 특수작전집단 A 사령관', locator: 'lead', excerpt: 'Stahlecker commanded Einsatzgruppe A, the most murderous of the four Einsatzgruppen' },
        ],
        career: [
            ['1927', '튀빙겐 대학 법학 박사', 'Doctorate in law, Tübingen'],
            ['1932', '나치당·친위대 가입', 'Joined the Nazi Party and the SS'],
            ['1938', '빈 유대인 이주 중앙청 수장', 'Head of the Central Agency for Jewish Emigration, Vienna'],
            ['1941', '특수작전집단 A 사령관, 오스트란트 보안경찰 사령관', 'Commander of Einsatzgruppe A; Security Police commander for Ostland'],
            ['1942', '소련 파르티잔에게 치명상', 'Fatally wounded by Soviet partisans'],
        ],
    }),
    person({
        id: 'karl-jager',
        given: ['카를', 'Karl'], family: ['예거', 'Jäger'], nativeName: 'Karl Jäger', years: '1888–1959',
        citizenship: 'germany', origin: null,
        epithet: ['리투아니아 유대인 총살을 지휘하고 「예거 보고서」를 남긴 특무부대 3 지휘관',
            'Commander of Einsatzkommando 3 who directed the murder of Lithuania’s Jews and tallied it in the Jäger Report'],
        bio: ['스위스 샤프하우젠에서 태어나 세 살 때 아버지를 따라 독일로 옮겼다. 제1차 세계대전에서 1급 철십자훈장을 받았고, 오케스트리온 공장 관리자로 일하며 1923년 나치당에 들어가 「발트키르히의 히틀러」로 불렸다. 1932년 친위대에 들어갔다. 1941년 7월부터 1943년 9월까지 카우나스에서 특수작전집단 A 산하 특무부대 3을 지휘하며 리투아니아인의 도움을 받아 유대인 남녀와 어린이를 가리지 않고 총살했고, 1941년 11월 제9요새 학살을 저질렀다. 1941년 12월 1일 13만 7,346명의 처형을 날마다 집계한 보고서를 썼다. 1943년 말 신경 쇠약으로 독일에 돌아갔고, 전후 농장 일꾼으로 살다 1959년 보고서가 드러나 체포되자 재판 전에 목을 매 자살했다.',
            'Born in Schaffhausen, Switzerland, he moved to Germany with his father at the age of three. He won the Iron Cross First Class in the First World War, managed an orchestrion factory in Waldkirch and joined the Nazi Party in 1923, becoming known as “Waldkirch’s Hitler”; he joined the SS in 1932. From July 1941 to September 1943 he commanded Einsatzkommando 3 of Einsatzgruppe A in Kaunas, which with Lithuanian help shot Jewish men, women and children indiscriminately and carried out the Ninth Fort massacres of November 1941. On 1 December 1941 he wrote a report keeping an almost daily tally of 137,346 executions. Sent back to Germany in late 1943 after a nervous breakdown, he lived after the war as a farm hand until his report came to light in 1959; arrested, he hanged himself while awaiting trial.'],
        fate: ['suicide', '재판을 기다리다 자살', 'Suicide while awaiting trial'],
        aliases: { ko: [], en: ['Karl Jäger', 'Karl Jaeger'] },
        sources: [S.jager, S.jagerReport],
        facts: {
            years: { claim: '1888–1959', locator: 'lead', excerpt: '20 September 1888 – 22 June 1959' },
            citizenship: { claim: 'German SS official', locator: 'lead', excerpt: 'was a German mid-ranking official in the SS of Nazi Germany' },
            bio: [
                { claim: 'born in Schaffhausen, moved to Germany at three', locator: 'Early life and career', excerpt: 'Jäger was born in Schaffhausen, Switzerland, and moved with his father to Germany when he was 3 years of age.' },
                { claim: 'Iron Cross First Class', locator: 'Early life and career', excerpt: 'where he received the Iron Cross (1st Class) and other awards' },
                { claim: 'orchestrion factory manager in Waldkirch', locator: 'Early life and career', excerpt: 'obtained a managerial position with the Weber orchestrion factory in Waldkirch' },
                { claim: 'Nazi Party 1923', locator: 'Early life and career', excerpt: 'He joined the Nazi Party in 1923' },
                { claim: '“Waldkirch’s Hitler”', locator: 'Early life and career', excerpt: "he became known as \"Waldkirch's Hitler\"" },
                { claim: 'SS 1932', locator: 'Early life and career', excerpt: 'Jäger joined the SS in 1932' },
                { claim: 'commander of Einsatzkommando 3 in Kaunas, July 1941 – September 1943', locator: 'Mass murders in Eastern Europe', excerpt: 'From July 1941 until September 1943 Jäger served as commander of the SD Einsatzkommando 3a, a sub-unit of Einsatzgruppe A under Franz Walter Stahlecker, in Kaunas.' },
                { claim: 'shot Jews indiscriminately with Lithuanian help', locator: 'Mass murders in Eastern Europe', excerpt: "Under Jäger's command, the Einsatzkommando, with the help of Lithuanians, shot Jewish men, women and children indiscriminately." },
                { claim: 'Ninth Fort massacres', locator: 'Mass murders in Eastern Europe', excerpt: 'It perpetrated the Ninth Fort massacres of November 1941.' },
                { claim: 'report of 1 December 1941', source: S.jagerReport, locator: 'lead', excerpt: 'was written on 1 December 1941 by Karl Jäger, commander of Einsatzkommando 3 (EK 3)' },
                { claim: '137,346 tallied', source: S.jagerReport, locator: 'Description', excerpt: 'The report keeps an almost daily running total of the murders of 137,346 people' },
                { claim: 'nervous breakdown, reassigned late 1943', locator: 'Mass murders in Eastern Europe', excerpt: 'Reassigned back to Germany near the end of 1943 after a nervous breakdown' },
                { claim: 'farm hand until 1959', locator: 'Escape, capture and suicide', excerpt: 'Jäger was able to assimilate back into society as a farm hand until his report was discovered in March 1959.' },
                { claim: 'suicide awaiting trial', locator: 'Escape, capture and suicide', excerpt: 'Jäger committed suicide by hanging himself in Hohenasperg prison' },
            ],
        },
        activities: [
            { functionId: 'security', affiliationId: 'german-nazi', startYear: 1932, endYear: 1945, primary: true, claim: '친위대 정보부(SD) 장교, 특무부대 3 지휘관', locator: 'Early life and career', excerpt: 'Jäger was named commander of Einsatzkommando 3, a unit of Einsatzgruppe A' },
        ],
        career: [
            ['1923', '나치당 입당', 'Joined the Nazi Party'],
            ['1932', '친위대 가입', 'Joined the SS'],
            ['1941–1943', '카우나스의 특무부대 3 지휘관', 'Commander of Einsatzkommando 3 in Kaunas'],
            ['1941', '「예거 보고서」 작성', 'Wrote the Jäger Report'],
            ['1959', '체포 뒤 옥중 자살', 'Arrested; suicide in prison'],
        ],
    }),
    person({
        id: 'viktors-arajs',
        given: ['빅토르스', 'Viktors'], family: ['아라이스', 'Arājs'], nativeName: 'Viktors Arājs', years: '1910–1988',
        citizenship: 'latvia', origin: { code: 'latvia', label: { ko: '라트비아인(어머니는 발트 독일계)', en: 'Latvian; mother of Baltic German family' } },
        epithet: ['룸불라 학살 등에서 라트비아 유대인의 약 절반을 죽인 아라이스 특공대의 지휘관',
            'Latvian former policeman whose Arajs Kommando, under the SS Security Service, murdered about half of Latvia’s Jews'],
        bio: ['발도네에서 라트비아인 대장장이 아버지와 발트 독일계 어머니 사이에 태어났다. 라트비아군에서 복무하고 라트비아 대학에서 법학을 공부했으며 1938년까지 경찰관으로 일했다. 1941년 7월 독일군이 리가에 들어오자 슈탈레커를 만나 대학생 단체와 뇌성십자 출신으로 부대를 꾸렸고, 이 부대는 7월 4일 리가 회당 방화에 가담했다. 아라이스 특공대는 라트비아와 벨라루스에서 약 2만 6,000명을 죽였고, 그는 1943년 친위대 소령이 되었다. 전후 1949년까지 영국군 포로수용소에 갇혔다가 가명으로 프랑크푸르트에서 일했다. 1979년 함부르크 지방법원은 1941년 12월 8일 리가 게토 유대인을 죽음으로 내몬 죄로 종신형을 선고했고, 1988년 카셀의 감옥에서 숨졌다.',
            'Born in Baldone to a Latvian blacksmith and a mother from a wealthy Baltic German family, he served in the Latvian Army, studied law at the University of Latvia and was a policeman until 1938. When the Germans entered Riga in July 1941 he was introduced to Stahlecker and recruited a unit from his student fraternity and the Pērkonkrusts, which took part in burning Riga’s synagogues on 4 July. The Arajs Kommando murdered some 26,000 people in Latvia and then Belarus, and he was made an SS-Sturmbannführer in 1943. Interned in a British camp until 1949, he lived under a false name and worked at a printing company in Frankfurt. In 1979 the Hamburg State Court sentenced him to life imprisonment for leading the Jews of the Riga ghetto to their deaths on 8 December 1941; he died in prison in Kassel in 1988.'],
        fate: ['natural', '복역 중 옥사', 'Died in prison'],
        aliases: { ko: [], en: ['Viktors Arājs', 'Viktors Arajs', 'Viktors Bernhard Arājs'] },
        sources: [S.arajs, S.arajsK],
        facts: {
            years: { claim: '1910–1988', locator: 'lead', excerpt: '13 January 1910 – 13 January 1988' },
            citizenship: { claim: 'Latvian collaborator', locator: 'lead', excerpt: 'was a Latvian/Baltic German collaborator and Nazi SS SD officer' },
            nationalOrigin: { claim: 'Latvian father, Baltic German mother', locator: 'Life', excerpt: 'His father was a Latvian blacksmith and his mother came from a wealthy family of Baltic Germans.' },
            bio: [
                { claim: 'born in Baldone', locator: 'Life', excerpt: 'Viktors Bernhard Arājs was born on 13 January 1910 in the town of Baldone' },
                { claim: 'Latvian Army service', locator: 'Life', excerpt: 'which he left in 1930 for mandatory national defense service in the Latvian Army' },
                { claim: 'law at the University of Latvia', locator: 'Life', excerpt: 'In 1932, Arājs studied law at the University of Latvia in Riga' },
                { claim: 'police until 1938', locator: 'Life', excerpt: 'Arājs remained with the Latvian police until he left the service in 1938.' },
                { claim: 'introduced to Stahlecker', locator: 'Activities during World War II', excerpt: 'Because of this friendship, Arājs was introduced to Stahlecker' },
                { claim: 'recruited from fraternity and Pērkonkrusts', locator: 'Activities during World War II', excerpt: 'Arājs recruited the core of his troops from his student fraternity and Pērkonkrusts.' },
                { claim: 'burning of Riga’s synagogues', source: S.arajsK, locator: 'Activity', excerpt: "On the night of 4 July, the Arajs Kommando were participants in the burning of Riga's synagogues." },
                { claim: 'some 26,000 murdered', locator: 'Activities during World War II', excerpt: 'The unit murdered approximately 26,000 people, first in Latvia and then in Belarus.' },
                { claim: 'SS-Sturmbannführer 1943', locator: 'Activities during World War II', excerpt: 'Arājs was promoted to police major in 1942, and in 1943 to SS-Sturmbannführer.' },
                { claim: 'interned until 1949', locator: 'Post-war', excerpt: 'Until 1949, Arājs was interned in a British prisoner-of-war camp in Germany.' },
                { claim: 'cover name, Frankfurt', locator: 'Post-war', excerpt: 'He worked in Frankfurt am Main as an assistant at a printing company.' },
                { claim: 'Hamburg verdict 1979', locator: 'Post-war', excerpt: 'he was found guilty in the State Court of Hamburg (Landgericht Hamburg) of having on 8 December 1941 conducted the Jews of the greater Riga Ghetto to their deaths' },
                { claim: 'life imprisonment', locator: 'Post-war', excerpt: 'he was sentenced to life imprisonment' },
                { claim: 'died in prison in Kassel 1988', locator: 'Post-war', excerpt: 'In 1988, Arājs died in solitary confinement in a prison in Kassel.' },
            ],
        },
        activities: [
            { functionId: 'security', affiliationId: 'german-nazi', startYear: 1941, endYear: 1945, primary: true, claim: '친위대 정보부(SD) 산하 아라이스 특공대 지휘관', locator: 'lead', excerpt: 'took part in the Holocaust during the German occupation of Latvia and Belarus as the leader of the Arajs Kommando' },
            { functionId: 'security', affiliationId: 'state-latvia', startYear: null, endYear: 1938, claim: '라트비아 경찰관', locator: 'Life', excerpt: 'Arājs remained with the Latvian police until he left the service in 1938.' },
        ],
        career: [
            ['1930', '라트비아군 복무', 'Service in the Latvian Army'],
            ['1938', '라트비아 경찰 퇴직', 'Left the Latvian police'],
            ['1941–1943', '아라이스 특공대 지휘관', 'Commander of the Arajs Kommando'],
            ['1979', '함부르크 지방법원 종신형', 'Life sentence, Hamburg State Court'],
        ],
    }),
    person({
        id: 'hjalmar-mae',
        given: ['햘마르', 'Hjalmar'], family: ['매에', 'Mäe'], nativeName: 'Hjalmar Mäe', years: '1901–1978',
        citizenship: 'estonia', origin: 'estonia',
        epithet: ['1941~1944년 독일 점령하 「에스토니아 자치행정」을 이끈 밥스 운동 출신의 협력 정치인',
            'Estonian Vaps politician who headed the collaborationist Estonian Self-Administration under German occupation in 1941–1944'],
        bio: ['하리우주 투할라에서 태어나 베를린·빈·인스브루크·그라츠에서 공부해 1927년 지구물리학, 1930년 헌법학 박사가 되었다. 두 차례 총선에 출마했다가 해방전쟁참전자동맹(밥스)에 들어가 선전 책임자가 되었고, 1935년 20년 강제노동형을 받았으나 1938년 사면으로 풀려나 독일로 건너가 독일 국적을 얻었다. 1941년 5월 헬싱키에서 에스토니아 해방위원회를 세웠고, 그해 독일군과 함께 돌아와 1941~1944년 에스토니아 자치행정을 이끌었다. 1944년 오스트리아로 달아나 서방 연합국에게 나치 범죄 혐의를 벗었고 오스트리아 정부 자문으로 일했다. 1990년대 에스토니아의 국제 조사위원회는 그를 에스토니아 경찰·친위대 부대의 범죄에 책임 있는 주요 인물로 지목했다.',
            'Born at Tuhala in Harju County, he studied in Berlin, Vienna, Innsbruck and Graz and took doctorates in geophysics (1927) and constitutional law (1930). After standing twice for parliament he joined the Vaps movement as its propaganda chief; sentenced in 1935 to twenty years’ hard labour, he was amnestied in 1938, went to Germany and took German citizenship. In May 1941 he founded the Estonian Liberation Committee in Helsinki, and returning with the German army that year he headed the Estonian Self-Administration from 1941 to 1944. In 1944 he fled to Austria, where the Western Allies cleared him of Nazi crimes and he later advised the Austrian government. In the 1990s Estonia’s International Commission named him among the Estonians chiefly responsible for crimes committed by Estonian police and SS units.'],
        fate: ['natural', '망명지 그라츠에서 사망', 'Died in Graz, Austria'],
        aliases: { ko: [], en: ['Hjalmar Mäe', 'Hjalmar Mae', 'Hjalmar-Johannes Mäe'] },
        sources: [S.mae, S.etMae, S.deMae],
        facts: {
            years: { claim: '1901–1978', locator: 'lead', excerpt: '24 October [O.S. 11 October] 1901 – 10 April 1978' },
            citizenship: { claim: 'Estonian politician', locator: 'lead', excerpt: 'was an Estonian politician and Nazi collaborator' },
            nationalOrigin: { claim: 'Estonian politician, born at Tuhala', source: S.etMae, locator: 'sissejuhatus', excerpt: '1901 Tuhala, Vladimiri vald, Harjumaa – 10. aprill 1978 Graz, Austria) oli Eesti poliitik' },
            bio: [
                { claim: 'born at Tuhala, died in Graz', source: S.etMae, locator: 'sissejuhatus', excerpt: '1901 Tuhala, Vladimiri vald, Harjumaa – 10. aprill 1978 Graz, Austria' },
                { claim: 'doctorates 1927 and 1930', locator: 'Biography', excerpt: 'After studies in Berlin, Vienna and Innsbruck, Mäe graduated with doctoral degrees in geophysics from the University of Innsbruck in 1927, and in constitutional law from the University of Graz in 1930.' },
                { claim: 'twice a candidate', locator: 'Biography', excerpt: 'Mäe was twice a candidate to the Riigikogu' },
                { claim: 'joined Vaps', locator: 'Biography', excerpt: 'He later joined the Vaps Movement, for which he was arrested during the government of Konstantin Päts.' },
                { claim: 'Vaps propaganda chief', source: S.etMae, locator: 'Vabadussõjalaste liikumises', excerpt: 'Samal päeval sai temast Eesti Vabadussõjalaste Liidu propagandajuht.' },
                { claim: '20 years, amnestied 1938, to Germany', locator: 'Biography', excerpt: 'In 1935 Mäe was sentenced to 20 years of hard labour, but was released under a 1938 amnesty law and moved to Nazi Germany.' },
                { claim: 'German citizenship', source: S.deMae, locator: 'Leben', excerpt: 'nach Deutschland und erhielt die deutsche Staatsbürgerschaft' },
                { claim: 'Estonian Liberation Committee, Helsinki, May 1941', source: S.etMae, locator: 'Eesti Vabastamise Komitee esimehena', excerpt: '1941. aasta mai algul sõitis Mäe Helsingisse, kus moodustas Eesti Vabastamise Komitee, mille esimeheks ta ka valiti.' },
                { claim: 'returned with the Germans and headed the Self-Administration', locator: 'Biography', excerpt: 'Mäe returned to Estonia with the German armies in 1941 and was made head of the Estonian Self-Administration' },
                { claim: 'fled to Austria, cleared, adviser', locator: 'Biography', excerpt: 'In 1944 he fled the advancing Red Army to Austria where he was cleared of Nazi crimes by the Western Allies, and later would serve as an advisor to the Austrian government.' },
                { claim: 'named by the International Commission', source: S.deMae, locator: 'Leben', excerpt: 'erklärte die von der estnischen Regierung eingesetzte Internationale Untersuchungskommission Mäe zu einem der estnischen Hauptverantwortlichen für Kriegsverbrechen und Verbrechen gegen die Menschlichkeit durch estnische Polizei- und SS-Einheiten' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: null, startYear: 1941, endYear: 1944, primary: true, claim: '에스토니아 자치행정 수장', locator: 'lead', excerpt: 'In 1941–1944 he headed the Estonian Self-Administration, a puppet government set up during the country\'s occupation by Nazi Germany during World War II.' },
            { functionId: 'propaganda', affiliationId: null, startYear: null, endYear: 1934, claim: '해방전쟁참전자동맹(밥스) 선전 책임자', source: S.etMae, locator: 'Vabadussõjalaste liikumises', excerpt: 'Samal päeval sai temast Eesti Vabadussõjalaste Liidu propagandajuht.' },
        ],
        career: [
            ['1927–1930', '인스브루크 지구물리학·그라츠 헌법학 박사', 'Doctorates in geophysics (Innsbruck) and constitutional law (Graz)'],
            ['1935', '밥스 운동으로 20년 강제노동형', 'Sentenced to twenty years’ hard labour as a Vaps leader'],
            ['1941', '헬싱키에서 에스토니아 해방위원회 결성', 'Founded the Estonian Liberation Committee in Helsinki'],
            ['1941–1944', '에스토니아 자치행정 수장', 'Head of the Estonian Self-Administration'],
            ['1944', '오스트리아로 망명', 'Fled to Austria'],
        ],
    }),
    person({
        id: 'zanis-lipke',
        given: ['자니스', 'Žanis'], family: ['립케', 'Lipke'], nativeName: 'Žanis Lipke', years: '1900–1987',
        citizenship: 'latvia', origin: 'latvia',
        epithet: ['루프트바페 하청 일을 이용해 리가 게토와 수용소의 유대인 수십 명을 빼내 숨긴 항만 노동자',
            'Riga docker who used his contract work for the Luftwaffe to smuggle dozens of Jews out of the ghetto and camps and hide them'],
        bio: ['옐가바에서 태어나 1919~1920년 라트비아 독립전쟁 때 라트비아군 포병으로 복무했고, 그 뒤 리가 항구에서 하역 노동자로 일했다. 거리에서 유대인 박해를 목격하고 구조를 결심해 루프트바페의 하청업자가 되었고, 1941년 11월 말부터 리가 게토와 주변 수용소의 유대인 노동자를 빼냈다. 아내 요한나와 친구들의 도움으로 이들을 창고와 집 마당에 판 은신처 등에 숨겨 1944년 10월 붉은군대가 올 때까지 지켰다. 살린 사람은 문헌에 따라 40명에서 약 55명이다. 전후 국가보안위원회는 그를 여러 차례 심문했다. 1966년 야드 바셈이 부부를 「열방의 의인」으로 인정했고, 1987년 그가 숨지자 리가의 유대인들이 장례를 치렀다.',
            'Born in Jelgava, he served in the Latvian Army’s artillery during the War of Independence in 1919–1920 and then worked as a docker in the port of Riga. Having witnessed the persecution of Jews in the streets, he resolved to save them, became a contractor for the Luftwaffe and from late November 1941 smuggled Jewish workers out of the Riga ghetto and nearby camps. With his wife Johanna and friends he hid them in warehouses and a bunker dug in his yard until the Red Army arrived in October 1944. The number saved is given as forty to about 55. After the war the KGB questioned him repeatedly. In 1966 Yad Vashem recognised him and his wife as Righteous Among the Nations, and when he died in 1987 the Jews of Riga arranged his funeral.'],
        fate: ['natural', '리가에서 사망', 'Died in Riga'],
        aliases: { ko: ['야니스 립케'], en: ['Žanis Lipke', 'Jānis Lipke', 'Zanis Lipke'] },
        sources: [S.lipke, S.lvLipke],
        facts: {
            years: { claim: '1900–1987', locator: 'lead', excerpt: '1 February 1900, Mitau – 14 May 1987, Riga' },
            citizenship: { claim: 'Latvian rescuer', locator: 'lead', excerpt: 'was a Latvian rescuer of Jews in Riga in World War II from the Holocaust in Latvia' },
            nationalOrigin: { claim: 'Latvian, born in Jelgava', source: S.lvLipke, locator: 'ievads', excerpt: 'dzimis 1900. gada 1. februārī Jelgavā' },
            bio: [
                { claim: 'artillery 1919–1920, then docker', source: S.lvLipke, locator: 'Dzīvesgājums', excerpt: 'Latvijas brīvības cīņu laikā no 1919. līdz 1920. gadam dienēja Latvijas armijas Daugavpils artilērijas pulkā, pēc kara beigām strādāja Rīgas ostā par krāvēju' },
                { claim: 'witnessed persecution, docker', locator: 'lead', excerpt: 'Lipke, a dock worker in the port of Riga, was determined to help save Latvian Jews from capture by the Nazis after witnessing actions against them in the streets.' },
                { claim: 'Luftwaffe contractor, smuggled workers', locator: 'lead', excerpt: 'He retrained in order to become a contractor for the Luftwaffe, and then used his position to smuggle Jewish workers out of the Riga Ghetto and camps in and around Riga' },
                { claim: 'from late November 1941', source: S.lvLipke, locator: 'Dzīvesgājums', excerpt: '1941. gada novembra beigās un decembrī viņš sāka organizēt Rīgas geto ieslodzīto ebreju bēgšanu.' },
                { claim: 'hid them with Johanna until October 1944', locator: 'lead', excerpt: 'whom he concealed with the aid of his wife Johanna until the arrival of the Red Army in October 1944' },
                { claim: 'bunker in his yard', source: S.lvLipke, locator: 'Dzīvesgājums', excerpt: 'Lipke izraka bunkuru savas mājas pagalmā Balasta dambī.' },
                { claim: 'forty saved (English Wikipedia)', locator: 'lead', excerpt: 'The Lipkes and their various helpers saved forty people in this way' },
                { claim: 'about 55 saved (Latvian Wikipedia)', source: S.lvLipke, locator: 'Dzīvesgājums', excerpt: 'Lipke kopā ar sievu Johannu, draugiem un paziņām nosargāja apmēram 55 ebreju dzīvības.' },
                { claim: 'questioned by the KGB', source: S.lvLipke, locator: 'Dzīvesgājums', excerpt: 'Lipki vairākkārt pratināja VDK' },
                { claim: 'Righteous Among the Nations 1966', locator: 'Honors', excerpt: 'Yad Vashem honored Lipke and his wife as Righteous Among the Nations on 28 June 1966.' },
                { claim: 'funeral by the Jews of Riga', locator: 'lead', excerpt: 'When Lipke died in 1987, the Jews of Riga arranged his funeral.' },
            ],
        },
        activities: [
            { functionId: 'organizing', affiliationId: null, startYear: 1941, endYear: 1944, primary: true, claim: '리가의 유대인 구조', locator: 'lead', excerpt: 'was a Latvian rescuer of Jews in Riga in World War II from the Holocaust in Latvia' },
            { functionId: 'military', affiliationId: 'state-latvia', startYear: 1919, endYear: 1920, claim: '라트비아 독립전쟁 때 포병 복무', source: S.lvLipke, locator: 'Dzīvesgājums', excerpt: 'Latvijas brīvības cīņu laikā no 1919. līdz 1920. gadam dienēja Latvijas armijas Daugavpils artilērijas pulkā' },
        ],
        career: [
            ['1919–1920', '라트비아 독립전쟁 포병 복무', 'Artillery service in the War of Independence'],
            ['1941–1944', '리가 게토·수용소 유대인 구출과 은닉', 'Smuggled Jews out of the Riga ghetto and camps and hid them'],
            ['1966', '「열방의 의인」 인정', 'Recognised as Righteous Among the Nations'],
        ],
    }),
    person({
        id: 'kazys-skirpa',
        given: ['카지스', 'Kazys'], family: ['시키르파', 'Škirpa'], nativeName: 'Kazys Škirpa', years: '1895–1979',
        citizenship: 'lithuania', origin: 'lithuania',
        epithet: ['1941년 6월 봉기를 준비한 리투아니아 행동주의 전선의 창설자이자 베를린 주재 공사',
            'Lithuanian officer and envoy in Berlin who founded the Lithuanian Activist Front behind the June Uprising of 1941'],
        bio: ['러시아 제국군 장교로 제1차 세계대전에 나갔고, 1918년 리투아니아 독립 뒤 맨 먼저 리투아니아군에 입대했으며 1919년 1월 1일 빌뉴스 게디미나스 탑에 리투아니아 국기를 올렸다. 1925년 참모총장이 되었으나 1926년 쿠데타에 맞서다 물러났다. 1927~1930년과 1938~1941년 독일 주재 공사를 지냈다. 1940년 소련 점령 뒤 베를린에서 나치와 손잡고 독립을 되찾으려는 리투아니아 행동주의 전선을 세웠고, 1941년 임시정부 총리로 지명되었으나 독일은 그를 가택연금했다. 1944년 리투아니아 정부 수립을 요구하는 각서를 보냈다가 체포되었다. 전후 미국으로 건너가 의회도서관에서 일했다. 반유대적 글 때문에 그를 기리는 이름 짓기는 논란이 되었다.',
            'Mobilised into the Imperial Russian Army in the First World War, he was the first to enlist in the Lithuanian armed forces after independence in 1918, and on 1 January 1919 his men raised the Lithuanian flag over Gediminas’ Tower in Vilnius. He became Chief of the General Staff in 1925 but had to resign after opposing the 1926 coup. He was envoy to Germany in 1927–1930 and 1938–1941. After the Soviet occupation of 1940 he founded in Berlin the Lithuanian Activist Front, which sought to restore independence by working with the Nazis; named prime minister of the provisional government in 1941, he was held under house arrest by the Germans. In 1944 he was arrested for a memorandum demanding a Lithuanian government. After the war he settled in the United States, working at the Library of Congress. His antisemitic writings have made dedications in his honour controversial.'],
        fate: ['natural', '망명 중 사망', 'Died in exile'],
        aliases: { ko: [], en: ['Kazys Škirpa', 'Kazys Skirpa'] },
        sources: [S.skirpa],
        facts: {
            years: { claim: '1895–1979', locator: 'lead', excerpt: '18 February 1895 – 18 August 1979' },
            citizenship: { claim: 'Lithuanian officer and diplomat', locator: 'lead', excerpt: 'was a Lithuanian military officer and diplomat' },
            nationalOrigin: { claim: 'Lithuanian', locator: 'lead', excerpt: 'was a Lithuanian military officer and diplomat' },
            bio: [
                { claim: 'Imperial Russian Army', locator: 'Army career', excerpt: 'In World War I, he was mobilised into the Imperial Russian Army and graduated from the Peterhof Military School.' },
                { claim: 'first to enlist', locator: 'Army career', excerpt: 'he returned and was the first to enlist in the Lithuanian armed forces' },
                { claim: 'flag over Gediminas’ Tower, 1 January 1919', locator: 'Army career', excerpt: "the men under his command raised the Lithuanian flag above Gediminas' Tower on 1 January 1919" },
                { claim: 'Chief of the General Staff, resigned after the 1926 coup', locator: 'Army career', excerpt: "he worked as Chief of the General Staff, but was forced to resign after the 1926 Lithuanian coup d'état" },
                { claim: 'envoy to Germany', locator: 'Political career', excerpt: 'Later, he served as a Lithuanian representative to Germany (1927–1930), League of Nations (1937), Poland (1938), and again Germany (1938–1941).' },
                { claim: 'founded the LAF', locator: 'Political career', excerpt: 'After the Soviet Union occupied Lithuania in 1940, Škirpa fled to Germany and founded the Lithuanian Activist Front (LAF), a resistance organization whose goal was to liberate Lithuania and re-establish its independence by working with the Nazis.' },
                { claim: 'named prime minister, house arrest', locator: 'Political career', excerpt: 'He was named prime minister in the Provisional Government of Lithuania; however, the Germans placed him under house arrest and did not allow him to leave for Lithuania.' },
                { claim: 'arrested June 1944', locator: 'Political career', excerpt: 'In June 1944, he was arrested for sending a memorandum to Nazi officials asking to replace German authorities in Lithuania with a Lithuanian government.' },
                { claim: 'United States, Library of Congress', locator: 'Later life', excerpt: 'In 1949, he emigrated to the United States. He worked at the Library of Congress.' },
                { claim: 'controversy over antisemitic writings', locator: 'Controversy', excerpt: 'These dedications have caused controversy in Lithuania due to his anti-Semitic writings.' },
            ],
        },
        activities: [
            { functionId: 'diplomacy', affiliationId: 'state-lithuania', startYear: 1927, endYear: 1941, primary: true, claim: '독일 주재 리투아니아 공사', locator: 'Political career', excerpt: 'Later, he served as a Lithuanian representative to Germany (1927–1930), League of Nations (1937), Poland (1938), and again Germany (1938–1941).' },
            { functionId: 'military', affiliationId: 'state-lithuania', startYear: 1918, endYear: 1926, claim: '리투아니아군 장교, 참모총장', locator: 'Army career', excerpt: "he worked as Chief of the General Staff, but was forced to resign after the 1926 Lithuanian coup d'état" },
            { functionId: 'organizing', affiliationId: null, startYear: 1940, endYear: 1941, claim: '리투아니아 행동주의 전선 창설', locator: 'lead', excerpt: 'He founded the Lithuanian Activist Front (LAF), which attempted to establish Lithuanian independence in June 1941.' },
        ],
        career: [
            ['1919', '빌뉴스 게디미나스 탑에 국기 게양', 'Raised the flag over Gediminas’ Tower'],
            ['1925–1926', '리투아니아군 참모총장', 'Chief of the Lithuanian General Staff'],
            ['1938–1941', '독일 주재 공사', 'Envoy to Germany'],
            ['1940–1941', '리투아니아 행동주의 전선 창설, 임시정부 총리 지명', 'Founded the Activist Front; named provisional prime minister'],
            ['1949', '미국 이주', 'Emigrated to the United States'],
        ],
    }),
    person({
        id: 'juri-uluots',
        given: ['위리', 'Jüri'], family: ['울루오츠', 'Uluots'], nativeName: 'Jüri Uluots', years: '1890–1945',
        citizenship: 'estonia', origin: 'estonia',
        epithet: ['소련 점령 뒤 대통령 직무를 맡은 에스토니아의 마지막 헌법상 총리, 1944년 티에프 정부를 세운 법학자',
            'Law professor and Estonia’s last constitutional prime minister who, acting as president, formed the Tief government in 1944'],
        bio: ['에스토니아현 키르블라에서 태어나 상트페테르부르크 대학에서 법학을 공부했고, 1944년까지 타르투 대학에서 로마법과 에스토니아법을 가르쳤다. 『포스티메스』 편집장과 하원의장을 거쳐 1939년부터 1940년 6월 소련군이 들어올 때까지 총리였고, 콘스탄틴 페츠 대통령이 소련에 체포되자 헌법에 따라 대통령 직무를 맡은 총리가 되었다. 1941년 7월 29일 독일군에 독립 정부 수립을 청했다가 거절당했고, 자치행정 수장 제안은 거부했다. 1944년 2월 7일 라디오로 징집에 응하라고 호소했고 3만 8,000명이 등록했다. 6월 오토 티에프를 부총리로 임명했고, 9월 독일군이 물러나자 티에프 정부를 세웠다. 그 뒤 스웨덴으로 건너갔고 1945년 1월 위암으로 숨졌다.',
            'Born in Kirbla Parish in the Governorate of Estonia, he studied law at St Petersburg University and taught Roman and Estonian law at the University of Tartu until 1944. Editor-in-chief of Postimees and speaker of the lower chamber, he was prime minister from 1939 until Soviet troops entered Estonia in June 1940; after President Konstantin Päts was arrested by the Soviets he became, under the constitution, prime minister in the duties of the president. On 29 July 1941 he asked the Germans to let him form an independent government and was refused, and he declined to head the Self-Administration. On 7 February 1944 he appealed by radio for men to answer the call-up, and 38,000 registered. In June he appointed Otto Tief deputy prime minister, and in September, as the Germans withdrew, formed the Tief government. He then reached Sweden, where he died of gastric cancer in January 1945.'],
        fate: ['natural', '망명지 스웨덴에서 병사', 'Died of cancer in exile in Sweden'],
        aliases: { ko: [], en: ['Jüri Uluots', 'Juri Uluots'] },
        sources: [S.uluots, S.eeOcc],
        facts: {
            years: { claim: '1890–1945', locator: 'lead', excerpt: '13 January 1890 – 9 January 1945' },
            citizenship: { claim: 'Estonian prime minister', locator: 'lead', excerpt: 'was an Estonian prime minister, journalist, prominent attorney' },
            nationalOrigin: { claim: 'born in the Governorate of Estonia', locator: 'Early life', excerpt: 'Uluots was born in Kirbla Parish (now Lääneranna Parish), in the Wiek County of the Governorate of Estonia in 1890' },
            bio: [
                { claim: 'law at St Petersburg', locator: 'Early life', excerpt: 'studied law at St. Petersburg University in 1910–1918' },
                { claim: 'taught at Tartu until 1944', locator: 'Early life', excerpt: 'He subsequently taught Roman and Estonian law at the University of Tartu until 1944.' },
                { claim: 'editor of Postimees', locator: 'Early life', excerpt: 'editor-in-chief of Postimees 1937–1938' },
                { claim: 'speaker of the lower chamber', locator: 'Political career', excerpt: 'He was speaker of the Riigivolikogu (lower chamber) from 4 April 1938 to 12 October 1939.' },
                { claim: 'prime minister 1939–1940', locator: 'Political career', excerpt: 'Uluots then served as prime minister from 1939 until June 1940 when Soviet troops entered Estonia' },
                { claim: 'prime minister in the duties of the president', locator: 'Political career', excerpt: 'Professor Uluots became prime minister in the duties of the president as dictated by the Estonian constitution' },
                { claim: 'met the Germans 29 July 1941', locator: 'Political career', excerpt: 'On July 29, 1941, Uluots met with the Nazi military government of Tartu' },
                { claim: 'refused, and declined the Self-Administration', locator: 'Political career', excerpt: 'his request was turned down, and the Nazis offered him to head the Estonian Self-Administration, but he refused' },
                { claim: 'radio address of 7 February 1944', source: S.eeOcc, locator: 'Estonians in German military units', excerpt: 'delivered a radio address on February 7 that implored all able-bodied men born from 1904 through 1923 to report for military service in the SS' },
                { claim: '38,000 draftees', locator: 'Political career', excerpt: '38,000 draftees appeared at German registration centers' },
                { claim: 'Tief deputy prime minister, 21 June 1944', locator: 'Political career', excerpt: 'On 21 June 1944, Jüri Uluots appointed Otto Tief as deputy prime minister.' },
                { claim: 'Tief government, September 1944', locator: 'Political career', excerpt: 'As the Germans retreated in September 1944, Uluots appointed a new government, headed by Otto Tief.' },
                { claim: 'died of gastric cancer in Sweden', locator: 'Political career', excerpt: 'Uluots died of gastric cancer shortly after arriving in Sweden in 1945' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-estonia', startYear: 1939, endYear: 1945, primary: true, claim: '에스토니아 총리, 대통령 직무대행', locator: 'Political career', excerpt: 'Uluots then served as prime minister from 1939 until June 1940 when Soviet troops entered Estonia' },
            { functionId: 'legislature', affiliationId: 'state-estonia', startYear: 1920, endYear: 1939, claim: '의원, 하원의장', locator: 'Political career', excerpt: 'Uluots was elected to the Riigikogu, the Estonian parliament, for 1920–1926, and from 1929 through 1932.' },
            { functionId: 'scholarship', affiliationId: null, startYear: null, endYear: 1944, claim: '타르투 대학 법학 교수·학장', locator: 'lead', excerpt: 'distinguished Professor and Dean of the Faculty of Law at the University of Tartu' },
        ],
        career: [
            ['1938–1939', '하원의장', 'Speaker of the lower chamber'],
            ['1939–1940', '에스토니아 총리', 'Prime minister of Estonia'],
            ['1940–1945', '대통령 직무를 맡은 총리', 'Prime minister in the duties of the president'],
            ['1944', '징집 호소, 티에프 정부 수립', 'Backed the call-up; formed the Tief government'],
        ],
    }),
].map(unaffiliated);
