// Person cards for event-1944.js (the Soviet reoccupation of the Baltic states,
// 1944–1953), see lib.js person(). Partisan and church activities have no
// catalog affiliation (LLKS, the Catholic Church), so they stay unresolved.
const { W, person } = require('./lib');

const E = t => W(encodeURI(t));
const ET = t => 'https://et.wikipedia.org/wiki/' + encodeURI(t);
const LT = t => 'https://lt.wikipedia.org/wiki/' + encodeURI(t);
const S = {
    karotamm: E('Nikolai_Karotamm'),
    etKarotamm: ET('Nikolai_Karotamm'),
    martsi: ET('Märtsipleenum'),
    zemaitis: E('Jonas_Žemaitis'),
    ltZemaitis: LT('Jonas_Žemaitis-Vytautas'),
    ramanauskas: E('Adolfas_Ramanauskas'),
    luksa: E('Juozas_Lukša'),
    borisevicius: E('Vincentas_Borisevičius'),
};

const unaffiliated = card => ({
    ...card,
    activities: card.activities.map(a => (a.affiliationId ? a : { ...a, affiliationStatus: 'unresolved', relation: 'unresolved' })),
});

module.exports = [
    person({
        id: 'nikolai-karotamm', groupId: 'stalin-era',
        given: ['니콜라이', 'Nikolai'], family: ['카로탐', 'Karotamm'], nativeName: 'Nikolai Karotamm', years: '1901–1969',
        citizenship: 'soviet', origin: 'estonia',
        epithet: ['1944~1950년 에스토니아 공산당 제1서기, 1950년 「부르주아 민족주의자 비호」로 해임된 당 지도자',
            'First Secretary of the Estonian Communist Party in 1944–1950, removed in 1950 for allegedly shielding “bourgeois nationalists”'],
        bio: ['1901년 패르누 지방에서 태어나 1925년 네덜란드로 건너가 공산당에 들어갔고, 1926년 소련에 정착해 서방소수민족공산대학에서 공부했다. 1938년 대숙청 때 체포되었다가 기소 없이 풀려났다. 독일 점령기에는 사실상 에스토니아 공산당을 이끌며 에스토니아 파르티잔 운동 참모부장을 지냈고, 1944년 9월 28일 제1서기로 선출되었다. 섬멸대대 중앙참모부를 이끌었고, 1949년 3월 추방에 앞서 각 군의 전권위원들에게 지시를 내렸다. 1950년 제8차 전원회의 뒤 해임되어 요한네스 캐빈으로 교체되었다. 이후 모스크바에서 경제학자로 일하며 1964년 박사 학위를 받았고, 캐빈과의 불화로 에스토니아에 돌아오지 못한 채 1969년 모스크바에서 숨졌다.',
            'Born in Pärnu County in 1901, he moved to the Netherlands in 1925 and joined its Communist Party, then settled in the Soviet Union in 1926 and studied at the Communist University of the National Minorities of the West. Arrested in the Great Purge in 1938, he was soon released without charges. During the German occupation he was the de facto leader of the Communist Party of Estonia and head of the Estonian partisan movement staff, and on 28 September 1944 he was elected First Secretary. He headed the central staff of the destruction battalions, and in March 1949 he briefed the county plenipotentiaries before the deportation. Removed after the Eighth Plenum of 1950 and replaced by Johannes Käbin, he worked in Moscow as an economist, took his doctorate in 1964, and, because of his disagreements with Käbin, never returned to Estonia; he died in Moscow in 1969.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: ['카로탐', '니콜라이 게오르기예비치 카로탐'], en: ['Karotamm', 'Nikolai Georgievich Karotamm'] },
        sources: [S.karotamm, S.etKarotamm, S.martsi],
        facts: {
            years: { claim: '1901–1969', locator: 'lead', excerpt: 'Nikolai Georgievich Karotamm (October 23, 1901 – September 21, 1969) was an Estonian communist politician.' },
            citizenship: { claim: 'Member of the All-Union Communist Party (b) from 1928', locator: 'Biography', excerpt: 'In 1928, Karotamm became a member of the All-Union Communist (b) Party' },
            nationalOrigin: { claim: 'Estonian communist politician', locator: 'lead', excerpt: 'was an Estonian communist politician' },
            bio: [
                { claim: 'born in Pärnu County in 1901', source: S.etKarotamm, locator: 'Elulugu', excerpt: 'Karotamm sündis 1901. aastal Pärnumaal' },
                { claim: 'Communist Party of the Netherlands', locator: 'Biography', excerpt: 'In 1925, he moved to the Netherlands and joined the Communist Party of the Netherlands.' },
                { claim: 'Communist University of the National Minorities of the West', locator: 'Biography', excerpt: 'In 1926, he settled in the Soviet Union and studied at the Communist University of the National Minorities of the West.' },
                { claim: 'arrested in 1938 and released', locator: 'Biography', excerpt: 'He was arrested during the Great Purge in 1938, but was soon released without charges.' },
                { claim: 'acting leader of the party during the war', locator: 'Biography', excerpt: 'Karotamm became the acting leader of the Communist Party of Estonia after he fled to Leningrad.' },
                { claim: 'head of the Estonian partisan movement staff 1942–1944', source: S.etKarotamm, locator: 'Tegevus Teise maailmasõja ajal', excerpt: 'Eesti NSV Partisaniliikumise Staabi ülem aastail 1942–1944' },
                { claim: 'elected First Secretary on 28 September 1944', source: S.etKarotamm, locator: 'Tegevus pärast 1944 okupeeritud Eestis', excerpt: 'Karotamm valiti 28. september 1944 pärast Tallinna vallutamist toimunud EKP KK pleenumil EK(b)P KK I sekretäriks' },
                { claim: 'head of the central staff of the destruction battalions', source: S.etKarotamm, locator: 'Tegevus pärast 1944 okupeeritud Eestis', excerpt: 'Hävituspataljonide ENSV SARKi Hävituspataljonide Keskstaabi ja hiljem ENSV Rahvakaitsepataljonide Keskstaabi ülem' },
                { claim: 'briefed the county plenipotentiaries for the March 1949 deportation', source: S.etKarotamm, locator: 'Kollektiviseerimine ja märtsiküüditamime', excerpt: '1949. aasta märtsis kutsuti EK(b)P Keskkomiteesse instrueerimisele, mille viis läbi EK(b)P Keskkomitee esimene sekretär Nikolai Karotamm' },
                { claim: 'removed at the Eighth Plenum and replaced by Käbin', source: S.martsi, locator: 'lead', excerpt: 'EK(b)P KK I sekretär Nikolai Karotamm sunniti ametist lahkuma ja tema asemele asus Johannes Käbin' },
                { claim: 'worked in Moscow at the Academy of Social Sciences and the Institute of Economics', locator: 'Biography', excerpt: 'He then settled in Moscow and studied in the Academy of Social Sciences under the Central Committee of the CPSU and later worked at the Institute of Economics of the Soviet Academy of Sciences.' },
                { claim: 'doctorate in 1964', locator: 'Biography', excerpt: 'He received his doctorate of economics in 1964.' },
                { claim: 'never returned to Estonia because of Käbin', locator: 'Biography', excerpt: 'Due to his disagreements with his successor Johannes Käbin, Karotamm never returned to Estonia.' },
                { claim: 'died in Moscow', locator: 'Biography', excerpt: 'He died in Moscow and was buried at the Metsakalmistu cemetery.' },
            ],
        },
        activities: [
            { functionId: 'political-leadership', affiliationId: 'soviet-party', startYear: 1944, endYear: 1950, primary: true, claim: 'First Secretary of the Communist Party of Estonia, 1944–1950', source: S.etKarotamm, locator: 'lead', excerpt: '1944–1950 EKP Keskkomitee I sekretär' },
            { functionId: 'scholarship', affiliationId: 'state-soviet', startYear: 1951, endYear: 1969, claim: 'Economist at the Institute of Economics of the Soviet Academy of Sciences', locator: 'Biography', excerpt: 'later worked at the Institute of Economics of the Soviet Academy of Sciences' },
        ],
        career: [
            ['1925', '네덜란드 공산당 입당', 'Joined the Communist Party of the Netherlands'],
            ['1928', '전연방공산당(볼셰비키) 입당', 'Joined the All-Union Communist Party (Bolsheviks)'],
            ['1941', '에스토니아 공산당 제2서기', 'Second Secretary of the Communist Party of Estonia'],
            ['1944–1950', '에스토니아 공산당 제1서기', 'First Secretary of the Communist Party of Estonia'],
            ['1950', '제8차 전원회의 뒤 해임', 'Removed after the Eighth Plenum'],
            ['1964', '경제학 박사', 'Doctorate in economics'],
        ],
    }),
    unaffiliated(person({
        id: 'jonas-zemaitis', groupId: 'world-cold-war',
        given: ['요나스', 'Jonas'], family: ['제마이티스', 'Žemaitis'], nativeName: 'Jonas Žemaitis', years: '1909–1954',
        citizenship: 'lithuania', origin: null,
        epithet: ['1949년 리투아니아 자유 전사 연합을 세워 의장으로서 파르티잔 저항을 이끈 장교',
            'Officer who founded the Union of Lithuanian Freedom Fighters in 1949 and led the partisan resistance as its chairman'],
        bio: ['팔랑가에서 태어나 1929년 카우나스 군사학교를 마친 포병 장교로, 1936~1938년 프랑스 퐁텐블로의 포병학교에서 공부했다. 1941년 6월 누이의 가족이 시베리아로 추방되었고, 독일 점령기에는 나치에 복무하지 않으려 전역했다. 1944년 리투아니아 지역방위군에 들어갔고, 붉은군대가 돌아오자 리투아니아 자유군과 파르티잔에 합류해 지휘관으로 올라섰다. 1949년 2월 리투아니아 자유 전사 연합을 세워 의장이 되었고 부대를 통합하고 투쟁의 법적 틀을 마련했다. 1951년 12월 뇌출혈로 마비되었고 1953년 5월 30일 체포되어 모스크바에서 베리야의 심문을 받은 뒤 1954년 부티르카 감옥에서 처형되었다. 2009년 리투아니아 제4대 대통령으로 공식 인정되었다.',
            'Born in Palanga, he graduated from the War School of Kaunas in 1929 as an artillery officer and studied at the School of Applied Artillery in Fontainebleau, France, in 1936–1938. In the deportations of June 1941 his sister’s whole family was sent to Siberia; under the German occupation he retired rather than serve the Nazis. In 1944 he joined the Lithuanian Territorial Defense Force, and when the Red Army returned he joined the Lithuanian Liberty Army and the partisans, rising to the leadership. In February 1949 he founded the Union of Lithuanian Freedom Fighters and became its chairman, working to unify the partisan units and give their struggle a legal framework. Paralysed by a cerebral haemorrhage in December 1951, he was arrested on 30 May 1953, interrogated in Moscow by Beria and executed in Butyrka prison in 1954. In 2009 he was officially named the fourth President of Lithuania.'],
        fate: ['executed', '처형', 'Executed'],
        aliases: { ko: ['제마이티스', '요나스 제마이티스-비타우타스'], en: ['Žemaitis', 'Jonas Žemaitis-Vytautas', 'Jonas Zemaitis'] },
        linkExpressions: [['ko', '제마이티스-비타우타스'], ['en', 'Žemaitis-Vytautas']],
        sources: [S.zemaitis, S.ltZemaitis],
        facts: {
            years: { claim: '1909–1954', locator: 'lead', excerpt: 'Jonas Žemaitis, also known under his nom de guerre Vytautas (15 March 1909 – 26 November 1954), was a Lithuanian general' },
            citizenship: { claim: 'Lithuanian general and partisan', locator: 'lead', excerpt: 'was a Lithuanian general and a Lithuanian partisan who led the resistance against the Soviet occupation' },
            bio: [
                { claim: 'born in Palanga', source: S.ltZemaitis, locator: 'Biografija', excerpt: 'Gimė Palangoje, Jono ir Petronėlės Žemaičių šeimoje.' },
                { claim: 'War School of Kaunas, 1926–1929', locator: 'Biography', excerpt: 'In September 1926, he started studying at the War School of Kaunas. In 1929, he finished this school and became a junior lieutenant.' },
                { claim: 'Fontainebleau 1936–1938', locator: 'Biography', excerpt: 'In 1936–1938, Žemaitis studied at the School of Applied Artillery in Fontainebleau, France.' },
                { claim: 'sister’s family deported in June 1941', locator: 'Biography', excerpt: "during the deportations of June 1941, the entire family of Žemaitis' sister, including their three children, was sent to Siberia" },
                { claim: 'retired rather than serve the Nazis', locator: 'Biography', excerpt: 'He did not want to serve the Nazis, and therefore he retired and settled down in Kaunas' },
                { claim: 'Lithuanian Territorial Defense Force 1944', locator: 'Biography', excerpt: 'In 1944, he joined the Lithuanian Territorial Defense Force, organized by Povilas Plechavičius.' },
                { claim: 'joined the Lithuanian Liberty Army and the partisans', locator: 'Biography', excerpt: 'When the Red Army returned to Lithuania, Žemaitis joined the Lithuanian Liberty Army and the Lithuanian partisans, steadily rising to a position of leadership.' },
                { claim: 'founded the Union in February 1949 and gave it a legal framework', locator: 'Biography', excerpt: 'In February 1949, he established the Union of Lithuanian Freedom Fighters and became its chairman; he worked to unify the partisan units, establish legal framework for partisan activities' },
                { claim: 'paralysed in December 1951', locator: 'Biography', excerpt: 'In December 1951, he suffered a cerebral hemorrhage and became paralyzed.' },
                { claim: 'arrested on 30 May 1953', locator: 'Biography', excerpt: 'arrested him on 30 May 1953' },
                { claim: 'interrogated by Beria, executed in Butyrka 1954', locator: 'Biography', excerpt: 'he was interrogated by the minister of Internal Affairs of the Soviet Union Lavrentiy Beria and was executed in the Butyrka prison in 1954.' },
                { claim: 'named fourth President of Lithuania in 2009', locator: 'Legacy', excerpt: 'was officially named as the fourth President of Lithuania in March 2009.' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: null, startYear: 1944, endYear: 1953, primary: true, claim: 'Chairman of the Union of Lithuanian Freedom Fighters (LLKS), no catalog affiliation', locator: 'Biography', excerpt: 'In February 1949, he established the Union of Lithuanian Freedom Fighters and became its chairman' },
            { functionId: 'military', affiliationId: 'state-lithuania', startYear: 1929, endYear: 1940, claim: 'Artillery officer of the Lithuanian army', locator: 'Biography', excerpt: 'Žemaitis was promoted to captain and commanded artillery units in the Lithuanian military' },
        ],
        career: [
            ['1929', '카우나스 군사학교 졸업, 포병 장교', 'Graduated from the War School of Kaunas; artillery officer'],
            ['1936–1938', '프랑스 퐁텐블로 포병학교', 'School of Applied Artillery, Fontainebleau'],
            ['1944', '리투아니아 지역방위군, 이어 파르티잔', 'Lithuanian Territorial Defense Force, then the partisans'],
            ['1949', '리투아니아 자유 전사 연합 의장', 'Chairman of the Union of Lithuanian Freedom Fighters'],
            ['1953', '체포', 'Arrested'],
            ['1954', '모스크바 부티르카 감옥에서 처형', 'Executed in Butyrka prison, Moscow'],
        ],
    })),
    unaffiliated(person({
        id: 'adolfas-ramanauskas', groupId: 'world-cold-war',
        given: ['아돌파스', 'Adolfas'], family: ['라마나우스카스', 'Ramanauskas'], nativeName: 'Adolfas Ramanauskas', years: '1918–1957',
        citizenship: 'lithuania', origin: 'lithuania',
        epithet: ['가명 「바나가스」, 1952년부터 리투아니아 자유 전사 연합을 이끈 마지막 파르티잔 지휘관',
            'Partisan commander “Vanagas” who led the Union of Lithuanian Freedom Fighters from 1952, the last commander to be captured'],
        bio: ['미국 뉴브리튼의 리투아니아 이민 가정에서 태어나 세 살 때 리투아니아로 왔다. 1940년 카우나스 군사학교를 마치고 교사로 일하다, NKVD가 학생들을 감시하라고 압박하자 1945년 초 「바나가스」(매)라는 가명으로 파르티잔에 들어갔다. 다이나바 군관구와 남부 지역의 사령관을 지내며 지하 신문을 펴냈고, 1949년 리투아니아 자유 전사 연합 의장의 제1대리가 되었다. 1952년 요나스 제마이티스를 이어 연합을 이끌며 무장 투쟁을 멈추고 수동적 저항으로 돌아서라고 명령했다. 1956년 10월 옛 동창의 배신으로 체포되어 고문당한 뒤 1957년 11월 처형되었다. 1941년 6월 봉기 때 그가 지휘한 부대가 유대인 학살에 관여했다는 주장이 있으나 리투아니아 정부는 부인한다.',
            'Born to a Lithuanian immigrant family in New Britain, Connecticut, he came to Lithuania at the age of three. He graduated from the War School of Kaunas in 1940 and worked as a teacher, and after the NKVD pressured him to spy on his students he joined the partisans in early 1945 under the nom de guerre Vanagas (“Hawk”). He commanded the Dainava military district and the Southern Lithuania Region, published underground newspapers, and in 1949 became first deputy chairman of the Union of Lithuanian Freedom Fighters. Succeeding Jonas Žemaitis as its leader in 1952, he ordered an end to armed struggle in favour of passive resistance. Betrayed by a former classmate, he was arrested in October 1956, tortured and executed in November 1957. The Simon Wiesenthal Center has alleged that a unit he commanded in the June 1941 uprising took part in killing Jews; the Lithuanian government denies this.'],
        fate: ['executed', '처형', 'Executed'],
        aliases: { ko: ['라마나우스카스', '아돌파스 라마나우스카스-바나가스'], en: ['Ramanauskas', 'Adolfas Ramanauskas-Vanagas'] },
        linkExpressions: [['ko', '바나가스'], ['en', 'Vanagas'], ['ko', '라마나우스카스-바나가스'], ['en', 'Ramanauskas-Vanagas']],
        sources: [S.ramanauskas],
        facts: {
            years: { claim: '1918–1957', locator: 'lead', excerpt: 'Adolfas Ramanauskas (6 March 1918 – 29 November 1957)' },
            citizenship: { claim: 'Leader of the Lithuanian partisans', locator: 'lead', excerpt: 'was one of the leaders of the Lithuanian partisans and the anti-Soviet resistance' },
            nationalOrigin: { claim: 'family of Lithuanian immigrants', locator: 'lead', excerpt: 'Ramanauskas was born in the United States to a family of Lithuanian immigrants who returned to Lithuania when he was 3 years old.' },
            bio: [
                { claim: 'born in New Britain, Connecticut', locator: 'Early life', excerpt: 'Ramanauskas was born to a Lithuanian immigrant family in New Britain, Connecticut, United States.' },
                { claim: 'War School class of 1940', locator: 'World War II', excerpt: 'His class of 1940 was the last graduating class before the Soviet Union occupied Lithuania in June 1940.' },
                { claim: 'teacher; joined after NKVD pressure', locator: 'lead', excerpt: 'he joined the anti-Soviet resistance after the NKVD pressured him to spy on his students' },
                { claim: 'joined the partisans in early 1945 as Vanagas', locator: 'Guerrilla warfare (1945–1952)', excerpt: 'In early 1945, Ramanauskas joined the Lithuanian partisans who waged a guerrilla war against the Soviet occupants. He adopted the nom-de-guerre Vanagas' },
                { claim: 'commander of the Dainava district and the Southern Lithuania Region', locator: '1946–1948', excerpt: 'He became commander of the Dainava military district after the death of Dominykas Jėčys-Ąžuolas in September 1947 and of the Southern Lithuania Region in 1948.' },
                { claim: 'published partisan newspapers', locator: '1946–1948', excerpt: 'He also wrote, edited, and published numerous partisan newspapers' },
                { claim: 'first deputy chairman in 1949', locator: '1949–1952', excerpt: 'Ramanauskas was elected to the presidium of the Union and as the first deputy of its chairman Jonas Žemaitis.' },
                { claim: 'leader in 1952; ordered passive resistance', locator: '1949–1952', excerpt: 'Ramanauskas officially ordered cessation of armed struggle in favour of passive resistance.' },
                { claim: 'betrayed and arrested in October 1956', locator: 'Hiding (1953–1956)', excerpt: 'Ramanauskas was betrayed by Antanas Urbonas, a former classmate at Kaunas, and arrested on 11 October 1956.' },
                { claim: 'executed November 1957', locator: 'Capture, torture and death (1956–1957)', excerpt: 'Sentenced to death on 25 September 1957, Vanagas was executed on 29 November 1957.' },
                { claim: 'Wiesenthal Center allegation', locator: 'World War II', excerpt: 'Ramanauskas admitted to commanding a partisan unit during the uprising that witnesses said butchered Jews in the ghetto of Druskininkai' },
                { claim: 'Lithuanian government denial', locator: 'World War II', excerpt: "The Lithuanian government replied that Ramanauskas' unit did not engage in any actions against Jews" },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: null, startYear: 1945, endYear: 1956, primary: true, claim: 'Partisan commander and leader of the Union of Lithuanian Freedom Fighters, no catalog affiliation', locator: '1949–1952', excerpt: 'When Žemaitis resigned due to poor health in 1952, Ramanauskas became the leader of the Union.' },
            { functionId: 'propaganda', affiliationId: null, startYear: 1946, endYear: 1952, claim: 'Editor of partisan newspapers', locator: '1946–1948', excerpt: 'He also wrote, edited, and published numerous partisan newspapers' },
        ],
        career: [
            ['1940', '카우나스 군사학교 졸업', 'Graduated from the War School of Kaunas'],
            ['1945', '파르티잔 합류, 여단장', 'Joined the partisans; brigade commander'],
            ['1947', '다이나바 군관구 사령관', 'Commander of the Dainava military district'],
            ['1949', '리투아니아 자유 전사 연합 의장 제1대리', 'First deputy chairman of the Union of Lithuanian Freedom Fighters'],
            ['1952', '연합 지도자', 'Leader of the Union'],
            ['1956–1957', '체포·처형', 'Arrested and executed'],
        ],
    })),
    unaffiliated(person({
        id: 'juozas-luksa', groupId: 'world-cold-war',
        given: ['유오자스', 'Juozas'], family: ['룩샤', 'Lukša'], nativeName: 'Juozas Lukša', years: '1921–1951',
        citizenship: 'lithuania', origin: null,
        epithet: ['1947년 철의 장막을 넘어 서방에 지원을 구하고 돌아와 MGB에 살해된 리투아니아 파르티잔 지도자',
            'Lithuanian partisan leader who crossed the Iron Curtain in 1947 to seek Western support and was killed by the MGB after returning'],
        bio: ['카우나스 근처 유오드부디스 마을의 농가에서 태어났다. 가톨릭 청년 단체 아테이티스와 극우·반유대·반소 단체 리투아니아 행동주의 전선(LAF)에 들어갔고, 1940~1941년 소련 점령기에 NKVD에 투옥되었다. 1944년부터 카우나스에서 지하 활동을 하다 1946년 무장 저항에 들어가 타우라스 군관구의 비루테 여단을 이끌었다. 1947년 말 철의 장막을 넘어 서방에 파르티잔의 자료를 전했고, 프랑스 정보기관과 CIA의 훈련을 받으며 『자유를 위한 투사들』을 썼다. 1949~1950년 낙하산으로 돌아왔다가 1951년 가을 파바르투피스 근처에서 MGB에 살해되었다. 목격자들은 그가 1941년 카우나스 리에투키스 차고 학살에 가담했다고 증언했으나 리투아니아 정부는 부인한다.',
            'Born to a farming family in the village of Juodbūdis near Kaunas, he joined the Catholic youth organisation Ateitis and the far-right, antisemitic and anti-Soviet Lithuanian Activist Front (LAF) at secondary school, and was imprisoned by the NKVD during the Soviet occupation of 1940–1941. After the Red Army returned in 1944 he worked in the Kaunas underground, joined the armed resistance in 1946 and commanded the Birutė brigade of the Tauras military district. At the end of 1947 he crossed the Iron Curtain with partisan documentation for the West, was trained by French intelligence and the CIA, and wrote Fighters for Freedom. Parachuted back by the CIA in 1949–1950, he was killed by the MGB near Pabartupis in the autumn of 1951. According to several witnesses he took part in the Lietūkis garage massacre in Kaunas in 1941; the Lithuanian government denies this.'],
        fate: ['killed', 'MGB에 피살', 'Killed by the MGB'],
        aliases: { ko: ['룩샤', '유오자스 룩샤-다우만타스'], en: ['Lukša', 'Juozas Lukša-Daumantas', 'Juozas Luksa'] },
        linkExpressions: [['ko', '룩샤-다우만타스'], ['en', 'Lukša-Daumantas'], ['en', 'Juozas Daumantas']],
        sources: [S.luksa],
        facts: {
            years: { claim: '1921–1951', locator: 'lead', excerpt: 'Juozas Lukša (10 August 1921 – 4 September 1951), also known by other pseudonyms such as Daumantas and Skirmantas' },
            citizenship: { claim: 'Leader of the Lithuanian partisan resistance', locator: 'lead', excerpt: 'was a leader of the anti-Soviet Lithuanian partisan armed resistance movement' },
            bio: [
                { claim: 'born in Juodbūdis to farmers', locator: 'Life', excerpt: 'Lukša was born on 10 August 1921 to a family of farmers in the village of Juodbūdis, near Kaunas.' },
                { claim: 'Ateitis and the LAF', locator: 'Life', excerpt: 'where he joined the catholic youth organization Ateitis and the far-right, anti-semitic, and anti-Soviet Lithuanian Activist Front (LAF)' },
                { claim: 'imprisoned by the NKVD 1940–41', locator: 'Life', excerpt: 'Due to being a member of the LAF, Lukša was imprisoned by the NKVD in Kaunas during the 1940–41 Soviet occupation of the Baltic states.' },
                { claim: 'underground in Kaunas, armed resistance from 1946', locator: 'Life', excerpt: 'In 1946, after the arrests of many activists, he left the city and joined the armed resistance.' },
                { claim: 'Birutė brigade of the Tauras district', locator: 'Life', excerpt: 'Within a year, he commanded the Birutė brigade of the Tauras military district.' },
                { claim: 'crossed the Iron Curtain at the end of 1947', locator: 'Life', excerpt: 'At the end of 1947, along with fellow partisans Jurgis Krikščiūnas-Rimvydas and Kazimieras Pyplys-Mažytis, Lukša crossed through the Iron Curtain' },
                { claim: 'trained by French intelligence and the CIA', locator: 'Life', excerpt: 'where he was trained by French intelligence agents and the CIA' },
                { claim: 'wrote Fighters for Freedom', locator: 'Life', excerpt: 'During his stay in the West, Lukša wrote Fighters for Freedom' },
                { claim: 'parachuted back 1949–1950', locator: 'Life', excerpt: 'He was parachuted back into Lithuania by the CIA sometime between 1949 and 1950.' },
                { claim: 'killed by the MGB near Pabartupis', locator: 'Life', excerpt: 'before being killed near Pabartupis by the MGB in the fall of 1951' },
                { claim: 'alleged participation in the Lietūkis garage massacre', locator: 'Alleged participation in the Kaunas pogrom', excerpt: 'Lukša was a participant in the 1941 Lietukis garage massacres in Kaunas' },
                { claim: 'denied by the Lithuanian government', locator: 'Alleged participation in the Kaunas pogrom', excerpt: 'The Lithuanian government denies these claims.' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: null, startYear: 1946, endYear: 1951, primary: true, claim: 'Lithuanian partisan commander, no catalog affiliation', locator: 'Life', excerpt: 'Within a year, he commanded the Birutė brigade of the Tauras military district.' },
            { functionId: 'propaganda', affiliationId: null, startYear: 1948, endYear: 1950, claim: 'Author of Fighters for Freedom', locator: 'Life', excerpt: 'During his stay in the West, Lukša wrote Fighters for Freedom' },
        ],
        career: [
            ['1940–1941', 'NKVD에 투옥', 'Imprisoned by the NKVD'],
            ['1946', '무장 저항 합류, 비루테 여단장', 'Joined the armed resistance; commander of the Birutė brigade'],
            ['1947', '철의 장막을 넘어 서방으로', 'Crossed the Iron Curtain to the West'],
            ['1949–1950', 'CIA 낙하산으로 귀환', 'Parachuted back by the CIA'],
            ['1951', 'MGB에 피살', 'Killed by the MGB'],
        ],
    })),
    unaffiliated(person({
        id: 'vincentas-borisevicius', groupId: 'world-cold-war',
        given: ['빈첸타스', 'Vincentas'], family: ['보리세비추스', 'Borisevičius'], nativeName: 'Vincentas Borisevičius', years: '1887–1946',
        citizenship: 'lithuania', origin: 'lithuania',
        epithet: ['파르티잔 지원 혐의로 1946년 처형된 리투아니아 텔샤이 교구의 가톨릭 주교',
            'Catholic bishop of Telšiai in Lithuania, executed in 1946 on charges that included supporting the partisans'],
        bio: ['부유한 리투아니아 농가에서 태어나 상트페테르부르크, 세이니 신학교, 스위스 프리부르 대학에서 공부했다. 제1차 세계대전 때 러시아 제국군 군종 사제였고, 1927년부터 1940년 소련 점령으로 문을 닫을 때까지 텔샤이 신학교 교장을 지냈다. 1943년 텔샤이 교구장이 되었고, 1944년 서방으로 피하지 않았다. 파르티잔 지원 등의 혐의로 1945년 12월과 1946년 2월 NKVD에 체포되었으며, 협력하면 사면하겠다는 제안을 거절했다. 1946년 8월 28일 반역죄로 사형을 선고받아 11월 18일 처형된 것으로 여겨지며, 투스쿨레나이 영지의 집단 매장지에 묻혔다. 재판에서 유대인 세 사람이 그가 유대인을 숨겨 주었다고 증언했다. 1990년 시복 절차가 시작되었다.',
            'Born to a family of well-off Lithuanian farmers, he studied in Saint Petersburg, at the Sejny Priest Seminary and at the University of Fribourg in Switzerland. In the First World War he was a chaplain in the Russian Imperial Army, and from 1927 he was rector of the Telšiai priest seminary until the Soviet occupation closed it in 1940. He became bishop of Telšiai in 1943 and refused to retreat to the West in 1944. Accused of anti-Soviet activities including support for the partisans, he was arrested by the NKVD in December 1945 and again in February 1946, and refused an offer of a pardon in exchange for cooperation. Sentenced to death for treason on 28 August 1946, he is believed to have been executed on 18 November and was buried in a mass grave at Tuskulėnai Manor in Vilnius. At his trial three Jews testified that he had helped Jews hide. His beatification process began in 1990.'],
        fate: ['executed', '처형', 'Executed'],
        aliases: { ko: ['보리세비추스'], en: ['Borisevičius', 'Vincentas Borisevicius'] },
        sources: [S.borisevicius],
        facts: {
            years: { claim: '1887–1946', locator: 'lead', excerpt: 'Vincentas Borisevičius (23 November 1887 – 18 November 1946) was a Lithuanian Roman Catholic bishop of the Telšiai Diocese.' },
            citizenship: { claim: 'Lithuanian bishop', locator: 'lead', excerpt: 'was a Lithuanian Roman Catholic bishop of the Telšiai Diocese' },
            nationalOrigin: { claim: 'family of Lithuanian farmers', locator: 'lead', excerpt: 'Born to a family of well-off Lithuanian farmers' },
            bio: [
                { claim: 'education', locator: 'lead', excerpt: "Borisevičius was educated at the boys' gymnasium of the Church of St. Catherine in Saint Petersburg, Sejny Priest Seminary, and University of Fribourg in Switzerland." },
                { claim: 'chaplain of the 10th Army', locator: 'lead', excerpt: 'he evacuated to Minsk where he worked as a chaplain of the 10th Army of the Russian Imperial Army' },
                { claim: 'rector of the Telšiai seminary 1927–1940', locator: 'lead', excerpt: 'The seminary was officially opened on 4 October 1927 and Borisevičius was its rector until it was closed in 1940 in the aftermath of the Soviet occupation of Lithuania.' },
                { claim: 'bishop of Telšiai after 1943', locator: 'lead', excerpt: 'After the death of Bishop Staugaitis on 7 July 1943, Borisevičius succeeded him as the new bishop of Telšiai.' },
                { claim: 'refused to retreat to the West', locator: 'Bishop and execution', excerpt: 'Borisevičius refused to follow the example many other Lithuanian members of the clergy and intelligentsia and retreat to the West' },
                { claim: 'arrested December 1945 and February 1946', locator: 'lead', excerpt: 'Accused of various anti-Soviet activities, including supporting Lithuanian partisans, Borisevičius was arrested by the NKVD in December 1945 and again in February 1946.' },
                { claim: 'refused cooperation for a pardon', locator: 'Bishop and execution', excerpt: 'He was offered a deal – cooperate with Soviet authorities in exchange for a pardon, but, after a discussion with Archbishop Mečislovas Reinys, he refused.' },
                { claim: 'sentenced to death 28 August 1946', locator: 'lead', excerpt: 'On 28 August, he was convicted of being a traitor under Article 58 of the Soviet Penal Code and sentenced to death.' },
                { claim: 'believed executed 18 November 1946', locator: 'Bishop and execution', excerpt: 'it is believed that the sentence was carried out on 18 November 1946 with twelve others' },
                { claim: 'buried at Tuskulėnai', locator: 'Bishop and execution', excerpt: 'Borisevičius was buried in a mass grave in Tuskulėnai Manor in Vilnius.' },
                { claim: 'Jews testified that he hid Jews', locator: 'Bishop and execution', excerpt: 'During his later Soviet trial, three Jews testified that he helped Jews to hide from the Holocaust.' },
                { claim: 'beatification process from 1990', locator: 'lead', excerpt: 'The process of his beatification was initiated in 1990.' },
            ],
        },
        activities: [
            { functionId: 'religion', affiliationId: null, startYear: 1910, endYear: 1946, primary: true, claim: 'Catholic priest, seminary rector and bishop of Telšiai, no catalog affiliation', locator: 'lead', excerpt: 'Borisevičius succeeded him as the new bishop of Telšiai' },
        ],
        career: [
            ['1910', '사제 서품', 'Ordained priest'],
            ['1916–1917', '러시아 제국군 제10군 군종 사제', 'Chaplain of the 10th Army of the Russian Imperial Army'],
            ['1927–1940', '텔샤이 신학교 교장', 'Rector of the Telšiai priest seminary'],
            ['1943', '텔샤이 교구장', 'Became bishop of Telšiai'],
            ['1946', 'NKVD에 체포되어 처형', 'Arrested by the NKVD and executed'],
        ],
    })),
];
