// Person cards for event-1940.js (the Soviet occupation of the Baltic states,
// 1939–1941), see lib.js person(). Excerpts are verbatim from the cited pages.
const { W, person } = require('./lib');

const E = t => W(encodeURI(t));
const ET = t => 'https://et.wikipedia.org/wiki/' + encodeURI(t);
const LV = t => 'https://lv.wikipedia.org/wiki/' + encodeURI(t);
const LT = t => 'https://lt.wikipedia.org/wiki/' + encodeURI(t);
const S = {
    vares: E('Johannes_Vares'),
    etVares: ET('Johannes_Vares'),
    kirh: E('Augusts_Kirhenšteins'),
    lvKirh: LV('Augusts_Kirhenšteins'),
    merkys: E('Antanas_Merkys'),
    ltMerkys: LT('Antanas_Merkys'),
    kreve: E('Vincas_Krėvė-Mickevičius'),
    ltKreve: LT('Vincas_Krėvė-Mickevičius'),
    munters: E('Vilhelms_Munters'),
    welles: E('Sumner_Welles'),
    wellesDecl: E('Welles_Declaration'),
    pats: E('Konstantin_Päts'),
};

module.exports = [
    person({
        id: 'johannes-vares', groupId: 'stalin-era',
        given: ['요하네스', 'Johannes'], family: ['바레스', 'Vares'], nativeName: 'Johannes Vares', years: '1890–1946',
        citizenship: 'soviet', origin: 'estonia',
        epithet: ['1940년 즈다노프의 강요로 에스토니아 괴뢰 정부의 총리가 되어 소련 편입을 청원한 시인·의사',
            'Poet and doctor whom Zhdanov forced on Estonia as puppet prime minister in June 1940, and who led the petition to join the Soviet Union'],
        bio: ['비리얀디 근처의 농가에서 태어나 키예프에서 의학을 공부했고, 제1차 세계대전과 에스토니아 독립전쟁에서 군의관으로 복무했다. 뒤에 요하네스 바르바루스라는 필명의 이름난 시인이자 급진 사회주의자가 되었다. 1940년 6월 소련이 에스토니아를 점령하자 안드레이 즈다노프는 콘스탄틴 페츠 대통령에게 바레스를 괴뢰 정부의 총리로 임명하게 했고, 그는 모스크바에 가입 청원을 전한 대표단을 이끌었다. 이후 에스토니아 SSR 최고소비에트 상임간부회 의장을 지냈고, 1941년 독일군이 오자 소련 내지로 피했다. 1944년 돌아와 독립전쟁 시기 행적으로 NKVD의 조사를 받았고, 1946년 11월 탈린의 관저에서 숨졌다. 자살로 여겨지지만 살해설도 있다.',
            'Born to a farming family near Viljandi, he studied medicine in Kiev and served as a military physician in the First World War and the Estonian War of Independence. He became a well-known poet and radical socialist under the pen name Johannes Barbarus. After the Soviet occupation of June 1940, Andrei Zhdanov forced President Konstantin Päts to appoint him prime minister of a communist-dominated puppet government, and he headed the delegation that delivered the petition to join the Soviet Union. He then chaired the Estonian SSR Supreme Soviet’s presidium, fled to Soviet Russia when the Germans came in 1941, and after returning in 1944 was investigated by the NKVD over his role in the War of Independence. He died in the presidential residence in Kadriorg, Tallinn, in November 1946, most probably by suicide, though murder has also been suggested.'],
        fate: ['suicide', '자살 추정', 'Probable suicide'],
        aliases: { ko: ['요한네스 바레스', '요하네스 바르바루스'], en: ['Johannes Barbarus', 'Johannes Vares-Barbarus'] },
        linkExpressions: [['ko', '요한네스 바레스'], ['ko', '요하네스 바르바루스'], ['en', 'Johannes Barbarus']],
        sources: [S.vares, S.etVares],
        facts: {
            years: { claim: '1890–1946', locator: 'lead', excerpt: '12 January 1890 [O.S. 31 December 1889] – 29 November 1946' },
            citizenship: { claim: 'Estonian and Soviet politician; head of the Estonian SSR Supreme Soviet Presidium', locator: 'lead', excerpt: 'was an Estonian and Soviet poet, medical doctor, and politician' },
            nationalOrigin: { claim: 'born to an Estonian farming family near Viljandi', locator: 'Early life and education', excerpt: 'Vares was born in a farmer family in the village of Kiisa, near Viljandi, Estonia.' },
            bio: [
                { claim: 'studied medicine in Kiev', locator: 'Early life and education', excerpt: 'in 1910–1914 studied medicine at the University of Kiev' },
                { claim: 'military physician in WWI and the War of Independence', locator: 'Medical career', excerpt: 'Vares served as a military physician in World War I, and after that as a military physician for the Estonian Army during the Estonian War of Independence (1918–1920).' },
                { claim: 'doctor in Pärnu, poet and radical socialist as Johannes Barbarus', locator: 'Medical career', excerpt: 'He subsequently became a well-known poet as well as a radical socialist, using the pen name Johannes Barbarus.' },
                { claim: 'Zhdanov forced Päts to appoint him puppet prime minister', locator: 'Prime minister of Estonia', excerpt: 'Andrei Zhdanov, leader of the Soviet aggression, forced the Estonian president Konstantin Päts to appoint Vares as prime minister of a communist-dominated puppet government.' },
                { claim: 'headed the delegation delivering the petition to Moscow', locator: 'Prime minister of Estonia', excerpt: 'He headed the delegation to Moscow on 6 August 1940 that formally delivered the petition to Stalin and the Soviet government' },
                { claim: 'chairman of the Presidium of the Estonian SSR Supreme Soviet 1940–1946', source: S.etVares, locator: 'sissejuhatus', excerpt: 'Eesti NSV Ülemnõukogu Presiidiumi esimees 1940–1946' },
                { claim: 'fled to Soviet Russia in 1941', locator: 'Exile in Russia', excerpt: 'Following the German invasion of Estonia in 1941, Vares fled to Soviet Russia' },
                { claim: 'NKVD investigation after 1944', locator: 'Return to Estonia and death', excerpt: 'Vares came under investigation by the Soviet NKVD for his activities in the Estonian War of Independence' },
                { claim: 'died in Kadriorg in November 1946', locator: 'Return to Estonia and death', excerpt: 'He committed suicide in presidential residence in Kadriorg, Tallinn, in November 1946' },
                { claim: 'suicide most probable; murder also suggested', source: S.etVares, locator: 'Elulugu', excerpt: 'kuid hiljem on peetud kõige tõenäolisemaks, et tegu oli enesetapuga' },
                { claim: 'murder also suggested', source: S.etVares, locator: 'Elulugu', excerpt: 'On oletatud ka seda, et ta tapeti.' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-estonia', startYear: 1940, endYear: 1940, claim: '1940년 6~8월 괴뢰 정부 총리', locator: 'Prime minister of Estonia', excerpt: 'forced the Estonian president Konstantin Päts to appoint Vares as prime minister of a communist-dominated puppet government' },
            { functionId: 'legislature', affiliationId: 'state-soviet', startYear: 1940, endYear: 1946, primary: true, claim: '에스토니아 SSR 최고소비에트 상임간부회 의장', source: S.etVares, locator: 'sissejuhatus', excerpt: 'Eesti NSV Ülemnõukogu Presiidiumi esimees 1940–1946' },
        ],
        career: [
            ['1910–1914', '키예프 대학교 의학 공부', 'Studied medicine at the University of Kiev'],
            ['1918–1920', '에스토니아 독립전쟁 군의관', 'Military physician in the Estonian War of Independence'],
            ['1940', '괴뢰 정부 총리, 소련 가입 청원 대표단장', 'Puppet prime minister; led the delegation petitioning to join the USSR'],
            ['1940–1946', '에스토니아 SSR 최고소비에트 상임간부회 의장', 'Chairman of the Estonian SSR Supreme Soviet’s presidium'],
        ],
    }),
    person({
        id: 'augusts-kirhensteins', groupId: 'stalin-era',
        given: ['아우구스츠', 'Augusts'], family: ['키르헨슈테인스', 'Kirhenšteins'], nativeName: 'Augusts Kirhenšteins', years: '1872–1963',
        citizenship: 'soviet', origin: 'latvia',
        epithet: ['1940년 소련 대사관이 정한 라트비아 괴뢰 정부의 총리로 소련 편입을 요청한 미생물학자',
            'Microbiologist who headed the puppet government chosen by the Soviet embassy in 1940 and requested Latvia’s incorporation into the USSR'],
        bio: ['리보니아 마즈살라차의 소작인 집안에서 태어나 타르투 수의학교를 마쳤고, 1905년 혁명에 가담했다가 스위스로 망명해 다보스의 결핵 연구소에서 일했다. 제1차 세계대전에는 세르비아군 수의관으로, 라트비아 독립전쟁에는 수의 부대 대위로 복무했다. 1919년 라트비아 대학교에 미생물학 연구소를 세웠고 1923년 라트비아 최초의 박사 학위 논문을 썼으며, 사회민주주의 지지자였다. 1940년 6월 소련 대사관에 불려 가 새 괴뢰 정부의 수반 자리를 제안받아 총리가 되었고, 7월 21일부터는 대통령 직무도 맡아 라트비아의 소련 편입을 요청했다. 1940~1952년 라트비아 SSR 최고소비에트 상임간부회 의장을 지냈고, 1941년 공산당에 들어갔다. 1963년 리가에서 숨졌다.',
            'Born the son of a tenant on a manor in Mazsalaca, Livonia, he studied at the Tartu Veterinary Institute, took part in the revolution of 1905 and emigrated to Switzerland, working at a tuberculosis institute in Davos. He served as a military veterinarian in the Serbian army in the First World War and as a captain in the veterinary units of the Latvian War of Independence. In 1919 he founded a Microbiology Institute at the University of Latvia, and in 1923 he defended the first doctoral thesis in Latvia; politically he supported social democracy. In June 1940 the Soviet embassy offered him the leadership of the new puppet government; as prime minister, and from 21 July acting president, he requested Latvia’s incorporation into the Soviet Union. He chaired the Latvian SSR Supreme Soviet’s presidium in 1940–1952, joined the Communist Party in 1941 and died in Riga in 1963.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: ['키르헨슈테인스'], en: ['Kirhenšteins', 'Kirchenšteins', 'Augusts Kirchenšteins'] },
        linkExpressions: [['en', 'Augusts Kirchenšteins'], ['en', 'Kirchenšteins']],
        sources: [S.kirh, S.lvKirh],
        facts: {
            years: { claim: '1872–1963', locator: 'lead', excerpt: '18 September 1872 – 3 November 1963' },
            citizenship: { claim: 'Latvian and Soviet politician; Presidium chairman of the Latvian SSR', locator: 'lead', excerpt: 'was a Latvian and Soviet microbiologist, politician and educator' },
            nationalOrigin: [
                { claim: 'Latvian veterinarian, microbiologist and politician', source: S.lvKirh, locator: 'ievads', excerpt: 'bija latviešu veterinārārsts, mikrobiologs un politiķis' },
                { claim: 'born on a manor in Mazsalaca, Livonia', locator: 'Biography', excerpt: 'Augusts Kirhenšteins was born on 18 September 1872 on the estate of Valtenberg Manor in Mazsalaca, in the Governorate of Livonia.' },
            ],
            bio: [
                { claim: 'son of a tenant', locator: 'Biography', excerpt: 'He was the eldest son of the tenant Mārtiņš Kirhenšteins' },
                { claim: 'Tartu Veterinary Institute', locator: 'Biography', excerpt: 'He then studied at the Tartu Veterinary Institute (1893-1901)' },
                { claim: '1905 revolution and emigration to Switzerland', locator: 'Biography', excerpt: 'after the 1905 revolution was defeated in Latvia, Kirhenšteins emigrated to Switzerland' },
                { claim: 'Davos tuberculosis institute', locator: 'Biography', excerpt: 'In 1911, he began work in Davos at the Institute for Tuberculosis Research as an assistant to the bacteriologist Carl Spengler.' },
                { claim: 'Serbian army veterinarian; captain in the War of Independence', locator: 'Biography', excerpt: 'During World War I, Kirhenšteins served in the Serbian army as a military veterinarian.' },
                { claim: 'captain in veterinary units', locator: 'Biography', excerpt: 'later becoming a captain in veterinary units of the Latvian National Armed Forces during the Latvian War of Independence' },
                { claim: 'Microbiology Institute at the University of Latvia', locator: 'Biography', excerpt: 'In 1919, he was elected as an associate professor at the University of Latvia, where he established a Microbiology Institute in the Faculty of Agriculture.' },
                { claim: 'first doctoral thesis in Latvia', locator: 'Biography', excerpt: 'this was the first doctoral thesis defended in Latvia' },
                { claim: 'supporter of social democracy', locator: 'Biography', excerpt: 'he was a supporter of social democracy' },
                { claim: 'invited to the Soviet embassy and offered the puppet government', locator: 'Biography', excerpt: 'After the occupation of Latvia, Kirhenšteins was invited to the USSR Embassy and offered to become the head of the new Soviet puppet government in Latvia' },
                { claim: 'prime minister from 20 June, acting president from 21 July 1940', locator: 'lead', excerpt: 'He was the de facto prime minister of Latvia from 20 June 1940 to 25 August 1940 and Acting de facto President of Latvia from 21 July 1940 to 25 August 1940.' },
                { claim: 'his government requested incorporation', locator: 'lead', excerpt: "It was Kirhenšteins' Soviet puppet government that requested the incorporation of Latvia into the Soviet Union after the occupation of the country in 1940." },
                { claim: 'Presidium chairman 1940–1952; party member 1941', locator: 'lead', excerpt: 'He became a member of the Communist Party in 1941. He was Chairman of the Presidium of the Supreme Soviet of the Latvian Soviet Socialist Republic 1940–1952.' },
                { claim: 'died in Riga 1963', locator: 'Biography', excerpt: 'He died on 3 November 1963 in Riga' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-latvia', startYear: 1940, endYear: 1940, claim: '1940년 괴뢰 정부 총리·대통령 직무대행', locator: 'lead', excerpt: 'He was the de facto prime minister of Latvia from 20 June 1940 to 25 August 1940' },
            { functionId: 'legislature', affiliationId: 'state-soviet', startYear: 1940, endYear: 1952, primary: true, claim: '라트비아 SSR 최고소비에트 상임간부회 의장', locator: 'lead', excerpt: 'He was Chairman of the Presidium of the Supreme Soviet of the Latvian Soviet Socialist Republic 1940–1952.' },
        ],
        career: [
            ['1893–1901', '타르투 수의학교', 'Tartu Veterinary Institute'],
            ['1911', '다보스 결핵 연구소 조수', 'Assistant at the tuberculosis institute in Davos'],
            ['1919', '라트비아 대학교 미생물학 연구소 설립', 'Founded the Microbiology Institute at the University of Latvia'],
            ['1940', '괴뢰 정부 총리, 대통령 직무대행', 'Puppet prime minister and acting president'],
            ['1940–1952', '라트비아 SSR 최고소비에트 상임간부회 의장', 'Chairman of the Latvian SSR Supreme Soviet’s presidium'],
        ],
    }),
    person({
        id: 'antanas-merkys',
        given: ['안타나스', 'Antanas'], family: ['메르키스', 'Merkys'], nativeName: 'Antanas Merkys', years: '1887–1955',
        citizenship: 'lithuania', origin: 'lithuania',
        epithet: ['1940년 소련의 최후통첩을 받아들이고 대통령 권한을 쥐었다가 팔레츠키스에게 넘긴 마지막 총리',
            'Last prime minister of independent Lithuania, who accepted the Soviet ultimatum of 1940, took the presidency and handed power to Paleckis'],
        bio: ['소농 집안에서 태어나 법학을 공부했고, 국방장관(1919, 1926~1927), 클라이페다 지사, 카우나스 시장을 지냈다. 1939년 가을 빌뉴스 지역 정부 전권위원을 거쳐 11월 총리가 되었고, 1940년 6월 최후통첩을 받아들이자고 주장했다. 스메토나가 망명하자 대통령 직무를 맡았고, 이튿날 라디오로 스스로 대통령이 되었다고 알린 뒤 6월 17일 유스타스 팔레츠키스를 총리로 임명하고 물러났다. 리투아니아는 이 권한 장악을 위헌으로 본다. 한 달 뒤 스웨덴으로 탈출하려다 리가에서 붙잡혀 사라토프로 추방되었고 1941년 투옥되었다. 1954년 풀려났으나 귀국하지 못하고 이듬해 숨졌다.',
            'Born to a smallholding peasant family near Skapiškis, he studied law and was minister of defence (1919, 1926–1927), governor of the Klaipėda Region and mayor of Kaunas. After serving in autumn 1939 as government commissioner for the Vilnius region, he became prime minister that November, and in June 1940 he argued for accepting the Soviet ultimatum. When Smetona left the country he became acting president, announced on the radio the next day that he was now president in his own right, and on 17 June appointed Justas Paleckis prime minister and resigned. Lithuania regards this takeover of the presidency as unconstitutional. A month later he tried to escape to Sweden but was arrested in Riga and deported to Saratov; he was imprisoned in 1941. Released in 1954 but not allowed to return to Lithuania, he died in Vladimir in 1955.'],
        fate: ['exile', '귀국 못 하고 소련에서 사망', 'Died in the USSR, barred from returning'],
        aliases: { ko: ['메르키스'], en: ['Merkys'] },
        sources: [S.merkys, S.ltMerkys],
        facts: {
            years: { claim: '1887–1955', locator: 'lead', excerpt: '1 February 1887 – 5 March 1955' },
            citizenship: { claim: 'prime minister of independent Lithuania', locator: 'lead', excerpt: 'was the last Prime Minister of independent Lithuania, serving from November 1939 to June 1940' },
            nationalOrigin: [
                { claim: 'Lithuanian lawyer and politician', source: S.ltMerkys, locator: 'įvadas', excerpt: 'teisininkas, politikas, paskutinis tarpukario Lietuvos Ministras pirmininkas' },
                { claim: 'born in Bajorai near Skapiškis', locator: 'Biography', excerpt: 'Merkys was born in Bajorai, near Skapiškis.' },
            ],
            bio: [
                { claim: 'smallholding peasant family', source: S.ltMerkys, locator: 'Biografija', excerpt: 'Gimė mažažemių valstiečių šeimoje.' },
                { claim: 'law; Russian Army in WWI', locator: 'Biography', excerpt: 'Educated in law, he served in the Russian Army during World War I (1914–18).' },
                { claim: 'Minister of Defence 1919', locator: 'Biography', excerpt: "In 1919, he served as the newly independent Lithuania's Minister of Defence" },
                { claim: 'Minister of Defence again 1926–1927, then Klaipėda governor', locator: 'Biography', excerpt: 'he became Minister of Defence again until 1927, when he was made Governor of the Klaipėda Region' },
                { claim: 'Klaipėda governor 1927–1932', source: S.ltMerkys, locator: 'Biografija', excerpt: '1927–1932 m. Klaipėdos gubernatorius' },
                { claim: 'Mayor of Kaunas 1933–1939', locator: 'Biography', excerpt: 'He became Mayor of Kaunas in 1933 and served in this position until 1939.' },
                { claim: 'government commissioner for Vilnius, autumn 1939', source: S.ltMerkys, locator: 'Biografija', excerpt: '1939 m. rudenį – Vyriausybės įgaliotinis Vilniui ir Vilniaus sričiai.' },
                { claim: 'prime minister from November 1939', locator: 'lead', excerpt: 'serving from November 1939 to June 1940' },
                { claim: 'suggested accepting the ultimatum', locator: 'Soviet ultimatum and occupation', excerpt: 'Merkys suggested accepting the ultimatum and offered to resign as prime minister' },
                { claim: 'announced on radio he was president', locator: 'Soviet ultimatum and occupation', excerpt: "The day after Smetona's departure, Merkys announced on national radio that he had removed Smetona and was now president in his own right." },
                { claim: 'appointed Paleckis and resigned 17 June', locator: 'Soviet ultimatum and occupation', excerpt: 'appointing left-wing journalist Justas Paleckis as the new prime minister. Merkys resigned later that day' },
                { claim: 'Lithuania regards the takeover as unconstitutional', locator: 'Soviet ultimatum and occupation', excerpt: "Lithuania has maintained that Merkys' takeover of the presidency was illegal and unconstitutional" },
                { claim: 'arrested in Riga, deported to Saratov, imprisoned 1941', locator: 'Soviet ultimatum and occupation', excerpt: 'A month later, Merkys attempted to escape to Sweden, but was arrested in Riga. He and his family were deported to Saratov in Russia. In 1941, Merkys was imprisoned.' },
                { claim: 'released 1954, not allowed to return; died 1955', locator: 'Soviet ultimatum and occupation', excerpt: 'In 1954, during the period of de-Stalinization, Merkys was released from prison, but not allowed to return to Lithuania. He lived in Vladimir until his death the following year, on 5 March 1955.' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-lithuania', startYear: 1919, endYear: 1940, primary: true, claim: '국방장관·클라이페다 지사·카우나스 시장·총리', locator: 'lead', excerpt: 'was the last Prime Minister of independent Lithuania, serving from November 1939 to June 1940' },
        ],
        career: [
            ['1919', '국방장관', 'Minister of Defence'],
            ['1927–1932', '클라이페다 지사', 'Governor of the Klaipėda Region'],
            ['1933–1939', '카우나스 시장', 'Mayor of Kaunas'],
            ['1939–1940', '총리', 'Prime minister'],
            ['1940', '대통령 직무대행, 소련 추방', 'Acting president; deported to the USSR'],
        ],
    }),
    person({
        id: 'vincas-kreve-mickevicius',
        given: ['빈차스', 'Vincas'], family: ['크레베미츠케비추스', 'Krėvė-Mickevičius'], nativeName: 'Vincas Krėvė-Mickevičius', years: '1882–1954',
        citizenship: 'lithuania', origin: 'lithuania',
        epithet: ['1940년 리투아니아 「인민정부」를 이끌다 몰로토프에게서 병합 방침을 듣고 사임한 작가',
            'Lithuanian writer who led the “People’s Government” of 1940 and resigned after Molotov told him the Baltic states would join the USSR'],
        bio: ['다주키야 지방의 농가에서 태어나 마을 사람들이 집안을 부르던 이름 크레베를 필명으로 삼았다. 리비우에서 문헌학 박사 학위를 받고 바쿠에서 교사로 일했으며, 1919년 아제르바이잔 주재 영사가 되었다. 1922년부터 리투아니아 대학교에서 슬라브 문학을 가르쳤고 리투아니아 문학의 고전 작가로 꼽힌다. 1940년 6월 소련 점령 뒤 「인민정부」에 들어가 외무장관과 총리 직무를 맡았으나, 7월 1일 밤 모스크바에서 몰로토프에게 발트 국가들이 모두 소련에 들어가야 한다는 말을 듣고 돌아와 사임했다. 1941년 리투아니아 SSR 과학아카데미 초대 원장이 되었고, 1944년 7월 오스트리아로 떠났고, 1947년부터 미국 펜실베이니아 대학교에서 가르치다 1954년 숨졌다.',
            'Born to a peasant family in the village of Subartonys in the Dzūkija region, he took his pen name from Krėvė, the name villagers gave his family. He received a doctorate in philology at Lviv in 1908, taught in Baku and in 1919 became Lithuania’s consul in Azerbaijan. From 1922 he taught Slavic literature at the University of Lithuania, and he is counted a classic of Lithuanian literature. After the Soviet occupation of June 1940 he joined the “People’s Government” as foreign minister and acting prime minister, but on the night of 1 July Molotov told him in Moscow that all the Baltic states had to join the Soviet Union; he returned and resigned. In 1941 he became the first president of the Lithuanian SSR Academy of Sciences. In July 1944 he left for Austria before the Soviets returned, and from 1947 he taught at the University of Pennsylvania until his death in 1954.'],
        fate: ['exile', '미국 망명 중 사망', 'Died in exile in the United States'],
        aliases: { ko: ['빈차스 크레베', '빈차스 미츠케비추스'], en: ['Vincas Krėvė', 'Vincas Mickevičius', 'Vincas Kreve-Mickevicius'] },
        linkExpressions: [['ko', '빈차스 크레베'], ['en', 'Vincas Krėvė'], ['en', 'Vincas Mickevičius']],
        sources: [S.kreve, S.ltKreve],
        facts: {
            years: { claim: '1882–1954', locator: 'lead', excerpt: 'October 19, 1882 – July 17, 1954' },
            citizenship: { claim: 'Lithuanian writer and politician', locator: 'lead', excerpt: 'was a Lithuanian writer, poet, novelist, playwright and philologist' },
            nationalOrigin: { claim: 'born to Lithuanian peasant farmers in Dzūkija', locator: 'Biography', excerpt: 'Vincas Mickevičius was born to a family of peasant farmers on October 19, 1882, in the village of Subartonys in the Dzūkija ethnographic region of Lithuania.' },
            bio: [
                { claim: 'pen name from the family nickname Krėvė', locator: 'Biography', excerpt: 'His family was called Krėvė by the local villagers, the name that he later used for his pen name.' },
                { claim: 'doctorate in philology at Lviv 1908', locator: 'Biography', excerpt: 'in 1908, he received his doctorate in philology' },
                { claim: 'teacher in Baku', locator: 'Biography', excerpt: 'In 1909, Krėvė-Mickevičius became a high school teacher in the city of Baku, Azerbaijan.' },
                { claim: 'consul in Azerbaijan', locator: 'Biography', excerpt: 'Krėvė-Mickevičius became Lithuanian Consul in Azerbaijan' },
                { claim: 'professor of Slavic literatures from 1922', locator: 'Biography', excerpt: 'When the University of Lithuania was founded in 1922, Vincas Krėvė-Mickevičius became professor of Slavic Languages and Literatures' },
                { claim: 'classic of Lithuanian literature', source: S.ltKreve, locator: 'įvadas', excerpt: 'lietuvių literatūros klasikas' },
                { claim: 'People’s Government: deputy PM and foreign minister, then acting PM', source: S.ltKreve, locator: 'Okupacijų metai', excerpt: 'buvo paskirtas ministro pirmininko pavaduotoju ir užsienio reikalų ministru, vėliau ėjo Ministro pirmininko pareigas' },
                { claim: 'Molotov on the night of 1 July: all Baltic states must join; resigned', source: S.ltKreve, locator: 'Okupacijų metai', excerpt: 'po 1940 m. liepos 1-osios nakties derybų su sovietų komisaru V. Molotovu, kur jam buvo pareikšta, kad visos Baltijos šalys turi įeiti į Sovietinių respublikų sąjungą' },
                { claim: 'wrote his resignation', source: S.ltKreve, locator: 'Okupacijų metai', excerpt: 'grįžęs iš Maskvos, parašė atsistatydinimo pareiškimą ir iš pareigų pasitraukė' },
                { claim: 'first president of the Lithuanian SSR Academy of Sciences 1941', source: S.ltKreve, locator: 'Okupacijų metai', excerpt: 'išrinktas pirmuoju LTSR mokslų akademijos prezidentu' },
                { claim: 'left for Austria in July 1944', source: S.ltKreve, locator: 'Emigracijoje', excerpt: '1944 m. liepos mėn., vengdamas bolševikų represijų, su šeima pasitraukė į Austriją.' },
                { claim: 'University of Pennsylvania from 1947', locator: 'Biography', excerpt: 'In 1947, the University of Pennsylvania extended an invitation to join its faculty.' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-lithuania', startYear: 1940, endYear: 1940, primary: true, claim: '1940년 인민정부 외무장관·총리 직무', source: S.ltKreve, locator: 'Okupacijų metai', excerpt: 'buvo paskirtas ministro pirmininko pavaduotoju ir užsienio reikalų ministru, vėliau ėjo Ministro pirmininko pareigas' },
        ],
        career: [
            ['1908', '리비우 대학교 문헌학 박사', 'Doctorate in philology, University of Lviv'],
            ['1919', '아제르바이잔 주재 리투아니아 영사', 'Lithuanian consul in Azerbaijan'],
            ['1922', '리투아니아 대학교 슬라브 문학 교수', 'Professor of Slavic literatures, University of Lithuania'],
            ['1940', '인민정부 외무장관·총리 직무', 'Foreign minister and acting prime minister of the People’s Government'],
            ['1947–1953', '펜실베이니아 대학교에서 강의', 'Taught at the University of Pennsylvania'],
        ],
    }),
    person({
        id: 'vilhelms-munters',
        given: ['빌헬름스', 'Vilhelms'], family: ['문테르스', 'Munters'], nativeName: 'Vilhelms Munters', years: '1898–1967',
        citizenship: 'latvia', origin: { code: 'latvia', label: { ko: '라트비아인 (에스토니아·발트 독일계)', en: 'Latvian (Estonian and Baltic German parentage)' } },
        epithet: ['1939년 소련–라트비아 상호원조조약에 서명하고 1940년 소련으로 추방된 라트비아 외무장관',
            'Latvian foreign minister who signed the Soviet–Latvian Mutual Assistance Treaty in 1939 and was deported to the Soviet Union in 1940'],
        bio: ['리가에서 에스토니아인 상인 아버지와 발트 독일인 어머니 사이에 태어났고, 라트비아 독립전쟁 때 에스토니아군에서 복무했다. 1920년부터 외무부에서 일하며 1933년 사무총장이 되었고, 1934년 울마니스의 쿠데타 뒤 사실상 외무부를 이끌다 1936~1940년 외무장관을 지냈다. 1939년 6월 독일–라트비아 불가침조약에, 10월 5일 소련–라트비아 상호원조조약에 서명했다. 소련 점령 뒤 1940년 7월 내무장관 빌리스 라치스가 지켜보는 가운데 가족과 함께 보로네시로 추방되었고, 1941년 6월 체포되어 1952년 징역 25년을 선고받았다. 1954년 풀려나 1958년 라트비아로 돌아왔고, 해외 라트비아인 단체를 비난하는 글을 쓰다 1967년 숨졌다.',
            'Born in Riga to an Estonian trader and a Baltic German mother, he served in the Estonian Army during the Latvian War of Independence. He joined the Latvian foreign ministry in 1920, became its general secretary in 1933, ran the ministry de facto after Kārlis Ulmanis’s coup of 1934 and was foreign minister from 1936 to 1940; he was also active on the Council of the League of Nations. In June 1939 he signed the German–Latvian Non-Aggression Pact and on 5 October 1939 the Soviet–Latvian Mutual Assistance Treaty. After the Soviet occupation he and his family were deported to Voronezh in July 1940 in the presence of the interior minister Vilis Lācis; he was arrested in June 1941 and in 1952 sentenced to 25 years. Released in 1954, he returned to Latvia in 1958, wrote against the Latvian diaspora organisations and died in Riga in 1967.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: ['문테르스'], en: ['Munters', 'Wilhelm Munters'] },
        linkExpressions: [['en', 'Wilhelm Munters']],
        sources: [S.munters],
        facts: {
            years: { claim: '1898–1967', locator: 'lead', excerpt: '25 July 1898 – 11 January 1967' },
            citizenship: { claim: 'Latvian diplomat and foreign minister', locator: 'lead', excerpt: 'was a Latvian diplomat who served as Minister of Foreign Affairs of the Republic of Latvia from 1936 to 1940' },
            nationalOrigin: { claim: 'Estonian father, Baltic German mother', locator: 'Early life', excerpt: 'in Riga to Estonian trader Nikolai Munter (Nikolajs Munters, died 1930) and Baltic German mother from Estonia' },
            bio: [
                { claim: 'fought as a cadet in the October Revolution', locator: 'Early life', excerpt: 'He, together with other cadets, took part in fighting during the Bolshevik October Revolution' },
                { claim: 'served in the Estonian Army in 1919–1920', locator: 'Early life', excerpt: 'he joined the 6th Infantry Regiment, 1st Division of the Estonian Army on 24 June 1919' },
                { claim: 'foreign ministry from 1920', locator: 'Diplomatic service career', excerpt: 'Since 20 December 1920, Munters began working at the Ministry of Foreign Affairs of Latvia.' },
                { claim: 'general secretary 1933', locator: 'Diplomatic service career', excerpt: 'On 14 July 1933, Munters was appointed general secretary of the Ministry of Foreign Affairs' },
                { claim: 'de facto head after the 1934 coup', locator: 'Diplomatic service career', excerpt: 'Munters became the de facto head of the ministry' },
                { claim: 'foreign minister 1936–1940', locator: 'Diplomatic service career', excerpt: 'Vilhelms Munters became the minister of foreign affairs of the Republic of Latvia on 14 July 1936, and served in this capacity until 21 June 1940.' },
                { claim: 'League of Nations Council', locator: 'lead', excerpt: 'He was also a member of the Council of the League of Nations from 1936 to 1938' },
                { claim: 'signed the German–Latvian pact and the Soviet–Latvian treaty', locator: 'Diplomatic service career', excerpt: 'On 7 June 1939, Munters signed the German-Latvian Non-Aggression Pact in Berlin and on 5 October 1939 - the Soviet–Latvian Mutual Assistance Treaty' },
                { claim: 'deported July 1940 in the presence of Vilis Lācis', locator: 'Deportation and imprisonment', excerpt: 'the Munters family was deported on 16 July 1940 in the presence of the collaborationist minister of the interior Vilis Lācis' },
                { claim: 'exile in Voronezh', locator: 'Deportation and imprisonment', excerpt: 'During forced exile in Voronezh, he worked in the Institute of Foreign Language Teachers.' },
                { claim: 'arrested 26 June 1941', locator: 'Deportation and imprisonment', excerpt: 'On 26 June 1941 Munters was arrested.' },
                { claim: 'sentenced to 25 years in 1952', locator: 'Deportation and imprisonment', excerpt: 'on 14 April 1952, the Special Council of the NKVD sentenced Munters to 25 years in prison' },
                { claim: 'released 1954', locator: 'Deportation and imprisonment', excerpt: 'he was released on 19 August 1954, but was forbidden to return to the Baltic states' },
                { claim: 'returned to Latvia 1958', locator: 'Final years and death', excerpt: 'In 1958 he together with his family was finally permitted to return to occupied Latvia' },
                { claim: 'articles against émigré organisations', locator: 'Final years and death', excerpt: 'critical of Latvian diaspora organizations' },
                { claim: 'died in Riga 1967', locator: 'Final years and death', excerpt: 'Vilhelms Munters died on 11 January 1967 in Riga' },
            ],
        },
        activities: [
            { functionId: 'diplomacy', affiliationId: 'state-latvia', startYear: 1920, endYear: 1940, primary: true, claim: '라트비아 외무부 관리, 1936~1940년 외무장관', locator: 'Diplomatic service career', excerpt: 'Vilhelms Munters became the minister of foreign affairs of the Republic of Latvia on 14 July 1936, and served in this capacity until 21 June 1940.' },
        ],
        career: [
            ['1920', '라트비아 외무부 입부', 'Joined the Latvian foreign ministry'],
            ['1933', '외무부 사무총장', 'General secretary of the foreign ministry'],
            ['1936–1940', '외무장관', 'Minister of foreign affairs'],
            ['1939', '소련–라트비아 상호원조조약 서명', 'Signed the Soviet–Latvian Mutual Assistance Treaty'],
            ['1940–1954', '소련 추방·투옥', 'Deported and imprisoned in the USSR'],
        ],
    }),
    person({
        id: 'sumner-welles',
        given: ['섬너', 'Sumner'], family: ['웰스', 'Welles'], nativeName: 'Sumner Welles', years: '1892–1961',
        citizenship: 'usa', origin: 'usa',
        epithet: ['1940년 7월 소련의 발트 3국 병합을 승인하지 않는다고 밝힌 웰스 선언의 미국 국무차관',
            'US Under Secretary of State whose Welles Declaration of July 1940 refused to recognise the Soviet annexation of the Baltic states'],
        bio: ['뉴욕의 부유한 정치 명문가에서 태어나 1914년 하버드 칼리지를 졸업했고, 집안 친구 프랭클린 루스벨트의 권유로 외교관이 되었다. 라틴아메리카 전문가로 일하다 쿨리지 대통령에게 외교 경력을 끊겼으나, 루스벨트 집권 뒤 라틴아메리카 담당 국무차관보를 거쳐 1937~1943년 국무차관을 지냈다. 1940년 7월 23일 국무장관 대행으로서 소련의 발트 3국 점령을 규탄하고 병합을 승인하지 않는 웰스 선언을 발표했고, 그 전날에는 콘스탄틴 페츠 가족에게 외교 비자를 내주도록 허가했다. 뒤에도 병합에 대한 어떤 양보에도 반대했다. 대서양 헌장 작성에 참여했으나, 1943년 열차 승무원들에게 성관계를 제안한 일이 퍼지면서 코델 헐에게 밀려났다. 1961년 뉴저지에서 숨졌다.',
            'Born in New York City to a wealthy political family, he graduated from Harvard in 1914 and joined the diplomatic service on the advice of the family friend Franklin Roosevelt. A Latin America specialist, he saw his career ended by President Coolidge, but under Roosevelt he became Assistant Secretary for Latin American Affairs and then Under Secretary of State from 1937 to 1943. As acting Secretary of State he issued the Welles Declaration on 23 July 1940, condemning the Soviet occupation of the Baltic states and refusing to recognise their annexation; the day before, he had authorised diplomatic visas for the family of Konstantin Päts. He went on to oppose any concession on the Baltic question. He helped write the Atlantic Charter, but was forced out by Cordell Hull in 1943 after word spread that he had propositioned two railroad porters. He died in New Jersey in 1961.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: ['벤저민 섬너 웰스'], en: ['Benjamin Sumner Welles'] },
        linkExpressions: [['ko', '벤저민 섬너 웰스'], ['en', 'Benjamin Sumner Welles']],
        sources: [S.welles, S.wellesDecl, S.pats],
        facts: {
            years: { claim: '1892–1961', locator: 'lead', excerpt: 'October 14, 1892 – September 24, 1961' },
            citizenship: { claim: 'American government official and diplomat', locator: 'lead', excerpt: 'was an American government official and diplomat' },
            nationalOrigin: { claim: 'born in New York City to a wealthy American family', locator: 'lead', excerpt: 'Born in New York City to a wealthy, well-connected political family' },
            bio: [
                { claim: 'Harvard 1914; Foreign Service on Roosevelt’s advice', locator: 'lead', excerpt: 'Welles graduated from Harvard College in 1914. He entered the Foreign Service at the advice of Franklin Roosevelt, who was a family friend.' },
                { claim: 'Latin America specialist; dismissed by Coolidge', locator: 'lead', excerpt: 'President Calvin Coolidge distrusted Welles because of his divorce, and dismissed him from the foreign service.' },
                { claim: 'Assistant Secretary for Latin American Affairs', locator: 'lead', excerpt: 'he put Welles in charge of Latin American affairs as Assistant Secretary of State for Latin American Affairs' },
                { claim: 'Under Secretary 1937–1943', locator: 'lead', excerpt: 'served as Under Secretary of State from 1937 to 1943' },
                { claim: 'Welles Declaration as acting Secretary of State', source: S.wellesDecl, locator: 'lead', excerpt: 'The Welles Declaration was a diplomatic statement issued on July 23, 1940, by Sumner Welles, the acting US Secretary of State' },
                { claim: 'visas for the Päts family', source: S.pats, locator: '1939–1940: World War II, Soviet invasion of Estonia', excerpt: 'The Acting US Secretary of State, Sumner Welles gave permission for issuing diplomatic visas to the entire Päts family already on the next day.' },
                { claim: 'opposed concessions on the Baltic question', source: S.wellesDecl, locator: 'Impact', excerpt: 'He interpreted any concession in the Baltic issue as' },
                { claim: 'wrote the Atlantic Charter', locator: 'Legacy', excerpt: 'With Roosevelt, Churchill and Alexander Cadogan, he wrote the Atlantic Charter' },
                { claim: 'forced out by Hull in 1943', locator: 'lead', excerpt: 'Welles was forced out of government service by Secretary Hull after his enemies began to spread word of a 1943 incident in which he had propositioned two male railroad porters for sex.' },
                { claim: 'died in Bernardsville 1961', locator: 'Personal life', excerpt: 'He died on September 24, 1961, at age 68 in Bernardsville, New Jersey.' },
            ],
        },
        activities: [
            { functionId: 'diplomacy', affiliationId: 'state-usa', startYear: null, endYear: 1943, primary: true, claim: '미국 외교관, 1937~1943년 국무차관', locator: 'lead', excerpt: 'served as Under Secretary of State from 1937 to 1943' },
        ],
        career: [
            ['1914', '하버드 칼리지 졸업, 외교관 입문', 'Graduated from Harvard; entered the diplomatic service'],
            ['1937–1943', '국무차관', 'Under Secretary of State'],
            ['1940', '웰스 선언 발표', 'Issued the Welles Declaration'],
            ['1941', '대서양 헌장 작성 참여', 'Helped write the Atlantic Charter'],
        ],
    }),
];
