// 1958–1992: the Great Leap, the Cultural Revolution, reform, Tiananmen.
const W = 'https://en.wikipedia.org/wiki/';
const K = 'https://ko.wikipedia.org/wiki/';
const M = 'https://www.marxists.org/reference/archive/mao/selected-works/';
const D = 'https://www.marxists.org/reference/archive/deng-xiaoping/';

module.exports = [
    {
        id: 'great-leap-forward', sortOrder: 235, period: '1958–1962', countries: ['china'],
        title: { ko: '대약진과 대기근', en: 'The Great Leap Forward and the Great Famine' },
        question: { ko: '「15년 안에 영국을 따라잡는다」는 운동은 어떻게 평시 최대의 기근이 되었는가?', en: 'How did a campaign to “overtake Britain in fifteen years” become the largest famine of peacetime history?' },
        summary: { ko: '1958년 마오는 소련 모델을 넘어 대중 동원으로 공업과 농업을 동시에 도약시키겠다며 인민공사·뒷마당 용광로·수리 건설을 밀어붙였다. 부풀려진 수확 보고와 높은 징발, 공동식당의 낭비가 겹쳐 1959~1961년 1,500만~4,500만 명이 굶어 죽었다. 1959년 루산 회의에서 펑더화이의 비판은 「반당」으로 몰렸고, 1962년 7천인 대회에서야 지도부는 후퇴를 인정했다.', en: 'In 1958 Mao set out to leap beyond the Soviet model by mobilising the masses to develop industry and agriculture at once, driving the people’s communes, backyard furnaces and irrigation works. Inflated harvest reports, high procurement and the waste of the communal dining halls combined to starve between fifteen and forty-five million people to death in 1959–1961. At the Lushan Conference of 1959 Peng Dehuai’s criticism was branded “anti-party”, and only at the Seven Thousand Cadres Conference of 1962 did the leadership admit the retreat.' },
        outcome: { ko: '류사오치·덩샤오핑의 조정 정책으로 경제는 회복되었으나 마오는 이를 「자본주의의 부활」로 보았고, 대약진의 책임을 둘러싼 지도부의 균열이 문화대혁명의 뿌리가 되었다. 기근의 규모는 1980년대 인구통계로 처음 드러났고 중국에서는 여전히 「3년 자연재해」로 불린다.', en: 'The economy recovered under the adjustment policies of Liu Shaoqi and Deng Xiaoping, but Mao saw them as a “restoration of capitalism”, and the split in the leadership over responsibility for the Leap became the root of the Cultural Revolution. The scale of the famine first emerged from the demographic data of the 1980s, and in China it is still called the “three years of natural disasters”.' },
        locations: [
            { lat: 32.15, lng: 114.09, label: { ko: '신양 (허난)', en: 'Xinyang (Henan)' } },
            { lat: 29.57, lng: 115.98, label: { ko: '루산', en: 'Lushan' } },
            { lat: 39.90, lng: 116.40, label: { ko: '베이징', en: 'Beijing' } },
            { lat: 39.02, lng: 115.66, label: { ko: '쉬수이 (허베이)', en: 'Xushui (Hebei)' } },
            { lat: 30.57, lng: 104.07, label: { ko: '청두', en: 'Chengdu' } },
        ],
        timeline: [
            { date: '1957.11', title: { ko: '「15년 안에 영국을 따라잡는다」', en: '“Overtake Britain in fifteen years”' }, body: { ko: '모스크바에서 마오가 소련의 「미국 추월」에 맞춰 철강 생산에서 영국을 앞서겠다고 선언했다.', en: 'In Moscow Mao matched the Soviet pledge to overtake America with a promise to pass Britain in steel output.' } },
            { date: '1958.05', title: { ko: '제8차 당대회 2차 회의: 총노선 채택', en: 'Second session of the Eighth Congress: the general line' }, body: { ko: '「많이·빨리·좋게·절약하며 사회주의를 건설하자」는 총노선이 채택되고 대약진이 공식화되었다.', en: 'The general line “go all out, aim high, build socialism with greater, faster, better and more economical results” was adopted and the Leap made official.' }, geo: { kind: 'point', lat: 39.90, lng: 116.40, label: { ko: '베이징', en: 'Beijing' } } },
            { date: '1958.08', title: { ko: '베이다이허 회의: 인민공사와 철강 1,070만 톤', en: 'Beidaihe conference: communes and 10.7 million tonnes of steel' }, body: { ko: '정치국이 인민공사의 전국화와 철강 생산 두 배를 결의했다. 마오는 「인민공사는 좋다」고 말했다.', en: 'The Politburo resolved to spread the communes nationwide and double steel output; Mao declared “people’s communes are good”.' }, geo: { kind: 'point', lat: 39.83, lng: 119.49, label: { ko: '베이다이허', en: 'Beidaihe' } } },
            { date: '1958.가을', title: { ko: '뒷마당 용광로와 「위성 밭」', en: 'Backyard furnaces and “sputnik fields”' }, body: { ko: '9천만 명이 철을 녹였고 신문은 무당 수만 근의 수확을 보도했다. 수확은 밭에 방치되었다.', en: 'Ninety million people smelted iron and newspapers reported harvests of tens of thousands of jin per mu; crops were left in the fields.' }, geo: { kind: 'point', lat: 39.02, lng: 115.66, label: { ko: '쉬수이', en: 'Xushui' } } },
            { date: '1958.11–1959.초', title: { ko: '첫 조정 시도', en: 'First attempts at adjustment' }, body: { ko: '정저우·우창 회의에서 마오가 「공산풍」의 과잉을 인정하고 목표를 낮췄으나 기본 노선은 유지했다.', en: 'At the Zhengzhou and Wuchang conferences Mao admitted the excesses of the “communist wind” and lowered targets while keeping the line.' } },
            { date: '1959.07–08', title: { ko: '루산 회의', en: 'The Lushan Conference' }, body: { ko: '펑더화이의 편지가 「우경 기회주의」로 규정되고 반당집단 숙청과 반우경 운동이 시작되었다.', en: 'Peng Dehuai’s letter was branded “right opportunism”; the anti-party clique purge and the anti-right-deviation campaign began.' }, geo: { kind: 'point', lat: 29.57, lng: 115.98, label: { ko: '루산', en: 'Lushan' } } },
            { date: '1959–1960', title: { ko: '신양 사건', en: 'The Xinyang incident' }, body: { ko: '허난 신양 지구에서 징발과 폭력으로 100만 명 이상이 죽었다. 1960년 말 중앙이 조사에 나섰다.', en: 'In Xinyang prefecture, Henan, procurement and violence killed more than a million; the centre investigated at the end of 1960.' }, geo: { kind: 'point', lat: 32.15, lng: 114.09, label: { ko: '신양', en: 'Xinyang' } } },
            { date: '1960.07', title: { ko: '소련 전문가 철수', en: 'Soviet experts withdrawn' }, body: { ko: '흐루쇼프가 1,390명의 기술자를 철수시켜 공업 사업이 중단되었다.', en: 'Khrushchev withdrew 1,390 technicians, halting industrial projects.' } },
            { date: '1960.11', title: { ko: '「12조」 긴급 지시', en: 'The “twelve articles” emergency directive' }, body: { ko: '사유 텃밭과 농촌 시장을 복원하고 생산대 소유를 인정했다. 조정이 시작되었다.', en: 'Private plots and rural markets were restored and team-level ownership recognised; the retreat began.' } },
            { date: '1961.01', title: { ko: '9중전회: 「조정·공고·충실·제고」', en: 'Ninth Plenum: “readjust, consolidate, fill out, raise standards”' }, body: { ko: '천윈·리푸춘의 조정 방침이 채택되고 곡물 수입이 시작되었다.', en: 'The adjustment policy of Chen Yun and Li Fuchun was adopted and grain imports began.' } },
            { date: '1962.01–02', title: { ko: '7천인 대회', en: 'The Seven Thousand Cadres Conference' }, body: { ko: '류사오치가 「3할은 천재, 7할은 인재」라 말했고 마오는 자아비판을 했다.', en: 'Liu Shaoqi said the disaster was “three parts nature, seven parts man”; Mao made a self-criticism.' }, geo: { kind: 'point', lat: 39.90, lng: 116.40, label: { ko: '베이징', en: 'Beijing' } } },
            { date: '1962.09', title: { ko: '10중전회: 「계급투쟁을 잊지 말자」', en: 'Tenth Plenum: “never forget class struggle”' }, body: { ko: '마오가 농가 청부제 확산을 자본주의 부활로 규정하고 조정의 종료를 선언했다.', en: 'Mao branded the spread of household contracting a restoration of capitalism and declared the retreat over.' } },
        ],
        sections: [
            {
                heading: { ko: '소련 모델을 넘어서', en: 'Beyond the Soviet model' },
                paragraphs: [
                    { ko: '제1차 5개년 계획은 성공했지만 마오는 그 모델 — 중공업 우선, 전문가 지배, 농촌의 잉여 추출 — 에 불만이 있었다. 1956년 「10대 관계론」과 1957년 「인민 내부 모순」 연설은 농업과 경공업, 지방의 주도권을 강조했다. 반우파 투쟁으로 비판 세력을 없앤 뒤 1957년 겨울 그는 수리 건설을 위한 농민 1억 명의 동원에서 대중 운동의 힘을 보았고, 11월 모스크바에서 「15년 안에 영국을 따라잡는다」고 선언했다.', en: 'The First Five-Year Plan had succeeded, but Mao was dissatisfied with its model — priority to heavy industry, rule by experts, extraction of the rural surplus. “On the Ten Major Relationships” (1956) and the “contradictions” speech of 1957 stressed agriculture, light industry and local initiative. With the critics removed by the Anti-Rightist Campaign, in the winter of 1957 he saw the power of mass movement in the mobilisation of a hundred million peasants for irrigation works, and in Moscow in November declared that China would “overtake Britain in fifteen years”.', sources: [W + 'Great_Leap_Forward', K + '%EB%8C%80%EC%95%BD%EC%A7%84_%EC%9A%B4%EB%8F%99'] },
                    { ko: '1958년 1~3월 난닝·청두 회의에서 마오는 1956년의 「반모진(反冒進)」— 무모한 전진에 반대 — 을 주장했던 저우언라이·천윈을 「우파에서 50미터 떨어진」 이들이라 몰아붙였고 저우는 자아비판을 했다. 5월 제8차 당대회 2차 회의는 총노선을 채택했다. 목표는 「두 다리로 걷기」— 현대적 공업과 토착 기술, 중앙과 지방, 도시와 농촌을 동시에 — 였고, 계획은 정치적 열의 앞에서 무의미해졌다.', en: 'At the Nanning and Chengdu conferences of January–March 1958 Mao attacked Zhou Enlai and Chen Yun, who had argued in 1956 against “rash advance”, as men “fifty metres from the rightists”, and Zhou made a self-criticism. In May the second session of the Eighth Congress adopted the general line. The aim was “walking on two legs” — modern industry and native methods, centre and localities, town and country all at once — and planning became meaningless before political zeal.', sources: [W + 'Great_Leap_Forward', W + 'Chen_Yun'] },
                ],
            },
            {
                heading: { ko: '1958년 여름: 인민공사와 강철', en: 'Summer 1958: communes and steel' },
                paragraphs: [
                    { ko: '허난과 허베이에서 합작사들이 통합되어 수천 가구의 「공사」가 생기자 마오는 8월 시찰에서 「인민공사는 좋다」고 말했고, 베이다이허 회의는 이를 전국에 확대했다. 연말까지 농가의 99%가 2만 6천여 개 인민공사에 편입되었다. 공사는 생산·행정·민병·교육을 하나로 묶었고 공동식당에서 「마음껏 먹는」 공급제, 사유 텃밭 폐지, 군대식 노동 편성이 시행되었다. 일부 지역은 「공산주의 진입」을 선언했다.', en: 'When cooperatives in Henan and Hebei merged into “communes” of thousands of households, Mao said on an inspection in August “people’s communes are good”, and the Beidaihe conference extended them nationwide; by the end of the year 99 per cent of households belonged to some 26,000 communes. The commune fused production, administration, militia and schooling; communal dining halls with “eat as much as you like” supply, the abolition of private plots and militarised labour organisation followed, and some areas declared they had “entered communism”.', sources: [W + 'People%27s_commune', W + 'Great_Leap_Forward'] },
                    { ko: '베이다이허 회의는 1958년 철강 목표를 1,070만 톤으로 두 배 올렸다. 목표를 채우기 위해 가을에 9천만 명이 뒷마당 용광로에서 철을 녹였고 농기구와 솥까지 녹여 넣었다. 생산된 「철」의 대부분은 쓸모없는 선철 덩어리였다. 같은 시기 「무당 만 근」의 수확을 보도한 「위성 밭」 경쟁은 통계를 허구로 만들었고, 노동력이 철강과 수리에 동원되는 동안 풍작의 상당 부분이 밭에서 썩었다.', en: 'Beidaihe doubled the 1958 steel target to 10.7 million tonnes. To meet it, ninety million people smelted iron in backyard furnaces that autumn, feeding in farm tools and cooking pots; most of the “steel” was useless pig iron. At the same time the competition of “sputnik fields” reporting ten thousand jin per mu turned statistics into fiction, and while labour was diverted to steel and irrigation a large part of a good harvest rotted in the fields.', sources: [W + 'Backyard_furnace', W + 'Great_Leap_Forward'] },
                ],
            },
            {
                heading: { ko: '기근의 기제', en: 'The mechanism of famine' },
                paragraphs: [
                    { ko: '1958년 곡물 생산은 실제 2억 톤이었으나 공식 발표는 3억 7,500만 톤이었고, 국가는 부풀려진 수치에 맞춰 징발량을 늘렸다. 1959년 실제 생산이 1억 7천만 톤으로 떨어졌음에도 징발률은 더 높아졌고 곡물 수출은 계속되었다. 지방 간부는 「은닉 곡물」을 찾는다며 농민을 구타했고 공동식당의 식량은 겨울이 되기 전에 바닥났다. 도시는 배급으로 보호되었고 농촌이 굶었다.', en: 'Actual grain output in 1958 was 200 million tonnes, but the official figure was 375 million, and the state raised procurement to match the inflated numbers. Although real output fell to 170 million tonnes in 1959 the procurement rate rose further and grain exports continued. Local cadres beat peasants in searches for “hidden grain”, and the dining halls’ stocks were exhausted before winter. The cities were protected by rationing; the countryside starved.', sources: [W + 'Great_Chinese_Famine', W + 'Yang_Jisheng_(journalist)'] },
                    { ko: '허난 신양 지구에서는 1959~1960년 100만 명 이상이 죽었고, 안후이·쓰촨·간쑤·구이저우가 가장 큰 피해를 입었다. 사망자 추정은 인구통계 방법에 따라 1,500만(중국 공식 추정)에서 3,600만(양지성), 4,500만(디쾨터)까지 갈리며, 원인 규명에서도 자연재해의 비중, 징발과 폭력의 역할, 마오와 지방 간부의 책임 배분이 논쟁이다. 확실한 것은 1960년 중국의 인구가 감소했다는 것이다.', en: 'In Xinyang prefecture, Henan, more than a million died in 1959–1960, and Anhui, Sichuan, Gansu and Guizhou suffered most. Estimates of the dead range with demographic method from fifteen million (China’s official estimate) to 36 million (Yang Jisheng) and 45 million (Dikötter), and the weight of natural disaster, the role of procurement and violence and the division of responsibility between Mao and local cadres are all disputed. What is certain is that China’s population fell in 1960.', sources: [W + 'Great_Chinese_Famine', W + 'Frank_Dik%C3%B6tter'] },
                ],
            },
            {
                heading: { ko: '루산: 비판이 반당이 되다', en: 'Lushan: criticism becomes treason' },
                paragraphs: [
                    { ko: '1959년 7월 장시 루산에서 열린 정치국 확대회의는 대약진의 과열을 조정하는 「신선회」로 시작했다. 후난에서 굶주림을 목격한 국방부장 펑더화이는 7월 14일 마오에게 사신을 보내 「소자산계급의 광열성」과 「정치가 경제를 대신한」 오류를 지적했다. 마오는 편지를 인쇄해 회의에 돌리고 7월 23일 연설에서 이를 우경의 공격으로 규정했으며, 자신이 물러나면 「농민을 이끌고 정부를 뒤엎겠다」고 위협했다.', en: 'The enlarged Politburo meeting at Lushan, Jiangxi, in July 1959 began as a “meeting of immortals” to cool the Leap. Peng Dehuai, the defence minister who had seen hunger in Hunan, wrote Mao a private letter on 14 July pointing to “petty-bourgeois fanaticism” and the error of “politics replacing economics”. Mao had the letter printed and circulated, and in his speech of 23 July branded it a rightist attack, threatening that if he were forced out he would “lead the peasants and overthrow the government”.', sources: [W + 'Lushan_Conference', M + 'volume-8/mswv8_34.htm'] },
                    { ko: '8중전회는 펑더화이·황커청·장원톈·저우샤오저우를 「반당집단」으로 규정했고 린뱌오가 국방부장이 되었다. 회의 뒤 전국의 「반우경」 운동은 조정을 요구한 간부 수백만 명을 조사했으며, 1959년 하반기 급진 정책이 되살아나 기근은 최악으로 치달았다. 루산은 대약진의 전환점이자 마오와 원로 사이 신뢰의 붕괴점이었고, 1965년 『해서파관』 비판이 이 사건의 은유로 읽힌 이유다.', en: 'The Eighth Plenum branded Peng Dehuai, Huang Kecheng, Zhang Wentian and Zhou Xiaozhou an “anti-party clique”, and Lin Biao became defence minister. The nationwide “anti-right-deviation” drive that followed investigated millions of cadres who had called for adjustment, radical policy revived in the second half of 1959 and the famine reached its worst. Lushan was the turning point of the Leap and the point where trust between Mao and the veterans broke — which is why the 1965 attack on Hai Rui Dismissed from Office was read as an allegory of the affair.', sources: [W + 'Lushan_Conference', W + 'Peng_Dehuai'] },
                ],
            },
            {
                heading: { ko: '후퇴: 12조에서 7천인 대회까지', en: 'Retreat: from the twelve articles to the Seven Thousand Cadres' },
                paragraphs: [
                    { ko: '1960년 여름 소련 전문가가 철수하고 신양의 참상이 중앙에 보고되자 정책이 바뀌기 시작했다. 11월 「12조」는 사유 텃밭과 농촌 시장, 생산대의 소유를 복원했고 1961년 「농업 60조」는 생산대를 기본 회계 단위로 삼아 공사를 축소했다. 캐나다·오스트레일리아에서 곡물을 수입했고 도시 인구 2천만 명을 농촌으로 돌려보냈다. 마오는 1961년 「조사 연구의 해」를 선언하며 한발 물러섰다.', en: 'In summer 1960, as the Soviet experts left and the horror of Xinyang was reported to the centre, policy began to change. The “twelve articles” of November restored private plots, rural markets and team ownership, and the “sixty articles on agriculture” of 1961 made the production team the basic accounting unit and shrank the commune. Grain was imported from Canada and Australia and twenty million urban residents were sent back to the countryside. Mao stepped back, declaring 1961 a “year of investigation and study”.', sources: [W + 'People%27s_commune', W + 'Great_Leap_Forward'] },
                    { ko: '1962년 1~2월 베이징의 7천인 대회에서 류사오치는 재난이 「3할은 천재, 7할은 인재」라고 말했고 마오는 이례적으로 자아비판을 했다. 그러나 마오의 자아비판은 「중앙의 책임은 내가 진다」는 형식이었고, 류사오치의 발언과 2월 시러우 회의에서 천윈이 제시한 「7·8년 회복」 전망, 그리고 안후이 등에서 확산되던 농가 청부제는 마오에게 「자본주의 부활」로 비쳤다. 9월 10중전회에서 그는 「계급투쟁을 잊지 말자」며 조정의 종료를 선언했다.', en: 'At the Seven Thousand Cadres Conference in Beijing in January–February 1962 Liu Shaoqi said the disaster was “three parts nature, seven parts man”, and Mao made an unusual self-criticism. But Mao’s self-criticism took the form “I take responsibility for the centre”, and Liu’s remark, Chen Yun’s forecast at the Xilou meeting in February of “seven or eight years” of recovery, and the household contracting spreading from Anhui looked to Mao like a “restoration of capitalism”. At the Tenth Plenum in September he declared the retreat over: “never forget class struggle”.', sources: [W + 'Seven_Thousand_Cadres_Conference', W + 'Liu_Shaoqi'] },
                ],
            },
            {
                heading: { ko: '기억과 역사학', en: 'Memory and historiography' },
                paragraphs: [
                    { ko: '중국에서 대기근은 오랫동안 「3년 자연재해」 또는 「3년 곤란 시기」로 불렸고 1981년 「역사결의」는 대약진을 「좌경 오류」로 규정하되 사망자를 언급하지 않았다. 1980년대 인구조사 자료가 공개되면서 서구 인구학자들이 초과 사망을 추산했고, 2008년 신화사 기자 양지성의 『묘비』는 지방 당안과 증언으로 3,600만이라는 수치를 제시했다. 이 책은 대륙에서 금서다.', en: 'In China the famine was long called the “three years of natural disasters” or the “three difficult years”, and the 1981 Resolution on History classed the Leap as a “leftist error” without mentioning the dead. When census data were released in the 1980s Western demographers estimated the excess deaths, and in 2008 the Xinhua journalist Yang Jisheng’s Tombstone, built from local archives and testimony, put the figure at 36 million; the book is banned on the mainland.', sources: [W + 'Yang_Jisheng_(journalist)', W + 'Great_Chinese_Famine'] },
                    { ko: '해석은 갈린다. 디쾨터는 기근을 국가 폭력의 결과로 보아 마오의 책임을 강조하고, 다른 연구자들은 정보의 왜곡과 지방 간부의 경쟁, 소련 부채 상환과 수출이라는 구조를 지적한다. 아마르티아 센은 언론과 반대당이 없는 체제에서 기근이 확인되지 못한 것을 지적했다. 대약진은 이후 「대중 동원」의 한계와 계획경제에서 정보의 문제를 논하는 사례가 되었고, 개혁기 지도부의 농가 청부제 수용은 이 경험에서 나왔다.', en: 'Interpretations diverge. Dikötter sees the famine as the product of state violence and stresses Mao’s responsibility; other scholars point to the structure of distorted information, competition among local cadres, and exports to repay Soviet debt. Amartya Sen noted that in a system without a free press or opposition the famine went unacknowledged. The Leap became a case study in the limits of “mass mobilisation” and the problem of information in planned economies, and the reform leadership’s acceptance of household contracting grew out of this experience.', sources: [W + 'Frank_Dik%C3%B6tter', W + 'Household_responsibility_system'] },
                ],
            },
        ],
        people: [
            { id: 'mao-zedong', kind: 'leader', relation: { ko: '대약진의 발의자', en: 'Initiator of the Great Leap' }, note: { ko: '인민공사와 철강 목표를 밀어붙였고 루산에서 펑더화이를 숙청했으며 1962년 조정을 끝냈다.', en: 'Drove the communes and steel targets, purged Peng Dehuai at Lushan and ended the retreat in 1962.' } },
            { id: 'peng-dehuai', kind: 'opponent', relation: { ko: '루산에서 대약진을 비판한 국방부장', en: 'Defence minister who criticised the Leap at Lushan' }, note: { ko: '1959년 7월 마오에게 보낸 편지로 「반당집단」의 수괴로 몰려 실각했다.', en: 'His July 1959 letter to Mao made him head of an “anti-party clique” and cost him his post.' } },
            { id: 'zhang-wentian', kind: 'opponent', relation: { ko: '루산에서 펑더화이를 지지한 외교부 부부장', en: 'Vice-foreign minister who backed Peng at Lushan' }, note: { ko: '대약진의 경제적 오류를 지적하는 연설로 반당집단에 포함되었다.', en: 'A speech on the Leap’s economic errors put him in the anti-party clique.' } },
            { id: 'liu-shaoqi', kind: 'executor', relation: { ko: '대약진의 집행자에서 조정의 지도자로', en: 'From executor of the Leap to leader of the retreat' }, note: { ko: '1958년 운동을 지지했고 1962년 「7할은 인재」라 말해 마오와 갈라졌다.', en: 'Backed the Leap in 1958 and broke with Mao in 1962 with “seven parts man-made”.' } },
            { id: 'deng-xiaoping', kind: 'executor', relation: { ko: '총서기, 조정 정책의 집행', en: 'General secretary implementing the adjustment' }, note: { ko: '「검은 고양이든 흰 고양이든」 발언으로 농가 청부제를 옹호했다.', en: 'Defended household contracting with “black cat or white cat”.' } },
            { id: 'chen-yun', kind: 'executor', relation: { ko: '조정 정책의 설계자', en: 'Architect of the adjustment' }, note: { ko: '1956년 반모진을 주장했다 비판받았고 1961~1962년 회복 정책을 세웠다.', en: 'Criticised for opposing rash advance in 1956, designed the recovery policy of 1961–1962.' } },
            { id: 'zhou-enlai', kind: 'participant', relation: { ko: '1958년 자아비판한 총리', en: 'Premier who made a self-criticism in 1958' }, note: { ko: '반모진으로 비판받은 뒤 대약진을 집행했고 기근 시 곡물 수입을 조직했다.', en: 'Criticised for opposing rash advance, executed the Leap and organised grain imports during the famine.' } },
            { id: 'lin-biao', kind: 'participant', relation: { ko: '펑더화이를 대신한 국방부장', en: 'Replaced Peng Dehuai as defence minister' }, note: { ko: '루산 뒤 군을 맡아 마오 숭배를 군에 도입했다.', en: 'Took over the army after Lushan and brought the Mao cult into it.' } },
            { id: 'chen-boda', kind: 'executor', relation: { ko: '대약진의 이론가', en: 'Theorist of the Leap' }, note: { ko: '『홍기』에서 인민공사와 「공산주의로의 이행」을 이론화했다.', en: 'Theorised the communes and the “transition to communism” in Red Flag.' } },
            { id: 'chen-yonggui', kind: 'participant', relation: { ko: '다자이 모델의 지도자', en: 'Leader of the Dazhai model' }, note: { ko: '1964년 이후 「농업은 다자이를 배우자」의 모델이 되었다.', en: 'Became the model of “learn from Dazhai” after 1964.' } },
            { id: 'khrushchev', kind: 'opponent', relation: { ko: '인민공사를 비판하고 전문가를 철수', en: 'Criticised the communes and withdrew the experts' }, note: { ko: '1960년 7월 소련 기술자 철수로 공업 계획이 중단되었다.', en: 'His withdrawal of Soviet technicians in July 1960 halted industrial projects.' } },
            { id: 'yang-jisheng', kind: 'witness', relation: { ko: '『묘비』의 저자', en: 'Author of Tombstone' }, note: { ko: '지방 당안과 증언으로 사망자 3,600만을 추산했다.', en: 'Estimated 36 million deaths from local archives and testimony.' } },
            { id: 'frank-dikotter', kind: 'witness', relation: { ko: '『마오의 대기근』의 저자', en: 'Author of Mao’s Great Famine' }, note: { ko: '4,500만 사망을 추산하고 기근을 국가 폭력으로 해석했다.', en: 'Estimated 45 million deaths and read the famine as state violence.' } },
        ],
        related: ['hundred-flowers-anti-rightist', 'sino-soviet-split', 'cultural-revolution'],
    },
    {
        id: 'cultural-revolution', sortOrder: 265, period: '1966–1976', countries: ['china', 'soviet', 'usa'],
        title: { ko: '문화대혁명', en: 'The Cultural Revolution' },
        question: { ko: '마오는 왜 자기 당을 파괴하려 했고, 그 10년은 누구에게 무엇을 남겼는가?', en: 'Why did Mao set out to destroy his own party, and what did the ten years leave behind for whom?' },
        summary: { ko: '대약진의 실패로 밀려난 마오는 1966년 「자본주의의 길을 걷는 당권파」를 치자며 학생 홍위병을 동원해 류사오치·덩샤오핑과 당 조직을 무너뜨렸다. 1967년 파벌 무장 충돌 뒤 군이 질서를 회복했고, 1971년 후계자 린뱌오의 죽음은 운동의 명분을 흔들었다. 1972년 닉슨 방중과 1976년 저우언라이·마오의 죽음, 4인방 체포로 10년이 끝났다.', en: 'Sidelined after the failure of the Great Leap, Mao in 1966 mobilised student Red Guards against “those in authority taking the capitalist road”, toppling Liu Shaoqi, Deng Xiaoping and the party apparatus. After the armed factional fighting of 1967 the army restored order, and the death of the designated successor Lin Biao in 1971 shook the movement’s credibility. Nixon’s visit in 1972 and the deaths of Zhou Enlai and Mao in 1976, followed by the arrest of the Gang of Four, ended the decade.' },
        outcome: { ko: '수십만~수백만 명이 죽고 교육과 문화가 파괴되었으며 당·국가 기구는 군과 혁명위원회로 대체되었다가 재건되었다. 1981년 「역사결의」는 문화대혁명을 「당·국가·인민에게 가장 심각한 좌절과 손실」로 규정했고, 이 경험이 덩샤오핑 개혁의 정치적 출발점이 되었다.', en: 'Hundreds of thousands to millions died, education and culture were wrecked, and the party-state apparatus was replaced by the army and revolutionary committees before being rebuilt. The 1981 Resolution on History called the Cultural Revolution “the most severe setback and the heaviest losses suffered by the party, the state and the people”, and that experience was the political starting point of Deng Xiaoping’s reforms.' },
        locations: [
            { lat: 39.91, lng: 116.40, label: { ko: '베이징 톈안먼', en: 'Tiananmen, Beijing' } },
            { lat: 31.23, lng: 121.47, label: { ko: '상하이', en: 'Shanghai' } },
            { lat: 30.59, lng: 114.30, label: { ko: '우한', en: 'Wuhan' } },
            { lat: 29.56, lng: 106.55, label: { ko: '충칭', en: 'Chongqing' } },
            { lat: 47.32, lng: 110.66, label: { ko: '운두르한 (몽골)', en: 'Öndörkhaan (Mongolia)' } },
            { lat: 39.63, lng: 118.18, label: { ko: '탕산', en: 'Tangshan' } },
        ],
        timeline: [
            { date: '1965.11.10', title: { ko: '야오원위안의 『해서파관』 비판', en: 'Yao Wenyuan attacks Hai Rui Dismissed from Office' }, body: { ko: '상하이 『문회보』의 비판문이 베이징의 펑전 그룹을 겨냥한 신호탄이었다.', en: 'The Shanghai Wenhui Bao article was the opening shot aimed at Peng Zhen’s group in Beijing.' }, geo: { kind: 'point', lat: 31.23, lng: 121.47, label: { ko: '상하이', en: 'Shanghai' } } },
            { date: '1966.05.16', title: { ko: '「5·16 통지」', en: 'The May 16 Notification' }, body: { ko: '정치국 확대회의가 펑전을 실각시키고 중앙문화혁명소조를 세워 「당권파」 타도를 선언했다.', en: 'An enlarged Politburo meeting removed Peng Zhen, created the Central Cultural Revolution Group and declared war on “those in authority”.' } },
            { date: '1966.08.05', title: { ko: '마오의 「사령부를 포격하라」', en: 'Mao’s “Bombard the Headquarters”' }, body: { ko: '마오의 대자보가 류사오치를 겨냥했고 11중전회는 린뱌오를 2인자로 올렸다.', en: 'Mao’s big-character poster targeted Liu Shaoqi; the Eleventh Plenum made Lin Biao second in command.' } },
            { date: '1966.08.18', title: { ko: '톈안먼의 홍위병 접견', en: 'Red Guards received at Tiananmen' }, body: { ko: '마오가 100만 홍위병을 접견했다. 「붉은 8월」 베이징에서만 1,772명이 맞아 죽었다.', en: 'Mao received a million Red Guards; in Beijing’s “Red August” 1,772 people were beaten to death.' }, geo: { kind: 'point', lat: 39.91, lng: 116.40, label: { ko: '톈안먼', en: 'Tiananmen' } } },
            { date: '1967.01', title: { ko: '상하이 「1월 폭풍」', en: 'Shanghai’s “January Storm”' }, body: { ko: '노동자 반란파가 상하이 시정부를 접수해 「탈권」의 모델이 되었다.', en: 'Worker rebels seized the Shanghai government, the model for “power seizures” nationwide.' }, geo: { kind: 'point', lat: 31.23, lng: 121.47, label: { ko: '상하이', en: 'Shanghai' } } },
            { date: '1967.02', title: { ko: '「2월 역류」', en: 'The “February Countercurrent”' }, body: { ko: '예젠잉·천이 등 원로들이 문혁소조에 항의했다가 비판받았다.', en: 'Ye Jianying, Chen Yi and other veterans protested against the Cultural Revolution Group and were rebuked.' } },
            { date: '1967.07', title: { ko: '우한 사건', en: 'The Wuhan incident' }, body: { ko: '우한 군구가 중앙 특사를 감금해 군의 이반 위기가 일어났다. 전국의 무장 충돌이 절정에 달했다.', en: 'The Wuhan military region detained the centre’s envoys, a crisis of army loyalty; armed factional fighting peaked across the country.' }, geo: { kind: 'point', lat: 30.59, lng: 114.30, label: { ko: '우한', en: 'Wuhan' } } },
            { date: '1968.07–12', title: { ko: '홍위병 해산과 상산하향', en: 'Red Guards disbanded; youth sent down' }, body: { ko: '노동자·군 선전대가 학교를 접수했고 12월 「지식청년은 농촌으로」 지시가 내려졌다.', en: 'Worker and army propaganda teams took over the schools; in December came the order sending educated youth to the countryside.' } },
            { date: '1968.10', title: { ko: '류사오치 제명', en: 'Liu Shaoqi expelled' }, body: { ko: '12중전회가 류사오치를 「반역자·내부 간첩·노동자의 배신자」로 영구 제명했다. 그는 1969년 11월 카이펑에서 옥사했다.', en: 'The Twelfth Plenum expelled Liu as a “renegade, traitor and scab”; he died in custody at Kaifeng in November 1969.' }, geo: { kind: 'point', lat: 34.80, lng: 114.31, label: { ko: '카이펑', en: 'Kaifeng' } } },
            { date: '1969.03', title: { ko: '전바오섬 충돌', en: 'Zhenbao Island clashes' }, body: { ko: '우수리강에서 중소 국경 전투가 벌어져 소련과의 전쟁 공포가 커졌다.', en: 'Sino-Soviet border battles on the Ussuri raised fears of war with the Soviet Union.' }, country: ['china', 'soviet'], geo: { kind: 'point', lat: 46.48, lng: 133.84, label: { ko: '전바오섬', en: 'Zhenbao Island' } } },
            { date: '1969.04', title: { ko: '제9차 당대회', en: 'The Ninth Congress' }, body: { ko: '린뱌오가 당 규약에 후계자로 명시되었고 중앙위원의 다수가 군인이었다.', en: 'Lin Biao was named successor in the party constitution; a majority of the Central Committee were soldiers.' } },
            { date: '1971.09.13', title: { ko: '린뱌오 사건', en: 'The Lin Biao incident' }, body: { ko: '린뱌오 일가가 탄 비행기가 몽골에서 추락했다. 당은 그가 쿠데타를 꾀했다고 발표했다.', en: 'The aircraft carrying Lin Biao and his family crashed in Mongolia; the party announced that he had plotted a coup.' }, geo: { kind: 'point', lat: 47.32, lng: 110.66, label: { ko: '운두르한', en: 'Öndörkhaan' } } },
            { date: '1972.02', title: { ko: '닉슨 방중', en: 'Nixon in China' }, body: { ko: '상하이 공동성명으로 미중 화해가 시작되었다.', en: 'The Shanghai Communiqué began Sino-American rapprochement.' }, country: ['china', 'usa'], geo: { kind: 'point', lat: 39.90, lng: 116.40, label: { ko: '베이징', en: 'Beijing' } } },
            { date: '1976.01–04', title: { ko: '저우언라이 사망과 4·5 톈안먼 사건', en: 'Zhou Enlai’s death and the April Fifth incident' }, body: { ko: '청명절 추모 집회가 진압되었고 덩샤오핑이 다시 실각했다.', en: 'Mourning gatherings at Qingming were suppressed and Deng Xiaoping fell again.' }, geo: { kind: 'point', lat: 39.91, lng: 116.40, label: { ko: '톈안먼', en: 'Tiananmen' } } },
            { date: '1976.09.09', title: { ko: '마오쩌둥 사망', en: 'Death of Mao Zedong' }, body: { ko: '7월 탕산 대지진 두 달 뒤 마오가 죽었다. 10월 6일 4인방이 체포되었다.', en: 'Mao died two months after the Tangshan earthquake; on 6 October the Gang of Four were arrested.' }, geo: { kind: 'point', lat: 39.90, lng: 116.40, label: { ko: '베이징', en: 'Beijing' } } },
        ],
        sections: [
            {
                heading: { ko: '기원: 대약진 이후의 두 노선', en: 'Origins: two lines after the Great Leap' },
                paragraphs: [
                    { ko: '1962년 이후 마오는 「일선」에서 물러나 류사오치·덩샤오핑이 일상 업무를 맡았고, 조정 정책이 경제를 회복시켰다. 마오는 이를 「수정주의」와 「자본주의 부활」로 보았다. 사회주의 교육운동(1963~1966)에서 류사오치의 공작대 방식과 마오의 「당권파」 규정이 충돌했고, 1965년 「23조」는 표적을 「당내 자본주의의 길을 걷는 당권파」로 옮겼다. 중소 논쟁에서 소련을 「수정주의」로 규정한 논리가 국내로 향한 것이다.', en: 'After 1962 Mao withdrew to the “second line” while Liu Shaoqi and Deng Xiaoping ran daily affairs, and the adjustment policies restored the economy. Mao saw this as “revisionism” and “restoration of capitalism”. In the Socialist Education Movement (1963–1966) Liu’s work-team methods clashed with Mao’s definition of “those in authority”, and the “twenty-three articles” of 1965 shifted the target to “those in authority within the party taking the capitalist road” — the logic that had branded the Soviet Union revisionist in the Sino-Soviet polemics turned inward.', sources: [W + 'Socialist_Education_Movement', W + 'Cultural_Revolution'] },
                    { ko: '마오의 무기는 세 가지였다. 린뱌오가 군에 도입한 마오 숭배와 『마오 주석 어록』, 장칭·캉성·천보다의 문화·이론 그룹, 그리고 당 기구 밖의 대중 동원이었다. 1965년 11월 야오원위안의 『해서파관』 비판은 베이징 시장 펑전과 「베이징 독립왕국」을 겨냥했고, 1966년 5월 「5·16 통지」는 펑전·뤄루이칭·루딩이·양상쿤을 실각시키며 「부르주아 대표 인물」이 당·정·군·문화계에 잠입했다고 선언했다.', en: 'Mao had three weapons: the Mao cult and the Little Red Book that Lin Biao had introduced into the army; the culture-and-theory group of Jiang Qing, Kang Sheng and Chen Boda; and mass mobilisation outside the party apparatus. Yao Wenyuan’s attack on Hai Rui Dismissed from Office in November 1965 targeted the Beijing mayor Peng Zhen and his “independent kingdom”, and the May 16 Notification of 1966 removed Peng, Luo Ruiqing, Lu Dingyi and Yang Shangkun, declaring that “representatives of the bourgeoisie” had infiltrated the party, state, army and culture.', sources: [W + 'Wu_Han_(historian)', W + 'Cultural_Revolution'] },
                ],
            },
            {
                heading: { ko: '1966년 여름: 홍위병', en: 'Summer 1966: the Red Guards' },
                paragraphs: [
                    { ko: '5월 25일 베이징대학의 대자보를 마오가 「전국 최초의 마르크스-레닌주의 대자보」로 승인하면서 학생 운동이 폭발했다. 류사오치가 보낸 공작대가 질서 회복을 시도하자 마오는 8월 5일 「사령부를 포격하라」는 자신의 대자보로 이를 「부르주아 독재」라 비난했다. 11중전회는 「16조」로 문화대혁명을 공식화하고 린뱌오를 유일한 부주석으로 올렸으며, 류사오치는 서열 8위로 떨어졌다.', en: 'When Mao endorsed a Peking University poster of 25 May as “the first Marxist-Leninist big-character poster in the country”, the student movement exploded. The work teams Liu Shaoqi sent to restore order were denounced in Mao’s own poster of 5 August, “Bombard the Headquarters”, as a “bourgeois dictatorship”. The Eleventh Plenum formalised the Cultural Revolution in the “sixteen points”, made Lin Biao sole vice-chairman and dropped Liu to eighth in rank.', sources: [W + 'Cultural_Revolution', W + 'Liu_Shaoqi'] },
                    { ko: '8월 18일 마오는 톈안먼에서 홍위병 100만 명을 접견했고 이후 11월까지 여덟 차례 접견에 1,100만 명이 모였다. 「4구 타파」의 이름으로 홍위병은 가택을 수색하고 문화재를 파괴했으며 교사와 「출신 나쁜」 이들을 구타했다. 베이징에서만 8~9월에 1,772명이 맞아 죽었고, 「혈통론」을 내건 간부 자녀의 노홍위병이 첫 단계를 주도했다. 12월 이후 「반란파」가 등장해 당 조직 자체를 공격했다.', en: 'On 18 August Mao received a million Red Guards at Tiananmen, and eleven million attended eight receptions through November. In the name of “destroying the Four Olds” Red Guards ransacked homes, destroyed cultural relics and beat teachers and people of “bad class origin”; in Beijing alone 1,772 were beaten to death in August and September. The “old Red Guards” of cadre children, preaching the “bloodline theory”, led the first phase; from December “rebel” groups emerged and attacked the party organisation itself.', sources: [W + 'Red_Guards', W + 'Red_August'] },
                ],
            },
            {
                heading: { ko: '1967년: 탈권과 무장 충돌', en: '1967: power seizures and armed struggle' },
                paragraphs: [
                    { ko: '1967년 1월 상하이의 노동자 반란파(왕훙원)가 장춘차오·야오원위안의 지도로 시정부를 접수했고 마오는 이를 「1월 폭풍」으로 승인했다. 전국에서 「탈권」이 뒤따랐으나 파벌들은 누가 진정한 반란파인지를 놓고 싸웠다. 2월 예젠잉·천이·탄전린 등 원로들이 문혁소조에 항의한 「2월 역류」는 마오의 질책으로 끝났고, 정치국은 사실상 기능을 멈췄다.', en: 'In January 1967 Shanghai’s worker rebels (Wang Hongwen), guided by Zhang Chunqiao and Yao Wenyuan, seized the municipal government, and Mao endorsed it as the “January Storm”. “Power seizures” followed across the country, but factions fought over who were the true rebels. In February the protest of veterans — Ye Jianying, Chen Yi, Tan Zhenlin — against the Cultural Revolution Group, the “February Countercurrent”, ended in Mao’s rebuke, and the Politburo effectively ceased to function.', sources: [W + 'Wang_Hongwen', W + 'Cultural_Revolution'] },
                    { ko: '군은 「좌파 지원」을 명령받았으나 어느 파벌이 좌파인지 알 수 없었다. 7월 우한 군구 사령관 천짜이다오가 반란파를 지원하러 온 중앙 특사를 감금한 우한 사건은 군의 이반 위기였고, 마오는 우한을 급히 떠났다. 여름 내내 충칭·창사 등에서 총과 대포가 동원된 파벌 전투가 벌어졌으며, 광시에서는 학살과 식인 사례까지 보고되었다. 1968년 여름 마오는 노동자·군 선전대로 학교를 접수하고 홍위병을 해산시켰다.', en: 'The army was ordered to “support the left” but could not tell which faction the left was. In July the Wuhan incident, in which the regional commander Chen Zaidao detained the centre’s envoys sent to back the rebels, was a crisis of army loyalty, and Mao left Wuhan in haste. All summer factions fought with guns and artillery in Chongqing, Changsha and elsewhere, and in Guangxi massacres and even cannibalism were reported. In summer 1968 Mao sent worker and army propaganda teams into the schools and disbanded the Red Guards.', sources: [W + 'Wuhan_incident', W + 'Guangxi_Massacre'] },
                ],
            },
            {
                heading: { ko: '희생자: 류사오치에서 이름 없는 이들까지', en: 'The victims: from Liu Shaoqi to the nameless' },
                paragraphs: [
                    { ko: '류사오치는 1967년 중난하이에서 비판 집회에 끌려 나갔고 1968년 10월 「반역자·내부 간첩·노동자의 배신자」로 영구 제명되어 1969년 11월 카이펑에서 옥사했다. 펑더화이·허룽·타오주가 박해 속에 죽었고, 덩샤오핑은 장시의 트랙터 공장으로 보내졌다. 「청리 계급대오」(1968~1969)와 「1타3반」(1970) 운동은 지방에서 수십만 명을 처형·박해했으며, 캉성이 조사한 「61인 반도 사건」과 「내몽골 인민당 사건」 같은 조작 사건이 이어졌다.', en: 'Liu Shaoqi was dragged to struggle sessions inside Zhongnanhai in 1967, expelled for life in October 1968 as a “renegade, traitor and scab”, and died in custody at Kaifeng in November 1969. Peng Dehuai, He Long and Tao Zhu died under persecution; Deng Xiaoping was sent to a tractor factory in Jiangxi. The “cleansing of the class ranks” (1968–1969) and “one strike, three antis” (1970) campaigns executed and persecuted hundreds of thousands in the provinces, and fabricated cases investigated by Kang Sheng — the “61 renegades”, the “Inner Mongolian People’s Party” — followed.', sources: [W + 'Liu_Shaoqi', W + 'Kang_Sheng'] },
                    { ko: '1968년 12월 「지식청년은 농촌으로」 지시로 1,700만 명이 하방되었고 대학은 1970년까지 신입생을 받지 않았다. 사망자는 추정 범위가 넓어 50만에서 200만 이상까지 제시되며, 박해받은 사람은 1억 명이라는 예젠잉의 1978년 발언이 있다. 지식인·교사·의사, 「지·부·반·괴·우」의 가족, 소수민족과 종교인이 특히 큰 피해를 입었다. 티베트의 사원과 전국의 문화재가 파괴되었다.', en: 'The December 1968 order sending educated youth to the countryside moved seventeen million people, and the universities admitted no new students until 1970. Estimates of the dead range widely, from half a million to more than two million, and Ye Jianying said in 1978 that a hundred million had been persecuted. Intellectuals, teachers and doctors, the families of the “five black categories”, ethnic minorities and religious believers suffered most; Tibet’s monasteries and cultural relics throughout the country were destroyed.', sources: [W + 'Down_to_the_Countryside_Movement', W + 'Cultural_Revolution'] },
                ],
            },
            {
                heading: { ko: '린뱌오의 죽음과 닉슨의 방문', en: 'The death of Lin Biao and the visit of Nixon' },
                paragraphs: [
                    { ko: '1969년 제9차 당대회는 린뱌오를 당 규약에 후계자로 명시했고 군은 혁명위원회를 통해 지방을 통치했다. 그러나 1970년 루산 회의에서 국가주석직 설치를 둘러싸고 마오와 린뱌오·천보다가 충돌했고, 마오는 천보다를 실각시키며 린뱌오를 압박했다. 1971년 9월 13일 린뱌오와 아내 예췬·아들 린리궈가 탄 트라이던트기가 몽골 운두르한에 추락했다. 당은 린뱌오가 마오 암살 쿠데타(「571 공정」)를 꾀하다 도주했다고 발표했다.', en: 'The Ninth Congress of 1969 wrote Lin Biao into the party constitution as successor, and the army ruled the provinces through revolutionary committees. But at the Lushan plenum of 1970 Mao clashed with Lin Biao and Chen Boda over restoring the state chairmanship, removed Chen and turned the pressure on Lin. On 13 September 1971 the Trident carrying Lin Biao, his wife Ye Qun and son Lin Liguo crashed at Öndörkhaan in Mongolia. The party announced that Lin had fled after plotting to assassinate Mao (“Project 571”).', sources: [W + 'Lin_Biao_incident', W + 'Chen_Boda'] },
                    { ko: '「가장 가까운 전우」의 배신은 마오 숭배와 문화대혁명의 명분을 안에서 무너뜨렸다. 마오는 저우언라이에게 정상화를 맡겼고 1973년 덩샤오핑이 복귀했다. 대외적으로는 1969년 전바오섬 충돌 이후 소련의 위협이 미국과의 화해를 재촉했다. 1971년 키신저의 비밀 방문, 10월 유엔 의석 회복, 1972년 2월 닉슨의 방중과 상하이 공동성명은 냉전의 지형을 바꾸었다. 문화대혁명의 「반제·반수」 구호 아래 중국은 미국과 손잡았다.', en: 'The treachery of the “closest comrade-in-arms” undermined the Mao cult and the Cultural Revolution’s rationale from within. Mao gave Zhou Enlai the task of normalisation and Deng Xiaoping returned in 1973. Abroad, the Soviet threat after the Zhenbao Island clashes of 1969 hastened rapprochement with the United States: Kissinger’s secret visit in 1971, the recovery of the UN seat in October, and Nixon’s visit and the Shanghai Communiqué of February 1972 redrew the map of the Cold War. Under the slogans of “anti-imperialism, anti-revisionism” China joined hands with America.', sources: ['https://history.state.gov/milestones/1969-1976/rapprochement-china', W + '1972_visit_by_Richard_Nixon_to_China'] },
                ],
            },
            {
                heading: { ko: '1976년: 세 사람의 죽음과 4인방의 체포', en: '1976: three deaths and the arrest of the Gang of Four' },
                paragraphs: [
                    { ko: '1974년 「린뱌오와 공자를 비판」 운동은 저우언라이를 겨냥했고, 1975년 덩샤오핑의 「정돈」이 성과를 내자 4인방은 「우경 번안풍 반격」으로 그를 다시 공격했다. 1976년 1월 저우언라이가 죽자 4월 청명절 톈안먼 광장에 100만 명이 추모 화환과 시를 바쳤고, 당국은 이를 「반혁명 사건」으로 진압한 뒤 덩샤오핑을 다시 실각시키고 화궈펑을 제1부주석으로 삼았다.', en: 'The 1974 campaign to “criticise Lin Biao and Confucius” was aimed at Zhou Enlai, and when Deng Xiaoping’s “consolidation” of 1975 showed results the Gang of Four attacked him again through the campaign to “beat back the right-deviationist reversal of verdicts”. After Zhou died in January 1976, a million people brought wreaths and poems to Tiananmen Square at Qingming in April; the authorities suppressed it as a “counter-revolutionary incident”, removed Deng again and made Hua Guofeng first vice-chairman.', sources: [W + '1976_Tiananmen_incident', W + 'Criticize_Lin,_Criticize_Confucius'] },
                    { ko: '7월 주더가 죽고 7월 28일 탕산 대지진이 24만 명을 앗아갔으며 9월 9일 마오가 죽었다. 예젠잉·리셴녠은 화궈펑을 설득했고 10월 6일 왕둥싱의 8341부대가 중난하이에서 장춘차오·왕훙원·야오원위안을, 이어 장칭을 체포했다. 화궈펑은 당 주석이 되었고 「문화대혁명의 승리적 종결」이 선언되었다. 1980~1981년 특별법정은 4인방과 린뱌오 그룹에 문화대혁명의 죄를 물었고, 1981년 「역사결의」는 마오가 「발동하고 이끈」 운동의 오류를 인정하되 그의 「공이 과보다 크다」고 결론지었다.', en: 'Zhu De died in July, the Tangshan earthquake of 28 July killed 240,000, and Mao died on 9 September. Ye Jianying and Li Xiannian persuaded Hua Guofeng, and on 6 October Wang Dongxing’s Unit 8341 arrested Zhang Chunqiao, Wang Hongwen and Yao Wenyuan at Zhongnanhai, then Jiang Qing. Hua became party chairman and the “victorious conclusion” of the Cultural Revolution was proclaimed. The special court of 1980–1981 tried the Gang of Four and the Lin Biao group for the crimes of the decade, and the 1981 Resolution on History acknowledged the errors of a movement Mao had “launched and led” while concluding that his merits outweighed his faults.', sources: [W + 'Gang_of_Four', W + 'Resolution_on_Certain_Questions_in_the_History_of_Our_Party_since_the_Founding_of_the_People%27s_Republic_of_China'] },
                ],
            },
            {
                heading: { ko: '해석: 이념, 권력, 사회', en: 'Interpretations: ideology, power, society' },
                paragraphs: [
                    { ko: '문화대혁명을 무엇으로 볼지는 여전히 논쟁이다. 마오의 이념 — 관료화한 당을 대중이 감시하고 「계속혁명」으로 수정주의를 막는다 — 을 진지하게 보는 해석, 대약진 실패 뒤 권력을 되찾으려는 권력투쟁으로 보는 해석(맥파쿼·쇤할스), 그리고 당 국가 아래 쌓인 사회적 불만 — 출신 성분 차별, 임시공, 하방 청년 — 이 마오의 호출을 계기로 분출한 사회적 갈등으로 보는 해석이 경쟁한다.', en: 'What the Cultural Revolution was remains disputed: interpretations that take Mao’s ideology seriously — the masses supervising a bureaucratised party, “continuous revolution” against revisionism — compete with those that read it as a power struggle to recover the authority lost after the Great Leap (MacFarquhar and Schoenhals), and with those that see the eruption, on Mao’s summons, of social grievances accumulated under the party-state: class-origin discrimination, temporary workers, sent-down youth.', sources: [W + 'Roderick_MacFarquhar', W + 'Cultural_Revolution'] },
                    { ko: '공식 역사는 문화대혁명을 「10년 동란」으로 규정하되 그 원인을 마오의 오류와 린뱌오·4인방의 「이용」으로 한정하고, 당의 지도 원칙과 마오쩌둥 사상은 지켰다. 이 틀은 1989년 이후 더 굳어져 2021년 「역사결의」는 문화대혁명 서술을 줄였다. 1980년대의 「상흔문학」과 회고록, 홍콩·해외의 연구가 기억을 이어 가지만 대륙에서 체계적 연구와 추모는 제한되어 있다. 한 세대 전체의 교육 공백과 「홍위병 세대」의 경험은 개혁기 중국 정치의 밑바닥에 남았다.', en: 'Official history classes the Cultural Revolution as “ten years of turmoil” but confines its causes to Mao’s errors and their “exploitation” by Lin Biao and the Gang of Four, preserving the party’s leading role and Mao Zedong Thought. The frame hardened after 1989, and the 2021 Resolution on History shortened the account further. The “scar literature” and memoirs of the 1980s and scholarship in Hong Kong and abroad keep memory alive, but systematic research and commemoration remain restricted on the mainland. The lost schooling of a whole generation and the experience of the “Red Guard generation” lie beneath the politics of reform-era China.', sources: [W + 'Cultural_Revolution', K + '%EB%AC%B8%ED%99%94_%EB%8C%80%ED%98%81%EB%AA%85'] },
                ],
            },
        ],
        people: [
            { id: 'mao-zedong', kind: 'leader', relation: { ko: '문화대혁명을 「발동하고 이끈」 주석', en: 'The chairman who “launched and led” the Cultural Revolution' }, note: { ko: '홍위병을 동원해 류사오치와 당 기구를 무너뜨렸고 1976년 9월 사망했다.', en: 'Mobilised the Red Guards against Liu Shaoqi and the apparatus; died in September 1976.' } },
            { id: 'liu-shaoqi', kind: 'target', relation: { ko: '「중국의 흐루쇼프」로 몰린 국가주석', en: 'State chairman branded “China’s Khrushchev”' }, note: { ko: '1968년 제명되어 1969년 카이펑에서 옥사했다.', en: 'Expelled in 1968, died in custody at Kaifeng in 1969.' } },
            { id: 'lin-biao', kind: 'executor', relation: { ko: '마오 숭배를 만든 후계자, 1971년 추락사', en: 'Successor who built the Mao cult, killed in the 1971 crash' }, note: { ko: '군을 통해 문화대혁명을 뒷받침했고 1971년 9월 몽골에서 죽었다.', en: 'Backed the Cultural Revolution through the army; died in Mongolia in September 1971.' } },
            { id: 'jiang-qing', kind: 'executor', relation: { ko: '중앙문혁소조 부조장 · 4인방의 수장', en: 'Deputy head of the Cultural Revolution Group and leader of the Gang of Four' }, note: { ko: '문예를 장악했고 1976년 10월 체포되었다.', en: 'Controlled the arts; arrested in October 1976.' } },
            { id: 'kang-sheng', kind: 'executor', relation: { ko: '문혁소조 고문, 조작 사건의 조사자', en: 'Adviser to the Group and investigator of fabricated cases' }, note: { ko: '류사오치·허룽 등에 대한 「전안(專案)」 조사를 주도했다.', en: 'Directed the “special case” investigations of Liu Shaoqi, He Long and others.' } },
            { id: 'chen-boda', kind: 'executor', relation: { ko: '중앙문혁소조 조장', en: 'Head of the Cultural Revolution Group' }, note: { ko: '1966~1970년 운동을 지휘하다 1970년 실각했다.', en: 'Led the Group from 1966 until his fall in 1970.' } },
            { id: 'zhang-chunqiao', kind: 'executor', relation: { ko: '상하이 「1월 폭풍」의 지도자', en: 'Leader of Shanghai’s “January Storm”' }, note: { ko: '탈권의 모델을 만들었고 4인방으로 체포되었다.', en: 'Created the model of power seizure; arrested with the Gang of Four.' } },
            { id: 'yao-wenyuan', kind: 'executor', relation: { ko: '『해서파관』 비판문의 필자', en: 'Author of the attack on Hai Rui Dismissed from Office' }, note: { ko: '1965년 11월의 글로 운동의 서막을 열었다.', en: 'His November 1965 article opened the movement.' } },
            { id: 'wang-hongwen', kind: 'executor', relation: { ko: '상하이 노동자 반란파의 지도자', en: 'Leader of the Shanghai worker rebels' }, note: { ko: '1967년 시정부를 접수했고 1973년 당 부주석이 되었다.', en: 'Seized the municipal government in 1967 and became party vice-chairman in 1973.' } },
            { id: 'zhou-enlai', kind: 'participant', relation: { ko: '국가 기구를 지킨 총리', en: 'The premier who kept the state running' }, note: { ko: '원로들을 보호하고 닉슨 방중을 성사시켰으며 1976년 1월 죽었다.', en: 'Protected veterans, brought off Nixon’s visit and died in January 1976.' } },
            { id: 'deng-xiaoping', kind: 'target', relation: { ko: '두 번 실각한 「제2의 당권파」', en: 'The “number two capitalist roader”, purged twice' }, note: { ko: '1966년과 1976년 실각했고 1973~1975년 복귀해 정돈을 이끌었다.', en: 'Fell in 1966 and 1976; returned in 1973–1975 to lead consolidation.' } },
            { id: 'peng-zhen', kind: 'target', relation: { ko: '첫 표적이 된 베이징 시장', en: 'Beijing mayor, the first target' }, note: { ko: '1966년 5월 「5·16 통지」로 실각했다.', en: 'Removed by the May 16 Notification of 1966.' } },
            { id: 'peng-dehuai', kind: 'target', relation: { ko: '박해 속에 죽은 전 국방부장', en: 'Former defence minister who died under persecution' }, note: { ko: '1966년 베이징으로 끌려와 비판당했고 1974년 옥중에서 죽었다.', en: 'Dragged to Beijing in 1966 for struggle sessions; died in custody in 1974.' } },
            { id: 'he-long', kind: 'target', relation: { ko: '박해 속에 죽은 원수', en: 'Marshal who died under persecution' }, note: { ko: '린뱌오·캉성의 공격으로 감금되어 1969년 사망했다.', en: 'Confined after attacks by Lin Biao and Kang Sheng; died in 1969.' } },
            { id: 'wu-han', kind: 'target', relation: { ko: '『해서파관』의 작가', en: 'Author of Hai Rui Dismissed from Office' }, note: { ko: '운동의 첫 비판 대상이 되어 1969년 옥사했다.', en: 'First target of criticism; died in prison in 1969.' } },
            { id: 'deng-tuo', kind: 'target', relation: { ko: '『연산야화』의 작가, 첫 자살자', en: 'Author of Evening Chats at Yanshan, the first suicide' }, note: { ko: '「삼가촌」 비판 뒤 1966년 5월 자살했다.', en: 'Killed himself in May 1966 after the “Three-Family Village” attack.' } },
            { id: 'luo-ruiqing', kind: 'target', relation: { ko: '전야에 실각한 총참모장', en: 'Chief of staff purged on the eve' }, note: { ko: '1965년 말 린뱌오의 고발로 실각했다.', en: 'Fell at the end of 1965 on Lin Biao’s denunciation.' } },
            { id: 'ye-jianying', kind: 'participant', relation: { ko: '「2월 역류」의 원로 · 4인방 체포의 조직자', en: 'Veteran of the “February Countercurrent” and organiser of the arrest of the Gang' }, note: { ko: '1967년 문혁소조에 항의했고 1976년 10월 체포를 결정했다.', en: 'Protested against the Group in 1967 and decided the arrests of October 1976.' } },
            { id: 'chen-yi', kind: 'target', relation: { ko: '「2월 역류」로 비판받은 외교부장', en: 'Foreign minister attacked in the “February Countercurrent”' }, note: { ko: '1967년 비판받았고 1972년 죽었다.', en: 'Criticised in 1967; died in 1972.' } },
            { id: 'hua-guofeng', kind: 'executor', relation: { ko: '마오의 후계자, 4인방 체포', en: 'Mao’s successor who arrested the Gang of Four' }, note: { ko: '1976년 4월 제1부주석이 되었고 10월 4인방을 체포했다.', en: 'First vice-chairman from April 1976; arrested the Gang in October.' } },
            { id: 'wang-dongxing', kind: 'executor', relation: { ko: '8341부대로 4인방 체포 집행', en: 'Executed the arrests with Unit 8341' }, note: { ko: '1976년 10월 6일 중난하이에서 체포를 지휘했다.', en: 'Directed the arrests at Zhongnanhai on 6 October 1976.' } },
            { id: 'richard-nixon', kind: 'participant', relation: { ko: '1972년 방중', en: 'Visited China in 1972' }, note: { ko: '상하이 공동성명으로 미중 화해를 열었다.', en: 'Opened Sino-American rapprochement with the Shanghai Communiqué.' } },
            { id: 'henry-kissinger', kind: 'participant', relation: { ko: '1971년 비밀 방문', en: 'Secret visit of 1971' }, note: { ko: '저우언라이와 닉슨 방중을 준비했다.', en: 'Prepared Nixon’s visit with Zhou Enlai.' } },
            { id: 'brezhnev', kind: 'opponent', relation: { ko: '1969년 국경 충돌기의 소련 지도자', en: 'Soviet leader in the 1969 border clashes' }, note: { ko: '전바오섬 충돌 뒤 대중 압박이 미중 화해를 재촉했다.', en: 'Pressure after Zhenbao Island hastened China’s turn to America.' } },
            { id: 'roderick-macfarquhar', kind: 'witness', relation: { ko: '『마오의 마지막 혁명』의 저자', en: 'Author of Mao’s Last Revolution' }, note: { ko: '1966~1976년의 표준적 서술을 썼다.', en: 'Wrote the standard narrative of 1966–1976.' } },
        ],
        related: ['great-leap-forward', 'sino-soviet-split', 'detente-salt', 'reform-and-opening'],
    },
    {
        id: 'reform-and-opening', sortOrder: 283, period: '1976–1992', countries: ['china'],
        title: { ko: '개혁개방: 덩샤오핑 시대', en: 'Reform and opening: the Deng Xiaoping era' },
        question: { ko: '마오의 당은 어떻게 시장을 받아들였고, 무엇을 끝내 바꾸지 않았는가?', en: 'How did Mao’s party come to accept the market, and what did it refuse to change?' },
        summary: { ko: '4인방 체포 뒤 화궈펑의 「양개범시」와 덩샤오핑의 「실사구시」가 맞섰고, 1978년 12월 11기 3중전회는 당의 중심을 경제건설로 옮겼다. 안후이의 농가생산책임제, 광둥의 경제특구, 국유기업 개혁과 가격 이중제가 이어졌으며 민주의 벽과 「자산계급 자유화」 비판이 정치적 경계를 그었다. 1989년의 후퇴 뒤 1992년 덩의 남순강화가 「사회주의 시장경제」를 확정했다.', en: 'After the arrest of the Gang of Four, Hua Guofeng’s “two whatevers” confronted Deng Xiaoping’s “seek truth from facts”, and in December 1978 the Third Plenum moved the party’s focus to economic construction. Household contracting in Anhui, the special economic zones in Guangdong, state-enterprise reform and the dual-track price system followed, while Democracy Wall and the campaigns against “bourgeois liberalisation” drew the political limits. After the retreat of 1989, Deng’s southern tour of 1992 settled the “socialist market economy”.' },
        outcome: { ko: '중국은 15년 만에 집단농업과 계획경제에서 벗어나 세계 시장에 편입되었고 빈곤이 급감했다. 그러나 「4항 기본원칙」은 정치체제 개혁을 배제했고, 후야오방·자오쯔양의 실각은 그 경계를 보여주었다. 소련의 해체와 대비되는 「중국의 길」은 여기서 나왔다.', en: 'Within fifteen years China left collective farming and the planned economy, joined the world market and saw poverty fall sharply. But the “four cardinal principles” excluded political reform, and the fall of Hu Yaobang and Zhao Ziyang marked the boundary. The “Chinese road” that contrasts with the Soviet collapse was made here.' },
        locations: [
            { lat: 39.90, lng: 116.40, label: { ko: '베이징', en: 'Beijing' } },
            { lat: 32.87, lng: 117.56, label: { ko: '샤오강촌 (안후이)', en: 'Xiaogang village (Anhui)' } },
            { lat: 22.54, lng: 114.06, label: { ko: '선전', en: 'Shenzhen' } },
            { lat: 30.57, lng: 104.07, label: { ko: '청두 (쓰촨)', en: 'Chengdu (Sichuan)' } },
        ],
        timeline: [
            { date: '1977.02', title: { ko: '「양개범시」 사설', en: 'The “two whatevers” editorial' }, body: { ko: '화궈펑 지도부가 마오의 결정과 지시를 모두 지킨다고 선언했다.', en: 'Hua Guofeng’s leadership declared it would uphold all Mao’s decisions and instructions.' } },
            { date: '1977.07', title: { ko: '덩샤오핑 복귀', en: 'Deng Xiaoping restored' }, body: { ko: '10기 3중전회가 덩의 직위를 회복시켰다. 그는 「마오쩌둥 사상을 완전하고 정확하게 이해하자」고 말했다.', en: 'The Third Plenum of the Tenth Central Committee restored Deng’s posts; he called for understanding Mao Zedong Thought “completely and accurately”.' } },
            { date: '1978.05.11', title: { ko: '「실천은 진리를 검증하는 유일한 기준」', en: '“Practice is the sole criterion of truth”' }, body: { ko: '『광명일보』의 논문이 양개범시를 겨냥한 전국 논쟁을 열었다.', en: 'A Guangming Daily article opened the nationwide debate aimed at the two whatevers.' } },
            { date: '1978.11.24', title: { ko: '샤오강촌의 비밀 계약', en: 'The secret contract at Xiaogang' }, body: { ko: '안후이 펑양현의 18호 농민이 손도장을 찍고 토지를 나누었다.', en: 'Eighteen households in Fengyang, Anhui, signed with thumbprints and divided the land.' }, geo: { kind: 'point', lat: 32.87, lng: 117.56, label: { ko: '샤오강촌', en: 'Xiaogang' } } },
            { date: '1978.12', title: { ko: '11기 3중전회', en: 'The Third Plenum of the Eleventh Central Committee' }, body: { ko: '당의 중심을 계급투쟁에서 경제건설로 옮기고 1976년 톈안먼 사건을 재평가했다. 천윈이 부주석이 되었다.', en: 'Moved the party’s focus from class struggle to economic construction and reversed the verdict on the 1976 Tiananmen incident; Chen Yun became vice-chairman.' }, geo: { kind: 'point', lat: 39.90, lng: 116.40, label: { ko: '베이징', en: 'Beijing' } } },
            { date: '1978.12–1979.03', title: { ko: '민주의 벽', en: 'Democracy Wall' }, body: { ko: '시단의 벽에 대자보가 붙었고 웨이징성은 「제5의 현대화」를 요구했다. 1979년 3월 덩은 4항 기본원칙을 선언하고 웨이를 체포했다.', en: 'Posters covered the wall at Xidan and Wei Jingsheng demanded the “fifth modernisation”; in March 1979 Deng proclaimed the four cardinal principles and Wei was arrested.' }, geo: { kind: 'point', lat: 39.91, lng: 116.37, label: { ko: '시단', en: 'Xidan' } } },
            { date: '1980.08', title: { ko: '경제특구 설치', en: 'Special economic zones established' }, body: { ko: '선전·주하이·산터우·샤먼이 특구가 되었다. 같은 달 자오쯔양이 총리가 되었다.', en: 'Shenzhen, Zhuhai, Shantou and Xiamen became special zones; the same month Zhao Ziyang became premier.' }, geo: { kind: 'point', lat: 22.54, lng: 114.06, label: { ko: '선전', en: 'Shenzhen' } } },
            { date: '1981.06', title: { ko: '「역사결의」', en: 'The Resolution on History' }, body: { ko: '6중전회가 문화대혁명을 오류로 규정하고 마오의 공과를 평가했다. 후야오방이 당 주석이 되었다.', en: 'The Sixth Plenum classed the Cultural Revolution an error and assessed Mao’s merits and faults; Hu Yaobang became party chairman.' } },
            { date: '1982.01', title: { ko: '중앙 1호 문건: 농가생산책임제 승인', en: 'No. 1 Central Document endorses household contracting' }, body: { ko: '1983년까지 인민공사가 해체되었다.', en: 'By 1983 the communes had been dissolved.' } },
            { date: '1984.10', title: { ko: '12기 3중전회: 「사회주의 상품경제」', en: 'Third Plenum of the Twelfth Central Committee: the “socialist commodity economy”' }, body: { ko: '개혁의 중심이 농촌에서 도시·국유기업으로 옮겨졌고 가격 이중제가 도입되었다.', en: 'Reform moved from the countryside to the cities and state enterprises; the dual-track price system was introduced.' } },
            { date: '1986.12–1987.01', title: { ko: '학생 시위와 후야오방 사임', en: 'Student protests and Hu Yaobang’s resignation' }, body: { ko: '허페이·상하이·베이징의 시위 뒤 후야오방이 「자산계급 자유화」에 관대했다는 이유로 물러났다.', en: 'After protests in Hefei, Shanghai and Beijing, Hu Yaobang was forced out for laxity toward “bourgeois liberalisation”.' } },
            { date: '1988.08', title: { ko: '가격개혁 「관문 돌파」 실패', en: 'The failed price “breakthrough”' }, body: { ko: '가격 자유화 발표로 사재기와 인플레이션이 일어나 개혁이 후퇴했다.', en: 'The announcement of price liberalisation set off panic buying and inflation and the reform was pulled back.' } },
            { date: '1992.01–02', title: { ko: '덩샤오핑의 남순강화', en: 'Deng’s southern tour' }, body: { ko: '우창·선전·주하이·상하이에서 「개혁하지 않으면 죽는 길뿐」이라며 개혁의 재가동을 지시했다. 10월 제14차 당대회가 사회주의 시장경제를 목표로 삼았다.', en: 'In Wuchang, Shenzhen, Zhuhai and Shanghai Deng said “without reform there is only a dead end”; in October the Fourteenth Congress made the socialist market economy the goal.' }, geo: { kind: 'point', lat: 22.54, lng: 114.06, label: { ko: '선전', en: 'Shenzhen' } } },
        ],
        sections: [
            {
                heading: { ko: '양개범시와 진리 기준 논쟁', en: 'The two whatevers and the criterion of truth' },
                paragraphs: [
                    { ko: '4인방을 체포한 화궈펑의 정통성은 마오의 지명에서 나왔다. 1977년 2월 『인민일보』 사설은 「마오 주석의 결정은 모두 단호히 지키고 지시는 모두 시종 따른다」고 선언했고, 이는 문화대혁명의 판정과 덩샤오핑의 실각도 유지한다는 뜻이었다. 덩은 4월 편지에서 「마오쩌둥 사상을 완전하고 정확하게」 이해하자고 응수했고 7월 복귀했다. 1978년 5월 후야오방이 조직한 「실천은 진리를 검증하는 유일한 기준」 논문은 전국 논쟁을 일으켜 원로들과 지방 지도자들을 덩 편으로 모았다.', en: 'Hua Guofeng’s legitimacy after arresting the Gang of Four derived from Mao’s nomination. The People’s Daily editorial of February 1977 declared “we will resolutely uphold whatever decisions Chairman Mao made and unswervingly follow whatever instructions he gave”, which meant keeping the verdicts of the Cultural Revolution and Deng’s exclusion. Deng replied in an April letter that Mao Zedong Thought must be understood “completely and accurately”, and returned in July. The article “Practice is the sole criterion of truth”, organised by Hu Yaobang in May 1978, set off a national debate that rallied the veterans and provincial leaders to Deng.', sources: [W + 'Two_Whatevers', D + '1977/124.htm'] },
                    { ko: '1978년 11~12월의 중앙공작회의는 예정된 농업 의제를 넘어 1976년 톈안먼 사건의 재평가, 펑더화이·타오주 등의 복권, 천윈의 정치국 상무위원 복귀를 결정했다. 12월 13일 덩의 폐막 연설 「사상을 해방하고 실사구시하며 일치단결해 앞을 보자」가 이어진 11기 3중전회의 기조가 되었다. 전회는 「계급투쟁을 강령으로」를 버리고 당의 중심을 사회주의 현대화 건설로 옮겼다. 화궈펑은 직위를 유지했으나 실권은 넘어갔다.', en: 'The central work conference of November–December 1978 went beyond its planned agricultural agenda to reverse the verdict on the 1976 Tiananmen incident, rehabilitate Peng Dehuai, Tao Zhu and others, and return Chen Yun to the Politburo Standing Committee. Deng’s closing speech of 13 December, “Emancipate the mind, seek truth from facts and unite as one in looking to the future”, became the keynote of the Third Plenum that followed. The plenum abandoned “class struggle as the key link” and moved the party’s focus to socialist modernisation; Hua kept his titles but power had passed.', sources: [D + '1978/110.htm', W + 'Boluan_Fanzheng'] },
                ],
            },
            {
                heading: { ko: '복권과 「역사결의」', en: 'Rehabilitation and the Resolution on History' },
                paragraphs: [
                    { ko: '후야오방의 중앙조직부는 1978년부터 문화대혁명과 그 이전의 억울한 사건을 재심했다. 류사오치는 1980년 복권되어 국장이 치러졌고, 반우파 투쟁의 우파 55만 명 중 극소수를 제외한 전원, 「61인 반도」와 「내몽골 인민당」 사건 관련자, 지주·부농 「모자」를 쓴 2천만 명이 낙인을 벗었다. 「발란반정(撥亂反正)」이라 불린 이 과정은 개혁의 사회적 기반을 만들었다.', en: 'From 1978 Hu Yaobang’s Organisation Department reviewed the unjust cases of the Cultural Revolution and before. Liu Shaoqi was rehabilitated in 1980 with a state funeral; all but a handful of the 550,000 rightists of 1957, those implicated in the “61 renegades” and “Inner Mongolian People’s Party” cases, and twenty million people wearing landlord and rich-peasant “hats” lost their labels. The process, called “bringing order out of chaos”, created the social base of reform.', sources: [W + 'Boluan_Fanzheng', W + 'Hu_Yaobang'] },
                    { ko: '마오를 어떻게 평가할지가 남았다. 1980~1981년 4천 명의 간부가 토론한 뒤 1981년 6월 6중전회가 채택한 「건국 이래 당의 약간의 역사 문제에 관한 결의」는 문화대혁명을 마오가 「발동하고 이끈」 전면적 오류로, 대약진을 좌경 오류로 규정하되 마오의 「공이 주요하고 과가 부차적」이며 마오쩌둥 사상은 「집단지혜의 결정」이라고 결론지었다. 덩은 「마오 주석의 깃발을 버리면 당의 역사 전체를 부정하는 것」이라며 흐루쇼프식 전면 부정을 거부했다. 같은 회의에서 화궈펑이 당 주석에서 물러나고 후야오방이 뒤를 이었다.', en: 'How to judge Mao remained. After four thousand cadres had debated it in 1980–1981, the “Resolution on Certain Questions in the History of Our Party since the Founding of the People’s Republic”, adopted by the Sixth Plenum in June 1981, classed the Cultural Revolution as a comprehensive error Mao had “launched and led” and the Great Leap as a leftist error, while concluding that Mao’s merits were primary and his faults secondary and that Mao Zedong Thought was the “crystallisation of collective wisdom”. Deng refused a Khrushchev-style total negation — “to discard Chairman Mao’s banner would be to negate the party’s whole history”. At the same plenum Hua Guofeng stepped down as chairman and Hu Yaobang succeeded him.', sources: [W + 'Resolution_on_Certain_Questions_in_the_History_of_Our_Party_since_the_Founding_of_the_People%27s_Republic_of_China', D + '1981/15.htm'] },
                ],
            },
            {
                heading: { ko: '농촌: 샤오강촌에서 인민공사 해체까지', en: 'The countryside: from Xiaogang to the end of the communes' },
                paragraphs: [
                    { ko: '개혁은 농민에게서 시작되었다. 1978년 가뭄 속에 안후이 펑양현 샤오강촌의 18호 농민은 처벌을 각오하고 토지를 나누는 계약서에 손도장을 찍었고, 이듬해 수확이 몇 배로 늘었다. 안후이 제1서기 완리는 이를 묵인하고 「성위 6조」로 뒷받침했으며, 쓰촨의 자오쯔양도 같은 실험을 허용했다. 「쌀을 먹으려면 완리를, 곡식을 먹으려면 쯔양을 찾으라」는 말이 돌았다.', en: 'Reform began with the peasants. In the drought of 1978 eighteen households at Xiaogang in Fengyang, Anhui, risked punishment by putting their thumbprints to a contract dividing the land, and the next year’s harvest multiplied. Wan Li, Anhui’s first secretary, looked away and backed them with the provincial “six articles”, and Zhao Ziyang in Sichuan permitted the same experiment; “for rice look for Wan Li, for grain look for Ziyang”, people said.', sources: [W + 'Household_responsibility_system', W + 'Wan_Li'] },
                    { ko: '중앙은 처음에 청부제를 빈곤 산간 지역에 한정했으나 1980년 「75호 문건」, 1982년 「1호 문건」으로 단계적으로 허용했고 1983년 정사분리로 인민공사가 해체되었다. 국가 수매가 인상과 함께 농업 생산은 1978~1984년 연 7% 이상 성장했고 곡물은 3억 톤에서 4억 톤이 되었다. 향진기업이 농촌 잉여노동을 흡수하며 1980년대 성장의 한 축이 되었다. 토지는 집단 소유로 남았고 경작권만 농가에 주어졌다.', en: 'The centre at first confined contracting to poor mountain areas, then allowed it step by step in “Document 75” of 1980 and the “No. 1 Document” of 1982; in 1983 the separation of government from commune dissolved the communes. With higher procurement prices, farm output grew more than seven per cent a year from 1978 to 1984 and grain rose from 300 to 400 million tonnes. Township and village enterprises absorbed surplus rural labour and became a pillar of 1980s growth. Land remained collectively owned, with only cultivation rights given to households.', sources: [W + 'Household_responsibility_system', W + 'Chinese_economic_reform'] },
                ],
            },
            {
                heading: { ko: '개방: 경제특구와 「창구」', en: 'Opening: the special zones and the “windows”' },
                paragraphs: [
                    { ko: '1979년 광둥 제1서기 시중쉰은 홍콩 탈출을 막을 방책으로 중앙에 「선행일보」의 자율권을 요구했고, 덩은 「특구」라는 이름과 함께 「중앙에 돈은 없으니 스스로 길을 뚫으라」고 답했다. 1980년 8월 선전·주하이·산터우·샤먼이 경제특구가 되었다. 홍콩 자본의 위탁가공, 토지 사용권의 유상 양도, 계약제 노동, 외국인 투자가 처음 허용되었고, 어촌 선전은 10년 만에 인구 100만의 도시가 되었다.', en: 'In 1979 Guangdong’s first secretary Xi Zhongxun asked the centre for the freedom to “take one step ahead” as a remedy for the flight to Hong Kong, and Deng answered with the name “special zone” and the words “the centre has no money; cut your own road”. In August 1980 Shenzhen, Zhuhai, Shantou and Xiamen became special economic zones. Processing for Hong Kong capital, paid transfer of land-use rights, contract labour and foreign investment were allowed for the first time, and the fishing town of Shenzhen became a city of a million within a decade.', sources: [W + 'Special_economic_zones_of_China', W + 'Xi_Zhongxun'] },
                    { ko: '특구는 논쟁의 대상이었다. 천윈 등 계획파는 특구를 「조계의 재현」으로 의심했고 1982년 광둥의 밀수 사건과 1985년 하이난 자동차 수입 스캔들이 비판의 근거가 되었다. 덩은 1984년 1월 첫 남순으로 「선전의 경험은 옳다」고 확인하고 14개 연해 도시를 추가 개방했으며, 1988년 하이난이 성이자 특구가 되었다. 「새장 경제」— 계획이라는 새장 안에서 시장이라는 새를 날린다 — 는 천윈이, 「돌다리를 더듬으며 강을 건넌다」는 실용주의는 덩이 대표했다.', en: 'The zones were contested. Chen Yun and the planners suspected them as a “revival of the concessions”, and the Guangdong smuggling cases of 1982 and the Hainan car-import scandal of 1985 gave critics ammunition. Deng’s first southern tour in January 1984 confirmed that “the experience of Shenzhen is correct” and opened fourteen more coastal cities; in 1988 Hainan became a province and a zone. Chen Yun stood for the “birdcage economy” — the bird of the market flying inside the cage of the plan — and Deng for the pragmatism of “crossing the river by feeling for stones”.', sources: [D + '1984/21.htm', W + 'Chen_Yun'] },
                ],
            },
            {
                heading: { ko: '정치의 경계: 민주의 벽과 4항 기본원칙', en: 'The political boundary: Democracy Wall and the four cardinal principles' },
                paragraphs: [
                    { ko: '1978년 11월 베이징 시단의 벽에 대자보가 붙기 시작했다. 처음에는 문화대혁명의 억울함과 1976년 톈안먼 사건 재평가 요구였고, 덩은 이를 「좋은 일」이라 하며 3중전회의 논쟁에 이용했다. 그러나 12월 전기공 웨이징성의 「제5의 현대화 — 민주」는 덩의 4개 현대화가 민주 없이는 공허하며 덩 자신도 독재자가 될 수 있다고 썼다. 『탐색』 『4·5 논단』 같은 민간 간행물이 잇달아 나왔다.', en: 'From November 1978 posters appeared on the wall at Xidan in Beijing. At first they voiced grievances from the Cultural Revolution and demands to reverse the verdict on the 1976 Tiananmen incident, and Deng called them “a good thing” and used them in the plenum’s debates. But in December the electrician Wei Jingsheng’s “The Fifth Modernisation — Democracy” argued that Deng’s four modernisations were hollow without democracy and that Deng himself could become a dictator. Unofficial journals such as Explorations and April Fifth Forum followed.', sources: [W + 'Democracy_Wall', W + 'Wei_Jingsheng'] },
                    { ko: '1979년 3월 30일 덩은 이론공작회의에서 「4항 기본원칙」— 사회주의 노선, 프롤레타리아 독재, 당의 지도, 마르크스레닌주의와 마오쩌둥 사상 — 을 선언했고, 다음 날 웨이징성이 체포되어 10월 15년형을 받았다. 민주의 벽은 12월 폐쇄되었고 1980년 헌법에서 「대명대방·대자보」의 권리가 삭제되었다. 4항 기본원칙은 이후 개혁의 정치적 한계로 작동해 1983년 「정신오염 청소」, 1987년 「자산계급 자유화 반대」 운동의 근거가 되었다.', en: 'On 30 March 1979 Deng proclaimed at a theory conference the “four cardinal principles” — the socialist road, the dictatorship of the proletariat, party leadership, and Marxism-Leninism and Mao Zedong Thought; Wei Jingsheng was arrested the next day and sentenced to fifteen years in October. Democracy Wall was closed in December, and the 1980 constitutional revision removed the right to “speak out freely and put up big-character posters”. The four principles thereafter set the political limit of reform, grounding the campaigns against “spiritual pollution” in 1983 and “bourgeois liberalisation” in 1987.', sources: [D + '1979/115.htm', W + 'Four_Cardinal_Principles'] },
                ],
            },
            {
                heading: { ko: '도시 개혁과 1980년대 후반의 동요', en: 'Urban reform and the turbulence of the late 1980s' },
                paragraphs: [
                    { ko: '1984년 10월 「경제체제 개혁에 관한 결정」은 개혁의 무대를 도시로 옮겼다. 국유기업에 이윤 유보와 경영 자율권이 주어졌고 계획 가격과 시장 가격이 공존하는 이중제가 도입되었으며, 개체호(자영업)와 사영기업이 허용되었다. 자오쯔양 총리 아래 1985~1988년 연 10%를 넘는 성장이 이어졌으나 이중제는 「관다오(官倒)」— 관료의 차익 거래 — 와 부패를 낳았고 인플레이션이 커졌다.', en: 'The “Decision on Reform of the Economic Structure” of October 1984 moved reform to the cities. State enterprises were given retained profits and managerial autonomy, a dual-track system in which plan and market prices coexisted was introduced, and individual and private businesses were allowed. Under Premier Zhao Ziyang growth exceeded ten per cent a year from 1985 to 1988, but the dual track bred “official profiteering” — cadres arbitraging between the two prices — and corruption, and inflation climbed.', sources: [W + 'Chinese_economic_reform', W + 'Zhao_Ziyang'] },
                    { ko: '1986년 말 팡리즈의 강연에 자극받은 학생 시위가 허페이에서 상하이·베이징으로 번지자 원로들은 후야오방에게 책임을 물어 1987년 1월 사임시켰고, 자오쯔양이 총서기가 되었다. 자오는 1987년 제13차 당대회에서 「사회주의 초급 단계」론과 당정 분리 등 정치체제 개혁을 제기했다. 1988년 여름 덩이 밀어붙인 가격 「관문 돌파」 시도는 사재기와 은행 인출 사태를 낳아 철회되었고, 「치리정돈」의 긴축 속에 개혁파와 보수파의 대립이 깊어진 채 1989년을 맞았다.', en: 'When student protests stirred by Fang Lizhi’s lectures spread from Hefei to Shanghai and Beijing at the end of 1986, the elders held Hu Yaobang responsible and forced his resignation in January 1987; Zhao Ziyang became general secretary. At the Thirteenth Congress that year Zhao advanced the theory of the “primary stage of socialism” and political reforms such as separating party and government. In summer 1988 the price “breakthrough” Deng pushed set off panic buying and bank runs and was withdrawn, and under the austerity of “rectification” the reformers and conservatives entered 1989 deeply divided.', sources: [W + '1986_Chinese_student_demonstrations', W + 'Zhao_Ziyang'] },
                ],
            },
            {
                heading: { ko: '1992년 남순강화와 「사회주의 시장경제」', en: 'The 1992 southern tour and the “socialist market economy”' },
                paragraphs: [
                    { ko: '1989년 6월의 진압과 소련·동유럽의 붕괴 뒤 보수파는 「화평연변(和平演變)」— 서방의 평화적 체제 전복 — 을 경계하며 개혁을 늦췄고 「성이 사회주의인가 자본주의인가」를 묻는 논쟁이 되살아났다. 88세의 덩은 공식 직위 없이 1992년 1~2월 우창·선전·주하이·상하이를 돌며 「개혁하지 않으면 죽는 길뿐」이며 「계획과 시장은 사회주의와 자본주의를 가르는 기준이 아니다」라고 말했다.', en: 'After the crackdown of June 1989 and the collapse of the Soviet bloc, the conservatives slowed reform while warning of “peaceful evolution” — subversion by the West — and the debate over whether a measure was “surnamed socialist or capitalist” revived. In January–February 1992 the 88-year-old Deng, holding no office, toured Wuchang, Shenzhen, Zhuhai and Shanghai declaring that “without reform there is only a dead end” and that “planning and markets are not what distinguish socialism from capitalism”.', sources: [D + '1992/179.htm', W + 'Deng_Xiaoping%27s_southern_tour'] },
                    { ko: '남순강화는 처음 홍콩과 광둥 언론을 통해 알려졌고, 군과 지방의 지지 속에 장쩌민 지도부가 이를 받아들였다. 1992년 10월 제14차 당대회는 「사회주의 시장경제 체제」를 개혁의 목표로 확정했고 이후 10년의 고도성장과 국유기업 개혁, 2001년 WTO 가입이 뒤따랐다. 개혁개방은 세계은행 기준으로 약 8억 명을 빈곤에서 벗어나게 했으나 불평등·부패·환경 파괴와 정치 개혁의 부재를 함께 남겼다. 덩의 길은 「경제는 개혁하고 정치는 지킨다」는 공식으로 고르바초프의 길과 대비되어 왔다.', en: 'The talks became known first through the Hong Kong and Guangdong press, and with the support of the army and the provinces the Jiang Zemin leadership adopted them. In October 1992 the Fourteenth Congress made the “socialist market economy” the goal of reform, and a decade of rapid growth, state-enterprise reform and WTO accession in 2001 followed. Reform and opening lifted some 800 million people out of poverty by the World Bank’s measure but left inequality, corruption, environmental damage and the absence of political reform. Deng’s road — reform the economy, hold the polity — has been contrasted ever since with Gorbachev’s.', sources: [W + 'Chinese_economic_reform', K + '%EA%B0%9C%ED%98%81%EA%B0%9C%EB%B0%A9'] },
                ],
            },
        ],
        people: [
            { id: 'deng-xiaoping', kind: 'leader', relation: { ko: '개혁개방의 「총설계사」', en: 'The “chief architect” of reform and opening' }, note: { ko: '1978년 3중전회에서 주도권을 잡았고 1979년 4항 기본원칙을 선언했으며 1992년 남순으로 개혁을 재가동했다.', en: 'Took the initiative at the 1978 plenum, proclaimed the four cardinal principles in 1979 and relaunched reform with the 1992 tour.' } },
            { id: 'hua-guofeng', kind: 'opponent', relation: { ko: '「양개범시」의 당 주석', en: 'Party chairman of the “two whatevers”' }, note: { ko: '1978년 논쟁에서 밀려 1981년 당 주석에서 물러났다.', en: 'Lost the 1978 debate and stepped down as chairman in 1981.' } },
            { id: 'hu-yaobang', kind: 'leader', relation: { ko: '복권과 사상 해방을 이끈 총서기', en: 'General secretary of rehabilitation and the emancipation of thought' }, note: { ko: '진리 기준 논쟁을 조직했고 1987년 「자산계급 자유화」 문제로 사임했다.', en: 'Organised the criterion-of-truth debate; resigned in 1987 over “bourgeois liberalisation”.' } },
            { id: 'zhao-ziyang', kind: 'leader', relation: { ko: '쓰촨의 농촌개혁에서 총리·총서기로', en: 'From Sichuan’s rural reforms to premier and general secretary' }, note: { ko: '1980~1989년 경제개혁을 지휘하고 정치체제 개혁을 제기했다.', en: 'Directed economic reform from 1980 to 1989 and raised political reform.' } },
            { id: 'chen-yun', kind: 'participant', relation: { ko: '「새장 경제」의 계획파 원로', en: 'The planners’ elder of the “birdcage economy”' }, note: { ko: '1978년 복귀해 조정을 이끌었고 특구와 급진 시장화에 제동을 걸었다.', en: 'Returned in 1978 to lead adjustment and braked the zones and rapid marketisation.' } },
            { id: 'wan-li', kind: 'executor', relation: { ko: '안후이의 농가생산책임제', en: 'Household contracting in Anhui' }, note: { ko: '샤오강촌의 실험을 묵인하고 전국화의 길을 열었다.', en: 'Tolerated the Xiaogang experiment and opened the way to its spread.' } },
            { id: 'xi-zhongxun', kind: 'executor', relation: { ko: '광둥의 경제특구 발의자', en: 'Initiator of Guangdong’s special zones' }, note: { ko: '1979년 「선행일보」 권한을 요구해 특구를 이끌어 냈다.', en: 'Asked in 1979 for the right to “take one step ahead” and secured the zones.' } },
            { id: 'ye-jianying', kind: 'participant', relation: { ko: '덩샤오핑 복권을 지지한 원로', en: 'Veteran who backed Deng’s return' }, note: { ko: '1977년 덩의 복귀와 1978년 전환을 뒷받침했다.', en: 'Supported Deng’s return in 1977 and the turn of 1978.' } },
            { id: 'li-xiannian', kind: 'participant', relation: { ko: '계획 우선을 주장한 원로', en: 'Elder arguing for the primacy of planning' }, note: { ko: '천윈과 함께 급진 개혁에 신중했다.', en: 'Cautious about rapid reform alongside Chen Yun.' } },
            { id: 'bo-yibo', kind: 'participant', relation: { ko: '후야오방 해임 회의를 주재한 원로', en: 'Elder who chaired the meeting that removed Hu Yaobang' }, note: { ko: '1987년 1월 「생활회」를 주재했다.', en: 'Presided over the “democratic life meeting” of January 1987.' } },
            { id: 'wang-dongxing', kind: 'opponent', relation: { ko: '양개범시를 지지한 부주석', en: 'Vice-chairman who backed the two whatevers' }, note: { ko: '1980년 부주석에서 물러났다.', en: 'Resigned the vice-chairmanship in 1980.' } },
            { id: 'wei-jingsheng', kind: 'opponent', relation: { ko: '「제5의 현대화」의 저자', en: 'Author of “The Fifth Modernisation”' }, note: { ko: '민주의 벽에 민주를 요구했다가 1979년 체포되어 15년형을 받았다.', en: 'Demanded democracy at Democracy Wall; arrested in 1979 and sentenced to fifteen years.' } },
            { id: 'fang-lizhi', kind: 'opponent', relation: { ko: '1986년 학생 시위의 정신적 지주', en: 'Spiritual guide of the 1986 student protests' }, note: { ko: '강연으로 시위를 자극했고 1987년 당적을 잃었다.', en: 'His lectures stirred the protests; expelled from the party in 1987.' } },
            { id: 'chen-yonggui', kind: 'opponent', relation: { ko: '농가 청부제에 반대한 다자이의 부총리', en: 'Dazhai’s vice-premier who opposed household contracting' }, note: { ko: '1980년 부총리에서 물러났다.', en: 'Left the vice-premiership in 1980.' } },
            { id: 'jiang-zemin', kind: 'participant', relation: { ko: '남순강화를 받아들인 총서기', en: 'General secretary who adopted the southern tour line' }, note: { ko: '1992년 제14차 당대회에서 사회주의 시장경제를 목표로 삼았다.', en: 'Made the socialist market economy the goal at the 1992 congress.' } },
            { id: 'maurice-meisner', kind: 'witness', relation: { ko: '개혁기 시장화의 비판적 역사가', en: 'Critical historian of reform-era marketisation' }, note: { ko: '『마오의 중국과 그 이후』에서 개혁이 사회주의의 약속을 저버렸다고 평가했다.', en: 'In Mao’s China and After judged that reform abandoned socialism’s promise.' } },
        ],
        related: ['cultural-revolution', 'tiananmen-1989', 'perestroika'],
    },
    {
        id: 'tiananmen-1989', sortOrder: 362, period: '1989', countries: ['china'],
        title: { ko: '1989년 톈안먼 시위와 6·4 진압', en: 'The Tiananmen protests and the crackdown of 4 June 1989' },
        question: { ko: '후야오방의 죽음을 애도하던 학생들은 왜 계엄군과 마주쳤고, 진압은 중국의 길을 어떻게 정했는가?', en: 'Why did students mourning Hu Yaobang end up facing martial-law troops, and how did the crackdown set China’s course?' },
        summary: { ko: '1989년 4월 후야오방의 죽음을 애도하는 학생 집회가 부패 척결과 언론 자유를 요구하는 시위로 번졌고, 4·26 사설의 「동란」 규정과 5월 단식으로 100만 명이 광장에 모였다. 고르바초프 방중 중 지도부는 계엄을 결정했고 자오쯔양은 반대하다 실각했다. 6월 3~4일 밤 군이 시내로 진입해 수백~수천 명이 죽었다.', en: 'In April 1989 student gatherings mourning Hu Yaobang grew into protests against corruption and for press freedom; the 26 April editorial branding them “turmoil” and the May hunger strike brought a million people to the square. During Gorbachev’s visit the leadership decided on martial law and Zhao Ziyang, who opposed it, fell. On the night of 3–4 June the army fought its way into the city and hundreds to thousands died.' },
        outcome: { ko: '당은 자오쯔양을 해임하고 장쩌민을 총서기로 세웠으며 「안정이 모든 것을 압도한다」는 원칙 아래 경제개혁을 재개하되 정치 개혁을 봉인했다. 사건은 중국에서 공식 기억에서 지워졌고, 소련·동유럽의 1989년과 대비되는 중국 체제의 궤적을 결정했다.', en: 'The party removed Zhao Ziyang, installed Jiang Zemin as general secretary and, on the principle that “stability overrides everything”, resumed economic reform while sealing off political reform. The event was erased from official memory in China and set the trajectory of the Chinese system in contrast to the 1989 of the Soviet bloc.' },
        locations: [
            { lat: 39.905, lng: 116.397, label: { ko: '톈안먼 광장', en: 'Tiananmen Square' } },
            { lat: 39.906, lng: 116.33, label: { ko: '무시디', en: 'Muxidi' } },
            { lat: 39.99, lng: 116.31, label: { ko: '베이징대학', en: 'Peking University' } },
            { lat: 30.57, lng: 104.07, label: { ko: '청두', en: 'Chengdu' } },
            { lat: 31.23, lng: 121.47, label: { ko: '상하이', en: 'Shanghai' } },
        ],
        timeline: [
            { date: '1989.04.15', title: { ko: '후야오방 사망', en: 'Death of Hu Yaobang' }, body: { ko: '심장마비로 죽은 전 총서기를 추모하는 화환과 대자보가 대학과 광장에 나타났다.', en: 'Wreaths and posters mourning the former general secretary, dead of a heart attack, appeared at the universities and in the square.' } },
            { date: '1989.04.22', title: { ko: '국장과 인민대회당 앞 청원', en: 'State funeral and the petition at the Great Hall' }, body: { ko: '학생 10만 명이 광장에 모였고 대표 세 명이 계단에 무릎을 꿇고 청원서를 올렸다.', en: 'A hundred thousand students filled the square; three representatives knelt on the steps to present a petition.' }, geo: { kind: 'point', lat: 39.905, lng: 116.397, label: { ko: '톈안먼 광장', en: 'Tiananmen Square' } } },
            { date: '1989.04.26', title: { ko: '『인민일보』 「동란」 사설', en: 'The People’s Daily “turmoil” editorial' }, body: { ko: '덩샤오핑의 발언에 따른 사설이 시위를 「계획적 음모·동란」으로 규정했다. 이튿날 최대 규모의 시위가 열렸다.', en: 'An editorial based on Deng Xiaoping’s remarks branded the movement a “planned conspiracy and turmoil”; the next day saw the largest march yet.' } },
            { date: '1989.05.04', title: { ko: '5·4 70주년과 자오쯔양의 연설', en: 'The May Fourth anniversary and Zhao Ziyang’s speech' }, body: { ko: '자오쯔양이 아시아개발은행 총회에서 학생들의 요구가 애국적이라며 대화를 제안했다.', en: 'Zhao told the Asian Development Bank meeting that the students’ demands were patriotic and proposed dialogue.' } },
            { date: '1989.05.13', title: { ko: '단식 시작', en: 'The hunger strike begins' }, body: { ko: '학생 수백 명이 광장에서 단식에 들어갔고 3천 명으로 늘었다. 시민의 지지가 폭발했다.', en: 'Hundreds of students began a hunger strike in the square, growing to three thousand; public support surged.' }, geo: { kind: 'point', lat: 39.905, lng: 116.397, label: { ko: '톈안먼 광장', en: 'Tiananmen Square' } } },
            { date: '1989.05.15–18', title: { ko: '고르바초프 방중', en: 'Gorbachev in Beijing' }, body: { ko: '30년 만의 중소 정상회담이 광장의 시위 때문에 환영식을 옮겨야 했다. 외신 1천 명이 시위를 세계에 전했다.', en: 'The first Sino-Soviet summit in thirty years had to move its welcoming ceremony because of the square; a thousand foreign journalists broadcast the protests to the world.' } },
            { date: '1989.05.17', title: { ko: '덩샤오핑 자택 회의: 계엄 결정', en: 'The meeting at Deng’s home: martial law decided' }, body: { ko: '100만 명이 거리에 나온 날, 원로들과 상무위원이 계엄을 결정했고 자오쯔양은 반대했다.', en: 'On the day a million marched, the elders and the Standing Committee decided on martial law; Zhao Ziyang dissented.' } },
            { date: '1989.05.19', title: { ko: '자오쯔양의 마지막 광장 방문 · 리펑의 계엄 연설', en: 'Zhao’s last visit to the square; Li Peng’s martial-law speech' }, body: { ko: '새벽 자오쯔양이 학생들에게 「우리는 너무 늦게 왔다」고 말했고, 밤에 리펑이 계엄을 선포했다.', en: 'At dawn Zhao told the students “we have come too late”; that night Li Peng announced martial law.' }, geo: { kind: 'point', lat: 39.905, lng: 116.397, label: { ko: '톈안먼 광장', en: 'Tiananmen Square' } } },
            { date: '1989.05.20–23', title: { ko: '시민이 군을 막다', en: 'Citizens block the army' }, body: { ko: '베이징 시민이 교외에서 계엄군의 진입을 막았고 부대는 철수했다.', en: 'Beijing residents stopped the martial-law troops in the suburbs and the units withdrew.' } },
            { date: '1989.05.30', title: { ko: '민주의 여신상', en: 'The Goddess of Democracy' }, body: { ko: '중앙미술학원 학생들이 세운 10미터 조각상이 마오의 초상을 마주 보았다.', en: 'A ten-metre statue built by Central Academy of Fine Arts students faced Mao’s portrait.' }, geo: { kind: 'point', lat: 39.905, lng: 116.397, label: { ko: '톈안먼 광장', en: 'Tiananmen Square' } } },
            { date: '1989.06.03–04', title: { ko: '6·4 진압', en: 'The crackdown of 4 June' }, body: { ko: '밤 10시경 무시디에서 군이 발포하며 시내로 진입했고 새벽 광장이 비워졌다. 사망자는 수백~수천 명으로 추정된다.', en: 'Around 10 pm troops opened fire at Muxidi and fought into the city; the square was cleared at dawn. The dead are estimated at hundreds to thousands.' }, geo: { kind: 'arrow', points: [[39.906, 116.30], [39.906, 116.33], [39.905, 116.397]], label: { ko: '서쪽 창안제 → 무시디 → 광장 (개략)', en: 'West Chang’an Avenue → Muxidi → the square (schematic)' }, actor: { ko: '계엄군', en: 'Martial-law troops' } } },
            { date: '1989.06.05', title: { ko: '「탱크맨」', en: '“Tank Man”' }, body: { ko: '창안제에서 한 남자가 탱크 행렬을 막아선 사진이 세계에 퍼졌다.', en: 'The photograph of a lone man blocking a column of tanks on Chang’an Avenue spread around the world.' } },
            { date: '1989.06.24', title: { ko: '4중전회: 자오쯔양 해임, 장쩌민 총서기', en: 'Fourth Plenum: Zhao removed, Jiang Zemin general secretary' }, body: { ko: '자오쯔양이 「동란 지지와 당 분열」로 해임되었고 상하이의 장쩌민이 발탁되었다.', en: 'Zhao was removed for “supporting the turmoil and splitting the party” and Jiang Zemin of Shanghai was chosen.' } },
        ],
        sections: [
            {
                heading: { ko: '1989년 봄의 조건', en: 'The conditions of spring 1989' },
                paragraphs: [
                    { ko: '1988년의 인플레이션(공식 18%)과 가격개혁 실패, 「관다오」로 상징되는 간부 부패, 1987년 후야오방 실각 이후 좁아진 정치 공간이 배경이었다. 지식인들은 1989년 초 팡리즈의 공개서한을 시작으로 웨이징성 등 정치범 석방을 청원했고, 5·4 운동 70주년과 건국 40주년, 프랑스 혁명 200주년이 겹친 해였다. 학생들 사이에서는 1986년 시위의 기억과 「신권위주의」 논쟁이 이어지고 있었다.', en: 'The background was the inflation of 1988 (officially eighteen per cent) and the failed price reform, cadre corruption symbolised by “official profiteering”, and the narrowed political space after Hu Yaobang’s fall in 1987. Beginning with Fang Lizhi’s open letter early in 1989, intellectuals petitioned for the release of Wei Jingsheng and other political prisoners, in a year that combined the seventieth anniversary of May Fourth, the fortieth of the People’s Republic and the bicentenary of the French Revolution. Among students the memory of the 1986 protests and the debate over “neo-authoritarianism” were alive.', sources: [W + '1989_Tiananmen_Square_protests_and_massacre', W + 'Fang_Lizhi'] },
                    { ko: '4월 15일 후야오방이 정치국 회의 중 심장마비로 쓰러져 죽자 그의 죽음은 1976년 저우언라이 추모가 그랬듯 정치적 표현의 계기가 되었다. 베이징대학과 인민대학에 대자보가 붙었고 17~18일 학생들이 광장으로 행진해 후야오방 재평가, 언론 자유, 간부 재산 공개, 교육 예산 증액 등 7개 요구를 냈다. 20일 신화먼 앞의 충돌과 22일 국장 날 인민대회당 계단에 무릎 꿇은 세 학생의 청원은 정부의 무응답과 함께 분노를 키웠다.', en: 'When Hu Yaobang collapsed with a heart attack at a Politburo meeting and died on 15 April, his death became an occasion for political expression, as the mourning for Zhou Enlai had in 1976. Posters went up at Peking and People’s Universities, and on 17–18 April students marched to the square with seven demands — a reassessment of Hu, press freedom, disclosure of cadres’ assets, more money for education. The scuffle at Xinhuamen on the 20th and, on the day of the state funeral on the 22nd, the three students kneeling on the steps of the Great Hall with a petition, met with no response and fed the anger.', sources: [W + '1989_Tiananmen_Square_protests_and_massacre', W + 'Hu_Yaobang'] },
                ],
            },
            {
                heading: { ko: '4·26 사설과 5·4', en: 'The 26 April editorial and May Fourth' },
                paragraphs: [
                    { ko: '자오쯔양이 북한을 방문한 사이 리펑과 베이징 시 지도부는 덩샤오핑에게 시위를 보고했고, 덩의 발언을 바탕으로 4월 26일 『인민일보』 사설은 시위를 「극소수가 계획한 음모이자 동란」으로 규정했다. 사설은 학생들을 분노하게 했다. 27일 5만 학생과 수십만 시민이 경찰 저지선을 뚫고 행진했으며, 이는 정부가 「동란」 규정을 철회하라는 요구가 이후 협상의 핵심 쟁점이 된 이유였다.', en: 'While Zhao Ziyang was visiting North Korea, Li Peng and the Beijing municipal leadership reported the protests to Deng Xiaoping, and on the basis of Deng’s remarks the People’s Daily editorial of 26 April branded the movement “a planned conspiracy and turmoil” by “an extremely small number”. The editorial enraged the students: on the 27th fifty thousand of them, with hundreds of thousands of citizens, broke through police lines, and the demand that the government withdraw the “turmoil” verdict became the central issue of every later negotiation.', sources: [W + '1989_Tiananmen_Square_protests_and_massacre', W + 'Li_Peng'] },
                    { ko: '귀국한 자오쯔양은 5월 4일 아시아개발은행 총회 연설에서 학생들의 요구가 애국적이며 「법과 질서 안에서 대화로 해결」해야 한다고 말해 4·26 사설과 다른 노선을 공개했다. 학생 조직 「고자련(高自聯)」은 대화 채널을 요구했고 언론인들은 「우리는 거짓말하고 싶지 않다」며 보도 자유를 요구했다. 5월 초 시위는 소강 상태였으나 정부의 대화 거부와 4·26 사설 고수가 다음 단계를 불렀다.', en: 'Back in Beijing, Zhao told the Asian Development Bank meeting on 4 May that the students’ demands were patriotic and should be resolved “through dialogue within law and order”, publicly revealing a line different from the editorial. The student federation demanded a channel for dialogue and journalists marched with the banner “we do not want to lie”. In early May the protests ebbed, but the government’s refusal of dialogue and its insistence on the editorial brought the next stage.', sources: [W + 'Zhao_Ziyang', W + '1989_Tiananmen_Square_protests_and_massacre'] },
                ],
            },
            {
                heading: { ko: '단식과 고르바초프', en: 'The hunger strike and Gorbachev' },
                paragraphs: [
                    { ko: '5월 13일 왕단·우얼카이시·차이링 등이 이끄는 학생 수백 명이 고르바초프 방중을 이틀 앞두고 광장에서 단식을 시작했다. 단식은 도시의 동정을 폭발시켜 노동자·지식인·언론인·심지어 당 기관 직원까지 행진에 나섰고, 17~18일에는 100만 명이 거리에 나왔다. 베이징 노동자 자치연합회가 결성되어 학생 운동을 넘어선 조직이 나타났으며 상하이·청두·시안 등 전국 수십 개 도시에서 시위가 일어났다.', en: 'On 13 May several hundred students led by Wang Dan, Wu’erkaixi and Chai Ling began a hunger strike in the square, two days before Gorbachev’s arrival. The strike released the city’s sympathy: workers, intellectuals, journalists and even staff of party organs marched, and on 17–18 May a million people were in the streets. The Beijing Workers’ Autonomous Federation was formed, an organisation beyond the student movement, and protests spread to dozens of cities including Shanghai, Chengdu and Xi’an.', sources: [W + 'Beijing_Workers%27_Autonomous_Federation', W + 'Wang_Dan_(dissident)'] },
                    { ko: '15일 도착한 고르바초프의 환영식은 광장을 피해 공항에서 열렸고, 30년 만의 중소 관계 정상화는 시위에 가려졌다. 방중 취재를 위해 온 외신 1천여 명이 광장을 생중계했다. 16일 자오쯔양은 고르바초프에게 「중요 문제는 덩샤오핑 동지가 결정한다」고 말했고, 이는 뒤에 덩에게 책임을 돌리려 했다는 비난의 근거가 되었다. 18일 리펑과 학생 대표의 텔레비전 대화는 결렬되었다.', en: 'Gorbachev’s welcoming ceremony on the 15th was held at the airport to avoid the square, and the normalisation of Sino-Soviet relations after thirty years was overshadowed by the protests; the thousand foreign journalists who had come for the visit broadcast the square live. On the 16th Zhao told Gorbachev that “Comrade Deng Xiaoping decides major questions”, later cited as an attempt to shift responsibility to Deng. The televised meeting between Li Peng and student representatives on the 18th collapsed.', sources: [W + '1989_Sino-Soviet_Summit', W + 'Mikhail_Gorbachev'] },
                ],
            },
            {
                heading: { ko: '계엄: 5월 17일에서 6월 3일까지', en: 'Martial law: from 17 May to 3 June' },
                paragraphs: [
                    { ko: '5월 17일 덩샤오핑 자택에서 열린 회의에서 덩은 「후퇴할 곳이 없다」며 계엄을 결정했고 상무위원 표결에서 자오쯔양과 후치리가 반대했다. 자오는 사직 의사를 밝힌 뒤 19일 새벽 광장을 찾아 「우리는 너무 늦게 왔다」고 말했다. 그날 밤 리펑은 텔레비전으로 계엄을 선포했고 20일 발효되었다. 그러나 베이징 시민은 교외 도로를 막고 병사들을 설득해 부대의 진입을 막았으며, 군은 일단 물러났다.', en: 'At the meeting at Deng Xiaoping’s home on 17 May Deng decided on martial law — “there is nowhere to retreat” — and in the Standing Committee vote Zhao Ziyang and Hu Qili dissented. Zhao offered his resignation and before dawn on the 19th went to the square to say “we have come too late”. That night Li Peng announced martial law on television; it took effect on the 20th. But Beijing residents blocked the suburban roads and talked to the soldiers, halting the units’ advance, and the army pulled back for the moment.', sources: [W + 'Zhao_Ziyang', W + '1989_Tiananmen_Square_protests_and_massacre'] },
                    { ko: '2주의 교착 동안 광장의 학생 수는 줄었고 지도부는 철수를 놓고 갈라졌다. 30일 「민주의 여신」이 세워졌고, 지방 학생들이 계속 유입되었다. 원로들은 상하이의 장쩌민을 후임 총서기로 낙점했고 전국 군구에서 부대가 베이징으로 집결했다. 6월 2일 덩과 원로들은 「어떤 대가를 치르더라도」 광장을 비우기로 결정했고, 3일 오후 군의 진입 명령이 내려졌다.', en: 'During two weeks of stalemate the number of students in the square fell and their leaders split over withdrawal. On the 30th the “Goddess of Democracy” was raised, and students from the provinces kept arriving. The elders chose Jiang Zemin of Shanghai as the next general secretary, and troops from military regions across the country gathered around Beijing. On 2 June Deng and the elders decided to clear the square “whatever the cost”, and on the afternoon of the 3rd the order to move in was given.', sources: [W + 'Goddess_of_Democracy', W + 'Jiang_Zemin'] },
                ],
            },
            {
                heading: { ko: '6월 3~4일 밤', en: 'The night of 3–4 June' },
                paragraphs: [
                    { ko: '3일 밤 10시경 서쪽 창안제의 무시디에서 제38군이 실탄을 발사하며 시민의 바리케이드를 돌파했고, 동·남쪽에서도 부대가 진입했다. 사망자 대부분은 광장이 아니라 무시디·시단·난츠쯔 등 시내 대로에서 총에 맞은 시민과 노동자였다. 새벽 1시 반 군이 광장을 포위했고 4시 소등 뒤 남은 학생들은 협상 끝에 5시경 남쪽으로 철수했다. 5일 창안제에서 탱크 행렬을 막아선 한 남자의 사진이 세계에 퍼졌다.', en: 'Around 10 pm on the 3rd, at Muxidi on western Chang’an Avenue, the 38th Army opened fire with live ammunition and broke through the citizens’ barricades, and units entered from the east and south as well. Most of the dead were not in the square but citizens and workers shot on the avenues — Muxidi, Xidan, Nanchizi. By 1.30 am the army had surrounded the square; after the lights went out at 4 am the remaining students withdrew southward around 5 after negotiation. On the 5th the photograph of a lone man blocking a column of tanks on Chang’an Avenue went round the world.', sources: [W + '1989_Tiananmen_Square_protests_and_massacre', W + 'Tank_Man'] },
                    { ko: '사망자 수는 확정되지 않았다. 중국 정부는 6월 말 「시민 200여 명과 군인 수십 명」이라 발표했고, 중국 적십자의 초기 추정 2,600명은 곧 철회되었으며, 영국 대사의 전문은 1만 명을 전했고 「톈안먼 어머니회」는 200명 이상의 이름을 확인했다. 진압 뒤 전국에서 수만 명이 체포되었고 베이징 노동자 자치연합회 회원 등 노동자들이 가장 무거운 형을 받았다. 6월 9일 덩샤오핑은 계엄군을 치하하며 사건을 「서방의 지원을 받은 반혁명 폭란」으로 규정했다.', en: 'The death toll has never been settled. At the end of June the government announced “over 200 civilians and dozens of soldiers”; the Chinese Red Cross’s initial estimate of 2,600 was quickly withdrawn; a British ambassador’s cable reported 10,000; the Tiananmen Mothers have verified more than 200 names. Tens of thousands were arrested across the country after the crackdown, and workers, including members of the Workers’ Autonomous Federation, received the heaviest sentences. On 9 June Deng Xiaoping congratulated the martial-law troops and called the event a “counter-revolutionary riot” backed by the West.', sources: ['https://nsarchive2.gwu.edu/NSAEBB/NSAEBB16/', 'https://history.state.gov/historicaldocuments/frus1989-92v03'] },
                ],
            },
            {
                heading: { ko: '결과: 안정이 모든 것을 압도한다', en: 'Consequences: stability overrides everything' },
                paragraphs: [
                    { ko: '6월 하순 4중전회는 자오쯔양을 총서기와 정치국 상무위원에서 해임하고 장쩌민을 총서기로 선출했다. 자오는 2005년 죽을 때까지 자택에 연금되었고, 팡리즈 부부는 미국 대사관에 13개월 피신했으며 학생 지도자들은 체포되거나 홍콩을 거쳐 망명했다. 서방은 무기 금수와 제재를 가했으나 부시 행정부는 스코크로프트를 비밀리에 보내 관계를 유지했다. 당 안에서는 「자산계급 자유화」 척결과 「화평연변」 경계가 강조되었다.', en: 'In late June the Fourth Plenum removed Zhao Ziyang as general secretary and from the Politburo Standing Committee and elected Jiang Zemin. Zhao remained under house arrest until his death in 2005; Fang Lizhi and his wife spent thirteen months in the US embassy; the student leaders were arrested or escaped into exile through Hong Kong. The West imposed arms embargoes and sanctions, but the Bush administration secretly sent Scowcroft to keep relations open. Inside the party the eradication of “bourgeois liberalisation” and vigilance against “peaceful evolution” were stressed.', sources: [W + '1989_Tiananmen_Square_protests_and_massacre', W + 'George_H._W._Bush'] },
                    { ko: '진압은 소련·동유럽의 1989년과 정반대의 결과를 낳았다. 몇 달 뒤 베를린 장벽이 무너지고 1991년 소련이 해체되는 동안 중국공산당은 권력을 지켰고, 덩은 1992년 남순강화로 경제개혁을 재개하면서 정치 개혁은 봉인했다. 「안정이 모든 것을 압도한다」는 원칙, 애국주의 교육, 인터넷 검열은 이 사건의 유산이다. 중국에서 6·4는 공식 기억에서 지워졌고 홍콩의 촛불 추모도 2020년 이후 금지되었으나, 「톈안먼 어머니회」와 해외의 기록은 계속되고 있다.', en: 'The crackdown produced the opposite outcome to the 1989 of the Soviet bloc. While the Berlin Wall fell months later and the Soviet Union dissolved in 1991, the Chinese Communist Party kept power, and Deng’s southern tour of 1992 resumed economic reform while sealing off political reform. The principle that “stability overrides everything”, patriotic education and internet censorship are legacies of the event. In China 4 June has been erased from official memory and Hong Kong’s candlelight vigil banned since 2020, but the Tiananmen Mothers and records abroad continue.', sources: [W + '1989_Tiananmen_Square_protests_and_massacre', K + '1989%EB%85%84_%ED%86%88%EC%95%88%EB%A8%BC_%EC%82%AC%EA%B1%B4'] },
                ],
            },
        ],
        people: [
            { id: 'deng-xiaoping', kind: 'executor', relation: { ko: '계엄과 진압을 결정한 최고 지도자', en: 'Paramount leader who decided on martial law and the crackdown' }, note: { ko: '4·26 사설의 근거가 된 발언을 했고 5월 17일 계엄을, 6월 2일 광장 소개를 결정했다.', en: 'His remarks underlay the 26 April editorial; decided martial law on 17 May and the clearing on 2 June.' } },
            { id: 'zhao-ziyang', kind: 'opponent', relation: { ko: '계엄에 반대해 실각한 총서기', en: 'General secretary who opposed martial law and fell' }, note: { ko: '5월 19일 광장에서 「우리는 너무 늦게 왔다」고 말했고 6월 해임되어 연금되었다.', en: 'Told the students “we have come too late” on 19 May; removed in June and confined.' } },
            { id: 'li-peng', kind: 'executor', relation: { ko: '계엄을 선포한 총리', en: 'Premier who declared martial law' }, note: { ko: '5월 18일 학생과의 대화가 결렬된 뒤 19일 계엄을 선포했다.', en: 'Declared martial law on 19 May after the dialogue of the 18th collapsed.' } },
            { id: 'hu-yaobang', kind: 'target', relation: { ko: '그의 죽음이 시위를 불렀다', en: 'Whose death sparked the protests' }, note: { ko: '4월 15일 사망했고 추모 집회가 시위로 번졌다.', en: 'Died on 15 April; the mourning became the movement.' } },
            { id: 'jiang-zemin', kind: 'participant', relation: { ko: '상하이에서 발탁된 새 총서기', en: 'The new general secretary chosen from Shanghai' }, note: { ko: '상하이 시위를 수습하고 『세계경제도보』를 폐간해 6월 총서기가 되었다.', en: 'Contained the Shanghai protests, closed the World Economic Herald and became general secretary in June.' } },
            { id: 'wan-li', kind: 'participant', relation: { ko: '해외에서 귀국해 계엄을 지지한 전인대 위원장', en: 'NPC chairman who returned from abroad and backed martial law' }, note: { ko: '학생들이 전인대 소집을 기대했으나 5월 27일 계엄 지지를 표명했다.', en: 'Students hoped he would convene the NPC; on 27 May he endorsed martial law.' } },
            { id: 'li-xiannian', kind: 'executor', relation: { ko: '강경 진압을 지지한 원로', en: 'Elder who supported the hard line' }, note: { ko: '5월 17일 회의에서 계엄을 지지했다.', en: 'Backed martial law at the 17 May meeting.' } },
            { id: 'bo-yibo', kind: 'executor', relation: { ko: '계엄을 지지한 원로', en: 'Elder who supported martial law' }, note: { ko: '원로 회의에서 강경론에 섰다.', en: 'Took the hard line in the elders’ deliberations.' } },
            { id: 'fang-lizhi', kind: 'opponent', relation: { ko: '정치범 석방 청원의 발의자, 미국 대사관 피신', en: 'Initiator of the prisoner petition; refuge in the US embassy' }, note: { ko: '진압 뒤 13개월 대사관에 머문 뒤 출국했다.', en: 'Spent thirteen months in the embassy after the crackdown before leaving.' } },
            { id: 'wei-jingsheng', kind: 'target', relation: { ko: '석방 청원의 대상이 된 정치범', en: 'Political prisoner named in the petitions' }, note: { ko: '1989년 초 지식인들이 그의 석방을 요구했다.', en: 'Intellectuals demanded his release early in 1989.' } },
            { id: 'gorbachev', kind: 'witness', relation: { ko: '시위 한가운데 베이징을 방문한 소련 지도자', en: 'Soviet leader who visited Beijing at the height of the protests' }, note: { ko: '5월 15~18일 방중으로 중소 관계를 정상화했다.', en: 'Normalised Sino-Soviet relations on his visit of 15–18 May.' } },
            { id: 'george-h-w-bush', kind: 'participant', relation: { ko: '제재와 비밀 접촉을 병행한 미국 대통령', en: 'US president who combined sanctions with secret contact' }, note: { ko: '무기 금수를 결정하면서 스코크로프트를 베이징에 보냈다.', en: 'Imposed an arms embargo while sending Scowcroft to Beijing.' } },
        ],
        related: ['reform-and-opening', 'revolutions-1989', 'new-thinking-diplomacy', 'sino-soviet-split'],
    },
];
