// 1911–1936: the republic, May Fourth, the first united front, the Long March.
const W = 'https://en.wikipedia.org/wiki/';
const K = 'https://ko.wikipedia.org/wiki/';
const M = 'https://www.marxists.org/reference/archive/mao/selected-works/';

module.exports = [
    {
        id: 'xinhai-revolution-1911', sortOrder: 12, period: '1911–1916', countries: ['china'],
        title: { ko: '신해혁명과 중화민국의 탄생', en: 'The 1911 Revolution and the birth of the Republic' },
        question: { ko: '2천 년의 제정을 끝낸 혁명은 왜 공화국이 아니라 군벌의 시대로 이어졌는가?', en: 'Why did the revolution that ended two thousand years of monarchy lead to warlords rather than a republic?' },
        summary: { ko: '1911년 10월 우창의 신군 봉기가 각 성의 독립 선언으로 번져 청 왕조가 무너지고 아시아 최초의 공화국이 섰다. 그러나 권력은 혁명파가 아니라 북양군의 위안스카이에게 넘어갔고, 그의 제정 복고 시도와 죽음은 군벌 할거를 남겼다.', en: 'In October 1911 a New Army mutiny at Wuchang spread into provincial declarations of independence, the Qing fell and Asia’s first republic was born. But power passed not to the revolutionaries but to Yuan Shikai of the Beiyang Army, whose bid to restore the monarchy and death left the country to warlords.' },
        outcome: { ko: '황제 체제는 사라졌지만 통일된 공화국은 서지 못했다. 국회와 헌법은 무력 앞에 무력했고, 쑨원의 국민당은 남방으로 밀려났으며, 이 실패의 경험이 5·4 세대가 「공화」 너머의 해답을 찾게 만들었다.', en: 'The imperial system vanished, but no unified republic replaced it. Parliament and constitution were helpless before armed force, Sun Yat-sen’s party was driven to the south, and the experience of this failure sent the May Fourth generation looking for answers beyond “the republic”.' },
        locations: [
            { lat: 30.55, lng: 114.30, label: { ko: '우창', en: 'Wuchang' } },
            { lat: 39.90, lng: 116.40, label: { ko: '베이징', en: 'Beijing' } },
            { lat: 32.06, lng: 118.78, label: { ko: '난징', en: 'Nanjing' } },
            { lat: 35.68, lng: 139.69, label: { ko: '도쿄', en: 'Tokyo' } },
            { lat: 23.13, lng: 113.26, label: { ko: '광저우', en: 'Guangzhou' } },
        ],
        timeline: [
            { date: '1905.08', title: { ko: '도쿄에서 중국동맹회 결성', en: 'Tongmenghui founded in Tokyo' }, body: { ko: '쑨원의 흥중회와 화흥회·광복회가 합쳐 「청 타도, 공화 수립, 토지 균등」을 강령으로 삼았다.', en: 'Sun Yat-sen’s Revive China Society merged with other groups on a programme of overthrowing the Qing, founding a republic and equalising land.' }, geo: { kind: 'point', lat: 35.68, lng: 139.69, label: { ko: '도쿄', en: 'Tokyo' } } },
            { date: '1911.05', title: { ko: '철도 국유화와 쓰촨 보로운동', en: 'Railway nationalisation and the Sichuan protests' }, body: { ko: '청 조정이 민영 철도를 외채로 국유화하자 쓰촨의 주주와 신사층이 봉기했고, 진압을 위해 후베이의 신군이 차출되었다.', en: 'When the court nationalised private railways with foreign loans, Sichuan shareholders and gentry rose, and Hubei’s New Army was drawn off to suppress them.' }, geo: { kind: 'point', lat: 30.57, lng: 104.07, label: { ko: '청두', en: 'Chengdu' } } },
            { date: '1911.10.10', title: { ko: '우창 봉기', en: 'Wuchang Uprising' }, body: { ko: '혁명파의 폭탄 사고로 명단이 드러나자 신군 공병대가 먼저 봉기해 하룻밤 사이 우창을 장악했고, 리위안훙이 도독으로 추대되었다.', en: 'After an accidental bomb blast exposed the revolutionaries, New Army engineers rose first and took Wuchang overnight; Li Yuanhong was made military governor.' }, geo: { kind: 'point', lat: 30.55, lng: 114.30, label: { ko: '우창', en: 'Wuchang' } } },
            { date: '1911.10–12', title: { ko: '각 성의 독립 선언', en: 'The provinces declare independence' }, body: { ko: '두 달 안에 24개 성 가운데 15개가 청으로부터의 독립을 선언했다. 대부분은 신군과 지방 신사·입헌파의 타협이었다.', en: 'Within two months fifteen of twenty-four provinces declared independence from the Qing, mostly through compromises between New Army units and local gentry constitutionalists.' }, geo: { kind: 'point', lat: 31.23, lng: 121.47, label: { ko: '상하이', en: 'Shanghai' } } },
            { date: '1912.01.01', title: { ko: '중화민국 임시정부 수립', en: 'Provisional government of the Republic' }, body: { ko: '난징에서 쑨원이 임시대총통에 취임했다. 재정과 군사력은 위안스카이의 북양군에 미치지 못했다.', en: 'Sun Yat-sen was inaugurated provisional president at Nanjing, with neither the money nor the arms to match Yuan Shikai’s Beiyang Army.' }, geo: { kind: 'point', lat: 32.06, lng: 118.78, label: { ko: '난징', en: 'Nanjing' } } },
            { date: '1912.02.12', title: { ko: '선통제 퇴위', en: 'The Xuantong Emperor abdicates' }, body: { ko: '위안스카이의 압박으로 청 조정이 퇴위 조서를 내렸고, 쑨원은 약속대로 총통직을 위안에게 넘겼다.', en: 'Under Yuan’s pressure the court issued the abdication edict, and Sun handed the presidency to Yuan as promised.' }, geo: { kind: 'point', lat: 39.92, lng: 116.39, label: { ko: '베이징 자금성', en: 'Forbidden City, Beijing' } } },
            { date: '1913.03', title: { ko: '쑹자오런 암살과 제2혁명', en: 'Song Jiaoren’s murder and the Second Revolution' }, body: { ko: '총선에서 승리한 국민당의 지도자 쑹자오런이 상하이역에서 피살되었다. 남방 성들의 무장 봉기(제2혁명)는 두 달 만에 진압되었다.', en: 'Song Jiaoren, leader of the Kuomintang that had won the elections, was shot at Shanghai station; the armed rising of the southern provinces was crushed within two months.' }, geo: { kind: 'point', lat: 31.23, lng: 121.47, label: { ko: '상하이', en: 'Shanghai' } } },
            { date: '1914.01', title: { ko: '국회 해산', en: 'Parliament dissolved' }, body: { ko: '위안스카이는 국민당을 해산하고 이어 국회를 정지시켰다. 1914년 약법은 총통에게 사실상 전제권을 주었다.', en: 'Yuan dissolved the Kuomintang and then suspended parliament; the constitutional compact of 1914 gave the president near-absolute power.' } },
            { date: '1915.12', title: { ko: '제정 선포와 호국전쟁', en: 'The monarchy proclaimed and the National Protection War' }, body: { ko: '위안이 「중화제국」 황제를 칭하자 윈난의 차이어가 호국군을 일으켰고 남방 성들이 잇달아 독립을 선언했다.', en: 'When Yuan proclaimed himself emperor, Cai E raised the National Protection Army in Yunnan and the southern provinces declared independence one after another.' }, geo: { kind: 'point', lat: 25.04, lng: 102.71, label: { ko: '쿤밍', en: 'Kunming' } } },
            { date: '1916.06.06', title: { ko: '위안스카이 사망', en: 'Death of Yuan Shikai' }, body: { ko: '제정을 취소한 지 석 달 만에 위안이 병사했다. 북양군은 안후이파·직례파·펑톈파로 갈라져 군벌 시대가 시작되었다.', en: 'Three months after cancelling the monarchy Yuan died; the Beiyang Army split into Anhui, Zhili and Fengtian cliques and the warlord era began.' } },
        ],
        sections: [
            {
                heading: { ko: '무너지는 왕조와 두 개의 대안', en: 'A collapsing dynasty and two alternatives' },
                paragraphs: [
                    { ko: '1895년 청일전쟁 패배와 1900년 의화단 사건 뒤 청 왕조는 신정(新政) 개혁으로 신식 군대와 학교, 지방 자문기구를 만들었다. 개혁은 왕조를 구하기 위한 것이었으나 결과적으로 왕조를 무너뜨릴 세력을 키웠다. 신군 장교와 유학생, 성의 자의국에 모인 신사층은 각기 다른 이유로 만주족 조정에 등을 돌렸다.', en: 'After defeat by Japan in 1895 and the Boxer catastrophe of 1900 the Qing launched the New Policies, creating modern armies, schools and provincial assemblies. The reforms were meant to save the dynasty but bred the forces that would destroy it: New Army officers, returned students and the gentry gathered in provincial assemblies each turned against the Manchu court for their own reasons.', sources: [W + 'Xinhai_Revolution', K + '%EC%8B%A0%ED%95%B4%ED%98%81%EB%AA%85'] },
                    { ko: '두 개의 대안이 경쟁했다. 캉유웨이·량치차오의 입헌파는 황제를 둔 입헌군주제를 원했고, 쑨원의 동맹회는 만주족 축출과 공화국을 내걸었다. 동맹회는 1907~1911년 남방에서 잇달아 봉기를 시도해 모두 실패했지만, 1911년 4월 광저우 황화강 봉기의 희생은 혁명파의 명분을 널리 알렸다.', en: 'Two alternatives competed. The constitutionalists of Kang Youwei and Liang Qichao wanted a constitutional monarchy with the emperor retained; Sun Yat-sen’s Tongmenghui demanded the expulsion of the Manchus and a republic. The Tongmenghui’s risings in the south between 1907 and 1911 all failed, but the martyrs of the Huanghuagang rising at Guangzhou in April 1911 spread the revolutionaries’ cause.', sources: [W + 'Tongmenghui', W + 'Sun_Yat-sen'] },
                ],
            },
            {
                heading: { ko: '철도와 신군: 우창의 하룻밤', en: 'Railways and the New Army: one night at Wuchang' },
                paragraphs: [
                    { ko: '직접적 계기는 철도였다. 1911년 5월 조정이 민간 자본으로 건설 중이던 간선 철도를 외국 차관으로 국유화하자 쓰촨의 주주들이 보로(保路) 운동을 일으켰고 9월에는 무장 충돌로 번졌다. 진압을 위해 후베이 신군의 일부가 쓰촨으로 이동하면서 우한의 방비가 얇아졌다.', en: 'The immediate trigger was the railways. In May 1911 the court nationalised trunk lines that private capital had been building, financing them with foreign loans; Sichuan shareholders launched the Railway Protection Movement, which turned into armed clashes in September. Part of the Hubei New Army was sent to Sichuan to suppress it, thinning the garrison at Wuhan.', sources: [W + 'Xinhai_Revolution', W + 'Wuchang_Uprising'] },
                    { ko: '10월 9일 한커우 러시아 조계에서 혁명파의 폭탄이 터져 명단이 압수되자, 신군 안의 혁명 조직은 검거를 기다리는 대신 10일 밤 봉기했다. 총독은 도주했고 혁명파는 지휘할 명망가가 없어 여단장 리위안훙을 강제로 도독에 앉혔다. 이 즉흥적 봉기가 왕조를 끝낸 것은 청의 통제력이 이미 지방에서 사라져 있었기 때문이다.', en: 'On 9 October a revolutionaries’ bomb exploded in the Russian concession at Hankou and their membership lists were seized; rather than wait for arrest, the revolutionary cells in the New Army rose on the night of the 10th. The viceroy fled, and the rebels, lacking a figure of standing, forced the brigade commander Li Yuanhong to become military governor. This improvised rising ended the dynasty because Qing control had already dissolved in the provinces.', sources: [W + 'Wuchang_Uprising', K + '%EC%8B%A0%ED%95%B4%ED%98%81%EB%AA%85'] },
                ],
            },
            {
                heading: { ko: '타협의 공화국: 쑨원에서 위안스카이로', en: 'A republic by compromise: from Sun to Yuan' },
                paragraphs: [
                    { ko: '조정은 파면했던 위안스카이를 불러 북양군을 맡겼다. 위안은 한커우·한양을 되찾아 군사적 우위를 보인 뒤 혁명파와 협상했고, 동시에 조정에는 퇴위를 압박했다. 미국에서 돌아온 쑨원은 1912년 1월 1일 난징에서 임시대총통에 취임했으나 청 황제가 퇴위하면 자리를 위안에게 넘기겠다고 약속했다.', en: 'The court recalled the dismissed Yuan Shikai and gave him the Beiyang Army. Having shown his military superiority by retaking Hankou and Hanyang, Yuan negotiated with the revolutionaries while pressing the court to abdicate. Sun Yat-sen, back from the United States, was inaugurated provisional president at Nanjing on 1 January 1912, but promised to hand the office to Yuan once the emperor stepped down.', sources: [W + 'Yuan_Shikai', W + 'Sun_Yat-sen'] },
                    { ko: '2월 12일 융유태후가 여섯 살 선통제의 이름으로 퇴위 조서를 내렸다. 조서는 「공화 입헌 국체」를 승인하고 위안스카이에게 임시정부 조직을 맡겼으며, 황실은 자금성 거주와 연 400만 냥의 우대를 받았다. 혁명은 만주족 통치를 끝냈지만 국가기구와 군대는 청의 것을 그대로 물려받았고, 그 정점에 위안이 있었다.', en: 'On 12 February the Empress Dowager Longyu issued the abdication edict in the name of the six-year-old Xuantong Emperor. It endorsed a “constitutional republican polity” and charged Yuan Shikai with forming the provisional government, while the imperial house kept the Forbidden City and an annual subsidy of four million taels. The revolution ended Manchu rule but inherited the Qing state and army intact, with Yuan at their head.', sources: [W + 'Puyi', W + 'Xinhai_Revolution'] },
                ],
            },
            {
                heading: { ko: '국회와 암살: 1913년의 제2혁명', en: 'Parliament and assassination: the Second Revolution of 1913' },
                paragraphs: [
                    { ko: '1912년 8월 동맹회는 다른 정파와 합쳐 국민당이 되었고 쑹자오런의 지휘로 그해 말 총선에서 압승했다. 쑹자오런은 내각책임제로 총통의 권한을 제한하려 했다. 1913년 3월 20일 그는 베이징으로 가는 길에 상하이역에서 총에 맞아 죽었고, 수사는 위안의 측근을 가리켰다.', en: 'In August 1912 the Tongmenghui merged with other groups into the Kuomintang, which under Song Jiaoren won the elections at the end of the year by a landslide. Song intended a cabinet system that would curb the president. On 20 March 1913, on his way to Beijing, he was shot at Shanghai station; the investigation pointed to Yuan’s entourage.', sources: [W + 'Second_Revolution_(Republic_of_China)', W + 'Kuomintang'] },
                    { ko: '위안은 국회의 승인 없이 열강에서 2,500만 파운드의 「선후대차관」을 들여와 군비를 마련했고, 국민당 계열 도독들을 파면했다. 7월 장시·장쑤 등 남방 7성이 봉기했으나(제2혁명) 북양군은 두 달 만에 이를 진압했다. 쑨원과 황싱은 일본으로 망명했고, 11월 위안은 국민당을 불법화하고 이듬해 국회를 정지시켰다.', en: 'Yuan raised a £25 million “Reorganisation Loan” from the powers without parliamentary approval and dismissed the Kuomintang military governors. In July seven southern provinces rose (the Second Revolution), but the Beiyang Army crushed them within two months. Sun Yat-sen and Huang Xing fled to Japan; in November Yuan outlawed the Kuomintang and the next year suspended parliament.', sources: [W + 'Second_Revolution_(Republic_of_China)', W + 'Yuan_Shikai'] },
                ],
            },
            {
                heading: { ko: '황제가 되려 한 대총통', en: 'The president who would be emperor' },
                paragraphs: [
                    { ko: '1915년 일본은 21개조 요구로 산둥의 독일 권익 계승과 만주·내몽골의 특권을 강요했고, 위안은 대부분을 받아들였다. 같은 해 그는 미국인 고문 굿노의 「중국에는 군주제가 적합하다」는 의견서를 앞세워 「주안회」를 조직하고 12월 국민대표대회의 「추대」로 제정을 선포해 1916년을 홍헌(洪憲) 원년으로 정했다.', en: 'In 1915 Japan’s Twenty-One Demands forced the transfer of Germany’s rights in Shandong and special privileges in Manchuria and Inner Mongolia, and Yuan accepted most of them. The same year, citing the American adviser Goodnow’s opinion that monarchy suited China, he organised the Peace Planning Society and in December had a “national representatives’ assembly” acclaim him emperor, naming 1916 the first year of Hongxian.', sources: [W + 'Yuan_Shikai', W + 'Twenty-One_Demands'] },
                    { ko: '반응은 위안의 예상과 달랐다. 12월 25일 윈난에서 차이어와 탕지야오가 호국군을 일으켰고 구이저우·광시가 뒤따랐으며 북양군 안의 장군들도 냉담했다. 위안은 1916년 3월 제정을 취소했으나 퇴진 요구는 계속되었고 6월 요독증으로 죽었다. 그의 죽음으로 북양군을 묶어 두던 마지막 끈이 끊어졌다.', en: 'The reaction was not what Yuan expected. On 25 December Cai E and Tang Jiyao raised the National Protection Army in Yunnan, Guizhou and Guangxi followed, and even the Beiyang generals were cool. Yuan cancelled the monarchy in March 1916, but demands for his resignation continued and he died of uraemia in June. His death cut the last thread that had held the Beiyang Army together.', sources: [W + 'Yuan_Shikai', K + '%EC%8B%A0%ED%95%B4%ED%98%81%EB%AA%85'] },
                ],
            },
            {
                heading: { ko: '군벌 시대의 개막', en: 'The opening of the warlord era' },
                paragraphs: [
                    { ko: '1916년 이후 베이징 정부는 국제적으로 승인된 중국 정부였지만 실권은 군대를 가진 자에게 있었다. 돤치루이의 안후이파, 펑궈장·우페이푸의 직례파, 장쭤린의 펑톈파가 베이징을 번갈아 장악했고, 남방에는 윈난·광시의 독립 군벌이 있었다. 1917년 장쉰의 복벽 소동과 국회 해산 뒤 쑨원은 광저우에서 호법(護法) 정부를 세워 두 개의 정부가 병존했다.', en: 'After 1916 the Beijing government was China’s internationally recognised government, but real power lay with whoever held troops. Duan Qirui’s Anhui clique, the Zhili clique of Feng Guozhang and Wu Peifu and Zhang Zuolin’s Fengtian clique took Beijing in turn, while independent warlords ruled Yunnan and Guangxi. After Zhang Xun’s farcical restoration of 1917 and the dissolution of parliament, Sun Yat-sen set up a Constitutional Protection government at Guangzhou, and two governments coexisted.', sources: [W + 'Beiyang_government', W + 'Constitutional_Protection_Movement'] },
                    { ko: '군벌 전쟁은 세금과 아편, 외국 차관으로 치러졌고 농촌은 징발과 약탈에 시달렸다. 1920년 직환전쟁, 1922년과 1924년의 직봉전쟁이 화베이를 휩쓸었다. 이 혼란은 5·4 세대에게 「공화」가 제도의 이름만으로는 아무것도 보장하지 않는다는 것을 가르쳤고, 쑨원에게는 자기 군대와 대중정당 없는 혁명이 불가능하다는 결론을 남겼다.', en: 'Warlord wars were financed by taxes, opium and foreign loans, and the countryside suffered requisition and plunder. The Zhili–Anhui War of 1920 and the Zhili–Fengtian Wars of 1922 and 1924 swept north China. The chaos taught the May Fourth generation that “the republic” as a name guaranteed nothing, and left Sun Yat-sen with the conclusion that revolution was impossible without an army and a mass party of his own.', sources: [W + 'Warlord_Era', W + 'First_Zhili%E2%80%93Fengtian_War'] },
                ],
            },
            {
                heading: { ko: '해석: 혁명인가, 왕조 교체인가', en: 'Interpretations: revolution or change of dynasty?' },
                paragraphs: [
                    { ko: '신해혁명을 어떻게 볼지는 뒤의 정치와 얽혀 있다. 국민당은 이를 쑨원이 이끈 국민혁명의 출발로, 공산당은 「구민주주의 혁명」의 미완성으로 규정했다. 마오의 「신민주주의론」은 신해혁명이 제국주의와 봉건세력을 타도하지 못한 부르주아 혁명이라며, 그 과제를 프롤레타리아가 이끄는 새 단계가 이어받는다고 썼다.', en: 'How the 1911 revolution is read is bound up with later politics. The Kuomintang made it the beginning of the national revolution led by Sun Yat-sen; the Communists classed it as the unfinished “old democratic revolution”. Mao’s “On New Democracy” called it a bourgeois revolution that had failed to overthrow imperialism and feudalism, whose tasks a new stage led by the proletariat would inherit.', sources: [M + 'volume-2/mswv2_26.htm', W + 'Xinhai_Revolution'] },
                    { ko: '레닌은 1912년 「중국의 민주주의와 나로드니키주의」에서 쑨원의 토지 강령을 러시아 나로드니키에 견주며 아시아의 각성을 반겼다. 역사가들은 혁명이 사회구조를 거의 바꾸지 못했고 지방 신사층의 권력이 오히려 강해졌다는 점, 그럼에도 「황제 없는 중국」이라는 사실 자체가 되돌릴 수 없는 변화였다는 점을 함께 지적한다.', en: 'Lenin, in “Democracy and Narodism in China” (1912), compared Sun’s land programme to the Russian Narodniks and welcomed the awakening of Asia. Historians note that the revolution barely touched the social structure and if anything strengthened the local gentry, while insisting that the bare fact of “a China without an emperor” was itself an irreversible change.', sources: [W + 'Xinhai_Revolution', W + 'Sun_Yat-sen'] },
                ],
            },
        ],
        people: [
            { id: 'sun-yat-sen', kind: 'leader', relation: { ko: '혁명파의 지도자 · 초대 임시대총통', en: 'Leader of the revolutionaries and first provisional president' }, note: { ko: '동맹회를 이끌었고 1912년 1월 난징에서 임시대총통에 취임한 뒤 위안스카이에게 자리를 넘겼다.', en: 'Led the Tongmenghui, took office as provisional president at Nanjing in January 1912 and yielded to Yuan Shikai.' } },
            { id: 'yuan-shikai', kind: 'executor', relation: { ko: '북양군 총수 · 공화국의 첫 대총통', en: 'Beiyang commander and the republic’s first president' }, note: { ko: '청 퇴위와 자신의 총통 취임을 함께 얻어낸 뒤 국회를 해산하고 1915년 제정을 시도했다.', en: 'Secured the Qing abdication and his own presidency, dissolved parliament and attempted a monarchy in 1915.' } },
            { id: 'puyi', kind: 'target', relation: { ko: '퇴위한 마지막 황제', en: 'The abdicated last emperor' }, note: { ko: '여섯 살에 퇴위 조서가 내려졌고 자금성에 남아 우대를 받았다.', en: 'The abdication edict was issued in his name at six; he remained in the Forbidden City under the favourable terms.' } },
            { id: 'wang-jingwei', kind: 'participant', relation: { ko: '동맹회의 젊은 혁명가', en: 'Young Tongmenghui revolutionary' }, note: { ko: '1910년 섭정왕 암살 미수로 투옥되었다가 혁명 뒤 풀려나 쑨원의 측근이 되었다.', en: 'Imprisoned after the 1910 attempt on the regent, freed by the revolution and became Sun’s confidant.' } },
            { id: 'chiang-kai-shek', kind: 'participant', relation: { ko: '상하이 봉기의 청년 장교', en: 'Young officer in the Shanghai rising' }, note: { ko: '일본에서 돌아와 1911년 11월 상하이·항저우 봉기에 참여했다.', en: 'Returned from Japan to take part in the Shanghai and Hangzhou risings of November 1911.' } },
            { id: 'zhang-zuolin', kind: 'participant', relation: { ko: '혁명기에 세력을 굳힌 만주 군벌', en: 'Manchurian strongman who consolidated during the revolution' }, note: { ko: '펑톈에서 혁명파를 진압하며 세력을 키워 뒤에 펑톈파 군벌이 되었다.', en: 'Built his power in Fengtian by suppressing the revolutionaries there, becoming the Fengtian warlord.' } },
            { id: 'lenin', kind: 'witness', relation: { ko: '「중국의 민주주의와 나로드니키주의」(1912)', en: '“Democracy and Narodism in China” (1912)' }, note: { ko: '쑨원의 강령을 러시아 나로드니키에 견주며 아시아의 각성으로 평가했다.', en: 'Compared Sun’s programme to the Russian Narodniks and hailed the awakening of Asia.' } },
        ],
        related: ['may-fourth-and-ccp-founding', 'first-united-front-1924-1927'],
    },
    {
        id: 'may-fourth-and-ccp-founding', sortOrder: 44, period: '1915–1921', countries: ['china', 'japan'],
        title: { ko: '5·4 운동과 중국공산당의 창당', en: 'May Fourth and the founding of the Chinese Communist Party' },
        question: { ko: '신문화운동의 「과학과 민주」는 어떻게 마르크스주의와 정당 창건으로 이어졌는가?', en: 'How did the New Culture Movement’s “science and democracy” lead to Marxism and the founding of a party?' },
        summary: { ko: '1915년 『신청년』이 연 신문화운동은 유교와 낡은 문체를 공격했고, 1919년 5월 4일 베르사유의 산둥 결정에 항의한 학생 시위가 전국의 파업으로 번졌다. 러시아 혁명의 충격 속에 리다자오·천두슈가 마르크스주의로 옮겨 갔고, 코민테른의 지원으로 1921년 7월 상하이에서 중국공산당이 창당되었다.', en: 'The New Culture Movement opened by New Youth in 1915 attacked Confucianism and the classical style; on 4 May 1919 student protests against the Versailles decision on Shandong grew into nationwide strikes. Under the impact of the Russian Revolution Li Dazhao and Chen Duxiu turned to Marxism, and with Comintern support the Chinese Communist Party was founded in Shanghai in July 1921.' },
        outcome: { ko: '백화문과 「과학·민주」는 지식층의 공통 언어가 되었고, 운동은 자유주의(후스)와 마르크스주의(천두슈·리다자오)로 갈라졌다. 창당 당시 50여 명이던 공산당은 코민테른의 「당내 합작」 지시에 따라 국민당과 손잡는 길로 들어섰다.', en: 'The vernacular and “science and democracy” became the common language of the educated, and the movement split into liberalism (Hu Shih) and Marxism (Chen Duxiu, Li Dazhao). The party of some fifty members at its founding was soon directed by the Comintern into a “bloc within” the Kuomintang.' },
        locations: [
            { lat: 39.91, lng: 116.40, label: { ko: '베이징 톈안먼', en: 'Tiananmen, Beijing' } },
            { lat: 31.22, lng: 121.47, label: { ko: '상하이 프랑스 조계', en: 'Shanghai French Concession' } },
            { lat: 36.07, lng: 120.38, label: { ko: '칭다오', en: 'Qingdao' } },
            { lat: 48.80, lng: 2.13, label: { ko: '베르사유', en: 'Versailles' } },
            { lat: 30.26, lng: 120.20, label: { ko: '자싱 남호', en: 'South Lake, Jiaxing' } },
        ],
        timeline: [
            { date: '1915.09', title: { ko: '『청년잡지』(신청년) 창간', en: 'New Youth founded' }, body: { ko: '천두슈가 상하이에서 창간해 「과학과 민주」를 내걸고 유교 윤리를 공격했다.', en: 'Chen Duxiu launched the magazine in Shanghai, raising “science and democracy” against Confucian ethics.' }, geo: { kind: 'point', lat: 31.22, lng: 121.47, label: { ko: '상하이', en: 'Shanghai' } } },
            { date: '1917.01', title: { ko: '후스의 「문학개량추의」', en: 'Hu Shih’s “Tentative proposals for literary reform”' }, body: { ko: '백화문으로 글을 쓰자는 제안이 『신청년』에 실려 문학혁명이 시작되었다.', en: 'The proposal to write in the vernacular appeared in New Youth and the literary revolution began.' } },
            { date: '1918.05', title: { ko: '루쉰의 「광인일기」', en: 'Lu Xun’s “Diary of a Madman”' }, body: { ko: '최초의 백화 단편소설이 「식인」의 예교를 고발했다.', en: 'The first vernacular short story indicted the “man-eating” Confucian order.' } },
            { date: '1918.11', title: { ko: '리다자오의 「볼셰비즘의 승리」', en: 'Li Dazhao’s “The victory of Bolshevism”' }, body: { ko: '베이징대 도서관장 리다자오가 러시아 혁명을 세계사의 새 시대로 환영했다.', en: 'Li Dazhao, Peking University’s librarian, hailed the Russian Revolution as a new era of world history.' }, geo: { kind: 'point', lat: 39.93, lng: 116.40, label: { ko: '베이징대학', en: 'Peking University' } } },
            { date: '1919.04.30', title: { ko: '베르사유의 산둥 결정', en: 'Versailles decides on Shandong' }, body: { ko: '강화회의가 독일의 산둥 권익을 중국이 아니라 일본에 넘기기로 했다.', en: 'The peace conference transferred Germany’s Shandong rights to Japan rather than China.' }, country: ['china', 'japan'], geo: { kind: 'point', lat: 48.80, lng: 2.13, label: { ko: '베르사유', en: 'Versailles' } } },
            { date: '1919.05.04', title: { ko: '톈안먼의 학생 시위', en: 'Student demonstration at Tiananmen' }, body: { ko: '13개 대학 3천여 명이 시위했고 친일 관료 차오루린의 집이 불탔다. 32명이 체포되었다.', en: 'Some three thousand students from thirteen colleges marched; the house of the pro-Japanese official Cao Rulin was burned and thirty-two students arrested.' }, geo: { kind: 'point', lat: 39.91, lng: 116.40, label: { ko: '톈안먼', en: 'Tiananmen' } } },
            { date: '1919.06.05', title: { ko: '상하이 총파업', en: 'Shanghai general strike' }, body: { ko: '노동자·상인이 파업과 철시에 나서면서 운동은 학생 시위를 넘어섰다. 정부는 관료 3명을 파면하고 조약 서명을 거부했다.', en: 'Workers and merchants struck and shut their shops, carrying the movement beyond the students; the government dismissed three officials and refused to sign the treaty.' }, geo: { kind: 'point', lat: 31.23, lng: 121.47, label: { ko: '상하이', en: 'Shanghai' } } },
            { date: '1920.04', title: { ko: '보이틴스키의 방문', en: 'Voitinsky’s mission' }, body: { ko: '코민테른 극동국의 보이틴스키가 리다자오·천두슈를 만나 공산주의 소조 결성을 도왔다.', en: 'Grigory Voitinsky of the Comintern met Li Dazhao and Chen Duxiu and helped form communist cells.' } },
            { date: '1921.07.23', title: { ko: '중국공산당 제1차 전국대표대회', en: 'First Congress of the Chinese Communist Party' }, body: { ko: '상하이 프랑스 조계에서 13명의 대표와 마링·니콜스키가 모였고, 경찰 수색을 피해 자싱 남호의 배 위에서 폐회했다.', en: 'Thirteen delegates met with Maring and Nikolsky in the French Concession and, after a police search, closed the congress on a boat on South Lake at Jiaxing.' }, geo: { kind: 'point', lat: 31.22, lng: 121.47, label: { ko: '상하이 프랑스 조계', en: 'Shanghai French Concession' } } },
        ],
        sections: [
            {
                heading: { ko: '『신청년』과 문화의 혁명', en: 'New Youth and the revolution in culture' },
                paragraphs: [
                    { ko: '위안스카이의 제정 시도가 실패한 1915년, 천두슈는 상하이에서 『청년잡지』를 창간해 청년에게 「자주적·진보적·과학적」이 되라고 요구했다. 잡지는 공자의 윤리가 전제정치의 토대라고 공격했고, 「덕 선생(민주)과 새 선생(과학)」이 구호가 되었다. 1917년 차이위안페이가 베이징대 총장이 되어 천두슈를 문과대학장으로 부르면서 잡지는 대학과 결합했다.', en: 'In 1915, as Yuan Shikai’s monarchy collapsed, Chen Duxiu founded Youth Magazine in Shanghai and called on the young to be “independent, progressive and scientific”. The magazine attacked Confucian ethics as the foundation of despotism, and “Mr Democracy and Mr Science” became its slogan. When Cai Yuanpei became chancellor of Peking University in 1917 and made Chen dean of letters, the magazine joined forces with the university.', sources: [W + 'New_Culture_Movement', W + 'Chen_Duxiu'] },
                    { ko: '후스는 1917년 1월 문어체 대신 백화문으로 쓰자고 제안했고, 천두슈는 이를 「문학혁명」으로 밀어붙였다. 1918년 루쉰의 「광인일기」는 새 문체로 낡은 사회를 「식인」의 역사로 고발했다. 백화문은 몇 년 안에 교과서와 신문의 문체가 되었고, 이 언어 혁명이 뒤에 대중정당의 선전을 가능하게 했다.', en: 'In January 1917 Hu Shih proposed writing in the vernacular instead of the classical language, and Chen Duxiu pushed it as a “literary revolution”. Lu Xun’s “Diary of a Madman” of 1918 used the new style to indict the old society as a history of “eating people”. Within a few years the vernacular was the language of textbooks and newspapers, and this revolution in language later made mass-party propaganda possible.', sources: [W + 'Hu_Shih', W + 'Lu_Xun'] },
                ],
            },
            {
                heading: { ko: '1919년 5월 4일', en: '4 May 1919' },
                paragraphs: [
                    { ko: '중국은 1917년 연합국 편으로 참전해 14만 명의 노동자를 유럽에 보냈고, 전승국으로서 독일이 산둥에 가진 권익의 반환을 기대했다. 그러나 1915년 21개조와 1918년 돤치루이 정부가 일본과 맺은 비밀 차관 협정은 일본의 계승을 사실상 인정하고 있었고, 4월 30일 파리 강화회의는 산둥을 일본에 넘겼다.', en: 'China had entered the war on the Allied side in 1917, sending 140,000 labourers to Europe, and expected as a victor the return of Germany’s rights in Shandong. But the Twenty-One Demands of 1915 and the secret loan agreements Duan Qirui’s government had signed with Japan in 1918 had effectively conceded Japanese succession, and on 30 April the Paris conference gave Shandong to Japan.', sources: [W + 'Shandong_Problem', W + 'May_Fourth_Movement'] },
                    { ko: '소식이 전해지자 5월 4일 베이징의 13개 대학 학생 3천여 명이 톈안먼에 모여 「밖으로 국권을 다투고 안으로 국적(國賊)을 징벌하라」고 외쳤다. 시위대는 친일 관료 차오루린의 집을 불태웠고 32명이 체포되었다. 이어진 동맹휴학과 6월 초 상하이의 노동자 파업·상인 철시는 정부를 굴복시켰다. 관료 세 명이 파면되었고 중국 대표단은 베르사유 조약에 서명하지 않았다.', en: 'When the news arrived, on 4 May some three thousand students from thirteen Beijing colleges gathered at Tiananmen shouting “Struggle for sovereignty abroad, punish the traitors at home”. They burned the house of the pro-Japanese official Cao Rulin, and thirty-two were arrested. The student strikes that followed and the workers’ strike and merchants’ shutdown in Shanghai in early June forced the government to yield: three officials were dismissed and the Chinese delegation refused to sign the Treaty of Versailles.', sources: [W + 'May_Fourth_Movement', K + '5%C2%B74_%EC%9A%B4%EB%8F%99'] },
                ],
            },
            {
                heading: { ko: '「문제와 주의」: 운동의 분화', en: '“Problems and isms”: the movement divides' },
                paragraphs: [
                    { ko: '1919년 여름 후스는 「문제를 많이 연구하고 주의를 적게 말하라」며 점진적 개혁을 주장했고, 리다자오는 「근본적 해결」 없이는 개별 문제도 풀 수 없다고 답했다. 이 논쟁은 신문화운동이 자유주의와 마르크스주의로 갈라지는 지점이었다. 같은 해 『신청년』은 리다자오가 편집한 마르크스주의 특집호를 냈다.', en: 'In summer 1919 Hu Shih urged “more study of problems, less talk of isms” and gradual reform; Li Dazhao replied that without a “fundamental solution” no individual problem could be solved. The exchange marked the point where the New Culture Movement split into liberalism and Marxism. That year New Youth published a special issue on Marxism edited by Li Dazhao.', sources: [W + 'Li_Dazhao', W + 'Hu_Shih'] },
                    { ko: '러시아 혁명은 이 전환의 배경이었다. 1919년 7월 소비에트 정부의 카라한 선언은 제정 러시아가 중국에서 얻은 특권을 포기하겠다고 밝혀 베르사유의 열강과 대비되었다. 리다자오는 「볼셰비즘의 승리」에서 이를 세계 노동자의 승리로 읽었고, 천두슈는 1920년 노동자와 결합하는 정당의 필요를 말하기 시작했다. 젊은 마오쩌둥·저우언라이·장궈타오가 이 시기에 마르크스주의를 접했다.', en: 'The Russian Revolution was the background to this turn. In July 1919 the Soviet government’s Karakhan declaration renounced the privileges tsarist Russia had gained in China, in pointed contrast to the powers at Versailles. Li Dazhao read it in “The victory of Bolshevism” as a victory of the world’s workers, and by 1920 Chen Duxiu was speaking of the need for a party joined to the workers. The young Mao Zedong, Zhou Enlai and Zhang Guotao encountered Marxism in these years.', sources: [W + 'Li_Dazhao', W + 'Chinese_Communist_Party'] },
                ],
            },
            {
                heading: { ko: '코민테른의 손길', en: 'The Comintern’s hand' },
                paragraphs: [
                    { ko: '1920년 4월 코민테른 극동국의 그리고리 보이틴스키가 베이징에서 리다자오를, 상하이에서 천두슈를 만났다. 그의 도움으로 여름에 상하이 공산주의 소조가 만들어졌고 베이징·창사·우한·광저우·지난과 도쿄·파리의 유학생 사이에 같은 조직이 생겼다. 소조들은 『공산당』 월간과 노동자 야학을 운영했다.', en: 'In April 1920 Grigory Voitinsky of the Comintern’s Far Eastern Bureau met Li Dazhao in Beijing and Chen Duxiu in Shanghai. With his help a Shanghai communist cell was formed that summer, and similar groups followed in Beijing, Changsha, Wuhan, Guangzhou and Jinan and among students in Tokyo and Paris. The cells ran a monthly, The Communist, and night schools for workers.', sources: [W + 'Chinese_Communist_Party', W + 'Chen_Duxiu'] },
                    { ko: '1921년 6월 코민테른 대표 마링(스네블릿)과 니콜스키가 상하이에 도착해 전국대회를 재촉했다. 7월 23일 프랑스 조계의 한 주택에서 각지 소조를 대표하는 13명이 모였다. 천두슈와 리다자오는 참석하지 않았고, 마오쩌둥은 창사 대표, 장궈타오는 의장이었다. 경찰의 수색으로 대회는 저장성 자싱의 남호 유람선 위로 옮겨 폐회했고, 천두슈가 서기로 선출되었다.', en: 'In June 1921 the Comintern representatives Maring (Sneevliet) and Nikolsky reached Shanghai and pressed for a national congress. On 23 July thirteen delegates representing the cells met in a house in the French Concession. Chen Duxiu and Li Dazhao were absent; Mao Zedong represented Changsha and Zhang Guotao chaired. A police search forced the congress to close on a pleasure boat on South Lake at Jiaxing in Zhejiang, and Chen Duxiu was elected secretary.', sources: [W + 'Chinese_Communist_Party', W + 'Zhang_Guotao'] },
                ],
            },
            {
                heading: { ko: '창당 강령과 노동운동', en: 'The founding programme and the labour movement' },
                paragraphs: [
                    { ko: '제1차 대회의 강령은 프롤레타리아 혁명군으로 부르주아지를 타도하고 사유재산을 폐지한다는 순수한 계급 노선이었으며, 다른 정당과의 제휴를 배제했다. 당은 「노동조합 서기부」를 세워 1922년 1월 홍콩 선원 파업, 9월 안위안 탄광 파업(리리싼·류사오치), 1923년 2월 징한 철도 파업을 조직했다. 2·7 참사로 불리는 철도 파업의 유혈 진압은 노동자만의 힘으로는 군벌을 이길 수 없음을 보여주었다.', en: 'The First Congress programme was a pure class line — overthrow the bourgeoisie with a proletarian revolutionary army, abolish private property — and ruled out alliance with other parties. The party set up a Labour Secretariat and organised the Hong Kong seamen’s strike of January 1922, the Anyuan miners’ strike of September (Li Lisan, Liu Shaoqi) and the Beijing–Hankou railway strike of February 1923. The bloody suppression of the railway strike, the “February Seventh massacre”, showed that workers alone could not defeat the warlords.', sources: [W + 'Chinese_Communist_Party', W + 'Li_Lisan'] },
                    { ko: '코민테른은 이미 1920년 제2차 대회에서 식민지·반식민지의 공산당이 민족 부르주아지의 혁명운동과 협력해야 한다고 결의했다. 마링은 쑨원의 국민당을 그 상대로 보고 1922년 8월 항저우 회의에서 「당내 합작」을 지시했고, 천두슈 등의 반대에도 코민테른의 규율이 관철되었다. 1923년 6월 제3차 대회는 공산당원의 국민당 가입을 결의해 다음 국면을 열었다.', en: 'The Comintern had resolved at its Second Congress in 1920 that communist parties in colonial and semi-colonial countries must cooperate with the revolutionary movement of the national bourgeoisie. Maring saw Sun Yat-sen’s Kuomintang as that partner and at the Hangzhou meeting of August 1922 directed a “bloc within”; despite objections from Chen Duxiu and others, Comintern discipline prevailed. The Third Congress of June 1923 resolved that Communists would join the Kuomintang, opening the next phase.', sources: [W + 'First_United_Front', W + 'Henk_Sneevliet'] },
                ],
            },
            {
                heading: { ko: '유산: 5·4의 두 계보', en: 'Legacy: the two lineages of May Fourth' },
                paragraphs: [
                    { ko: '5·4 운동은 이후 모든 중국 정치세력이 자기 것으로 주장하는 사건이 되었다. 공산당은 1939년 마오의 규정에 따라 5·4를 「신민주주의 혁명」의 출발점으로 삼고 5월 4일을 청년절로 정했으며, 국민당과 대만은 이를 문예절로 기념했다. 1989년 톈안먼 광장의 학생들도 5·4 70주년을 자신들의 날로 불렀다.', en: 'May Fourth became an event every Chinese political force claimed as its own. Following Mao’s 1939 definition, the Communists made it the starting point of the “new democratic revolution” and declared 4 May Youth Day; the Kuomintang and Taiwan commemorated it as Literature Day. The students in Tiananmen Square in 1989 called the seventieth anniversary of May Fourth their own day.', sources: [W + 'May_Fourth_Movement', M + 'volume-2/mswv2_26.htm'] },
                    { ko: '역사가들은 신문화운동의 「전면적 반전통」이 뒤의 급진주의를 예비했다고 보는 견해와, 운동이 자유주의·무정부주의·마르크스주의가 공존한 열린 공간이었으며 그 다원성이 1927년 이후 정치에 의해 닫혔다고 보는 견해로 나뉜다. 후스와 천두슈가 같은 잡지에서 출발해 정반대의 길로 간 것은 이 시기의 성격을 압축한다.', en: 'Historians divide between those who see the New Culture Movement’s “total anti-traditionalism” as preparing later radicalism, and those who see the movement as an open space where liberalism, anarchism and Marxism coexisted, a plurality closed down by politics after 1927. That Hu Shih and Chen Duxiu began in the same magazine and went opposite ways sums up the character of these years.', sources: [W + 'New_Culture_Movement', W + 'Hu_Shih'] },
                ],
            },
        ],
        people: [
            { id: 'chen-duxiu', kind: 'leader', relation: { ko: '『신청년』 창간인 · 초대 당 서기', en: 'Founder of New Youth and first party secretary' }, note: { ko: '신문화운동의 기수였고 1921년 창당 대회에서 서기로 선출되었다.', en: 'Standard-bearer of the New Culture Movement, elected secretary at the 1921 founding congress.' } },
            { id: 'li-dazhao', kind: 'leader', relation: { ko: '중국 최초의 마르크스주의자', en: 'China’s first Marxist' }, note: { ko: '베이징대 도서관장으로 「볼셰비즘의 승리」를 썼고 베이징 소조를 세웠다.', en: 'As Peking University librarian wrote “The victory of Bolshevism” and founded the Beijing cell.' } },
            { id: 'hu-shih', kind: 'participant', relation: { ko: '백화문 운동의 제창자', en: 'Proponent of the vernacular movement' }, note: { ko: '「문학개량추의」로 문학혁명을 열었고 「문제와 주의」 논쟁에서 자유주의 쪽에 섰다.', en: 'Opened the literary revolution and took the liberal side in the “problems and isms” debate.' } },
            { id: 'lu-xun', kind: 'participant', relation: { ko: '「광인일기」의 작가', en: 'Author of “Diary of a Madman”' }, note: { ko: '최초의 백화 단편으로 신문화운동의 문학을 대표했다.', en: 'Wrote the first vernacular short story, the movement’s defining literary work.' } },
            { id: 'mao-zedong', kind: 'participant', relation: { ko: '창사 대표로 창당 대회 참석', en: 'Changsha delegate to the founding congress' }, note: { ko: '베이징대 도서관 조수로 리다자오 밑에서 일했고 1921년 대회에 참석했다.', en: 'Worked under Li Dazhao as a library assistant and attended the 1921 congress.' } },
            { id: 'zhang-guotao', kind: 'participant', relation: { ko: '5·4 학생 지도자 · 창당 대회 의장', en: 'May Fourth student leader and congress chairman' }, note: { ko: '베이징대 학생회를 이끌었고 1921년 제1차 대회를 주재했다.', en: 'Led the Peking University students and chaired the First Congress.' } },
            { id: 'grigory-voitinsky', kind: 'participant', relation: { ko: '코민테른 극동국 대표', en: 'Comintern Far Eastern Bureau envoy' }, note: { ko: '1920년 리다자오·천두슈를 만나 공산주의 소조 결성을 도왔다.', en: 'Met Li Dazhao and Chen Duxiu in 1920 and helped form the first cells.' } },
            { id: 'henk-sneevliet', kind: 'participant', relation: { ko: '「마링」, 창당 대회의 코민테른 대표', en: '“Maring”, Comintern representative at the founding' }, note: { ko: '제1차 대회에 참석했고 1922년 국민당과의 당내 합작을 지시했다.', en: 'Attended the First Congress and in 1922 directed the bloc within the Kuomintang.' } },
            { id: 'qu-qiubai', kind: 'participant', relation: { ko: '모스크바 특파원 출신의 초기 이론가', en: 'Early theorist back from Moscow' }, note: { ko: '1920~1922년 모스크바에서 러시아 혁명을 취재하고 돌아와 당의 이론가가 되었다.', en: 'Reported from Moscow in 1920–1922 and returned to become a party theorist.' } },
            { id: 'zhou-enlai', kind: 'participant', relation: { ko: '톈진 각오사와 파리 지부', en: 'Tianjin Awakening Society and the Paris branch' }, note: { ko: '톈진에서 5·4 시위로 투옥되었고 프랑스에서 유럽 지부를 조직했다.', en: 'Jailed for May Fourth protests in Tianjin and organised the European branch in France.' } },
            { id: 'lev-karakhan', kind: 'witness', relation: { ko: '카라한 선언(1919)', en: 'The Karakhan declaration (1919)' }, note: { ko: '제정 러시아의 대중국 특권 포기를 선언해 지식인의 소련관에 영향을 주었다.', en: 'Renounced tsarist privileges in China, shaping how Chinese intellectuals saw Soviet Russia.' } },
        ],
        related: ['xinhai-revolution-1911', 'first-united-front-1924-1927'],
    },
    {
        id: 'first-united-front-1924-1927', sortOrder: 63, period: '1924–1927', countries: ['china', 'soviet'],
        title: { ko: '제1차 국공합작과 북벌, 1927년의 파국', en: 'The first united front, the Northern Expedition and the catastrophe of 1927' },
        question: { ko: '군벌을 무너뜨린 국민혁명은 왜 그 동맹자인 공산당을 학살하는 것으로 끝났는가?', en: 'Why did the national revolution that toppled the warlords end by massacring its Communist allies?' },
        summary: { ko: '소련의 원조와 코민테른의 지시로 공산당원이 국민당에 가입한 국공합작은 황푸군관학교와 북벌로 군벌 중국을 흔들었다. 그러나 노동자·농민 운동이 커지자 장제스는 1927년 4월 상하이에서 공산당을 학살했고, 스탈린이 기대한 우한의 국민당 좌파도 7월 공산당과 결별했다.', en: 'With Soviet aid and on Comintern orders, Communists joined the Kuomintang; the united front built the Whampoa Academy and launched the Northern Expedition that shook warlord China. But as the workers’ and peasants’ movements grew, Chiang Kai-shek massacred the Communists in Shanghai in April 1927, and the Wuhan Kuomintang left on which Stalin had counted broke with them in July.' },
        outcome: { ko: '국민당은 난징에 통일 정부를 세웠고 공산당은 도시에서 사실상 소멸해 무장 봉기와 농촌 근거지로 방향을 바꿨다. 모스크바에서는 중국 정책의 실패가 스탈린-트로츠키 투쟁의 쟁점이 되었고, 중국에서는 마오의 「총구에서 정권이 나온다」가 교훈으로 남았다.', en: 'The Kuomintang set up a unified government at Nanjing; the Communists were all but wiped out in the cities and turned to armed uprisings and rural bases. In Moscow the failure of China policy became an issue in the Stalin–Trotsky struggle; in China the lesson that survived was Mao’s “political power grows out of the barrel of a gun”.' },
        locations: [
            { lat: 23.13, lng: 113.26, label: { ko: '광저우', en: 'Guangzhou' } },
            { lat: 31.23, lng: 121.47, label: { ko: '상하이', en: 'Shanghai' } },
            { lat: 30.59, lng: 114.30, label: { ko: '우한', en: 'Wuhan' } },
            { lat: 32.06, lng: 118.78, label: { ko: '난징', en: 'Nanjing' } },
            { lat: 28.23, lng: 112.94, label: { ko: '창사', en: 'Changsha' } },
            { lat: 55.75, lng: 37.62, label: { ko: '모스크바', en: 'Moscow' } },
        ],
        timeline: [
            { date: '1923.01.26', title: { ko: '쑨원-요페 공동선언', en: 'Sun–Joffe joint statement' }, body: { ko: '소련이 국민당을 지원하되 소비에트 제도를 중국에 적용하지 않는다고 확인했다.', en: 'The Soviet Union would aid the Kuomintang while agreeing that the soviet system did not suit China.' }, country: ['china', 'soviet'], geo: { kind: 'point', lat: 31.23, lng: 121.47, label: { ko: '상하이', en: 'Shanghai' } } },
            { date: '1924.01', title: { ko: '국민당 제1차 전국대표대회', en: 'First Kuomintang Congress' }, body: { ko: '보로딘이 기초한 당 규약으로 국민당을 개조했고 공산당원 리다자오 등이 중앙집행위원이 되었다.', en: 'The party was reorganised on a constitution drafted by Borodin; Communists including Li Dazhao joined the Central Executive Committee.' }, geo: { kind: 'point', lat: 23.13, lng: 113.26, label: { ko: '광저우', en: 'Guangzhou' } } },
            { date: '1924.06', title: { ko: '황푸군관학교 개교', en: 'Whampoa Military Academy opens' }, body: { ko: '장제스가 교장, 저우언라이가 정치부 주임이었고 소련 고문단이 훈련을 맡았다.', en: 'Chiang Kai-shek was commandant, Zhou Enlai head of the political department, and Soviet advisers ran the training.' }, country: ['china', 'soviet'], geo: { kind: 'point', lat: 23.10, lng: 113.43, label: { ko: '황푸', en: 'Whampoa' } } },
            { date: '1925.03.12', title: { ko: '쑨원 사망', en: 'Death of Sun Yat-sen' }, body: { ko: '베이징에서 간암으로 죽었다. 국민당 안의 좌우 대립이 표면화되었다.', en: 'He died of liver cancer in Beijing; the left–right split inside the Kuomintang came into the open.' }, geo: { kind: 'point', lat: 39.90, lng: 116.40, label: { ko: '베이징', en: 'Beijing' } } },
            { date: '1925.05.30', title: { ko: '5·30 운동', en: 'May Thirtieth Movement' }, body: { ko: '상하이 조계 경찰이 시위대에 발포해 13명이 죽자 전국적 반제국주의 파업이 일어났고 공산당원이 급증했다.', en: 'Concession police fired on demonstrators in Shanghai, killing thirteen; nationwide anti-imperialist strikes followed and party membership surged.' }, geo: { kind: 'point', lat: 31.23, lng: 121.47, label: { ko: '상하이', en: 'Shanghai' } } },
            { date: '1926.03.20', title: { ko: '중산함 사건', en: 'The Zhongshan Warship incident' }, body: { ko: '장제스가 계엄을 선포해 공산당원 정치위원과 소련 고문을 일시 구금했다. 합작은 유지되었으나 공산당의 국민당 내 지위는 제한되었다.', en: 'Chiang declared martial law and briefly detained Communist commissars and Soviet advisers; the front survived but Communists’ positions in the KMT were curtailed.' }, geo: { kind: 'point', lat: 23.13, lng: 113.26, label: { ko: '광저우', en: 'Guangzhou' } } },
            { date: '1926.07', title: { ko: '북벌 개시', en: 'The Northern Expedition begins' }, body: { ko: '국민혁명군 10만이 광저우를 떠나 우페이푸·쑨촨팡의 군벌군을 격파하며 북상했다.', en: 'A hundred thousand National Revolutionary Army troops left Guangzhou and drove north against Wu Peifu and Sun Chuanfang.' }, geo: { kind: 'arrow', points: [[23.13, 113.26], [28.23, 112.94], [30.59, 114.30]], label: { ko: '광저우 → 창사 → 우한 (개략)', en: 'Guangzhou → Changsha → Wuhan (schematic)' }, actor: { ko: '국민혁명군', en: 'National Revolutionary Army' } } },
            { date: '1927.03', title: { ko: '마오의 「후난 농민운동 고찰 보고」', en: 'Mao’s Hunan peasant movement report' }, body: { ko: '농민협회의 폭력적 「과도함」을 옹호하며 농민을 혁명의 주력으로 규정했다.', en: 'Defended the peasant associations’ “excesses” and cast the peasantry as the main force of the revolution.' }, geo: { kind: 'point', lat: 28.23, lng: 112.94, label: { ko: '창사', en: 'Changsha' } } },
            { date: '1927.03.21', title: { ko: '상하이 노동자 무장봉기', en: 'Shanghai workers’ armed uprising' }, body: { ko: '저우언라이가 지휘한 노동자 규찰대가 군벌군을 몰아내고 국민혁명군에 앞서 상하이를 장악했다.', en: 'Worker pickets led by Zhou Enlai drove out the warlord garrison and took Shanghai ahead of the National Revolutionary Army.' }, geo: { kind: 'point', lat: 31.23, lng: 121.47, label: { ko: '상하이', en: 'Shanghai' } } },
            { date: '1927.04.12', title: { ko: '4·12 정변 (상하이 학살)', en: 'The 12 April coup (Shanghai massacre)' }, body: { ko: '장제스가 청방과 군대를 동원해 노동자 규찰대를 무장해제하고 공산당원 수백 명을 처형했다.', en: 'Chiang used the Green Gang and his troops to disarm the pickets and execute hundreds of Communists.' }, geo: { kind: 'point', lat: 31.23, lng: 121.47, label: { ko: '상하이', en: 'Shanghai' } } },
            { date: '1927.07.15', title: { ko: '우한 정부의 분공', en: 'Wuhan breaks with the Communists' }, body: { ko: '왕징웨이의 국민당 좌파가 공산당원을 축출했다. 보로딘과 소련 고문단은 소련으로 돌아갔다.', en: 'Wang Jingwei’s Kuomintang left expelled the Communists; Borodin and the Soviet advisers went home.' }, country: ['china', 'soviet'], geo: { kind: 'point', lat: 30.59, lng: 114.30, label: { ko: '우한', en: 'Wuhan' } } },
            { date: '1927.08.01', title: { ko: '난창 봉기', en: 'Nanchang Uprising' }, body: { ko: '저우언라이·허룽·주더가 이끈 국민혁명군 일부가 봉기했다. 인민해방군은 이날을 건군일로 삼는다.', en: 'Units led by Zhou Enlai, He Long and Zhu De rose at Nanchang; the People’s Liberation Army dates its founding to this day.' }, geo: { kind: 'point', lat: 28.68, lng: 115.86, label: { ko: '난창', en: 'Nanchang' } } },
        ],
        sections: [
            {
                heading: { ko: '모스크바가 광저우를 택하다', en: 'Moscow chooses Guangzhou' },
                paragraphs: [
                    { ko: '1922년 영국·미국에 거듭 거절당한 쑨원은 소련으로 눈을 돌렸다. 1923년 1월 상하이에서 소련 대표 아돌프 요페와 낸 공동선언은 「공산주의나 소비에트 제도는 중국에 도입할 수 없다」고 확인하면서도 소련의 지원을 약속했다. 그해 가을 코민테른이 보낸 미하일 보로딘이 광저우에 도착해 국민당을 레닌주의 정당으로 개조하는 작업을 시작했다.', en: 'Rebuffed repeatedly by Britain and the United States in 1922, Sun Yat-sen turned to the Soviet Union. His joint statement with the Soviet envoy Adolph Joffe in Shanghai in January 1923 affirmed that “communism or the soviet system cannot be introduced into China” while promising Soviet support. That autumn Mikhail Borodin, sent by the Comintern, arrived in Guangzhou and began rebuilding the Kuomintang as a Leninist party.', sources: [W + 'First_United_Front', W + 'Mikhail_Borodin'] },
                    { ko: '1924년 1월 국민당 제1차 전국대표대회는 보로딘이 기초한 규약을 채택해 민주집중제와 당 조직을 도입했고, 리다자오·탄핑산 등 공산당원이 중앙집행위원이 되었다. 쑨원은 「연소·용공·부조농공」을 새 삼민주의의 정책으로 삼았다. 소련은 무기와 자금을 보냈고 6월 황푸군관학교가 문을 열어 장제스가 교장, 저우언라이가 정치부 주임을 맡았다.', en: 'In January 1924 the Kuomintang’s First Congress adopted Borodin’s constitution, introducing democratic centralism and a party apparatus, and Communists including Li Dazhao and Tan Pingshan joined the Central Executive Committee. Sun made “alliance with Russia, admission of Communists, assistance to workers and peasants” the policies of his reinterpreted Three Principles. The Soviets sent arms and money, and in June the Whampoa Military Academy opened with Chiang Kai-shek as commandant and Zhou Enlai as head of its political department.', sources: [W + 'Whampoa_Military_Academy', W + 'Sun_Yat-sen'] },
                ],
            },
            {
                heading: { ko: '「당내 합작」의 논리', en: 'The logic of the “bloc within”' },
                paragraphs: [
                    { ko: '공산당원이 국민당에 개인 자격으로 가입하는 방식은 코민테른의 마링이 고안했다. 코민테른의 식민지 테제에 따르면 중국은 부르주아 민족혁명 단계에 있었고, 작은 공산당은 국민당이라는 「모든 계급의 연합」 안에서 대중을 조직해 힘을 키워야 했다. 천두슈는 계급적 독자성을 잃는다며 반대했으나 코민테른의 규율을 따랐다.', en: 'The device of Communists joining the Kuomintang as individuals was Maring’s. By the Comintern’s colonial theses China was in the stage of bourgeois national revolution, and the small Communist Party had to build strength by organising the masses inside the Kuomintang, the “bloc of all classes”. Chen Duxiu objected that the party would lose its class independence but submitted to Comintern discipline.', sources: [W + 'First_United_Front', W + 'Henk_Sneevliet'] },
                    { ko: '합작은 공산당에 극적인 성장을 가져왔다. 1925년 5·30 운동과 이어진 광저우·홍콩 대파업(16개월)은 당원을 1천 명에서 1927년 초 5만 8천 명으로 늘렸고, 후난·광둥의 농민협회 회원은 수백만에 이르렀다. 그러나 같은 성장이 국민당 우파와 지주·상인층의 공포를 키웠고, 쑨원 사후 이 긴장을 조정할 권위는 없었다.', en: 'The alliance brought the Communists dramatic growth. The May Thirtieth Movement of 1925 and the sixteen-month Guangzhou–Hong Kong strike raised membership from a thousand to 58,000 by early 1927, and the peasant associations of Hunan and Guangdong counted millions. But the same growth fed the fears of the Kuomintang right and of landlords and merchants, and after Sun’s death no authority remained to manage the tension.', sources: [W + 'May_Thirtieth_Movement', W + 'First_United_Front'] },
                ],
            },
            {
                heading: { ko: '북벌: 군대와 대중운동의 경주', en: 'The Northern Expedition: army and mass movement race north' },
                paragraphs: [
                    { ko: '1926년 3월 중산함 사건으로 장제스는 공산당의 국민당 내 지위를 제한하고 군권을 굳혔다. 소련 고문단은 합작을 지키기 위해 이를 받아들였다. 7월 국민혁명군 총사령이 된 장제스는 북벌을 개시해 우페이푸의 군을 격파하고 10월 우한을, 이듬해 3월 난징·상하이를 점령했다. 소련의 무기와 공산당의 선전·정보 조직이 진격을 도왔다.', en: 'After the Zhongshan Warship incident of March 1926 Chiang curtailed the Communists’ positions in the Kuomintang and consolidated his military authority; the Soviet advisers accepted this to preserve the front. As commander-in-chief from July he launched the Northern Expedition, smashed Wu Peifu’s army, took Wuhan in October and Nanjing and Shanghai the following March. Soviet arms and the Communists’ propaganda and intelligence networks aided the advance.', sources: [W + 'Northern_Expedition', W + 'Chiang_Kai-shek'] },
                    { ko: '군대가 지나간 자리에서 대중운동이 폭발했다. 후난에서는 농민협회가 지주를 심판하고 토지를 점거했으며, 마오쩌둥은 1927년 3월 「후난 농민운동 고찰 보고」에서 「혁명은 손님을 청해 밥을 먹는 일이 아니다」라며 농민의 폭력을 옹호했다. 우한과 상하이의 노동조합은 무장 규찰대를 조직했다. 국민혁명군 장교 다수가 지주 집안 출신이었고, 이 충돌이 합작의 운명을 결정했다.', en: 'Where the army passed, the mass movement exploded. In Hunan peasant associations tried landlords and seized land, and in March 1927 Mao’s “Report on an Investigation of the Peasant Movement in Hunan” defended their violence — “a revolution is not a dinner party”. Unions in Wuhan and Shanghai organised armed pickets. Most National Revolutionary Army officers came from landlord families, and this collision decided the fate of the front.', sources: [M + 'volume-1/mswv1_2.htm', W + 'Northern_Expedition'] },
                ],
            },
            {
                heading: { ko: '1927년 4월 12일, 상하이', en: '12 April 1927, Shanghai' },
                paragraphs: [
                    { ko: '1927년 3월 21일 저우언라이가 지휘한 상하이 노동자 규찰대가 봉기해 군벌군을 몰아내고 국민혁명군을 맞았다. 그러나 장제스는 상하이의 은행가·상인과 조계 당국, 청방 두목 두웨성과 손을 잡았다. 4월 12일 새벽 청방 무장대와 국민혁명군 26군이 노동조합 본부를 습격해 규찰대를 무장해제했고, 항의 시위에 기관총이 발사되었다.', en: 'On 21 March 1927 the Shanghai worker pickets under Zhou Enlai rose, drove out the warlord garrison and welcomed the National Revolutionary Army. But Chiang had made his arrangements with the city’s bankers and merchants, the concession authorities and the Green Gang boss Du Yuesheng. Before dawn on 12 April Green Gang gunmen and the 26th Army attacked union headquarters and disarmed the pickets; machine guns were turned on the protest march that followed.', sources: [W + 'Shanghai_massacre', W + 'Zhou_Enlai'] },
                    { ko: '며칠 사이 상하이에서 수백 명이 처형되었고 광저우·난징·샤먼 등에서 「청당(淸黨)」이 이어졌다. 4월 18일 장제스는 난징에 별도의 국민정부를 세워 우한 정부와 맞섰다. 베이징에서는 장쭤린이 소련 대사관을 수색해 4월 28일 리다자오를 교수형에 처했다. 도시의 공산당 조직은 몇 달 만에 거의 사라졌다.', en: 'Within days hundreds were executed in Shanghai and “party purification” followed in Guangzhou, Nanjing, Xiamen and elsewhere. On 18 April Chiang established a rival Nationalist government at Nanjing against Wuhan. In Beijing Zhang Zuolin raided the Soviet embassy and on 28 April hanged Li Dazhao. Within months the urban Communist organisation had all but vanished.', sources: [W + 'Shanghai_massacre', W + 'Li_Dazhao'] },
                ],
            },
            {
                heading: { ko: '우한의 실험과 붕괴', en: 'The Wuhan experiment and its collapse' },
                paragraphs: [
                    { ko: '스탈린과 코민테른은 우한의 국민당 좌파(왕징웨이)를 「혁명의 중심」으로 규정하고 공산당에 합작 유지를 지시했다. 1927년 4~5월 중공 제5차 대회는 토지 몰수를 주장하는 마오 등의 급진안을 누르고 우한 정부와의 협력을 택했다. 그러나 5월 창사에서 국민혁명군 부대가 농민협회를 학살한 「마일(馬日) 사변」이 일어났고 우한의 장군들도 공산당에 등을 돌렸다.', en: 'Stalin and the Comintern designated the Wuhan Kuomintang left under Wang Jingwei the “centre of the revolution” and ordered the Communists to keep the alliance. The party’s Fifth Congress in April–May 1927 rejected the radical land-confiscation line of Mao and others and chose cooperation with Wuhan. But in May a National Revolutionary Army unit massacred peasant associations at Changsha (the “Horse Day incident”), and the Wuhan generals too turned against the Communists.', sources: [W + 'First_United_Front', W + 'Wang_Jingwei'] },
                    { ko: '6월 코민테른 대표 M. N. 로이가 스탈린의 새 전보 — 노동자·농민 무장, 국민당 지도부 교체 — 를 왕징웨이에게 보여준 것은 결별을 앞당겼다. 7월 15일 우한 정부는 공산당원의 축출을 결의했고 보로딘은 몽골을 거쳐 모스크바로 돌아갔다. 천두슈는 실패의 책임을 지고 총서기에서 물러났으며, 코민테른은 자기 노선이 아니라 그의 「우경 기회주의」를 원인으로 지목했다.', en: 'In June the Comintern delegate M. N. Roy showed Wang Jingwei Stalin’s new telegram — arm the workers and peasants, replace the Kuomintang leadership — and hastened the break. On 15 July the Wuhan government resolved to expel the Communists, and Borodin returned to Moscow by way of Mongolia. Chen Duxiu took the blame and resigned as general secretary; the Comintern attributed the failure not to its own line but to his “right opportunism”.', sources: [W + 'Mikhail_Borodin', W + 'Chen_Duxiu'] },
                ],
            },
            {
                heading: { ko: '모스크바의 논쟁: 스탈린과 트로츠키', en: 'The debate in Moscow: Stalin and Trotsky' },
                paragraphs: [
                    { ko: '중국 정책은 1926~1927년 소련 당내 투쟁의 핵심 쟁점이었다. 트로츠키와 지노비예프의 연합반대파는 공산당이 국민당에서 나와 소비에트를 세워야 한다고 주장했고, 스탈린과 부하린은 국민당을 「혁명적 의회」에 견주며 합작을 옹호했다. 4월 5일 스탈린은 「장제스를 레몬처럼 짜낸 뒤 버리면 된다」고 말했고, 일주일 뒤 상하이 학살이 일어났다.', en: 'China policy was a central issue of the Soviet party struggle of 1926–1927. Trotsky and Zinoviev’s United Opposition argued that the Communists should leave the Kuomintang and form soviets; Stalin and Bukharin compared the Kuomintang to a “revolutionary parliament” and defended the alliance. On 5 April Stalin said Chiang would be “squeezed like a lemon and then thrown away”; a week later came the Shanghai massacre.', sources: [W + 'Leon_Trotsky', 'https://www.marxists.org/reference/archive/stalin/works/1927/05/24.htm'] },
                    { ko: '스탈린은 우한에 마지막 희망을 걸었다가 그것도 무너지자 노선을 급선회해 무장 봉기를 지시했고, 난창(8월)·추수 봉기(9월)·광저우 코뮌(12월)이 모두 실패했다. 트로츠키는 『중국 혁명의 문제』에서 이 과정을 스탈린 노선의 파산으로 기록했고, 이 논쟁은 이후 세계 공산주의 운동에서 「통일전선」의 조건을 둘러싼 논쟁의 원형이 되었다.', en: 'Stalin staked his last hopes on Wuhan and, when that too collapsed, swung to ordering armed uprisings — Nanchang in August, the Autumn Harvest rising in September, the Guangzhou Commune in December — all of which failed. Trotsky recorded the sequence in Problems of the Chinese Revolution as the bankruptcy of Stalin’s line, and the argument became the prototype of later debates in the world communist movement over the terms of the “united front”.', sources: ['https://www.marxists.org/archive/trotsky/1932/pcr/index.htm', W + 'Guangzhou_Uprising'] },
                ],
            },
            {
                heading: { ko: '총구에서 정권이 나온다', en: 'Political power grows out of the barrel of a gun' },
                paragraphs: [
                    { ko: '1927년 8월 7일 한커우 긴급회의는 천두슈를 해임하고 취추바이를 지도자로 세우며 토지혁명과 무장 봉기를 결의했다. 마오는 이 회의에서 「정권은 총구에서 나온다」고 말했다. 8월 1일 난창에서 허룽·예팅·주더의 부대가 봉기해 인민해방군의 출발점이 되었고, 마오의 추수 봉기군은 패배 뒤 징강산으로 들어가 첫 농촌 근거지를 세웠다.', en: 'The emergency conference at Hankou on 7 August 1927 removed Chen Duxiu, installed Qu Qiubai and resolved on agrarian revolution and armed insurrection; it was here that Mao said “political power grows out of the barrel of a gun”. On 1 August the troops of He Long, Ye Ting and Zhu De had risen at Nanchang, the starting point of the People’s Liberation Army, and after the defeat of the Autumn Harvest rising Mao’s force withdrew to Jinggangshan to found the first rural base.', sources: [W + 'Nanchang_uprising', W + 'Autumn_Harvest_Uprising'] },
                    { ko: '국민당은 1928년 6월 베이징을 점령하고 장쭤린이 일본군에 폭살된 뒤 장쉐량의 귀순으로 명목상 통일을 이루었다. 난징 10년(1927~1937)의 국민정부는 관세 자주권 회복과 도시 근대화를 이루었으나 농촌은 손대지 못했고, 공산당 소탕에 군사력을 집중했다. 1927년의 파국은 두 당이 각자의 방식으로 「누가 중국을 통치할 것인가」를 무력으로 결정하게 만든 출발점이었다.', en: 'The Kuomintang took Beijing in June 1928 and, after Zhang Zuolin was killed by a Japanese bomb, achieved nominal unification when Zhang Xueliang submitted. The Nanjing decade (1927–1937) recovered tariff autonomy and modernised the cities but left the countryside untouched, concentrating its armies on exterminating the Communists. The catastrophe of 1927 was the point from which both parties set out to settle “who rules China” by force.', sources: [W + 'Northern_Expedition', W + 'Zhang_Zuolin'] },
                ],
            },
        ],
        people: [
            { id: 'sun-yat-sen', kind: 'leader', relation: { ko: '합작을 결정한 국민당 총리', en: 'Kuomintang leader who chose the alliance' }, note: { ko: '요페와 공동선언을 내고 1924년 국민당을 개조했으며 1925년 사망했다.', en: 'Issued the statement with Joffe, reorganised the Kuomintang in 1924 and died in 1925.' } },
            { id: 'chiang-kai-shek', kind: 'executor', relation: { ko: '북벌 총사령 · 4·12 정변의 주역', en: 'Commander of the Northern Expedition and author of the April coup' }, note: { ko: '황푸군관학교 교장에서 총사령이 되어 북벌을 이끌었고 1927년 4월 상하이에서 공산당을 학살했다.', en: 'Rose from Whampoa commandant to commander-in-chief, led the expedition and massacred the Communists in Shanghai in April 1927.' } },
            { id: 'mikhail-borodin', kind: 'leader', relation: { ko: '코민테른 파견 국민당 고문', en: 'Comintern adviser to the Kuomintang' }, note: { ko: '국민당을 레닌주의 정당으로 개조했고 1927년 7월 우한에서 철수했다.', en: 'Rebuilt the Kuomintang on Leninist lines and withdrew from Wuhan in July 1927.' } },
            { id: 'chen-duxiu', kind: 'leader', relation: { ko: '중공 총서기, 실패의 책임을 진 인물', en: 'Party general secretary who bore the blame' }, note: { ko: '당내 합작에 반대했으나 코민테른을 따랐고 1927년 8월 해임되었다.', en: 'Opposed the bloc within but obeyed the Comintern; removed in August 1927.' } },
            { id: 'zhou-enlai', kind: 'participant', relation: { ko: '황푸 정치부 주임 · 상하이 봉기 지휘', en: 'Whampoa political director and leader of the Shanghai rising' }, note: { ko: '1927년 3월 상하이 노동자 봉기를 지휘했고 8월 난창 봉기를 이끌었다.', en: 'Directed the Shanghai workers’ rising in March 1927 and led the Nanchang Uprising in August.' } },
            { id: 'mao-zedong', kind: 'participant', relation: { ko: '「후난 농민운동 고찰 보고」', en: 'Author of the Hunan peasant report' }, note: { ko: '국민당 농민운동강습소를 운영했고 1927년 농민 폭력을 옹호한 뒤 추수 봉기를 이끌었다.', en: 'Ran the Kuomintang’s peasant institute, defended peasant violence in 1927 and led the Autumn Harvest rising.' } },
            { id: 'wang-jingwei', kind: 'participant', relation: { ko: '우한 국민당 좌파의 지도자', en: 'Leader of the Wuhan Kuomintang left' }, note: { ko: '스탈린이 기대한 「혁명의 중심」이었으나 1927년 7월 공산당과 결별했다.', en: 'Stalin’s hoped-for “centre of the revolution”, who broke with the Communists in July 1927.' } },
            { id: 'stalin', kind: 'leader', relation: { ko: '합작 유지를 지시한 소련 지도자', en: 'Soviet leader who insisted on the alliance' }, note: { ko: '장제스를 「레몬처럼 짜낸다」고 했고 우한 붕괴 뒤 봉기 노선으로 급선회했다.', en: 'Said Chiang would be “squeezed like a lemon”, then swung to insurrection after Wuhan fell.' } },
            { id: 'trotsky', kind: 'opponent', relation: { ko: '합작 노선의 비판자', en: 'Critic of the alliance line' }, note: { ko: '공산당의 국민당 탈퇴와 소비에트 수립을 주장했고 『중국 혁명의 문제』를 썼다.', en: 'Demanded that the Communists leave the Kuomintang and form soviets; wrote Problems of the Chinese Revolution.' } },
            { id: 'mn-roy', kind: 'participant', relation: { ko: '1927년 코민테른 대표', en: 'Comintern delegate in 1927' }, note: { ko: '스탈린의 전보를 왕징웨이에게 보여 결별을 앞당겼다.', en: 'Showed Stalin’s telegram to Wang Jingwei and hastened the break.' } },
            { id: 'adolph-joffe', kind: 'participant', relation: { ko: '쑨원-요페 공동선언의 소련 대표', en: 'Soviet signatory of the Sun–Joffe statement' }, note: { ko: '1923년 1월 쑨원과 합작의 기본 틀을 합의했다.', en: 'Agreed the basic terms of the alliance with Sun in January 1923.' } },
            { id: 'li-dazhao', kind: 'target', relation: { ko: '베이징에서 처형된 공산당 창건자', en: 'Party founder hanged in Beijing' }, note: { ko: '국민당 중앙집행위원이었고 1927년 4월 장쭤린에게 처형되었다.', en: 'A Kuomintang Central Executive Committee member, executed by Zhang Zuolin in April 1927.' } },
            { id: 'zhang-zuolin', kind: 'opponent', relation: { ko: '베이징의 군벌, 소련 대사관 수색', en: 'Warlord of Beijing who raided the Soviet embassy' }, note: { ko: '1927년 4월 소련 대사관을 수색하고 리다자오를 처형했다.', en: 'Raided the Soviet embassy in April 1927 and executed Li Dazhao.' } },
            { id: 'he-long', kind: 'participant', relation: { ko: '난창 봉기 총지휘', en: 'Commander of the Nanchang Uprising' }, note: { ko: '1927년 8월 1일 봉기를 지휘했고 직후 입당했다.', en: 'Commanded the rising of 1 August 1927 and joined the party days later.' } },
            { id: 'zhu-de', kind: 'participant', relation: { ko: '난창 봉기 잔여 부대를 이끈 지휘관', en: 'Led the survivors of Nanchang' }, note: { ko: '봉기 잔여 부대를 이끌고 1928년 징강산에서 마오와 합류했다.', en: 'Led the remnants to join Mao at Jinggangshan in 1928.' } },
        ],
        related: ['may-fourth-and-ccp-founding', 'jiangxi-soviet-and-long-march', 'succession-struggle'],
    },
    {
        id: 'jiangxi-soviet-and-long-march', sortOrder: 72, period: '1927–1936', countries: ['china'],
        title: { ko: '징강산에서 옌안까지: 소비에트 근거지와 대장정', en: 'From Jinggangshan to Yan’an: the soviet bases and the Long March' },
        question: { ko: '도시에서 궤멸한 공산당은 어떻게 농촌의 군대가 되었고, 왜 대장정은 패주이면서 마오의 승리였는가?', en: 'How did a party destroyed in the cities become a rural army, and why was the Long March both a rout and Mao’s victory?' },
        summary: { ko: '1927년의 학살 뒤 마오와 주더는 징강산에서 홍군과 농촌 근거지를 세웠고, 1931년 루이진에 중화소비에트공화국이 섰다. 장제스의 다섯 차례 포위토벌 끝에 1934년 10월 홍군은 장시를 버리고 1만 킬로미터를 행군했으며, 1935년 쭌이 회의에서 마오가 군사 지도권을 잡았다. 1936년 산베이 도착과 시안 사변이 항일 통일전선의 문을 열었다.', en: 'After the massacres of 1927 Mao and Zhu De built a Red Army and a rural base at Jinggangshan, and in 1931 the Chinese Soviet Republic was proclaimed at Ruijin. After Chiang Kai-shek’s five encirclement campaigns the Red Army abandoned Jiangxi in October 1934 and marched ten thousand kilometres; at the Zunyi Conference of 1935 Mao took military command. Arrival in northern Shaanxi in 1936 and the Xi’an Incident opened the way to an anti-Japanese united front.' },
        outcome: { ko: '8만 6천 명으로 출발한 중앙홍군은 8천 명 남짓으로 산베이에 닿았지만 당은 살아남았고 지도부는 마오 중심으로 재편되었다. 「농촌으로 도시를 포위한다」는 전략, 유격전의 원칙, 대장정의 신화가 이후 중국 혁명의 정체성이 되었다.', en: 'The Central Red Army that set out with 86,000 reached northern Shaanxi with barely eight thousand, but the party survived and its leadership was rebuilt around Mao. The strategy of “surrounding the cities from the countryside”, the principles of guerrilla war and the myth of the Long March became the identity of the Chinese revolution.' },
        locations: [
            { lat: 25.89, lng: 116.03, label: { ko: '루이진', en: 'Ruijin' } },
            { lat: 26.72, lng: 114.16, label: { ko: '징강산', en: 'Jinggangshan' } },
            { lat: 27.70, lng: 106.93, label: { ko: '쭌이', en: 'Zunyi' } },
            { lat: 36.59, lng: 109.49, label: { ko: '옌안', en: 'Yan’an' } },
            { lat: 34.26, lng: 108.94, label: { ko: '시안', en: 'Xi’an' } },
        ],
        timeline: [
            { date: '1927.10', title: { ko: '징강산 근거지', en: 'The Jinggangshan base' }, body: { ko: '추수 봉기의 패잔병 천여 명을 이끌고 마오가 후난·장시 경계의 산악에 들어갔다. 1928년 4월 주더의 부대가 합류해 홍군 제4군이 되었다.', en: 'Mao led a thousand survivors of the Autumn Harvest rising into the mountains on the Hunan–Jiangxi border; in April 1928 Zhu De’s force joined to form the Fourth Red Army.' }, geo: { kind: 'point', lat: 26.72, lng: 114.16, label: { ko: '징강산', en: 'Jinggangshan' } } },
            { date: '1930.07', title: { ko: '리리싼 노선과 창사 공격', en: 'The Li Lisan line and the attack on Changsha' }, body: { ko: '당 중앙의 도시 봉기 명령으로 펑더화이의 홍군이 창사를 열흘간 점령했다가 물러났다. 코민테른은 리리싼을 소환했다.', en: 'On the centre’s orders for urban insurrection Peng Dehuai’s Red Army held Changsha for ten days before withdrawing; the Comintern recalled Li Lisan.' }, geo: { kind: 'point', lat: 28.23, lng: 112.94, label: { ko: '창사', en: 'Changsha' } } },
            { date: '1930.12', title: { ko: '푸톈 사변', en: 'The Futian incident' }, body: { ko: '장시 홍군 안의 「AB단」 숙청으로 수천 명이 처형되었다. 근거지 안의 첫 대규모 내부 숙청이었다.', en: 'The purge of the “AB League” inside the Jiangxi Red Army killed thousands, the first large internal purge in the bases.' }, geo: { kind: 'point', lat: 27.03, lng: 115.13, label: { ko: '푸톈', en: 'Futian' } } },
            { date: '1931.11.07', title: { ko: '중화소비에트공화국 수립', en: 'Chinese Soviet Republic proclaimed' }, body: { ko: '루이진에서 마오를 주석으로 임시중앙정부가 섰다. 토지법과 혼인법이 공포되었다.', en: 'A provisional central government with Mao as chairman was established at Ruijin; land and marriage laws were promulgated.' }, geo: { kind: 'point', lat: 25.89, lng: 116.03, label: { ko: '루이진', en: 'Ruijin' } } },
            { date: '1933–1934', title: { ko: '제5차 포위토벌', en: 'The fifth encirclement campaign' }, body: { ko: '장제스의 50만 병력이 토치카 봉쇄망으로 근거지를 조였다. 보구와 오토 브라운의 진지전은 홍군을 소모시켰다.', en: 'Chiang’s 500,000 troops squeezed the base with a blockhouse network; the positional defence of Bo Gu and Otto Braun bled the Red Army.' }, geo: { kind: 'point', lat: 25.89, lng: 116.03, label: { ko: '장시 소비에트', en: 'Jiangxi Soviet' } } },
            { date: '1934.10.16', title: { ko: '대장정 출발', en: 'The Long March begins' }, body: { ko: '중앙홍군 8만 6천 명이 루이진을 떠나 서쪽으로 향했다. 12월 샹강 도하에서 절반을 잃었다.', en: 'The Central Red Army of 86,000 left Ruijin heading west; at the Xiang River crossing in December it lost half its strength.' }, geo: { kind: 'arrow', points: [[25.89, 116.03], [25.6, 111.0], [27.70, 106.93]], label: { ko: '루이진 → 샹강 → 쭌이 (개략)', en: 'Ruijin → Xiang River → Zunyi (schematic)' }, actor: { ko: '중앙홍군', en: 'Central Red Army' } } },
            { date: '1935.01.15', title: { ko: '쭌이 회의', en: 'Zunyi Conference' }, body: { ko: '정치국 확대회의가 보구·브라운의 군사 지도를 비판하고 마오를 정치국 상무위원으로 올렸다. 장원톈이 총서기가 되었다.', en: 'An enlarged Politburo meeting condemned the military leadership of Bo Gu and Braun and raised Mao to the Standing Committee; Zhang Wentian became general secretary.' }, geo: { kind: 'point', lat: 27.70, lng: 106.93, label: { ko: '쭌이', en: 'Zunyi' } } },
            { date: '1935.05', title: { ko: '진사강 도하와 루딩교', en: 'The Jinsha crossing and Luding Bridge' }, body: { ko: '홍군은 진사강을 건너 국민당군을 따돌리고 다두강의 루딩 철삭교를 돌파했다.', en: 'The Red Army crossed the Jinsha to shake off pursuit and forced the iron-chain Luding Bridge over the Dadu River.' }, geo: { kind: 'point', lat: 29.91, lng: 102.23, label: { ko: '루딩교', en: 'Luding Bridge' } } },
            { date: '1935.06–09', title: { ko: '장궈타오와의 분열', en: 'The split with Zhang Guotao' }, body: { ko: '쓰촨 마오궁에서 제4방면군과 합류했으나 북상 대 서진을 놓고 대립해 두 군이 갈라졌다. 마오는 북으로 갔다.', en: 'The armies met Zhang Guotao’s Fourth Front Army at Maogong in Sichuan but split over marching north or west; Mao went north.' }, geo: { kind: 'point', lat: 31.0, lng: 102.4, label: { ko: '마오궁', en: 'Maogong' } } },
            { date: '1935.10.19', title: { ko: '산베이 우치진 도착', en: 'Arrival at Wuqi, northern Shaanxi' }, body: { ko: '중앙홍군이 류즈단·시중쉰의 산간 근거지에 닿았다. 1년 만에 11개 성 1만 2,500킬로미터를 행군했다.', en: 'The Central Red Army reached the Shaanxi–Gansu base of Liu Zhidan and Xi Zhongxun after a year, eleven provinces and 12,500 kilometres.' }, geo: { kind: 'arrow', points: [[27.70, 106.93], [29.91, 102.23], [31.0, 102.4], [36.92, 108.18]], label: { ko: '쭌이 → 루딩 → 마오궁 → 우치 (개략)', en: 'Zunyi → Luding → Maogong → Wuqi (schematic)' }, actor: { ko: '중앙홍군', en: 'Central Red Army' } } },
            { date: '1936.10', title: { ko: '세 방면군의 회사(會師)', en: 'The three front armies unite' }, body: { ko: '허룽·런비스의 제2방면군과 제4방면군이 간쑤 후이닝에서 중앙홍군과 합류해 대장정이 끝났다.', en: 'The Second Front Army of He Long and Ren Bishi and the Fourth Front Army joined the Central Red Army at Huining, Gansu, ending the Long March.' }, geo: { kind: 'point', lat: 35.69, lng: 105.05, label: { ko: '후이닝', en: 'Huining' } } },
            { date: '1936.12.12', title: { ko: '시안 사변', en: 'The Xi’an Incident' }, body: { ko: '장쉐량·양후청이 장제스를 감금해 내전 중지와 항일을 요구했다. 저우언라이의 중재로 풀려난 장제스는 공산당 토벌을 멈췄다.', en: 'Zhang Xueliang and Yang Hucheng seized Chiang Kai-shek to demand an end to civil war and resistance to Japan; released through Zhou Enlai’s mediation, Chiang halted the campaigns against the Communists.' }, geo: { kind: 'point', lat: 34.26, lng: 108.94, label: { ko: '시안', en: 'Xi’an' } } },
        ],
        sections: [
            {
                heading: { ko: '산으로 간 혁명', en: 'The revolution goes to the mountains' },
                paragraphs: [
                    { ko: '1927년 가을 추수 봉기에서 패한 마오는 남은 천여 명을 이끌고 후난·장시 경계의 징강산으로 들어갔다. 산적 두목 위안원차이·왕쭤와 손잡고 지주 토지를 몰수하는 근거지를 세웠고, 1928년 4월 주더의 난창 봉기 잔여 부대가 합류해 홍군 제4군이 되었다. 「적이 진격하면 물러나고, 적이 멈추면 교란하고, 적이 지치면 치고, 적이 물러나면 추격한다」는 16자 유격전 원칙이 여기서 나왔다.', en: 'Defeated in the Autumn Harvest rising of 1927, Mao led his thousand survivors into Jinggangshan on the Hunan–Jiangxi border. Allying with the bandit chiefs Yuan Wencai and Wang Zuo, he built a base that confiscated landlord land, and in April 1928 Zhu De’s remnants from Nanchang joined to form the Fourth Red Army. The sixteen-character guerrilla formula — “the enemy advances, we retreat; the enemy halts, we harass; the enemy tires, we strike; the enemy retreats, we pursue” — was born here.', sources: [W + 'Jinggangshan', W + 'Zhu_De'] },
                    { ko: '마오는 1928년 「중국의 붉은 정권은 왜 존재할 수 있는가」에서 군벌 사이의 분열과 열강의 경쟁이 농촌의 「할거」를 가능하게 한다고 설명했다. 이는 노동자 봉기를 기다리는 당 중앙과 다른 길이었다. 1929년 구톈 회의는 「당이 총을 지휘한다」는 원칙으로 군대 안의 당 조직을 확립했고, 1930년까지 장시 남부와 푸젠 서부에 수십 개 현의 근거지가 생겼다.', en: 'In “Why is it that Red political power can exist in China?” (1928) Mao explained that splits among the warlords and rivalry among the powers made separate rural regimes possible — a different road from the party centre waiting for workers’ uprisings. The Gutian Conference of 1929 established party organisation within the army on the principle that “the party commands the gun”, and by 1930 bases covered dozens of counties in southern Jiangxi and western Fujian.', sources: [M + 'volume-1/mswv1_3.htm', W + 'Chinese_Soviet_Republic'] },
                ],
            },
            {
                heading: { ko: '당 중앙과 근거지의 긴장', en: 'Tension between the centre and the bases' },
                paragraphs: [
                    { ko: '상하이의 당 중앙은 여전히 도시 봉기를 정통으로 여겼다. 1930년 리리싼은 「혁명의 고조」를 선언하고 홍군에 창사·우한·난창 공격을 명령했다. 펑더화이의 부대가 7월 창사를 열흘 점령했으나 곧 밀려났고, 코민테른은 리리싼을 모스크바로 소환했다. 1931년 1월 파벨 미프가 후원한 왕밍 등 「28인의 볼셰비키」가 당 중앙을 장악했다.', en: 'The party centre in Shanghai still held urban insurrection to be orthodox. In 1930 Li Lisan proclaimed a “revolutionary high tide” and ordered the Red Army against Changsha, Wuhan and Nanchang. Peng Dehuai’s troops held Changsha for ten days in July before being driven out, and the Comintern recalled Li to Moscow. In January 1931 the “28 Bolsheviks” around Wang Ming, backed by Pavel Mif, took over the centre.', sources: [W + 'Li_Lisan', W + 'Wang_Ming'] },
                    { ko: '근거지 안에서도 폭력이 있었다. 1930년 12월 장시 홍군 20군의 일부가 「AB단(반볼셰비키단)」 숙청에 항의해 반란했고, 마오의 총전위(總前委)는 이를 진압하며 이후 수천 명을 처형했다. 푸톈 사변은 근거지의 권력투쟁과 숙청의 첫 사례였다. 1932년 닝두 회의에서 마오는 군사 지휘권을 잃고 정부 업무로 밀려났으며, 1933년 당 중앙이 상하이에서 루이진으로 옮겨 오면서 보구와 코민테른 고문 오토 브라운이 군을 지휘했다.', en: 'There was violence inside the bases too. In December 1930 part of the 20th Army in Jiangxi mutinied against the purge of the “AB (Anti-Bolshevik) League”; Mao’s front committee suppressed it and thousands were executed afterwards. The Futian incident was the first case of power struggle and purge in the bases. At the Ningdu conference of 1932 Mao lost military command and was sidelined into government work, and when the centre moved from Shanghai to Ruijin in 1933 Bo Gu and the Comintern adviser Otto Braun took charge of the army.', sources: [W + 'Chinese_Soviet_Republic', W + 'Otto_Braun_(communist)'] },
                ],
            },
            {
                heading: { ko: '루이진: 국가의 실험', en: 'Ruijin: the experiment in statehood' },
                paragraphs: [
                    { ko: '1931년 11월 7일, 러시아 혁명 기념일에 루이진에서 중화소비에트공화국 임시중앙정부가 선포되었고 마오가 주석이 되었다. 정부는 토지법으로 지주 토지를 몰수해 빈농에 나누고 「부농 제한」 정책을 폈으며, 혼인법으로 이혼의 자유와 매매혼 금지를 정했다. 인구 300만의 근거지에서 세금·은행·학교와 선거가 시도되었다.', en: 'On 7 November 1931, the anniversary of the Russian Revolution, the provisional central government of the Chinese Soviet Republic was proclaimed at Ruijin with Mao as chairman. Its land law confiscated landlord land for the poor and “restricted” rich peasants; its marriage law established freedom of divorce and banned purchase marriage. In a base of three million people it experimented with taxation, banking, schools and elections.', sources: [W + 'Chinese_Soviet_Republic', M + 'volume-1/mswv1_8.htm'] },
                    { ko: '장제스는 1930년 말부터 「위초(圍剿)」로 불린 포위토벌을 시작했다. 첫 네 차례(1930~1933)는 홍군의 유인·섬멸 전술에 패했다. 1933년 10월 시작된 제5차 토벌에서 국민당군은 독일 고문의 조언으로 토치카를 촘촘히 세워 봉쇄망을 좁혔고, 보구와 브라운은 「국문 밖에서 적을 막자」는 진지전으로 맞섰다가 병력을 소모했다. 1934년 여름 근거지의 상실은 시간문제였다.', en: 'From late 1930 Chiang Kai-shek launched the encirclement campaigns. The first four (1930–1933) were defeated by the Red Army’s tactics of luring and annihilating. In the fifth, begun in October 1933, the Nationalists on German advice tightened a blockhouse cordon step by step, and Bo Gu and Braun answered with positional defence “outside the gates”, wasting the army. By summer 1934 the loss of the base was a matter of time.', sources: [W + 'Encirclement_campaigns', W + 'Long_March'] },
                ],
            },
            {
                heading: { ko: '대장정: 탈출에서 전략적 이동으로', en: 'The Long March: from escape to strategic movement' },
                paragraphs: [
                    { ko: '1934년 10월 16일 밤 중앙홍군 8만 6천 명이 루이진을 떠났다. 취추바이 등 부상자와 병약자, 천이의 유격부대는 남겨졌다. 짐을 잔뜩 진 행군은 느렸고, 12월 초 광시 샹강 도하에서 국민당군과 지방군의 협공으로 병력의 절반 이상을 잃었다. 이 참패는 보구·브라운의 지도에 대한 불만을 폭발시켰다.', en: 'On the night of 16 October 1934 the Central Red Army of 86,000 left Ruijin, leaving behind the wounded and sick such as Qu Qiubai and Chen Yi’s guerrillas. The overloaded column moved slowly, and in early December, crossing the Xiang River in Guangxi under attack from Nationalist and provincial troops, it lost more than half its strength. The disaster brought the discontent with Bo Gu and Braun to a head.', sources: [W + 'Long_March', K + '%EB%8C%80%EC%9E%A5%EC%A0%95'] },
                    { ko: '1935년 1월 구이저우 쭌이에서 열린 정치국 확대회의는 브라운의 군사 지도를 비판하고 마오를 정치국 상무위원으로 올렸으며, 곧 마오·저우언라이·왕자샹의 3인 군사소조가 지휘를 맡았다. 이후 홍군은 츠수이강을 네 번 건너며 국민당군을 교란하고 윈난으로 우회해 5월 진사강을 건넜다. 「쭌이 회의」는 뒤에 마오 지도권의 출발점으로 공식화되었으나, 실제 권력의 이동은 몇 년에 걸쳐 완성되었다.', en: 'The enlarged Politburo meeting at Zunyi, Guizhou, in January 1935 condemned Braun’s military leadership and raised Mao to the Standing Committee; soon a three-man military group of Mao, Zhou Enlai and Wang Jiaxiang took command. The Red Army then crossed the Chishui River four times to confuse pursuit, swung through Yunnan and crossed the Jinsha in May. The Zunyi Conference was later canonised as the beginning of Mao’s leadership, though the actual shift of power took years to complete.', sources: [W + 'Zunyi_Conference', W + 'Long_March'] },
                ],
            },
            {
                heading: { ko: '설산·초지·장궈타오', en: 'Snow mountains, grasslands and Zhang Guotao' },
                paragraphs: [
                    { ko: '5월 말 다두강의 루딩 철삭교 돌파와 6월 자진산 설산 횡단을 거쳐 홍군은 쓰촨 서부 마오궁에서 장궈타오의 제4방면군 8만 명과 합류했다. 그러나 병력이 10배인 장궈타오는 지도부 재편을 요구했고, 북상해 항일 전선에 가까운 산시로 가자는 마오와 서쪽 쓰촨·시캉의 오지로 가자는 장궈타오가 대립했다. 9월 두 군은 갈라졌고 장궈타오는 별도의 「중앙」을 선포했다.', en: 'After forcing the iron-chain bridge at Luding on the Dadu River in late May and crossing the Jiajin snow mountains in June, the Red Army met Zhang Guotao’s Fourth Front Army of 80,000 at Maogong in western Sichuan. Zhang, with ten times the troops, demanded a reshuffle of the leadership, and Mao’s plan to march north toward Shaanxi and the anti-Japanese front clashed with Zhang’s to go west into the wilds of Sichuan and Xikang. In September the two armies parted and Zhang proclaimed a rival “centre”.', sources: [W + 'Zhang_Guotao', W + 'Battle_of_Luding_Bridge'] },
                    { ko: '마오의 부대는 초지(草地)의 늪을 건너 9월 라쯔커우를 돌파했고 10월 19일 산베이 우치진에서 류즈단의 근거지에 닿았다. 남하한 장궈타오는 쓰촨에서 패해 이듬해 북상했고, 1936년 10월 후이닝에서 세 방면군이 합류하며 대장정이 끝났다. 장궈타오가 서쪽으로 보낸 서로군 2만은 하서회랑에서 마씨 군벌에게 궤멸되었다. 이 분열은 1938년 장궈타오의 탈당으로 마무리되었다.', en: 'Mao’s force crossed the marshes of the grasslands, broke through Lazikou in September and on 19 October reached Liu Zhidan’s base at Wuqi in northern Shaanxi. Zhang Guotao, turning south, was defeated in Sichuan and marched north the following year; the three front armies united at Huining in October 1936, ending the Long March. The Western Route Army of 20,000 that Zhang sent west was destroyed by the Ma warlords in the Hexi Corridor. The split ended with Zhang’s defection in 1938.', sources: [W + 'Long_March', W + 'Xu_Xiangqian'] },
                ],
            },
            {
                heading: { ko: '시안 사변과 통일전선', en: 'The Xi’an Incident and the united front' },
                paragraphs: [
                    { ko: '1935년 8월 코민테른 제7차 대회는 반파시즘 통일전선을 결의했고 중공은 「8·1 선언」으로 항일을 위한 내전 중지를 제안했다. 그러나 장제스는 「안내양외(安內攘外)」 — 먼저 국내를 평정한다 — 를 고수하며 만주에서 쫓겨난 장쉐량의 동북군을 산베이 토벌에 투입했다. 동북군 장병은 고향을 되찾을 항일을 원했고, 공산당은 이들과 비밀리에 접촉했다.', en: 'In August 1935 the Comintern’s Seventh Congress resolved on the anti-fascist united front, and the Chinese party’s “August First Declaration” proposed ending the civil war to resist Japan. Chiang, however, held to “internal pacification before external resistance” and sent Zhang Xueliang’s Northeastern Army, driven from Manchuria, against the Shaanxi base. Its soldiers wanted a war with Japan to recover their homes, and the Communists made secret contact with them.', sources: [W + 'Xi%27an_Incident', W + 'Zhang_Xueliang'] },
                    { ko: '1936년 12월 12일 새벽 장쉐량과 양후청의 부대가 시안 교외 화칭츠에서 장제스를 감금하고 내전 중지·항일·정치범 석방 등 8개 조항을 요구했다. 난징의 강경파는 토벌을 주장했고 모스크바는 장제스 처형이 일본만 이롭게 한다며 석방을 요구했다. 저우언라이가 시안에 와 중재했고 장제스는 구두로 내전 중지를 약속한 뒤 25일 풀려났다. 장쉐량은 그를 따라 난징에 갔다가 반세기의 연금에 들어갔고, 1937년 7월 중일전쟁이 터지면서 제2차 국공합작이 성립했다.', en: 'Before dawn on 12 December 1936 troops of Zhang Xueliang and Yang Hucheng seized Chiang at Huaqing Pool outside Xi’an and presented eight demands: end the civil war, resist Japan, release political prisoners. Nanjing’s hardliners wanted a punitive expedition; Moscow demanded Chiang’s release, arguing that his death would benefit only Japan. Zhou Enlai came to mediate, and Chiang was freed on the 25th after verbally promising to halt the civil war. Zhang Xueliang followed him to Nanjing and into half a century of house arrest, and when war with Japan broke out in July 1937 the second united front was formed.', sources: [W + 'Xi%27an_Incident', W + 'Second_United_Front'] },
                ],
            },
            {
                heading: { ko: '신화와 역사', en: 'Myth and history' },
                paragraphs: [
                    { ko: '대장정은 1936년 에드거 스노의 『중국의 붉은 별』로 세계에 알려졌고, 공산당은 이를 「선언서이자 선전대이자 파종기」(마오)로 신화화했다. 루딩교의 22용사, 설산과 초지의 고난은 혁명 서사의 핵심 장면이 되었으며 이후 세대의 「장정 정신」 교육에 쓰였다. 마오 자신은 대장정을 자기 지도권의 기원 신화로 삼았다.', en: 'The Long March became known to the world through Edgar Snow’s Red Star over China (1936), and the party mythologised it as “a manifesto, a propaganda force, a seeding machine” (Mao). The twenty-two heroes of Luding Bridge and the ordeals of snow mountain and grassland became core scenes of the revolutionary narrative, used to teach the “Long March spirit” to later generations, and Mao made it the origin myth of his own leadership.', sources: [W + 'Long_March', W + 'Mao_Zedong'] },
                    { ko: '역사가들은 루딩교 전투의 규모, 행군 거리(1만 2,500킬로미터에서 6천 킬로미터까지의 추정), 쭌이 회의의 실제 결정, 그리고 국민당군이 홍군을 「몰아내되 섬멸하지 않은」 지방 군벌 정치의 역할을 재검토해 왔다. 확실한 것은 당이 살아남았다는 사실과, 1930년대 후반 옌안에서 마오가 이 생존의 서사를 자신의 노선과 결합했다는 점이다.', en: 'Historians have re-examined the scale of the fighting at Luding Bridge, the distance marched (estimates range from 12,500 down to 6,000 kilometres), what the Zunyi Conference actually decided, and the role of provincial warlord politics in a Nationalist pursuit that “drove out but did not destroy” the Red Army. What is certain is that the party survived, and that at Yan’an in the late 1930s Mao fused this narrative of survival with his own line.', sources: [W + 'Long_March', W + 'Zunyi_Conference'] },
                ],
            },
        ],
        people: [
            { id: 'mao-zedong', kind: 'leader', relation: { ko: '징강산 근거지 창건자 · 쭌이 이후 군사 지도자', en: 'Founder of the Jinggangshan base and military leader after Zunyi' }, note: { ko: '농촌 근거지 전략을 세웠고 1935년 쭌이 회의에서 지휘권을 되찾았다.', en: 'Devised the rural-base strategy and regained command at the Zunyi Conference of 1935.' } },
            { id: 'zhu-de', kind: 'leader', relation: { ko: '홍군 총사령', en: 'Commander-in-chief of the Red Army' }, note: { ko: '1928년 징강산에서 마오와 합류해 「주마오 홍군」을 이끌었고 대장정을 지휘했다.', en: 'Joined Mao at Jinggangshan in 1928, led the “Zhu–Mao” Red Army and commanded on the Long March.' } },
            { id: 'zhou-enlai', kind: 'leader', relation: { ko: '쭌이 이후 3인 군사소조 · 시안 사변 중재자', en: 'Member of the post-Zunyi military group and mediator at Xi’an' }, note: { ko: '쭌이에서 마오를 지지했고 1936년 12월 시안에서 장제스 석방을 중재했다.', en: 'Backed Mao at Zunyi and mediated Chiang’s release at Xi’an in December 1936.' } },
            { id: 'bo-gu-qin-bangxian', kind: 'leader', relation: { ko: '대장정 출발 당시 당 총책', en: 'Party leader at the start of the March' }, note: { ko: '제5차 토벌의 진지전을 지휘했고 쭌이에서 책임을 추궁당했다.', en: 'Directed the positional defence in the fifth campaign and was held responsible at Zunyi.' } },
            { id: 'otto-braun', kind: 'leader', relation: { ko: '코민테른 군사고문 「리더」', en: 'Comintern military adviser “Li De”' }, note: { ko: '진지전으로 근거지를 잃었고 쭌이 회의에서 비판받은 뒤 지휘에서 배제되었다.', en: 'Lost the base with positional warfare and was removed from command after Zunyi.' } },
            { id: 'zhang-guotao', kind: 'opponent', relation: { ko: '제4방면군 지도자, 마오와 결별', en: 'Fourth Front Army leader who split with Mao' }, note: { ko: '1935년 별도의 「중앙」을 세우고 남하했다가 1936년 합류했다.', en: 'Set up a rival “centre” in 1935, went south and rejoined in 1936.' } },
            { id: 'zhang-wentian', kind: 'participant', relation: { ko: '쭌이 이후 당 총서기', en: 'General secretary after Zunyi' }, note: { ko: '보구를 대신해 총서기가 되어 마오의 군사 지도를 뒷받침했다.', en: 'Replaced Bo Gu as general secretary and supported Mao’s military leadership.' } },
            { id: 'peng-dehuai', kind: 'participant', relation: { ko: '제3군단장', en: 'Commander of the Third Army Group' }, note: { ko: '1930년 창사를 점령했고 대장정에서 주력 군단을 이끌었다.', en: 'Took Changsha in 1930 and led a main army group on the March.' } },
            { id: 'lin-biao', kind: 'participant', relation: { ko: '제1군단장', en: 'Commander of the First Army Group' }, note: { ko: '대장정의 선봉 군단을 지휘했다.', en: 'Commanded the vanguard army group of the Long March.' } },
            { id: 'liu-bocheng', kind: 'participant', relation: { ko: '홍군 총참모장', en: 'Chief of staff of the Red Army' }, note: { ko: '진사강·다두강 도하와 이족(彝族) 지역 통과를 이끌었다.', en: 'Led the Jinsha and Dadu crossings and the passage through Yi territory.' } },
            { id: 'he-long', kind: 'participant', relation: { ko: '제2방면군 총지휘', en: 'Commander of the Second Front Army' }, note: { ko: '후난·후베이 근거지에서 출발해 1936년 후이닝에서 합류했다.', en: 'Marched from the Hunan–Hubei base to join at Huining in 1936.' } },
            { id: 'xu-xiangqian', kind: 'participant', relation: { ko: '제4방면군 총지휘', en: 'Commander of the Fourth Front Army' }, note: { ko: '장궈타오 휘하에서 남하했고 1936년 서로군의 궤멸을 겪었다.', en: 'Went south under Zhang Guotao and saw the Western Route Army destroyed in 1936.' } },
            { id: 'ren-bishi', kind: 'participant', relation: { ko: '제2방면군 정치위원', en: 'Political commissar of the Second Front Army' }, note: { ko: '허룽과 함께 제2방면군을 이끌고 합류했다.', en: 'Led the Second Front Army with He Long to the rendezvous.' } },
            { id: 'ye-jianying', kind: 'participant', relation: { ko: '참모장, 장궈타오의 분열 기도를 보고', en: 'Chief of staff who reported Zhang Guotao’s move' }, note: { ko: '1935년 9월 장궈타오의 전보를 마오에게 알려 북상을 가능하게 했다.', en: 'Passed Zhang Guotao’s telegram to Mao in September 1935, enabling the march north.' } },
            { id: 'chiang-kai-shek', kind: 'opponent', relation: { ko: '포위토벌의 지휘자 · 시안 사변의 피감금자', en: 'Director of the encirclement campaigns, detained at Xi’an' }, note: { ko: '다섯 차례 토벌로 장시 근거지를 무너뜨렸고 1936년 시안에서 감금되었다.', en: 'Destroyed the Jiangxi base in five campaigns and was seized at Xi’an in 1936.' } },
            { id: 'zhang-xueliang', kind: 'executor', relation: { ko: '시안 사변의 주모자', en: 'Instigator of the Xi’an Incident' }, note: { ko: '1936년 12월 장제스를 감금해 내전 중지를 요구했다.', en: 'Detained Chiang in December 1936 to demand an end to the civil war.' } },
            { id: 'xi-zhongxun', kind: 'participant', relation: { ko: '산베이 근거지의 창건자', en: 'Founder of the northern Shaanxi base' }, note: { ko: '류즈단과 함께 세운 근거지가 대장정의 종착지가 되었다.', en: 'The base he built with Liu Zhidan became the destination of the March.' } },
            { id: 'qu-qiubai', kind: 'target', relation: { ko: '장시에 남겨져 처형된 전 지도자', en: 'Former leader left behind and executed' }, note: { ko: '병으로 대장정에 동행하지 못하고 1935년 국민당군에 붙잡혀 처형되었다.', en: 'Too ill to march, captured by Nationalist troops in 1935 and executed.' } },
            { id: 'wang-ming', kind: 'participant', relation: { ko: '모스크바에서 당을 대표한 「28인의 볼셰비키」 수장', en: 'Head of the “28 Bolsheviks”, representing the party in Moscow' }, note: { ko: '1931년 당 중앙을 장악한 뒤 모스크바로 가 코민테른 주재 대표가 되었다.', en: 'Took over the centre in 1931 and then represented the party at the Comintern.' } },
        ],
        related: ['first-united-front-1924-1927', 'sino-japanese-war-1937-1945'],
    },
];
