// 1937–1957: the war with Japan, the civil war, consolidation, the Hundred Flowers.
const W = 'https://en.wikipedia.org/wiki/';
const K = 'https://ko.wikipedia.org/wiki/';
const M = 'https://www.marxists.org/reference/archive/mao/selected-works/';
const CS = 'https://countrystudies.us/china/';

module.exports = [
    {
        id: 'sino-japanese-war-1937-1945', sortOrder: 96, period: '1937–1945', countries: ['china', 'japan', 'usa'],
        title: { ko: '중일전쟁과 제2차 국공합작', en: 'The war with Japan and the second united front' },
        question: { ko: '8년의 항일전쟁은 왜 국민당을 소모시키고 공산당을 키웠는가?', en: 'Why did eight years of war against Japan exhaust the Nationalists and build up the Communists?' },
        summary: { ko: '1937년 7월 루거우차오 사건으로 시작된 전면전에서 일본군은 연안 도시와 철도를 점령했고 국민정부는 충칭으로 물러났다. 홍군은 팔로군·신4군으로 개편되어 적 후방에 근거지를 넓혔다. 1941년 완난 사변 이후 두 당의 합작은 사실상 무너졌고, 옌안의 정풍운동은 마오의 당을 완성했다. 1945년 일본 항복 때 공산당은 당원 120만, 정규군 90만, 인구 1억의 해방구를 가진 세력이었다.', en: 'In the full-scale war that began with the Marco Polo Bridge incident of July 1937 Japan occupied the coastal cities and railways and the Nationalist government withdrew to Chongqing. The Red Army, reorganised as the Eighth Route and New Fourth Armies, spread base areas behind enemy lines. After the New Fourth Army incident of 1941 the united front was hollow, and the rectification movement at Yan’an completed Mao’s party. At Japan’s surrender in 1945 the Communists had 1.2 million members, 900,000 regular troops and liberated areas of a hundred million people.' },
        outcome: { ko: '전쟁은 국민정부의 도시 기반과 재정을 무너뜨리고 인플레이션과 부패를 남긴 반면, 공산당에게는 농촌 동원·통일전선·마오쩌둥 사상이라는 세 가지 무기를 주었다. 1945년의 힘의 균형은 1937년과 완전히 달랐다.', en: 'The war destroyed the Nationalist government’s urban base and finances and left inflation and corruption, while it gave the Communists three weapons: rural mobilisation, the united front and Mao Zedong Thought. The balance of forces in 1945 bore no resemblance to that of 1937.' },
        locations: [
            { lat: 36.59, lng: 109.49, label: { ko: '옌안', en: 'Yan’an' } },
            { lat: 39.85, lng: 116.21, label: { ko: '루거우차오', en: 'Marco Polo Bridge' } },
            { lat: 32.06, lng: 118.78, label: { ko: '난징', en: 'Nanjing' } },
            { lat: 29.56, lng: 106.55, label: { ko: '충칭', en: 'Chongqing' } },
            { lat: 30.70, lng: 118.41, label: { ko: '징현 (완난)', en: 'Jing County (southern Anhui)' } },
        ],
        timeline: [
            { date: '1937.07.07', title: { ko: '루거우차오 사건', en: 'Marco Polo Bridge incident' }, body: { ko: '베이핑 교외에서 일본군과 중국군이 충돌해 전면전으로 번졌다.', en: 'A clash between Japanese and Chinese troops outside Beiping escalated into full-scale war.' }, country: ['china', 'japan'], geo: { kind: 'point', lat: 39.85, lng: 116.21, label: { ko: '루거우차오', en: 'Marco Polo Bridge' } } },
            { date: '1937.08–11', title: { ko: '상하이 전투', en: 'Battle of Shanghai' }, body: { ko: '장제스가 정예군을 투입해 3개월을 버텼으나 병력 20만 이상을 잃었다.', en: 'Chiang committed his best divisions and held for three months at the cost of over 200,000 casualties.' }, country: ['china', 'japan'], geo: { kind: 'point', lat: 31.23, lng: 121.47, label: { ko: '상하이', en: 'Shanghai' } } },
            { date: '1937.09.22', title: { ko: '제2차 국공합작 공식 성립', en: 'The second united front announced' }, body: { ko: '공산당이 소비에트 정부 해체와 홍군의 국민혁명군 개편을 선언했고 장제스가 이를 승인했다.', en: 'The Communists announced the dissolution of the soviet government and the Red Army’s reorganisation into the National Revolutionary Army; Chiang accepted.' } },
            { date: '1937.09.25', title: { ko: '핑싱관 전투', en: 'Battle of Pingxingguan' }, body: { ko: '린뱌오의 115사단이 일본군 수송대를 매복 격파해 팔로군의 첫 승리를 알렸다.', en: 'Lin Biao’s 115th Division ambushed a Japanese supply column, the Eighth Route Army’s first victory.' }, country: ['china', 'japan'], geo: { kind: 'point', lat: 39.38, lng: 113.86, label: { ko: '핑싱관', en: 'Pingxingguan' } } },
            { date: '1937.12', title: { ko: '난징 대학살', en: 'Nanjing Massacre' }, body: { ko: '수도 함락 뒤 일본군이 수 주 동안 포로와 민간인 수만~수십만 명을 학살했다.', en: 'After the capital fell Japanese troops massacred tens of thousands and more of prisoners and civilians over several weeks.' }, country: ['china', 'japan'], geo: { kind: 'point', lat: 32.06, lng: 118.78, label: { ko: '난징', en: 'Nanjing' } } },
            { date: '1938.05', title: { ko: '마오의 「지구전론」', en: 'Mao’s “On Protracted War”' }, body: { ko: '전략적 방어·대치·반격의 3단계론으로 항전의 장기화를 예견했다.', en: 'Foresaw a long war in three stages — strategic defence, stalemate and counter-offensive.' }, geo: { kind: 'point', lat: 36.59, lng: 109.49, label: { ko: '옌안', en: 'Yan’an' } } },
            { date: '1938.10', title: { ko: '우한·광저우 함락, 충칭 천도', en: 'Wuhan and Guangzhou fall; the capital moves to Chongqing' }, body: { ko: '일본군이 연안과 창장 중류를 장악했고 전선은 교착 국면에 들어갔다.', en: 'Japan held the coast and the middle Yangtze; the front settled into stalemate.' }, country: ['china', 'japan'], geo: { kind: 'point', lat: 29.56, lng: 106.55, label: { ko: '충칭', en: 'Chongqing' } } },
            { date: '1940.01', title: { ko: '「신민주주의론」', en: '“On New Democracy”' }, body: { ko: '마오가 프롤레타리아가 이끄는 여러 계급의 연합독재라는 혁명의 첫 단계를 정식화했다.', en: 'Mao formulated the first stage of the revolution as a joint dictatorship of several classes led by the proletariat.' } },
            { date: '1940.03', title: { ko: '왕징웨이의 난징 정부', en: 'Wang Jingwei’s Nanjing government' }, body: { ko: '일본이 후원하는 「국민정부」가 난징에 세워졌다.', en: 'A Japanese-sponsored “National Government” was installed at Nanjing.' }, country: ['china', 'japan'], geo: { kind: 'point', lat: 32.06, lng: 118.78, label: { ko: '난징', en: 'Nanjing' } } },
            { date: '1940.08–12', title: { ko: '백단대전', en: 'Hundred Regiments Offensive' }, body: { ko: '펑더화이가 화베이에서 팔로군 100여 개 연대로 철도·광산을 공격했고, 일본군의 「삼광 작전」 보복이 뒤따랐다.', en: 'Peng Dehuai attacked railways and mines across north China with over a hundred Eighth Route Army regiments; Japan answered with the “three alls” reprisals.' }, country: ['china', 'japan'], geo: { kind: 'point', lat: 37.87, lng: 112.55, label: { ko: '타이위안 일대', en: 'Taiyuan area' } } },
            { date: '1941.01', title: { ko: '완난 사변 (신4군 사건)', en: 'The New Fourth Army incident' }, body: { ko: '국민당군이 안후이 남부에서 신4군 본부를 공격해 9천 명 가운데 대부분을 죽이거나 포로로 잡았다. 합작은 사실상 끝났다.', en: 'Nationalist troops attacked the New Fourth Army headquarters in southern Anhui, killing or capturing most of its nine thousand men; the front was effectively over.' }, geo: { kind: 'point', lat: 30.70, lng: 118.41, label: { ko: '징현', en: 'Jing County' } } },
            { date: '1942.02', title: { ko: '옌안 정풍운동 시작', en: 'The Yan’an rectification begins' }, body: { ko: '마오의 「당의 작풍을 정돈하자」 연설로 사상 정비 운동이 시작되었다.', en: 'Mao’s speech “Rectify the Party’s Style of Work” launched the campaign.' }, geo: { kind: 'point', lat: 36.59, lng: 109.49, label: { ko: '옌안', en: 'Yan’an' } } },
            { date: '1944.07', title: { ko: '미군 딕시 사절단 옌안 도착', en: 'The US Dixie Mission reaches Yan’an' }, body: { ko: '미군 관찰단이 옌안에 상주하며 공산당과 접촉했다. 같은 해 일본의 이치고 작전이 국민당군을 대파했다.', en: 'A US Army observer group took up residence at Yan’an; the same year Japan’s Ichi-Go offensive routed the Nationalist armies.' }, country: ['china', 'usa'], geo: { kind: 'point', lat: 36.59, lng: 109.49, label: { ko: '옌안', en: 'Yan’an' } } },
            { date: '1945.04–06', title: { ko: '중공 제7차 당대회', en: 'The Seventh Party Congress' }, body: { ko: '마오쩌둥 사상이 당 규약에 들어갔고 마오가 주석으로 선출되었다.', en: 'Mao Zedong Thought entered the party constitution and Mao was elected chairman.' }, geo: { kind: 'point', lat: 36.59, lng: 109.49, label: { ko: '옌안', en: 'Yan’an' } } },
            { date: '1945.08.15', title: { ko: '일본 항복', en: 'Japan surrenders' }, body: { ko: '소련의 만주 진공과 원폭 투하 뒤 일본이 항복했다. 두 당은 점령지 접수를 놓고 경쟁에 들어갔다.', en: 'After the Soviet invasion of Manchuria and the atomic bombs Japan surrendered; the two parties raced to take over the occupied areas.' }, country: ['china', 'japan'], geo: { kind: 'point', lat: 39.90, lng: 116.40, label: { ko: '베이핑', en: 'Beiping' } } },
        ],
        sections: [
            {
                heading: { ko: '루거우차오에서 난징까지', en: 'From Marco Polo Bridge to Nanjing' },
                paragraphs: [
                    { ko: '1931년 만주를 점령한 일본은 1935년까지 화베이의 「자치」를 강요하며 잠식했고, 1937년 7월 7일 밤 베이핑 교외 루거우차오의 소규모 충돌을 전면전으로 확대했다. 장제스는 7월 17일 루산 담화에서 「최후의 관두」를 선언했고, 8월 상하이에 독일식 훈련을 받은 정예 사단을 투입해 3개월을 버텼으나 병력 20만 이상을 잃었다.', en: 'Having seized Manchuria in 1931, Japan encroached on north China by forcing “autonomy” on it through 1935, and on the night of 7 July 1937 escalated a minor clash at Marco Polo Bridge outside Beiping into full war. In his Lushan statement of 17 July Chiang declared “the last critical juncture”, and in August he threw his German-trained divisions into Shanghai, holding for three months at a cost of more than 200,000 men.', sources: [W + 'Marco_Polo_Bridge_Incident', W + 'Battle_of_Shanghai'] },
                    { ko: '12월 13일 수도 난징이 함락되었고 일본군은 수 주에 걸쳐 포로와 민간인을 학살했다. 희생자 수는 중국의 30만 명 공식 추정에서 서구 학계의 수만~20만 명 추정까지 갈린다. 국민정부는 우한을 거쳐 1938년 10월 쓰촨 충칭으로 옮겼고, 일본군은 연안과 철도·대도시를 장악했으나 광대한 농촌은 「점」과 「선」만 지배하는 데 그쳤다.', en: 'The capital Nanjing fell on 13 December and for weeks Japanese troops massacred prisoners and civilians; estimates of the dead range from China’s official 300,000 to Western scholarly figures of tens of thousands up to 200,000. The Nationalist government moved via Wuhan to Chongqing in Sichuan in October 1938; Japan held the coast, the railways and the big cities, but in the vast countryside it controlled only “points and lines”.', sources: [W + 'Nanjing_Massacre', W + 'Second_Sino-Japanese_War'] },
                ],
            },
            {
                heading: { ko: '합작의 조건: 팔로군과 신4군', en: 'The terms of the front: the Eighth Route and New Fourth Armies' },
                paragraphs: [
                    { ko: '시안 사변 뒤의 협상은 전쟁이 터지자 급히 마무리되었다. 1937년 8월 산베이의 홍군 4만 6천 명은 국민혁명군 제8로군(주더·펑더화이) 3개 사단으로, 남방의 유격대는 신4군(예팅·샹잉)으로 개편되었고, 산간닝 변구는 국민정부 관할의 「특구」가 되었다. 9월 22일 공산당은 「국공합작 선언」에서 삼민주의 실현을 위해 싸우겠다고 밝혔고 장제스가 이를 승인했다.', en: 'The negotiations that followed the Xi’an Incident were hurriedly concluded when war broke out. In August 1937 the 46,000 Red Army troops in northern Shaanxi became three divisions of the Eighth Route Army (Zhu De, Peng Dehuai) of the National Revolutionary Army, the southern guerrillas became the New Fourth Army (Ye Ting, Xiang Ying), and the Shaan-Gan-Ning border region became a “special region” under the national government. On 22 September the Communists declared they would fight for the Three Principles of the People, and Chiang endorsed the declaration.', sources: [W + 'Second_United_Front', W + 'Eighth_Route_Army'] },
                    { ko: '합작은 두 당이 서로 다른 계산으로 맺은 것이었다. 장제스에게는 공산당을 국가 군대 안에 묶어 두는 장치였고, 마오에게는 「독립자주」 원칙 아래 적 후방으로 진출할 기회였다. 1937년 9월 핑싱관에서 린뱌오의 115사단이 일본군 수송대를 매복 격파한 승리는 정치적으로 크게 선전되었으나, 마오는 대규모 정규전을 피하고 유격전과 근거지 건설에 집중하라고 지시했다. 왕밍은 1937년 말 모스크바에서 돌아와 「모든 것을 통일전선을 통해」라며 국민당 협조를 앞세웠고, 이 노선 차이는 곧 당내 투쟁이 되었다.', en: 'The two parties entered the front with different calculations. For Chiang it was a device to bind the Communists inside the national army; for Mao, an opportunity to move behind enemy lines under the principle of “independence and initiative”. Lin Biao’s ambush of a Japanese supply column at Pingxingguan in September 1937 was loudly publicised, but Mao ordered the army to avoid large regular battles and concentrate on guerrilla war and base-building. Wang Ming, returning from Moscow at the end of 1937, urged “everything through the united front” and cooperation with the Kuomintang, and this difference of line soon became an inner-party struggle.', sources: [W + 'Battle_of_Pingxingguan', W + 'Wang_Ming'] },
                ],
            },
            {
                heading: { ko: '충칭의 전쟁: 소모와 인플레이션', en: 'Chongqing’s war: attrition and inflation' },
                paragraphs: [
                    { ko: '1938년 10월 우한 함락 뒤 전선은 교착되었다. 국민당군은 1938년 타이얼좡에서 승리를 거두기도 했으나 정예 병력의 손실, 화베이·화둥 세수 기반의 상실, 일본군의 충칭 폭격으로 소모되었다. 정부는 지폐 발행으로 전비를 댔고 1937년에서 1945년 사이 물가는 2천 배 넘게 올랐다. 징병과 징발은 농민의 원한을 샀고 관료의 부패가 만연했다.', en: 'After Wuhan fell in October 1938 the front stalemated. The Nationalist army won at Taierzhuang in 1938 but was worn down by the loss of its best troops, of its tax base in north and east China, and by the bombing of Chongqing. The government financed the war by printing money and prices rose more than two thousandfold between 1937 and 1945; conscription and requisition bred peasant resentment and official corruption spread.', sources: [W + 'Battle_of_Taierzhuang', W + 'Second_Sino-Japanese_War'] },
                    { ko: '1941년 12월 태평양전쟁으로 중국은 연합국의 일원이 되었고 미국의 원조와 스틸웰 장군이 왔으나 장제스와 스틸웰의 갈등은 1944년 스틸웰 소환으로 끝났다. 1944년 일본의 이치고 작전은 허난에서 광시까지 국민당군을 대파해 정부의 무능을 드러냈다. 같은 해 미군 딕시 사절단이 옌안에 상주하며 공산당의 규율과 사기에 호의적인 보고를 보냈고, 미국은 두 당의 연립을 중재하려 했다.', en: 'With the Pacific War in December 1941 China became one of the Allies, and American aid and General Stilwell arrived, but Chiang’s conflict with Stilwell ended in the general’s recall in 1944. Japan’s Ichi-Go offensive that year routed the Nationalist armies from Henan to Guangxi and exposed the government’s weakness. The same year the US Army’s Dixie Mission took up residence at Yan’an and sent favourable reports on Communist discipline and morale, and Washington tried to broker a coalition of the two parties.', sources: [W + 'Joseph_Stilwell', W + 'Dixie_Mission'] },
                ],
            },
            {
                heading: { ko: '적 후방의 근거지', en: 'Bases behind enemy lines' },
                paragraphs: [
                    { ko: '팔로군은 일본군이 지나간 화베이 농촌에 진차지(녜룽전)·진지루위(류보청·덩샤오핑)·산둥 등 근거지를 세웠다. 근거지 정부는 지주 토지를 몰수하지 않는 대신 소작료·이자 감면(감조감식)을 시행하고 「3·3제」로 공산당원·좌파·중간파가 정권을 나누는 통일전선 정부를 운영했다. 이 온건한 정책은 신민주주의의 실험이었고, 지주와 중농까지 항일의 이름으로 끌어들였다.', en: 'The Eighth Route Army built bases in the north China countryside Japan had swept through — Jin-Cha-Ji (Nie Rongzhen), Jin-Ji-Lu-Yu (Liu Bocheng and Deng Xiaoping), Shandong. Base governments did not confiscate landlord land but reduced rents and interest, and ran united-front administrations under the “three-thirds system” dividing office among Communists, leftists and centrists. This moderate policy was the laboratory of New Democracy, drawing in landlords and middle peasants in the name of resistance.', sources: [W + 'Shaan-Gan-Ning_Border_Region', M + 'volume-2/mswv2_26.htm'] },
                    { ko: '1940년 8~12월 펑더화이가 지휘한 백단대전은 팔로군 100여 개 연대로 화베이의 철도·탄광을 공격해 일본군에 큰 피해를 주었다. 그러나 이는 팔로군의 실력을 노출했고, 일본군은 「모두 죽이고 모두 태우고 모두 빼앗는」 삼광(三光) 소탕작전으로 보복해 1941~1942년 근거지 인구와 병력이 크게 줄었다. 마오는 뒤에 백단대전을 대규모 정규전의 잘못으로 비판했고 이는 1959년 펑더화이 비판의 한 항목이 되었다.', en: 'From August to December 1940 the Hundred Regiments Offensive under Peng Dehuai struck railways and mines across north China with more than a hundred regiments and inflicted heavy losses on Japan. But it exposed the Eighth Route Army’s strength, and Japan retaliated with the “kill all, burn all, loot all” mopping-up campaigns; in 1941–1942 the population and troops of the bases fell sharply. Mao later criticised the offensive as a mistaken resort to large-scale regular warfare, and it became one of the charges against Peng in 1959.', sources: [W + 'Hundred_Regiments_Offensive', W + 'Peng_Dehuai'] },
                ],
            },
            {
                heading: { ko: '완난 사변: 합작의 실질적 종언', en: 'The New Fourth Army incident: the end of the front in substance' },
                paragraphs: [
                    { ko: '창장 하류에서 신4군이 세력을 넓히자 국민당은 1940년 10월 창장 이북으로의 이동을 명령했다. 1941년 1월 이동 중이던 신4군 본부 9천 명이 안후이 남부 징현에서 국민당군 8만의 포위를 받아 대부분 전사하거나 포로가 되었고, 군장 예팅은 체포되고 부군장 샹잉은 살해되었다. 장제스는 신4군의 「반란」을 이유로 부대 번호를 취소했다.', en: 'As the New Fourth Army expanded on the lower Yangtze, the Kuomintang ordered it north of the river in October 1940. In January 1941 its headquarters column of nine thousand, on the move, was surrounded by 80,000 Nationalist troops at Jing County in southern Anhui; most were killed or captured, the commander Ye Ting was arrested and his deputy Xiang Ying killed. Chiang cancelled the army’s designation for “mutiny”.', sources: [W + 'New_Fourth_Army_incident', W + 'Chen_Yi_(marshal)'] },
                    { ko: '공산당은 천이를 대리군장으로 신4군을 재건했고 국민당에 대한 선전전에서 우위를 얻었다. 이후 두 당은 「합작」의 이름을 유지한 채 서로를 봉쇄했다. 국민당은 산간닝 변구를 40만 병력으로 포위했고, 옌안은 「자력갱생」의 대생산운동으로 봉쇄를 버텼다. 소련의 대일 중립조약(1941년 4월) 뒤 옌안에 대한 소련의 지원은 미미했고 공산당은 자립적으로 성장했다.', en: 'The Communists rebuilt the New Fourth Army with Chen Yi as acting commander and gained the upper hand in the propaganda war. Thereafter the two parties blockaded each other while keeping the name of “cooperation”: the Kuomintang ringed the Shaan-Gan-Ning region with 400,000 troops and Yan’an survived through the “self-reliance” production drive. After the Soviet–Japanese neutrality pact of April 1941 Soviet support for Yan’an was slight, and the party grew on its own resources.', sources: [W + 'New_Fourth_Army_incident', W + 'Second_United_Front'] },
                ],
            },
            {
                heading: { ko: '옌안: 정풍운동과 마오쩌둥 사상', en: 'Yan’an: rectification and Mao Zedong Thought' },
                paragraphs: [
                    { ko: '1942년 2월 마오는 「당의 작풍을 정돈하자」와 「당팔고에 반대한다」로 정풍운동을 열었다. 표적은 소련에서 돌아온 왕밍 등의 「교조주의」와 지식인의 「주관주의」였고, 방법은 지정 문헌 학습·자아비판·심사였다. 왕스웨이의 「야생 백합」이 옌안의 등급제를 비판하자 그는 「트로츠키파」로 몰렸고, 5월 「옌안 문예좌담회 연설」은 문예가 노동자·농민·병사에 복무해야 한다고 규정했다.', en: 'In February 1942 Mao opened the rectification movement with “Rectify the Party’s Style of Work” and “Oppose Stereotyped Party Writing”. The targets were the “dogmatism” of Wang Ming and the returned students and the “subjectivism” of intellectuals; the methods were study of assigned texts, self-criticism and screening. When Wang Shiwei’s “Wild Lilies” criticised the graded privileges at Yan’an he was branded a Trotskyist, and in May the “Talks at the Yan’an Forum on Literature and Art” laid down that art must serve workers, peasants and soldiers.', sources: [M + 'volume-3/mswv3_06.htm', M + 'volume-3/mswv3_08.htm'] },
                    { ko: '1943년 캉성의 「구조 운동」은 국민당 지역에서 온 청년 수천 명을 특무로 몰아 자백을 강요했고, 마오는 이듬해 과잉을 인정했다. 1945년 4월 「약간의 역사 문제에 관한 결의」는 당사를 마오의 노선이 옳았던 역사로 다시 썼고, 4~6월 제7차 당대회는 류사오치의 보고를 통해 「마오쩌둥 사상」을 당의 지도사상으로 규약에 넣었다. 마오는 당 주석이 되었고, 옌안에서 형성된 지도부 — 류사오치·저우언라이·주더·런비스 — 가 이후 30년을 통치했다.', en: 'In 1943 Kang Sheng’s “rescue campaign” branded thousands of young people from the Nationalist areas as agents and forced confessions; Mao admitted the excesses the next year. The “Resolution on Certain Questions in the History of Our Party” of April 1945 rewrote party history as the vindication of Mao’s line, and the Seventh Congress of April–June, through Liu Shaoqi’s report, wrote “Mao Zedong Thought” into the constitution as the party’s guiding ideology. Mao became chairman, and the leadership formed at Yan’an — Liu Shaoqi, Zhou Enlai, Zhu De, Ren Bishi — ruled for the next thirty years.', sources: [W + 'Yan%27an_Rectification_Movement', W + 'Mao_Zedong_Thought'] },
                ],
            },
            {
                heading: { ko: '1945년의 결산', en: 'The balance sheet of 1945' },
                paragraphs: [
                    { ko: '1945년 8월 소련군이 만주에 진공하고 원폭이 투하되자 일본은 항복했다. 그 시점에 공산당은 당원 120만, 정규군 91만과 민병 200만, 19개 해방구 인구 약 1억을 가지고 있었다. 1937년의 4만 병력과 비교하면 전쟁은 공산당을 전국 정당으로 만든 셈이었다. 국민당은 여전히 정부·도시·미국의 승인을 가졌으나 군대는 지치고 재정은 무너져 있었다.', en: 'Japan surrendered in August 1945 after the Soviet invasion of Manchuria and the atomic bombs. By then the Communists had 1.2 million members, 910,000 regular troops with two million militia, and nineteen liberated areas of about a hundred million people; against the 40,000 troops of 1937, the war had made them a national party. The Kuomintang still held the government, the cities and American recognition, but its army was exhausted and its finances broken.', sources: [W + 'Second_Sino-Japanese_War', W + 'Chinese_Communist_Revolution'] },
                    { ko: '전쟁의 해석은 지금도 갈린다. 공산당은 자신이 항일의 「중류지주」였다고 말하고, 국민당과 많은 역사가는 대규모 전투의 대부분을 국민당군이 치렀다고 반박한다. 확실한 것은 중국이 1,400만~2천만 명의 인명 손실을 치렀고, 전쟁이 국민당의 국가를 소모시키는 동시에 공산당에게 농민 동원의 학교를 제공했다는 점이다. 이 비대칭이 1946년 내전의 출발 조건이었다.', en: 'The interpretation of the war remains disputed. The Communists say they were the “mainstay” of resistance; the Kuomintang and many historians reply that Nationalist armies fought most of the large battles. What is certain is that China lost between fourteen and twenty million people, and that the war exhausted the Nationalist state while giving the Communists a school of peasant mobilisation. This asymmetry was the starting condition of the civil war of 1946.', sources: [W + 'Second_Sino-Japanese_War', K + '%EC%A4%91%EC%9D%BC_%EC%A0%84%EC%9F%81'] },
                ],
            },
        ],
        people: [
            { id: 'mao-zedong', kind: 'leader', relation: { ko: '옌안의 당 지도자 · 「지구전론」과 정풍운동', en: 'Party leader at Yan’an: “On Protracted War” and rectification' }, note: { ko: '유격전과 근거지 건설을 지시했고 정풍운동으로 당을 자신의 사상 아래 통일했다.', en: 'Ordered guerrilla war and base-building and united the party under his thought through rectification.' } },
            { id: 'chiang-kai-shek', kind: 'leader', relation: { ko: '국민정부 주석 · 항전의 총사령', en: 'Head of the Nationalist government and commander of the resistance' }, note: { ko: '충칭에서 8년의 항전을 이끌었으나 국가와 군대를 소모했다.', en: 'Led eight years of resistance from Chongqing at the cost of his state and army.' } },
            { id: 'zhu-de', kind: 'leader', relation: { ko: '팔로군 총사령', en: 'Commander-in-chief of the Eighth Route Army' }, note: { ko: '홍군의 개편 뒤 팔로군을 지휘했다.', en: 'Commanded the Eighth Route Army after the Red Army’s reorganisation.' } },
            { id: 'peng-dehuai', kind: 'executor', relation: { ko: '백단대전의 지휘관', en: 'Commander of the Hundred Regiments Offensive' }, note: { ko: '1940년 화베이에서 대규모 공세를 지휘했고 뒤에 이 일로 비판받았다.', en: 'Directed the 1940 offensive in north China and was later criticised for it.' } },
            { id: 'lin-biao', kind: 'participant', relation: { ko: '115사단장, 핑싱관의 승리', en: '115th Division commander, victor of Pingxingguan' }, note: { ko: '1937년 9월 첫 승리를 거둔 뒤 부상으로 소련에서 치료받았다.', en: 'Won the first victory in September 1937, then was wounded and treated in the Soviet Union.' } },
            { id: 'nie-rongzhen', kind: 'participant', relation: { ko: '진차지 근거지 사령관', en: 'Commander of the Jin-Cha-Ji base' }, note: { ko: '화베이 최초의 항일 근거지를 세워 지휘했다.', en: 'Founded and commanded the first anti-Japanese base in north China.' } },
            { id: 'liu-bocheng', kind: 'participant', relation: { ko: '129사단장', en: 'Commander of the 129th Division' }, note: { ko: '덩샤오핑과 진지루위 근거지를 세웠다.', en: 'Built the Jin-Ji-Lu-Yu base with Deng Xiaoping.' } },
            { id: 'deng-xiaoping', kind: 'participant', relation: { ko: '129사단 정치위원', en: 'Political commissar of the 129th Division' }, note: { ko: '류보청과 함께 「류덩」 부대를 이끌었다.', en: 'Led the “Liu–Deng” army with Liu Bocheng.' } },
            { id: 'chen-yi', kind: 'participant', relation: { ko: '완난 사변 뒤 신4군 대리군장', en: 'Acting commander of the New Fourth Army after the incident' }, note: { ko: '1941년 궤멸된 신4군을 재건했다.', en: 'Rebuilt the New Fourth Army after its destruction in 1941.' } },
            { id: 'wang-ming', kind: 'opponent', relation: { ko: '「모든 것을 통일전선을 통해」 노선', en: '“Everything through the united front”' }, note: { ko: '1937년 말 귀국해 국민당 협조를 앞세웠다가 정풍운동의 표적이 되었다.', en: 'Returned at the end of 1937 urging cooperation with the Kuomintang, and became the target of rectification.' } },
            { id: 'kang-sheng', kind: 'executor', relation: { ko: '정풍운동의 「구조 운동」 지휘', en: 'Directed the rectification “rescue campaign”' }, note: { ko: '사회부장으로 1943년 간부 심사와 자백 강요를 주도했다.', en: 'As Social Affairs chief ran the 1943 cadre screening and forced confessions.' } },
            { id: 'wang-shiwei', kind: 'target', relation: { ko: '「야생 백합」의 작가, 정풍의 첫 희생자', en: 'Author of “Wild Lilies”, rectification’s first victim' }, note: { ko: '1942년 옌안의 특권을 비판했다가 트로츠키파로 몰려 1947년 처형되었다.', en: 'Criticised privilege at Yan’an in 1942, was branded a Trotskyist and executed in 1947.' } },
            { id: 'ding-ling', kind: 'target', relation: { ko: '「3·8절 유감」으로 비판받은 작가', en: 'Writer criticised for “Thoughts on March 8”' }, note: { ko: '옌안의 성차별을 지적했다가 정풍운동에서 비판받았다.', en: 'Pointed to sexism at Yan’an and was criticised in the rectification.' } },
            { id: 'liu-shaoqi', kind: 'participant', relation: { ko: '제7차 당대회에서 마오쩌둥 사상을 정식화', en: 'Codified Mao Zedong Thought at the Seventh Congress' }, note: { ko: '당 규약 개정 보고로 마오쩌둥 사상을 당의 지도사상으로 규정했다.', en: 'His report on the constitution made Mao Zedong Thought the party’s guiding ideology.' } },
            { id: 'zhou-enlai', kind: 'participant', relation: { ko: '충칭 주재 공산당 대표', en: 'Communist representative at Chongqing' }, note: { ko: '국민정부와의 연락과 통일전선 외교를 맡았다.', en: 'Handled liaison with the Nationalist government and united-front diplomacy.' } },
            { id: 'wang-jingwei', kind: 'opponent', relation: { ko: '일본 후원 난징 정부의 수반', en: 'Head of the Japanese-sponsored Nanjing government' }, note: { ko: '1938년 충칭을 떠나 1940년 일본이 세운 정부를 이끌었다.', en: 'Left Chongqing in 1938 and led the Japanese-installed government from 1940.' } },
            { id: 'hirohito', kind: 'opponent', relation: { ko: '침략국 일본의 천황', en: 'Emperor of the invading power' }, note: { ko: '1945년 8월 항복을 선언했다.', en: 'Announced the surrender in August 1945.' } },
        ],
        related: ['jiangxi-soviet-and-long-march', 'chinese-civil-war-1945-1949', 'pacific-war', 'soviet-japanese-border-wars'],
    },
    {
        id: 'chinese-civil-war-1945-1949', sortOrder: 145, period: '1945–1949', countries: ['china', 'usa', 'soviet'],
        title: { ko: '국공내전', en: 'The Chinese Civil War' },
        question: { ko: '미국의 지원과 압도적 병력을 가진 국민당은 어떻게 4년 만에 대륙을 잃었는가?', en: 'How did the Kuomintang, with American backing and overwhelming numbers, lose the mainland in four years?' },
        summary: { ko: '일본 항복 뒤 충칭 회담과 마셜의 중재는 두 당의 무장 경쟁을 막지 못했다. 1946년 전면 내전이 시작되자 국민당군은 도시를 점령했으나 만주에서 린뱌오의 동북야전군에 밀렸고, 1948~1949년 랴오선·화이하이·핑진 세 전역에서 150만 병력을 잃었다. 1949년 4월 인민해방군이 창장을 건넜고 장제스는 대만으로 퇴각했다.', en: 'After Japan’s surrender the Chongqing talks and Marshall’s mediation could not stop the two parties’ armed competition. When full civil war began in 1946 the Nationalists took cities but were pushed back in Manchuria by Lin Biao’s Northeast Field Army, and in the three campaigns of 1948–1949 — Liaoshen, Huaihai and Pingjin — they lost 1.5 million men. In April 1949 the People’s Liberation Army crossed the Yangtze and Chiang Kai-shek retreated to Taiwan.' },
        outcome: { ko: '공산당은 토지개혁으로 농민을 동원하고 국민당의 인플레이션·부패·군사적 실책을 이용해 승리했다. 10월 1일 중화인민공화국이 선포되었고, 대만해협을 사이에 둔 두 정부의 대치와 미·소 냉전의 아시아 전선이 시작되었다.', en: 'The Communists won by mobilising the peasantry through land reform and exploiting Nationalist inflation, corruption and military blunders. On 1 October the People’s Republic was proclaimed, and the confrontation of two governments across the Taiwan Strait and the Asian front of the Cold War began.' },
        locations: [
            { lat: 34.26, lng: 117.19, label: { ko: '쉬저우 (화이하이)', en: 'Xuzhou (Huaihai)' } },
            { lat: 41.80, lng: 123.43, label: { ko: '선양', en: 'Shenyang' } },
            { lat: 29.56, lng: 106.55, label: { ko: '충칭', en: 'Chongqing' } },
            { lat: 39.90, lng: 116.40, label: { ko: '베이핑', en: 'Beiping' } },
            { lat: 32.06, lng: 118.78, label: { ko: '난징', en: 'Nanjing' } },
            { lat: 25.03, lng: 121.57, label: { ko: '타이베이', en: 'Taipei' } },
        ],
        timeline: [
            { date: '1945.08.28–10.10', title: { ko: '충칭 회담과 쌍십협정', en: 'The Chongqing talks and the Double Tenth Agreement' }, body: { ko: '마오가 미국 대사 헐리의 보증으로 충칭에 가 장제스와 회담했다. 협정은 정치협상회의 개최에 합의했으나 군대 문제는 풀지 못했다.', en: 'Mao flew to Chongqing under US ambassador Hurley’s guarantee to meet Chiang; the agreement promised a political consultative conference but left the army question unresolved.' }, country: ['china', 'usa'], geo: { kind: 'point', lat: 29.56, lng: 106.55, label: { ko: '충칭', en: 'Chongqing' } } },
            { date: '1945.08–1946.04', title: { ko: '만주를 둘러싼 경쟁', en: 'The race for Manchuria' }, body: { ko: '소련군 점령하의 만주에 공산당군이 먼저 들어갔고 미군은 국민당군을 공수했다. 소련은 일본군 무기를 넘기고 1946년 봄 철수했다.', en: 'Communist troops entered Soviet-occupied Manchuria first while US aircraft flew in Nationalist armies; the Soviets handed over Japanese weapons and withdrew in spring 1946.' }, country: ['china', 'soviet', 'usa'], geo: { kind: 'point', lat: 41.80, lng: 123.43, label: { ko: '선양', en: 'Shenyang' } } },
            { date: '1946.01', title: { ko: '마셜의 정전 중재', en: 'Marshall’s ceasefire' }, body: { ko: '트루먼의 특사 마셜이 정전과 정치협상회의를 이끌어 냈으나 만주에서 전투는 계속되었다.', en: 'Truman’s envoy Marshall secured a ceasefire and the consultative conference, but fighting went on in Manchuria.' }, country: ['china', 'usa'] },
            { date: '1946.05', title: { ko: '쓰핑 전투', en: 'Battle of Siping' }, body: { ko: '린뱌오의 부대가 쓰핑에서 한 달을 버티다 패퇴해 쑹화강 북쪽으로 밀렸다.', en: 'Lin Biao’s troops held Siping for a month before retreating north of the Songhua River.' }, geo: { kind: 'point', lat: 43.17, lng: 124.35, label: { ko: '쓰핑', en: 'Siping' } } },
            { date: '1946.06', title: { ko: '전면 내전 개시', en: 'Full-scale civil war' }, body: { ko: '국민당군이 중원 해방구를 공격했다. 마셜은 1947년 1월 중재 실패를 선언하고 귀국했다.', en: 'Nationalist forces attacked the Central Plains liberated area; Marshall declared his mission a failure and left in January 1947.' } },
            { date: '1947.03', title: { ko: '옌안 함락', en: 'Yan’an falls' }, body: { ko: '후쭝난의 국민당군이 옌안을 점령했으나 마오는 산베이에 남아 유격전을 지휘했다.', en: 'Hu Zongnan’s Nationalists took Yan’an, but Mao stayed in northern Shaanxi directing the war.' }, geo: { kind: 'point', lat: 36.59, lng: 109.49, label: { ko: '옌안', en: 'Yan’an' } } },
            { date: '1947.06', title: { ko: '류덩 부대의 다볘산 진격', en: 'The Liu–Deng thrust into the Dabie Mountains' }, body: { ko: '류보청·덩샤오핑이 황허를 건너 국민당 지역 깊숙이 진출해 전략적 반격을 열었다.', en: 'Liu Bocheng and Deng Xiaoping crossed the Yellow River deep into Nationalist territory, opening the strategic counter-offensive.' }, geo: { kind: 'arrow', points: [[35.5, 115.0], [31.3, 115.5]], label: { ko: '황허 → 다볘산 (개략)', en: 'Yellow River → Dabie Mountains (schematic)' }, actor: { ko: '인민해방군', en: 'People’s Liberation Army' } } },
            { date: '1947.10', title: { ko: '「중국토지법대강」', en: 'Outline Land Law' }, body: { ko: '해방구에서 지주 토지의 몰수와 균등 분배가 공포되어 농민 동원을 뒷받침했다.', en: 'Confiscation and equal division of landlord land was promulgated in the liberated areas, underpinning peasant mobilisation.' } },
            { date: '1948.09–11', title: { ko: '랴오선 전역', en: 'Liaoshen campaign' }, body: { ko: '동북야전군이 진저우를 점령해 만주를 봉쇄하고 창춘·선양의 국민당군 47만을 섬멸했다.', en: 'The Northeast Field Army took Jinzhou, sealed Manchuria and destroyed 470,000 Nationalist troops at Changchun and Shenyang.' }, geo: { kind: 'point', lat: 41.10, lng: 121.12, label: { ko: '진저우', en: 'Jinzhou' } } },
            { date: '1948.11–1949.01', title: { ko: '화이하이 전역', en: 'Huaihai campaign' }, body: { ko: '쉬저우 일대에서 60만 해방군이 국민당군 55만을 섬멸했다. 농민 500만이 보급을 날랐다.', en: 'Around Xuzhou 600,000 PLA troops destroyed 550,000 Nationalists; five million peasants carried supplies.' }, geo: { kind: 'point', lat: 34.26, lng: 117.19, label: { ko: '쉬저우', en: 'Xuzhou' } } },
            { date: '1948.11–1949.01', title: { ko: '핑진 전역', en: 'Pingjin campaign' }, body: { ko: '톈진이 함락되고 베이핑의 푸쭤이가 1월 31일 무혈 항복했다.', en: 'Tianjin fell and Fu Zuoyi surrendered Beiping without a fight on 31 January.' }, geo: { kind: 'point', lat: 39.90, lng: 116.40, label: { ko: '베이핑', en: 'Beiping' } } },
            { date: '1949.04.21', title: { ko: '창장 도하', en: 'Crossing the Yangtze' }, body: { ko: '해방군 100만이 창장을 건너 23일 난징을 점령했다. 5월 상하이, 10월 광저우가 뒤따랐다.', en: 'A million PLA troops crossed the Yangtze and took Nanjing on the 23rd; Shanghai fell in May and Guangzhou in October.' }, geo: { kind: 'arrow', points: [[32.5, 118.0], [32.06, 118.78]], label: { ko: '창장 도하 → 난징 (개략)', en: 'Yangtze crossing → Nanjing (schematic)' }, actor: { ko: '인민해방군', en: 'People’s Liberation Army' } } },
            { date: '1949.10.01', title: { ko: '중화인민공화국 선포', en: 'The People’s Republic proclaimed' }, body: { ko: '마오가 톈안먼에서 중앙인민정부 수립을 선포했다. 12월 장제스는 타이베이로 옮겼다.', en: 'Mao proclaimed the Central People’s Government at Tiananmen; in December Chiang moved to Taipei.' }, geo: { kind: 'point', lat: 39.91, lng: 116.40, label: { ko: '톈안먼', en: 'Tiananmen' } } },
        ],
        sections: [
            {
                heading: { ko: '항복의 순간: 누가 접수하는가', en: 'The moment of surrender: who takes over?' },
                paragraphs: [
                    { ko: '1945년 8월 10일 주더는 팔로군에 일본군 점령지 접수를 명령했고 장제스는 공산당군에 「현 위치 대기」를, 일본군에는 국민당군에만 항복하라고 지시했다. 미군은 국민당군 50만을 항공기와 선박으로 연안 도시와 화베이로 실어 날랐고, 공산당은 산둥과 허베이의 병력 10만과 간부 2만을 만주로 보냈다. 소련군이 점령한 만주는 일본이 남긴 최대의 공업 지대였다.', en: 'On 10 August 1945 Zhu De ordered the Eighth Route Army to take over Japanese-held areas; Chiang told the Communists to “stay where you are” and the Japanese to surrender only to Nationalist forces. American aircraft and ships moved 500,000 Nationalist troops to the coastal cities and north China, while the Communists sent 100,000 troops and 20,000 cadres from Shandong and Hebei into Manchuria, the largest industrial region Japan had left, then under Soviet occupation.', sources: [W + 'Chinese_Civil_War', CS + '23.htm'] },
                    { ko: '스탈린은 1945년 8월 국민정부와 우호동맹조약을 맺어 뤼순·다롄과 만주 철도의 권익을 얻은 대가로 장제스를 유일한 정부로 인정했고, 마오에게 충칭 회담에 응하라고 권했다. 8월 28일 마오는 미국 대사 헐리의 보증 아래 충칭으로 날아가 43일간 장제스와 협상했다. 10월 10일의 쌍십협정은 정치협상회의 개최와 「평화 건국」에 합의했으나 해방구 정권과 군대의 처리는 미결로 남겼다.', en: 'In August 1945 Stalin signed a treaty of friendship with the Nationalist government that gave the Soviets rights at Port Arthur, Dalian and on the Manchurian railways in exchange for recognising Chiang as China’s sole government, and he urged Mao to go to Chongqing. On 28 August Mao flew there under US ambassador Hurley’s guarantee and negotiated with Chiang for forty-three days. The Double Tenth Agreement of 10 October promised a political consultative conference and “peaceful nation-building” but left the liberated-area governments and the armies unsettled.', sources: [W + 'Chongqing_Negotiations', W + 'Double_Tenth_Agreement'] },
                ],
            },
            {
                heading: { ko: '마셜의 중재와 실패', en: 'Marshall’s mission and its failure' },
                paragraphs: [
                    { ko: '트루먼은 1945년 12월 조지 마셜 장군을 특사로 보내 연립정부와 군대 통합을 중재하게 했다. 1946년 1월 정전 협정과 정치협상회의는 헌법 개정과 국민당 일당제 종식에 합의했고, 2월 군대 통합안이 서명되었다. 그러나 국민당 강경파는 협상회의 결정을 뒤집었고, 소련군이 철수하는 만주에서는 양군이 곧바로 충돌했다.', en: 'In December 1945 Truman sent General George Marshall to broker a coalition government and the integration of the armies. The ceasefire of January 1946 and the political consultative conference agreed on constitutional revision and the end of one-party rule, and a plan to merge the armies was signed in February. But Kuomintang hardliners overturned the conference decisions, and in Manchuria, as the Soviets withdrew, the two armies clashed at once.', sources: [W + 'Marshall_Mission', W + 'George_C._Marshall'] },
                    { ko: '1946년 4~5월 쓰핑 전투에서 린뱌오는 마오의 명령으로 도시 방어전을 벌였다가 패해 쑹화강 북쪽으로 물러났고, 마셜의 압력으로 국민당군의 추격이 멈춘 6월의 휴전은 공산당에 숨 쉴 시간을 주었다. 6월 말 국민당군이 중원 해방구를 공격하면서 전면 내전이 시작되었다. 마셜은 양측을 「극단파」로 비난하며 1947년 1월 귀국했고, 미국은 국민당에 원조를 계속하되 직접 개입은 피했다.', en: 'At Siping in April–May 1946 Lin Biao, on Mao’s orders, fought a defensive battle for the city, lost and fell back north of the Songhua; the June truce that Marshall pressed on the Nationalists halted their pursuit and gave the Communists breathing space. Full civil war began at the end of June when Nationalist forces attacked the Central Plains liberated area. Marshall left in January 1947 denouncing “extremists” on both sides, and the United States continued aid to the Nationalists while avoiding direct intervention.', sources: [W + 'Battle_of_Siping', 'https://history.state.gov/milestones/1945-1952/chinese-rev'] },
                ],
            },
            {
                heading: { ko: '국민당의 공세와 그 한계', en: 'The Nationalist offensive and its limits' },
                paragraphs: [
                    { ko: '1946년 국민당군은 430만 병력과 미국제 장비로 해방구의 도시 대부분을 점령했고 1947년 3월에는 옌안까지 손에 넣었다. 그러나 점령한 도시는 병력을 분산시켰고 철도선 방어에 묶인 부대는 기동력을 잃었다. 공산당은 「도시를 포기하고 병력을 보존한다」는 원칙으로 물러나며 고립된 부대를 하나씩 섬멸했다. 마오는 산베이의 작은 마을들을 옮겨 다니며 지휘했다.', en: 'In 1946 the Nationalists, with 4.3 million troops and American equipment, took most of the towns in the liberated areas and in March 1947 Yan’an itself. But the captured cities dispersed their forces, and units tied to defending railway lines lost mobility. The Communists withdrew on the principle of “give up cities, preserve forces” and destroyed isolated units one by one, while Mao directed the war from a succession of small villages in northern Shaanxi.', sources: [W + 'Chinese_Civil_War', CS + '23.htm'] },
                    { ko: '후방에서 국민정부는 무너지고 있었다. 접수 관료의 부패(「접수」가 「겁수(劫收)」로 불렸다), 통화 남발로 인한 초인플레이션, 1947년 2·28 사건으로 드러난 대만 통치의 폭력, 학생 운동에 대한 탄압이 도시 중간층을 등 돌리게 했다. 1948년 8월 금원권 개혁은 몇 달 만에 실패했고 상하이의 물가는 1937년의 수백만 배가 되었다.', en: 'Behind the lines the Nationalist state was disintegrating. The corruption of the takeover officials (“takeover” became “plunder-over”), hyperinflation from the printing presses, the violence of Taiwan’s rule exposed in the 28 February incident of 1947 and the repression of student protests turned the urban middle classes away. The gold yuan reform of August 1948 failed within months, and Shanghai prices reached millions of times their 1937 level.', sources: [W + 'Chinese_Civil_War', W + 'Chiang_Kai-shek'] },
                ],
            },
            {
                heading: { ko: '토지개혁: 농민을 전쟁에 묶다', en: 'Land reform: binding the peasants to the war' },
                paragraphs: [
                    { ko: '1946년 5월 「5·4 지시」로 공산당은 항일전쟁기의 감조감식에서 지주 토지 몰수로 돌아섰고, 1947년 10월 「중국토지법대강」은 촌락 단위의 균등 분배를 명령했다. 「소고(訴苦)」 집회에서 농민은 지주를 고발했고, 분배받은 토지를 지키려는 이해가 징병과 보급 동원의 기반이 되었다. 화이하이 전역에서 500만 농민이 손수레로 보급을 날랐다는 통계는 이 동원의 규모를 보여준다.', en: 'With the “May Fourth Directive” of 1946 the Communists moved from the wartime rent reductions to confiscating landlord land, and the Outline Land Law of October 1947 ordered equal division village by village. At “speak bitterness” meetings peasants denounced landlords, and their stake in keeping the land they received became the basis of conscription and supply mobilisation; the figure of five million peasants hauling supplies by handcart in the Huaihai campaign shows the scale.', sources: [W + 'Land_Reform_Movement_(China)', W + 'Huaihai_campaign'] },
                    { ko: '토지개혁은 폭력을 동반했다. 1947년의 급진 국면에서 부농·중농까지 「투쟁」 대상이 되었고 지주 수십만 명이 처형되거나 맞아 죽었다. 1948년 초 마오와 런비스는 「좌경」 과잉을 시정하라고 지시해 중농 보호로 돌아섰다. 이 경험 — 대중 동원과 과잉, 그리고 시정 — 은 건국 후 토지개혁의 원형이 되었다.', en: 'Land reform was violent. In the radical phase of 1947 rich and middle peasants too became targets of “struggle”, and hundreds of thousands of landlords were executed or beaten to death. In early 1948 Mao and Ren Bishi ordered the “leftist” excesses corrected and returned to protecting middle peasants. This experience — mass mobilisation, excess and correction — became the template for land reform after 1949.', sources: [W + 'Land_Reform_Movement_(China)', W + 'Ren_Bishi'] },
                ],
            },
            {
                heading: { ko: '세 개의 전역: 1948년 가을에서 1949년 겨울까지', en: 'The three campaigns: autumn 1948 to winter 1949' },
                paragraphs: [
                    { ko: '1948년 가을 힘의 균형이 뒤집혔다. 9~11월 랴오선 전역에서 린뱌오의 동북야전군은 진저우를 먼저 점령해 만주의 출구를 막고, 창춘을 굶겨 항복시키고(포위 5개월간 민간인 수만~10여만 명 아사), 선양의 국민당군을 섬멸해 만주 전체와 병력 47만을 얻었다. 만주의 공업과 소련이 넘긴 일본군 무기가 해방군의 손에 들어왔다.', en: 'In autumn 1948 the balance turned. In the Liaoshen campaign of September–November Lin Biao’s Northeast Field Army first took Jinzhou to seal the exit from Manchuria, starved Changchun into surrender (tens of thousands or more civilians died in the five-month siege) and destroyed the Nationalist armies at Shenyang, gaining all Manchuria and 470,000 troops. Manchuria’s industry and the Japanese weapons the Soviets had handed over fell to the PLA.', sources: [W + 'Liaoshen_campaign', W + 'Siege_of_Changchun'] },
                    { ko: '11월 초 쉬저우 일대에서 시작된 화이하이 전역에서 천이·류보청·덩샤오핑·쑤위의 화둥·중원 야전군 60만은 65일 동안 국민당군 55만을 포위 섬멸했다. 국민당 지휘부의 혼선과 두위밍 병단의 고립이 결정적이었다. 같은 시기 핑진 전역에서 동북야전군이 화베이로 들어와 톈진을 함락시켰고, 베이핑의 푸쭤이는 1949년 1월 31일 무혈 항복했다. 세 전역에서 국민당은 150만 병력을 잃었다.', en: 'In the Huaihai campaign that began around Xuzhou in early November, the East China and Central Plains Field Armies of Chen Yi, Liu Bocheng, Deng Xiaoping and Su Yu, 600,000 strong, encircled and destroyed 550,000 Nationalists in sixty-five days; confusion in the Nationalist command and the isolation of Du Yuming’s army group were decisive. In the simultaneous Pingjin campaign the Northeast Field Army entered north China and took Tianjin, and Fu Zuoyi surrendered Beiping without a fight on 31 January 1949. In the three campaigns the Nationalists lost 1.5 million men.', sources: [W + 'Huaihai_campaign', W + 'Pingjin_campaign'] },
                ],
            },
            {
                heading: { ko: '창장 도하와 대만 퇴각', en: 'Crossing the Yangtze and the retreat to Taiwan' },
                paragraphs: [
                    { ko: '1949년 1월 장제스는 「하야」하고 리쭝런이 총통 대리로 화평 교섭에 나섰으나, 공산당의 8개 조건은 사실상 항복 요구였다. 4월 20일 협상이 결렬되자 이튿날 해방군 100만이 창장을 건너 23일 난징을 점령했다. 영국 군함 애머시스트호가 창장에서 포격당한 사건은 열강의 시대가 끝났음을 알렸다. 5월 상하이, 8월 창사, 10월 광저우, 11월 충칭이 차례로 함락되었다.', en: 'In January 1949 Chiang “retired” and Li Zongren as acting president sought peace, but the Communists’ eight conditions amounted to a demand for surrender. When talks collapsed on 20 April, a million PLA troops crossed the Yangtze the next day and took Nanjing on the 23rd; the shelling of the British frigate Amethyst on the river signalled that the age of the powers was over. Shanghai fell in May, Changsha in August, Guangzhou in October and Chongqing in November.', sources: [W + 'Yangtze_River_Crossing_Campaign', W + 'Chinese_Civil_War'] },
                    { ko: '장제스는 1949년 내내 황금과 정예 부대, 고궁 유물을 대만으로 옮겼고 12월 10일 청두에서 타이베이로 날아갔다. 대만에는 국민당군 60만과 피란민 100만이 모였다. 하이난·저우산 군도는 1950년 함락되었으나, 1950년 6월 한국전쟁이 터지자 트루먼이 제7함대를 대만해협에 보내 공산당의 대만 공격 계획은 무기한 연기되었다. 두 정부의 대치는 이렇게 고착되었다.', en: 'Throughout 1949 Chiang moved gold, his best troops and the Palace Museum treasures to Taiwan, and on 10 December he flew from Chengdu to Taipei; 600,000 troops and a million refugees gathered on the island. Hainan and the Zhoushan islands fell in 1950, but when the Korean War broke out in June 1950 Truman sent the Seventh Fleet into the Taiwan Strait and the Communist plan to attack Taiwan was postponed indefinitely. The standoff between the two governments was thus frozen.', sources: [W + 'Chiang_Kai-shek', 'https://history.state.gov/milestones/1953-1960/taiwan-strait-crises'] },
                ],
            },
            {
                heading: { ko: '왜 공산당이 이겼는가', en: 'Why the Communists won' },
                paragraphs: [
                    { ko: '1949년 8월 미국 국무부의 「중국 백서」는 국민당의 패배가 「미국의 통제 밖」에 있었다고 결론지었고, 마오는 「레이턴 스튜어트여, 안녕」에서 이를 조롱했다. 미국 안에서는 「누가 중국을 잃었는가」 논쟁이 매카시즘의 불씨가 되었다. 스탈린은 1949년 초까지도 창장 이북에서 멈추라고 조언했으나 마오는 이를 무시했고, 뒤에 「우리를 믿지 않았다」고 회고했다.', en: 'The State Department’s China White Paper of August 1949 concluded that the Nationalist defeat lay “beyond the control of the United States”, and Mao mocked it in “Farewell, Leighton Stuart!”. In America the question of “who lost China” fed McCarthyism. Stalin advised as late as early 1949 that the Communists stop at the Yangtze; Mao ignored him and later recalled that Moscow “did not trust us”.', sources: [M + 'volume-4/mswv4_67.htm', W + 'Chinese_Civil_War'] },
                    { ko: '역사가들은 승리의 원인을 여러 층위에서 찾는다. 농촌 동원과 토지개혁, 규율 있는 군대와 통일된 지휘, 국민당의 부패·인플레이션·전략적 실책, 만주라는 병참 기지, 그리고 항일전쟁이 만든 힘의 비대칭이다. 공산당의 승리를 「농민 혁명」으로 보는 해석과 「군사적 정복」으로 보는 해석은 이후 인민공화국의 성격을 둘러싼 논쟁으로 이어진다.', en: 'Historians locate the causes of victory on several levels: rural mobilisation and land reform, a disciplined army under unified command, Nationalist corruption, inflation and strategic blunders, Manchuria as a logistical base, and the asymmetry of forces created by the war with Japan. Whether the Communist victory is read as a “peasant revolution” or a “military conquest” feeds the later debate over the nature of the People’s Republic.', sources: [W + 'Chinese_Communist_Revolution', CS + '23.htm'] },
                ],
            },
        ],
        people: [
            { id: 'mao-zedong', kind: 'leader', relation: { ko: '공산당 주석 · 전쟁의 최고 지휘자', en: 'Party chairman and supreme director of the war' }, note: { ko: '충칭 회담에 나섰고 산베이에서 세 전역을 지휘했으며 1949년 10월 건국을 선포했다.', en: 'Went to the Chongqing talks, directed the three campaigns from Shaanxi and proclaimed the republic in October 1949.' } },
            { id: 'chiang-kai-shek', kind: 'leader', relation: { ko: '국민정부 총통', en: 'President of the Nationalist government' }, note: { ko: '1949년 1월 하야했다가 12월 대만으로 퇴각했다.', en: 'Retired in January 1949 and withdrew to Taiwan in December.' } },
            { id: 'lin-biao', kind: 'executor', relation: { ko: '동북야전군 사령관 · 랴오선·핑진 전역', en: 'Northeast Field Army commander at Liaoshen and Pingjin' }, note: { ko: '만주를 정복하고 화베이를 점령해 승리의 결정적 국면을 만들었다.', en: 'Conquered Manchuria and took north China, the decisive phase of the victory.' } },
            { id: 'liu-bocheng', kind: 'executor', relation: { ko: '중원야전군 사령관 · 화이하이 전역', en: 'Central Plains Field Army commander at Huaihai' }, note: { ko: '1947년 다볘산 진격과 1948~1949년 화이하이 전역을 지휘했다.', en: 'Led the 1947 Dabie thrust and the Huaihai campaign.' } },
            { id: 'deng-xiaoping', kind: 'executor', relation: { ko: '화이하이 전역 총전위 서기', en: 'Secretary of the Huaihai front committee' }, note: { ko: '화이하이 전역의 정치적 총책임자였고 창장 도하 뒤 서남을 접수했다.', en: 'Political head of the Huaihai campaign; took over the Southwest after the Yangtze crossing.' } },
            { id: 'chen-yi', kind: 'executor', relation: { ko: '화둥야전군 사령관', en: 'East China Field Army commander' }, note: { ko: '화이하이 전역에 참전하고 상하이를 점령했다.', en: 'Fought at Huaihai and took Shanghai.' } },
            { id: 'zhu-de', kind: 'leader', relation: { ko: '인민해방군 총사령', en: 'Commander-in-chief of the PLA' }, note: { ko: '1945년 8월 일본군 점령지 접수를 명령했다.', en: 'Ordered the takeover of Japanese-held areas in August 1945.' } },
            { id: 'zhou-enlai', kind: 'participant', relation: { ko: '충칭 회담과 마셜 중재의 공산당 협상 대표', en: 'Communist negotiator at Chongqing and with Marshall' }, note: { ko: '1945~1946년 협상을 이끌었다.', en: 'Led the negotiations of 1945–1946.' } },
            { id: 'liu-shaoqi', kind: 'participant', relation: { ko: '토지개혁 정책의 책임자', en: 'In charge of land-reform policy' }, note: { ko: '1947년 전국토지회의를 주재해 「중국토지법대강」을 채택했다.', en: 'Chaired the 1947 national land conference that adopted the Outline Land Law.' } },
            { id: 'ren-bishi', kind: 'participant', relation: { ko: '토지개혁 과잉의 시정', en: 'Corrected land-reform excesses' }, note: { ko: '1948년 1월 계급 구분과 중농 보호를 다시 규정했다.', en: 'Redefined class categories and middle-peasant protection in January 1948.' } },
            { id: 'george-c-marshall', kind: 'participant', relation: { ko: '미국의 중재 특사', en: 'US mediator' }, note: { ko: '1945년 12월~1947년 1월 연립정부 수립을 중재하다 실패를 선언했다.', en: 'Mediated for a coalition from December 1945 and declared failure in January 1947.' } },
            { id: 'harry-s-truman', kind: 'participant', relation: { ko: '국민당 원조와 불개입의 미국 대통령', en: 'US president: aid without intervention' }, note: { ko: '마셜을 파견하고 1949년 백서로 국민당 패배의 책임을 부인했다.', en: 'Sent Marshall and in the 1949 White Paper disclaimed responsibility for the Nationalist defeat.' } },
            { id: 'stalin', kind: 'participant', relation: { ko: '1945년 국민정부와 조약, 신중한 조언', en: 'Treaty with the Nationalists in 1945 and cautious advice' }, note: { ko: '장제스를 승인하고 마오에게 협상을 권했으며 만주에서는 공산당을 도왔다.', en: 'Recognised Chiang, urged Mao to negotiate, and helped the Communists in Manchuria.' } },
            { id: 'song-ziwen', kind: 'participant', relation: { ko: '1945년 중소조약 협상의 국민정부 외교부장', en: 'Nationalist foreign minister in the 1945 Sino-Soviet treaty' }, note: { ko: '모스크바에서 스탈린과 우호동맹조약을 협상했다.', en: 'Negotiated the treaty of friendship with Stalin in Moscow.' } },
            { id: 'peng-dehuai', kind: 'participant', relation: { ko: '서북야전군 사령관', en: 'Northwest Field Army commander' }, note: { ko: '옌안 함락 뒤 산베이와 서북을 되찾았다.', en: 'Recovered northern Shaanxi and the Northwest after Yan’an fell.' } },
        ],
        related: ['sino-japanese-war-1937-1945', 'chinese-revolution-1949', 'manchurian-operation', 'prc-consolidation-1949-1956'],
    },
    {
        id: 'prc-consolidation-1949-1956', sortOrder: 186, period: '1949–1956', countries: ['china', 'soviet'],
        title: { ko: '신민주주의에서 사회주의 개조로', en: 'From New Democracy to socialist transformation' },
        question: { ko: '「여러 계급의 연합」을 약속한 새 국가는 왜 7년 만에 사유재산을 없앴는가?', en: 'Why did a state that promised a “coalition of classes” abolish private property within seven years?' },
        summary: { ko: '건국 초기 공산당은 토지개혁·반혁명 진압·항미원조·삼반오반으로 권력을 다졌고, 1950년 중소조약과 소련 원조로 제1차 5개년 계획을 시작했다. 1953년 「과도기 총노선」은 신민주주의를 사실상 끝냈고, 1955~1956년 농업 집단화와 상공업 공사합영으로 사회주의 개조가 「기본적으로 완성」되었다. 가오강·라오수스 사건은 건국 후 첫 지도부 숙청이었다.', en: 'In its first years the party consolidated power through land reform, the suppression of counter-revolutionaries, the Korean War mobilisation and the Three-anti and Five-anti campaigns, and with the 1950 Sino-Soviet treaty and Soviet aid began the First Five-Year Plan. The “general line for the transition period” of 1953 effectively ended New Democracy, and the collectivisation of agriculture and the joint state-private conversion of commerce and industry in 1955–1956 “basically completed” socialist transformation. The Gao Gang–Rao Shushi affair was the first leadership purge of the People’s Republic.' },
        outcome: { ko: '1956년 중국은 소련형 계획경제와 일당 국가를 갖춘 사회주의 국가가 되었다. 급속한 개조의 성공은 마오에게 자신감을 주어 소련 모델을 넘어서는 「중국의 길」 — 대약진 — 을 구상하게 했다.', en: 'By 1956 China was a socialist state with a Soviet-type planned economy and a one-party state. The success of rapid transformation gave Mao the confidence to conceive a “Chinese road” beyond the Soviet model — the Great Leap.' },
        locations: [
            { lat: 39.90, lng: 116.40, label: { ko: '베이징', en: 'Beijing' } },
            { lat: 55.75, lng: 37.62, label: { ko: '모스크바', en: 'Moscow' } },
            { lat: 31.23, lng: 121.47, label: { ko: '상하이', en: 'Shanghai' } },
            { lat: 41.80, lng: 123.43, label: { ko: '선양', en: 'Shenyang' } },
            { lat: 40.12, lng: 124.39, label: { ko: '단둥 (압록강)', en: 'Dandong (Yalu)' } },
        ],
        timeline: [
            { date: '1949.09', title: { ko: '정치협상회의와 공동강령', en: 'The CPPCC and the Common Programme' }, body: { ko: '공산당·민주당파·무당파가 참여한 회의가 임시헌법 구실의 공동강령을 채택했다.', en: 'A conference of Communists, democratic parties and non-party figures adopted the Common Programme as a provisional constitution.' } },
            { date: '1949.12–1950.02', title: { ko: '마오의 모스크바 방문과 중소조약', en: 'Mao in Moscow and the Sino-Soviet treaty' }, body: { ko: '두 달의 협상 끝에 우호동맹상호원조조약과 3억 달러 차관에 합의했다.', en: 'After two months of hard bargaining the treaty of friendship, alliance and mutual assistance and a $300 million loan were signed.' }, country: ['china', 'soviet'], geo: { kind: 'point', lat: 55.75, lng: 37.62, label: { ko: '모스크바', en: 'Moscow' } } },
            { date: '1950.06', title: { ko: '토지개혁법 공포', en: 'Land Reform Law' }, body: { ko: '전국 농촌에서 지주 토지 몰수와 분배가 시작되어 1952년 말 완료되었다.', en: 'Confiscation and division of landlord land began nationwide and was completed by the end of 1952.' } },
            { date: '1950.10', title: { ko: '반혁명 진압운동 · 한국전쟁 참전', en: 'Suppression of counter-revolutionaries; entry into the Korean War' }, body: { ko: '10월 10일 반혁명 진압 지시가 내려졌고 19일 인민지원군이 압록강을 건넜다.', en: 'The directive to suppress counter-revolutionaries was issued on 10 October; on the 19th the People’s Volunteers crossed the Yalu.' }, geo: { kind: 'point', lat: 40.12, lng: 124.39, label: { ko: '압록강', en: 'Yalu River' } } },
            { date: '1951.12–1952.10', title: { ko: '삼반·오반 운동', en: 'Three-anti and Five-anti campaigns' }, body: { ko: '간부의 부패와 자본가의 「5독」을 겨냥한 운동으로 민간 상공업이 국가에 종속되었다.', en: 'Campaigns against cadre corruption and the capitalists’ “five poisons” subordinated private business to the state.' }, geo: { kind: 'point', lat: 31.23, lng: 121.47, label: { ko: '상하이', en: 'Shanghai' } } },
            { date: '1953', title: { ko: '제1차 5개년 계획 · 과도기 총노선', en: 'First Five-Year Plan and the general line for the transition' }, body: { ko: '소련 원조 156개 사업으로 중공업 건설이 시작되었고, 마오는 신민주주의 대신 사회주의 이행을 선언했다.', en: 'Heavy-industry construction began with 156 Soviet-aided projects, and Mao proclaimed the transition to socialism in place of New Democracy.' }, country: ['china', 'soviet'], geo: { kind: 'point', lat: 41.80, lng: 123.43, label: { ko: '선양 (동북 공업지대)', en: 'Shenyang (Northeast industrial base)' } } },
            { date: '1954.02', title: { ko: '가오강·라오수스 사건', en: 'The Gao Gang–Rao Shushi affair' }, body: { ko: '4중전회가 두 사람을 「반당연맹」으로 비판했고 가오강은 8월 자살했다.', en: 'The Fourth Plenum condemned the two as an “anti-party alliance”; Gao Gang killed himself in August.' } },
            { date: '1954.09', title: { ko: '헌법 제정과 전국인민대표대회', en: 'The 1954 constitution and the National People’s Congress' }, body: { ko: '첫 헌법이 채택되고 마오가 국가주석, 류사오치가 전인대 상무위원장이 되었다.', en: 'The first constitution was adopted; Mao became state chairman and Liu Shaoqi chaired the NPC Standing Committee.' } },
            { date: '1955.07', title: { ko: '「농업 합작화 문제에 관하여」', en: '“On the Question of Agricultural Cooperation”' }, body: { ko: '마오가 점진론자를 「전족한 여인」이라 비판하며 집단화를 가속했고 1년 만에 농가 90%가 합작사에 들어갔다.', en: 'Mao attacked the gradualists as “women with bound feet” and accelerated collectivisation; within a year ninety per cent of households were in cooperatives.' } },
            { date: '1956.01', title: { ko: '상공업 공사합영 완료', en: 'Joint state-private conversion completed' }, body: { ko: '베이징·상하이 등에서 자본가들이 「북과 징을 울리며」 기업의 국가 편입을 신청했다.', en: 'In Beijing, Shanghai and elsewhere capitalists applied “to the sound of gongs and drums” for their firms to be taken into joint ownership.' }, geo: { kind: 'point', lat: 39.90, lng: 116.40, label: { ko: '베이징', en: 'Beijing' } } },
            { date: '1956.09', title: { ko: '제8차 당대회', en: 'The Eighth Party Congress' }, body: { ko: '사회주의 개조의 완성을 선언하고 주요 모순을 「선진적 제도와 낙후한 생산력」으로 규정했으며 마오쩌둥 사상을 당 규약에서 뺐다.', en: 'Declared socialist transformation complete, defined the main contradiction as “advanced institutions and backward productive forces” and dropped Mao Zedong Thought from the constitution.' } },
        ],
        sections: [
            {
                heading: { ko: '공동강령: 연합정부의 약속', en: 'The Common Programme: the promise of coalition' },
                paragraphs: [
                    { ko: '1949년 9월 베이징에서 열린 중국인민정치협상회의에는 공산당 외에 민주동맹·국민당혁명위원회 등 민주당파와 무당파 인사가 참여했다. 회의가 채택한 공동강령은 「노동자계급이 이끄는 인민민주독재」를 국가 형태로 삼되 민족자본의 보호, 사유재산 존중, 다당 협력을 약속했다. 쑹칭링 등 비공산당 인사가 부주석이 되었고 마오는 「인민민주독재론」에서 이 연합의 계급적 한계를 명시했다.', en: 'The Chinese People’s Political Consultative Conference that met in Beijing in September 1949 included, besides the Communists, the democratic parties such as the Democratic League and the Kuomintang Revolutionary Committee and non-party figures. The Common Programme it adopted made the “people’s democratic dictatorship led by the working class” the form of the state while promising protection of national capital, respect for private property and multi-party cooperation. Non-Communists such as Soong Ching-ling became vice-chairs, and Mao’s “On the People’s Democratic Dictatorship” spelled out the class limits of the coalition.', sources: [M + 'volume-4/mswv4_65.htm', 'https://english.www.gov.cn/archive/white_paper/2014/09/09/content_281474986284659.htm'] },
                    { ko: '새 정부의 첫 과제는 초인플레이션 수습과 경제 복구였다. 천윈은 국영 무역기업을 통해 곡물·면화를 장악하고 통화를 통일해 1950년 봄 물가를 안정시켰다. 1952년까지 공업 생산은 전전 최고 수준을 회복했다. 이 시기의 혼합경제는 국영 부문이 주도하되 민간 상공업과 시장이 공존하는 것이었고, 마오는 신민주주의 단계가 「상당히 긴 기간」 계속될 것이라 말했다.', en: 'The new government’s first tasks were to tame hyperinflation and restore the economy. Chen Yun used state trading companies to control grain and cotton and unified the currency, stabilising prices by spring 1950; by 1952 industrial output had regained its pre-war peak. The mixed economy of these years was state-led but left private business and markets in place, and Mao said the New Democratic stage would last “a fairly long period”.', sources: [CS + '24.htm', W + 'Chen_Yun'] },
                ],
            },
            {
                heading: { ko: '모스크바의 두 달', en: 'Two months in Moscow' },
                paragraphs: [
                    { ko: '1949년 12월 마오는 스탈린의 70세 생일에 맞춰 첫 외국 방문으로 모스크바에 갔다. 스탈린은 1945년 국민정부와 맺은 조약을 유지하려 했고 마오는 몇 주 동안 별장에서 사실상 방치되었다. 저우언라이가 합류한 1월에야 협상이 시작되어 2월 14일 우호동맹상호원조조약이 서명되었다. 소련은 3억 달러의 차관과 1952년까지의 창춘철도·뤼순 반환을 약속했으나 몽골 독립 승인과 신장·만주의 특권을 요구했다.', en: 'In December 1949 Mao made his first trip abroad, to Moscow for Stalin’s seventieth birthday. Stalin wanted to keep the 1945 treaty with the Nationalists and Mao was left virtually idle at a dacha for weeks; only when Zhou Enlai arrived in January did negotiations begin, and the treaty of friendship, alliance and mutual assistance was signed on 14 February. The Soviets promised a $300 million loan and the return of the Changchun railway and Port Arthur by 1952, but required recognition of Mongolia’s independence and privileges in Xinjiang and Manchuria.', sources: [W + 'Sino-Soviet_Treaty_of_Friendship,_Alliance_and_Mutual_Assistance', W + 'Mao_Zedong'] },
                    { ko: '「일변도(一邊倒)」 — 소련 쪽에 선다 — 는 마오가 1949년 6월 이미 선언한 노선이었다. 조약은 냉전에서 중국의 자리를 정했고, 1953년 시작된 제1차 5개년 계획의 156개 핵심 사업에 소련의 설비·기술자·차관이 투입되었다. 안산 제철소와 창춘 자동차 공장 같은 동북의 공업 기지가 이렇게 세워졌다. 그러나 스탈린의 대우에 대한 마오의 불만은 뒤에 중소 분열의 개인적 배경이 되었다.', en: '“Leaning to one side” — the Soviet side — was a line Mao had declared in June 1949. The treaty fixed China’s place in the Cold War, and Soviet equipment, technicians and credits went into the 156 key projects of the First Five-Year Plan begun in 1953; the industrial bases of the Northeast, such as the Anshan steelworks and the Changchun automobile plant, were built this way. Mao’s resentment at his treatment by Stalin, however, became part of the personal background of the later Sino-Soviet split.', sources: [W + 'First_five-year_plan_(China)', CS + '24.htm'] },
                ],
            },
            {
                heading: { ko: '토지개혁과 반혁명 진압', en: 'Land reform and the suppression of counter-revolutionaries' },
                paragraphs: [
                    { ko: '1950년 6월 토지개혁법은 새로 해방된 남방과 서부 농촌에서 지주 토지의 몰수와 분배를 명령했다. 공작대가 마을에 들어가 계급을 구분하고 「소고」 집회와 「투쟁대회」를 열었으며, 지주는 처형·투옥되거나 「감독 노동」에 놓였다. 1952년 말까지 3억 농민이 4,700만 헥타르를 분배받았고, 처형된 지주는 100만~200만 명으로 추산된다. 개혁은 향촌의 옛 권력을 없애고 당의 조직을 마을 단위까지 뿌리내리게 했다.', en: 'The Land Reform Law of June 1950 ordered confiscation and division of landlord land in the newly liberated countryside of the south and west. Work teams entered villages, classified households and held “speak bitterness” and “struggle” meetings; landlords were executed, imprisoned or placed under “supervised labour”. By the end of 1952 three hundred million peasants had received 47 million hectares, and an estimated one to two million landlords had been executed. The reform destroyed the old rural power and rooted the party’s organisation at village level.', sources: [W + 'Land_Reform_Movement_(China)', CS + '24.htm'] },
                    { ko: '한국전쟁 참전과 함께 1950년 10월 시작된 반혁명 진압운동은 국민당 잔당·비밀결사·「토비」를 겨냥했다. 마오는 처형 비율의 「할당」을 지방에 내려보냈고 1951년 봄 대중집회에서의 공개 처형이 절정에 달했다. 공식 집계로 71만 명이 처형되었으며, 사상개조 운동은 지식인에게 자아비판과 미국 「숭배」의 청산을 요구했다. 전쟁은 이 모든 운동에 「보가위국」의 명분을 주었다.', en: 'The Campaign to Suppress Counter-revolutionaries, launched in October 1950 alongside the entry into the Korean War, targeted Nationalist remnants, secret societies and “bandits”. Mao sent execution “quotas” down to the provinces, and public executions at mass rallies peaked in spring 1951; by the official count 710,000 people were executed. The thought-reform campaign demanded that intellectuals criticise themselves and purge their “worship” of America. The war gave every campaign the justification of “protecting the home and defending the country”.', sources: [W + 'Campaign_to_Suppress_Counterrevolutionaries', W + 'People%27s_Volunteer_Army'] },
                ],
            },
            {
                heading: { ko: '삼반·오반: 자본가의 종속', en: 'Three-anti, Five-anti: the subordination of the capitalists' },
                paragraphs: [
                    { ko: '1951년 말 시작된 삼반 운동은 간부의 부패·낭비·관료주의를, 1952년의 오반 운동은 자본가의 뇌물·탈세·국가재산 절취·부실공사·경제정보 절취를 겨냥했다. 노동자와 점원이 고용주를 고발하는 「호랑이 사냥」 집회가 상하이·톈진의 상공업계를 휩쓸었고, 벌금과 추징으로 기업 자산이 국가로 넘어갔다. 상하이에서만 자살이 수백 건에 이르렀다.', en: 'The Three-anti campaign begun at the end of 1951 targeted cadres’ corruption, waste and bureaucratism; the Five-anti of 1952 targeted the capitalists’ bribery, tax evasion, theft of state property, cheating on contracts and theft of economic information. “Tiger-hunting” meetings at which workers and clerks denounced their employers swept the business communities of Shanghai and Tianjin, and fines and back-taxes transferred company assets to the state; in Shanghai alone suicides ran into the hundreds.', sources: [W + 'Three-anti_and_Five-anti_Campaigns', CS + '24.htm'] },
                    { ko: '오반 운동은 공동강령이 약속한 민족자본의 보호를 사실상 철회했다. 자본가는 「법을 지키는 부류」와 「위법 부류」로 분류되었고, 국가는 원자재 공급과 판매를 통제해 민간 기업을 계획에 묶었다. 1953년 마오가 「과도기 총노선」에서 「10~15년 안에 사회주의 공업화와 개조를 완성한다」고 선언했을 때, 신민주주의는 사실상 끝나 있었다. 류사오치와 저우언라이는 더 완만한 이행을 생각했으나 마오를 따랐다.', en: 'The Five-anti effectively withdrew the Common Programme’s protection of national capital. Capitalists were sorted into “law-abiding” and “law-breaking” categories, and the state bound private firms to the plan by controlling their supplies and sales. When in 1953 Mao proclaimed in the “general line for the transition period” that socialist industrialisation and transformation would be completed “in ten to fifteen years”, New Democracy was in substance over. Liu Shaoqi and Zhou Enlai had envisaged a slower transition but followed Mao.', sources: [W + 'Three-anti_and_Five-anti_Campaigns', W + 'Liu_Shaoqi'] },
                ],
            },
            {
                heading: { ko: '가오강·라오수스 사건', en: 'The Gao Gang–Rao Shushi affair' },
                paragraphs: [
                    { ko: '동북의 「왕」으로 불린 가오강은 1952년 베이징으로 옮겨 국가계획위원회 주석이 되었고, 마오가 류사오치·저우언라이의 온건 노선에 불만을 표하자 이를 후계 구도의 신호로 읽었다. 그는 조직부장 라오수스와 함께 원로들을 상대로 류사오치를 「백구(白區)」 출신으로 깎아내리며 지지를 모았으나, 덩샤오핑과 천윈이 마오에게 보고했다. 1953년 12월 마오는 「두 개의 사령부」를 경고했다.', en: 'Gao Gang, the “king of the Northeast”, moved to Beijing in 1952 as chairman of the State Planning Commission and read Mao’s displeasure with the moderate line of Liu Shaoqi and Zhou Enlai as a signal about the succession. With the organisation chief Rao Shushi he canvassed the veterans, belittling Liu as a man of the “white areas”, but Deng Xiaoping and Chen Yun reported to Mao, who in December 1953 warned against “two headquarters”.', sources: [W + 'Gao_Gang', W + 'Rao_Shushi'] },
                    { ko: '1954년 2월 4중전회는 두 사람을 「반당연맹」으로 비판했고 가오강은 8월 자살했으며 라오수스는 1955년 체포되어 1975년 옥사했다. 사건은 소련과의 관계도 건드렸다. 가오강은 소련 고문과 가까웠고, 뒤에 흐루쇼프는 그가 스탈린에게 정보를 제공했다고 회고했다. 건국 후 첫 지도부 숙청은 「당내 두 노선」이라는 틀이 마오의 손에서 언제든 쓰일 수 있음을 보여주었다.', en: 'In February 1954 the Fourth Plenum condemned the two as an “anti-party alliance”; Gao Gang killed himself in August, and Rao Shushi was arrested in 1955 and died in prison in 1975. The affair also touched relations with Moscow: Gao had been close to the Soviet advisers, and Khrushchev later recalled that he had passed information to Stalin. The first leadership purge of the People’s Republic showed that the frame of “two lines within the party” was available to Mao at any time.', sources: [W + 'Gao_Gang', CS + '24.htm'] },
                ],
            },
            {
                heading: { ko: '「사회주의 고조」: 집단화와 공사합영', en: 'The “socialist high tide”: collectivisation and joint ownership' },
                paragraphs: [
                    { ko: '토지개혁 뒤 농촌은 호조조 → 초급 합작사(토지 출자, 배당) → 고급 합작사(집단 소유)의 단계를 밟도록 계획되었다. 1955년 여름 마오는 「농업 합작화 문제에 관하여」에서 속도를 늦추려는 간부를 「전족한 여인」에 비유하며 고조를 명령했고, 1956년 말 농가의 96%가 고급 합작사에 들어갔다. 소련이 5년 걸린 집단화를 중국은 1년 반 만에 완료했으며, 곡물 통일구매판매(1953)와 호적제(1958)가 농민을 토지에 묶었다.', en: 'After land reform the countryside was to move through stages — mutual-aid teams, lower cooperatives (land pooled, dividends paid), higher cooperatives (collective ownership). In summer 1955 Mao’s “On the Question of Agricultural Cooperation” compared cadres who wanted to slow down to “women with bound feet” and ordered a high tide; by the end of 1956, 96 per cent of households were in higher cooperatives. China completed in eighteen months what had taken the Soviet Union five years, and unified grain purchase (1953) and household registration (1958) bound the peasants to the land.', sources: [CS + '24.htm', W + 'First_five-year_plan_(China)'] },
                    { ko: '도시에서는 1955년 말부터 몇 달 만에 모든 민간 상공업이 「공사합영」으로 전환되었다. 자본가는 자산 평가액의 연 5% 「정식(定息)」을 10년간 받는 조건으로 소유권을 넘겼고, 베이징과 상하이에서는 북과 징을 울리며 전환을 「신청」하는 행진이 조직되었다. 1956년 9월 제8차 당대회는 개조의 완성을 선언하고 「대규모 계급투쟁은 끝났다」고 했으나, 마오는 곧 이 판단을 뒤집게 된다.', en: 'In the cities, from late 1955 all private business was converted to “joint state-private” ownership within months. Capitalists surrendered ownership in return for a fixed annual interest of five per cent of assessed assets for ten years, and in Beijing and Shanghai parades were organised to “apply” for conversion to gongs and drums. In September 1956 the Eighth Congress declared transformation complete and “large-scale class struggle” over — a judgement Mao would soon reverse.', sources: [CS + '24.htm', W + 'Three-anti_and_Five-anti_Campaigns'] },
                ],
            },
            {
                heading: { ko: '1956년: 모델의 완성과 첫 균열', en: '1956: the model completed, the first cracks' },
                paragraphs: [
                    { ko: '제1차 5개년 계획은 연 15% 이상의 공업 성장을 달성했고 헌법(1954)·국가기구·계획 체계가 소련을 본떠 갖추어졌다. 그러나 1956년 2월 흐루쇼프의 비밀연설은 개인숭배와 소련 모델 자체를 문제 삼았고, 4월 마오는 「10대 관계론」에서 중공업 편중과 중앙집권을 완화하는 「중국의 길」을 말했다. 제8차 당대회가 당 규약에서 마오쩌둥 사상을 뺀 것은 이 분위기의 표현이었다.', en: 'The First Five-Year Plan achieved industrial growth of over fifteen per cent a year, and the constitution of 1954, the state apparatus and the planning system were modelled on the Soviet Union. But Khrushchev’s secret speech in February 1956 put the personality cult and the Soviet model itself in question, and in April Mao’s “On the Ten Major Relationships” spoke of a “Chinese road” easing the bias toward heavy industry and central control. The Eighth Congress’s removal of Mao Zedong Thought from the party constitution expressed the same mood.', sources: [W + 'First_five-year_plan_(China)', W + 'Sino-Soviet_split'] },
                    { ko: '개조의 속도는 문제를 남겼다. 고급 합작사에서 농민의 노동 의욕은 떨어졌고 1956~1957년 일부 지역에서 탈퇴 요구와 소요가 있었으며, 헝가리 혁명은 지도부에 충격을 주었다. 마오는 이 긴장을 「인민 내부 모순」으로 다루겠다며 지식인에게 비판을 권했고, 그 결과가 백화제방과 반우파 투쟁이었다. 1956년의 자신감과 불안이 함께 다음 10년의 급진화를 준비했다.', en: 'The speed of transformation left problems. In the higher cooperatives peasant incentive fell, in 1956–1957 some areas saw demands to withdraw and unrest, and the Hungarian revolution shocked the leadership. Mao proposed to handle the tension as “contradictions among the people” and invited intellectuals to criticise, with the Hundred Flowers and the Anti-Rightist Campaign as the result. The confidence and the anxiety of 1956 together prepared the radicalisation of the next decade.', sources: [M + 'volume-5/mswv5_58.htm', W + 'Hundred_Flowers_Campaign'] },
                ],
            },
        ],
        people: [
            { id: 'mao-zedong', kind: 'leader', relation: { ko: '당 주석 · 국가주석, 개조의 가속자', en: 'Party and state chairman, accelerator of transformation' }, note: { ko: '중소조약을 맺고 과도기 총노선과 농업 집단화의 고조를 명령했다.', en: 'Signed the Sino-Soviet treaty and ordered the general line and the collectivisation high tide.' } },
            { id: 'liu-shaoqi', kind: 'leader', relation: { ko: '당 조직과 토지개혁·집단화 정책의 책임자', en: 'In charge of party organisation, land reform and collectivisation policy' }, note: { ko: '완만한 이행을 생각했으나 마오를 따랐고 가오강의 공격 대상이었다.', en: 'Favoured a slower transition but followed Mao; the target of Gao Gang’s attack.' } },
            { id: 'zhou-enlai', kind: 'leader', relation: { ko: '총리 겸 외교부장', en: 'Premier and foreign minister' }, note: { ko: '모스크바 협상을 마무리했고 제1차 5개년 계획을 관장했다.', en: 'Concluded the Moscow negotiations and oversaw the First Five-Year Plan.' } },
            { id: 'chen-yun', kind: 'executor', relation: { ko: '경제 안정과 계획의 설계자', en: 'Architect of stabilisation and planning' }, note: { ko: '1950년 물가를 안정시키고 통일구매판매 제도를 설계했다.', en: 'Stabilised prices in 1950 and designed unified grain purchase.' } },
            { id: 'gao-gang', kind: 'target', relation: { ko: '「반당연맹」으로 몰려 자살한 계획위원회 주석', en: 'Planning chief purged as an “anti-party alliance”' }, note: { ko: '1954년 비판받고 8월 자살했다.', en: 'Condemned in 1954 and killed himself in August.' } },
            { id: 'rao-shushi', kind: 'target', relation: { ko: '가오강과 함께 숙청된 조직부장', en: 'Organisation chief purged with Gao Gang' }, note: { ko: '1955년 체포되어 1975년 옥중에서 사망했다.', en: 'Arrested in 1955 and died in prison in 1975.' } },
            { id: 'deng-xiaoping', kind: 'participant', relation: { ko: '가오강의 접근을 마오에게 보고', en: 'Reported Gao Gang’s approach to Mao' }, note: { ko: '천윈과 함께 가오강의 움직임을 알려 사건의 계기를 만들었다.', en: 'With Chen Yun alerted Mao to Gao’s manoeuvres.' } },
            { id: 'bo-yibo', kind: 'participant', relation: { ko: '재정부장, 1953년 신세제 논란', en: 'Finance minister in the 1953 tax controversy' }, note: { ko: '공사 기업을 동등하게 과세하는 신세제로 마오의 비판을 받았다.', en: 'Criticised by Mao for a new tax system that treated public and private firms alike.' } },
            { id: 'peng-dehuai', kind: 'executor', relation: { ko: '인민지원군 사령관', en: 'Commander of the People’s Volunteers' }, note: { ko: '1950년 10월 압록강을 건너 한국전쟁을 지휘했다.', en: 'Crossed the Yalu in October 1950 and commanded in Korea.' } },
            { id: 'song-qingling', kind: 'participant', relation: { ko: '중앙인민정부 부주석', en: 'Vice-chair of the Central People’s Government' }, note: { ko: '비공산당 인사로 연합정부의 상징이었다.', en: 'A non-Communist figure symbolising the coalition.' } },
            { id: 'stalin', kind: 'participant', relation: { ko: '1950년 조약의 소련 측 당사자', en: 'Soviet party to the 1950 treaty' }, note: { ko: '마오를 두 달간 기다리게 한 뒤 동맹과 차관에 동의했다.', en: 'Kept Mao waiting two months before agreeing to the alliance and loan.' } },
            { id: 'luo-ruiqing', kind: 'executor', relation: { ko: '공안부장, 반혁명 진압운동', en: 'Public security minister in the suppression campaign' }, note: { ko: '1950~1951년 반혁명 진압운동을 집행했다.', en: 'Executed the 1950–1951 campaign against counter-revolutionaries.' } },
            { id: 'shen-zhihua', kind: 'witness', relation: { ko: '중소 동맹사의 연구자', en: 'Historian of the Sino-Soviet alliance' }, note: { ko: '소련 문서로 1950년 조약 협상과 한국전쟁 참전 결정을 재구성했다.', en: 'Reconstructed the 1950 treaty talks and the Korea decision from Soviet archives.' } },
        ],
        related: ['chinese-revolution-1949', 'korean-war', 'hundred-flowers-anti-rightist', 'sino-soviet-split'],
    },
    {
        id: 'hundred-flowers-anti-rightist', sortOrder: 215, period: '1956–1957', countries: ['china'],
        title: { ko: '백화제방에서 반우파 투쟁으로', en: 'From the Hundred Flowers to the Anti-Rightist Campaign' },
        question: { ko: '당을 비판하라고 초대한 마오는 왜 6주 만에 비판자 55만 명을 우파로 낙인찍었는가?', en: 'Why did Mao, having invited criticism of the party, brand 550,000 critics as rightists within six weeks?' },
        summary: { ko: '흐루쇼프의 비밀연설과 헝가리 혁명 뒤 마오는 「백 가지 꽃이 피게 하라」며 지식인에게 당의 관료주의 비판을 권했다. 1957년 5월 비판이 일당 지배 자체로 번지자 6월 8일 방향을 바꿔 반우파 투쟁을 시작했고, 덩샤오핑이 지휘한 운동은 55만 명에게 우파 낙인을 찍어 노동교양과 하방으로 보냈다.', en: 'After Khrushchev’s secret speech and the Hungarian revolution Mao urged intellectuals to “let a hundred flowers bloom” and criticise the party’s bureaucratism. When in May 1957 the criticism spread to one-party rule itself, he reversed course on 8 June and launched the Anti-Rightist Campaign; run by Deng Xiaoping, it labelled 550,000 people as rightists and sent them to labour re-education and the countryside.' },
        outcome: { ko: '지식인의 비판 통로가 닫히면서 대약진의 과오를 견제할 힘이 사라졌다. 「우파」 낙인은 1978년 이후에야 취소되었고, 운동이 처음부터 「양모」였는지를 둘러싼 논쟁은 마오 시대의 성격을 묻는 질문이 되었다.', en: 'With the intellectuals’ channel of criticism closed, nothing remained to check the errors of the Great Leap. The “rightist” labels were reversed only after 1978, and the argument over whether the campaign was an “open plot” from the start became a question about the nature of the Mao era.' },
        locations: [
            { lat: 39.99, lng: 116.31, label: { ko: '베이징대학', en: 'Peking University' } },
            { lat: 39.90, lng: 116.40, label: { ko: '베이징 중난하이', en: 'Zhongnanhai, Beijing' } },
            { lat: 31.23, lng: 121.47, label: { ko: '상하이', en: 'Shanghai' } },
            { lat: 39.80, lng: 98.00, label: { ko: '자볜거우 (간쑤)', en: 'Jiabiangou (Gansu)' } },
        ],
        timeline: [
            { date: '1956.02', title: { ko: '흐루쇼프의 비밀연설', en: 'Khrushchev’s secret speech' }, body: { ko: '스탈린 비판이 중국 지도부에 개인숭배와 소련 모델의 문제를 제기했다.', en: 'The denunciation of Stalin raised the questions of the personality cult and the Soviet model for the Chinese leadership.' } },
            { date: '1956.05.02', title: { ko: '「백화제방·백가쟁명」 제기', en: 'The Hundred Flowers slogan raised' }, body: { ko: '마오가 최고국무회의에서 학문·예술의 다양성을 권하는 방침을 밝혔다.', en: 'Mao announced at the Supreme State Conference a policy encouraging diversity in scholarship and the arts.' } },
            { date: '1956.10–11', title: { ko: '헝가리 혁명', en: 'The Hungarian revolution' }, body: { ko: '부다페스트의 봉기와 소련의 개입은 마오에게 당과 대중의 괴리가 위험함을 보여주었다.', en: 'The Budapest uprising and Soviet intervention showed Mao the danger of a gulf between party and people.' } },
            { date: '1957.02.27', title: { ko: '「인민 내부 모순의 올바른 처리」', en: '“On the Correct Handling of Contradictions Among the People”' }, body: { ko: '마오가 사회주의 사회의 비적대적 모순은 설득과 토론으로 풀어야 한다고 연설했다.', en: 'Mao argued that non-antagonistic contradictions in socialist society must be resolved by persuasion and discussion.' } },
            { date: '1957.04.27', title: { ko: '당 정풍운동 지시', en: 'The party rectification directive' }, body: { ko: '중앙이 당 외부 인사의 비판을 받는 정풍을 지시했고 5월 초 「대명대방」이 시작되었다.', en: 'The centre ordered a rectification open to criticism from outside the party; the “great blooming” began in early May.' } },
            { date: '1957.05', title: { ko: '비판의 분출', en: 'The outpouring of criticism' }, body: { ko: '민주당파와 대학에서 일당 독점, 소련 모방, 숙청 운동의 과잉을 비판하는 발언과 대자보가 쏟아졌다.', en: 'From the democratic parties and the universities came speeches and posters attacking one-party monopoly, Soviet imitation and the excesses of past campaigns.' }, geo: { kind: 'point', lat: 39.99, lng: 116.31, label: { ko: '베이징대학', en: 'Peking University' } } },
            { date: '1957.05.15', title: { ko: '마오의 내부 지시 「사정이 변하고 있다」', en: 'Mao’s internal note “Things are beginning to change”' }, body: { ko: '당 간부에게 배포된 글에서 마오는 우파가 「미쳐 날뛰게」 두라고 지시했다.', en: 'In a note circulated to cadres Mao said to let the rightists “run wild” for the time being.' } },
            { date: '1957.06.08', title: { ko: '「이것은 무엇 때문인가」', en: '“What is this for?”' }, body: { ko: '『인민일보』 사설과 당 내부 지시로 반우파 투쟁이 시작되었다.', en: 'A People’s Daily editorial and an internal directive launched the Anti-Rightist Campaign.' } },
            { date: '1957.07–09', title: { ko: '우파 낙인의 확산', en: 'The spread of the rightist label' }, body: { ko: '각 단위에 할당이 내려와 지식인·학생·간부 55만 명이 우파로 규정되었다.', en: 'Quotas went down to each unit and 550,000 intellectuals, students and cadres were labelled.' } },
            { date: '1957.08', title: { ko: '노동교양 제도 도입', en: 'Re-education through labour introduced' }, body: { ko: '재판 없이 행정 결정으로 수용을 허용하는 제도가 우파 처리의 도구가 되었다.', en: 'A system of confinement by administrative decision without trial became the instrument for dealing with rightists.' }, geo: { kind: 'point', lat: 39.80, lng: 98.00, label: { ko: '자볜거우 농장', en: 'Jiabiangou farm' } } },
            { date: '1959–1961', title: { ko: '우파 수용소의 대기근', en: 'Famine in the rightist camps' }, body: { ko: '간쑤 자볜거우 농장의 우파 3천 명 가운데 대부분이 굶어 죽었다.', en: 'Most of the three thousand rightists at Jiabiangou farm in Gansu starved to death.' }, geo: { kind: 'point', lat: 39.80, lng: 98.00, label: { ko: '자볜거우', en: 'Jiabiangou' } } },
            { date: '1978–1980', title: { ko: '우파 낙인 취소', en: 'The labels reversed' }, body: { ko: '당은 극소수를 제외한 전원의 우파 판정을 「착오」로 취소했으나 운동 자체는 「필요했다」고 유지했다.', en: 'The party cancelled the labels of all but a handful as “mistaken” while maintaining that the campaign itself had been “necessary”.' } },
        ],
        sections: [
            {
                heading: { ko: '1956년의 두 충격', en: 'The two shocks of 1956' },
                paragraphs: [
                    { ko: '1956년 2월 소련 제20차 당대회에서 흐루쇼프가 스탈린을 비판하자 중국 지도부는 두 가지 반응을 보였다. 4월 『인민일보』의 「프롤레타리아 독재의 역사적 경험에 관하여」는 스탈린의 공을 7, 과를 3으로 평가하며 소련의 「전면 부정」에 거리를 두었고, 동시에 제8차 당대회는 집단지도와 개인숭배 반대를 강조하며 마오쩌둥 사상을 당 규약에서 뺐다. 마오는 겉으로 이를 받아들였다.', en: 'When Khrushchev denounced Stalin at the Soviet Twentieth Congress in February 1956 the Chinese leadership reacted in two ways. In April the People’s Daily article “On the Historical Experience of the Dictatorship of the Proletariat” rated Stalin seventy per cent good and thirty per cent bad, distancing itself from Moscow’s “total negation”; at the same time the Eighth Congress stressed collective leadership and opposition to the personality cult and dropped Mao Zedong Thought from the constitution. Mao outwardly accepted this.', sources: [W + 'Sino-Soviet_split', W + 'Hundred_Flowers_Campaign'] },
                    { ko: '10~11월 폴란드의 10월과 헝가리 혁명은 다른 교훈을 주었다. 마오는 헝가리의 봉기가 당이 대중과 괴리되고 관료주의가 쌓인 결과라고 보았고, 중국에서 같은 일을 막으려면 당 밖의 비판을 받아 관료주의를 씻어 내야 한다고 판단했다. 그는 「인민 내부 모순」 개념으로 사회주의 사회에도 모순이 있음을 인정했고, 이는 소련의 「모순 없는 사회」론과 다른 독자적 이론으로 제시되었다.', en: 'The Polish October and the Hungarian revolution of October–November taught a different lesson. Mao read the Hungarian rising as the result of a party cut off from the masses and of accumulated bureaucratism, and judged that to prevent the same in China the party must accept criticism from outside to wash away its bureaucratism. His concept of “contradictions among the people” admitted that socialist society too had contradictions, presented as an original theory against the Soviet doctrine of a “society without contradictions”.', sources: [W + 'Hungarian_Revolution_of_1956', M + 'volume-5/mswv5_58.htm'] },
                ],
            },
            {
                heading: { ko: '「백 가지 꽃이 피게 하라」', en: '“Let a hundred flowers bloom”' },
                paragraphs: [
                    { ko: '구호는 1956년 5월 처음 제기되었으나 지식인은 1955년 후펑 사건 — 문예이론가 후펑과 그 「반혁명 집단」 수천 명의 체포 — 을 기억하며 침묵했다. 1957년 2월 27일 최고국무회의에서 마오는 1,800명의 간부와 지식인 앞에서 「인민 내부 모순의 올바른 처리」를 연설해 비판이 「독초」가 아닌 「향기로운 꽃」이 될 수 있다고 안심시켰다. 연설의 원문은 회람되었으나 6월에야 크게 수정되어 공개되었다.', en: 'The slogan was first raised in May 1956, but intellectuals kept silent, remembering the Hu Feng affair of 1955 — the arrest of the literary theorist Hu Feng and thousands of his “counter-revolutionary clique”. On 27 February 1957 Mao addressed 1,800 cadres and intellectuals at the Supreme State Conference with “On the Correct Handling of Contradictions Among the People”, reassuring them that criticism could be a “fragrant flower” rather than a “poisonous weed”. The speech circulated in its original form but was published, heavily revised, only in June.', sources: [W + 'Hu_Feng', M + 'volume-5/mswv5_58.htm'] },
                    { ko: '당 지도부 다수 — 류사오치·펑전 등 — 는 당 밖의 비판을 받는 정풍에 소극적이었고, 마오는 3~4월 지방을 돌며 간부들을 설득했다. 4월 27일 중앙의 정풍 지시가 내려지자 5월 초부터 통일전선부가 민주당파와 지식인을 초청하는 좌담회를 열었고 신문이 비판을 실었다. 「대명대방(大鳴大放)」이라 불린 이 국면은 약 5주간 계속되었다.', en: 'Most of the leadership — Liu Shaoqi, Peng Zhen and others — were reluctant to open a rectification to outside criticism, and in March and April Mao toured the provinces to persuade the cadres. After the central directive of 27 April, from early May the United Front Department convened forums for the democratic parties and intellectuals and the newspapers printed the criticism. This phase, called the “great blooming and contending”, lasted about five weeks.', sources: [W + 'Hundred_Flowers_Campaign', W + 'Peng_Zhen'] },
                ],
            },
            {
                heading: { ko: '비판은 어디까지 갔는가', en: 'How far the criticism went' },
                paragraphs: [
                    { ko: '비판은 마오가 기대한 「관료주의·종파주의·주관주의」의 범위를 넘었다. 민주동맹의 장보쥔은 정책을 심의할 「정치 설계원」을, 뤄룽지는 반혁명 진압·삼반오반의 억울한 사건을 재심할 위원회를 제안했다. 지식인들은 「당천하(黨天下)」— 당이 모든 것을 독점한다 — 를 비판했고 소련 모방과 「외행이 내행을 지도한다」는 불만을 토로했다. 우한(武漢)·청두 등에서는 노동자 파업과 학생 소요도 있었다.', en: 'The criticism went beyond the “bureaucratism, sectarianism and subjectivism” Mao had expected. Zhang Bojun of the Democratic League proposed a “political design institute” to deliberate on policy; Luo Longji proposed a committee to review unjust cases from the suppression and Three-anti campaigns. Intellectuals attacked the “party’s empire” — the party’s monopoly of everything — and complained of Soviet imitation and of “laymen leading experts”. There were workers’ strikes and student disturbances in Wuhan, Chengdu and elsewhere.', sources: [W + 'Zhang_Bojun', W + 'Hundred_Flowers_Campaign'] },
                    { ko: '베이징대학에서는 5월 19일부터 학생들이 「민주의 벽」에 대자보를 붙였다. 물리학과 학생 탄톈룽 등은 반혁명 진압의 처형 통계 공개, 소련의 헝가리 개입 재평가, 「계급투쟁」 교육의 중단을 요구했고 「백화학사」 같은 자생 조직이 생겼다. 대학의 발언은 뒤에 가장 가혹하게 처벌되었다. 린시링 같은 인민대학 학생은 「진정한 사회주의」를 내걸고 당의 특권을 비판했다.', en: 'At Peking University students began pasting big-character posters on a “democracy wall” from 19 May. The physics student Tan Tianrong and others demanded publication of the execution figures of the suppression campaign, a reassessment of Soviet intervention in Hungary and an end to “class struggle” education, and spontaneous groups such as the Hundred Flowers Society appeared. The universities’ speech was later punished most harshly; Lin Xiling of People’s University attacked party privilege in the name of “genuine socialism”.', sources: [W + 'Hundred_Flowers_Campaign', W + 'Anti-Rightist_Campaign'] },
                ],
            },
            {
                heading: { ko: '6월 8일: 방향 전환', en: '8 June: the reversal' },
                paragraphs: [
                    { ko: '5월 15일 마오는 당 간부에게 「사정이 변하고 있다」는 글을 돌려 우파의 공격이 시작되었으며 당분간 「미쳐 날뛰게」 두라고 지시했다. 6월 8일 『인민일보』 사설 「이것은 무엇 때문인가」와 같은 날의 당내 지시는 「우파의 진공」에 대한 반격을 선언했다. 마오가 2월 연설에서 제시했던 「향기로운 꽃과 독초」를 가르는 여섯 기준은 6월 공개된 수정본에 삽입되어 사후적 근거가 되었다.', en: 'On 15 May Mao circulated to cadres a note, “Things are beginning to change”, saying the rightists’ attack had begun and should be allowed to “run wild” for the moment. On 8 June the People’s Daily editorial “What is this for?” and an internal directive of the same day declared a counter-attack on the “rightists’ offensive”. The six criteria for telling “fragrant flowers” from “poisonous weeds”, absent from the February speech, were inserted into the revised version published in June and served as retroactive justification.', sources: [W + 'Anti-Rightist_Campaign', M + 'volume-5/mswv5_64.htm'] },
                    { ko: '운동은 덩샤오핑이 총서기로 실무를 지휘했다. 표적은 먼저 장보쥔·뤄룽지·추안핑 등 민주당파와 언론계의 유명 인사였고 이어 각 기관·대학·중등학교에서 5% 안팎의 할당을 채우는 방식으로 확대되었다. 1957년 말까지 30만, 최종적으로 공식 집계 55만 2,877명이 우파로 규정되었으며, 실제 수는 이보다 훨씬 많다는 추정이 있다. 작가 딩링·아이칭, 학자 마인추, 젊은 팡리즈가 포함되었다.', en: 'Deng Xiaoping, as general secretary, ran the campaign in practice. The first targets were prominent figures of the democratic parties and the press — Zhang Bojun, Luo Longji, Chu Anping — and it then spread through every institution, university and secondary school, filling quotas of about five per cent. By the end of 1957 300,000 people had been labelled, and the final official count was 552,877, thought to understate the real number considerably. The writers Ding Ling and Ai Qing, the scholar Ma Yinchu and the young Fang Lizhi were among them.', sources: [W + 'Anti-Rightist_Campaign', W + 'Deng_Xiaoping'] },
                ],
            },
            {
                heading: { ko: '처벌: 노동교양과 하방', en: 'Punishment: labour re-education and rural exile' },
                paragraphs: [
                    { ko: '우파는 여섯 등급으로 나뉘어 해고·강등·감봉·「감독 노동」·노동교양 처분을 받았다. 1957년 8월 국무원이 도입한 노동교양은 재판 없이 행정 결정으로 수용하는 제도로, 우파 처리를 위해 급히 마련되었고 2013년까지 존속했다. 간쑤의 자볜거우 농장에는 우파 약 3천 명이 보내졌고 1960년 대기근 속에 대부분이 굶어 죽었다.', en: 'Rightists were sorted into six grades and dismissed, demoted, docked in pay, put under “supervised labour” or sent to re-education through labour. Introduced by the State Council in August 1957, re-education through labour confined people by administrative decision without trial; hastily created to deal with the rightists, it survived until 2013. About three thousand rightists were sent to Jiabiangou farm in Gansu, and most starved to death in the famine of 1960.', sources: [W + 'Re-education_through_labor', W + 'Jiabiangou'] },
                    { ko: '낙인은 본인에 그치지 않았다. 우파의 자녀는 진학과 취업에서 차별받았고 「우파 가족」은 이후 20년의 정치운동에서 거듭 표적이 되었다. 1959년 루산 회의 뒤 「반우경」 운동은 같은 논리를 당 안으로 돌려 간부 수백만 명을 조사했다. 반우파 투쟁이 만든 침묵 속에서 1958년 대약진의 과장 보고와 실패는 아무 견제도 받지 않았다.', en: 'The label did not stop with the individual. Rightists’ children were discriminated against in schooling and employment, and “rightist families” were targets again and again in the political campaigns of the next twenty years. After the Lushan Conference of 1959 the “anti-right-deviation” drive turned the same logic inward on the party, investigating millions of cadres. In the silence the campaign produced, the inflated reports and failures of the Great Leap of 1958 met no check.', sources: [W + 'Anti-Rightist_Campaign', W + 'Lushan_Conference'] },
                ],
            },
            {
                heading: { ko: '「양모」인가 변심인가', en: 'Open plot or change of mind?' },
                paragraphs: [
                    { ko: '마오는 1957년 7월 「뱀을 굴에서 끌어냈다」고 말했고, 공식 역사는 운동이 처음부터 반대자를 드러내는 「양모(陽謀)」였다고 설명한다. 맥파쿼 등 역사가들은 마오가 진심으로 당 관료주의를 견제할 비판을 원했으나 비판이 당의 지도 원칙에 이르자 놀라 방향을 바꿨으며, 「양모」는 사후에 만든 설명이라고 본다. 어느 쪽이든 결과는 같았다.', en: 'In July 1957 Mao said he had “lured the snakes out of their holes”, and official history explains the campaign as an “open plot” from the start to expose opponents. Historians such as MacFarquhar hold that Mao genuinely wanted criticism to check party bureaucratism, took fright when it reached the party’s leading role, and reversed course — the “open plot” being an explanation constructed afterwards. Either way the outcome was the same.', sources: [W + 'Roderick_MacFarquhar', W + 'Hundred_Flowers_Campaign'] },
                    { ko: '1978년 이후 당은 반우파 투쟁이 「필요했으나 심각하게 확대되었다」고 규정하며 55만 명 가운데 96명을 제외한 전원의 낙인을 취소했다. 운동 자체의 정당성은 유지되었고, 장보쥔 등 「대우파」의 복권은 지금도 이루어지지 않았다. 지식인이 당과 맺은 관계 — 초대와 배신, 침묵과 순응 — 는 이 사건에서 하나의 원형을 얻었고, 1989년의 학생들에게도 기억되었다.', en: 'After 1978 the party ruled that the campaign had been “necessary but seriously enlarged” and cancelled the labels of all but ninety-six of the 550,000. The legitimacy of the campaign itself was maintained, and the “great rightists” such as Zhang Bojun have never been rehabilitated. The relationship between intellectuals and the party — invitation and betrayal, silence and conformity — found one of its archetypes in this episode, remembered by the students of 1989 as well.', sources: [W + 'Anti-Rightist_Campaign', K + '%EB%B0%98%EC%9A%B0%ED%8C%8C_%EC%9A%B4%EB%8F%99'] },
                ],
            },
        ],
        people: [
            { id: 'mao-zedong', kind: 'leader', relation: { ko: '비판을 초대하고 반우파 투쟁으로 돌아선 당 주석', en: 'Party chairman who invited criticism and reversed it' }, note: { ko: '「인민 내부 모순」 연설로 백화제방을 열었고 6월 8일 반격을 지시했다.', en: 'Opened the Hundred Flowers with the “contradictions” speech and ordered the counter-attack of 8 June.' } },
            { id: 'deng-xiaoping', kind: 'executor', relation: { ko: '반우파 투쟁의 실무 총책', en: 'Ran the Anti-Rightist Campaign' }, note: { ko: '총서기로 운동을 지휘했고 1980년 「확대는 잘못이었으나 운동은 필요했다」고 평가했다.', en: 'Directed the campaign as general secretary; in 1980 judged the enlargement wrong but the campaign necessary.' } },
            { id: 'liu-shaoqi', kind: 'participant', relation: { ko: '당 밖의 비판에 소극적이었던 지도부', en: 'Part of the leadership reluctant to open the party to criticism' }, note: { ko: '정풍 개방에 신중했으나 반우파 투쟁을 지지했다.', en: 'Cautious about open rectification, supported the anti-rightist turn.' } },
            { id: 'peng-zhen', kind: 'participant', relation: { ko: '베이징의 당 지도자, 대학 우파 처벌', en: 'Beijing party leader in the university purge' }, note: { ko: '베이징 시위 서기로 대학의 우파 처리를 관장했다.', en: 'As Beijing party secretary oversaw the treatment of rightists in the universities.' } },
            { id: 'zhou-enlai', kind: 'participant', relation: { ko: '지식인 정책의 온건파', en: 'Moderate on intellectual policy' }, note: { ko: '1956년 「지식인 문제」 보고로 지식인 우대를 주장했다.', en: 'His 1956 report on intellectuals argued for better treatment of them.' } },
            { id: 'ding-ling', kind: 'target', relation: { ko: '우파로 몰린 작가', en: 'Writer labelled a rightist' }, note: { ko: '1957년 우파로 규정되어 북대황 농장에서 20년 넘게 노동했다.', en: 'Labelled in 1957 and spent more than twenty years labouring in the Great Northern Wilderness.' } },
            { id: 'fang-lizhi', kind: 'target', relation: { ko: '우파로 몰린 젊은 물리학자', en: 'Young physicist labelled a rightist' }, note: { ko: '1957년 우파로 당적을 잃었다가 복권되었다.', en: 'Lost his party membership as a rightist in 1957 and was later rehabilitated.' } },
            { id: 'kang-sheng', kind: 'executor', relation: { ko: '이론·선전 부문의 강경파', en: 'Hardliner in theory and propaganda' }, note: { ko: '반우파 투쟁 뒤 이론·문화 부문에서 영향력을 되찾았다.', en: 'Regained influence in theory and culture after the anti-rightist turn.' } },
            { id: 'roderick-macfarquhar', kind: 'witness', relation: { ko: '『문화대혁명의 기원』 제1권의 저자', en: 'Author of The Origins of the Cultural Revolution, vol. 1' }, note: { ko: '1956~1957년 지도부 내부의 대립을 문화대혁명의 출발점으로 분석했다.', en: 'Analysed the leadership conflicts of 1956–1957 as the starting point of the Cultural Revolution.' } },
            { id: 'khrushchev', kind: 'participant', relation: { ko: '비밀연설로 논쟁을 촉발', en: 'Whose secret speech set off the debate' }, note: { ko: '스탈린 비판이 중국의 개인숭배·소련 모델 논의를 열었다.', en: 'His denunciation of Stalin opened the Chinese discussion of the cult and the Soviet model.' } },
        ],
        related: ['prc-consolidation-1949-1956', 'twentieth-party-congress', 'hungarian-revolution', 'great-leap-forward'],
    },
];
