exec(open('/tmp/prepare-french-first.py').read().split("t=fetched('august')")[0])
t=(B/'sources/saintjust8.pages.txt').read_text();t=t[t.index('SAINT-JUST, au nom'):];t=re.sub(r'^\(\d\).*$', '',t,flags=re.M);t=re.sub(r'^(?:SÉANCE DU|ARCHIVES PARLEMENTAIRES).*$', '',t,flags=re.M);t=re.sub(r'^\d{3}$','',t,flags=re.M);t=re.sub(r'¬\s*','',t);t=re.sub(r'\(\d\)\s*\.?','',t)
d=(B/'sources/saintjust8-decree.pages.txt').read_text();d=d[d.index('La Convention nationale'):];a=d.index('(1) Broch.');z=d.index('profit de la République.',a);d=d[:a]+d[z:];d=re.sub(r'¬\s*','',d);d=re.sub(r'\(\d\)\s*\.?','',d).replace('ensuite i perpétuité. a','ensuite à perpétuité.').replace('cour-riers','courriers')
prefix='''Citoyens, je vous présente, au nom du comité de salut public, le mode d’exécution du décret rendu le 8 de ce mois contre les ennemis de la révolution.
C’est une idée très généralement sentie que toute la sagesse du gouvernement consiste à réduire le parti opposé à la Révolution et à rendre le peuple heureux aux dépens de tous les vices et de tous les ennemis de la liberté.
C’est le moyen d’affermir la Révolution que de la faire tourner au profit de ceux qui la soutiennent et à la ruine de ceux qui la combattent.
Identifiez-vous par la pensée aux mouvements secrets de tous les cœurs ; franchissez les idées intermédiaires qui vous séparent du but où vous tendez. Il vaut mieux hâter la marche de la révolution que de la suivre au gré de tous les complots qui l’embarrassent, qui l’entravent. C’est à vous d’en déterminer le plan et d’en précipiter les résultats, pour l’avantage de l’humanité.
Que le cours rapide de votre politique entraîne toutes les intrigues de l’étranger ; un grand coup que vous frappez retentit sur le trône et sur le cœur de tous les rois. Les lois et les mesures de détail sont des piqûres que l’aveuglement endurci ne sent pas.'''
v=(B/'sources/saintjust13-page23.txt').read_text();v=v[v.index('Faites-vous respecter'):v.index('(Ce discours')];v=re.sub(r'\(\d\)\s*\.?','',v)
w=(B/'sources/saintjust13-page23.txt').read_text();w=w[w.index('La Convention nationale, sur le rapport'):w.index('La Convention adopte ce décret')];a=w.index('(1) Broch.');z=w.index('nir, dans le plus bref délai',a);w=w[:a].rstrip().removesuffix('parve-')+'parvenir, dans le plus bref délai'+w[z+len('nir, dans le plus bref délai'):];w=re.sub(r'\(\d\)\s*\.?','',w).replace('en-fans','enfans').replace("jo'n-dra",'joindra')
save('saint-just-ventose-reports-decrees-1794',['Rapport du 8 ventôse an II (26 février 1794)']+t.splitlines()+['Décret du 8 ventôse']+d.splitlines()+['Rapport du 13 ventôse an II (3 mars 1794)']+prefix.splitlines()+v.splitlines()+['Décret du 13 ventôse']+w.splitlines(),'https://www.persee.fr/doc/arcpa_0000-0000_1964_num_85_1_32659_t1_0516_0000_3','방토즈 8일·13일 보고 두 편과 각각의 최종 채택 법령 전문. Archives parlementaires, t. LXXXV, 516–520쪽; t. LXXXVI, 22–23쪽. 13일은 1794년 3월 3일이다. 22쪽 OCR 누락은 이미지 직접 전사. 현대 교감 주석·별개 초안은 제외. 13일 원판: https://archives-parlementaires.persee.fr/prt/7ec3b7fe-44bd-41d8-9ffa-f79a9b83fbba')
t=(B/'sources/jabarti-jumada.txt').read_text();t=t[t.index('واستهل شهر جمادى الأولى'):t.index('واستهل شهر جمادى ثانية')];t=re.sub(r'^(?:ذكر دخول الفرنساوية|عجايب الآثار).*$', '',t,flags=re.M);t=re.sub(r'^\d{1,3}$','',t,flags=re.M)
# Keep page-spanning sentences together; split at paragraph/date starts.
lines=[]
for l in t.splitlines():
 if not l.strip():continue
 if l.startswith(('وفي ','وأما ','واستهل ','وفيه ','ولما ','وذلك ','فكان ','هذا ','وصورتها:')) or not lines:lines.append(l)
 else:lines[-1]+=' '+l
save('al-jabarti-french-occupation-1798',lines,'https://downloads.hindawi.org/books/53519152.pdf','عبد الرحمن الجبرتي, عجائب الآثار في التراجم والأخبار, 제4권, Hindawi 디지털 원문, 인쇄면 37–45쪽 중 히즈라력 1213년 주마다 알아우왈월 기록 전체. 1798년 카이로 봉기를 포함하는 날짜 경계가 있는 발췌다. 다음 주마다 앗사니월 직전까지; 책 전체 번역이 아니다. 아랍어 PDF의 우좌 순서와 Unicode 합자를 정규화했으며 현대 영어 번역을 거치지 않는다.')
p=B/'specs/al-jabarti-french-occupation-1798.json';s=json.loads(p.read_text());s['sourceLang']='ar';s['glossary']={'extra':{'الفرنسيس':'프랑스인','الأزهر':'알아즈하르','بونابرت':'보나파르트','الديوان':'디완','المماليك':'맘루크'}};s['documents'][0]['register']+=' 히즈라력 날짜를 임의로 양력으로 바꾸지 않는다. PDF 문자 추출의 명백한 합자 순서 오류(امل→الم, بني→بين 등)는 문맥에 따라 판독하되 확정 불가능한 부분은 [원문 판독 불명]으로 명시한다.';p.write_text(json.dumps(s,ensure_ascii=False,indent=2)+'\n')
