// 탐보프 반란과 농민 봉기 (1918–1922, 중심 1920.08–1922)
const E = t => 'https://en.wikipedia.org/wiki/' + encodeURI(t);
const RU = t => 'https://ru.wikipedia.org/wiki/' + encodeURI(t);
const P = (lat, lng, ko, en) => ({ kind: 'point', lat, lng, label: { ko, en } });
const S = {
  tamb: E('Tambov_Rebellion'),
  tambru: RU('Тамбовское_восстание'),
  antonov: E('Alexander_Antonov_(politician)'),
  tokm: RU('Токмаков,_Пётр_Михайлович'),
  wsib: E('West_Siberian_rebellion'),
  wsibru: RU('Западно-Сибирское_восстание_(1921—1922)'),
  green: E('Green_armies'),
  prodr: E('Prodrazverstka'),
  kombed: E('Committees_of_Poor_Peasants'),
  tsiur: E('Alexander_Tsiurupa'),
  chapan: E('Chapan_rebellion'),
  pitch: E('Pitchfork_uprising'),
  pitchru: RU('Вилочное_восстание'),
  sorokino: E('Peasant_rebellion_of_Sorokino'),
  sapru: RU('Восстание_Сапожкова'),
  sapp: RU('Сапожков,_Александр_Васильевич'),
  nep: E('New_Economic_Policy'),
  cong10: E('10th_Congress_of_the_Russian_Communist_Party_(Bolsheviks)'),
  prodnalog: RU('Продналог'),
  rcw: E('Russian_Civil_War'),
};

module.exports = {
  sections: [
    {
      heading: { ko: '징발과 마을: 1918~1919년의 농민 봉기와 녹색군 {russia}', en: 'Requisitions and the village: peasant revolts and the Greens, 1918–1919 {russia}' },
      paragraphs: [
        {
          ko: '1918년 5월 9일 레닌의 법령이 「식량 독재」를 선포한 뒤, 소브나르콤은 1919년 1월 11일 식량 할당 징발, 곧 프로드라즈뵤르스트카를 소비에트 러시아 전역에 도입했다. 이 제도는 1916년 11월 제정 러시아 농업부가 전쟁 수행을 위해 처음 도입한 곡물 할당에서 이름과 방식을 빌린 것이었다. 식량인민위원부는 각 주의 파종 면적과 수확 예상량, 이전 해의 비축량을 근거로 할당량을 정했고, 이 계획은 주에서 군, 향, 마을을 거쳐 개별 농가까지 쪼개져 내려갔다. 처음에는 곡물과 사료만 대상이었지만 1919~1920년 조달 기간에는 감자와 고기가, 1920년 말에는 사실상 모든 농산물이 할당에 들어갔다. 소련 통계로 거둔 곡물·사료는 1918~1919년 1억 790만 푸드, 1919~1920년 2억 1,250만 푸드, 1920~1921년 3억 6,700만 푸드로 해마다 늘었다. 징발은 붉은 군대와 도시를 먹였지만 곡물 판매가 금지된 상태에서 농민에게 남는 것은 거의 없었고, 내전이 끝나 갈수록 농촌의 불만은 커졌다.',
          en: 'After Lenin\'s decree of 9 May 1918 proclaimed a "food dictatorship", the Sovnarkom introduced compulsory food apportionment, the prodrazverstka, across Soviet Russia on 11 January 1919. Both the name and the method came from the grain apportionment the tsarist Ministry of Agriculture had introduced in November 1916 for the war effort. The Food Commissariat set quotas from each province\'s sown area, expected yield and previous reserves, and the plan was broken down from province to district, township and village and finally to individual households. At first it covered grain and fodder; in the 1919–20 campaign potatoes and meat were added, and by the end of 1920 almost every farm product was subject to it. By Soviet figures, grain and fodder collected rose from 107.9 million poods in 1918–19 to 212.5 million in 1919–20 and 367 million in 1920–21. Requisitioning fed the Red Army and the towns, but with grain sales banned it left peasants with little, and rural discontent grew as the civil war drew to a close.',
          sources: [S.prodr],
        },
        {
          ko: '징발을 실제로 수행한 것은 식량 부대(프로도트랴드)와 빈농위원회(콤베드)였다. 식량인민위원 알렉산드르 추루파는 1918년부터 도시에서 무장 부대 수십 개를 조직해 농촌으로 보냈다. 그는 부대가 다른 방법이 모두 실패한 뒤에만 파견되며 마을에 정치의식을 전하는 선전원이기도 하다고 주장했지만, 때로 제정 시대 경찰의 행태를 흉내 냈다는 점은 인정했다. 1918년 6월 11일 전러시아중앙집행위원회는 마을 안에서 남는 곡물을 찾아내 몰수하도록 빈농위원회를 세우게 했다. 부농과 고용주는 가입할 수 없었다. 역사가 올랜도 파이지스에 따르면 대부분의 마을은 스스로를 친족으로 이어진 평등한 공동체로 여겨 빈농만의 기구를 거부하거나 주민 전원이 가입하는 위원회를 만들었고, 실제 위원회는 마을 밖에서 온 도시민·병사·토지 없는 장인이 채우는 경우가 많아 「지방 마피아」처럼 굴었다. 1918년 12월 2일 빈농위원회는 마을 소비에트에 통합되어 이듬해 봄까지 러시아에서 사라졌지만, 소련 역사가 가라시뮥의 집계로 그때까지 13만 1,637개가 세워졌다.',
          en: 'The requisitions were carried out by food detachments (prodotryady) and Committees of Poor Peasants (kombedy). From 1918 Food Commissar Alexander Tsyurupa organised dozens of armed detachments in the towns and sent them into the countryside. He claimed they were sent only when every other method had failed and that they also carried political awareness into the villages, but conceded that they sometimes copied the behaviour of the tsarist police. On 11 June 1918 the All-Russian Central Executive Committee ordered the creation of kombedy to locate and seize surplus grain inside each village; wealthy peasants and employers of labour were barred. According to the historian Orlando Figes, most villages thought of themselves as communities of equals bound by kinship and either refused to form a separate body for the poor or set up one that everyone joined; actual committees were often staffed by outsiders such as townsmen, soldiers and landless craftsmen and behaved "more like a local mafia". On 2 December 1918 the kombedy were merged into the village soviets and had disappeared in Russia by the following spring, but by the Soviet historian Garasimiuk\'s count 131,637 had been set up.',
          sources: [S.tsiur, S.kombed],
        },
        {
          ko: '징발은 처음부터 저항에 부딪혔다. 1918년 5월의 식량 독재 이후 보로네시·탐보프·펜자·사라토프주와 코스트로마·모스크바·노브고로드·페트로그라드·프스코프·스몰렌스크 일대에서 농민과 붉은 군대의 충돌이 잇따랐고, 볼셰비키는 이를 유혈로 진압했다. 가장 큰 초기 봉기는 1919년 3월 볼가 강 중류에서 일어난 「차파니 전쟁」이었다. 3월 3일 사마라주 센길레이군 노보데비치예 마을 주민들이 수확물을 징발하던 부대를 무장 해제했고, 진압하러 온 첫 부대는 오히려 봉기 편에 서서 자기 장교들을 쏘았다. 3월 7일 봉기군은 거의 싸우지 않고 볼가 강변의 스타브로폴을 점령해 제1차 세계대전 참전 장교 알렉세이 돌리닌을 지도자로 세웠고, 징발 폐지와 소비에트 자유선거, 「볼셰비키 코미사르 지배」의 종식을 요구했다. 봉기 이름은 이 지역 농민이 겨울에 입던 양가죽 외투 「차판」에서 왔다. 미하일 프룬제가 이끄는 약 1만 3천 명이 투입되어 3월 14일 스타브로폴을, 15일 노보데비치예를 되찾았고 4월 중순 싸움이 끝났다. 봉기군 규모는 최소 3만 명에서 10만~15만 명까지 추정이 엇갈리고, 농민 약 1만 명이 목숨을 잃은 것으로 추산된다.',
          en: 'Requisitioning met resistance from the start. After the food dictatorship of May 1918, clashes between peasants and the Red Army were reported in Voronezh, Tambov, Penza and Saratov provinces and around Kostroma, Moscow, Novgorod, Petrograd, Pskov and Smolensk, and the Bolsheviks crushed them bloodily. The largest early revolt was the "Chapan War" on the middle Volga in March 1919. On 3 March the villagers of Novodevichye in Sengilei district, Samara province, disarmed a detachment requisitioning their harvest, and the first troops sent against them went over to the rebels and shot their own officers. On 7 March the rebels took Stavropol on the Volga almost without a fight, made the First World War officer Aleksey Dolinin their leader, and demanded an end to requisitions, free elections to the soviets and the end of "Bolshevik commissarocracy". The revolt was named after the chapan, the sheepskin coat local peasants wore in winter. Some 13,000 troops under Mikhail Frunze retook Stavropol on 14 March and Novodevichye on the 15th, and fighting ended by mid-April. Estimates of the rebel force range from at least 30,000 to 100,000–150,000, and about 10,000 peasants are estimated to have died.',
          sources: [S.rcw, S.chapan],
        },
        {
          ko: '이런 농민 무장 집단을 통틀어 「녹색군」이라 불렀다. 녹색군은 볼셰비키뿐 아니라 백군과 외국 간섭군에도 맞서 자기 마을을 징발과 보복에서 지키려 한 반쯤 조직된 지역 민병이었다. 이념적으로 중립이었지만 때로 사회혁명당과 연결되었다. 이름은 숲으로 숨어든 탈영병 무리에서 나왔다. 백군이 패배하면서 같은 계급을 계속 억압하라는 명령에 반발한 붉은 군대 농민 병사들이 무기를 들고 숲에 모였고, 1919~1921년 녹색군 대원과 지휘관 상당수가 이런 탈영병이었다. 소비에트 당국은 농민 소요를 짧고 소규모인 「분트」와, 수천 명이 도시를 점령하고 일관된 정치 강령을 내세우는 「봉기(보스스타니예)」로 나누었는데, 차파니 전쟁이 첫 번째 「봉기」로 꼽힌다. 1920년 백군이 사실상 패하자 징발의 명분은 더 약해졌다. 1921년 공식적으로 약 250만 명의 병사가 동원 해제되었고, 고향에 돌아간 이들 가운데 상당수가 녹색군에 합류했다. 녹색군은 탈영병이 들고 온 무기와 붉은 군대 창고·수비대에서 빼앗은 무기 말고는 몽둥이와 쇠스랑, 도끼, 사냥총으로 싸웠다.',
          en: 'Such armed peasant groups were collectively called the "Greens". They were semi-organised local militias that fought not only the Bolsheviks but also the Whites and the foreign interventionists to protect their communities from requisitions and reprisals. They were ideologically neutral but at times associated with the Socialist Revolutionaries. The name came from bands of deserters hiding in the forests: as the Whites were beaten, Red Army peasant soldiers who resented being ordered to keep repressing their own class took their weapons into the woods, and in 1919–21 many Green fighters and leaders were such deserters. Soviet authorities divided peasant unrest into the bunt, a brief revolt with few participants, and the vosstaniye, an insurrection of thousands able to take towns and put forward a coherent programme; the Chapan War is counted as the first true vosstaniye. Once the Whites were effectively defeated in 1920, the justification for requisitioning weakened further. Officially some 2.5 million soldiers were demobilised in 1921, and many of those who went home joined the Greens. Apart from the weapons deserters brought with them and arms seized from Red Army depots and garrisons, the Greens fought with clubs, pitchforks, axes and hunting guns.',
          sources: [S.green],
        },
      ],
    },
    {
      heading: { ko: '탐보프주의 1920년 8월과 알렉산드르 안토노프 {russia}', en: 'Tambov province in August 1920 and Alexander Antonov {russia}' },
      paragraphs: [
        {
          ko: '모스크바에서 남동쪽으로 500킬로미터가 채 안 되는 탐보프주는 혁명 전 인구 약 400만 명 가운데 도시 주민이 26만 8천 명에 불과한 농업 지대였다. 깊은 흑토 위에 자리 잡아 제국에서 가장 부유한 주 가운데 하나로 꼽혔고, 혁명 전 이곳 농민은 곡물 약 100만 톤을 생산해 그 3분의 1을 주 밖으로 내보냈다. 1917년 선거에서 농촌은 압도적으로 사회혁명당을 지지했고, 1918년 3월 브레스트 강화가 비준된 뒤에는 볼셰비키 대의원들이 지방 소비에트에서 쫓겨나기까지 했다. 1920년 8월 주 전체 365만 명 가운데 공산당원과 후보당원은 1만 3,490명이었고 농촌에는 4,492명뿐이었다. 모스크바에 가깝고 전선에서 멀다는 위치 때문에 식량 부대의 활동이 특히 활발했으며, 러시아어 출처에 따르면 1917~1919년 이 주에서만 최대 4만 명이 볼셰비키와 식량 부대, 빈농위원회에 맞선 국지 봉기와 유격 활동에 참여했다. 1919년 여름 백군 마몬토프 장군의 기병 습격은 이 지역 유격대에 많은 무기를 남겼다.',
          en: 'Tambov province, less than 500 km southeast of Moscow, was farming country: of its roughly 4 million people before the revolution only 268,000 lived in towns. Lying on deep black earth, it counted among the richest provinces of the empire, and before 1917 its peasants produced about a million tonnes of grain, a third of which left the province. In the 1917 elections the countryside voted overwhelmingly for the Socialist Revolutionaries, and in March 1918, after the Treaty of Brest-Litovsk was ratified, Bolshevik delegates were even thrown out of local soviets. In August 1920 the province\'s 3.65 million people included 13,490 Communists and candidate members, only 4,492 of them in the countryside. Close to Moscow and far from the fronts, it saw especially intensive food-detachment activity, and according to Russian-language sources up to 40,000 people in the province took part in local revolts and partisan actions against the Bolsheviks, food detachments and kombedy in 1917–19. General Mamontov\'s White cavalry raid in summer 1919 left large stocks of weapons in partisan hands.',
          sources: [S.tamb, S.tambru],
        },
        {
          ko: '봉기의 이름이 된 알렉산드르 안토노프는 1889년 모스크바에서 태어나 아버지의 고향인 탐보프주 키르사노프에서 자랐다. 사회혁명당에 들어가 혁명 자금을 위한 「징수(엑스프로프리아치야)」, 곧 역과 은행 강도에 가담했고, 1909년 사라토프에서 체포되어 20년 강제노동형을 받고 실리셀부르크 요새와 블라디미르 중앙감옥에서 복역했다. 1917년 2월 혁명 뒤 정치범 사면으로 풀려나 민경대에서 일했고, 그해 10월 키르사노프군 민경대장이 되었다. 볼셰비키 권력이 농촌에 뻗치자 그는 직위를 지키려 좌파 사회혁명당에 이름을 올렸지만 활동은 거의 하지 않았다. 러시아어 출처에 따르면 1918년 12월~1919년 1월 그는 10~15명의 「전투대」를 꾸려 소비에트 기관을 습격하고 지방 볼셰비키를 암살하기 시작했고, 1919년 여름에는 주로 탈영병으로 이루어진 150명 규모로 커졌다. 영어 출처는 이 무리가 200명이 넘는 곡물 징수원을 죽였고 1920년 초여름 6천 명까지 늘었다고 쓴다. 그가 다니는 지역에는 식량 부대가 나타나기를 꺼렸고, 농민들은 그를 자기들의 보호자로 여겼다.',
          en: 'Alexander Antonov, whose name the rising came to bear, was born in Moscow in 1889 and grew up in Kirsanov in Tambov province, his father\'s home town. He joined the Socialist Revolutionaries and took part in "expropriations", robberies of stations and banks for the revolutionary cause; arrested in Saratov in 1909, he was sentenced to twenty years of katorga, served in the Schlüsselburg fortress and the Vladimir Central prison. Freed by the political amnesty after the February Revolution of 1917, he worked in the new militia and in October became head of the Kirsanov district militia. As Bolshevik power reached into the countryside he registered with the Left SRs to keep his post, but took little part in their work. According to Russian-language sources, in December 1918–January 1919 he formed a "combat squad" of 10–15 men that raided Soviet offices and assassinated local Bolsheviks; by summer 1919 it had grown to 150, mostly deserters. English-language sources say his bands killed more than 200 grain collectors and grew to 6,000 by early summer 1920. Food detachments avoided the areas where he operated, and peasants saw him as their protector.',
          sources: [S.antonov, S.tambru, S.tamb],
        },
        {
          ko: '1920년 탐보프에는 가뭄이 들어 수확한 곡물이 1,200만 푸드에 그쳤지만, 할당 징발량은 줄지 않은 1,150만 푸드였다. 러시아어 출처에 따르면 봉기는 8월 15일 탐보프군 히트로보 마을에서 식량 부대를 무장 해제하면서 시작되었다. 영어 출처는 히트로보 봉기를 8월 19일로 적고, 징발 부대가 손에 닿는 것을 모두 가져가며 「일흔 살 노인들을 사람들 앞에서 때렸다」고 전한다. 소총이 모자라 쇠스랑과 몽둥이로 무장한 농민들은 진압하러 온 부대를 물리쳤다. 8월 19일에는 탐보프군 카멘카, 보리소글렙스크군 투골루코보 등 여러 마을에서 농민이 곡물 납부를 거부하고 유격대와 함께 식량 부대와 지방 공산당원, 체카 요원을 죽였으며, 같은 날 아파나시옙카 마을에서 작은 무리들이 하나의 유격군으로 합쳤다. 봉기군은 주도 탐보프를 노렸으나 10킬로미터 앞에서 기관총에 흩어졌다. 그 뒤 봉기는 탐보프·키르사노프·보리소글렙스크·모르샨스크·코즐로프군과 이웃한 사라토프주·보로네시주의 군으로 번져, 300만 명이 넘는 주민이 사는 지역을 휩쓸었다.',
          en: 'In 1920 drought hit Tambov and the harvest came to only 12 million poods of grain, yet the requisition quota stayed at 11.5 million. According to Russian-language sources the rising began on 15 August in the village of Khitrovo in Tambov district when a food detachment was disarmed. English-language sources date the Khitrovo revolt to 19 August and say the requisition squad had taken everything it could and "beat up elderly men of seventy in full view of the public". With few rifles, the villagers armed themselves with pitchforks and clubs and drove off the troops sent against them. On 19 August peasants in several villages, among them Kamenka in Tambov district and Tugolukovo in Borisoglebsk district, refused to hand over grain and, with partisan help, killed food-detachment men, local Communists and Chekists; the same day several small groups merged into one partisan army at Afanasyevka. The rebels tried to take the provincial capital Tambov but were scattered by machine guns ten kilometres short of it. The rising then spread through the Tambov, Kirsanov, Borisoglebsk, Morshansk and Kozlov districts and neighbouring districts of Saratov and Voronezh provinces, an area with more than three million inhabitants.',
          sources: [S.tambru, S.tamb],
        },
        {
          ko: '8월 21일 탐보프 주당위원회는 비상 작전본부를 세우고 계엄을 선포했지만 사태는 이미 손을 떠나 있었다. 8월 31일 탐보프주 집행위원회 의장 알렉산드르 슐리흐테르가 직접 토벌대를 이끌고 나섰다가 패해 해임되었다. 붉은 군대 주력은 폴란드-소비에트 전쟁과 북타브리아의 브랑겔 공세에 묶여 있었고, 영어 출처에 따르면 탐보프주에 남은 병력은 마을에서 징집되어 같은 계급과 싸울 의욕이 없는 3천 명 남짓이었다. 10월 레닌은 펠릭스 제르진스키와 에프라임 스클란스키, 바실리 코르네프에게 「안토놉시나의 격파를 서두르라」고 지시했다. 10월 15일까지 지방 예비병과 국내경비대(VOKhR)·특수임무부대(ChON)를 모아 4,447명, 기관총 22정, 대포 5문을 갖추었지만, 안토노프 쪽은 이미 최대 2만 명에 맥심 기관총 44정, 3인치 포 5문을 보유하고 있었다. 10월까지 볼셰비키는 주의 농촌을 완전히 잃고 탐보프시와 몇몇 소도시만 지켰으며, 봉기군 지역에서는 소비에트 기관이 모두 폐지되고 공산당원 약 1천 명이 살해되었다.',
          en: 'On 21 August the Tambov provincial party committee set up an emergency operational staff and declared a state of siege, but events were already out of control. On 31 August Alexander Shlikhter, chairman of the provincial executive committee, led a punitive detachment against the rebels himself, was defeated and was removed from his post. The Red Army\'s main forces were tied down in the Polish–Soviet War and by Wrangel\'s offensive in northern Tavria, and according to English-language sources only about 3,000 unreliable troops, drafted from local villages and unwilling to fight their own class, remained in the province. In October Lenin instructed Felix Dzerzhinsky, Efraim Sklyansky and Vasily Kornev to "speed up the destruction of the Antonovshchina". By 15 October local reserves and units of the Internal Guard (VOKhR) and Special Purpose Units (ChON) had raised Soviet strength to 4,447 men with 22 machine guns and five guns, while Antonov already had up to 20,000 men, 44 Maxim guns and five three-inch guns. By October the Bolsheviks had lost the province\'s countryside entirely, holding only the city of Tambov and a few small towns; in rebel areas all Soviet institutions were abolished and about 1,000 Communists were killed.',
          sources: [S.tambru, S.tamb],
        },
      ],
    },
    {
      heading: { ko: '근로농민동맹과 파르티잔 군 {russia}', en: 'The Union of Working Peasants and the partisan armies {russia}' },
      paragraphs: [
        {
          ko: '1920년 11월 14일 봉기군은 모든 병력을 하나의 지휘 아래 모아 탐보프 지방 연합 파르티잔 군을 만들었다. 러시아어 출처에 따르면 그 사령관은 키르사노프군 이노콥카 마을 농민 출신의 표트르 토크마코프였다. 그는 러일전쟁 때 징집되어 제1차 세계대전 갈리치아 전선에서 성 게오르기 십자훈장과 메달을 네 등급 모두 받았고 중위까지 올랐으며, 브레스트 강화 뒤 고향에 돌아와 민경대원으로 일하다 1918년 유격대를 만들었다. 1920년 6월 제2봉기군 사령관이 되었다가 11월 연합군 전체를 맡았고, 정치 조직인 근로농민동맹의 의장도 겸해 군사와 정치 양쪽의 수장이었다. 연합군은 카멘카에 본부를 둔 제1봉기군(사령관 알렉산드르 보구슬랍스키 대령), 키르사노프군 코뱌키에 본부를 둔 제2봉기군, 이반 콜레스니코프가 이끈 기병 위주의 제3군으로 이루어졌다. 이 출처는 안토노프를 제2봉기군 참모장으로 적는다. 반면 영어 출처와 소련 시대의 이름 「안토놉시나」는 안토노프를 봉기 전체의 지도자로 내세우며, 어느 쪽이 실제 지휘의 중심이었는지는 출처마다 무게가 다르다.',
          en: 'On 14 November 1920 the rebels put all their forces under one command, forming the United Partisan Army of the Tambov Region. According to Russian-language sources its commander was Pyotr Tokmakov, a peasant from Inokovka in Kirsanov district. Called up during the Russo-Japanese War, he won all four classes of the St George Cross and medal on the Galician front in the First World War and rose to lieutenant; after Brest-Litovsk he went home, worked in the militia and in 1918 formed a partisan band. In June 1920 he took command of the 2nd Insurgent Army and in November of the whole united army, and as chairman of the Union of Working Peasants he headed the movement both militarily and politically. The united army comprised the 1st Insurgent Army headquartered at Kamenka under Colonel Aleksandr Boguslavsky, the 2nd headquartered at Kobyaki in Kirsanov district, and a mainly mounted 3rd army under Ivan Kolesnikov. These sources list Antonov as chief of staff of the 2nd Army. English-language sources and the Soviet-era name "Antonovshchina", by contrast, present Antonov as leader of the whole rising, and the sources weigh differently who was the real centre of command.',
          sources: [S.tambru, S.tokm, S.tamb],
        },
        {
          ko: '근로농민동맹은 살아남은 사회혁명당 조직들을 바탕으로 만들어졌고, 볼셰비키 독재 타도와 제헌의회 소집, 정치적·경제적 자유 회복이라는 사회혁명당에 가까운 구호를 내걸었다. 1920년 12월 동맹이 낸 선언은 계급 구분 없는 모든 시민의 정치적 평등, 내전 종식과 외국과의 항구적 평화, 평등·보통·직접·비밀 선거에 의한 제헌의회 소집과 소환권, 그때까지 공산주의자와 싸운 단체와 정당이 선출로 세우는 과도 기관, 언론·출판·양심·결사·집회의 자유를 요구했다. 경제 강령으로는 옛 제헌의회가 채택한 토지 사회화 법의 완전한 시행, 협동조합을 통한 생필품 공급, 공장의 부분적 탈국유화와 함께 중공업·탄광·야금은 국가 소유로 남길 것, 노동자 통제와 국가의 생산 감독, 러시아와 외국 자본의 경제 재건 참여를 내세웠다. 옛 제국 안 여러 민족의 자결과 소농 경영을 위한 국가 신용, 수공업의 자유, 보편적 의무 문맹 퇴치도 들어 있었다. 안토노프 자신은 자유 거래와 물자 이동의 허용, 징발 중단, 소비에트 행정기관과 체카의 해산을 요구했다.',
          en: 'The Union of Working Peasants was built on the surviving Socialist Revolutionary organisations and adopted slogans close to the SRs\': the overthrow of the Bolshevik dictatorship, the convocation of a Constituent Assembly and the restoration of political and economic freedoms. Its manifesto of December 1920 demanded political equality for all citizens without division into classes; an end to the civil war and lasting peace with foreign states; a Constituent Assembly elected by equal, universal, direct and secret suffrage with the right to recall deputies; until then, provisional authorities elected by the unions and parties that had fought the Communists; and freedom of speech, the press, conscience, association and assembly. Its economic programme called for full implementation of the land-socialisation law adopted by the former Constituent Assembly, supply of necessities through cooperatives, partial denationalisation of factories while heavy industry, coal mining and metallurgy stayed in state hands, workers\' control and state supervision of production, and Russian and foreign capital in economic reconstruction. It also called for self-determination for the nationalities of the former empire, state credit for small farms, freedom for handicrafts and compulsory universal literacy. Antonov himself demanded free trade and movement of goods, an end to requisitions and the dissolution of the Soviet administration and the Cheka.',
          sources: [S.tamb, S.tambru],
        },
        {
          ko: '안토노프는 농민 부대를 붉은 군대를 본떠 정치위원과 정찰·통신 부서를 둔 18~20개 연대로 편성하고 엄격한 규율을 세웠다. 봉기군에는 의무대와 증원 여단이 있었고, 여성과 어린이, 노인까지 동원한 연락·정보망이 있었다. 각 마을은 자기 부대를 무장시키고 먹여 살리는 책임을 졌다. 러시아어 출처에 따르면 봉기는 1921년 1~2월 절정에 이르러 보병 14개 연대, 기병 5개 연대, 독립 여단 1개에 기관총 25정, 대포 5문을 갖춘 두 개 군, 약 5만 명에 달했다. 영어 출처는 두 군 21개 연대로 쓰고, 1920년 10월~1921년 1월 최대 5만 명을 동원했으며 1921년 2월에는 2만~4만 명 가운데 절반이 상근 전투원, 나머지는 시간제였다고 전한다. 약 6천 명이 기병이었다. 봉기군은 국영농장 60곳을 파괴하고 랴잔-우랄 철도의 운행을 마비시켰으며, 징발 곡물을 실은 열차를 빼앗아 마을에 나누어 주었다. 그러나 중화기가 없어 도시를 점령하지 못했고, 자기 마을을 지키는 데 머무는 지역성 때문에 다른 농민 운동과 손잡거나 큰 도시로 진군하지 못했다.',
          en: 'Antonov organised the peasant units on the Red Army model into 18–20 regiments with political commissars, reconnaissance and communications departments, and imposed strict discipline. The rebels had a medical staff and reinforcement brigades, and a communications and intelligence network that used women, children and the elderly. Each village was responsible for arming and feeding its own unit. According to Russian-language sources the rising peaked in January–February 1921 at about 50,000 men in two armies with 14 infantry and 5 cavalry regiments, one separate brigade, 25 machine guns and five guns. English-language sources give two armies of 21 regiments, say up to 50,000 were mobilised between October 1920 and January 1921, and put the force in February 1921 at 20,000–40,000, half of them full-time fighters and half part-time. About 6,000 were mounted. The rebels destroyed 60 state farms, halted traffic on the Ryazan–Ural railway, and seized trains of requisitioned grain and handed it out to villages. But without heavy weapons they could not take towns, and a localism focused on defending their own villages kept them from joining other peasant movements or marching on large cities.',
          sources: [S.tamb, S.tambru, S.green],
        },
        {
          ko: '1921년 5월 근로농민동맹은 제헌의회가 소집될 때까지 다스릴 「탐보프 파르티잔 지구 임시 민주 공화국」을 선포했다. 러시아어 출처는 선포일을 5월 20일, 장소를 키르사노프군 카라이살티키 마을의 주민 집회로 적고, 수반으로 저항에 가장 적극적이던 농민 셴댜핀이 추대되었다고 쓴다. 영어 출처에 따르면 이 공화국은 혁명 전 러시아 국기를 썼고, 백군의 구호였던 「위대하고 단일하며 나눌 수 없는 러시아 만세」가 봉기군의 표어 가운데 하나가 되었다. 같은 출처는 봉기군이 붉은 깃발을 군기로 써서 혁명의 중심 상징을 자기 것으로 주장했다고도 적어, 상징의 사용은 부대와 시기에 따라 달랐던 것으로 보인다. 토크마코프의 최후도 출처마다 다르다. 러시아어 인물 문서는 그가 1921년 2월 28일 보리소글렙스크군으로 가는 제2군 원정 중 보고슬롭카 마을 근처에서 사실상 유탄에 맞아 전사했다고 쓰지만, 영어 출처는 그가 1921년 6월 보구슬랍스키와 비슷한 시기에 전투에서 죽었다고 적는다. 영어 출처는 강령을 갖춘 덕에 이 운동이 다른 농민 봉기에 없던 응집력을 얻었지만 정부를 무엇으로 대신할지에 대한 분명한 구상은 없었고, 안토노프는 모스크바로 진군해 볼셰비키 지배를 끝내기를 꿈꾸었다고 평가한다.',
          en: 'In May 1921 the Union of Working Peasants proclaimed a "Provisional Democratic Republic of the Tambov Partisan Region" to govern until a Constituent Assembly met. Russian-language sources date the proclamation to 20 May at a public meeting in the village of Karai-Saltyki in Kirsanov district, and say a peasant named Shendyapin, one of the most active resisters, was put forward as its head. According to English-language sources the republic used the pre-revolutionary Russian flag, and the White slogan "Long live the Great, United and Indivisible Russia" became one of the rebels\' mottos. The same sources also say the rebels fought under the red flag and so claimed the central symbol of the revolution, which suggests that symbols varied by unit and period. Accounts of Tokmakov\'s end also differ. His Russian-language biography says he was killed, in effect by a stray bullet, near the village of Bogoslovka on 28 February 1921 during the 2nd Army\'s raid into Borisoglebsk district, whereas English-language sources say he died in battle in June 1921, around the same time as Boguslavsky. English-language sources judge that its programme gave the movement a coherence other peasant risings lacked, but that it had no clear idea of what should replace the government, while Antonov dreamed of marching on Moscow and ending Bolshevik rule.',
          sources: [S.tamb, S.tambru, S.tokm],
        },
      ],
    },
    {
      heading: { ko: '1921년 서시베리아: 이심에서 토볼스크까지 {russia}', en: 'Western Siberia, 1921: from Ishim to Tobolsk {russia}' },
      paragraphs: [
        {
          ko: '콜차크 정권이 무너진 뒤 시베리아는 소비에트 곡물 정책의 새 공급지가 되었다. 영어 출처에 따르면 약 3만 5천 명의 식량 부대 병력이 시베리아에 배치되었다. 1920년 7월 20일 소브나르콤은 「시베리아의 곡물 잉여 수거에 관하여」 결정을 내려 농민에게 지난해 잉여와 새 수확의 잉여를 동시에 바치게 했다. 1920년 6월 20일부터 1921년 3월 1일까지 시베리아 혁명위원회 관할 6개 주(이르쿠츠크·예니세이·톰스크·옴스크·알타이·세미팔라틴스크)는 1억 1천만 푸드, 튜멘주는 817만 7천 푸드, 예카테린부르크주 1천만 푸드, 첼랴빈스크주 1,700만 푸드를 내야 했다. 이는 전국 할당 4억 4천만 푸드의 3분의 1이었다. 곡물 외에도 고기 627만 푸드와 버터·달걀·감자·가죽·양모·뿔·발굽까지 37가지 할당이 매겨졌다. 1920년 큰 흉작을 겪은 이심군에서도 지방 당국은 식량용 곡물과 종자까지 거두었고, 튜멘주는 계획의 102퍼센트를 채웠다. 1920년 12월 제8차 소비에트 대회의 결정에 따라 농가의 종자를 모두 공동 창고로 옮기는 종자 할당까지 준비되었다.',
          en: 'After the fall of the Kolchak regime, Siberia became a new source for Soviet grain policy. According to English-language sources some 35,000 food-detachment troops were stationed there. On 20 July 1920 the Sovnarkom decreed "On the Removal of Grain Surpluses in Siberia", obliging peasants to surrender the previous years\' surpluses and the new harvest\'s at the same time. Between 20 June 1920 and 1 March 1921 the six provinces under the Siberian Revolutionary Committee (Irkutsk, Yenisei, Tomsk, Omsk, Altai and Semipalatinsk) were to deliver 110 million poods, Tyumen province 8,177,000, Yekaterinburg province 10 million and Chelyabinsk province 17 million, a third of the national quota of 440 million poods. Besides grain, 37 separate levies were imposed, including 6.27 million poods of meat as well as butter, eggs, potatoes, hides, wool, horns and hooves. Even in Ishim district, hit by a severe crop failure in 1920, local authorities took food grain and seed, and Tyumen province fulfilled 102 per cent of its plan. Following decisions of the Eighth Congress of Soviets in December 1920, a seed levy was prepared to move all household seed into communal granaries.',
          sources: [S.wsibru, S.wsib],
        },
        {
          ko: '1920년 12월 31일 이심군 페가노보 향의 여성 집회는 식량 위원들의 횡포를 불법으로 규정하고 9명으로 된 식량 부대를 무장 해제했다. 1921년 1월 31일에는 이심군 북부 첼노콥스코예와 추르탄 마을에서 농민들이 종자 곡물 반출을 막으려 했고, 병사들이 발포해 2명이 죽고 2명이 다쳤다. 이번에는 농민들이 물러서지 않고 말뚝과 쇠스랑, 사냥총을 들고 징발원들을 쫓아냈다. 사흘 만에 봉기는 이심군 북부 전체로 퍼졌고, 곧 튜멘·토볼스크·얄루토롭스크·타라·튜칼린스크와 쿠르간·캄실로프·샤드린스크군으로 번졌다. 2월에 봉기군은 시베리아 횡단 철도의 두 노선을 3주 동안 마비시켰고, 2월 14일 페트로파블롭스크(오늘날 카자흐스탄의 페트로파블), 21일 토볼스크와 콕체타프, 3월 10일 수르구트, 21일 베료조보, 4월 1일 오브도르스크, 5일 카르카랄린스크를 차지했다. 봄의 봉기 지역은 북쪽 오브도르스크에서 남쪽 카르카랄린스크까지, 서쪽 투구림역에서 동쪽 수르구트까지 이르렀다. 페트로파블롭스크는 세 번 주인이 바뀐 끝에 2월 16일 붉은 군대 손에 남았다.',
          en: 'On 31 December 1920 a women\'s assembly in Peganovo township, Ishim district, declared the food commissars\' conduct illegal and disarmed a nine-man food detachment. On 31 January 1921 peasants in the villages of Chelnokovskoye and Churtan in northern Ishim district tried to stop seed grain being taken away; soldiers opened fire, killing two and wounding two. This time the peasants did not back down: armed with stakes, pitchforks and hunting guns, they drove the requisitioners out. Within three days the rising covered all of northern Ishim district and soon spread to the Tyumen, Tobolsk, Yalutorovsk, Tara, Tyukalinsk, Kurgan, Kamyshlov and Shadrinsk districts. In February the rebels paralysed both lines of the Trans-Siberian Railway for three weeks and took Petropavlovsk (today Petropavl in Kazakhstan) on 14 February, Tobolsk and Kokchetav on the 21st, Surgut on 10 March, Beryozovo on 21 March, Obdorsk on 1 April and Karkaralinsk on 5 April. In spring the insurgent zone stretched from Obdorsk in the north to Karkaralinsk in the south and from Tugulym station in the west to Surgut in the east. Petropavlovsk changed hands three times before remaining with the Red Army on 16 February.',
          sources: [S.wsibru],
        },
        {
          ko: '서시베리아 봉기는 참가자 수와 지리적 범위로 볼 때 녹색군 봉기 가운데 가장 컸지만 가장 덜 연구된 봉기로 꼽힌다. 러시아어 출처는 4월까지 봉기군이 10만 명을 넘었다고 쓰면서도 문헌에 따라 3만~15만 명으로 엇갈린다고 밝힌다. 영어 출처는 역사가 블라디미르 슐퍄코프의 7만~10만 명을 소개하면서 5만 5천~6만 명이 가장 그럴듯하다고 보고, 봉기군이 다스린 지역 인구를 340만 명으로 적는다. 가장 널리 퍼진 구호는 「공산주의자 없는 소비에트」였고, 봉기군은 언론·집회·결사의 자유, 자유 거래, 자기 땅과 생산물을 처분할 권리, 곧 곡물 독점의 폐지를 요구했다. 해방된 지역에서는 자유롭게 선출된 향·마을 농민 소비에트가 다시 세워졌다. 그러나 사회혁명당의 견해와 군주제 지지가 함께 섞여, 일부 지역에서는 계급 호칭과 견장이 되살아났다. 단일 본부는 없었고, 퇴역 중위 블라디미르 로딘이 이끈 이심-페트로파블롭스크 지구의 시베리아 본부 같은 여러 지휘부가 따로 움직였다. 지휘관 상당수는 두 전쟁을 거친 하사관과 준위 출신 농민이었고, 18~35세(때로 45세) 남성을 강제로 동원하기도 했다.',
          en: 'By number of participants and geographic extent, the West Siberian rising was the largest of the Green revolts, yet it is also counted among the least studied. Russian-language sources say the insurgents exceeded 100,000 by April while noting that the literature gives anything from 30,000 to 150,000. English-language sources cite the historian Vladimir Shulpyakov\'s 70,000–100,000 but consider 55,000–60,000 the most likely figure, and put the population under rebel control at 3.4 million. The most widespread slogan was "Soviets without Communists", and the rebels demanded freedom of speech, assembly and association, free trade and the right to dispose of their land and produce, that is, an end to the grain monopoly. Freely elected township and village peasant soviets were restored in liberated areas. Yet SR views and monarchism coexisted, and in some places ranks and epaulettes reappeared. There was no single headquarters; separate commands acted independently, such as the Main Siberian Staff in the Ishim–Petropavlovsk area under the former lieutenant Vladimir Rodin. Many commanders were peasant NCOs and ensigns hardened by two wars, and men aged 18–35 (sometimes 45) were mobilised by force.',
          sources: [S.wsib, S.wsibru],
        },
      ],
    },
    {
      heading: { ko: '볼가에서 캅카스까지: 1920~1921년의 「농민 전쟁」 {russia}', en: 'From the Volga to the Caucasus: the "peasant war" of 1920–1921 {russia}' },
      paragraphs: [
        {
          ko: '1920년 2월 우파주 멘젤린스크군에서는 「쇠스랑 봉기」라고도 불리는 「검은 독수리」 봉기가 일어났다. 러시아어 출처에 따르면 노바야옐란 마을의 식량 위원은 감당할 수 없는 5,535푸드의 곡물을 24시간 안에 내라고 요구하며 2월 4일 여성 2명을 포함한 주민 20명을 영하 30도의 추위 속 창고에 인질로 가두었다. 2월 7일 쇠스랑과 도끼를 든 마을 사람들이 인질을 풀어 주면서 식량 부대원 4명이 죽었고, 9일에는 협상하러 온 멘젤린스크군 체카 의장과 자인스크 민경대장이 살해되었다. 영어 출처는 첫 충돌을 2월 4일로 적는다. 전직 하사관 알렉세이 밀로바노프가 이끈 봉기는 우파주의 벨레베이·비르스크군과 카잔주 치스토폴군, 사마라주 부굴마군으로 퍼져 약 5만 명의 「검은 독수리 군」을 이루었다. 소총은 약 1,200정뿐이었다. 체카 소속 공화국 국내 방위군은 기관총과 대포로 대응했고, 3월 중순까지 봉기는 진압되었다. 영어 출처에 따르면 소비에트군 약 800명과 봉기군 3천여 명이 죽고 수백 개 마을이 불탔다.',
          en: 'In February 1920 the "Black Eagle" rising, also called the Pitchfork Uprising, broke out in Menzelinsk district of Ufa province. According to Russian-language sources, the food commissar in the village of Novaya Yelan demanded an impossible 5,535 poods of grain within 24 hours and on 4 February locked twenty villagers, two of them women, in a barn as hostages in thirty degrees of frost. On 7 February villagers armed with pitchforks and axes freed the hostages, killing four detachment members, and on the 9th the chairman of the Menzelinsk district Cheka and the head of the Zainsk militia, who had come to negotiate, were killed. English-language sources date the first clash to 4 February. Led by the former sergeant-major Aleksey Milovanov, the rising spread to the Belebey and Birsk districts of Ufa province, Chistopol district of Kazan province and Bugulma district of Samara province, forming a "Black Eagle" army of about 50,000 with only some 1,200 rifles. The Cheka\'s Troops for the Internal Defence of the Republic answered with machine guns and artillery, and by mid-March the rising was crushed. According to English-language sources about 800 Soviet troops and more than 3,000 rebels died and hundreds of villages were burned.',
          sources: [S.pitchru, S.pitch],
        },
        {
          ko: '1920년 7월에는 붉은 군대 지휘관이 봉기를 일으켰다. 알렉산드르 사포시코프는 사마라주 노보우젠스크의 농민 출신 소위로, 1917년 노보우젠스크군 소비에트 초대 의장을 지낸 좌파 사회혁명당원이었다. 내전 중 제22사단을 이끌고 1919년 우랄스크에서 80일 동안 포위를 버텨 이름을 떨쳤으나, 「서툰 지휘와 부대를 해치는 정치」를 이유로 전선에서 물러났다. 부줄루크군에서 제9기병사단을 편성하던 그는 7월 8일 해임 소식을 들었고, 14일 포그롬노예 마을의 사단 집회에서 명령 제1호로 사단을 「제1 진리의 붉은 군대」로 바꾸었다. 그는 소비에트 재선거와 식량 부대 폐지, 자유 거래를 요구하며 공산당이 프롤레타리아 전체가 아닌 한 당의 독재를 하고 있다고 비판했다. 보병 500명과 기병 500명으로 부줄루크를 점령했지만 16일 내주었고, 우랄스크와 노보우젠스크 공격도 실패했다. 당국은 지도자들의 가족을 인질로 잡았다. 9월 6일 사포시코프는 아스트라한주 초원의 코임 아울 근처에서 추격대에게 사살되었다. 사마라 혁명재판소는 150명 가운데 52명에게 사형을 선고했고, 순회 재판에서도 최소 117명이 사형을 받았다.',
          en: 'In July 1920 a Red Army commander rose in revolt. Alexander Sapozhkov, a second lieutenant of peasant stock from Novouzensk in Samara province, was a Left SR who had been the first chairman of the Novouzensk district soviet in 1917. In the civil war he commanded the 22nd Division and won fame holding Uralsk through an 80-day siege in 1919, but was removed from the front for "incompetent command and a corrupting policy". While forming the 9th Cavalry Division in Buzuluk district he learned of his dismissal on 8 July, and on the 14th, at a divisional meeting in the village of Pogromnoye, his Order No. 1 renamed the division the "1st Red Army of Truth". He demanded new elections to the soviets, the abolition of food detachments and free trade, and charged that the Communists were exercising the dictatorship of one party rather than of the whole proletariat. With 500 infantry and 500 cavalry he took Buzuluk but gave it up on the 16th, and attacks on Uralsk and Novouzensk failed. The authorities took the leaders\' families hostage. On 6 September Sapozhkov was shot by pursuers near the aul of Koim in the Astrakhan steppe. The Samara revolutionary tribunal sentenced 52 of 150 defendants to death, and travelling sessions sentenced at least 117 more.',
          sources: [S.sapru, S.sapp],
        },
        {
          ko: '봉기는 다른 곳에서도 이어졌다. 1921년 1월 알타이의 바르나울 동쪽과 비스크 북쪽에서는 소로키노를 중심으로 5천~1만 명의 농민이 「깨끗한 소비에트 권력을 위하여」, 「공산주의자 없는 소비에트」를 내걸고 일어났다. 백군 출신과 아나키스트 유격대가 함께한 이 봉기에서 2월 소로키노 근처 전투로 봉기군 약 400명과 붉은 군대 병사 5명이 죽었다. 같은 1월 24일 추바시 지역의 야드린군에서는 5천~7천 명의 농민이 징발에 맞서 일어났다가 사흘 만에 진압되었다. 남쪽에서는 1920년 쿠반·돈 카자크와 캅카스 산악민이 봉기해 3만 명이 넘는 유격대를 이루었고, 이듬해 여름 결정적으로 패한 뒤에도 쿠반·돈의 작은 녹색군 무리가 1923년까지 남았다. 우크라이나에서는 다닐로 테르필로가 키예프주 농촌을 장악하고 2만 명을 거느렸으며, 니키포르 흐리호리우 같은 아타만들이 진영을 바꾸어 가며 싸웠다. 가장 크고 조직적인 운동은 네스토르 마흐노의 아나키스트 농민군이었다. 우크라이나의 농민군과 마흐노의 행로는 [우크라이나 혁명과 전쟁](/commulingo/events/ukraine-1917-1921)에서 다룬다.',
          en: 'Risings continued elsewhere. In January 1921, east of Barnaul and north of Biysk in the Altai, 5,000–10,000 peasants centred on Sorokino rose under the slogans "For a clean Soviet power" and "Soviets without Communists". White veterans and anarchist partisans fought side by side, and a battle near Sorokino in February killed about 400 rebels and five Red Army soldiers. On 24 January 1921, in Yadrin district of the Chuvash Autonomous Region, 5,000–7,000 peasants rose against requisitions and were crushed within three days. In the south, Kuban and Don Cossacks and Caucasian mountaineers rose in 1920, forming guerrilla forces of more than 30,000; after their decisive defeat the following summer, small Green bands remained active in the Kuban and Don until 1923. In Ukraine Danylo Terpylo controlled the countryside of Kiev province with 20,000 armed followers, and atamans such as Nykyfor Hryhoriv fought while switching sides. The largest and best-organised movement was Nestor Makhno\'s anarchist peasant army. Ukraine\'s peasant armies and Makhno\'s course are covered in [the Ukrainian Revolution and war](/commulingo/events/ukraine-1917-1921).',
          sources: [S.sorokino, S.chapan, S.green],
        },
        {
          ko: '1921년 1월이 되자 농민 봉기는 탐보프와 서시베리아 말고도 사마라·사라토프·차리친·아스트라한으로 번져 있었다. 영어 출처는 1919~1921년 동부 우크라이나와 탐보프, 시베리아의 대규모 봉기에 10만 명이 넘는 유격대원과 수백만 명의 농민 지지자가 관여했다고 쓴다. 레닌은 이를 소비에트 역사상 첫 「큰 국내 정치 위기」라고 불렀고, 1921년 3월 8일 제10차 당대회 개회 연설에서 이 소부르주아적 반혁명이 「데니킨, 유데니치, 콜차크를 합친 것보다 훨씬 더 위험하다」고 말했다. 같은 시기 도시에서도 위기가 겹쳤다. 페트로그라드와 모스크바에서 노동자 항의가 일어났고, 1921년 3월 크론시타트 수병들은 소비에트 재선거와 함께 전국에서 봉기 중인 농민을 위한 요구를 결의에 담았다. 그 경위와 진압은 [크론시타트 봉기](/commulingo/events/kronstadt-1921)에서 다룬다. 소비에트 지도부는 봉기를 하나하나 개별 소요로 다루며 가혹하게 진압하다가, 운동의 힘을 깨달았을 때 이미 그것이 소비에트 권력에 대한 심각한 사회적·군사적 위협이 되어 있었다는 평가도 있다.',
          en: 'By January 1921 peasant revolts had spread beyond Tambov and Western Siberia to Samara, Saratov, Tsaritsyn and Astrakhan. English-language sources say the great risings in eastern Ukraine, Tambov and Siberia in 1919–21 involved more than 100,000 guerrillas and millions of peasant supporters. Lenin called it the first "great internal political crisis" in Soviet history, and in his opening speech to the 10th Party Congress on 8 March 1921 he said this petty-bourgeois counter-revolution was "far more dangerous than all the forces of Denikin, Yudenich and Kolchak combined". The crisis reached the towns at the same time: workers protested in Petrograd and Moscow, and in March 1921 the Kronstadt sailors\' resolution combined new elections to the soviets with demands on behalf of the peasants in revolt across the country. That rising and its suppression are covered in [the Kronstadt rebellion](/commulingo/events/kronstadt-1921). One assessment holds that the Soviet leadership treated each rising as a separate disturbance and suppressed it harshly, and that by the time it grasped the movement\'s strength it had become a serious social and military threat to Soviet power.',
          sources: [S.tamb, S.green],
        },
      ],
    },
    {
      heading: { ko: '징발에서 현물세로: 1921년 2~3월의 정책 전환 {russia}', en: 'From requisition to tax in kind: the policy turn of February–March 1921 {russia}' },
      paragraphs: [
        {
          ko: '정책 전환은 봉기의 압력 속에서 단계적으로 이루어졌다. 1921년 2월 8일 정치국은 발레리안 오볼렌스키(필명 오신스키)의 보고 「파종 운동과 농민의 상태에 관하여」를 듣고 할당 징발을 현물세로 바꾸는 문제를 논의했고, 2월 16일 『프라우다』에 공개 토론을 열기로 해 17일과 26일 첫 글이 실렸다. 탐보프에는 그보다 먼저 손이 갔다. 영어 출처에 따르면 니콜라이 부하린이 주민을 끌어오기 위한 「비강제적 조치」를 마련하라는 임무를 받아 할당량을 낮추라고 권고했고, 블라디미르 안토노프-옵세옌코는 탐보프 농민 두 명 중 한 명이 굶주리고 있다는 것을 직접 보았다. 같은 출처는 소비에트 지도부가 2월 2일 이 지역에 대한 징발 중단과 현물세 도입을 발표했고, 그 소식이 2월 9일부터 탐보프에 퍼졌다고 쓴다. 러시아어 출처는 식량인민위원부의 결정으로 2월 12일 탐보프주에서 할당 징발의 집행이 멈추었다고 적는다. 어느 쪽이든 탐보프의 징발 중단은 제10차 당대회의 전국적 결정보다 앞섰다.',
          en: 'The policy turn came in stages under the pressure of the risings. On 8 February 1921 the Politburo heard Valerian Obolensky\'s (pen name Osinsky) report "On the sowing campaign and the condition of the peasantry" and discussed replacing apportionment with a tax in kind; on 16 February it decided to open a public debate in Pravda, and the first articles appeared on the 17th and 26th. Tambov was dealt with earlier. According to English-language sources Nikolai Bukharin was commissioned to draw up "non-coercive measures" to win over the population and recommended lowering quotas, and Vladimir Antonov-Ovseenko saw for himself that every other Tambov farmer was starving. The same sources say the Soviet leadership announced on 2 February the end of requisitioning and a tax in kind for the region, and that the news began circulating in Tambov on 9 February. Russian-language sources say that by decision of the Food Commissariat the collection of the apportionment was halted in Tambov province on 12 February. Either way, the halt in Tambov came before the national decision of the 10th Party Congress.',
          sources: [S.prodnalog, S.tamb, S.tambru],
        },
        {
          ko: '제10차 당대회는 1921년 3월 8일부터 16일까지 모스크바에서 투표권 대의원 694명, 발언권 대의원 296명이 모인 가운데 열렸고, 의제에는 식량 공급, 할당 징발, 현물세와 연료 위기가 들어 있었다. 레닌은 일반 보고에서 신경제정책(네프)을 조심스럽게 꺼냈고, 레프 트로츠키는 두 차례 연설에서 전시 공산주의가 「경제가 아니라 군사적 필요와 조건이 강요한 것」이었다고 설명했다. 대회 결정에 따라 3월 21일 전러시아중앙집행위원회는 「할당 징발을 현물세로 바꾸는 것에 관한」 법령을 공포했다. 현물세는 수확과 가족 수, 가축을 따져 생산물의 일정 비율로 매기는 고정세였고, 부농에게 무겁게 매기는 누진세였으며 가장 가난한 농가는 면제되었다. 1920~1921년 할당 징발로 거둔 곡물이 3억 6,700만 푸드였던 데 비해 1921~1922년 현물세는 2억 4천만 푸드로 정해졌고, 흉작 때문에 실제로는 이보다 덜 걷혔다. 서시베리아 봉기에 관한 러시아어 출처는 이 봉기를 3월 21일의 전환을 낳은 원인 가운데 하나로 꼽는다. 같은 대회는 당내 분파를 금지하는 결의도 채택했다.',
          en: 'The 10th Party Congress met in Moscow from 8 to 16 March 1921 with 694 voting and 296 non-voting delegates; its agenda included food supply, apportionment, the tax in kind and the fuel crisis. Lenin cautiously introduced the New Economic Policy (NEP) in his general report, and Leon Trotsky explained in two speeches that war communism had been "dictated not by economic, but by military needs, considerations and conditions". Following the congress\'s decision, on 21 March the All-Russian Central Executive Committee issued the decree "On the Replacement of Apportionment by a Tax in Kind". The tax in kind was a fixed levy assessed as a share of output according to the harvest, the number of mouths and the livestock; it was progressive, weighing more heavily on wealthier peasants, and the poorest households were exempt. Whereas apportionment had taken 367 million poods of grain in 1920–21, the tax for 1921–22 was set at 240 million poods, and because of the crop failure even less was actually collected. Russian-language sources on the West Siberian rising count it among the causes of the 21 March change. The same congress also adopted a resolution banning factions within the party.',
          sources: [S.cong10, S.nep, S.prodnalog, S.wsibru],
        },
        {
          ko: '탐보프에서는 양보와 함께 사면이 선전되었다. 일반 봉기 참가자에게는 무기를 넘기고 지휘관의 소재를 알리는 조건으로 사면이 약속되었고, 이 조치는 77종의 호소문·전단·포스터·소책자로 널리 알려졌다. 영어 출처에 따르면 3월 20일 투항자 전원에 대한 사면이 발표되어 2주 동안 약 3천 명이 투항했지만 무기를 들고 온 사람은 아주 적었다. 봉기군 지휘부도 변화를 느꼈다. 안토노프는 2월 21일 제1봉기군 명령 제21호에서 「파르티잔 부대들 사이에 전투 의지가 약해지고 부끄러운 비겁함이 보인다」고 썼고, 러시아어 출처에 따르면 징발 폐지를 기뻐하는 고렐로예 마을 농민들에게 「그렇다, 농민들이 이겼다. 물론 잠시 동안이지만. 그런데 우리 지휘관들에게는 이제 끝장이다」라고 말했다. 그래도 싸움은 계속되었다. 4월 11일 안토노프는 5천 명으로 라스카조보 수비대를 협공해 붉은 군대 대대 하나를 포로로 잡고 대포와 기관총 11정, 소총 400정을 노획했다. 그러나 4월 하순 키르사노프 공격은 두 차례 모두 실패했고, 공산당 측 추산으로 이어진 추격에서 봉기군 2천 명이 죽었다.',
          en: 'In Tambov the concessions came with a publicised amnesty. Rank-and-file rebels were promised amnesty on condition that they surrendered their weapons and revealed where their commanders were, and the measures were spread through 77 different appeals, leaflets, posters and pamphlets. According to English-language sources a general amnesty for all who surrendered was announced on 20 March; in the two weeks it was in force about 3,000 rebels gave themselves up, but very few brought weapons. The rebel leadership felt the change. In Order No. 21 to the 1st Insurgent Army on 21 February Antonov wrote that "fighting spirit is beginning to weaken among the partisan units, and shameful cowardice is observed", and according to Russian-language sources he told peasants of Goreloye who rejoiced at the end of requisitions: "Yes, the muzhiks have won. For a while, of course. But for us, father-commanders, it\'s the end now." Still the fighting went on. On 11 April Antonov struck the Rasskazovo garrison in a pincer attack with 5,000 men, capturing an entire Red Army battalion along with a gun, 11 machine guns and 400 rifles. But both assaults on Kirsanov in late April failed, and by Communist estimates 2,000 rebels died in the pursuit that followed.',
          sources: [S.tambru, S.tamb],
        },
      ],
    },
    {
      heading: { ko: '진압: 전권위원회와 투하쳅스키 {russia}', en: 'Suppression: the Plenipotentiary Commission and Tukhachevsky {russia}' },
      paragraphs: [
        {
          ko: '1921년 2월 6일 전러시아중앙집행위원회는 블라디미르 안토노프-옵세옌코를 위원장으로 하는 전권위원회를 탐보프주에 보냈고, 이 위원회가 봉기 진압의 최고 기관이 되었다. 그때 A. V. 파블로프 휘하 병력은 1만 1,602명, 기관총 136정, 대포 18문이었다. 폴란드와의 전쟁이 끝나고 브랑겔군이 크림에서 철수하자 붉은 군대는 정규군을 돌릴 수 있게 되었다. 4월 27일 정치국은 미하일 투하쳅스키를 탐보프주 군 사령관으로, 이에로님 우보레비치를 부사령관으로, 니콜라이 카쿠린을 참모장으로 임명했고, 그리고리 코톱스키도 파견되었다. 전러시아 체카에서는 겐리흐 야고다와 바실리 울리흐가 왔다. 투하쳅스키는 한 달 안에 봉기를 끝내라는 지시를 받았다. 러시아어 출처에 따르면 5월 말 병력은 보병 3만 5천, 기병 8천, 기관총 463정, 대포 63문의 4만 3천 명이었고, 전체적으로 포병 여단 9개와 장갑차 부대 5개, 장갑열차 4대, 항공대 2개, 모스크바·오룔 보병학교와 보리소글렙스크 기병학교의 생도까지 최대 5만 5천 명이 투입되었다. 영어 출처는 5만~10만 명으로 적는다.',
          en: 'On 6 February 1921 the All-Russian Central Executive Committee sent a Plenipotentiary Commission chaired by Vladimir Antonov-Ovseenko to Tambov province, and it became the supreme body for crushing the rising. At that point A. V. Pavlov commanded 11,602 men with 136 machine guns and 18 guns. With the war against Poland over and Wrangel\'s army evacuated from the Crimea, the Red Army could divert regular troops. On 27 April the Politburo appointed Mikhail Tukhachevsky commander of the forces in Tambov province, Ieronim Uborevich his deputy and Nikolai Kakurin chief of staff, and Grigory Kotovsky was also sent. Genrikh Yagoda and Vasily Ulrikh came from the All-Russian Cheka. Tukhachevsky was directed to finish the rising within a month. According to Russian-language sources, by the end of May he had 43,000 men (35,000 infantry and 8,000 cavalry with 463 machine guns and 63 guns), and in all up to 55,000 were committed, including nine artillery brigades, five armoured-car detachments, four armoured trains, two air detachments and cadets of the Moscow and Oryol infantry schools and the Borisoglebsk cavalry school. English-language sources give 50,000–100,000.',
          sources: [S.tambru, S.tamb],
        },
        {
          ko: '투하쳅스키는 5월 6일 평정 작전을 발표하고 봉기 지역을 「군대로 가득 채우는」 계획을 세웠다. 영어 출처에 따르면 정규군 외에 중국인·헝가리인 국제주의자 부대와 체카 부대, 특수임무부대, 그리고 정치적으로 믿을 만하다고 여겨진 콤소몰 단원이 대거 배치되었다. 5월 25일 코톱스키의 독립 기병여단은 바실리 셀랸스키가 이끄는 봉기군 2개 연대를 격파했고, 셀랸스키는 치명상을 입었다. 5월 31일 이반 페드코가 지휘한 장갑차 7대가 드베 세스트리치 마을에서 봉기군 3천 명을 기습해 큰 손실을 입혔다. 러시아어 출처에 따르면 5월 28일부터 6월 7일까지 인자비노역 일대에서 우보레비치가 총지휘한 코톱스키 여단, 제14독립기병여단, 제15시베리아기병사단, 보리소글렙스크 기병학교 생도들이 안토노프의 제2봉기군을 격파했다. 영어 출처는 6월 1~9일 카멘카 근처에서 우보레비치의 세 부대가 안토노프와 보구슬랍스키의 2천 명과 여섯 차례 싸워 800명을 죽였다고 쓴다. 그 뒤 보구슬랍스키의 제1봉기군은 결전을 피했고 주도권은 완전히 붉은 군대로 넘어갔다.',
          en: 'Tukhachevsky announced his pacification campaign on 6 May with a plan to "flood the rebellion area with troops". According to English-language sources, besides regular forces he deployed Chinese and Hungarian internationalist units, Cheka detachments, Special Purpose Units and large numbers of Komsomol members, considered politically reliable. On 25 May Kotovsky\'s separate cavalry brigade routed two rebel regiments under Vasily Selyansky, who was mortally wounded. On 31 May seven armoured cars under Ivan Fedko surprised 3,000 rebels at the village of Dve Sestritsy and dispersed them with heavy losses. According to Russian-language sources, between 28 May and 7 June, around Inzhavino station, Kotovsky\'s brigade, the 14th Separate Cavalry Brigade, the 15th Siberian Cavalry Division and Borisoglebsk cavalry cadets under Uborevich\'s overall command destroyed Antonov\'s 2nd Insurgent Army. English-language sources say that on 1–9 June three forces under Uborevich fought six battles near Kamenka against 2,000 rebels under Antonov and Boguslavsky, killing 800. After that Boguslavsky\'s 1st Insurgent Army avoided a decisive battle, and the initiative passed entirely to the Red Army.',
          sources: [S.tamb, S.tambru],
        },
        {
          ko: '1921년 6월 11일 전권위원회는 명령 제171호 「개별 비적과 그들을 숨겨 주는 가족에 대한 탄압 조치 개시에 관하여」를 냈다. 명령은 「사회혁명당 비적의 뿌리를 뽑기 위해」 이름을 밝히지 않는 시민을 재판 없이 그 자리에서 총살하고, 무기를 숨긴 마을에서 인질을 잡아 무기를 내놓지 않으면 총살하며, 숨긴 무기가 나오면 그 집의 가장 연장자인 일꾼을 재판 없이 총살하도록 했다. 비적이 숨어든 집의 가족은 체포해 주 밖으로 추방하고 재산을 몰수하며 연장자 일꾼을 총살하고, 달아난 가족의 재산은 소비에트 권력에 충실한 농민에게 나누어 주고 집은 불태우거나 허물게 했다. 안토노프-옵세옌코와 투하쳅스키, 주 집행위원회 의장 라브로프가 서명한 명령은 마을 집회에서 낭독되었다. 6월 23일 명령 제116호는 향 전체를 포위하고 60~100명을 인질로 잡아 두 시간 안에 비적과 무기를 내놓지 않으면 주민 앞에서 총살하는 방식을 권장했다. 6월 27일 오시놉카 마을에서는 인질 약 40명 가운데 21명이, 7월 3~4일 보고슬롭카에서는 36명이 총살되었다. 투하쳅스키는 「총살 없이는 아무것도 되지 않는다」고 적었다.',
          en: 'On 11 June 1921 the Plenipotentiary Commission issued Order No. 171, "On the beginning of repressive measures against individual bandits and the families sheltering them". To "finally uproot the SR-bandit roots", it ordered that citizens who refused to give their names be shot on the spot without trial; that hostages be taken in villages hiding weapons and shot if the weapons were not surrendered; and that where hidden weapons were found, the eldest working member of the household be shot without trial. Families who sheltered a bandit were to be arrested and deported from the province, their property confiscated and their eldest worker shot; the property of families who fled was to be shared among peasants loyal to Soviet power and their houses burned or pulled down. Signed by Antonov-Ovseenko, Tukhachevsky and provincial executive chairman Lavrov, the order was read out at village assemblies. Order No. 116 of 23 June recommended cordoning off whole townships, taking 60–100 hostages and shooting them in front of the villagers if bandits and weapons were not handed over within two hours. On 27 June 21 of some 40 hostages were shot in the village of Osinovka, and on 3–4 July 36 hostages in Bogoslovka. Tukhachevsky wrote: "Without shootings nothing works."',
          sources: [S.tambru],
        },
        {
          ko: '6월 9일 전권위원회 회의는 숲에 남은 봉기군을 가스로 「몰아내기로」 결정했고, 6월 12일 투하쳅스키는 명령 제0116호에 서명했다. 「비적들이 숨은 숲을 독가스로 청소하되, 질식성 가스 구름이 숲 전체에 퍼져 그 안에 숨은 모든 것을 없애도록 정확히 계산하라」는 내용이었다. 6월 24일 포병 감찰관은 화학탄 2천 발의 발주가 났으며 전투 구역별로 나누어 보낼 것이라고 보고했다. 러시아어 출처에 따르면 처음에는 분사식 가스가 시도되었으나 효과가 없어 화학 포탄으로 바뀌었고, 최루성 클로로피크린을 넣은 포탄이 쓰였다. 문서로 확인되는 사용은 세 차례로, 7월 13일 한 포병대가 화학 유탄 47발을 쏘았고 8월 3일 키페츠 호수의 섬을 포격하며 화학탄 59발을 썼다. 피해를 두고는 해석이 갈린다. 일부 연구는 화학탄이 봉기군뿐 아니라 민간인도 죽였다고 주장한다. 반면 A. S. 보브코프는 사용 사실은 확인하면서도 붉은 군대에 경험이 없어 효과가 의심스럽고 사상자 기록이 없다고 지적했고, 군사사가 글루시코와 실로는 세 번 모두 전투 효과를 내기에 모자란 양이 쓰여 이후 사용이 중단되었다고 본다.',
          en: 'On 9 June a meeting of the Plenipotentiary Commission decided to "smoke out" the rebels remaining in the forests with gas, and on 12 June Tukhachevsky signed Order No. 0116: "The forests where the bandits are hiding are to be cleared with poison gases, calculated precisely so that the cloud of asphyxiating gas spreads fully through the whole forest, destroying everything hiding in it." On 24 June the inspector of artillery reported that 2,000 chemical shells had been ordered and would be distributed among the combat sectors. According to Russian-language sources, gas released from cylinders was tried first without effect, and chemical artillery shells were then used, filled with the tear agent chloropicrin. Three uses are documented: on 13 July an artillery battalion fired 47 chemical shells, and on 3 August a battery shelling an island in Lake Kipets fired 59. Interpretations of the effect differ. Some studies say the chemical shells killed civilians as well as rebels. A. S. Bobkov, while confirming the use, doubted its effectiveness given the Red Army\'s lack of experience and noted the absence of any record of casualties; the military historians Glushko and Shilo conclude that in all three cases too few shells were used to have a combat effect, which explains why their use was abandoned.',
          sources: [S.tambru, S.tamb],
        },
      ],
    },
    {
      heading: { ko: '수용소와 인명 피해 {russia}', en: 'Camps and the human toll {russia}' },
      paragraphs: [
        {
          ko: '인질과 봉기군 가족은 주 강제노동 관리국이 서둘러 마련한 「집중 수용소」에 갇혔다. 영어 출처에 따르면 1921년 7월 어린이 약 1천 명을 포함한 마을 주민 5만~10만 명이 이런 수용소에 수용되었고, 일부 마을은 주민 전체가 갇혔다. 수용자들은 콜레라와 발진티푸스에 시달렸고, 1921년 가을 월 사망률은 15~20퍼센트로 추정된다. 러시아어 출처에 따르면 6월 27일 전권위원회 회의는 수용소에 「젖먹이부터 시작하는 미성년자가 대거 몰려든다」고 기록하고, 15세 미만 어린이 인질을 어른과 따로 두며 세 살 아이는 어머니와 함께 있게 하자고 제안했다. 7월 수용소를 비우는 조치로 어린 자녀를 둔 인질이 집으로 돌아간 뒤에도 1~10세 어린이 인질 450명 이상이 남아 있었다. 7월 20일 탐보프군 정치위원회는 어린이와 임신부, 어린 자녀를 둔 여성을 인질로 잡지 말라는 명령을 따로 내려야 했다. 체포·추방된 가족의 재산은 정권의 지지자와 협력자에게 넘어갔고, 코프테보·히트로보·베르흐네스파스코예 같은 마을은 포격으로 완전히 파괴되었으며 65~70호의 제2카레옙카처럼 주민을 내쫓고 불태운 마을도 있었다.',
          en: 'Hostages and rebels\' families were held in "concentration camps" hastily set up by the provincial forced-labour administration. According to English-language sources, 50,000–100,000 villagers, including about 1,000 children, were interned in such camps in July 1921, and in some cases entire villages were held. Inmates suffered from cholera and typhus, and the monthly death rate in autumn 1921 is estimated at 15–20 per cent. According to Russian-language sources, the Plenipotentiary Commission noted on 27 June "a large influx of minors, starting with infants" into the camps and proposed holding child hostages under fifteen apart from adults and letting mothers stay with three-year-olds. Even after the camps were partly emptied in July and hostages with small children sent home, more than 450 child hostages aged one to ten remained. On 20 July the Tambov district political commission had to issue a separate order forbidding the arrest of children, pregnant women and women with small children as hostages. Property confiscated from arrested and deported families was given to the regime\'s supporters and collaborators; villages such as Koptevo, Khitrovo and Verkhnespasskoye were destroyed entirely by artillery, and some, like the 65–70-household 2nd Kareyevka, were emptied of their inhabitants and burned.',
          sources: [S.tamb, S.tambru],
        },
        {
          ko: '피해 규모는 출처마다 크게 다르다. 영어 출처는 진압 과정에서 약 10만 명이 체포되고 약 1만 5천 명이 죽었다고 추산하며, 투항한 봉기군 약 6천 명이 총살되거나 추방되었다고 쓴다. 추방된 이들은 지방 수용소를 거쳐 백군 장교와 크론시타트 봉기 포로를 가두던 북부의 특별 수용소로 옮겨졌고, 그곳의 사망률은 다른 수용소보다 특히 높았다. 러시아어 출처에서 역사가 율리야 칸토르는 탄압을 받은 탐보프 농민을 3만~5만 명으로 추산한다. 러시아의 연구자와 향토사가들은 봉기와 진압 뒤 주의 인구 감소를 약 24만 명으로 계산하며, 보리스 센니코프는 1920~1922년 전쟁과 처형, 수용소로 인한 탐보프 지역의 손실을 이 정도로 본다. 반대편의 폭력도 있었다. 봉기군은 공산당원 약 1천 명을 죽였고, 인질 제도에 맞서 붉은 군대 병사와 공산당원, 소비에트 직원과 그 가족을 인질로 잡아 총살했다. 투하쳅스키와 안토노프-옵세옌코를 노린 암살 시도도 있었다. 전투와 징벌, 볼셰비키 농업 정책이 겹친 결과 봉기 지역에는 기근이 닥쳤고, 이는 이듬해 볼가 유역의 [대기근](/commulingo/events/volga-famine)과 이어졌다.',
          en: 'Estimates of the toll vary widely. English-language sources estimate that about 100,000 people were arrested and about 15,000 killed during the suppression, and say some 6,000 rebels who surrendered were shot or deported. The deportees passed through local camps to special camps in the north otherwise reserved for White officers and captured Kronstadt insurgents, where mortality was particularly high compared with the rest of the camp system. In Russian-language sources the historian Yulia Kantor estimates the number of Tambov peasants subjected to repression at 30,000–50,000. Russian researchers and local historians calculate the province\'s population loss after the rising and its suppression at about 240,000, and Boris Sennikov puts the Tambov region\'s losses from war, executions and camps in 1920–22 at about that figure. There was violence on the other side too. The rebels killed some 1,000 Communists and, in answer to the hostage system, took and shot Red Army soldiers, Communists, Soviet employees and their families; there were also assassination attempts on Tukhachevsky and Antonov-Ovseenko. Fighting, punitive measures and Bolshevik agrarian policy together brought famine to the rebel areas, which ran into the following year\'s [Volga famine](/commulingo/events/volga-famine).',
          sources: [S.tamb, S.tambru, S.rcw],
        },
      ],
    },
    {
      heading: { ko: '마지막 저항: 니즈니시브랴이와 이심 {russia}', en: 'The last resistance: Nizhny Shibryai and Ishim {russia}' },
      paragraphs: [
        {
          ko: '1921년 여름 탐보프 봉기군 주력은 무너졌다. 7월 초 지도부는 전투 부대에 작은 무리로 나뉘어 숲에 숨어 유격전을 하거나 집으로 흩어지라는 명령을 내렸고, 8월까지 유격전이 이어졌다. 영어 출처에 따르면 9월에는 봉기군이 약 1천 명으로 줄었다. 같은 출처가 그해 말에도 4천 명 이하가 싸우고 있었다고 적어 수치는 엇갈리지만, 지휘관 대부분이 죽은 뒤 남은 무리는 늪과 숲에서 쫓기며 지냈다. 제1봉기군의 보구슬랍스키도 전투 중 죽었다. 산발적인 충돌은 1922년 여름까지 이어지다 잦아들었다. 1922년 6월 24일 안토노프와 동생 드미트리는 보리소글렙스크 근처 니즈니시브랴이 마을에서 체카 부대에 포위되었다. 체포하려던 부대가 숨은 집에 불을 지르자 두 사람은 빠져나오려다 사살되었고, 문서는 안토노프가 끝까지 무기를 놓지 않았다고 전한다. 그들은 닷새째 되는 날 탐보프의 카잔 성모 수도원 담장 근처에 묻혔다. 러시아어 출처에 따르면 7월 16일 투하쳅스키는 당중앙위원회에 「반란은 청산되었고 소비에트 권력이 모든 곳에서 회복되었다」고 보고했다.',
          en: 'In summer 1921 the main Tambov rebel forces collapsed. In early July the leadership ordered combat units to split into small groups and either hide in the forests and fight as guerrillas or go home, and guerrilla fighting went on until August. According to English-language sources the rebels were down to about 1,000 by September; the same sources also say no more than 4,000 were still fighting at the end of the year, so the figures conflict, but with almost all their leaders dead the last groups lived on the run in swamps and forests. Boguslavsky of the 1st Insurgent Army was also killed in action. Scattered clashes continued until summer 1922 before dying away. On 24 June 1922 Antonov and his brother Dmitry were surrounded by a Cheka detachment in the village of Nizhny Shibryai near Borisoglebsk. When the detachment set fire to the house where they were hiding, the brothers tried to break out and were shot down; documents say Antonov fought to the end without laying down his weapon. They were buried on the fifth day near the walls of the Kazan Mother of God monastery in Tambov. According to Russian-language sources, on 16 July Tukhachevsky reported to the Central Committee: "The mutiny has been liquidated, Soviet power has been restored everywhere."',
          sources: [S.tambru, S.tamb, S.antonov],
        },
        {
          ko: '서시베리아에서는 2월 12일 시베리아 혁명위원회 의장 이반 스미르노프, 시베리아 담당 총사령관 보좌 바실리 쇼린, 시베리아 체카 의장 이반 파블루놉스키로 이루어진 전권 「트로이카」가 진압을 맡았다. 같은 날 시베리아 혁명위원회 명령은 철도변 마을 주민에게 철도 보존의 책임을 지우고, 그 가운데서 잡은 인질을 봉기군이 나타나면 총살하도록 했다. 철로가 훼손되면 반경 10베르스타 안의 마을을 모두 불태웠다는 기록도 있다. 스미르노프는 3월 중순 붉은 군대와 봉기군의 손실이 1 대 15라고 했고, 싸움이 시작된 지 한 달 반이 안 되는 사이 이심군에서 약 7천 명, 페트로파블롭스크군에서 1만 5천 명의 농민이 죽었다고 집계했다. 붉은 군대는 장갑열차와 포병을 앞세워 철도를 따라 반격했다. 2월 24일 북부 간선에서 마주 오던 부대가 바가이역에서 만났고, 3월 4일 옴스크-첼랴빈스크 노선이 뚫렸다. 그 결과 2만 명이 넘는 이심-페트로파블롭스크 집단이 포위되었고, 내분 속에 총사령관 로딘이 죽었다. 콕체타프 방면으로 밀려난 카자크 부대 약 2천 명은 5월 중순 중국으로 넘어갔다.',
          en: 'In Western Siberia a plenipotentiary "troika" formed on 12 February, made up of Siberian Revolutionary Committee chairman Ivan Smirnov, assistant commander-in-chief for Siberia Vasily Shorin and Siberian Cheka chief Ivan Pavlunovsky, took charge of the suppression. An order of the Siberian Revolutionary Committee the same day made villagers along the railways responsible for its safety and had hostages taken from among them, to be shot if rebel bands appeared. Records say that whenever the track was damaged, every village within ten versts was burned. Smirnov put Red Army and rebel losses at 1 to 15 in mid-March, and counted about 7,000 peasants killed in Ishim district and 15,000 in Petropavlovsk district in less than the first month and a half of fighting. The Red Army counter-attacked along the railways behind armoured trains and artillery. On 24 February units advancing toward each other along the northern line met at Vagai station, and on 4 March the Omsk–Chelyabinsk line was cleared. More than 20,000 rebels of the Ishim–Petropavlovsk grouping were encircled, and commander-in-chief Rodin was killed amid infighting. Some 2,000 Cossacks driven toward Kokchetav crossed into China in mid-May.',
          sources: [S.wsibru, S.wsib],
        },
        {
          ko: '북쪽의 봉기군은 봄까지 버텼다. 4월 7일 붉은 군대가 봉기군의 수도 격이던 토볼스크를 공격해 이튿날 점령했고, 봉기군 5천 명이 포로가 되었다. 4월 28일 옙시노와 5월 1일 아로마셰보의 야간 전투에서 약 1만 명이 모인 이심군 북부의 봉기군은 죽거나 다치거나 강에 빠진 사람이 약 700명, 포로가 약 5,700명에 이르는 큰 손실을 입었다. 5월 11일에는 플라톤 로파레프가 이끈 40명의 상륙대가 1천 킬로미터를 행군해 사마로보를 기습했고, 5월 16일 그 근처 전투에서 「인민군」 사령관 바실리 젤톱스키가 죽었다. 5월 말 베료조보와 수르구트가, 6월 2일 오브도르스크가 되찾아졌다. 그 뒤 봉기군은 유격전으로 돌아섰다. 8월 초 표트르 셰브첸코의 「제1해방연대」가 다시 아로마셰보 일대를 차지했지만 8월 25일 기습을 받아 셰브첸코와 111명이 칼에 베여 죽었다. 1921년 여름부터 이심군에는 기근과 콜레라가 닥쳐 불완전한 공식 통계로도 8,159명이 굶어 죽었다. 마지막 거점은 1922년 말에야 사라졌고, 12월 보고서는 「비적 행위」가 거의 사라졌다고 적었다.',
          en: 'The northern rebels held out into spring. On 7 April the Red Army stormed Tobolsk, the insurgents\' de facto capital, taking it the next day and capturing 5,000 rebels. In night battles at Yevsino on 28 April and Aromashevo on 1 May the northern Ishim rebels, about 10,000 strong, lost some 700 killed, wounded or drowned and about 5,700 taken prisoner. On 11 May a landing party of 40 men under Platon Loparev, after a march of a thousand kilometres, surprised Samarovo, and on 16 May the "People\'s Army" commander Vasily Zheltovsky was killed in fighting nearby. Beryozovo and Surgut were retaken at the end of May and Obdorsk on 2 June. The rebels then turned to guerrilla warfare. In early August Pyotr Shevchenko\'s "1st Liberation Regiment" again occupied the Aromashevo area, but on 25 August it was surprised and Shevchenko and 111 of his men were cut down. From summer 1921 famine and cholera struck Ishim district, where incomplete official figures counted 8,159 deaths from hunger. The last centres of resistance disappeared only at the end of 1922, when a December report stated that "banditry" had all but disappeared.',
          sources: [S.wsibru, S.wsib],
        },
      ],
    },
    {
      heading: { ko: '「쿨라크·사회혁명당 반란」인가 「농민 전쟁」인가 {russia}', en: '"Kulak-SR mutiny" or "peasant war"? {russia}' },
      paragraphs: [
        {
          ko: '소련 역사학은 탐보프 봉기를 「안토놉시나」, 「안토노프 반란」, 때로는 「탐보프 작전」이라고 불렀다. 1923년 탐보프 주당위원회 출판사가 낸 자료집의 부제는 「탐보프주의 사회혁명당 비적 행위의 역사」였고, 명령 제171호도 「사회혁명당 비적의 뿌리」를 겨냥했다. 공식 선전은 봉기를 「사회혁명당과 장교들의 봉기」로 불러 징발이라는 실제 원인을 가렸고, 볼셰비키는 녹색군을 백군의 한 갈래로 그리며 쿨라크의 영향을 부풀렸다. 알타이 소로키노 봉기의 공식 이름도 「소로키노 쿨라크 반란」이었다. 영어 출처에 따르면 소련은 이 운동을 같은 시기 볼셰비키에 맞선 다른 좌파 운동처럼 무정부적 비적 떼로 그렸다. 진압을 지휘한 투하쳅스키는 1926년 「반혁명 봉기와의 투쟁」이라는 글로 경험을 정리했고, 미하일 프룬제는 정규군에 맞선 유격대의 저항에 깊은 인상을 받아 유격 전술을 연구했다. 러시아어 출처에 따르면 역사가 바실리 츠베트코프는 1919년 남러시아 백군이 안토노프와 접촉하려다 실패한 밀사 파견 기록을 근거로 백군 지휘부가 봉기 조직에 관여했다고 주장한다. 니콜라이 비르타의 소설 『고독』은 1941년 스탈린상을 받았다.',
          en: 'Soviet historiography called the Tambov rising the "Antonovshchina", the "Antonov mutiny" or sometimes the "Tambov operation". A 1923 collection published by the Tambov provincial party committee was subtitled "materials on the history of SR banditry in Tambov province", and Order No. 171 likewise targeted "the SR-bandit roots". Official propaganda called the revolts "risings of SRs and officers", hiding their real cause in requisitioning, and the Bolsheviks portrayed the Greens as a branch of the Whites and exaggerated the role of kulaks. The Sorokino rising in the Altai was officially named the "Kulak Rebellion of Sorokino". According to English-language sources, the Soviets portrayed the movement as anarchic banditry, like other left-wing movements opposing them in the period. Tukhachevsky, who directed the suppression, summed up his experience in a 1926 article, "The Struggle against Counter-revolutionary Risings", and Mikhail Frunze, impressed by the guerrillas\' resistance to regular forces, began studying guerrilla tactics. According to Russian-language sources, the historian Vasily Tsvetkov argues from records of a failed 1919 mission by the White command in South Russia to contact Antonov that the White command was complicit in organising the rising. Nikolai Virta\'s novel Loneliness won a Stalin Prize in 1941.',
          sources: [S.tambru, S.green, S.sorokino, S.tamb],
        },
        {
          ko: '소련 붕괴 뒤 문서고가 열리면서 서술의 중심은 농민 자신과 탄압으로 옮겨 갔다. 1994년 빅토르 다닐로프와 테오도어 샤닌이 편집한 문서집 『탐보프주의 농민 봉기』가 나왔고, 2007년 탐보프 국립문서보관소는 800쪽 분량의 문서·회고록 모음을 펴냈다. 미국 역사가 에릭 랜디스의 2008년 연구서 『비적과 파르티잔』은 제목 자체가 두 시각을 나란히 놓는다. 러시아 역사가 P. F. 알료시킨과 Yu. A. 바실리예프는 1918~1922년의 봉기 전체를 「전시 공산주의 정책 아래의 농민 전쟁」, 「공산주의자에 맞서 소비에트를 위한 농민 전쟁」으로 묶어 연구했다. 보리스 센니코프는 1918~1921년 탐보프 봉기를 1929~1933년의 「탈농민화」와 이어 읽었고, 2011년 BBC 러시아어 방송은 「러시아의 방데: 정치적 보복인가 제노사이드인가」라는 물음을 다루었다. 화학 무기를 두고는 보브코프가 2011년 「허구와 사실」을 가르려 했다. 1996년 보리스 옐친의 대통령령은 차파니 전쟁과 1921년 추바시 봉기의 참가자들을 복권했고, 2007년 탐보프에는 1921년의 비극에 휘말린 모든 농민에게 바친 「탐보프 농부」 기념비가 섰다.',
          en: 'After the Soviet collapse, opened archives shifted the focus to the peasants themselves and to the repression. In 1994 a document collection, The Peasant Uprising in Tambov Province, appeared under the editorship of Viktor Danilov and Teodor Shanin, and in 2007 the Tambov State Archive published an 800-page volume of documents and memoirs. The title of the American historian Erik Landis\'s 2008 study, Bandits and Partisans, itself sets the two perspectives side by side. The Russian historians P. F. Aleshkin and Yu. A. Vasiliev have studied the risings of 1918–22 as a whole as "a peasant war under the policy of war communism" and "a peasant war for the Soviets against the Communists". Boris Sennikov read the Tambov rising of 1918–21 together with the "de-peasantisation" of 1929–33, and in 2011 the BBC Russian Service took up the question "The Russian Vendée: political reprisal or genocide?". On chemical weapons, Bobkov sought in 2011 to separate "fictions and facts". A 1996 decree of President Boris Yeltsin rehabilitated participants in the Chapan War and the 1921 Chuvash rising, and in 2007 a monument to the "Tambov Muzhik", dedicated to all the peasants caught up in the tragic events of 1921, was unveiled in Tambov.',
          sources: [S.tambru, S.chapan],
        },
        {
          ko: '봉기가 네프에 얼마나 영향을 주었는지도 논쟁거리다. 봉기를 직접 겪은 러시아 사회학자 피티림 소로킨은 봉기군이 자기 행동으로 네프를 강요했다고 결론지었고, 러시아어 출처는 탐보프 봉기가 크론시타트 봉기처럼 전시 공산주의를 버리고 네프로 넘어가는 결정에 크게 기여했다고 쓴다. 서시베리아 봉기에 관한 러시아어 출처도 이 봉기를 3월 21일 전환의 원인 가운데 하나로 꼽는다. 그러나 녹색군에 관한 영어 출처는 녹색군이 정책 변화에 기여한 것은 분명하지만 그 영향의 크기는 논쟁의 여지가 있다고 보며, 오히려 네프와 비가 농촌 사정을 나아지게 해 봉기의 기반인 농민의 불만을 꺼뜨렸다는 점이 덜 논쟁적이라고 쓴다. 같은 출처는 무자비한 테러도 한몫했지만 봉기를 끝낸 가장 큰 무기는 1921~1922년의 기근이었다고 본다. 탐보프에서는 현물세와 체카의 활동, 그리고 당에 들어가 혜택을 얻은 수천 명의 지역 주민이 함께 1921년 봄 상황을 누그러뜨렸다. 마을의 저항이 정책을 바꾸게 했는지, 아니면 이미 준비되던 전환이 봉기를 꺼뜨렸는지를 두고 출처들은 서로 다른 무게를 둔다.',
          en: 'How far the risings shaped the NEP is also debated. The Russian sociologist Pitirim Sorokin, a contemporary witness, concluded that the insurgents had forced the NEP through their actions, and Russian-language sources write that the Tambov rising, like Kronstadt, contributed greatly to the decision to abandon war communism for the NEP. Russian-language sources on the West Siberian rising likewise count it among the causes of the 21 March change. The English-language source on the Green armies, however, holds that while the Greens certainly contributed to the policy change, the extent of their influence is open to debate; it considers far less contestable that the NEP, together with better rainfall, improved rural conditions and so removed the peasant discontent on which the risings drew. The same source argues that ruthless terror played its part but that the main weapon in ending the risings was the famine of 1921–22. In Tambov, the tax in kind, the Cheka\'s work and the enrolment of thousands of locals in the party, with the benefits that brought, together defused the situation in spring 1921. The sources weigh differently whether village resistance forced the policy change or a change already in preparation extinguished the risings.',
          sources: [S.tamb, S.tambru, S.wsibru, S.green],
        },
      ],
    },
  ],

  timeline: [
    ['1918.06.11', '빈농위원회 설치 지시', 'Committees of Poor Peasants ordered', '전러시아중앙집행위원회가 마을 안의 잉여 곡물을 찾아 몰수하도록 빈농위원회를 세우게 했다. 12월 2일 마을 소비에트에 통합되었다.', 'The All-Russian Central Executive Committee ordered kombedy set up to find and seize surplus grain inside villages. They were merged into village soviets on 2 December.', 'russia'],
    ['1919.01.11', '프로드라즈뵤르스트카 전국 도입', 'Prodrazverstka introduced nationwide', '소브나르콤 법령으로 주별 할당을 농가까지 쪼개 내리는 식량 할당 징발이 소비에트 러시아 전역에 도입되었다.', 'A Sovnarkom decree introduced compulsory food apportionment, broken down from provinces to households, across Soviet Russia.', 'russia'],
    ['1919.03.03', '차파니 전쟁 시작', 'Chapan War begins', '사마라주 노보데비치예 주민이 징발 부대를 무장 해제했다. 봉기는 볼가 중류로 번졌다가 4월 중순 진압되었다.', 'Villagers of Novodevichye in Samara province disarmed a requisition squad; the revolt spread along the middle Volga and was crushed by mid-April.', 'russia', P(53.6072, 48.8386, '노보데비치예', 'Novodevichye')],
    ['1920.02.07', '검은 독수리(쇠스랑) 봉기', 'Black Eagle (Pitchfork) Uprising', '우파주 노바야옐란 주민이 인질을 풀어 주며 식량 부대와 충돌했다. 약 5만 명으로 커진 봉기는 3월 중순 진압되었다.', 'Villagers of Novaya Yelan in Ufa province clashed with a food detachment while freeing hostages; the rising grew to some 50,000 and was crushed by mid-March.', 'russia'],
    ['1920.07.14', '사포시코프의 「진리의 군대」', 'Sapozhkov\'s "Army of Truth"', '해임된 제9기병사단장 알렉산드르 사포시코프가 사단을 「제1 진리의 붉은 군대」로 바꾸고 부줄루크를 점령했다. 그는 9월 6일 사살되었다.', 'Dismissed 9th Cavalry Division commander Alexander Sapozhkov renamed his division the "1st Red Army of Truth" and took Buzuluk; he was killed on 6 September.', 'russia', P(52.7667, 52.2667, '부줄루크', 'Buzuluk')],
    ['1920.08.15–08.19', '탐보프 봉기 시작', 'Tambov rising begins', '히트로보에서 식량 부대를 무장 해제한 데 이어(영어 출처는 19일) 8월 19일 여러 마을이 곡물 납부를 거부하고 유격군으로 뭉쳤다.', 'After a food detachment was disarmed at Khitrovo (dated the 19th in English-language sources), several villages refused grain deliveries on 19 August and merged into a partisan army.', 'russia', P(52.7167, 41.4333, '탐보프', 'Tambov')],
    ['1920.11.14', '탐보프 연합 파르티잔 군', 'United Partisan Army of Tambov', '봉기군이 표트르 토크마코프를 사령관으로 3개 군의 연합군을 만들었다. 12월 근로농민동맹이 선언을 냈다.', 'The rebels formed a united army of three armies under Pyotr Tokmakov; in December the Union of Working Peasants issued its manifesto.', 'russia'],
    ['1921.01.31', '서시베리아 봉기 시작', 'West Siberian rising begins', '이심군 첼노콥스코예와 추르탄에서 종자 반출을 막으려던 농민이 징발원들을 쫓아냈다. 사흘 만에 이심군 북부가 봉기했다.', 'Peasants trying to stop seed grain being removed drove out requisitioners at Chelnokovskoye and Churtan in Ishim district; within three days northern Ishim district had risen.', 'russia', P(56.1167, 69.5, '이심', 'Ishim')],
    ['1921.02.06', '전권위원회 파견', 'Plenipotentiary Commission sent', '전러시아중앙집행위원회가 안토노프-옵세옌코를 위원장으로 하는 전권위원회를 탐보프에 보냈다.', 'The All-Russian Central Executive Committee sent a Plenipotentiary Commission under Antonov-Ovseenko to Tambov.', 'russia'],
    ['1921.02.12', '탐보프 징발 중단', 'Requisitioning halted in Tambov', '러시아어 출처에 따르면 식량인민위원부 결정으로 탐보프주의 할당 징발 집행이 멈추었다.', 'According to Russian-language sources, the Food Commissariat halted the collection of the apportionment in Tambov province.', 'russia'],
    ['1921.02.21', '봉기군의 토볼스크 점령', 'Rebels take Tobolsk', '서시베리아 봉기군이 토볼스크를 차지했다. 2월 시베리아 횡단 철도 두 노선이 3주 동안 마비되었다.', 'West Siberian rebels took Tobolsk; in February both lines of the Trans-Siberian Railway were paralysed for three weeks.', 'russia', P(58.1953, 68.2581, '토볼스크', 'Tobolsk')],
    ['1921.03.08–03.16', '제10차 당대회', '10th Party Congress', '현물세 도입과 신경제정책이 결정되었다. 레닌은 농민 반혁명이 백군 장군들을 합친 것보다 더 위험하다고 말했다.', 'The congress decided on the tax in kind and the New Economic Policy; Lenin said the peasant counter-revolution was more dangerous than the White generals combined.', 'russia'],
    ['1921.03.21', '현물세 법령', 'Tax-in-kind decree', '전러시아중앙집행위원회가 할당 징발을 현물세로 바꾸는 법령을 공포했다.', 'The All-Russian Central Executive Committee decreed the replacement of apportionment by a tax in kind.', 'russia'],
    ['1921.04.11', '라스카조보 습격', 'Raid on Rasskazovo', '안토노프가 5천 명으로 라스카조보 수비대를 무너뜨리고 붉은 군대 대대 하나를 포로로 잡았다.', 'Antonov overran the Rasskazovo garrison with 5,000 men and captured an entire Red Army battalion.', 'russia', P(52.6667, 41.8833, '라스카조보', 'Rasskazovo')],
    ['1921.04.27', '투하쳅스키 임명', 'Tukhachevsky appointed', '정치국이 투하쳅스키를 탐보프주 군 사령관, 우보레비치를 부사령관으로 임명했다.', 'The Politburo appointed Tukhachevsky commander of the forces in Tambov province, with Uborevich as deputy.', 'russia'],
    ['1921.04.28–05.01', '옙시노·아로마셰보 전투', 'Battles of Yevsino and Aromashevo', '이심군 북부 봉기군이 약 700명의 사상자와 약 5,700명의 포로를 내고 무너졌다.', 'The northern Ishim rebels collapsed, losing some 700 killed, wounded or drowned and about 5,700 prisoners.', 'russia', P(56.8623, 68.6427, '아로마셰보', 'Aromashevo')],
    ['1921.05.28–06.07', '인자비노 일대 전투', 'Battles around Inzhavino', '우보레비치가 지휘한 기병 부대들이 안토노프의 제2봉기군을 격파했다.', 'Cavalry under Uborevich\'s command destroyed Antonov\'s 2nd Insurgent Army.', 'russia', P(52.3241, 42.4864, '인자비노', 'Inzhavino')],
    ['1921.06.11', '명령 제171호', 'Order No. 171', '전권위원회가 재판 없는 총살, 인질 총살, 가족 추방과 재산 몰수를 명령했다.', 'The Plenipotentiary Commission ordered shooting without trial, execution of hostages, and deportation and confiscation for families.', 'russia'],
    ['1921.06.12', '독가스 사용 명령', 'Poison-gas order', '투하쳅스키가 명령 제0116호로 숲에 숨은 봉기군을 독가스로 「청소」하라고 명령했다.', 'In Order No. 0116 Tukhachevsky ordered the forests where rebels were hiding to be "cleared" with poison gas.', 'russia'],
    ['1921.07.13', '화학탄 사용 기록', 'Chemical shells recorded', '한 포병대가 전투에서 화학 유탄 47발을 쏜 기록이 남았다. 8월 3일 키페츠 호수의 섬에도 59발이 쓰였다.', 'An artillery battalion recorded firing 47 chemical shells in battle; another 59 were fired at an island in Lake Kipets on 3 August.', 'russia'],
    ['1922.06.24', '안토노프 형제의 죽음', 'Death of the Antonov brothers', '니즈니시브랴이 마을에서 체카 부대에 포위된 안토노프와 동생 드미트리가 불붙은 집을 빠져나오다 사살되었다.', 'Surrounded by a Cheka detachment in Nizhny Shibryai, Antonov and his brother Dmitry were shot while breaking out of a burning house.', 'russia'],
    ['1922.12', '서시베리아 봉기의 끝', 'End of the West Siberian rising', '마지막 거점이 진압되고, 12월 보고서는 「비적 행위」가 거의 사라졌다고 적었다.', 'The last centres were crushed, and a December report stated that "banditry" had all but disappeared.', 'russia'],
  ],

  people: [
    ['alexander-antonov', 'leader', '탐보프 봉기 지도자', 'Leader of the Tambov rising', '사회혁명당 출신 전 키르사노프 민경대장으로 1920년 탐보프 봉기를 이끌어 봉기에 이름을 남겼고, 1922년 6월 24일 체카 부대에 사살되었다.', 'A former SR and Kirsanov militia chief, led the 1920 Tambov rising that bears his name and was shot by a Cheka detachment on 24 June 1922.', 'peasant-insurgents'],
    ['pyotr-tokmakov', 'leader', '연합 파르티잔 군 사령관', 'Commander of the United Partisan Army', '러시아어 출처에 따르면 탐보프 연합 파르티잔 군 사령관이자 근로농민동맹 의장이었다. 1921년 2월 28일 전사했다는 기록과 6월에 죽었다는 기록이 엇갈린다.', 'According to Russian-language sources, commanded the United Partisan Army of Tambov and chaired the Union of Working Peasants; accounts place his death on 28 February 1921 or in June.', 'peasant-insurgents'],
    ['alexander-sapozhkov', 'leader', '「진리의 군대」 지도자', 'Leader of the "Army of Truth"', '붉은 군대 제9기병사단장으로 1920년 7월 징발 폐지와 자유 거래를 내걸고 봉기했다가 9월 6일 사살되었다.', 'As commander of the Red Army\'s 9th Cavalry Division, rose in July 1920 demanding an end to requisitions and free trade, and was killed on 6 September.', 'peasant-insurgents'],
    ['lenin', 'leader', '소브나르콤 의장', 'Chairman of the Sovnarkom', '1920년 10월 탐보프 봉기의 격파를 서두르라고 지시했고, 1921년 3월 제10차 당대회에서 네프를 꺼내며 농민 반혁명을 백군보다 더 위험하다고 말했다.', 'Ordered the destruction of the Tambov rising sped up in October 1920, and in March 1921 introduced the NEP at the 10th Congress, calling the peasant counter-revolution more dangerous than the Whites.', 'soviet-forces'],
    ['antonov-ovseenko', 'executor', '탐보프 전권위원회 위원장', 'Chairman of the Tambov Plenipotentiary Commission', '1921년 2월부터 진압의 최고 기관인 전권위원회를 이끌었고, 인질 총살과 가족 추방을 명한 명령 제171호에 서명했다.', 'From February 1921 chaired the Plenipotentiary Commission that directed the suppression, and signed Order No. 171 ordering hostage shootings and family deportations.', 'soviet-forces'],
    ['tukhachevsky', 'executor', '탐보프주 군 사령관', 'Commander of forces in Tambov province', '1921년 4월 진압군 사령관이 되어 명령 제171호에 서명하고, 6월 12일 숲에 독가스를 쓰라는 명령 제0116호를 내렸다.', 'Took command of the suppression in April 1921, co-signed Order No. 171 and on 12 June issued Order No. 0116 to use poison gas in the forests.', 'soviet-forces'],
    ['ieronim-uborevich', 'executor', '탐보프 진압군 부사령관', 'Deputy commander in Tambov', '1921년 5~6월 인자비노·카멘카 일대에서 기병 부대들을 지휘해 안토노프의 제2봉기군을 격파했다.', 'In May–June 1921 commanded the cavalry that destroyed Antonov\'s 2nd Insurgent Army around Inzhavino and Kamenka.', 'soviet-forces'],
    ['grigory-kotovsky', 'participant', '독립 기병여단장', 'Commander of a separate cavalry brigade', '1921년 5월 25일 셀랸스키의 봉기군 2개 연대를 격파하고 인자비노 일대 전투에 참가했다.', 'Routed two rebel regiments under Selyansky on 25 May 1921 and fought in the battles around Inzhavino.', 'soviet-forces'],
    ['ivan-fedko', 'participant', '장갑차 부대 지휘관', 'Armoured-car commander', '1921년 5월 31일 장갑차 7대로 드베 세스트리치 마을의 봉기군 3천 명을 기습했다.', 'With seven armoured cars, surprised 3,000 rebels at Dve Sestritsy on 31 May 1921.', 'soviet-forces'],
    ['yagoda', 'participant', '전러시아 체카 간부', 'Senior Cheka official', '1921년 봄 진압을 위해 전러시아 체카에서 탐보프로 파견되었다.', 'Was sent from the All-Russian Cheka to Tambov in spring 1921 for the suppression.', 'soviet-forces'],
    ['dzerzhinsky', 'participant', '전러시아 체카 의장', 'Chairman of the All-Russian Cheka', '1920년 10월 레닌에게서 「안토놉시나」 격파를 서두르라는 지시를 받았고 1921년 1월 조직국 회의에서 진압을 논의했다.', 'Was instructed by Lenin in October 1920 to speed up the destruction of the "Antonovshchina", and discussed the campaign at the Orgburo in January 1921.', 'soviet-forces'],
    ['alexander-shlikhter', 'participant', '탐보프주 집행위원회 의장', 'Chairman of the Tambov provincial executive committee', '1920년 가뭄에도 곡물 징발을 밀어붙였고, 8월 31일 토벌대를 이끌다 패해 해임되었다.', 'Pressed grain collection despite the 1920 drought, and was removed after his punitive detachment was defeated on 31 August.', 'soviet-forces'],
    ['alexander-tsyurupa', 'participant', '식량인민위원', 'People\'s Commissar for Food', '1918년부터 도시에서 무장 식량 부대 수십 개를 조직해 농촌의 곡물 징발에 보냈다.', 'From 1918 organised dozens of armed food detachments in the towns and sent them to requisition grain in the countryside.', 'soviet-forces'],
    ['bukharin', 'participant', '볼셰비키 지도자', 'Bolshevik leader', '영어 출처에 따르면 탐보프 주민을 끌어오기 위한 「비강제적 조치」를 맡아 할당량 인하를 권고했다.', 'According to English-language sources, was tasked with "non-coercive measures" to win over Tambov\'s population and recommended lower quotas.', 'soviet-forces'],
    ['osinsky', 'participant', '농업 정책 담당', 'Agrarian policy official', '1921년 2월 8일 정치국에서 파종 운동과 농민의 상태를 보고해 현물세 전환 논의를 열었다.', 'His report to the Politburo on 8 February 1921 on the sowing campaign and the peasantry opened the discussion of the tax in kind.', 'soviet-forces'],
    ['trotsky', 'participant', '군사인민위원', 'People\'s Commissar for War', '제10차 당대회에서 전시 공산주의가 군사적 필요가 강요한 것이었다고 설명하며 네프를 개관했고, 사포시코프 봉기 진압 조치에도 관여했다.', 'Outlined the NEP at the 10th Congress, describing war communism as dictated by military needs, and had a hand in measures against Sapozhkov\'s revolt.', 'soviet-forces'],
    ['frunze', 'participant', '붉은 군대 지휘관', 'Red Army commander', '1919년 3월 약 1만 3천 명을 이끌고 차파니 전쟁을 진압했고, 뒤에 농민 유격대의 저항에서 유격 전술을 연구했다.', 'Led some 13,000 troops to crush the Chapan War in March 1919, and later studied guerrilla tactics from the peasant insurgents\' resistance.', 'soviet-forces'],
    ['ivan-smirnov', 'executor', '시베리아 혁명위원회 의장', 'Chairman of the Siberian Revolutionary Committee', '1921년 2월 서시베리아 봉기 진압 「트로이카」를 이끌었고, 이심·페트로파블롭스크군에서 죽은 농민 수를 집계했다.', 'Headed the troika that suppressed the West Siberian rising from February 1921 and reported the numbers of peasants killed in Ishim and Petropavlovsk districts.', 'soviet-forces'],
  ],

  notes: [
    '인물 카드: 탐보프 지도자는 기존 카드 alexander-antonov(알렉산드르 안토노프, 1889–1922)가 바로 이 사람이므로 새 카드가 필요 없다(브리프의 alexander-antonov-rebel 대신 기존 id 사용). 새 카드는 pyotr-tokmakov, alexander-sapozhkov 두 명.',
    '표기: 사포시코프는 지시받은 표기. 국립국어원 러시아어 표기(ж가 무성 자음 앞에서 「시」, 예: 메레시콥스키)를 따르면 「사포시코프」가 된다. 토크마코프는 규정과 일치. 지명 니즈니시브랴이(Нижний Шибряй), 키페츠(Кипец), 셴댜핀(Шендяпин)은 직접 옮긴 것.',
    '엇갈린 날짜·수치:',
    '- 탐보프 봉기 시작: ru는 8월 15일 히트로보(식량 부대 무장 해제), 19일 카멘카·투골루코보 등과 아파나시옙카의 통합. en은 히트로보 봉기를 8월 19일로 씀. 본문·연표에 둘 다 밝힘.',
    '- 탐보프 징발 중단: en은 2월 2일 발표·9일부터 탐보프에 유포, ru는 2월 12일 식량인민위원부 결정. 둘 다 씀.',
    '- 토크마코프의 죽음: ru 인물 문서는 1921년 2월 28일 보고슬롭카 근처, en Tambov Rebellion은 6월 보구슬랍스키 전사 뒤 「같은 운명」. 그런데 ru 탐보프 문서는 5월 20일 공화국 선포를 「토크마코프와 주민」이 했다고 써서 ru 인물 문서와 모순. 본문은 공화국 선포를 「근로농민동맹·주민 집회」로 쓰고 토크마코프 사망은 두 설을 병기.',
    '- 탐보프 지도 구조: ru는 토크마코프가 연합군 사령관·근로농민동맹 의장, 안토노프는 제2봉기군 참모장. en·소련 명칭은 안토노프를 지도자로. 본문은 두 시각을 병기.',
    '- 봉기군 규모: ru 1921년 1~2월 약 5만 명(2개 군), 1920년 10월 15일 최대 2만 명. en 14,000 또는 18,000(초기), 최대 5만, 1921년 2월 2만~4만, 21개 연대 또는 18~20개 연대. ru 연합군은 1920년 11월 3개 군으로 시작.',
    '- 진압군 규모: ru 5월 말 4만 3천, 전체 최대 5만 5천. en 10만 명(리드) 또는 5만~10만.',
    '- 탄압 피해: en 체포 약 10만·사망 약 1만 5천, 수용 5만~10만(어린이 약 1천), 투항자 약 6천 총살·추방. ru 칸토르 3만~5만 명 탄압, 인구 감소 약 24만(연구자·향토사가; en Russian Civil War는 센니코프 추정으로 소개).',
    '- 독가스: ru는 「클로로피크린」 포탄과 함께 「염소 E56」도 언급. 문서로 확인된 사용 3건(그중 수치는 7월 13일 47발, 8월 3일 59발 두 건만). 사상자 기록 없음(보브코프). en은 리드에서 「1921년 여름 화학무기를 써서 주력을 괴멸」이라고 써 효과를 크게 봄. 본문은 ru의 논쟁 구도를 따랐고 en 리드의 단정은 쓰지 않음.',
    '- 서시베리아 봉기 기간: ru 리드는 1921년 1월 31일~8월, 본문은 1922년 말까지 마지막 거점. en은 1921년 초~1922년 말. 규모 ru 4월 10만 이상·문헌 3만~15만, en 5만 5천~6만(가장 그럴듯)·슐퍄코프 7만~10만.',
    '- 서시베리아 도시 점령일: ru 같은 문서 안에서 콕체타프 2월 21일/23일, 수르구트 3월 9일/10일로 엇갈림. 목록 쪽(2월 21일, 3월 10일)을 씀. en은 점령 도시 목록에 이심·바라빈스크·카인스크도 넣음(ru는 이심을 「여러 번 주인이 바뀐 곳」으로만 씀) — 본문에 이심 점령은 쓰지 않음.',
    '- 쇠스랑 봉기: ru 2월 4일 인질, 7일 충돌. en 첫 충돌 2월 4일(마을 이름 Yanga Yelan = 노바야옐란).',
    '- 카멘카 6월 1~9일 전투(en)와 인자비노 5월 28일~6월 7일 전투(ru)는 같은 작전의 다른 서술일 가능성이 큼. 둘 다 출처를 밝혀 씀.',
    '- 투하쳅스키의 1922년 7월 16일 보고는 ru에만 있음.',
    '- 1921년 잔존 봉기군: en 안에서 9월 약 1천 명, 연말 4천 명 이하로 엇갈림. 둘 다 씀.',
    '- 사포시코프: ru 인물 문서는 좌파 사회혁명당원, ru 봉기 문서 리드는 「아나키스트」. 본문은 좌파 사회혁명당원으로만 씀.',
    '- 탐보프 공화국의 깃발: en 안에서 「혁명 전 국기」와 「붉은 깃발」이 함께 나옴. 본문에 둘 다 밝힘.',
    '- 1996년 옐친 대통령령 복권: en Chapan rebellion 문서의 서술(「these revolts」)이라 본문은 차파니·추바시 봉기 참가자로 한정. 탐보프 참가자에 대한 복권 여부는 확인 못 함.',
    '확인 못 해 뺀 것: 빅토르 체르노프·칼리닌의 역할(받은 출처에 없음), 체카의 1921년 2월 118건 집계(상위 사건 본문에만 있고 받은 출처에 없음), 트로츠키의 1920년 2월 현물세 제안(볼가 기근 본문에만 있음), 그라치오시의 「농민 대전쟁」론(출처 미확보 — 「농민 전쟁」론은 알료시킨·바실리예프 저작으로 대신).',
    '링크 위험: 「안토노프」는 안토노프-옵세옌코·알렉세이 안토노프·올레크 안토노프와 혼동될 수 있음(본문은 첫 등장 시 「알렉산드르 안토노프」 전체 이름). 「임시 민주 공화국」 등 일반어 링크 여부 확인 필요. 「제2봉기군」 등 군 명칭은 일반어.',
    '진영 배정: 피티림 소로킨(기존 카드)은 본문에만 등장하고 진영이 맞지 않아 인물 행에서 뺐다.',
  ],
};
