// Glossary terms for the peasant-uprisings-1920-1922 event (2026-10-04).
// Built with lib.js term(); see BRIEF2.md/BRIEF3.md for sources and spelling rules.
//
// Original (Russian) names:
//   union-of-working-peasantry   Союз трудового крестьянства (СТК)
//   west-siberian-uprising-1921  Западно-Сибирское восстание (1921—1922)
//   chapan-war                   Чапанная война (чапанка, чапанное восстание)
//   tambov-order-171             Приказ Полномочной комиссии ВЦИК № 171 «О начале проведения
//                                репрессивных мер против отдельных бандитов и укрывающих их семей»
//   green-armies                 Зелёные (Зелёная армия, зеленоармейцы)
//
// Not made (already in terms-snapshot): antonovshchina 안토놉시나 (the Tambov rising
// itself, alias 탐보프 봉기), prodrazvyorstka, prodnalog, prodotryad,
// kombedy-committees-of-the-poor, food-dictatorship.
const { term } = require('../lib');

const E = t => 'https://en.wikipedia.org/wiki/' + encodeURI(t);
const RU = t => 'https://ru.wikipedia.org/wiki/' + encodeURI(t);
const S = {
    tambEn: E('Tambov_Rebellion'),
    tambRu: RU('Тамбовское_восстание'),
    tokm: RU('Токмаков,_Пётр_Михайлович'),
    wsibEn: E('West_Siberian_rebellion'),
    wsibRu: RU('Западно-Сибирское_восстание_(1921—1922)'),
    chapanEn: E('Chapan_rebellion'),
    chapanRu: RU('Чапанная_война'),
    green: E('Green_armies'),
};

module.exports = [
    term({
        id: 'union-of-working-peasantry', ko: '근로농민동맹 (탐보프)', en: 'Union of Working Peasantry (Tambov)', category: 'factions', period: '1920–1921', startYear: 1920, endYear: 1921,
        definition: ['1920~1921년 탐보프 봉기 때 봉기군이 살아남은 사회혁명당 조직을 바탕으로 세운 정치 조직. 볼셰비키 독재 타도와 제헌의회 소집, 정치적·경제적 자유의 회복을 내걸었고, 1921년 5월 「탐보프 파르티잔 지구 임시 민주 공화국」을 선포했다. 러시아어 출처는 탐보프 연합 파르티잔 군 사령관 표트르 토크마코프를 의장으로, 영어 출처는 알렉산드르 안토노프를 지도자로 적는다.',
            'The political organisation of the Tambov insurgents of 1920–1921, built on the surviving Socialist Revolutionary organisations. It called for the overthrow of the Bolshevik dictatorship, the convocation of a Constituent Assembly and the restoration of political and economic freedoms, and in May 1921 proclaimed the "Provisional Democratic Republic of the Tambov Partisan Region". The Russian-language source names Pyotr Tokmakov, commander of the United Partisan Army of Tambov, as its chairman; the English-language source names Alexander Antonov as its leader.'],
        body: ['1920년 11월 14일 탐보프 봉기군은 모든 병력을 탐보프 지방 연합 파르티잔 군으로 묶으면서 정치 조직으로 근로농민동맹을 함께 세웠다. 러시아어 출처에 따르면 토크마코프가 군 사령관과 동맹 의장을 겸해 군사와 정치 양쪽에서 봉기군의 수장이었고, 영어 출처는 동맹의 목표를 「공산주의자-볼셰비키 정부의 타도」로 요약한다. 1920년 12월 동맹이 낸 선언은 계급 구분 없는 모든 시민의 정치적 평등, 내전 종식과 외국과의 항구적 평화, 평등·보통·직접·비밀 선거에 의한 제헌의회 소집과 대의원 소환권, 그때까지 공산주의자와 싸운 단체와 정당이 선출로 세우는 과도 기관, 언론·출판·양심·결사·집회의 자유를 요구했다. 경제 강령으로는 옛 제헌의회가 채택한 토지 사회화 법의 완전한 시행, 협동조합을 통한 생필품 공급, 공장의 부분적 탈국유화와 중공업·탄광·야금의 국가 소유 유지, 노동자 통제, 러시아와 외국 자본의 경제 재건 참여를 내세웠고, 옛 제국 안 여러 민족의 자결과 소농을 위한 국가 신용, 수공업의 자유, 보편적 의무 문맹 퇴치도 넣었다.\n\n1921년 5월 동맹은 민주적으로 선출된 제헌의회가 열릴 때까지 다스릴 「탐보프 파르티잔 지구 임시 민주 공화국」을 선포했다. 러시아어 출처는 선포를 5월 20일 키르사노프군 카라이살티키 마을 주민 집회의 일로 적고, 수반으로 농민 셴댜핀이 추대되었다고 쓴다. 영어 출처에 따르면 이 공화국은 혁명 전 러시아 국기를 썼고 백군의 구호 「위대하고 단일하며 나눌 수 없는 러시아 만세」가 봉기군의 표어 가운데 하나가 되었다. 같은 출처는 강령을 갖춘 덕에 이 운동이 다른 농민 봉기에 없던 힘과 응집력을 얻었지만, 정부를 무엇으로 대신할지에 대한 분명한 구상은 없었다고 평가한다. 1921년 여름 붉은 군대의 진압으로 봉기군 주력이 무너지면서 동맹도 사라졌다.',
            'On 14 November 1920 the Tambov insurgents united all their forces in the United Partisan Army of the Tambov region and at the same time founded the Union of Working Peasantry as their political organisation. According to the Russian-language source, Tokmakov was both army commander and chairman of the Union and so headed the insurgents on the military and the political line alike; the English-language source sums up the Union\'s goal as the "overthrow of the government of Communist-Bolsheviks". Its manifesto of December 1920 demanded political equality for all citizens without division into classes, an end to the civil war and a lasting peace with foreign states, a Constituent Assembly elected by equal, universal, direct and secret suffrage with the right to recall deputies, provisional authorities elected meanwhile by the unions and parties that had fought the communists, and freedom of speech, the press, conscience, unions and assembly. Its economic programme called for the full implementation of the land-socialisation law of the former Constituent Assembly, supply of necessities through the cooperatives, partial denationalisation of factories while heavy industry, coal mining and metallurgy stayed in state hands, workers\' control, and the participation of Russian and foreign capital in restoring the economy; it also included self-determination for the nationalities of the former empire, state credit for small farming, freedom for handicrafts and compulsory universal literacy education.\n\nIn May 1921 the Union proclaimed the "Provisional Democratic Republic of the Tambov Partisan Region", to rule until a democratically elected Constituent Assembly met. The Russian-language source dates the proclamation to 20 May at a village meeting in Karai-Saltyki, Kirsanov district, and says the peasant Shendyapin was put forward as head of the republic. According to the English-language source, the republic used the pre-revolutionary Russian flag, and the White slogan "Long live the Great United and Indivisible Russia" became one of the rebels\' mottos. The same source holds that its programme gave the movement a strength and coherence other peasant uprisings lacked, but that it had no clear idea of how to replace the government. The Union disappeared when the Red Army broke the main insurgent forces in the summer of 1921.'],
        aliases: { ko: ['근로농민동맹', '탐보프 근로농민동맹'], en: ['Union of Working Peasantry', 'Union of Working Peasants', 'Union of Toiling Peasants', 'Soyuz trudovogo krestyanstva'] },
        people: ['pyotr-tokmakov', 'alexander-antonov'],
        events: ['peasant-uprisings-1920-1922', 'civil-war'],
        sources: [S.tambEn, S.tambRu, S.tokm], locator: 'en: Organization; Union of Working Peasants — ru: Армия восставших; Перелом (20 мая 1921) — ru Токмаков: Биография',
    }),
    term({
        id: 'west-siberian-uprising-1921', ko: '1921년 서시베리아 봉기', en: 'West Siberian Uprising of 1921', category: 'factions', period: '1921–1922', startYear: 1921, endYear: 1922,
        definition: ['1921년 1월 31일 튜멘주 이심군에서 시작되어 서시베리아 전역으로 번진 농민 봉기. 곡물 할당 징발과 종자 징발에 맞서 일어났고, 「공산주의자 없는 소비에트」를 내걸고 토볼스크·페트로파블롭스크 등 여러 도시를 차지했다. 참가자 수와 지역 범위로 녹색군 봉기 가운데 가장 컸다고 평가되며, 1921년 봄 붉은 군대에 주력이 꺾였고 마지막 거점은 1922년 말에 사라졌다.',
            'A peasant uprising that began in Ishim district, Tyumen province, on 31 January 1921 and spread across Western Siberia. Raised against grain and seed requisitioning under the slogan "Soviets without communists", it took several towns including Tobolsk and Petropavlovsk. It is regarded as the largest of the Green uprisings in numbers and territory; its main forces were broken by the Red Army in the spring of 1921, and its last pockets disappeared at the end of 1922.'],
        body: ['콜차크 정권이 무너진 뒤 시베리아는 곡물 징발의 새 공급지가 되었다. 1920년 7월 20일 소브나르콤 결정에 따라 1920년 6월 20일부터 1921년 3월 1일까지 시베리아 혁명위원회 관할 6개 주가 1억 1천만 푸드, 튜멘주가 817만 7천 푸드의 곡물을 내야 했고, 이는 전국 할당 4억 4천만 푸드의 3분의 1이었다. 곡물 외에도 고기와 버터·달걀·가죽·양모 등 37가지 할당이 매겨졌다. 1920년 큰 흉작을 겪은 이심군에서도 식량용 곡물과 종자까지 거두었고, 1920년 12월에는 농가의 종자를 모두 공동 창고로 옮기는 종자 할당까지 준비되었다. 1921년 1월 31일 첼노콥스코예 마을에서 종자 반출을 막으려던 농민들에게 병사들이 발포한 것을 계기로 봉기가 이심군 북부 전체로, 이어 튜멘·토볼스크·얄루토롭스크·쿠르간 등지로 번졌다. 봉기군은 2월 시베리아 횡단 철도의 두 노선을 3주 동안 마비시켰고, 2월 14일 페트로파블롭스크, 21일 토볼스크, 3월 10일 수르구트, 21일 베료조보, 4월 1일 오브도르스크를 차지했다.\n\n가장 널리 퍼진 구호는 「공산주의자 없는 소비에트」였고, 봉기군은 언론·집회·결사의 자유와 자유 거래, 자기 땅과 생산물을 처분할 권리를 요구했으며 해방된 지역에서 자유 선거로 향·마을 소비에트를 다시 세웠다. 단일 본부는 없어 퇴역 중위 블라디미르 로딘의 시베리아 본부 같은 여러 지휘부가 따로 움직였다. 규모는 문헌마다 3만~15만 명으로 엇갈리며, 러시아어 출처는 4월까지 10만 명을 넘었다고 쓰고 영어 출처는 5만 5천~6만 명을 가장 그럴듯한 수치로 본다. 진압은 이반 스미르노프 등이 이끈 전권 「트로이카」가 맡았고, 스미르노프의 집계로 싸움이 시작된 지 한 달 반 남짓 사이 이심군에서 약 7천 명, 페트로파블롭스크군에서 1만 5천 명의 농민이 죽었다. 붉은 군대는 4월 토볼스크를 되찾고 4월 말~5월 초 아로마셰보 일대에서 봉기군에 큰 타격을 주었다. 그 뒤 봉기군은 유격전으로 돌아섰고, 1922년 12월 보고서는 「비적 행위」가 거의 사라졌다고 적었다.',
            'After Kolchak\'s regime collapsed, Siberia became a new source for grain requisitioning. Under a Sovnarkom decision of 20 July 1920, the six provinces under the Siberian Revolutionary Committee were to deliver 110 million poods of grain and Tyumen province 8,177,000 poods between 20 June 1920 and 1 March 1921, a third of the national quota of 440 million poods. Besides grain there were 37 levies in all, from meat to butter, eggs, hides and wool. Even in Ishim district, hit by a severe crop failure in 1920, the authorities took food grain and seed, and in December 1920 a seed levy was prepared to move all household seed into communal stores. On 31 January 1921 soldiers fired on peasants trying to stop seed grain being taken from the village of Chelnokovskoye, and the revolt spread across northern Ishim district and then to Tyumen, Tobolsk, Yalutorovsk, Kurgan and other districts. In February the rebels paralysed both lines of the Trans-Siberian Railway for three weeks, and they took Petropavlovsk on 14 February, Tobolsk on 21 February, Surgut on 10 March, Beryozovo on 21 March and Obdorsk on 1 April.\n\nThe most widespread slogan was "Soviets without communists"; the rebels demanded freedom of speech, assembly and association, free trade and the right to dispose of their own land and produce, and in the areas they freed they restored freely elected volost and village soviets. There was no single headquarters: several commands, such as the Siberian headquarters of the retired lieutenant Vladimir Rodin, acted separately. Estimates of their numbers range from 30,000 to 150,000; the Russian-language source says they exceeded 100,000 by April, while the English-language source considers 55,000–60,000 the most likely figure. The suppression was directed by a plenipotentiary troika including Ivan Smirnov, who reported that in a month and a half of fighting about 7,000 peasants had been killed in Ishim district and 15,000 in Petropavlovsk district. The Red Army retook Tobolsk in April and dealt the rebels a heavy blow around Aromashevo at the end of April and the beginning of May. The rebels then turned to guerrilla warfare, and in December 1922 reports stated that "banditry" had all but disappeared.'],
        aliases: { ko: ['서시베리아 농민 봉기', '1921~1922년 서시베리아 봉기'], en: ['West Siberian rebellion', 'West Siberian uprising', 'West Siberian peasant uprising', 'West Siberian Uprising of 1921–1922'] },
        people: ['ivan-smirnov'],
        events: ['peasant-uprisings-1920-1922', 'civil-war'],
        sources: [S.wsibRu, S.wsibEn], locator: 'ru: преамбула; Предпосылки восстания; Начало восстания; Идеология повстанцев; Характер боевых действий — en: Rebellion; End',
    }),
    term({
        id: 'chapan-war', ko: '차파니 전쟁', en: 'Chapan War', category: 'factions', period: '1919', startYear: 1919, endYear: 1919,
        definition: ['1919년 3~4월 볼가 강 중류의 심비르스크주와 사마라주에서 곡물 할당 징발과 강제 징집에 맞서 일어난 농민 봉기. 러시아 내전기 볼셰비키에 맞선 가장 큰 농민 봉기 가운데 하나로, 도시를 점령하고 일관된 요구를 내세운 첫 「봉기(보스스타니예)」로 꼽힌다. 이름은 이 지역 농민이 겨울에 입던 양가죽 외투 「차판」에서 왔다.',
            'A peasant uprising in Simbirsk and Samara provinces on the middle Volga in March–April 1919 against grain requisitioning and forced conscription. One of the largest peasant revolts against the Bolsheviks in the Russian Civil War, it is counted as the first vosstaniye, or great peasant rebellion, to take towns and put forward a coherent programme. Its name comes from the chapan, the sheepskin winter coat worn by the peasants of the region.'],
        body: ['1919년 초 심비르스크주에는 중앙에서 온 식량 부대원 3,500명과 식량군 병사 1,700명이 있었고, 2월까지 이 주에서만 300만 푸드가 넘는 곡물이 징발되었다. 같은 시기 1918년 12월에 도입된 비상세 징수도 시작되어, 농민들 사이에는 자신들이 굶어 죽게 되었다는 생각이 퍼졌다. 1919년 3월 3일 센길레이군 노보데비치예 마을 주민들이 곡물과 가축을 거두러 온 위원들에 맞서 경종을 울리고 공산당원과 위원들을 체포했으며 붉은 군대 분견대를 무장 해제했다. 진압하러 온 부대는 오히려 농민 편에 섰고, 봉기는 이웃 마을로 번졌다. 3월 7일 봉기군은 싸움 없이 스타브로폴을 차지하고 제1차 세계대전 참전 장교 알렉세이 돌리닌을 지도자로 세웠으며, 「모든 권력을 근로 인민에게! 공산주의자의 전횡을 타도하라!」는 호소문을 냈다. 영어 출처는 봉기군이 징발 폐지와 소비에트 자유선거, 「볼셰비키 코미사르 지배」의 종식을 요구했다고 쓴다. 참가자 수는 최소 3만 명에서 10만~15만 명까지 추정이 엇갈린다.\n\n사마라에서는 주당위원회 의장 발레리안 쿠이비셰프와 제4군 사령관 미하일 프룬제의 주도로 혁명 야전 참모부가 꾸려졌고, 정규군과 노동자 연대, 헝가리인 국제주의자 중대 등이 투입되었다. 영어 출처는 프룬제 휘하 병력을 약 1만 3천 명으로 적는다. 붉은 군대는 3월 14일 스타브로폴을, 같은 날 또는 15일 노보데비치예를 되찾았고, 봉기는 3월 말~4월 초까지 흩어진 거점에서 이어지다 4월 중순 끝났다. 프룬제는 레닌에게 진압 과정에서 적어도 1천 명이 죽고 600명이 넘는 「주모자와 쿨라크」가 총살되었으며 우신스코예 마을을 불태웠다고 보고했다. 진압 뒤에는 대량 체포와 처형, 수용소 수감이 뒤따랐고, 봉기의 인명 피해는 농민 약 1만 명으로 추산된다. 4월 체카 보고는 봉기 마을 농민 대부분이 중농이고 쿨라크는 마을마다 5~10명을 넘지 않았다고 적었으며, 레프 트로츠키는 4월 6일 사마라에서 볼가 농민 봉기를 「무서운 경고」라고 불렀다. 러시아어 출처에 따르면 참가자와 그 자녀는 1991년 10월 정치 탄압 희생자 복권법으로 탄압 희생자로 인정되었고, 영어 출처는 1996년 보리스 옐친의 대통령령으로 복권되었다고 쓴다.',
            'At the start of 1919 there were 3,500 food-detachment workers and 1,700 food-army soldiers from the central provinces in the villages of Simbirsk province, and by February more than 3 million poods of grain had been requisitioned there alone. At the same time collection began of the emergency tax introduced in December 1918, and the peasants came to believe they were being condemned to starvation. On 3 March 1919 the villagers of Novodevichye in Sengiley district sounded the alarm bell against the officials who had come for grain and livestock, arrested the communists and officials and disarmed a Red Army detachment. The troops sent to put them down went over to the peasants, and the revolt spread to neighbouring villages. On 7 March the rebels took Stavropol without a fight, put the First World War officer Aleksey Dolinin at their head and issued an appeal: "All power to the working people! Down with the domination of the communists!" The English-language source says they demanded the abolition of requisitioning, free elections to the soviets and an end to the "Bolshevik commissarocracy". Estimates of their numbers range from at least 30,000 to 100,000–150,000.\n\nIn Samara a revolutionary field staff was set up on the initiative of Valerian Kuybyshev, chairman of the provincial party committee, and Mikhail Frunze, commander of the 4th Army, and regular units, a workers\' regiment and a Hungarian internationalist company were sent in; the English-language source puts Frunze\'s force at about 13,000. The Red Army retook Stavropol on 14 March and Novodevichye the same day or on the 15th, and the revolt lingered in scattered pockets until late March and early April before the fighting ended in mid-April. Frunze reported to Lenin that at least 1,000 people had been killed in the suppression, more than 600 "ringleaders and kulaks" shot, and the village of Usinskoye burned. Mass arrests, executions and camps followed, and the uprising is estimated to have cost the lives of some 10,000 peasants. A Cheka report in April found that most peasants in the rebel villages were middle peasants, with no more than five to ten kulaks per village, and on 6 April Leon Trotsky called the Volga peasant uprising "a formidable warning" in a speech in Samara. According to the Russian-language source, the participants and their children were recognised as victims of repression by the rehabilitation law of October 1991; the English-language source says they were rehabilitated by a decree of President Boris Yeltsin in 1996.'],
        aliases: { ko: ['차파니 봉기', '차판 전쟁', '차판 봉기'], en: ['Chapan rebellion', 'Chapan uprising', 'Chapannaya voyna', 'Chapanka'] },
        people: ['frunze', 'kuibyshev', 'trotsky'],
        events: ['peasant-uprisings-1920-1922', 'civil-war'],
        sources: [S.chapanRu, S.chapanEn], locator: 'ru: преамбула; Причины восстания; Ход восстания; Подавление; Итоги и последствия; Реабилитация — en: lead; Rebellion; Suppression; Consequences',
    }),
    term({
        id: 'tambov-order-171', ko: '탐보프 명령 제171호', en: 'Tambov Order No. 171', category: 'repression', period: '1921', startYear: 1921, endYear: 1921,
        definition: ['1921년 6월 11일 탐보프 봉기를 진압하던 전러시아중앙집행위원회 전권위원회가 낸 명령 「개별 비적과 그들을 숨겨 주는 가족에 대한 탄압 조치 개시에 관하여」. 이름을 밝히지 않는 주민의 즉결 총살, 무기를 숨긴 마을의 인질 총살, 봉기군을 숨긴 가족의 체포·추방과 재산 몰수, 그 집 연장자 일꾼의 재판 없는 총살을 규정했다. 위원장 블라디미르 안토노프-옵세옌코와 사령관 미하일 투하쳅스키가 서명했다.',
            'An order issued on 11 June 1921 by the Plenipotentiary Commission of the All-Russian Central Executive Committee that was suppressing the Tambov rebellion, "On the start of repressive measures against individual bandits and the families sheltering them". It prescribed summary execution of citizens who refused to give their names, the shooting of hostages in villages that hid weapons, and the arrest and deportation of families who sheltered insurgents, the confiscation of their property and the execution without trial of the eldest worker of the household. It was signed by the commission\'s chairman, Vladimir Antonov-Ovseenko, and the commander of the forces, Mikhail Tukhachevsky.'],
        body: ['명령은 6월 1일부터 시작된 단호한 투쟁으로 「안토노프의 비적 떼」가 격파되었다고 밝히고, 「사회혁명당 비적의 뿌리를 완전히 뽑기 위해」 일곱 개 조항을 내렸다. 이름을 밝히기를 거부하는 시민은 재판 없이 그 자리에서 총살하고, 무기를 숨긴 마을에는 인질을 잡는다는 판결을 내려 무기를 내놓지 않으면 인질을 총살하며, 숨긴 무기가 나오면 그 집의 가장 연장자인 일꾼을 재판 없이 총살하도록 했다. 비적이 숨어든 집의 가족은 체포해 주 밖으로 추방하고 재산을 몰수하며 연장자 일꾼을 총살하고, 비적의 가족이나 재산을 숨긴 가족도 비적으로 다루도록 했다. 달아난 비적 가족의 재산은 소비에트 권력에 충실한 농민에게 나누어 주고 남은 집은 불태우거나 허물게 했으며, 마지막 조항은 명령을 「가혹하고 무자비하게」 집행하라고 했다. 안토노프-옵세옌코와 투하쳅스키, 주 집행위원회 의장 라브로프, 서기 바실리예프가 서명했고, 명령은 마을 집회에서 낭독되었다.\n\n이튿날인 6월 12일 투하쳅스키는 참모장 니콜라이 카쿠린과 함께 숲에 숨은 봉기군에게 독가스를 쓰라는 명령 제0116호에 서명했다. 6월 23일 전권위원회 명령 제116호는 봉기 성향이 강한 향을 포위하고 유력 주민 60~100명을 인질로 잡은 뒤 향 집회에서 명령 제130호와 제171호를 읽고, 두 시간 안에 비적과 무기를 내놓지 않으면 주민 앞에서 인질을 총살하는 「청소」 방식을 권장했다. 6월 27일 오시놉카 마을에서는 인질 약 40명 가운데 21명이, 7월 3~4일 보고슬롭카에서는 36명이 총살되었고, 위협이 통하지 않은 65~70호의 제2카레옙카 마을은 주민을 내쫓고 불태웠다. 수용소에는 어린이도 많이 갇혀, 7월 수용소를 비운 뒤에도 1~10세 어린이 인질이 450명 넘게 남았고, 7월 20일에는 어린이와 임신부, 어린 자녀를 둔 여성을 인질로 잡지 말라는 지시가 따로 내려졌다. 러시아어 출처는 인질 제도가 봉기군을 더욱 격분시켜 그들도 붉은 군대 병사와 공산당원, 소비에트 직원과 그 가족을 인질로 잡아 총살했다고 쓰며, 역사가 율리야 칸토르는 탄압을 받은 탐보프 농민을 3만~5만 명으로 추산한다.',
            'The order declared that the "decisive struggle against banditry" since 1 June had routed "Antonov\'s band" and, "in order finally to uproot the SR-bandit roots", laid down seven points. Citizens who refused to give their names were to be shot on the spot without trial; villages hiding weapons were to be sentenced to the taking of hostages, who would be shot if the weapons were not surrendered; where hidden weapons were found, the eldest worker of the family was to be shot on the spot without trial. The family in whose house a bandit had hidden was to be arrested and deported from the province, its property confiscated and its eldest worker shot without trial, and families hiding bandits\' relatives or property were to be treated as bandits. If a bandit\'s family fled, its property was to be shared among peasants loyal to Soviet power and the abandoned houses burned or dismantled; the last point ordered that the order be carried out "severely and mercilessly". It was signed by Antonov-Ovseenko, Tukhachevsky, the chairman of the provincial executive committee Lavrov and the secretary Vasilyev, and was to be read out at village assemblies.\n\nThe next day, 12 June, Tukhachevsky and his chief of staff Nikolai Kakurin signed Order No. 0116 to use poison gas against insurgents hiding in the forests. On 23 June the commission\'s Order No. 116 recommended a "cleansing" method: surround a volost with strong bandit sympathies, take 60–100 prominent residents hostage, read Orders No. 130 and 171 at a volost assembly, and shoot the hostages in front of the population if bandits and weapons were not handed over within two hours. On 27 June 21 of about 40 hostages were shot in the village of Osinovka, and on 3–4 July 36 in Bogoslovka; where threats failed, as in Vtoraya Kareevka with its 65–70 households, the inhabitants were evicted and the village burned. Many children were held in the camps: even after the camps were thinned out in July more than 450 child hostages aged one to ten remained, and on 20 July a separate instruction forbade taking children, pregnant women and women with small children as hostages. The Russian-language source notes that the hostage system enraged the insurgents, who in turn took and shot Red Army soldiers, communists, Soviet employees and their families, and the historian Yulia Kantor estimates that 30,000–50,000 Tambov peasants suffered repression.'],
        aliases: { ko: ['탐보프 전권위원회 명령 제171호'], en: ['Order No. 171 of the Tambov Plenipotentiary Commission', 'Tambov Order 171'] },
        people: ['antonov-ovseenko', 'tukhachevsky', 'nikolai-kakurin'],
        events: ['peasant-uprisings-1920-1922', 'civil-war'],
        sources: [S.tambRu], locator: 'ru: Разгром восстания (приказ № 171, № 0116, № 116); Репрессии',
    }),
    term({
        id: 'green-armies', ko: '녹색군 (러시아 내전)', en: 'Green armies (Russian Civil War)', category: 'factions', period: '1918–1922', startYear: 1918, endYear: 1922,
        definition: ['러시아 내전기인 1918~1922년 볼셰비키와 백군, 외국 간섭군 모두에 맞서 싸운 농민 무장 집단을 통틀어 부르는 이름. 징발과 보복에서 자기 마을을 지키려 한 반쯤 조직된 지역 민병으로, 정치적으로는 중립이었지만 때로 사회혁명당과 연결되었다. 이름은 숲으로 숨어든 붉은 군대 탈영병 무리에서 나왔으며, 볼셰비키의 승리가 다가오면서 1922년에 흩어졌다.',
            'The collective name for the armed peasant groups that fought all governments in the Russian Civil War from 1918 to 1922: the Bolsheviks, the Whites and the foreign interventionists. They were semi-organised local militias defending their communities against requisitions and reprisals, politically neutral but at times associated with the Socialist Revolutionary Party. The name came from the bands of Red Army deserters who hid in the forests, and the movement dissolved in 1922 as the Bolshevik victory approached.'],
        body: ['녹색군의 배경은 전시 공산주의의 곡물 징발이었다. 볼셰비키는 남는 곡물을 강제로 거두기 위해 8만 명 규모의 식량 부대를 꾸렸고, 이들이 종자와 생필품까지 빼앗자 농민들은 숲으로 달아나 반란군에 합류했다. 녹색군은 귀족 토지의 몰수와 농촌 시장 경제의 유지, 스스로 뽑은 소비에트에 의한 자치를 원했고, 지주의 권리를 되살리려는 백군에도 늘 적대적이었다. 백군이 사실상 패한 1920년 이후 징발의 명분이 약해지자 같은 계급을 억압하라는 명령에 반발한 농민 출신 붉은 군대 병사들이 무기를 들고 숲에 모였고, 1919~1921년 녹색군 대원과 지휘관 상당수가 이런 탈영병이었다. 1921년 공식적으로 약 250만 명이 동원 해제되면서 고향에 돌아간 많은 병사가 녹색군에 합류했다. 소비에트 당국은 농민 소요를 짧고 소규모인 「분트」와, 수천 명이 도시를 점령하고 일관된 강령을 내세우는 「봉기(보스스타니예)」로 나누었는데, 1919년의 차파니 전쟁이 첫 「봉기」로 꼽힌다. 1920년의 쇠스랑 봉기, 알렉산드르 안토노프의 탐보프 봉기, 녹색군 봉기 가운데 가장 컸던 1921~1922년 서시베리아 봉기, 우크라이나의 아타만 니키포르 흐리호리우와 다닐로 테르필로의 봉기가 대표적이며, 네스토르 마흐노의 아나키스트 농민군도 이 흐름에서 함께 다루어진다.\n\n녹색군은 탈영병이 들고 온 무기와 빼앗은 무기 말고는 몽둥이와 쇠스랑, 도끼, 사냥총으로 싸웠고, 다리를 폭파하고 전신선과 철도를 끊는 유격전을 벌였다. 1919~1921년 동부 우크라이나와 탐보프, 시베리아의 대규모 봉기에는 10만 명이 넘는 유격대원과 수백만 명의 농민 지지자가 관여했고, 레닌은 이를 소비에트 역사상 첫 「큰 국내 정치 위기」라 부르며 1921년 3월 8일 제10차 당대회에서 「데니킨, 유데니치, 콜차크를 합친 것보다 훨씬 더 위험하다」고 말했다. 볼셰비키는 녹색군을 백군의 한 갈래로 그리고 쿨라크의 영향을 부풀렸으며, 처음에는 각 봉기를 개별 소요로 다루며 가혹하게 진압하다가 뒤에는 대량 테러와 선전, 봉기 지역을 군대로 채우는 방식으로 맞섰다. 녹색군은 지역에 머무는 성격과 서로 간의 조율 부족, 내부 갈등 때문에 실패했다. 영어 출처는 녹색군이 1921년 신경제정책으로의 전환에 기여한 것은 분명하지만 그 정도는 논쟁의 여지가 있다고 보고, 네프와 늘어난 강우가 농촌 사정을 나아지게 해 녹색군의 기반을 허문 점과 1921~1922년 기근이 봉기를 끝낸 가장 큰 무기였다는 점을 강조한다.',
            'The background to the Greens was the grain requisitioning of war communism. The Bolsheviks formed an 80,000-strong supply army to seize grain surpluses by force, and when its detachments took seed and vital reserves as well, peasants fled to the forests and joined the rebels. The Greens wanted to seize the nobility\'s land, keep the rural market economy and govern their communities through soviets of their own choosing, and they were always hostile to the Whites, who sought to restore the landowners\' rights. Once the Whites were effectively beaten in 1920 and requisitioning lost its justification, peasant soldiers of the Red Army who refused to keep oppressing their own class deserted with their weapons to the forests, and in 1919–1921 most Green fighters and leaders were such deserters. Officially some 2.5 million soldiers were demobilised in 1921, and many who went home joined the Greens. The Soviet authorities divided peasant unrest into the short, small bunt and the vosstaniye, an insurrection of thousands able to take towns and put forward a coherent programme; the Chapan War of 1919 is counted as the first vosstaniye. Major Green movements included the Pitchfork uprising of 1920, Alexander Antonov\'s Tambov rebellion, the West Siberian rebellion of 1921–1922, the largest of the Green uprisings, and the risings of the Ukrainian atamans Nykyfor Hryhoriv and Danylo Terpylo, while Nestor Makhno\'s anarchist peasant army is treated alongside them.\n\nApart from the arms that deserters brought or that they captured, the Greens fought with sticks, pitchforks, axes and hunting rifles, waging guerrilla war by blowing up bridges and cutting telegraph lines and railways. The great uprisings in eastern Ukraine, Tambov and Siberia in 1919–1921 involved more than 100,000 guerrillas and millions of peasant supporters; Lenin called this the first "great internal political crisis" in Soviet history and on 8 March 1921, at the 10th Party Congress, declared it "far more dangerous than all the forces of Denikin, Yudenich and Kolchak combined". The Bolsheviks portrayed the Greens as a branch of the White movement and exaggerated the role of the kulaks; at first they treated each revolt as a separate disturbance and crushed it harshly, later turning to mass terror, propaganda and flooding rebel areas with troops. The Greens failed because of their local outlook, their lack of coordination and internal tensions. The English-language source holds that the Greens clearly contributed to the turn to the New Economic Policy in 1921, though the extent is debated, and stresses that the NEP and increased rainfall undercut their base by improving rural conditions and that the famine of 1921–1922 was the main weapon that ended the revolts.'],
        aliases: { ko: ['녹색군'], en: ['Green armies', 'Green Army (Russian Civil War)', 'Zelenoarmeytsy', 'Zelyonaya armiya'] },
        people: ['alexander-antonov', 'nestor-makhno', 'nykyfor-hryhoriv', 'lenin'],
        events: ['peasant-uprisings-1920-1922', 'civil-war', 'ukraine-1917-1921'],
        sources: [S.green], locator: 'lead; Background; Objectives; Rejection of the Whites; Organisation; Peasant Wars; Tactics; Bolshevik response; Reasons for failure',
    }),
];
