// Person cards for the finland-1917-1920 event (Finnish independence and civil
// war, 1917–1920), see lib.js person(). Excerpts are verbatim from the cited
// pages (en/fi/ru Wikipedia as fetched 2026-10-04). Bodies with no catalog
// affiliation (the Finnish Red Guards, the People's Delegation, the Finnish
// Trade Union Federation) stay unresolved.
// Native names are Finnish (Latin script); Gylling, Haapalainen and Rahja carry
// Soviet citizenship with Finnish origin, as kuusinen does.
const { W, person } = require('../lib');

const E = t => W(encodeURI(t));
const FI = t => 'https://fi.wikipedia.org/wiki/' + encodeURI(t);
const RU = t => 'https://ru.wikipedia.org/wiki/' + encodeURI(t);
const S = {
    stahl: E('Kaarlo_Juho_Ståhlberg'),
    pres1919: E('1919_Finnish_presidential_election'),
    tartuRU: RU('Тартуский_мирный_договор_между_РСФСР_и_Финляндией'),
    gylling: E('Edvard_Gylling'),
    aaltonen: E('Ali_Aaltonen'),
    aaltonenFI: FI('Ali_Aaltonen'),
    haapa: E('Eero_Haapalainen'),
    tokoi: E('Oskari_Tokoi'),
    tokoiFI: FI('Oskari_Tokoi'),
    rahja: E('Eino_Rahja'),
    rahjaFI: FI('Eino_Rahja'),
};

const unaffiliated = card => ({
    ...card,
    activities: card.activities.map(a => (a.affiliationId ? a : { ...a, affiliationStatus: 'unresolved', relation: 'unresolved' })),
});

module.exports = [
    person({
        id: 'kaarlo-juho-stahlberg', groupId: 'world-interwar',
        given: ['카를로 유호', 'Kaarlo Juho'], family: ['스톨베리', 'Ståhlberg'], nativeName: 'Kaarlo Juho Ståhlberg', years: '1865–1952',
        citizenship: 'finland', origin: 'finland',
        epithet: ['공화국 헌법을 설계하고 내전 뒤 화해를 꾀한 핀란드의 초대 대통령',
            'Jurist who shaped Finland’s republican constitution and, as its first president, sought to reconcile the defeated Reds'],
        bio: ['1865년 수오무살미에서 태어난 법학자로, 청년핀란드당의 입헌주의자로서 러시아화에 법적으로 맞섰다. 1905~1907년 메헬린 상원의 통상·산업 담당 의원, 1908~1918년 헬싱키 대학 행정법 교수를 지냈고 1914년 의회 의장이었다. 1917년 헌법위원회 위원장이 되어 공화국 헌법안을 주도했고, 1918년 승자들의 입헌군주제 구상에 맞서 공화제를 지지했다. 1919년 7월 의회에서 만네르헤임을 143표 대 50표로 누르고 초대 대통령이 되어 소비에트 러시아와의 강화를 지지했으며, 적색 포로 대부분을 사면하고 타르투 조약을 비준했다. 1925년 재선에 나서지 않았고, 1930년 라푸아 운동 활동가들에게 납치되기도 했다. 1952년 숨졌다.',
            'Born in Suomussalmi in 1865, he was a jurist and a constitutionalist of the Young Finnish Party who resisted Russification by legal means. He was senator for trade and industry in the Mechelin Senate in 1905–1907, professor of administrative law at the University of Helsinki in 1908–1918 and Speaker of Parliament in 1914. As chairman of the Constitutional Council from 1917 he led the drafting of the republican constitution, and in 1918 he backed a republic against the constitutional monarchy favoured by the victors of the civil war. Elected the first president by Parliament in July 1919, defeating Mannerheim by 143 votes to 50, he favoured peace with Soviet Russia, pardoned most of the Red prisoners and ratified the Treaty of Tartu. He did not seek re-election in 1925, was kidnapped by Lapua Movement activists in 1930 and died in 1952.'],
        fate: ['natural', '자연사', 'Natural causes'],
        aliases: { ko: [], en: ['K. J. Ståhlberg', 'Kaarlo Juho Stahlberg', 'Carl Johan Ståhlberg'] },
        sources: [S.stahl, S.pres1919, S.tartuRU],
        facts: {
            years: { claim: '1865–1952', locator: 'lead', excerpt: '28 January 1865 – 22 September 1952' },
            citizenship: { claim: 'Finnish jurist and first president of Finland', locator: 'lead', excerpt: 'was a Finnish jurist and academic who was one of the most important pioneers of republicanism in the country' },
            nationalOrigin: { claim: 'born in Suomussalmi, Grand Duchy of Finland', locator: 'Early life', excerpt: 'Ståhlberg was born in Suomussalmi, in the Kainuu region of the Grand Duchy of Finland' },
            bio: [
                { claim: 'constitutionalist resisting Russification', locator: 'Career as academic and civil servant', excerpt: 'He was a "constitutionalist" – supporting the already existing Finnish constitutional framework and constitutional legislative policies, including legislative resistance, against the attempted Russification of Finland.' },
                { claim: 'member of the Young Finnish Party', locator: 'Career as academic and civil servant', excerpt: 'becoming a member of the Young Finnish Party' },
                { claim: 'senator for trade and industry, 1905', locator: 'Career as politician', excerpt: 'In 1905, he was appointed as a Senator in the newly formed Senate of Leo Mechelin, with responsibility for trade and industry.' },
                { claim: 'professor of administrative law until 1918', locator: 'Career as politician', excerpt: 'appointed as Professor of Administrative Law at the University of Helsinki, a position he retained until 1918' },
                { claim: 'Speaker of Parliament, 1914', locator: 'Career as politician', excerpt: 'Ståhlberg also served as Speaker of the Parliament in 1914.' },
                { claim: 'chairman of the Constitutional Council, 1917', locator: 'Career as politician', excerpt: 'Instead, the Social Democrat Oskari Tokoi was elected, with Ståhlberg being appointed as chairman of the Constitutional Council.' },
                { claim: 'his proposals became the 1919 constitution', locator: 'Architect of the Finnish constitution', excerpt: 'His proposals would eventually be enacted as the Constitution of Finland in 1919.' },
                { claim: 'backed a republic against the monarchists in 1918', locator: 'Architect of the Finnish constitution', excerpt: 'In 1918, Ståhlberg supported the idea of republic instead of a constitutional monarchy which was supported by more conservative victors of the civil war.' },
                { claim: 'elected president 25 July 1919 over Mannerheim, 143 to 50', locator: 'First President of Finland', excerpt: "he was elected by Parliament as President of the Republic on 25 July 1919, defeating Carl Gustaf Mannerheim (the candidate supported by the National Coalition and Swedish People's parties) by 143 votes to 50." },
                { claim: 'favoured a peace treaty with Soviet Russia', source: S.pres1919, locator: 'lead', excerpt: 'Ståhlberg favoured the signing of a peace treaty between Finland and the Soviet Russia' },
                { claim: 'pardoned most Red prisoners', locator: 'First President of Finland', excerpt: 'most of the Red prisoners, despite the strong criticism that this aroused from many right-wing Finns' },
                { claim: 'ratified the Treaty of Tartu on 11 December 1920', source: S.tartuRU, locator: 'Подписание и ратификация', excerpt: '11 декабря 1920 года президент Финляндии Стольбергом ратифицировал договор' },
                { claim: 'did not seek re-election in 1925', locator: 'Post-presidential life', excerpt: 'Ståhlberg did not seek re-election in 1925' },
                { claim: 'kidnapped by Lapua Movement activists in 1930', locator: 'Post-presidential life', excerpt: 'In 1930, activists from the right-wing Lapua Movement kidnapped him and his wife, attempting to send them to the Soviet Union' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-finland', startYear: 1919, endYear: 1925, primary: true, claim: 'First President of Finland, 1919–1925', locator: 'lead', excerpt: 'He was the first president of Finland (1919–1925) and a liberal nationalist.' },
            { functionId: 'law', affiliationId: 'state-finland', startYear: 1917, endYear: 1918, claim: 'Chairman of the Constitutional Council drafting the republican constitution', locator: 'Architect of the Finnish constitution', excerpt: 'As chairman of the council, Ståhlberg was involved in the drafting and re-drafting of constitutional proposals during 1918' },
            { functionId: 'law', affiliationId: 'state-finland', startYear: 1918, endYear: 1919, claim: 'First President of the Supreme Administrative Court', locator: 'Architect of the Finnish constitution', excerpt: "Ståhlberg's appointment as the first President of the Supreme Administrative Court in 1918" },
            { functionId: 'legislature', affiliationId: 'state-finland', startYear: 1914, endYear: 1914, claim: 'Speaker of the Parliament of Finland', locator: 'Career as politician', excerpt: 'Ståhlberg also served as Speaker of the Parliament in 1914.' },
        ],
        career: [
            ['1905–1907', '메헬린 상원 의원(통상·산업 담당)', 'Senator for trade and industry in the Mechelin Senate'],
            ['1908–1918', '헬싱키 대학 행정법 교수', 'Professor of Administrative Law, University of Helsinki'],
            ['1914', '핀란드 의회 의장', 'Speaker of the Parliament of Finland'],
            ['1917–1918', '헌법위원회 위원장', 'Chairman of the Constitutional Council'],
            ['1918', '초대 최고행정법원장', 'First President of the Supreme Administrative Court'],
            ['1919–1925', '핀란드 초대 대통령', 'First President of Finland'],
        ],
    }),
    unaffiliated(person({
        id: 'edvard-gylling', groupId: 'world-interwar',
        given: ['에드바르드', 'Edvard'], family: ['귈링', 'Gylling'], nativeName: 'Edvard Gylling', years: '1881–1938',
        citizenship: 'soviet', origin: 'finland',
        epithet: ['적색 핀란드의 재정 위원을 지내고 카렐리야 자치 공화국 정부를 이끈 핀란드 사회주의자',
            'Finnish socialist who was Red Finland’s commissar of finance and later headed the government of Soviet Karelia'],
        bio: ['1881년 쿠오피오에서 태어난 통계학자·경제학자로, 1909년 소작제 연구로 박사 학위를 받아 사회민주당의 농업 전문가가 되었다. 1908~1917년 사회민주당 의원이자 당 부의장이었고, 1917년 11월 쿠시넨과 「우리는 요구한다」를 썼다. 내전 때 인민대표위원회 재정 위원으로 3월 1일 소비에트 러시아와의 조약을 협상해 서명했고, 패전 무렵 비푸리 방어를 조직했다. 스웨덴으로 피해 핀란드 공산당 스톡홀름 사무국을 이끌다 1920년 레닌에게 카렐리야 자치를 보고했다. 1923~1935년 카렐리야 자치 공화국 인민위원회의 의장으로 핀란드화 정책을 폈으나 「민족주의적 쇼비니즘」으로 몰려 해임되었고, 1938년 모스크바에서 총살되었다.',
            'Born in Kuopio in 1881, the statistician and economist took his doctorate in 1909 with a thesis on crofting and became the Social Democrats’ agrarian expert. He sat in the Diet for the party from 1908 to 1917, was its vice chairman, and in November 1917 co-wrote “We demand” with Kuusinen. In the civil war he was Commissar of Finance of the People’s Delegation, led the talks for the 1 March treaty with Soviet Russia and signed it, and organised the defence of Viipuri at the end. Escaping to Sweden, he headed the Stockholm bureau of the Communist Party of Finland and in 1920 reported to Lenin on Karelian autonomy. As chairman of the Council of People’s Commissars of Soviet Karelia in 1923–1935 he pursued Finnicisation, was condemned for “nationalist chauvinism” and removed, and was shot in Moscow in 1938.'],
        fate: ['executed', '총살', 'Executed by shooting'],
        aliases: { ko: ['에드바르드 오토 빌헬름 귈링'], en: ['Edvard Otto Vilhelm Gylling'] },
        sources: [S.gylling, S.haapa],
        facts: {
            years: { claim: '1881–1938', locator: 'lead', excerpt: '30 November 1881 – 14 June 1938' },
            citizenship: { claim: 'head of government of Soviet Karelia', locator: 'lead', excerpt: "eventually becoming the leader of Soviet Karelia as Chairman of the Council of its People's Commissars from 1923 to 1935" },
            nationalOrigin: { claim: 'born in Kuopio, Finland', locator: 'Early life and career', excerpt: 'Gylling was born in Kuopio in 1881 into a middle-class family.' },
            bio: [
                { claim: 'doctorate on the crofter institution, 1909', locator: 'Early life and career', excerpt: 'He completed his doctorate at the Imperial Alexander University in Finland in 1909 with a thesis on the development of the crofter institution in Finland during the Swedish period' },
                { claim: 'Social Democratic deputy 1908–1917 and vice chairman', locator: 'lead', excerpt: 'A member of the Diet of Finland for the Social Democratic Party of Finland from 1908 to 1917 and vice chairman of the party' },
                { claim: 'co-authored "We demand" with Kuusinen', locator: 'Early life and career', excerpt: 'In November 1917 he co-authored with Otto Wille Kuusinen the declaration Vi kräver ("We demand")' },
                { claim: 'Commissar of Finance in the Red government', locator: 'Finnish Civil War', excerpt: 'Gylling took charge of economic affairs in the Red government as Commissar of Finance' },
                { claim: 'signed the 1 March 1918 treaty', locator: 'Finnish Civil War', excerpt: 'signed in Saint Petersburg by Vladimir Lenin and Joseph Stalin from the Russian side and by Gylling and Oskari Tokoi from the Finnish side' },
                { claim: 'organised the defence of Viipuri', source: S.haapa, locator: 'Finnish Civil War', excerpt: "Haapalainen and Edvard Gylling were one of the few leading Reds who stayed in Viipuri and organized the city's defense" },
                { claim: 'headed the Stockholm bureau of the Communist Party of Finland', locator: 'Finnish Civil War', excerpt: 'Instead, he went underground in Vyborg and then escaped to Sweden, where he headed the Stockholm bureau of the Communist Party of Finland' },
                { claim: 'reported to Lenin on Karelian autonomy, May 1920', locator: 'Finnish Civil War', excerpt: "In May 1920, he travelled to Moscow at Lenin's invitation to report on the feasibility of creating an autonomous Karelian republic" },
                { claim: 'Finnicisation policy in Karelia', locator: 'Soviet Karelia', excerpt: "With Lenin's authorisation, Gylling implemented a Finnicisation policy despite Finns being a clear minority in the region." },
                { claim: 'accused of nationalist chauvinism', locator: 'Soviet Karelia', excerpt: 'Gylling was accused of "nationalist chauvinism"' },
                { claim: 'removed in October 1935', locator: 'Soviet Karelia', excerpt: 'He was removed from his post as head of government of the Karelian Soviet Republic in October 1935' },
                { claim: 'executed at Kommunarka, 14 June 1938', locator: 'Arrest and execution', excerpt: 'He was executed on 14 June 1938 at the Kommunarka shooting ground in Moscow.' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-soviet', startYear: 1923, endYear: 1935, primary: true, claim: 'Chairman of the Council of People’s Commissars of the Karelian ASSR', locator: 'Soviet Karelia', excerpt: "and Gylling served as Chairman of its Council of People's Commissars" },
            { functionId: 'political-leadership', affiliationId: 'party-finnish-social-democratic', relation: 'membership', startYear: 1908, endYear: 1918, claim: 'Social Democratic deputy and vice chairman of the party', locator: 'lead', excerpt: 'A member of the Diet of Finland for the Social Democratic Party of Finland from 1908 to 1917 and vice chairman of the party' },
            { functionId: 'economy', affiliationId: null, startYear: 1918, endYear: 1918, claim: 'Commissar of Finance of the Finnish People’s Delegation (no catalog affiliation)', locator: 'Finnish Civil War', excerpt: 'Gylling took charge of economic affairs in the Red government as Commissar of Finance' },
            { functionId: 'political-leadership', affiliationId: 'party-finnish-communist', relation: 'membership', startYear: 1918, endYear: 1920, claim: 'Head of the Stockholm bureau of the Communist Party of Finland', locator: 'Finnish Civil War', excerpt: 'where he headed the Stockholm bureau of the Communist Party of Finland' },
        ],
        career: [
            ['1905', '마르크스주의 잡지 「사회주의 평론」 편집장', 'Editor-in-chief of the Marxist journal Sosialistinen aikakausilehti'],
            ['1908–1917', '핀란드 의회 의원(사회민주당), 당 부의장', 'Social Democratic member of the Diet; party vice chairman'],
            ['1918', '인민대표위원회 재정 위원', 'Commissar of Finance, Finnish People’s Delegation'],
            ['1918–1920', '핀란드 공산당 스톡홀름 사무국장', 'Head of the Stockholm bureau of the Communist Party of Finland'],
            ['1920–1923', '카렐리야 노동 코뮌 지도', 'Leading the Karelian Workers’ Commune'],
            ['1923–1935', '카렐리야 자치 소비에트 사회주의 공화국 인민위원회의 의장', 'Chairman of the Council of People’s Commissars of the Karelian ASSR'],
        ],
    })),
    unaffiliated(person({
        id: 'ali-aaltonen', groupId: 'world-interwar',
        given: ['알리', 'Ali'], family: ['알토넨', 'Aaltonen'], nativeName: 'Ali Aaltonen', years: '1884–1918',
        citizenship: 'finland', origin: 'finland',
        epithet: ['러시아 군 장교 출신으로 핀란드 적위대의 초대 총사령관이 된 노동 기자',
            'Labour journalist and former Russian army officer who became the first commander-in-chief of the Finnish Red Guards'],
        bio: ['1884년 얘므새의 가난한 농업노동자 집안에서 태어나 1903년 러시아 군에 들어갔고, 러일전쟁에 중위로 참전한 뒤 1905년 혁명의 사회주의자들과 어울리다 모스크바에서 투옥되고 군에서 쫓겨났다. 핀란드로 돌아와 투르쿠·비푸리·코트카의 노동 신문에서 일하며 사회민주당 당직도 맡았다. 1917년 10월 헬싱키에서 노동자 질서수비대를 조직했고, 11월 총파업 뒤 그 총사령관이 되었다. 1918년 1월 페트로그라드에서 술에 빠지고도 볼셰비키에게서 무기와 탄약을 대량으로 사들였으나, 1월 28일 에로 하팔라이넨으로 교체되었다. 탐페레 전투 마지막 밤 포위를 뚫고 나왔지만 라흐티 부근에서 붙잡혀 1918년 5월 헨날라 수용소에서 총살되었다.',
            'Born in 1884 to a poor land worker’s family in Jämsä, he joined the Russian Army in 1903, served as a lieutenant in the Russo-Japanese War, joined the socialists in the 1905 revolution, and was jailed in Moscow and expelled from the military. Back in Finland he worked for the labour press in Turku, Vyborg and Kotka and as a Social Democratic party official. In October 1917 he organised the Workers’ Order Guards in Helsinki and after the November general strike became their commander-in-chief. In January 1918, despite heavy drinking in Petrograd, he bought a large cargo of guns and ammunition from the Bolsheviks, but on 28 January he was replaced by Eero Haapalainen. He broke out of besieged Tampere on the battle’s last night, was captured near Lahti and was shot at the Hennala camp in May 1918.'],
        fate: ['executed', '총살', 'Executed by shooting'],
        aliases: { ko: ['알렉시 알토넨'], en: ['Aleksi Aaltonen'] },
        sources: [S.aaltonen, S.aaltonenFI],
        facts: {
            years: { claim: '1884–1918', locator: 'lead', excerpt: '2 August 1884 – May 1918' },
            citizenship: { claim: 'Finnish journalist', locator: 'lead', excerpt: 'was a Finnish journalist and former lieutenant of the Russian Imperial Army' },
            nationalOrigin: { claim: 'born in Jämsä, Finland', locator: 'Early years', excerpt: "Aaltonen was born to a poor land worker's family in Jämsä." },
            bio: [
                { claim: 'joined the Russian Army in 1903', locator: 'Early years', excerpt: 'Aaltonen dropped out of high school in 1903 and joined the Russian Army.' },
                { claim: 'lieutenant in the Russo-Japanese War; socialist in 1905', locator: 'Early years', excerpt: 'In 1904–1905 he served as a lieutenant in the Russo-Japanese War and was later affiliated with the socialist groups of the Russian revolution of 1905.' },
                { claim: 'jailed in Moscow and expelled from the military', locator: 'Early years', excerpt: 'Aaltonen was jailed in Moscow and expelled from the military' },
                { claim: 'labour journalist in Turku, Vyborg and Kotka', locator: 'Early years', excerpt: 'After his release, Aaltonen returned to Finland and worked for the labour press in Turku, Vyborg and Kotka.' },
                { claim: 'Social Democratic party official', locator: 'Early years', excerpt: 'He also worked as a party official for the Social Democrats.' },
                { claim: 'organised the Workers’ Order Guards in October 1917', locator: 'In the Finnish Civil War', excerpt: "In October 1917, Aaltonen was in Helsinki organizing the Workers' Order Guards, which soon became the Red Guards." },
                { claim: 'elected commander-in-chief after the November strike', locator: 'In the Finnish Civil War', excerpt: 'After the general strike in November, he was elected the commander-in-chief of the Order Guards as Adolf Taimi refused.' },
                { claim: 'bought arms from the Bolsheviks in Petrograd', locator: 'In the Finnish Civil War', excerpt: 'Despite his heavy drinking in Saint Petersburg, which was known as Petrograd at the time, Aaltonen managed to buy a large cargo of guns and ammunition from the Bolsheviks.' },
                { claim: 'replaced by Haapalainen on 28 January', locator: 'In the Finnish Civil War', excerpt: 'Finally, on 28 January, Aaltonen was replaced by Eero Haapalainen.' },
                { claim: 'broke out of besieged Tampere', locator: 'In the Finnish Civil War', excerpt: 'On the night between the 5 and 6 April, Aaltonen led a unit of Reds that managed to break through the enemy siege and fled across the ice of lake Näsijärvi.' },
                { claim: 'way closed near Lahti', locator: 'In the Finnish Civil War', excerpt: 'At the end of April, their way was closed by the German troops in the village of Nastola near Lahti.' },
                { claim: 'shot at the Hennala camp, May 1918', locator: 'In the Finnish Civil War', excerpt: 'Aaltonen was captured and taken to the Hennala camp, where he was shot by the Estonian colonel Hans Kalm in May 1918.' },
                { claim: 'Finnish source: captured on 11 May in Hollola', source: S.aaltonenFI, locator: 'Pako Tampereelta ja kuolema', excerpt: 'hänet vangittiin lauantaina 11. toukokuuta Hollolan pitäjän Miekkiön kylästä' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: null, startYear: 1917, endYear: 1918, primary: true, claim: 'First commander-in-chief of the Finnish Red Guards (no catalog affiliation)', locator: 'lead', excerpt: 'who served as the first commander-in-chief of the Finnish Red Guards from November 1917 to the end of January 1918' },
            { functionId: 'military', affiliationId: 'russian-empire', startYear: 1903, endYear: 1905, claim: 'Lieutenant in the Imperial Russian Army in the Russo-Japanese War', locator: 'Early years', excerpt: 'In 1904–1905 he served as a lieutenant in the Russo-Japanese War' },
            { functionId: 'organizing', affiliationId: 'party-finnish-social-democratic', startYear: null, endYear: 1917, claim: 'Party official and labour journalist for the Social Democrats', locator: 'Early years', excerpt: 'He also worked as a party official for the Social Democrats.' },
        ],
        career: [
            ['1904–1905', '러시아 군 중위로 러일전쟁 참전', 'Lieutenant in the Russian Army in the Russo-Japanese War'],
            ['1917', '헬싱키 노동자 질서수비대 조직', 'Organiser of the Workers’ Order Guards in Helsinki'],
            ['1917–1918', '노동자 질서수비대·적위대 초대 총사령관', 'First commander-in-chief of the Order Guards and Red Guards'],
            ['1918', '적위대 참모부, 해메 전선 참모', 'Red Guard general staff; staff of the Häme Front'],
        ],
    })),
    unaffiliated(person({
        id: 'eero-haapalainen', groupId: 'world-interwar',
        given: ['에로', 'Eero'], family: ['하팔라이넨', 'Haapalainen'], nativeName: 'Eero Haapalainen', years: '1880–1937',
        citizenship: 'soviet', origin: 'finland',
        epithet: ['1918년 1~3월 핀란드 적위대 총사령관을 지낸 노동조합 지도자',
            'Trade union leader who commanded the Finnish Red Guards from January to March 1918'],
        bio: ['1880년 쿠오피오에서 태어나 헬싱키 대학 법학부를 다니다 노동운동에 뛰어들었다. 1905년 총파업 때 헬싱키 적위대 조직자의 한 사람이었고, 1907년 핀란드 노동조합연맹 초대 의장이 되었으나 1911년 음주 문제로 물러났다. 1917년 무장 혁명을 공공연히 주장한 급진파로 적위대 5인 위원회에 뽑혔고, 1918년 1월 군사 훈련도 없이 알리 알토넨의 뒤를 이어 적위대 총사령관이 되었다. 잇단 패배로 3월 20일 해임된 뒤 에드바르드 귈링과 비푸리 방어를 조직하다 5월 페트로그라드로 탈출했다. 망명 핀란드 공산당 창당에 참여했고 카렐리야 노동 코뮌에서 일했으나, 1937년 대숙청 때 체포되어 페트로자보츠크에서 총살되었다.',
            'Born in Kuopio in 1880, he joined the labour movement while studying law at Helsinki University. He was one of the leading Red Guard organisers in Helsinki during the 1905 general strike and in 1907 became the first chairman of the Finnish Trade Union Federation, losing the post in 1911 over his drinking. One of the most radical voices of 1917, openly calling for armed revolution, he was elected to the five-man committee of the Red Guards and in January 1918, without any military training, succeeded Ali Aaltonen as their commander-in-chief. Removed on 20 March after a series of defeats, he organised the defence of Viipuri with Edvard Gylling and escaped to Petrograd in May. He helped found the exiled Communist Party of Finland and worked in the Karelian Workers’ Commune, but was arrested in the Great Purge and shot in Petrozavodsk in 1937.'],
        fate: ['executed', '총살', 'Executed by shooting'],
        aliases: { ko: [], en: [] },
        sources: [S.haapa],
        facts: {
            years: { claim: '1880–1937', locator: 'lead', excerpt: '27 October 1880 – 27 November 1937' },
            citizenship: { claim: 'fled to Soviet Russia and lived in Soviet Karelia', locator: 'lead', excerpt: "Haapalainen fled to Soviet Russia in May 1918 after the Reds' defeat where he joined the exile Communist Party of Finland and was active in Soviet Karelia." },
            nationalOrigin: { claim: 'born in Kuopio, Finland', locator: 'Early years', excerpt: 'Eero Haapalainen was born on 27 October 1880 in the town of Kuopio in eastern Finland.' },
            bio: [
                { claim: 'entered the Helsinki law faculty in 1901', locator: 'Early years', excerpt: 'entered the Helsinki University Faculty of Law in 1901' },
                { claim: 'joined the labour movement and the Social Democratic Party', locator: 'Early years', excerpt: "In Helsinki, he became involved with the labour movement and joined the Sawmill Workers' Union and the Social Democratic Party of Finland." },
                { claim: 'Red Guard organiser in 1905', locator: 'Early years', excerpt: 'Haapalainen was one of the leading Red Guard organizers in Helsinki during the 1905 general strike.' },
                { claim: 'first chairman of SAJ, 1907', locator: 'Early years', excerpt: 'In April 1907, Haapalainen was elected as the first chairman of the Finnish Trade Union Federation (SAJ)' },
                { claim: 'expelled from the office in 1911', locator: 'Early years', excerpt: 'Haapalainen was expelled from the office in 1911 due to his alcoholism.' },
                { claim: 'radical calling for armed revolution', locator: 'Finnish Civil War', excerpt: 'Haapalainen was one of the most radical persons in the labour movement, openly calling for armed revolution' },
                { claim: 'elected to the five-man Red Guard committee', locator: 'Finnish Civil War', excerpt: 'A month later, Haapalainen was elected to the five-men committee which was in charge of all Finnish Red Guards.' },
                { claim: 'replaced Aaltonen without military training', locator: 'Finnish Civil War', excerpt: "Haapalainen replaced Ali Aaltonen as the Red Guards' commander-in-chief, even though he did not have any military training." },
                { claim: 'removed on 20 March', locator: 'Finnish Civil War', excerpt: 'On 20 March, Haapalainen was removed as commander-in-chief of the Red Guards after a series of defeats.' },
                { claim: 'organised the defence of Viipuri with Gylling', locator: 'Finnish Civil War', excerpt: "Haapalainen and Edvard Gylling were one of the few leading Reds who stayed in Viipuri and organized the city's defense" },
                { claim: 'fled to Petrograd in May', locator: 'Finnish Civil War', excerpt: 'in May, fled to Petrograd on a motor boat' },
                { claim: 'co-founder of the exiled Communist Party of Finland', locator: 'Life in the Soviet Union', excerpt: 'was also one of the founders of the exile Communist Party of Finland in August 1918' },
                { claim: 'posts in the Karelian Workers’ Commune', locator: 'Life in the Soviet Union', excerpt: "He held several posts in the Karelian Workers' Commune but was dismissed in 1923 due to his drinking problem." },
                { claim: 'shot in Petrozavodsk, 27 November 1937', locator: 'Death', excerpt: 'On 27 November 1937, Haapalainen was shot in Petrozavodsk.' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: null, startYear: 1918, endYear: 1918, primary: true, claim: 'Commander-in-chief of the Finnish Red Guards (no catalog affiliation)', locator: 'lead', excerpt: 'who served as the commander-in-chief of the Red Guards from January to March 1918 during the Finnish Civil War' },
            { functionId: 'organizing', affiliationId: 'party-finnish-social-democratic', relation: 'membership', startYear: null, endYear: 1918, claim: 'Member of the Social Democratic Party of Finland', locator: 'Early years', excerpt: "joined the Sawmill Workers' Union and the Social Democratic Party of Finland" },
            { functionId: 'organizing', affiliationId: null, startYear: 1907, endYear: 1911, claim: 'First chairman of the Finnish Trade Union Federation (no catalog affiliation)', locator: 'Early years', excerpt: 'In April 1907, Haapalainen was elected as the first chairman of the Finnish Trade Union Federation (SAJ)' },
            { functionId: 'political-leadership', affiliationId: 'party-finnish-communist', relation: 'membership', startYear: 1918, endYear: 1925, claim: 'Co-founder of the exiled Communist Party of Finland', locator: 'Life in the Soviet Union', excerpt: 'was also one of the founders of the exile Communist Party of Finland in August 1918' },
            { functionId: 'government', affiliationId: 'state-soviet', startYear: 1920, endYear: 1923, claim: 'Several posts in the Karelian Workers’ Commune', locator: 'Life in the Soviet Union', excerpt: "He held several posts in the Karelian Workers' Commune" },
            { functionId: 'scholarship', affiliationId: 'state-soviet', startYear: 1931, endYear: 1935, claim: 'Head of the revolution research department of the Karelian Research Institute', locator: 'Life in the Soviet Union', excerpt: 'his last assignment was the head of the revolution research department in the Karelian Research Institute in Petrozavodsk' },
        ],
        career: [
            ['1907–1911', '핀란드 노동조합연맹(SAJ) 초대 의장', 'First chairman of the Finnish Trade Union Federation (SAJ)'],
            ['1917', '퀴미 제지공장 적위대 사령관, 적위대 5인 위원회 위원', 'Commander of the Kymi Paper Mill Red Guard; member of the five-man Red Guard committee'],
            ['1918', '적위대 총사령관, 인민대표위원회 위원', 'Commander-in-chief of the Red Guards; member of the People’s Delegation'],
            ['1920–1923', '카렐리야 노동 코뮌의 여러 직책', 'Several posts in the Karelian Workers’ Commune'],
            ['1931–1935', '카렐리야 연구소 혁명사 연구부장', 'Head of the revolution research department, Karelian Research Institute'],
        ],
    })),
    unaffiliated(person({
        id: 'oskari-tokoi', groupId: 'world-interwar',
        given: ['오스카리', 'Oskari'], family: ['토코이', 'Tokoi'], nativeName: 'Oskari Tokoi', years: '1873–1963',
        citizenship: 'finland', origin: 'finland',
        epithet: ['세계 최초의 사회민주주의자 정부 수반이 되었다가 적색 정부에 참여한 핀란드 노동 지도자',
            'Finnish labour leader who became the world’s first Social Democratic head of government and then joined the Red government'],
        bio: ['1873년 중부 포흐얀마의 칸누스에서 태어나 17살에 미국으로 건너가 광산에서 일하며 급진적 서부광부연맹에 들었다. 1900년 돌아와 1907년 사회민주당 의원이 되었고, 1912~1917년 핀란드 노동조합연맹 의장, 1913년 의회 의장을 지냈다. 1917년 상원 경제부 부의장, 곧 세계 최초의 사회민주주의 총리가 되었다. 내전 때 인민대표위원회 식량 위원을 맡아 소비에트 러시아와의 3월 1일 조약에 서명했고, 패전 뒤 러시아로 피했다. 1919~1920년 영국이 꾸린 무르만스크 군단의 정치 고문이 되어 핀란드 공산당에게서 사형 선고를 받았다. 1922~1949년 미국에서 사회민주주의 신문 『라이바야』를 만들었고, 1944년 「토코이 법」으로 내전 관련 혐의를 벗었다.',
            'Born in Kannus in Central Ostrobothnia in 1873, he emigrated to America at 17, worked in the mines and joined the radical Western Federation of Miners. Back in Finland from 1900, he entered Parliament for the Social Democrats in 1907, chaired the Finnish Trade Union Federation in 1912–1917 and was Speaker in 1913. In 1917 he became vice-chairman of the Senate’s economic department, the world’s first social democratic prime minister. In the civil war he was commissar for supply in the People’s Delegation, signed the 1 March treaty with Soviet Russia and fled to Russia after the defeat. In 1919–1920 he advised the British-organised Murmansk Legion, for which the Communist Party of Finland sentenced him to death. From 1922 to 1949 he edited the social democratic paper Raivaaja in the United States, and the 1944 Lex Tokoi cleared him of the civil war charges.'],
        fate: ['natural', '자연사', 'Natural causes'],
        aliases: { ko: ['안티 오스카리 토코이', '안티 오스카리 히르비'], en: ['Antti Oskari Tokoi', 'Antti Oskari Hirvi'] },
        sources: [S.tokoi, S.tokoiFI, S.gylling],
        facts: {
            years: { claim: '1873–1963', locator: 'lead', excerpt: '15 April 1873 – 4 April 1963' },
            citizenship: { claim: 'Finnish socialist politician', locator: 'lead', excerpt: 'was a Finnish socialist politician who served as a leader of the Social Democratic Party of Finland' },
            nationalOrigin: { claim: 'born in Kannus, Central Ostrobothnia', locator: 'Early years', excerpt: 'Oskari Tokoi was born as Antti Oskari Hirvi in Yliviirre parish, Kannus in the Central Ostrobothnia region of Finland' },
            bio: [
                { claim: 'emigrated to America at 17', locator: 'Early years', excerpt: 'the 17-year old Oskari quit the family farm to emigrate to America' },
                { claim: 'miner; Western Federation of Miners', locator: 'First American interlude', excerpt: 'Tokoi worked in a series of coal and hard metal mines in Wyoming, Colorado, and the Dakota Territory, joining the radical Western Federation of Miners in connection with his employment.' },
                { claim: 'returned to Finland in 1900', locator: 'First American interlude', excerpt: 'Tokoi returned to Finland in 1900, where he worked as a farmer and a merchant.' },
                { claim: 'elected to Parliament in 1907', locator: 'Finnish political career', excerpt: 'In 1907 Tokoi was elected to the parliament (Eduskunta) as a representative of the Social Democrats.' },
                { claim: 'chairman of the Trade Union Federation 1912–1917', locator: 'Finnish political career', excerpt: 'From 1912 to 1917 he was the chairman of the Finnish Trade Union Federation.' },
                { claim: 'Speaker in 1913', locator: 'Finnish political career', excerpt: 'In 1913 Tokoi was elected as the speaker of the Eduskunta' },
                { claim: 'vice-chairman of the Senate’s economic department, first social democratic prime minister', source: S.tokoiFI, locator: 'Elämänvaiheet', excerpt: '1917 hänet nimitettiin Suomen Senaatin talousosaston varapuheenjohtajaksi. Tuolloin hänestä tuli maailman ensimmäinen sosiaalidemokraattinen pääministeri.' },
                { claim: 'commissar for supply in the People’s Delegation', locator: 'Finnish political career', excerpt: 'worked as the "commissar in charge of provisions" (minister for supply) in the Finnish People\'s Delegation' },
                { claim: 'signed the 1 March 1918 treaty', source: S.gylling, locator: 'Finnish Civil War', excerpt: 'by Gylling and Oskari Tokoi from the Finnish side' },
                { claim: 'fled to Russia after the war', locator: 'Finnish political career', excerpt: 'After the war, fearing punishment from the victorious Whites, he fled to Russia.' },
                { claim: 'political advisor to the Murmansk Legion 1919–1920', locator: 'Final emigration', excerpt: 'During 1919 and 1920, he worked as a political advisor to the Murmansk Legion' },
                { claim: 'death sentence from the Communist Party of Finland', source: S.tokoiFI, locator: 'Elämänvaiheet', excerpt: 'Vasta perustettu Suomen Kommunistinen Puolue (SKP) langetti Kuusisen johdolla Tokoille ja tämän kumppaneille kuolemantuomion, jota ei koskaan peruttu.' },
                { claim: 'editor of Raivaaja 1922–1949', source: S.tokoiFI, locator: 'Elämänvaiheet', excerpt: 'Raivaaja-lehden toimittajana vuosina 1922–1949' },
                { claim: 'Lex Tokoi, 1944', locator: 'Final emigration', excerpt: 'In 1944, the Finnish Parliament passed the so-called Lex Tokoi, by which Tokoi was exonerated of all charges related to the Finnish Civil War.' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-finland', startYear: 1917, endYear: 1917, primary: true, source: S.tokoiFI, claim: 'Vice-chairman of the Senate’s economic department (head of government), 1917', locator: 'Elämänvaiheet', excerpt: '1917 hänet nimitettiin Suomen Senaatin talousosaston varapuheenjohtajaksi' },
            { functionId: 'legislature', affiliationId: 'state-finland', startYear: 1913, endYear: 1913, claim: 'Speaker of the Eduskunta', locator: 'Finnish political career', excerpt: 'In 1913 Tokoi was elected as the speaker of the Eduskunta' },
            { functionId: 'political-leadership', affiliationId: 'party-finnish-social-democratic', relation: 'membership', startYear: 1907, endYear: 1918, claim: 'Leader of the Social Democratic Party of Finland', locator: 'lead', excerpt: 'who served as a leader of the Social Democratic Party of Finland' },
            { functionId: 'organizing', affiliationId: null, startYear: 1912, endYear: 1917, claim: 'Chairman of the Finnish Trade Union Federation (no catalog affiliation)', locator: 'Finnish political career', excerpt: 'From 1912 to 1917 he was the chairman of the Finnish Trade Union Federation.' },
            { functionId: 'economy', affiliationId: null, startYear: 1918, endYear: 1918, claim: 'Commissar for supply in the Finnish People’s Delegation (no catalog affiliation)', locator: 'Finnish political career', excerpt: 'worked as the "commissar in charge of provisions" (minister for supply) in the Finnish People\'s Delegation' },
        ],
        career: [
            ['1907–1918', '핀란드 의회 의원(사회민주당)', 'Social Democratic member of the Parliament of Finland'],
            ['1912–1917', '핀란드 노동조합연맹 의장', 'Chairman of the Finnish Trade Union Federation'],
            ['1913', '핀란드 의회 의장', 'Speaker of the Parliament of Finland'],
            ['1917', '상원 경제부 부의장(정부 수반)', 'Vice-chairman of the Senate’s economic department (head of government)'],
            ['1918', '인민대표위원회 식량 위원', 'Commissar for supply, Finnish People’s Delegation'],
            ['1919–1920', '무르만스크 군단 정치 고문', 'Political adviser to the Murmansk Legion'],
            ['1922–1949', '미국 『라이바야』 편집인', 'Editor of Raivaaja in the United States'],
        ],
    })),
    unaffiliated(person({
        id: 'eino-rahja', groupId: 'world-interwar',
        given: ['에이노', 'Eino'], family: ['라흐야', 'Rahja'], nativeName: 'Eino Rahja', years: '1885–1936',
        citizenship: 'soviet', origin: 'finland',
        epithet: ['레닌의 핀란드 피신을 도왔고 1918년 적위대 3인 지도부에 든 페테르부르크 핀란드인 볼셰비키',
            'Petrograd Finnish Bolshevik who helped Lenin escape to Finland in 1917 and sat on the Red Guards’ three-man command in 1918'],
        bio: ['1885년 크론시타트의 핀란드인 노동자 집안에서 태어나 페테르부르크에서 선반공으로 일했고, 1903년 러시아 사회민주노동당에 들어가 볼셰비키 편에 섰다. 1917년 여름 레닌의 핀란드 피신을 조직했고, 10월 혁명 무렵 레닌의 경호를 맡았다. 1917~1918년 겨울 동생 유카와 함께 핀란드 적위대의 무기를 구해 왔고, 1918년 3월 20일 하팔라이넨이 해임되자 에베르트 엘로란타·아돌프 타이미와 3인 지도부를 이루었다가 렘팰래 전선 사령관이 되었다. 패전 뒤 붉은 군대 군단장까지 올랐고, 핀란드 공산당에서 쿠시넨·만네르와 다투다 1927년 중앙위원회에서 밀려났다. 1935년 알코올 중독으로 군에서 쫓겨나 사형 선고를 받았으나 1936년 집행 전 결핵으로 죽었다.',
            'Born in Kronstadt in 1885 to a Petersburg Finnish working family, he worked in St Petersburg as a turner among other jobs and joined the Russian Social Democratic Labour Party in 1903, siding with the Bolsheviks. He organised Lenin’s escape to Finland in the summer of 1917 and guarded him around the October Revolution. Over the winter of 1917–1918 he and his brother Jukka procured arms for the Finnish Red Guards; when Haapalainen was dismissed on 20 March 1918 he formed a three-man command with Evert Eloranta and Adolf Taimi, then took over the Lempäälä front. After the defeat he rose to corps commander in the Red Army and quarrelled with Kuusinen and Manner in the Communist Party of Finland, which dropped him from its Central Committee in 1927. Expelled from the army for alcoholism in 1935 and sentenced to death, he died of tuberculosis in 1936 before the sentence was carried out.'],
        fate: ['natural', '사형 집행 전 병사', 'Died of illness before execution'],
        aliases: { ko: ['에이노 에이나리 라흐야'], en: ['Eino Einari Rahja'] },
        sources: [S.rahja, S.rahjaFI],
        facts: {
            years: { claim: '1885–1936', locator: 'lead', excerpt: '20 June 1885 – 26 April 1936' },
            citizenship: { claim: 'lived in Soviet Russia and served in the Red Army', locator: 'Life', excerpt: 'he fled to the Russian SFSR where he lived for the rest of his life' },
            nationalOrigin: { claim: 'Petersburg Finn', source: S.rahjaFI, locator: 'johdanto', excerpt: 'oli pietarinsuomalainen bolševikki ja puna-armeijan upseeri' },
            bio: [
                { claim: 'born in Kronstadt', locator: 'Life', excerpt: 'Born in Kronstadt, Russian Empire' },
                { claim: 'worked as a turner in St Petersburg', source: S.rahjaFI, locator: 'Venäjän vallankumous ja Suomen sisällissota', excerpt: 'Rahja työskenteli Pietarissa sorvarina' },
                { claim: 'joined the RSDLP in 1903, Bolshevik', locator: 'Life', excerpt: "He joined the Russian Social Democratic Labour Party in 1903, becoming aligned with the party's Bolshevik faction." },
                { claim: 'organised Lenin’s escape to Finland in 1917', locator: 'Life', excerpt: "Rahja organized Lenin's temporary escape to Finland in the summer of 1917." },
                { claim: 'Lenin’s bodyguard in October 1917', source: S.rahjaFI, locator: 'johdanto', excerpt: 'Rahja toimi V. I. Leninin henkilökohtaisena turvamiehenä ja henkivartijana' },
                { claim: 'procured arms for the Red Guards with his brother Jukka', source: S.rahjaFI, locator: 'Venäjän vallankumous ja Suomen sisällissota', excerpt: 'Vuodenvaihteessa 1917–1918 Eino ja Jukka Rahja hankkivat Suomen punakaarteille aseita.' },
                { claim: 'three-man command after Haapalainen, 20 March 1918', source: S.rahjaFI, locator: 'Venäjän vallankumous ja Suomen sisällissota', excerpt: '20. maaliskuuta punakaartin ylipäällikkö Eero Haapalainen erotettiin ja tilalle nimitettiin Rahjan, Evert Elorannan ja Adolf Taimin muodostama kolmikko.' },
                { claim: 'commander of the Lempäälä front from 24 March', source: S.rahjaFI, locator: 'Venäjän vallankumous ja Suomen sisällissota', excerpt: 'kun hän 24. maaliskuuta alkaen toimi Lempäälän rintaman ylipäällikkönä' },
                { claim: 'one of the most capable Red military leaders', locator: 'Life', excerpt: 'During the Finnish Civil War, Rahja was one of the most capable military leaders of the Reds.' },
                { claim: 'corps commander in the Red Army', locator: 'Life', excerpt: 'became, for example, a commander of the army corps (komkor) in the Red Army' },
                { claim: 'criticised Kuusinen and Manner', source: S.rahjaFI, locator: 'Sisällissodan jälkeen', excerpt: 'Rahjat puolestaan arvostelivat SKP:n johtohahmoja, kuten Otto Wille Kuusista ja Kullervo Mannerta.' },
                { claim: 'expelled from the SKP Central Committee in 1927', locator: 'Life', excerpt: 'Eino Rahja was expelled from the Central Committee of the Communist Party of Finland in 1927.' },
                { claim: 'expelled from the army, sentenced to death, died of tuberculosis', locator: 'Life', excerpt: 'Rahja was expelled from the army in 1935 for his alcoholism and later sentenced to death in 1936, however, he died in April 1936 from tuberculosis and alcohol abuse, before he could be executed.' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: null, startYear: 1918, endYear: 1918, primary: true, source: S.rahjaFI, claim: 'Member of the three-man command of the Finnish Red Guards; commander of the Lempäälä front (no catalog affiliation)', locator: 'Venäjän vallankumous ja Suomen sisällissota', excerpt: 'tilalle nimitettiin Rahjan, Evert Elorannan ja Adolf Taimin muodostama kolmikko' },
            { functionId: 'organizing', affiliationId: 'soviet-party', relation: 'membership', startYear: 1903, endYear: 1917, claim: 'Bolshevik member of the RSDLP from 1903; organised Lenin’s escape in 1917', locator: 'Life', excerpt: "He joined the Russian Social Democratic Labour Party in 1903, becoming aligned with the party's Bolshevik faction." },
            { functionId: 'military', affiliationId: 'state-soviet', startYear: 1918, endYear: 1935, claim: 'Red Army commander, rising to komkor', locator: 'Life', excerpt: 'became, for example, a commander of the army corps (komkor) in the Red Army' },
            { functionId: 'political-leadership', affiliationId: 'party-finnish-communist', relation: 'membership', startYear: 1918, endYear: 1927, claim: 'Leading member of the Communist Party of Finland until dropped from its Central Committee in 1927', locator: 'Life', excerpt: 'Eino Rahja was expelled from the Central Committee of the Communist Party of Finland in 1927.' },
        ],
        career: [
            ['1903', '러시아 사회민주노동당 입당(볼셰비키)', 'Joined the RSDLP (Bolshevik)'],
            ['1917', '레닌의 핀란드 피신 조직, 레닌 경호', 'Organised Lenin’s escape to Finland; Lenin’s bodyguard'],
            ['1918', '적위대 3인 지도부, 렘팰래 전선 사령관', 'Three-man command of the Red Guards; commander of the Lempäälä front'],
            ['1919–1922', '붉은 군대 핀란드인 부대 정치위원·감찰관', 'Commissar and inspector of the Red Army’s Finnish units'],
            ['1918–1927', '핀란드 공산당 지도부', 'Leadership of the Communist Party of Finland'],
            ['1935', '붉은 군대에서 해임', 'Expelled from the Red Army'],
        ],
    })),
];
