// Glossary terms for the finland-1917-1920 event (2026-10-04), built with
// lib.js term(). Facts come from the en/fi/ru Wikipedia pages listed in each
// term's sources (fetched 2026-10-04).
//
// original (원어명):
//   finnish-red-guards               Punakaarti (sv. Röda gardet); 1918: Suomen Punainen Kaarti
//   finnish-white-guard              Suojeluskunta (sv. Skyddskår)
//   peoples-delegation-of-finland    Suomen kansanvaltuuskunta
//   battle-of-tampere                Tampereen taistelu
//   heimosodat                       heimosodat (sg. heimosota)
//   treaty-of-tartu-finland-1920     Tarton rauha (ru. Тартуский мирный договор; sv. Fredsfördraget i Dorpat)
//   kingdom-of-finland-1918          Suomen kuningaskunta (sv. Konungariket Finland)
//
// The Russian Red Guards already have the term red-guards (적위대); the
// Finnish body is a separate entry and never takes the bare 적위대 / Red Guards.
// The Treaty of Tartu here is the Finnish–Soviet one of 14 October 1920; the
// bare 타르투 조약 / Treaty of Tartu is left out because the Estonian–Soviet
// treaty of February 1920 shares it.
const { term } = require('../lib');

const E = t => 'https://en.wikipedia.org/wiki/' + encodeURI(t);
const FI = t => 'https://fi.wikipedia.org/wiki/' + encodeURI(t);
const RU = t => 'https://ru.wikipedia.org/wiki/' + encodeURI(t);
const S = {
    redg: E('Red_Guards_(Finland)'),
    whiteg: E('White_Guard_(Finland)'),
    fswr: E("Finnish_Socialist_Workers'_Republic"),
    delegationFI: FI('Suomen_kansanvaltuuskunta'),
    tampere: E('Battle_of_Tampere'),
    tampereFI: FI('Tampereen_taistelu'),
    heimo: E('Heimosodat'),
    heimoFI: FI('Heimosodat'),
    tartu: E('Treaty_of_Tartu_(Finland–Russia)'),
    tartuFI: FI('Tarton_rauha'),
    tartuRU: RU('Тартуский_мирный_договор_между_РСФСР_и_Финляндией'),
    kingdom: E('Kingdom_of_Finland'),
    pres1919: E('1919_Finnish_presidential_election'),
};

module.exports = [
    term({
        id: 'finnish-red-guards', ko: '핀란드 적위대', en: 'Finnish Red Guards', category: 'party-state', period: '1905–1920', startYear: 1905, endYear: 1920,
        definition: ['핀란드 노동운동의 준군사 조직. 1905년 총파업 때 처음 생겼다가 이듬해 해산되었고, 1917년 2월 혁명 뒤 노동자 질서수비대로 다시 조직되었다. 1918년 1월 헬싱키 적위대와 합쳐 「핀란드 적위대」가 되어 내전에서 적색 핀란드의 군대로 싸웠으나 5월 백군과 독일군에 패했고, 1920년까지 조직된 세력으로서 사라졌다.',
            'The paramilitary units of the Finnish labour movement. First formed during the 1905 general strike and disbanded the following year, they were re-established as the Workers’ Order Guards after the February Revolution of 1917. In January 1918 they merged with the Helsinki Red Guard into the Red Guard of Finland, which fought as the army of Red Finland in the civil war until its defeat by the Whites and the Germans in May; by 1920 it had ceased to exist as an organised force.'],
        body: ['1905년 총파업 때 치안을 맡은 국민수비대가 노동계급의 적위대와 부르주아 쪽 보호대로 갈라졌고, 1906년 8월 스베아보리 반란 중 하카니에미에서 두 조직이 총격전을 벌인 뒤 상원은 둘 다 금지했다. 1917년 여름 식량난 속 농업 파업과 7월 13일 후이티넨 충돌 뒤 우익 농민들이 보호대를 만들자, 노동운동은 노동자 질서수비대로 맞섰다. 10월 20일 노동조합연맹의 호소 뒤 3주 만에 수비대는 237개, 3만 명을 넘었고 11월 총파업이 끝날 무렵 4만~5만 명이 되었다. 러시아 제국 군 중위 출신 기자 알리 알토넨이 첫 총사령관이었다. 1918년 1월 6일 헬싱키 수비대가 사회민주당에서 독립해 헬싱키 적위대로 이름을 바꾸었고, 1월 25일 상원이 보호대를 정부군으로 선언하자 노동운동은 이를 노동계급에 대한 선전포고로 받아들였다. 수비대들은 「핀란드 적위대」로 통합되었고, 26일 밤 헬싱키 노동자회관 탑에 붉은 등을 켜 혁명을 알렸다.\n\n지휘권은 알토넨에서 에로 하팔라이넨으로, 3월 20일 에이노 라햐·아돌프 타이미·에베르트 엘로란타의 3인 지도부로, 4월 10일 독재 권한을 받은 쿨레르보 만네르에게로 넘어갔다. 영어 출처는 전력을 개전 때 3만~4만 명, 절정기 8만~12만 명으로 추산하며, 여기에는 여성 전투원 2,000~2,600명이 포함된다. 대원은 산업 노동자와 토지 없는 농촌 노동자, 소작농이었고, 장교를 선거로 뽑아 규율이 느슨했으며 무기 대부분을 러시아 군에게서 얻었다. 이름은 같지만 러시아의 적위대와는 따로 핀란드 사회민주당 지역 조직과 노동조합을 통해 모집된 조직이었고, 러시아인의 참여는 적었다. 핀란드에 남아 있던 러시아 제국 군과 발트 함대 병력 약 4만 명 가운데 적위대에 들어간 사람은 장교 수십 명을 포함해 수백 명뿐이었고, 대부분은 귀국만을 바랐다. 알토넨이 볼셰비키에게서 사들인 소총 1만 5천 정 등을 실은 열차가 2월 초 도착했다. 탐페레에서 1만~1만 1천 명이 포로가 되었고, 전쟁이 끝난 뒤 약 8만 명이 포로가 되어 1만 2천~1만 4천 명이 수용소에서 병과 영양실조, 처형으로 죽었다. 1만~1만 3천 명은 소비에트 러시아로 피했고, 그 일부는 영국이 만든 무르만스크 군단이나 에스토니아 독립전쟁에 나선 붉은 군대 제7군에서 핀란드 백군 의용병과 싸웠다.',
            'During the 1905 general strike the National Guard set up to keep order split into the working-class Red Guards and the bourgeois Protection Corps; after the two clashed in a gunfight at Hakaniemi during the Sveaborg rebellion in August 1906, the Senate banned both. In the summer of 1917, amid food shortages and farm strikes, right-wing farmers began forming Protection Guards after the Huittinen clash of 13 July, and the labour movement answered with the Workers’ Order Guards. Within three weeks of the Trade Union Federation’s appeal of 20 October they numbered 237 guards with more than 30,000 members, and 40,000–50,000 by the end of the November general strike. The journalist Ali Aaltonen, a former lieutenant of the Imperial Russian Army, was their first commander-in-chief. On 6 January 1918 the Helsinki guard broke away from the Social Democratic Party as the Helsinki Red Guard, and when the Senate declared the Protection Corps government troops on 25 January the labour movement took it as a declaration of war on the working class. The guards merged into the Red Guard of Finland, and on the night of 26 January a red lantern lit on the tower of the Helsinki Workers’ Hall proclaimed the revolution.\n\nCommand passed from Aaltonen to Eero Haapalainen, on 20 March to the troika of Eino Rahja, Adolf Taimi and Evert Eloranta, and on 10 April to Kullervo Manner with dictatorial powers. The English-language source puts their strength at 30,000–40,000 at the outbreak and 80,000–120,000 at the peak, including 2,000–2,600 women fighters. The fighters were industrial workers, landless rural labourers and crofters; officers were elected, discipline was lax and most weapons came from the Russian troops. Despite the shared name they were recruited apart from the Russian Red Guards, through the local sections of the Finnish Social Democratic Party and the labour unions, and Russian participation was low: of some 40,000 soldiers of the Imperial Russian Army and the Baltic Fleet still in Finland, only a few hundred, including a few dozen officers, joined the Red Guards, and most simply wanted to go home. A train carrying 15,000 rifles and other arms that Aaltonen had bought from the Bolsheviks arrived in early February. At Tampere 10,000–11,000 were captured; after the war some 80,000 became prisoners, of whom 12,000–14,000 died in the camps of disease, malnutrition and execution. Between 10,000 and 13,000 fled to Soviet Russia, where some fought Finnish White volunteers in the British-raised Murmansk Legion or in the 7th Red Army during the Estonian War of Independence.'],
        aliases: { ko: ['푸나카르티', '핀란드 붉은 근위대'], en: ['Red Guards (Finland)', 'Finnish Red Guard', 'Red Guard of Finland', 'Punakaarti', 'Röda gardet'] },
        people: ['ali-aaltonen', 'eero-haapalainen', 'eino-rahja', 'carl-manner', 'edvard-gylling'],
        events: ['finland-1917-1920', 'civil-war', 'baltic-wars-of-independence'],
        sources: [S.redg], locator: 'lead; 1905 general strike and Sveaborg rebellion; 1917 re-establishment; 1918 Civil War (Commanders, Size, Organization, War); After the war',
    }),
    term({
        id: 'finnish-white-guard', ko: '핀란드 자위대', en: 'Finnish White Guard', category: 'party-state', period: '1917–1944', startYear: 1917, endYear: 1944,
        definition: ['1918년 핀란드 내전에서 적위대를 꺾은 백색 진영의 자원 민병대. 공식 명칭은 「수오옐루스쿤타」(보호대)였고 서방에서는 「백위대」로 불렸다. 1917년 여름부터 지역별로 생겨 1918년 1월 백군의 주축이 되었고, 내전 뒤 군의 자원 예비 조직으로 남았다가 1944년 11월 소련의 요구로 해산되었다.',
            'The volunteer militia of the White side that defeated the Red Guards in the Finnish Civil War of 1918. Officially the Suojeluskunta (Protection Corps or Civil Guard), it was known in the West as the White Guard. Formed locally from the summer of 1917, it made up the core of the White Army in January 1918, remained a voluntary part of the armed forces after the war and was disbanded in November 1944 at the Soviet Union’s demand.'],
        body: ['1905년 총파업 때 생긴 시민 경비대는 1906년 무렵 정파에 따라 갈라졌다. 1917년 2월 혁명으로 러시아의 권력이 무너지자 질서를 지키려는 경비대가 다시 생겼고, 적위대가 혁명적 러시아 부대에게서 무기를 얻은 반면 보호대는 스웨덴과 독일의 지지자들에게서 무기를 받았다. 1918년 1월 13일 의회의 비사회주의 다수파는 상원에 보호대로 경찰력을 꾸릴 권한을 주었고, 상원은 만네르헤임에게 이를 바탕으로 새 군대를 만들어 달라고 했다. 1월 27~28일 밤 보호대는 포흐얀마의 러시아 수비대를 무장해제하기 시작했다. 내전 초기 백군의 대부분은 보호대였지만, 독일에서 훈련받은 예거 약 1,900명과 스웨덴 의용병 1,200명이 장교를 맡은 징집병 부대가 곧 그만큼 늘어났고, 영어 출처는 이것이 승패를 가른 요인이었다고 본다. 적색 테러로 약 1,100명이 죽었고, 2004년 정부 위탁 조사에 따르면 백색 테러로 약 7,370명이 처형되거나 살해되었다(더 오래된 사회주의 계열 연구는 1만 명). 그 가혹함 때문에 적색 쪽은 이들을 「라흐타리카르티」(도살자 부대)라 불렀다.\n\n1918년 8월 2일 국가평의회 법령이 보호대에 법적 근거를 주었고, 1919~1934년에는 군의 자원 부분으로서 동원 때 별도 부대를 이루었다. 모든 기초자치단체에 지부가 있었고, 스키·사격·페사팔로 같은 체육 활동과 합창단·악단도 꾸렸다. 공식적으로는 정치적 중립이었지만 비공식적으로는 반좌파·반공·보수였으며 노동운동은 대체로 이를 배척했다. 1932년 라푸아 운동의 맨챌래 반란 때 일부가 가담했으나 대다수는 정부에 충성했다. 1934년 동원 체제가 바뀌며 독자적 무장 세력의 역할은 끝났고, 겨울전쟁 때 야전군 병력의 4분의 1을 보호대원이 차지했다. 1940년 2월 15일 보호대 지도부와 사회민주당이 공동 성명을 내 오랜 반목을 풀었다. 1944년 11월 소련의 요구로 해산되었고, 소련은 이를 파시스트 조직으로 여겼다.',
            'The civil guards formed during the 1905 general strike had split along party lines by 1906. When Russian power in Finland collapsed with the February Revolution of 1917, guards for protection and order sprang up again; the Red Guards got their arms from revolutionary Russian units, the White Guards from Swedish and German supporters. On 13 January 1918 the non-socialist majority in Parliament authorised the Senate to organise a police force of the White Guard, and the Senate asked Mannerheim to form a new army on that basis. During the night of 27–28 January the White Guards began disarming the Russian garrisons in Ostrobothnia. The Guards made up most of the White Army at first, but conscript units officered by some 1,900 German-trained Jägers and 1,200 Swedish volunteers soon matched them, which the English-language source counts as crucial to the outcome. The Red terror killed some 1,100 people; according to a government-commissioned study of 2004 the White terror executed or otherwise killed about 7,370 (older socialist-leaning studies say 10,000). Their ruthlessness earned them the name Lahtarikaarti, the Butcher Guard, among the Reds.\n\nA decree of the Council of State gave the Guard a legal basis on 2 August 1918, and from 1919 to 1934 it was a voluntary part of the army with its own formations in mobilisation. Every municipality had a chapter, which also ran skiing, shooting and pesäpallo, choirs and orchestras. Officially neutral, it was unofficially anti-leftist, anticommunist and conservative, and largely rejected by the labour movement. Some units joined the Lapua Movement’s Mäntsälä rebellion of 1932, but the majority stayed loyal to the government. The 1934 reform of the mobilisation system ended its role as a separate armed force, and in the Winter War Guard members made up a quarter of the field army. On 15 February 1940 the Guard leadership and the Social Democratic Party issued a joint statement that healed the old rift. The Guard was disbanded in November 1944 at the Soviet Union’s demand; the Soviet Union regarded it as a fascist organisation.'],
        aliases: { ko: ['수오옐루스쿤타', '핀란드 백위대', '핀란드 보호대'], en: ['White Guard (Finland)', 'Civil Guard (Finland)', 'Finnish Civil Guard', 'Suojeluskunta', 'Skyddskår', 'Protection Corps (Finland)'] },
        people: ['carl-gustaf-emil-mannerheim', 'pehr-evind-svinhufvud'],
        events: ['finland-1917-1920', 'civil-war', 'winter-war'],
        sources: [S.whiteg, S.redg], locator: 'lead; Historical context; The White Guards in the Civil War; The White Guards after the Civil War; Relations with politicians; Heritage',
    }),
    term({
        id: 'peoples-delegation-of-finland', ko: '핀란드 인민대표위원회', en: 'Finnish People’s Delegation', category: 'party-state', period: '1918', startYear: 1918, endYear: 1918,
        definition: ['핀란드 내전 때 적색 진영의 혁명 정부(1918년 1월 28일~4월 25일). 사회민주당 좌파 인사들로 구성되고 쿨레르보 만네르가 의장을 맡아, 스빈후부드의 상원과 의회를 밀어내고 헬싱키와 남부 핀란드에서 스스로 법령을 냈다. 그 국가는 흔히 적색 핀란드라 불리며, 「핀란드 사회주의 노동자 공화국」이라는 이름은 3월 1일 소비에트 러시아와 맺은 조약에만 나온다.',
            'The revolutionary government of the Reds in the Finnish Civil War (28 January – 25 April 1918). Made up of left-wing Social Democrats and chaired by Kullervo Manner, it pushed aside Svinhufvud’s Senate and Parliament and issued its own laws in Helsinki and southern Finland. Its state is usually called Red Finland; the name Finnish Socialist Workers’ Republic appears only in the treaty it signed with Soviet Russia on 1 March 1918.'],
        body: ['무장 혁명은 노동자 질서수비대 지도부와 1월 23일 사회민주당 당위원회에서 떨어져 나온 「핀란드 노동자 집행위원회」(의장 에로 하팔라이넨)가 결정했다. 1월 26~27일 밤 상원 의원과 의원 33명 등을 체포하라는 명령은 공개 포고가 먼저 퍼지는 바람에 실패했다. 인민대표위원회는 28일 세워져 그날 아침 시작된 봉기를 이끌었고, 명단은 하팔라이넨의 제안을 바탕으로 했다. 전 의회 의장 만네르가 의장, 전 상원 경제부 부의장 오스카리 토코이가 식량 위원을 맡았고, 영어 출처의 각료 명단에는 에드바르드 귈링(재정), 오토 빌레 쿠시넨(교육) 등이 있다. 위원회는 첫날 수도의 부르주아 신문을 모두 폐간했고(다른 도시는 며칠 뒤), 2월 2일 적위대를 국가가 유지하도록 정했으나 실제로는 거의 통제하지 못했다. 헬싱키에서 89차례, 비푸리에서 열 차례 가까이 회의를 열어 45개 법령을 냈는데, 1871년 파리 코뮌과 볼셰비키의 입법, 무엇보다 핀란드 노동운동의 이전 강령을 본보기로 삼았다. 2월 23일 주로 쿠시넨이 만든 헌법 초안에는 프롤레타리아 독재 개념이 없었고, 스위스·미국 헌법과 프랑스 혁명의 영향 아래 국민투표를 폭넓게 쓰는 민주적 사회주의를 그렸지만 끝내 채택되지 못했다.\n\n소비에트 러시아는 인민대표위원회를 핀란드의 합법 정부로 인정한 유일한 국가였다. 귈링이 주도한 협상 끝에 3월 1일 두 정부는 조약을 맺었는데, 국호에 「사회주의 노동자 공화국」을 넣자고 한 것은 레닌이었고 인민대표위원회는 뒤에 이를 받아들인 대표들을 탓했다. 적색 다수의 목표는 중립적인 독립 핀란드였고, 조약으로 페차모를 얻었으나 동카렐리야 문제는 열린 채 남았다. 영어 출처는 조약이 브레스트 강화 협상 중인 볼셰비키에게 별 의미가 없었다고 본다. 탐페레를 잃은 뒤 4월 6일 정부와 적위대 참모부는 비푸리로 옮겼고, 4월 10일 만네르가 독재 권한과 함께 총사령관직을 넘겨받았다. 위원 대부분은 4월 25일 페트로그라드로 달아났다. 패전 뒤 온건 사회주의자들은 공화국 체제에 합류했고, 극좌파는 1918년 8월 모스크바에서 핀란드 공산당을 세웠다.',
            'The armed revolution was decided by the leadership of the Workers’ Order Guards and the Finnish Workers’ Executive Committee, split off from the Social Democratic party committee on 23 January and chaired by Eero Haapalainen. Its order on the night before 27 January to arrest the senators, 33 deputies and other leaders failed because a public notice spread first. The People’s Delegation was set up on 28 January to lead the uprising begun that morning, its list of members based on Haapalainen’s proposal. The former Speaker Manner became chairman and the former vice-chairman of the Senate’s economic department, Oskari Tokoi, took the lesser post of commissar for supply; the English-language cabinet list also includes Edvard Gylling (finance) and Otto Wille Kuusinen (education). On its first day it closed all bourgeois newspapers in the capital (elsewhere in the following days), and on 2 February it put the Red Guards on the state’s payroll, though in practice it could hardly control them. It met 89 times in Helsinki and nearly ten times in Viipuri and issued 45 statutes, modelled on the Paris Commune of 1871, Bolshevik legislation and above all the earlier programmes of the Finnish labour movement. The draft constitution of 23 February, mainly Kuusinen’s work, omitted the dictatorship of the proletariat and, influenced by the Swiss and US constitutions and the French Revolution, sketched a democratic socialism with extensive use of referendums, but it was never adopted.\n\nSoviet Russia was the only state that recognised the People’s Delegation as the lawful government of Finland. After talks led by Gylling, the two governments signed a treaty on 1 March; it was Lenin who proposed adding “Socialist Workers’ Republic” to the name, and the Delegation later blamed its envoys for giving in. The majority of the Reds wanted a neutral, independent Finland; the treaty gave them Petsamo, while the question of East Karelia remained open. The English-language source judges that the treaty mattered little to the Bolsheviks, who were negotiating peace with Germany. After the loss of Tampere the government and the Red Guard staff moved to Viipuri on 6 April, and on 10 April Manner took over the supreme command with dictatorial powers. Most of the commissars fled to Petrograd on 25 April. After the defeat the moderate socialists joined the republican system, while the far left founded the Communist Party of Finland in Moscow in August 1918.'],
        aliases: { ko: ['핀란드 인민대표단', '칸산발투우스쿤타'], en: ["Finnish People's Delegation", 'People’s Delegation of Finland', "People's Delegation of Finland", 'Kansanvaltuuskunta', 'Suomen kansanvaltuuskunta'] },
        people: ['carl-manner', 'eero-haapalainen', 'oskari-tokoi', 'edvard-gylling', 'kuusinen', 'lenin'],
        events: ['finland-1917-1920', 'civil-war', 'brest-litovsk'],
        sources: [S.fswr, S.delegationFI, S.redg], locator: 'en FSWR: lead; Draft constitution; Relations with Lenin; Finnish Civil war; Defeat and Political Collapse; Cabinet — fi: johdanto; Perustaminen ja välittömät toimet; Istunnot ja lainsäädäntötoiminta; Valtuuskunnan kokoonpano — en Red Guards: War',
    }),
    term({
        id: 'battle-of-tampere', ko: '탐페레 전투', en: 'Battle of Tampere', category: 'international', period: '1918', startYear: 1918, endYear: 1918,
        definition: ['핀란드 내전에서 가장 잘 알려지고 가장 피비린내 나는 전투. 1918년 3월 중순 만네르헤임이 지휘한 백군이 공세를 시작해 3월 23일 노동운동의 중심 도시 탐페레를 포위했고, 시가전 끝에 4월 6일 함락했다. 백군 승리는 내전의 전환점이 되었으며, 항복한 적위대원 처형과 1만 명이 넘는 포로 수용이 뒤따랐다.',
            'The best-known and deadliest battle of the Finnish Civil War. The Whites under Mannerheim opened their offensive in mid-March 1918, encircled Tampere, the centre of the labour movement, from 23 March and took it after street fighting on 6 April. The White victory became the turning point of the war, followed by executions of surrendering Reds and the internment of more than 10,000 prisoners.'],
        body: ['교외를 합쳐 인구 약 6만 명인 탐페레는 핀란드에서 세 번째로 큰 도시이자 가장 공업화된 도시로, 노동운동의 수도로 여겨졌다. 적색 정부는 헬싱키에 있었지만 철도와 많은 노동자 인구 덕에 탐페레가 적위대의 주 근거지가 되었고, 탐페레 적위대는 여성 300명을 포함해 약 6,000명이었다. 영어 출처에 따르면 백군은 3월 15일(핀란드어 출처는 16일) 공세를 시작해 랭키포흐야와 오리베시에서 적색 전선을 무너뜨렸다. 약 1만 5천 명의 적위대가 탐페레로 물러나 끝까지 지키기로 했고, 3월 23일 백군 1만 7천 명이 도시를 포위했다. 에이노 라햐는 남쪽 렘팰래에서 3,500명으로 반격했다. 3월 28일 「피의 목요일」 공격에서 예거 장교가 이끈 징집병 부대와 스웨덴 여단이 큰 손실을 입었고, 적색 지휘관 후고 살멜라가 사고로 죽어 베르네르 레흐티매키가 뒤를 이었다. 이후 닷새 동안 포격으로 노동자 지구 탐멜라와 퀴탤래가 거의 파괴되었다.\n\n4월 3일 새벽 백군의 결정적 공세는 집집마다 싸우며 동쪽 노동자 지구를 차지했고, 4일 탐메르코스키강을 건넜다. 5일 시청이 마지막 거점으로 무너졌고, 그날 저녁 레흐티매키와 알리 알토넨 등 적색 무리가 얼어붙은 호수를 건너 빠져나갔다. 4월 6일 아침 퓌니키 탑에 백기가 올랐다. 영어 출처는 전사자를 백군 600~820명, 적군 600~1,000명으로 추산하고, 전투 뒤 적색 약 1,000명과 러시아인 200명이 처형되었다고 적는다. 핀란드어 출처는 적색 약 2,000명이 죽었고 그 절반이 처형된 포로였으며 백색은 약 700명이 죽었다고 본다. 1만 명이 넘는 포로가 중앙광장에 거의 하루 동안 세워졌다가 칼레반캉가스 수용소로 옮겨졌고, 다섯 달 동안 1,228명이 처형과 병, 굶주림으로 죽었다. 핀란드어 출처는 참가 병력으로 보아 북유럽 전쟁사에서 그때까지 가장 큰 전투였다고 쓴다.',
            'With about 60,000 people including suburbs, Tampere was Finland’s third-largest and most industrialised town and was regarded as the capital of the labour movement. Although the Red government sat in Helsinki, the railways and large working-class population made Tampere the main base of the Red Guards, whose Tampere guard numbered about 6,000, including 300 women. According to the English-language source the Whites began their operation on 15 March (the Finnish-language source says 16 March) and broke the Red front at Länkipohja and Orivesi. Some 15,000 Reds fell back on Tampere and resolved to defend it, and on 23 March 17,000 Whites besieged the town. Eino Rahja counterattacked with 3,500 men at Lempäälä to the south. In the “Bloody Thursday” assault of 28 March the conscript battalions led by Jäger officers and the Swedish Brigade suffered heavy losses, while the Red commander Hugo Salmela was killed in an accident and replaced by Verner Lehtimäki. Five days of shelling then all but destroyed the working-class districts of Tammela and Kyttälä.\n\nThe decisive White offensive of 3 April took the eastern working-class districts house by house and crossed the Tammerkoski on the 4th. On the 5th the City Hall fell as the last Red pocket, and that evening Lehtimäki, Ali Aaltonen and other Reds escaped across the frozen lakes. On the morning of 6 April a white flag went up on the Pyynikki Tower. The English-language source estimates 600–820 Whites and 600–1,000 Reds killed, and records that about 1,000 Reds and 200 Russians were executed after the battle. The Finnish-language source puts the Red dead at about 2,000, half of them executed prisoners, and the White dead at about 700. More than 10,000 prisoners stood in the Central Square for nearly a day before being moved to the Kalevankangas camp, where 1,228 died of executions, disease or hunger within five months. The Finnish-language source calls it, by the numbers engaged, the largest battle in Nordic military history up to that time.'],
        aliases: { ko: ['1918년 탐페레 전투', '탐페렌 타이스텔루'], en: ['Tampereen taistelu', 'Battle of Tampere (1918)', 'Siege of Tampere'] },
        people: ['carl-gustaf-emil-mannerheim', 'eino-rahja', 'ali-aaltonen'],
        events: ['finland-1917-1920', 'civil-war'],
        sources: [S.tampere, S.tampereFI], locator: 'en: lead; Background; Siege of Tampere; Bloody Thursday; Battle in the town; Casualties; Aftermath — fi: johdanto',
    }),
    term({
        id: 'heimosodat', ko: '헤이모소다트', en: 'Heimosodat', category: 'nationalities', period: '1918–1922', startYear: 1918, endYear: 1922,
        definition: ['「친족 전쟁」이라는 뜻의 핀란드어로, 1918~1922년 핀란드 의용병이 핀란드와 맞닿은 옛 러시아 제국 영토, 곧 다른 핀계 민족이 많이 사는 동카렐리야·잉그리아·페차모와 에스토니아에서 벌인 일련의 무력 충돌과 사적 원정을 가리킨다. 핀란드 국가는 공식 당사자가 아니었지만, 출처에 따라 약 9,000~1만 명의 의용병이 참여했다.',
            'Finnish for “kindred nations wars”: the series of armed conflicts and private military expeditions of 1918–1922 in which Finnish volunteers fought in former Russian imperial territories bordering Finland and inhabited largely by other Finnic peoples — East Karelia, Ingria, Petsamo and Estonia. The Finnish state was not officially a party, but some 9,000 to 10,000 volunteers took part, depending on the source.'],
        body: ['1918년 비에나 원정에서는 3월 10일 쿠르트 마르티 발레니우스의 부대가 북비에나 국경을 넘었고, 21일 국경을 넘은 칼 빌헬름 말름의 부대는 비에나의 켐 근처까지 갔으나 4월 10일 공격에서 밀려났다. 영국의 선전과 식량 원조로 카렐리야인들이 돌아서면서, 7월 말름을 대신한 토이보 쿠이스마의 원정대도 10월 2일 핀란드로 물러났다. 1918년과 1920년의 페차모 원정은 모두 철수로 끝났다. 1919년 4월 21일 군나르 폰 헤르첸이 이끈 아우누스 원정대는 올로네츠를 빠르게 차지하고 페트로자보츠크 앞까지 갔으나 주민의 호응이 적어 6월 말 물러났다. 에스토니아 독립전쟁에는 한스 칼름의 「북방의 아들들」과 마르틴 엑스트룀의 제1핀란드의용군이 참전했고, 1918~1920년 잉그리아인 봉기에서는 북잉그리아 연대가 몇몇 마을을 지켜 키르야살로 공화국을 세웠다. 영어 출처는 무르만스크 군단과 1919년의 페트로그라드 진격도 이 목록에 넣는다. 마지막은 1921~1922년 동카렐리야 봉기로, 2,500명의 숲 게릴라에 핀란드 의용병 약 500명이 지휘관으로 가담했으나 2만 명의 소비에트군에 무너졌다.\n\n동기는 친족 민족 사상, 반볼셰비즘, 대핀란드 사상, 그리고 단순한 모험심이었다. 영어 출처는 갓 독립한 핀란드에서 다른 핀계 민족의 독립을 도울 의무를 느낀 민족주의·실지 회복주의와, 내전의 상처로 많은 백색 지지자가 급진적 민족주의자가 된 사정을 함께 든다. 핀란드어 출처에 따르면 약 660명의 핀란드인이 죽었다. 레폴라(1918)와 포라얘르비(1919)가 핀란드에 합류했지만 성과를 거둔 것은 에스토니아 독립전쟁뿐이었다. 전쟁은 동카렐리야 봉기를 빼면 1920년 타르투 조약으로 끝났고, 친족 활동가들은 이 조약을 「수치의 강화」라 불렀다. 동카렐리야인과 잉그리아인 2만 명 가까이가 핀란드로 피했고, 이를 계기로 대핀란드 사상을 이어 가려는 아카데믹 카렐리야 협회가 생겼다. 동카렐리야 문제는 1920년대 초 핀란드와 소비에트 러시아의 관계를 괴롭혔다. 영어 출처는 2차 세계대전의 고된 5년이 이 열기를 식혔다고 본다.',
            'In the Viena expedition of 1918, Kurt Martti Wallenius’s force crossed into northern Viena on 10 March, and Carl Wilhelm Malm’s force, crossing on 21 March, got near Kem before being thrown back on 10 April. British propaganda and food aid turned the Karelians against the Finns, and Toivo Kuisma’s expedition, which replaced Malm’s in July, was forced back into Finland on 2 October. The Petsamo expeditions of 1918 and 1920 both ended in withdrawal. The Aunus expedition under Gunnar von Hertzen crossed the border on 21 April 1919, quickly took Olonets and reached the outskirts of Petrozavodsk, but drew little local support and withdrew at the end of June. In the Estonian War of Independence Finns fought in Hans Kalm’s Sons of the North and Martin Ekström’s 1st Finnish Volunteer Corps, and in the Ingrian rising of 1918–1920 the North Ingrian regiment held a few villages that formed the Republic of Kirjasalo. The English-language source also lists the Murmansk Legion and the 1919 advance on Petrograd. The last was the East Karelian uprising of 1921–1922, in which some 500 Finnish volunteers served as officers of 2,500 forest guerrillas before 20,000 Soviet troops crushed it.\n\nThe motives were the idea of kinship, anti-Bolshevism, the Greater Finland idea and plain love of adventure. The English-language source links them to nationalism and irredentism in newly independent Finland, where many felt bound to help other Finnic peoples to independence, and to the trauma of the civil war, which made many White sympathisers radical nationalists. According to the Finnish-language source about 660 Finns died. Repola (1918) and Porajärvi (1919) joined Finland, but only the Estonian war succeeded. Apart from the East Karelian uprising, the wars ended with the Treaty of Tartu in 1920, which the kinship activists called a “shameful peace”. Nearly 20,000 East Karelians and Ingrians fled to Finland, prompting the founding of the Academic Karelia Society to keep the Greater Finland idea alive, and the East Karelian question strained relations between Finland and Soviet Russia in the early 1920s. The English-language source holds that the strenuous five years of the Second World War cooled this enthusiasm.'],
        aliases: { ko: ['친족 전쟁', '헤이모소타'], en: ['Kindred Nations Wars', 'Kinship Wars', 'Wars for kindred peoples', 'Kinfolk wars', 'heimosota'] },
        people: [],
        events: ['finland-1917-1920', 'baltic-wars-of-independence', 'civil-war'],
        sources: [S.heimo, S.heimoFI], locator: 'en: lead; list of conflicts; Glossary — fi: johdanto; Vienan retket; Viron vapaussota; Aunuksen retkikunta; Petsamon retket; Inkeriläisten kansannousu; Itäkarjalaisten kansannousu',
    }),
    term({
        id: 'treaty-of-tartu-finland-1920', ko: '타르투 조약 (핀란드–소비에트 러시아)', en: 'Treaty of Tartu (Finland–Soviet Russia)', category: 'international', period: '1920', startYear: 1920, endYear: 1920,
        definition: ['1920년 10월 14일 에스토니아 타르투에서 핀란드와 소비에트 러시아가 거의 다섯 달의 협상 끝에 맺은 강화 조약. 국경을 옛 핀란드 대공국과 러시아 제국의 경계로 확정하고, 페차모를 핀란드에 넘기는 대신 레폴라·포라얘르비와 북잉그리아를 러시아에 돌려주었다. 12월 31일 발효했으며, 같은 해 2월 같은 도시에서 맺어진 에스토니아–소비에트 러시아 조약과는 별개다.',
            'The peace treaty signed by Finland and Soviet Russia in Tartu, Estonia, on 14 October 1920 after nearly five months of negotiations. It fixed the border along the old line between the Grand Duchy of Finland and the Russian Empire and gave Petsamo to Finland, while Repola, Porajärvi and North Ingria went back to Russia. It came into force on 31 December and is distinct from the Estonian–Soviet treaty signed in the same city that February.'],
        body: ['핀란드 내전이 터지자 두 나라의 외교 관계는 끊겼고, 소브나르콤은 적색 인민대표위원회를 핀란드 정부로 인정했다. 핀란드어 출처에 따르면 핀란드는 1918년부터 두 나라가 전쟁 상태에 있었다고 보았다. 1920년 러시아 내전에서 볼셰비키의 승리가 확실해 보이자 이웃 나라들은 관계 정상화에 나섰고, 에스토니아(2월, 타르투)·라트비아(6월, 리가)·리투아니아(7월, 모스크바)가 먼저 조약을 맺었다. 협상은 폴란드–소비에트 전쟁과 같은 시기에 진행되었다. 핀란드 대표단은 유호 쿠스티 파시키비가 이끌었고 유호 벤놀라, 알렉산데르 프레이, 루돌프 발덴, 배이뇌 탄네르, 배이뇌 보이온마, 배이뇌 키빌린나가 참여했다. 소비에트 대표단에는 얀 안토노비치 베르진, 플라톤 케르젠체프, 니콜라이 티흐메네프, 알렉산드르 사모일로, 예브게니 베렌스가 있었다. 조약은 타르투의 에스토니아 학생회 건물에서 서명되었다.\n\n핀란드는 북극해의 얼지 않는 항구가 있는 페차모를 얻었다. 1864년 알렉산드르 2세가 카렐리야 지협의 땅과 맞바꾸어 주겠다고 약속했던 곳이다. 대신 비에나·아우누스 원정 때 합병해 점령했던 레폴라와 포라얘르비에서 물러나고, 북잉그리아를 넘겨 북잉그리아 공화국을 해체했다. 소비에트는 라도가 호수의 핀란드 항구에서 네바강을 거쳐 핀란드만으로 가는 상선의 자유 항행을, 핀란드는 페차모를 거쳐 노르웨이로 가는 육상 통과를 보장했다. 핀란드는 크론시타트 맞은편 이노 요새의 무장을 풀고 핀란드만 바깥 섬들을 비무장화했다. 러시아어 출처에 따르면 전러시아 중앙집행위원회가 10월 23일, 핀란드 의회가 12월 1일 조약을 승인했고 스톨베리 대통령이 12월 11일 비준했으며, 비준서는 12월 31일 모스크바에서 교환되었다. 의회의 민족주의 우파는 대핀란드의 이상을 버린 조약을 수치스럽다고 했고, 친족 활동가들은 「수치의 강화」라 불렀다. 1921~1922년 동카렐리야 봉기에 핀란드 의용병이 가담하면서 첫 논란이 일었고, 조약은 1939년 소련이 겨울전쟁을 일으켜 깨뜨렸으며 1940년 모스크바 강화 조약으로 대체되었다.',
            'Diplomatic relations broke off when the Finnish Civil War began, and the Sovnarkom recognised the Red People’s Delegation as the government of Finland. According to the Finnish-language source, Finland held that a state of war had existed between the two countries since 1918. By 1920, as a Bolshevik victory in the Russian Civil War looked certain, Russia’s neighbours moved to normalise relations: Estonia (February, at Tartu), Latvia (June, at Riga) and Lithuania (July, at Moscow) signed their treaties first, and the talks coincided with the Polish–Soviet War. The Finnish delegation was led by Juho Kusti Paasikivi and included Juho Vennola, Alexander Frey, Rudolf Walden, Väinö Tanner, Väinö Voionmaa and Väinö Kivilinna; the Soviet delegation included Jan Antonovich Berzin, Platon Kerzhentsev, Nikolai Tikhmenev, Alexander Samoylo and Yevgeny Berens. The treaty was signed in the building of the Estonian Students’ Society in Tartu.\n\nFinland gained Petsamo with its ice-free harbour on the Arctic Ocean, which Tsar Alexander II had promised in 1864 in exchange for a piece of the Karelian Isthmus. In return it left Repola and Porajärvi, annexed and occupied during the Viena and Aunus expeditions, and handed over North Ingria, disbanding the Republic of North Ingria. The Soviets guaranteed free navigation for merchant ships from Finland’s Ladoga ports via the Neva to the Gulf of Finland, and Finland guaranteed land transit to Norway through Petsamo. Finland also disarmed the coastal fortress of Ino opposite Kronstadt and demilitarised its outer islands in the Gulf of Finland. According to the Russian-language source the All-Russian Central Executive Committee approved the treaty on 23 October and the Finnish Parliament on 1 December, President Ståhlberg ratified it on 11 December, and ratifications were exchanged in Moscow on 31 December. Nationalist and rightist deputies called it shameful for abandoning the ideal of a greater Finland, and kinship activists named it the “shameful peace”. It first became controversial when Finnish volunteers joined the East Karelian uprising of 1921–1922; the Soviet Union broke it by starting the Winter War in 1939, and it was replaced by the Moscow Peace Treaty of 1940.'],
        aliases: { ko: ['핀란드–소비에트 러시아 타르투 조약', '핀란드-소비에트 러시아 타르투 조약', '타르톤 라우하'], en: ['Treaty of Tartu (Finland–Russia)', 'Treaty of Tartu (Russian–Finnish)', 'Finnish–Soviet Treaty of Tartu', 'Tarton rauha'] },
        people: ['juho-kusti-paasikivi', 'rudolf-walden', 'vaino-tanner', 'vaino-voionmaa', 'platon-kerzhentsev', 'kaarlo-juho-stahlberg'],
        events: ['finland-1917-1920', 'civil-war', 'winter-war'],
        sources: [S.tartu, S.tartuFI, S.tartuRU, S.heimoFI], locator: 'en: lead; Political background; Contents; Delegations — fi: johdanto; Maiden välinen sotatila — ru: ratification — fi Heimosodat: Itäkarjalaisten kansannousu',
    }),
    term({
        id: 'kingdom-of-finland-1918', ko: '핀란드 왕국 (1918)', en: 'Kingdom of Finland (1918)', category: 'party-state', period: '1918', startYear: 1918, endYear: 1918,
        definition: ['핀란드 내전 뒤 승리한 백색 진영이 독일 왕족을 국왕으로 세워 핀란드를 군주국으로 만들려다 실패한 시도. 1918년 10월 9일 사회민주당이 거의 빠진 의회가 헤센의 프리드리히 카를 공을 국왕으로 뽑았으나, 그는 핀란드에 오지도 즉위하지도 않은 채 독일 패전 뒤 12월 14일 왕위를 포기했다. 1919년 공화국 헌법으로 핀란드는 공화국이 되었다.',
            'The failed attempt by the victorious Whites after the Finnish Civil War to make Finland a monarchy under a German prince. On 9 October 1918 a Parliament with almost no Social Democrats elected Prince Friedrich Karl of Hesse king, but he never took the throne or came to Finland, and renounced it on 14 December after Germany’s defeat. The republican constitution of 1919 confirmed Finland as a republic.'],
        body: ['1917년 12월 독립 때 군주제에 기운 의원은 소수였고, 의회는 공화국을 선언했다. 그러나 내전 뒤 승리한 백색은 사회민주당을 의회에서 배제했고(영어 출처에 따르면 마티 파시부오리 1명만 남았다. 전쟁 전 사회민주당은 200석 가운데 92석이었다), 군주파는 내전이 제약 없는 민선 의회의 불안정을 보여 주었다며 파벌 위에 선 국왕이 필요하다고 주장했다. 근거는 스웨덴 시대인 1772년의 정부 형태법이 여전히 유효하다는 법리였다. 리투아니아가 7월 우라흐 공작을 민다우가스 2세로 뽑았고 발트 독일인 귀족들도 독일 보호령을 청하던 때였다. 독일은 예거 부대를 훈련시키며 독립 준비를 지원한 유일한 열강이었고 내전에도 개입했으며, 핀란드의 처지는 이미 보호령에 가까워지고 있었다. 친독일 총리 유호 쿠스티 파시키비의 정부가 10월 빌헬름 2세의 처남인 프리드리히 카를 공에게 왕관을 제안했고, 페르 에빈드 스빈후부드가 섭정이 되었다. 새 군주제 헌법은 필요한 가중 다수를 얻지 못해 미뤄졌고, 한 의원은 「핀란드와 카렐리야의 왕 카를레 1세」라는 칭호를 제안하기도 했다.\n\n11월 9일 빌헬름 2세가 퇴위하고 이틀 뒤 휴전이 이루어지자, 서방의 경고를 받은 라우리 잉만 총리의 정부는 자신도 군주파였지만 프리드리히 카를에게 왕위 포기를 청했다. 승전국들은 독일과의 동맹을 버려야 핀란드 독립을 승인하겠다고 알렸다. 프리드리히 카를은 12월 14일 왕위를 포기했고 발트해 사단도 핀란드를 떠났다. 스빈후부드가 물러나고 카를 구스타프 에밀 만네르헤임이 섭정이 되었다. 1918년 군주정 구상에 반대해 공화제를 지지했던 카를로 유호 스톨베리의 헌법안이 1919년 정부 형태법이 되었고, 1919년 3월 선거에서 공화파 정당들이 의석의 4분의 3을 얻었다. 7월 의회는 스톨베리를 초대 대통령으로 뽑았고, 그는 만네르헤임의 뒤를 이었다.',
            'At independence in December 1917 only a minority of deputies leaned towards monarchy, and Parliament declared Finland a republic. After the civil war, however, the victorious Whites excluded the Social Democrats from Parliament (according to the English-language source only Matti Paasivuori remained; before the war they had held 92 of 200 seats), and the monarchists argued that the war had shown the instability of an unconstrained elected parliament and that the nation needed a king above factions. Their legal ground was that the Swedish-era Instrument of Government of 1772 was still in force. In July Lithuania had elected the Duke of Urach as Mindaugas II, and Baltic German nobles were asking for a German protectorate. Germany was the only power that had supported the preparations for independence, not least by training the Jäger troops, and had also intervened in the civil war; Finland’s position was already drifting towards that of a protectorate. In October the pro-German government of Prime Minister Juho Kusti Paasikivi offered the crown to Prince Friedrich Karl, brother-in-law of Wilhelm II, while Pehr Evind Svinhufvud became Regent. A new monarchist constitution was delayed for lack of the required qualified majority, and one deputy proposed the style “Karl I, King of Finland and Karelia”.\n\nAfter Wilhelm II abdicated on 9 November and the armistice followed two days later, warnings from the West led the government of Prime Minister Lauri Ingman, himself a monarchist, to ask Friedrich Karl to give up the crown. The victors made clear that Finland’s independence would be recognised only if it abandoned its alliance with Germany. Friedrich Karl renounced the throne on 14 December, the Baltic Sea Division left Finland, Svinhufvud resigned and Carl Gustaf Emil Mannerheim became Regent. The proposals of Kaarlo Juho Ståhlberg, who had backed a republic against the monarchy plan in 1918, became the 1919 Instrument of Government, and in the March 1919 election republican parties won three-quarters of the seats. In July Parliament elected Ståhlberg the first president, succeeding Mannerheim.'],
        aliases: { ko: ['핀란드 왕국', '1918년 핀란드 왕국', '수오멘 쿠닝가스쿤타'], en: ['Kingdom of Finland', 'Suomen kuningaskunta', 'Konungariket Finland'] },
        people: ['pehr-evind-svinhufvud', 'juho-kusti-paasikivi', 'carl-gustaf-emil-mannerheim', 'kaarlo-juho-stahlberg', 'wilhelm-ii'],
        events: ['finland-1917-1920', 'brest-litovsk', 'world-war-i-aftermath-1918-1923'],
        sources: [S.kingdom, E('Kaarlo_Juho_Ståhlberg'), S.pres1919], locator: 'en Kingdom of Finland: lead; History — en Ståhlberg: Architect of the Finnish constitution; First President of Finland',
    }),
];
