// Glossary terms for the belarus-1917-1921 event (2026-10-04), built with
// lib.js term(). Facts come from the en/ru Wikipedia pages listed in each
// term's sources (fetched 2026-10-04).
//
// original (원어명):
//   belarusian-peoples-republic        be. Беларуская Народная Рэспубліка (БНР; Biełaruskaja Narodnaja Respublika);
//                                      ru. Белорусская Народная Республика (БНР)
//   socialist-soviet-republic-of-byelorussia              ru. Социалистическая Советская Республика Белоруссия (ССРБ);
//                                      be. Сацыялістычная Савецкая Рэспубліка Беларусь (ССРБ)
//   litbel                             ru. Литовско-Белорусская Советская Социалистическая Республика (Литбел)
//   slutsk-uprising-1920               be. Слуцкае паўстанне / Слуцкі збройны чын; ru. Слуцкое восстание
//   first-all-belarusian-congress      be. Першы Усебеларускі з’езд (en source: Першы Ўсебеларускі кангрэс);
//                                      ru. Первый Всебелорусский съезд
//   belarusian-socialist-hramada       be. Беларуская сацыялістычная грамада (БСГ);
//                                      ru. Белорусская социалистическая грамада (громада)
//
// Spelling follows the event: the country and nation in general are
// 벨라루스, Soviet states and bodies are 벨로루시. socialist-soviet-republic-of-byelorussia is the
// SSRB of 1919 and 1920–1922 only, headed 「벨로루시 사회주의 소비에트 공화국」;
// it never takes 「벨로루시 소비에트 사회주의 공화국」 / Byelorussian SSR, the
// Union republic of 1922–1991. The All-Belarusian Congress of Soviets of
// February 1919 is a different body from first-all-belarusian-congress, and the
// Belarusian Peasants' and Workers' Hramada (1925) is a different party from
// belarusian-socialist-hramada, so neither term takes the bare 흐라마다 / Hramada.
// The overlapping glossary entry interwar-ukrainian-and-belarusian-national-question
// covers the interwar minority question in Poland, not these bodies.
const { term } = require('../lib');

const E = t => 'https://en.wikipedia.org/wiki/' + encodeURI(t);
const RU = t => 'https://ru.wikipedia.org/wiki/' + encodeURI(t);
const S = {
    bnr: E("Belarusian_People's_Republic"),
    bnrRU: RU('Белорусская_Народная_Республика'),
    rada: E('Rada_of_the_Belarusian_Democratic_Republic'),
    ssrb: E('Socialist_Soviet_Republic_of_Byelorussia'),
    ssrbRU: RU('Социалистическая_Советская_Республика_Белоруссия'),
    litbel: E('Socialist_Soviet_Republic_of_Lithuania_and_Belorussia'),
    slutsk: E('Slutsk_uprising'),
    slutskRU: RU('Слуцкое_восстание'),
    congress: E('First_All-Belarusian_Congress'),
    congressRU: RU('Первый_Всебелорусский_съезд'),
    bsa: E('Belarusian_Socialist_Assembly'),
    bsaRU: RU('Белорусская_социалистическая_грамада'),
    bpwu: E("Belarusian_Peasants'_and_Workers'_Union"),
    zhyl: E('Zmicier_Zhylunovich'),
};

// term() writes one period string to both languages and records String(endYear)
// as evidence. For a body that still exists, give each language its own period
// and record the open end year as still active (the term service requires
// evidence for endYear even when it is empty).
function ongoing(spec, periodKo, periodEn) {
    const t = term({ ...spec, period: periodEn, endYear: null });
    t.fields.period = { ko: periodKo, en: periodEn };
    t.fields.evidence = t.fields.evidence.map(e => (e.field === 'endYear' ? { ...e, claim: 'Rada still active in exile; no end year' } : e));
    return t;
}

module.exports = [
    ongoing({
        id: 'belarusian-peoples-republic', ko: '벨라루스 인민공화국', en: 'Belarusian People’s Republic', category: 'nationalities', startYear: 1918,
        definition: ['1918년 독일군 점령 아래 민스크에서 라다가 선포한 벨라루스의 국가. 「벨라루스 민주공화국」으로도 불린다. 3월 9일 제2헌장으로 수립되고 3월 25일 제3헌장으로 독립을 선포했으나 벨라루스 전역을 다스린 적은 없었다. 1918년 12월 붉은 군대가 민스크에 들어오자 정부는 리투아니아로 옮겨 1919년부터 망명했고, 소비에트-폴란드 전쟁 끝에 벨라루스 땅이 나뉘면서 국가로서는 사라졌다. 그 라다는 지금도 망명 정부로 남아 있다.',
            'The Belarusian state proclaimed in Minsk by its Rada under German occupation in 1918, also known as the Belarusian Democratic Republic. Established by the Second Constituent Charter of 9 March and declared independent by the Third Charter of 25 March, it never governed the whole of Belarus. When the Red Army entered Minsk in December 1918 its government moved to Lithuania and from 1919 went into exile, and the state disappeared when the Polish–Soviet War divided the Belarusian lands. Its Rada still exists as a government in exile.'],
        body: ['2월 혁명 뒤 벨라루스에서는 러시아 공화국 안의 자치냐 독립이냐를 두고 논쟁이 벌어졌다. 새 국가 구상은 1917년 12월 제1차 전벨라루스 대회에서 나왔으나 대회는 볼셰비키에게 해산되었다. 1918년 2월 21일 독일군이 민스크를 점령하기 몇 시간 전, 대회 라다의 집행위원회는 제1헌장으로 스스로를 이 지역의 권력으로 선언하고 이반 바론카를 의장으로 인민서기국을 세웠다. 3월 3일 브레스트-리토프스크 조약이 맺어진 뒤 라다는 제2헌장으로 인민공화국을 세웠고, 3월 25일 제3헌장으로 모길료프현 전체와 민스크·그로드노·빌뉴스·비텝스크·스몰렌스크현의 벨라루스인 지역을 영토로 내세우며 독립을 선포했다. 이때 라다 위원은 77명으로, 대회에서 뽑힌 36명에 빌뉴스 벨라루스인 대표, 러시아인·폴란드인·유대인 소수민족 대표, 지방자치체와 도시 대표가 더해졌다. 같은 날 라다는 빌헬름 2세에게 「독일 제국과의 동맹 속에서」 독립을 굳히도록 도와 달라는 전보를 보냈고, 이 전보는 라다를 심각한 위기에 빠뜨려 일부 사회주의자들이 인민서기국을 떠났다. 독일은 끝내 공화국을 승인하지 않았다. 흰색·빨간색·흰색의 삼색기와 리투아니아 대공국 문장에서 온 「파호냐」가 상징이었고, 영어 출처에 따르면 150~350개 학교가 세워졌다.\n\n1918년 12월 독일군이 물러나고 붉은 군대가 민스크에 들어오자 라다는 빌뉴스와 그로드노를 거쳐 카우나스로 옮겼다. 안톤 루츠케비치 총리는 1919년 파리 강화회의에 대표단을 이끌었고, 영어 출처는 에스토니아(1919년 10월)와 핀란드(1919년 12월)가 공식 승인했다고 적지만, 러시아어 출처는 각지의 대표부가 어떤 법적 승인도 받지 못했다고 본다. 역사가 올레크 와티쇼네크에 따르면 공화국 군대에서 약 1만 1천 명이 복무했다. 1920년 11월 11일 바츨라우 라스토우스키의 정부는 리투아니아와 협력 조약을 맺었고, 같은 해 말 슬루츠크 봉기가 일어났다. 1925년 10월 베를린의 전벨라루스 정치 회의에서 망명 정부는 권한을 소비에트 벨로루시 정부에 넘기고 해산하기로 했지만, 라다 의장 피오트라 크레체우스키는 이를 받아들이지 않았고 라다는 소비에트 벨로루시를 공식 인정하지 않은 채 망명지에 남았다. 소비에트 벨로루시로 돌아간 라스토우스키 등 여러 지도자는 1930년대에 탄압받았다. 라다는 1945년 서독으로 옮겼고, 2026년 현재 가장 오래된 망명 정부다. 1980년대 말부터 벨라루스 민족민주 야당은 3월 25일을 「자유의 날」로 기념한다.',
            'After the February Revolution Belarusians debated whether to seek autonomy within the Russian Republic or independence. The idea of a new state was put forward at the First All-Belarusian Congress in December 1917, which the Bolsheviks dispersed. On 21 February 1918, a few hours before German troops occupied Minsk, the executive committee of the Congress’s Rada declared itself the authority in the region by its First Constituent Charter and set up the People’s Secretariat under Ivan Varonka. After the Treaty of Brest-Litovsk was signed on 3 March, the Rada established the People’s Republic by its Second Charter, and on 25 March its Third Charter proclaimed independence, claiming the whole of the Mogilev Governorate and the Belarusian parts of the Minsk, Grodno, Vilna, Vitebsk and Smolensk Governorates. The Rada then had 77 members: 36 elected at the Congress plus representatives of the Vilnius Belarusians, of the Russian, Polish and Jewish minorities, and of local governments and cities. That same day it telegraphed Wilhelm II asking for help in strengthening its independence “in union with the German Empire”; the telegram plunged the Rada into a severe crisis, and some socialists left the People’s Secretariat. Germany never recognised the republic. Its symbols were the white-red-white flag and the Pahonia, taken from the arms of the Grand Duchy of Lithuania, and according to the English-language source between 150 and 350 schools were founded.\n\nWhen the Germans withdrew in December 1918 and the Red Army entered Minsk, the Rada moved via Vilnius and Hrodna to Kaunas. Prime Minister Anton Luckievič led a delegation to the Paris Peace Conference in 1919; the English-language source states that Estonia (October 1919) and Finland (December 1919) officially recognised the republic, while the Russian-language source holds that none of its missions abroad obtained legal recognition. According to the historian Oleg Łatyszonek about 11,000 people served in its army. On 11 November 1920 Vaclau Lastouski’s government signed a cooperation treaty with Lithuania, and the Slutsk uprising broke out at the end of that year. In October 1925 the All-Belarusian Political Conference in Berlin decided that the government in exile should hand its powers to the government of Soviet Byelorussia and dissolve, but the Rada’s chairman Piotra Krečeŭski refused to accept it, and the Rada stayed in exile without ever officially recognising Soviet Byelorussia. Many leaders who returned to Soviet Byelorussia, Lastouski among them, were repressed in the 1930s. The Rada moved to West Germany in 1945, and as of 2026 it is the oldest existing government in exile. Since the late 1980s the Belarusian national democratic opposition has celebrated 25 March as Freedom Day.'],
        aliases: { ko: ['벨라루스 민주공화국', '벨로루시 인민공화국'], en: ["Belarusian People's Republic", 'Belarusian Democratic Republic', 'Belarusian National Republic', 'BNR', 'Biełaruskaja Narodnaja Respublika'] },
        people: ['jan-sierada', 'anton-luckievic', 'vaclau-lastouski', 'piotra-krecheuski', 'stanislaw-bulak-balachowicz', 'jozef-pilsudski'],
        events: ['belarus-1917-1921', 'civil-war', 'soviet-polish-war', 'brest-litovsk'],
        sources: [S.bnr, S.bnrRU, S.rada], locator: 'en BNR: lead; History (Background, Territory, Military, Foreign relations, Other actions); Exile; Symbols — ru BNR: lead; БНР в эмиграции; Символы БНР — en Rada: Formation; In exile',
    }, '1918–현재 (1919년부터 망명)', '1918–present (in exile since 1919)'),
    term({
        id: 'socialist-soviet-republic-of-byelorussia', ko: '벨로루시 사회주의 소비에트 공화국', en: 'Socialist Soviet Republic of Byelorussia', category: 'party-state', period: '1919–1922', startYear: 1919, endYear: 1922,
        definition: ['1919년 1월 1일 스몰렌스크에서 선포된 소비에트 공화국. 2월 27일 소비에트 리투아니아와 합쳐 리트벨이 되면서 사라졌다가 1920년 7월 31일 같은 이름으로 다시 세워졌고, 1922년 12월 소련 결성 조약에 참여해 소련의 벨로루시 소비에트 사회주의 공화국이 되었다. 소련 역사학과 벨라루스 역사학은 이 선포를 벨로루시 소비에트 사회주의 공화국의 첫 선포로 본다.',
            'The Soviet republic proclaimed in Smolensk on 1 January 1919. It disappeared when it merged with Soviet Lithuania into Litbel on 27 February, was re-established under the same name on 31 July 1920, and in December 1922 joined the treaty that formed the USSR, becoming the Byelorussian Soviet Socialist Republic within it. Soviet historians, and Belarusian historiography after them, count its proclamation as the first proclamation of the Byelorussian SSR.'],
        body: ['1918년 서부 주의 지도부는 벨라루스를 러시아 소비에트 공화국의 한 지역 단위로 여겼고, 벨라루스인이 아직 뚜렷한 민족 의식을 갖추지 못해 자결 원칙이 맞지 않는다고 주장했다. 반면 1918년 1월 31일 민족인민위원부 안에 세워진 벨라루스 민족위원부의 알렉산드르 체르뱌코프와 즈미체르 질루노비치는 벨라루스 소비에트 공화국이 필요하다고 보았고, 러시아어 출처는 3월 25일 벨라루스 인민공화국의 독립 선포도 이런 인식에 적지 않은 영향을 주었다고 설명한다. 12월 21~23일 모스크바의 러시아 공산당 벨라루스 지부 회의가 공화국 수립을 결정했고, 12월 30~31일 스몰렌스크의 서부 주 당 조직 제6차 회의는 스스로를 벨로루시 공산당(볼셰비키) 창립 대회로 선언하고 질루노비치를 의장으로 하는 임시 노동자·농민 정부를 뽑았다. 공화국은 비텝스크·그로드노·모길료프·민스크·스몰렌스크현을 아우르는 것으로 선포되었고 정부는 1월 초 민스크로 옮겼다. 그러나 1월 16일 러시아 공산당 중앙위원회는 스몰렌스크·비텝스크·모길료프현을 러시아로 돌리고 소비에트 리투아니아와 합치라고 결정했다. 2월 2~3일 민스크의 제1차 전벨로루시 소비에트 대회는 헌법을 채택하고 영토를 민스크·그로드노현으로 줄였는데, 전쟁 중이라 정부가 실제로 다스린 곳은 민스크현의 6개 군뿐이었다. 2월 27일 공화국은 리트벨에 흡수되었다.\n\n1920년 7월 11일 붉은 군대가 민스크를 되찾은 뒤, 7월 30일 리투아니아·벨로루시 공산당과 프세볼로트 이그나톱스키의 벨로루시 공산주의 조직, 분트가 만나 공화국을 다시 세우기로 하고 벨로루시 군사혁명위원회를 만들었다. 7월 31일 다시 선포된 공화국의 독립 선언은 민스크현의 6개 군에도 못 미치는 경계 안에서 발표되었다. 1921년 1월 16일 러시아 소비에트 연방 사회주의 공화국과 맺은 노동자·농민 연합 조약은 두 공화국의 독립과 주권을 서로 인정했다. 1921년 리가 조약으로 국경이 정해지면서 서벨라루스는 폴란드에 넘어갔고, 1922년 12월 공화국은 러시아·우크라이나·자캅카스 공화국과 함께 소련 결성 조약에 서명했다. 영어 출처는 소련 역사학이 이 공화국을 소련 가입 뒤의 이름인 벨로루시 소비에트 사회주의 공화국으로 불러 왔다고 지적하고, 볼셰비키가 이를 완충 공화국으로 여겼다고 설명한다.',
            'In 1918 the leadership of the Western Oblast regarded Belarus as a territorial unit of the Russian Soviet republic and argued that the Belarusians, still lacking a distinct national consciousness, did not qualify for self-determination. Alexander Chervyakov and Zmicier Zhylunovich of the Belarusian National Commissariat, set up within the People’s Commissariat for Nationalities on 31 January 1918, held instead that a Belarusian Soviet republic was needed, and the Russian-language source notes that the Belarusian People’s Republic’s declaration of independence of 25 March played no small part in shaping that view. A conference of the Belarusian sections of the Russian Communist Party in Moscow on 21–23 December decided to set up the republic, and on 30–31 December the Sixth Conference of the Western Oblast party organisations in Smolensk declared itself the founding congress of the Communist Party (Bolsheviks) of Byelorussia and elected a Provisional Workers’ and Peasants’ Government under Zhylunovich. The republic was proclaimed to comprise the Vitebsk, Grodno, Mogilev, Minsk and Smolensk Governorates, and its government moved to Minsk in early January. On 16 January, however, the Central Committee of the Russian Communist Party decided to return the Smolensk, Vitebsk and Mogilev Governorates to Russia and to merge the republic with Soviet Lithuania. The First All-Belarusian Congress of Soviets in Minsk on 2–3 February adopted a constitution and cut the territory to the Minsk and Grodno Governorates; in wartime the government actually controlled only six uyezds of the Minsk Governorate. On 27 February the republic was absorbed into Litbel.\n\nAfter the Red Army retook Minsk on 11 July 1920, a meeting on 30 July of the Communist Party of Lithuania and Belorussia, Vsevolod Ignatovsky’s Belorussian Communist Organisation and the Bund decided to re-establish the republic and formed the Belorussian Military Revolutionary Committee. The republic was proclaimed again on 31 July, its declaration of independence covering less than six uyezds of the Minsk Governorate. The Union Workers’ and Peasants’ Treaty with the Russian Socialist Federative Soviet Republic of 16 January 1921 recognised the independence and sovereignty of both parties. The Treaty of Riga of 1921 fixed the borders and left Western Belarus to Poland, and in December 1922 the republic signed the treaty on the formation of the USSR together with the Russian, Ukrainian and Transcaucasian republics. The English-language source notes that Soviet historiography has referred to the republic by its later name as a Union republic, the Byelorussian Soviet Socialist Republic, and describes it as a buffer republic in Bolshevik eyes.'],
        aliases: { ko: ['백러시아 사회주의 소비에트 공화국'], en: ['SSRB', 'Socialist Soviet Republic of Belorussia', 'Belorussian Socialist Soviet Republic'] },
        people: ['zmicier-zhylunovich', 'alexander-myasnikov', 'alexander-chervyakov', 'vilgelm-knorin', 'adolph-joffe', 'sverdlov', 'stalin'],
        events: ['belarus-1917-1921', 'civil-war', 'soviet-polish-war', 'ussr-formation'],
        sources: [S.ssrbRU, S.ssrb, S.litbel], locator: 'ru SSRB: lead; Предыстория; Создание ССРБ; Ликвидация ССРБ; Восстановление ССРБ — en SSRB: History — en Litbel: Background; Minsk and Vilna congresses; Final stages of the republic',
    }),
    term({
        id: 'litbel', ko: '리투아니아-벨로루시 사회주의 소비에트 공화국', en: 'Socialist Soviet Republic of Lithuania and Belorussia', category: 'party-state', period: '1919–1920', startYear: 1919, endYear: 1920,
        definition: ['1919년 2월 27일 소비에트 리투아니아와 벨로루시 사회주의 소비에트 공화국이 합쳐 세운 소비에트 공화국. 줄여서 리트벨이라 한다. 빌뉴스를 수도로 삼았으나 폴란드군과 리투아니아군의 진격으로 8월까지 주장한 영토를 모두 잃었다. 흔히 소비에트 러시아의 괴뢰 국가로 평가되며, 끝난 시점은 학자마다 다르다. 소련 역사학은 벨로루시 공화국이 다시 세워진 1920년 7월 31일을 끝으로 본다.',
            'The Soviet republic formed on 27 February 1919 by the merger of Soviet Lithuania and the Socialist Soviet Republic of Byelorussia, known for short as Litbel. Its capital was Vilnius, but the advance of the Polish and, to a lesser extent, the Lithuanian armies stripped it of all its claimed territory by August 1919. It is often described as a puppet state of Soviet Russia, and its end date is disputed; Soviet historiography dated it to 31 July 1920, when the Byelorussian republic was re-established.'],
        body: ['1919년 1월 16일 러시아 공산당 중앙위원회는 소비에트 리투아니아와 소비에트 벨로루시의 통합을 결정했다. 1월 22일 모스크바의 대표로 민스크에 온 아돌프 이오페에게 벨로루시 볼셰비키 지도부는 통합을 거부하며 그가 무능하다고 항의했다. 그러나 2월 2~3일 제1차 전벨로루시 소비에트 대회에서 야코프 스베르들로프가 「백군-벨라루스-리투아니아 정부」에 맞서려면 단결해야 한다고 호소했고, 2월 18~20일 빌뉴스의 리투아니아 소비에트 대회(대의원 220명)도 통합에 찬성했다. 2월 27일 두 공화국 중앙집행위원회의 합동 회의는 카지미에시 치호프스키를 중앙집행위원회 의장으로, 빈차스 카프수카스를 인민위원회 의장으로 뽑았다. 영토 안의 인구는 약 400만 명이었다. 공용어는 러시아어·벨라루스어·리투아니아어·폴란드어·이디시어 다섯이었으나 실제로는 러시아어가 주로 쓰였다. 이오페가 주요 각료를 직접 골랐고, 정부에서는 리투아니아인이 벨로루시인보다 많아 벨로루시인은 대개 두 번째 자리에 머물렀다. 3월 4~6일 두 공산당이 합쳐 리투아니아·벨로루시 공산당이 되었는데, 몰수한 영지를 농민에게 나누지 않고 국영 농장으로 만들기로 한 결정이 농민과 당의 관계를 틀어지게 했다.\n\n폴란드군이 4월 17~21일 빌뉴스를 점령하자 정부는 드빈스크를 거쳐 4월 28일 민스크로 옮겼다. 4월 19일 카프수카스·이오시프 운쉴리흐트·모이세이 칼마노비치로 국방회의가 꾸려졌고, 5월 30일 중앙집행위원회는 군사와 경제 업무를 러시아 소비에트 공화국 정부에 넘기는 조약에 서명했다. 3월 13일 창설된 리투아니아-벨로루시군은 5월 말까지 안드레이 스네사레프가 지휘했으나 6월 9일 붉은 군대 제16군으로 바뀌었다. 18~40세 남성 징집령은 주민의 저항에 부딪혀 6월 민스크현의 탈영병이 약 3만 3천 명에 이르렀고, 전시 공산주의 아래의 징발과 러시아로의 식량 공출 압박 속에 6월에는 기근이 퍼졌다. 7월 13일 이오시프 스탈린이 국방회의와 인민위원회의 해산을 제안했고, 7월 17일 국방회의가 해산되었다. 폴란드군은 8월 8일 민스크를, 8월 27일 마지막 도시인 노보알렉산드롭스크를 차지했다. 역사가들은 리트벨을 괴뢰 국가(피오트르 워소프스키, 데이비드 마플스 등)나 「종이 국가」(도로타 미하우크)로 보며, 소련 역사학은 반혁명에 맞선 방어 조치로 설명했다.',
            'On 16 January 1919 the Central Committee of the Russian Communist Party decided to unite Soviet Lithuania and Soviet Belorussia. When Adolph Joffe arrived in Minsk on 22 January as Moscow’s representative, the Belorussian Bolshevik leaders rejected the merger and protested that he was incompetent. At the First All-Belorussian Congress of Soviets on 2–3 February, however, Yakov Sverdlov called for unity against the “White Army-Belorussian-Lithuanian government”, and the Lithuanian Congress of Soviets in Vilnius on 18–20 February, with 220 delegates, also backed the union. A joint meeting of the two Central Executive Committees on 27 February elected Kazimierz Cichowski chairman of the Central Executive Committee and Vincas Kapsukas chairman of the Council of People’s Commissars. The territory under its control had about four million inhabitants. It had five official languages – Russian, Belorussian, Lithuanian, Polish and Yiddish – though Russian predominated in practice. Joffe hand-picked the key ministers, and Lithuanians outnumbered Belorussians in the government, the latter generally confined to second-tier posts. On 4–6 March the two Communist parties merged into the Communist Party of Lithuania and Belorussia, whose decision to turn confiscated estates into state farms instead of dividing them among the peasants soured relations between the peasantry and the party.\n\nWhen the Polish army took Vilnius on 17–21 April, the government moved via Dvinsk to Minsk on 28 April. A Defence Council of Kapsukas, Iosif Unshlikht and Moisei Kalmanovich was formed on 19 April, and on 30 May the Central Executive Committee signed a treaty handing military and economic affairs to the government of the Russian Soviet republic. The Lithuanian-Belorussian Army, created on 13 March and commanded by Andrei Snesarev until the end of May, became the 16th Army of the Red Army on 9 June. The conscription of men aged 18 to 40 met popular resistance, leaving some 33,000 deserters in the Minsk Governorate by June, and amid war-communist requisitions and pressure to supply food to Russia famine spread in June. On 13 July Joseph Stalin proposed dissolving the Defence Council and the Council of People’s Commissars, and the Defence Council was dissolved on 17 July. Polish forces took Minsk on 8 August and Novoalexandrovsk, the republic’s last town, on 27 August. Historians have called Litbel a puppet state (Piotr Łossowski, David Marples and others) or a “paper state” (Dorota Michaluk), while Soviet historiography presented it as a defensive measure against counter-revolution.'],
        aliases: { ko: ['리트벨', '리투아니아-벨로루시 소비에트 사회주의 공화국'], en: ['Litbel', 'LitBel', 'SSR LiB', 'Lithuanian–Byelorussian Soviet Socialist Republic', 'Lithuanian-Byelorussian SSR', 'Socialist Soviet Republic of Lithuania and White Russia'] },
        people: ['vincas-kapsukas', 'adolph-joffe', 'sverdlov', 'zigmas-angarietis', 'iosif-unshlikht', 'moisei-kalmanovich', 'vilgelm-knorin', 'andrei-snesarev', 'stalin', 'zmicier-zhylunovich'],
        events: ['belarus-1917-1921', 'soviet-polish-war', 'baltic-wars-of-independence', 'civil-war'],
        sources: [S.litbel], locator: 'lead; Background; Minsk and Vilna congresses; Founding of the SSR LiB; Evacuation to Minsk; Evacuation to Bobruisk; Fall of Minsk and Bobruisk; Government; Defense Council; Economy; Army; Historiography',
    }),
    term({
        id: 'slutsk-uprising-1920', ko: '슬루츠크 봉기', en: 'Slutsk uprising', category: 'nationalities', period: '1920', startYear: 1920, endYear: 1920,
        definition: ['1920년 11~12월 소비에트-폴란드 전쟁이 끝나갈 무렵 슬루츠크 일대에서 벨라루스 인민공화국에 충성하는 비정규 부대가 붉은 군대에 맞서 독립 벨라루스를 세우려 한 무장 시도. 「슬루츠크 무장 투쟁」이라고도 한다. 리가 예비 강화가 슬루츠크군을 소비에트 쪽에 넘기자 지역 대회가 봉기를 결정했고, 반군은 12월 28일 새 국경을 넘어 무기를 내려놓았다.',
            'An armed attempt in November–December 1920, near the end of the Polish–Soviet War, by irregular Belarusian forces loyal to the Belarusian People’s Republic to establish an independent Belarus against the Red Army in the region of Slutsk; also called the Slutsk defence or Slutsk military action. After the preliminary peace of Riga assigned the Slutsk district to the Soviet side, a district congress launched the rising, and the insurgents laid down their arms across the new border on 28 December.'],
        body: ['1920년 10월 12일 리가에서 맺은 예비 강화는 오늘날의 벨라루스와 우크라이나 땅을 둘로 나누는 국경을 정했고, 그 경계선에 따라 슬루츠크군은 벨로루시 소비에트 공화국에 넘어가게 되었다. 회담에는 벨라루스 인민공화국 대표도, 소비에트 벨로루시 대표도 초청되지 않았다. 그해 가을 민스크현에서는 벨라루스 민족운동이 퍼져, 어떤 볼로스트 주민들은 모스크바가 임명한 혁명위원회를 거부했다. 슬루츠크에는 1918년 파벨 자브리트의 벨라루스 민족위원회가 세워졌고, 독립 운동의 지지자 대부분은 벨라루스 사회혁명당 슬루츠크 위원회에 모였다. 러시아어 출처는 봉기의 주력이 전시 공산주의에 저항한 농민이었고 지역 지식인과 소귀족이 이끌었다고 설명한다. 폴란드군이 물러가며 고장 난 소총 500정을 남겼고, 억류된 부와크-바와호비치 부대의 잔존 병력이 소총과 기관총, 탄약을 넘겼다. 11월 15일 슬루츠크와 15개 볼로스트의 대의원 105~132명이 모인 대회는 이 일대에 벨라루스 인민공화국의 권력을 선포하고 「볼셰비키 점령」에 항의했으며, 사회혁명당원 블라디미르 프라쿨레비치를 의장으로 17명의 슬루츠크 라다를 뽑았다. 라다는 16~50세 남성의 총동원을 선포하고 사흘 만에 제1슬루츠크 연대와 제2그로조보 연대로 슬루츠크 여단을 꾸렸다. 무기와 자금을 폴란드군 사령부가 댔는지, 부와크-바와호비치만이 보잘것없는 도움을 주었는지는 벨라루스 역사가들 사이에서 엇갈린다.\n\n폴란드군은 11월 24일 슬루츠크를 떠났고 여단도 서쪽 세메제보로 물러났다. 전투는 11월 27일 시작되어 반군이 바실치치 부근에서 붉은 군대를 물리쳤지만, 붉은 군대 제8·17사단이 들어오자 12월 7일 세메제보를 잃었다. 반군은 12일 많은 포탄과 함께 세메제보를 되찾고 17일 비즈나를 차지했으나, 19일 비즈나에서, 20일 세메제보에서 물러났다. 무기와 장교, 식량이 모자랐고 발진티푸스가 돌았다. 12월 28일 탄약이 떨어진 여단은 새 국경이 된 모로치강을 건너 무기를 내려놓고 폴란드에 억류되었다. 평가는 엇갈린다. 러시아어 출처가 인용한 벨라루스 학계의 한 견해는 폴란드군이 철수하는 땅에 아직 붉은 군대도 소비에트 권력도 없었으므로 봉기라 할 수 없다고 보고, 지휘관이었던 안톤 소콜-쿠틸롭스키도 「봉기는 없었다」고 썼다. 반면 페레스트로이카 이후 벨라루스 인민전선 등은 11월 27일을 「영웅의 날」로 기념해 왔으나, 루카셴코 정부는 이 사건을 중요하게 여기지 않는다. 1948년 독일 미텐발트에 망명자들이 기념비를 세웠고, 바실 비카우의 소설 『검은 화전 위에서』와 1995년의 영화가 이 사건을 다루었다.',
            'The preliminary peace signed in Riga on 12 October 1920 drew a border that divided the lands of present-day Belarus and Ukraine in two, and its demarcation line assigned the Slutsk district to the Byelorussian Soviet republic. No delegation was invited to the talks either from the Belarusian People’s Republic or from Soviet Byelorussia. That autumn the Belarusian national movement spread through the Minsk Governorate, where the people of some volosts rejected the revolutionary committees appointed from Moscow. In Slutsk Paval Zhavryd’s Belarusian National Committee had been set up in 1918, and most supporters of independence gathered in the Slutsk committee of the Belarusian Party of Socialist Revolutionaries. The Russian-language source explains that the main force of the rising was the peasantry resisting war communism, led by the local intelligentsia and petty gentry. The retreating Polish troops left behind 500 faulty rifles, and the interned remnants of Bułak-Bałachowicz’s force handed over rifles, machine guns and ammunition. On 15 November a congress of 105–132 delegates from Slutsk and 15 volosts proclaimed the authority of the Belarusian People’s Republic in the area, protested against the “Bolshevik occupation” and elected a 17-member Slutsk Rada chaired by the Socialist Revolutionary Uladzimir Prakulevich. The Rada declared a general mobilisation of men aged 16 to 50 and within three days formed the Slutsk Brigade from the 1st Slutsk and 2nd Hrozava regiments. Belarusian historians disagree over whether the Polish command supplied arms and money or whether only Bułak-Bałachowicz gave meagre help.\n\nThe Polish troops left Slutsk on 24 November and the brigade withdrew west to Semezhevo. Fighting began on 27 November, and the insurgents beat back the Red Army near Vasilchitsy, but once the Red 8th and 17th Divisions arrived they lost Semezhevo on 7 December. They retook it on the 12th along with large stocks of shells and took Vyzna on the 17th, but fell back from Vyzna on the 19th and from Semezhevo on the 20th. Arms, officers and food ran short, and typhus broke out. On 28 December, out of ammunition, the brigade crossed the Moroch river, now the border, laid down its arms and was interned by Poland. Assessments differ. One view in Belarusian scholarship, cited by the Russian-language source, holds that there could be no uprising because neither the Red Army nor Soviet power was yet present in the land the Poles were evacuating, and the commander Anton Sokal-Kutyloŭski himself wrote that “there was no uprising”. Since perestroika, by contrast, the Belarusian Popular Front and others have marked 27 November as Heroes Day, while Lukashenko’s government does not regard the event as significant. Emigrants raised a monument near Mittenwald in Germany in 1948, and Vasil Bykau’s novel On Black Slash-and-Burn Fields and a 1995 film portrayed the events.'],
        aliases: { ko: ['슬루츠크 무장 투쟁', '슬루츠크 방어전'], en: ['Slutsk defence', 'Slutsk military action', 'Slutsk Uprising', 'Słuck uprising', 'Slucki zbrojny čyn'] },
        people: ['stanislaw-bulak-balachowicz'],
        events: ['belarus-1917-1921', 'soviet-polish-war', 'civil-war'],
        sources: [S.slutsk, S.slutskRU], locator: 'en: lead; Prelude; Modern reflections; In culture — ru: Предыстория; Съезд Слуцкого уезда; Военная подготовка; Военные действия; Современное восприятие',
    }),
    term({
        id: 'first-all-belarusian-congress', ko: '제1차 전벨라루스 대회', en: 'First All-Belarusian Congress', category: 'nationalities', period: '1917', startYear: 1917, endYear: 1917,
        definition: ['1917년 12월 18~31일(구력 5~18일) 대벨라루스 라다가 민스크에 소집한 벨라루스 정치 단체들의 대회. 1,872명의 대의원이 모여 벨라루스 민족의 자결권과 민주공화정을 인정했으나, 결의안의 첫 항만 채택한 채 서부 주 볼셰비키 당국에 해산되었다. 대회가 뽑은 라다와 집행위원회는 지하에서 활동을 이어 가 1918년 벨라루스 인민공화국의 라다가 되었다.',
            'The congress of Belarusian political organisations convened in Minsk by the Great Belarusian Rada on 18–31 December 1917 (O.S. 5–18 December). Its 1,872 delegates recognised the Belarusian people’s right to self-determination and a democratic republican form of government, but it was dispersed by the Bolshevik authorities of the Western Oblast after adopting only the first point of its resolution. The council and executive committee it elected carried on underground and in 1918 became the Rada of the Belarusian People’s Republic.'],
        body: ['대회를 열자는 생각은 1917년 봄부터 여러 벨라루스 정치 조직 사이에서 나왔고, 11월 대벨라루스 라다와 중앙 벨라루스 군사 라다, 서부 전선의 벨라루스 집행위원회가 「벨라루스 민족 전체에게」 호소문을 내 12월 5일(신력 18일) 민스크 대회를 소집했다. 첫 회의에는 1,872명의 대의원이 나왔고 그 가운데 1,167명이 의결권을 가졌다. 민스크·모길료프·비텝스크·그로드노·스몰렌스크·빌뉴스의 향우회, 우파와 좌파 사회혁명당, 볼셰비키와 멘셰비키, 흐라마다, 젬스트보와 시의회, 노동조합, 병사와 피란민, 소비에트 대표까지 모였고, 대의원 다수는 농민 출신이었다. 핵심 쟁점은 러시아와의 관계였다. 우파 성향과 서부 출신 대의원은 즉시 완전한 독립을 주장했고, 좌파와 동부 출신은 민주적 러시아 연방 안에 남자고 했다. 러시아어 출처는 넓은 자치나 독립을 주장한 벨라루스 사회주의 흐라마다와, 동부 출신이 많고 러시아와의 연합을 고수한 「지역주의자」의 대립을 강조한다. 대회는 얀 세라다를 의장으로 71명의 라다와 그 집행위원회를 뽑았다.\n\n12월 18일(구력) 새벽 1시 15분, 15개 항의 타협적 결의안이 낭독되었다. 결의안은 「자치」라는 말조차 쓰지 않고 지역 통치와 러시아 연방과의 관계를 다루었으며, 임시 지역 권력이 벨라루스 제헌 회의를 서둘러 소집하도록 했다. 대의원들은 첫 항만 만장일치로 채택할 수 있었다. 그때 볼셰비키 병력이 건물을 에워쌌고, 서부 주 내무위원 류드비크 레자프스키가 들어와 대회 해산과 의장단 체포를 선언했다. 대의원들은 바리케이드를 쌓고 주먹다짐까지 벌였지만 세라다를 포함한 의장단 27명이 체포되고 대의원들은 쫓겨났다. 대회 라다는 다음 날 비밀리에 모였고, 1918년 1월 2일(구력 1917년 12월 20일) 17명의 집행위원회를 뽑았다. 서부 주 정부 의장 카를 란데르는 소브나르콤과 스탈린에게 보낸 전보에서 대회를 크게 왜곡해 보고했다. 러시아어 출처는 해산의 주된 이유를 권력을 나누기 싫어한 서부 주 당국에서 찾고 법적 근거는 없었다고 보며, 현장에 있던 알렉산드르 체르뱌코프, 즈미체르 질루노비치, 빌헬름 크노린도 뒤에 해산이 꼭 필요했는지 의문을 나타냈다. 벨라루스 측 저자들에 따르면 대회는 벨라루스 문제를 국제 의제로 올려, 브레스트-리토프스크 강화 회담에서 소비에트 측이 해산을 이유로 비판받았다. 1919년 2월 볼셰비키는 같은 장소에서 이름이 거의 같은 제1차 전벨로루시 소비에트 대회를 열었다.',
            'The idea of a congress had circulated among Belarusian political organisations since the spring of 1917, and in November the Great Belarusian Rada, the Central Belarusian Military Rada and the Belarusian executive committee of the Western Front issued an appeal “To the whole Belarusian people” convening it in Minsk from 5 (18) December. The first session was attended by 1,872 delegates, 1,167 of them with a vote. Regional associations of Minsk, Mogilev, Vitebsk, Grodno, Smolensk and Vilnius, right and left Socialist Revolutionaries, Bolsheviks and Mensheviks, the Hramada, zemstvos and town councils, trade unions, soldiers, refugees and soviets were all represented, and most delegates were of peasant origin. The central question was the relationship with Russia. Right-leaning delegates and many from western Belarus wanted immediate full independence, while left-leaning and eastern delegates proposed staying within a democratic Russian federation. The Russian-language source stresses the clash between the Belarusian Socialist Hramada, which sought broad autonomy or even independence, and the “regionalists”, mostly from the east, who held to union with Russia. The congress elected a 71-member council under Jan Sierada and its executive committee.\n\nAt 1:15 a.m. on 18 December (O.S.) a 15-point compromise resolution was read out. It avoided even the word “autonomy”, dealing instead with the government of the region and its link with a Russian federation, and charged a provisional regional authority with convening a Belarusian constituent assembly as soon as possible. The delegates managed to adopt only the first point, unanimously. Bolshevik troops then surrounded the building, and Ludvik Rezavsky, the Western Oblast’s commissar for internal affairs, came in to declare the congress dissolved and its presidium arrested. The delegates built barricades and came to blows, but 27 members of the presidium, Sierada among them, were arrested and the delegates driven out. The council met in secret the next day and on 2 January 1918 (O.S. 20 December 1917) elected a 17-member executive committee. Karl Lander, chairman of the Western Oblast government, gave a badly distorted account of the congress in his telegram to the Sovnarkom and Stalin. The Russian-language source finds the main reason for the dispersal in the Western Oblast authorities’ unwillingness to share power and sees no legal basis for it, and Alexander Chervyakov, Zmicier Zhylunovich and Vilgelm Knorin, who were present, later doubted that it had been necessary. According to Belarusian authors the congress put the Belarusian question on the international agenda, and the Soviet side was criticised for the dispersal at the Brest-Litovsk peace talks. In February 1919 the Bolsheviks held their First All-Belarusian Congress of Soviets, with an almost identical name, in the same building.'],
        aliases: { ko: ['전벨라루스 대회', '1917년 전벨라루스 대회'], en: ['All-Belarusian Congress', 'First All-Belarusian Conference', 'All-Belarusian Congress of 1917'] },
        people: ['jan-sierada', 'piotra-krecheuski', 'alexander-chervyakov', 'zmicier-zhylunovich', 'vilgelm-knorin', 'stalin'],
        events: ['belarus-1917-1921', 'october-revolution', 'brest-litovsk'],
        sources: [S.congress, S.congressRU], locator: 'en: lead; Background; The congress; Aftermath — ru: История',
    }),
    term({
        id: 'belarusian-socialist-hramada', ko: '벨라루스 사회주의 흐라마다', en: 'Belarusian Socialist Hramada', category: 'nationalities', period: '1902–1919', startYear: 1902, endYear: 1919,
        definition: ['러시아 제국의 벨라루스 지역에서 활동한 첫 벨라루스 민족 정당. 1902년 겨울 벨라루스 혁명 흐라마다로 세워져 1903년 12월 이름을 바꾸었다. 사회주의적 개혁과 함께 빌뉴스에 의회를 두는 민족·지역 자치를 요구했고, 뒤에는 독자 국가를 내세웠다. 1917년 혁명 뒤 벨라루스 인민공화국 수립을 이끌었으나 여러 정당으로 갈라졌고, 1919년 7월 27일 활동을 끝냈다.',
            'The first Belarusian national political party, active in the Belarusian lands of the Russian Empire. Founded in the winter of 1902 as the Belarusian Revolutionary Hramada, it took its new name in December 1903. Alongside socialist reforms it demanded national and territorial autonomy with a diet in Vilnius, and later statehood of its own. After the revolution of 1917 it led the way to the Belarusian People’s Republic, but it split into several parties and ceased to exist on 27 July 1919.'],
        body: ['당은 벨라루스 청년들의 민족·문화 동아리들을 바탕으로 생겼고, 안톤·이반 루츠케비치 형제와 알라이자 파시케비치 등이 창립을 이끌었다. 1903년 12월 빌뉴스의 제1차 대회는 이름을 벨라루스 사회주의 흐라마다로 바꾸고 첫 강령을 채택했는데, 대소비에트 백과사전에 따르면 폴란드 사회당 강령에 빌뉴스 의회를 둔 민족·지역 자치 요구를 더한 것이었다. 당은 토지의 지방 공유화와 노동 입법을 주장했고, 전제정 타도라는 당면 목표를 위해 제국의 다른 좌파 세력과 함께 행동해야 한다고 보았다. 계급 투쟁의 중요성은 인정하면서도 벨라루스인 사이의 계급 투쟁은 부정했다. 당원은 주로 지식인과 농민, 농업 노동자였고 민스크·빌뉴스·상트페테르부르크에 지부가 있었다. 1906년 1월 민스크에서 제2차 대회를 열었으나 1907년부터는 사실상 활동을 멈추고 합법 벨라루스어 신문 『나샤 니바』의 발행에 힘을 모았다. 얀 세라다, 바츨라우 라스토우스키, 즈미체르 질루노비치, 언어학자 브라니슬라우 타라시케비치, 뒤의 라다 의장 바실 자하르카, 라다의 유일한 여성 위원 팔루타 바두노바 등이 당원이었다.\n\n2월 혁명 뒤 흐라마다는 활동을 되살려 벨라루스 자치, 이어 독자 국가 건설에 나섰다. 1917년 9월 마르크스주의 계열 일부가 벨라루스 사회민주노동당을 만들려고 떠났고, 10월 14~25일 민스크의 제3차 대회에서는 여러 집단 사이의 큰 이견이 드러났다. 1917~1918년 벨라루스 사회혁명당, 벨라루스 사회주의 연방주의자당, 벨라루스 사회민주당이 갈라져 나갔다. 그래도 흐라마다는 벨라루스 인민공화국 수립에서 큰 역할을 했고, 영어 출처에 따르면 1918년 3월 19일 그 주도로 라다가 임시 의회가 되었으며 라다 위원 대부분이 당원이었다. 볼셰비키는 흐라마다를 적대시해, 레닌은 이를 「좌익 인민주의 성향의 민족주의 소부르주아 정당」이라 불렀고 서부 주 제2차 소비에트 대회는 라다를 반혁명·반소비에트 기구로 선언했다. 당은 1919년 7월 27일 활동을 끝냈다. 소비에트-폴란드 전쟁 뒤 폴란드령이 된 서벨라루스에 남은 많은 활동가는 벨라루스 자치를 위해 싸웠고, 1925년 폴란드 의회의 벨라루스 의원들이 세운 벨라루스 농민·노동자 흐라마다는 이름은 비슷하지만 다른 정당이다.',
            'The party grew out of national and cultural circles of young Belarusians, and the brothers Anton and Ivan Luckievič and Alaiza Pashkevich were among its founders. Its first congress in Vilnius in December 1903 renamed it the Belarusian Socialist Hramada and adopted its first programme, which according to the Great Soviet Encyclopedia took over the programme of the Polish Socialist Party and added a demand for national and territorial autonomy with a diet in Vilnius. The party called for the municipalisation of land and for labour legislation, and held that it should act together with the other left-wing forces of the empire towards the immediate goal of overthrowing the autocracy. While acknowledging the importance of class struggle in general, it denied that there was class struggle among Belarusians. Its members were mainly intellectuals, peasants and agricultural labourers, and it had branches in Minsk, Vilnius and Saint Petersburg. It held its second congress in Minsk in January 1906, but from 1907 it practically ceased active work and concentrated on publishing the legal Belarusian-language newspaper Nasha Niva. Its members included Jan Sierada, Vaclau Lastouski, Zmicier Zhylunovich, the linguist Branislaŭ Taraškievič, the later Rada chairman Vasil Zacharka and Paluta Badunova, the only woman in the Rada.\n\nAfter the February Revolution the Hramada revived and worked for Belarusian autonomy and then for statehood. In September 1917 part of its Marxist wing left to found the Belarusian Social Democratic Workers’ Party, and its third congress in Minsk on 14–25 October revealed deep disagreements between its groups. In 1917–1918 the Belarusian Party of Socialist Revolutionaries, the Belarusian Party of Socialist Federalists and the Belarusian Social Democratic Party split off. The Hramada nonetheless played a large part in founding the Belarusian People’s Republic; according to the English-language source the Rada became the temporary parliament on its initiative on 19 March 1918, and most of the Rada’s members belonged to it. The Bolsheviks were hostile: Lenin called it a “nationalist petite bourgeoisie party of left-populist orientation”, and the Second Congress of Soviets of the Western Oblast declared the Rada counter-revolutionary and anti-Soviet. The party ceased to exist on 27 July 1919. After the Polish–Soviet War many of its activists found themselves in Western Belarus under Poland and fought for Belarusian autonomy; the Belarusian Peasants’ and Workers’ Hramada, founded in 1925 by Belarusian deputies to the Polish Sejm, is a different party despite the similar name.'],
        aliases: { ko: ['벨라루스 혁명 흐라마다', '벨라루스 사회주의 흐로마다'], en: ['Belarusian Socialist Assembly', 'Belarusian Revolutionary Hramada', 'Belarusian Revolutionary Party', 'Biełaruskaja sacyjalistyčnaja hramada', 'BSH'] },
        people: ['anton-luckievic', 'jan-sierada', 'vaclau-lastouski', 'zmicier-zhylunovich', 'lenin'],
        events: ['belarus-1917-1921', 'civil-war'],
        sources: [S.bsaRU, S.bsa, S.bpwu, S.zhyl], locator: 'ru: lead; История; Программа и социальный состав — en BSA: lead; Notable members — en BPWU: lead — en Zhylunovich: Life',
    }),
];
