-- 052_commulingo_nkvd_subordinates.sql
-- Adds the subordinates of the three NKVD chiefs already in the dictionary
-- (yagoda, yezhov, beria). Three cohorts, plus the Georgian apparatus:
--   * Yagoda's OGPU/NKVD department heads and regional barons
--   * The Gulag and canal administrators
--   * Beria's Transcaucasian clients, incl. the December 1953 trial group
--   * The Georgian security officials tried at Tbilisi in September 1955
--
-- Framing note: the cohorts are patronage networks, not fates. Only Molchanov,
-- Pauker and Prokofiev fell *with* Yagoda; Balitsky, Berman and Deribas
-- outlasted him and were purged later by Yezhov. Evdokimov left the organs for
-- party work in Jan 1934, was hostile to Yagoda, and rose under Yezhov because
-- of it. Each bio states the man's own trajectory rather than his patron's.
--
-- Sourcing: Petrov & Skorkin, "Kto rukovodil NKVD 1934-1941"; Petrov, "Kto
-- rukovodil organami gosbezopasnosti 1941-1954"; RGASPI indictment texts
-- (f.17 op.171 dd.474/476) via istmat; Memorial execution-list data.
-- Contested claims are omitted rather than asserted. Specifically excluded:
-- Blokhin's cause of death (suicide vs. heart attack, both in the record) and
-- his apron/gauntlets (one 1991 deposition); Pauker's Orlov-memoir anecdotes;
-- Nadaraya's custodial testimony about Beria's sexual crimes; Tsanava's
-- "suicide" (medical record gives cardiac failure); Molchanov's rehabilitation
-- (three sources, three answers). `moment` is left empty throughout: no
-- attributable quotation survives for these men that is not memoir-derived.
--
-- Idempotent: ON CONFLICT updates content but preserves existing sort_order.
--
-- DO NOT REPLAY THIS ON A LIVE DB. It was applied once, on 2026-07-15. People
-- are normally edited through the admin UI (data/commulingo/people-admin-store.js),
-- and the ON CONFLICT DO UPDATE above would silently overwrite any later edit to
-- these 32 rows with the prose below. It is committed as the textual record of
-- this content and of the sourcing decisions above, not as a replayable step.
-- If you need it in a fresh environment, check first that these ids are absent.

INSERT INTO commulingo_people
    (id, group_id, sort_order, initial, cyrillic, years_label, birth_year, death_year,
     name_ko, name_en, epithet_ko, epithet_en, moment_ko, moment_en, bio_ko, bio_en,
     fate_kind, fate_label_ko, fate_label_en,
     citizenship_code, citizenship_label_ko, citizenship_label_en,
     origin_code, origin_label_ko, origin_label_en, updated_at)
SELECT v.id, 'stalin-era',
       (SELECT COALESCE(MAX(sort_order), -1) FROM commulingo_people) + v.ord,
       v.initial, v.cyrillic, v.years_label, v.birth_year, v.death_year,
       v.name_ko, v.name_en, v.epithet_ko, v.epithet_en, '', '', v.bio_ko, v.bio_en,
       v.fate_kind, v.fate_label_ko, v.fate_label_en,
       'soviet', '소련', 'Soviet Union',
       v.origin_code, v.origin_label_ko, v.origin_label_en, NOW()
FROM (VALUES

-- ---------------------------------------------------------------- Yagoda's men
('molchanov', 1, 'Г', 'Георгий Молчанов', '1897–1937', 1897, 1937,
 '게오르기 몰차노프', 'Georgy Molchanov',
 '야고다의 비밀정치국장', 'Yagoda''s chief of the Secret Political Department',
 $q$1920년 체카에 들어가 그로즈니 체카 의장과 이바노보-보즈네센스크 GPU 책임자를 지내며 집단화기의 탄압을 조직했다. 1931년 11월 야고다는 그를 비밀정치국(SPO) 국장에 앉혔다. 반대파와 성직자, 인텔리겐치아, 농민을 감시하고 탄압하는 기관으로, 야고다 체제의 정치경찰 기능 그 자체였다. 1932년 류틴 그룹 체포를 지휘했고, 1934년 키로프 암살 뒤의 대량 체포('키로프 물결')를 운영했으며, 1935년 크렘린 사건과 1936년 8월 지노비예프-카메네프 재판의 수사 실무를 맡았다. 그의 자리는 전적으로 야고다의 후원에 달려 있었다. 1936년 9월 예조프가 야고다를 대체하자 SPO에서 밀려나 벨로루시 NKVD로 좌천됐고, 예조프가 야고다의 기구를 숙청할 때 가장 먼저 체포된 고위 간부 중 하나가 되어 1937년 10월 총살됐다.$q$,
 $q$Molchanov entered the Cheka in 1920 and rose through provincial security work, chairing the Grozny Cheka and running the Ivanovo-Voznesensk GPU, where he organized repression during forced collectivization. In November 1931 Yagoda made him chief of the Secret Political Department, the branch responsible for surveillance and repression of former oppositionists, clergy, intelligentsia and the peasantry. He was thus the operational manager of Yagoda's core political-police function: he directed the 1932 arrests of the Ryutin group, ran the mass arrests of the "Kirov stream" after December 1934, and handled the investigative preparation of the 1935 Kremlin Case and the August 1936 Zinoviev-Kamenev trial. His position depended entirely on Yagoda's patronage. When Yezhov took over in September 1936 he was pushed out to the Belorussian NKVD, then became one of the first senior officers arrested in the purge of Yagoda's apparatus. He was shot in October 1937.$q$,
 'executed', '처형', 'Executed', 'ukraine', '우크라이나', 'Ukraine'),

('pauker', 2, 'К', 'Карл Паукер', '1893–1937', 1893, 1937,
 '카를 파우케르', 'Karl Pauker',
 '스탈린의 경호를 맡은 작전국장', 'The operations chief who guarded Stalin',
 $q$렘베르크(현 리비우)의 유대인 이발사이자 극장 분장사 출신으로, 1914년 오스트리아-헝가리군에 징집됐다가 1915년 러시아군에 포로로 잡혔다. 투르케스탄 포로수용소에서 급진화되어 1917년 볼셰비키에 가담했고 1918년 사마르칸트에서 체카에 들어갔다. 1923년부터 OGPU 작전국(Operod) 국장으로 체포와 수색, 감시, 처형, 크렘린 경비를 관장했으며, 1924년부터는 스탈린의 개인 경호를 직접 책임져 그에게 상시로 접근할 수 있는 몇 안 되는 인물이 되었다. 야고다 아래에서 그의 작전국은 1930년대 정치사건의 물리적 기구를 공급했고, 1936년 8월 재판 뒤의 처형을 집행했다. 개인적 근접성은 그를 지켜 주지 못했다. 1937년 4월 당에서 제명·해임되고 며칠 뒤 스탈린 암살 모의 혐의로 체포되어 8월 총살됐으며, 복권되지 않았다.$q$,
 $q$A Galician Jew from Lemberg with four years of schooling, Pauker worked as a theatrical hairdresser and make-up artist before conscription into the Austro-Hungarian army in 1914. Captured in 1915, he was radicalized in a Turkestan POW camp, joined the Bolsheviks in 1917 and entered the Cheka at Samarkand in 1918. By 1923 he headed the OGPU Operations Department, which controlled arrests, searches, surveillance, executions and Kremlin guard duty. From 1924 he personally ran Stalin's bodyguard, becoming a fixture of the household and one of the few men with constant physical access to him. Under Yagoda his department supplied the arresting officers and physical machinery for the political cases of the early 1930s, and administered the executions following the August 1936 trial. Proximity did not protect him: expelled from the party and dismissed in April 1937, he was arrested days later on a charge of preparing an attempt on Stalin's life and shot that August. He has never been rehabilitated.$q$,
 'executed', '처형', 'Executed', 'ukraine', '우크라이나', 'Ukraine'),

('matvei-berman', 3, 'М', 'Матвей Берман', '1898–1939', 1898, 1939,
 '마트베이 베르만', 'Matvei Berman',
 '굴라크를 확장한 최장수 수장', 'The longest-serving chief who built up the Gulag',
 $q$스무 살이던 1918년 체카에 들어가 글라조프 지구 체카 의장을 지냈고, 시베리아와 중앙아시아를 거치며 부랴트-몽골 자치공화국 내무인민위원과 우즈베크 GPU 의장을 역임했다. 1930년 신설된 굴라크의 부책임자가 되었고, 1932년 6월부터 1937년 8월까지 굴라크를 이끌었다. 초기 수장 가운데 최장수였으며 야고다의 NKVD 재임 기간 전체에 걸쳐 수용소 체계를 운영한 인물이다. 그의 아래에서 굴라크는 교정노동 실험에서 소비에트 경제의 핵심 도구로 확장됐다. 1933년 완공된 백해-발트 운하와 이어 모스크바-볼가 운하를 죄수 노동으로 건설했고, 강제노동을 공개적으로 정당화한 '개조'(perekovka) 교리를 선전했다. 그의 몰락은 야고다와 함께 오지 않았다. 1937년 8월 체신인민위원으로 옮겨졌고, 예조프의 측근들이 무너지던 1938년 12월 말렌코프의 집무실에서 체포되어 1939년 3월 총살됐다. 1957년 복권됐다.$q$,
 $q$Berman joined the Cheka in 1918 at twenty and chaired the Glazov district Cheka, then moved through Siberian and Central Asian posts, serving as internal affairs commissar of the Buryat-Mongolian ASSR and chairman of the Uzbek GPU. In 1930 he became deputy chief of the newly created Gulag, and from June 1932 to August 1937 he headed it, the longest-serving of its early chiefs and the man who ran the camp system throughout Yagoda's tenure. Under him the Gulag expanded from a corrective-labour experiment into a central instrument of the Soviet economy: he oversaw the prisoner-built White Sea-Baltic Canal, completed in 1933, and then the Moscow-Volga Canal, and promoted the doctrine of "reforging" that publicly justified forced labour. His fall came later than Yagoda's. In August 1937 he was moved to People's Commissar of Communications, a standard prelude to arrest, and was taken in December 1938 in Malenkov's office as Yezhov's own circle collapsed. He was shot in March 1939 and rehabilitated in 1957.$q$,
 'executed', '처형', 'Executed', 'russia', '러시아', 'Russia'),

('balitsky', 4, 'В', 'Всеволод Балицкий', '1892–1937', 1892, 1937,
 '프세볼로트 발리츠키', 'Vsevolod Balitsky',
 '우크라이나 보안기구의 지배자', 'The master of the Ukrainian security apparatus',
 $q$경력을 거의 전부 우크라이나에서 쌓았다. 1918년 12월 전우크라이나 체카 콜레기움에 들어가 볼히니아와 키예프 체카를 이끌었고, 1923년부터 십사 년 대부분을 우크라이나 GPU 수장으로 보내며 공화국 보안의 지배적 인물이자 동시에 내무인민위원이었다. 1932년 11월 곡물 조달을 무조건 관철하라는 지시와 함께 OGPU 전권대표로 우크라이나에 파견되어 홀로도모르 기간의 보안기구를 지휘했고, 1933년 3월 정치국은 그를 포함한 트로이카에 봉기·반혁명 사건을 사형으로 처결할 권한을 주었다. '우크라이나 군사조직'(UVO) 사건을 비롯한 민족주의 조작 사건들을 운영했고, 키로프 암살 뒤 우크라이나의 대량 체포와 추방을 감독했다. 1935년 국가보안위원 1급에 올랐으나 야고다의 몰락을 일 년도 넘기지 못했다. 1937년 5월 극동으로 전출되었고 7월 예조프의 영장으로 체포되어 11월 총살됐다. 러시아 법원은 1998년 복권을 거부했다.$q$,
 $q$Balitsky built his career almost entirely in Ukraine, entering the All-Ukrainian Cheka collegium in December 1918 and chairing the Volhynia and Kyiv Chekas before heading the Ukrainian GPU from 1923, a post he held for most of the next fourteen years. He was the dominant security figure in the republic and simultaneously its internal affairs commissar. Sent back as OGPU plenipotentiary in November 1932 with instructions to enforce grain procurement unconditionally, he directed the security apparatus during the Holodomor, and in March 1933 the Politburo empowered a troika including him to try insurrection and counter-revolution cases with capital authority. He ran the fabricated Ukrainian nationalist cases of the period, including the "Ukrainian Military Organisation" affair, and after Kirov's murder oversaw mass arrests and deportations. Promoted to Commissar of State Security 1st Rank in 1935, he survived Yagoda's fall by less than a year: transferred to the Far East in May 1937, arrested in July on Yezhov's warrant, and shot in November. Russian courts refused him rehabilitation in 1998.$q$,
 'executed', '처형', 'Executed', 'ukraine', '우크라이나', 'Ukraine'),

('georgy-prokofiev', 5, 'Г', 'Георгий Прокофьев', '1895–1937', 1895, 1937,
 '게오르기 프로코피예프', 'Georgy Prokofiev',
 '경제 파괴 사건을 만들어 낸 부인민위원', 'The deputy commissar who manufactured the wrecking cases',
 $q$키예프 출신 체키스트로 OGPU 비밀국과 정보국을 거쳐 1926년 2월 경제국(EKU) 국장이 되어 1931년까지 이끌었다. 경제 방첩을 담당한 이 부서는 그의 지휘 아래 소비에트 기술 전문가들을 겨눈 대규모 '파괴 공작' 사건들을 만들어 냈고, 산업의 실패를 범죄로 바꾸어 놓았다. 1932년 11월 OGPU 부의장이 되면서 동시에 보안기관에 갓 예속된 일반 경찰, 곧 민병대(GURKM)를 관장했다. 통상적 치안을 체키스트의 통제 아래 두는 통합이었다. 1934년 7월 NKVD가 창설되자 야고다의 제2부인민위원으로서 신설 인민위원부 최상층의 소수 집단에 들었고, 1935년 국가보안위원 1급을 받았다. 야고다의 측근들과 함께 무너졌다. 예조프가 취임한 1936년 9월 체신인민위원부로 옮겨졌고 1937년 4월 체포되어 8월 총살됐으며, 복권되지 않았다.$q$,
 $q$A Kyiv-born Chekist, Prokofiev headed the OGPU Secret Department and then the Information Department before taking over the Economic Directorate in February 1926, which he ran until 1931. That branch was responsible for economic counter-intelligence, and under his direction it manufactured the great wrecking and sabotage cases against Soviet technical specialists that criminalized industrial failure. In November 1932 he became a deputy chairman of the OGPU and simultaneously took charge of the civil militia, the ordinary police, which had just been subordinated to the security organs, a consolidation that placed regular policing under Chekist control. When the NKVD was created in July 1934 he became Yagoda's second deputy commissar, one of the small group at the top of the new commissariat, and received the rank of Commissar of State Security 1st Rank in 1935. He fell with Yagoda's circle: shifted to the Communications commissariat in September 1936 as Yezhov took over, arrested in April 1937, and shot that August. He has not been rehabilitated.$q$,
 'executed', '처형', 'Executed', 'ukraine', '우크라이나', 'Ukraine'),

('redens', 6, 'С', 'Станислав Реденс', '1892–1940', 1892, 1940,
 '스타니슬라프 레덴스', 'Stanislav Redens',
 '스탈린의 처남이자 모스크바주 트로이카 의장', 'Stalin''s brother-in-law who chaired the Moscow troika',
 $q$롬자 지방 출신 폴란드인으로 1918년 체카에 들어가 오데사와 키예프, 하리코프, 크림에서 복무했고, 1920년 크림 체카 의장으로 항복한 브란겔군에 대한 대량 보복을 지휘했다. 스탈린의 두 번째 아내의 언니인 안나 알릴루예바와 결혼해 스탈린의 처남이 되면서 경력이 보강됐다. 자캅카스와 우크라이나 전권대표를 거쳐 1933년 2월 모스크바주 NKVD 관리국장이 되어 야고다의 재임 기간 전체와 예조프 시기 초반까지 그 자리를 지켰다. 야고다 아래에서는 수도권 보안을 운영하며 키로프 암살 뒤의 체포와 지노비예프·카메네프 사건 준비에 관여했다. 가장 큰 역할은 야고다가 몰락한 뒤에 왔다. 1937년 7월 30일 NKVD 명령 제00447호에 따른 모스크바주 트로이카를 주재하며 대량 사형 판결을 내렸고, 처형은 부토보와 코무나르카에서 집행됐다. 1938년 1월 카자흐스탄으로 옮겨졌다가 그해 11월 폴란드 정보기관 간첩 혐의로 체포되어 1940년 2월 총살됐다.$q$,
 $q$A Pole from the Lomzha region, Redens entered the Cheka in 1918 and served in Odessa, Kyiv, Kharkov and Crimea, chairing the Crimean Cheka during the mass reprisals against Wrangel's defeated forces in 1920. His career was reinforced by marriage to Anna Alliluyeva, sister of Stalin's second wife, making him Stalin's brother-in-law. After plenipotentiary postings in Transcaucasia and Ukraine, he was appointed head of the NKVD directorate for Moscow Region in February 1933, holding it through Yagoda's entire tenure and into Yezhov's. Under Yagoda he ran security in the capital region and took part in the post-Kirov arrests and the preparation of cases against Zinoviev and Kamenev. His largest role came after Yagoda's fall: he chaired the Moscow region troika under NKVD Order No. 00447 of 30 July 1937, presiding over mass death sentences, with executions carried out at Butovo and Kommunarka. Moved to Kazakhstan in January 1938, he was arrested that November, accused of spying for Poland, and shot in February 1940.$q$,
 'executed', '처형', 'Executed', 'poland', '폴란드', 'Poland'),

('deribas', 7, 'Т', 'Терентий Дерибас', '1883–1938', 1883, 1938,
 '테렌티 데리바스', 'Terenty Deribas',
 '극동의 보안 총독', 'The security viceroy of the Far East',
 $q$1904년 입당한 고참 볼셰비키로 1918년 당과 적군 정치사업을 거쳐 체카에 들어갔다. 1923년부터 정치적 반대파를 담당한 GPU-OGPU 비밀국을 이끌었고 1927년 비밀작전총국 제1부국장이 되었다. 1929년 OGPU 전권대표로 극동에 파견되어 팔 년을 머물며 지역의 보안 총독이 되었고, 1934년 7월부터 극동변경주 NKVD 관리국장과 극동군 특별부장을 겸했다. 1931년부터 OGPU-NKVD 콜레기움 위원이었다. 이 시기 그는 지역의 수용소 경제를 운영해 바이칼-아무르 철도(BAM) 건설을 죄수 노동으로 지휘했고, 일본과 마주한 국경의 방첩을 관장하며 중국인과 조선인 주민을 겨눈 조작 사건들을 감독했다. 오랜 재임과 독자성은 예조프가 지방 NKVD 실력자들을 겨누자 표적이 되었다. 1937년 5월 해임되고 8월 체포되어 1938년 7월 총살됐으며 1957년 복권됐다.$q$,
 $q$Deribas was an old Bolshevik, in the party since 1904, who came to the Cheka in 1918 from party and Red Army political work. He headed the GPU-OGPU Secret Department from 1923, the branch handling political opposition, and became first deputy chief of the Secret-Operational Directorate in 1927. In 1929 he was sent to the Far East as OGPU plenipotentiary and stayed eight years, becoming the region's security viceroy and, from July 1934, chief of the NKVD directorate for the Far Eastern Territory and head of the Special Department of the Far Eastern Army. He sat on the OGPU-NKVD collegium from 1931. In this period he ran the region's camp economy, directing Baikal-Amur railway construction with prisoner labour, and oversaw counter-intelligence on the Japanese frontier, including fabricated cases against Chinese and Korean populations. Long tenure and independence made him a target once Yezhov moved against regional NKVD barons: removed in May 1937, arrested in August, shot in July 1938. He was rehabilitated in 1957.$q$,
 'executed', '처형', 'Executed', 'ukraine', '우크라이나', 'Ukraine'),

('evdokimov', 8, 'Е', 'Ефим Евдокимов', '1891–1940', 1891, 1940,
 '예핌 예브도키모프', 'Yefim Yevdokimov',
 '샤흐티 사건의 설계자이자 북캅카스의 실력자', 'Architect of the Shakhty case and boss of the North Caucasus',
 $q$내전 세대의 체키스트로 현장의 폭력을 통해 이름을 얻었다. 1920년 11월 체카 '크림 타격단'을 이끌어 항복한 브란겔군 병사들에 대한 대량 처형을 조직했다. 1923년 OGPU 전권대표로 북캅카스에 파견되어 지속적인 지역 권력 기반과 자신의 복무를 넘어 존속한 개인적 후견망을 구축했다. 기술 전문가를 겨눈 최초의 대형 여론재판인 1928년 샤흐티 사건의 설계자로, 자백을 받아내고 유지하는 일을 직접 책임졌으며 1929년부터 OGPU 비밀작전총국을 이끌었다. 야고다와의 관계는 종속이 아니라 적대였다. 1934년 1월 보안기관을 떠나 북캅카스 당 제1서기로 옮겼으므로 야고다의 NKVD 재임기 동안 그는 인민위원부 바깥에 있었다. 1936년 예조프가 취임하자 그의 위상은 크게 올랐고 북캅카스의 부하들이 중앙 NKVD를 채웠으며, 1937년 2월 중앙위원회 총회에서 그는 야고다가 자신의 활동을 방해했다고 공격했다. 예조프와 함께 무너져 1938년 11월 체포되고 1940년 2월 총살됐으며 1956년 복권됐다.$q$,
 $q$Yevdokimov was a Chekist of the civil-war generation who made his name through violence in the field: he headed the Cheka "Crimean Strike Group" in November 1920, organizing the mass executions of Wrangel's surrendered soldiers. Posted to the North Caucasus as OGPU plenipotentiary in 1923, he built a durable regional power base and a personal clientele that outlasted his own service. He was the architect of the 1928 Shakhty case, the first great show trial of technical specialists, personally responsible for extracting and maintaining the confessions, and from 1929 he ran the OGPU's Secret-Operational Directorate. His relationship with Yagoda was hostile rather than subordinate, and he left the security organs in January 1934 for party work as first secretary in the North Caucasus, so during Yagoda's NKVD tenure he was outside the commissariat. When Yezhov took over in 1936 his standing rose sharply, his North Caucasus proteges filled the central NKVD, and at the February 1937 plenum he attacked Yagoda for obstructing him. He fell with Yezhov: arrested in November 1938, shot in February 1940, rehabilitated in 1956.$q$,
 'executed', '처형', 'Executed', 'kazakhstan', '카자흐스탄', 'Kazakhstan'),

-- ---------------------------------------------------------------- Yezhov's men
('leplevsky', 9, 'И', 'Израиль Леплевский', '1896–1938', 1896, 1938,
 '이즈라일 레플렙스키', 'Israel Leplevsky',
 '우크라이나 대량작전을 정점으로 끌어올린 자', 'The man who drove the Ukrainian mass operations to their peak',
 $q$브레스트-리톱스크의 가난한 유대인 가정에서 태어나 분트를 거쳐 1917년 초 볼셰비키에 가담했고, 1920년대 우크라이나 GPU에서 경력을 쌓으며 옛 제정군 장교들을 겨눈 '베스나' 사건에 참여했다. 1934년부터 벨로루시 NKVD를 이끌며 '벨로루시 민족중앙' 사건을 조작했고, 1936년 11월 적군 지휘부 숙청을 담당한 국가보안총국 특별부장으로 옮겨 투하쳅스키 사건에 가까이 있었다. 1937년 6월 예조프는 그를 우크라이나 NKVD 수장으로 키예프에 보냈고, 그곳에서 그는 대량작전을 정점으로 끌어올렸다. 명령 제00447호에 따른 작전, 제00485호에 따른 '폴란드 작전', 날조된 '우크라이나 군사조직' 음모, 옛 보로티비스트 파괴가 그의 지휘 아래 이루어졌다. 1938년 1월 소환되어 수송 부문으로 옮겨졌고, 예조프의 측근들이 해체되던 그해 4월 체포되어 7월 코무나르카에서 총살됐다. 예조프의 고위 부하 가운데 자신이 운영한 테러에 가장 먼저 삼켜진 축에 든다.$q$,
 $q$Born to a poor Jewish family in Brest-Litovsk, Leplevsky passed through the Bund before joining the Bolsheviks in early 1917, and built his career inside the Ukrainian GPU during the 1920s, where he took part in the "Vesna" case against former imperial officers. He ran the NKVD of Belorussia from 1934, fabricating the "Belorussian National Centre" affair, then moved in November 1936 to head the Special Department of the GUGB, the body handling the purge of the Red Army command, which placed him close to the Tukhachevsky case. In June 1937 Yezhov sent him to Kyiv as Ukrainian NKVD chief, where he drove the mass operations to their peak: Order No. 00447, the "Polish operation" under Order No. 00485, the invented "Ukrainian Military Organisation" conspiracy, and the destruction of the former Borotbisty. Recalled in January 1938 and shifted to transport work, he was arrested that April as Yezhov's circle was dismantled and shot at Kommunarka in July, one of the earliest of Yezhov's senior lieutenants consumed by the terror he administered.$q$,
 'executed', '처형', 'Executed', 'belarus', '벨라루스', 'Belarus'),

('uspensky', 10, 'А', 'Александр Успенский', '1902–1940', 1902, 1940,
 '알렉산드르 우스펜스키', 'Alexander Uspensky',
 '자살을 위장하고 달아난 우크라이나 NKVD 수장', 'The Ukrainian NKVD chief who faked his suicide and ran',
 $q$크렘린 경비대와 지방 NKVD를 거쳐 올라온 젊고 공격적인 체키스트였다. 1937년 2월부터 오렌부르크 NKVD 수장으로 대량작전을 유별난 열의로 밀어붙여 예조프의 눈에 들었고, 1938년 1월 레플렙스키를 대신해 우크라이나 NKVD 수장이 되어 우크라이나 테러의 마지막이자 가장 격렬한 국면을 주재했다. 예조프와 스탈린이 계속 올려 잡은 할당에 맞추어 수만 건의 체포를 보고했다. 1938년 가을 예조프가 무너지자 그는 무엇이 닥칠지 알아차렸다. 11월 14일 드네프르 강가에 유서와 외투를 남겨 익사한 것처럼 자살을 위장하고 사라졌다. 위조 서류로 우랄 일대를 다섯 달 떠돌다 1939년 4월 15일 첼랴빈스크주 미아스에서 붙잡혔다. 군사콜레기움 재판을 거쳐 1940년 1월 총살됐고 복권되지 않았다. 그의 도주는 예조프에 대한 기소의 핵심 요소가 되었다.$q$,
 $q$Uspensky was a young, aggressive Chekist who rose through the Kremlin commandant's staff and provincial NKVD posts. As head of the Orenburg NKVD from February 1937 he made his name driving the mass operations with exceptional zeal, which brought him to Yezhov's attention. In January 1938 he replaced Leplevsky as Ukrainian NKVD chief and presided over the final, most intense phase of the terror in Ukraine, reporting tens of thousands of arrests against quotas that Yezhov and Stalin kept raising. As Yezhov fell in autumn 1938, Uspensky understood what was coming. On 14 November 1938 he staged his own suicide, leaving a note and his coat at the Dnieper, and vanished. He lived under false papers across the Urals for five months until the NKVD tracked him to Miass and arrested him on 15 April 1939. Tried by the Military Collegium, he was shot in January 1940 and never rehabilitated. His flight became a central element in the case against Yezhov.$q$,
 'executed', '처형', 'Executed', 'russia', '러시아', 'Russia'),

('belsky', 11, 'Л', 'Лев Бельский', '1889–1941', 1889, 1941,
 '레프 벨스키', 'Lev Belsky',
 '소비에트 민병대를 관장한 부인민위원', 'The deputy commissar who ran the Soviet police',
 $q$미르의 유대인 가정에서 아브람 레빈으로 태어나 십대에 분트를 거쳤고, 제정군 복무 뒤 1918년 체카에 들어가 스물아홉에 심비르스크 도 체카를 이끌었다. 1920년대에는 러시아 남부와 중앙아시아, 모스크바주에서 OGPU 전권대표직을 맡으며 수사관보다는 신뢰할 만한 행정가로 평판을 쌓았다. 1934년 소비에트 민병대, 곧 정규 경찰 기구 전체를 인수했고 1936년 11월 예조프는 그를 내무인민위원부 부인민위원으로 올렸다. 그 자리에서 그는 대량 사형 판결을 내리던 지방 트로이카들을 조직한 기구의 상층에 앉았고, 트로이카조차 우회하는 '특별 절차'로 NKVD 요원들을 체포하고 처리하는 일에 관여했다. 예조프가 약해지던 1938년 4월 철도인민위원부로 밀려났고, 예조프 자신보다 몇 달 뒤인 1939년 6월 체포됐다. 재판은 1941년 7월에야 열렸고 모스크바가 소개되던 그해 10월 16일 총살됐다. 복권되지 않았다.$q$,
 $q$Born Abram Levin to a Jewish family in Mir, Belsky passed through the Bund as a teenager, served in the imperial army, and joined the Cheka in 1918, running the Simbirsk provincial Cheka at twenty-nine. Through the 1920s he held OGPU plenipotentiary posts in southern Russia, Central Asia and the Moscow region, building a reputation as a reliable administrator rather than an investigator. In 1934 he took over the Soviet militia, the entire regular police apparatus, and in November 1936 Yezhov made him a deputy People's Commissar of Internal Affairs. In that role he sat at the top of the machinery that organized the regional troikas issuing mass death sentences, and he took part in arresting and disposing of NKVD officers under the "special procedure" that bypassed even the troikas. He was eased out to the railways commissariat in April 1938 as Yezhov weakened, and arrested in June 1939, a few months after Yezhov himself. His trial came only in July 1941; he was shot on 16 October 1941 as Moscow was being evacuated. He has never been rehabilitated.$q$,
 'executed', '처형', 'Executed', 'belarus', '벨라루스', 'Belarus'),

('zhukovsky', 12, 'С', 'Семён Жуковский', '1896–1940', 1896, 1940,
 '세묜 주콥스키', 'Semyon Zhukovsky',
 '무역 관리에서 부인민위원이 된 이례', 'The trade official who became a deputy commissar',
 $q$예조프의 부인민위원들 가운데 이례적인 인물로, 직업 체키스트가 아니라 대외무역 관리 출신이었다. 키예프의 유대인 가정에서 태어나 1920년대 후반과 1930년대 초를 소비에트 무역대표로 독일에서 보냈고 이후 대외무역인민위원부 수입국을 이끌었다. 당 사업으로 그를 알던 예조프가 1936년 10월 NKVD로 끌어들여 인민위원부의 건물과 보급, 물적 기반을 운영하는 행정경제국(AHU) 책임자로 앉혔다. 1937년 방첩과 작전기술 부서를 거쳐 1938년 1월 행정을 담당하는 부인민위원이 되었다. 스탈린이 제거한 예조프의 사람들 가운데 가장 이른 축에 들었다. 1938년 10월 3일 카자흐스탄 리데르 복합광산 소장으로 임명되었는데 명백한 좌천이었고, 부임하기도 전인 10월 22일 체포됐다. 트로츠키주의 혐의로 당에서 제명되어 열다섯 달을 갇혀 있다가 1940년 1월 군사콜레기움 판결로 총살됐다.$q$,
 $q$Zhukovsky was unusual among Yezhov's deputies: a foreign-trade official rather than a career Chekist. Born in Kyiv to a Jewish family, he spent the late 1920s and early 1930s in Germany as a Soviet trade representative and then ran the import department of the Foreign Trade Commissariat. Yezhov, who knew him from party work, pulled him into the NKVD in October 1936 and put him in charge of the Administrative-Economic Directorate, the body that ran the commissariat's buildings, supply and physical infrastructure. He moved through counter-intelligence and operational-technology posts in 1937 and in January 1938 became a deputy People's Commissar handling administrative affairs. He was among the very first of Yezhov's people Stalin removed: on 3 October 1938 he was appointed director of the Ridder polymetallic combine in Kazakhstan, a transparent demotion, and was arrested on 22 October before he could take up the post. Expelled from the party for alleged Trotskyism, he was held for fifteen months and shot in January 1940 on the Military Collegium's sentence.$q$,
 'executed', '처형', 'Executed', 'ukraine', '우크라이나', 'Ukraine'),

('blokhin', 13, 'В', 'Василий Блохин', '1895–1955', 1895, 1955,
 '바실리 블로힌', 'Vasily Blokhin',
 '세 명의 수장을 거쳐 이십칠 년을 집행한 사형집행인', 'The executioner who served twenty-seven years under three chiefs',
 $q$블라디미르 도의 농민 아들로 1921년 체카에 들어가 1926년부터 OGPU 행정국 사령부(코만다투라)를 이끌었다. 루뱐카 내부감옥의 사형 판결을 집행하던 작은 부서였다. 야고다와 예조프, 베리야를 거치며 이십칠 년간 그 자리를 지켰고, 모스크바 여론재판에서 처형된 고위 인사들과 1938년부터 1939년 사이 무너진 NKVD 지도부 상당수를 포함해 막대한 수의 처형을 직접 집행하거나 감독했다. 문서로 가장 잘 남은 단일 작전은 카틴이다. 1940년 3월 5일 정치국 결정에 따라 그해 4월과 5월 오스타시코프 수용소의 폴란드인 포로들을 칼리닌(현 트베리) NKVD 청사의 방음 지하실에서 총살한 팀을 지휘했고, 시신은 메드노예에 묻혔다. 1940년 4월 27일 적기훈장을 받았다. 베리야가 몰락한 1953년 퇴역했고 탈스탈린화가 진행되던 1954년 11월 소장 계급을 박탈당했으며 1955년 2월 사망했다.$q$,
 $q$Blokhin was a peasant's son from Vladimir Governorate who joined the Cheka in 1921 and by 1926 headed the Kommandatura of the OGPU's administrative directorate, the small unit that carried out death sentences in the Lubyanka's internal prison. He held that post for twenty-seven years, through Yagoda, Yezhov and Beria, personally shooting or supervising the shooting of an enormous number of prisoners, including senior figures condemned in the Moscow show trials and much of the NKVD leadership that fell in 1938 and 1939. His most documented single operation was the Katyn massacre: in April and May 1940, following the Politburo decision of 5 March 1940, he led the team that shot the Polish prisoners of the Ostashkov camp in a soundproofed basement room at the Kalinin NKVD building, with the bodies buried at Mednoye. He was decorated with the Order of the Red Banner on 27 April 1940. He retired in 1953 after Beria's fall, was stripped of his general's rank in November 1954 during de-Stalinization, and died in February 1955.$q$,
 '', '1955년 사망, 사인은 기록이 엇갈린다', 'Died 1955, cause disputed in the record', 'russia', '러시아', 'Russia'),

('firin', 14, 'С', 'Семён Фирин', '1898–1937', 1898, 1937,
 '세묜 피린', 'Semyon Firin',
 '‘개조’ 선전을 만든 드미트라크 수용소장', 'The Dmitlag chief who staged the "reforging" propaganda',
 $q$빌뉴스의 가난한 유대인 가정에서 푸프코라는 성으로 태어나 비텝스크의 공장에서 일하다 제정군에서 탈영해 1918년 볼셰비키에 가담했다. 내전기 리투아니아에서 파르티잔 부대를 이끈 뒤 적군 정보기관으로 옮겨 1920년대 내내 발칸과 터키에서 활동했다. 수용소 행정가로서는 이례적인 이력이다. OGPU로 전속해 1932년 백해-발트 운하 수용소 부소장이 되었고 운하가 개통된 1933년 레닌훈장을 받았다. 이어 모스크바 외곽에서 죄수들이 모스크바-볼가 운하를 파던 거대한 수용소 복합체 드미트라크를 맡아 '개조' 선전의 전시장으로 만들었다. 1934년 막심 고리키, 레오폴트 아베르바흐와 함께 운하를 찬양한 악명 높은 문집 『벨로모르』를 공동 편집했다. 드미트라크에서 그는 생산성이 낮다고 판정된 죄수의 배급을 깎았다. 야고다의 사람이었던 그는 예조프가 그 집단을 겨누자 1937년 4월 NKVD 내부의 '작전-체키스트 음모'를 이끌었다는 혐의로 체포되어 8월 총살됐다.$q$,
 $q$Firin, born Pupko to a poor Jewish family in Vilnius, worked in a Vitebsk factory, deserted from the imperial army, and joined the Bolsheviks in 1918. He led partisan units in Lithuania during the Civil War and then moved into Red Army military intelligence, running operations in the Balkans and Turkey through the 1920s, an unusual background for a camp administrator. He transferred to the OGPU and in 1932 became deputy chief of the White Sea-Baltic Canal camp, receiving the Order of Lenin in 1933 when the canal opened. He then took over Dmitlag, the vast camp complex outside Moscow whose prisoners dug the Moscow-Volga Canal, and made it a showpiece of the "reforging" propaganda: he co-edited, with Maxim Gorky and Leopold Averbakh, the notorious 1934 volume "Belomor" celebrating the canal. At Dmitlag he cut rations for prisoners judged unproductive. He belonged to Yagoda's circle, and when Yezhov turned on it he was arrested in April 1937 on charges of leading an "operational-Chekist conspiracy" inside the NKVD, and shot that August.$q$,
 'executed', '처형', 'Executed', 'lithuania', '리투아니아', 'Lithuania'),

('lazar-kogan', 15, 'Л', 'Лазарь Коган', '1889–1939', 1889, 1939,
 '라자리 코간', 'Lazar Kogan',
 '굴라크의 초대 수장이자 벨로모르 건설 책임자', 'The Gulag''s first chief and builder of Belomor',
 $q$시베리아의 부유한 유대인 상인의 아들로 아나코-코뮤니스트로 출발했다. 1908년 키예프 군관구 법원에서 강도죄로 사형을 선고받았다가 징역으로 감형됐다. 1918년 볼셰비키에 가담해 체카와 국경경비대를 거쳐 올라섰고, 1930년 신설된 굴라크의 초대 수장이 되었다. 1931년부터는 백해-발트 운하 건설을 지휘했다. 강제노동으로 기반시설을 지을 수 있음을 보여 주려 한 체제의 전시 사업이었다. 약 십칠만 명의 죄수가 이 년이 못 되어 227킬로미터 수로를 뚫었고 사망자는 수만 명에 이르렀다. 이후 굴라크 부수장으로 모스크바-볼가 운하 일을 하다가 1936년 수상운수인민위원부 부인민위원으로 옮겼다. 피린과 마찬가지로 야고다 시대의 사람이었다. 1938년 1월 체포되어 예조프에게, 이어 베리야에게 거듭 참회의 편지를 썼으나 1939년 3월 코무나르카에서 총살됐다. 예조프의 부하들과 달리 1956년 복권됐다.$q$,
 $q$Kogan was the son of a wealthy Jewish merchant in Siberia who began as an anarcho-communist; in 1908 a Kyiv military district court sentenced him to death for armed robbery, commuted to penal servitude. He joined the Bolsheviks in 1918 and rose through the Cheka and the border troops. In 1930 he became the first head of the newly created Gulag, and from 1931 directed the construction of the White Sea-Baltic Canal, the regime's showcase demonstration that forced labour could build infrastructure. Roughly 170,000 prisoners cut the 227-kilometre waterway in under two years, with tens of thousands of deaths. He then served as deputy chief of the Gulag and worked on the Moscow-Volga Canal before moving in 1936 to the Water Transport Commissariat as deputy commissar. Like Firin, he was a man of the Yagoda era. He was arrested in January 1938, wrote repeated letters of repentance to Yezhov and then to Beria, and was shot at Kommunarka in March 1939. Unlike the Yezhov lieutenants, he was rehabilitated in 1956.$q$,
 'executed', '처형', 'Executed', 'russia', '러시아', 'Russia'),

('frenkel', 16, 'Н', 'Нафталий Френкель', '1883–1960', 1883, 1960,
 '나프탈리 프렌켈', 'Naftaly Frenkel',
 '죄수에서 총국장으로, 제 침대에서 죽은 굴라크 행정가', 'From prisoner to directorate chief, and dead in his own bed',
 $q$굴라크에서 가장 신화화된 행정가이자 가장 잘 기록된 생존자다. 출신은 실제로 불분명하다. 그 자신의 죄수 등록카드는 오스만 통치하 하이파를 적고 있으나, 콘스탄티노플의 유대인이라는 설과 오데사 출신설, 헝가리인설, 오스트리아인설이 엇갈린다. 상인으로 소비에트 체제에 들어와 1923년 불법 월경 혐의로 체포됐다. 밀수를 뜻할 수도, 그저 지나친 상업적 성공을 뜻할 수도 있던 죄목이었고, 솔로프키 십 년형을 받았다. 그곳에서 그는 거의 유례없는 일을 해냈다. 수용소 노동 조직에 관한 제안, 무엇보다 죄수의 배급을 생산량에 연동하자는 제안을 앞세워 약 일 년 만에 죄수에서 행정가가 되었다. 조기 석방되어 1931년 11월 백해-발트 운하 공사 책임자가 되었고, 이어 BAM 수용소를 운영했으며 1937년부터는 NKVD의 철도건설총국 전체를 이끌었다. 대테러와 전쟁을 거치며 그 자리를 지켰고 레닌훈장을 세 번 받았으며 1947년 중장 계급과 연금을 받고 퇴역해 1960년 병사했다. 동시대인 대부분이 얻지 못한 결말이었다.$q$,
 $q$Frenkel is the Gulag's most mythologized administrator and its most documented survivor. His origins are genuinely obscure: his own prisoner card gives Haifa under Ottoman rule, while accounts variously make him a Constantinople Jew, an Odessan, a Hungarian or an Austrian. He entered the Soviet system as a merchant, was arrested in 1923 for illegal border crossing, a charge covering smuggling or simply excessive commercial success, and sentenced to ten years at Solovki. There he did something almost unique: within about a year he moved from prisoner to administrator, on the strength of proposals for organizing camp labour, above all tying prisoners' food rations to their output. Released early, he was made chief of works on the White Sea-Baltic Canal in November 1931, then ran BAMLag, and from 1937 headed the NKVD's entire railway construction directorate. He held that post through the Terror and the war, collected three Orders of Lenin, retired in 1947 with a general's rank and pension, and died in his bed in 1960, an outcome almost none of his contemporaries achieved.$q$,
 'natural', '자연사', 'Natural causes', '', '', ''),

-- ------------------------------------------------------------------ Beria's men
-- NOTE: bogdan-kobulov and naum-eitingon are deliberately absent. Both already
-- exist in commulingo_people with curated entries; re-inserting them here would
-- overwrite that prose. Amayak Kobulov (Bogdan's younger brother) is a distinct
-- person and is added below.
('goglidze', 18, 'С', 'Сергей Гоглидзе', '1901–1953', 1901, 1953,
 '세르고 고글리제', 'Sergo Goglidze',
 '조지아 대테러의 실무 총괄에서 극동의 총독으로', 'From running the terror in Georgia to overlord of the Far East',
 $q$1920년대 캅카스에서 베리야를 만난 조지아 출신 국경경비대 정치장교로, 1934년 조지아 내무인민위원이 되고 공화국 NKVD 트로이카를 주재하며 조지아 대테러의 실무 총괄이 되었다. 베리야의 후원으로 1938년 말 레닌그라드로 옮겨 예조프의 사람들을 정리했고, 1941년에는 몰다비아로 파견되어 독일 침공 직전 새로 병합된 베사라비아에서 대규모 추방을 감독했다. 전쟁과 그 이후 여러 해를 소비에트 극동의 보안 총수로 보냈다. 1951년 8월 아바쿠모프가 실각한 뒤 이그나티예프가 그를 중앙으로 불러 MGB 제1부장관에 앉혔고, 군 방첩을 관장했으며 1952년 말부터는 '의사들의 음모' 수사를 감독했다. 1953년 3월 베리야가 내무부로 돌아오면서 고위직을 유지했다. 7월 3일 동독에서 구금되어 12월 18일부터 23일까지 베리야와 함께 재판을 받고 당일 저녁 총살됐다. 복권되지 않았다.$q$,
 $q$A Georgian border-troops political officer who met Beria in the Caucasus in the 1920s, Goglidze became People's Commissar of Internal Affairs of Georgia in 1934 and chaired the republic's NKVD troika, making him the operational manager of the Great Terror in Georgia. Beria's patronage carried him to Leningrad in late 1938 to clean out Yezhov's men, then to Moldavia in 1941, where he supervised the mass deportations from newly annexed Bessarabia on the eve of the German invasion. He spent the war and the following years as the security overlord of the Soviet Far East. In August 1951, after Abakumov's fall, Ignatiev brought him back to the centre as first deputy MGB minister; he ran military counter-intelligence and, from late 1952, supervised the Doctors' Plot investigation. Beria's return to the MVD in March 1953 kept him in senior service. He was detained in East Germany on 3 July 1953, tried with Beria from 18 to 23 December 1953, and shot the same evening. He has never been rehabilitated.$q$,
 'executed', '처형', 'Executed', 'georgia', '조지아', 'Georgia'),

('dekanozov', 19, 'В', 'Владимир Деканозов', '1898–1953', 1898, 1953,
 '블라디미르 데카노조프', 'Vladimir Dekanozov',
 '리투아니아 병합을 연출하고 베를린에서 선전포고를 받은 자', 'He staged Lithuania''s annexation and took the declaration of war in Berlin',
 $q$바쿠의 조지아인 가정에서 데카노지시빌리라는 성으로 태어나 1921년 체카에 들어가 십 년을 자캅카스 보안기구에서 보내며 베리야의 가장 오랜 부하 가운데 하나가 되었다. 조지아의 식품공업과 고스플란을 거쳐 1938년 12월 모스크바로 불려와, 베리야가 막 참수해 놓은 NKVD 대외정보를 맡아 레지덴투라를 숙청하고 재건했다. 1939년 5월 외무인민위원부로 옮겨 몰로토프의 부인민위원이 되었으나 여전히 베리야의 사람이었다. 1940년 여름 전권대표로 카우나스에 파견되어 리투아니아 병합을 연출했고, 인민정부를 세우고 병합 요청을 만들어 낸 선거를 연출했다. 1940년 11월부터 베를린 주재 대사로 있다가 1941년 6월 22일 아침 리벤트로프에게서 선전포고를 받았다. 전쟁기를 외교직으로 넘겼고 1953년 3월 베리야가 그를 조지아 내무장관에 앉혔다. 베리야가 체포된 며칠 뒤 함께 체포되어 12월 23일 총살됐다.$q$,
 $q$Born in Baku to a Georgian family (original surname Dekanozishvili), Dekanozov joined the Cheka in 1921 and spent a decade in Transcaucasian security work, becoming one of Beria's oldest clients. After a spell running Georgia's food industry and Gosplan, he was brought to Moscow in December 1938 to head NKVD foreign intelligence, which Beria had just decapitated; he purged and rebuilt the residencies. In May 1939 he moved to the Foreign Commissariat as Molotov's deputy while remaining Beria's man, and in the summer of 1940 he was sent to Kaunas as plenipotentiary to engineer Lithuania's annexation, installing the People's Government and staging the elections that produced the annexation request. From November 1940 he was ambassador in Berlin and received Ribbentrop's declaration of war on the morning of 22 June 1941. He survived the war in diplomatic posts, and in March 1953 Beria made him MVD minister of Georgia. Arrested days after Beria, he was tried and shot on 23 December 1953.$q$,
 'executed', '처형', 'Executed', 'azerbaijan', '아제르바이잔', 'Azerbaijan'),

('meshik', 20, 'П', 'Павел Мешик', '1910–1953', 1910, 1953,
 '파벨 메시크', 'Pavel Meshik',
 '원폭 계획의 보안을 맡은 최연소 측근', 'The youngest of the circle, security chief of the atomic project',
 $q$베리야 측근 가운데 가장 젊었다. 1932년 우크라이나의 공장에서 NKVD로 보내져 경제와 방첩 부문을 거쳐 올라섰다. 베리야 아래에서 1939년 NKVD 수사부장이 되었고 1941년 2월 서른의 나이로 우크라이나 국가보안인민위원이 되었다. 전쟁기에는 NKVD 경제국을 운영했고 이후 스메르시 부국장을 지냈다. 1945년부터 그의 중심 임무는 베리야가 총괄하던 원폭 계획, 곧 제1총국의 보안과 방첩이었고 이로써 체제가 가장 신뢰하는 실무자 가운데 하나가 되었다. 1953년 3월 베리야는 그를 우크라이나 내무장관에 앉혔고, 그곳에서 그는 후원자의 민족정책 노선을 집행해 서부 주들에서 우크라이나어 사무와 현지 간부 승진을 요구하며 공화국 당 지도부와 충돌했다. 6월 30일 키예프에서 체포되어 베리야와 함께 비공개 재판을 받고 12월 23일 총살됐다. 2000년 반역 혐의는 취소됐으나 복권되지는 않았다.$q$,
 $q$The youngest of Beria's inner circle, Meshik was sent from a Ukrainian factory into the NKVD in 1932 and rose through its economic and counter-intelligence branches. Under Beria he headed the NKVD Investigative Unit in 1939 and was made People's Commissar of State Security of Ukraine in February 1941 at the age of thirty. He ran the NKVD's Economic Directorate during the war, then served as a deputy head of SMERSH. From 1945 his central assignment was security and counter-intelligence for the First Main Directorate, the atomic bomb programme Beria supervised, which made him one of the regime's most trusted operators. In March 1953 Beria installed him as MVD minister of Ukraine, where he executed his patron's nationalities line, demanding office work in Ukrainian and the promotion of local cadres in the western oblasts, which antagonized the republic's party leadership. He was arrested in Kyiv on 30 June 1953, tried in camera with Beria, and shot on 23 December 1953. The treason charge was voided in 2000, but he was not rehabilitated.$q$,
 'executed', '처형', 'Executed', 'ukraine', '우크라이나', 'Ukraine'),

('vlodzimirsky', 21, 'Л', 'Лев Влодзимирский', '1905–1953', 1905, 1953,
 '레프 블로지미르스키', 'Lev Vlodzimirsky',
 '특별중요사건 수사부장', 'Head of the unit for especially important cases',
 $q$바르나울의 폴란드계 가정에서 태어나 1920년대 말 OGPU에 들어가 1937년 중앙기구로 전속됐다. 베리야의 주요 심문 책임자가 되어 1939년부터 NKVD 수사부장을, 1943년 5월부터는 체제의 가장 민감한 수감자들을 다루던 NKGB 특별중요사건 수사부장을 맡았다. 1941년 적군 공군 지휘부를 겨눈 사건, 곧 리차고프와 스무시케비치, 시테른, 로크티오노프를 상대로 한 수사를 지휘했는데, 이들은 1941년 10월 베리야의 문서 명령으로 재판 없이 총살됐다. 연출가 프세볼로트 메이예르홀트의 심문에도 관여했다. 1946년 수사기구에서 밀려나 코불로프의 대외재산총국에서 육 년을 서류직으로 보냈다. 1953년 3월 베리야가 그를 MVD 특별수사부장으로 복귀시켰고, 그곳에서 '의사들의 음모'를 뒤집고 류민 사건을 처리했다. 7월 17일 체포되어 베리야와 함께 재판을 받고 12월 23일 총살됐다.$q$,
 $q$Born in Barnaul to a family of Polish descent, Vlodzimirsky joined the OGPU in the late 1920s and was transferred to the central apparatus in 1937. He became Beria's principal interrogator: head of the NKVD Investigative Unit from 1939 and, from May 1943, head of the Investigative Unit for Especially Important Cases of the NKGB, the body that handled the regime's most sensitive prisoners. He directed the 1941 case against the Red Army air force command, Rychagov, Smushkevich, Shtern and Loktionov, whose defendants were shot without trial in October 1941 on a written order from Beria, and he was involved in the interrogation of the director Vsevolod Meyerhold. Removed from the investigative apparatus in 1946, he spent six years in clerical posts at Kobulov's foreign-property directorate. In March 1953 Beria restored him to head the MVD's special investigations, where he handled the reversal of the Doctors' Plot and the case against Ryumin. He was arrested on 17 July 1953, tried with Beria, and shot on 23 December.$q$,
 'executed', '처형', 'Executed', 'russia', '러시아', 'Russia'),

('amayak-kobulov', 22, 'А', 'Амаяк Кобулов', '1906–1955', 1906, 1955,
 '아마야크 코불로프', 'Amayak Kobulov',
 '나치의 역정보를 모스크바로 흘려보낸 베를린 레지덴트', 'The Berlin rezident who piped Nazi disinformation to Moscow',
 $q$보그단 코불로프의 동생으로 경력 전체를 가족과 베리야에게 빚졌다. 대테러기에 가그라 NKVD와 압하지야 NKVD를 운영했고, 1938년 12월 서른둘의 나이에 아무런 관련 자격 없이 우크라이나 NKVD 대행 수장이 되었다. 1939년 베를린에 대사관 참사관 겸 '자하르'라는 암호명의 합법 NKVD 레지덴트로 파견됐다. 독일어를 못하고 작전 훈련도 받지 않은 그의 임명을 역사가들은 정보기관에서 드러난 베리야의 족벌주의의 가장 분명한 사례로 본다. 그의 주력 첩자 '리체이스트', 곧 라트비아 언론인 오레스츠 베를링스는 실제로는 독일이 심은 인물이었고 그 자료는 리벤트로프 정보국의 루돌프 리쿠스가 작성했다. 그리하여 코불로프는 1940년부터 1941년까지 나치의 역정보를 모스크바로 흘려보냈다. 전쟁기는 우즈베키스탄 보안 총수로, 전후는 포로 관리 제국을 운영하고 굴라크 부수장을 지냈다. 1953년 6월 27일 동독에서 체포되어 베리야와 별도로 재판을 받고 1954년 10월 선고, 1955년 2월 총살됐다.$q$,
 $q$The younger brother of Bogdan Kobulov, Amayak owed his entire career to family and to Beria. He ran the Gagra NKVD and Abkhaz NKVD during the Terror, and in December 1938 was made acting NKVD chief of Ukraine at thirty-two despite no relevant qualification. In 1939 he was sent to Berlin as embassy counsellor and legal NKVD rezident under the codename "Zakhar", an appointment historians treat as the clearest case of Beria's nepotism in the intelligence service, since he spoke no German and had no operational training. His prize agent "Lycéist", the Latvian journalist Orests Berlings, was in fact a German plant whose material was written by Rudolf Likus of Ribbentrop's information bureau, so Kobulov piped Nazi disinformation into Moscow through 1940 and 1941. He spent the war as security chief of Uzbekistan and the post-war years running the prisoner-of-war empire and deputizing at the Gulag. Arrested in East Germany on 27 June 1953, he was tried separately from Beria, condemned in October 1954 and shot in February 1955.$q$,
 'executed', '처형', 'Executed', 'georgia', '조지아', 'Georgia'),

('tsanava', 23, 'Л', 'Лаврентий Цанава', '1900–1955', 1900, 1955,
 '라브렌티 차나바', 'Lavrentiy Tsanava',
 '‘두 번째 라브렌티’, 미호엘스 살해의 감독자', 'The "second Lavrentiy", who supervised the Mikhoels killing',
 $q$밍그렐리아에서 라브렌티 잔즈가바로 태어나 1938년 차나바로 성을 바꾸었고, 그해 12월 베리야에 의해 벨로루시 NKVD 수장으로 앉혀져 병합된 옛 폴란드 동부 영토의 소비에트화와 뒤이은 추방을 지휘했다. '두 번째 라브렌티'라 불렸고 1951년까지 거의 끊이지 않고 벨로루시 국가보안을 운영했으며, 서부전선 특별부를 관장하고 파르티잔운동 중앙참모부 부장을 지냈다. 가장 악명 높은 행위는 배우이자 유대인반파시스트위원회 의장이던 솔로몬 미호엘스와 평론가 블라디미르 골루보프를 1948년 1월 12일에서 13일로 넘어가는 밤 민스크에서 살해한 일이다. 스탈린의 명령에 따라 차나바의 다차에서 MGB 요원들이 저지른 뒤 교통사고로 위장했다. 1951년 소련 MGB 부장관으로 승진했으나 1952년 해임되고 당에서 제명됐다. 1953년 4월 4일 미호엘스 사건을 다시 열던 베리야 자신의 MVD에 체포되어 재판 한 번 받지 못한 채 1955년 10월 12일 부티르카 감옥에서 사망했다.$q$,
 $q$Born Lavrentiy Dzhandzhgava in Mingrelia, he took the surname Tsanava in 1938 and was installed by Beria as NKVD chief of Belorussia in December 1938, where he directed the sovietization of the annexed eastern Polish territories and the deportations that followed. Nicknamed "the second Lavrentiy", he ran Belorussian state security almost continuously until 1951, oversaw Special Departments on the Western Front, and deputized at the Central Staff of the Partisan Movement. His most notorious act was the murder of the actor and Jewish Anti-Fascist Committee chairman Solomon Mikhoels, together with the critic Vladimir Golubov, in Minsk on the night of 12 to 13 January 1948: the killing was carried out by MGB officers at Tsanava's dacha on Stalin's order and staged as a road accident. Promoted to deputy MGB minister of the USSR in 1951, he was dismissed and expelled from the party in 1952. He was arrested on 4 April 1953 by Beria's own MVD as it reopened the Mikhoels case, and died in Butyrka prison on 12 October 1955 without ever coming to trial.$q$,
 'natural', '재판 없이 옥중 사망', 'Died in custody, never tried', 'georgia', '조지아', 'Georgia'),

('milshtein', 24, 'С', 'Соломон Мильштейн', '1899–1955', 1899, 1955,
 '솔로몬 밀시테인', 'Solomon Milshtein',
 '강제이주의 열차를 조직한 수송총국장', 'The transport chief who assembled the deportation trains',
 $q$빌나 출신 유대인으로 1920년대와 1930년대를 베리야 아래 조지아 당 사업에서 보냈다. 1938년 11월 후원자가 NKVD를 인수하자 모스크바로 불려와 처음에는 수사부 부부장, 1939년 3월부터는 NKVD 수송총국장이 되었다. 이 자리는 그를 스탈린 테러의 철도 기구 운영자로 만들었다. 그의 총국은 병합 지역 폴란드인들의 추방, 이어 1943년과 1944년 카라차이인과 칼미크인, 체첸인, 잉구시인의 추방을 위한 열차를 편성하고 움직였다. 그 공로로 1944년 3월 수보로프 훈장 2급을 받았다. 민간인을 강제이주시킨 대가로 주어진 전공 훈장이었고, 소비에트 국가 자신이 1962년 이를 취소했다. 1947년까지 NKGB 수송총국을 이끌다 철도 관리직으로 밀려났고 1951년 굴라크 지도부로 복귀했다. 1953년 3월 베리야는 그를 메시크의 제1부장관으로 키예프에 보냈다. 7월 3일 체포되어 베리야와 별도로 재판을 받고 1954년 10월 선고, 1955년 1월 총살됐다.$q$,
 $q$A Jew from Vilna who spent the 1920s and 1930s in Georgian party work under Beria, Milshtein was summoned to Moscow in November 1938 when his patron took over the NKVD, first as deputy head of the Investigative Unit and then, from March 1939, as head of the NKVD's Main Transport Directorate. That post made him the administrator of the railway apparatus of Stalinist terror: his directorate assembled and moved the trains for the deportations of the Poles from the annexed territories, and then of the Karachais, Kalmyks, Chechens and Ingush in 1943 and 1944. For that work he was awarded the Order of Suvorov 2nd class in March 1944, a combat decoration given for deporting civilians, which the Soviet state itself annulled in 1962. He ran the transport directorate of the NKGB through 1947, was sidelined to a railway management job, and returned to the Gulag leadership in 1951. In March 1953 Beria sent him to Kyiv as Meshik's first deputy. Arrested on 3 July 1953, he was tried separately from Beria, condemned in October 1954 and shot in January 1955.$q$,
 'executed', '처형', 'Executed', 'lithuania', '리투아니아', 'Lithuania'),

('mamulov', 25, 'С', 'Степан Мамулов', '1902–1976', 1902, 1976,
 '스테판 마물로프', 'Stepan Mamulov',
 'NKVD 서기국을 쥔 문서의 관문', 'The gatekeeper who held the NKVD secretariat',
 $q$티플리스의 아르메니아인(본래 성 마물랸)으로 체키스트가 아니라 당 관료였다. 1920년대와 1930년대를 압하지야와 조지아, 카자흐스탄에서 보내며 티플리스 시당 서기까지 올랐다. 1939년 8월 베리야가 그를 모스크바로 불러 NKVD 서기국장에 앉혔고, 이로써 그는 인민위원부 전체 문서 흐름의 관문이 되었다. 모든 명령과 보고, 스탈린에게 올라가는 상신이 그의 사무실을 거쳤다. 1946년 4월 내무부 부장관이 되어 수용소 관리와 보급을 관장했다. 그의 권력은 절차적이고 파생적이었으며, 그래서 베리야와 따로, 더 낮은 범주로 재판을 받았다. 1953년 12월의 집단이 아니라 1954년 9월 28일, 베리야의 각료회의 서기국을 운영하던 보리스 루드비고프와 함께였다. 십오 년형을 받아 블라디미르 중앙감옥에서 형기를 다 채우고 1968년 6월 28일 석방됐다. 자신을 파괴한 체제보다 오래 산 베리야 측근 가운데 하나였고 1976년 사망했다.$q$,
 $q$An Armenian from Tiflis (family name Mamulyan), Mamulov was a party functionary rather than a Chekist, working in Abkhazia, Georgia and Kazakhstan through the 1920s and 1930s and rising to secretary of the Tbilisi city committee. Beria brought him to Moscow in August 1939 to head the Secretariat of the NKVD, which made him the gatekeeper of the commissariat's entire paper flow: every order, report and submission to Stalin passed through his office. In April 1946 he became a deputy minister of internal affairs, overseeing camp administrations and supply. His power was procedural and derivative, which is why he was tried separately from Beria and in a lesser category: not with the December 1953 group, but on 28 September 1954, alongside Boris Ludvigov, who had run Beria's secretariat at the Council of Ministers. Sentenced to fifteen years, he served the entire term at Vladimir Central and was released on 28 June 1968, one of the few members of Beria's circle to outlive the regime that destroyed it. He died in 1976.$q$,
 'natural', '십오 년형 복역 뒤 자연사', 'Served fifteen years, died of natural causes', 'georgia', '조지아', 'Georgia'),

-- ------------------------------------------------- Georgian apparatus / Tbilisi 1955
('rapava', 27, 'А', 'Авксентий Рапава', '1899–1955', 1899, 1955,
 '압크센티 라파바', 'Avksenty Rapava',
 '십 년간 조지아 경찰기구를 운영한 자', 'He ran the Georgian police apparatus for a decade',
 $q$밍그렐리아 코르츠헬리의 농민 가정에서 태어나 1920년대 중반 체카-OGPU에 들어가 1930년부터 아자리야 GPU를 이끌고 조지아 GPU 부의장을 지냈다. 1937년 명령 제00447호로 재판 외 사형 판결 권한을 부여받은 NKVD '특별 트로이카'에 앉았고, 잠시 소비에트 압하지야 정부를 이끌었다. 1938년부터 조지아 NKVD를 이끌었고 1948년까지 공화국 국가보안장관을 지냈으며 1945년 7월 중장으로 승진했다. 1948년 법무부로 옮겨졌다가 1951년 11월 조작된 '밍그렐리아 사건'으로 체포됐고, 스탈린 사후 석방·복권되었으나 베리야가 몰락하자 1953년 7월 재체포됐다. 1955년 9월 트빌리시에서 다른 일곱 명의 조지아 보안 관리들과 함께 공개 재판을 받고 반혁명 범죄로 유죄 판결을 받아 11월 15일 총살됐다.$q$,
 $q$Born to a peasant family in Kortskheli in Mingrelia, Rapava entered the Cheka and OGPU in the mid-1920s, heading the Adjarian GPU from 1930 and serving as deputy chairman of the Georgian GPU. In 1937 he sat on the NKVD "special troika" empowered by Order No. 00447 to pass extrajudicial death sentences, and briefly led Soviet Abkhazia's government. From 1938 he headed the NKVD of the Georgian SSR, continuing as republican state security minister until 1948, and was promoted lieutenant general in July 1945. Moved to the justice ministry in 1948, he was arrested in November 1951 in the fabricated "Mingrelian affair", released and rehabilitated after Stalin's death, then re-arrested in July 1953 once Beria fell. Tried publicly in Tbilisi in September 1955 alongside seven other Georgian security officials, he was convicted of counter-revolutionary crimes and shot on 15 November 1955.$q$,
 'executed', '처형', 'Executed', 'georgia', '조지아', 'Georgia'),

('rukhadze', 28, 'Н', 'Николай Рухадзе', '1905–1955', 1905, 1955,
 '니콜라이 루하제', 'Nikolai Rukhadze',
 '밍그렐리아 사건을 몰아붙이다 스스로 무너진 자', 'He drove the Mingrelian affair and then fell himself',
 $q$1920년대에 조지아 보안기구에 들어가 1937년 압하지야 가그라의 NKVD 지구부를 이끌었다. 남아 있는 그의 기소장은 이 시기 '간이 수사' 방식으로 이루어진 삼백 건 이상의 체포와 심문 중 사망을 그에게 돌린다. 1939년부터 조지아 NKVD 수사과를 운영했고, 전쟁기에는 내무부인민위원 겸 자캅카스전선 특별부장을, 이후 자캅카스 스메르시 방첩 책임자를 지냈다. 1948년 공화국 국가보안장관에 임명되어 베리야의 부하들을 겨눈 조작 사건 '밍그렐리아 사건'을 몰아붙인 핵심 인물이 되었다. 그럼에도 그 자신이 무너졌다. 스탈린이 죽기 몇 달 전인 1952년 11월 체포되었고, 결국 1955년 9월 밍그렐리아 사건이 아니라 베리야 집단의 일원이라는 혐의로 재판을 받아 11월 15일 트빌리시에서 총살됐다.$q$,
 $q$Rukhadze joined the Georgian security organs in the 1920s and by 1937 headed the NKVD district office in Gagra, Abkhazia, where his surviving indictment attributes to him over 300 arrests conducted by "simplified investigation" methods, including deaths under interrogation. From 1939 he ran the investigation section of the Georgian NKVD, then served as deputy internal affairs commissar and head of the Special Department of the Transcaucasian Front during the war, later leading SMERSH counter-intelligence in the Transcaucasus. Appointed republican state security minister in 1948, he became a driving figure in the fabricated "Mingrelian affair" against Beria's clients. He nonetheless fell himself: arrested in November 1952, months before Stalin's death, he was ultimately tried in September 1955 not for the Mingrelian case but as an alleged member of Beria's group, and was shot in Tbilisi on 15 November 1955.$q$,
 'executed', '처형', 'Executed', 'georgia', '조지아', 'Georgia'),

('shalva-tsereteli', 29, 'Ш', 'Шалва Церетели', '1894–1955', 1894, 1955,
 '샬바 체레텔리', 'Shalva Tsereteli',
 '제정군 장교 출신의 공작 요원', 'The tsarist officer who became a covert operative',
 $q$체레텔리 공작 가문의 후손으로 1914년부터 1915년까지 제정 러시아군 소위로 복무하고 몇 달을 포로로 보낸 뒤, 1921년 소비에트 권력이 수립되자 조지아 체카에 들어갔다. 귀족이자 제정군 장교 출신이라는 배경은 베리야의 사람들 가운데 이례적이었다. 1937년과 1938년 조지아 민병대를 이끌고 NKVD '특별 트로이카'에 앉았으며, 1939년부터 자캅카스 국경경비대를 지휘했다. 1941년 8월 조지아 제1부내무인민위원, 1946년 부국가보안장관이 되었고 1945년 7월 중장에 올랐다. 역사가들은 그를 은밀한 납치와 살해에 동원된 요원 가운데 하나로 본다. 문서 자료는 1939년 7월 주중 소련 대사 이반 봅쿤-루가네츠와 그 아내를 교통사고로 위장해 살해한 사건에 그를 위치시킨다. 베리야가 몰락한 뒤 1953년 8월 체포되어 트빌리시에서 재판을 받고 1955년 11월 15일 총살됐다.$q$,
 $q$A descendant of the Georgian princely house of Tsereteli, Tsereteli served as an ensign in the Imperial Russian Army in 1914 and 1915 and spent months as a prisoner of war before joining the Georgian Cheka after Soviet power was established in 1921. He was an unusual figure among Beria's men for his noble and tsarist-officer background. He headed the Georgian militia and sat on the NKVD "special troika" during the 1937 and 1938 terror, then commanded the Transcaucasian border troops from 1939. He became first deputy internal affairs commissar of the Georgian SSR in August 1941 and deputy state security minister in 1946, reaching lieutenant general in July 1945. Historians identify him as one of the operatives used for covert abductions and killings; archival materials place him in the July 1939 murder of the Soviet ambassador to China, Ivan Bovkun-Luganets, and his wife, staged as a car accident. Arrested in August 1953 after Beria's fall, he was tried in Tbilisi and shot on 15 November 1955.$q$,
 'executed', '처형', 'Executed', 'georgia', '조지아', 'Georgia'),

('nadaraya', 30, 'С', 'Сардион Надарая', '1903–1982', 1903, 1982,
 '사르디온 나다라야', 'Sardion Nadaraya',
 '베리야의 경호를 맡은 내부감옥 책임자', 'Beria''s bodyguard chief, formerly of the internal prison',
 $q$조지아 서부 세피에티 마을에서 태어나 1926년 보안기관에 들어갔고, 대테러가 절정이던 1937년에는 조지아 NKVD 내부감옥을 운영했다. 1939년부터 베리야의 개인 경호 부책임자로 후원자를 따라 모스크바로 옮겼고, MGB 경호총국에서 일한 뒤 1953년에는 베리야의 경호 책임자가 되었다. 베리야가 몰락한 뒤 체포되어 1955년 9월 트빌리시 공개 재판의 여덟 번째 피고가 되었다. 기소장은 형법 58조를 적용해 내부감옥에서의 수감자 구타 관여와, 고문으로 인한 사망을 은폐한 허위 사망진단서 작성을 그에게 물었다. 여섯 명의 고위 피고와 달리 처형을 면했다. 십 년형을 받아 1965년 모르도바의 수용소에서 석방됐고 1982년 모스크바에서 사망했다.$q$,
 $q$Born in the village of Sepieti in western Georgia, Nadaraya entered the security organs in 1926 and by 1937 was running the NKVD internal prison of the Georgian SSR during the height of the terror. From 1939 he served as deputy chief of Beria's personal security, following his patron to Moscow, and worked in the guards directorate of the MGB before becoming chief of Beria's detail by 1953. Arrested after Beria's fall, he was the eighth defendant at the public Tbilisi trial of September 1955. The indictment charged him under Article 58 with involvement in the beating of prisoners in the internal prison and with arranging falsified death certificates concealing deaths caused by torture. Unlike the six senior defendants, he escaped execution: he received ten years, was released from a Mordovian camp in 1965, and died in Moscow in 1982.$q$,
 'natural', '십 년형 복역 뒤 자연사', 'Served ten years, died of natural causes', 'georgia', '조지아', 'Georgia'),

('karanadze', 31, 'Г', 'Григорий Каранадзе', '1902–1970', 1902, 1970,
 '그리고리 카라나제', 'Grigory Karanadze',
 '숙청을 넘기고 살아남은 조지아 내무장관', 'The Georgian interior minister who survived the purge',
 $q$밍그렐리아의 식당지기 아들로 종교학교에서 삼 년을 배운 것이 전부였으나 콤소몰과 당 사업을 거쳐 1935년 트빌리시 지구당 제1서기가 되었다. 베리야가 소련 NKVD를 인수한 뒤인 1938년 11월 크림 자치공화국 내무인민위원으로 임명됐고, 1942년 12월 다게스탄에서 같은 직책을 맡았으며, 1943년 5월 조지아 내무인민위원이 되어 1952년까지 그 자리를 지켰다. 1945년 7월 중장으로 승진했다. 1952년 4월 조작된 '밍그렐리아 사건'으로 체포됐으나 스탈린이 죽자 베리야가 사건을 중단시켜 완전히 복권되었고 1953년 4월 조지아 내무부 부장관이 되었다. 베리야의 다른 조지아 부하들과 달리 그는 끝내 재판을 받지 않았다. 1957년부터 공화국 산림위원회에서 일하다 1970년 사망했다.$q$,
 $q$The son of a canteen keeper from Mingrelia, with only three years of schooling at a religious school, Karanadze rose through Komsomol and party work, becoming a district party first secretary in Tbilisi in 1935. After Beria took over the NKVD USSR, he was appointed people's commissar of internal affairs of the Crimean ASSR in November 1938, moved to the same post in Dagestan in December 1942, and in May 1943 became internal affairs commissar of Georgia, a post he held until 1952. He was promoted lieutenant general in July 1945. In April 1952 he was arrested in the fabricated "Mingrelian affair"; Beria halted the case after Stalin's death and Karanadze was fully rehabilitated and made deputy internal affairs minister of Georgia in April 1953. Unlike Beria's other Georgian lieutenants he was never tried, and from 1957 served in the republic's forestry administration until his death in 1970.$q$,
 'natural', '자연사', 'Natural causes', 'georgia', '조지아', 'Georgia'),

('savitsky', 32, 'К', 'Константин Савицкий', '1905–1955', 1905, 1955,
 '콘스탄틴 사비츠키', 'Konstantin Savitsky',
 '코불로프의 개인 비서, 1955년의 사형수', 'Kobulov''s personal secretary, condemned in 1955',
 $q$타슈켄트에서 태어나 1931년 조지아 NKVD에 들어가 1937년과 1938년 공화국 제4부에서 요원과 과장, 부부장으로 일했다. 1939년 예비역으로 전역했다가 1941년 소련 NKVD 제4국으로 복귀했고, 1943년부터 베리야의 최측근 가운데 하나이던 보그단 코불로프의 개인 비서로 일했으며 이후 NKGB 서기국과 대외재산관리국에서 근무했다. 1953년 3월 베리야가 내무부로 돌아오자 제1부장관이 된 코불로프의 보좌관이 되었다. 베리야가 몰락한 며칠 뒤인 7월 1일 체포됐다. 1954년 기소장은 그를 크리먄, 하잔, 파라모노프와 함께 조지아에서 수감자를 고문하고 사건을 조작한 수사관들로 묶었다. 대령 계급에 그쳤음에도 사형 피고가 되어 1955년 11월 15일 총살됐다.$q$,
 $q$Born in Tashkent, Savitsky joined the NKVD of the Georgian SSR in 1931 and worked as an operative, section head and assistant head of the republic's 4th department during the terror of 1937 and 1938. Discharged to the reserves in 1939, he was recalled in 1941 to the 4th directorate of the NKVD USSR and from 1943 served as personal secretary to Bogdan Kobulov, one of Beria's closest associates, later working in the NKGB secretariat and in the administration of Soviet property abroad. When Beria returned to the interior ministry in March 1953, Savitsky became assistant to Kobulov as first deputy minister. He was arrested on 1 July 1953, days after Beria's downfall. The 1954 indictment grouped him with Krimyan, Khazan and Paramonov as investigators who had tortured detainees and fabricated cases in Georgia. He reached only the rank of colonel, and was shot on 15 November 1955.$q$,
 'executed', '처형', 'Executed', 'uzbekistan', '우즈베키스탄', 'Uzbekistan'),

('khazan', 33, 'А', 'Александр Хазан', '1906–1955', 1906, 1955,
 '알렉산드르 하잔', 'Alexander Khazan',
 '1938년 풀려나 1955년 총살된 수사관', 'Released in 1938, shot in 1955',
 $q$오데사의 유대인 가정에서 태어나 1928년 무렵 오데사 GPU 요원으로 보안기관에 들어갔다. 1933년 OGPU 고등학교에서 퇴교당한 뒤 조지아 NKVD로 배치되어 요원과 과장을 거쳐 1937년 공화국 비밀정치부(SPO) 제1과장이 되었다. 1938년 2월 도발적 수사 방식을 이유로 고글리제의 명령에 따라 체포되었으나 약 두 달 뒤 베리야의 지시로 풀려나 전역 처리에 그쳤다. 이후 전쟁기에 소련 NKVD 중앙기구에서 복무하다 1945년 보안기관을 떠났다. 베리야가 몰락한 뒤 체포되어 1955년 9월 트빌리시에서 사건을 조작하고 수감자를 고문한 혐의를 받은 조지아 NKVD 수사관 가운데 하나로 재판을 받고 11월 15일 총살됐다.$q$,
 $q$Born in Odessa to a Jewish family, Khazan entered the security organs around 1928 as an operative in the Odessa GPU. After being dismissed from the Higher School of the OGPU in 1933 he was posted to the NKVD of Georgia, where he worked as an operative and section head before becoming head of the 1st section of the republic's Secret-Political Department in 1937. He was arrested in February 1938 on Sergei Goglidze's orders for provocative investigative methods, but was released after roughly two months on Beria's instructions and merely discharged. He later served in the central apparatus of the NKVD USSR during the war and left the service in 1945. Arrested after Beria's fall, he was tried at Tbilisi in September 1955 as one of the Georgian NKVD investigators accused of fabricating cases and torturing detainees, and was shot on 15 November 1955.$q$,
 'executed', '처형', 'Executed', 'ukraine', '우크라이나', 'Ukraine'),

('krimyan', 34, 'Н', 'Никита Кримян', '1913–1955', 1913, 1955,
 '니키타 크리먄', 'Nikita Krimyan',
 '서른한 살에 아르메니아 국가보안장관이 된 수사관', 'The investigator who became Armenia''s security minister at thirty-one',
 $q$1913년 카르스에서 노동자 계급 아르메니아인 가정에 태어났다. 당시 카르스는 러시아 제국 영토였고 오늘날은 튀르키예에 속한다. 1932년 7월 트빌리시의 자캅카스 GPU 경제부 견습으로 보안기관에 들어가 대테러기 조지아 NKVD에서 빠르게 올라섰다. 1937년과 1938년 과장을 지냈고 이어 공화국 수사부 부부장과 부장이 되었다. 1940년 리보프로 파견됐고 1941년부터 1945년까지 야로슬라블주에서 복무하며 1943년부터 주 NKGB 관리국을 이끌었다. 1945년 4월 서른한 살에 아르메니아 국가보안인민위원, 이어 장관에 임명됐다. 1947년 해임되어 울리야놉스크주 MGB 관리국장으로 좌천됐고 1951년 보안기관에서 완전히 물러나 아르메니아 식품공업부 인사부장으로 일했다. 베리야가 몰락한 뒤인 1953년 9월 25일 사회주의 법질서의 반복적 위반 혐의로 체포됐다. 1955년 9월 트빌리시에서 베리야의 조지아 관련자 집단의 일원으로 공개 재판을 받아 사형을 선고받고 11월 15일 총살됐다.$q$,
 $q$Krimyan was born in 1913 in Kars, then Russian imperial territory and today part of Turkey, into a working-class Armenian family. He entered the security organs in July 1932 as a trainee in the Economic Department of the Transcaucasian GPU in Tbilisi and rose rapidly inside the Georgian NKVD during the Great Terror, serving as a section chief in 1937 and 1938 and then as deputy chief and chief of the republic's Investigative Department. In 1940 he was posted to Lvov, and from 1941 to 1945 served in Yaroslavl Oblast, heading its NKGB administration from 1943. In April 1945, aged thirty-one, he was appointed People's Commissar, later Minister, of State Security of the Armenian SSR. Removed in 1947 and demoted to head the MGB administration in Ulyanovsk Oblast, he was dismissed from the organs in 1951 and worked in Armenia's food industry ministry. Arrested on 25 September 1953 after Beria's fall, he was tried in open court at Tbilisi in September 1955 as one of the group of Beria's Georgian associates, sentenced to death, and shot on 15 November 1955.$q$,
 'executed', '처형', 'Executed', 'turkey', '튀르키예', 'Turkey')

) AS v(id, ord, initial, cyrillic, years_label, birth_year, death_year,
       name_ko, name_en, epithet_ko, epithet_en, bio_ko, bio_en,
       fate_kind, fate_label_ko, fate_label_en, origin_code, origin_label_ko, origin_label_en)
ON CONFLICT (id) DO UPDATE SET
    group_id = EXCLUDED.group_id, initial = EXCLUDED.initial, cyrillic = EXCLUDED.cyrillic,
    years_label = EXCLUDED.years_label, birth_year = EXCLUDED.birth_year, death_year = EXCLUDED.death_year,
    name_ko = EXCLUDED.name_ko, name_en = EXCLUDED.name_en,
    epithet_ko = EXCLUDED.epithet_ko, epithet_en = EXCLUDED.epithet_en,
    bio_ko = EXCLUDED.bio_ko, bio_en = EXCLUDED.bio_en,
    fate_kind = EXCLUDED.fate_kind, fate_label_ko = EXCLUDED.fate_label_ko, fate_label_en = EXCLUDED.fate_label_en,
    citizenship_code = EXCLUDED.citizenship_code,
    citizenship_label_ko = EXCLUDED.citizenship_label_ko, citizenship_label_en = EXCLUDED.citizenship_label_en,
    origin_code = EXCLUDED.origin_code,
    origin_label_ko = EXCLUDED.origin_label_ko, origin_label_en = EXCLUDED.origin_label_en,
    updated_at = NOW();


-- Patronymics ---------------------------------------------------------------
INSERT INTO commulingo_person_patronymics (person_id, patronymic_ko, patronymic_en, cyrillic_patronymic, updated_at)
SELECT v.id, v.p_ko, v.p_en, v.p_ru, NOW()
FROM (VALUES
    ('molchanov', '안드레예비치', 'Andreyevich', 'Андреевич'),
    ('pauker', '빅토로비치', 'Viktorovich', 'Викторович'),
    ('matvei-berman', '다비도비치', 'Davydovich', 'Давыдович'),
    ('balitsky', '아폴로노비치', 'Apollonovich', 'Аполлонович'),
    ('georgy-prokofiev', '예브게니예비치', 'Yevgenyevich', 'Евгеньевич'),
    ('redens', '프란체비치', 'Frantsevich', 'Францевич'),
    ('deribas', '드미트리예비치', 'Dmitriyevich', 'Дмитриевич'),
    ('evdokimov', '게오르기예비치', 'Georgiyevich', 'Георгиевич'),
    ('leplevsky', '모이세예비치', 'Moiseyevich', 'Моисеевич'),
    ('uspensky', '이바노비치', 'Ivanovich', 'Иванович'),
    ('belsky', '니콜라예비치', 'Nikolayevich', 'Николаевич'),
    ('zhukovsky', '보리소비치', 'Borisovich', 'Борисович'),
    ('blokhin', '미하일로비치', 'Mikhailovich', 'Михайлович'),
    ('firin', '그리고리예비치', 'Grigoryevich', 'Григорьевич'),
    ('lazar-kogan', '이오시포비치', 'Iosifovich', 'Иосифович'),
    ('frenkel', '아로노비치', 'Aronovich', 'Аронович'),
    ('goglidze', '아르세니예비치', 'Arsenievich', 'Арсеньевич'),
    ('dekanozov', '게오르기예비치', 'Georgiyevich', 'Георгиевич'),
    ('meshik', '야코블레비치', 'Yakovlevich', 'Яковлевич'),
    ('vlodzimirsky', '예멜리야노비치', 'Yemelyanovich', 'Емельянович'),
    ('amayak-kobulov', '자하로비치', 'Zakharovich', 'Захарович'),
    ('tsanava', '포미치', 'Fomich', 'Фомич'),
    ('milshtein', '라파일로비치', 'Rafailovich', 'Рафаилович'),
    ('mamulov', '솔로모노비치', 'Solomonovich', 'Соломонович'),
    ('rapava', '나리키예비치', 'Narikievich', 'Нарикиевич'),
    ('rukhadze', '막시모비치', 'Maksimovich', 'Максимович'),
    ('shalva-tsereteli', '오타로비치', 'Otarovich', 'Отарович'),
    ('nadaraya', '니콜라예비치', 'Nikolayevich', 'Николаевич'),
    ('karanadze', '테오필로비치', 'Teofilovich', 'Теофилович'),
    ('savitsky', '세르게예비치', 'Sergeyevich', 'Сергеевич'),
    ('khazan', '사모일로비치', 'Samoylovich', 'Самойлович'),
    ('krimyan', '아르카디예비치', 'Arkadyevich', 'Аркадьевич')
) AS v(id, p_ko, p_en, p_ru)
WHERE EXISTS (SELECT 1 FROM commulingo_people p WHERE p.id = v.id)
ON CONFLICT (person_id) DO UPDATE SET
    patronymic_ko = EXCLUDED.patronymic_ko, patronymic_en = EXCLUDED.patronymic_en,
    cyrillic_patronymic = EXCLUDED.cyrillic_patronymic, updated_at = NOW();


-- Aliases (full name with patronymic; birth names where documented) ----------
INSERT INTO commulingo_person_aliases (person_id, lang, alias, sort_order)
SELECT v.id, v.lang, v.alias, v.ord
FROM (VALUES
    ('molchanov', 'ko', '게오르기 안드레예비치 몰차노프', 0),
    ('molchanov', 'en', 'Georgy Andreyevich Molchanov', 0),
    ('pauker', 'ko', '카를 빅토로비치 파우케르', 0),
    ('pauker', 'en', 'Karl Viktorovich Pauker', 0),
    ('matvei-berman', 'ko', '마트베이 다비도비치 베르만', 0),
    ('matvei-berman', 'en', 'Matvei Davydovich Berman', 0),
    ('balitsky', 'ko', '프세볼로트 아폴로노비치 발리츠키', 0),
    ('balitsky', 'en', 'Vsevolod Apollonovich Balitsky', 0),
    ('georgy-prokofiev', 'ko', '게오르기 예브게니예비치 프로코피예프', 0),
    ('georgy-prokofiev', 'en', 'Georgy Yevgenyevich Prokofiev', 0),
    ('redens', 'ko', '스타니슬라프 프란체비치 레덴스', 0),
    ('redens', 'en', 'Stanislav Frantsevich Redens', 0),
    ('deribas', 'ko', '테렌티 드미트리예비치 데리바스', 0),
    ('deribas', 'en', 'Terenty Dmitriyevich Deribas', 0),
    ('evdokimov', 'ko', '예핌 게오르기예비치 예브도키모프', 0),
    ('evdokimov', 'en', 'Yefim Georgiyevich Yevdokimov', 0),
    ('leplevsky', 'ko', '이즈라일 모이세예비치 레플렙스키', 0),
    ('leplevsky', 'en', 'Izrail Moiseyevich Leplevsky', 0),
    ('uspensky', 'ko', '알렉산드르 이바노비치 우스펜스키', 0),
    ('uspensky', 'en', 'Aleksandr Ivanovich Uspensky', 0),
    ('belsky', 'ko', '레프 니콜라예비치 벨스키', 0),
    ('belsky', 'ko', '아브람 미하일로비치 레빈', 1),
    ('belsky', 'en', 'Lev Nikolayevich Belsky', 0),
    ('belsky', 'en', 'Abram Mikhailovich Levin', 1),
    ('zhukovsky', 'ko', '세묜 보리소비치 주콥스키', 0),
    ('zhukovsky', 'en', 'Semyon Borisovich Zhukovsky', 0),
    ('blokhin', 'ko', '바실리 미하일로비치 블로힌', 0),
    ('blokhin', 'en', 'Vasily Mikhailovich Blokhin', 0),
    ('firin', 'ko', '세묜 그리고리예비치 피린', 0),
    ('firin', 'ko', '세묜 푸프코', 1),
    ('firin', 'en', 'Semyon Grigoryevich Firin', 0),
    ('firin', 'en', 'Semyon Pupko', 1),
    ('lazar-kogan', 'ko', '라자리 이오시포비치 코간', 0),
    ('lazar-kogan', 'en', 'Lazar Iosifovich Kogan', 0),
    ('frenkel', 'ko', '나프탈리 아로노비치 프렌켈', 0),
    ('frenkel', 'en', 'Naftaly Aronovich Frenkel', 0),
    ('goglidze', 'ko', '세르게이 아르세니예비치 고글리제', 0),
    ('goglidze', 'en', 'Sergei Arsenievich Goglidze', 0),
    ('dekanozov', 'ko', '블라디미르 게오르기예비치 데카노조프', 0),
    ('dekanozov', 'ko', '블라디미르 데카노지시빌리', 1),
    ('dekanozov', 'en', 'Vladimir Georgievich Dekanozov', 0),
    ('dekanozov', 'en', 'Vladimir Dekanozishvili', 1),
    ('meshik', 'ko', '파벨 야코블레비치 메시크', 0),
    ('meshik', 'en', 'Pavel Yakovlevich Meshik', 0),
    ('vlodzimirsky', 'ko', '레프 예멜리야노비치 블로지미르스키', 0),
    ('vlodzimirsky', 'en', 'Lev Emelyanovich Vlodzimirsky', 0),
    ('amayak-kobulov', 'ko', '아마야크 자하로비치 코불로프', 0),
    ('amayak-kobulov', 'en', 'Amayak Zakharovich Kobulov', 0),
    ('tsanava', 'ko', '라브렌티 포미치 차나바', 0),
    ('tsanava', 'ko', '라브렌티 잔즈가바', 1),
    ('tsanava', 'en', 'Lavrentiy Fomich Tsanava', 0),
    ('tsanava', 'en', 'Lavrentiy Dzhandzhgava', 1),
    ('milshtein', 'ko', '솔로몬 라파일로비치 밀시테인', 0),
    ('milshtein', 'en', 'Solomon Rafailovich Milshtein', 0),
    ('mamulov', 'ko', '스테판 솔로모노비치 마물로프', 0),
    ('mamulov', 'ko', '스테판 마물랸', 1),
    ('mamulov', 'en', 'Stepan Solomonovich Mamulov', 0),
    ('mamulov', 'en', 'Stepan Mamulyan', 1),
    ('rapava', 'ko', '압크센티 나리키예비치 라파바', 0),
    ('rapava', 'en', 'Avksenty Narikievich Rapava', 0),
    ('rukhadze', 'ko', '니콜라이 막시모비치 루하제', 0),
    ('rukhadze', 'en', 'Nikolai Maksimovich Rukhadze', 0),
    ('shalva-tsereteli', 'ko', '샬바 오타로비치 체레텔리', 0),
    ('shalva-tsereteli', 'en', 'Shalva Otarovich Tsereteli', 0),
    ('nadaraya', 'ko', '사르디온 니콜라예비치 나다라야', 0),
    ('nadaraya', 'en', 'Sardion Nikolaevich Nadaraya', 0),
    ('karanadze', 'ko', '그리고리 테오필로비치 카라나제', 0),
    ('karanadze', 'en', 'Grigory Teofilovich Karanadze', 0),
    ('savitsky', 'ko', '콘스탄틴 세르게예비치 사비츠키', 0),
    ('savitsky', 'en', 'Konstantin Sergeyevich Savitsky', 0),
    ('khazan', 'ko', '알렉산드르 사모일로비치 하잔', 0),
    ('khazan', 'en', 'Alexander Samoylovich Khazan', 0),
    ('krimyan', 'ko', '니키타 아르카디예비치 크리먄', 0),
    ('krimyan', 'en', 'Nikita Arkadyevich Krimyan', 0)
) AS v(id, lang, alias, ord)
WHERE EXISTS (SELECT 1 FROM commulingo_people p WHERE p.id = v.id)
ON CONFLICT (person_id, lang, alias) DO UPDATE SET sort_order = EXCLUDED.sort_order;


-- Career entries ------------------------------------------------------------
INSERT INTO commulingo_person_career_entries (person_id, sort_order, period_label, role_ko, role_en, updated_at)
SELECT v.id, v.ord, v.period, v.role_ko, v.role_en, NOW()
FROM (VALUES
    ('molchanov', 0, '1919–1921', '그로즈니 체카 의장', 'Chairman of the Grozny Cheka'),
    ('molchanov', 1, '1925–1931', '이바노보-보즈네센스크 도 GPU 책임자', 'Chief of the Ivanovo-Voznesensk provincial GPU'),
    ('molchanov', 2, '1931–1936', 'OGPU·NKVD 비밀정치국장', 'Chief of the Secret Political Department, OGPU and NKVD'),
    ('molchanov', 3, '1936–1937', '벨로루시 내무인민위원', 'People''s Commissar of Internal Affairs, Belorussian SSR'),
    ('molchanov', 4, '1937', '체포와 처형', 'Arrested and executed'),
    ('pauker', 0, '1922–1923', 'OGPU 작전국 부국장', 'Deputy chief of the OGPU Operations Department'),
    ('pauker', 1, '1923–1936', 'OGPU·NKVD 작전국장', 'Chief of the OGPU and NKVD Operations Department'),
    ('pauker', 2, '1924–1937', '스탈린 개인 경호 책임자', 'Chief of Stalin''s personal security'),
    ('pauker', 3, '1936–1937', '국가보안총국 제1부장', 'Chief of the 1st Department, GUGB NKVD'),
    ('pauker', 4, '1937', '체포와 처형', 'Arrested and executed'),
    ('matvei-berman', 0, '1923–1924', '부랴트-몽골 자치공화국 내무인민위원', 'People''s Commissar of Internal Affairs, Buryat-Mongolian ASSR'),
    ('matvei-berman', 1, '1927–1928', '우즈베크 GPU 의장', 'Chairman of the GPU of the Uzbek SSR'),
    ('matvei-berman', 2, '1930–1932', '굴라크 부수장', 'Deputy chief of the Gulag'),
    ('matvei-berman', 3, '1932–1937', '굴라크 수장', 'Chief of the Gulag'),
    ('matvei-berman', 4, '1936–1937', '내무부인민위원 겸임', 'Deputy People''s Commissar of Internal Affairs (concurrent)'),
    ('matvei-berman', 5, '1937–1938', '체신인민위원', 'People''s Commissar of Communications'),
    ('matvei-berman', 6, '1938–1939', '체포, 재판과 처형', 'Arrested, tried and executed'),
    ('balitsky', 0, '1919–1922', '볼히니아·키예프 체카 의장, 전우크라이나 체카 부의장', 'Chairman of the Volhynia and Kyiv Chekas; deputy chairman of the All-Ukrainian Cheka'),
    ('balitsky', 1, '1923–1931', '우크라이나 GPU 의장', 'Chairman of the GPU of the Ukrainian SSR'),
    ('balitsky', 2, '1924–1930', '우크라이나 내무인민위원 겸임', 'People''s Commissar of Internal Affairs, Ukrainian SSR (concurrent)'),
    ('balitsky', 3, '1931–1934', 'OGPU 부의장', 'Deputy chairman of the OGPU'),
    ('balitsky', 4, '1932–1934', '우크라이나 주재 OGPU 전권대표', 'OGPU plenipotentiary representative for the Ukrainian SSR'),
    ('balitsky', 5, '1934–1937', '우크라이나 내무인민위원', 'People''s Commissar of Internal Affairs, Ukrainian SSR'),
    ('balitsky', 6, '1937', '극동 전출, 체포와 처형', 'Transferred to the Far East, arrested and executed'),
    ('georgy-prokofiev', 0, '1922–1926', 'OGPU 비밀국장, 이어 정보국장', 'Chief of the OGPU Secret Department, then the Information Department'),
    ('georgy-prokofiev', 1, '1926–1931', 'OGPU 경제국장', 'Chief of the Economic Directorate, OGPU'),
    ('georgy-prokofiev', 2, '1932–1934', 'OGPU 부의장', 'Deputy chairman of the OGPU'),
    ('georgy-prokofiev', 3, '1932–1934', '노농민병대 총국장 겸임', 'Chief of the Main Directorate of Workers'' and Peasants'' Militia (concurrent)'),
    ('georgy-prokofiev', 4, '1934–1936', '내무 제2부인민위원', 'Second Deputy People''s Commissar of Internal Affairs'),
    ('georgy-prokofiev', 5, '1936–1937', '체신 제1부인민위원', 'First Deputy People''s Commissar of Communications'),
    ('georgy-prokofiev', 6, '1937', '체포와 처형', 'Arrested and executed'),
    ('redens', 0, '1920–1921', '크림 체카 의장', 'Chairman of the Crimean Cheka'),
    ('redens', 1, '1928–1931', '자캅카스 주재 OGPU 전권대표', 'OGPU plenipotentiary representative for the Transcaucasian SFSR'),
    ('redens', 2, '1931–1933', '우크라이나 주재 OGPU 전권대표', 'OGPU plenipotentiary representative for the Ukrainian SSR'),
    ('redens', 3, '1933–1938', '모스크바주 NKVD 관리국장', 'Chief of the NKVD Directorate for Moscow Region'),
    ('redens', 4, '1937–1938', '모스크바주 트로이카 의장', 'Chairman of the Moscow region troika'),
    ('redens', 5, '1938', '카자흐 내무인민위원', 'People''s Commissar of Internal Affairs, Kazakh SSR'),
    ('redens', 6, '1938–1940', '체포, 재판과 처형', 'Arrested, tried and executed'),
    ('deribas', 0, '1923–1927', 'GPU·OGPU 비밀국장', 'Chief of the Secret Department, GPU and OGPU'),
    ('deribas', 1, '1927–1929', 'OGPU 비밀작전총국 제1부국장', 'First deputy chief of the Secret-Operational Directorate, OGPU'),
    ('deribas', 2, '1929–1934', '극동변경주 주재 OGPU 전권대표', 'OGPU plenipotentiary representative for the Far Eastern Territory'),
    ('deribas', 3, '1933–1934', 'BAM 건설 책임자', 'Head of Baikal-Amur Mainline construction'),
    ('deribas', 4, '1934–1937', '극동변경주 NKVD 관리국장 겸 극동군 특별부장', 'Chief of the NKVD Directorate for the Far Eastern Territory; head of the Special Department of the Far Eastern Army'),
    ('deribas', 5, '1937–1938', '체포, 재판과 처형', 'Arrested, tried and executed'),
    ('evdokimov', 0, '1919–1920', '모스크바 체카 특별부장, 이어 남서·남부전선 특별부 부부장', 'Chief of the Special Department of the Moscow Cheka; deputy chief of the Special Departments of the Southwestern and Southern Fronts'),
    ('evdokimov', 1, '1920–1921', '체카 크림 타격단 책임자', 'Head of the Cheka "Crimean Strike Group"'),
    ('evdokimov', 2, '1923–1929', '북캅카스 주재 OGPU 전권대표', 'OGPU plenipotentiary representative for the North Caucasus'),
    ('evdokimov', 3, '1929–1931', 'OGPU 비밀작전총국장, 콜레기움 위원', 'Chief of the Secret-Operational Directorate, OGPU; collegium member'),
    ('evdokimov', 4, '1934–1937', '북캅카스(이후 아조프-흑해)변경주 당 제1서기', 'First secretary of the North Caucasus, later Azov-Black Sea, territorial party committee'),
    ('evdokimov', 5, '1937–1938', '로스토프주 당 제1서기', 'First secretary of the Rostov regional party committee'),
    ('evdokimov', 6, '1938', '수상운수 부인민위원', 'Deputy People''s Commissar of Water Transport'),
    ('evdokimov', 7, '1938–1940', '체포, 재판과 처형', 'Arrested, tried and executed'),
    ('leplevsky', 0, '1934–1936', '벨로루시 내무인민위원', 'People''s Commissar of Internal Affairs, Belorussian SSR'),
    ('leplevsky', 1, '1936–1937', '국가보안총국 특별부장', 'Chief of the Special Department, GUGB NKVD'),
    ('leplevsky', 2, '1937–1938', '우크라이나 내무인민위원', 'People''s Commissar of Internal Affairs, Ukrainian SSR'),
    ('leplevsky', 3, '1938', 'NKVD 제6부장, 이어 제3관리국장(수송·통신)', 'Chief of the 6th Department, then of the 3rd Directorate (transport and communications), NKVD'),
    ('leplevsky', 4, '1938', '체포와 처형', 'Arrested and executed'),
    ('uspensky', 0, '1936–1937', '서시베리아 NKVD 관리국 부국장', 'Deputy head of the West Siberian NKVD directorate'),
    ('uspensky', 1, '1937–1938', '오렌부르크주 NKVD 관리국장', 'Head of the NKVD directorate for Orenburg Oblast'),
    ('uspensky', 2, '1938', '우크라이나 내무인민위원', 'People''s Commissar of Internal Affairs, Ukrainian SSR'),
    ('uspensky', 3, '1938–1939', '자살 위장 뒤 도주, 미아스에서 체포', 'Faked suicide and fled; arrested at Miass'),
    ('uspensky', 4, '1940', '재판과 처형', 'Tried and executed'),
    ('belsky', 0, '1934–1936', 'NKVD 노농민병대 총국장', 'Chief of the Main Directorate of Workers'' and Peasants'' Militia, NKVD'),
    ('belsky', 1, '1936–1938', '내무부인민위원', 'Deputy People''s Commissar of Internal Affairs'),
    ('belsky', 2, '1938–1939', '철도 제1부인민위원', 'First Deputy People''s Commissar of Railways'),
    ('belsky', 3, '1939–1941', '체포, 재판과 처형', 'Arrested, tried and executed'),
    ('zhukovsky', 0, '1932–1936', '베를린 주재 무역대표부 부대표, 대외무역인민위원부 수입국장', 'Deputy trade representative in Berlin; head of the import department, Commissariat of Foreign Trade'),
    ('zhukovsky', 1, '1936–1937', 'NKVD 행정경제국장', 'Chief of the Administrative-Economic Directorate, NKVD'),
    ('zhukovsky', 2, '1937', '국가보안총국 제3부 부부장, 제12부장', 'Deputy chief of the 3rd Department and chief of the 12th Department, GUGB NKVD'),
    ('zhukovsky', 3, '1938', '내무부인민위원', 'Deputy People''s Commissar of Internal Affairs'),
    ('zhukovsky', 4, '1938–1940', '체포, 재판과 처형', 'Arrested, tried and executed'),
    ('blokhin', 0, '1926–1953', 'NKVD·MGB 행정경제국 사령부장, 사실상의 사형집행 책임자', 'Chief of the Kommandatura of the NKVD and MGB administrative directorate, de facto chief executioner'),
    ('blokhin', 1, '1937–1938', '대테러기 처형 집행과 감독', 'Carried out and supervised executions during the Great Terror'),
    ('blokhin', 2, '1940', '칼리닌 처형팀 지휘(카틴 작전)', 'Commanded the execution team at Kalinin during the Katyn operation'),
    ('blokhin', 3, '1953–1954', '퇴역, 이어 계급 박탈', 'Retired, then stripped of rank'),
    ('firin', 0, '1920년대', '적군 정보기관 요원(그리스·터키·불가리아·유고슬라비아)', 'Red Army military intelligence operative in Greece, Turkey, Bulgaria and Yugoslavia'),
    ('firin', 1, '1932–1933', '백해-발트 운하 수용소 부소장', 'Deputy chief of the White Sea-Baltic Canal camp'),
    ('firin', 2, '1933–1937', '드미트라크 수용소장(모스크바-볼가 운하)', 'Chief of Dmitlag, the camp building the Moscow-Volga Canal'),
    ('firin', 3, '1937', '체포와 처형', 'Arrested and executed'),
    ('lazar-kogan', 0, '1930–1932', 'OGPU 굴라크 수장', 'Chief of the Gulag, OGPU'),
    ('lazar-kogan', 1, '1931–1933', '백해-발트 운하 건설 책임자', 'Chief of construction of the White Sea-Baltic Canal'),
    ('lazar-kogan', 2, '1932–1936', '굴라크 부수장', 'Deputy chief of the Gulag'),
    ('lazar-kogan', 3, '1936–1938', '수상운수 부인민위원', 'Deputy People''s Commissar of Water Transport'),
    ('lazar-kogan', 4, '1938–1939', '체포와 처형', 'Arrested and executed'),
    ('frenkel', 0, '1924–1927', '솔로프키 수용소 죄수에서 행정가로', 'Prisoner turned administrator at the Solovki camp'),
    ('frenkel', 1, '1931–1933', '백해-발트 운하 공사 책임자', 'Chief of works, White Sea-Baltic Canal'),
    ('frenkel', 2, '1933–1937', 'BAM 수용소장', 'Chief of BAMLag, the Baikal-Amur railway camp'),
    ('frenkel', 3, '1937–1947', 'NKVD·MVD 철도건설총국장', 'Chief of the Main Directorate of Railway Construction, NKVD and MVD'),
    ('frenkel', 4, '1947', '중장 계급과 연금으로 퇴역', 'Retired with the rank of lieutenant general and a pension'),
    ('goglidze', 0, '1934–1938', '조지아 내무인민위원, 조지아 NKVD 트로이카 의장', 'People''s Commissar of Internal Affairs, Georgian SSR; chairman of the NKVD troika for Georgia'),
    ('goglidze', 1, '1938–1941', '레닌그라드주 NKVD 관리국장', 'Head of the NKVD Directorate for Leningrad Region'),
    ('goglidze', 2, '1941', '몰다비아 주재 NKVD 전권대표', 'NKVD plenipotentiary for the Moldavian SSR'),
    ('goglidze', 3, '1941–1951', '하바롭스크변경주 NKVD·MGB 책임자, 극동 MGB 전권대표', 'Head of NKVD and MGB for Khabarovsk Territory; MGB plenipotentiary for the Far East'),
    ('goglidze', 4, '1951–1952', '국가보안 제1부장관', 'First Deputy Minister of State Security'),
    ('goglidze', 5, '1951–1952', '우즈베크 국가보안장관', 'Minister of State Security, Uzbek SSR'),
    ('goglidze', 6, '1952–1953', 'MGB 제3총국장(군 방첩), 국가보안 제1부장관', 'Head of the 3rd Main Directorate (military counter-intelligence), MGB; again First Deputy Minister of State Security'),
    ('goglidze', 7, '1953', '구금, 재판과 처형', 'Detained, tried and executed'),
    ('dekanozov', 0, '1921–1931', '아제르바이잔·조지아 체카·GPU 근무', 'Cheka and GPU posts in Azerbaijan and Georgia'),
    ('dekanozov', 1, '1936–1938', '조지아 식품공업인민위원, 이어 고스플란 의장', 'People''s Commissar of Food Industry, then chairman of Gosplan, Georgian SSR'),
    ('dekanozov', 2, '1938–1939', 'NKVD 국가보안총국 제5부장(대외정보)', 'Head of foreign intelligence, 5th Department of the GUGB NKVD'),
    ('dekanozov', 3, '1939–1947', '외무 부인민위원(부장관)', 'Deputy People''s Commissar, later Deputy Minister, of Foreign Affairs'),
    ('dekanozov', 4, '1940', '리투아니아 주재 전권대표, 병합 감독', 'Soviet plenipotentiary in Lithuania, supervising its annexation'),
    ('dekanozov', 5, '1940–1941', '독일 주재 소련 대사', 'USSR Ambassador to Germany'),
    ('dekanozov', 6, '1953', '조지아 내무장관', 'Minister of Internal Affairs, Georgian SSR'),
    ('dekanozov', 7, '1953', '체포, 재판과 처형', 'Arrested, tried and executed'),
    ('meshik', 0, '1939–1941', 'NKVD 수사부장, 경제총국 부국장', 'Head of the Investigative Unit, NKVD; deputy head of the Main Economic Directorate'),
    ('meshik', 1, '1941', '우크라이나 국가보안인민위원', 'People''s Commissar of State Security, Ukrainian SSR'),
    ('meshik', 2, '1941–1943', 'NKVD 경제국장', 'Head of the Economic Directorate, NKVD'),
    ('meshik', 3, '1943–1945', '스메르시 부국장', 'Deputy head of SMERSH counter-intelligence'),
    ('meshik', 4, '1945–1953', '제1총국 부국장(원폭 계획 보안·방첩)', 'Deputy head of the First Main Directorate, security and counter-intelligence for the atomic project'),
    ('meshik', 5, '1953', '우크라이나 내무장관', 'Minister of Internal Affairs, Ukrainian SSR'),
    ('meshik', 6, '1953', '체포, 재판과 처형', 'Arrested, tried and executed'),
    ('vlodzimirsky', 0, '1938–1939', 'NKVD 국가보안총국 수사부 부부장, 이어 부장', 'Deputy head, then head of the Investigative Unit of the GUGB, NKVD'),
    ('vlodzimirsky', 1, '1940–1941', '국가보안총국 제3부장, 수사 부부장', 'Head of the 3rd Department, GUGB NKVD; deputy head of investigation'),
    ('vlodzimirsky', 2, '1941–1943', 'NKVD 수사부장', 'Head of the Investigative Unit, NKVD'),
    ('vlodzimirsky', 3, '1943–1946', 'NKGB·MGB 특별중요사건 수사부장', 'Head of the Investigative Unit for Especially Important Cases, NKGB and MGB'),
    ('vlodzimirsky', 4, '1946–1947', '고리키주 MGB 관리국장, 이어 예비역', 'Head of the MGB Directorate for Gorky Region, then discharged to the reserve'),
    ('vlodzimirsky', 5, '1947–1953', '대외 소비에트재산총국 부장', 'Department head in the Main Directorate of Soviet Property Abroad'),
    ('vlodzimirsky', 6, '1953', 'MVD 특별중요사건 수사부장', 'Head of the Investigative Unit for Especially Important Cases, MVD'),
    ('vlodzimirsky', 7, '1953', '체포, 재판과 처형', 'Arrested, tried and executed'),
    ('amayak-kobulov', 0, '1937–1938', '가그라 시 NKVD 부장, 이어 압하지야 자치공화국 NKVD', 'Head of the Gagra city NKVD department, then of the NKVD of the Abkhaz ASSR'),
    ('amayak-kobulov', 1, '1938–1939', '우크라이나 내무인민위원 대행', 'Acting People''s Commissar of Internal Affairs, Ukrainian SSR'),
    ('amayak-kobulov', 2, '1939–1941', '베를린 주재 대사관 참사관, NKVD 합법 레지덴트', 'Counsellor of the Soviet embassy in Berlin; legal NKVD rezident'),
    ('amayak-kobulov', 3, '1941–1945', '우즈베크 국가보안인민위원, 이어 내무인민위원', 'People''s Commissar of State Security, then of Internal Affairs, Uzbek SSR'),
    ('amayak-kobulov', 4, '1945–1951', '포로·억류자 관리총국 부국장, 이어 제1부국장', 'Deputy, then first deputy head of the Main Directorate for POWs and Internees'),
    ('amayak-kobulov', 5, '1951–1953', '포로관리국장 겸 굴라크 제1부수장', 'Head of the POW directorate and first deputy head of the Gulag'),
    ('amayak-kobulov', 6, '1953–1955', '체포, 별도 재판과 처형', 'Arrested, tried separately and executed'),
    ('tsanava', 0, '1938–1941', '벨로루시 내무인민위원', 'People''s Commissar of Internal Affairs, Belorussian SSR'),
    ('tsanava', 1, '1941', '벨로루시 국가보안인민위원', 'People''s Commissar of State Security, Belorussian SSR'),
    ('tsanava', 2, '1941–1943', '벨로루시 NKVD, 서부·중부전선 특별부장', 'NKVD of the Belorussian SSR; head of Special Departments of the Western and Central Fronts'),
    ('tsanava', 3, '1942–1943', '파르티잔운동 중앙참모부 부장', 'Deputy head of the Central Staff of the Partisan Movement'),
    ('tsanava', 4, '1943–1951', '벨로루시 국가보안인민위원, 이어 장관', 'People''s Commissar, then Minister, of State Security, Belorussian SSR'),
    ('tsanava', 5, '1951–1952', '소련 국가보안 부장관, 제2총국장(방첩)', 'Deputy Minister of State Security of the USSR; head of the 2nd Main Directorate'),
    ('tsanava', 6, '1953–1955', '체포, 재판 없이 옥중 사망', 'Arrested; died in custody without trial'),
    ('milshtein', 0, '1920년대–1938', '조지아 당 사업, 트빌리시 시당 서기 등', 'Party work in Georgia, including secretary of the Tbilisi city committee'),
    ('milshtein', 1, '1938–1939', 'NKVD 수사부 부부장', 'Deputy head of the Investigative Unit, NKVD'),
    ('milshtein', 2, '1939–1941', 'NKVD 수송총국장', 'Head of the Main Transport Directorate, NKVD'),
    ('milshtein', 3, '1941–1942', 'NKVD 특별부관리국 제1부국장', 'First deputy head of the Directorate of Special Departments, NKVD'),
    ('milshtein', 4, '1942–1943', 'NKVD 수송국장', 'Head of the Transport Directorate, NKVD'),
    ('milshtein', 5, '1943–1947', 'NKGB·MGB 제3관리국장(수송)', 'Head of the 3rd Directorate (transport), NKGB and MGB'),
    ('milshtein', 6, '1951–1953', 'MVD 굴라크 부수장', 'Deputy head of the Gulag, MVD'),
    ('milshtein', 7, '1953', '우크라이나 내무 제1부장관', 'First Deputy Minister of Internal Affairs, Ukrainian SSR'),
    ('milshtein', 8, '1953–1955', '체포, 별도 재판과 처형', 'Arrested, tried separately and executed'),
    ('mamulov', 0, '1923–1938', '압하지야·조지아·카자흐스탄 당 사업, 트빌리시 시당 서기', 'Party work in Abkhazia, Georgia and Kazakhstan; secretary of the Tbilisi city committee'),
    ('mamulov', 1, '1939–1946', 'NKVD·MVD 서기국장', 'Head of the Secretariat of the NKVD and MVD'),
    ('mamulov', 2, '1946–1953', '내무 부장관(수용소·보급 관장)', 'Deputy Minister of Internal Affairs, supervising camp and supply administrations'),
    ('mamulov', 3, '1953', '조지아 공산당 중앙위원회 부장', 'Department head, Central Committee of the Communist Party of Georgia'),
    ('mamulov', 4, '1953–1968', '체포, 십오 년형 복역', 'Arrested; served a fifteen-year sentence'),
    ('rapava', 0, '1930–1931', '아자리야 GPU 책임자', 'Head of the Adjarian GPU'),
    ('rapava', 1, '1931–1933', '조지아 GPU 부의장', 'Deputy chairman of the Georgian GPU'),
    ('rapava', 2, '1936–1937', '자캅카스·조지아 부내무인민위원', 'Deputy People''s Commissar of Internal Affairs, Transcaucasian SFSR and Georgian SSR'),
    ('rapava', 3, '1937–1938', '압하지야 중앙집행위원회 의장, 이어 인민위원회의 의장', 'Chairman of the Abkhaz Central Executive Committee, then of the Abkhaz Council of People''s Commissars'),
    ('rapava', 4, '1938–1943', '조지아 내무인민위원', 'People''s Commissar of Internal Affairs, Georgian SSR'),
    ('rapava', 5, '1943–1948', '조지아 국가보안인민위원, 이어 장관', 'People''s Commissar, then Minister, of State Security, Georgian SSR'),
    ('rapava', 6, '1948–1951', '조지아 법무장관', 'Minister of Justice, Georgian SSR'),
    ('rapava', 7, '1953', '조지아 국가통제장관', 'Minister of State Control, Georgian SSR'),
    ('rapava', 8, '1953–1955', '체포, 트빌리시 재판과 처형', 'Arrested, tried at Tbilisi and executed'),
    ('rukhadze', 0, '1937–1938', '압하지야 가그라 지구 NKVD 부장', 'Head of the Gagra district NKVD department, Abkhazia'),
    ('rukhadze', 1, '1939–1941', '조지아 NKVD 수사과장', 'Chief of the investigation section, NKVD of the Georgian SSR'),
    ('rukhadze', 2, '1941–1943', '조지아 부내무인민위원, 자캅카스전선 특별부장', 'Deputy People''s Commissar of Internal Affairs, Georgian SSR; head of the Special Department of the Transcaucasian Front'),
    ('rukhadze', 3, '1943–1945', '자캅카스전선·군관구 스메르시 방첩 책임자', 'Head of SMERSH counter-intelligence, Transcaucasian Front and Military District'),
    ('rukhadze', 4, '1948–1952', '조지아 국가보안장관', 'Minister of State Security, Georgian SSR'),
    ('rukhadze', 5, '1952–1955', '체포, 트빌리시 재판과 처형', 'Arrested, tried at Tbilisi and executed'),
    ('shalva-tsereteli', 0, '1914–1915', '제정 러시아군 소위, 포로', 'Ensign in the Imperial Russian Army; prisoner of war'),
    ('shalva-tsereteli', 1, '1937–1938', '조지아 민병대 책임자, NKVD 특별 트로이카 위원', 'Head of the Georgian militia; member of the NKVD "special troika"'),
    ('shalva-tsereteli', 2, '1939–1941', '자캅카스 국경경비대 관리국장', 'Head of the Transcaucasian border troops administration'),
    ('shalva-tsereteli', 3, '1941–1946', '조지아 제1부내무인민위원', 'First Deputy People''s Commissar of Internal Affairs, Georgian SSR'),
    ('shalva-tsereteli', 4, '1946–1953', '조지아 부국가보안장관, 국경경비대 지휘 겸임', 'Deputy Minister of State Security, Georgian SSR, while retaining border troops command'),
    ('shalva-tsereteli', 5, '1953–1955', '체포, 트빌리시 재판과 처형', 'Arrested, tried at Tbilisi and executed'),
    ('nadaraya', 0, '1937–1938', '조지아 NKVD 내부감옥 부책임자, 이어 책임자', 'Deputy head, then head, of the NKVD internal prison of the Georgian SSR'),
    ('nadaraya', 1, '1939–1946', '베리야 개인 경호 부책임자', 'Deputy head of Beria''s personal security detail'),
    ('nadaraya', 2, '1946–1952', 'MGB 경호총국 장교', 'Officer, guards directorate of the MGB'),
    ('nadaraya', 3, '1952–1953', 'MGB 제41 경호대 부책임자', 'Deputy head of personal security unit No. 41, MGB'),
    ('nadaraya', 4, '1953', '베리야 개인 경호 책임자', 'Chief of Beria''s personal security'),
    ('nadaraya', 5, '1953–1965', '체포, 십 년형 복역', 'Arrested; served a ten-year sentence'),
    ('karanadze', 0, '1935–1937', '트빌리시·시그나기 지구당 제1서기', 'First secretary of the Tbilisi and Signakhi district party committees'),
    ('karanadze', 1, '1938–1941', '크림 자치공화국 내무인민위원', 'People''s Commissar of Internal Affairs, Crimean ASSR'),
    ('karanadze', 2, '1942–1943', '다게스탄 자치공화국 내무인민위원', 'People''s Commissar of Internal Affairs, Dagestan ASSR'),
    ('karanadze', 3, '1943–1952', '조지아 내무인민위원, 이어 장관', 'People''s Commissar, then Minister, of Internal Affairs, Georgian SSR'),
    ('karanadze', 4, '1952–1953', '‘밍그렐리아 사건’으로 체포, 이후 복권', 'Arrested in the "Mingrelian affair", later rehabilitated'),
    ('karanadze', 5, '1953', '조지아 내무 부장관', 'Deputy Minister of Internal Affairs, Georgian SSR'),
    ('karanadze', 6, '1957–1970', '조지아 각료회의 국가산림위원회 부의장', 'Deputy chairman, State Forestry Committee of the Georgian Council of Ministers'),
    ('savitsky', 0, '1931–1939', '조지아 NKVD 제4부 요원, 과장, 부부장', 'Operative, then section head and assistant head of the 4th department, NKVD of the Georgian SSR'),
    ('savitsky', 1, '1941–1943', 'NKVD 제4국 과 부책임자', 'Deputy section chief, 4th directorate, NKVD'),
    ('savitsky', 2, '1943–1945', '보그단 코불로프의 개인 비서', 'Personal secretary to Bogdan Kobulov'),
    ('savitsky', 3, '1945–1953', 'NKGB 서기국 부국장, 이후 대외 소비에트재산총국 보좌', 'Deputy chief of the NKGB secretariat; later assistant in the Main Administration of Soviet Property Abroad'),
    ('savitsky', 4, '1953', '내무 제1부장관 보그단 코불로프의 보좌관', 'Assistant to Bogdan Kobulov, first deputy minister of internal affairs'),
    ('savitsky', 5, '1953–1955', '체포, 트빌리시 재판과 처형', 'Arrested, tried at Tbilisi and executed'),
    ('khazan', 0, '1928–1933', '오데사 GPU 관구부 요원, OGPU 고등학교 수학', 'Operative, Odessa GPU regional department; student at the Higher School of the OGPU'),
    ('khazan', 1, '1933–1937', '조지아 NKVD 요원, 이어 과장', 'Operative, then section head, NKVD of the Georgian SSR'),
    ('khazan', 2, '1937–1938', '조지아 NKVD 비밀정치부 제1과장 겸 부부장', 'Head of the 1st section and assistant head of the Secret-Political Department, NKVD of the Georgian SSR'),
    ('khazan', 3, '1938', '체포되었다가 두 달 뒤 석방, 전역', 'Arrested, released after two months and discharged'),
    ('khazan', 4, '1942–1945', 'NKVD 중앙기구 장교', 'Officer, central apparatus of the NKVD'),
    ('khazan', 5, '1953–1955', '체포, 트빌리시 재판과 처형', 'Arrested, tried at Tbilisi and executed'),
    ('krimyan', 0, '1932–1935', '자캅카스 GPU 경제부 견습, 이어 담당관', 'Trainee in the Economic Department of the Transcaucasian GPU, then authorized officer'),
    ('krimyan', 1, '1935–1937', '조지아 NKVD 국가보안관리국 선임요원, 이어 과 부책임자', 'Senior operative, then assistant section chief, UGB NKVD of the Georgian SSR'),
    ('krimyan', 2, '1937–1938', '조지아 NKVD 국가보안관리국 과장', 'Section chief, UGB NKVD of the Georgian SSR'),
    ('krimyan', 3, '1938–1940', '조지아 NKVD 수사부 부부장, 이어 부장', 'Deputy chief, then chief, of the Investigative Department, NKVD of the Georgian SSR'),
    ('krimyan', 4, '1940–1941', '리보프주 NKVD 관리국 부국장', 'Deputy chief of the NKVD Administration for Lvov Oblast'),
    ('krimyan', 5, '1941–1943', '야로슬라블주 NKGB·NKVD 관리국 부국장', 'Deputy chief of the NKGB and NKVD Administration for Yaroslavl Oblast'),
    ('krimyan', 6, '1943–1945', '야로슬라블주 NKGB 관리국장', 'Chief of the NKGB Administration for Yaroslavl Oblast'),
    ('krimyan', 7, '1945–1947', '아르메니아 국가보안인민위원, 이어 장관', 'People''s Commissar, then Minister, of State Security of the Armenian SSR'),
    ('krimyan', 8, '1947–1950', '울리야놉스크주 MGB 관리국장', 'Chief of the MGB Administration for Ulyanovsk Oblast'),
    ('krimyan', 9, '1951–1953', '아르메니아 식품공업부 인사부장', 'Head of the personnel department, Ministry of Food Industry of the Armenian SSR'),
    ('krimyan', 10, '1953–1955', '체포, 트빌리시 재판과 처형', 'Arrested, tried at Tbilisi and executed')
) AS v(id, ord, period, role_ko, role_en)
WHERE EXISTS (SELECT 1 FROM commulingo_people p WHERE p.id = v.id)
  AND NOT EXISTS (
      SELECT 1 FROM commulingo_person_career_entries c
      WHERE c.person_id = v.id AND c.sort_order = v.ord
  );


-- Role marker: all of these belong to the state-security office -------------
INSERT INTO commulingo_person_roles (person_id, icon, office_id, label_ko, label_en, updated_at)
SELECT v.id, '', 'state-security', '', '', NOW()
FROM (VALUES
    ('molchanov'), ('pauker'), ('matvei-berman'), ('balitsky'), ('georgy-prokofiev'),
    ('redens'), ('deribas'), ('evdokimov'), ('leplevsky'), ('uspensky'),
    ('belsky'), ('zhukovsky'), ('blokhin'), ('firin'), ('lazar-kogan'),
    ('frenkel'), ('goglidze'), ('dekanozov'), ('meshik'),
    ('vlodzimirsky'), ('amayak-kobulov'), ('tsanava'), ('milshtein'), ('mamulov'),
    ('rapava'), ('rukhadze'), ('shalva-tsereteli'), ('nadaraya'),
    ('karanadze'), ('savitsky'), ('khazan'), ('krimyan')
) AS v(id)
WHERE EXISTS (SELECT 1 FROM commulingo_people p WHERE p.id = v.id)
ON CONFLICT (person_id) DO UPDATE SET
    office_id = EXCLUDED.office_id, updated_at = NOW();
