-- Term-to-term relations. The definitions already cross-reference each other
-- (NEP names the NEPmen, kolkhoz names the sovkhoz, prodrazvyorstka names the
-- food dictatorship) but nothing linked them, so the glossary had no internal
-- graph at all.
--
-- Pairs are stored once and mirrored when read (data/commulingo/terms-store.js),
-- so 'nep <-> nepman' needs one row, not two.

CREATE TABLE IF NOT EXISTS commulingo_term_relations (
    term_id    TEXT NOT NULL REFERENCES commulingo_terms(id) ON DELETE CASCADE,
    related_id TEXT NOT NULL REFERENCES commulingo_terms(id) ON DELETE CASCADE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (term_id, related_id),
    CHECK (term_id <> related_id)
);

INSERT INTO commulingo_term_relations (term_id, related_id) VALUES
-- NEP and the agrarian question
('nep', 'nepman'),
('nep', 'war-communism'),
('nep', 'prodrazvyorstka'),
('nep', 'smychka'),
('nep', 'great-break'),
('nep', 'khozraschet'),
('nep', 'chervonets'),
('nep', 'primitive-socialist-accumulation'),
('nep', 'goelro'),
('nep', 'state-capitalism'),
('nep', 'right-opposition'),
('war-communism', 'prodrazvyorstka'),
('war-communism', 'food-dictatorship'),
('war-communism', 'red-terror'),
('war-communism', 'left-communists'),
('prodrazvyorstka', 'food-dictatorship'),
('prodrazvyorstka', 'kulak'),
('collectivization', 'kulak'),
('collectivization', 'kolkhoz'),
('collectivization', 'great-break'),
('collectivization', 'chayanovshchina'),
('collectivization', 'little-october'),
('kolkhoz', 'kulak'),
('kolkhoz', 'zveno'),
('kolkhoz', 'food-sovereignty'),
('kulak', 'nepman'),
('great-break', 'primitive-socialist-accumulation'),
('great-break', 'right-opposition'),
('great-break', 'menshevizing-idealism'),
('great-break', 'stakhanovite-movement'),
-- Planning, money, accounting
('control-figures', 'goelro'),
('control-figures', 'primitive-socialist-accumulation'),
('chervonets', 'khozraschet'),
('khozraschet', 'zveno'),
('smychka', 'primitive-socialist-accumulation'),
-- Repression and law
('gulag', 'article-58'),
('gulag', 'sharashka'),
('gulag', 'great-purge'),
('article-58', 'great-purge'),
('article-58', 'socialist-legality'),
('article-58', 'sharashka'),
('great-purge', 'yezhovshchina'),
('great-purge', 'moscow-trials'),
('great-purge', 'troika'),
('great-purge', 'old-bolshevik'),
('moscow-trials', 'left-opposition'),
('moscow-trials', 'right-opposition'),
('moscow-trials', 'old-bolshevik'),
('red-terror', 'troika'),
('red-terror', 'revolutionary-legal-consciousness'),
('socialist-legality', 'revolutionary-legal-consciousness'),
('socialist-legality', 'great-purge'),
('troika', 'yezhovshchina'),
-- Theory
('permanent-revolution', 'socialism-in-one-country'),
('permanent-revolution', 'left-opposition'),
('permanent-revolution', 'dual-power'),
('socialism-in-one-country', 'right-opposition'),
('socialism-in-one-country', 'juche'),
('soviet-thermidor', 'bonapartism'),
('soviet-thermidor', 'nomenklatura'),
('soviet-thermidor', 'left-opposition'),
('soviet-thermidor', 'state-capitalism'),
('dictatorship-of-the-proletariat', 'democratic-centralism'),
('dictatorship-of-the-proletariat', 'dual-power'),
('dictatorship-of-the-proletariat', 'free-association-of-producers'),
('reformism', 'liquidationism'),
('reformism', 'eurocommunism'),
('reformism', 'mass-strike'),
('mass-strike', 'dual-power'),
('mass-strike', '1987-system'),
('law-of-the-tendency-of-the-rate-of-profit-to-fall', 'state-capitalism'),
-- Factions and line struggles
('left-opposition', 'right-opposition'),
('left-opposition', 'declaration-of-46'),
('left-communists', 'workers-opposition'),
('workers-opposition', 'democratic-centralism'),
('declaration-of-46', 'democratic-centralism'),
('chayanovshchina', 'kondratievshchina'),
('kondratievshchina', 'control-figures'),
-- Party and state
('nomenklatura', 'old-bolshevik'),
('nomenklatura', 'sovnarkom'),
('sovnarkom', 'dual-power'),
('perestroika', 'glasnost'),
('perestroika', 'khozraschet'),
('perestroika', 'zveno'),
-- Nationalities and culture
('korenizatsiya', 'great-russian-chauvinism'),
('korenizatsiya', 'national-delimitation'),
('korenizatsiya', 'autonomization'),
('korenizatsiya', 'little-october'),
('autonomization', 'national-delimitation'),
('autonomization', 'great-russian-chauvinism'),
('proletkult', 'socialist-realism'),
('proletkult', 'likbez'),
('socialist-realism', 'stakhanovite-movement'),
-- International movement
('two-camps-doctrine', 'brezhnev-doctrine'),
('two-camps-doctrine', 'eurocommunism'),
('brezhnev-doctrine', 'eurocommunism'),
-- Korean political economy
('1987-system', 'chaebol-state'),
('1987-system', 'super-corporate-union'),
('1987-system', 'division-system'),
('1987-system', 'jobless-growth'),
('1987-system', 'anti-imperialist-anti-monopoly'),
('1987-system', 'anti-insurrection-shield'),
('chaebol-state', 'developmental-state'),
('chaebol-state', 'comprador-monopoly-capitalism'),
('gap-investment', 'public-concept-of-land-ownership'),
('gap-investment', 'real-financial-divergence'),
('super-corporate-union', 'precariat'),
('division-system', 'juche'),
('anti-imperialist-anti-monopoly', 'comprador-monopoly-capitalism'),
-- Contemporary capitalism and left discourse
('precariat', 'jobless-growth'),
('jobless-growth', 'developmental-state'),
('economic-security', 'semiconductor-supercycle'),
('semiconductor-supercycle', 'real-financial-divergence'),
('real-financial-divergence', 'law-of-the-tendency-of-the-rate-of-profit-to-fall'),
('ecosocialism', 'food-sovereignty'),
('ecosocialism', 'community-wealth-building'),
('ecosocialism', 'digital-communism'),
('food-sovereignty', 'community-wealth-building'),
('digital-communism', 'free-association-of-producers'),
('hukou-system', 'developmental-state')
ON CONFLICT DO NOTHING;
