-- Glossary entries for every genealogy-chart node that previously had no
-- dictionary target. The matching chart refs are added in the same change,
-- so all fifteen boxes become links as soon as this migration is applied.

INSERT INTO commulingo_terms
    (id, sort_order, term_ko, term_en, original, period_label,
     period_ko, period_en, start_year, end_year, category,
     definition_ko, definition_en, sources)
VALUES
('zimmerwald-movement', 10140,
 $q$치머발트 운동$q$, $q$Zimmerwald Movement$q$, $q$Zimmerwalder Bewegung$q$, $q$1915–1917$q$,
 $q$1915–1917$q$, $q$1915–1917$q$, 1915, 1917, 'international',
 $q$제1차 세계대전 중 각국 사회주의 정당의 전쟁 지지에 반대한 국제주의자들의 운동. 1915년 스위스 치머발트 회의와 1916년 킨탈 회의를 중심으로 전쟁 반대 세력을 다시 연결했으며, 내부의 치머발트 좌파는 제3인터내셔널 창립 세력의 한 축이 되었다.$q$,
 $q$The internationalist movement of socialists who opposed their parties' support for the First World War. It reconnected anti-war currents through the Zimmerwald conference of 1915 and the Kiental conference of 1916; its Zimmerwald Left became one of the formative currents of the Third International.$q$,
 $q$["https://encyclopedia.1914-1918-online.net/article/zimmerwald-conference/ — conference, manifesto, International Socialist Commission and Kiental sequel", "https://www.marxists.org/glossary/orgs/z/i.htm — Zimmerwald Left, its programme and role before the Third International"]$q$::jsonb),

('vienna-union', 10141,
 $q$빈 국제연합 (2½ 인터내셔널)$q$, $q$Vienna Union (Two-and-a-Half International)$q$,
 $q$Internationale Arbeitsgemeinschaft Sozialistischer Parteien$q$, $q$1921–1923$q$,
 $q$1921–1923$q$, $q$1921–1923$q$, 1921, 1923, 'international',
 $q$제2인터내셔널의 개혁주의와 코민테른의 혁명 노선 사이에서 통합을 시도한 중도 사회주의 정당들의 국제 조직. 1921년 빈에서 결성되어 독일 독립사회민주당, 영국 독립노동당, 러시아 멘셰비키 등을 묶었고, 1923년 재건된 제2인터내셔널과 합쳐 노동사회주의 인터내셔널을 만들었다.$q$,
 $q$An international organization of centrist socialist parties that tried to bridge the reformism of the Second International and the revolutionary line of the Comintern. Founded in Vienna in 1921, it included the German USPD, the British ILP and the Russian Mensheviks, and merged with the reconstituted Second International in 1923 to form the Labour and Socialist International.$q$,
 $q$["https://www.marxists.org/glossary/orgs/t/w.htm — formation, political position and 1923 reunion", "https://www.marxists.org/archive/hallas/works/1985/comintern/ch3.htm — Vienna Union membership, unity campaign and creation of the LSI"]$q$::jsonb),

('anarcho-syndicalist-iwa', 10142,
 $q$아나르코생디칼리슴 국제노동자협회$q$, $q$Anarcho-syndicalist International Workers' Association$q$,
 $q$Asociación Internacional de los Trabajadores$q$, $q$1922–$q$,
 $q$1922년–$q$, $q$1922–present$q$, 1922, NULL, 'international',
 $q$혁명적 노동조합을 사회 변혁의 주체로 보는 아나르코생디칼리슴 국제 조직. 1922년 베를린에서 코민테른 계열의 적색노동조합 인터내셔널과 구별되는 연합으로 창립되었고, 스페인의 CNT를 비롯한 각국 생디칼리스트 노조가 참여했다. 1864년의 제1인터내셔널과 같은 영어 약칭 IWA를 쓴다.$q$,
 $q$The anarcho-syndicalist international that treats revolutionary unions as the agents of social transformation. Founded in Berlin in 1922 as an alternative to the Comintern-aligned Red International of Labour Unions, it included syndicalist unions such as Spain's CNT. It shares the English abbreviation IWA with the First International of 1864.$q$,
 $q$["https://iwa-ait.org/node/86 — founding congress in Berlin, dates, delegates and participating unions", "https://www.iwa-ait.org/content/kropotkin-and-rebuilding-international-workers-association — the 1922 refounding and anarcho-syndicalist lineage"]$q$::jsonb),

('labour-and-socialist-international', 10143,
 $q$노동사회주의 인터내셔널$q$, $q$Labour and Socialist International$q$,
 $q$Sozialistische Arbeiter-Internationale$q$, $q$1923–1940$q$,
 $q$1923–1940$q$, $q$1923–1940$q$, 1923, 1940, 'international',
 $q$재건된 제2인터내셔널과 빈 국제연합이 1923년 함부르크에서 합쳐 만든 사회민주주의·노동당의 국제 조직. 공산주의 인터내셔널과 세계 노동운동의 지도권을 두고 경쟁했으나 파시즘의 확대와 제2차 세계대전 발발 속에서 활동을 멈췄다.$q$,
 $q$The international of social-democratic and labour parties created at Hamburg in 1923 by the merger of the reconstituted Second International and the Vienna Union. It competed with the Communist International for leadership of the world labour movement, but ceased operating amid the spread of fascism and the outbreak of the Second World War.$q$,
 $q$["https://www.marxists.org/archive/hallas/works/1985/comintern/ch3.htm — the 1923 merger and interwar setting", "https://en.wikipedia.org/wiki/Labour_and_Socialist_International — organization, dates and rivalry with the Comintern"]$q$::jsonb),

('socialist-international', 10144,
 $q$사회주의 인터내셔널$q$, $q$Socialist International$q$, $q$$q$, $q$1951–$q$,
 $q$1951년–$q$, $q$1951–present$q$, 1951, NULL, 'international',
 $q$제2차 세계대전 뒤 사회민주주의·사회주의 정당들이 재건한 국제 조직. 1951년 프랑크푸르트 창립대회에서 현재의 형태를 갖추고 민주사회주의의 목표와 과제를 선언했으며, 전간기 노동사회주의 인터내셔널의 계보를 이었다.$q$,
 $q$The international organization rebuilt after the Second World War by social-democratic and socialist parties. It took its present form at the Frankfurt Congress of 1951, which declared the aims and tasks of democratic socialism, and continued the lineage of the interwar Labour and Socialist International.$q$,
 $q$["https://www.socialistinternational.org/about-us/ — official history and re-establishment in 1951", "https://www.socialistinternational.org/our-meetings/congresses/i-frankfurt/ — Frankfurt founding congress and declaration"]$q$::jsonb),

('fourth-international-splits', 10145,
 $q$제4인터내셔널의 분열과 재통합$q$, $q$Splits and Reunification of the Fourth International$q$,
 $q$$q$, $q$1953 / 1963$q$,
 $q$1953년 분열, 1963년 부분 재통합$q$, $q$1953 split; 1963 partial reunification$q$, 1953, 1963, 'international',
 $q$트로츠키주의 제4인터내셔널이 미셸 파블로의 전술과 각국 공산당·사회민주당에 대한 태도를 둘러싸고 1953년 국제서기국과 국제위원회로 갈라진 사건과 그 뒤의 부분적 재결합. 1963년 다수파는 쿠바혁명 평가 등의 접근을 바탕으로 통합서기국을 구성했지만 프랑스와 영국의 주요 분파는 합류하지 않아 복수의 국제 조직이 남았다.$q$,
 $q$The 1953 division of the Trotskyist Fourth International into the International Secretariat and International Committee over Michel Pablo's tactics and attitudes toward communist and social-democratic parties, followed by a partial reunion. In 1963 majorities reunited around converging views including their assessment of the Cuban Revolution, but important French and British currents stayed out, leaving multiple rival internationals.$q$,
 $q$["https://en.wikipedia.org/wiki/Fourth_International — 1953 schism, 1963 partial reunification and successor currents", "https://en.wikipedia.org/wiki/Fourth_International_(post-reunification) — causes of the split and path to reunification"]$q$::jsonb),

('narodniks', 10146,
 $q$나로드니키$q$, $q$Narodniks$q$, $q$народники$q$, $q$1860년대–1880년대$q$,
 $q$1860년대–1880년대$q$, $q$1860s–1880s$q$, 1860, 1889, 'theory',
 $q$러시아의 농민공동체와 농민 혁명을 사회주의로 가는 토대로 본 19세기 후반의 인민주의 운동. 지식인들의 ‘인민 속으로’ 운동, 토지와 자유당, 인민의 의지 등 여러 흐름을 낳았으며, 러시아 마르크스주의는 나로드니키의 농민사회주의와 논쟁하는 가운데 형성되었다.$q$,
 $q$The late nineteenth-century Russian populist movement that treated the peasant commune and a peasant revolution as the basis of a road to socialism. It produced currents including the “going to the people” campaign, Land and Liberty and the People's Will; Russian Marxism formed in polemic against its peasant socialism.$q$,
 $q$["https://www.britannica.com/topic/Narodnik — origins, peasant orientation and the going-to-the-people movement", "https://www.marxists.org/archive/lenin/works/1894/friends/index.htm — contemporary Marxist polemic against Narodnik social theory"]$q$::jsonb),

('economism', 10147,
 $q$경제주의$q$, $q$Economism$q$, $q$экономизм$q$, $q$1899–1903$q$,
 $q$1899–1903$q$, $q$1899–1903$q$, 1899, 1903, 'theory',
 $q$노동자의 임금·노동시간 등 경제투쟁을 우선하고 전제정에 맞선 정치투쟁의 지도는 자유주의 세력에 맡기려 한 러시아 사회민주주의 내부의 조류. 『라보차야 미슬』과 『라보체예 델로』를 중심으로 나타났고, 『이스크라』와 레닌의 『무엇을 할 것인가?』가 이를 비판하며 전국적 정치조직의 필요성을 주장했다.$q$,
 $q$A current within Russian Social Democracy that prioritized workers' economic struggles over wages and hours while leaving leadership of the political struggle against autocracy to liberal forces. Associated with Rabochaya Mysl and Rabocheye Dyelo, it was attacked by Iskra and Lenin's What Is to Be Done?, which argued for a nationwide political organization.$q$,
 $q$["https://www.marxists.org/archive/lenin/works/1902/witbd/ — Lenin's contemporary critique of Economism and argument for political organization", "https://www.marxists.org/archive/lenin/works/1901/dec/06.htm — draft declaration on Iskra and the Economists"]$q$::jsonb),

('rsdlp', 10148,
 $q$러시아사회민주노동당$q$, $q$Russian Social Democratic Labour Party$q$,
 $q$Российская социал-демократическая рабочая партия$q$, $q$1898–1918$q$,
 $q$1898–1918$q$, $q$1898–1918$q$, 1898, 1918, 'party-state',
 $q$러시아 제국의 여러 마르크스주의 조직을 하나로 묶기 위해 1898년 민스크에서 창당된 정당. 제1차 대회는 곧바로 탄압받았지만 당명과 선언을 남겼고, 1903년 제2차 대회에서 볼셰비키와 멘셰비키가 갈라졌다. 볼셰비키 분파는 1918년 러시아공산당(볼셰비키)으로 당명을 바꿨다.$q$,
 $q$The party founded at Minsk in 1898 to unite the Marxist organizations of the Russian Empire. Its first congress was immediately repressed but left a party name and manifesto; at the second congress in 1903 it divided into Bolshevik and Menshevik wings. The Bolshevik organization renamed itself the Russian Communist Party (Bolsheviks) in 1918.$q$,
 $q$["https://www.marxists.org/history/international/social-democracy/rsdlp/1898/manifesto.htm — manifesto of the 1898 founding congress", "https://en.wikipedia.org/wiki/Russian_Social_Democratic_Labour_Party — founding, congresses and factional development"]$q$::jsonb),

('menshevik-defencists-internationalists', 10149,
 $q$멘셰비키 방위파와 국제주의파$q$, $q$Menshevik Defencists and Internationalists$q$,
 $q$оборонцы и интернационалисты$q$, $q$1914–1917$q$,
 $q$1914–1917$q$, $q$1914–1917$q$, 1914, 1917, 'factions',
 $q$제1차 세계대전에서 러시아의 전쟁 수행을 지지할지를 둘러싼 멘셰비키 내부의 분열. 플레하노프·포트레소프 등의 방위파는 조국 방위를 내세웠고, 마르토프가 이끈 국제주의파는 전쟁을 제국주의 전쟁으로 규정해 반대했다. 1917년 2월혁명 뒤에는 혁명 방위를 명분으로 전쟁 계속을 지지하는 ‘혁명적 방위주의’가 다시 경계를 흔들었다.$q$,
 $q$The Menshevik division over whether to support Russia's conduct of the First World War. Defencists such as Plekhanov and Potresov invoked national defence, while the Internationalists led by Martov opposed the conflict as an imperialist war. After the February Revolution of 1917, “revolutionary defencism” in support of continuing the war blurred the boundary again.$q$,
 $q$["https://en.wikipedia.org/wiki/Factions_of_the_Russian_Social_Democratic_Labour_Party — Menshevik Defencists and Martov's Internationalists", "https://www.marxists.org/archive/lenin/works/1914/oct/x01.htm — contemporary debate over war, internationalism and Menshevik currents"]$q$::jsonb),

('workers-opposition', 10150,
 $q$노동자반대파$q$, $q$Workers' Opposition$q$, $q$Рабочая оппозиция$q$, $q$1920–1921$q$,
 $q$1920–1921$q$, $q$1920–1921$q$, 1920, 1921, 'factions',
 $q$산업 관리를 관료적 국가기관이 아니라 생산자들의 노동조합에 맡기자고 주장한 러시아공산당 내부 분파. 알렉산드라 콜론타이, 알렉산드르 실랴프니코프, 세르게이 메드베데프 등이 이끌었으며, 1921년 제10차 당대회의 분파 금지 결의 뒤 해산했다.$q$,
 $q$A faction of the Russian Communist Party that argued industrial management should pass from bureaucratic state organs to the producers' trade unions. Led by figures including Alexandra Kollontai, Alexander Shliapnikov and Sergei Medvedev, it dissolved after the Tenth Party Congress banned factions in 1921.$q$,
 $q$["https://www.marxists.org/archive/kollonta/1921/workers-opposition/index.htm — Kollontai's contemporary statement of the faction's programme", "https://en.wikipedia.org/wiki/Workers%27_Opposition — formation, leaders, union-management demand and suppression"]$q$::jsonb),

('united-opposition', 10151,
 $q$통합반대파$q$, $q$United Opposition$q$, $q$Объединённая оппозиция$q$, $q$1926–1927$q$,
 $q$1926–1927$q$, $q$1926–1927$q$, 1926, 1927, 'factions',
 $q$트로츠키의 좌익반대파와 지노비예프·카메네프의 신반대파가 1926년 결성한 당내 연합. 당내 민주주의 회복, 관료주의 비판, 공업화 가속과 국제혁명 노선을 요구하며 스탈린·부하린 다수파에 맞섰으나 1927년 지도자와 지지자들이 당에서 축출되면서 해체되었다.$q$,
 $q$The inner-party alliance formed in 1926 between Trotsky's Left Opposition and the New Opposition of Zinoviev and Kamenev. It challenged the Stalin-Bukharin majority with demands for restored party democracy, opposition to bureaucracy, faster industrialization and an international revolutionary line, but collapsed when its leaders and supporters were expelled in 1927.$q$,
 $q$["https://www.marxists.org/archive/trotsky/1927/opposition/index.htm — platform of the Joint Opposition", "https://www.encyclopedia.com/history/encyclopedias-almanacs-transcripts-and-maps/united-opposition — leadership, programme and defeat"]$q$::jsonb),

('1918-rsfsr-constitution', 10152,
 $q$1918년 러시아 소비에트 헌법$q$, $q$1918 Constitution of the Russian SFSR$q$,
 $q$Конституция РСФСР 1918 года$q$, $q$1918$q$,
 $q$1918년$q$, $q$1918$q$, 1918, 1918, 'party-state',
 $q$10월혁명 뒤 러시아 소비에트 연방 사회주의 공화국이 채택한 최초의 헌법. 「근로 피착취 인민의 권리 선언」을 헌법의 첫 부분으로 삼고 모든 권력이 노동자·병사·농민 소비에트에 속한다고 규정했으며, 이행기의 노동자·빈농 독재와 착취계급의 정치적 권리 제한을 명문화했다.$q$,
 $q$The first constitution of the Russian Soviet Federative Socialist Republic after the October Revolution. It incorporated the Declaration of Rights of the Working and Exploited People, vested power in workers', soldiers' and peasants' soviets, and formalized both a transitional dictatorship of workers and poor peasants and restrictions on the political rights of exploiting classes.$q$,
 $q$["https://www.constituteproject.org/constitution/Russia_1918 — full translated constitution, declaration, soviet power and transitional provisions", "https://www.marxists.org/history/ussr/government/constitution/1918/ — historical English text"]$q$::jsonb),

('developed-socialism', 10153,
 $q$발전된 사회주의$q$, $q$Developed Socialism$q$, $q$развитой социализм$q$, $q$1960년대 말–1980년대$q$,
 $q$1960년대 말–1980년대$q$, $q$late 1960s–1980s$q$, 1967, 1986, 'theory',
 $q$공산주의가 곧 도래한다는 흐루쇼프기의 공약을 뒤로 미루고 소련의 현 단계를 장기간 지속될 성숙한 사회주의로 규정한 브레즈네프 시기의 공식 이론. 계급 적대는 사라지고 노동자·농민·지식인이 가까워져 전인민적 국가가 성립했다고 설명했으며, 1977년 헌법의 이념적 토대가 되었다.$q$,
 $q$The official Brezhnev-era doctrine that retreated from Khrushchev's promise of imminent communism and defined the Soviet present as a long-lasting stage of mature socialism. It held that class antagonisms had disappeared, workers, peasants and intellectuals were converging, and an all-people's state had arisen; it supplied the ideological basis of the 1977 Constitution.$q$,
 $q$["https://www.encyclopedia.com/history/encyclopedias-almanacs-transcripts-and-maps/developed-socialism — origin, content and fate of the doctrine", "https://doaj.org/article/92bec24f88da48479424c05cafd1b10b — developed socialism as the ideological framework of the Brezhnev period"]$q$::jsonb),

('1977-soviet-constitution', 10154,
 $q$1977년 소련 헌법$q$, $q$1977 Constitution of the Soviet Union$q$,
 $q$Конституция СССР 1977 года$q$, $q$1977–1991$q$,
 $q$1977–1991$q$, $q$1977–1991$q$, 1977, 1991, 'party-state',
 $q$브레즈네프 시기 채택되어 소련 해체 때까지 효력을 지닌 소련의 마지막 헌법. 서문에서 ‘발전된 사회주의 사회’의 건설을 선언하고 국가를 전인민국가로 규정했으며, 제6조에서 소련공산당을 사회와 국가의 지도적·향도적 힘으로 명문화했다. 1988~1990년 개헌은 인민대의원대회와 대통령제를 도입하고 당의 독점적 지위를 폐지했다.$q$,
 $q$The Soviet Union's final constitution, adopted under Brezhnev and in force until the Union dissolved. Its preamble declared that a “developed socialist society” had been built, it defined the USSR as an all-people's state, and Article 6 enshrined the Communist Party as the leading and guiding force of society and the state. Amendments from 1988 to 1990 introduced the Congress of People's Deputies and presidency and removed the party's monopoly.$q$,
 $q$["https://www.marxists.org/history/ussr/government/constitution/1977/constitution-ussr-1977.pdf — full text, preamble and Article 6", "https://www.loc.gov/item/2018694225/ — Library of Congress record for the official English-language constitution"]$q$::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO commulingo_term_aliases (term_id, lang, alias, sort_order) VALUES
('zimmerwald-movement', 'ko', '치머발트 운동', 10),
('zimmerwald-movement', 'ko', '치머발트 좌파', 20),
('zimmerwald-movement', 'en', 'Zimmerwald movement', 10),
('zimmerwald-movement', 'en', 'Zimmerwald Left', 20),
('vienna-union', 'ko', '빈 국제연합', 10),
('vienna-union', 'ko', '2½ 인터내셔널', 20),
('vienna-union', 'ko', '제2.5인터내셔널', 30),
('vienna-union', 'en', 'Vienna Union', 10),
('vienna-union', 'en', 'Two-and-a-Half International', 20),
('anarcho-syndicalist-iwa', 'ko', '아나르코생디칼리슴 IWA', 10),
('anarcho-syndicalist-iwa', 'ko', '국제노동자협회 IWA', 20),
('anarcho-syndicalist-iwa', 'en', 'anarcho-syndicalist IWA', 10),
('anarcho-syndicalist-iwa', 'en', 'International Workers Association', 20),
('labour-and-socialist-international', 'ko', '노동사회주의 인터내셔널', 10),
('labour-and-socialist-international', 'ko', 'LSI', 20),
('labour-and-socialist-international', 'en', 'Labour and Socialist International', 10),
('socialist-international', 'ko', '사회주의 인터내셔널', 10),
('socialist-international', 'en', 'Socialist International', 10),
('fourth-international-splits', 'ko', '제4인터의 분열과 재통합', 10),
('fourth-international-splits', 'ko', '제4인터내셔널의 분열', 20),
('fourth-international-splits', 'en', 'Fourth International split', 10),
('fourth-international-splits', 'en', 'Fourth International reunification', 20),
('narodniks', 'ko', '나로드니키', 10),
('narodniks', 'ko', '인민주의자', 20),
('narodniks', 'en', 'Narodniks', 10),
('narodniks', 'en', 'Russian populists', 20),
('economism', 'ko', '경제주의', 10),
('economism', 'en', 'Economism', 10),
('rsdlp', 'ko', '러시아사회민주노동당', 10),
('rsdlp', 'ko', '러시아 사회민주노동당', 20),
('rsdlp', 'en', 'RSDLP', 10),
('rsdlp', 'en', 'Russian Social Democratic Labour Party', 20),
('menshevik-defencists-internationalists', 'ko', '멘셰비키 방위파', 10),
('menshevik-defencists-internationalists', 'ko', '멘셰비키 국제주의파', 20),
('menshevik-defencists-internationalists', 'en', 'Menshevik Defencists', 10),
('menshevik-defencists-internationalists', 'en', 'Menshevik Internationalists', 20),
('workers-opposition', 'ko', '노동자반대파', 10),
('workers-opposition', 'ko', '노동자 반대파', 20),
('workers-opposition', 'en', 'Workers'' Opposition', 10),
('united-opposition', 'ko', '통합반대파', 10),
('united-opposition', 'ko', '연합반대파', 20),
('united-opposition', 'en', 'United Opposition', 10),
('1918-rsfsr-constitution', 'ko', '1918년 헌법', 10),
('1918-rsfsr-constitution', 'ko', '1918년 러시아 헌법', 20),
('1918-rsfsr-constitution', 'en', '1918 Constitution', 10),
('1918-rsfsr-constitution', 'en', '1918 RSFSR Constitution', 20),
('developed-socialism', 'ko', '발전된 사회주의', 10),
('developed-socialism', 'ko', '발달한 사회주의', 20),
('developed-socialism', 'en', 'developed socialism', 10),
('developed-socialism', 'en', 'mature socialism', 20),
('1977-soviet-constitution', 'ko', '1977년 헌법', 10),
('1977-soviet-constitution', 'ko', '브레즈네프 헌법', 20),
('1977-soviet-constitution', 'en', '1977 Soviet Constitution', 10),
('1977-soviet-constitution', 'en', 'Brezhnev Constitution', 20)
ON CONFLICT DO NOTHING;

INSERT INTO commulingo_term_relations (term_id, related_id) VALUES
('vienna-union', 'labour-and-socialist-international'),
('labour-and-socialist-international', 'socialist-international'),
('fourth-international-splits', 'permanent-revolution'),
('economism', 'iskra'),
('rsdlp', 'democratic-centralism'),
('workers-opposition', 'democratic-centralism'),
('united-opposition', 'left-opposition'),
('united-opposition', 'right-opposition'),
('developed-socialism', 'all-peoples-state'),
('developed-socialism', '1977-soviet-constitution'),
('1977-soviet-constitution', 'all-peoples-state')
ON CONFLICT DO NOTHING;
