-- Full audit of people whose recorded death year is 1936–1941.
--
-- Add omitted Great Terror victims from the mass-operation years, the
-- 1939–40 aftershock (prison deaths, executions and overseas assassination),
-- and the 1941 wartime executions at Oryol/Medvedev Forest, Barbysh and in
-- the first purge of the wartime military command. Natural deaths, combat
-- deaths and executions unrelated to Soviet repression are intentionally
-- excluded.
--
-- A few NKVD officers were both perpetrators and later victims. As in
-- migration 054, the one-relation-per-person schema keeps those people under
-- `executor`, with the label "집행자이자 표적".

INSERT INTO commulingo_history_event_people
    (event_id, person_id, sort_order, relation_kind,
     relation_ko, relation_en, note_ko, note_en)
VALUES
('great-terror', 'grigory-evdokimov', 300, 'target', '제1차 모스크바 재판의 표적', 'Target of the First Moscow Trial',
 '지노비예프의 측근이자 신반대파 지도자로 몰려 1936년 제1차 모스크바 재판 뒤 처형되었다.',
 'A former Zinoviev ally and New Opposition leader, he was condemned in the First Moscow Trial and executed in 1936.'),
('great-terror', 'nestor-lakoba', 301, 'target', '숙청의 전조가 된 표적', 'A target in the purge''s prelude',
 '압하지야 지도자로 베리야와 충돌한 뒤 1936년 독살되었고, 사후 가족과 측근도 탄압받았다.',
 'The Abkhaz leader died by poisoning in 1936 after clashing with Beria; his family and associates were then repressed.'),

('great-terror', 'boris-eltsin', 302, 'target', '좌익반대파 표적', 'Left Opposition target',
 '좌익반대파 활동으로 유배와 정치격리소 수감을 거듭하다 1937년 처형되었다.',
 'Repeatedly exiled and imprisoned for Left Opposition activity, he was executed in 1937.'),
('great-terror', 'jakub-hanecki', 303, 'target', '고참 혁명가 표적', 'Old revolutionary targeted',
 '레닌의 지하 재정망을 운영한 폴란드계 혁명가로, 혁명박물관장 재임 중 체포되어 1937년 처형되었다.',
 'The Polish revolutionary who had run Lenin''s underground financial network was arrested while directing the Museum of the Revolution and executed in 1937.'),
('great-terror', 'alexander-krasnoshchyokov', 304, 'target', '경제 관료 표적', 'Economic official targeted',
 '극동공화국 초대 수반이자 네프기 산업금융 설계자였으나 1937년 체포·처형되었다.',
 'The first head of the Far Eastern Republic and an architect of NEP-era industrial finance was arrested and executed in 1937.'),
('great-terror', 'august-kork', 305, 'target', '군 지휘부 표적', 'Military command target',
 '프룬제 군사아카데미 교장이던 2급 군사령관으로, 투하쳅스키 사건에서 1937년 처형되었다.',
 'A second-rank army commander and head of the Frunze Military Academy, he was executed in the Tukhachevsky case in 1937.'),
('great-terror', 'nikolai-glebov-avilov', 306, 'target', '레닌그라드 반대파 표적', 'Leningrad opposition target',
 '초대 체신인민위원이자 레닌그라드 반대파 인사로 몰려 1937년 처형되었다.',
 'The first commissar of posts and telegraphs was targeted for his Leningrad opposition ties and executed in 1937.'),
('great-terror', 'vladimir-smirnov', 307, 'target', '민주중앙집권파 표적', 'Democratic Centralist target',
 '민주중앙집권파와 좌익반대파에서 당내 민주주의를 주장하다 1937년 처형되었다.',
 'A Democratic Centralist and Left Oppositionist who argued for inner-party democracy, he was executed in 1937.'),
('great-terror', 'ivan-akulov', 308, 'target', '검찰 관료 표적', 'Prosecutorial official targeted',
 '초대 소련 검찰총장으로 탄압 제도의 형성에 관여했으나, 자신도 1937년 그 기구에 의해 처형되었다.',
 'The first Soviet procurator general helped shape the repressive legal system but was himself executed by it in 1937.'),
('great-terror', 'moisei-kalmanovich', 309, 'target', '경제 관료 표적', 'Economic official targeted',
 '전 국가은행 총재이자 국영농장 인민위원으로 재직하다 체포되어 1937년 처형되었다.',
 'A former State Bank chairman and commissar for state farms, he was arrested and executed in 1937.'),
('great-terror', 'semyon-lobov', 310, 'target', '산업 관료 표적', 'Industrial official targeted',
 '임업인민위원으로 레닌 훈장을 받은 이듬해 체포되어 1937년 총살되었다.',
 'The forestry commissar was arrested the year after receiving the Order of Lenin and shot in 1937.'),
('great-terror', 'daniil-sulimov', 311, 'target', '공화국 정부 수반 표적', 'Republican government head targeted',
 'RSFSR 인민위원회의 의장으로 재임하다 1937년 중앙위 전원회의 직후 체포·처형되었다.',
 'The chairman of the Russian republic''s government was arrested after the June 1937 Central Committee plenum and executed.'),
('great-terror', 'stanislav-messing', 312, 'target', '보안기관 고참 표적', 'Security veteran targeted',
 '체카·OGPU 고위 간부에서 대외무역 관료로 밀려난 뒤 폴란드 간첩 혐의로 1937년 처형되었다.',
 'A former senior Cheka and OGPU officer later shifted to foreign trade, he was executed in 1937 as an alleged Polish spy.'),
('great-terror', 'vladimir-polonsky', 313, 'target', '당·노조 관료 표적', 'Party and union official targeted',
 '당 중앙 조직부장과 전연방 노동조합평의회 서기를 지낸 뒤 1937년 우익 조직 혐의로 처형되었다.',
 'A former Central Committee organization chief and trade-union secretary, he was executed in 1937 for an alleged Rightist organization.'),
('great-terror', 'vitaly-primakov', 314, 'target', '군 지휘부 표적', 'Military command target',
 '붉은 카자크 창설자이자 고위 기병 지휘관으로, 투하쳅스키 사건에서 1937년 처형되었다.',
 'Founder of the Red Cossacks and a senior cavalry commander, he was executed in the Tukhachevsky case in 1937.'),
('great-terror', 'ordzhonikidze', 315, 'target', '숙청 압박의 피해자', 'Victim of purge pressure',
 '대숙청이 중공업 간부와 친형을 덮치자 스탈린과 충돌했고 1937년 스스로 목숨을 끊었다.',
 'As the purge consumed industrial cadres and his brother, he clashed with Stalin and took his own life in 1937.'),
('great-terror', 'alexander-chervyakov', 316, 'target', '공화국 지도부 표적', 'Republican leadership target',
 '벨라루스 소비에트 공화국의 창립자이자 국가원수로, 1937년 숙청 압박 속에서 자결했다.',
 'A founder and head of Soviet Belarus, he died by suicide amid purge pressure in 1937.'),
('great-terror', 'andres-nin', 317, 'target', '해외 공작의 표적', 'Target of an overseas operation',
 '스페인 POUM 지도자로 1937년 공화파 비밀경찰에 납치되어 NKVD가 관여한 작전 속에서 살해되었다.',
 'The Spanish POUM leader was abducted by Republican security police and killed in a 1937 operation involving the NKVD.'),

('great-terror', 'alexander-smirnov', 318, 'target', '고참 볼셰비키 표적', 'Old Bolshevik targeted',
 '전 농업인민위원이자 중앙위 서기로, 반대파 연루 혐의 뒤 대숙청에서 1938년 처형되었다.',
 'A former agriculture commissar and Central Committee secretary, he was executed in 1938 after accusations of opposition activity.'),
('great-terror', 'pyotr-bogdanov', 319, 'target', '경제 관료 표적', 'Economic official targeted',
 '네프기 최고경제회의 의장과 암토르그 사장을 지낸 뒤 1937년 체포되어 1938년 처형되었다.',
 'A former head of the Supreme Economic Council and Amtorg, he was arrested in 1937 and executed in 1938.'),
('great-terror', 'aleksandr-serebrovsky', 320, 'target', '공업화 관료 표적', 'Industrialization official targeted',
 '석유·금 채굴 산업을 건설한 중공업 부인민위원으로, 1937년 체포되어 이듬해 처형되었다.',
 'The deputy heavy-industry commissar who built the oil and gold industries was arrested in 1937 and executed the next year.'),
('great-terror', 'boris-kamkov', 321, 'target', '좌파 사회혁명당 표적', 'Left SR target',
 '좌파 사회혁명당 공동 창립자로 오랜 투옥과 유배 끝에 1938년 처형되었다.',
 'A co-founder of the Left Socialist Revolutionaries, he was executed in 1938 after years of prison and exile.'),
('great-terror', 'semyon-dimanshtein', 322, 'target', '민족정책 관료 표적', 'Nationalities official targeted',
 '소비에트 유대인 민족정책의 핵심 설계자로 활동하다 1938년 체포·처형되었다.',
 'A principal architect of Soviet Jewish nationalities policy, he was arrested and executed in 1938.'),
('great-terror', 'vasily-shmidt', 323, 'target', '노동 관료 표적', 'Labour official targeted',
 '초기 소비에트 노동인민위원과 정부 부의장을 지낸 뒤 우익 편향 혐의로 숙청되어 1938년 처형되었다.',
 'A former labour commissar and deputy head of government, he was purged for alleged Rightist deviation and executed in 1938.'),
('great-terror', 'pyotr-koganovich', 324, 'target', '좌익반대파 표적', 'Left Opposition target',
 '좌익반대파 강령 서명자로 1937년 체포되어 1938년 군사법정에서 사형 선고 직후 처형되었다.',
 'A signatory of a Left Opposition platform, he was arrested in 1937 and executed immediately after sentencing in 1938.'),
('great-terror', 'volodymyr-zatonsky', 325, 'target', '우크라이나 지도부 표적', 'Ukrainian leadership target',
 '우크라이나 교육인민위원과 중앙위 서기를 지낸 뒤 1937년 체포되어 1938년 처형되었다.',
 'A Ukrainian education commissar and Central Committee secretary, he was arrested in 1937 and executed in 1938.'),
('great-terror', 'arkady-rozengolts', 326, 'target', '제3차 모스크바 재판의 표적', 'Target of the Third Moscow Trial',
 '전 대외무역인민위원으로 제3차 모스크바 재판에서 사형을 선고받고 1938년 처형되었다.',
 'The former foreign-trade commissar was condemned in the Third Moscow Trial and executed in 1938.'),
('great-terror', 'hryhoriy-hrynko', 327, 'target', '제3차 모스크바 재판의 표적', 'Target of the Third Moscow Trial',
 '소련 재무인민위원으로 제3차 모스크바 재판의 피고가 되어 1938년 처형되었다.',
 'The Soviet finance commissar was made a defendant in the Third Moscow Trial and executed in 1938.'),
('great-terror', 'vladislav-kosior', 328, 'target', '좌익반대파 표적', 'Left Opposition target',
 '민주중앙집권파와 좌익반대파에서 활동한 뒤 장기 수감 중 다시 기소되어 1938년 처형되었다.',
 'A Democratic Centralist and Left Oppositionist, he was re-prosecuted during imprisonment and executed in 1938.'),
('great-terror', 'nikolai-gorbunov', 329, 'target', '과학행정 관료 표적', 'Science administrator targeted',
 '레닌의 비서이자 과학아카데미 상임서기로 활동하다 1937년 체포되어 1938년 처형되었다.',
 'Lenin''s former secretary and a senior Academy of Sciences administrator, he was arrested in 1937 and executed in 1938.'),
('great-terror', 'eduard-berzin', 330, 'target', '수용소 관리자 표적', 'Camp administrator targeted',
 '달스트로이와 콜리마 수용소 체계를 세운 관리자였으나 1937년 체포되어 1938년 처형되었다.',
 'The administrator who built Dalstroy and the Kolyma camp system was arrested in 1937 and executed in 1938.'),
('great-terror', 'iosif-vareikis', 331, 'target', '지방 당 지도부 표적', 'Regional party leader targeted',
 '극동의 숙청과 한인 강제이주를 집행한 지방 당서기였으나 자신도 1937년 체포되어 이듬해 처형되었다.',
 'A regional party secretary who enforced purges and the Korean deportation in the Far East, he was himself arrested in 1937 and executed the next year.'),
('great-terror', 'lev-maryasin', 332, 'target', '금융 관료 표적', 'Financial official targeted',
 '전 고스방크 총재로 1936년 말 체포되어 고문을 겪은 뒤 1938년 총살되었다.',
 'The former State Bank chairman was arrested in late 1936, tortured and shot in 1938.'),
('great-terror', 'ivan-kutyakov', 333, 'target', '군 지휘부 표적', 'Military command target',
 '내전기 25소총병사단을 이끈 고위 지휘관으로 1937년 체포되어 1938년 처형되었다.',
 'The senior commander who had led the 25th Rifle Division in the civil war was arrested in 1937 and executed in 1938.'),
('great-terror', 'yakov-alksnis', 334, 'target', '군 지휘부 표적', 'Military command target',
 '붉은 군대 공군 사령관으로 투하쳅스키 재판에 참여한 뒤 자신도 체포되어 1938년 처형되었다.',
 'The Red Army air-force commander sat in judgment in the Tukhachevsky trial, then was himself arrested and executed in 1938.'),
('great-terror', 'georgy-langemak', 335, 'target', '과학기술자 표적', 'Scientist and engineer targeted',
 '카추샤 로켓탄의 기반을 만든 로켓연구소 수석기술자로, 허위 고발 뒤 1938년 처형되었다.',
 'The chief engineer whose work underlay the Katyusha rockets was executed in 1938 after a false denunciation.'),
('great-terror', 'pavel-mif', 336, 'target', '코민테른 관료 표적', 'Comintern official targeted',
 '코민테른의 중국 담당자이자 중국학자로 활동하다 대숙청에서 체포되어 1938년 처형되었다.',
 'A Comintern China specialist and scholar, he was arrested in the Great Terror and executed in 1938.'),
('great-terror', 'gennady-smirnov', 337, 'target', '계획 관료 표적', 'Planning official targeted',
 '고스플란 의장 재임 중 체포되어 반혁명 조직 혐의로 1938년 총살되었다.',
 'Arrested while serving as Gosplan chairman, he was shot in 1938 for an alleged counterrevolutionary organization.'),

('great-terror', 'carl-manner', 338, 'target', '수용소의 표적', 'Camp victim',
 '핀란드 공산당 공동 창립자이자 전 지도자로 1935년 체포되어 우흐타-페초라 수용소에서 1939년 옥사했다.',
 'A co-founder and former leader of the Finnish Communist Party, he was arrested in 1935 and died in the Ukhta-Pechora camp in 1939.'),
('great-terror', 'aleksei-gastev', 339, 'target', '노동과학자 표적', 'Labour scientist targeted',
 '중앙노동연구소를 세운 노동과학자이자 시인으로 1938년 체포되어 1939년 총살되었다.',
 'The labour scientist and poet who founded the Central Institute of Labour was arrested in 1938 and shot in 1939.'),
('great-terror', 'ivan-fedko', 340, 'target', '군 지휘부 표적', 'Military command target',
 '국방제1부인민위원까지 오른 고위 지휘관으로 1938년 체포되어 1939년 처형되었다.',
 'A senior commander who rose to first deputy defence commissar, he was arrested in 1938 and executed in 1939.'),
('great-terror', 'semyon-gendin', 341, 'target', '정보기관 지휘부 표적', 'Intelligence command target',
 'GRU 국장 대리로 재직하다 1938년 체포되어 1939년 처형되었다.',
 'Serving as acting head of military intelligence, he was arrested in 1938 and executed in 1939.'),
('great-terror', 'trotsky', 342, 'target', '해외 암살의 표적', 'Target of overseas assassination',
 '추방 뒤에도 좌익반대파와 제4인터내셔널을 이끌다가 스탈린의 지시를 받은 자객에게 1940년 멕시코에서 암살되었다.',
 'He led the Left Opposition and Fourth International in exile until an assassin acting on Stalin''s orders killed him in Mexico in 1940.'),
('great-terror', 'vladimir-groman', 343, 'target', '수용소의 표적', 'Camp victim',
 '1930년 체포되어 멘셰비키 재판에서 10년형을 선고받고 1940년 수즈달 수용소에서 옥사했다.',
 'Arrested in 1930 and sentenced to ten years in the Menshevik Trial, he died in the Suzdal prison in 1940.'),

('great-terror', 'filipp-goloshchyokin', 344, 'target', '후속 처형의 표적', 'Target of a later execution',
 '카자흐스탄 전 당서기로 1939년 체포되어 독소전 발발 뒤인 1941년 총살되었다.',
 'The former Kazakhstan party secretary was arrested in 1939 and shot after the German invasion in 1941.'),
('great-terror', 'mikhail-kedrov', 345, 'target', '전시 비사법 처형의 표적', 'Target of wartime extrajudicial execution',
 '1939년 체포 뒤 무죄 판결을 받았으나 석방되지 않았고 1941년 베리야의 지시로 사라토프에서 총살되었다.',
 'Arrested in 1939 and acquitted but not released, he was shot at Saratov on Beria''s order in 1941.'),
('great-terror', 'maria-spiridonova', 346, 'target', '메드베데프 숲 처형의 표적', 'Target of the Medvedev Forest execution',
 '1937년 다시 체포되어 장기형을 복역하다 독일군 접근을 구실로 1941년 오룔의 메드베데프 숲에서 처형되었다.',
 'Rearrested in 1937 and serving a long sentence, she was executed at Medvedev Forest near Oryol as German forces approached in 1941.'),
('great-terror', 'dmitry-pavlov', 347, 'target', '전쟁 초기 군 지휘부 표적', 'Wartime military command target',
 '독소전 초 서부전선 붕괴의 책임을 뒤집어쓰고 체포되어 1941년 7월 처형되었다.',
 'Blamed for the collapse of the Western Front after the German invasion, he was arrested and executed in July 1941.'),
('great-terror', 'grigory-shtern', 348, 'target', '전시 비사법 처형의 표적', 'Target of wartime extrajudicial execution',
 '극동전선 사령관과 방공총국장을 지낸 소비에트연방영웅으로, 1941년 체포되어 재판 없이 총살되었다.',
 'A Hero of the Soviet Union and former Far Eastern Front and air-defence commander, he was arrested and shot without trial in 1941.'),
('great-terror', 'ivan-proskurov', 349, 'target', '전시 비사법 처형의 표적', 'Target of wartime extrajudicial execution',
 '전 GRU 국장으로 독일 침공을 경고한 뒤 실각했고, 1941년 체포되어 10월 28일 재판 없이 총살되었다.',
 'The former military-intelligence chief who had warned of German invasion was arrested and shot without trial on 28 October 1941.'),
('great-terror', 'pavel-rychagov', 350, 'target', '전시 비사법 처형의 표적', 'Target of wartime extrajudicial execution',
 '전 공군 총국장으로 항공 사고 책임을 둘러싸고 실각한 뒤 1941년 체포되어 10월 28일 재판 없이 총살되었다.',
 'The former air-force chief fell over aviation losses, was arrested in 1941 and shot without trial on 28 October.'),
('great-terror', 'yuri-steklov', 351, 'target', '수감 중 사망한 표적', 'Target who died in custody',
 '1938년 체포된 언론인·헌법 기초자로, 1941년 사라토프 감옥에서 사망했다.',
 'The journalist and constitutional drafter was arrested in 1938 and died in Saratov prison in 1941.'),
('great-terror', 'mikhail-kaganovich', 352, 'target', '전쟁 초기 숙청 압박의 피해자', 'Victim of early-wartime purge pressure',
 '전 항공공업인민위원으로 전쟁 초기 고문 자백에 연루되어 추궁받던 중 1941년 스스로 목숨을 끊었다.',
 'The former aviation-industry commissar took his own life in 1941 after being implicated by coerced testimony early in the war.'),

('great-terror', 'boris-berman', 353, 'executor', '집행자이자 표적', 'Enforcer turned target',
 '벨라루스 NKVD 수장으로 대량 체포와 쿠라파티 처형을 지휘한 뒤 1938년 체포되어 1939년 처형되었다.',
 'The Belarus NKVD chief directed mass arrests and the Kurapaty executions, then was arrested in 1938 and executed in 1939.'),
('great-terror', 'isaak-shapiro', 354, 'executor', '집행자이자 표적', 'Enforcer turned target',
 '예조프 비서실과 NKVD 작전 기록을 관리한 뒤 예조프 몰락과 함께 체포되어 1940년 처형되었다.',
 'He managed Yezhov''s secretariat and NKVD operational records, then was arrested in Yezhov''s fall and executed in 1940.'),
('great-terror', 'sergei-shpigelglas', 355, 'executor', '집행자이자 표적', 'Enforcer turned target',
 'NKVD 대외정보 국장 대행으로 해외 납치·암살을 지휘한 뒤 1938년 체포되어 1940년 처형되었다.',
 'The acting foreign-intelligence chief directed overseas kidnappings and assassinations, then was arrested in 1938 and executed in 1940.'),
('great-terror', 'zalman-passov', 356, 'executor', '집행자이자 표적', 'Enforcer turned target',
 '폴란드 작전과 NKVD 방첩을 지휘한 뒤 예조프 체제 숙청에서 체포되어 1940년 처형되었다.',
 'He directed counterintelligence work in the Polish Operation, then was arrested in the purge of Yezhov''s apparatus and executed in 1940.')
ON CONFLICT (event_id, person_id) DO NOTHING;
