// Hungary on the Axis side, 1938 – March 1944 (Hungary 1919–1944 batch, 2026-10-01).
// Exports { event, people, terms } built with ./lib.js.
const { W, HU, P, event: buildEvent, person, term } = require('./lib');

const E = t => W(encodeURI(t));
const H = t => HU(encodeURI(t));
const USHMM = 'https://encyclopedia.ushmm.org/content/en/article/hungary-before-the-german-occupation';
const S = {
    hww2: E('Hungary_in_World_War_II'),
    imredy: E('Béla_Imrédy'),
    huImredy: H('Imrédy_Béla'),
    holo: E('The_Holocaust_in_Hungary'),
    ushmm: USHMM,
    ushmmKp: 'https://encyclopedia.ushmm.org/content/en/article/kamenets-podolsk',
    v1: E('First_Vienna_Award'),
    cu: E('Carpatho-Ukraine'),
    slovakWar: E('Slovak–Hungarian_War'),
    v2: E('Second_Vienna_Award'),
    tri: E('Tripartite_Pact'),
    teleki: E('Pál_Teleki'),
    bardossy: E('László_Bárdossy'),
    kassa: E('Bombing_of_Kassa'),
    kp: E('Kamianets-Podilskyi_massacre'),
    novisad: E('Novi_Sad_raid'),
    huNovisad: H('Újvidéki_vérengzés_(1942)'),
    labour: E('Labour_service_in_Hungary_during_World_War_II'),
    huLabour: H('Munkaszolgálat'),
    army2: E('Second_Army_(Hungary)'),
    huDon: H('Magyar_2._hadsereg'),
    huJany: H('Jány_Gusztáv'),
    jany: E('Gusztáv_Jány'),
    vk: E('Voronezh–Kharkov_offensive'),
    kallay: E('Miklós_Kállay'),
    marg: E('German_invasion_of_Hungary_(1944)'),
    hcp: E('Hungarian_Communist_Party'),
    huSchonherz: H('Schönherz_Zoltán'),
    huRozsa: H('Rózsa_Ferenc_(politikus)'),
    rozsa: E('Ferenc_Rózsa'),
    kadar: E('János_Kádár'),
    huBp: H('Békepárt_(1943)'),
    rakosi: E('Mátyás_Rákosi'),
    bajcsy: E('Endre_Bajcsy-Zsilinszky'),
};

const sections = [
    {
        heading: { ko: '우경화와 제1·2차 유대인법 (1938–1939)', en: 'The turn to the right and the First and Second Jewish Laws (1938–1939)' },
        paragraphs: [
            {
                ko: '대공황과 트리아농 조약의 상처 속에서 헝가리 정치는 1930년대 내내 오른쪽으로 기울었다. 1934년 독일과의 무역협정으로 경제가 독일에 묶였고, 1935년 살러시 페렌츠가 세운 극우 정당은 뒤에 화살십자당이 되었다. 1938년 헝가리는 트리아농 조약의 군비 제한을 공개적으로 거부했다. 굄뵈시의 후임 총리 더라니 칼만은 나치와 국내 반유대주의자를 함께 달래려고 제1차 유대인법을 내놓았고, 법은 1938년 5월 통과되어 사무직 전문직과 상공업에서 유대인의 비율을 20%로 제한했다.',
                en: 'Amid the Depression and the wound of Trianon, Hungarian politics moved steadily to the right in the 1930s. A 1934 trade agreement tied the economy to Germany, and the far-right party Ferenc Szálasi founded in 1935 grew into the Arrow Cross. In 1938 Hungary openly repudiated Trianon’s limits on its armed forces. Gömbös’s successor as prime minister, Kálmán Darányi, tried to appease both the Nazis and Hungarian antisemites with the First Jewish Law, passed in May 1938, which capped the share of Jews in the white-collar professions and in business and industry at 20 per cent.',
                sources: [S.hww2, S.ushmm],
            },
            {
                ko: '1938년 5월 더라니가 물러나자 호르티는 국립은행 총재 출신의 임레디 벨러를 총리로 임명했다. 처음에 영국과의 관계를 중시하던 임레디는 3월 독일의 오스트리아 병합을 보고 그해 가을부터 외교를 독일·이탈리아 쪽으로 돌렸다. 그는 「기적의 혁명」을 내걸고 의회에서 벗어난 독재적 개편을 주장했으며, 1938년 12월 더 가혹한 제2차 유대인법안을 제출했다. 1939년 2월 베틀렌 이슈트반 등 정적들이 그의 외가 쪽 유대계 조상을 밝혀내자 임레디는 자신의 유대인 정책에 걸려 사임했다.',
                en: 'When Darányi stepped down in May 1938, Horthy appointed Béla Imrédy, a former president of the National Bank, as prime minister. Imrédy had at first valued relations with Britain, but after the German annexation of Austria in March he turned his foreign policy towards Germany and Italy from the autumn of 1938. Proclaiming a “miraculous revolution”, he pressed for a dictatorial reorganisation free of parliament, and in December 1938 he introduced a harsher Second Jewish Law. In February 1939 opponents including István Bethlen uncovered Jewish ancestry on his mother’s side, and Imrédy, caught by his own Jewish policy, resigned.',
                sources: [S.imredy, S.huImredy, S.hww2],
            },
            {
                ko: '후임 텔레키 팔 정부는 1939년 5월 제2차 유대인법을 통과시켰다. 이 법은 처음으로 유대인을 인종으로 정의해 조부모 가운데 둘 이상이 유대인으로 태어난 사람을 유대인으로 보았고, 기독교로 개종한 사람들의 지위도 바꾸었다. 전문직과 배우 직업의 유대인 비율은 6%, 민간 기업의 고용은 12%로 제한되었고 공직 취업과 신문 편집이 금지되었다. 약 25만 명의 헝가리 유대인이 생계를 잃었고, 많은 유대인이 투표권을 잃었다.',
                en: 'Imrédy’s successor, Pál Teleki, carried the Second Jewish Law through in May 1939. For the first time it defined Jews by race — anyone with two or more grandparents born Jewish counted as a Jew — and so changed the status of converts to Christianity. Jews were limited to 6 per cent in the professions and among actors and to 12 per cent of private company staff, and barred from public employment and from editing newspapers. Some 250,000 Hungarian Jews lost their livelihood, and many lost the vote.',
                sources: [S.hww2, S.holo, S.ushmm],
            },
        ],
    },
    {
        heading: { ko: '빈 중재와 영토 확장 (1938–1940)', en: 'The Vienna Awards and territorial expansion (1938–1940)' },
        paragraphs: [
            {
                ko: '1938년 9월 뮌헨 협정으로 체코슬로바키아가 약해지자 헝가리는 헝가리인이 사는 남부 슬로바키아와 남부 루테니아를 요구했다. 10월 초 비정규 「누더기 근위대」가 국경을 넘어 들어갔고 협상은 교착되었다. 독일과 이탈리아의 외무장관 리벤트로프와 치아노는 11월 2일 빈 벨베데레 궁에서 제1차 빈 중재를 내려 약 1만 1900㎢, 인구 약 87만 명(86.5%가 헝가리인)의 땅을 헝가리에 넘겼고, 헝가리군은 11월 5~10일 이 지역에 들어갔다. 코시체(헝가리어 커셔)도 이때 헝가리 땅이 되었다.',
                en: 'When the Munich Agreement of September 1938 weakened Czechoslovakia, Hungary claimed the Magyar-populated south of Slovakia and of Ruthenia. In early October irregulars of the “Ragged Guard” crossed the border, and talks deadlocked. On 2 November the German and Italian foreign ministers, Ribbentrop and Ciano, delivered the First Vienna Award at the Belvedere Palace in Vienna, transferring to Hungary about 11,900 km² with some 870,000 inhabitants, 86.5 per cent of them Hungarians; Hungarian troops marched in between 5 and 10 November. Košice — Kassa to Hungarians — became Hungarian with them.',
                sources: [S.hww2, S.v1, S.huImredy, S.slovakWar],
            },
            {
                ko: '1939년 3월 체코슬로바키아가 해체되자 15일 카르파티아 우크라이나가 아우후스틴 볼로신을 대통령으로 독립을 선언했지만, 히틀러의 승인을 받은 헝가리군은 3월 14~18일 나머지 루테니아를 점령해 저항을 꺾고 폴란드와의 옛 국경을 되찾았다. 헝가리는 독일의 보호국이 된 티소의 슬로바키아는 승인했지만, 3월 23일 국경 분쟁을 이유로 동부 슬로바키아를 공격했다. 31일까지 이어진 「작은 전쟁」으로 헝가리는 동쪽 끝 띠 모양의 땅 1697㎢를 더 얻었다.',
                en: 'When Czechoslovakia broke up in March 1939, Carpatho-Ukraine declared independence on 15 March under President Avgustyn Voloshyn, but Hungarian troops, with Hitler’s permission, occupied the rest of Ruthenia between 14 and 18 March, crushed resistance and restored the old common border with Poland. Hungary recognised Tiso’s Slovakia, a German protégé, yet on 23 March attacked eastern Slovakia over a border dispute; the “Little War”, which lasted until the 31st, gained Hungary a further strip of 1,697 km² at the eastern end.',
                sources: [S.cu, S.v1, S.slovakWar, S.hww2],
            },
            {
                ko: '1940년 6월 루마니아가 소련의 최후통첩에 베사라비아와 북부 부코비나를 내주자 헝가리는 트란실바니아 요구를 밀어붙였다. 8월 협상이 결렬되고 양국 군대가 국경에 집결하자 독일과 이탈리아가 다시 중재에 나섰고, 8월 30일 리벤트로프와 치아노는 제2차 빈 중재로 북부 트란실바니아 4만 3492㎢를 헝가리에 넘겼다. 주민 구성은 다툼거리였다. 1930년 루마니아 인구조사는 헝가리인 38%, 루마니아인 49%로, 1941년 헝가리 인구조사는 헝가리인 53.5%, 루마니아인 39.1%로 셌다. 9월 진주 과정에서 헝가리군은 이프와 트레즈네아 마을에서 루마니아 주민을 학살했다.',
                en: 'When Romania yielded Bessarabia and northern Bukovina to a Soviet ultimatum in June 1940, Hungary pressed its claim to Transylvania. After talks broke down in August and both armies massed on the border, Germany and Italy again arbitrated: on 30 August Ribbentrop and Ciano’s Second Vienna Award gave Hungary the 43,492 km² of Northern Transylvania. Its ethnic make-up was disputed — the Romanian census of 1930 counted 38 per cent Hungarians and 49 per cent Romanians, the Hungarian census of 1941 53.5 and 39.1 per cent. As they marched in during September, Hungarian troops massacred Romanian villagers at Ip and Treznea.',
                sources: [S.v2, S.hww2],
            },
        ],
    },
    {
        heading: { ko: '삼국동맹, 「영원한 우호」, 텔레키의 자살 (1940–1941)', en: 'The Tripartite Pact, “eternal friendship” and Teleki’s suicide (1940–1941)' },
        paragraphs: [
            {
                ko: '1940년 9월 독일·이탈리아·일본이 삼국동맹을 맺자 베를린 주재 대사 스토여이 되메는 루마니아보다 먼저 가입해야 한다고 재촉했고, 호르티는 헝가리가 첫 번째 신규 가입국이 되기를 바랐다. 헝가리는 1940년 11월 20일 독일의 압력 속에 텔레키 총리의 서명으로 삼국동맹에 가입했다. 같은 해 12월 텔레키는 섭정 파벨 공의 유고슬라비아와 「영원한 우호」 조약을 맺었다. 텔레키는 독일과 협력해 영토를 되찾으면서도 전쟁에는 휘말리지 않으려 했고, 1939년 폴란드 침공 때도 헝가리가 폴란드를 칠 수 없다고 히틀러에게 썼다.',
                en: 'When Germany, Italy and Japan signed the Tripartite Pact in September 1940, the minister in Berlin, Döme Sztójay, urged that Hungary join before Romania did, and Horthy wanted Hungary to be the first new member. On 20 November 1940, under German pressure, Prime Minister Teleki signed Hungary’s accession. In December Teleki also concluded a treaty of “eternal friendship” with Prince Paul’s Yugoslavia. Teleki sought to regain territory in co-operation with Germany while staying out of the war; in 1939 he had written to Hitler that Hungary could not on moral grounds take armed action against Poland.',
                sources: [S.tri, S.hww2, S.teleki],
            },
            {
                ko: '1941년 3월 27일 베오그라드 쿠데타로 유고슬라비아가 삼국동맹 가입을 뒤집자 히틀러는 유고슬라비아 침공에 헝가리의 참여를 요구하며 영토를 약속했고, 호르티는 곧바로 받아들였다. 국방장관 버르터 카로이와 참모총장 베르트 헨리크는 기회를 놓치지 말라고 다그쳤다. 4월 3일 런던의 헝가리 공사는 영국이 독일군 통과를 허용하면 단교하고 유고슬라비아를 공격하면 선전포고하겠다고 경고했다고 알려 왔다. 그날 자정 무렵 독일군이 헝가리로 들어오기 시작했다는 소식으로 보이는 전화를 받은 텔레키는 밤사이 권총으로 목숨을 끊었다. 유서에는 「우리는 비겁함 때문에 약속을 깼다… 악당들과 동맹을 맺었다… 나는 당신을 막지 못했다. 내 죄다」라고 적혀 있었다.',
                en: 'When a coup in Belgrade on 27 March 1941 reversed Yugoslavia’s accession to the pact, Hitler demanded Hungarian participation in an invasion of Yugoslavia in return for territory, and Horthy accepted at once; Defence Minister Károly Bartha and Chief of Staff Henrik Werth urged him not to miss the chance. On 3 April the minister in London reported that Britain would break off relations if German troops were allowed through and declare war if Hungary attacked Yugoslavia. That night, after a call thought to have told him that the German army had begun its march into Hungary, Teleki shot himself. His note read: “We broke our word, – out of cowardice … We have allied ourselves to scoundrels … I did not hold you back. I am guilty.”',
                sources: [S.teleki, S.hww2],
            },
            {
                ko: '후임 총리는 외무장관 바르도시 라슬로였다. 독일이 4월 6일 유고슬라비아를 침공하고 10일 크로아티아 독립국이 선포되자, 헝가리 정부는 유고슬라비아가 더는 존재하지 않는다는 구실로 11일 국경을 넘었다. 헝가리군은 바치카·바라냐·메지무르예·프레크무리예를 차지했고, 이 1만 1417㎢의 「남부 회복 지역」은 1941년 12월 정식으로 병합되었다. 영국 외무장관 이든은 우호조약을 맺은 지 몇 달 만에 유고슬라비아를 공격한 것이 헝가리 명예의 「영원한 수치」로 남으리라고 말했다.',
                en: 'The new prime minister was the foreign minister, László Bárdossy. After Germany invaded Yugoslavia on 6 April and the Independent State of Croatia was proclaimed on the 10th, the Hungarian government crossed the frontier on the 11th on the pretext that Yugoslavia had ceased to exist. Hungarian troops took Bačka, Baranja, Međimurje and Prekmurje, and these 11,417 km² of “Recovered Southern Territories” were formally annexed in December 1941. The British foreign secretary, Eden, said it would remain an “everlasting shame” on Hungary’s reputation that it had attacked Yugoslavia months after a pact of friendship.',
                sources: [S.bardossy, S.hww2, S.novisad],
            },
        ],
    },
    {
        heading: { ko: '커셔 폭격과 대소련 참전 (1941)', en: 'The bombing of Kassa and war on the Soviet Union (1941)' },
        paragraphs: [
            {
                ko: '1941년 6월 22일 독일이 소련을 침공했을 때 히틀러는 헝가리에 참전을 요청하지 않았다. 그러나 베르트와 버르터는 참전하면 히틀러가 트리아농으로 잃은 땅 전부를 돌려줄 것이고 전쟁은 6주면 끝난다고 주장했다. 6월 23일 몰로토프는 헝가리 공사에게 헝가리가 중립을 지키면 루마니아에 대한 헝가리의 요구를 반대하지 않겠다고 전했지만, 바르도시는 이 전보를 각료회의에 알리지 않았다. 6월 26일 정체불명의 비행기가 커셔(코시체)를 폭격했다.',
                en: 'When Germany invaded the Soviet Union on 22 June 1941, Hitler did not ask Hungary to take part. Werth and Bartha, however, argued that Hitler would reward participation by restoring all the lands lost at Trianon and that the war would be over in six weeks. On 23 June Molotov told the Hungarian minister in Moscow that the Soviet Union would not object to Hungarian claims against Romania if Hungary stayed neutral, but Bárdossy did not pass the telegram on to the cabinet. On 26 June unidentified aircraft bombed Kassa (Košice).',
                sources: [S.kassa, S.hww2],
            },
            {
                ko: '헝가리 군부는 터지지 않은 폭탄 하나가 소련제라며 소련의 소행으로 단정했다. 호르티는 보복을 명령했고, 바르도시는 6월 27일 의회에 나가 헝가리와 소련 사이에 전쟁 상태가 존재한다고 선언했다. 선전포고에 의회의 동의를 받도록 한 헌법 절차는 지켜지지 않았다. 범인은 지금도 밝혀지지 않았다. 호르티는 회고록에서 독일의 조작이라고 주장했고, 체코슬로바키아·슬로바키아·루마니아 비행기설도 나왔다. 역사가 롬시치 이그나츠는 프레쇼우를 노린 소련 폭격기의 오폭이 가장 그럴듯하다고 보면서, 지도부가 폭격을 위협으로 본 것은 「그렇게 보고 싶었기 때문」이라고 썼다.',
                en: 'The Hungarian military, citing an unexploded bomb of Soviet make, blamed the Soviet Union. Horthy ordered retaliation, and on 27 June Bárdossy told parliament that a state of war existed between Hungary and the Soviet Union — without the parliamentary consent the constitution required for a declaration of war. Responsibility has never been settled: Horthy’s memoirs called it a German provocation, and Czechoslovak, Slovak and Romanian aircraft have all been suggested. The historian Ignác Romsics thought a Soviet bomber aiming at Prešov the likeliest culprit, and wrote that Hungary’s leaders saw the raid as a threat “because they wanted to view it as such”.',
                sources: [S.bardossy, S.kassa],
            },
            {
                ko: '7월 1일 헝가리의 카르파티아 집단이 독일 제17군 휘하로 소련 우크라이나에 들어갔고, 그 기동군단은 8월 우만 포위전에 참가했다. 1941년 말 영국은 헝가리군이 소련에서 철수하지 않으면 선전포고하겠다고 통첩했고 12월 6일 전쟁 상태가 시작되었다. 진주만 공격 뒤 바르도시는 미국과 단교했고, 12월 15일 미국과도 전쟁 상태에 있다고 발표했다. 반년 사이에 헝가리는 유고슬라비아·소련·영국·미국과 전쟁을 하는 나라가 되었다.',
                en: 'On 1 July the Hungarian Carpathian Group advanced into Soviet Ukraine under the German Seventeenth Army, and its mechanised corps fought in the encirclement at Uman in August. In late 1941 Britain warned that it would declare war unless Hungarian forces left the Soviet Union, and a state of war began on 6 December. After Pearl Harbor Bárdossy broke off relations with the United States and on 15 December announced a state of war with it too. Within half a year Hungary was at war with Yugoslavia, the Soviet Union, Britain and the United States.',
                sources: [S.hww2, S.bardossy],
            },
        ],
    },
    {
        heading: { ko: '카미야네츠포딜스키, 노비사드, 노동봉사 (1941–1942)', en: 'Kamianets-Podilskyi, Novi Sad and labour service (1941–1942)' },
        paragraphs: [
            {
                ko: '참전 직후 외국인 관리 당국은 「부적합한 외국인」 유대인을 추방하기로 했다. 대상은 주로 폴란드·러시아 출신과 서유럽 난민이었지만, 시민권을 증명하지 못한 헝가리 유대인도 끌려갔고 카르파티아 지역에서는 공동체 전체가 추방되기도 했다. 바르도시는 7월 12일 추방 명령에 서명했다. 화물열차로 쾨뢰시메죄까지 실려 간 유대인은 옛 국경 너머 독일군에 넘겨졌고, 8월 10일까지 약 1만 4000명, 그달 하순 4000명이 더 보내졌다. 미국 홀로코스트 기념관은 추방된 사람을 2만 명 이상으로 본다.',
                en: 'Soon after Hungary entered the war, the agency in charge of foreign nationals decided to deport “unsuitable alien” Jews — mostly Polish and Russian Jews and refugees from western Europe, but also Hungarian Jews who could not document their citizenship, and in the Carpathian region whole communities. Bárdossy signed the deportation order on 12 July. Taken by freight train to Kőrösmező, the Jews were handed over to the Germans beyond the old frontier: about 14,000 by 10 August and 4,000 more later that month. The United States Holocaust Memorial Museum puts the number deported at more than 20,000.',
                sources: [S.kp, S.ushmmKp, S.ushmm, S.bardossy],
            },
            {
                ko: '이들은 콜로미야에서 카미야네츠포딜스키까지 걸어서 끌려갔고, 8월 27~28일(미국 홀로코스트 기념관은 26~28일) 프리드리히 예켈른 휘하의 친위대·경찰 부대와 현지 우크라이나 협력자들이 추방자와 현지 유대인을 쏘아 죽였다. 예켈른의 보고에 따르면 희생자는 2만 3600명이었고 그 가운데 약 1만 6000명이 헝가리에서 추방된 사람이었다(미국 홀로코스트 기념관은 카미야네츠포딜스키로 끌려간 추방자를 1만 4000~1만 6000명으로 본다). 「최종 해결」의 첫 대규모 학살 가운데 하나였다. 부다페스트 주재 미국 공사 허버트 펠이 거듭 항의했지만 바르도시는 학살이 없다고 거짓말했다. 바르도시 정부는 1941년 8월 유대인과 비유대인의 결혼과 성관계를 금지한 제3차 유대인법을 공포했다.',
                en: 'They were marched from Kolomyia to Kamianets-Podilskyi, where on 27–28 August (26–28 August according to the US Holocaust Memorial Museum) SS and police units under Friedrich Jeckeln and local Ukrainian collaborators shot the deportees together with the local Jews. Jeckeln reported 23,600 victims, some 16,000 of them deported from Hungary (the Museum puts the deportees taken to Kamianets-Podilskyi at 14,000–16,000) — one of the first large-scale massacres of the “Final Solution”. The American minister in Budapest, Herbert Pell, protested repeatedly, but Bárdossy lied that there had been no massacre. In August 1941 his government enacted the Third Jewish Law, which banned marriage and sexual relations between Jews and non-Jews.',
                sources: [S.kp, S.ushmmKp, S.ushmm, S.bardossy],
            },
            {
                ko: '병합된 바치카에서는 1941년 하반기 소규모 무장 저항이 일어났다. 1942년 1월 초 파르티잔과의 교전을 구실로 참모총장 솜버테이이 페렌츠가 징벌 작전을 명령했다. 마침 카이텔이 헝가리군 전체의 동부전선 파견을 요구하러 부다페스트에 와 있었고, 바르도시는 점령지에 군대가 필요하다는 것을 보여 주려 했다. 1월 6일 추루그에서 시작된 습격은 20~23일 노비사드(우이비데크)에서 절정에 이르렀다. 페케테헐미체이드네르 페렌츠의 부대는 영하 29도의 날씨에 주민을 도나우강 강변으로 끌고 가 기관총으로 쏘고 얼음을 깨 시신을 던졌다. 희생자는 연구에 따라 약 3300명에서 4116명이며, 대부분 세르비아인과 유대인이었다.',
                en: 'In annexed Bačka small-scale armed resistance broke out in the second half of 1941. In early January 1942, taking a clash with Partisans as pretext, Chief of Staff Ferenc Szombathelyi ordered punitive raids. Keitel was then in Budapest to demand the whole Hungarian army for the Eastern Front, and Bárdossy wanted to show that troops were needed in the occupied lands. Beginning at Čurug on 6 January, the raids culminated in Novi Sad (Újvidék) on 20–23 January, where Ferenc Feketehalmy-Czeydner’s troops marched residents to the Danube bank in −29 °C, machine-gunned them and broke the ice to throw in the bodies. Estimates of the dead run from about 3,300 to 4,116, mostly Serbs and Jews.',
                sources: [S.novisad, S.huNovisad, S.ushmm],
            },
            {
                ko: '유대인 남성은 정규군 대신 노동봉사(munkaszolgálat)로 징집되었다. 1939년 국방법에 근거해 텔레키 정부가 만든 이 제도는 처음에는 「믿을 수 없는」 자들의 비무장 노동이었지만, 1941년 봄부터 유대인을 따로 분리해 제복 대신 표식 완장을 채우는 반유대주의 제도로 바뀌었다. 1941년 여름부터 수만 명이 우크라이나 전선 근처로 보내져 지뢰 제거와 중노동에 내몰렸고, 굶주림과 감독관의 학대로 많은 사람이 죽었다. 미국 홀로코스트 기념관은 약 10만 명이 동원되어 1944년 3월 이전에 2만 5000~4만 2000명이 죽었다고 추산한다.',
                en: 'Jewish men were conscripted not into the army but into labour service (munkaszolgálat). Created by the Teleki government under the 1939 defence act, it began as unarmed labour for the “unreliable”, but from spring 1941 Jews were segregated, denied uniforms and made to wear identifying armbands. From summer 1941 tens of thousands were sent near the front in Ukraine to clear mines and do heavy labour, and many died of hunger and abuse by their guards. The US Holocaust Memorial Museum estimates that about 100,000 men were conscripted and that 25,000–42,000 died before March 1944.',
                sources: [S.labour, S.huLabour, S.ushmm],
            },
        ],
    },
    {
        heading: { ko: '돈강의 제2군 (1942–1943)', en: 'The Second Army on the Don (1942–1943)' },
        paragraphs: [
            {
                ko: '모스크바 앞에서 실패한 독일은 1941년 말 동맹국에 더 많은 병력을 요구했다. 히틀러는 1941년 12월 말 호르티·무솔리니·안토네스쿠에게 편지를 보냈고, 1942년 1월 카이텔이 부다페스트에 왔다. 그 결과 야니 구스타브가 지휘하는 제2군이 동부전선으로 갔다. 20만 9000명 규모의 제2군은 4월 11일 남부 집단군에 배속되어 4월 17일부터 6월 27일까지 822편의 열차로 이동했다. 나라의 「현대적」 장비를 거의 다 모았는데도 기동 수단과 대전차 무기가 모자랐고, 독일이 약속한 장비는 오지 않았다.',
                en: 'Having failed before Moscow, Germany demanded more troops from its allies at the end of 1941: Hitler wrote to Horthy, Mussolini and Antonescu in late December, and Keitel came to Budapest in January 1942. The result was the despatch of the Second Army under Gusztáv Jány. The 209,000-strong army was assigned to Army Group South on 11 April and moved east from 17 April to 27 June in 822 trains. Although it received nearly all the country’s “modern” equipment, it lacked motor transport and anti-tank weapons, and the equipment Germany promised never came.',
                sources: [S.huDon, S.army2, S.huJany],
            },
            {
                ko: '1942년 여름 청색 작전에서 제2군은 보로네시 부근 돈강까지 진출했다. 강 서안에 남은 우리우·코로토야크·슈추치예의 소련 교두보를 없애려는 공격은 거듭 실패했고, 1942년 한 해의 손실은 사상자와 실종자를 합쳐 3만 3763명이었다. 겨울이 오자 보급이 무너져 방한복·식량·연료가 바닥났고, 독일 부대가 스탈린그라드로 빠져나가면서 제2군이 지켜야 할 전선은 점점 넓어졌다. 1942년 12월 27일 참모본부는 히틀러의 요구에 따라 돈강 진지의 무조건 사수를 명령했다.',
                en: 'In the summer offensive of 1942 the Second Army advanced to the Don near Voronezh. Repeated attacks failed to eliminate the Soviet bridgeheads left on the west bank at Uriv, Korotoyak and Shchuchye, and the army’s losses in 1942 came to 33,763 dead, wounded and missing. With winter, supply collapsed — winter clothing, food and fuel ran out — and as German units were drawn off to Stalingrad, the front the army had to hold grew ever longer. On 27 December 1942, at Hitler’s demand, the General Staff ordered the Don positions held at all costs.',
                sources: [S.army2, S.huDon, S.huJany],
            },
            {
                ko: '1943년 1월 12일 필리프 골리코프의 보로네시 전선군이 우리우 교두보에서 오스트로고시스크-로소시 작전을 시작했다. 영하 30도 아래의 추위 속에 전선은 여러 곳에서 뚫렸고, B 집단군 사령관 바이흐스는 예비대 투입을 거부했다. 독일군은 후퇴를 금지했고, 야니는 이 명령을 고수하다 1월 17일에야 철수를 허락했다. 포위된 부대들은 무너지거나 얼어 죽었다. 제2군은 약 19만 명의 병력과 1만 7000명의 유대인 노동봉사자 가운데 약 10만 명이 죽고 3만 5000명이 다치고 6만 명이 포로가 되었다는 추산이 있으며, 헝가리 쪽 연구는 손실을 10만~12만 명으로 본다.',
                en: 'On 12 January 1943 Filipp Golikov’s Voronezh Front launched the Ostrogozhsk–Rossosh offensive from the Uriv bridgehead. In temperatures below −30 °C the front was broken in several places, and Weichs, commanding Army Group B, refused to commit his reserve. The Germans forbade retreat, and Jány held to the order until he allowed withdrawal only on 17 January. Encircled units were destroyed or froze to death. One estimate puts the losses of the roughly 190,000 soldiers and 17,000 Jewish labour servicemen at about 100,000 dead, 35,000 wounded and 60,000 captured; Hungarian accounts put the loss at 100,000–120,000 men.',
                sources: [S.huDon, S.army2, S.vk, S.huJany],
            },
            {
                ko: '1월 24일 야니는 「제2 헝가리군은 명예를 잃었다…」로 시작하는 군령을 내려 병사들을 비겁하다고 비난하고 가혹한 징계를 명령했다. 이 명령은 큰 분노를 샀고, 호르티의 지시로 3월에 철회되었다. 살아남은 병사들은 5월 말까지 귀국했고 야니는 8월 지휘권에서 물러났다. 1943년 2월 스탈린그라드의 독일 제6군도 항복했다. 제2군은 더는 전투 부대로 기능하지 못했고, 독일군은 남은 부대를 전선에서 뺐다.',
                en: 'On 24 January Jány issued an order of the day beginning “The Hungarian Second Army has lost its honour…”, accusing his men of cowardice and ordering drastic discipline. It caused general outrage, and on Horthy’s instruction it was withdrawn in March. The survivors were brought home by the end of May, and Jány was relieved in August. The German Sixth Army at Stalingrad had surrendered in February 1943. The Second Army ceased to exist as an effective fighting force, and the Germans pulled what was left of it from the front.',
                sources: [S.huDon, S.huJany, S.army2, S.hww2],
            },
        ],
    },
    {
        heading: { ko: '지하 공산당과 반독일 야당 (1940–1943)', en: 'The underground Communists and the anti-German opposition (1940–1943)' },
        paragraphs: [
            {
                ko: '헝가리 공산당(KMP)은 1919년 이후 불법이었고, 1932년 셜러이 임레와 퓌르시트 샨도르가 처형된 뒤 약해져 1936년 코민테른이 해산시켰다. 1924년부터 갇혀 있던 라코시 마차시는 1940년 10월 가석방되어, 1849년 러시아군이 빼앗아 간 헝가리 혁명군 군기와 교환되는 형식으로 소련에 갔다. 독일의 소련 침공 뒤 공산당은 비공산 세력과 함께 반독일 전선을 만들려 했다. 쇤헤르츠 졸탄이 이끈 독립위원회는 1941년 10월 6일 버차니 영원의 등불 앞과 11월 1일 코슈트·탄치치의 묘 앞에서 시위를 열었고, 사회민주당 기관지 『네프서버』의 1941년 성탄 특집호에는 버이치질린스키 엔드레가 전쟁 이탈과 토지개혁, 보통선거를 위한 「독립전선」을 호소하는 글을 썼다.',
                en: 'Illegal since 1919, the Hungarian Communist Party (KMP) was so weakened after the execution of Imre Sallai and Sándor Fürst in 1932 that the Comintern dissolved it in 1936. Mátyás Rákosi, imprisoned since 1924, was paroled in October 1940 and allowed to leave for the Soviet Union in exchange for Hungarian revolutionary banners captured by Russian troops in 1849. After Germany attacked the Soviet Union the Communists sought an anti-German front with non-Communists. The Independence Committee led by Zoltán Schönherz staged demonstrations at the Batthyány eternal flame on 6 October 1941 and at the graves of Kossuth and Táncsics on 1 November, and in the Christmas 1941 issue of the Social Democratic Népszava Endre Bajcsy-Zsilinszky called for an “Independence Front” to take Hungary out of the war and bring land reform and universal suffrage.',
                sources: [S.hcp, S.rakosi, S.huSchonherz, S.bajcsy],
            },
            {
                ko: '1942년 2월 1일 지하 기관지 『서버드 네프』가 창간되어 로저 페렌츠가 편집을 맡았다. 1942년 5~6월과 7월의 대량 검거로 공산당 지도부는 무너졌다. 로저는 6월 1일 체포되어 2주 뒤 경찰 구금 중 석연치 않게 숨졌고, 7월 6일 체포된 쇤헤르츠는 참모본부 특별재판소에서 사형을 선고받아 10월 9일 처형되었다. 1943년 1월 다시 검거가 이어진 뒤 카다르 야노시가 지도부를 맡았다. 같은 해 코민테른이 해산되자 카다르는 경찰을 따돌리려고 당을 해산한 것처럼 꾸며 「평화당」으로 재건했는데, 모스크바의 라코시 등은 이를 비난했다. 평화당은 칼러이의 퇴진과 단독 강화, 화살십자당 해산을 요구했다.',
                en: 'The underground paper Szabad Nép appeared on 1 February 1942, edited by Ferenc Rózsa. Mass arrests in May–June and July 1942 destroyed the Communist leadership. Rózsa, arrested on 1 June, died in unclear circumstances in police custody two weeks later; Schönherz, arrested on 6 July, was sentenced to death by the special court of the Chief of the General Staff and executed on 9 October. After a further wave of arrests in January 1943 János Kádár took over the leadership. When the Comintern was dissolved that year, Kádár staged a sham dissolution to throw off the police and refounded the party as the Peace Party, a step Rákosi and the Moscow émigrés condemned. The Peace Party demanded Kállay’s removal, a separate peace and the dissolution of the Arrow Cross.',
                sources: [S.huRozsa, S.huSchonherz, S.kadar, S.huBp, S.hcp],
            },
            {
                ko: '의회 안의 반대는 소수였다. 버이치질린스키는 노비사드 학살을 앞두고 바르도시에게 경고했고, 학살 뒤에는 의회에서 이를 「국가가 조직한 포그롬」이라 부르며 책임자 처벌을 요구했다. 1943년 1월 학살 1주기에 다시 발언하려 하자 화살십자당과 헝가리 쇄신당 의원들이 「반역」이라고 외치며 그를 막았다. 국방부는 1942년 내내 그가 군의 명예를 더럽힌다며 기소를 경고했다. 사회민주당은 전쟁 중 점점 활동이 어려워졌고, 1944년 독일 점령과 함께 불법화되었다.',
                en: 'Opposition in parliament was a small minority. Bajcsy-Zsilinszky warned Bárdossy before the Novi Sad raid and afterwards called it “a state-organized pogrom” in parliament, demanding that those responsible be tried. When he tried to raise it again on its first anniversary in January 1943, Arrow Cross and Party of Hungarian Renewal deputies shouted him down with cries of “Treason!”; throughout 1942 the Defence Ministry had warned that he would be prosecuted for impugning the army’s honour. The Social Democrats found activity ever harder during the war, and with the German occupation in 1944 the party was outlawed.',
                sources: [S.bajcsy, E('Social_Democratic_Party_of_Hungary')],
            },
        ],
    },
    {
        heading: { ko: '칼러이의 「시소 정책」과 마르가레테 작전의 결정 (1942–1944)', en: 'Kállay’s “see-saw” and the decision for Operation Margarethe (1942–1944)' },
        paragraphs: [
            {
                ko: '1942년 3월 호르티는 바르도시를 물러나게 하고 베틀렌 계열의 보수파 칼러이 미클로시를 총리로 앉혔다. 칼러이는 첫 연설에서 대소련 전쟁을 「우리의 전쟁」이라 부르고 사회민주당을 단속해 유대계 당원 수백 명을 노동봉사로 보냈지만, 뒤로는 연합국과 접촉했다. 독일이 헝가리 유대인의 강제 이송을 거듭 요구하자 칼러이와 호르티는 유대인 문제는 국내 문제이며 이송은 경제를 무너뜨린다며 거부했다. 그래서 1944년 3월까지 수십만 명의 유대인이 살아남았지만, 차별법과 노동봉사는 계속되었다. 앞뒤로 오가는 그의 정책은 「칼러이 투스텝」, 「칼러이 시소」라 불렸다.',
                en: 'In March 1942 Horthy forced Bárdossy out and installed Miklós Kállay, a conservative of the Bethlen school, as prime minister. In his first speech Kállay called the war against the Soviet Union “our war” and cracked down on the Social Democrats, sending hundreds of Jewish members to labour service, but behind the scenes he sought contact with the Allies. When Germany repeatedly demanded the deportation of Hungary’s Jews, Kállay and Horthy refused, calling it a domestic matter that would wreck the economy; hundreds of thousands of Jews thus survived until March 1944, though discrimination and labour service went on. His back-and-forth policy became known as the “Kállay two-step” or “Kállay see-saw”.',
                sources: [S.kallay, S.ushmm, S.hww2],
            },
            {
                ko: '돈강의 참패 뒤인 1943년 1월 말 베틀렌, 수좌대주교 세레디, 대법원장은 호르티에게 동부전선의 병력 철수와 노비사드 책임자 처벌을 건의했다. 2월 기자 프레이 언드라시가 이스탄불에서 영국 측과 접촉했고, 4월 칼러이는 로마에서 무솔리니에게 헝가리·이탈리아·핀란드의 「추축 안의 추축」을 제안했다가 거절당했다. 4월 클레스하임 회담에서 히틀러는 헝가리의 평화 타진을 알고 있다며 경고했다. 칼러이 정부는 의회에서 임레디의 헝가리 쇄신당과 화살십자당의 공격을 받았고, 1943년 5월 호르티는 의회를 정회했다.',
                en: 'After the Don disaster, at the end of January 1943, Bethlen, the Prince Primate Cardinal Serédi and the chief justice advised Horthy to withdraw the troops from the Eastern Front and punish those responsible for Novi Sad. In February the journalist András Frey opened contacts with the British in Istanbul, and in April Kállay proposed to Mussolini in Rome an “axis within the Axis” of Hungary, Italy and Finland, which Mussolini rejected. At the Klessheim meeting in April Hitler warned Horthy and Kállay that he knew of their peace feelers. In parliament Kállay was attacked by Imrédy’s Party of Hungarian Renewal and the Arrow Cross, and in May 1943 Horthy prorogued parliament.',
                sources: [S.kallay, S.marg],
            },
            {
                ko: '1943년 7월 연합군이 시칠리아에 상륙하고 무솔리니가 실각하자 협상이 빨라졌다. 9월 9일 이스탄불 앞 마르마라해의 요트에서 영국 대사 내치불휴거슨과 헝가리 외교관 베레시 라슬로는 연합군이 헝가리 국경에 도착하면 헝가리군이 항복한다는 비밀 예비 휴전에 서명했다. 칼러이는 무조건 항복 조항에 반대했지만, 헝가리 영사와 리스본 공사가 조건을 받아들이겠다고 전했다. 칼러이는 노비사드 학살 책임자들을 1943년 12월 군사재판에 넘겼으나, 유죄 판결을 받은 페케테헐미체이드네르 등은 1944년 1월 독일로 달아났다.',
                en: 'When the Allies landed in Sicily in July 1943 and Mussolini fell, the talks accelerated. On 9 September, on a yacht in the Sea of Marmara off Istanbul, the British ambassador Sir Hughe Knatchbull-Hugessen and the Hungarian diplomat László Veress signed a secret preliminary armistice under which Hungarian forces would surrender once Allied troops reached Hungary. Kállay objected to its unconditional-surrender formula, but the Hungarian consul in Istanbul and the minister in Lisbon signalled acceptance. Kállay put those responsible for Novi Sad before a court martial in December 1943, but Feketehalmy-Czeydner and the other convicted officers fled to Germany in January 1944.',
                sources: [S.kallay, S.marg, S.novisad],
            },
            {
                ko: '1943년 9월 이탈리아가 연합국과 휴전하자 히틀러는 국방군 최고사령부에 헝가리 점령 계획(마르가레테 1)과 루마니아 점령 계획(마르가레테 2)을 세우게 했고, 카이텔은 9월 30일 준비가 끝났다고 보고했다. 11월부터 영국 대사관의 시종 엘리에사 바즈나가 빼돌린 문서로 베레시의 비밀 휴전 내용도 베를린에 알려졌다. 1944년 초 붉은군대가 카르파티아산맥 기슭에 다가가자 히틀러는 루마니아 석유가 지나는 헝가리가 동맹에서 이탈할 것을 걱정했다. 괴벨스는 3월 4일 일기에 「배신은 벌받아야 한다」고 썼고, 히틀러가 헝가리의 유대인 70만 명을 놓치지 않겠다고 말했다고 적었다.',
                en: 'After Italy’s armistice with the Allies in September 1943, Hitler had the Wehrmacht high command plan the occupation of Hungary (Margarethe I) and of Romania (Margarethe II); Keitel reported on 30 September that both plans were ready. From November documents stolen by Elyesa Bazna, the British ambassador’s valet, also told Berlin of Veress’s secret armistice. As the Red Army neared the foothills of the Carpathians in early 1944, Hitler feared that Hungary, through which Romanian oil reached the Reich, would leave the alliance. On 4 March Goebbels wrote in his diary that “treason had to be punished”, quoting Hitler as saying that he would not let Hungary’s 700,000 Jews slip through his fingers.',
                sources: [S.marg, S.kallay],
            },
            {
                ko: '히틀러는 3월 7일 마르가레테 1 작전을 발동하기로 했다. 처음에는 헝가리를 루마니아·크로아티아·슬로바키아에 나눠 주는 군사적 해결을 생각했지만, 친위대 장교 빌헬름 회틀은 호르티를 섭정 자리에 남겨 두어야 철도 파괴 같은 저항 없이 헝가리 국가 기구 전체의 협력을 얻을 수 있다고 건의했고, 히틀러는 먼저 이 정치적 해결을 시도하기로 했다. 3월 12일 독일군에 주요 시설 장악 명령이 내려졌고, 힘러는 아이히만에게 헝가리 유대인을 아우슈비츠로 이송할 준비를 지시했다. 호르티는 클레스하임으로 불려 갔고, 3월 19일 독일군이 헝가리에 들어왔다.',
                en: 'On 7 March Hitler decided to activate Margarethe I. His first idea was a military solution that would partition Hungary among Romania, Croatia and Slovakia, but the SS officer Wilhelm Höttl argued that keeping Horthy as regent would secure the co-operation of the whole Hungarian state without sabotage of the railways, and Hitler decided to try this political solution first. On 12 March German troops were ordered to seize key Hungarian facilities, and Himmler instructed Eichmann to prepare the deportation of Hungary’s Jews to Auschwitz. Horthy was summoned to Klessheim, and on 19 March German troops entered Hungary.',
                sources: [S.marg, S.ushmm],
            },
        ],
    },
];

const event = buildEvent({
    id: 'hungary-axis-1938-1944',
    title: { ko: '추축국 편의 헝가리: 빈 중재에서 돈강까지', en: 'Hungary on the Axis side: from the Vienna Awards to the Don' },
    period: '1938–1944.03',
    sortOrder: 106,
    question: {
        ko: '독일 덕에 잃은 땅을 되찾은 헝가리는 왜 원하지 않던 전쟁에 깊이 빠져들었고, 빠져나가려던 시도는 왜 독일의 점령으로 끝났는가?',
        en: 'Why was Hungary, which regained lost lands thanks to Germany, drawn deep into a war it had not wanted — and why did its attempt to get out end in German occupation?',
    },
    summary: {
        ko: '1938~1941년 헝가리는 두 차례의 빈 중재와 루테니아·유고슬라비아 점령으로 트리아농 조약에서 잃은 땅의 일부를 되찾았고, 그 대가로 삼국동맹에 가입하고 세 차례의 유대인법을 만들었다. 1941년 텔레키가 유고슬라비아 침공에 항의해 자살한 뒤 바르도시 정부는 커셔 폭격을 구실로 소련에 선전포고했고, 카미야네츠포딜스키 추방과 노비사드 학살, 유대인 노동봉사가 뒤따랐다. 1943년 1월 돈강에서 제2군이 무너지자 칼러이 정부는 서방 연합국과 비밀 휴전을 맺으려 했다. 이를 알아챈 히틀러는 1944년 3월 헝가리 점령을 결정했다.',
        en: 'Between 1938 and 1941 Hungary regained part of the lands lost at Trianon through the two Vienna Awards and the occupation of Ruthenia and Yugoslav territory, paying for it by joining the Tripartite Pact and passing three Jewish laws. After Teleki’s suicide in protest at the invasion of Yugoslavia in 1941, Bárdossy’s government declared war on the Soviet Union on the pretext of the Kassa bombing, and the Kamianets-Podilskyi deportations, the Novi Sad raid and Jewish labour service followed. When the Second Army was destroyed on the Don in January 1943, Kállay’s government sought a secret armistice with the Western Allies. Hitler, who learned of it, decided in March 1944 to occupy Hungary.',
    },
    outcome: {
        ko: '되찾은 땅은 전후 모두 반환되었고, 독일 점령 전에 이미 카미야네츠포딜스키 학살, 노비사드 학살, 노동봉사로 수만 명의 유대인이 죽었고 돈강에서는 병사 약 10만 명이 목숨을 잃었다. 1944년 3월 19일 독일 점령으로 헝가리 유대인의 대량 이송과 학살이 시작되었다.',
        en: 'All the regained lands were returned after the war, and before the German occupation the Kamianets-Podilskyi massacre, the Novi Sad raid and labour service had already killed tens of thousands of Jews, and about 100,000 soldiers had died on the Don. The German occupation of 19 March 1944 opened the mass deportation and murder of Hungary’s Jews.',
    },
    sections,
    timeline: [
        ['1938.05.29', '제1차 유대인법', 'First Jewish Law', '전문직과 상공업의 유대인 비율을 20%로 제한했다.', 'It capped the share of Jews in the professions and business at 20 per cent.', 'hungary'],
        ['1938.11.02', '제1차 빈 중재', 'First Vienna Award', '독일과 이탈리아가 남부 슬로바키아와 남부 루테니아를 헝가리에 넘겼다.', 'Germany and Italy awarded southern Slovakia and southern Ruthenia to Hungary.', ['hungary', 'czechoslovakia', 'germany', 'italy'], P(48.1915, 16.3809, '빈 벨베데레 궁', 'Belvedere Palace, Vienna')],
        ['1939.02', '임레디 사임', 'Imrédy resigns', '정적들이 유대계 조상을 밝혀내자 총리직에서 물러났다.', 'He resigned when opponents exposed his Jewish ancestry.', 'hungary'],
        ['1939.03.14', '카르파티아 우크라이나 점령', 'Occupation of Carpatho-Ukraine', '헝가리군이 18일까지 나머지 루테니아를 점령했다.', 'Hungarian troops occupied the rest of Ruthenia by the 18th.', ['hungary', 'czechoslovakia'], P(48.17, 23.29, '후스트', 'Khust')],
        ['1939.03.23', '슬로바키아와의 「작은 전쟁」', 'The “Little War” with Slovakia', '31일까지 싸워 동부 슬로바키아의 띠 모양 땅을 얻었다.', 'Fighting until the 31st won a strip of eastern Slovakia.', ['hungary', 'slovakia']],
        ['1939.05.05', '제2차 유대인법', 'Second Jewish Law', '유대인을 인종으로 정의하고 비율 제한을 6%로 낮췄다.', 'It defined Jews racially and cut the quotas to 6 per cent.', 'hungary'],
        ['1940.08.30', '제2차 빈 중재', 'Second Vienna Award', '북부 트란실바니아가 루마니아에서 헝가리로 넘어갔다.', 'Northern Transylvania passed from Romania to Hungary.', ['hungary', 'romania', 'germany', 'italy']],
        ['1940.10.30', '라코시 석방', 'Rákosi released', '1849년의 군기와 교환되는 형식으로 소련으로 떠났다.', 'He left for the Soviet Union in exchange for the 1849 banners.', ['hungary', 'soviet']],
        ['1940.11.20', '삼국동맹 가입', 'Accession to the Tripartite Pact', '헝가리가 창설국 다음 첫 가입국이 되었다.', 'Hungary became the first state to join after the founders.', ['hungary', 'germany', 'italy']],
        ['1941.04.03', '텔레키의 자살', 'Teleki’s suicide', '유고슬라비아 침공 참여에 항의하며 목숨을 끊었다.', 'He took his life in protest at joining the invasion of Yugoslavia.', 'hungary', P(47.4966, 19.0362, '부다페스트 산도르 궁', 'Sándor Palace, Budapest')],
        ['1941.04.11', '유고슬라비아 침공', 'Invasion of Yugoslavia', '헝가리군이 바치카 등을 점령해 12월에 병합했다.', 'Hungarian troops took Bačka and other areas, annexed in December.', ['hungary', 'yugoslavia', 'germany']],
        ['1941.06.26', '커셔 폭격', 'Bombing of Kassa', '정체불명의 비행기가 커셔를 폭격했고 이튿날 헝가리가 소련에 선전포고했다.', 'Unidentified aircraft bombed Kassa; next day Hungary declared war on the USSR.', ['hungary', 'soviet'], P(48.7164, 21.2611, '커셔(코시체)', 'Kassa (Košice)')],
        ['1941.08.27', '카미야네츠포딜스키 학살', 'Kamianets-Podilskyi massacre', '헝가리에서 추방된 유대인을 포함해 2만 3600명이 학살되었다.', '23,600 Jews, including deportees from Hungary, were shot.', ['hungary', 'germany', 'soviet'], P(48.6845, 26.5856, '카미야네츠포딜스키', 'Kamianets-Podilskyi')],
        ['1941.12.06', '영국과의 전쟁', 'War with Britain', '영국의 통첩 시한이 지나 전쟁 상태가 되었고 15일 미국과도 전쟁 상태를 발표했다.', 'Britain’s deadline expired; on the 15th war with the US was announced too.', ['hungary', 'uk', 'usa']],
        ['1942.01.20', '노비사드 학살', 'Novi Sad raid', '헝가리군이 23일까지 세르비아인과 유대인 수천 명을 죽였다.', 'Hungarian troops killed thousands of Serbs and Jews by the 23rd.', ['hungary', 'yugoslavia'], P(45.2551, 19.8452, '노비사드(우이비데크)', 'Novi Sad (Újvidék)')],
        ['1942.03.09', '칼러이 내각', 'Kállay government', '호르티가 바르도시를 물러나게 하고 칼러이를 총리에 앉혔다.', 'Horthy replaced Bárdossy with Kállay.', 'hungary'],
        ['1942.10.09', '쇤헤르츠 처형', 'Schönherz executed', '공산당 지하 지도자가 군사 특별재판 끝에 처형되었다.', 'The underground Communist leader was executed after a special military trial.', 'hungary'],
        ['1943.01.12', '돈강 전선 붕괴', 'Don front collapses', '소련의 오스트로고시스크-로소시 작전으로 제2군이 무너졌다.', 'The Soviet Ostrogozhsk–Rossosh offensive destroyed the Second Army.', ['hungary', 'soviet', 'germany'], P(50.8656, 39.0823, '오스트로고시스크', 'Ostrogozhsk')],
        ['1943.09.09', '이스탄불 비밀 휴전', 'Secret armistice off Istanbul', '베레시가 영국 대사와 예비 휴전에 서명했다.', 'Veress signed a preliminary armistice with the British ambassador.', ['hungary', 'uk', 'turkey'], P(40.95, 28.95, '마르마라해', 'Sea of Marmara')],
        ['1944.03.07', '마르가레테 작전 발동 결정', 'Margarethe ordered', '히틀러가 헝가리 점령 작전의 발동을 결정했다.', 'Hitler decided to activate the occupation of Hungary.', ['germany', 'hungary']],
    ],
    locations: [
        ['부다페스트', 'Budapest', 47.4979, 19.0402, 'main'],
        ['빈', 'Vienna', 48.2082, 16.3738, 'place'],
        ['커셔(코시체)', 'Kassa (Košice)', 48.7164, 21.2611, 'place'],
        ['노비사드', 'Novi Sad', 45.2551, 19.8452, 'place'],
        ['카미야네츠포딜스키', 'Kamianets-Podilskyi', 48.6845, 26.5856, 'place'],
        ['보로네시', 'Voronezh', 51.6720, 39.1843, 'place'],
        ['이스탄불', 'Istanbul', 41.0082, 28.9784, 'place'],
    ],
    countries: ['hungary', 'germany', 'italy', 'soviet', 'czechoslovakia', 'slovakia', 'romania', 'yugoslavia', 'uk', 'usa', 'turkey'],
    relations: { related: ['horthy-regime-1920-1938', 'great-patriotic-war', 'stalingrad', 'yugoslav-partisans'] },
    focus: { ko: '호르티 정권(추축국 참전 정부)', en: 'The Horthy government at war' },
    people: [
        ['miklos-horthy', 'leader', '섭정', 'Regent', '삼국동맹 가입과 유고슬라비아·소련 참전을 승인했고, 1942년 칼러이를 앉혀 전쟁 이탈을 모색했다.', 'Approved joining the Tripartite Pact and the wars on Yugoslavia and the USSR, then installed Kállay in 1942 to seek a way out.'],
        ['bela-imredy', 'leader', '총리(1938–1939)', 'Prime minister 1938–1939', '외교를 독일 쪽으로 돌리고 제2차 유대인법을 제출했다가 유대계 조상이 드러나 물러났다.', 'Turned foreign policy towards Germany and introduced the Second Jewish Law, then fell when his Jewish ancestry came out.'],
        ['pal-teleki', 'leader', '총리(1939–1941)', 'Prime minister 1939–1941', '제2차 유대인법과 노동봉사제를 도입하고 삼국동맹에 서명했으나 유고슬라비아 침공에 항의해 자살했다.', 'Introduced the Second Jewish Law and labour service and signed the Tripartite Pact, but killed himself over the invasion of Yugoslavia.'],
        ['laszlo-bardossy', 'leader', '총리(1941–1942)', 'Prime minister 1941–1942', '커셔 폭격 뒤 소련에 선전포고하고 유대인 추방과 제3차 유대인법을 밀어붙였다.', 'Declared war on the USSR after the Kassa bombing and pushed through the deportations and the Third Jewish Law.'],
        ['miklos-kallay', 'leader', '총리(1942–1944)', 'Prime minister 1942–1944', '유대인 이송 요구를 거부하며 서방 연합국과 비밀 휴전을 추진했다.', 'Refused German deportation demands and pursued a secret armistice with the Western Allies.'],
        ['gusztav-jany', 'executor', '제2군 사령관', 'Commander, Second Army', '돈강에서 후퇴 금지 명령을 고수했고 패배 뒤 병사들을 비난하는 군령을 내렸다.', 'Held to the no-retreat order on the Don and after the defeat issued an order of the day blaming his men.'],
        ['adolf-hitler', 'participant', '독일 총통', 'German Führer', '영토를 대가로 헝가리를 전쟁에 끌어들였고 1944년 3월 헝가리 점령을 결정했다.', 'Drew Hungary into the war with territorial rewards and in March 1944 decided to occupy it.'],
        ['joachim-von-ribbentrop', 'participant', '독일 외무장관', 'German foreign minister', '치아노와 함께 두 차례 빈 중재를 내렸다.', 'Delivered both Vienna Awards together with Ciano.'],
        ['galeazzo-ciano', 'participant', '이탈리아 외무장관', 'Italian foreign minister', '리벤트로프와 함께 두 차례 빈 중재를 내렸다.', 'Delivered both Vienna Awards together with Ribbentrop.'],
        ['benito-mussolini', 'participant', '이탈리아 총리', 'Italian prime minister', '1943년 4월 칼러이가 제안한 「추축 안의 추축」을 거절했다.', 'Rejected the “axis within the Axis” Kállay proposed in April 1943.'],
        ['ion-antonescu', 'participant', '루마니아 지도자', 'Romanian leader', '1941년 말 호르티·무솔리니와 함께 히틀러에게서 동부전선 증원 요구 편지를 받았다.', 'Received Hitler’s letter of late 1941, like Horthy and Mussolini, demanding more troops for the Eastern Front.'],
        ['wilhelm-keitel', 'participant', '독일 국방군 최고사령부 총장', 'Chief of the Wehrmacht high command', '1942년 1월 부다페스트에 와 헝가리군의 동부전선 투입을 요구했고, 마르가레테 계획을 준비했다.', 'Came to Budapest in January 1942 to demand Hungarian troops for the Eastern Front and prepared the Margarethe plans.'],
        ['maximilian-von-weichs', 'participant', 'B 집단군 사령관', 'Commander, Army Group B', '1943년 1월 소련 공세 초기에 헝가리군을 도울 예비대 투입을 거부했다.', 'Refused to commit his reserve to support the Hungarians at the start of the Soviet offensive in January 1943.'],
        ['molotov', 'participant', '소련 외무인민위원', 'Soviet foreign commissar', '1941년 6월 23일 헝가리가 중립을 지키면 루마니아에 대한 요구를 지지하겠다고 전했다.', 'On 23 June 1941 offered to back Hungarian claims on Romania if Hungary stayed neutral.'],
        ['filipp-golikov', 'opponent', '소련 보로네시 전선군 사령관', 'Commander, Soviet Voronezh Front', '오스트로고시스크-로소시 작전으로 헝가리 제2군을 무너뜨렸다.', 'Destroyed the Hungarian Second Army in the Ostrogozhsk–Rossosh offensive.'],
        ['anthony-eden', 'participant', '영국 외무장관', 'British foreign secretary', '유고슬라비아 침공을 헝가리의 「영원한 수치」라 부르고 단교와 선전포고를 경고했다.', 'Warned of a break and war over Yugoslavia and called the attack an “everlasting shame” for Hungary.'],
        ['winston-churchill', 'witness', '영국 총리', 'British prime minister', '텔레키의 자살을 독일의 유고슬라비아 공격에 대한 죄를 씻으려는 희생이라고 썼다.', 'Wrote that Teleki’s suicide was a sacrifice to absolve himself and his people of guilt for the attack on Yugoslavia.'],
        ['istvan-bethlen', 'participant', '전 총리, 보수파 원로', 'Former prime minister, conservative elder', '임레디의 유대계 조상을 밝혀냈고 1943년 1월 동부전선 철수를 호르티에게 건의했다.', 'Helped expose Imrédy’s Jewish ancestry and in January 1943 urged Horthy to withdraw from the Eastern Front.'],
        ['matyas-rakosi', 'target', '수감 중인 공산당 지도자', 'Imprisoned Communist leader', '1940년 1849년의 군기와 교환되는 형식으로 풀려나 소련으로 갔고, 뒤에 평화당 결성을 비난했다.', 'Released to the USSR in 1940 in exchange for the 1849 banners; later condemned the founding of the Peace Party.'],
        ['zoltan-schonherz', 'opponent', '공산당 지하 지도자', 'Underground Communist leader', '독립위원회를 이끌어 반전 시위를 조직했고 1942년 처형되었다.', 'Led the Independence Committee, organised anti-war demonstrations and was executed in 1942.'],
        ['ferenc-rozsa', 'opponent', '『서버드 네프』 편집인', 'Editor of Szabad Nép', '지하 기관지를 창간해 편집하다 1942년 체포되어 구금 중 숨졌다.', 'Founded and edited the underground party paper and died in custody after his arrest in 1942.'],
        ['janos-kadar', 'opponent', '공산당 지하 지도자', 'Underground Communist leader', '1943년 지도부를 맡아 공산당을 평화당으로 바꾸었다.', 'Took over the leadership in 1943 and turned the Communist Party into the Peace Party.'],
        ['gabor-peter', 'opponent', '공산당 지하 지도부원', 'Underground Communist leader', '1943년 대량 검거 뒤 카다르와 함께 새 지도부를 이루었다.', 'Formed the new leadership with Kádár after the mass arrests of 1943.'],
    ],
});

const people = [
    person({
        id: 'bela-imredy',
        given: ['벨러', 'Béla'], family: ['임레디', 'Imrédy'], nativeName: 'Imrédy Béla', years: '1891–1946',
        epithet: ['외교를 독일 쪽으로 돌리고 제2차 유대인법을 낸 뒤 유대계 조상이 드러나 물러난 총리',
            'Prime minister who swung Hungary towards Germany and drafted the Second Jewish Law, then fell over his own Jewish ancestry'],
        bio: ['부다페스트의 가톨릭 가정에서 태어나 재무부에서 일한 경제 전문가로, 1932년 굄뵈시 내각의 재무장관, 1935년 국립은행 총재가 되었다. 1938년 5월 총리가 되어 그해 가을부터 외교를 독일·이탈리아 쪽으로 돌렸고, 그의 재임 중 제1차 빈 중재로 남부 슬로바키아가 헝가리에 돌아왔다. 독재적 개편과 제2차 유대인법을 추진했으나 1939년 2월 정적들이 그의 유대계 조상을 밝혀내 사임했다. 1940년 친파시스트 정당 헝가리 쇄신당을 세웠고, 1944년 독일 점령 뒤 스토여이 내각의 장관을 지냈다. 1946년 인민재판소의 사형 선고로 총살되었다.',
            'Born to a Catholic family in Budapest, he was an economist in the finance ministry who became Gömbös’s finance minister in 1932 and president of the National Bank in 1935. Prime minister from May 1938, he turned foreign policy towards Germany and Italy from that autumn, and under him the First Vienna Award returned southern Slovakia to Hungary. He pressed for a dictatorial reorganisation and the Second Jewish Law, but resigned in February 1939 when opponents exposed his Jewish ancestry. In 1940 he founded the pro-fascist Party of Hungarian Renewal, and after the German occupation of 1944 he served in Sztójay’s cabinet. Sentenced to death by a People’s Tribunal, he was shot in 1946.'],
        fate: ['executed', '처형', 'Executed'],
        aliases: { ko: [], en: ['Béla Imrédy', 'Bela Imredy', 'Imrédy Béla'] },
        sources: [S.imredy, S.huImredy],
        facts: {
            years: { claim: '1891–1946', locator: 'lead', excerpt: '29 December 1891 – 28 February 1946' },
            citizenship: { claim: 'Hungarian prime minister', locator: 'lead', excerpt: 'was Prime Minister of Hungary from 1938 to 1939' },
            nationalOrigin: { claim: 'born in Budapest', locator: 'biography', excerpt: 'Born in Budapest to a Catholic family' },
            bio: [
                { claim: 'Finance minister 1932, National Bank 1935', locator: 'biography', excerpt: 'In 1932, he was appointed Minister of Finance under the fascist Prime Minister Gyula Gömbös. Following his resignation in 1935, Imrédy took on the role of President of the Hungarian National Bank.' },
                { claim: 'pro-German turn from autumn 1938', locator: 'biography', excerpt: 'from the autumn of 1938 onward, he pivoted Hungary\'s foreign policy towards pro-German and pro-Italian policies' },
                { claim: 'resigned over Jewish ancestry; founded Party of Hungarian Renewal', locator: 'biography', excerpt: 'founded the Party of Hungarian Renewal, a pro-fascist and antisemitic organization, in October of that year' },
                { claim: 'First Vienna Award under his government', source: S.huImredy, locator: 'bevezető', excerpt: 'így 1938 novemberében, az első bécsi döntés hatására a tengelyhatalmak jelentős magyarlakta területet csatoltak vissza Magyarországhoz' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-hungary', startYear: 1938, endYear: 1939, primary: true, claim: '1938–1939년 헝가리 총리', locator: 'biography', excerpt: 'When Darányi stepped down in May 1938, Regent Miklós Horthy appointed Imrédy as the new prime minister' },
            { functionId: 'economy', affiliationId: 'state-hungary', startYear: 1928, endYear: 1938, claim: '국립은행 이사와 총재, 재무장관', locator: 'biography', excerpt: 'Imrédy was made Director of the Hungarian National Bank in 1928' },
        ],
        career: [
            ['1928–1932', '헝가리 국립은행 이사', 'Director, Hungarian National Bank'],
            ['1932–1935', '굄뵈시 내각 재무장관', 'Finance minister under Gömbös'],
            ['1935–1938', '헝가리 국립은행 총재', 'President, Hungarian National Bank'],
            ['1938–1939', '총리, 제2차 유대인법 제출', 'Prime minister; introduced the Second Jewish Law'],
            ['1940–1944', '헝가리 쇄신당 창립·당수', 'Founder and leader, Party of Hungarian Renewal'],
            ['1944', '스토여이 내각 경제 담당 장관', 'Minister of economic coordination under Sztójay'],
        ],
    }),
    person({
        id: 'laszlo-bardossy',
        given: ['라슬로', 'László'], family: ['바르도시', 'Bárdossy'], nativeName: 'Bárdossy László', years: '1890–1946',
        epithet: ['커셔 폭격을 구실로 소련에 선전포고하고 유대인 추방을 승인한 전시 총리',
            'Wartime prime minister who declared war on the Soviet Union over the Kassa bombing and approved the deportation of Jews'],
        bio: ['솜버테이 출신의 법률가이자 외교관으로, 1922년 외무부로 옮겨 언론국장 등을 지냈다. 1941년 1월 외무장관이 되었고, 4월 텔레키가 자살하자 총리를 겸했다. 트리아농으로 잃은 땅을 되찾으려 친독 노선을 걸어 유고슬라비아 침공에 참여했고, 6월 커셔 폭격 뒤 의회 동의 없이 소련과의 전쟁 상태를 선언했으며, 영국·미국과도 전쟁에 들어갔다. 「외국인」 유대인 추방과 제3차 유대인법을 밀어붙였고, 1942년 3월 호르티에 의해 물러났다. 전후 인민재판소에서 사형을 선고받아 1946년 1월 총살되었다.',
            'A lawyer and diplomat from Szombathely, he moved to the foreign ministry in 1922 and headed its press department. He became foreign minister in January 1941 and, after Teleki’s suicide in April, prime minister as well. Seeking to regain lands lost at Trianon, he followed a pro-German line, joined the invasion of Yugoslavia, declared a state of war with the Soviet Union without parliament’s consent after the Kassa bombing in June, and took Hungary into war with Britain and the United States. He pushed through the deportation of “alien” Jews and the Third Jewish Law, and Horthy forced him out in March 1942. Sentenced to death by a People’s Court after the war, he was shot in January 1946.'],
        fate: ['executed', '처형', 'Executed'],
        aliases: { ko: [], en: ['László Bárdossy', 'Laszlo Bardossy', 'Bárdossy László'] },
        sources: [S.bardossy],
        facts: {
            years: { claim: '1890–1946', locator: 'lead', excerpt: '10 December 1890 – 10 January 1946' },
            citizenship: { claim: 'Hungarian prime minister', locator: 'lead', excerpt: 'served as Prime Minister of Hungary from April 1941 to March 1942' },
            nationalOrigin: { claim: 'born in Szombathely', locator: 'Early life', excerpt: 'Born at Szombathely on 10 December 1890' },
            bio: [
                { claim: 'foreign minister then prime minister in 1941', locator: 'lead', excerpt: 'Bárdossy was appointed Foreign Minister in January 1941 and, following Pál Teleki\'s suicide in April, succeeded as Prime Minister.' },
                { claim: 'war with USSR, UK, US', locator: 'lead', excerpt: 'Afterwards, during his office Hungary became belligerent with the Soviet Union, United Kingdom and the United States.' },
                { claim: 'Third Jewish Law', locator: 'Domestic policies', excerpt: 'Bárdossy enacted the Third Jewish Law in August 1941' },
                { claim: 'executed 1946', locator: 'lead', excerpt: 'He was executed by firing squad in January 1946.' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-hungary', startYear: 1941, endYear: 1942, primary: true, claim: '1941–1942년 헝가리 총리', locator: 'lead', excerpt: 'served as Prime Minister of Hungary from April 1941 to March 1942' },
            { functionId: 'diplomacy', affiliationId: 'state-hungary', startYear: 1922, endYear: 1942, claim: '외무부 관료, 외무장관', locator: 'Early life', excerpt: 'In February 1922, he transferred to the newly established Ministry of Foreign Affairs' },
        ],
        career: [
            ['1913–1922', '문교부 관료', 'Official, Ministry of Culture and Education'],
            ['1922–1941', '외무부 언론국장, 외교관', 'Press chief and diplomat, foreign ministry'],
            ['1941', '외무장관', 'Foreign minister'],
            ['1941–1942', '총리 겸 외무장관, 대소련 참전', 'Prime minister and foreign minister; war on the USSR'],
            ['1945–1946', '인민재판소 사형 선고, 처형', 'Sentenced by a People’s Court and executed'],
        ],
    }),
    person({
        id: 'miklos-kallay',
        given: ['미클로시', 'Miklós'], family: ['칼러이', 'Kállay'], nativeName: 'Kállay Miklós', years: '1887–1967',
        epithet: ['독일의 유대인 이송 요구를 거부하며 서방 연합국과 비밀 휴전을 꾀한 전시 총리',
            'Wartime prime minister who refused German deportation demands and sought a secret armistice with the Western Allies'],
        bio: ['서볼치 지방의 오랜 젠트리 가문 출신으로 주지사를 거쳐 1932~1935년 농업장관을 지냈고 베틀렌 계열의 보수파였다. 1941년 상원에서 제3차 유대인법에 반대표를 던졌다. 1942년 3월 호르티의 요청으로 총리가 되어 대소련 전쟁을 이어 가면서도 독일의 유대인 이송 요구를 거부하고 서방 연합국과 휴전을 협상했다. 1943년 9월 이스탄불 앞바다에서 비밀 예비 휴전이 맺어졌으나, 1944년 3월 독일이 헝가리를 점령하자 물러나 튀르키예 공사관에 숨었다. 1944년 10월 붙잡혀 다하우와 마우트하우젠에 갇혔다가 1945년 풀려났고, 1946년 망명해 뉴욕에서 숨졌다.',
            'From an old gentry family of Szabolcs County, he was a county lord-lieutenant and minister of agriculture from 1932 to 1935, a conservative of the Bethlen school. In 1941 he voted in the upper house against the Third Jewish Law. Made prime minister at Horthy’s request in March 1942, he kept up the war against the Soviet Union while refusing German demands to deport Hungary’s Jews and negotiating an armistice with the Western Allies. A secret preliminary armistice was signed off Istanbul in September 1943, but when Germany occupied Hungary in March 1944 he was ousted and hid in the Turkish legation. Captured in October 1944, he was held in Dachau and Mauthausen until freed in 1945; he went into exile in 1946 and died in New York.'],
        fate: ['exile', '망명지에서 사망', 'Died in exile'],
        aliases: { ko: [], en: ['Miklós Kállay', 'Miklos Kallay', 'Kállay Miklós', 'Nicholas Kállay'] },
        sources: [S.kallay],
        facts: {
            years: { claim: '1887–1967', locator: 'lead', excerpt: '23 January 1887 – 14 January 1967' },
            citizenship: { claim: 'Hungarian prime minister', locator: 'lead', excerpt: 'served as Prime Minister of Hungary during World War II, from 9 March 1942 to 22 March 1944' },
            nationalOrigin: { claim: 'Hungarian gentry family', locator: 'Early life and career', excerpt: 'The Kállay family was old and influential among the local gentry of their region' },
            bio: [
                { claim: 'resisted Nazi pressure, contacted Allies', locator: 'lead', excerpt: 'Kállay successfully protected refugees and prisoners, resisted Nazi pressure regarding Jews, established contact with the Allies and negotiated conditions under which Hungary would switch sides against Germany.' },
                { claim: 'voted against Third Jewish Law', locator: 'Early life and career', excerpt: 'In August 1941 as a member of the Upper House, Kállay voted against the Third Anti-Jewish law' },
                { claim: 'Turkish legation, Dachau, Mauthausen', locator: 'Imprisonment', excerpt: 'He was sent first to Dachau and then to Mauthausen.' },
                { claim: 'exile and death in New York', locator: 'lead', excerpt: 'He went into exile in 1946 and died two decades later in New York City.' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-hungary', startYear: 1942, endYear: 1944, primary: true, claim: '1942–1944년 헝가리 총리', locator: 'lead', excerpt: 'served as Prime Minister of Hungary during World War II, from 9 March 1942 to 22 March 1944' },
            { functionId: 'agriculture', affiliationId: 'state-hungary', startYear: 1932, endYear: 1935, claim: '농업장관', locator: 'Early life and career', excerpt: 'later as minister of agriculture (1932–1935)' },
        ],
        career: [
            ['1921–1929', '서볼치 주 주지사', 'Lord-lieutenant of Szabolcs County'],
            ['1929–1931', '상무부 차관', 'Deputy under-secretary, Ministry of Trade'],
            ['1932–1935', '농업장관', 'Minister of agriculture'],
            ['1942–1944', '총리, 연합국과 비밀 휴전 협상', 'Prime minister; secret armistice talks with the Allies'],
            ['1944–1945', '튀르키예 공사관 피신, 다하우·마우트하우젠 수감', 'Refuge in the Turkish legation; Dachau and Mauthausen'],
            ['1946–1967', '망명, 미국 정착', 'Exile; settled in the United States'],
        ],
    }),
    person({
        id: 'gusztav-jany',
        given: ['구스타브', 'Gusztáv'], family: ['야니', 'Jány'], nativeName: 'Jány Gusztáv', years: '1883–1947',
        epithet: ['1943년 1월 돈강에서 무너진 헝가리 제2군의 사령관',
            'Commander of the Hungarian Second Army destroyed on the Don in January 1943'],
        bio: ['하우칭거라는 성으로 태어나 루도비카 사관학교와 빈 군사대학을 나왔고, 제1차 세계대전 때 참모 장교로 복무했다. 1924년 비테즈 기사단에 들어가며 어머니의 성 야니를 택했고, 1931~1936년 루도비카 사관학교를 이끌었다. 1940년 3월 제2군 사령관이 되었고, 1942년 군을 이끌고 돈강으로 갔다. 1943년 1월 소련 공세 때 후퇴 금지 명령을 고수하다 군이 무너지자 병사들을 비겁하다고 비난하는 군령을 내렸다. 전후 스스로 귀국해 1947년 인민재판소에서 사형을 선고받고 총살되었고, 1993년 대법원에서 무죄로 복권되었다.',
            'Born Gusztáv Hautzinger, he trained at the Ludovika Academy and the Vienna war college and served as a staff officer in the First World War. On entering the Order of Vitéz in 1924 he took his mother’s surname, Jány, and from 1931 to 1936 he headed the Ludovika Academy. He became commander of the Second Army in March 1940 and led it to the Don in 1942. During the Soviet offensive of January 1943 he held to the no-retreat order, and when the army collapsed he issued an order of the day accusing his men of cowardice. Returning home voluntarily after the war, he was sentenced to death by a People’s Court and shot in 1947; the Supreme Court exonerated him in 1993.'],
        fate: ['executed', '처형', 'Executed'],
        aliases: { ko: ['하우칭거 구스타브 (본명)'], en: ['Gusztáv Jány', 'Gusztav Jany', 'Jány Gusztáv', 'Gusztáv Hautzinger (birth name)'] },
        sources: [S.huJany, S.jany],
        facts: {
            years: { claim: '1883–1947', source: S.jany, locator: 'lead', excerpt: '21 October 1883 – 26 November 1947' },
            citizenship: { claim: 'Hungarian officer', source: S.jany, locator: 'lead', excerpt: 'was a Hungarian military officer during the Second World War' },
            nationalOrigin: { claim: 'born Hautzinger in Rajka', locator: 'bevezető', excerpt: 'Vitéz Jány Gusztáv (született Hautzinger) (Rajka, 1883. október 21.' },
            bio: [
                { claim: 'took mother\'s surname in 1924', locator: 'A két világháború között', excerpt: 'ekkor – ennek feltételeként – magyarosította vezetéknevét édesanyja nevére' },
                { claim: 'infamous order of 24 January 1943', locator: 'A második világháborúban', excerpt: 'Hadseregének felbomlása láttán adta ki Jány „A 2. magyar hds. elvesztette becsületét…” kezdetű hírhedt parancsát' },
                { claim: 'executed, exonerated 1993', source: S.jany, locator: 'lead', excerpt: 'After the war, he was found guilty of war crimes and executed by firing squad. He was posthumously exonerated in 1993 by the Supreme Court of Hungary.' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: 'state-hungary', startYear: 1940, endYear: 1943, primary: true, claim: '헝가리 제2군 사령관', locator: 'A két világháború között', excerpt: 'Horthy Miklós a Magyar 2. hadsereg parancsnokságával Jányt bízta meg 1940. március 1-jétől.' },
            { functionId: 'education', affiliationId: 'state-hungary', startYear: 1931, endYear: 1936, claim: '루도비카 사관학교 교장', locator: 'A két világháború között', excerpt: '1931. szeptember 1-jétől a Ludovika Akadémia I. főcsoportjának parancsnokaként öt évig vezette az intézményt.' },
        ],
        career: [
            ['1905', '루도비카 사관학교 졸업, 소위 임관', 'Graduated from the Ludovika Academy; commissioned'],
            ['1914–1918', '제1차 세계대전 참모 장교', 'Staff officer in the First World War'],
            ['1931–1936', '루도비카 사관학교 교장', 'Head of the Ludovika Academy'],
            ['1940–1943', '제2군 사령관, 돈강 전투', 'Commander, Second Army; the Don'],
            ['1947', '인민재판소 사형 선고, 처형', 'Sentenced by a People’s Court and executed'],
        ],
    }),
    person({
        id: 'zoltan-schonherz',
        given: ['졸탄', 'Zoltán'], family: ['쇤헤르츠', 'Schönherz'], nativeName: 'Schönherz Zoltán', years: '1905–1942',
        epithet: ['독립위원회를 이끌어 반전 시위를 조직하다 1942년 처형된 공산당 지하 지도자',
            'Underground Communist leader who organised anti-war demonstrations through the Independence Committee and was executed in 1942'],
        bio: ['커셔(코시체)에서 태어나 프라하에서 공부하던 대학생 시절 노동운동에 들어갔다. 1938년 11월 제1차 빈 중재 뒤 지하로 들어가 헝가리에서 활동하며 공산당 연락원과 손잡았다. 1940년 12월부터 공산당의 반전 투쟁을 조직하고 독립위원회를 이끌어 1941년 10월 6일과 11월 1일의 시위를 열었다. 『네프서버』 1941년 성탄호를 준비했고, 1942년 2월 1일 지하 기관지 『서버드 네프』 창간호의 사설을 썼다. 1942년 7월 6일 체포되어 참모본부 특별재판소에서 사형을 선고받고 10월 9일 처형되었다.',
            'Born in Kassa (Košice), he joined the labour movement as a university student in Prague. After the First Vienna Award of November 1938 he went underground and worked in Hungary, linking up with the Communist Party’s representative. From December 1940 he organised the party’s anti-war struggle and led the Independence Committee, which staged the demonstrations of 6 October and 1 November 1941. He prepared the Christmas 1941 issue of Népszava and wrote the editorial of the first issue of the underground Szabad Nép on 1 February 1942. Arrested on 6 July 1942, he was sentenced to death by the special court of the Chief of the General Staff and executed on 9 October.'],
        fate: ['executed', '처형', 'Executed'],
        aliases: { ko: [], en: ['Zoltán Schönherz', 'Zoltan Schonherz', 'Schönherz Zoltán'] },
        sources: [S.huSchonherz],
        facts: {
            years: { claim: '1905–1942', locator: 'bevezető', excerpt: '(Kassa, 1905. július 25. – Budapest, 1942. október 9.)' },
            citizenship: { claim: 'Hungarian engineer and labour leader', locator: 'bevezető', excerpt: 'magyar elektromérnök, pártmunkás, munkásmozgalmi vezető' },
            nationalOrigin: { claim: 'born in Kassa', locator: 'bevezető', excerpt: 'Schönherz Zoltán (Kassa, 1905. július 25.' },
            bio: [
                { claim: 'went underground after the First Vienna Award', locator: 'Élete', excerpt: 'majd az első bécsi döntést (1938. november) követően illegalitásba vonult és Magyarországon dolgozott tovább' },
                { claim: 'Independence Committee demonstrations 1941', locator: 'Élete', excerpt: 'Ez a szervezet rendezte meg 1941. október 6-án a Batthyány-örökmécsesnél, valamint november 1-jén a Kossuth és Táncsics sírjánál lezajlott tüntetéseket.' },
                { claim: 'arrested and executed 1942', locator: 'Élete', excerpt: 'Az ítélet végrehajtására október 9-én került sor a Margit körúti fogház udvarán.' },
            ],
        },
        activities: [
            { functionId: 'organizing', affiliationId: 'party-hungarian-communist', relation: 'membership', startYear: 1940, endYear: 1942, primary: true, claim: '공산당 반전 투쟁과 독립위원회 조직', locator: 'Élete', excerpt: '1940 decemberétől szervezte a KMP háborúellenes harcát, valamint a Függetlenségi Bizottságot irányította.' },
        ],
        career: [
            ['1920년대', '프라하 대학생, 노동운동 참여', 'Student in Prague; joined the labour movement'],
            ['1938', '제1차 빈 중재 뒤 지하로 들어가 헝가리에서 활동', 'Went underground in Hungary after the First Vienna Award'],
            ['1940–1942', '공산당 반전 투쟁 조직, 독립위원회 지도', 'Organised the party’s anti-war work; led the Independence Committee'],
            ['1942', '『서버드 네프』 창간호 사설 집필', 'Wrote the editorial of the first Szabad Nép'],
            ['1942', '체포, 군 특별재판 사형 선고, 처형', 'Arrested, sentenced by a military special court, executed'],
        ],
    }),
    person({
        id: 'ferenc-rozsa',
        given: ['페렌츠', 'Ferenc'], family: ['로저', 'Rózsa'], nativeName: 'Rózsa Ferenc', years: '1906–1942',
        epithet: ['지하 기관지 『서버드 네프』의 첫 편집인으로 1942년 체포되어 구금 중 숨진 공산주의자',
            'Communist who was the first editor of the underground Szabad Nép and died in custody after his arrest in 1942'],
        bio: ['부다페스트에서 태어나 카를스루에와 드레스덴에서 토목공학을 공부했고, 드레스덴 사회주의 학생연맹을 이끌며 나치의 위험을 경고하는 글을 썼다. 1931년 귀국해 형 리하르드의 권유로 지하 공산주의 운동에 들어갔고, 1935년 공산주의 청년동맹 간부가 되었다. 1938년부터 사회민주당과 노동조합 안의 공산당 조직을 만들었고, 1941년 6월 독소전쟁 뒤 지하로 들어가 「독립운동」을 이끌었다. 1942년 2월 『서버드 네프』 편집장이 되었다가 6월 1일 체포되었고, 2주 뒤 석연치 않은 상황에서 숨졌다.',
            'Born in Budapest, he studied civil engineering in Karlsruhe and Dresden, where he led the socialist students’ association and wrote warnings against the Nazis. Back in Hungary in 1931, he was drawn by his brother Richárd into the underground Communist movement and in 1935 joined the leadership of the Communist Youth League. From 1938 he built Communist cells inside the Social Democratic Party and the trade unions, and after June 1941 he went underground as a leader of the “independence movement”. Editor-in-chief of Szabad Nép from February 1942, he was arrested on 1 June and died two weeks later in unclear circumstances.'],
        fate: ['killed', '구금 중 사망', 'Died in custody'],
        aliases: { ko: [], en: ['Ferenc Rózsa', 'Ferenc Rozsa', 'Rózsa Ferenc'] },
        sources: [S.huRozsa, S.rozsa],
        facts: {
            years: { claim: '1906–1942', source: S.rozsa, locator: 'lead', excerpt: '4 December 1906 – 13 June 1942' },
            citizenship: { claim: 'Hungarian Communist', source: S.rozsa, locator: 'lead', excerpt: 'was a Hungarian Communist leader, anti-fascist activist and journalist.' },
            nationalOrigin: { claim: 'born in Budapest', locator: 'bevezető', excerpt: 'Rózsa Ferenc (Budapest, 1906. december 4.' },
            bio: [
                { claim: 'joined the underground movement through his brother', locator: 'Élete', excerpt: 'Miután hazatért, Richárd bátyja bevonta az illegális kommunista mozgalomba.' },
                { claim: 'editor-in-chief of Szabad Nép from February 1942', locator: 'Élete', excerpt: 'Az 1942. február 1-jétől a kommunista párt lapjának, a Szabad Népnek lett a főszerkesztője' },
                { claim: 'arrested 1 June 1942, died in unclear circumstances', locator: 'Élete', excerpt: 'Kétheti fogság után tisztázatlan körülmények között elhunyt' },
            ],
        },
        activities: [
            { functionId: 'propaganda', affiliationId: 'party-hungarian-communist', relation: 'membership', startYear: 1942, endYear: 1942, primary: true, claim: '『서버드 네프』 편집장', locator: 'Élete', excerpt: 'Az 1942. február 1-jétől a kommunista párt lapjának, a Szabad Népnek lett a főszerkesztője' },
            { functionId: 'organizing', affiliationId: 'party-hungarian-communist', relation: 'membership', startYear: 1932, endYear: 1942, claim: '공산당 지하 조직가', source: S.rozsa, locator: 'Biography', excerpt: 'he returned to Hungary and became a member of the Hungarian Communist Party the next year' },
        ],
        career: [
            ['1920년대', '카를스루에·드레스덴 유학, 사회주의 학생연맹 지도', 'Studied in Karlsruhe and Dresden; led the socialist students’ association'],
            ['1932', '헝가리 공산당 입당', 'Joined the Hungarian Communist Party'],
            ['1935', '공산주의 청년동맹 지도부', 'Leadership of the Communist Youth League'],
            ['1938–1941', '사회민주당·노동조합 안 공산당 조직 구축', 'Built Communist cells in the Social Democratic Party and unions'],
            ['1942', '『서버드 네프』 편집장, 체포 뒤 구금 중 사망', 'Editor of Szabad Nép; died in custody after arrest'],
        ],
    }),
];

const terms = [
    term({
        id: 'vienna-awards', ko: '빈 중재', en: 'Vienna Awards', category: 'international', period: '1938–1940', startYear: 1938, endYear: 1940,
        definition: ['나치 독일과 파시스트 이탈리아가 빈 벨베데레 궁에서 내린 두 차례의 영토 중재. 1938년 11월 2일 제1차 중재는 남부 슬로바키아와 남부 루테니아를 체코슬로바키아에서, 1940년 8월 30일 제2차 중재는 북부 트란실바니아를 루마니아에서 떼어 헝가리에 넘겼다.',
            'Two territorial arbitrations delivered by Nazi Germany and Fascist Italy at the Belvedere Palace in Vienna. The First Award of 2 November 1938 transferred southern Slovakia and southern Ruthenia from Czechoslovakia to Hungary; the Second Award of 30 August 1940 transferred Northern Transylvania from Romania to Hungary.'],
        body: ['두 중재는 모두 독일 외무장관 리벤트로프와 이탈리아 외무장관 치아노가 주재했다. 제1차 빈 중재는 뮌헨 협정의 직접적 결과로, 헝가리는 약 1만 1900㎢와 인구 약 87만 명을 얻었다. 제2차 빈 중재는 헝가리와 루마니아의 협상이 결렬되고 양국 군대가 국경에 모인 상황에서 내려졌고, 북부 트란실바니아 4만 3492㎢가 헝가리로 넘어갔다.\n\n헝가리는 이로써 트리아농 조약으로 잃은 땅의 일부를 되찾았지만 독일·이탈리아에 더 깊이 묶였다. 진주 과정에서 이프와 트레즈네아에서 루마니아 주민이 학살되었다. 두 중재로 얻은 땅은 제2차 세계대전 뒤 모두 원래 나라에 돌아갔다.',
            'Both awards were presided over by the German foreign minister Ribbentrop and the Italian foreign minister Ciano. The First Vienna Award was a direct consequence of the Munich Agreement and gave Hungary about 11,900 km² with some 870,000 inhabitants. The Second Vienna Award came after Hungarian–Romanian talks broke down and both armies massed on the border, and gave Hungary the 43,492 km² of Northern Transylvania.\n\nHungary thus regained part of the lands lost at Trianon but was bound more tightly to Germany and Italy. Romanian villagers were massacred at Ip and Treznea as Hungarian troops marched in. All the territory gained by the two awards was returned after the Second World War.'],
        aliases: { ko: ['제1차 빈 중재', '제2차 빈 중재'], en: ['First Vienna Award', 'Second Vienna Award', 'Vienna Arbitration', 'bécsi döntések'] },
        people: ['joachim-von-ribbentrop', 'galeazzo-ciano', 'miklos-horthy', 'bela-imredy', 'pal-teleki'],
        events: ['hungary-axis-1938-1944'],
        sources: [S.v1, S.v2], locator: 'lead; Background; Award sections',
    }),
    term({
        id: 'hungarian-anti-jewish-laws', ko: '헝가리 유대인법', en: 'Hungarian anti-Jewish laws', category: 'repression', period: '1938–1942', startYear: 1938, endYear: 1942,
        definition: ['1938~1942년 헝가리 의회가 독일 뉘른베르크법을 본떠 만든 일련의 반유대주의 법률. 제1차 법(1938)은 전문직과 상공업의 유대인 비율을 20%로 제한했고, 제2차 법(1939)은 유대인을 인종으로 정의하며 제한을 강화했으며, 제3차 법(1941)은 유대인과 비유대인의 결혼과 성관계를 금지했다.',
            'A series of antisemitic laws passed by the Hungarian parliament in 1938–1942 in emulation of Germany’s Nuremberg Laws. The First Law (1938) capped Jews at 20 per cent in the professions and business; the Second (1939) defined Jews racially and tightened the limits; the Third (1941) banned marriage and sexual relations between Jews and non-Jews.'],
        body: ['제1차 유대인법은 더라니 정부가 제출해 임레디 정부 초기인 1938년 5월 통과되었다. 임레디가 1938년 12월 제출한 제2차 유대인법은 텔레키 정부 때인 1939년 5월 통과되어, 조부모 가운데 둘 이상이 유대인으로 태어난 사람을 유대인으로 보고 전문직 비율을 6%로 낮췄으며 공직과 신문 편집에서 유대인을 배제하고 투표권도 제한했다. 바르도시 정부는 1941년 8월 제3차 법을 만들었고, 1942년에는 유대인의 토지 소유를 금지하는 법이 뒤따랐다.\n\n이 법들로 수만 명이 일자리와 사업을 잃었고, 1939년 법만으로 약 25만 명이 생계를 잃었다. 군 복무에서 배제된 유대인 남성은 노동봉사로 징집되었다. 미국 홀로코스트 기념관은 이 시기를 헝가리 정부가 스스로 유대인을 박해한 홀로코스트의 첫 단계로 본다.',
            'The First Jewish Law, introduced by the Darányi government, passed in May 1938 at the start of Imrédy’s premiership. The Second, introduced by Imrédy in December 1938 and passed under Teleki in May 1939, counted as Jewish anyone with two or more grandparents born Jewish, cut the professional quota to 6 per cent, excluded Jews from public employment and newspaper editing and restricted their vote. Bárdossy’s government enacted the Third Law in August 1941, and a 1942 law banned Jews from owning land.\n\nTens of thousands lost jobs and businesses; the 1939 law alone cost some 250,000 people their livelihood. Jewish men, barred from the army, were conscripted into labour service. The US Holocaust Memorial Museum treats this period as the first stage of the Holocaust in Hungary, in which the Hungarian government persecuted Jews on its own initiative.'],
        aliases: { ko: ['제1차 유대인법', '제2차 유대인법', '제3차 유대인법'], en: ['First Jewish Law', 'Second Jewish Law', 'Third Jewish Law', 'zsidótörvények'] },
        people: ['bela-imredy', 'pal-teleki', 'laszlo-bardossy', 'miklos-horthy'],
        events: ['hungary-axis-1938-1944'],
        sources: [S.ushmm, S.holo], locator: 'Anti-Jewish laws sections',
    }),
    term({
        id: 'kamianets-podilskyi-massacre', ko: '카미야네츠포딜스키 학살', en: 'Kamianets-Podilskyi massacre', category: 'repression', period: '1941', startYear: 1941, endYear: 1941,
        definition: ['1941년 8월 27~28일 독일 점령하 소련 우크라이나의 카미야네츠포딜스키에서 프리드리히 예켈른 휘하의 친위대·경찰 부대가 유대인 2만 3600명을 쏘아 죽인 학살. 희생자 가운데 약 1만 6000명은 헝가리가 「외국인」이라며 추방한 유대인이었다.',
            'The shooting of 23,600 Jews at Kamianets-Podilskyi in German-occupied Soviet Ukraine on 27–28 August 1941 by SS and police units under Friedrich Jeckeln. Some 16,000 of the victims were Jews whom Hungary had deported as “aliens”.'],
        body: ['헝가리가 소련에 선전포고한 뒤 외국인 관리 당국은 시민권을 증명하지 못하는 유대인을 추방하기로 했고, 바르도시 총리가 7월 12일 명령에 서명했다. 폴란드·러시아 출신 유대인과 난민뿐 아니라 서류를 갖추지 못한 헝가리 유대인과 카르파티아 지역의 공동체 전체가 쾨뢰시메죄를 거쳐 독일군에 넘겨졌다.\n\n추방자들은 콜로미야에서 카미야네츠포딜스키까지 걸어서 끌려가 현지 유대인과 함께 학살되었다. 「최종 해결」의 첫 대규모 학살 가운데 하나로 꼽히며, 바르도시는 전후 인민재판소에서 이 추방에 대한 책임을 추궁받았다.',
            'After Hungary declared war on the Soviet Union, the agency for foreign nationals decided to deport Jews who could not prove their citizenship, and Prime Minister Bárdossy signed the order on 12 July. Polish and Russian Jews and refugees, but also Hungarian Jews without papers and whole communities in the Carpathian region, were handed over to the Germans via Kőrösmező.\n\nThe deportees were marched from Kolomyia to Kamianets-Podilskyi and murdered together with the local Jews. It is counted among the first large-scale massacres of the “Final Solution”, and after the war Bárdossy was held to account for the deportations before a People’s Court.'],
        aliases: { ko: ['카메네츠포돌스크 학살'], en: ['Kamenets-Podolsk massacre', 'Kamianets-Podilskyi Massacre'] },
        people: ['laszlo-bardossy'],
        events: ['hungary-axis-1938-1944'],
        sources: [S.kp, S.ushmmKp], locator: 'lead; History',
    }),
    term({
        id: 'novi-sad-raid-1942', ko: '노비사드 학살', en: 'Novi Sad raid', category: 'repression', period: '1942', startYear: 1942, endYear: 1942,
        definition: ['1942년 1월 헝가리군과 헌병대가 병합된 바치카에서 파르티잔 소탕을 구실로 벌인 학살. 1월 6일 추루그에서 시작해 20~23일 노비사드(우이비데크)에서 절정에 이르렀고, 연구에 따라 약 3300~4100명, 대부분 세르비아인과 유대인이 죽었다.',
            'A massacre carried out in January 1942 by the Hungarian army and gendarmerie in annexed Bačka on the pretext of fighting Partisans. Beginning at Čurug on 6 January, it culminated in Novi Sad (Újvidék) on 20–23 January; estimates of the dead, mostly Serbs and Jews, range from about 3,300 to 4,100.'],
        body: ['참모총장 솜버테이이 페렌츠가 징벌 작전을 명령했고, 바르도시 정부는 독일에 점령지 병력이 필요하다는 것을 보여 주려 했다. 노비사드에서 페케테헐미체이드네르 페렌츠의 부대는 혹한 속에 주민을 도나우강 강변으로 끌고 가 쏘고 시신을 얼음 구멍에 던졌다. 노비사드 시 행정장관 데아크 라슬로가 부다페스트에 알린 뒤에야 학살이 멈췄다.\n\n의원 버이치질린스키 엔드레가 의회에서 이를 고발했고, 칼러이 정부는 1943년 12월 책임자들을 군사재판에 넘겼으나 유죄 판결을 받은 장교들은 1944년 1월 독일로 달아났다. 헝가리어로는 「추운 날들」이라고도 불리며, 2013년 헝가리 대통령이 세르비아에 공식 사과했다.',
            'Chief of Staff Ferenc Szombathelyi ordered the punitive raids, and Bárdossy’s government wanted to show Germany that troops were needed in the occupied territories. In Novi Sad Ferenc Feketehalmy-Czeydner’s troops marched residents to the Danube in bitter cold, shot them and threw the bodies into holes in the ice. The killing stopped only after the city’s lord lieutenant, László Deák, alerted Budapest.\n\nThe deputy Endre Bajcsy-Zsilinszky denounced it in parliament, and Kállay’s government brought those responsible before a court martial in December 1943, but the convicted officers fled to Germany in January 1944. In Hungarian it is also called the “Cold Days”; in 2013 Hungary’s president formally apologised to Serbia.'],
        aliases: { ko: ['우이비데크 학살', '남부 바치카 습격'], en: ['Novi Sad massacre', 'Újvidék massacre', 'Raid in southern Bačka', 'újvidéki vérengzés', 'újvidéki hideg napok'] },
        people: ['laszlo-bardossy', 'miklos-kallay', 'miklos-horthy'],
        events: ['hungary-axis-1938-1944'],
        sources: [S.novisad, S.huNovisad], locator: 'lead; Prelude; Aftermath',
    }),
    term({
        id: 'hungarian-labour-service', ko: '헝가리 노동봉사제', en: 'Labour service (Hungary)', category: 'repression', period: '1939–1945', startYear: 1939, endYear: 1945,
        definition: ['1939~1945년 헝가리가 유대인 남성과 「믿을 수 없는」 사람들을 정규군 대신 비무장 노동부대에 징집한 제도(munkaszolgálat). 1941년부터 유대인을 분리해 표식 완장을 채우고 동부전선 근처로 보냈으며, 1944년 3월 이전에만 2만 5000~4만 2000명이 죽었다.',
            'The Hungarian system (munkaszolgálat) that conscripted Jewish men and others deemed “unreliable” into unarmed labour units instead of the army in 1939–1945. From 1941 Jews were segregated, made to wear armbands and sent near the Eastern Front; 25,000–42,000 died before March 1944 alone.'],
        body: ['1939년 국방법과 같은 해 5월의 정부령으로 텔레키 정부가 도입했다. 처음에는 군 복무에 부적합하다고 본 젊은이들의 단기 노동이었으나, 유대인법과 전쟁 속에 유대인과 소수민족, 좌파 반대자를 배제하고 모욕하는 제도로 커졌다.\n\n돈강의 제2군에는 약 1만 7000명의 유대인 노동봉사자가 따라갔다. 이들은 지뢰 제거와 중노동에 내몰렸고 굶주림과 감독관의 폭력으로 많이 죽었으며, 1943년 1월의 패주 때 손실이 특히 컸다. 시인 라드노티 미클로시와 작가 세르브 언털도 노동봉사 중에 숨졌다.',
            'It was introduced by the Teleki government under the 1939 defence act and a decree of May that year. At first short unarmed service for young men judged unfit for the army, amid the Jewish laws and the war it grew into an institution for excluding and humiliating Jews, national minorities and left-wing opponents.\n\nSome 17,000 Jewish labour servicemen accompanied the Second Army to the Don. Driven to clear mines and do heavy labour, many died of hunger and the violence of their guards, with especially heavy losses in the rout of January 1943. The poet Miklós Radnóti and the writer Antal Szerb died in labour service.'],
        aliases: { ko: ['헝가리 노동봉사대'], en: ['munkaszolgálat', 'Hungarian Labor Service System', 'Hungarian labour service'] },
        people: ['pal-teleki', 'gusztav-jany', 'miklos-kallay'],
        events: ['hungary-axis-1938-1944'],
        sources: [S.labour, S.huLabour, S.ushmm, S.army2], locator: 'lead; Origins; Operation Barbarossa',
    }),
];

module.exports = { event, people, terms };
