// Person cards for event-1944.js (Hungary 1944–1945), see lib.js person().
const { W, HU, person } = require('./lib');

const DE = t => 'https://de.wikipedia.org/wiki/' + t;

const S = {
    miklos: W('Béla_Miklós'),
    huMiklos: HU('Miklós_Béla'),
    wallenberg: W('Raoul_Wallenberg'),
    pfeffer: W('Karl_Pfeffer-Wildenbruch'),
    dePfeffer: DE('Karl_Pfeffer-Wildenbruch'),
    kasztner: W('Rezső_Kasztner'),
    huKasztner: HU('Kasztner_Rezső'),
    lutz: W('Carl_Lutz'),
};

// An activity with affiliationId null has no catalog affiliation (the Swedish
// legation, the Budapest Aid and Rescue Committee): person() marks every
// activity confirmed, so these are re-marked unresolved, as in event-horthy.js.
const unaffiliated = card => ({
    ...card,
    activities: card.activities.map(a => (a.affiliationId ? a : { ...a, affiliationStatus: 'unresolved', relation: 'unresolved' })),
});

module.exports = [
    person({
        id: 'bela-miklos',
        given: ['벨러', 'Béla'], family: ['미클로시', 'Miklós'], nativeName: 'Miklós Béla', years: '1890–1948',
        origin: { code: 'hungary', label: { ko: '헝가리 (세케이)', en: 'Hungarian (Székely)' } },
        epithet: ['1944년 10월 소련군 쪽으로 넘어가 데브레첸 임시국민정부를 이끈 헝가리 제1군 사령관',
            'Commander of the Hungarian First Army who went over to the Soviets in October 1944 and headed the provisional government in Debrecen'],
        bio: ['부다페스트의 세케이 가문에서 태어나 1910년 루도비카 사관학교를 마치고 제1차 세계대전에 참전했다. 1933~1936년 베를린 주재 무관, 1942년 10월부터 호르티 섭정의 군사실장을 지냈고 1943년 상급대장이 되었다. 1944년 8월 1일 제1군 사령관이 되어 추축국 이탈을 지지했고, 10월 15일 이탈 시도가 실패하자 이튿날 소련군 쪽으로 넘어가 라디오로 휘하 지휘관들에게 투항을 호소했다. 12월 데브레첸 임시국민의회에서 임시국민정부 총리로 뽑혀 1945년 11월 총선까지 재임했고, 이 정부가 소련과 휴전하고 독일에 선전포고했으며 인민재판소를 세웠다. 1947년 헝가리 독립당 의원이 되었으나 의석을 박탈당해 물러났고 1948년 숨져 군의 예우 없이 묻혔다.',
            'Born in Budapest into a Székely family, he graduated from the Ludovica Military Academy in 1910 and fought in the First World War. He was military attaché in Berlin from 1933 to 1936, headed Horthy’s military office from October 1942 and became colonel general in 1943. Given command of the First Army on 1 August 1944, he supported leaving the Axis; after the failed attempt of 15 October he went over to the Soviets the next day and urged his commanders by radio to defect. In December the Interim National Assembly in Debrecen elected him prime minister of the Provisional National Government, which made the armistice with the Soviets, declared war on Germany and set up people’s tribunals; he served until the November 1945 elections. Elected for the Hungarian Independence Party in 1947, he lost his seat, withdrew from public life and died in 1948, buried without military honours.'],
        fate: ['natural', '사인 불명 사망', 'Died of unknown causes'],
        aliases: { ko: ['달노키 미클로시 벨러'], en: ['Béla Miklós', 'Miklós Béla', 'Béla Miklós de Dálnok', 'Béla Dálnoki Miklós'] },
        sources: [S.miklos, S.huMiklos],
        facts: {
            years: { claim: '1890–1948', locator: 'lead', excerpt: '11 June 1890 – 21 November 1948' },
            citizenship: { claim: 'Hungarian officer and politician', locator: 'lead', excerpt: 'was a Hungarian military officer and politician who served as acting Prime Minister of Hungary' },
            nationalOrigin: [
                { claim: 'born into a Székely family', locator: 'Early career', excerpt: 'Béla Miklós was born into a Székely primipilus family in Budapest on 11 June 1890.' },
                { claim: 'old Székely family', source: S.huMiklos, locator: 'Élete és pályafutása', excerpt: 'Ősi székely lófő családból származott.' },
            ],
            bio: [
                { claim: 'Ludovica 1910, hussar lieutenant, First World War', locator: 'Early career', excerpt: 'After graduating from Ludovica Military Academy in 1910, he was promoted to Hussar Lieutenant. He participated in the First World War.' },
                { claim: 'military attaché in Berlin 1933–1936', source: S.huMiklos, locator: 'Élete és pályafutása', excerpt: '1933–1936 között Berlinben katonai attasé' },
                { claim: 'head of Horthy’s military office October 1942; colonel general 1943', locator: 'Early career', excerpt: 'he became military director of the office of Admiral Miklós Horthy, regent of Hungary, in October 1942. He was promoted to Colonel General in 1943.' },
                { claim: 'First Army from 1 August 1944, supported leaving the Axis', locator: 'Late World War II', excerpt: 'Miklós became commanding general of the Hungarian First Army from 1 August 1944 and he supported leaving the Axis powers and joining the Red Army.' },
                { claim: 'the attempt to leave the war failed', source: S.huMiklos, locator: 'Az 1944-es kiugrási kísérlet', excerpt: 'A kiugrási kísérlet azonban, a nem megfelelő előkészítettség miatt megbukott.' },
                { claim: 'defected on 16 October 1944', locator: 'Late World War II', excerpt: 'On 16 October 1944, Miklós was ordered to appear at the headquarters of German General Heinrici. Suspicious of an eventual arrest, he defected through the Hungarian front with one of his aides and two sergeants.' },
                { claim: 'radio appeal to his commanders', locator: 'Late World War II', excerpt: 'he spoke on the radio and made a plea for the commanding officers of his Hungarian First Army to defect with their units to the Soviets' },
                { claim: 'elected head of the interim government in Debrecen, until November 1945', locator: 'Interim government', excerpt: 'The Assembly elected the interim government, with Soviet approval, which was headed by Miklós. He remained in this post until the coming elections on 15 November 1945.' },
                { claim: 'armistice with the Soviets, war on Germany', source: S.huMiklos, locator: 'bevezető', excerpt: 'Az általa vezetett nemzeti kormány kötötte meg a szovjetekkel való fegyverszünetet és üzent hadat a náci Németországnak' },
                { claim: 'people’s tribunals', locator: 'Interim government', excerpt: "The Provisional National Government established the people's tribunes." },
                { claim: 'Independence Party seat 1947, cancelled', locator: 'Later career', excerpt: 'In the semi-free 1947 Hungarian parliamentary election, he won a seat for the party. However, all mandates of the Independence Party, which was defamed as "fascist", were canceled in November 1947' },
                { claim: 'withdrew from public life', locator: 'Later career', excerpt: 'After that, Miklós withdrew from public life.' },
                { claim: 'died 1948 of unknown causes, no military honours', locator: 'Later career', excerpt: 'He died one year later of unknown causes and was buried without military honour.' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-hungary', startYear: 1944, endYear: 1945, primary: true, claim: '임시국민정부 총리', locator: 'Interim government', excerpt: 'The Assembly elected the interim government, with Soviet approval, which was headed by Miklós. He remained in this post until the coming elections on 15 November 1945.' },
            { functionId: 'military', affiliationId: 'state-hungary', startYear: 1910, endYear: 1944, claim: '헝가리군 장교, 제1군 사령관', locator: 'Late World War II', excerpt: 'Miklós became commanding general of the Hungarian First Army from 1 August 1944' },
            { functionId: 'legislature', affiliationId: 'state-hungary', startYear: 1947, endYear: 1947, claim: '1947년 독립당 의원 당선', locator: 'Later career', excerpt: 'In the semi-free 1947 Hungarian parliamentary election, he won a seat for the party.' },
        ],
        career: [
            ['1910', '루도비카 사관학교 졸업, 경기병 소위', 'Graduated from the Ludovica Academy; hussar lieutenant'],
            ['1933–1936', '베를린 주재 무관', 'Military attaché in Berlin'],
            ['1942–1944', '섭정 군사실장', 'Head of the Regent’s military office'],
            ['1944', '제1군 사령관, 10월 16일 소련군 쪽으로 넘어감', 'Commander of the First Army; went over to the Soviets on 16 October'],
            ['1944–1945', '임시국민정부 총리', 'Prime minister of the Provisional National Government'],
            ['1947', '헝가리 독립당 의원 당선, 의석 박탈', 'Elected for the Hungarian Independence Party; seat cancelled'],
        ],
    }),
    unaffiliated(person({
        id: 'raoul-wallenberg',
        given: ['라울', 'Raoul'], family: ['발렌베리', 'Wallenberg'], nativeName: 'Raoul Wallenberg', years: '1912–?',
        citizenship: 'sweden',
        origin: { code: 'sweden', label: { ko: '스웨덴', en: 'Swedish' } },
        epithet: ['부다페스트 스웨덴 공사관에서 보호여권과 보호 가옥으로 유대인을 구하고 소련 구금 중 사라진 외교관',
            'Swedish diplomat who sheltered Budapest Jews with protective passports and safe houses, then vanished in Soviet custody'],
        bio: ['스톡홀름 근처에서 태어나 미국에서 건축을 공부했고, 1941년부터 무역회사 일로 부다페스트를 자주 오갔다. 1944년 6월 미국 전쟁난민위원회 구조 임무의 책임자로 뽑혀 7월 9일 스웨덴 공사관에 부임했고, 소지자를 스웨덴 국민으로 대우하게 하는 「보호여권」을 발급하고 건물 32채를 치외법권 구역으로 선포해 1만 명 가까이를 숨겼다. 10만 명 구조설은 과장으로 평가되며, 야드 바셈은 보호 서류를 받은 사람을 약 4,500명으로 본다. 1945년 1월 17일 포위전 중 스메르시에 간첩 혐의로 구금된 뒤 사라졌고, 소련은 1957년 그가 1947년 루뱌카에서 심장마비로 죽었다고 밝혔으나 사인과 날짜는 지금도 논란이다. 2016년 스웨덴 국세청이 그의 사망을 선고했다.',
            'Born near Stockholm, he studied architecture in the United States and from 1941 travelled often to Budapest for a trading company. Chosen in June 1944 to lead the rescue mission of the US War Refugee Board, he reached the Swedish legation in Budapest on 9 July issued “protective passports” identifying the bearers as Swedish subjects, and sheltered almost 10,000 people in 32 buildings he declared extraterritorial. Historians regard the claim that he saved 100,000 Jews as an exaggeration; Yad Vashem puts the number granted protective paperwork at about 4,500. Detained by SMERSH on suspicion of espionage during the siege on 17 January 1945, he disappeared; in 1957 the Soviet authorities said he had died of a heart attack in the Lubyanka in 1947, but the cause and date of his death have been disputed ever since. In 2016 the Swedish Tax Agency declared him dead.'],
        fate: ['', '소련 구금 중 실종', 'Disappeared in Soviet custody'],
        aliases: { ko: [], en: ['Raoul Wallenberg'] },
        sources: [S.wallenberg],
        facts: {
            years: { claim: 'born 1912, disappeared 1945; date of death unknown', locator: 'lead', excerpt: '4 August 1912 – disappeared 17 January 1945' },
            citizenship: { claim: 'Swedish diplomat', locator: 'lead', excerpt: 'was a Swedish architect, businessman, diplomat, and humanitarian' },
            nationalOrigin: { claim: 'Swedish family', locator: 'Early life', excerpt: 'Raoul Oscar Wallenberg (1888–1912), a Swedish naval officer' },
            bio: [
                { claim: 'born at Lidingö near Stockholm', locator: 'Early life', excerpt: 'Wallenberg was born in 1912 in Lidingö Municipality, near Stockholm' },
                { claim: 'architecture degree, Michigan 1935', locator: 'Early life', excerpt: 'Wallenberg graduated from the University of Michigan in 1935 with a degree in architecture.' },
                { claim: 'travelled to Budapest from 1941', locator: 'World War II', excerpt: 'He soon learned to speak Hungarian and, from 1941, made increasingly frequent travels to Budapest.' },
                { claim: 'appointed by the War Refugee Board’s Olsen in June 1944', locator: 'Recruitment by the War Refugee Board', excerpt: 'Olsen was introduced to Wallenberg by Lauer in June 1944 and came away from the meeting impressed and, shortly thereafter, appointed Wallenberg to lead the mission.' },
                { claim: 'arrived at the Swedish legation on 9 July 1944', locator: 'Mission to Budapest', excerpt: 'When Wallenberg reached the Swedish legation in Budapest on 9 July 1944' },
                { claim: 'protective passports', locator: 'Mission to Budapest', excerpt: 'they issued "protective passports" (German: Schutzpass), which identified the bearers as Swedish subjects awaiting repatriation and thus prevented their deportation.' },
                { claim: '32 extraterritorial buildings', locator: 'Mission to Budapest', excerpt: 'Wallenberg rented 32 buildings in Budapest and declared them to be extraterritorial, protected by diplomatic immunity.' },
                { claim: 'almost 10,000 people', locator: 'Mission to Budapest', excerpt: 'The buildings eventually housed almost 10,000 people.' },
                { claim: '100,000 an exaggeration; Yad Vashem about 4,500', locator: 'lead', excerpt: 'historians regard that figure as an exaggeration; Yad Vashem estimates the number of people granted protective paperwork as about 4,500 individuals.' },
                { claim: 'detained by SMERSH on 17 January 1945 and disappeared', locator: 'lead', excerpt: 'On 17 January 1945, during the Siege of Budapest by the Red Army, agents of SMERSH detained Wallenberg on suspicion of espionage, and he subsequently disappeared.' },
                { claim: 'Soviet 1957 account: died 1947 in the Lubyanka', locator: 'lead', excerpt: 'In 1957, 12 years after his disappearance, he was reported by Soviet authorities to have died of a suspected myocardial infarction on 17 July 1947 while imprisoned in the Lubyanka' },
                { claim: 'cause and date disputed', locator: 'lead', excerpt: 'his cause and date of death have been disputed ever since' },
                { claim: 'declared dead by the Swedish Tax Agency in 2016', locator: 'lead', excerpt: 'In 2016, the Swedish Tax Agency declared him dead in absentia, with the pro forma date of death noted as 31 July 1952.' },
            ],
        },
        activities: [
            { functionId: 'diplomacy', affiliationId: null, startYear: 1944, endYear: 1945, primary: true, claim: '부다페스트 스웨덴 공사관 외교관(구조 임무)', locator: 'lead', excerpt: "While serving as Sweden's special envoy in Budapest between July and December 1944, Wallenberg issued protective passports and sheltered Jews in buildings which he declared as Swedish territory." },
            { functionId: 'economy', affiliationId: null, startYear: 1936, endYear: 1944, claim: '중부유럽 무역회사 공동 소유주·국제 담당 이사', locator: 'World War II', excerpt: 'Within a year, Wallenberg was a joint owner and the International Director of the company.' },
        ],
        career: [
            ['1935', '미시간 대학 건축학 학위', 'Architecture degree, University of Michigan'],
            ['1936–1944', '중부유럽 무역회사 근무, 공동 소유주', 'Central European Trading Company; joint owner'],
            ['1944', '부다페스트 스웨덴 공사관 부임, 보호여권 발급', 'Joined the Swedish legation in Budapest; issued protective passports'],
            ['1945', '스메르시에 구금된 뒤 실종', 'Detained by SMERSH and disappeared'],
            ['2016', '스웨덴 국세청 사망 선고', 'Declared dead by the Swedish Tax Agency'],
        ],
    })),
    person({
        id: 'karl-pfeffer-wildenbruch',
        given: ['카를', 'Karl'], family: ['페퍼빌덴브루흐', 'Pfeffer-Wildenbruch'], nativeName: 'Karl Pfeffer-Wildenbruch', years: '1888–1971',
        citizenship: 'germany', origin: 'germany',
        epithet: ['부다페스트 포위전에서 항복을 거부하고 독일군을 지휘한 무장친위대 제9산악군단장',
            'Commander of the Waffen-SS IX Mountain Corps who led the German forces in the siege of Budapest and refused to surrender'],
        bio: ['1907년 군에 들어가 제1차 세계대전 때 참모장교로 콘스탄티노플의 독일 군사사절단에서 일했다. 1919년 경찰로 옮겨 칠레 경찰대 책임자, 경찰학교 감찰총감을 지냈고, 친위대에 들어가 힘러의 참모부에서 일했다. 1939년 말 친위대 경찰사단을, 1943년 라트비아인 제6친위군단을 맡았다. 1944년 12월 부다페스트의 제9친위산악군단장이 되어 1944년 12월 24일부터 1945년 2월 11일까지 포위전에서 독일군을 지휘했고, 모든 항복 권유를 거부해 길고 참혹한 포위전으로 이어졌다. 탈출 시도가 실패한 뒤 소련군 포로가 되어 1949년 징역 25년을 선고받았고, 1955년 풀려나 1971년 빌레펠트에서 교통사고로 숨졌다.',
            'He joined the army in 1907 and in the First World War served as a General Staff officer, including with the German military mission in Constantinople. Moving to the police in 1919, he headed Chile’s Carabineros and became inspector general of police schools, then joined the SS and served on Himmler’s staff. He commanded the SS Polizei Division from late 1939 and the VI SS Army Corps (Latvian) from 1943. Appointed commander of the IX SS Mountain Corps in Budapest in December 1944, he led the German forces in the siege from 24 December 1944 to 11 February 1945 and refused all invitations to surrender, setting off a long and bloody siege. Taken prisoner by the Soviets after the failed breakout, he was sentenced in 1949 to 25 years, released in 1955 and killed in a traffic accident at Bielefeld in 1971.'],
        fate: ['killed', '교통사고', 'Traffic accident'],
        aliases: { ko: [], en: ['Karl Pfeffer-Wildenbruch', 'Karl Paul Pfeffer-Wildenbruch'] },
        sources: [S.pfeffer, S.dePfeffer, S.wallenberg],
        facts: {
            years: { claim: '1888–1971', locator: 'lead', excerpt: '12 June 1888 – 29 January 1971' },
            citizenship: { claim: 'German SS and police official', locator: 'lead', excerpt: 'was a German SS and police (Ordnungspolizei) official during the Nazi era' },
            nationalOrigin: { claim: 'German officer born in Kalkberge-Rüdersdorf', source: S.dePfeffer, locator: 'Einleitung', excerpt: '* 12. Juni 1888 in Kalkberge-Rüdersdorf; † 29. Januar 1971 in Bielefeld) war ein deutscher Offizier' },
            bio: [
                { claim: 'army 1907; General Staff; Constantinople', locator: 'Career', excerpt: 'joined the army in 1907 and served in World War I. He joined the German General Staff, and served as a military attaché to the German military mission in Constantinople' },
                { claim: 'police 1919', locator: 'Career', excerpt: 'In August 1919 Pfeffer-Wildenbruch joined the police service' },
                { claim: 'Chief of the Chilean Carabineros', locator: 'Career', excerpt: 'In 1928 he went to Santiago de Chile, to serve as Chief of the Chilean Carabineros de Chile.' },
                { claim: 'inspector general of police schools 1936', locator: 'Career', excerpt: 'from May 1936 he was the Inspector General of Police schools' },
                { claim: 'joined the SS, Himmler’s staff', locator: 'Career', excerpt: 'Pfeffer-Wildenbruch joined the SS (No. 292 713) and served on the Personal Staff Reichsführer-SS' },
                { claim: 'SS Polizei Division end of 1939', locator: 'Career', excerpt: 'Pfeffer-Wildenbruch was given command of the 4th SS Polizei Division with the rank of SS-Gruppenführer' },
                { claim: 'VI SS Army Corps (Latvian) 1943', locator: 'Career', excerpt: 'In October 1943, Pfeffer-Wildenbruch was appointed commander of the newly formed VI SS Army Corps (Latvian)' },
                { claim: 'IX SS Mountain Corps in Budapest, siege 24 December–11 February', locator: 'Career', excerpt: 'In December 1944 Pfeffer-Wildenbruch was appointed commander of the IX SS Mountain Corps, stationed in Budapest, Hungary. He was in command of the German forces during the Battle of Budapest from 24 December 1944 to 11 February 1945.' },
                { claim: 'refused all invitations to surrender', source: S.wallenberg, locator: 'Disappearance', excerpt: 'the German commander of Budapest, SS Lieutenant General Karl Pfeffer-Wildenbruch, refused all invitations to surrender, setting in motion a protracted and bloody siege of Budapest' },
                { claim: 'captured in the breakout', locator: 'Career', excerpt: 'During the attempt to break out from Budapest, he was seriously wounded and was taken prisoner by the Soviet forces.' },
                { claim: 'breakout failed', source: S.dePfeffer, locator: 'Zeit des Nationalsozialismus', excerpt: 'Als der Ausbruch aus Budapest seiner etwa 500-köpfigen Gruppe scheiterte' },
                { claim: '25 years in 1949; released 1955', locator: 'Career', excerpt: 'On 10 August 1949 he was sentenced to 25 years. In 1955, he was released' },
                { claim: 'traffic accident 1971', locator: 'Career', excerpt: 'Pfeffer-Wildenbruch was killed in a traffic accident on 29 January 1971 at Bielefeld.' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: 'german-nazi', startYear: 1939, endYear: 1945, primary: true, claim: '무장친위대 사단장·군단장, 부다페스트 방어 지휘', locator: 'Career', excerpt: 'He was in command of the German forces during the Battle of Budapest from 24 December 1944 to 11 February 1945.' },
            { functionId: 'security', affiliationId: 'state-germany', startYear: 1919, endYear: 1943, claim: '경찰 지휘관, 경찰학교 감찰총감', locator: 'Career', excerpt: 'from May 1936 he was the Inspector General of Police schools' },
            { functionId: 'military', affiliationId: 'state-germany', startYear: 1907, endYear: 1919, claim: '제1차 세계대전 참모장교', locator: 'Career', excerpt: 'joined the army in 1907 and served in World War I. He joined the German General Staff' },
        ],
        career: [
            ['1907–1919', '독일군 장교, 참모장교', 'German army officer and General Staff officer'],
            ['1919', '경찰 입직', 'Joined the police'],
            ['1928', '칠레 경찰대 책임자', 'Chief of the Chilean Carabineros'],
            ['1936', '경찰학교 감찰총감', 'Inspector General of Police schools'],
            ['1939–1940', '친위대 경찰사단장', 'Commander, SS Polizei Division'],
            ['1943–1944', '제6친위군단(라트비아인)장', 'Commander, VI SS Army Corps (Latvian)'],
            ['1944–1945', '제9친위산악군단장, 부다페스트 방어 지휘', 'Commander, IX SS Mountain Corps; defence of Budapest'],
            ['1945–1955', '소련 포로, 1949년 징역 25년 선고', 'Soviet prisoner; sentenced to 25 years in 1949'],
        ],
    }),
    unaffiliated(person({
        id: 'rezso-kasztner',
        given: ['레죄', 'Rezső'], family: ['커스트네르', 'Kasztner'], nativeName: 'Kasztner Rezső', years: '1906–1957',
        citizenship: { code: 'hungary', label: { ko: '헝가리 (이후 이스라엘)', en: 'Hungary (later Israel)' } },
        origin: { code: 'hungary', label: { ko: '헝가리 (유대계)', en: 'Hungary (Jewish)' } },
        epithet: ['아이히만과 협상해 유대인 1,684명을 「커스트네르 열차」로 스위스에 보낸 시온주의자 변호사',
            'Zionist lawyer who negotiated with Eichmann to send 1,684 Jews to Switzerland on what became known as the Kasztner train'],
        bio: ['콜로즈바르(클루지나포카)의 유대인 공동체에서 태어나 15세에 시온주의자가 되어 유대계 신문 『우이 켈레트』 기자와 변호사로 일했다. 1941년 부다페스트로 옮겨 난민을 국경 너머로 들여오던 부다페스트 구호구조위원회의 지도자가 되었다. 1944년 여름 아이히만과 협상해 돈과 금, 다이아몬드를 대가로 유대인 1,684명을 아우슈비츠 대신 스위스로 보내는 「커스트네르 열차」를 성사시켰다. 열차는 베르겐벨젠으로 돌려졌다가 8월과 12월 두 차례에 걸쳐 스위스에 닿았다. 전후 이스라엘에서 정부 대변인이 되었으나 나치 협력 고발을 둘러싼 1955년 재판에서 「악마에게 영혼을 팔았다」는 판결을 받았고, 1957년 3월 총격을 받아 숨졌다. 1958년 대법원은 혐의 두 가지를 뒤집었다.',
            'Born into the Jewish community of Kolozsvár (Cluj-Napoca), he became a Zionist at fifteen and worked as a journalist for the Jewish paper Új Kelet and as a lawyer. Moving to Budapest in 1941, he became a leader of the Budapest Aid and Rescue Committee, which smuggled Jewish refugees into Hungary. In the summer of 1944 he negotiated with Eichmann to let 1,684 Jews leave for Switzerland instead of Auschwitz on what became known as the Kasztner train, in exchange for money, gold and diamonds. Diverted to Bergen-Belsen, the passengers reached Switzerland in two groups in August and December 1944. After the war he moved to Israel and became a government spokesman, but a 1955 ruling in a trial over charges that he had collaborated with the Nazis said he had “sold his soul to the devil”; he was shot in March 1957 and died of his wounds. In 1958 the Supreme Court overturned two of the charges.'],
        fate: ['assassinated', '암살', 'Assassinated'],
        aliases: { ko: [], en: ['Rezső Kasztner', 'Kasztner Rezső', 'Rudolf Kastner', 'Israel Kastner', 'Rudolf Israel Kastner'] },
        linkExpressions: [['en', 'Rudolf Kastner'], ['en', 'Israel Kastner'], ['en', 'Rudolf Israel Kastner']],
        sources: [S.kasztner, S.huKasztner],
        facts: {
            years: { claim: '1906–1957', locator: 'lead', excerpt: '1906 – 15 March 1957' },
            citizenship: { claim: 'Hungarian-Israeli journalist and lawyer', locator: 'lead', excerpt: 'was a Hungarian-Israeli journalist and lawyer' },
            nationalOrigin: [
                { claim: 'born into the Jewish community of Kolozsvár', locator: 'Childhood', excerpt: 'into a local community of 15,000 Jews' },
                { claim: 'his relatives were Kolozsvár Jews on the train list', source: S.huKasztner, locator: 'bevezető', excerpt: 'szerepelt 388 kolozsvári zsidó neve, akik Kasztner rokonai' },
            ],
            bio: [
                { claim: 'born in Kolozsvár 1906', locator: 'Childhood', excerpt: 'Kasztner was born in 1906 in Kolozsvár' },
                { claim: 'Zionist at 15', locator: 'Education', excerpt: 'he decided at the age of 15 to become a Zionist' },
                { claim: 'law school, then Új Kelet', locator: 'Early career', excerpt: 'He attended law school, as she wished, then worked full-time for Új Kelet after graduating' },
                { claim: 'Új Kelet a Jewish newspaper', locator: 'Education', excerpt: 'the local Jewish newspaper Új Kelet' },
                { claim: 'moved to Budapest 1941', locator: 'Rise of Nazism', excerpt: 'Kasztner, then 36 years old, decided to move to Budapest to look for a job' },
                { claim: 'leader of the Aid and Rescue Committee', locator: 'lead', excerpt: 'Kasztner was one of the leaders of the Budapest Aid and Rescue Committee (Va\'adat Ezrah Vehatzalah, or Vaada), which smuggled Jewish refugees into Hungary during World War II.' },
                { claim: 'repeated meetings with Eichmann in summer 1944', locator: 'Negotiations', excerpt: 'During the summer of 1944, Kasztner repeatedly met with Adolf Eichmann' },
                { claim: '1,684 Jews to Switzerland for money, gold and diamonds', locator: 'lead', excerpt: 'Kasztner negotiated with Adolf Eichmann, a senior SS officer and a mastermind of the Holocaust, to allow 1,684 Jews to leave instead for Switzerland on what became known as the Kastner train, in exchange for money, gold, and diamonds.' },
                { claim: 'diverted to Bergen-Belsen, then Switzerland in August and December 1944', source: S.huKasztner, locator: 'bevezető', excerpt: 'Az utasokat először egy bergen-belseni különleges (a hírhedt koncentrációs táborhoz közeli) lágerbe vitték, majd több hónap után két részletben, az első 318 fős csoportot 1944 augusztusában, a másodikat négy hónappal később Svájcba engedték.' },
                { claim: 'Israel, spokesman 1952', locator: 'lead', excerpt: 'Kasztner moved to Israel after the war, becoming a spokesman for the Ministry of Trade and Industry in 1952.' },
                { claim: 'accused of collaboration in 1953', locator: 'lead', excerpt: 'In 1953 he was accused of having been a Nazi collaborator in a pamphlet self-published by freelance writer Malchiel Gruenwald.' },
                { claim: '1955 ruling “sold his soul to the devil”', locator: 'lead', excerpt: 'a ruling in 1955 that Kasztner had, in the words of Judge Benjamin Halevy, "sold his soul to the devil"' },
                { claim: 'shot March 1957, died 12 days later', locator: 'lead', excerpt: 'Kasztner was shot on March 3, 1957, by Zeev Eckstein' },
                { claim: 'died of his injuries', locator: 'lead', excerpt: 'died of his injuries 12 days later' },
                { claim: 'Supreme Court 1958 overturned two charges, upheld one', locator: 'lead', excerpt: 'The Supreme Court of Israel overturned two of the charges against Kasztner in January 1958 in a 4–1 decision' },
                { claim: 'assassinated 1957', locator: 'lead', excerpt: 'He was assassinated in 1957 after an Israeli court accused him of having "sold his soul to the devil," a charge that was overturned by the Supreme Court of Israel in 1958.' },
            ],
        },
        activities: [
            { functionId: 'organizing', affiliationId: null, startYear: 1941, endYear: 1945, primary: true, claim: '부다페스트 구호구조위원회 지도자', locator: 'lead', excerpt: 'Kasztner was one of the leaders of the Budapest Aid and Rescue Committee (Va\'adat Ezrah Vehatzalah, or Vaada), which smuggled Jewish refugees into Hungary during World War II.' },
            { functionId: 'propaganda', affiliationId: null, startYear: null, endYear: 1941, claim: '유대계 신문 『우이 켈레트』 기자', locator: 'Early career', excerpt: 'He attended law school, as she wished, then worked full-time for Új Kelet after graduating' },
            { functionId: 'government', affiliationId: 'state-israel', startYear: 1952, endYear: 1955, claim: '이스라엘 상공부 대변인', locator: 'lead', excerpt: 'Kasztner moved to Israel after the war, becoming a spokesman for the Ministry of Trade and Industry in 1952.' },
        ],
        career: [
            ['1921', '시온주의 청년단 가입', 'Joined a Zionist youth group'],
            ['1930년대', '『우이 켈레트』 기자, 변호사', 'Journalist for Új Kelet; lawyer'],
            ['1941', '부다페스트로 이주', 'Moved to Budapest'],
            ['1944', '아이히만과 협상, 커스트네르 열차', 'Negotiations with Eichmann; the Kasztner train'],
            ['1952', '이스라엘 상공부 대변인', 'Spokesman, Israeli Ministry of Trade and Industry'],
            ['1955', '그루엔발트 명예훼손 재판 판결', 'Ruling in the Gruenwald libel trial'],
            ['1957', '피격, 사망', 'Shot and died of his wounds'],
        ],
    })),
    person({
        id: 'carl-lutz',
        given: ['카를', 'Carl'], family: ['루츠', 'Lutz'], nativeName: 'Carl Lutz', years: '1895–1975',
        citizenship: 'switzerland', origin: 'switzerland',
        epithet: ['부다페스트 주재 스위스 부영사로 보호증서와 보호 가옥으로 유대인 수만 명을 구한 외교관',
            'Swiss vice-consul in Budapest who saved tens of thousands of Jews with protective letters and safe houses'],
        bio: ['스위스 발첸하우젠에서 태어나 1913년 미국으로 건너갔고, 1920년부터 스위스 영사 업무를 맡아 미국과 야파에서 일했다. 1942년 부다페스트 주재 스위스 부영사가 되어 유대인 기구와 협력했다. 1944년 헝가리 정부와 나치와 협상해 팔레스타인 이주용 보호증서 8,000장을 허가받았는데, 이를 개인이 아닌 가족 단위로 적용하고 모두 1~8,000번 번호를 단 증서를 수만 장 더 발급했다. 부다페스트 곳곳의 가옥 약 76채를 스위스 공사관 별관으로 선포했고, 그중 「유리집」에는 약 3,000명이 피신했다. 6만 2,000명 넘게 구한 것으로 평가되지만 전후 권한을 넘어섰다는 비판을 받았다가 1958년에야 복권되었고, 1965년 야드 바셈의 「열방의 의인」이 되었다.',
            'Born in Walzenhausen, Switzerland, he emigrated to the United States in 1913 and from 1920 worked in the Swiss consular service in the US and in Jaffa. Appointed Swiss vice-consul in Budapest in 1942, he cooperated with the Jewish Agency. In 1944 he negotiated with the Hungarian government and the Nazis for permission to issue 8,000 protective letters for emigration to Palestine, applied it to families rather than individuals, and issued tens of thousands more letters, all numbered between one and 8,000. He declared some 76 houses around Budapest annexes of the Swiss legation; about 3,000 people found refuge at the “Glass House”. Credited with saving over 62,000 Jews, he was criticised after the war for exceeding his authority and rehabilitated only in 1958; in 1965 Yad Vashem named him one of the Righteous Among the Nations.'],
        fate: ['natural', '베른에서 사망', 'Died in Bern'],
        aliases: { ko: [], en: ['Carl Lutz', 'Carl Robert Lutz'] },
        sources: [S.lutz],
        facts: {
            years: { claim: '1895–1975', locator: 'lead', excerpt: '30 March 1895 – 12 February 1975' },
            citizenship: { claim: 'Swiss diplomat', locator: 'lead', excerpt: 'was a Swiss diplomat who most notably served as the Swiss Vice Consul to Hungary in Budapest from 1942 until the end of World War II' },
            nationalOrigin: { claim: 'born in Walzenhausen, Switzerland', locator: 'Early life and education', excerpt: 'Lutz was born 30 March 1895 in Walzenhausen, Switzerland' },
            bio: [
                { claim: 'emigrated to the US in 1913', locator: 'Early life and education', excerpt: 'In 1913, aged 18, Lutz emigrated to the United States' },
                { claim: 'Swiss consular corps from 1920', locator: 'Early life and education', excerpt: 'In 1920, Lutz found a job in the Swiss consular corps at the Swiss Legation in Washington, D.C.' },
                { claim: 'vice-consul in Jaffa 1935–1942', locator: 'Diplomatic career', excerpt: 'He was assigned in January 1935 as vice-consul to the Swiss Consulate General in Jaffa' },
                { claim: 'vice-consul in Budapest 1942, cooperated with the Jewish Agency', locator: 'Actions during the Second World War', excerpt: 'Appointed in 1942 as Swiss vice-consul in Budapest, Hungary, Lutz soon began cooperating with the Jewish Agency for Israel.' },
                { claim: 'negotiated permission for 8,000 protective letters', locator: 'Actions during the Second World War', excerpt: 'Lutz negotiated a special deal with the Hungarian government and the Nazis.  He gained permission to issue protective letters to 8,000 Hungarian Jews for emigration to Palestine.' },
                { claim: 'families, tens of thousands more letters numbered 1–8,000', locator: 'Actions during the Second World War', excerpt: 'Lutz deliberately used his permission for 8,000 as applying to families rather than individuals, and proceeded to issue tens of thousands of additional protective letters, all of them bearing a number between one and 8,000.' },
                { claim: 'some 76 safe houses', locator: 'Actions during the Second World War', excerpt: 'He also set up some 76 "safe houses" around Budapest, declaring them annexes of the Swiss legation' },
                { claim: 'Glass House, about 3,000', locator: 'Actions during the Second World War', excerpt: 'About 3,000 Hungarian Jews found refuge at the Glass House and in a neighboring building.' },
                { claim: 'saved over 62,000', locator: 'lead', excerpt: 'He is credited with saving over 62,000 Jews during the Second World War' },
                { claim: 'criticised for exceeding authority; rehabilitated 1958', locator: 'Legacy and honours', excerpt: 'Soon after the war, he was first criticized by the Swiss government for having exceeded his authority' },
                { claim: 'rehabilitated 1958', locator: 'Legacy and honours', excerpt: 'Many years later, in 1958, as part of Swiss national rethinking of the war years, Lutz was "rehabilitated" in terms of public reputation' },
                { claim: 'Righteous Among the Nations 1965', locator: 'Legacy and honours', excerpt: '1965, Lutz was the first Swiss national named to the list of "Righteous Among the Nations" by Yad Vashem' },
                { claim: 'died in Bern 1975', locator: 'Personal life', excerpt: 'Lutz died in Bern, Switzerland, in 1975, aged 79.' },
            ],
        },
        activities: [
            { functionId: 'diplomacy', affiliationId: 'state-switzerland', startYear: 1920, endYear: 1961, primary: true, claim: '스위스 외교관, 부다페스트 주재 부영사', locator: 'lead', excerpt: 'was a Swiss diplomat who most notably served as the Swiss Vice Consul to Hungary in Budapest from 1942 until the end of World War II' },
        ],
        career: [
            ['1913', '미국 이주', 'Emigrated to the United States'],
            ['1920', '워싱턴 스위스 공사관 근무 시작', 'Joined the Swiss Legation in Washington'],
            ['1935–1942', '야파 주재 스위스 부영사', 'Swiss vice-consul in Jaffa'],
            ['1942–1945', '부다페스트 주재 스위스 부영사', 'Swiss vice-consul in Budapest'],
            ['1952–1961', '브레겐츠 주재 스위스 총영사', 'Swiss consul general in Bregenz'],
            ['1965', '열방의 의인', 'Righteous Among the Nations'],
        ],
    }),
];
