// Person cards for event-1944.js (Hungary 1944–1945), see lib.js person().
const { W, HU, person } = require('./lib');

const E = t => W(encodeURI(t));
const H = t => HU(encodeURI(t));
const S = {
    veesenmayer: E('Edmund_Veesenmayer'),
    huVeesenmayer: H('Edmund_Veesenmayer'),
    endre: E('László_Endre'),
    huEndre: H('Endre_László_(politikus)'),
    baky: E('László_Baky'),
    huBaky: H('Baky_László'),
    jaross: E('Andor_Jaross'),
    huJaross: H('Jaross_Andor'),
    lakatos: E('Géza_Lakatos'),
    huLakatos: H('Lakatos_Géza'),
};

module.exports = [
    person({
        id: 'edmund-veesenmayer',
        given: ['에드문트', 'Edmund'], family: ['페젠마이어', 'Veesenmayer'], nativeName: 'Edmund Veesenmayer', years: '1904–1977',
        citizenship: 'germany', origin: 'germany',
        epithet: ['1944년 헝가리 주재 제국 전권대표로서 헝가리 정부에 유대인 이송을 압박한 친위대 외교관',
            'SS diplomat who, as Reich plenipotentiary in Hungary in 1944, pressed the Hungarian government to deport its Jews to Auschwitz'],
        bio: ['바트키싱겐에서 교사의 아들로 태어나 뮌헨에서 정치학을 공부해 1928년 박사 학위를 받았다. 1932년 나치당에 들어갔고, 오스트리아 슈슈니크 총리의 사임 공작, 1939년 체코슬로바키아 해체, 1941년 크로아티아 독립국 선포에 관여했다. 1944년 3월 독일의 헝가리 점령과 함께 친위대 여단지도자로서 헝가리 주재 제국 전권대표가 되어 게슈타포 등 국방군 밖의 점령 기관을 지휘했고, 헝가리 정부에 유대인의 아우슈비츠 이송을 압박했다. 6월에는 리벤트로프에게 약 34만 명의 유대인이 제국으로 넘겨졌다고 보고했고, 10월에는 화살십자당의 권력 장악을 도왔다. 1949년 빌헬름가 재판에서 징역 20년을 선고받았으나 1951년 풀려났고, 1977년 다름슈타트에서 숨졌다.',
            'Born in Bad Kissingen, the son of a schoolteacher, he studied political science in Munich and took his doctorate in 1928. He joined the Nazi Party in 1932 and took part in forcing the resignation of Austria’s Chancellor Schuschnigg, the dismemberment of Czechoslovakia in 1939 and the proclamation of the Independent State of Croatia in 1941. Promoted to SS-Brigadeführer, he became Reich plenipotentiary in Hungary when Germany occupied it in March 1944, with authority over all occupying forces except the Wehrmacht, chiefly the Gestapo, and pressed the Hungarian government to deport its Jews to Auschwitz. In June he cabled Ribbentrop that some 340,000 Jews had been delivered to the Reich, and in October he helped the Arrow Cross take power. Sentenced to 20 years at the Ministries Trial in 1949, he was released in 1951 and died in Darmstadt in 1977.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: ['베젠마이어'], en: ['Edmund Veesenmayer'] },
        sources: [S.veesenmayer, S.huVeesenmayer],
        facts: {
            years: { claim: '1904–1977', locator: 'lead', excerpt: '12 November 1904 – 24 December 1977' },
            citizenship: { claim: 'German SS functionary', locator: 'lead', excerpt: 'was a high-ranking German SS functionary and Holocaust perpetrator during the Nazi era' },
            nationalOrigin: [
                { claim: 'German economist and diplomat of the Third Reich', source: S.huVeesenmayer, locator: 'bevezető', excerpt: 'vezető német közgazdász, a Harmadik Birodalom diplomatája' },
                { claim: 'son of a schoolteacher from Oberstaufen', locator: 'Early life', excerpt: 'Veesenmayer was the son of school teacher Franz Xaver Veesenmayer from Oberstaufen in Kempten (Allgäu).' },
            ],
            bio: [
                { claim: 'born in Bad Kissingen', source: S.huVeesenmayer, locator: 'bevezető', excerpt: 'Edmund Veesenmayer (Bad Kissingen, 1904. november 12.' },
                { claim: 'son of a schoolteacher', locator: 'Early life', excerpt: 'Veesenmayer was the son of school teacher Franz Xaver Veesenmayer' },
                { claim: 'doctorate in political science in Munich 1928', locator: 'Early life', excerpt: 'From 1923 to 1926 he studied political science in Munich, where he received a doctorate in political science in 1928.' },
                { claim: 'joined the Nazi Party in 1932', locator: 'SS career', excerpt: 'Veesenmayer joined the Nazi Party (NSDAP) in November 1932' },
                { claim: 'Schuschnigg’s resignation', locator: 'SS career', excerpt: 'forcing the resignation of Chancellor Kurt Schuschnigg' },
                { claim: 'dismembering Czechoslovakia 1939', locator: 'SS career', excerpt: "His next job was dismembering Czechoslovakia and making Jozef Tiso's Slovakia subservient to Nazi Germany in March 1939." },
                { claim: 'proclamation of the Independent State of Croatia 1941', locator: 'SS career', excerpt: 'Here, he arranged (with Ustashe leader Slavko Kvaternik) the proclamation of the Independent State of Croatia' },
                { claim: 'Brigadeführer and Reich plenipotentiary in Hungary', locator: 'SS career', excerpt: 'On 15 March 1944, he was promoted to SS-Brigadeführer and became Reich plenipotentiary after the German occupation of Hungary.' },
                { claim: 'authority over occupying forces except the Wehrmacht, chiefly the Gestapo', source: S.huVeesenmayer, locator: 'Élete', excerpt: 'a Wehrmachton kívül minden megszállóerő (főleg a Gestapo) fölött rendelkezési joga volt' },
                { claim: 'pressured Hungary to deport Jews to Auschwitz', locator: 'lead', excerpt: 'Installed as the German plenipotentiary to Hungary in March 1944, he pressured the Hungarian government to cooperate in deporting Hungarian Jews to the Auschwitz death camp.' },
                { claim: '340,000 reported to Ribbentrop', locator: 'SS career', excerpt: 'On 15 June 1944, Veesenmayer told Joachim von Ribbentrop in a telegram that some 340,000 Jews had been delivered to the Reich.' },
                { claim: 'helped the Arrow Cross take power', source: S.huVeesenmayer, locator: 'Élete', excerpt: 'A Szálasi-puccs során segítséget nyújtott a nyilas hatalomátvételhez' },
                { claim: '20 years at the Ministries Trial 1949', locator: 'Trial and conviction', excerpt: "In the Ministries Trial in 1949, Veesenmayer received a sentence of 20 years' imprisonment" },
                { claim: 'released 1951', locator: 'Trial and conviction', excerpt: 'Veesenmayer was released on 16 December 1951.' },
                { claim: 'died in Darmstadt 1977', locator: 'Trial and conviction', excerpt: 'At the end of his life, he lived in Darmstadt, where he died in 1977.' },
            ],
        },
        activities: [
            { functionId: 'diplomacy', affiliationId: 'state-germany', startYear: 1941, endYear: 1945, primary: true, claim: '1944년 헝가리 주재 제국 전권대표', locator: 'SS career', excerpt: 'On 15 March 1944, he was promoted to SS-Brigadeführer and became Reich plenipotentiary after the German occupation of Hungary.' },
            { functionId: 'organizing', affiliationId: 'german-nazi', startYear: 1932, endYear: 1945, claim: '나치당원·친위대원', locator: 'SS career', excerpt: 'Veesenmayer joined the Nazi Party (NSDAP) in November 1932' },
        ],
        career: [
            ['1928', '뮌헨에서 정치학 박사', 'Doctorate in political science, Munich'],
            ['1932', '나치당 입당', 'Joined the Nazi Party'],
            ['1939', '체코슬로바키아 해체 공작', 'Worked on dismembering Czechoslovakia'],
            ['1941', '자그레브에서 크로아티아 독립국 선포 주선', 'Arranged the proclamation of the Independent State of Croatia in Zagreb'],
            ['1944', '헝가리 주재 제국 전권대표', 'Reich plenipotentiary in Hungary'],
            ['1949–1951', '빌헬름가 재판 징역 20년, 1951년 석방', 'Sentenced to 20 years at the Ministries Trial; released 1951'],
        ],
    }),
    person({
        id: 'laszlo-endre',
        given: ['라슬로', 'László'], family: ['엔드레', 'Endre'], nativeName: 'Endre László', years: '1895–1946',
        epithet: ['1944년 내무부 차관으로 버키 라슬로와 함께 헝가리 유대인의 게토 수용과 아우슈비츠 이송을 맡은 극우 관료',
            'Interior Ministry state secretary who in 1944 ran the ghettoisation and deportation of Hungary’s Jews with László Baky'],
        bio: ['어보니의 부유한 집안에서 태어나 제1차 세계대전에 경기병 장교로 싸웠고, 평의회 공화국이 무너진 뒤 MOVE 등 반혁명 단체에 가담해 잔혹함으로 이름났다. 1923년부터 15년 동안 괴될뢰 수석 군수, 1938년 페스트주 부지사를 지내며 반유대법이 미흡하다며 해수욕장 출입 금지 등을 독자적으로 가했다. 1944년 독일 점령 뒤 여로시 언도르 밑에서 내무부 차관이 되어 유대인 게토 수용과 이송에 폭넓은 권한을 받았고, 버키 라슬로와 함께 아이히만을 도와 5~7월 40만 명이 넘는 헝가리 유대인을 이송했다. 9월 해임되었으나 화살십자당 집권 뒤 작전 지역 민정 담당 정부위원이 되었다. 1945년 달아났다가 미군에 붙잡혀 넘겨졌고, 1946년 사형 선고를 받아 교수형을 당했다.',
            'Born into a wealthy Abony family, he served as a hussar officer in the First World War and after the fall of the Soviet Republic joined counter-revolutionary groups such as MOVE, noted for his extreme cruelty. Chief magistrate of Gödöllő from 1923 and deputy lord-lieutenant of Pest county from 1938, he called the anti-Jewish laws too mild and imposed his own restrictions, such as banning Jews from beaches. After the German occupation in 1944 he became state secretary under Interior Minister Andor Jaross with far-reaching powers to ghettoise and deport the Jews, and with László Baky helped Eichmann deport over 400,000 Hungarian Jews between May and July. Removed in September, he returned under the Arrow Cross as commissioner for civil administration in the operational areas. Captured by US forces after fleeing in 1945, he was handed back, sentenced to death and hanged in 1946.'],
        fate: ['executed', '처형(교수형)', 'Executed by hanging'],
        aliases: { ko: [], en: ['László Endre', 'Laszlo Endre', 'Endre László'] },
        sources: [S.endre, S.huEndre],
        facts: {
            years: { claim: '1895–1946', locator: 'lead', excerpt: 'January 1, 1895 – March 29, 1946' },
            citizenship: { claim: 'Hungarian right-wing politician', locator: 'lead', excerpt: 'was a Hungarian right-wing politician and collaborator with the Nazis during the Second World War' },
            nationalOrigin: { claim: 'Hungarian politician born in Abony', source: S.huEndre, locator: 'bevezető', excerpt: 'fajvédő magyar politikus, belügyi államtitkár' },
            bio: [
                { claim: 'born into a wealthy Abony family', locator: 'Early years', excerpt: 'Born into a wealthy Abony family' },
                { claim: 'hussar officer from 1915', source: S.huEndre, locator: 'Élete, pályafutása', excerpt: 'Az első világháborúban 1915-től huszártisztként vett részt' },
                { claim: 'joined counter-revolutionary organisations after the Soviet Republic', source: S.huEndre, locator: 'Élete, pályafutása', excerpt: 'A Tanácsköztársaság bukása után részt vett ellenforradalmi szervezetek' },
                { claim: 'MOVE, extreme cruelty', locator: 'Early years', excerpt: 'He became involved in the right wing nationalist society Magyar Országos Véderő Egyesület (MOVE) during which he became noted for his extreme cruelty' },
                { claim: 'chief magistrate of Gödöllő for 15 years from 1923', source: S.huEndre, locator: 'Élete, pályafutása', excerpt: '1923-ban Gödöllőn kinevezték főszolgabíróvá; e tisztséget 15 éven át töltötte be.' },
                { claim: 'deputy lord-lieutenant of Pest county 1938', source: S.huEndre, locator: 'Élete, pályafutása', excerpt: '1938-ban, miután Pest-Pilis-Solt-Kiskun vármegye alispánjává választották' },
                { claim: 'own anti-Jewish restrictions', locator: 'Early years', excerpt: "Endre argued that the Hungarian government's anti-Jewish laws were not harsh enough, and on his own initiative he imposed further restrictions on Jewish life, such as banning Jews from beaches and spas" },
                { claim: 'state secretary under Jaross', locator: 'Ministry of the Interior', excerpt: 'was appointed state secretary in the Ministry of the Interior in the Nazi-controlled government under Interior Minister Andor Jaross' },
                { claim: 'powers to ghettoise and deport', locator: 'Ministry of the Interior', excerpt: "He was given far-reaching powers to ghettoize and deport the country's Jewish population." },
                { claim: 'more than 400,000 deported May–July 1944', locator: 'Ministry of the Interior', excerpt: 'Along with László Baky, Endre and Jaross eagerly helped Adolf Eichmann amass and deport more than 400,000 Hungarian Jews between May and July 1944.' },
                { claim: 'removed in September', locator: 'Removal and return', excerpt: 'Endre was removed from power in September of the same year' },
                { claim: 'commissioner for civil administration in the operational areas', source: S.huEndre, locator: 'Élete, pályafutása', excerpt: '1944. október 29-én Szálasi a hadműveleti területek polgári közigazgatásának kormánybiztosává nevezte ki' },
                { claim: 'fled, captured by US forces, extradited', source: S.huEndre, locator: 'Élete, pályafutása', excerpt: '1945 márciusában Németországba menekült, ott az amerikai csapatok fogságába esett, és a magyar állam kérésére kiadták.' },
                { claim: 'sentenced to death by the People’s Tribunal', source: S.huEndre, locator: 'Élete, pályafutása', excerpt: 'A Népbíróság mint egyik háborús főbűnöst kötél általi halálra ítélte' },
                { claim: 'hanged 1946', locator: 'Trial and execution', excerpt: 'Endre was hanged by way of the Austro-Hungarian pole method on March 29, 1946.' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-hungary', startYear: 1923, endYear: 1945, primary: true, claim: '1944년 내무부 행정 차관', locator: 'Ministry of the Interior', excerpt: 'was appointed state secretary in the Ministry of the Interior in the Nazi-controlled government under Interior Minister Andor Jaross' },
        ],
        career: [
            ['1915–1918', '경기병 장교', 'Hussar officer'],
            ['1919–1921', '반혁명 단체 활동', 'Active in counter-revolutionary groups'],
            ['1923–1938', '괴될뢰 수석 군수', 'Chief magistrate of Gödöllő'],
            ['1938–1944', '페스트주 부지사', 'Deputy lord-lieutenant of Pest county'],
            ['1944', '내무부 행정 차관', 'Administrative state secretary, Interior Ministry'],
            ['1944–1945', '작전 지역 민정 담당 정부위원', 'Commissioner for civil administration in the operational areas'],
            ['1946', '인민재판소 사형 선고, 처형', 'Sentenced by the People’s Tribunal and executed'],
        ],
    }),
    person({
        id: 'laszlo-baky',
        given: ['라슬로', 'László'], family: ['버키', 'Baky'], nativeName: 'Baky László', years: '1898–1946',
        epithet: ['헌병대 출신의 국민사회주의자로, 1944년 내무부 차관으로서 엔드레 라슬로와 함께 유대인 이송을 맡은 인물',
            'Gendarmerie officer turned National Socialist who as state secretary for the interior in 1944 ran the deportation of Jews with László Endre'],
        bio: ['부다페스트에서 태어나 사관학교를 나와 제1차 세계대전에 장교로 싸웠고, 1919년 세게드에서 폭력적인 반혁명 활동으로 이름을 얻은 뒤 헌병대 지도자로 떠올랐다. 1938년 헌병 소장으로 물러나 헝가리 국민사회주의당에 들어갔고, 1939년 의원이 되었으며 독일 자금의 신문 『머저르샤그』 편집인이 되었다. 1944년 독일 점령 뒤 내무부 정무 차관이 되어 엔드레 라슬로와 함께 유대인 이송을 맡았고, 4월 4일 아이히만 특무대와의 회의를 주재해 유대인 재산을 빼앗고 도시 게토로 옮긴 뒤 독일로 이송하기로 정했다. 여름에 해임되고 반호르티 쿠데타 모의로 체포되었으나 화살십자당 집권 뒤 국가보안국장이 되었다. 1945년 오스트리아에서 붙잡혀 넘겨졌고, 1946년 교수형을 당했다.',
            'Born in Budapest, a military academy graduate and First World War officer, he made his name in Szeged in 1919 with violent counter-revolutionary work and rose to be one of the Gendarmerie’s leading figures. Retiring in 1938 as a major-general, he joined the Hungarian National Socialist Party, entered parliament in 1939 and edited the German-funded Magyarság. After the German occupation in 1944 he became political state secretary for the interior and, with László Endre, took charge of deporting the Jews; on 4 April he chaired a meeting with Eichmann’s officers that agreed to seize Jews’ possessions and move them into urban ghettos before deportation to Germany. Removed in the summer and arrested for plotting a coup against Horthy, he headed the National Security Office under the Arrow Cross. Arrested in Austria in 1945 and returned, he was hanged in 1946.'],
        fate: ['executed', '처형(교수형)', 'Executed by hanging'],
        aliases: { ko: [], en: ['László Baky', 'Laszlo Baky', 'Baky László'] },
        sources: [S.baky, S.huBaky],
        facts: {
            years: { claim: '1898–1946', locator: 'lead', excerpt: '13 September 1898 – 29 March 1946' },
            citizenship: { claim: 'leading member of the Hungarian Nazi movement', locator: 'lead', excerpt: 'was a leading member of the Hungarian Nazi movement' },
            nationalOrigin: { claim: 'Hungarian far-right politician', source: S.huBaky, locator: 'bevezető', excerpt: 'szélsőjobboldali magyar politikus a két világháború között' },
            bio: [
                { claim: 'born in Budapest', source: S.huBaky, locator: 'bevezető', excerpt: 'Baky László (Budapest, 1898. szeptember 13.' },
                { claim: 'officer in World War I', source: S.huBaky, locator: 'Élete', excerpt: 'Katonatisztként vett részt az első világháború harcaiban' },
                { claim: 'academy graduate, Szeged 1919, gendarmerie leader', locator: 'lead', excerpt: 'A military academy graduate, he came to prominence in Szeged in 1919 for his violent counterrevolutionary work and rose through the ranks to become one of the leading figures in the Gendarmerie.' },
                { claim: 'left as major-general in 1938 for the National Socialist Party', locator: 'lead', excerpt: 'he finally left the gendarmes in 1938 (as a major-general) to join the Hungarian National Socialist Party' },
                { claim: 'deputy 1939', locator: 'lead', excerpt: 'He was elected as a deputy in 1939' },
                { claim: 'editor of Magyarság', locator: 'lead', excerpt: 'he was appointed editor of the German-funded newspaper Magyarság' },
                { claim: 'state secretary under Jaross', locator: 'lead', excerpt: 'Baky was elevated to state secretary in the Ministry of the Interior, under Andor Jaross.' },
                { claim: 'political state secretary', source: S.huBaky, locator: 'Élete', excerpt: '1944-ben a Belügyminisztérium politikai államtitkára lett.' },
                { claim: 'responsibility for deportations with Endre', locator: 'lead', excerpt: "Along with his fellow state secretary, László Endre, Baky eagerly accepted responsibility for deporting the country's Jews to the extermination camps." },
                { claim: 'chaired the meeting of 4 April', locator: 'lead', excerpt: "On 4 April he chaired a meeting attended by senior members of Adolf Eichmann's commando unit" },
                { claim: 'possessions seized, ghettos, deportation', locator: 'lead', excerpt: 'in which it was agreed that Jews, having first had their possessions seized, would be moved into urban ghettos before deportation to Germany' },
                { claim: 'removed and arrested for a coup plot', locator: 'lead', excerpt: 'Baky was removed from his positions during the summer of 1944 and was then arrested after conspiring, unsuccessfully, to lead a coup against Miklós Horthy' },
                { claim: 'head of the National Security Office', source: S.huBaky, locator: 'Élete', excerpt: 'de a nyilas hatalomátvételt követően a Nemzetbiztonsági Iroda vezetője lett' },
                { claim: 'fled, arrested in Austria', locator: 'lead', excerpt: 'He fled the country in 1945 but was arrested in Austria and returned to Budapest.' },
                { claim: 'sentenced to death', locator: 'lead', excerpt: 'Baky, Endre and Jaross were all tried, found guilty of crimes against the state and sentenced to death' },
                { claim: 'hanged 1946', locator: 'lead', excerpt: 'Baky was hanged by the Austro-Hungarian pole method on 29 March 1946.' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-hungary', startYear: 1944, endYear: 1945, primary: true, claim: '1944년 내무부 정무 차관', locator: 'lead', excerpt: 'Baky was elevated to state secretary in the Ministry of the Interior, under Andor Jaross.' },
            { functionId: 'security', affiliationId: 'state-hungary', startYear: 1919, endYear: 1938, claim: '헌병대 지도자', locator: 'lead', excerpt: 'A military academy graduate, he came to prominence in Szeged in 1919 for his violent counterrevolutionary work and rose through the ranks to become one of the leading figures in the Gendarmerie.' },
            { functionId: 'legislature', affiliationId: 'state-hungary', startYear: 1939, endYear: 1944, claim: '1939년 의원 당선', locator: 'lead', excerpt: 'He was elected as a deputy in 1939' },
        ],
        career: [
            ['1914–1918', '제1차 세계대전 장교', 'Officer in the First World War'],
            ['1919–1938', '헌병 장교, 소장으로 퇴역', 'Gendarmerie officer, retired as major-general'],
            ['1939–1944', '국회의원, 『머저르샤그』 편집인', 'Member of parliament; editor of Magyarság'],
            ['1944', '내무부 정무 차관', 'Political state secretary, Interior Ministry'],
            ['1944–1945', '국가보안국장', 'Head of the National Security Office'],
            ['1946', '인민재판소 사형 선고, 처형', 'Sentenced by the People’s Tribunal and executed'],
        ],
    }),
    person({
        id: 'andor-jaross',
        given: ['언도르', 'Andor'], family: ['여로시', 'Jaross'], nativeName: 'Jaross Andor', years: '1896–1946',
        epithet: ['체코슬로바키아의 헝가리계 정치인에서 1944년 스토여이 내각의 내무장관이 되어 유대인 이송을 조직한 인물',
            'Hungarian minority leader in Czechoslovakia who, as interior minister in Sztójay’s cabinet in 1944, organised the deportation of Jews'],
        bio: ['헝가리 왕국 코마롬주 코마롬체히(오늘날 슬로바키아 체히)에서 태어나, 1920년대 초 트리아농 조약으로 떨어져 나간 펠비데크의 헝가리계 정치에 뛰어들었다. 1933년 헝가리 국민당 대표, 1935년 프라하 하원 의원이 되었고 통일 헝가리당 서기장을 지냈다. 1938년부터 1940년까지 헝가리 정부의 펠비데크 담당 무임소 장관을 지냈고, 1940년 임레디 벨러와 극우 정당 헝가리 쇄신당을 세웠다. 1944년 독일 점령 뒤 스토여이 내각의 내무장관이 되어 차관 버키 라슬로·엔드레 라슬로와 함께 유대인 이송을 조직했다. 8월 17일 호르티의 압력으로 물러났다. 전후 서쪽으로 달아났다가 미군에 붙잡혀 헝가리로 넘겨졌고, 인민재판소에서 사형을 선고받아 1946년 총살되었다.',
            'Born in Komáromcsehi, Komárom County (now Čechy, Slovakia), he entered the politics of the Hungarian minority in Upper Hungary, cut off by Trianon, in the early 1920s. He became chairman of the Hungarian National Party in 1933 and a deputy in Prague in 1935, and was general secretary of the United Hungarian Party. From 1938 to 1940 he was Hungary’s minister without portfolio for Upper Hungary, and in 1940 he co-founded the far-right Party of Hungarian Renewal with Béla Imrédy. As interior minister in Sztójay’s cabinet after the German occupation of 1944, he organised the deportation of the Jews with his state secretaries László Baky and László Endre. He resigned under Horthy’s pressure on 17 August. After the war he fled west, was captured by the Americans, handed over to Hungary, sentenced to death by the People’s Tribunal and shot in 1946.'],
        fate: ['executed', '처형(총살)', 'Executed by firing squad'],
        aliases: { ko: [], en: ['Andor Jaross', 'Jaross Andor'] },
        sources: [S.jaross, S.huJaross],
        facts: {
            years: { claim: '1896–1946', locator: 'lead', excerpt: '23 May 1896 – 11 April 1946' },
            citizenship: { claim: 'politician in Czechoslovakia and later in Hungary', locator: 'lead', excerpt: 'was an ethnic Hungarian politician most active in interwar Czechoslovakia and later in Hungary during World War II' },
            nationalOrigin: { claim: 'ethnic Hungarian', locator: 'lead', excerpt: 'was an ethnic Hungarian politician' },
            bio: [
                { claim: 'born in Komáromcsehi', locator: 'lead', excerpt: 'Born in Komáromcsehi, in the Komárom County of the Kingdom of Hungary (present-day Čechy, Slovakia)' },
                { claim: 'entered Upper Hungary politics in the early 1920s', source: S.huJaross, locator: 'Élete', excerpt: 'az 1920-as évek elején kapcsolódott be az anyaországtól a trianoni döntéssel elszakított Felvidék politikai életébe' },
                { claim: 'chairman of the Hungarian National Party 1933', source: S.huJaross, locator: 'Élete', excerpt: '1925-ben pedig a Magyar Nemzeti Párt egyik országos alelnöke lett, nyolc évvel később pedig elnöke' },
                { claim: 'Prague Chamber of Deputies 1935', source: S.huJaross, locator: 'Élete', excerpt: '1935-ben a prágai Képviselőház tagjává vált.' },
                { claim: 'general secretary of the United Hungarian Party', locator: 'lead', excerpt: 'he became general secretary of the United Hungarian Party' },
                { claim: 'minister without portfolio for Upper Hungary 1938–1940', source: S.huJaross, locator: 'Élete', excerpt: '1938-tól 1940-ig a felvidéki ügyek tárcanélküli minisztere volt a mindenkori magyar kormányban' },
                { claim: 'founded the Party of Hungarian Renewal with Imrédy 1940', source: S.huJaross, locator: 'Élete', excerpt: '1940-ben Imrédy Bélával megalakította a szélsőjobboldali Magyar Megújulás Pártját.' },
                { claim: 'interior minister in the Sztójay cabinet', source: S.huJaross, locator: 'Élete', excerpt: 'A Sztójay-kormányban belügyminiszteri tisztséget kapott.' },
                { claim: 'organised the deportation with Baky and Endre', source: S.huJaross, locator: 'Élete', excerpt: 'Államtitkárai, Baky László és Endre László segítségével ekkor megszervezte a zsidók deportálását.' },
                { claim: 'resigned under Horthy’s pressure on 17 August 1944', source: S.huJaross, locator: 'Élete', excerpt: '1944. augusztus 17-én Horthy nyomására lemondott tisztségéről.' },
                { claim: 'fled west, captured by Americans', source: S.huJaross, locator: 'Élete', excerpt: 'A háború után nyugatra menekült, ahol amerikai fogságba került.' },
                { claim: 'extradited and sentenced by the People’s Tribunal', source: S.huJaross, locator: 'Élete', excerpt: 'végül Magyarországnak adták ki, ahol államtitkáraival együtt a népbíróság halálra ítélte, majd kivégezték' },
                { claim: 'executed by firing squad', locator: 'lead', excerpt: 'After the war, Jaross was tried by the Hungarian authorities and executed by firing squad.' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-hungary', startYear: 1938, endYear: 1944, primary: true, claim: '1944년 스토여이 내각 내무장관', locator: 'lead', excerpt: 'Jaross was put in charge of the Interior Ministry' },
            { functionId: 'legislature', affiliationId: 'state-czechoslovakia', startYear: 1935, endYear: 1938, claim: '프라하 하원 의원', source: S.huJaross, locator: 'Élete', excerpt: '1935-ben a prágai Képviselőház tagjává vált.' },
        ],
        career: [
            ['1925–1933', '헝가리 국민당 부대표', 'Vice-chairman, Hungarian National Party'],
            ['1933', '헝가리 국민당 대표', 'Chairman, Hungarian National Party'],
            ['1935–1938', '체코슬로바키아 하원 의원', 'Member of the Czechoslovak Chamber of Deputies'],
            ['1938–1940', '펠비데크 담당 무임소 장관', 'Minister without portfolio for Upper Hungary'],
            ['1940', '헝가리 쇄신당 창당', 'Co-founded the Party of Hungarian Renewal'],
            ['1944', '내무장관', 'Interior minister'],
            ['1946', '인민재판소 사형 선고, 처형', 'Sentenced by the People’s Tribunal and executed'],
        ],
    }),
    person({
        id: 'geza-lakatos',
        given: ['게저', 'Géza'], family: ['러커토시', 'Lakatos'], nativeName: 'Lakatos Géza', years: '1890–1967',
        origin: null,
        epithet: ['1944년 8~10월 총리로서 유대인 이송을 멈추고 휴전을 준비했으나 화살십자당 쿠데타로 물러난 장군',
            'General who as prime minister in August–October 1944 halted the Jewish deportations and prepared an armistice until the Arrow Cross coup'],
        bio: ['부다페스트에서 태어나 1910년 루도비카 사관학교를 졸업했고, 1919년 헝가리 적군 사령부에서 복무하다 호르티의 국민군에 들어갔다. 1928~1934년 프라하 주재 무관을 지냈고 1943년 제2군, 1944년 4월 제1군 사령관이 되었다. 베틀렌 이슈트반의 천거로 1944년 8월 29일 스토여이의 후임 총리가 되어 은밀히 휴전 준비를 맡았고, 그의 정부는 유대인 이송을 멈추고 책임 차관들을 갈아치웠다. 10월 15일 판처파우스트 작전과 화살십자당 쿠데타로 휴전이 무산되자 밤새 페젠마이어와 협상한 끝에 호르티에게 항복을 권했고, 사임을 강요받고 독일 측에 갇혔다. 전후 기소되지 않았으나 연금과 땅을 빼앗겼고, 1965년 딸이 사는 애들레이드로 건너가 1967년 숨졌다.',
            'Born in Budapest, he graduated from the Ludovika Academy in 1910 and in 1919 served at the Hungarian Red Army’s headquarters before joining Horthy’s National Army. Military attaché in Prague from 1928 to 1934, he commanded the Second Army from 1943 and the First Army from April 1944. Recommended by István Bethlen, he succeeded Sztójay as prime minister on 29 August 1944 with a secret mandate to prepare an armistice; his government stopped the deportation of Jews and replaced the state secretaries responsible. When Operation Panzerfaust and the Arrow Cross coup thwarted the armistice on 15 October, he negotiated through the night with Veesenmayer, then urged Horthy to surrender; forced to resign, he was imprisoned by the Germans. Never prosecuted, he lost his pension and lands, and in 1965 joined his daughter in Adelaide, where he died in 1967.'],
        fate: ['natural', '오스트레일리아에서 자연사', 'Died in Australia'],
        aliases: { ko: [], en: ['Géza Lakatos', 'Geza Lakatos', 'Lakatos Géza'] },
        sources: [S.lakatos, S.huLakatos],
        facts: {
            years: { claim: '1890–1967', locator: 'lead', excerpt: '30 April 1890 – 21 May 1967' },
            citizenship: { claim: 'Hungarian colonel general and prime minister', locator: 'lead', excerpt: 'was a colonel general in the Hungarian Army during World War II who served briefly as Prime Minister of Hungary' },
            bio: [
                { claim: 'born in Budapest', source: S.huLakatos, locator: 'bevezető', excerpt: 'Lakatos Géza (Budapest, 1890. április 30.' },
                { claim: 'Ludovika Academy 1910', source: S.huLakatos, locator: 'Pályájának kezdete', excerpt: '1910-ben végezte el a Ludovika Akadémiát' },
                { claim: 'brigade staff officer in World War I', source: S.huLakatos, locator: 'I. világháború', excerpt: 'az osztrák-magyar hadsereg egyik dandárjának vezérkari tisztjeként szolgált' },
                { claim: 'Red Army HQ 1919, then the National Army', source: S.huLakatos, locator: 'I. világháború', excerpt: 'a Magyar Vörös Hadsereg gödöllői főparancsnokságán szolgált, végül beállt Horthy Miklós Nemzeti Hadseregébe' },
                { claim: 'military attaché in Prague 1928–1934', locator: 'Officer', excerpt: 'He was a military attaché in Prague from 1928 to 1934.' },
                { claim: 'Second Army 1943', locator: 'Officer', excerpt: 'On 5 August 1943 he succeeded vitéz Gusztáv Jány as commander of the Second Army.' },
                { claim: 'First Army April 1944', locator: 'Officer', excerpt: 'On 1 April 1944 he was appointed commander of the 1st Hungarian Army' },
                { claim: 'recommended by Bethlen', locator: 'Officer', excerpt: 'István Bethlen advised the regent of Hungary, Miklós Horthy, that he should sack the current prime minister, Döme Sztójay, and replace him with Lakatos.' },
                { claim: 'prime minister 29 August 1944, secretly charged with preparing an armistice', source: S.huLakatos, locator: 'Politikai szerepe', excerpt: '1944. augusztus 29-én Horthy miniszterelnökké nevezte ki, és titokban megbízta a háborúból való kilépés és a fegyverszünet előkészítésével.' },
                { claim: 'stopped the deportation of Jews', locator: 'Prime Minister', excerpt: 'stopped the deportation of Hungarian Jews' },
                { claim: 'replaced the state secretaries responsible', source: S.huLakatos, locator: 'Politikai szerepe', excerpt: 'leváltották a zsidók deportálásáért felelős államtitkárokat' },
                { claim: 'Operation Panzerfaust', locator: 'Prime Minister', excerpt: 'the Germans launched Operation Panzerfaust' },
                { claim: 'Arrow Cross coup', locator: 'Prime Minister', excerpt: 'The far-right Arrow Cross Party, backed by the Germans, immediately staged a coup and took full control of the government.' },
                { claim: 'negotiated with Veesenmayer through the night', locator: 'Operation Panzerfaust', excerpt: 'Lakatos spent the rest of the night negotiating with Veesenmayer' },
                { claim: 'urged Horthy to surrender', locator: 'Operation Panzerfaust', excerpt: 'Lakatos told Horthy that he had a written promise that Horthy Jr. would not be executed and that Horthy would be spared if he surrendered.' },
                { claim: 'forced to resign, imprisoned by the Germans', locator: 'Operation Panzerfaust', excerpt: 'Lakatos was forced to resign that day, and was imprisoned by the Germans in Sopronkőhida.' },
                { claim: 'not prosecuted', locator: 'Later Career', excerpt: 'Lakatos was one of the few prime ministers from the Horthy era who were not prosecuted for war crimes under the new regime.' },
                { claim: 'pension revoked and lands confiscated', locator: 'Later Career', excerpt: 'His military pension was revoked by the Communist authorities and his lands were also confiscated in 1949.' },
                { claim: 'went to Adelaide in 1965, died 1967', locator: 'Later Career', excerpt: 'Following his wife\'s death in 1965, the authorities permitted Lakatos to travel to Adelaide where his daughter lived since 1957. He died there two years later, in 1967.' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-hungary', startYear: 1944, endYear: 1944, primary: true, claim: '1944년 8~10월 총리', locator: 'lead', excerpt: 'served briefly as Prime Minister of Hungary, under regent Miklós Horthy from 29 August 1944, until 15 October 1944' },
            { functionId: 'military', affiliationId: 'state-hungary', startYear: 1910, endYear: 1944, claim: '제2군·제1군 사령관', locator: 'Officer', excerpt: 'On 5 August 1943 he succeeded vitéz Gusztáv Jány as commander of the Second Army.' },
            { functionId: 'diplomacy', affiliationId: 'state-hungary', startYear: 1928, endYear: 1934, claim: '프라하 주재 무관', locator: 'Officer', excerpt: 'He was a military attaché in Prague from 1928 to 1934.' },
        ],
        career: [
            ['1910', '루도비카 사관학교 졸업', 'Graduated from the Ludovika Academy'],
            ['1915–1918', '오스트리아-헝가리군 참모장교', 'Staff officer, Austro-Hungarian army'],
            ['1928–1934', '프라하 주재 무관', 'Military attaché in Prague'],
            ['1943–1944', '제2군 사령관', 'Commander, Second Army'],
            ['1944', '제1군 사령관', 'Commander, First Army'],
            ['1944', '총리(8월 29일~10월 15일)', 'Prime minister (29 August – 15 October)'],
            ['1965–1967', '오스트레일리아 애들레이드 거주, 사망', 'Lived and died in Adelaide, Australia'],
        ],
    }),
];
