// Person cards for the transcaucasia-1917-1921 event (revolution and war in the
// Caucasus, 1917–1921), see lib.js person(). Excerpts are verbatim from the cited
// pages. Bodies with no catalog affiliation (the First Republic of Armenia, the
// Musavat party, the Transcaucasian Commissariat, the Progressive Republican
// Party, the Mountainous Republic and the Dagestan insurgents) stay unresolved.
const { W, person } = require('./lib');

const E = t => W(encodeURI(t));
const RU = t => 'https://ru.wikipedia.org/wiki/' + encodeURI(t);
const S = {
    zhordania: E('Noe_Zhordania'),
    gegechkori: E('Evgeni_Gegechkori'),
    rasulzade: E('Mahammad_Amin_Rasulzade'),
    khatisian: E('Alexander_Khatisian'),
    andranik: E('Andranik'),
    dunsterville: E('Lionel_Dunsterville'),
    karabekir: E('Kâzım_Karabekir'),
    gotsinsky: E('Najmuddin_of_Gotzo'),
    ruGotsinsky: RU('Гоцинский,_Нажмудин'),
};

const unaffiliated = card => ({
    ...card,
    activities: card.activities.map(a => (a.affiliationId ? a : { ...a, affiliationStatus: 'unresolved', relation: 'unresolved' })),
});

module.exports = [
    person({
        id: 'noe-zhordania', groupId: 'world-interwar',
        given: ['노이', 'Noe'], family: ['조르다니아', 'Zhordania'], nativeName: 'ნოე ჟორდანია', years: '1868–1953',
        citizenship: 'georgia', origin: 'georgia',
        epithet: ['1918~1921년 그루지야 민주공화국 정부를 이끈 그루지야 멘셰비키의 지도자',
            'Leader of the Georgian Mensheviks who headed the government of the Democratic Republic of Georgia in 1918–1921'],
        bio: ['1868년 그루지야 서부 구리아에서 태어나 바르샤바 수의학교에서 마르크스주의를 받아들였고, 1890년대 그루지야 최초의 합법 마르크스주의 단체 메사메 다시를 이끌었다. 1903년 멘셰비키 편에 섰고 1906년 제1대 국가 두마 의원이 되었다. 1917년 트빌리시 소비에트와 그루지야 민족회의를 이끌었고, 1918년 5월 독립 선포 회의를 주재한 뒤 7월 그루지야 민주공화국 정부 수반이 되어 토지개혁과 사회 입법을 이끌었다. 1921년 붉은 군대의 침공으로 프랑스에 망명해 망명정부를 이끌다 1953년 파리 근교에서 숨졌다.',
            'Born in Guria, western Georgia, in 1868, he took up Marxism at the Warsaw Veterinary Institute and in the 1890s led Mesame Dasi, Georgia’s first legal Marxist organization. He sided with the Mensheviks in 1903 and sat in the First State Duma in 1906. In 1917 he chaired the Tbilisi Soviet and the National Council of Georgia; in May 1918 he headed the session that declared independence, and from July he led the government of the Democratic Republic of Georgia, carrying out land reform and social legislation. After the Red Army invasion of 1921 he went into exile in France, led the government-in-exile and died near Paris in 1953.'],
        fate: ['exile', '망명지에서 사망', 'Died in exile'],
        aliases: { ko: ['노에 조르다니아', '노에 요르다니아'], en: ['Noe Jordania', 'Noy Zhordaniya'] },
        sources: [S.zhordania],
        facts: {
            years: { claim: '1868–1953', locator: 'lead', excerpt: '15 January [O.S. 3 January] 1868 – January 11, 1953' },
            citizenship: { claim: 'Georgian Menshevik politician who chaired the government of the Democratic Republic of Georgia', locator: 'lead', excerpt: 'was a Georgian journalist and Menshevik politician' },
            nationalOrigin: { claim: 'born in Guria, western Georgia', locator: 'Early life and background', excerpt: 'to a petty landowner family living in the village of Lanchkhuti in Guria, western Georgia' },
            bio: [
                { claim: 'graduated from the Georgian Orthodox Theological Seminary in Tbilisi', locator: 'Education', excerpt: 'He then moved to Tbilisi where he graduated from the Georgian Orthodox Theological Seminary' },
                { claim: 'took up Marxism in Warsaw', locator: 'Education', excerpt: 'In 1891 he moved to Warsaw, Poland, and attended the Warsaw Veterinarian Institute. During this period young Zhordania understood the basics of Marxism.' },
                { claim: 'leader of Mesame Dasi in the 1890s', locator: 'Early career', excerpt: 'in the 1890s he became a leader of the first legal Marxist organization in Georgia, called the Mesame Dasi (the Third Group)' },
                { claim: 'sided with the Mensheviks at the 2nd Congress in 1903', locator: 'Early career', excerpt: 'Having been elected as a delegate to the 2nd Congress of the Russian Social Democratic Labour Party (RSDLP) in 1903, he sided with the Menshevik faction and gained significant influence.' },
                { claim: 'elected to the First Duma in 1906, spokesman of the SD faction', locator: 'Early career', excerpt: 'he was elected to the First State Duma from the Tiflis Governorate and became a spokesman for the Social-Democratic faction' },
                { claim: 'chaired the Tbilisi soviet after February 1917', locator: 'Revolution and independence', excerpt: 'After the 1917 February Revolution, he chaired the Tbilisi soviet' },
                { claim: 'chair of the presidium of the National Council of Georgia, November 1917', locator: 'Revolution and independence', excerpt: 'On November 26, 1917, he obtained a chair of the Presidium of the National Council of Georgia and played a leading role in the consolidation of Menshevik power in Georgia.' },
                { claim: 'headed the session that declared independence in May 1918', locator: 'Revolution and independence', excerpt: 'in May 1918, when he headed a parliamentary session which declared the independent Democratic Republic of Georgia' },
                { claim: 'head of government from 24 July 1918', locator: 'Revolution and independence', excerpt: 'On July 24, 1918, he became Head of the Government of Georgia.' },
                { claim: 'land reform, legislation and de jure recognition', locator: 'Revolution and independence', excerpt: 'his government had organized a successful land reform, adopted comprehensive social and political legislation, and cultivated widespread international ties, enabling Georgia to become the only Transcaucasian nation to earn de jure recognition from Soviet Russia and the Western powers' },
                { claim: 'Soviet invasion of 1921 and the government-in-exile in France', locator: 'Revolution and independence', excerpt: 'However, the invasion of the Soviet armies in February–March 1921 toppled the Georgian government, forcing Zhordania and many of his colleagues to seek refuge in France, where he led the government-in-exile' },
                { claim: 'died at Leuville-sur-Orge in 1953', locator: 'Emigration and death', excerpt: 'Noe Zhordania died at the age of 85, on January 11, 1953, in Leuville-sur-Orge, where he is buried.' },
            ],
        },
        activities: [
            { functionId: 'political-leadership', affiliationId: 'state-georgia', startYear: 1918, endYear: 1921, primary: true, claim: 'Chairman of the government of the Democratic Republic of Georgia, 1918–1921', locator: 'lead', excerpt: 'later chaired the government of the Democratic Republic of Georgia from July 24, 1918, until March 18, 1921' },
            { functionId: 'political-leadership', affiliationId: 'russian-mensheviks', relation: 'membership', startYear: 1903, endYear: null, claim: 'Leading Menshevik from the 1903 congress', locator: 'Early career', excerpt: 'he sided with the Menshevik faction and gained significant influence' },
        ],
        career: [
            ['1890년대', '메사메 다시 지도자', 'Leader of Mesame Dasi'],
            ['1906', '제1대 국가 두마 의원', 'Member of the First State Duma'],
            ['1917', '트빌리시 소비에트 의장, 그루지야 국민평의회 의장', 'Chairman of the Tbilisi Soviet and of the National Council of Georgia'],
            ['1918–1921', '그루지야 민주공화국 정부 수반', 'Head of the government of the Democratic Republic of Georgia'],
            ['1921–1953', '프랑스에서 망명정부 수반', 'Head of the government-in-exile in France'],
        ],
    }),
    unaffiliated(person({
        id: 'evgeni-gegechkori', groupId: 'world-interwar',
        given: ['예브게니', 'Evgeni'], family: ['게게치코리', 'Gegechkori'], nativeName: 'ევგენი გეგეჭკორი', years: '1881–1954',
        citizenship: 'georgia', origin: 'georgia',
        epithet: ['자캅카스 위원부 의장을 거쳐 그루지야 민주공화국 외무장관을 지낸 멘셰비키 정치가',
            'Menshevik politician who chaired the Transcaucasian Commissariat and became foreign minister of the Democratic Republic of Georgia'],
        bio: ['1881년 마르트빌리의 귀족 집안에서 태어나 모스크바 대학 시절 사회민주주의 운동에 들어가 멘셰비키가 되었고, 1907~1912년 제3대 국가 두마 의원을 지냈다. 1917년 11월부터 1918년 3월까지 자캅카스 인민위원부 의장을 지냈고, 이어 자캅카스 세임 정부에서 전쟁장관을 맡았다. 1918년 5월 그루지야 독립선언서에 서명했고, 그루지야 민주공화국에서 외무장관·법무장관과 정부 부의장을 지냈다. 1921년 3월 프랑스로 망명했고, 1953년부터 1954년 파리에서 숨질 때까지 망명정부를 이끌었다.',
            'Born to a noble family in Martvili in 1881, he joined the Social Democratic movement as a student at Moscow University, became a Menshevik and sat in the Third State Duma from 1907 to 1912. From November 1917 to March 1918 he chaired the Transcaucasian Commissariat, then served as minister of war under the Transcaucasian Sejm. He signed the Georgian declaration of independence in May 1918 and was foreign minister, justice minister and deputy head of government of the Democratic Republic of Georgia. He left for France in March 1921 and from 1953 until his death in Paris in 1954 headed the government in exile.'],
        fate: ['exile', '망명지에서 사망', 'Died in exile'],
        aliases: { ko: ['에브게니 게게치코리'], en: ['Evgeny Gegechkori', 'Yevgeni Gegechkori'] },
        sources: [S.gegechkori],
        facts: {
            years: { claim: '1881–1954', locator: 'lead', excerpt: '(20 January 1881, in Martvili – 5 June 1954, in Paris)' },
            citizenship: { claim: 'Georgian politician, minister of the Democratic Republic of Georgia', locator: 'lead', excerpt: 'was a Georgian nobleman, politician, and Social Democratic revolutionary' },
            nationalOrigin: { claim: 'Georgian nobleman', locator: 'lead', excerpt: 'was a Georgian nobleman' },
            bio: [
                { claim: 'noble family; student movement 1903; Mensheviks', locator: 'lead', excerpt: 'Born of a noble family, he entered the Social Democratic student movement in 1903 during his studies at the Imperial Moscow University and soon joined the Menshevik wing of the Russian Social Democratic Labour Party.' },
                { claim: '1905 revolution; Third Duma 1907–1912', locator: 'lead', excerpt: 'He was involved in the 1905 revolution in Georgia and was elected a member to the Third State Duma for the Kutais Governorate from 1907 to 1912.' },
                { claim: 'Provisional Government commissar in western Georgia', locator: 'lead', excerpt: 'During the February Revolution in 1917, Gegechkori became commissar for the Russian Provisional Government in western Georgia.' },
                { claim: 'chairman of the Transcaucasian Commissariat, Sejm, minister of war', locator: 'lead', excerpt: 'From 28 November 1917 to 26 March 1918 he chaired the Transcaucasian Commissariat and served as minister of labor before leading the Transcaucasian Sejm and becoming its minister of war.' },
                { claim: 'signed the act of independence', locator: 'lead', excerpt: 'On May 26, 1918, he signed the Act of Declaration of Independence of the Democratic Republic of Georgia.' },
                { claim: 'foreign minister, justice minister', locator: 'lead', excerpt: 'he became its Minister of Foreign Affairs and also served as the Minister of Justice' },
                { claim: 'deputy chairman of the government', locator: 'lead', excerpt: 'Evgeni Gegechkori was appointed as the Deputy Chairman of the Government' },
                { claim: 'left for France in March 1921', locator: 'lead', excerpt: 'After the Red Army invasion of Georgia, Gegechkori left for France in March 1921.' },
                { claim: 'headed the government in exile from 1953', locator: 'lead', excerpt: 'From 1953 until his death, he headed the Georgian government in exile.' },
            ],
        },
        activities: [
            { functionId: 'diplomacy', affiliationId: 'state-georgia', startYear: 1918, endYear: 1921, primary: true, claim: 'Minister of Foreign Affairs of the Democratic Republic of Georgia', locator: 'lead', excerpt: 'After the establishment of the Democratic Republic of Georgia in May 1918, he became its Minister of Foreign Affairs' },
            { functionId: 'government', affiliationId: null, startYear: 1917, endYear: 1918, claim: 'Chairman of the Transcaucasian Commissariat, no catalog affiliation', locator: 'lead', excerpt: 'From 28 November 1917 to 26 March 1918 he chaired the Transcaucasian Commissariat' },
            { functionId: 'political-leadership', affiliationId: 'russian-mensheviks', relation: 'membership', startYear: 1903, endYear: null, claim: 'Member of the Menshevik wing of the RSDLP', locator: 'lead', excerpt: 'soon joined the Menshevik wing of the Russian Social Democratic Labour Party' },
        ],
        career: [
            ['1907–1912', '제3대 국가 두마 의원', 'Member of the Third State Duma'],
            ['1917', '러시아 임시정부 서부 그루지야 위원', 'Russian Provisional Government commissar for western Georgia'],
            ['1917–1918', '자캅카스 위원부 의장', 'Chairman of the Transcaucasian Commissariat'],
            ['1918–1921', '그루지야 민주공화국 외무장관', 'Minister of Foreign Affairs of the Democratic Republic of Georgia'],
            ['1953–1954', '그루지야 망명정부 수반', 'Head of the Georgian government in exile'],
        ],
    })),
    unaffiliated(person({
        id: 'mammad-amin-rasulzade', groupId: 'world-interwar',
        given: ['마메드 아민', 'Mammad Amin'], family: ['라술자데', 'Rasulzade'], nativeName: 'Məhəmməd Əmin Rəsulzadə', years: '1884–1955',
        citizenship: 'azerbaijan', origin: 'azerbaijan',
        epithet: ['무사바트의 지도자로 1918년 아제르바이잔 국민평의회를 이끌어 아제르바이잔 민주공화국 독립을 선포한 정치가',
            'Musavat leader who headed the Azerbaijani National Council that declared the Azerbaijan Democratic Republic in 1918'],
        bio: ['1884년 바쿠 근처에서 태어나 1904년 무슬림 사회민주주의 조직 후메트를 세웠다. 1909년 이란 입헌혁명에 참여했고, 1913년 바쿠로 돌아와 무사바트의 지도자가 되었다. 1918년 5월 아제르바이잔 민족회의 의장으로서 5월 28일 아제르바이잔 공화국의 독립을 선포했다. 1920년 공화국이 무너진 뒤 저항을 지휘하다 체포되었으나, 예전에 이오시프 스탈린을 경찰로부터 숨겨 준 일 덕분에 풀려나 모스크바로 옮겨졌다. 1922년 핀란드로 탈출해 튀르키예·폴란드·루마니아에서 망명 생활을 했고, 1955년 앙카라에서 숨졌다.',
            'Born near Baku in 1884, he founded Hummet, a Muslim social-democratic organization, in 1904. He took part in the Iranian Constitutional Revolution in 1909, and after returning to Baku in 1913 he became the chief of Musavat. As head of the Azerbaijani National Council he declared the independence of the Azerbaijan Republic on 28 May 1918. After the republic fell in 1920 he directed resistance until his arrest, but because he had once hidden Joseph Stalin from the police he was released and taken to Moscow. He escaped to Finland in 1922, lived in exile in Turkey, Poland and Romania, and died in Ankara in 1955.'],
        fate: ['exile', '망명지에서 사망', 'Died in exile'],
        aliases: { ko: ['마하마드 아민 라술자데', '메메트 에민 레술자데'], en: ['Mahammad Amin Rasulzade', 'Mammad Amin Rasulzadeh', 'Mehmet Emin Resulzade'] },
        sources: [S.rasulzade],
        facts: {
            years: { claim: '1884–1955', locator: 'lead', excerpt: '(31 January 1884 – 6 March 1955)' },
            citizenship: { claim: 'Azerbaijani politician, head of the Azerbaijani National Council', locator: 'lead', excerpt: 'was an Azerbaijani politician, journalist and the head of the Azerbaijani National Council' },
            nationalOrigin: { claim: 'Azerbaijani, born near Baku', locator: 'Early life', excerpt: 'Born on 31 January 1884 to Akhund Haji Molla Alakbar Rasulzadeh in Novkhany, near Baku' },
            bio: [
                { claim: 'educated in Baku', locator: 'Early life', excerpt: 'received his education at the Russian-Muslim Secondary School and then at the Technical College in Baku' },
                { claim: 'founded Hummet in 1904 and edited its newspapers', locator: 'Early life', excerpt: 'In 1904 he founded the first Muslim social-democrat organisation "Hummet" and became editor-in-chief of its newspapers' },
                { claim: 'fled to Iran in 1909 for the Constitutional Revolution', locator: 'Early life', excerpt: 'In 1909, under the persecution from Tsarist authorities, Rasulzade fled Baku to participate in the Iranian Constitutional Revolution of 1905–1911.' },
                { claim: 'co-founder of the Democrat Party of Persia', locator: 'Early life', excerpt: 'became one of the founders of Democrat Party of Persia' },
                { claim: 'fled to Istanbul in 1911', locator: 'Early life', excerpt: 'Rasulzade fled to Istanbul, then capital of Ottoman Empire' },
                { claim: 'returned 1913, joined Musavat and became its chief', locator: 'The Musavat Party and Azerbaijan Democratic Republic', excerpt: 'joined the then secret Musavat (Equality) party in 1913' },
                { claim: 'quickly became chief of Musavat', locator: 'The Musavat Party and Azerbaijan Democratic Republic', excerpt: 'and quickly became its chief' },
                { claim: 'head of the Muslim faction in the Seym; head of the National Council May 1918', locator: 'The Musavat Party and Azerbaijan Democratic Republic', excerpt: 'Rasulzade became head of Muslim faction in the Seym, the parliament of the Transcaucasian Federation. After the dissolution of the Transcaucasian Federation, the Muslim faction re-organized into the Azerbaijani National Council, whose head Rasulzade was unanimously elected in May 1918.' },
                { claim: 'declared independence on 28 May 1918', locator: 'The Musavat Party and Azerbaijan Democratic Republic', excerpt: 'On 28 May 1918 the Azerbaijani National Council, headed by Rasulzade, declared an independent Azerbaijan Republic.' },
                { claim: 'hid in Lahıc to direct resistance; arrested August 1920', locator: 'The Musavat Party and Azerbaijan Democratic Republic', excerpt: 'Rasulzade left Baku and went into hiding in the mountainous village of Lahıc, Ismailli to direct the resistance to Sovietization. But in August 1920' },
                { claim: 'released thanks to the rescue of Stalin', locator: 'The Musavat Party and Azerbaijan Democratic Republic', excerpt: 'It was only due to an earlier rescue of Joseph Stalin, as Rasulzade hid Stalin from the police, that Rasulzade was released and transferred from Azerbaijan to Russia.' },
                { claim: 'Commissariat on Nations, escape to Finland 1922', locator: 'The Musavat Party and Azerbaijan Democratic Republic', excerpt: 'For the next two years, Rasulzade worked as the press representative at the Commissariat on Nations in Moscow.  He was seconded to Saint Petersburg in 1922 from where he escaped to Finland.' },
                { claim: 'exile in Turkey', locator: 'Exile', excerpt: 'For the rest of his life, Rasulzade lived in exile first in Turkey.' },
                { claim: 'Poland 1938, Romania 1940', locator: 'Exile', excerpt: 'he went to Poland in 1938, where he met his wife, Wanda, niece of Polish statesman Józef Piłsudski, then to Romania in 1940' },
                { claim: 'died 1955, buried in Ankara', locator: 'Exile', excerpt: 'He died in 1955, a broken man according to Thomas Goltz, and was buried in Cebeci Asri cemetery in Ankara.' },
            ],
        },
        activities: [
            { functionId: 'political-leadership', affiliationId: null, startYear: 1913, endYear: null, primary: true, claim: 'Chief of the Musavat party, no catalog affiliation', locator: 'The Musavat Party and Azerbaijan Democratic Republic', excerpt: 'joined the then secret Musavat (Equality) party in 1913' },
            { functionId: 'legislature', affiliationId: 'state-azerbaijan', startYear: 1918, endYear: 1918, claim: 'Head of the Azerbaijani National Council, May 1918', locator: 'The Musavat Party and Azerbaijan Democratic Republic', excerpt: 'the Azerbaijani National Council, whose head Rasulzade was unanimously elected in May 1918' },
        ],
        career: [
            ['1904', '후메트 창립', 'Founded Hummet'],
            ['1909–1911', '이란 입헌혁명 참가, 페르시아 민주당 창립', 'Iranian Constitutional Revolution; co-founded the Democrat Party of Persia'],
            ['1913', '무사바트 입당, 지도자', 'Joined Musavat and became its chief'],
            ['1918', '아제르바이잔 국민평의회 의장, 독립 선포', 'Head of the Azerbaijani National Council; declaration of independence'],
            ['1920', '체포 뒤 석방, 모스크바 민족인민위원부', 'Arrested, released and sent to the Commissariat on Nations in Moscow'],
            ['1922–1955', '망명', 'Exile'],
        ],
    })),
    unaffiliated(person({
        id: 'alexander-khatisian', groupId: 'world-interwar',
        given: ['알렉산드르', 'Alexander'], family: ['하티샨', 'Khatisian'], nativeName: 'Ալեքսանդր Խատիսեան', years: '1874–1945',
        citizenship: 'armenia', origin: 'armenia',
        epithet: ['아르메니아 제1공화국의 외무장관·총리로 바투미 조약과 알렉산드로폴 조약에 서명한 다슈나크 정치가',
            'Dashnak foreign minister and prime minister of the First Republic of Armenia who signed the treaties of Batum and Alexandropol'],
        bio: ['1874년 트빌리시의 아르메니아인 귀족 가문에서 태어나 의사 교육을 받았고, 1910~1917년 트빌리시 시장을 지내며 1914년 아르메니아인 의용대 창설을 조직했다. 1917년 다슈나크에 들어갔다. 아르메니아 공화국의 외무장관으로 1918년 6월 바투미 조약에 서명했고, 1919년 5월부터 1920년 5월 봉기의 여파로 물러날 때까지 총리를 지냈다. 1920년 12월 3일 그가 이끈 대표단이 카즘 카라베키르와 알렉산드로폴 조약에 서명했으나, 권력이 이미 소비에트 당국에 넘어간 뒤라 무효로 여겨진다. 파리로 망명해 1945년 그곳에서 숨졌다.',
            'Born in Tbilisi in 1874 to a prominent Armenian family of noble origins, he trained as a doctor, was mayor of Tbilisi from 1910 to 1917 and in 1914 organized the Armenian volunteer detachments. He joined the Dashnaktsutyun in 1917. As foreign minister of the Republic of Armenia he signed the Treaty of Batum in June 1918, and he was prime minister from May 1919 until he resigned after the May Uprising of 1920. On 3 December 1920 a delegation led by him signed the Treaty of Alexandropol with Kâzım Karabekir, but power had already passed to the Soviet authorities and the treaty is held to be invalid. He went into exile in Paris and died there in 1945.'],
        fate: ['exile', '망명지에서 사망', 'Died in exile'],
        aliases: { ko: ['알렉산드르 하티시안'], en: ['Alexander Khatisyan'] },
        sources: [S.khatisian],
        facts: {
            years: { claim: '1874–1945', locator: 'lead', excerpt: '17 February 1874 – 10 March 1945' },
            citizenship: { claim: 'Armenian politician, prime minister of the First Republic of Armenia', locator: 'lead', excerpt: 'was an Armenian politician, doctor and journalist' },
            nationalOrigin: { claim: 'born to a prominent Armenian family', locator: 'Biography', excerpt: 'to a prominent Armenian family of noble origins' },
            bio: [
                { claim: 'born in Tbilisi', locator: 'Biography', excerpt: 'Khatisian was born in Tiflis in the Tiflis Governorate of the Russian Empire (Tbilisi, Georgia)' },
                { claim: 'trained as a doctor', locator: 'Biography', excerpt: 'received his training as a doctor at universities in Moscow, Kharkov and Germany' },
                { claim: 'mayor of Tbilisi 1910–1917', locator: 'Biography', excerpt: 'He served as the mayor of Tiflis from 1910 to 1917.' },
                { claim: 'organized Armenian volunteer detachments in 1914', locator: 'Biography', excerpt: 'about the creation of Armenian volunteer detachments in the summer of 1914, which Khatisian enthusiastically supported and organized' },
                { claim: 'joined the ARF in 1917', locator: 'Biography', excerpt: 'In 1917, Khatisian became a member of the Armenian Revolutionary Federation.' },
                { claim: 'foreign minister, Treaty of Batum', locator: 'Biography', excerpt: 'After declaration of the First Republic of Armenia, he served as foreign minister and signed the Treaty of Batum with the Ottoman Empire.' },
                { claim: 'prime minister May 1919–May 1920, resigned after the May Uprising', locator: 'Biography', excerpt: 'then served as prime minister from May 1919 to May 1920, resigning in the aftermath of the Bolshevik-led May Uprising' },
                { claim: 'sought aid in European capitals', locator: 'Biography', excerpt: 'After his resignation, he sought aid for the Republic of Armenia in various European capitals.' },
                { claim: 'Treaty of Alexandropol, invalid', locator: 'Biography', excerpt: 'On December 3, 1920, an Armenian delegation led by Khatisian signed the Treaty of Alexandropol with Kemalist Turkey, though the government it represented no longer existed (power had already been transferred to the new Soviet authorities), making the treaty illegal.' },
                { claim: 'exile in Paris and memoirs', locator: 'Biography', excerpt: 'Following the Soviet takeover of Armenia, Khatisian went into exile in Paris, France. He wrote his memoirs' },
                { claim: 'died in Paris in 1945', locator: 'Biography', excerpt: 'He died in Paris on 10 March 1945 at the age of 71.' },
            ],
        },
        activities: [
            { functionId: 'diplomacy', affiliationId: null, startYear: 1918, endYear: 1920, primary: true, claim: 'Foreign minister of the First Republic of Armenia; signed the treaties of Batum and Alexandropol (no catalog affiliation)', locator: 'Biography', excerpt: 'he served as foreign minister and signed the Treaty of Batum with the Ottoman Empire' },
            { functionId: 'government', affiliationId: null, startYear: 1919, endYear: 1920, claim: 'Prime minister of the First Republic of Armenia (no catalog affiliation)', locator: 'Biography', excerpt: 'then served as prime minister from May 1919 to May 1920' },
            { functionId: 'government', affiliationId: null, startYear: 1910, endYear: 1917, claim: 'Mayor of Tbilisi (municipal office, no catalog affiliation)', locator: 'Biography', excerpt: 'He served as the mayor of Tiflis from 1910 to 1917.' },
        ],
        career: [
            ['1910–1917', '트빌리시 시장', 'Mayor of Tbilisi'],
            ['1917', '다슈나크 입당', 'Joined the Dashnaktsutyun'],
            ['1918', '아르메니아 외무장관, 바투미 조약 서명', 'Foreign minister of Armenia; signed the Treaty of Batum'],
            ['1919–1920', '아르메니아 총리', 'Prime minister of Armenia'],
            ['1920', '알렉산드로폴 조약 서명', 'Signed the Treaty of Alexandropol'],
            ['1921–1945', '파리 망명', 'Exile in Paris'],
        ],
    })),
    unaffiliated(person({
        id: 'andranik-ozanian', groupId: 'world-interwar',
        given: ['안드라니크', 'Andranik'], family: ['오자냔', 'Ozanian'], nativeName: 'Անդրանիկ Օզանյան', years: '1865–1927',
        citizenship: 'armenia', origin: 'armenia',
        epithet: ['아르메니아 공화국을 인정하지 않고 독자 부대를 이끌어 잔게주르를 지킨 아르메니아 페다이 지휘관',
            'Armenian fedayi commander who rejected the Republic of Armenia and held Zangezur with his own division'],
        bio: ['1865년 오스만 제국 샤빈카라히사르에서 태어나 다슈나크의 페다이 부대를 이끌었고, 제1차 세계대전 때 러시아군의 제1아르메니아 의용대대를 지휘했다. 아르메니아 공화국과 바투미 조약을 인정하지 않은 그는 1918년 특별타격사단을 이끌고 잔게주르를 장악했다. 역사가 도널드 블록섬은 그가 무슬림 마을을 파괴해 이 지역을 아르메니아인만의 땅으로 바꾸려 했다고 보고, 안트라니그 찰라비안은 그가 잔게주르의 아르메니아인을 지켰다고 본다. 1918년 12월 영국군의 요청으로 카라바흐 진격을 멈추었고, 1919년 부대를 해산했다. 1927년 미국 프레즈노에서 숨졌다.',
            'Born in Shabin-Karahisar in the Ottoman Empire in 1865, he led fedayi units of the Dashnaktsutyun and in the First World War commanded the first Armenian volunteer battalion of the Russian army. Refusing to recognize the Republic of Armenia or the Treaty of Batum, he took control of Zangezur with his Special Striking Division in 1918. The historian Donald Bloxham writes that he sought to make it homogeneously Armenian by destroying Muslim villages, while Antranig Chalabian argues that he saved Zangezur’s Armenians from annihilation. In December 1918 he halted his advance into Karabakh at British request, and in 1919 he disbanded his unit. He died in Fresno, California, in 1927.'],
        fate: ['natural', '협심증', 'Angina'],
        aliases: { ko: ['안드라니크', '안드라니크 장군'], en: ['Andranik', 'General Andranik'] },
        linkExpressions: [['ko', '안드라니크'], ['en', 'Andranik']],
        sources: [S.andranik],
        facts: {
            years: { claim: '1865–1927', locator: 'lead', excerpt: '(25 February 1865 – 31 August 1927)' },
            citizenship: { claim: 'Armenian military commander and statesman', locator: 'lead', excerpt: 'was an Armenian military commander and statesman' },
            nationalOrigin: { claim: 'Armenian born in the Ottoman Empire', locator: 'Early life', excerpt: 'Andranik Ozanian was born on 25 February 1865 in the town of Shabin-Karahisar (Şebinkarahisar), in the Sivas Vilayet of the Ottoman Empire' },
            bio: [
                { claim: 'armed struggle from the late 1880s; ARF fedayi units', locator: 'lead', excerpt: 'Andranik entered the armed struggle against the Ottoman government and Kurdish irregulars in the late 1880s. After joining the Armenian Revolutionary Federation (Dashnaktsutyun), he led various fedayi units' },
                { claim: 'broke with the ARF in 1907', locator: 'lead', excerpt: 'eventually breaking with the Dashnaktsutyun in 1907 over its brief rapprochement with the Young Turks' },
                { claim: 'commander of the first Armenian volunteer battalion', locator: 'lead', excerpt: 'At the outbreak of World War I, Andranik was appointed commander of the first Armenian volunteer battalion within the Russian Imperial Army.' },
                { claim: 'entered Van on 19 May 1915', locator: 'World War I', excerpt: 'Andranik entered the liberated city on 19 May 1915' },
                { claim: 'major-general, Western Armenian division', locator: 'Russian Revolution and Turkish reoccupation', excerpt: "Andranik, promoted to the rank of major-general by the Caucasus Front command, was appointed to lead the Corps' Western Armenian division." },
                { claim: 'retreat from Erzurum', locator: 'Russian Revolution and Turkish reoccupation', excerpt: 'Following an attempt to defend Erzurum against numerically superior Ottoman forces, Andranik retreated from the city.' },
                { claim: 'refused to recognize the republic or the Treaty of Batum', locator: 'lead', excerpt: 'He refused to recognize the First Republic of Armenia or the Treaty of Batum' },
                { claim: 'proclaimed Nakhichevan part of Soviet Russia', locator: 'First Republic of Armenia', excerpt: 'In a defiant political move on 14 July 1918, Andranik proclaimed Nakhichevan an integral part of Soviet Russia' },
                { claim: 'Special Striking Division in Zangezur', locator: 'Zangezur', excerpt: 'As Ottoman forces advanced toward Nakhichevan, Andranik and his Special Striking Division transitioned to the rugged, mountainous terrain of Zangezur to establish a strategic defense.' },
                { claim: 'control over the district by September', locator: 'Zangezur', excerpt: 'by September, he had established effective administrative and military control over the district' },
                { claim: 'Bloxham: destroying Muslim villages', locator: 'Zangezur', excerpt: 'According to historian Donald Bloxham, Andranik pursued a policy of transforming Zangezur into a demographically homogenous Armenian territory by destroying Muslim villages' },
                { claim: 'Chalabian: saved the Armenians of Zangezur', locator: 'Zangezur', excerpt: "Conversely, Antranig Chalabian argues that Andranik's presence was the sole factor preventing the complete annihilation of the sixty thousand Armenian inhabitants of Zangezur" },
                { claim: 'halted 40 km from Shusha at Thomson’s request', locator: 'Karabakh', excerpt: 'By early December, Andranik was within 40 km (25 miles) of Shushi when he was intercepted by a message from the British commander in Baku, General W. M. Thomson.' },
                { claim: 'returned to Zangezur', locator: 'Karabakh', excerpt: 'Andranik halted his campaign and returned to Zangezur' },
                { claim: 'disbanded his unit in April 1919', locator: 'Departure', excerpt: 'On 13 April 1919, Andranik arrived in Etchmiadzin' },
                { claim: 'chose to disband his unit', locator: 'Departure', excerpt: 'Andranik chose to disband his unit' },
                { claim: 'relief work in Europe and the US', locator: 'Last years', excerpt: 'From 1919 to 1922, Andranik traveled around Europe and the United States seeking support for the Armenian refugees.' },
                { claim: 'settled in Fresno in 1922', locator: 'Last years', excerpt: 'Andranik and Nevarte moved to the United States and settled in Fresno in 1922.' },
                { claim: 'died of angina in 1927', locator: 'Death', excerpt: 'Andranik died from angina on 31 August 1927' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: null, startYear: 1918, endYear: 1919, primary: true, claim: 'Commander of the Special Striking Division in Zangezur, acting independently of the Armenian government (no catalog affiliation)', locator: 'Zangezur', excerpt: 'Andranik and his Special Striking Division transitioned to the rugged, mountainous terrain of Zangezur' },
            { functionId: 'military', affiliationId: 'russian-empire', startYear: 1914, endYear: 1916, claim: 'Commander of the first Armenian volunteer battalion within the Imperial Russian Army', locator: 'World War I', excerpt: 'From November 1914 to August 1915, he spearheaded this unit of approximately 1,200 volunteers within the Imperial Russian Army during the Caucasus Campaign.' },
        ],
        career: [
            ['1892', '아르메니아 혁명연맹 가입', 'Joined the Armenian Revolutionary Federation'],
            ['1914–1916', '러시아 제국군 제1아르메니아 의용대대장', 'Commander of the first Armenian volunteer battalion, Imperial Russian Army'],
            ['1918', '소장, 서아르메니아 사단장', 'Major-general; commander of the Western Armenian division'],
            ['1918–1919', '특별타격사단장, 잔게주르', 'Commander of the Special Striking Division in Zangezur'],
            ['1922', '프레즈노 정착', 'Settled in Fresno'],
        ],
    })),
    person({
        id: 'lionel-dunsterville', groupId: 'world-interwar',
        given: ['라이어널', 'Lionel'], family: ['던스터빌', 'Dunsterville'], nativeName: 'Lionel Charles Dunsterville', years: '1865–1946',
        citizenship: 'uk', origin: 'uk',
        epithet: ['1918년 던스터포스를 이끌고 페르시아를 가로질러 바쿠 방어에 나선 영국 장군',
            'British general who led Dunsterforce across Persia to defend Baku in 1918'],
        bio: ['1865년 스위스 로잔에서 태어나 러디어드 키플링과 같은 학교를 다녔고, 키플링의 소설 속 「스토키」의 모델이 되었다. 영국령 인도군 장교로 북서변경과 중국에서 복무했다. 1917년 말 메소포타미아 전선 등에서 뽑은 1,000명 미만의 연합군 부대 던스터포스의 지휘관이 되어 1918년 1월 바그다드를 출발해 페르시아를 가로질렀다. 1918년 8월 센트로카스피 독재 정부가 장악한 바쿠의 방어에 나섰으나, 9월 14일 오스만군의 공세 앞에서 바쿠를 버리고 물러났다. 1946년 잉글랜드 데번주에서 숨졌다.',
            'Born in Lausanne in 1865, he went to school with Rudyard Kipling and was the model for “Stalky” in Kipling’s stories. An officer of the British Indian Army, he served on the North-West Frontier and in China. At the end of 1917 he was given command of Dunsterforce, an Allied force of fewer than 1,000 men drawn from the Mesopotamian and other fronts, which left Baghdad in January 1918 and crossed Persia. In August 1918 he took up the defence of Baku, then held by the Centro Caspian Dictatorship, but on 14 September he abandoned the city before the Ottoman assault. He died in Devon, England, in 1946.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: ['라이어널 찰스 던스터빌', '스토키'], en: ['L. C. Dunsterville', 'Stalky'] },
        sources: [S.dunsterville],
        facts: {
            years: { claim: '1865–1946', locator: 'lead', excerpt: '(9 November 1865 – 18 March 1946)' },
            citizenship: { claim: 'British Indian Army officer', locator: 'lead', excerpt: 'was a British Indian Army officer' },
            nationalOrigin: { claim: 'son of a British Indian Army general', locator: 'Early life', excerpt: 'the son of Lieutenant General Lionel D\'Arcy Dunsterville (1830–1912) of the Indian Army' },
            bio: [
                { claim: 'born in Lausanne', locator: 'Early life', excerpt: 'Lionel Charles Dunsterville was born in Lausanne, Switzerland on 9 November 1865' },
                { claim: 'schoolmate of Kipling', locator: 'Early life', excerpt: 'He went to school with Rudyard Kipling' },
                { claim: 'model for Stalky', locator: 'Early life', excerpt: 'He served as the inspiration for the character "Stalky" in Kipling\'s collection of school stories Stalky & Co..' },
                { claim: 'commissioned 1884', locator: 'Early military career', excerpt: 'Dunsterville was commissioned into the British Army as a lieutenant in the Royal Sussex Regiment on 23 August 1884.' },
                { claim: 'Indian Army, North-West Frontier, Waziristan', locator: 'Early military career', excerpt: 'He later transferred to the British Indian Army, was promoted to captain on 23 August 1895, and served on the North-West Frontier and in Waziristan.' },
                { claim: 'China during the Boxer Rebellion', locator: 'Early military career', excerpt: 'As a railway staff officer he served in China during the Boxer Rebellion 1900–02' },
                { claim: 'appointed to lead Dunsterforce at the end of 1917', locator: 'First World War', excerpt: 'At the end of 1917 the army appointed then-Major Dunsterville to lead an Allied force (Dunsterforce) of fewer than 1,000 Australian, British, Canadian and New Zealand troops, drawn from the Mesopotamian and Western Fronts' },
                { claim: 'set out from Baghdad in January 1918', locator: 'First World War', excerpt: 'His mission set out from Baghdad in January 1918' },
                { claim: 'fought the Jangali at Manjil', locator: 'First World War', excerpt: 'On his way to Bandar-e Anzali on the Persian Caspian Sea coast he also fought Mirza Kuchik Khan and his Jangali forces in Manjil.' },
                { claim: 'defence of Baku held by the Centro Caspian Dictatorship', locator: 'First World War', excerpt: 'Dunsterville was assigned to re-inforce the defence of the key oil-field and port of Baku (in present-day Azerbaijan), held from 26 July 1918 by the anti-Soviet Centro Caspian Dictatorship.' },
                { claim: 'arrived 6 August, abandoned Baku 14 September', locator: 'First World War', excerpt: 'Dunsterforce personnel first arrived in Baku on 6 August 1918. However, the British and their allies had to abandon Baku on 14 September 1918 in the face of an onslaught by 14,000 Ottoman troops' },
                { claim: 'died at Torquay in 1946', locator: 'Post-war years', excerpt: 'Dunsterville died at the age of 80 in March 1946 at Torquay, Devon, England' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: 'state-uk', startYear: 1917, endYear: 1918, primary: true, claim: 'Commander of Dunsterforce', locator: 'lead', excerpt: 'who led Dunsterforce across present-day Iraq and Iran towards the Caucasus and Baku during the First World War' },
            { functionId: 'military', affiliationId: 'state-uk', startYear: 1884, endYear: null, claim: 'Officer of the British Army and the British Indian Army from 1884', locator: 'Early military career', excerpt: 'Dunsterville was commissioned into the British Army as a lieutenant in the Royal Sussex Regiment on 23 August 1884.' },
        ],
        career: [
            ['1884', '영국 육군 중위 임관', 'Commissioned lieutenant, British Army'],
            ['1900–1902', '의화단 운동 때 중국 복무', 'Service in China during the Boxer Rebellion'],
            ['1915', '임시 준장, 젤룸 여단장', 'Temporary brigadier general, commanding the Jhelum Brigade'],
            ['1917–1918', '던스터포스 지휘관', 'Commander of Dunsterforce'],
            ['1918', '소장 진급', 'Promoted major-general'],
        ],
    }),
    unaffiliated(person({
        id: 'kazim-karabekir', groupId: 'world-interwar',
        given: ['카즘', 'Kâzım'], family: ['카라베키르', 'Karabekir'], nativeName: 'Kâzım Karabekir', years: '1882–1948',
        citizenship: 'turkey', origin: 'turkey',
        epithet: ['터키 독립전쟁 동부 전선 사령관으로 1920년 아르메니아를 침공해 알렉산드로폴 조약을 받아 낸 장군',
            'Eastern Front commander of the Turkish War of Independence who invaded Armenia in 1920 and imposed the Treaty of Alexandropol'],
        bio: ['1882년 이스탄불에서 태어나 오스만 육군대학을 수석으로 졸업했고, 제1차 세계대전 때 갈리폴리와 쿠트, 캅카스 전선에서 싸웠다. 무스타파 케말의 국민운동에 가담해 독립전쟁의 동부 전선을 지휘했다. 1920년 9월 아르메니아를 침공해 카르스와 알렉산드로폴을 점령했고, 이 원정에서 그의 군대는 아르메니아 민간인 수만 명을 쫓아내고 학살했다. 12월 알렉산드로폴 조약에, 1921년 카르스 조약에 서명했다. 1924년 첫 야당 진보공화당을 세웠으나 당이 폐쇄되었고, 1946년 대국민의회 의장이 되어 1948년 재임 중 숨졌다.',
            'Born in Istanbul in 1882, he graduated at the top of his class from the Ottoman Military College and fought at Gallipoli, at Kut and on the Caucasus front in the First World War. Joining Mustafa Kemal’s national movement, he commanded the Eastern Front in the War of Independence. He invaded Armenia in September 1920 and took Kars and Alexandropol; during the campaign his army displaced and massacred tens of thousands of Armenian civilians. He signed the Treaty of Alexandropol in December and the Treaty of Kars in 1921. In 1924 he founded the Progressive Republican Party, the first opposition party, which was closed; elected speaker of the Grand National Assembly in 1946, he died in office in 1948.'],
        fate: ['natural', '심장마비', 'Heart attack'],
        aliases: { ko: ['무사 카즘 카라베키르', '카즘 제이레크'], en: ['Musa Kâzım Karabekir', 'Kiazim Karabekir', 'Kazim Karabekir', 'Kâzım Zeyrek'] },
        sources: [S.karabekir],
        facts: {
            years: { claim: '1882–1948', locator: 'lead', excerpt: '1882 – 26 January 1948' },
            citizenship: { claim: 'Turkish general and politician', locator: 'lead', excerpt: 'was a Turkish general and politician' },
            nationalOrigin: { claim: 'Turkish family from the Karamanid region', locator: 'Early life', excerpt: 'The Karabekir family traced its heritage back to the medieval Karamanid principality, in central Anatolia, where his family belonged to the Afshar tribe.' },
            bio: [
                { claim: 'born in Istanbul, son of an Ottoman general', locator: 'Early life', excerpt: 'Karabekir was born in 1882 as the son of an Ottoman general, Mehmet Emin Pasha' },
                { claim: 'top of his class at the Military College in 1902', locator: 'Early life', excerpt: 'He continued his education at the Ottoman Military College, which he finished on 6 December 1902 at the top of his class.' },
                { claim: '14th Division at Gallipoli', locator: 'World War I', excerpt: 'As commander of the 14th Division, Karabekir fought in the Battle of Gallipoli in the summer of 1915.' },
                { claim: '18th Corps victory at Kut', locator: 'World War I', excerpt: 'In April 1916, he took over the command of the 18th Corps, which gained a great victory over the British forces led by General Charles Townshend during the Siege of Kut-al Amara in Iraq.' },
                { claim: '2nd Corps on the Caucasus front', locator: 'World War I', excerpt: 'Karabekir was appointed commander of the 2nd Corps on the Caucasus front and fought bitterly against the Russian and Armenian forces for almost ten months.' },
                { claim: '15th Army Corps at Erzurum, May 1918', locator: 'World War I', excerpt: 'In  May 1918 he became the commander of the 15th Army Corps in Erzurum' },
                { claim: 'refused to surrender; joined the national movement; Eastern Front', locator: 'Turkish War of Independence', excerpt: 'gave Karabekir the order to surrender to Entente powers, which he refused to obey' },
                { claim: 'joined Mustafa Kemal and commanded the Eastern Front', locator: 'Turkish War of Independence', excerpt: 'He pledged with Mustafa Kemal to join the Turkish national movement and then took command of the Eastern Front during the Turkish War of Independence' },
                { claim: 'invasion of Armenia in September 1920', locator: 'Turkish War of Independence', excerpt: 'In early September 1920, Karabekir commenced a military invasion of Armenia.' },
                { claim: 'Kars 30 October, Alexandropol 6 November', locator: 'Turkish War of Independence', excerpt: 'the Turkish armies captured Kars on 30 October and occupied Alexandropol, Armenia\'s largest city at the time, on 6 November' },
                { claim: 'Treaty of Alexandropol with Khatisian’s delegation', locator: 'Turkish War of Independence', excerpt: 'A ceasefire was concluded on 18 November between Karabekir and a delegation led by Alexander Khatisian.' },
                { claim: 'signed 3 December 1920', locator: 'Turkish War of Independence', excerpt: 'Karabekir affixed his signature under the peace agreement, the Treaty of Alexandropol, which was signed on 3 December 1920.' },
                { claim: 'massacre of Armenian civilians, about 60,000', locator: 'Turkish War of Independence', excerpt: "Karabekir's army displaced and massacred tens of thousands of Armenian civilians during the campaign against Armenia, with conservative estimates placing the number killed at approximately 60,000." },
                { claim: 'signed the Treaty of Kars', locator: 'Turkish War of Independence', excerpt: 'to sign also the friendship agreement Treaty of Kars with the Soviet Union on 23 October 1921' },
                { claim: 'Progressive Republican Party founded 1924', locator: 'lead', excerpt: "He was the founder and leader of the Progressive Republican Party, the Turkish Republic's first opposition party to Atatürk" },
                { claim: 'party closed 1925, imprisoned, acquitted', locator: 'Political career', excerpt: 'The party was closed on 5 June 1925 by the government, and Karabekir was imprisoned by the Independence Tribunals with many of his party members but later acquitted and released.' },
                { claim: 'speaker 1946, died in office 1948', locator: 'Political career', excerpt: 'He was elected speaker of the parliament on 5 August 1946. He died in office at the age of 66 on 26 January 1948 in Ankara after a heart attack.' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: 'state-turkey', startYear: 1902, endYear: 1924, primary: true, claim: 'Ottoman and Turkish army commander; Eastern Front commander in the War of Independence', locator: 'lead', excerpt: 'He was the commander of the Eastern Army of the Ottoman Empire during the Turkish War of Independence, and fought a successful military campaign against the Armenian Democratic Republic.' },
            { functionId: 'political-leadership', affiliationId: null, startYear: 1924, endYear: 1925, claim: 'Founder and leader of the Progressive Republican Party (no catalog affiliation)', locator: 'lead', excerpt: 'He was the founder and leader of the Progressive Republican Party' },
            { functionId: 'legislature', affiliationId: 'state-turkey', startYear: 1946, endYear: 1948, claim: 'Speaker of the Grand National Assembly', locator: 'Political career', excerpt: 'He was elected speaker of the parliament on 5 August 1946.' },
        ],
        career: [
            ['1915', '갈리폴리 전투 제14사단장', 'Commander of the 14th Division at Gallipoli'],
            ['1918', '제15군단 사령관(에르주룸)', 'Commander of the 15th Army Corps, Erzurum'],
            ['1920', '아르메니아 침공, 알렉산드로폴 조약 서명', 'Invasion of Armenia; signed the Treaty of Alexandropol'],
            ['1921', '카르스 조약 서명', 'Signed the Treaty of Kars'],
            ['1924–1925', '진보공화당 창당·당수', 'Founder and leader of the Progressive Republican Party'],
            ['1946–1948', '대국민의회 의장', 'Speaker of the Grand National Assembly'],
        ],
    })),
    unaffiliated(person({
        id: 'najmuddin-gotsinsky', groupId: 'world-interwar',
        given: ['나주무딘', 'Najmuddin'], family: ['고친스키', 'Gotsinsky'], nativeName: 'Нажмудин Гоцинский', years: '1859–1925',
        citizenship: { code: 'russia', label: { ko: '러시아 제국', en: 'Russian Empire' } }, origin: null,
        epithet: ['북캅카스의 무프티로서 1918~1925년 다게스탄과 체첸의 반볼셰비키 봉기를 이끈 아바르인 종교 지도자',
            'Avar religious leader and mufti of the North Caucasus who led anti-Bolshevik uprisings in Dagestan and Chechnya in 1918–1925'],
        bio: ['1859년 다게스탄 고초브 마을의 아바르인 귀족 지주 집안에서 태어난 이슬람 학자다. 1917년 5월 북캅카스 산악민 연합 대회에서 북캅카스의 무프티가 되었고, 8월 다게스탄·체첸의 이맘으로 추대되었다가 사흘 만에 칭호를 내려놓았다. 1918년 볼셰비키와 싸웠고, 1919년 데니킨의 의용군을 공산주의자보다 덜한 악으로 보고 협력했다. 1920년 9월 다게스탄 봉기를 일으켜 이끌었으나 봉기는 1921년 5월 진압되었다. 체첸으로 옮겨 다시 봉기를 준비하다 1925년 9월 체포되어 그해 10월 총살되었다.',
            'Born in 1859 to an aristocratic Avar landowning family in the village of Gotsob in Dagestan, he was an Islamic scholar. In May 1917 the congress of the Union of Highlanders of the North Caucasus made him mufti of the North Caucasus, and in August he was proclaimed Imam of Dagestan and Chechnya but gave up the title three days later. He fought the Bolsheviks in 1918, and in 1919 he collaborated with Denikin’s Volunteer Army as a lesser evil than the communists. In September 1920 he raised and led the Dagestan uprising, which was put down in May 1921. Moving to Chechnya to prepare another rising, he was arrested in September 1925 and shot that October.'],
        fate: ['executed', '총살', 'Executed by shooting'],
        aliases: { ko: ['나주무딘 도노고'], en: ['Najmuddin of Gotzo', 'Nazhmudin Gotsinsky', 'Nazhmudin Donogo'] },
        sources: [S.gotsinsky, S.ruGotsinsky],
        facts: {
            years: { claim: '1859–1925', locator: 'lead', excerpt: '(1859 – October 1925)' },
            citizenship: { claim: 'born in Dagestan Oblast of the Russian Empire', source: S.ruGotsinsky, locator: 'lead', excerpt: '1859, Гоцоб, Дагестанская область, Российская империя' },
            bio: [
                { claim: 'born to an aristocratic family in Gotsob', locator: 'Early life and career', excerpt: "Najmuddin was born in 1859 in the village of Gotsob, in the Russian Empire's Dagestan Oblast to an aristocratic family." },
                { claim: 'Avar father', locator: 'Early life and career', excerpt: 'His Avar father, Muhammad Donogo, had been a naib under Imam Shamil' },
                { claim: 'joined the ulama', locator: 'Early life and career', excerpt: 'joining the ulama after receiving a religious education' },
                { claim: 'naib of Koisubu 1895–1903', locator: 'Early life and career', excerpt: 'He next was naib of Koisubu Prefecture within the Avar District of Dagestan Oblast, the same office his father had held, from 1895 to 1903.' },
                { claim: 'supported February; Dagestan Oblast Provisional Executive Committee', locator: 'Revolution and the Mountainous Republic', excerpt: 'Najmuddin supported the 1917 February Revolution, and after the revolution\'s success he became a member of the Dagestan Oblast Provisional Executive Committee' },
                { claim: 'appointed mufti at the First Congress in Vladikavkaz', locator: 'Revolution and the Mountainous Republic', excerpt: 'Najmuddin attended the First Congress of the Union of Highlanders of the North Caucasus, which took place in May 1917 in Vladikavkaz. There, he was appointed as mufti of the North Caucasus' },
                { claim: 'appointed Imam on 17 August 1917', locator: 'Revolution and the Mountainous Republic', excerpt: 'On 17 August 1917, Najmuddin was formally appointed as Imam of Dagestan and Chechnya' },
                { claim: 'gave up the title three days later', locator: 'Revolution and the Mountainous Republic', excerpt: 'Three days later, he was instructed to give up his title by the congress\'s attendees' },
                { claim: 'confirmed as mufti', locator: 'Revolution and the Mountainous Republic', excerpt: "Najmuddin's status as mufti, rather than imam, was affirmed" },
                { claim: 'fought the Red Army in 1918', locator: 'Resistance against the Bolsheviks', excerpt: 'The Red Army and forces loyal to Najmuddin continued to clash until August 1918' },
                { claim: 'saw Denikin as a lesser evil', locator: 'Collaboration with the Whites', excerpt: 'he viewed Denikin as a lesser evil capable of defeating the communists' },
                { claim: 'uprising in the Avar District, September 1920', locator: 'Uprising in Dagestan (1920–1921)', excerpt: 'Najmuddin returned to Dagestan ahead of Said, leading an uprising in the Avar District in September 1920. The uprising soon spread across Dagestan' },
                { claim: 'defeated in May 1921', locator: 'Uprising in Dagestan (1920–1921)', excerpt: 'The uprising was eventually defeated in May 1921' },
                { claim: 'Chechnya and British intelligence', locator: 'Uprising in Dagestan (1920–1921)', excerpt: 'Najmuddin left for Chechnya, where he was in contact with British intelligence' },
                { claim: '1924–1925 insurgency in Chechnya, captured September 1925', locator: 'lead', excerpt: 'Following the failure of a 1924–1925 insurgency in Chechnya led by Najmuddin, he was captured by the Red Army in September 1925.' },
                { claim: 'arrested on 5 September', locator: 'Capture and execution', excerpt: 'Najmuddin was arrested on 5 September.' },
                { claim: 'sentenced 15 October 1925, executed', locator: 'Capture and execution', excerpt: 'On 15 October 1925, Najmuddin was sentenced to execution by shooting in Rostov-on-Don. He was executed later that month.' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: null, startYear: 1918, endYear: 1925, primary: true, claim: 'Leader of anti-Bolshevik uprisings in Dagestan and Chechnya (no catalog affiliation)', locator: 'lead', excerpt: 'who led multiple uprisings against the Bolsheviks during and after the Russian Civil War' },
            { functionId: 'religion', affiliationId: null, startYear: 1917, endYear: 1919, claim: 'Mufti of the North Caucasus and of the Mountainous Republic (no catalog affiliation)', locator: 'lead', excerpt: 'Najmuddin first served as Mufti of the Mountainous Republic of the Northern Caucasus' },
        ],
        career: [
            ['1895–1903', '아바르 관구 코이수부 구역 나이브', 'Naib of Koisubu, Avar District'],
            ['1917', '북캅카스 무프티', 'Mufti of the North Caucasus'],
            ['1917', '다게스탄·체첸 이맘으로 추대, 사흘 만에 사퇴', 'Proclaimed Imam of Dagestan and Chechnya; gave up the title three days later'],
            ['1920–1921', '다게스탄 봉기 지도', 'Led the Dagestan uprising'],
            ['1924–1925', '체첸 봉기', 'Insurgency in Chechnya'],
            ['1925', '체포, 로스토프나도누에서 처형', 'Arrested; executed in Rostov-on-Don'],
        ],
    })),
];
