// Sections 6–8 of transcaucasia-1917-1921: the Azerbaijan Democratic Republic,
// Britain and the Whites, and the North Caucasus (1918–1921).
const E = t => 'https://en.wikipedia.org/wiki/' + encodeURI(t.replace(/ /g, '_'));
const RU = t => 'https://ru.wikipedia.org/wiki/' + encodeURI(t.replace(/ /g, '_'));

const S = {
    adr: E('Azerbaijan Democratic Republic'),
    rasulzade: E('Mahammad Amin Rasulzade'),
    khoyski: E('Fatali Khan Khoyski'),
    musavat: E('Musavat'),
    shusha: E('Shusha massacre'),
    aaw: E('Armenian–Azerbaijani war (1918–1920)'),
    thomson: E('William Montgomerie Thomson'),
    batum: E('Batum oblast'),
    swc: E('Provisional National Government of the Southwestern Caucasus'),
    sochi: E('Sochi conflict'),
    afsr: E('Armed Forces of South Russia'),
    drgRu: RU('Грузинская демократическая республика'),
    drg: E('Democratic Republic of Georgia'),
    kuban: E("Kuban People's Republic"),
    terek: E('Terek Soviet Republic'),
    terekRu: RU('Терская советская республика'),
    ncsr: E('North Caucasian Soviet Republic'),
    mrnc: E('Mountainous Republic of the Northern Caucasus'),
    gorRu: RU('Горская республика'),
    emirate: E('North Caucasian Emirate'),
    emirateRu: RU('Северо-Кавказский эмират'),
    uzun: E('Uzun-Hajji'),
    gotsinsky: E('Najmuddin of Gotzo'),
    dagUp: E('Dagestan uprising'),
    dagUpRu: RU('Восстание в Дагестане (1920—1921)'),
    mountainAssr: E('Mountain Autonomous Soviet Socialist Republic'),
    ordzh: E('Sergo Ordzhonikidze'),
    kirov: E('Sergei Kirov'),
};

const P = (lat, lng, ko, en) => ({ kind: 'point', lat, lng, label: { ko, en } });

module.exports = {
    sections: [
        {
            heading: { ko: '아제르바이잔 민주공화국 {azerbaijan armenia}', en: 'The Azerbaijan Democratic Republic {azerbaijan armenia}' },
            paragraphs: [
                {
                    ko: '1918년 5월 26일 자캅카스 민주연방공화국이 해체되자 자캅카스 의회(세임)의 무슬림 분파는 아제르바이잔 민족회의로 재편했고, 만장일치로 의장에 뽑힌 마메드 아민 라술자데가 이끄는 민족회의는 5월 28일 트빌리시에서 아제르바이잔 민주공화국의 수립을 선포했다. 함께 발표된 민족 헌장은 아제르바이잔을 자캅카스 남부·동부를 영역으로 하는 주권 민주공화국으로 규정하고, 민족·종교·계급·직업·성별과 관계없이 모든 시민에게 시민적·정치적 권리를 보장한다고 약속했다. 바쿠가 볼셰비키의 손에 있었으므로 정부는 간자를 임시 수도로 삼았고, 첫 총리 파탈리 칸 호이스키가 내각을 이끌었다. 호이스키는 오스만 정부와의 동맹을 성사시켜 바쿠의 센트로카스피 독재 정권을 몰아내는 데 큰 역할을 했다고 평가되며, 바쿠는 1918년 9월 오스만 이슬람 군대와 아제르바이잔 부대가 입성한 뒤에야 공화국의 수도가 되었다. 집권당 무사바트(평등)는 1911년 비밀 결사로 출발해 범이슬람주의·범튀르크주의·사회주의 이념을 내걸었다가 아제르바이잔 민족주의 정당으로 변모했고, 1913년 귀국해 입당한 라술자데가 곧 당을 이끌었다. 2월 혁명 뒤 합법화된 무사바트는 캅카스 무슬림의 선도 정당이 되었다. 공화국의 대외 노선은 오스만 지향기(1918년 5~10월), 서방 지향기(1918년 11월~1920년 1월), 다각적 협력 모색기(1920년 1~4월)로 나뉜다.',
                    en: 'When the Transcaucasian Democratic Federative Republic dissolved on 26 May 1918, the Muslim faction of the Transcaucasian Sejm reconstituted itself as the Azerbaijani National Council. Led by Mammad Amin Rasulzade, whom it had unanimously elected chairman, the council proclaimed the Azerbaijan Democratic Republic in Tbilisi on 28 May. Its National Charter declared Azerbaijan a sovereign democratic republic covering the south and east of Transcaucasia and promised all citizens full civil and political rights regardless of ethnicity, religion, class, profession or sex. With Baku in Bolshevik hands, the government made Ganja its temporary capital, and the first prime minister, Fatali Khan Khoyski, headed the cabinet. Khoyski is credited with a central role in the alliance with the Ottoman government that removed the Centrocaspian Dictatorship from Baku, and the city became the capital only after the Ottoman Army of Islam and Azerbaijani units entered it in September 1918. The governing party, Musavat ("Equality"), had begun in 1911 as a secret society with pan-Islamist, pan-Turkist and socialist ideas and evolved into an Azerbaijani nationalist party; Rasulzade joined it on his return in 1913 and soon led it. Legalised after the February Revolution, Musavat became the leading party of Caucasian Muslims. The republic\'s foreign policy is usually divided into an Ottoman orientation (May–October 1918), a Western orientation (November 1918 – January 1920) and a search for broader cooperation (January–April 1920).',
                    sources: [S.adr, S.rasulzade, S.khoyski, S.musavat],
                },
                {
                    ko: '1918년 12월 의회가 문을 열면서 민족회의는 해산되었다(개원일은 출처에 따라 12월 5일 또는 7일). 동방 무슬림 세계 최초의 민주 의회로 꼽히는 이 의회의 의장 알리마르단 톱추바쇼프는 국가원수로 인정되어 1919년 파리 강화회의에 아제르바이잔 대표로 나갔다. 의석 수는 출처에 따라 96석 또는 120석으로 엇갈리지만, 38석의 무사바트가 무소속 일부와 함께 최대 분파를 이루었고, 아흐라르·이티하드·무슬림 사회민주당과 함께 아르메니아인(120석 중 21석)·러시아인·폴란드인·독일인·유대인 등 소수민족 대표도 의석을 얻었다. 다섯 차례 구성된 내각은 모두 무사바트와 다른 정당의 연립이었고, 처음 세 내각은 호이스키가, 나머지 두 내각은 나시브 유시프베일리가 이끌었으며, 보수 성향의 이티하드가 주된 야당이었다. 의회는 145차례 회의에서 270여 건의 법안을 다루어 230건을 채택했고, 1919년에는 여성에게 남성과 같은 참정권을 주어 무슬림이 다수인 나라 가운데 처음으로 여성 참정권을 실현했다. 1919년 9월 1일에는 바쿠 국립대학이 세워졌고 학생 100명이 국비로 해외에 유학했다. 공화국은 러시아 내전에서 붉은 군대와 백군 어느 쪽에도 서지 않는 중립을 표방했다. 파리에서 아제르바이잔 대표단을 만난 우드로 윌슨은 자캅카스 여러 민족의 연방을 권하며 아제르바이잔 문제는 러시아 문제 전체가 해결되기 전에는 풀 수 없다고 냉담하게 말했지만, 1920년 1월 12일 연합국 최고회의는 그루지야와 함께 아제르바이잔을 사실상(de facto) 승인했다.',
                    en: 'The National Council was dissolved when parliament opened in December 1918 (on the 5th or the 7th, depending on the source). Described as the first democratic parliament in the Muslim East, it was chaired by Alimardan Topchubashov, who was recognised as head of state and represented Azerbaijan at the Paris Peace Conference in 1919. Sources give its size as either 96 or 120 seats; Musavat, with 38 members, formed the largest faction together with some independents, while Ahrar, Ittihad and the Muslim Social Democrats sat alongside representatives of Armenian (21 of 120 seats), Russian, Polish, German and Jewish minorities. All five cabinets were coalitions of Musavat and other parties: Khoyski led the first three and Nasib Yusifbeyli the last two, with the conservative Ittihad as the main opposition. In 145 sessions parliament considered more than 270 bills and adopted 230. In 1919 it gave women the same political rights as men, making Azerbaijan the first Muslim-majority country to enfranchise women. Baku State University was founded on 1 September 1919, and 100 students were sent abroad at state expense. In the Russian Civil War the republic declared itself neutral, siding with neither Reds nor Whites. When Woodrow Wilson received the Azerbaijani delegation in Paris, he was cool, urging a confederation of the Transcaucasian peoples and saying the Azerbaijani question could not be settled before the Russian question as a whole; yet on 12 January 1920 the Allied Supreme Council extended de facto recognition to Azerbaijan along with Georgia.',
                    sources: [S.adr, S.musavat, S.rasulzade],
                },
                {
                    ko: '카라바흐(나고르노카라바흐)를 놓고 아르메니아와 다투던 아제르바이잔 정부는 1919년 1월 15일 호스로프 베이 술타노프를 카라바흐 총독으로 임명했다. 슈샤에 소규모 부대를 두었던 영국은 이 임명을 받아들이되 최종 귀속은 강화회의가 정한다고 했고, 카라바흐 아르메니아인 대회는 2월과 4월 거듭 아제르바이잔의 권한을 거부했다. 1919년 6월 슈샤에서 두 공동체가 충돌하자 술타노프는 아르메니아인 구역을 봉쇄했고, 6월 중순에는 약 2,000명의 아제르바이잔 비정규 기병이 인근 아르메니아인 마을 하이발리켄드를 공격해 약 600명이 숨졌다. 8월 22일 합의로 카라바흐는 최종 지위가 정해질 때까지 잠정적으로 아제르바이잔 안에 두되 내부 자치를 누리기로 했으나, 아르메니아 측 서술에 따르면 아제르바이잔 당국은 곧 수비대를 늘리고 아르메니아인을 무장 해제했으며 경제 봉쇄를 가했다. 1920년 3월 22일 밤 아르메니아인 무장대가 아제르바이잔 수비대를 무장 해제하려던 봉기가 실패하자, 22일부터 26일까지 아제르바이잔 군대와 주민이 슈샤의 아르메니아인 구역을 불태우고 주민을 학살했다. 희생자 수는 출처와 정의에 따라 500명에서 3만 명까지 크게 엇갈린다. 리처드 호바니시안은 당시 아르메니아 정부 보고를 근거로 시내에서만 약 500명으로 보았고, 외르크 바베로프스키는 8,000명, 테사 호프만은 학살 당일과 그 뒤 며칠 동안 2만 명이 죽었다고 썼다. 5,000~6,000명이 탈출했고 4월 11일까지 카라바흐의 마을 30여 곳이 파괴되어 약 2만 5천 명이 집을 잃었다.',
                    en: 'Contesting Karabakh (Nagorno-Karabakh) with Armenia, the Azerbaijani government appointed Khosrov bey Sultanov governor-general of Karabakh on 15 January 1919. Britain, which kept a small detachment in Shusha, accepted the appointment but insisted that the territory\'s final status belonged to the peace conference, and the Armenian assembly of Karabakh rejected Azerbaijani authority in February and again in April. After clashes between the two communities in Shusha in June 1919, Sultanov blockaded the Armenian quarter, and in mid-June some 2,000 Azerbaijani irregular horsemen attacked the nearby Armenian village of Khaibalikend, leaving about 600 dead. An agreement of 22 August placed Karabakh provisionally within Azerbaijan, with internal autonomy, until its final status was decided, but according to Armenian accounts the Azerbaijani authorities soon reinforced their garrisons, disarmed the Armenians and imposed an economic blockade. On the night of 22 March 1920 an Armenian attempt to disarm the Azerbaijani garrison failed, and from 22 to 26 March Azerbaijani troops and townspeople burned the Armenian quarter of Shusha and massacred its inhabitants. Estimates of the dead range from 500 to 30,000 depending on source and definition: Richard Hovannisian, citing a contemporary Armenian government report, put the toll at about 500 in the town itself, Jörg Baberowski at 8,000, and Tessa Hofmann at 20,000 in the days of and following the pogrom. Five to six thousand Armenians escaped, and by 11 April some thirty villages in Karabakh had been devastated, leaving about 25,000 people homeless.',
                    sources: [S.shusha, S.aaw],
                },
            ],
        },
        {
            heading: { ko: '석유와 해협 사이에서: 영국과 백군 {uk russia georgia azerbaijan}', en: 'Between oil and the Straits: Britain and the Whites {uk russia georgia azerbaijan}' },
            paragraphs: [
                {
                    ko: '1918년 10월 30일 무드로스 휴전으로 오스만군이 자캅카스에서 물러나자 그 자리를 영국이 차지했다. 북페르시아 부대를 지휘하던 윌리엄 톰슨 장군은 11월 16일 반다르안잘리에서 무사바트 대표들을 만나 오스만군과 아제르바이잔군의 바쿠 철수, 아르메니아 부대의 바쿠 진입 저지, 영국 관할 아래의 지역 민병대 창설, 바쿠 유전의 석유를 영국에 공급하는 일, 자캅카스 철도 동쪽 종점의 확보를 목표로 밝혔다. 이튿날 톰슨은 영국 인도군 병사들과 니콜라이 바라토프의 러시아 부대를 이끌고 바쿠에 들어왔다(영국군 규모는 출처에 따라 약 2,000명에서 5,000명까지 다르다). 스스로 바쿠 군정 총독을 자처한 그는 계엄을 선포하고 아제르바이잔 국기를 내리게 했으며, 연합국은 러시아의 질서를 되살리기 전에는 돌아갈 수 없다고 연설해 바쿠 러시아인들의 환영을 받았다. 처음에 그는 공화국을 인정하지 않았지만 묵시적으로 협력했다. 영국군은 11~12월 바쿠·트빌리시·바투미 같은 요충을 점령해 자캅카스 철도와 바쿠의 석유·등유 수송을 손에 넣었고, 바투미주에 주둔한 제27사단은 데니킨의 의용군에 물자를 보내는 보급 종점 구실도 했다. 영국은 1918년 12월에 벌어진 그루지야와 아르메니아의 국경 전쟁을 이듬해 1월 중재해 분쟁 지역 한가운데에 영국 총독이 관할하는 중립 지대를 두게 했고, 1919년 4월에는 카르스의 「남서캅카스 임시 국민정부」를 해산시키는 등 지역 분쟁의 조정자로 나섰다.',
                    en: 'When the Armistice of Mudros on 30 October 1918 forced the Ottomans out of Transcaucasia, Britain took their place. On 16 November General William Thomson, commander of the North Persia Force, met Musavat representatives in Bandar-e Anzali and set out his aims: the evacuation of Ottoman and Azerbaijani units from Baku, keeping Armenian troops out of the city, a local militia under British administration, oil from the Baku fields for Britain, and control of the eastern terminus of the Transcaucasus Railway. The next day he entered Baku with soldiers of the British Indian Army and a Russian detachment under Nikolai Baratov; sources put the British force at anywhere from about 2,000 to 5,000 men. Declaring himself military governor, Thomson imposed martial law, ordered the Azerbaijani flag taken down and told his audience that the Allies could not go home without restoring order in Russia, to the delight of Baku\'s Russians. He did not at first recognise the republic, though he tacitly cooperated with it. In November and December British troops occupied key points such as Baku, Tbilisi and Batumi, giving them control of the Transcaucasus Railway and of oil and kerosene shipments from Baku, and the 27th Division in the Batum oblast also served as a supply terminal for Denikin\'s Volunteer Army. Britain set itself up as the arbiter of regional quarrels: in January 1919 it mediated an end to the Georgian–Armenian border war of December 1918, leaving a neutral zone under a British governor in the middle of the disputed district, and in April 1919 it dissolved the Kars-based provisional government of the Southwestern Caucasus.',
                    sources: [S.thomson, S.adr, S.drgRu, S.batum, S.swc],
                },
                {
                    ko: '그러나 영국의 정책은 이중적이었다. 그루지야 역사가 A. 멘테샤시빌리는 영국이 한편으로 「단일 불가분의 러시아」의 회복과 볼셰비키 타도를 내건 데니킨군을 돕고, 다른 한편으로 영국의 힘을 빌려 주권을 굳히려는 현지 정부들의 기대를 부추기며 상황에 따라 「분할 통치」로 줄타기했다고 평가한다. 노이 조르다니아는 훗날 영국 사령부가 데니킨의 이익까지 대변하며, 데니킨에게 복종하면 볼셰비키를 이긴 뒤 자치를 주겠다고 제안했다고 회고했다. 가장 날카로운 충돌은 흑해 연안의 소치에서 벌어졌다. 1918년 7월 그루지야군은 붉은 군대를 밀어내고 소치를 거쳐 투압세까지 나아갔고, 9월 18일 소치 지역 회의가 그루지야와의 「임시」 통합을 선언하자 백군 지도부가 거세게 반발했다. 9월 25~26일 예카테리노다르에서 의용군과 예브게니 게게치코리 외무장관이 이끈 그루지야 대표단이 만났지만 회담은 결렬되었고, 1919년 2월 6일 백군은 가그라에서 그루지야군 지휘부를 사로잡으며 그루지야군을 브지브강 너머로 밀어냈다. 영국이 브지브강에 경계선을 긋자 그루지야군은 4월 반격에 나섰고, 영국은 다시 개입해 프소우강에 새 경계선을 설정했다. 5월 트빌리시 회담으로 분쟁은 사실상 끝났고, 프소우강은 오늘날 러시아–그루지야 국경이 되었다. 1919년 6월 16일 아제르바이잔과 그루지야는 국경을 위협하는 데니킨의 의용군에 맞서 방위 조약을 맺었다. 상황이 안정되었다고 본 영국은 1919년 8월 19일 바쿠에서 철수했다.',
                    en: 'Yet British policy was double-edged. The Georgian historian A. Menteshashvili argues that Britain helped Denikin\'s army, which fought for a "united and indivisible" Russia and the overthrow of the Bolsheviks, while encouraging the hopes of local governments that sought to secure their sovereignty with British help, manoeuvring by "divide and rule" as circumstances required. Noe Zhordania later recalled that the British command also represented Denikin\'s interests and offered Georgia autonomy after a victory over the Bolsheviks in return for submission to Denikin. The sharpest clash came on the Black Sea coast at Sochi. In July 1918 Georgian troops pushed back the Reds and advanced through Sochi as far as Tuapse, and when a local council declared Sochi\'s "temporary" union with Georgia on 18 September, the White leadership protested bitterly. Talks between the Volunteer Army and a Georgian delegation led by Foreign Minister Evgeni Gegechkori at Ekaterinodar on 25–26 September broke down, and on 6 February 1919 the Whites captured the Georgian commander and his staff at Gagra and drove the Georgians back across the Bzyb River. Britain drew a demarcation line on the Bzyb; when the Georgians counter-attacked in April, it intervened again and set a new line on the Psou River. Talks in Tbilisi in May effectively ended the conflict, and the Psou remains the Russian–Georgian border today. On 16 June 1919 Azerbaijan and Georgia signed a defensive treaty against Denikin\'s Volunteer Army, which was threatening their borders. With the situation judged stable, British forces left Baku on 19 August 1919.',
                    sources: [S.drgRu, S.sochi, S.adr],
                },
                {
                    ko: '1920년 1월 12일 연합국 최고회의는 그루지야와 아제르바이잔, 뒤이어 아르메니아의 독립을 사실상 승인했다. 러시아어 출처는 연합국이 1919년 내내 데니킨의 승리를 기대하며 승인을 미루다가, 데니킨의 패배와 붉은 군대의 캅카스 접근이 알려진 뒤에야 이들을 소비에트 러시아와 동방 사이의 완충국으로 삼으려 했다고 서술한다. 승인의 한계는 뚜렷했다. 영국 외무차관 그린우드는 하원에서 이 결정이 각국의 국경 문제를 예단하지 않으며 대표 교환에도 변화가 없다고 답했고, 미국은 결정에 동의하지 않았다. 아제르바이잔 측 서술은 연합국의 반볼셰비키 행동이 자캅카스에서는 현상 유지, 승인, 외교적 항의 같은 말의 수준을 크게 넘지 않았다고 평가한다. 그 사이 남러시아 군대는 무너지고 있었다. 1920년 1월 29일 쿠반 카자크 중심의 캅카스군이 해체되어 단명한 쿠반군으로 바뀌었고, 의용군의 남은 병력은 3월 26~27일 노보로시스크에서 크림으로 철수했으며, 쿠반군은 4월 18~20일 붉은 군대에 항복했다. 데니킨은 4월 초 모든 권한을 표트르 브란겔에게 넘겼다. 영국군은 1920년 7월 7일 바투미를 그루지야군에 넘기고 떠났는데, 이 철수는 소비에트 러시아가 그루지야의 독립을 인정하는 대신 그루지야가 러시아에 적대적인 군대를 들이지 않기로 한 1920년 모스크바 조약의 결과로도 설명된다.',
                    en: 'On 12 January 1920 the Allied Supreme Council granted de facto recognition to Georgia and Azerbaijan, and subsequently to Armenia. Russian-language accounts say the Allies had withheld recognition throughout 1919 in the expectation that Denikin would win, and moved only once his defeat and the Red Army\'s approach to the Caucasus were known, intending the republics as buffer states between Soviet Russia and the East. The recognition had clear limits. In the House of Commons the Under-Secretary for Foreign Affairs, Greenwood, stated that it did not prejudge the republics\' boundaries and had brought no change in representation, and the United States declined to endorse it. An Azerbaijani assessment holds that, in Transcaucasia at least, Allied action against Bolshevism rarely went beyond words such as status quo, recognition and diplomatic remonstrance. Meanwhile the Armed Forces of South Russia were collapsing. On 29 January 1920 the Caucasus Army, made up mainly of Kuban Cossacks, was disbanded and replaced by the short-lived Kuban Army; the remnants of the Volunteer Army were evacuated from Novorossiysk to Crimea on 26–27 March, and the Kuban Army surrendered to the Red Army on 18–20 April. In early April Denikin handed all authority to Pyotr Wrangel. British troops handed Batumi over to the Georgian army and left on 7 July 1920, a withdrawal also attributed to the 1920 Treaty of Moscow, under which Soviet Russia recognised Georgian independence in exchange for Georgia\'s promise not to host forces hostile to Russia.',
                    sources: [S.adr, S.drgRu, S.afsr, S.swc, S.batum, S.drg],
                },
            ],
        },
        {
            heading: { ko: '북캅카스: 소비에트 공화국, 산악공화국, 이맘의 에미르국 {russia soviet}', en: 'The North Caucasus: Soviet republics, the Mountain Republic and an imam\'s emirate {russia soviet}' },
            paragraphs: [
                {
                    ko: '러시아 제국이 무너진 뒤 북캅카스에는 여러 정권이 겹쳐 들어섰다. 쿠반 카자크의 쿠반 라다는 1918년 1월 28일 쿠반 인민공화국을 선포하고 2월 16일 독립을 선언했다. 볼셰비키는 3월 1일 퍄티고르스크의 제2차 테레크 민족대회에서 테레크 소비에트 공화국을 세웠는데, 다른 소비에트 공화국과 달리 연립 정부였고 수도는 뒤에 블라디카프카스로 옮겨졌다. 테레크 당국이 카자크 토지를 몰수해 땅 없는 체첸인·인구시인에게 넘기기로 하자 7월 게오르기 비체라호프가 이끄는 카자크 봉기가 일어났다. 7월 블라디카프카스에 파견된 세르고 오르조니키제는 8월 카자크가 도시를 점령하자 산으로 피했다가, 소비에트 체제가 그들이 바라는 이슬람 질서와 비슷하다며 체첸인·인구시인을 설득했고, 인구시인의 도움으로 8월 중순 도시를 되찾았다. 1918년 말 그는 북캅카스 일대의 볼셰비키 기관을 사실상 모두 장악했다. 7월 7일에는 쿠반–흑해·스타브로폴·테레크 소비에트 공화국을 합친 북캅카스 소비에트 공화국이 예카테리노다르를 수도로 세워졌으나, 8월 16일 데니킨의 의용군이 예카테리노다르를 점령했고, 연말까지 영토 대부분을 잃은 공화국은 1919년 1월 11일 폐지되었다. 테레크 공화국도 1919년 초 의용군에 정복되었다. 백군 편에 섰던 쿠반 라다는 점차 데니킨과 멀어져 우크라이나, 이어 그루지야와의 연방을 모색했고, 파리 강화회의에 간 대표단은 1919년 4월 데니킨과의 결별을 선언했다. 데니킨은 1919년 11월 라다 건물을 포위해 의원 10명을 체포하고 대표단원 알렉세이 쿨라부호프를 반역죄로 공개 교수했다. 쿠반은 1920년 초 대부분 붉은 군대에 점령되었다.',
                    en: 'After the empire\'s collapse, rival authorities piled up in the North Caucasus. The Kuban Rada of the Kuban Cossacks proclaimed the Kuban People\'s Republic on 28 January 1918 and declared independence on 16 February. On 1 March the Bolsheviks founded the Terek Soviet Republic at the Second Congress of the Peoples of the Terek in Pyatigorsk; unlike other Soviet republics it was a coalition government, and its capital later moved to Vladikavkaz. When the Terek authorities decided to confiscate Cossack land for landless Chechens and Ingush, the Cossacks rose in July under Georgy Bicherakhov. Sergo Ordzhonikidze, sent to Vladikavkaz in July, fled to the mountains when the Cossacks seized the city in August, persuaded the Chechens and Ingush that the soviet system resembled the Islamic order they wanted, and with Ingush help retook Vladikavkaz in mid-August; by the end of 1918 he effectively controlled every Bolshevik body in the region. On 7 July the North Caucasian Soviet Republic was formed from the Kuban–Black Sea, Stavropol and Terek Soviet republics with Ekaterinodar as its capital, but Denikin\'s Volunteer Army took Ekaterinodar on 16 August, and having lost most of its territory by year\'s end the republic was abolished on 11 January 1919. The Terek republic fell to the Volunteer Army early that year. The Kuban Rada, which had backed the Whites, drifted away from Denikin, seeking federation first with Ukraine and then with Georgia, and in April 1919 its delegation at the Paris Peace Conference announced a break with him. In November 1919 Denikin had the Rada building surrounded, ten members arrested and a delegate, Alexey Kulabukhov, publicly hanged for treason. By early 1920 the Red Army held most of the Kuban.',
                    sources: [S.kuban, S.terek, S.terekRu, S.mrnc, S.ordzh, S.ncsr],
                },
                {
                    ko: '산악민 자치 운동은 1917년 5월 블라디카프카스에서 결성된 북캅카스·다게스탄 산악민 연합에서 시작되었다. 체첸 출신 석유업자 타파 체르모예프가 중앙위원회 의장, 아바르인 학자 나주무딘 고친스키가 무프티를 맡은 이 연합은 1918년 초 볼셰비키에 밀려 테미르한슈라를 거쳐 트빌리시로 옮겨 갔고, 1918년 5월 11일 북캅카스 산악공화국의 독립을 선포했다(선포 장소는 출처에 따라 바투미 강화회의 또는 이스탄불로 서술된다). 산악공화국은 오스만 원정군의 도움으로 테미르한슈라와 데르벤트를 차지했으나 오스만의 패전으로 원정군은 곧 물러났다. 뒤이어 우세한 외세가 된 영국은 처음에는 지지를 약속했지만 데니킨을 반볼셰비키 주력으로 보고 백군과 협력하라고 권했고, 데니킨은 산악공화국과의 어떤 협력도 거부했다. 백군은 카바르다와 북오세티야를 빠르게 점령했으나 체첸·인구시에서 거센 저항을 만나 초토화 전술을 썼고, 1919년 5월 페트롭스크와 데르벤트를 점령했다. 데니킨의 최후통첩에 테미르한슈라의 프셰마호 코체프 정부는 해산해 트빌리시로 망명했다. 성직자들의 노선은 갈렸다. 고친스키는 공산주의자를 더 큰 위협으로 보고 데니킨을 「덜한 악」으로 받아들였지만, 셰이크 우준 하지는 「돼지가 검든 희든 무슨 차이냐」며 양쪽을 다 거부했다. 1919년 5월 보틀리흐 회의에서 다게스탄·체첸의 이맘으로 추대된 우준 하지는 9월 19일 베데노를 근거지로 오스만 술탄의 보호를 받는 샤리아 군주국 북캅카스 에미르국을 선포했다(술탄의 칙서는 위조로 여겨진다). 에미르국은 니콜라이 기칼로가 이끈 붉은 군대 패잔병을 받아들여 함께 보즈드비젠스코예와 샬리에서 백군을 이겼고, 그루지야의 승인과 무기 지원을 받았다. 병력은 데니킨이 말한 4,000~5,000명부터 레닌에게 올라간 보고의 8,500명까지 다양하게 전해지지만, 체첸 역사가 마이르베크 바차가예프는 1,000명을 넘은 적이 없다고 본다.',
                    en: 'Mountaineer self-rule began with the Union of the Mountaineers of the North Caucasus and Dagestan, founded at Vladikavkaz in May 1917 with the Chechen oil magnate Tapa Chermoev as chairman of its central committee and the Avar scholar Najmuddin Gotsinsky as mufti. Driven out by the Bolsheviks in early 1918, its leaders moved to Temir-Khan-Shura and then to Tbilisi, and on 11 May 1918 they declared the independence of the Mountainous Republic of the Northern Caucasus (sources place the declaration either at the Batumi peace conference or in Istanbul). With an Ottoman expeditionary force the republic took Temir-Khan-Shura and Derbent, but the Ottoman defeat soon forced the troops to withdraw. Britain, now the dominant foreign power, at first promised support but then, regarding Denikin as the main force against the Bolsheviks, urged the mountaineers to cooperate with the Whites, while Denikin refused any cooperation. The Whites quickly took Kabarda and North Ossetia but met fierce resistance in Chechnya and Ingushetia, where they resorted to scorched-earth tactics, and in May 1919 they captured Petrovsk and Derbent. Under Denikin\'s ultimatum the Kotsev government at Temir-Khan-Shura dissolved itself and fled to Tbilisi. The clergy split. Gotsinsky saw the communists as the greater threat and accepted Denikin as the lesser evil, while Sheikh Uzun-Hajji rejected both sides: "What difference does it make if the pig is black or white?" Proclaimed imam of Dagestan and Chechnya at Botlikh in May 1919, Uzun-Hajji declared the North Caucasian Emirate, a sharia monarchy under the protection of the Ottoman sultan, with its base at Vedeno on 19 September (the sultan\'s firman is believed to have been forged). Taking in Nikolai Gikalo\'s defeated Red units, the emirate beat the Whites at Vozdvizhenskoye and Shali and won Georgian recognition and arms. Estimates of its strength range from Denikin\'s 4,000–5,000 to 8,500 in a report to Lenin, though the Chechen historian Mairbek Vatchagaev holds it never exceeded 1,000.',
                    sources: [S.mrnc, S.gorRu, S.uzun, S.gotsinsky, S.emirate, S.emirateRu],
                },
                {
                    ko: '1920년 2~3월 제11군이 들어와 무슬림 성직자들과 함께 데니킨군을 테레크와 다게스탄에서 몰아냈다. 3월 말 붉은 군대가 그로즈니를 차지하자 우준 하지는 도시를 넘기라고 요구했으나 거절당했고, 볼셰비키는 세속 권력을 내놓으면 이맘 칭호를 인정하겠다고 제안했다. 장티푸스를 앓던 우준 하지는 3월 30일 숨졌고 에미르국은 며칠 뒤 사라졌다. 4월 8일 결성된 러시아 공산당 캅카스국(카프비우로)은 오르조니키제를 의장, 1919년 아스트라한에서 소비에트 권력을 유혈로 다잡았던 세르게이 키로프를 부의장으로 삼았다. 그러나 산악 지대에서 새 권력은 곧 반발에 부딪혔다. 행정의 부실과 남용, 식량 징발과 테러가 원인으로 꼽히는 다게스탄 봉기는 1920년 9월 그루지야에서 넘어온 산악민 부대로 시작되었다. 고친스키가 이끌고 샤밀의 손자 사이드 샤밀이 명목상 지도자로 추대된 봉기군은 약 600명에서 6,000명으로, 1921년 1월에는 많게는 9,700명으로 불어나 아바르·안디·구니브 관구를 거의 장악하고 훈자흐와 구니브의 붉은 군대 수비대를 포위했으며, 아리카니 협곡과 보틀리흐에서 붉은 군대 부대를 섬멸했다. 붉은 군대는 증원군과 포병·장갑차·항공기, 러시아어 출처에 따르면 화학무기까지 동원해 1921년 1~3월 거점을 되찾았고, 2월 그루지야가 소비에트화되자 봉기군은 배후를 잃었다. 5월 마지막 거점 기다틀이 함락되며 봉기는 끝났다. 붉은 군대 지휘관 토도르스키에 따르면 붉은 군대 사망자는 5,000명이었고 산악민의 희생은 알려지지 않았으며, 약 100개 마을이 파괴되었다. 그 사이 1921년 1월 20일 소비에트 정부는 다게스탄을 뺀 북캅카스에 체첸·인구시·오세티야·카바르다 등 6개 관구, 인구 약 80만 명의 산악 자치 소비에트 사회주의 공화국을 세웠다. 이는 내전기 통합 구상의 유산을 받아들인 것으로 평가되지만, 1920년 테레크 카자크 3만 4,637명이 강제 이주된 뒤의 일이었고 공화국은 1924년까지 민족별 자치주로 해체되었다.',
                    en: 'In February–March 1920 the 11th Army arrived and, together with the Muslim clergy, drove Denikin\'s forces out of the Terek region and Dagestan. When the Red Army took Grozny at the end of March, Uzun-Hajji demanded the city and was refused; the Bolsheviks instead offered to recognise him as imam if he surrendered his temporal power. Already ill with typhus, he died on 30 March, and the emirate vanished a few days later. The Caucasian Bureau of the Russian Communist Party, formed on 8 April, was chaired by Ordzhonikidze, with Sergei Kirov, who had imposed Soviet power on Astrakhan with bloodshed in 1919, as his deputy. In the highlands, however, the new order soon met resistance. The Dagestan uprising, blamed on poor and abusive administration, grain requisitioning and terror, began in September 1920 with mountaineer bands crossing from Georgia. Led by Gotsinsky, with Imam Shamil\'s grandson Said Shamil as nominal leader, the rebels grew from about 600 to around 6,000 and perhaps 9,700 by January 1921; they controlled most of the Avar, Andi and Gunib districts, besieged the Red garrisons at Khunzakh and Gunib, and wiped out Red units in the Arakani gorge and at Botlikh. The Red Army brought in reinforcements, artillery, armoured cars, aircraft and, according to Russian sources, chemical weapons, retaking the strongholds between January and March 1921, and the Sovietisation of Georgia in February cut the rebels off from their rear. The last stronghold, Gidatl, fell in May. According to the Red commander Todorsky, the Red Army lost 5,000 dead; mountaineer losses are unknown, and about a hundred villages were destroyed. Meanwhile, on 20 January 1921, the Soviet government created the Mountain Autonomous Soviet Socialist Republic, covering the North Caucasus apart from Dagestan, with six districts including Chechnya, Ingushetia, Ossetia and Kabarda and about 800,000 people. It is seen as acknowledging the unity projects of the civil war, but it followed the deportation of 34,637 Terek Cossacks in 1920, and by 1924 it had been broken up into ethnic autonomous oblasts.',
                    sources: [S.mrnc, S.uzun, S.ordzh, S.kirov, S.dagUp, S.dagUpRu, S.gotsinsky, S.mountainAssr],
                },
            ],
        },
    ],
    timeline: [
        ['1918.11.17', '톰슨의 영국군, 바쿠 진주', 'Thomson\'s British troops enter Baku', '오스만군이 물러난 바쿠에 윌리엄 톰슨 장군이 영국 인도군과 러시아 부대를 이끌고 들어와 군정 총독을 자처하고 계엄을 선포했다.', 'General William Thomson entered Baku, vacated by the Ottomans, with British Indian and Russian troops, proclaimed himself military governor and imposed martial law.', ['uk', 'azerbaijan'], P(40.41, 49.87, '바쿠', 'Baku')],
        ['1918.12', '아제르바이잔 의회 개원', 'Azerbaijani parliament opens', '민족회의를 대신한 의회가 열렸다. 무사바트가 최대 분파였고 아르메니아인·러시아인 등 소수민족 대표도 의석을 얻었으며, 의회는 1919년 여성 참정권을 도입했다.', 'A parliament replaced the National Council. Musavat was the largest faction, minorities including Armenians and Russians held seats, and in 1919 it enfranchised women.', 'azerbaijan', P(40.37, 49.84, '바쿠', 'Baku')],
        ['1919.02.06', '백군, 소치 분쟁에서 그루지야군 격퇴', 'Whites drive back the Georgians at Sochi', '데니킨의 군대가 가그라에서 그루지야군 지휘부를 사로잡고 그루지야군을 브지브강 너머로 밀어냈다. 영국의 개입으로 뒤에 프소우강이 경계가 되었다.', 'Denikin\'s forces captured the Georgian command at Gagra and pushed the Georgians beyond the Bzyb; British intervention later fixed the line on the Psou.', ['russia', 'georgia', 'uk'], P(43.60, 39.73, '소치', 'Sochi')],
        ['1919.05', '의용군, 다게스탄 점령', 'Volunteer Army occupies Dagestan', '백군이 페트롭스크와 데르벤트를 점령하고, 데니킨의 최후통첩에 북캅카스 산악공화국 정부가 해산해 트빌리시로 망명했다.', 'The Whites took Petrovsk and Derbent, and under Denikin\'s ultimatum the government of the Mountainous Republic dissolved itself and fled to Tbilisi.', 'russia', P(42.98, 47.50, '페트롭스크', 'Petrovsk')],
        ['1919.09.19', '북캅카스 에미르국 선포', 'North Caucasian Emirate proclaimed', '우준 하지가 베데노를 근거지로 오스만 술탄의 보호를 받는 샤리아 군주국을 선포하고 데니킨군과 싸웠다.', 'Uzun-Hajji proclaimed a sharia monarchy under Ottoman protection, based at Vedeno, and fought Denikin\'s forces.', 'russia', P(42.96, 46.10, '베데노', 'Vedeno')],
        ['1920.01.12', '연합국, 그루지야·아제르바이잔 사실상 승인', 'Allies recognise Georgia and Azerbaijan de facto', '연합국 최고회의가 두 공화국(뒤이어 아르메니아)을 사실상 승인했지만, 국경 문제는 예단하지 않는다고 못박았다.', 'The Allied Supreme Council recognised the two republics (and later Armenia) de facto, while stating that their boundaries were not prejudged.', ['uk', 'georgia', 'azerbaijan']],
        ['1920.03.22–26', '슈샤 학살', 'Shusha massacre', '아르메니아인 봉기가 실패한 뒤 아제르바이잔 군대와 주민이 슈샤의 아르메니아인 구역을 불태우고 주민을 학살했다. 희생자 추정은 500명에서 3만 명까지 엇갈린다.', 'After a failed Armenian uprising, Azerbaijani troops and townspeople burned Shusha\'s Armenian quarter and massacred its inhabitants; estimates range from 500 to 30,000 dead.', ['azerbaijan', 'armenia'], P(39.76, 46.75, '슈샤', 'Shusha')],
        ['1920.09–1921.05', '다게스탄 봉기', 'Dagestan uprising', '고친스키가 이끈 산악민 봉기가 다게스탄 고지대 대부분을 장악했으나, 그루지야의 소비에트화 뒤 붉은 군대에 진압되었다. 붉은 군대는 5,000명을 잃었다.', 'A mountaineer revolt led by Gotsinsky seized most of highland Dagestan but was crushed by the Red Army after Georgia\'s Sovietisation; the Reds lost 5,000 dead.', 'soviet', P(42.54, 46.70, '훈자흐', 'Khunzakh')],
        ['1921.01.20', '산악 자치 소비에트 사회주의 공화국 수립', 'Mountain ASSR founded', '소비에트 정부가 다게스탄을 뺀 북캅카스에 6개 관구, 약 80만 명의 산악 자치공화국을 세웠다.', 'The Soviet government created a Mountain autonomous republic of six districts and about 800,000 people covering the North Caucasus apart from Dagestan.', 'soviet', P(43.02, 44.68, '블라디카프카스', 'Vladikavkaz')],
    ],
    people: [
        ['mammad-amin-rasulzade', 'leader', '아제르바이잔 민족회의 의장', 'Chairman of the Azerbaijani National Council', '민족회의를 이끌고 1918년 5월 28일 아제르바이잔 민주공화국 수립을 선포했다.', 'Led the National Council that proclaimed the Azerbaijan Democratic Republic on 28 May 1918.', 'national-governments'],
        ['anton-denikin', 'leader', '남러시아 군대 총사령관', 'Commander-in-chief of the Armed Forces of South Russia', '「단일 불가분 러시아」를 내걸고 그루지야와 소치를 다투었으며, 북캅카스와 다게스탄을 점령하고 쿠반 라다를 탄압했다.', 'Fought Georgia over Sochi in the name of a "united and indivisible" Russia, occupied the North Caucasus and Dagestan, and suppressed the Kuban Rada.', 'british-and-whites'],
        ['pyotr-wrangel', 'participant', '캅카스군 사령관', 'Commander of the Caucasus Army', '쿠반 카자크 중심의 캅카스군을 지휘했고, 1920년 4월 데니킨에게서 모든 권한을 넘겨받았다.', 'Commanded the largely Kuban Cossack Caucasus Army and took over all authority from Denikin in April 1920.', 'british-and-whites'],
        ['noe-zhordania', 'witness', '그루지야 정부 수반', 'Head of the Georgian government', '영국 사령부가 데니킨의 이익까지 대변하며 그루지야에 데니킨 복종을 요구했다고 회고했다.', 'Recalled that the British command also represented Denikin\'s interests and pressed Georgia to submit to him.', 'national-governments'],
        ['evgeni-gegechkori', 'participant', '그루지야 외무장관', 'Georgian foreign minister', '1918년 9월 예카테리노다르에서 의용군과 소치 귀속 문제를 협상했으나 결렬되었다.', 'Negotiated with the Volunteer Army over Sochi at Ekaterinodar in September 1918, without result.', 'national-governments'],
        ['ordzhonikidze', 'leader', '북캅카스 볼셰비키 지도자, 캅카스국 의장', 'Bolshevik leader in the North Caucasus, chairman of the Caucasian Bureau', '1918년 인구시인의 도움으로 블라디카프카스를 되찾았고 1920년 4월 캅카스국 의장이 되었다.', 'Retook Vladikavkaz with Ingush help in 1918 and became chairman of the Caucasian Bureau in April 1920.', 'soviet-forces'],
        ['kirov', 'participant', '캅카스국 부의장', 'Deputy chairman of the Caucasian Bureau', '1919년 아스트라한에서 소비에트 권력을 다잡았고, 1920년 캅카스국 부의장으로서 다게스탄 봉기 진압 동원에도 참여했다.', 'Enforced Soviet power in Astrakhan in 1919 and, as deputy head of the Caucasian Bureau, took part in mobilising against the Dagestan uprising.', 'soviet-forces'],
        ['najmuddin-gotsinsky', 'leader', '북캅카스 무프티, 다게스탄 봉기 지도자', 'Mufti of the North Caucasus, leader of the Dagestan uprising', '1919년 데니킨을 「덜한 악」으로 받아들였다가, 1920~1921년 다게스탄 반소비에트 봉기를 이끌었다.', 'Accepted Denikin as the lesser evil in 1919, then led the anti-Soviet Dagestan uprising of 1920–1921.', 'north-caucasus-mountaineers'],
    ],
    notes: [
        '독립 선언 장소: 지시문은 「간자에서 독립 선언」이라 했으나 en ADR 문서는 민족회의가 1918.5.28 트빌리시(Tiflis)에서 선포했고 간자는 임시 수도였다고 함 — 본문은 트빌리시 선포·간자 임시 수도로 씀.',
        '아제르바이잔 의회: 개원일 12월 7일(ADR Establishment 절)과 12월 5일(Domestic 절)이 같은 문서 안에서 엇갈림 → 본문 「12월 5일 또는 7일」, 연표 날짜는 1918.12. 의석도 120석(서두, 아르메니아인 21석)과 96석(Domestic 절, 무사바트 38석)으로 엇갈려 둘 다 적음.',
        '여성 참정권 연도 1919는 en Musavat 문서에서만 확인(ADR 문서는 연도 없음).',
        '톰슨 부대 규모: en Thomson 문서 약 2,000명(영국 인도군), en ADR 문서 5,000명 → 범위로 씀. ru 그루지야 문서의 「1918년 말 그루지야 2.5만, 자캅카스 6만 명」 영국군 수치는 다른 출처로 확인 못 해 뺌.',
        '영국 바쿠 철수 1919.8.19(en ADR). 바투미 철수 1920.7.7은 en 「Provisional National Government of the Southwestern Caucasus」(파일 en__Kars_Republic.txt, 옛 제목 Kars Republic이 리다이렉트됨) 문서, 「1920년 여름」은 en Batum oblast. 모스크바 조약과의 연관은 en Democratic Republic of Georgia 서술.',
        '「단일 불가분 러시아」와 멘테샤시빌리 평가, 조르다니아 회고, 연합국 승인 지연 배경은 ru 「Грузинская демократическая республика」(첫 줄 제목 소문자 д) 문서에만 있음. 이 ru 문서 소치 절은 친러시아 관점이 강해 본문에는 en Sochi conflict 기준 사실만 씀.',
        'en ADR의 「데니킨–아르메니아 비밀 군사 협정, 아르메니아군이 데니킨군 제7군단 구성」 주장은 출처 하나뿐이고 논쟁적이라 뺌.',
        '산악공화국 독립 선포(1918.5.11) 장소: en 문서 「이스탄불 망명 중」, ru 문서 「바투미 강화회의」 → 둘 다 적음. 영토·인구도 en(430,874 km², 1,120만)과 ru(12.5만 km², 약 400만)가 크게 달라 뺌.',
        '우준 하지 사인: en Uzun-Hajji 문서는 장티푸스로 병사, en Najmuddin 문서는 「died in combat」 → 본문은 병사로 씀. ru 에미르국 문서와 en Uzun-Hajji 문서가 1920.5.11 산악민 대회를 그의 사후 일로 적음(본문에서 뺌).',
        '다게스탄 봉기: en Najmuddin 문서는 봉기가 1920.5.11 베데노 회합에서 시작했고 훈자흐·구니브를 「점령」했다고 하나, en Dagestan uprising·ru 문서는 9월 시작·두 곳 포위로 씀 → 후자 따름. 「약 100개 마을 파괴」와 화학무기 사용은 ru 문서에만 있음.',
        '산악 ASSR 수립일: en Mountain ASSR 문서 1921.1.20, en Mountainous Republic 문서는 「1921년 4월」 → 1.20 따름.',
        '쿠반 라다 탄압 날짜: en Kuban 문서가 「1919.11.6」을 데니킨이 소식을 들은 날·점령일로 혼용해 본문은 「1919년 11월」로만 씀.',
        '키로프의 아스트라한 「4,000명 이상 살해」는 몬테피오리 인용이라 본문에는 수치 없이 「유혈로」만 씀.',
        '링크 위험: 「의용군」「캅카스군」「쿠반군」「제11군」 등 군 명칭, 「민족회의」(아제르바이잔 민족회의로 풀어 씀), 「캅카스국」(러시아 공산당 캅카스국). 「이슬람 군대」는 오스만 이슬람 군대로 씀.',
    ].join('\n'),
};
