// Sections 9–10 of transcaucasia-1917-1921: Sovietization 1920–1921 and assessment.
const E = t => 'https://en.wikipedia.org/wiki/' + encodeURI(t.replace(/ /g, '_'));
const RU = t => 'https://ru.wikipedia.org/wiki/' + encodeURI(t.replace(/ /g, '_'));

const S = {
    azInv: E('Soviet invasion of Azerbaijan'),
    bakuRu: RU('Бакинская операция'),
    ganja: E('1920 Ganja revolt'),
    aaw: E('Armenian–Azerbaijani war (1918–1920)'),
    nzhdeh: E('Garegin Nzhdeh'),
    tiArm: E('Turkish invasion of Armenia'),
    alex: E('Treaty of Alexandropol'),
    karabekir: E('Kâzım Karabekir'),
    arInv: E('Soviet invasion of Armenia'),
    febUp: E('February Uprising'),
    mtnArm: E('Republic of Mountainous Armenia'),
    geInv: E('Soviet invasion of Georgia'),
    geRu: RU('Советизация Грузии'),
    moscow21: E('Treaty of Moscow (1921)'),
    kars: E('Treaty of Kars'),
    affair: E('Georgian affair'),
    tsfsr: E('Transcaucasian Socialist Federative Soviet Republic'),
    august: E('August Uprising'),
    narimanov: E('Nariman Narimanov'),
    ordzh: E('Sergo Ordzhonikidze'),
    army11: E('11th Army (RSFSR)'),
};

const P = (lat, lng, ko, en) => ({ kind: 'point', lat, lng, label: { ko, en } });

module.exports = {
    sections: [
        {
            heading: { ko: '소비에트화, 1920–1921 {soviet azerbaijan armenia georgia turkey}', en: 'Sovietization, 1920–1921 {soviet azerbaijan armenia georgia turkey}' },
            paragraphs: [
                {
                    ko: '북캅카스에서 백군을 몰아낸 제11군은 1920년 4월 아제르바이잔 국경에 이르렀다. 러시아어 문헌에 따르면 바쿠 작전은 아제르바이잔 공산당 지도부와 캅카스 전선 사령관 미하일 투하쳅스키, 혁명군사위원 그리고리 오르조니키제가 함께 짰다. 4월 27일 새벽 3시 장갑열차 「제3 인터내셔널」이 사무르강 다리의 국경을 넘었는데, 이는 바쿠의 공산주의자들이 정부에 최후통첩을 내기 12시간 전이었다. 같은 날 바쿠에서는 노동자 부대와 함대가 역·우편국·전신국을 장악했고, 국방장관 사마드 메흐만다로프는 의회에 무력 저항이 불가능하다고 보고했다. 의회는 그날 밤 아제르바이잔의 완전한 독립 유지, 붉은 군대의 바쿠 강제 진입 방지 등을 조건으로 내걸고 반대 1표로 권력 이양을 의결했고, 4월 28일 새벽 2시 해산했다. 나리만 나리마노프를 포함한 6인의 아제르바이잔 혁명위원회(아즈레브콤)가 소비에트 공화국을 선포하고 모스크바에 원조를 청하는 전보를 보냈으며, 같은 날 새벽 아나스타스 미코얀 등을 태운 장갑열차가 바쿠역에 들어왔다. 아제르바이잔 정부가 요청한 군사 지원을 노이 조르다니아의 그루지야 정부는 거절했고, 일부 터키 장교들은 붉은 군대에 저항하지 말라고 선전했다. 10~15일 사이에 나히체반(7월 말)을 뺀 전국에 소비에트 권력이 세워졌고, 5월 12일 제11군 부대가 슈샤에 들어갔다. 카라바흐의 아르메니아군을 지휘하던 드라스타마트 카나얀(드로)과 가레긴 은즈데는 5월 24일 철수에 합의했으나, 은즈데는 8월 붉은 군대의 잔게주르·카라바흐·나히체반 진입을 허용한 소련-아르메니아 합의 뒤에도 잔게주르 남부를 떠나라는 명령을 거부했다.',
                    en: 'Having driven the Whites out of the North Caucasus, the 11th Army reached the Azerbaijani frontier in April 1920. According to Russian-language accounts, the Baku operation was planned jointly by the leaders of the Azerbaijani Communist Party, the Caucasian Front commander Mikhail Tukhachevsky and the front\'s military-revolutionary council member Grigory Ordzhonikidze. At 3 a.m. on 27 April the armoured train "III International" crossed the border at the Samur bridge, twelve hours before Baku communists delivered their ultimatum to the government. That day workers\' detachments and the fleet seized the city\'s station, post office and telegraph, and War Minister Samad Mehmandarov told parliament that armed resistance was not feasible. Late that night parliament voted, with one vote against, to hand over power on conditions that included preserving Azerbaijan\'s full independence and preventing the Red Army from entering Baku by force, and it dissolved itself at 2 a.m. on 28 April. A six-member Azerbaijani Revolutionary Committee (Azrevkom) including Nariman Narimanov proclaimed a Soviet republic and cabled Moscow for help; early on 28 April an armoured train carrying Anastas Mikoyan and others pulled into Baku station. Noe Zhordania\'s Georgian government declined Azerbaijan\'s request for military aid, while some Turkish officers urged the population not to resist the Red Army. Within ten to fifteen days Soviet rule had been established across the country except Nakhchivan (late July), and on 12 May 11th Army units entered Shusha. Drastamat Kanayan (Dro) and Garegin Nzhdeh, commanding Armenian forces in Karabakh, agreed on 24 May to withdraw, but in August Nzhdeh refused orders to leave southern Zangezur even after a Soviet–Armenian agreement allowed the Red Army into Zangezur, Karabakh and Nakhchivan.',
                    sources: [S.azInv, S.bakuRu, S.nzhdeh, S.aaw],
                },
                {
                    ko: '점령 초기 바쿠에서는 주민들이 「약탈 주간」이라 부른 며칠 동안의 약탈이 벌어졌고, 독일 역사가 외르크 바베로프스키는 볼셰비키가 점령자로 들어왔다고 썼다. 보고에 따르면 처음 이틀 동안 바일 감옥에서 300명이 처형되었으며, 5월 16일 바쿠에 도착한 나리마노프는 혁명위원회의 재가 없는 처형을 금지하자고 제안했으나 받아들여지지 않았다. 한편 1920년 4월부터 10월 말까지 아제르바이잔에서 러시아로 보낸 석유는 1억 4,500만 푸드에 이르렀고, 레닌은 4월 29일 바쿠 소식이 「우리 공업 전체를 되살릴 경제적 기반」을 뜻한다고 말했다. 옛 아제르바이잔군 장교들의 해임과 부대 해산에 대한 불만은 5월 26~31일의 간자 봉기로 터졌다. 약 2,000명의 병사로 시작한 봉기는 시민 의용병이 가세해 1만~1만 2,000명으로 불어났고, 성직자들은 볼셰비키 정부에 대한 성전을 호소했다. 5월 29일 붉은 군대의 공격이 실패하자 제11군은 보병 5개 연대, 기병 6개 연대, 대포 57문 등을 모아 31일 북쪽에서 총공세를 폈다. 제11군 작전부장의 보고조차 포격으로 도시의 절반이 파괴되었다고 적었고, 진압 뒤 장군 12명을 비롯한 장교와 군인 수백 명이 총살되었다. 이 봉기 뒤 남아 있던 아제르바이잔군 부대는 모두 해산되었고, 다른 지방의 봉기는 1924년까지 완전히 진압되지 않았다.',
                    en: 'The first days of the occupation brought what Baku residents called the "Week of Plunder", and the German historian Jörg Baberowski writes that the Bolsheviks entered Azerbaijan as occupiers. Reports indicate that 300 people were executed at Bayil prison in the first two days; Narimanov, who reached Baku on 16 May, proposed that no one be executed without the Revolutionary Committee\'s sanction, but the proposal was rejected. Between April and the end of October 1920 some 145 million poods of oil were shipped from Azerbaijan to Russia, and on 29 April Lenin said that the news from Baku meant "an economic base capable of revitalizing our entire industry". Resentment at the dismissal of officers of the former Azerbaijani army and the disbanding of its units erupted in the Ganja revolt of 26–31 May. Begun by about 2,000 soldiers, the rising grew to 10,000–12,000 as townspeople joined, and clerics called for holy war against the Bolshevik government. After a failed Red Army attack on 29 May, the 11th Army massed five infantry and six cavalry regiments and 57 guns and launched a general assault from the north on 31 May. Even the report of the 11th Army\'s head of operations recorded that shelling had destroyed half of Ganja, and after the suppression hundreds of officers and soldiers, twelve generals among them, were shot. All remaining Azerbaijani army formations were then disbanded, and uprisings elsewhere in the country were not fully suppressed until 1924.',
                    sources: [S.azInv, S.ganja],
                },
                {
                    ko: '세브르 조약을 거부한 앙카라의 터키 대국민의회 정부는 1920년 4월 26일 무스타파 케말 명의로 레닌에게 「제국주의 정부들」에 맞선 공동 투쟁을 약속하며 금과 무기를 요청했고, 그해 소비에트 정부는 소총 6,000정과 탄약, 금괴를 보냈다. 6월 동부전선 사령관이 된 카즘 카라베키르는 9월 13일 새벽 올투 일대의 아르메니아군을 공격했고, 사르카미시를 거쳐 10월 30일 카르스를, 일주일 뒤 알렉산드로폴을 점령했다. 아르메니아는 11월 18일 휴전에 응했으며, 이 침공으로 학살된 아르메니아인은 약 6만 명에서 많게는 10만 명으로 추산된다. 그 사이 스탈린은 레닌의 지시로 오르조니키제에게 아제르바이잔에서 아르메니아로 들어가 친볼셰비키 정부를 세우라고 명했다. 11월 28~29일 밤 아나톨리 게커의 제11군이 카라반사라이(지금의 이제반)로 넘어왔고, 아르메니아 혁명위원회가 소비에트 공화국을 선포했다. 12월 2일 아르메니아 정부는 소련 전권대표 보리스 레그란과 협정을 맺고 소비에트 정부에 권력을 넘겼는데, 협정은 다슈나크 당원을 처벌하지 않고 소비에트 러시아가 영토 안전을 보장한다고 약속했다. 바로 다음 날 새벽 알렉산드르 하티샨의 대표단은 카라베키르와 알렉산드로폴 조약에 서명해 옛 카르스주와 수르말루를 터키에 넘기고, 군대를 소총수 1,500명으로 줄이며, 세브르 조약을 무효로 선언했다. 서명 전날 정부가 이미 사임했으므로 이 조약은 무효로 간주되지만, 그 국경은 뒤의 카르스 조약의 틀이 되었다. 붉은 군대는 12월 4일 예레반에 들어갔고, 6일에는 체카가 뒤따랐다.',
                    en: 'Rejecting the Treaty of Sèvres, the Grand National Assembly government in Ankara wrote to Lenin in Mustafa Kemal\'s name on 26 April 1920, pledging a common struggle against "imperialist governments" and asking for gold and arms; that year the Soviet government sent 6,000 rifles, ammunition and gold bullion. Kâzım Karabekir, appointed to command the Eastern Front in June, attacked Armenian positions around Oltu before dawn on 13 September, pushed through Sarıkamış, took Kars on 30 October and Alexandropol a week later. Armenia accepted a ceasefire on 18 November; estimates of Armenians massacred during the invasion run from about 60,000 to as many as 100,000. Meanwhile Stalin, on Lenin\'s instruction, ordered Ordzhonikidze to enter Armenia from Azerbaijan and install a pro-Bolshevik government. On the night of 28–29 November Anatoly Gekker\'s 11th Army crossed at Karavansarai (today Ijevan), and an Armenian Revolutionary Committee proclaimed a Soviet republic. On 2 December the Armenian government signed an agreement with the Soviet plenipotentiary Boris Legran and handed power to a Soviet government; it promised that Dashnak members would not be persecuted and that Soviet Russia would guarantee Armenia\'s security. In the early hours of the next day Alexander Khatisian\'s delegation signed the Treaty of Alexandropol with Karabekir, ceding the former Kars oblast and Surmalu to Turkey, limiting the army to 1,500 riflemen and renouncing Sèvres. Because the government had resigned the day before, the treaty is regarded as invalid, yet its borders became the framework for the later Treaty of Kars. The Red Army entered Yerevan on 4 December, and the Cheka followed on the 6th.',
                    sources: [S.tiArm, S.alex, S.karabekir, S.arInv],
                },
                {
                    ko: '소비에트 아르메니아 당국은 다슈나크 당원을 탄압하지 않겠다는 약속을 어겼다. 약 1,000명의 장교가 체포되어 예레반에서 알라베르디까지 걸어서 끌려갔고, 1921년 2월에는 사르다라바트 전투의 지휘관 다니엘 베크-피루먄 등이 총살되었으며, 농민의 밀은 보상 없이 징발되었다. 다슈나크는 2월 13일 봉기를 일으켜 18일 예레반에 들어갔고, 마지막 총리 시몬 브라치안이 이끄는 조국구원위원회가 정부 역할을 맡았다. 그러나 수적으로 크게 앞선 붉은 군대가 3월 24일 대공세를 펴 4월 2일 예레반을 되찾았고, 봉기 세력과 피란민은 잔게주르로 물러났다. 그곳에서는 은즈데가 소련 정부의 잔게주르·카라바흐 아제르바이잔 편입 제안을 거부하고 1920년 12월 25일 시우니크의 자치를 선언해 두었다. 4월 26일 타테브 수도원에서 열린 대회는 산악 아르메니아 공화국의 독립을 선포했고, 6월 1일 국호를 아르메니아 공화국으로 바꿔 브라치안이 총리를 맡았다. 이 공화국은 시우니크를 소비에트 아르메니아에 남긴다는 소련 측 약속을 받고 1921년 7월 항복했으며, 은즈데와 지도자들은 페르시아로 넘어갔다. 볼셰비키 정부는 봉기의 원인을 검토해 주민을 더 관용적으로 대하기로 했고, 알렉산드르 먀스니코프를 아르메니아 인민위원회의 의장으로 임명했다. 카라바흐에 대해서는 1921년 7월 5일 러시아 공산당 캅카스국이 산악 지대를 아제르바이잔 관할에 두기로 결정했다.',
                    en: 'The Soviet Armenian authorities broke their promise not to persecute Dashnaks. About 1,000 officers were arrested and marched on foot from Yerevan to Alaverdi; in February 1921 Daniel Bek-Pirumyan and other commanders of the Battle of Sardarabad were shot, and peasants\' wheat was requisitioned without compensation. The Dashnaks rose on 13 February and entered Yerevan on the 18th, where a Salvation Committee of the Fatherland under the last prime minister, Simon Vratsian, took up the functions of government. But the far more numerous Red Army opened a large offensive on 24 March and retook Yerevan on 2 April, and the insurgents and refugees withdrew to Zangezur. There Nzhdeh had already rejected the Soviet proposal to attach Zangezur and Karabakh to Soviet Azerbaijan and on 25 December 1920 declared Syunik self-governing. On 26 April 1921 a congress at Tatev monastery proclaimed the independent Republic of Mountainous Armenia, renamed the Republic of Armenia on 1 June with Vratsian as prime minister. It capitulated in July 1921 after Soviet promises to keep Syunik within Soviet Armenia, and Nzhdeh and the republic\'s leaders crossed into Persia. The Bolshevik government reviewed the causes of the revolt, decided to treat the population with more tolerance, and appointed Alexander Myasnikov chairman of Armenia\'s Council of People\'s Commissars. As for Karabakh, on 5 July 1921 the Caucasian Bureau of the Russian Communist Party decided to leave its mountainous part under Azerbaijani jurisdiction.',
                    sources: [S.febUp, S.mtnArm, S.nzhdeh, S.aaw],
                },
                {
                    ko: '1920년 5월 모스크바 조약으로 독립을 인정받은 그루지야의 처리를 두고 볼셰비키 지도부는 갈라져 있었다. 오르조니키제가 의장, 세르게이 키로프가 부의장인 캅카스국과 민족인민위원 스탈린은 즉각적인 군사 전복을 거듭 주장했고, 레프 트로츠키는 「때 이른 개입」에 반대하며 주민이 스스로 혁명을 일으킬 준비 기간을 두자고 했으며, 레닌은 처음에 무력 사용을 거부하고 극도의 신중함을 요구했다. 1921년 2월 11~12일 밤 오르조니키제의 부추김으로 아르메니아인이 많이 사는 로리 지구와 슐라베리에서 볼셰비키가 그루지야 초소를 공격했고, 필리프 마하라제가 이끄는 그루지야 혁명위원회가 모스크바에 원조를 청했다. 러시아 공산당 중앙위원회는 2월 14일 제11군의 트빌리시 점령을 조건부로 허용했는데, 이 결정은 카를 라데크가 반대했고 우랄에 있던 트로츠키에게는 알리지 않았다. 2월 16일 게커의 주력이 국경을 넘었고, 코조리 고지에서 일주일 동안 공방이 이어진 끝에 그루지야군 총사령관 기오르기 크비니타제가 철수를 명령해 2월 25일 붉은 군대가 트빌리시에 들어가 그루지야 소비에트 공화국을 선포했다. 그 사이 카라베키르는 2월 23일 아르다한·아르트빈 철수를 요구하는 최후통첩을 내고 국경 지대를 점령했고, 3월 8일 터키군은 그루지야 정부와의 구두 합의로 바투미 주변에 진주해 소련과 위기를 빚었다. 3월 2일 레닌은 멘셰비키와 「받아들일 만한 타협」을 찾는 것이 매우 중요하다고 강조했으나 멘셰비키는 연립 제안을 거부했다.',
                    en: 'The Bolshevik leadership was divided over Georgia, whose independence it had recognized in the Treaty of Moscow of May 1920. The Caucasian Bureau, chaired by Ordzhonikidze with Sergei Kirov as his deputy, and Stalin as People\'s Commissar of Nationalities repeatedly pressed for a military overthrow; Leon Trotsky opposed a "premature intervention" and wanted a preparatory period so that the population could make the revolution itself; and Lenin at first rejected the use of force and called for extreme caution. On the night of 11–12 February 1921, at Ordzhonikidze\'s instigation, Bolsheviks attacked Georgian posts in the largely Armenian district of Lori and at Shulaveri, and a Georgian Revolutionary Committee headed by Filipp Makharadze appealed to Moscow for help. On 14 February the Russian Communist Party Central Committee conditionally allowed the 11th Army to occupy Tbilisi, a decision Karl Radek opposed and that was kept from Trotsky, then in the Urals. Gekker\'s main force crossed the border on 16 February; after a week of fighting for the Kojori heights, the Georgian commander-in-chief Giorgi Kvinitadze ordered a withdrawal, and on 25 February the Red Army entered Tbilisi and proclaimed a Georgian Soviet Socialist Republic. Meanwhile Karabekir issued an ultimatum on 23 February demanding Georgia\'s evacuation of Ardahan and Artvin and occupied the border districts, and on 8 March Turkish troops took up positions around Batumi under a verbal agreement with the Georgian government, provoking a crisis with Moscow. On 2 March Lenin stressed the "tremendous importance" of an acceptable compromise with the Mensheviks, but they turned down the offer of a coalition.',
                    sources: [S.geInv, S.geRu, S.affair],
                },
                {
                    ko: '3월 16일 모스크바에서 소비에트 러시아와 터키 대국민의회 정부는 우호 조약을 맺었다. 이 조약으로 터키는 바투미와 사르프 이북 지역을 소비에트 그루지야에 넘기는 대신 카르스주를 얻었고, 나히체반은 소비에트 아제르바이잔의 보호 아래 자치 지역이 되었다. 같은 날 영국은 소비에트 정부와 통상협정을 맺어 옛 러시아 제국 영토에서 반소 활동을 삼가기로 사실상 약속했으므로, 그루지야 정부의 서방 개입 기대는 사라졌다. 터키군이 바투미에서 물러나지 않자 그루지야 정부는 3월 17일 쿠타이시에서 혁명위원회 측과 휴전했고, 18일 기오르기 마즈니아슈빌리 장군이 이끄는 그루지야군이 바투미에서 터키군과 시가전을 벌였다. 그 사이 멘셰비키 정부는 이탈리아 배를 타고 망명길에 올랐고, 19일 마즈니아슈빌리는 도시를 혁명위원회에 넘겼다. 바투미 사태로 중단되었던 협상은 9월 26일 카르스에서 재개되어, 10월 13일 터키와 아르메니아·아제르바이잔·그루지야의 세 소비에트 공화국이 러시아의 참여 아래 카르스 조약에 서명했다. 터키 측 서명자에는 카라베키르가 있었다. 조약은 모스크바 조약을 재확인해 아르다한·아르트빈·카르스와 수르말루를 터키에 주고, 바투미를 포함한 북부를 그루지야 안의 아자르 자치공화국으로 삼으며, 터키군을 알렉산드로폴 일대에서 철수시켰다. 이때 그어진 터키와 아르메니아·그루지야·아제르바이잔의 국경은 오늘날까지 이어진다.',
                    en: 'On 16 March Soviet Russia and the Grand National Assembly government signed a treaty of friendship in Moscow. Turkey gave Batumi and the area north of Sarp to Soviet Georgia and received the Kars oblast, and Nakhchivan became an autonomous territory under Soviet Azerbaijan\'s protection. On the same day Britain signed a trade agreement with the Soviet government that effectively committed it to refrain from anti-Soviet activity in the former Russian Empire, ending Georgian hopes of Western intervention. When Turkish troops would not leave Batumi, the Georgian government agreed an armistice with the Revolutionary Committee at Kutaisi on 17 March, and on the 18th Georgian troops under General Giorgi Mazniashvili fought the Turks in the streets of Batumi. Meanwhile the Menshevik government sailed into exile on an Italian ship, and on the 19th Mazniashvili handed the city to the Revolutionary Committee. Talks broken off by the Batumi fighting resumed at Kars on 26 September, and on 13 October Turkey and the three Soviet republics of Armenia, Azerbaijan and Georgia, with Soviet Russia participating, signed the Treaty of Kars; Karabekir was among the Turkish signatories. The treaty reaffirmed the Moscow terms, giving Ardahan, Artvin, Kars and Surmalu to Turkey, making the northern part with Batumi the Adjar autonomous republic within Georgia, and requiring Turkish troops to withdraw from the Alexandropol area. The borders it drew between Turkey and Armenia, Georgia and Azerbaijan remain in place today.',
                    sources: [S.moscow21, S.geInv, S.kars, S.tsfsr],
                },
            ],
        },
        {
            heading: { ko: '평가: 민족혁명인가, 내전의 한 전선인가, 국제 분쟁인가 {georgia armenia azerbaijan}', en: 'Assessment: national revolution, civil-war front or international conflict? {georgia armenia azerbaijan}' },
            paragraphs: [
                {
                    ko: '소련 역사학은 자캅카스의 소비에트화를 「내전과 외국 간섭」의 일부로 보았다. 초기에는 그루지야 원정을 「혁명 전쟁」이라 불렀으나 이 말이 「침략」과 구별하기 어려워지자, 뒤의 공식 서술은 현지 노동자·농민이 봉기해 붉은 군대의 도움을 청했다는 설명으로 바꾸었다. 소련 저자들은 러시아 부대의 역할을 협상국과 터키의 간섭에 맞선 자캅카스 근로인민의 「형제적·국제주의적 원조」로 규정했고, 1967년 소련 책자는 아르메니아의 1920년 11월을 다슈나크 통치를 끝낸 근로인민의 봉기로 묘사했다. 아제르바이잔에서 1920년 4월은 「4월 혁명」으로 기념되다가 1937~1938년 탄압기 이후 그 말이 문서에서 사라졌다. 반면 피루즈 카젬자데는 제11군이 공식 요청 전에 들어온 점을 들어 무사바트 정부의 몰락을 「되살아난 러시아의 힘」의 결과로 보았고, 바베로프스키 등은 이를 「침공」으로 서술한다. 망명 정치인과 독립 이후의 국가 기관도 같은 결론을 내렸다. 1989년 그루지야 최고소비에트 위원회는 1921년의 사건을 「군사 간섭이자 점령」으로 판정했고, 1991년 아제르바이잔의 독립 회복 헌법 법률은 1920년 4월을 「점령」으로 규정했으며, 그루지야는 2010년부터 2월 25일을 「소비에트 점령의 날」로 기념한다. 다만 평가가 한 방향만은 아니다. 타데우시 시비엥토호프스키는 무사바트의 몰락을 대중의 「공동체적 의식」과 무관심에서 찾았고, 아르메니아에 대해서는 소련의 개입만이 아르메니아인 학살의 완결을 막았다고 보는 역사가들도 있다.',
                    en: 'Soviet historiography treated the sovietization of Transcaucasia as part of "the Civil War and Foreign Intervention". Early Soviet writing called the Georgian campaign a "revolutionary war", but as that term became hard to distinguish from "aggression" the official account shifted to a story of local workers and peasants rising and asking the Red Army for help. Soviet authors described the role of Russian units as "fraternal, internationalist assistance" protecting the working people of Transcaucasia from Entente and Turkish intervention, and a 1967 Soviet book portrayed Armenia\'s November 1920 as a rising of the working people that ended Dashnak rule. In Azerbaijan April 1920 was commemorated as the "April Revolution" until the term vanished from documents after the repressions of 1937–1938. By contrast, Firuz Kazemzadeh, noting that the 11th Army crossed the border before any official request, attributed the Musavat government\'s fall to "the power of a resurgent Russia", and Jörg Baberowski and others describe it as an invasion. Exiles and post-independence state bodies reached the same conclusion: a 1989 commission of the Georgian Supreme Soviet found the events of 1921 to have been "military interference, intervention, and occupation", Azerbaijan\'s 1991 constitutional act on restoring independence calls April 1920 an "occupation", and since 2010 Georgia has marked 25 February as Soviet Occupation Day. The verdicts do not all point one way, however: Tadeusz Swietochowski explained the Musavat collapse by the masses\' "communal consciousness" and indifference, and several historians argue that for Armenia only Soviet intervention prevented the completion of the Armenian genocide.',
                    sources: [S.geInv, S.azInv, S.arInv, S.tiArm],
                },
                {
                    ko: '국제사의 관점에서 자캅카스의 소비에트화는 러시아 내전의 마지막 전선이자 소비에트 러시아와 케말의 터키가 협상국의 질서를 함께 무너뜨린 과정이었다. 케말은 1920년 2월 카라베키르에게 영국의 「캅카스 장벽」을 뒤에서 허물라고 지시했고, 8월 대국민의회에서 붉은 군대의 아제르바이잔 점령을 「우리의 목표이자 영향력」이라 불렀다. 아제르바이잔의 역사가 R. 무스타파자데는 아제르바이잔 민주공화국 몰락의 가장 중요한 요인으로 바로 이 터키-소련 접근을 꼽는다. 스탈린은 1920년 11월 캅카스의 의미가 원료와 연료뿐 아니라 유럽과 아시아, 러시아와 터키 사이의 전략적 위치에 있다며, 캅카스를 누가 지배하느냐를 혁명과 협상국의 대결로 설명했다. 그러나 두 동맹국의 이해는 아르메니아와 바투미에서 부딪혔고, 그 결과 볼셰비키는 아니와 쿨프를 아르메니아에 남기려던 시도에서 물러서며 카르스 조약에서 큰 영토를 양보했다. 영국은 철수했고, 망명한 그루지야 지도부가 1921년 3월 27일 이스탄불에서 세계 사회주의 정당들에 보낸 호소에도 국제 사회는 대체로 침묵했다. 다슈나크는 지금도 카르스 조약을 모스크바의 통제 아래 맺어진 국제법 위반이라며 거부한다.',
                    en: 'From the standpoint of international history, the sovietization of Transcaucasia was both the last front of the Russian Civil War and a process in which Soviet Russia and Kemal\'s Turkey jointly dismantled the Entente\'s order in the region. In February 1920 Kemal instructed Karabekir to break up Britain\'s "Caucasus barrier" from the rear, and in August he told the Grand National Assembly that the Red Army\'s occupation of Azerbaijan was "our objective, influence, and work". The Azerbaijani historian R. Mustafazadeh identifies this Turkish–Soviet rapprochement as the most critical factor in the fall of the Azerbaijan Democratic Republic. In November 1920 Stalin argued that the Caucasus mattered not only for raw materials and fuel but for its strategic position between Europe and Asia and between Russia and Turkey, framing control of the region as a contest between the revolution and the Entente. The two allies\' interests collided over Armenia and Batumi, however, and the Bolsheviks gave up their attempt to keep Ani and Kulp for Armenia and made large territorial concessions at Kars. Britain had withdrawn, and the world largely met with silence the appeal that the exiled Georgian leadership sent from Istanbul to the world\'s socialist parties on 27 March 1921. The Dashnaks still reject the Treaty of Kars as a breach of international law concluded under Moscow\'s control.',
                    sources: [S.azInv, S.kars, S.geInv],
                },
                {
                    ko: '레닌은 1920년 3월 바쿠 진공을 앞두고 오르조니키제에게 바쿠는 「극히 중요하다」면서도 그루지야에 대해서는 더 신중하게 행동하라고 권했다. 1921년 그루지야 점령 뒤에도 그는 친볼셰비키 봉기가 주장된 만큼의 대중적 지지를 얻지 못했음을 알고 그루지야 지식인·농민과의 화해 정책을 지지했고, 마하라제 같은 온건파는 멘셰비키에 대한 관용과 점진적 토지개혁, 그루지야의 주권 존중을 주장했다. 그러나 스탈린은 1921년 7월 트빌리시 노동자 집회에서 야유를 받은 뒤 마하라제를 해임하고 폴리카르프 므디바니를 앉혔으며, 그루지야 체카도 라브렌티 베리야 등으로 교체했다. 오르조니키제가 1921년 말 추진한 세 공화국의 연합은 1922년 3월 12일 자캅카스 사회주의 소비에트 공화국 연방 연맹으로, 12월 13일 하나의 연방 공화국인 자캅카스 사회주의 연방 소비에트 공화국으로 바뀌었다. 그루지야를 독자 공화국으로 연방에 들이려던 므디바니와 마하라제는 「민족 편향」으로 몰렸고, 오르조니키제가 므디바니파 인사를 때린 사건을 계기로 레닌은 1922년 12월 말 스탈린과 오르조니키제에게 대러시아 민족주의의 책임이 있다고 보게 되었다. 이 「그루지야 사건」의 패배 뒤 강화된 탄압은 1924년 8월 그루지야 봉기와 수천 명이 죽은 보복으로 이어졌다. 그리고 1922년 12월 30일 자캅카스 연방은 러시아·우크라이나·벨라루스와 함께 [소련의 결성](/commulingo/events/ussr-formation)에 참여한 네 창설 공화국 가운데 하나가 되었다.',
                    en: 'In March 1920, ahead of the push on Baku, Lenin told Ordzhonikidze that Baku was "extremely, extremely important" but recommended "acting with greater caution" toward Georgia. After the occupation of Georgia in 1921 he recognized that the pro-Bolshevik revolt had lacked the popular backing claimed for it and favoured reconciliation with the Georgian intelligentsia and peasantry, while moderates such as Makharadze urged tolerance toward the Mensheviks, gradual land reform and respect for Georgia\'s sovereignty. But after being booed at a Tbilisi workers\' meeting in July 1921, Stalin removed Makharadze in favour of Polikarp Mdivani and replaced the Georgian Cheka leadership with harder men, Lavrentiy Beria among them. The union of the three republics that Ordzhonikidze set in motion in late 1921 became the Federative Union of Socialist Soviet Republics of Transcaucasia on 12 March 1922 and, on 13 December, a single federal state, the Transcaucasian Socialist Federative Soviet Republic. Mdivani and Makharadze, who wanted Georgia to enter the Union as a republic in its own right, were branded "national deviationists", and after Ordzhonikidze struck a member of Mdivani\'s group Lenin concluded in late December 1922 that Stalin and Ordzhonikidze were guilty of imposing Great Russian nationalism. The intensified repression that followed the defeat of the Georgians in this "Georgian affair" led to the August 1924 uprising and reprisals that cost several thousand lives. And on 30 December 1922 the Transcaucasian federation became one of the four founding republics, with Russia, Ukraine and Belarus, in the [formation of the USSR](/commulingo/events/ussr-formation).',
                    sources: [S.azInv, S.affair, S.tsfsr, S.august],
                },
            ],
        },
    ],
    timeline: [
        ['1920.04.27–28', '제11군의 바쿠 진입', 'The 11th Army enters Baku', '장갑열차가 국경을 넘은 날 밤 아제르바이잔 의회가 권력 이양을 의결했고, 혁명위원회가 소비에트 공화국을 선포했다.', 'As armoured trains crossed the border, the Azerbaijani parliament voted to hand over power and a Revolutionary Committee proclaimed a Soviet republic.', ['azerbaijan', 'soviet'], P(40.41, 49.87, '바쿠', 'Baku')],
        ['1920.05.26–31', '간자 봉기', 'Ganja revolt', '옛 아제르바이잔군 장교들이 일으킨 봉기가 1만 명 이상으로 커졌으나 제11군의 포격과 총공세로 진압되었다.', 'A revolt led by officers of the former Azerbaijani army grew to over ten thousand before the 11th Army crushed it with shelling and a general assault.', 'azerbaijan', P(40.68, 46.36, '간자', 'Ganja')],
        ['1920.09.13–11.18', '터키의 아르메니아 침공', 'Turkish invasion of Armenia', '카라베키르의 동부전선군이 10월 30일 카르스, 11월 초 알렉산드로폴을 점령했고 아르메니아는 11월 18일 휴전에 응했다.', 'Karabekir\'s Eastern Front army took Kars on 30 October and Alexandropol in early November; Armenia accepted a ceasefire on 18 November.', ['turkey', 'armenia'], P(40.60, 43.10, '카르스', 'Kars')],
        ['1920.11.29–12.04', '아르메니아 소비에트화', 'Sovietization of Armenia', '제11군이 이제반 방면으로 들어오고, 12월 2일 정부가 권력을 넘긴 뒤 4일 붉은 군대가 예레반에 입성했다.', 'The 11th Army crossed near Ijevan; the government handed over power on 2 December and the Red Army entered Yerevan on the 4th.', ['armenia', 'soviet'], P(40.18, 44.51, '예레반', 'Yerevan')],
        ['1920.12.03', '알렉산드로폴 조약', 'Treaty of Alexandropol', '하티샨의 대표단이 카르스주와 수르말루를 터키에 넘기는 조약에 서명했으나, 전날 정부가 사임해 무효로 간주된다.', 'Khatisian\'s delegation signed away the Kars oblast and Surmalu to Turkey, but the treaty is regarded as invalid because the government had resigned the day before.', ['armenia', 'turkey'], P(40.79, 43.85, '알렉산드로폴', 'Alexandropol')],
        ['1921.02.13–04.02', '아르메니아 2월 봉기', 'February Uprising in Armenia', '다슈나크가 예레반을 되찾아 42일 동안 다스렸으나 붉은 군대의 공세로 잔게주르로 물러났다.', 'The Dashnaks retook Yerevan and held it for 42 days before a Red Army offensive drove them back to Zangezur.', 'armenia', P(40.18, 44.51, '예레반', 'Yerevan')],
        ['1921.02.16–25', '그루지야 침공과 트빌리시 함락', 'Invasion of Georgia and fall of Tbilisi', '로리 봉기를 구실로 국경을 넘은 제11군이 코조리 고지 전투 끝에 트빌리시에 들어가 그루지야 소비에트 공화국을 선포했다.', 'Crossing the border on the pretext of the Lori uprising, the 11th Army took Tbilisi after the fighting on the Kojori heights and proclaimed a Georgian Soviet republic.', ['georgia', 'soviet'], P(41.72, 44.79, '트빌리시', 'Tbilisi')],
        ['1921.03.16', '모스크바 조약', 'Treaty of Moscow', '소비에트 러시아와 앙카라 정부가 우호 조약을 맺어 카르스주를 터키에, 바투미를 그루지야에 두고 나히체반을 아제르바이잔 보호하의 자치 지역으로 정했다.', 'Soviet Russia and the Ankara government signed a friendship treaty leaving the Kars oblast to Turkey and Batumi to Georgia and making Nakhchivan autonomous under Azerbaijan\'s protection.', ['soviet', 'turkey']],
        ['1921.03.18–19', '바투미 전투와 그루지야 정부 망명', 'Battle of Batumi and the Georgian government\'s exile', '그루지야군이 터키군과 시가전을 벌이는 사이 멘셰비키 정부가 배로 망명했고, 도시는 혁명위원회에 넘어갔다.', 'While Georgian troops fought the Turks in the streets, the Menshevik government left by sea into exile and the city passed to the Revolutionary Committee.', ['georgia', 'turkey'], P(41.64, 41.64, '바투미', 'Batumi')],
        ['1921.04–07', '산악 아르메니아 공화국', 'Republic of Mountainous Armenia', '타테브 대회가 독립을 선포한 은즈데의 공화국은 시우니크를 아르메니아에 남긴다는 약속을 받고 7월 항복했다.', 'Proclaimed at a congress in Tatev, Nzhdeh\'s republic capitulated in July after a promise that Syunik would remain in Armenia.', 'armenia', P(39.38, 46.25, '타테브', 'Tatev')],
        ['1921.10.13', '카르스 조약', 'Treaty of Kars', '터키와 세 소비에트 공화국이 서명해 오늘날까지 이어지는 국경을 확정했다.', 'Signed by Turkey and the three Soviet republics, it fixed borders that remain in place today.', ['turkey', 'armenia', 'azerbaijan', 'georgia'], P(40.60, 43.10, '카르스', 'Kars')],
    ],
    people: [
        ['nariman-narimanov', 'leader', '아제르바이잔 혁명위원회 의장', 'Chairman of the Azerbaijani Revolutionary Committee', '아즈레브콤과 소비에트 아제르바이잔 정부를 이끌며 무분별한 처형과 징발을 제한하려 했다.', 'Headed Azrevkom and the Soviet Azerbaijani government and tried to curb indiscriminate executions and confiscations.', 'soviet-forces'],
        ['ordzhonikidze', 'leader', '캅카스국 의장', 'Chairman of the Caucasian Bureau', '아제르바이잔·아르메니아·그루지야 진공을 지휘하고 로리 봉기를 부추겨 그루지야 침공을 이끌어 냈다.', 'Directed the advances into Azerbaijan, Armenia and Georgia and instigated the Lori rising that opened the invasion of Georgia.', 'soviet-forces'],
        ['stalin', 'leader', '민족인민위원', 'People\'s Commissar of Nationalities', '그루지야의 무력 전복을 거듭 주장했고, 1921년 7월 그루지야 혁명위원회 지도부를 교체했다.', 'Repeatedly pressed for the military overthrow of Georgia and in July 1921 replaced the Georgian Revolutionary Committee leadership.', 'soviet-forces'],
        ['lenin', 'leader', '인민위원회의 의장', 'Chairman of the Council of People\'s Commissars', '그루지야에 대한 신중함을 권하다가 1921년 2월 14일 침공에 동의했고, 이후 화해 정책을 지지했다.', 'Urged caution over Georgia, consented to the invasion on 14 February 1921, then backed a conciliatory policy.', 'soviet-forces'],
        ['trotsky', 'participant', '군사인민위원', 'People\'s Commissar of War', '그루지야에 대한 「때 이른 개입」에 반대했으나 뒤에 소책자로 침공을 옹호했다.', 'Opposed a "premature intervention" in Georgia but later defended the invasion in a pamphlet.', 'soviet-forces'],
        ['kirov', 'participant', '캅카스국 부의장', 'Deputy chairman of the Caucasian Bureau', '오르조니키제와 함께 캅카스국을 이끌었고 1921년 아제르바이잔 공산당 제1서기가 되었다.', 'Co-led the Caucasian Bureau with Ordzhonikidze and became First Secretary of the Azerbaijani Communist Party in 1921.', 'soviet-forces'],
        ['mikoyan', 'participant', '바쿠 진공 참가자', 'Participant in the Baku operation', '1920년 4월 28일 장갑열차를 타고 바쿠에 들어왔다.', 'Entered Baku aboard an armoured train on 28 April 1920.', 'soviet-forces'],
        ['tukhachevsky', 'participant', '캅카스 전선 사령관', 'Caucasian Front commander', '러시아어 문헌에 따르면 바쿠 작전 계획을 함께 세웠다.', 'According to Russian-language accounts, helped draw up the plan of the Baku operation.', 'soviet-forces'],
        ['alexander-myasnikov', 'leader', '아르메니아 인민위원회 의장', 'Chairman of Armenia\'s Council of People\'s Commissars', '2월 봉기 진압 뒤 소비에트 아르메니아 정부의 수반에 임명되었다.', 'Was appointed head of the Soviet Armenian government after the February Uprising was suppressed.', 'soviet-forces'],
        ['filipp-makharadze', 'leader', '그루지야 혁명위원회 의장', 'Chairman of the Georgian Revolutionary Committee', '슐라베리에서 혁명위원회를 이끌고 모스크바에 원조를 청했으나 1921년 7월 온건하다는 이유로 해임되었다.', 'Led the Revolutionary Committee at Shulaveri and appealed to Moscow for help, but was removed in July 1921 as insufficiently firm.', 'soviet-forces'],
        ['polikarp-mdivani', 'participant', '그루지야 혁명위원회 의장(1921)', 'Chairman of the Georgian Revolutionary Committee (1921)', '마하라제 후임이 되었으나 자캅카스 연방 편입에 반대해 「그루지야 사건」의 중심이 되었다.', 'Succeeded Makharadze but opposed merging Georgia into the Transcaucasian federation, becoming central to the Georgian affair.', 'soviet-forces'],
        ['beria', 'executor', '그루지야 체카 간부', 'Georgian Cheka officer', '1921년 그루지야 체카에 기용되었고 1924년 봉기 뒤의 대량 탄압을 주도했다.', 'Was brought into the Georgian Cheka in 1921 and led the mass repression after the 1924 uprising.', 'soviet-forces'],
        ['chicherin', 'participant', '외무인민위원', 'People\'s Commissar for Foreign Affairs', '터키군의 바투미 진주에 항의 각서를 냈다.', 'Protested the Turkish occupation of Batumi in a formal note.', 'soviet-forces'],
        ['kazim-karabekir', 'leader', '터키 동부전선 사령관', 'Commander of the Turkish Eastern Front', '아르메니아를 침공해 카르스와 알렉산드로폴을 점령했고 알렉산드로폴·카르스 조약에 서명했다.', 'Invaded Armenia, took Kars and Alexandropol, and signed the treaties of Alexandropol and Kars.', 'ottoman-turkish'],
        ['mustafa-kemal-ataturk', 'leader', '터키 대국민의회 의장', 'Chairman of the Grand National Assembly of Turkey', '레닌에게 공동 투쟁과 원조를 청하고 카라베키르에게 아르메니아 진격을 명령했다.', 'Sought a common struggle and aid from Lenin and ordered Karabekir to advance into Armenia.', 'ottoman-turkish'],
        ['alexander-khatisian', 'participant', '아르메니아 대표단장', 'Head of the Armenian delegation', '정부가 사임한 다음 날 새벽 알렉산드로폴 조약에 서명했다.', 'Signed the Treaty of Alexandropol in the early hours after his government had resigned.', 'national-governments'],
        ['noe-zhordania', 'target', '그루지야 정부 수반', 'Head of the Georgian government', '1920년 4월 아제르바이잔의 지원 요청을 거절했고 1921년 3월 바투미에서 망명했다.', 'Declined Azerbaijan\'s request for help in April 1920 and went into exile from Batumi in March 1921.', 'national-governments'],
        ['mammad-amin-rasulzade', 'target', '무사바트 지도자', 'Musavat leader', '권력 이양 조건에 반대했으나 다수 의견을 따랐고, 스탈린의 개입으로 처형을 면했다.', 'Disagreed with the terms of surrender but bowed to the majority, and was spared execution through Stalin\'s intervention.', 'national-governments'],
    ],
    notes: [
        '알렉산드로폴 조약 날짜: Treaty of Alexandropol·Turkish invasion of Armenia·Kâzım Karabekir 문서는 1920년 12월 3일(새벽) 서명, Soviet invasion of Armenia 문서는 12월 2일로 적음. 본문과 연표는 12월 3일(정부 사임 다음 날 새벽)로 씀.',
        '터키 공세 개시일: Turkish invasion of Armenia 본문은 9월 13일 새벽 2시 30분, Treaty of Alexandropol 서두는 「9월 12일 시작」. 9월 13일 새벽으로 씀.',
        '카르스 조약 날짜: Treaty of Kars·Soviet invasion of Georgia·Treaty of Moscow (1921)는 10월 13일, Kâzım Karabekir와 Armenian–Azerbaijani war 문서는 10월 23일. 10월 13일로 씀.',
        '알렉산드로폴 점령: Turkish invasion of Armenia는 「카르스 점령 일주일 뒤」, Soviet invasion of Armenia는 「11월 7일까지」. 「일주일 뒤/11월 초」로 씀.',
        '아르메니아인 피해: Turkish invasion of Armenia 문서에 「한 추산 10만 명」과 「약 6만 명 사망」이 함께 있어 6만~10만 범위로 씀.',
        '간자 봉기 총 사망자 수는 원문에 없음. 총살 장교 수는 원문 서두의 중복 나열(장군 12명, 대령·중령 27명, 대위 46명, 준위 146명, 기타 267명 등)을 「장군 12명을 비롯한 수백 명」으로 요약.',
        '바일 감옥 300명 처형은 Soviet invasion of Azerbaijan의 「Reports indicate」 서술이라 「보고에 따르면」으로 씀.',
        '레닌의 1921년 4월 「아제르바이잔·그루지야·아르메니아·다게스탄·산악공화국 공산주의 동지들에게」 서한은 받아 온 원문에서 확인하지 못해 쓰지 않음. 대신 1920년 3월 오르조니키제에게 보낸 전보(Soviet invasion of Azerbaijan; 「같은 날」로만 나와 정확한 날짜는 3월 17일 전후로 추정, 본문은 「1920년 3월」), 1921년 3월 2일 타협 강조(Soviet invasion of Georgia), 화해 정책(Georgian affair)을 근거로 씀.',
        '1924년 8월 봉기: August Uprising 문서는 「수천 명」, Soviet invasion of Georgia는 1924.8.29–9.5 「12,578명 처형」. 본문은 「수천 명」으로만 씀.',
        '카라바흐 1921.7.5 캅카스국 결정은 Armenian–Azerbaijani war 문서에서 「스탈린 의장 아래」로 되어 있으나 이 서술은 논쟁적이어서 본문에서 의장 언급은 뺌.',
        '잔게주르를 1920년 11월 소비에트 아제르바이잔이 「우호의 상징」으로 아르메니아에 넘겼다는 서술(Armenian–Azerbaijani war)은 본문에 넣지 않음.',
        '링크 위험: 「체카」, 「캅카스국」, 「혁명위원회」는 일반어라 다른 항목으로 링크될 수 있음 — 본문에서는 대부분 「아제르바이잔 혁명위원회」「그루지야 혁명위원회」처럼 한정했으나 9절 끝 문단의 「혁명위원회」 단독 사용 몇 곳 확인 필요. 「대국민의회」도 확인 필요.',
        '투하쳅스키의 바쿠 작전 계획 참여는 ru 「Бакинская операция」 서두에만 있음.',
    ].join('\n'),
};
