// 자캅카스의 혁명과 전쟁 — 처음 3개 절 (1917.11–1918.9)
const E = t => 'https://en.wikipedia.org/wiki/' + encodeURI(t);
const RU = t => 'https://ru.wikipedia.org/wiki/' + encodeURI(t);
const S = {
  ozakom: E('Special_Transcaucasian_Committee'),
  comm: RU('Закавказский_комиссариат'),
  seim: RU('Закавказский_сейм'),
  armaz: RU('Армяно-азербайджанская_война_(1918—1920)'),
  tdfr: E('Transcaucasian_Democratic_Federative_Republic'),
  march: E('March_Days'),
  commune: RU('Бакинская_коммуна'),
  bc26: E('26_Baku_Commissars'),
  centro: E('Centrocaspian_Dictatorship'),
  dunster: E('Dunsterforce'),
  bbaku: E('Battle_of_Baku'),
  sept: E('September_Days'),
  brest: E('Treaty_of_Brest-Litovsk'),
  campaign: E('Caucasus_campaign'),
  treb: E('Trebizond_Peace_Conference'),
  batum: E('Treaty_of_Batum'),
  sard: E('Battle_of_Sardarabad'),
  arm1: E('First_Republic_of_Armenia'),
};

module.exports = {
  sections: [
    {
      heading: { ko: '1917년: 페트로그라드와 다른 길 {georgia armenia azerbaijan}', en: '1917: A different road from Petrograd {georgia armenia azerbaijan}' },
      paragraphs: [
        {
          ko: '2월 혁명 뒤 러시아 임시정부는 1917년 3월 캅카스 총독을 대신할 기구로 국가두마 의원 바실리 하를라모프를 의장으로 하는 특별 자캅카스 위원회(오자콤)를 세웠다. 그러나 페트로그라드에서처럼 이곳에도 이중권력이 생겨, 오자콤은 트빌리시 소비에트를 비롯한 소비에트들 위에 권위를 세우지 못했다. 11월 7일 볼셰비키가 페트로그라드에서 권력을 잡았다는 소식이 이튿날 캅카스에 닿자 트빌리시 소비에트는 곧바로 반대를 선언했고, 그루지야 멘셰비키 노이 조르다니아는 볼셰비키의 권력 장악이 불법이므로 캅카스는 그 지시를 따르지 말고 질서가 회복되기를 기다려야 한다고 주장했다. 11월 24일 트빌리시에서 열린 회의에는 각 정당과 지역 소비에트, 오자콤, 캅카스 전선 사령부 대표에 영국·프랑스 무관과 미국 영사까지 참석해 소비에트 러시아 인민위원회의(소브나르콤)의 권력을 인정하지 않기로 했고, 소수였던 볼셰비키는 규탄 선언을 읽고 퇴장했다. 그 결과 11월 28일 오자콤을 대신하는 자캅카스 인민위원부가 세워졌다. 그루지야 멘셰비키가 내무·군사·농업 같은 핵심 부서를 맡고 무사바트·다슈나크·사회혁명당이 나머지를 나눈 연정으로, 의장 겸 외무 담당은 예브게니 게게치코리였다. 인민위원부는 스스로 전러시아 제헌의회가 소집될 때까지만 일하는 과도 기구라고 밝혔다. 군사력은 민족별로 조직된 아르메니아·그루지야·무슬림 민족회의에 기대야 했고, 자기가 만든 법을 집행할 힘도 거의 없었다.',
          en: 'After the February Revolution, the Russian Provisional Government replaced the Viceroy of the Caucasus in March 1917 with the Special Transcaucasian Committee (Ozakom), chaired by the Duma deputy Vasily Kharlamov. As in Petrograd, though, dual power took hold: the Ozakom never managed to impose its authority on the soviets, above all the Tbilisi Soviet. News of the Bolshevik seizure of power on 7 November reached the Caucasus the next day, and the Tbilisi Soviet declared against it at once. The Georgian Menshevik Noe Zhordania argued that the coup was illegal and that the Caucasus should ignore Bolshevik directives and wait for order to return. A meeting in Tbilisi on 24 November, attended by the parties, the regional soviets, the Ozakom, the Caucasus Front command, British and French military attachés and the US consul, refused to recognise the Soviet Council of People\'s Commissars (Sovnarkom); the Bolshevik minority read out a denunciation and walked out. On 28 November the Ozakom gave way to the Transcaucasian Commissariat, a coalition in which Georgian Mensheviks held the key portfolios of interior, war and agriculture while the Musavat, the Dashnaks and the Socialist Revolutionaries shared the rest. Evgeni Gegechkori was its chairman and commissar for external affairs. The Commissariat described itself as a caretaker that would govern only until the All-Russian Constituent Assembly met. For armed force it depended on the ethnically organised Armenian, Georgian and Muslim national councils, and it had almost no means of enforcing the laws it passed.',
          sources: [S.ozakom, S.tdfr, S.comm],
        },
        {
          ko: '12월 18일 캅카스 전선 총사령관 미하일 프르제발스키 장군이 인민위원부를 대신해 오스만 제3군과 에르진잔 휴전을 맺자, 지칠 대로 지친 러시아 병사들은 대거 전선을 떠나 귀향길에 올랐다. 인민위원부는 군대를 가능한 한 동원 해제하고 부대를 「민족화」하기로 결정해, 아르메니아 군단과 그루지야 군단, 간자 일대의 무슬림 군단이 이때 편성되기 시작했다. 반면 1918년 1월 초 트빌리시의 제2차 캅카스 지역 군대 대회에서 다수를 차지한 볼셰비키와 좌파 사회혁명당은 병사들이 무기를 지닌 채 고향으로 돌아가 적위대를 만들어야 한다고 결의했다. 게게치코리는 볼셰비키 편에 선 부대가 들어오지 못하도록 트빌리시를 봉쇄하고 그루지야 부대로 트빌리시 병기고를 장악하게 했으며, 1월 19일 자캅카스 지역 소비에트 중앙 의장 조르다니아 명의의 전보는 각지 소비에트에 귀환 부대의 무기를 회수하라고 지시했다. 무기를 둘러싼 충돌은 철도역마다 벌어졌고, 가장 참혹한 것이 1월 22~25일 샴코르역 일대의 사건이었다. 러시아어 출처에 따르면 아제르바이잔 무장 집단의 공격으로 러시아 병사 약 2,000명이 죽고 수천 명이 다쳤으며, 대포 30여 문과 기관총 약 100정, 소총 1만 2천 정이 탈취되었다. 바쿠 소비에트는 이 사건을 인민위원부를 공격하는 근거로 삼았다. 역사가 V. M. 무하노프는 샴코르 사건이 자캅카스를 무정부 상태로 몰아넣어 아르메니아인과 아제르바이잔인의 충돌이 거의 날마다 벌어지게 했다고 본다.',
          en: 'On 18 December the commander of the Caucasus Front, General Mikhail Przhevalsky, acting for the Commissariat, concluded the Armistice of Erzincan with the Ottoman Third Army, and exhausted Russian soldiers began leaving the front en masse. The Commissariat resolved to demobilise the army as far as possible and to "nationalise" its units, and Armenian and Georgian corps, along with a Muslim corps around Ganja, began to form. Meanwhile the Second Caucasian Regional Army Congress, held in Tbilisi in early January 1918 and dominated by Bolsheviks and Left SRs, resolved that soldiers should go home with their weapons and form Red Guards. Gegechkori closed Tbilisi to Bolshevised units and had Georgian troops seize the Tbilisi arsenal, and on 19 January a telegram issued in the name of Zhordania, as head of the Transcaucasian regional centre of soviets, told local soviets to take weapons from units passing through. Clashes over arms broke out at station after station. The bloodiest was at Shamkhor on 22–25 January: according to Russian-language sources, attacks by Azerbaijani armed bands killed about 2,000 Russian soldiers and wounded several thousand, and more than 30 guns, about 100 machine guns and 12,000 rifles were seized. The Baku Soviet turned the incident against the Commissariat. The historian V. M. Mukhanov argues that Shamkhor tipped Transcaucasia into anarchy, after which clashes between Armenians and Azerbaijanis became almost daily events.',
          sources: [S.comm, S.armaz, S.march, S.campaign],
        },
        {
          ko: '1월 18일 페트로그라드에서 처음이자 마지막으로 열린 전러시아 제헌의회가 볼셰비키에게 해산되자, 인민위원부 지도자들은 러시아와의 끈이 사실상 끊겼다고 판단했다. 그들은 1월 중순 오스만이 브레스트-리토프스크 강화 회담에 참여하라고 초청했을 때 러시아와 따로 움직이기를 꺼려 답하지 않았지만, 이제 자캅카스가 정당한 정부를 갖추고 오스만과 직접 협상할 수 있도록 독자적인 입법 기관을 만들기로 했다. 2월 23일 트빌리시에서 자캅카스 세임이 문을 열었다. 새 선거 없이 제헌의회 선거 결과를 쓰되 당선 기준을 3분의 1로 낮춰 작은 정당도 들어오게 했고, 의장은 니콜라이 치헤이제가 맡았다. 의석은 그루지야 멘셰비키 30~32석, 무사바트와 무소속 무슬림 30석, 다슈나크 27석이 셋으로 나눴고, 볼셰비키는 러시아와 자캅카스의 유일한 정부는 소브나르콤이라며 세임을 거부했다. 그 사이 오스만군은 2월 중순 휴전을 깨고 공세에 나서 에르진잔(2월 13일)과 트라브존(2월 24일)을 되찾았다. 첫 회기부터 세임은 갈라졌다. 다슈나크는 러시아 안의 자치와 서아르메니아의 자결을 주장했고, 아제르바이잔 측은 러시아와 무관하게 오스만과 강화하자고 했으며, 그루지야 측은 대체로 후자 편에 섰다. 독립 선언은 일단 미뤄졌고, 세임은 1914년 국경 회복과 동아나톨리아 민족의 자결을 목표로 오스만과 협상하기로 결의했다.',
          en: 'When the All-Russian Constituent Assembly met for the first and only time in Petrograd on 18 January and was dispersed by the Bolsheviks, the Commissariat\'s leaders concluded that their ties to Russia had effectively been cut. In mid-January they had left unanswered an Ottoman invitation to join the peace talks at Brest-Litovsk, unwilling to act apart from Russia; now they decided to create a legislature of their own, so that Transcaucasia would have a legitimate government able to negotiate with the Ottomans directly. The Transcaucasian Seim opened in Tbilisi on 23 February. Instead of holding new elections it used the Constituent Assembly results, with the threshold lowered to a third so that smaller parties could take seats, and Nikolai Chkheidze became its chairman. Three blocs dominated: the Georgian Mensheviks with 30–32 seats, the Musavat and non-party Muslims with 30, and the Dashnaks with 27. The Bolsheviks boycotted it, insisting that the Sovnarkom was the only legitimate government for Russia, Transcaucasia included. Meanwhile the Ottoman army broke the armistice in mid-February and retook Erzincan (13 February) and Trabzon (24 February). The Seim split from its first session. The Dashnaks wanted autonomy within Russia and self-determination for Western Armenia, the Azerbaijanis wanted peace with the Ottomans regardless of Russia, and the Georgians mostly sided with them. Independence was shelved, and the Seim resolved to negotiate with the Ottomans on the basis of the 1914 border and self-determination for the peoples of eastern Anatolia.',
          sources: [S.tdfr, S.seim, S.commune, S.campaign],
        },
      ],
    },
    {
      heading: { ko: '바쿠 코뮌 {azerbaijan uk turkey}', en: 'The Baku Commune {azerbaijan uk turkey}' },
      paragraphs: [
        {
          ko: '트빌리시가 소브나르콤을 거부하는 동안 석유 도시 바쿠는 반대 길을 걸었다. 1917년 10월 스테판 샤우먄이 이끄는 볼셰비키가 바쿠 소비에트 집행위원회를 장악했고, 11월 중순 소비에트는 스스로를 바쿠의 최고 권력으로 선포했다. 12월에는 소브나르콤이 샤우먄을 캅카스 임시 특별위원으로 임명했다. 그러나 볼셰비키는 소비에트 안에서도 단독 과반이 아니었고, 바쿠 인구에서 가장 큰 집단인 무슬림의 대표성도 약했다. 3월 9일 해산된 캅카스 토착 기병사단의 지휘관 탈리신스키 장군이 체포되면서 무슬림 주민의 반감이 커졌다. 3월 30일 기선 에벨리나호의 무슬림 승무원이 봉기를 준비한다는 근거 없는 보고를 받은 소비에트가 이들을 무장 해제하려 하면서 시가전이 시작되었다. 이것이 4월 2일까지 이어진 3월 사태다. 소비에트는 샤우먄, 프로코피 자파리제, 나리만 나리마노프 등이 참여한 혁명 방위 위원회를 세워 도시에 계엄을 선포했고 무슬림 주거 지역을 포격했다. 처음 중립을 지키던 다슈나크 부대 3,000~4,000명이 소비에트 편에 서면서 싸움은 민족 학살의 성격을 띠었다. 샤우먄 자신도 다슈나크의 참여가 내전에 민족 학살의 성격을 더했지만 피할 수 없었고 의도적으로 그렇게 했다고 썼다. 사망자 수는 출처마다 크게 다르다. 독립 연구자들 사이에서는 샤우먄이 레닌에게 보낸 편지에도 나오는 무슬림 희생자 약 3,000명이 널리 받아들여지지만, 아제르바이잔 측은 1만 2천 명을 주장했고 다슈나크 지도자 카레킨 파스테르마지안은 아제르바이잔인 1만 명 이상과 아르메니아인 약 2,500명을 제시했다.',
          en: 'While Tbilisi rejected the Sovnarkom, the oil city of Baku went the other way. In October 1917 the Bolsheviks under Stepan Shaumyan won control of the Baku Soviet\'s executive committee, and in mid-November the Soviet declared itself the supreme authority in Baku. In December the Sovnarkom named Shaumyan its temporary extraordinary commissar for the Caucasus. Even so, the Bolsheviks lacked a majority of their own in the Soviet, and the city\'s largest group, its Muslims, was poorly represented in it. Muslim resentment grew after the arrest on 9 March of General Talyshinski, commander of the disbanded Caucasian Native Cavalry Division. On 30 March the Soviet, acting on an unfounded report that the Muslim crew of the steamer Evelina was armed and ready to revolt, tried to disarm them, and street fighting broke out. These were the March Days, which lasted until 2 April. The Soviet set up a Committee of Revolutionary Defence, including Shaumyan, Prokofy Dzhaparidze and Nariman Narimanov, declared a state of siege and shelled Muslim neighbourhoods. When the 3,000–4,000-strong Dashnak forces, neutral at first, joined the Soviet side, the fighting took on the character of an ethnic massacre. Shaumyan himself wrote that the Dashnaks\' participation lent the civil war something of that character, that it could not be avoided, and that the Bolsheviks had gone into it deliberately. Estimates of the dead vary widely. Independent historians most often accept about 3,000 Muslim victims, a figure Shaumyan also gave in a private letter to Lenin. Azerbaijani representatives claimed 12,000, while the Dashnak leader Karekin Pastermadjian put the toll at over 10,000 Azerbaijanis and nearly 2,500 Armenians.',
          sources: [S.march, S.commune, S.bbaku],
        },
        {
          ko: '3월 사태 뒤 많은 무슬림 생존자가 간자로 피했고 무사바트는 바쿠 현에서 활동을 멈췄다. 4월 바쿠 소비에트는 볼셰비키와 좌파 사회혁명당만으로 바쿠 인민위원회의를 꾸렸다. 소비에트 역사학이 「바쿠 코뮌」이라 부른 이 정부의 출범일은 영어 출처가 4월 13일, 러시아어 출처가 4월 25일로 적는다. 샤우먄이 이끈 인민위원회의는 은행·선박 회사·어업과 석유 산업을 국유화하고 법원과 학교를 개편했으며, 5월 22일 지하자원 국유화 법령과 8시간 노동제를 내놓았다. 그러나 군대는 70%가 아르메니아인으로 다슈나크의 영향 아래 있었고, 북쪽에서는 나주무딘 고친스키의 부대가 페트롭스크를 장악해 북캅카스에서 들어오던 식량 길이 끊겼다. 5월 28일 독립을 선언한 아제르바이잔 민주공화국은 오스만에 군사 지원을 청했고, 엔베르 파샤의 동생 누리 파샤가 간자에서 캅카스 이슬람 군대를 편성했다. 6월 6일 바쿠의 군사 인민위원 그리고리 코르가노프가 간자 공격을 명령했지만, 바쿠 붉은 군대는 6월 27일~7월 1일 괴이차이 전투에서 패해 물러났다. 영어 출처에 따르면 샤우먄이 모스크바에 요청한 병력과 북캅카스에서 모은 곡물은 이오시프 스탈린의 명령으로 차리친에 묶였다. 다슈나크·우파 사회혁명당·멘셰비키는 페르시아 북부의 영국군 지휘관 라이어널 던스터빌을 불러들이자고 주장했고, 7월 25일 소비에트 다수가 영국군 초청에 찬성하자 볼셰비키 인민위원들은 사임했다. 이튿날 무혈 정변으로 사회혁명당과 멘셰비키가 주도하는 센트로카스피 독재가 들어섰다.',
          en: 'After the March Days many Muslim survivors fled to Ganja, and the Musavat ceased operating in the Baku Governorate. In April the Baku Soviet formed a Baku Council of People\'s Commissars made up only of Bolsheviks and Left SRs. Soviet historiography called this government the "Baku Commune"; English-language sources date its founding to 13 April, Russian ones to 25 April. Led by Shaumyan, it nationalised the banks, shipping companies, fisheries and the oil industry and reorganised the courts and schools, and in May it decreed the nationalisation of mineral resources (22 May) and an eight-hour working day. But its army was 70 percent Armenian and under strong Dashnak influence, and in the north the forces of Najmuddin Gotsinsky had taken Petrovsk, cutting Baku off from grain supplies from the North Caucasus. The Azerbaijan Democratic Republic, proclaimed on 28 May, asked the Ottomans for military help, and Enver Pasha\'s brother Nuri Pasha raised the Caucasus Army of Islam at Ganja. On 6 June Baku\'s commissar for military affairs, Grigory Korganov, ordered an offensive on Ganja, but the Baku Red Army was beaten at Goychay on 27 June – 1 July and fell back. According to English-language sources, troops Shaumyan had requested from Moscow, and grain collected in the North Caucasus, were held at Tsaritsyn on the orders of Joseph Stalin. The Dashnaks, Right SRs and Mensheviks pressed to call in the British under Lionel Dunsterville, then in northern Persia. On 25 July a majority of the Soviet voted to invite them, and the Bolshevik commissars resigned. The next day a bloodless coup installed the Centrocaspian Dictatorship, led by Socialist Revolutionaries and Mensheviks.',
          sources: [S.march, S.commune, S.bc26, S.bbaku, S.centro],
        },
        {
          ko: '이슬람 군대의 선발대가 7월 30일 바쿠 외곽 고지에 이르자 던스터빌은 부대를 급파했지만, 영국군 본대는 8월 16일에야 바쿠에 닿았고 전투에 나선 병력은 1,000명 남짓이었다. 바쿠 방어의 주력은 옛 러시아군 장군 게오르기 도쿠차예프가 지휘하는 약 6,000명의 바쿠 군대였는데 대부분 아르메니아인이었다. 누리 파샤의 군대에는 오스만군 약 1만 4천 명에 아제르바이잔 군단과 북캅카스 의용병이 더해졌다. 8월 26일 본격적인 공세가 시작되었고, 8월 말 비나가디 언덕과 디가가 함락되자 던스터빌은 9월 1일 센트로카스피 지도부에 철수 의사를 내비쳤다. 9월 14일 마지막 공세가 벌어졌고, 그날 밤 던스터포스와 바쿠 군대의 남은 병력은 배를 타고 엔젤리로 떠났다. 9월 15일 오스만-아제르바이잔군이 바쿠에 들어왔고, 아르메니아인 학살인 「9월 사태」가 뒤따랐다. 희생자 추정치는 1만~3만 명이다. 아르메니아 민족회의가 꾸린 조사 위원회는 8,988명을, 아르메니아 제노사이드 박물관은 29,063명을 제시한다. 원정에 동행한 독일 장교들은 누리 파샤에게 직접 항의했다.',
          en: 'When the vanguard of the Army of Islam reached the heights above Baku on 30 July, Dunsterville hurried troops forward, but his main contingent arrived only on 16 August, and the British in the battle numbered roughly 1,000. The backbone of the defence was the Baku Army of about 6,000 men under the former tsarist general Georgy Dokuchaev, most of them Armenians. Nuri Pasha\'s force combined some 14,000 Ottoman soldiers with the Azerbaijani corps and North Caucasian volunteers. The main assault began on 26 August; after Binagadi Hill and Diga fell at the end of the month, Dunsterville told the Centrocaspian leaders on 1 September that he was thinking of withdrawing. The final attack came on 14 September, and that night the remnants of Dunsterforce and the Baku Army sailed for Enzeli. On 15 September the Ottoman-Azerbaijani army entered Baku, and the massacre of Armenians known as the September Days followed. Estimates of the dead range from 10,000 to 30,000. A special commission of the Armenian National Council counted 8,988; the Armenian Genocide Museum gives 29,063. German officers attached to the expedition protested directly to Nuri Pasha.',
          sources: [S.bbaku, S.dunster, S.sept, S.centro],
        },
        {
          ko: '코뮌이 무너진 뒤 샤우먄 등 볼셰비키 지도자들은 아스트라한으로 가려다 카스피 함대에 붙잡혀 바쿠 감옥에 갇혀 있었다. 바쿠가 함락되던 9월 14일 아나스타스 미코얀이 이끈 무리가 그들을 빼냈고, 일행은 투르크멘호를 타고 다시 아스트라한으로 향했다. 그러나 배는 크라스노보드스크로 갔다. 최근 연구는 선원들이 아스트라한에서 체포될까 두려워 그렇게 했다고 보지만, 소련 역사학은 배에 탄 영국 장교 두 사람이 항로를 바꾸게 했다고 서술했다. 크라스노보드스크에서 체포된 이들은 사회혁명당원 표도르 푼티코프가 이끄는 아슈하바드 위원회의 결정에 따라 9월 20일 밤 트랜스카스피아 철도의 페레발역과 아흐차쿠이마역 사이에서 총살되었다. 이들이 「26인 바쿠 코미사르」다. 영국 책임 문제는 지금도 엇갈린다. 영국 연락 장교 레지널드 티그존스는 위원회 회의에 참석했으나 포로를 인질로 넘겨 달라는 상관 윌프리드 맬러슨의 제안을 전하지 않았다. 역사가 리처드 울먼은 위원회가 영국에 기대고 있었으니 티그존스가 마음만 먹었다면 처형을 막을 수 있었는데도 개입하지 않았다고 본다. 1926년 처형된 푼티코프는 책임을 티그존스에게 돌렸지만, 영국은 현지 관리들이 저지른 일이라며 관여를 부인했다. 이 사건은 이후 영국과 소비에트 정부의 관계를 더욱 악화시켰다. 함께 끌려간 미코얀이 어떻게 살아남았는지는 아직 분명하지 않다.',
          en: 'After the Commune fell, Shaumyan and the other Bolshevik leaders tried to reach Astrakhan but were intercepted by the Caspian flotilla and jailed in Baku. On 14 September, as the city fell, a group led by Anastas Mikoyan got them out, and they boarded the steamer Turkmen, again bound for Astrakhan. The ship went to Krasnovodsk instead. Recent historians think the sailors feared arrest in Astrakhan; Soviet historiography said two British officers on board ordered the change of course. Arrested at Krasnovodsk, the prisoners were handed to the Ashkhabad Committee led by the Socialist Revolutionary Fyodor Funtikov, and on the night of 20 September, 26 of them were shot between the stations of Pereval and Akhcha-Kuyma on the Transcaspian Railway. They became known as the 26 Baku Commissars. British responsibility remains disputed. The British liaison officer Reginald Teague-Jones attended the committee meeting but did not pass on his superior Wilfrid Malleson\'s suggestion that the prisoners be handed over as hostages. The historian Richard Ullman argues that because the committee depended on British support, Teague-Jones could have stopped the executions had he wished, but chose not to intervene. Funtikov, executed in 1926, blamed Teague-Jones; Britain denied involvement and said local officials had acted alone. The affair further soured relations between Britain and the Soviet government. How Mikoyan, who was in the group, survived is still unclear.',
          sources: [S.bc26, S.march],
        },
      ],
    },
    {
      heading: { ko: '한 달짜리 연방 {georgia armenia azerbaijan turkey}', en: 'A federation that lasted a month {georgia armenia azerbaijan turkey}' },
      paragraphs: [
        {
          ko: '3월 3일 소비에트 러시아는 브레스트-리토프스크 조약에 서명해 전쟁에서 빠져나왔다. 조약은 1877~78년 러시아-튀르크 전쟁 때 러시아가 얻은 카르스·아르다한·바투미를 오스만에 넘겨주었고, 역사가 리처드 호바니시안에 따르면 아르메니아 민족 부대를 해산할 의무도 비밀 부속서로 러시아에 지웠다. 회담에 끼지 못한 자캅카스는 조약을 인정하지 않고 해당 지역에서 물러나지 않겠다고 여러 나라 정부에 알렸다. 3월 14일 트라브존에서 아카키 치헨켈리가 이끄는 세임 대표단과 오스만 대표 라우프 베이의 강화 회의가 열렸다. 대표단에는 알렉산드르 하티샨도 있었다. 라우프는 첫 회의에서 대표단이 누구를 대표하느냐고 물었고, 오스만은 이들을 국가가 아닌 지역 주민들의 대표로 대했다. 그 사이 오스만군은 3월 12일 에르주룸을 되찾고 3월 말 1914년 국경을 넘었다. 오스만은 자캅카스가 먼저 독립을 선언해야 협상을 이어 가겠다고 했고, 4월 5일 치헨켈리는 브레스트-리토프스크 조약을 협상의 바탕으로 받아들이자고 세임에 촉구했다. 그러나 트빌리시의 분위기는 달랐다. 이라클리 체레텔리는 열띤 연설로 바투미 방어와 조약 거부를 호소했고, 세임은 동료 무슬림과 싸우기를 꺼린 아제르바이잔 의원들을 표결로 누르고 4월 14일 오스만과의 전쟁 상태를 선언했다. 체레텔리와 조르다니아는 표결이 끝나자마자 바투미 방어에 나섰다.',
          en: 'On 3 March Soviet Russia signed the Treaty of Brest-Litovsk and left the war. The treaty handed Kars, Ardahan and Batumi, which Russia had taken in the Russo-Turkish War of 1877–78, to the Ottoman Empire, and according to the historian Richard Hovannisian a secret annex obliged the Bolsheviks to disband Armenian national units. Transcaucasia, which had not been party to the talks, told foreign governments that it would neither honour the treaty nor evacuate those districts. On 14 March a Seim delegation led by Akaki Chkhenkeli, which included Alexander Khatisian, opened peace talks at Trabzon with the Ottoman delegate Rauf Bey. At the first session Rauf asked whom the delegation represented; the Ottomans treated it as speaking for the peoples of the region rather than for a state. Meanwhile the Ottoman army retook Erzurum on 12 March and crossed the 1914 border by the end of the month. The Ottomans would continue only if Transcaucasia first declared independence, and on 5 April Chkhenkeli urged the Seim to accept the Brest-Litovsk terms as the basis for talks. The mood in Tbilisi was different. Irakli Tsereteli made an impassioned speech for defending Batumi and repudiating the treaty, and on 14 April the Seim, outvoting the Azerbaijani deputies who were unwilling to fight fellow Muslims, declared a state of war with the Ottoman Empire. As soon as the vote was over, Tsereteli and Zhordania left to join the defence of Batumi.',
          sources: [S.brest, S.campaign, S.tdfr, S.treb, S.seim],
        },
        {
          ko: '그러나 바투미는 바로 그 4월 14일 거의 저항 없이 오스만군에 넘어갔다. 수비 병력은 영어 출처가 약 3,000명, 러시아어 출처가 약 1만 4천 명과 대포 100문으로 적어 차이가 크다. 오스만군은 카르스도 포위했다. 군사적 열세가 분명해지자 그루지야 민족회의는 독립 선언만이 길이라고 판단했다. 4월 22일 세임은 다슈나크의 망설임과 사회혁명당의 반대 속에서 자캅카스를 「독립된 민주 연방 공화국」으로 선포했다. 게게치코리 정부는 물러났고 치헨켈리가 총리 겸 외무장관을 맡았다. 새 공화국은 브레스트-리토프스크 조건을 받아들이겠다고 오스만 제3군 사령관 베히프 파샤에게 알렸고, 치헨켈리의 휴전 지시에 따라 4월 25일 아르메니아군은 카르스 요새를 내주고 물러났다. 영어 출처에 따르면 오스만은 이때 소총 1만 1천 정과 대포 67문 등을 손에 넣었다. 카르스 포기에 반발한 다슈나크는 한때 내각 참여를 거부했다. 오스만은 4월 28일 연방을 승인했지만 진격은 멈추지 않았다. 러시아어 출처에 따르면 독일과 오스만은 4월 27일 자캅카스를 세력권으로 나누는 비밀 협정을 맺었다.',
          en: 'Batumi, however, fell to the Ottomans with little resistance on that same 14 April. English-language sources put its garrison at about 3,000, while a Russian-language source speaks of some 14,000 soldiers and 100 guns. The Ottomans also laid siege to Kars. With Ottoman military superiority now plain, the Georgian National Council decided that declaring independence was the only way out. On 22 April the Seim, over Dashnak hesitation and Socialist Revolutionary opposition, proclaimed Transcaucasia "an independent democratic federative republic". Gegechkori\'s government stepped down, and Chkhenkeli became prime minister and foreign minister. The new republic informed Vehib Pasha, commander of the Ottoman Third Army, that it accepted the Brest-Litovsk terms, and on Chkhenkeli\'s order to cease fighting the Armenian troops gave up the fortress of Kars on 25 April. According to English-language sources the Ottomans took some 11,000 rifles and 67 guns there. Angered by the loss of Kars, the Dashnaks at first refused to join the cabinet. The Ottoman Empire recognised the federation on 28 April but kept advancing. According to a Russian-language source, Germany and the Ottoman Empire signed a secret agreement on 27 April dividing Transcaucasia into spheres of influence.',
          sources: [S.tdfr, S.campaign, S.seim],
        },
        {
          ko: '5월 11일 바투미에서 다시 열린 회의에서 오스만 대표 할릴 베이는 두 나라가 이미 전쟁을 치렀으니 브레스트 조약은 더는 기준이 아니라며, 카르스·바투미에 더해 아할칼라키·아할치헤·수르말루와 알렉산드로폴·예레반·에치미아진의 상당 부분을 요구하는 조약 초안을 내밀었다. 카르스-줄파 철도를 따라 사실상 아르메니아 전체를 가져가는 조건이었다. 오스만군은 5월 15일 알렉산드로폴을 점령했고 21일 다시 진격했다. 아르메니아군은 5월 21~29일 사르다라바트, 21~24일 바시아파란, 24~28일 카라킬리사에서 맞섰다. 예레반 서쪽 약 40km 사르다라바트에서 다니엘 베크-피루먄이 지휘한 반격은 7,500~10,000명으로 추산되는 오스만군을 밀어내 예레반으로 가는 길을 막았다. 그 사이 그루지야 지도자들은 독일에 보호를 구했다. 5월 26일 체레텔리가 세임에서 연방의 실패를 선언하자 세임은 「전쟁과 평화 문제에서 근본적인 차이가 생겼다」며 자캅카스의 해체를 확인하고 권한을 내려놓았다. 같은 날 조르다니아가 그루지야 독립 선언문을 읽었다. 5월 28일에는 마메드 아민 라술자데가 이끄는 아제르바이잔 민족회의와 트빌리시의 아르메니아 민족회의가 각각 독립을 선언했다. 6월 4일 세 나라는 오스만과 바투미 조약을 맺었다. 아르메니아에는 동아르메니아의 9분의 1도 안 되는 땅만 남았고, 할양된 지역의 전쟁 전 주민 125만 명 가운데 다수가 아르메니아인이었다.',
          en: 'When talks reopened at Batumi on 11 May, the Ottoman delegate Halil Bey declared that Brest-Litovsk no longer applied, since the two sides had since been at war, and tabled a draft treaty demanding, besides Kars and Batumi, the districts of Akhalkalaki, Akhaltsikhe and Surmalu and large parts of Alexandropol, Yerevan and Etchmiadzin. Running along the Kars–Julfa railway, the line would have put practically all of Armenia under Ottoman rule. Ottoman troops took Alexandropol on 15 May and advanced again on 21 May. The Armenians made their stand at Sardarabad (21–29 May), Bash Abaran (21–24 May) and Karakilisa (24–28 May). At Sardarabad, about 40 km west of Yerevan, a counter-attack led by Daniel Bek-Pirumyan threw back an Ottoman force estimated at 7,500–10,000 men and closed the road to Yerevan. The Georgian leaders, meanwhile, had turned to Germany for protection. On 26 May Tsereteli told the Seim that the federation had failed, and the Seim, citing "basic differences" on questions of war and peace, certified the dissolution of Transcaucasia and laid down its powers. The same day Zhordania read out Georgia\'s declaration of independence. On 28 May the Azerbaijani National Council led by Mammad Amin Rasulzade and the Armenian National Council in Tbilisi each declared independence. On 4 June the three states signed the Treaty of Batum with the Ottoman Empire. Armenia was left with less than a ninth of Eastern Armenia, and most of the 1.25 million pre-war inhabitants of the ceded lands had been Armenians.',
          sources: [S.tdfr, S.sard, S.campaign, S.arm1, S.batum],
        },
      ],
    },
  ],

  timeline: [
    ['1917.11.28', '자캅카스 인민위원부 수립', 'Transcaucasian Commissariat formed', '트빌리시에서 그루지야 멘셰비키·무사바트·다슈나크 등이 오자콤을 대신하는 정부를 세우고 소브나르콤을 인정하지 않았다. 의장은 예브게니 게게치코리였다.', 'In Tbilisi, Georgian Mensheviks, the Musavat, the Dashnaks and others replaced the Ozakom with a government of their own that refused to recognise the Sovnarkom. Evgeni Gegechkori was its chairman.', ['georgia', 'armenia', 'azerbaijan'], { kind: 'point', lat: 41.6938, lng: 44.8015, label: { ko: '트빌리시', en: 'Tbilisi' } }],
    ['1917.12.18', '에르진잔 휴전', 'Armistice of Erzincan', '캅카스 전선의 러시아군과 오스만 제3군이 휴전했다. 러시아 병사들이 대거 귀향길에 오르며 전선이 무너졌다.', 'Russian forces on the Caucasus Front and the Ottoman Third Army agreed a ceasefire. Russian soldiers headed home en masse and the front dissolved.', ['russia', 'turkey'], { kind: 'point', lat: 39.7500, lng: 39.4900, label: { ko: '에르진잔', en: 'Erzincan' } }],
    ['1918.01.22–01.25', '샴코르 사건', 'Shamkhor incident', '샴코르역 일대에서 아제르바이잔 무장 집단이 귀환하는 러시아 병사들의 열차를 습격했다. 러시아어 출처에 따르면 약 2,000명이 죽었다.', 'Azerbaijani armed bands attacked trains carrying Russian soldiers home near Shamkhor station. Russian-language sources put the dead at about 2,000.', ['azerbaijan', 'russia'], { kind: 'point', lat: 40.8300, lng: 46.0200, label: { ko: '샴코르', en: 'Shamkhor' } }],
    ['1918.03.30–04.02', '바쿠 3월 사태', 'March Days in Baku', '바쿠 소비에트와 다슈나크 부대가 무사바트 세력과 싸우는 과정에서 무슬림 주민이 대거 학살되었다. 사망자 추정치는 약 3,000명에서 1만 2천 명까지 엇갈린다.', 'Fighting between the Baku Soviet with Dashnak units and the Musavat turned into a massacre of Muslims. Estimates of the dead range from about 3,000 to 12,000.', 'azerbaijan', { kind: 'point', lat: 40.4093, lng: 49.8671, label: { ko: '바쿠', en: 'Baku' } }],
    ['1918.04.22', '자캅카스 민주연방공화국 선포', 'Transcaucasian Democratic Federative Republic proclaimed', '바투미를 잃은 뒤 세임이 오스만의 요구에 따라 독립 연방 공화국을 선포했다. 사흘 뒤 카르스가 오스만에 넘어갔다.', 'After the loss of Batumi, the Seim bowed to Ottoman demands and proclaimed an independent federal republic. Kars was handed to the Ottomans three days later.', ['georgia', 'armenia', 'azerbaijan']],
    ['1918.05.21–05.29', '사르다라바트 전투', 'Battle of Sardarabad', '예레반 서쪽에서 아르메니아군이 오스만군의 진격을 막았다. 바시아파란·카라킬리사에서도 같은 시기에 싸움이 벌어졌다.', 'West of Yerevan, Armenian forces halted the Ottoman advance; fighting went on at the same time at Bash Abaran and Karakilisa.', ['armenia', 'turkey'], { kind: 'point', lat: 40.1000, lng: 44.0200, label: { ko: '사르다라바트', en: 'Sardarabad' } }],
    ['1918.05.26–05.28', '연방 해체와 세 나라의 독립', 'Federation dissolved, three states declare independence', '5월 26일 세임이 해산하고 그루지야가 독립을 선언했으며, 28일 아제르바이잔과 아르메니아가 뒤따랐다. 6월 4일 세 나라는 오스만과 바투미 조약을 맺었다.', 'On 26 May the Seim dissolved and Georgia declared independence; Azerbaijan and Armenia followed on the 28th. On 4 June all three signed the Treaty of Batum with the Ottoman Empire.', ['georgia', 'armenia', 'azerbaijan']],
    ['1918.09.15', '바쿠 함락과 9월 사태', 'Fall of Baku and the September Days', '던스터포스가 철수한 뒤 오스만-아제르바이잔군이 바쿠에 들어왔고 아르메니아인 1만~3만 명이 학살되었다.', 'After Dunsterforce withdrew, the Ottoman-Azerbaijani army entered Baku, and 10,000–30,000 Armenians were massacred.', ['azerbaijan', 'turkey', 'uk']],
    ['1918.09.20', '26인 바쿠 코미사르 처형', 'Execution of the 26 Baku Commissars', '크라스노보드스크에서 체포된 바쿠 코뮌 지도자 26명이 아슈하바드 위원회의 결정으로 트랜스카스피아 철도변에서 총살되었다.', 'Arrested at Krasnovodsk, 26 leaders of the Baku Commune were shot beside the Transcaspian Railway on the orders of the Ashkhabad Committee.', ['azerbaijan', 'uk']],
  ],

  people: [
    ['stepan-shaumyan', 'leader', '바쿠 인민위원회의 의장', 'Chairman of the Baku Council of People\'s Commissars', '바쿠 소비에트를 이끌어 3월 사태 뒤 바쿠 코뮌을 세웠고, 1918년 9월 20일 처형되었다.', 'Led the Baku Soviet, set up the Baku Commune after the March Days and was executed on 20 September 1918.', 'soviet-forces'],
    ['nikolai-chkheidze', 'leader', '자캅카스 세임 의장', 'Chairman of the Transcaucasian Seim', '1918년 2월 소집된 세임의 의장으로 브레스트-리토프스크 조항을 인정하지 않는다고 오스만에 답했다.', 'As chairman of the Seim convened in February 1918, told the Ottomans it would not recognise the Brest-Litovsk terms.', 'national-governments'],
    ['evgeni-gegechkori', 'leader', '자캅카스 인민위원부 의장', 'Chairman of the Transcaucasian Commissariat', '인민위원부를 이끌며 볼셰비키 편에 선 귀환 부대가 트빌리시에 들어오지 못하게 막았고, 1918년 4월 연방 선포와 함께 물러났다.', 'Headed the Commissariat, closed Tbilisi to Bolshevised troops returning from the front and stepped down when the federation was proclaimed in April 1918.', 'national-governments'],
    ['noe-zhordania', 'leader', '그루지야 멘셰비키 지도자', 'Georgian Menshevik leader', '10월 혁명을 불법으로 규정해 자캅카스의 독자 노선을 주장했고, 1918년 5월 26일 그루지야 독립 선언문을 읽었다.', 'Denounced the October seizure of power as illegal, argued for a separate course for Transcaucasia and read Georgia\'s declaration of independence on 26 May 1918.', 'national-governments'],
    ['irakli-tsereteli', 'participant', '그루지야 멘셰비키 세임 의원', 'Georgian Menshevik deputy in the Seim', '바투미 방어와 브레스트 조약 거부를 호소했고, 1918년 5월 26일 세임에서 연방의 실패를 선언했다.', 'Called for the defence of Batumi and repudiation of Brest-Litovsk, and announced the federation\'s failure in the Seim on 26 May 1918.', 'national-governments'],
    ['alexander-khatisian', 'participant', '트라브존·바투미 협상 대표', 'Delegate at the Trabzon and Batumi talks', '트라브존 강화 회의 대표단에 참여했고, 아르메니아 외무장관으로 바투미 조약에 서명했다.', 'Sat on the delegation at the Trabzon peace conference and signed the Treaty of Batum as Armenia\'s foreign minister.', 'national-governments'],
    ['mammad-amin-rasulzade', 'leader', '아제르바이잔 민족회의 의장', 'Chairman of the Azerbaijani National Council', '1918년 5월 28일 아제르바이잔 민주공화국을 선포한 민족회의를 이끌었고 바투미 조약에 서명했다.', 'Led the National Council that proclaimed the Azerbaijan Democratic Republic on 28 May 1918, and signed the Treaty of Batum.', 'national-governments'],
    ['andranik-ozanian', 'participant', '아르메니아 의용군 지휘관', 'Armenian volunteer commander', '서아르메니아 난민 부대를 이끌었고, 1918년 3월 알렉산드로폴에서 러시아 병사들을 무장 해제하려는 시도를 연설로 말렸다.', 'Commanded a force of Western Armenian refugees, and in March 1918 talked Armenian leaders out of disarming Russian soldiers passing through Alexandropol.', 'national-governments'],
    ['enver-pasha', 'leader', '오스만 지도자', 'Ottoman leader', '캅카스 이슬람 군대를 만들어 동생 누리 파샤에게 맡기고 바쿠 공략을 명령했다.', 'Created the Caucasus Army of Islam, put his brother Nuri Pasha in charge of it and ordered it to take Baku.', 'ottoman-turkish'],
    ['kazim-karabekir', 'participant', '오스만 제1캅카스 군단장', 'Commander of the Ottoman I Caucasian Corps', '그의 군단 병력이 1918년 5월 동아르메니아를 침공한 특별 지대의 주축을 이루었다.', 'Units of his corps formed the core of the detachment that invaded Eastern Armenia in May 1918.', 'ottoman-turkish'],
    ['lionel-dunsterville', 'leader', '던스터포스 사령관', 'Commander of Dunsterforce', '센트로카스피 독재의 초청으로 바쿠를 방어하다 1918년 9월 14일 밤 엔젤리로 철수했다.', 'Defended Baku at the Centrocaspian Dictatorship\'s invitation and withdrew to Enzeli on the night of 14 September 1918.', 'british-and-whites'],
    ['nariman-narimanov', 'participant', '바쿠 혁명 방위 위원회 위원', 'Member of the Baku Committee of Revolutionary Defence', '3월 사태 때 소비에트 측 혁명 방위 위원회에 참여했다.', 'Sat on the Soviet\'s Committee of Revolutionary Defence during the March Days.', 'soviet-forces'],
    ['mikoyan', 'participant', '바쿠 볼셰비키', 'Baku Bolshevik', '바쿠 함락 때 갇혀 있던 코미사르들을 빼냈고, 크라스노보드스크에서 함께 붙잡혔으나 처형을 피했다.', 'Freed the imprisoned commissars as Baku fell, was arrested with them at Krasnovodsk, and escaped execution.', 'soviet-forces'],
    ['stalin', 'participant', '소브나르콤 위원', 'Sovnarkom member', '영어 출처에 따르면 바쿠로 갈 병력과 곡물을 차리친에 묶어 두었다.', 'According to English-language sources, held troops and grain bound for Baku at Tsaritsyn.', 'soviet-forces'],
    ['najmuddin-gotsinsky', 'participant', '다게스탄 이맘', 'Dagestani imam', '그의 부대가 페트롭스크를 장악해 바쿠와 북캅카스를 잇는 길을 끊었다.', 'His forces took Petrovsk, cutting Baku off from the North Caucasus.', 'north-caucasus-mountaineers'],
  ],

  notes: [
    '엇갈린 수치·날짜:',
    '- 인민위원부 수립: 트빌리시 회의 11월 24일(구력 11일), 수립 11월 28일(구력 15일). en March_Days는 "11 November 1917" replaced(구력)로 적음.',
    '- 샤우먄의 캅카스 임시 특별위원 임명: ru 자캅카스 인민위원부 문서는 구력 12월 6일(신력 19일), ru 바쿠 코뮌 문서는 구력 12월 16일(신력 29일) 회의, 발표일은 구력 20일. 본문은 「12월」로만 씀.',
    '- 오스만 공세 재개: ru 세임 문서는 구력 1월 30일(신력 2월 12일), en TDFR은 "30 January [O.S. 17 January]", en Caucasus campaign은 2월 2일·5일. 본문은 「2월 중순」, 에르진잔 2월 13일·트라브존 2월 24일(campaign).',
    '- 세임 의석: ru 세임 문서는 전체 125석, 멘셰비키 32·무사바트+무소속 30·다슈나크 27. en TDFR은 멘셰비키 30·무사바트 30·다슈나크 27. en March Days는 아제르바이잔 대표 44명. 본문은 「30~32석」.',
    '- en Special_Transcaucasian_Committee와 Battle_of_Baku는 세임이 1918년 2월 24일 독립을 선포했다고 쓰나, en TDFR·ru 세임 문서는 4월 22일. 4월 22일을 따름.',
    '- 샴코르 사망자 약 2,000명은 ru 문서(인민위원부, 아르메니아-아제르바이잔 전쟁)만의 수치. en 출처에는 수치 없음.',
    '- 3월 사태 사망자: 샤우먄 양측 3,000명 이상, 무슬림 약 3,000명(독립 연구자 다수), NYT 1918년 2,000명, 아제르바이잔 측 12,000명, 파스테르마지안 아제르바이잔인 10,000+·아르메니아인 약 2,500, Barby 무슬림 7,000+볼셰비키·아르메니아인 3,000 등.',
    '- 바쿠 코뮌 기간: en 26_Baku_Commissars 4월 13일~7월 25일(첫 문단은 7월 26일까지), ru 바쿠 코뮌 리드 4월 25일~7월 31일, 같은 문서 본문은 7월 26일 교체·97일, en September Days는 7월 31일 볼셰비키 사임, en March Days는 8월 1일 교체. 본문은 7월 25일 표결·이튿날 정변(Centrocaspian, Battle of Baku의 7월 26일 정변)으로 씀.',
    '- 석유 국유화: en은 석유 산업 국유화를 언급하나 날짜 없음. ru의 5월 22일은 「지하자원(недр) 국유화」 법령. 석유 산업 국유화 법령의 정확한 날짜는 확인 못 함.',
    '- 이슬람 군대 규모: Caucasus campaign 14,000~25,000명, Battle of Baku는 오스만군 약 14,000명이라면서 오스만군이 30%라고도 써서 내부적으로 어긋남. 본문은 「오스만군 약 1만 4천 명에 아제르바이잔 군단·북캅카스 의용병」. September Days는 9월 초 공세 병력 15,000명.',
    '- 9월 사태: 10,000~30,000명, 아르메니아 민족회의 위원회 8,988명, 아르메니아 제노사이드 박물관 29,063명. en March Days는 "nearly 10,000".',
    '- 바투미 수비대: en Caucasus campaign 3,000명(공격 오스만군 10,000~12,000), ru 세임 문서 약 14,000명·대포 100문.',
    '- 카르스: en TDFR은 아르메니아군 3,000명이 버텼다고, en Caucasus campaign은 수비대 약 10,000명이라고 씀. 본문에는 수비 병력 수를 넣지 않음.',
    '- 아르메니아 독립: en Caucasus campaign은 그루지야와 같은 날(5월 26일)로 쓰지만 en TDFR·First Republic of Armenia는 28일(성명은 30일 발표, 28일 소급). 28일을 따름.',
    '- 독일-오스만 비밀 협정(4월 27일)은 ru 세임 문서에만 있음.',
    '확인 못 한 점·서술상 주의:',
    '- 26인 처형 방식: en 26_Baku_Commissars는 총살로 쓰되, 센니코프가 인용한 차이킨의 말로 「한 투르크멘인이 칼로 참수했다」는 주장도 소개함. 본문은 총살로 씀.',
    '- 영국 책임: 소련 측(푼티코프 진술, 소련 역사학의 영국 장교 항로 변경 주장)과 영국의 부인, 울먼의 평가를 출처대로 나눠 씀.',
    '- 스탈린의 차리친 병력·곡물 억류는 en Battle_of_Baku만의 서술이라 「영어 출처에 따르면」으로 씀. 인물 행 직함은 출처에서 확인되지 않은 세부 직책 대신 「소브나르콤 위원」으로만 씀.',
    '- 엔베르 파샤 직함은 출처에서 확인된 「오스만 삼두 지도자(triumvir)」 수준으로만 「오스만 지도자」라 씀.',
    '- 프로코피 자파리제는 카드가 없어 인물 행에서 뺐고 본문에만 이름을 씀.',
    '- 지도 좌표(트빌리시·에르진잔·샴코르·바쿠·사르다라바트)는 출처 본문이 아닌 일반 지명 좌표. 사르다라바트는 기념 단지 부근 근사값.',
    '- 링크 위험: 「러시아 임시정부」, 「전러시아 제헌의회」, 「인민위원회의(소브나르콤)」, 「바쿠 인민위원회의」가 각각 다른 항목에 자동 링크될 수 있음. 「제3군」은 「오스만 제3군」으로만 씀.',
  ].join('\n'),
};
