// Sections 4–5: Democratic Republic of Georgia, First Republic of Armenia (to the eve of Sovietization).
const E = t => 'https://en.wikipedia.org/wiki/' + encodeURI(t.replace(/ /g, '_'));
const RU = t => 'https://ru.wikipedia.org/wiki/' + encodeURI(t.replace(/ /g, '_'));

const S = {
    drg: E('Democratic Republic of Georgia'),
    drgRu: RU('Грузинская демократическая республика'),
    zhordania: E('Noe Zhordania'),
    gsdpRu: RU('Социал-демократическая партия Грузии'),
    jugheli: E('Valiko Jugheli'),
    chkheidze: E('Nikolay Chkheidze'),
    armGeoWar: E('Armeno-Georgian War'),
    ossetia: E('Georgian–Ossetian conflicts of 1918-1920'),
    sochi: E('Sochi conflict'),
    coup: E('1920 Georgian coup attempt'),
    moscow: E('Treaty of Moscow (1920)'),
    tsereteli: E('Irakli Tsereteli'),
    kautskyRu: RU('Каутский, Карл'),
    fra: E('First Republic of Armenia'),
    kajaznuni: E('Hovhannes Kajaznuni'),
    khatisian: E('Alexander Khatisian'),
    andranik: E('Andranik'),
    nzhdeh: E('Garegin Nzhdeh'),
    shusha: E('Shusha massacre'),
    mayUprising: E('May Uprising'),
    sevres: E('Treaty of Sèvres'),
    wilsonian: E('Wilsonian Armenia'),
};

const P = (lat, lng, ko, en) => ({ kind: 'point', lat, lng, label: { ko, en } });

module.exports = {
    sections: [
        {
            heading: { ko: '그루지야 민주공화국: 멘셰비키의 사회민주주의 국가 {georgia}', en: 'The Democratic Republic of Georgia: a Menshevik social democracy {georgia}' },
            paragraphs: [
                {
                    ko: '1918년 5월 26일 자캅카스 연방이 해체되던 날 그루지야 민족회의는 독립을 선언했고, 이틀 뒤 포티 조약으로 독일의 보호를 받아들였다. 러시아어 자료에 따르면 프리드리히 크레스 폰 크레센슈타인이 지휘하는 약 3,000명의 독일 원정군이 크림에서 바다로 건너와 포티항에 상륙했고, 독일의 외교 압력으로 오스만군의 진격이 멈췄다. 첫 정부는 노이 라미슈빌리가 이끌었으나 1918년 여름부터 노이 조르다니아가 정부 수반을 맡았고, 예브게니 게게치코리가 외무장관 겸 부수반이 되었다. 독일이 패전한 뒤에는 영국군이 그 자리를 대신했다. 1919년 2월 14일 그루지야 제헌의회 선거에서 사회민주당(멘셰비키)은 81.5%를 얻어 130석 가운데 109석을 차지했고, 3월 21일 조르다니아는 사회민주당 단독 정부를 꾸렸다. 의장에는 니콜라이 치헤이제가 선출되었지만 그는 파리 강화회의에 가 있어 첫 회의에 나오지 못했다. 독립선언은 민족·신앙·신분·성별과 관계없이 정치적 권리를 보장했고, 여성 참정권 아래 여성과 아홉 개 민족의 대표가 의회에 들어갔다. 제헌의회는 토지개혁, 사법·지방자치 개혁, 배심재판, 압하지야 등 소수민족 자치를 포함한 126개 법률을 채택했고 트빌리시에 첫 대학이 세워졌다. 이 때문에 이 나라는 「최초의 사회민주주의 국가」로 불리기도 한다. 무력의 중심은 1917년 9월 5일 노동자 수비대로 출발한 인민수비대였다. 이 부대는 국방부가 아니라 의회의 직접 통제를 받았고, 멘셰비키 활동가 발리코 주겔리가 줄곧 지휘했다. 반면 경제는 위기였다. 치아투라 망간 광산의 노동자는 1913년 3,500명에서 1919년 250명으로 줄었고, 도시는 식량 부족에 시달렸다.',
                    en: 'On 26 May 1918, the day the Transcaucasian federation dissolved, the National Council of Georgia declared independence, and two days later it placed the country under German protection in the Treaty of Poti. According to Russian-language accounts, a German expeditionary force of about 3,000 men under Friedrich Kress von Kressenstein was shipped from Crimea to Poti, and German diplomatic pressure halted the Ottoman advance. The first government was led by Noe Ramishvili, but from the summer of 1918 Noe Zhordania headed the government, with Evgeni Gegechkori as foreign minister and deputy chairman. After Germany\'s defeat, British troops took its place. In the elections to the Georgian Constituent Assembly on 14 February 1919 the Social Democrats (Mensheviks) won 81.5 percent of the vote and 109 of 130 seats, and on 21 March Zhordania formed a purely Social Democratic cabinet. Nikolay Chkheidze was elected president of the assembly, though he was in Paris for the peace conference and missed its first session. The act of independence guaranteed political rights regardless of nationality, creed, social rank or sex; with women voting, women and representatives of nine ethnic groups sat in parliament. The assembly passed 126 laws, covering land reform, judicial and local-government reform, jury trials and autonomy for minorities such as the Abkhaz, and Georgia\'s first university opened in Tbilisi. For this the republic has been called the "first social democratic state." Its main armed force was the People\'s Guard, founded on 5 September 1917 as the Workers\' Guard. It answered to parliament rather than the war ministry and was commanded throughout by the Menshevik activist Valiko Jugheli. The economy, by contrast, was in crisis: the workforce at the Chiatura manganese mines fell from 3,500 in 1913 to 250 in 1919, and the towns went short of food.',
                    sources: [S.drg, S.drgRu, S.zhordania, S.gsdpRu, S.chkheidze],
                },
                {
                    ko: '신생 공화국은 이웃 및 소수민족과 잇달아 충돌했다. 아르메니아인이 다수인 보르찰로(로리)와 아할칼라키를 두고 1918년 12월 7일 아르메니아와 전쟁이 벌어졌다. 아르메니아군은 트빌리시 48km 앞까지 진격했으나(약 10km라고 쓴 서술도 있다) 막바지 그루지야의 반격과 협상국의 압력 속에 12월 31일 자정 휴전했다. 영국 감독 아래 로리 중립지대가 생겼고, 결과는 양쪽 모두 승리를 주장한 무승부로 평가된다. 전쟁 중 그루지야의 아르메니아인은 대량 체포를 당했다. 러시아어 자료에 따르면 18~45세 아르메니아인 남성 전원이 전쟁포로로 선포되어 쿠타이시 근처 수용소에 갇혔다. 남오세티야에서는 토지 문제와 민족 갈등, 볼셰비키의 선동이 얽혔다. 1918년 3월 반란자들이 츠힌발리를 약탈했고, 1919년 10월에는 로키에서 소비에트 권력이 선포되었다. 1920년 5월 8일에는 블라디카프카스에서 넘어온 볼셰비키 부대의 지원 속에 로키에서 다시 소비에트 공화국이 선포되었고, 6월 8일에는 남오세티야 전역의 소비에트 권력이 선포되었다. 주겔리의 인민수비대는 6월 12일 츠힌발리를 되찾고 가혹한 진압에 나섰다. 여러 마을이 불탔고 약 5,000명이 죽었으며 2만 명의 오세티야인이 소비에트 러시아로 피란했다. 오세티야 측 자료는 사망자를 4,812~5,279명, 곧 지역 오세티야인의 6~8%로 집계하며 이를 「제노사이드」라 부른다. 그루지야 측은 수치가 과장되었고 진압이 반볼셰비키 작전이었다고 반박하며, 유럽연합 보고서도 제노사이드 주장을 근거 없다고 보았다. 압하지야에서는 1918년 4월 수후미를 장악한 볼셰비키 코뮌을 5월 17일 그루지야 수비대가 몰아냈고, 6월 8일 압하지야 인민평의회가 자치 단위로 그루지야에 합류했다. 그루지야군은 1918~1919년 소치 일대를 한동안 장악하기도 했다.',
                    en: 'The young republic clashed repeatedly with its neighbours and its minorities. On 7 December 1918 war broke out with Armenia over the Armenian-majority districts of Borchaly (Lori) and Akhalkalaki. Armenian forces advanced to within 48 km of Tbilisi (one account says about 10 km), but a late Georgian counterattack and Allied pressure brought a ceasefire at midnight on 31 December. The British set up a Lori neutral zone under their supervision, and the outcome is usually judged inconclusive, with each side claiming success. During the war Armenians in Georgia were arrested en masse; according to Russian-language accounts, all Armenian men aged 18 to 45 were declared prisoners of war and interned in a camp near Kutaisi. In South Ossetia, land grievances, ethnic tension and Bolshevik agitation fed one another. Rebels plundered Tskhinvali in March 1918, and Soviet power was proclaimed at Roki in October 1919. On 8 May 1920 a Soviet republic was again proclaimed at Roki, backed by a Bolshevik force from Vladikavkaz, and on 8 June Soviet authority was declared throughout South Ossetia. Jugheli\'s People\'s Guard retook Tskhinvali on 12 June and put down the revolt with great violence. Many villages were burned; about 5,000 people died and 20,000 Ossetians fled to Soviet Russia. Ossetian sources put the dead at 4,812–5,279, or 6–8 percent of the region\'s Ossetians, and call it genocide. Georgia rejects the figures as exaggerated and describes the campaign as an anti-Bolshevik operation; a European Union report also found the genocide allegations unfounded. In Abkhazia the Georgian Guard ousted the Bolshevik commune that had taken Sukhumi in April 1918 on 17 May, and on 8 June the Abkhaz People\'s Council joined Georgia as an autonomous unit. Georgian troops also held the Sochi district for a time in 1918–1919.',
                    sources: [S.armGeoWar, S.drgRu, S.ossetia, S.jugheli, S.sochi, S.drg],
                },
                {
                    ko: '1920년 1월 소비에트 러시아가 남러시아 백군에 맞선 동맹을 제안하자 그루지야는 중립을 내세워 거절했다. 조르다니아는 「동방의 광신자들보다 서방의 제국주의자들을 택하겠다」고 말했다. 4월 제11군이 아제르바이잔을 소비에트화하자 세르고 오르조니키제는 그루지야 진격 허가를 모스크바에 요청했다. 그루지야 정부는 5월 1일 동원령을 내리고 트빌리시 사관학교장 기오르기 크비니타제를 총사령관에 임명했다. 5월 2~3일 밤 볼셰비키 약 25명이 정권 장악의 첫 단계로 이 사관학교를 습격했지만 크비니타제와 생도들에게 격퇴되었고, 주모자인 아르메니아인 볼셰비키 세 명은 군사재판 끝에 처형되었다. 오르조니키제의 독자 판단으로 보이는 붉은 군대의 국경 진입도 격퇴되었다. 폴란드와의 전쟁을 앞둔 레닌은 두 번째 전선을 피하기로 했다. 5월 7일 그리골 우라타제와 레프 카라한이 모스크바 조약에 서명했다. 러시아는 그루지야의 독립을 무조건 인정하고 내정 불간섭을 약속했다. 그루지야는 러시아에 적대적인 군대를 무장해제·억류하기로 했고, 비밀 부속서로 공산당의 자유로운 활동과 출판을 보장했다. 게게치코리는 이를 주권 침해로 보았으나 조르다니아는 국제적 승인을 우선했다. 석방된 볼셰비키는 그루지야 공산당을 세웠으나 내무장관 노이 라미슈빌리가 다시 체포했고, 소비에트 전권대표 세르게이 키로프는 게게치코리와 격한 각서를 주고받았다. 같은 해 8월 이라클리 체레텔리의 주선으로 카를 카우츠키가 그루지야를 찾았다. 러시아어 자료에 따르면 그는 1920년 가을 석 달을 머물렀다. 그는 1921년 『그루지야: 사회민주주의 농민 공화국』을 펴냈고, 레프 트로츠키는 이를 반박하는 글을 썼다. 아홉 달의 불안한 평화는 1921년 2월 붉은 군대의 침공으로 끝났다.',
                    en: 'In January 1920 Soviet Russia offered an alliance against the White armies in South Russia; Georgia declined, citing neutrality, and Zhordania remarked, "I prefer the imperialists of the West to the fanatics of the East." When the 11th Army Sovietized Azerbaijan in April, Sergo Ordzhonikidze asked Moscow for permission to advance into Georgia. The Georgian government ordered mobilization on 1 May and appointed Giorgi Kvinitadze, director of the Tbilisi military school, commander-in-chief. On the night of 2–3 May some 25 Bolsheviks attacked the school as a first step toward seizing power, but Kvinitadze and his cadets drove them off; the three Armenian Bolshevik ringleaders were court-martialled and executed. Red Army units that crossed the border, apparently on Ordzhonikidze\'s own initiative, were also thrown back. Facing war with Poland, Lenin decided against opening a second front. On 7 May Grigol Uratadze and Lev Karakhan signed the Treaty of Moscow. Russia recognized Georgia\'s independence unconditionally and promised not to interfere in its affairs; Georgia undertook to disarm and intern forces hostile to Russia, and a secret supplement guaranteed the Communist Party freedom to organize and publish. Gegechkori considered this an infringement of sovereignty, but Zhordania put international recognition first. The released Bolsheviks founded a Communist Party of Georgia, only to be re-arrested by Interior Minister Noe Ramishvili, and the Soviet envoy Sergei Kirov exchanged sharp notes with Gegechkori. That August, with Irakli Tsereteli\'s help, Karl Kautsky came to Georgia; Russian-language sources say he stayed three months in the autumn of 1920. In 1921 he published Georgia: A Social-Democratic Peasant Republic, which Leon Trotsky answered in a rebuttal. Nine months of uneasy peace ended with the Red Army invasion of February 1921.',
                    sources: [S.drgRu, S.zhordania, S.coup, S.moscow, S.drg, S.tsereteli, S.kautskyRu],
                },
            ],
        },
        {
            heading: { ko: '아르메니아 공화국: 난민의 나라와 다슈나크 정부 {armenia}', en: 'The Republic of Armenia: a land of refugees under the Dashnaks {armenia}' },
            paragraphs: [
                {
                    ko: '트빌리시에 있던 아르메니아 민족회의는 1918년 5월 28일 독립을 선언하고, 다슈나크 지도자 호바네스 카자즈누니와 알렉산드르 하티샨을 예레반으로 보내 정부를 세우게 했다. 카자즈누니가 첫 총리가 되었고 하티샨은 외무장관으로 6월 4일 바투미 조약에 서명했다. 사르다라바트 등지에서 오스만군을 막아 낸 뒤였지만, 조약은 아르메니아를 예레반 주변 약 1만 1,000km²로 묶었다. 엔베르 파샤는 「결코 새 터키 제국의 이익에 영향을 줄 수 없는 작은 아르메니아 국가」에 동의했을 뿐이라고 말했다. 1918년 5~9월 오스만군 침공 동안 아르메니아인 5만~10만 명이 학살된 것으로 추산되며, 철수하는 오스만군은 가축과 농기구, 식량을 대거 가져갔다. 역사가 피루즈 카젬자데는 1918년 여름 아르메니아에 적어도 60만 명의 난민이 몰려 있었다고 썼다. 그해 겨울은 재앙이었다. 구호가 닿기 전 난민 15만~18만 명, 곧 인구의 20%가 굶주림과 추위로 죽었다. 1919년 중반까지 주민 약 20만 명이 숨졌고, 아르메니아 내무부 자료로는 1919년 여름까지 발진티푸스와 기근으로 19만 2,000명이 죽었다. 소련 측 추정은 30만 명에 이른다. 1919년 예레반에서만 1만 9,000명이 발진티푸스에 걸렸다. 미국은 1,100만 달러의 원조를 보냈다.',
                    en: 'The Armenian National Council in Tbilisi declared independence on 28 May 1918 and sent the Dashnak leaders Hovhannes Kajaznuni and Alexander Khatisian to Yerevan to form a government. Kajaznuni became the first prime minister, and Khatisian, as foreign minister, signed the Treaty of Batum on 4 June. Though Ottoman forces had been held at Sardarabad and elsewhere, the treaty confined Armenia to about 11,000 km² around Yerevan. Enver Pasha said he had consented only to "a small Armenian state that could never in any way affect the interests of the new Turkish empire." An estimated 50,000 to 100,000 Armenians were killed during the Ottoman invasion of May–September 1918, and the withdrawing Ottoman army carried off livestock, farm tools and food. The historian Firuz Kazemzadeh wrote that in the summer of 1918 Armenia held at least 600,000 refugees. The winter that followed was catastrophic. Before relief arrived, 150,000 to 180,000 refugees, some 20 percent of the population, died of famine and exposure. About 200,000 inhabitants had died by mid-1919; Armenia\'s interior ministry counted 192,000 deaths from typhus and famine by that summer, and Soviet estimates reach 300,000. In Yerevan alone, 19,000 people caught typhus in 1919. The United States sent $11 million in aid.',
                    sources: [S.fra, S.kajaznuni, S.khatisian],
                },
                {
                    ko: '오스만 제국이 무드로스 휴전으로 물러나자 아르메니아는 영토를 넓혔다. 1918년 12월 로리를 둘러싸고 그루지야와 싸운 것도 이때였다. 카자즈누니 총리는 그루지야군이 「강제로 점령한 아르메니아 땅」에서 철수하지 않으면 필요한 조치를 취하겠다고 통보했고, 아르메니아 측은 이 전쟁을 아르메니아 땅의 해방으로 기억한다. 1919년 4월 10일 오스만이 후원한 서남캅카스 공화국이 아르메니아군과 영국군에 항복하자, 카르스 주가 아르메니아에 편입되어 영토는 4만 4,000km²를 넘었다. 1918년 4월 피란한 10만여 명 가운데 6만 명이 돌아왔다. 5월에는 나히체반 편입이 선포되었고, 5월 28일 독립 1주년에는 하티샨이 서아르메니아와의 통합을 선언하는 「통일 아르메니아 법」을 낭독했다. 하티샨은 1919년 5월부터 총리를 맡았다. 1919년 의회 선거는 다슈나크의 독점을 확인했고 볼셰비키는 선거를 거부했다. 그러나 7월부터 아제르바이잔과 터키 밀사가 부추긴 무슬림 봉기가 카르스와 나히체반에서 일어났다. 미국 구호요원들은 나히체반 일대에서 아르메니아인 1만 명이 죽고 45개 마을이 파괴되었다고 확인했고, 1919년 말 아르메니아는 나히체반 전역을 잃었다.',
                    en: 'As the Ottomans withdrew under the Armistice of Mudros, Armenia expanded. This was also when it fought Georgia over Lori in December 1918: Prime Minister Kajaznuni warned that unless Georgian troops left "that part of Armenia occupied forcibly by Georgia," Armenia would take the necessary measures, and the Armenian side remembers the war as a liberation of Armenian land. On 10 April 1919 the Ottoman-backed Southwest Caucasus Republic surrendered to Armenian and British forces, and the Kars Oblast was annexed, bringing Armenia to more than 44,000 km². Of the more than 100,000 Armenians who had fled in April 1918, 60,000 returned. The annexation of Nakhchivan was announced in May, and on 28 May, the first anniversary of independence, Khatisian read out the Act of United Armenia proclaiming union with Western Armenia. Khatisian served as prime minister from May 1919. The 1919 parliamentary election confirmed the Dashnaks\' monopoly; the Bolsheviks boycotted it. From July, however, Muslim insurgencies encouraged by Azerbaijani and Turkish envoys broke out in Kars and Nakhchivan. American relief workers confirmed that 10,000 Armenians had been killed and 45 villages destroyed around Nakhchivan, and by the end of 1919 Armenia had lost all of Nakhchivan.',
                    sources: [S.fra, S.armGeoWar, S.khatisian],
                },
                {
                    ko: '카라바흐와 잔게주르를 둘러싼 아제르바이잔과의 전쟁에서 아르메니아 쪽 주역은 정부 밖의 무장 지도자들이었다. 바투미 조약을 반역이라 부르며 공화국을 인정하지 않은 안드라니크는 3,000~5,000명의 부대와 약 3만 명의 난민을 이끌고 1918년 9월까지 잔게주르를 장악했다. 역사가 도널드 블록섬은 그가 무슬림 마을을 파괴해 잔게주르를 아르메니아인만의 땅으로 만들려 했다고 보지만, 안트라니크 찰라비안은 그가 잔게주르 아르메니아인 6만 명의 몰살을 막았다고 주장한다. 12월 슈샤 40km 앞까지 다가갔던 그는 영국군 사령관 윌리엄 톰슨의 요청에 진격을 멈췄다. 역사가 크리스토퍼 워커는 카라바흐가 아제르바이잔 관할로 남은 것이 「영국 장교의 말을 믿은」 결과라고 평했다. 안드라니크는 1919년 4월 에치미아진에서 부대를 해산하고 아르메니아를 떠났다. 1919년 8월 22일 카라바흐 아르메니아인은 강화회의 결정 때까지 아제르바이잔의 자치 지역으로 남기로 합의했다. 11월 아제르바이잔의 잔게주르 공세는 격퇴되었고, 1920년 1월 아쿨리스 학살에 분노한 가레긴 은즈데의 유격대는 고리스 남동쪽의 9개 마을과 40개 촌락을 쓸어버렸다. 1920년 3월 아르메니아 공화국 요원들이 조직한 카라바흐 봉기는 실패했고, 슈샤의 아르메니아인 학살로 이어졌다(아래 아제르바이잔 절). 은즈데와 드로의 부대가 4월 카라바흐로 들어갔지만, 아제르바이잔이 소비에트화된 뒤인 5월 24일 철수하고 지역 볼셰비키에게 권력을 넘겼다. 아제르바이잔 외교관들은 1918년 이후 무슬림 마을 300곳이 파괴되었다고 주장했다.',
                    en: 'In the war with Azerbaijan over Karabakh and Zangezur, the leading Armenian actors were armed commanders outside the government. Andranik, who called the Treaty of Batum treason and refused to recognize the republic, led 3,000–5,000 men and some 30,000 refugees into Zangezur and controlled it by September 1918. The historian Donald Bloxham argues that he set out to make Zangezur homogeneously Armenian by destroying Muslim villages; Antranig Chalabian contends that he alone prevented the annihilation of Zangezur\'s 60,000 Armenians. In December, within 40 km of Shusha, he halted at the request of the British commander, General William Thomson. The historian Christopher Walker concluded that Karabakh stayed under Azerbaijani jurisdiction because of "Andranik\'s trust of the word of a British officer." Andranik disbanded his force at Etchmiadzin in April 1919 and left Armenia. On 22 August 1919 the Karabakh Armenians agreed to remain an autonomous part of Azerbaijan pending the peace conference. An Azerbaijani offensive on Zangezur in November was beaten back, and in January 1920 Garegin Nzhdeh\'s partisans, enraged by the massacre of Armenians at Akulis, "wiped out" nine villages and 40 hamlets southeast of Goris. In March 1920 a Karabakh uprising organized by agents of the Armenian republic failed and led to the massacre of Shusha\'s Armenians (see the Azerbaijan section below). Nzhdeh\'s and Dro\'s forces entered Karabakh in April, but after Azerbaijan\'s Sovietization they withdrew on 24 May and handed power to local Bolsheviks. Azerbaijani diplomats, for their part, claimed that 300 Muslim villages had been destroyed since 1918.',
                    sources: [S.fra, S.andranik, S.nzhdeh, S.shusha],
                },
                {
                    ko: '붉은 군대가 바쿠에 들어간 직후 아르메니아 볼셰비키도 움직였다. 1920년 1월 비밀리에 아르메니아 공산당이 세워졌고, 5월 1일 예레반 등지에서 반정부 시위가 벌어졌다. 5월 5일 하티샨 내각이 물러나고 하모 오한잔얀의 다슈나크 단독 내각이 비상사태를 선포했다. 5월 10일 사르기스 무사옐랸이 지휘하는 장갑열차 「바르단 조라바르」가 반란에 가담했고, 혁명위원회는 알렉산드로폴에서 소비에트 아르메니아를 선포하고 카르스와 사르카미시도 장악했다. 서아르메니아 출신 유격대장 세부흐 네르세샨의 부대가 13일 알렉산드로폴에 도착하자 반란자들은 이튿날 도시를 떠났다. 지도자들은 투옥되었고 일부는 이감 도중 살해되었다. 소비에트 정부는 6월 4일 공산주의자 박해가 계속되면 관계가 손상될 것이라고 경고했다. 훗날 소비에트 아르메니아는 이 봉기를 영웅적 투쟁으로 기렸지만, 비판자들은 「아르메니아의 볼셰비즘은 지식인들의 머릿속에만 있었다」고 평했다. 외교 무대에서는 희망과 좌절이 엇갈렸다. 미국 상원은 1920년 6월 1일 아르메니아 위임통치안을 52 대 23으로 부결했다. 그러나 8월 10일 아르메니아 대표가 서명한 세브르 조약은 아르메니아를 「자유로운 독립국」으로 인정하고 에르주룸·트라브존·반·비틀리스 주의 국경을 미국 대통령의 중재에 맡겼다. 우드로 윌슨 정부가 그은 「윌슨 아르메니아」 국경은 흑해 출구까지 포함했다. 같은 날 아르메니아는 소비에트 러시아와 잠정 경계에 합의해 카라바흐·잔게주르·나히체반을 러시아군 점령 아래 분쟁지로 남겼다. 세브르 조약은 끝내 비준되지 않았고, 그해 가을 터키 국민군의 침공이 시작되었다.',
                    en: 'Soon after the Red Army entered Baku, Armenia\'s Bolsheviks moved too. An Armenian Communist Party had been founded in secret in January 1920, and on 1 May there were anti-government demonstrations in Yerevan and other towns. On 5 May Khatisian\'s cabinet resigned, and an all-Dashnak cabinet under Hamo Ohanjanyan declared a state of emergency. On 10 May the armoured train Vardan Zoravar under Sargis Musayelian joined the rebels, whose revolutionary committee proclaimed Soviet Armenia in Alexandropol and also took Kars and Sarıkamış. When the Western Armenian guerrilla commander Sebouh Nersesian reached Alexandropol on the 13th, the rebels abandoned the town the next day. The leaders were imprisoned, and some were killed while being moved between prisons. On 4 June the Soviet government warned that relations would suffer if the persecution of Communists continued. Soviet Armenia later celebrated the revolt as a heroic struggle, while critics remarked that "Bolshevism in Armenia existed only in the heads of intellectuals." Diplomacy brought both hope and disappointment. On 1 June 1920 the US Senate rejected an American mandate for Armenia by 52 votes to 23. But the Treaty of Sèvres, signed by Armenian delegates on 10 August, recognized Armenia as "free and independent" and submitted its frontier in the vilayets of Erzurum, Trebizond, Van and Bitlis to arbitration by the President of the United States. The "Wilsonian Armenia" boundary drawn by Woodrow Wilson\'s administration included an outlet to the Black Sea. The same day, Armenia agreed a provisional line with Soviet Russia that left Karabakh, Zangezur and Nakhchivan as disputed districts under Russian occupation. The Treaty of Sèvres was never ratified, and that autumn the Turkish Nationalist invasion began.',
                    sources: [S.mayUprising, S.fra, S.khatisian, S.sevres, S.wilsonian],
                },
            ],
        },
    ],

    timeline: [
        ['1918.05.28', '포티 조약 — 독일의 보호', 'Treaty of Poti: German protection',
            '독립 이틀 뒤 그루지야는 독일의 보호를 받아들였고, 약 3,000명의 독일군이 포티항에 상륙해 오스만군의 진격을 막았다.',
            'Two days after independence Georgia accepted German protection; some 3,000 German troops landed at Poti and the Ottoman advance was halted.',
            ['georgia', 'germany'], P(42.1462, 41.6719, '포티', 'Poti')],
        ['1918.12.07–12.31', '아르메니아-그루지야 전쟁', 'Armeno-Georgian War',
            '로리와 아할칼라키를 두고 두 공화국이 싸웠다. 아르메니아군이 트빌리시 가까이 진격한 뒤 영국의 중재로 휴전하고 로리 중립지대가 생겼다.',
            'The two republics fought over Lori and Akhalkalaki. After Armenian forces advanced toward Tbilisi, a British-brokered ceasefire created the Lori neutral zone.',
            ['georgia', 'armenia'], P(41.2490, 44.8030, '사다흘로', 'Sadakhlo')],
        ['1919.02.14', '그루지야 제헌의회 선거', 'Georgian Constituent Assembly election',
            '사회민주당(멘셰비키)이 81.5%를 얻어 130석 가운데 109석을 차지했다. 3월 21일 노이 조르다니아가 단독 정부를 꾸렸다.',
            'The Social Democrats (Mensheviks) won 81.5 percent and 109 of 130 seats; on 21 March Noe Zhordania formed a one-party government.',
            'georgia', P(41.6938, 44.8015, '트빌리시', 'Tbilisi')],
        ['1919.04.10', '아르메니아의 카르스 편입', 'Armenia takes over Kars',
            '서남캅카스 공화국이 아르메니아군과 영국군에 항복하고 카르스 주가 아르메니아에 편입되었다. 5월에는 나히체반 편입도 선포되었다.',
            'The Southwest Caucasus Republic surrendered to Armenian and British forces and the Kars Oblast passed to Armenia; the annexation of Nakhchivan followed in May.',
            'armenia', P(40.6013, 43.0975, '카르스', 'Kars')],
        ['1920.05.03–05.07', '트빌리시 쿠데타 시도와 모스크바 조약', 'Tbilisi coup attempt and Treaty of Moscow',
            '볼셰비키의 트빌리시 사관학교 습격이 격퇴되었다. 5월 7일 소비에트 러시아는 그루지야 독립을 인정했고, 그루지야는 비밀 부속서로 공산당을 합법화했다.',
            'A Bolshevik attack on the Tbilisi military school was repulsed. On 7 May Soviet Russia recognized Georgian independence, and a secret supplement legalized the Communist Party in Georgia.',
            ['georgia', 'russia'], P(41.6938, 44.8015, '트빌리시', 'Tbilisi')],
        ['1920.05.10–05.14', '아르메니아 5월 봉기', 'May Uprising in Armenia',
            '볼셰비키가 세운 혁명위원회가 알렉산드로폴에서 소비에트 아르메니아를 선포했으나 정부군이 나흘 만에 진압했다.',
            'A Bolshevik revolutionary committee proclaimed Soviet Armenia in Alexandropol; government troops suppressed the revolt within four days.',
            'armenia', P(40.7894, 43.8475, '알렉산드로폴', 'Alexandropol')],
        ['1920.06.08–06.12', '남오세티야 봉기 진압', 'Suppression of the South Ossetian uprising',
            '혁명위원회가 남오세티야 전역의 소비에트 권력을 선포했으나 인민수비대가 6월 12일 츠힌발리를 되찾았다. 약 5,000명이 죽고 2만 명이 피란했다.',
            'A revolutionary committee declared Soviet power across South Ossetia, but the People\'s Guard retook Tskhinvali on 12 June. About 5,000 died and 20,000 fled.',
            'georgia', P(42.2257, 43.9701, '츠힌발리', 'Tskhinvali')],
        ['1920.08.10', '세브르 조약', 'Treaty of Sèvres',
            '아르메니아는 「자유로운 독립국」으로 인정받고 서아르메니아 국경은 미국 대통령의 중재에 맡겨졌지만, 조약은 비준되지 않았다.',
            'Armenia was recognized as "free and independent" and its western frontier left to US presidential arbitration, but the treaty was never ratified.',
            ['armenia', 'turkey']],
    ],

    people: [
        ['noe-zhordania', 'leader', '그루지야 정부 수반', 'Chairman of the Georgian government',
            '멘셰비키 정부를 이끌며 토지개혁과 소수민족 자치를 추진했고, 국제적 승인을 위해 1920년 모스크바 조약을 받아들였다.',
            'Led the Menshevik government, pursued land reform and minority autonomy, and accepted the 1920 Treaty of Moscow to win recognition.',
            'national-governments'],
        ['evgeni-gegechkori', 'leader', '그루지야 외무장관', 'Georgian foreign minister',
            '모스크바 조약의 억류 조항을 주권 침해로 보았고, 공산당원 재체포를 두고 키로프와 각서를 주고받았다.',
            'Regarded the Treaty of Moscow\'s internment clause as an infringement of sovereignty and traded notes with Kirov over the re-arrest of Communists.',
            'national-governments'],
        ['nikolai-chkheidze', 'participant', '그루지야 제헌의회 의장', 'President of the Georgian Constituent Assembly',
            '제헌의회 의장으로 선출되었고, 파리 강화회의 대표단을 이끌며 그루지야의 승인을 구했다.',
            'Was elected president of the Constituent Assembly and led the delegation seeking recognition at the Paris Peace Conference.',
            'national-governments'],
        ['irakli-tsereteli', 'participant', '그루지야 외교 대표', 'Georgian diplomat',
            '파리 강화회의에서 그루지야의 승인을 위해 활동했고, 1920년 카우츠키의 그루지야 방문을 도왔다.',
            'Lobbied for Georgian recognition at the Paris Peace Conference and helped arrange Karl Kautsky\'s 1920 visit to Georgia.',
            'national-governments'],
        ['alexander-khatisian', 'leader', '아르메니아 총리(1919–1920)', 'Prime Minister of Armenia (1919–1920)',
            '바투미 조약에 서명하고 「통일 아르메니아 법」을 낭독했으며, 5월 봉기 와중에 내각과 함께 사임했다.',
            'Signed the Treaty of Batum, read out the Act of United Armenia, and resigned with his cabinet during the May Uprising.',
            'national-governments'],
        ['andranik-ozanian', 'participant', '잔게주르의 아르메니아 의용 부대 지휘관', 'Armenian irregular commander in Zangezur',
            '공화국을 인정하지 않은 채 잔게주르를 장악했고, 영국의 요청으로 카라바흐 진격을 멈춘 뒤 1919년 부대를 해산했다.',
            'Held Zangezur while refusing to recognize the republic, halted his Karabakh advance at British request, and disbanded his force in 1919.',
            'national-governments'],
        ['ordzhonikidze', 'participant', '캅카스 붉은 군대 정치위원', 'Bolshevik commissar with the Red Army in the Caucasus',
            '아제르바이잔 소비에트화 뒤 그루지야 진격 허가를 요청했고, 1920년 5월 붉은 군대의 국경 진입을 독자적으로 이끈 것으로 보인다.',
            'Sought permission to advance into Georgia after Azerbaijan\'s Sovietization and apparently pushed troops across the border on his own initiative in May 1920.',
            'soviet-forces'],
        ['lenin', 'leader', '소비에트 러시아 인민위원회의 의장', 'Chairman of the Soviet Russian Council of People\'s Commissars',
            '폴란드 전쟁 중 두 번째 전선을 피하려 그루지야 침공을 미루고 모스크바 조약 협상에 동의했다.',
            'Deferred an invasion of Georgia to avoid a second front during the Polish war and agreed to the Treaty of Moscow talks.',
            'soviet-forces'],
        ['lev-karakhan', 'participant', '모스크바 조약 러시아 측 서명자', 'Russian signatory of the Treaty of Moscow',
            '1920년 5월 7일 러시아를 대표해 그루지야 독립을 인정하는 모스크바 조약에 서명했다.',
            'Signed the 7 May 1920 Treaty of Moscow recognizing Georgian independence on Russia\'s behalf.',
            'soviet-forces'],
        ['kirov', 'participant', '그루지야 주재 소비에트 전권대표', 'Soviet plenipotentiary in Georgia',
            '모스크바 조약 뒤 트빌리시에 부임해 그루지야 공산당원 재체포에 항의했다.',
            'Posted to Tbilisi after the Treaty of Moscow, he protested the re-arrest of Georgian Communists.',
            'soviet-forces'],
        ['woodrow-wilson', 'participant', '세브르 조약 국경 중재자', 'Arbitrator of the Sèvres frontier',
            '세브르 조약에 따라 터키-아르메니아 국경 중재를 맡았고, 그의 정부가 「윌슨 아르메니아」 국경을 그었다.',
            'Was entrusted under the Treaty of Sèvres with arbitrating the Turkish–Armenian frontier, which his administration drew as "Wilsonian Armenia".'],
    ],

    notes: [
        '제2인터내셔널 대표단: 카우츠키의 방문만 원문에서 확인(en Irakli Tsereteli: 체레텔리가 1920년 8월 카우츠키 방문을 도움 / ru Каутский: 1920년 가을 석 달 체류). 반데르벨데·맥도널드 등 대표단 방문과 「1920년 9월」 날짜는 받아 온 어느 본문에서도 확인 못 해 쓰지 않았다(en Emile Vandervelde, Ramsay MacDonald 문서에도 언급 없음). 트로츠키의 반박서 제목(Between Red and White)은 en DRG의 외부 링크 목록에만 있어 본문에서는 제목 없이 「반박하는 글」로 썼다.',
        '조르다니아 정부 수반 취임일: en Noe Zhordania 문서 안에서 「1918년 7월 24일」과 「6월 24일부터」가 엇갈려 「1918년 여름부터」로 썼다.',
        '아르메니아-그루지야 전쟁: 개전일 en 12월 7일 / ru 12월 9일. 아르메니아군 최근접 거리 en 리드 「트빌리시 10km」, 같은 문서 본문과 en First Republic of Armenia는 30마일(48km) — 48km를 본문에, 10km를 괄호로 병기. 아르메니아인 남성 18~45세 수용(12월 16일)은 ru 문서만의 서술이라 「러시아어 자료에 따르면」으로 씀.',
        '아르메니아 총리 재임: Kajaznuni 문서는 카자즈누니 재임을 1919년 8월 7일까지(1919년 6월부터 해외 활동), Khatisian 문서는 하티샨 총리 재임을 1919년 5월부터로 써서 겹친다. 본문은 「하티샨은 1919년 5월부터 총리」로만 씀.',
        '바투미 조약 영토: en First Republic of Armenia의 4,000제곱마일(10,000km²)+조정 400제곱마일(1,000km²)을 합쳐 「약 1만 1,000km²」로 씀.',
        '아르메니아 기근·티푸스 사망: 15만~18만(난민, 구호 전), 약 20만(1919년 중반까지 주민), 19만 2,000(내무부, 1919년 여름까지), 30만(소련 추정, 파이프스 인용) — 모두 en First Republic of Armenia.',
        '남오세티야: 사망 약 5,000·피란 2만(en), 오세티야 측 4,812~5,279명(6~8%) — en·ru 일치. 유럽연합 보고서 평가는 en 문서 기준.',
        '슈샤 학살 사망자: en Shusha massacre — 호바니시안 500명(도시 안), 바베로프스키 8,000명, 그 밖에 2만~3만 명 추정까지. 아제르바이잔 절과 겹칠 수 있어 범위만 한 줄로 썼다.',
        '그루지야 동원령: en coup attempt 문서는 5월 1일, ru DRG는 4월 28일 조르다니아의 동원 호소문 게재. 본문은 5월 1일.',
        '윌슨 중재 판정일(1920.11.22)은 en Wilsonian Armenia 외부 링크 제목에만 있어 본문에 날짜를 쓰지 않았다. en Wilsonian Armenia의 「Treaty of Alexandropol on November 2, 1920」은 다른 문서(12월 2~3일)와 어긋나는 오기로 보여 쓰지 않음.',
        '인물 카드가 없는 주요 인물(본문에만 등장): 호바네스 카자즈누니, 가레긴 은즈데, 발리코 주겔리, 기오르기 크비니타제, 노이 라미슈빌리, 그리골 우라타제, 하모 오한잔얀, 세부흐 네르세샨, 사르기스 무사옐랸, 카를 카우츠키, 윌리엄 톰슨, 드로. 카자즈누니·은즈데는 새 카드 후보로 검토할 만하다.',
        '링크 위험: 「민족회의」(그루지야/아르메니아 민족회의로 한정해 씀), 「제헌의회」(러시아 제헌의회와 혼동 방지를 위해 「그루지야 제헌의회」로 첫 언급), 「인민수비대」, 「혁명위원회」(일반명사). 「적위대」는 오링크 우려로 쓰지 않음. 「세르게이 키로프」는 기존 카드명 그대로.',
    ].join('\n'),
};
