// Glossary terms for the transcaucasia-1917-1921 batch (2026-10-04).
// Built with lib.js term(); see BRIEF.md for sources and spelling rules.
const { term } = require('./lib');

const E = t => 'https://en.wikipedia.org/wiki/' + encodeURI(t);
const RU = t => 'https://ru.wikipedia.org/wiki/' + encodeURI(t);
const S = {
    commissars: E('26_Baku_Commissars'),
    bakuCommuneRu: RU('Бакинская_коммуна'),
    tdfr: E('Transcaucasian_Democratic_Federative_Republic'),
    arf: E('Armenian_Revolutionary_Federation'),
    khatisian: E('Alexander_Khatisian'),
    kajaznuni: E('Hovhannes_Kajaznuni'),
    vratsian: E('Simon_Vratsian'),
    musavat: E('Musavat'),
    kars: E('Treaty_of_Kars'),
    mrnc: E('Mountainous_Republic_of_the_Northern_Caucasus'),
    mrncRu: RU('Горская_республика'),
};

// term() writes one period string to both languages and records String(endYear)
// as evidence. For a body that still exists, give each language its own period
// and record the open end year as the party still being active (the term
// service requires evidence for endYear even when it is empty).
function ongoing(spec, periodKo, periodEn) {
    const t = term({ ...spec, period: periodEn, endYear: null });
    t.fields.period = { ko: periodKo, en: periodEn };
    t.fields.evidence = t.fields.evidence.map(e => (e.field === 'endYear' ? { ...e, claim: 'still active; no end year' } : e));
    return t;
}

module.exports = [
    term({
        id: 'baku-commune', ko: '바쿠 코뮌', en: 'Baku Commune', category: 'party-state', period: '1918', startYear: 1918, endYear: 1918,
        definition: ['1918년 4월 25일 바쿠 소비에트가 구성한 바쿠 인민위원회의(바쿠 소브나르콤)를 소비에트 역사학이 부른 이름. 스테판 샤우먄이 이끈 볼셰비키·좌파 사회혁명당 정부로 바쿠와 주변 지역을 다스렸고, 이름은 1871년 파리 코뮌을 본뜬 것이었다. 7월 말 다슈나크·우파 사회혁명당·멘셰비키가 주도한 센트로카스피 독재로 교체되었다.',
            'The name Soviet historiography gave to the Baku Council of People’s Commissars (Baku Sovnarkom), formed by the Baku Soviet on 25 April 1918. A government of Bolsheviks and Left Socialist Revolutionaries led by Stepan Shaumyan, it ruled Baku and the surrounding districts and was named after the Paris Commune of 1871. At the end of July it was replaced by the Centrocaspian Dictatorship, led by the Dashnaks, Right SRs and Mensheviks.'],
        body: ['3월 사건 뒤인 1918년 4월 바쿠 소비에트 308석 가운데 볼셰비키는 58석에 그쳤지만, 샤우먄은 볼셰비키와 좌파 사회혁명당만으로 인민위원회의를 꾸리자는 결의를 찬성 124, 반대 2, 기권 20으로 통과시켰다. 다른 정파는 소비에트 권력을 인정하는 조건으로 개인 자격으로만 참여할 수 있었다. 좌파 사회혁명당 출신 위원은 4명이었고, 나머지는 볼셰비키였다. 정부는 스스로 러시아 소비에트 공화국에서 떨어져 나가는 것이 아니라 그 일부라고 선언했다. 정부는 법원과 학교를 개편하고 은행·해운·어업·석유 산업을 수용했으며, 5월 22일 지하자원 국유화 법령을 내고 5월 25일 8시간 노동제를 도입했다. 영어 출처에 따르면 바쿠 체카가 처형한 사람은 공금을 횡령한 소비에트 위원 두 명뿐이었다.\n\n코뮌의 기반은 약했다. 볼셰비키는 소비에트에서 소수였고, 바쿠 인구에서 가장 큰 집단인 무슬림은 정부에 대표되지 않았다. 군대의 70%는 아르메니아인이어서 다슈나크의 영향력이 컸고, 간자 공격이 실패할 때 아르메니아인 병사들이 무슬림 주민에게 폭력과 약탈을 저질렀다. 괵차이에서 붉은 군대가 캅카스 이슬람군에 패하자, 7월 25일 다슈나크·우파 사회혁명당·멘셰비키가 다수를 이룬 바쿠 소비에트는 엔젤리에 있던 라이어널 던스터빌의 영국군을 불러들이기로 의결했다. 인민위원들은 항의 표시로 사퇴했고, 7월 26일 97일 만에 센트로카스피 독재가 그 자리를 이었다. 러시아어 출처는 아제르바이잔인들이 코뮌을 볼셰비키와 아르메니아인의 결탁으로 보았다고 적는다.',
            'After the March Days, the Bolsheviks held only 58 of the 308 seats in the Baku Soviet in April 1918, yet Shaumyan carried a resolution, by 124 votes to 2 with 20 abstentions, to form a Council of People’s Commissars of Bolsheviks and Left SRs alone. Members of other factions could take part only individually and on condition that they recognised Soviet power. Four commissars were Left SRs and the rest were Bolsheviks. The government declared that it was not seceding from the Russian Soviet Republic but remained part of it. It reorganised the courts and schools, expropriated banks, shipping, fisheries and the oil industry, decreed the nationalisation of the subsoil on 22 May and introduced the eight-hour working day on 25 May. According to the English-language source, the Baku Cheka executed only two people, both members of the Soviet caught embezzling public funds.\n\nThe commune stood on weak ground. The Bolsheviks were a minority in the Soviet, and the Muslims, the largest group in the city’s population, were not represented in the government. Seventy per cent of its troops were Armenians, which gave the Dashnaks great influence, and during the failed attack on Ganja Armenian soldiers committed violence and looting against the Muslim population. After the Red Army was beaten by the Islamic Army of the Caucasus at Goychay, the Baku Soviet, with a majority of Dashnaks, Right SRs and Mensheviks, voted on 25 July to call in Lionel Dunsterville’s British force from Enzeli. The commissars resigned in protest, and on 26 July, after 97 days, the Centrocaspian Dictatorship took their place. The Russian-language source notes that Azerbaijanis saw the commune as a case of Bolshevik–Armenian collusion.'],
        aliases: { ko: ['바쿠 인민위원회의', '바쿠 소브나르콤'], en: ['Baku Council of People’s Commissars', "Baku Council of People's Commissars", 'Baku Sovnarkom'] },
        people: ['stepan-shaumyan', 'lionel-dunsterville'],
        events: ['transcaucasia-1917-1921', 'civil-war'],
        sources: [S.bakuCommuneRu, S.commissars], locator: 'ru: преамбула; Ход заседания Баксовета; Комиссары Бакинской коммуны; Деятельность Баксовнаркома; Народное хозяйство — en: Baku Commune',
    }),
    term({
        id: 'twenty-six-baku-commissars', ko: '26인 바쿠 코미사르', en: '26 Baku Commissars', category: 'party-state', period: '1918', startYear: 1918, endYear: 1918,
        definition: ['1918년 9월 20일 밤 트랜스카스피아 철도의 페레발역과 아흐차쿠이마역 사이에서 총살된 바쿠 코뮌의 볼셰비키·좌파 사회혁명당 활동가 26명. 바쿠 인민위원회의 의장 스테판 샤우먄과 바쿠 소비에트 집행위원회 의장 프로코피 자파리제 등이 포함되었고, 소련은 이들을 혁명의 순교자로 기렸다.',
            'The 26 Bolshevik and Left Socialist Revolutionary members of the Baku Commune who were shot on the night of 20 September 1918 between the stations of Pereval and Akhcha-Kuyma on the Trans-Caspian Railway. They included Stepan Shaumyan, chairman of the Baku Council of People’s Commissars, and Prokopius Dzhaparidze, chairman of the executive committee of the Baku Soviet, and the Soviet Union honoured them as martyrs of the revolution.'],
        body: ['바쿠 코뮌이 무너진 뒤 지도자들은 아스트라한으로 가려다 카스피 함대에 붙잡혀 수감되었다. 1918년 9월 14일 바쿠가 오스만군에 함락될 때 아나스타스 미코얀이 이끈 무리가 이들을 빼냈고, 일행은 투르크멘호를 타고 아스트라한으로 향했지만 배는 크라스노보드스크로 갔다. 최근 연구는 선원들이 아스트라한에서 체포될까 두려워했기 때문으로, 소비에트 역사학은 배에 탄 영국 장교 두 명이 항로를 바꾸게 했기 때문으로 설명한다. 이들은 크라스노보드스크에서 체포되었고, 사회혁명당원 표도르 푼티코프가 이끄는 아슈하바드 위원회의 결정에 따라 투르크멘인 병사들에게 처형되었다. 26명에는 인민위원만이 아니라 경호원·서기·기자도 있었고, 그리스인·라트비아인·유대인·러시아인·그루지야인·아르메니아인·아제르바이잔인이 섞여 있었다. 미코얀이 어떻게 살아남았는지는 지금도 불확실하다.\n\n소련은 처형의 책임을 영국에 돌렸다. 영국 연락 장교 레지널드 티그존스는 위원회 회의에 참석했으나 이들을 인질로 넘겨받자는 영국군 소장 윌프리드 맬리슨의 제안을 전하지 않았고, 역사가 리처드 울먼은 그가 마음만 먹었다면 처형을 막을 수 있었다고 본다. 1926년 바쿠에서 재판을 받고 총살된 푼티코프는 티그존스가 총살을 명령했다고 주장했지만, 영국은 개입을 부인했다. 이 논란은 영국과 소비에트 정부의 관계를 더 나쁘게 했다. 유해는 1920년 바쿠 중심 광장에 다시 묻혔고, 이들은 영화·회화·우표와 기념비로 기려졌다. 2009년 아제르바이잔 당국은 26인 기념비를 철거하고 1월 26일 유해를 호브산 묘지로 옮겨 묻었는데, 아르메니아에서는 이를 아르메니아인을 수도 중심에서 치우려는 조치로 받아들였다.',
            'After the fall of the Baku Commune its leaders tried to reach Astrakhan but were intercepted by the Caspian fleet and imprisoned. On 14 September 1918, as Baku fell to Ottoman forces, a group led by Anastas Mikoyan freed them, and they boarded the ship Turkmen for Astrakhan, but the ship went to Krasnovodsk instead. Recent historians attribute this to the sailors’ fear of arrest in Astrakhan; Soviet historiography said that two British officers on board ordered the change of course. They were arrested in Krasnovodsk and, on the decision of the Ashkhabad Committee led by the Socialist Revolutionary Fyodor Funtikov, executed by Turkmen soldiers. The 26 included not only commissars but also bodyguards, a clerk and a journalist, and were Greeks, Latvians, Jews, Russians, Georgians, Armenians and Azerbaijanis. How Mikoyan survived remains uncertain.\n\nThe Soviet Union blamed the British. The British liaison officer Reginald Teague-Jones attended the committee’s meeting but did not pass on Major-General Wilfrid Malleson’s proposal to hand the prisoners over to the British as hostages, and the historian Richard H. Ullman holds that he could have stopped the executions had he wished. Funtikov, tried and shot in Baku in 1926, claimed that Teague-Jones had ordered the shooting, but Britain denied any involvement. The dispute further soured relations between Britain and the Soviet government. The remains were reburied in a central square in Baku in 1920, and the commissars were commemorated in films, paintings, stamps and monuments. In 2009 the Azerbaijani authorities demolished the 26 Commissars Memorial and on 26 January reburied the remains at Hovsan Cemetery, a move the Armenian public saw as motivated by reluctance to have ethnic Armenians buried in the centre of the capital.'],
        aliases: { ko: ['26인의 바쿠 코미사르', '26인의 바쿠 인민위원', '26인 바쿠 인민위원', '바쿠 26인 코미사르'], en: ['Twenty-Six Baku Commissars', 'Twenty-six Baku Commissars'] },
        people: ['stepan-shaumyan', 'mikoyan'],
        events: ['transcaucasia-1917-1921', 'civil-war'],
        sources: [S.commissars, S.bakuCommuneRu], locator: 'lead; Baku Commune; The executions; Impact; The Commissars; Demolition of the 26 Commissars Memorial and reburial — ru: Комиссары Бакинской коммуны',
    }),
    term({
        id: 'transcaucasian-democratic-federative-republic', ko: '자캅카스 민주연방공화국', en: 'Transcaucasian Democratic Federative Republic', category: 'nationalities', period: '1918', startYear: 1918, endYear: 1918,
        definition: ['1918년 4월 22일 트빌리시의 자캅카스 세임이 선포해 5월 28일까지 존속한 그루지야·아르메니아·아제르바이잔의 연방 국가. 오스만 제국의 침공 앞에서 독립국 자격으로 강화 협상을 하기 위해 세워졌으나, 세 민족 집단의 목표가 엇갈려 한 달여 만에 5월 26일 그루지야가, 28일 아르메니아와 아제르바이잔이 독립을 선언하며 해체되었다.',
            'A federal state of Georgia, Armenia and Azerbaijan proclaimed by the Transcaucasian Seim in Tbilisi on 22 April 1918 that lasted until 28 May. It was created so that the region could negotiate peace with the invading Ottoman Empire as an independent state, but the diverging goals of its three main ethnic groups broke it up after about a month: Georgia declared independence on 26 May, followed by Armenia and Azerbaijan on 28 May.'],
        body: ['10월 혁명 뒤 볼셰비키를 따르지 않기로 한 자캅카스는 1917년 11월 예브게니 게게치코리를 의장으로 하는 자캅카스 인민위원부를 세웠고, 1918년 2월 23일 트빌리시에 입법기관 세임을 열었다. 세임은 새 선거 없이 러시아 제헌의회 선거 결과를 쓰고 의석 문턱을 3분의 1로 낮춰 구성되었으며, 의장은 니콜라이 치헤이제였다. 그루지야 멘셰비키와 무사바트가 각 30석, 다슈나크가 27석을 차지했고 볼셰비키는 참여를 거부했다. 브레스트-리토프스크 조약이 아르다한·바투미·카르스를 오스만에 넘기자 세임은 조약을 인정하지 않았으나, 트라브존 강화 회의에서 오스만 대표는 독립을 선언해야만 협상하겠다고 했다. 세임은 4월 14일 오스만에 전쟁을 선포했지만 같은 날 바투미가 함락되었고, 4월 22일 다비트 오니아시빌리의 발의로 독립 민주연방공화국을 선포하며 브레스트-리토프스크 조약의 조건을 받아들이고 카르스를 내주었다. 오스만은 4월 28일 새 국가를 승인했다.\n\n4월 26일 아카키 치헨켈리가 총리 겸 외무장관을 맡은 13명의 내각이 세임의 승인을 받았다. 그러나 5월 11일 바투미 회담에서 오스만 대표 할릴 베이는 브레스트-리토프스크 조약을 더는 인정하지 않는다며 아할칼라키·아할치헤·수르말루와 알렉산드로폴·예레반·에치미아진의 상당 부분까지 요구했고, 5월 21일 아르메니아로 다시 진격했다. 아르메니아인이 오스만군과 싸우고 아제르바이잔인이 바쿠의 볼셰비키 문제에 매달린 사이 그루지야 지도부는 노이 조르다니아를 통해 독일에 지원을 구했다. 5월 26일 이라클리 체레텔리가 연방은 실패했다고 연설한 뒤 세임은 해산을 의결했고, 그루지야가 독립을 선포했다. 이틀 뒤 아르메니아와 아제르바이잔이 뒤따랐다. 역사가 리처드 호바니시안은 이 국가가 「독립적이지도, 민주적이지도, 연방적이지도, 공화국이지도 않았다」고 평했고, 세 나라는 뒤에 1922–1936년의 자캅카스 사회주의 연방 소비에트 공화국으로 강제로 다시 묶였다.',
            'Refusing to follow the Bolsheviks after the October Revolution, Transcaucasia set up the Transcaucasian Commissariat under Evgeni Gegechkori in November 1917 and opened a legislature, the Seim, in Tbilisi on 23 February 1918. The Seim was formed without a new election from the results of the Russian Constituent Assembly election, with the threshold lowered to one third, and was chaired by Nikolay Chkheidze. The Georgian Mensheviks and the Musavat each held 30 seats and the Dashnaks 27, while the Bolsheviks boycotted it. When the Treaty of Brest-Litovsk ceded Ardahan, Batumi and Kars to the Ottoman Empire, the Seim refused to recognise it, but at the Trabzon peace conference the Ottoman delegates would negotiate only if Transcaucasia declared independence. The Seim declared war on the Ottoman Empire on 14 April, the day Batumi fell, and on 22 April, on a motion by Davit Oniashvili, proclaimed an independent democratic federative republic, accepting the terms of Brest-Litovsk and surrendering Kars. The Ottoman Empire recognised the new state on 28 April.\n\nOn 26 April the Seim confirmed a thirteen-member cabinet with Akaki Chkhenkeli as prime minister and foreign minister. At the Batumi conference on 11 May, however, the Ottoman delegate Halil Bey declared that Brest-Litovsk no longer applied and demanded Akhalkalaki, Akhaltsikhe, Surmalu and large parts of Alexandropol, Yerevan and Etchmiadzin as well, and on 21 May Ottoman forces resumed their advance into Armenia. With the Armenians fighting the Ottomans and the Azerbaijanis preoccupied with the Bolsheviks in Baku, the Georgian leadership sought German help through Noe Zhordania. On 26 May, after Irakli Tsereteli told the Seim that the federation had failed, it voted to dissolve itself and Georgia proclaimed its independence; Armenia and Azerbaijan followed two days later. The historian Richard G. Hovannisian judged that the state “was not independent, democratic, federative, or a republic”, and the three countries were later forcibly reunited as the Transcaucasian Socialist Federative Soviet Republic of 1922–1936.'],
        aliases: { ko: ['자캅카스 민주 연방 공화국'], en: ['TDFR', 'Transcaucasian Democratic Federal Republic'] },
        people: ['evgeni-gegechkori', 'nikolai-chkheidze', 'irakli-tsereteli', 'noe-zhordania'],
        events: ['transcaucasia-1917-1921', 'brest-litovsk', 'world-war-i', 'civil-war'],
        sources: [S.tdfr], locator: 'lead; Transcaucasian Commissariat; Seim; Trabzon peace conference; Establishment; Independence; Break-up; Legacy',
    }),
    ongoing({
        id: 'armenian-revolutionary-federation', ko: '아르메니아 혁명연맹 (다슈나크추튠)', en: 'Armenian Revolutionary Federation (Dashnaktsutyun)', category: 'nationalities', startYear: 1890,
        definition: ['1890년 트빌리시에서 크리스타포르 미카엘리안·스테판 조리안·시몬 자바리안이 세운 아르메니아의 민족주의·사회주의 정당. 다슈나크추튠(「연맹」)이라고도 하며 당원은 줄여서 다슈나크라 부른다. 1918–1920년 아르메니아 제1공화국의 집권당이었고, 소비에트화 뒤 금지되어 디아스포라에서 활동하다 1991년 이후 아르메니아에 돌아왔다.',
            'An Armenian nationalist and socialist party founded in Tbilisi in 1890 by Christapor Mikaelian, Stepan Zorian and Simon Zavarian. It is also called Dashnaktsutyun (“Federation”), and its members are called Dashnaks for short. It was the ruling party of the First Republic of Armenia in 1918–1920; banned after Sovietisation, it worked in the diaspora and returned to Armenia after 1991.'],
        body: ['연맹은 러시아 제국의 아르메니아인 소집단들이 합쳐 생겼고, 무장봉기로 오스만 제국의 아르메니아인 지역에 자치를 얻는 것을 처음 목표로 삼았다. 1903년 차르 정부가 아르메니아 교회 재산을 몰수하자 러시아 당국과의 투쟁으로 돌아섰고, 1905–1906년 아르메니아인·타타르인 충돌에서 무장 활동을 벌였다. 캅카스 총독 보론초프-다시코프는 연맹에 학살의 큰 책임이 있다고 보고했고, 연맹은 무슬림의 공격에 맞서 주민을 지켰다고 주장했다. 1907년 제2인터내셔널에 가입했으며, 1915년 아르메니아인 제노사이드 때 지도자들이 추방·살해되는 가운데 반 저항을 이끌었다.\n\n자캅카스 세임에서 다슈나크는 27석을 차지했고, 1918년 5월 28일 아르메니아 공화국이 선포되자 집권당이 되어 총리·국방장관·내무장관 등 주요 직책을 맡았다. 첫 총리 호바네스 카자즈누니가 당원이었고, 1917년 입당한 알렉산드르 하티샨이 1919년 5월부터 1920년 5월까지 총리를 지냈다. 바쿠에서는 다슈나크가 1918년 7월 영국군을 불러들이자는 쪽에 섰다. 1919년 당은 독립되고 통일된 아르메니아를 강령에 넣었으나, 1920년 가을 터키-아르메니아 전쟁에서 패해 12월 2일 알렉산드로폴 조약을 맺었고 북쪽에서 들어온 붉은 군대에 권력을 넘겼다. 당은 금지되고 지도자들은 망명했으며, 1921년 2월 봉기 때 시몬 브라치안이 조국구원위원회를 40일 동안 이끌었다. 연맹은 지금도 카르스 조약을 국제법 위반이라며 거부한다.',
            'The federation arose from the merger of small Armenian groups in the Russian Empire, and its original aim was to win autonomy for the Armenian-populated areas of the Ottoman Empire through armed rebellion. When the tsarist government moved to confiscate Armenian Church property in 1903 it turned to struggle against the Russian authorities, and it engaged in armed activity during the Armenian–Tatar clashes of 1905–1906. The Caucasus viceroy Vorontsov-Dashkov reported that the federation bore a major share of responsibility for the massacres, while the federation argued that it had defended the population against Muslim attacks. It joined the Second International in 1907, and during the Armenian genocide of 1915, as its leaders were deported and killed, it led the Van resistance.\n\nThe Dashnaks held 27 seats in the Transcaucasian Seim, and when the Republic of Armenia was proclaimed on 28 May 1918 they became the ruling party, holding key posts including prime minister, defence minister and interior minister. The first prime minister, Hovhannes Kajaznuni, was a member, and Alexander Khatisian, who had joined in 1917, was prime minister from May 1919 to May 1920. In Baku the Dashnaks backed calling in the British in July 1918. In 1919 the party adopted an independent and united Armenia as part of its programme, but after defeat in the Turkish–Armenian War in autumn 1920 it signed the Treaty of Alexandropol on 2 December and ceded power to the Red Army invading from the north. The party was banned and its leaders exiled; during the February Uprising of 1921 Simon Vratsian headed the Committee for the Salvation of the Fatherland for 40 days. The federation still rejects the Treaty of Kars as a violation of international law.'],
        aliases: { ko: ['아르메니아 혁명연맹', '다슈나크추튠', '다슈나크당', '다슈나크'], en: ['Armenian Revolutionary Federation', 'Dashnaktsutyun', 'Dashnaktsutiun', 'Dashnak party', 'Dashnak'] },
        people: ['alexander-khatisian'],
        events: ['transcaucasia-1917-1921', 'civil-war', 'world-war-i'],
        sources: [S.arf, S.tdfr, S.khatisian, S.kajaznuni, S.vratsian, S.commissars, S.kars], locator: 'lead; History; Russian Empire; World War I and the Armenian genocide; First Republic of Armenia (1918–1920); Ideology and goals — TDFR: Seim; Khatisian: Biography; Kajaznuni: lead, Early life; Vratsian: lead; 26 Baku Commissars: Baku Commune; Treaty of Kars: Position of the Armenian Revolutionary Federation',
    }, '1890–현재', '1890–present'),
    ongoing({
        id: 'musavat', ko: '무사바트', en: 'Musavat', category: 'nationalities', startYear: 1911,
        definition: ['1911년 바쿠에서 마메드 아민 라술자데 등이 비밀 조직으로 세운 아제르바이잔의 정당. 이름은 아랍어로 「평등」이라는 뜻이다. 1918–1920년 아제르바이잔 민주공화국의 주도 정당이었고, 1920년 볼셰비키의 침공 뒤 다시 지하와 망명지에서 활동했다. 1989년 아제르바이잔에서 재건 운동이 일어나 1992년 정식으로 다시 세워졌다.',
            'An Azerbaijani political party founded in Baku in 1911 as a secret organisation by Mammad Amin Rasulzade and others; its name means “equality” in Arabic. It was the leading party of the Azerbaijan Democratic Republic in 1918–1920, returned to underground and exile activity after the Bolshevik invasion of 1920, and was revived in Azerbaijan from 1989, being formally re-established in 1992.'],
        body: ['처음 이름은 무슬림 민주 무사바트당이었고, 초기 당원 가운데는 뒤에 아제르바이잔 SSR의 공산당 지도자가 되는 나리만 나리마노프도 있었다. 범이슬람주의와 범튀르크주의에 기울었으면서도 1차 세계대전 때는 차르 정부를 지지했다. 2월 혁명 뒤 합법 정당이 되어 1917년 6월 17일 튀르크 연방주의자당과 합쳤고, 10월 첫 대회에서 민족·영토 자치에 바탕을 둔 연방 민주 러시아, 8시간 노동제, 농민에 대한 토지 분배를 담은 76개 조 강령을 채택했다. 멘셰비키·사회혁명당·볼셰비키는 무사바트를 「베크와 칸」의 당이라 불렀지만, 소련 역사가 A. L. 포포프는 혁명 초기의 무사바트가 민주주의와 사회주의의 입장에 서 있었다며 반동 정당으로 단정할 수 없다고 썼다.\n\n자캅카스 세임에서 무사바트는 30석을 얻어 여당의 하나가 되었고, 이 무렵 오스만 보호 아래 무슬림 통일 국가를 지향했다. 1918년 5월 28일 아제르바이잔 민주공화국이 독립하자 의회 다수당이 되었고, 라술자데가 12월 7일까지 첫 국가수반을 지냈다. 「아제르바이잔」이라는 국명이 이때 채택되었고 1919년 여성에게 투표권이 주어졌다. 1920년 4월 붉은 군대의 침공으로 공화국이 무너진 뒤 당은 비밀 위원회를 꾸려 간자·카라바흐·자카탈라·랭캐런 봉기를 준비했으나, 소비에트 당국은 1923년까지 당원을 적어도 2,000명 체포했다. 남은 지도자들은 망명했고, 라술자데는 1923년 무사바트 해외국을 세웠다.',
            'Its first name was the Muslim Democratic Musavat Party, and its early members included Nariman Narimanov, later the Communist leader of the Azerbaijan SSR. Although it leaned towards pan-Islamism and pan-Turkism, it supported the tsarist regime during the First World War. It became a legal party after the February Revolution, merged with the Party of Turkic Federalists on 17 June 1917, and at its first congress in October adopted a 76-article programme calling for a federative democratic Russia based on national and territorial autonomy, the eight-hour working day and the distribution of land to the peasants. Mensheviks, SRs and Bolsheviks branded it a party of “beks and khans”, but the Soviet historian A. L. Popov wrote that in the early revolutionary period the Musavat stood for democracy and even socialism and could not be classified a priori as reactionary.\n\nThe Musavat won 30 seats in the Transcaucasian Seim and became one of its ruling parties, by then aiming at a united Muslim state under Ottoman protection. When the Azerbaijan Democratic Republic became independent on 28 May 1918 it held the majority in its parliament, and Rasulzade was the first head of state until 7 December. The name “Azerbaijan” was adopted under its leadership, and women received the vote in 1919. After the republic fell to the Red Army invasion in April 1920, the party formed a secret committee and prepared rebellions in Ganja, Karabakh, Zaqatala and Lankaran, but the Soviet authorities arrested at least 2,000 of its members by 1923. The remaining leaders went into exile, where Rasulzade founded the party’s Foreign Bureau in 1923.'],
        aliases: { ko: ['무사바트당', '뮈사바트', '무슬림 민주 무사바트당'], en: ['Müsavat', 'Musavat Party', 'Müsavat Party', 'Muslim Democratic Musavat Party', 'Musavat Party of Turkic Federalists'] },
        people: ['mammad-amin-rasulzade', 'nariman-narimanov'],
        events: ['transcaucasia-1917-1921', 'civil-war'],
        sources: [S.musavat], locator: 'lead; Early Musavat (1911–1923); Early Musavat under Rasulzade leadership; Musavat in ADR Government; Musavat-in-exile; New Musavat (since 1989)',
    }, '1911–현재', '1911–present'),
    term({
        id: 'treaty-of-kars', ko: '카르스 조약', en: 'Treaty of Kars', category: 'international', period: '1921', startYear: 1921, endYear: 1921,
        definition: ['1921년 10월 13일 카르스에서 터키 대국민의회 정부와 소비에트 아르메니아·아제르바이잔·그루지야가 러시아 SFSR의 참여 아래 맺은 국경 조약. 1921년 3월 모스크바 조약을 재확인해 카르스·아르다한을 터키에, 바투미를 소비에트 그루지야에 두고 나히체반을 아제르바이잔 보호 아래 자치 지역으로 정했다.',
            'A border treaty signed in Kars on 13 October 1921 by the Grand National Assembly of Turkey and the Soviet republics of Armenia, Azerbaijan and Georgia, with the participation of the Russian SFSR. Reaffirming the Treaty of Moscow of March 1921, it left Kars and Ardahan to Turkey and Batumi to Soviet Georgia and made Nakhchivan an autonomous territory under Azerbaijan’s protection.'],
        body: ['터키 쪽에서는 카즘 카라베키르가, 소비에트 러시아 쪽에서는 대사 야코프 가네츠키가 서명했고, 아르메니아의 아스카나즈 므라뱐, 아제르바이잔의 베흐부드 샤흐타흐틴스키, 그루지야의 샬바 엘리아바도 서명자였다. 옛 바투미주는 나뉘어 남쪽 아르트빈 일대가 터키로, 바투미 항을 포함한 북쪽이 아자르 자치 소비에트 사회주의 공화국으로서 소비에트 그루지야에 남았다. 조약은 무슬림 주민이 많은 이 지역의 자치와 바투미 항을 통한 터키 물자의 무관세 통과를 보장했다. 아르메니아와 터키의 국경은 아후랸강(아르파차이강)과 아라스강으로 정해져, 터키는 카르스·아르다한·올투와 아니 유적, 아라라트산을 포함한 수르말루와 쿨프 소금광산을 얻었다. 볼셰비키는 아니와 쿨프를 남기려 했지만 터키는 거절했고, 대신 터키군은 알렉산드로폴을 포함한 오늘날 시라크주 서부에서 물러났다. 제5조는 나히체반을 아제르바이잔 보호 아래 자치 지역으로 정했고, 1924년 나히체반 자치 소비에트 사회주의 공화국이 되었다.\n\n2차 세계대전 뒤인 1945년 6월 7일 뱌체슬라프 몰로토프는 터키 대사에게 카르스·아르다한·아르트빈을 소련에 돌려 달라고 요구했다. 니키타 흐루쇼프에 따르면 라브렌티 베리야가 이오시프 스탈린을 부추긴 것이었다. 미국과 영국은 이 요구에 반대했고, 소련은 1953년 스탈린이 죽은 뒤 영토 요구를 철회하고 1991년 해체 때까지 조약을 지켰다. 소련 해체 뒤 러시아·그루지야·아제르바이잔은 조약을 받아들였고, 아르메니아는 2006년 조약을 아르메니아 SSR의 법적 승계국으로서 인정하면서도 터키가 봉쇄로 교통 자유를 정한 제17조를 어기고 있다고 지적했다. 아르메니아 혁명연맹은 1921년의 자캅카스 공화국들이 모스크바의 통제 아래 있었다며 조약을 국제법 위반으로 거부한다.',
            'Kâzım Karabekir signed for Turkey and Ambassador Yakov Ganetsky for Soviet Russia; the signatories also included Askanaz Mravyan for Armenia, Behboud Shahtahtinsky for Azerbaijan and Shalva Eliava for Georgia. The former Batumi oblast was divided: the southern part around Artvin went to Turkey, while the northern part, including the port of Batumi, stayed with Soviet Georgia as the Adjar Autonomous Soviet Socialist Republic. The treaty guaranteed the autonomy of this largely Muslim region and the duty-free transit of Turkish goods through the port of Batumi. The Armenian–Turkish border was drawn along the Akhuryan (Arpachay) and Aras rivers, giving Turkey Kars, Ardahan, Oltu and the ruins of Ani, as well as Surmalu with Mount Ararat and the Kulp salt mines. The Bolsheviks tried to keep Ani and Kulp, but Turkey refused, while Turkish troops withdrew from the western part of present-day Shirak Province, including Alexandropol. Article V made Nakhchivan an autonomous territory under Azerbaijan’s protection; it became the Nakhichevan ASSR in 1924.\n\nAfter the Second World War, on 7 June 1945, Vyacheslav Molotov told the Turkish ambassador that Kars, Ardahan and Artvin should be returned to the Soviet Union; according to Nikita Khrushchev, Lavrentiy Beria had goaded Joseph Stalin into the claim. The United States and Britain opposed it, and after Stalin’s death in 1953 the Soviet Union renounced its territorial claims and honoured the treaty until its dissolution in 1991. Afterwards Russia, Georgia and Azerbaijan accepted the treaty; in 2006 Armenia said it accepted it as the legal successor of the Armenian SSR but that Turkey, through its blockade, was violating Article XVII on free transit. The Armenian Revolutionary Federation rejects the treaty as a violation of international law, arguing that the Transcaucasian republics of 1921 were under Moscow’s control.'],
        aliases: { ko: ['1921년 카르스 조약'], en: ['Kars Treaty', '1921 Treaty of Kars'] },
        people: ['kazim-karabekir', 'yakov-ganetsky', 'molotov', 'beria', 'stalin'],
        events: ['transcaucasia-1917-1921', 'world-war-i-aftermath-1918-1923', 'ussr-formation'],
        sources: [S.kars], locator: 'lead; Signatories; Terms; Attempted annulment by the Soviet Union; History since 1991',
    }),
    term({
        id: 'mountainous-republic-of-the-northern-caucasus', ko: '북캅카스 산악공화국', en: 'Mountainous Republic of the Northern Caucasus', category: 'nationalities', period: '1917–1920', startYear: 1917, endYear: 1920,
        definition: ['1917년 5월 블라디카프카스에서 결성된 북캅카스·다게스탄 산악민연합을 바탕으로 1918년 5월 11일 독립을 선포한 북캅카스의 국가. 옛 테레크주와 다게스탄주의 체첸인·인구시인·오세트인·카바르다인·다게스탄 민족 등을 아우르려 했으나, 1919년 5월 데니킨의 의용군에 밀려 정부가 해산했다. 러시아어 출처는 최종 소멸을 1920년 3~5월로 본다.',
            'A North Caucasian state that grew out of the Union of the United Mountaineers of the North Caucasus and Dagestan, founded in Vladikavkaz in May 1917, and declared independence on 11 May 1918. It sought to unite the Chechens, Ingush, Ossetians, Kabardians, Dagestani peoples and others of the former Terek and Dagestan oblasts, but its government dissolved in May 1919 under pressure from Denikin’s Volunteer Army. Russian-language sources date its final end to March–May 1920.'],
        body: ['1917년 5월 대회는 체첸 출신 석유업자 타파 체르모예프를 중앙위원회 의장으로, 아바르인 학자 나주무딘 고친스키를 북캅카스의 무프티로 뽑았고, 연방 민주 러시아 안의 자치를 목표로 내걸었다. 10월 혁명 뒤 연합은 자치를 선언하고 1917년 12월 테레크 카자크와 공동 정부를 세웠지만, 땅을 둘러싼 산악민과 카자크의 갈등 속에 권위를 잃었다. 1918년 3월 볼셰비키가 블라디카프카스를 차지하자 정부는 테미르한슈라를 거쳐 트빌리시로 옮겨 갔다. 러시아어 출처에 따르면 독립 선포는 오스만군이 점령한 바투미의 회담장에서 이루어졌고, 영어 출처는 이스탄불 망명 중이었다고 적는다. 공화국은 7월 8일 오스만 제국과 군사 원조를 포함한 우호 조약을 맺었고, 게오르기 치체린은 독립 선포에 항의하는 각서를 독일 대사에게 보냈다. 공화국은 오스만 원정군의 도움으로 테미르한슈라를 차지했고, 오스만군이 점령한 데르벤트에서 10월 13일 공화국의 재건을 기념해 국기를 올렸다.\n\n오스만이 패전해 물러난 뒤 1918년 말 프셰마호 코체프가 연립 내각을 맡았다. 영국은 처음 공화국을 지지했으나 곧 데니킨과 협력하라고 압박했고, 데니킨은 어떤 협력도 거부했다. 1919년 5월 의용군이 페트롭스크와 데르벤트를 점령하자 테미르한슈라의 정부는 해산하고 다시 트빌리시로 망명했다. 그해 9월 우준 하지는 베데노에서 북캅카스 에미르국을 선포했는데, 러시아어 출처에 따르면 그 지도자들은 산악공화국을 「신화 속의 국가」라 불렀다. 산악공화국 쪽 기구로 활동하던 방위평의회가 1920년 봄 볼셰비키에 장악되며 공화국은 끝났고, 볼셰비키와의 협력을 거부한 고친스키는 1925년 붙잡혀 처형되었다. 볼셰비키는 이 통합 구상의 유산을 의식해 1921년 다게스탄을 뺀 북캅카스 전역에 산악 자치 소비에트 사회주의 공화국을 세웠다.',
            'The May 1917 congress elected Tapa Chermoev, a Chechen oil magnate, as chairman of its Central Committee and the Avar scholar Najmuddin Gotsinsky as mufti of the North Caucasus, and set the goal of autonomy within a federal, democratic Russia. After the October Revolution the union declared autonomy and in December 1917 formed a joint government with the Terek Cossacks, but it lost authority amid the land conflict between mountaineers and Cossacks. When the Bolsheviks took Vladikavkaz in March 1918, the government moved to Temir-Khan-Shura and then to Tbilisi. According to the Russian-language source, independence was proclaimed at the negotiations in Ottoman-occupied Batumi; the English-language source says it was declared in exile in Istanbul. On 8 July the republic concluded a friendship treaty with the Ottoman Empire that included military aid, and Georgy Chicherin sent a note protesting the declaration to the German ambassador. With the help of an Ottoman expeditionary force the republic occupied Temir-Khan-Shura, and on 13 October it raised its flag in Ottoman-held Derbent to celebrate its re-establishment.\n\nAfter the defeated Ottomans withdrew, Pshemakho Kotsev took over a coalition cabinet at the end of 1918. Britain at first supported the republic but soon pressed it to cooperate with Denikin, who rejected any cooperation. When the Volunteer Army took Petrovsk and Derbent in May 1919, the government in Temir-Khan-Shura dissolved and went into exile in Tbilisi again. In September Uzun Hajji proclaimed the North Caucasian Emirate in Vedeno, whose leaders, according to the Russian-language source, called the Mountain Republic a “mythical state”. The republic ended when the Bolsheviks took over the defence council that had acted as its organ in spring 1920, and Gotsinsky, who refused to cooperate with the Bolsheviks, was captured and executed in 1925. Acknowledging the legacy of these unity projects, the Bolsheviks created the Mountain Autonomous Soviet Socialist Republic in 1921, covering the whole North Caucasus except Dagestan.'],
        aliases: { ko: ['북캅카스 산악민 공화국', '북캅카스 민족연합 공화국'], en: ['Mountain Republic of the Northern Caucasus', 'Mountainous Republic of the North Caucasus', 'United Republics of the North Caucasus', 'Republic of the Union of Peoples of the North Caucasus', 'MRNC'] },
        people: ['najmuddin-gotsinsky', 'anton-denikin', 'chicherin'],
        events: ['transcaucasia-1917-1921', 'civil-war'],
        sources: [S.mrnc, S.mrncRu], locator: 'lead; Union of the Peoples of the North Caucasus; Alliance with the Cossacks and Growing Disorder; Red Army Invasion and Government in Exile; Ottoman Intervention; White Army Occupation and Dissolution; Subsequent Developments — ru: преамбула; Провозглашение независимости; Внешняя политика',
    }),
];
