// Person cards for the volga-ural-crimea-1917-1921 event (Volga-Ural Muslim and
// Crimean Tatar national movements, 1917–1921), see lib.js person(). Excerpts are
// verbatim from the cited pages (en/ru Wikipedia as fetched 2026-10-04).
// Bodies with no catalog affiliation (the Bashkir government and army, the Milli
// Idare and Idel-Ural, the Muslim Socialist Committee, the Crimean Tatar
// Directory and Musispolkom, the Crimean Regional Government, Milliy Firqa)
// stay unresolved. Tatar, Bashkir and Crimean Tatar origin has no flag code, so
// national origin is left empty. Native names: Bashkir Cyrillic for Validi,
// Tatar Cyrillic for Maksudi and Vakhitov, Crimean Tatar Latin for Çelebicihan
// and Seydamet, Crimean Tatar/Russian Cyrillic for Ibraimov.
const { W, person } = require('../lib');

const E = t => W(encodeURI(t));
const RU = t => 'https://ru.wikipedia.org/wiki/' + encodeURI(t);
const S = {
    togan: E('Zeki_Velidi_Togan'),
    validiRU: RU('Валиди,_Ахмет-Заки'),
    bashkiria: E('Bashkiria_(1917–1919)'),
    maks: E('Sadri_Maksudi_Arsal'),
    maksRU: RU('Максуди,_Садри'),
    idel: E('Idel-Ural_State'),
    vakh: E('Mullanur_Waxitov'),
    vakhRU: RU('Вахитов,_Мулланур_Муллазянович'),
    muskom: E('Muskom'),
    celebi: E('Noman_Chelebidjikhan'),
    celebiRU: RU('Челебиджихан,_Номан'),
    cpr: E("Crimean_People's_Republic"),
    seyd: E('Cafer_Seydahmet_Kırımer'),
    seydRU: RU('Сейдамет,_Джафер'),
    ibr: E('Veli_İbraimov'),
    ibrRU: RU('Ибраимов,_Вели'),
};

const unaffiliated = card => ({
    ...card,
    activities: card.activities.map(a => (a.affiliationId ? a : { ...a, affiliationStatus: 'unresolved', relation: 'unresolved' })),
});

module.exports = [
    unaffiliated(person({
        id: 'zaki-validi', groupId: 'world-interwar',
        given: ['아흐메트제키', 'Ahmet-Zaki'], family: ['발리디', 'Validi'], nativeName: 'Әхмәтзәки Вәлиди', years: '1890–1970',
        citizenship: { code: 'russia', label: { ko: '러시아 제국 → 튀르키예', en: 'Russian Empire → Turkey' } }, origin: null,
        epithet: ['바시키르 자치를 선포하고 바시키르 군을 이끌다 소비에트 쪽으로 넘어간 바시키르 민족운동 지도자',
            'Leader of the Bashkir national movement who proclaimed Bashkir autonomy, commanded the Bashkir Army and took it over to the Soviet side'],
        bio: ['1890년 우파 현 쿠쟈노보에서 태어나 카잔의 카시미야 마드라사에서 투르크 역사를 가르쳤다. 1917년 사회혁명당에 들어가 제헌의회 의원이 되었고, 샤리프 마나토프와 바시키르 중앙 슈로를 꾸려 바시키르 자치를 선포하고 바시키르 군 사령관이 되었다. 1918년 2월 볼셰비키에게 체포되었다가 4월 풀려나 두토프·콜차크 편에서 싸웠으나, 1919년 2월 군을 소비에트 쪽으로 넘겼다. 1920년 바시레프콤 의장이 되었지만 6월 자치 축소에 반발해 사퇴하고 투르키스탄에서 바스마치 운동을 이끌었다. 1923년 망명해 1925년 튀르키예 국적을 얻었고, 이스탄불 대학 교수와 빈 대학 박사가 되었다. 1970년 이스탄불에서 숨졌다.',
            'Born in 1890 in Kuzyanovo, Ufa province, he taught Turkic history at the Qasimiya madrasa in Kazan. In 1917 he joined the Socialist Revolutionaries and was elected to the Constituent Assembly; with Sharif Manatov he organised the Bashkir Central Shuro, proclaimed Bashkir autonomy and became commander of the Bashkir Army. Arrested by the Bolsheviks in February 1918 and freed in April, he fought alongside Dutov and Kolchak, but in February 1919 took his troops over to the Soviet side. He became chairman of the Bashrevkom in 1920, resigned in June in protest at the curtailing of autonomy and led the Basmachi movement in Turkestan. He emigrated in 1923, became a Turkish citizen in 1925, a professor at Istanbul University and a doctor of the University of Vienna, and died in Istanbul in 1970.'],
        fate: ['exile', '망명지에서 사망', 'Died in exile'],
        aliases: { ko: ['제키 벨리디 토간', '아흐메트제키 발리도프', '아흐메트제키 발리디 토간'], en: ['Zaki Validi', 'Zeki Velidi Togan', 'Ahmet Zeki Velidi Togan', 'Akhmet-Zaki Validov', 'Zaki Validov'] },
        sources: [S.togan, S.validiRU, S.bashkiria],
        facts: {
            years: { claim: '1890–1970', locator: 'lead', excerpt: '10 December 1890 – 26 July 1970' },
            citizenship: { claim: 'granted Turkish citizenship in 1925', source: S.validiRU, locator: 'В эмиграции', excerpt: '3 июня 1925 года в турецкой «Ресми газете» был опубликован Указ Кабинета министров Турции о предоставлении А. Валиди турецкого гражданства.' },
            bio: [
                { claim: 'born in Kuzyanovo, Sterlitamak district, Ufa province', locator: 'Biography', excerpt: 'He was born in Kuzyanovo (Bashkir: Көҙән) village of Sterlitamaksky Uyezd, Ufa Governorate' },
                { claim: 'taught at the Qasimiya madrasa; Duma bureau 1915–1917', locator: 'Biography', excerpt: 'From 1912 to 1915, Velidi taught in the madrasa in Kazan (Qasimiyä), and from 1915 to 1917, he was a member of the bureau, supporting Muslim deputies at the State Duma.' },
                { claim: 'taught history of the Turks at the Qasimiya', source: S.validiRU, locator: 'Становление', excerpt: 'С 1909 года Ахметзаки уже назначали преподавателем истории тюрков и арабской литературы.' },
                { claim: 'Constituent Assembly deputy; SR from 1917', source: S.validiRU, locator: 'Деятельность с 1917 года', excerpt: 'Избран депутатом Всероссийского учредительного собрания от Уфимской губернии. Депутат Миллэт Меджлиси (1917—1918). В 1917 году стал членом Партии социалистов-революционеров.' },
                { claim: 'organised the Bashkir Shuro with Manatov', locator: 'Biography', excerpt: 'with Şərif Manatov, he organized the Bashkir Shuro (Council)' },
                { claim: 'commander of the Bashkir Army', source: S.validiRU, locator: 'Деятельность с 1917 года', excerpt: 'Валидов был избран членом Башкирского правительства и предпарламента Башкурдистана — Малого Курултая, а также был назначен командующим Башкирским войском.' },
                { claim: 'arrested February 1918, freed April 1918', source: S.validiRU, locator: 'Деятельность с 1917 года', excerpt: 'В феврале 1918 года был арестован большевиками в Оренбурге в числе восьмерых членов Башкирского Правительства, в апреле освобождён при атаке отрядов казаков и башкир на город.' },
                { claim: 'fought under Dutov and Kolchak, then switched sides', locator: 'Biography', excerpt: "In 1918 and 1919, Velidi's Bashkir troops first fought under Ataman Alexander Dutov, then under Admiral Kolchak against Bolshevik forces. After the RSFSR promised autonomy to Bashkirs, Velidi switched allegiance, fighting with the Bolsheviks." },
                { claim: 'organised the switch of the Bashkir troops in February 1919', source: S.validiRU, locator: 'Деятельность с 1917 года', excerpt: 'В феврале 1919 года Валиди стал организатором перехода башкирских войск на сторону Красной армии.' },
                { claim: 'chairman of the Bashrevkom from February 1920; resigned in June 1920', source: S.validiRU, locator: 'Деятельность с 1917 года', excerpt: 'в феврале 1920 года был избран председателем Башкирского военно-революционного комитета' },
                { claim: 'resigned over the decree of 19 May 1920', source: S.validiRU, locator: 'Деятельность с 1917 года', excerpt: 'вместе с остальными членами Башревкома, ушёл в отставку' },
                { claim: 'leader of the Basmachi movement', locator: 'Biography', excerpt: 'In Turkistan, Velidi became a leader of the Basmachi Movement.' },
                { claim: 'emigrated in 1923', source: S.validiRU, locator: 'Деятельность в Туркестане', excerpt: 'После ряда военно-политических неудач в 1923 году Валиди эмигрировал за границу.' },
                { claim: 'Chair of Turkish History at Istanbul University, 1927', locator: 'Biography', excerpt: 'From 1925, Velidi lived in Turkey and was appointed Chair of Turkish History at the Istanbul University in 1927.' },
                { claim: 'doctorate at the University of Vienna, 1935', locator: 'Biography', excerpt: 'where he gained a doctor of philosophy at the University of Vienna in 1935' },
                { claim: 'died in Istanbul', source: S.validiRU, locator: 'преамбула', excerpt: '26 июля 1970, Стамбул' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: null, startYear: 1917, endYear: 1919, primary: true, source: S.bashkiria, claim: 'Leader of the Bashkir Army (no catalog affiliation)', locator: 'History', excerpt: 'an independent army, named simply the Bashkir Army, was established under the leadership of Zeki Velidi Togan' },
            { functionId: 'political-leadership', affiliationId: null, startYear: 1917, endYear: 1919, source: S.bashkiria, claim: 'Deputy chairman of the Bashkir Central Shuro, co-signatory of the autonomy declaration (no catalog affiliation)', locator: 'History', excerpt: 'The declaration of autonomy was signed by Central Shuro chairman Sharif Manatov, deputy chairman Zeki Velidi Togan, and secretary Shaikhzada Babich' },
            { functionId: 'government', affiliationId: 'state-soviet', startYear: 1919, endYear: 1920, claim: 'Chairman of the Bashrevkom (Bashkir Revolutionary Committee)', locator: 'Biography', excerpt: 'From February 1919 to June 1920, he was chairman of the Bashrevkom (Bashkir Revolutionary Committee).' },
            { functionId: 'organizing', affiliationId: 'russian-sr', relation: 'membership', startYear: 1917, endYear: 1918, source: S.validiRU, claim: 'Member of the Socialist Revolutionary Party', locator: 'Деятельность с 1917 года', excerpt: 'В 1917 году стал членом Партии социалистов-революционеров.' },
            { functionId: 'organizing', affiliationId: 'soviet-party', relation: 'membership', startYear: 1920, endYear: 1920, source: S.validiRU, claim: 'Joined the RKP(b) in 1920', locator: 'Деятельность с 1917 года', excerpt: 'В 1920 году стал членом РКП(б).' },
            { functionId: 'scholarship', affiliationId: 'state-turkey', startYear: 1927, endYear: 1970, claim: 'Professor of Turkish history at Istanbul University', locator: 'Biography', excerpt: 'was appointed Chair of Turkish History at the Istanbul University in 1927' },
        ],
        career: [
            ['1909–1915', '카잔 카시미야 마드라사 교사', 'Teacher at the Qasimiya madrasa in Kazan'],
            ['1915–1917', '국가 두마 무슬림 의원 지원국', 'Bureau supporting the Muslim deputies of the State Duma'],
            ['1917–1919', '바시키르 중앙 슈로 부의장, 바시키르 군 사령관', 'Deputy chairman of the Bashkir Central Shuro; commander of the Bashkir Army'],
            ['1919–1920', '바시레프콤 군사 인민위원·부의장, 1920년 의장', 'Military commissar and deputy chairman of the Bashrevkom; chairman in 1920'],
            ['1920–1923', '투르키스탄 바스마치 운동 지도자', 'Leader of the Basmachi movement in Turkestan'],
            ['1927', '이스탄불 대학 튀르크사 교수', 'Chair of Turkish History, Istanbul University'],
            ['1935', '빈 대학 철학 박사', 'Doctor of philosophy, University of Vienna'],
        ],
    })),
    unaffiliated(person({
        id: 'sadri-maksudi', groupId: 'world-interwar',
        given: ['사드리', 'Sadri'], family: ['막수디', 'Maksudi'], nativeName: 'Садри Максуди', years: '1878–1957',
        citizenship: { code: 'russia', label: { ko: '러시아 제국 → 튀르키예', en: 'Russian Empire → Turkey' } }, origin: null,
        epithet: ['두마의 무슬림 의원으로 활동하고 이델-우랄 민족 행정부를 이끈 타타르 법률가',
            'Tatar lawyer and Duma deputy who headed the national administration of Idel-Ural'],
        bio: ['1878년 카잔 근처 타슈수 마을에서 태어나, 이스마일 가스프린스키의 권유로 1901~1906년 파리 대학 법학부에서 공부했다. 1906년 「이티파크 알무슬리민」 중앙위원이 되었고, 카잔 현에서 제2·3대 국가 두마 의원으로 뽑혔다. 1917년 전러시아 무슬림 협의회 집행위원회 위원이 되었고, 1918년 1월 5일 내부 러시아·시베리아 무슬림 민족·문화 자치 기관인 밀리 이다레의 의장에 뽑혀 이델-우랄 국가 수반이 되었다. 볼셰비키가 카잔·우파 현을 장악하자 핀란드로 망명했고, 1919년 파리 강화회의에서 이델-우랄 주민의 권리를 호소했으나 성과는 없었다. 1925년 튀르키예로 가 법사학 교수와 국회의원을 지냈고 1957년 이스탄불에서 숨졌다.',
            'Born in 1878 in the village of Tashsu near Kazan, he studied law at the University of Paris in 1901–1906 on Ismail Gasprinsky’s advice. In 1906 he joined the Central Committee of Ittifaq al-Muslimin, and he sat for Kazan province in the Second and Third State Dumas. In 1917 he was on the executive committee of the All-Russian Muslim Council, and on 5 January 1918 he was elected chairman of the Milli Idare, the body of national-cultural autonomy of the Muslims of Inner Russia and Siberia, becoming head of the Idel-Ural State. When the Bolsheviks took Kazan and Ufa provinces he fled to Finland; at the Paris Peace Conference in 1919 he pleaded for the peoples of Idel-Ural, without result. He moved to Turkey in 1925, became a professor of legal history and a member of parliament, and died in Istanbul in 1957.'],
        fate: ['exile', '망명지에서 사망', 'Died in exile'],
        aliases: { ko: ['사드리 막수디 아르살', '사드레트딘 막수도프', '사드리 막수도프'], en: ['Sadri Maksudi Arsal', 'Sadri Maqsudi', 'Sadretdin Maksudov', 'Sadri Maksudov'] },
        sources: [S.maks, S.maksRU, S.idel],
        facts: {
            years: { claim: '1878–1957', locator: 'lead', excerpt: 'Sadri Maksudi Arsal 1878 – 20 February 1957' },
            citizenship: { claim: 'member of the Turkish Parliament', locator: 'Biography', excerpt: 'Arsal was elected as member of the Turkish Parliament for three legislative periods.' },
            bio: [
                { claim: 'born in Tashsu near Kazan', locator: 'Biography', excerpt: 'Sadri Maksudi Arsal was born in 1878 in the village of Taşsu near Kazan, Russian Empire.' },
                { claim: 'law faculty in Paris 1901–1906 on Gasprinsky’s advice', source: S.maksRU, locator: 'Биография', excerpt: 'По совету крымскотатарского интеллектуала Исмаила Гаспринского отправился во Францию, где в 1901—1906 годах учился на юридическом факультете Парижского университета' },
                { claim: 'Central Committee of Ittifaq al-Muslimin', source: S.maksRU, locator: 'Российский политик', excerpt: 'ЦК партии «Иттифак аль-Муслимин»' },
                { claim: 'Second and Third Duma for Kazan', locator: 'Biography', excerpt: 'Arsal operated as a representative of the District of Kazan in the second Duma in 1907 and the third in 1908.' },
                { claim: 'member of Ikomus', source: S.maksRU, locator: 'Во время революции', excerpt: 'Был избран членом Икомус (Исполнительного комитета Всероссийского мусульманского совета).' },
                { claim: 'chairman of the Milli Idare, 5 January 1918', source: S.maksRU, locator: 'Штат Идель-Урал', excerpt: '5 января 1918 года Садри Максуди был избран председателем Милли Идарэ, органа национально-культурной автономии мусульман тюрко-татар Внутренней России и Сибири.' },
                { claim: 'president of the Idel-Ural State', locator: 'lead', excerpt: 'He was the president of the short-lived Idel-Ural State.' },
                { claim: 'emigrated to Finland', source: S.maksRU, locator: 'Штат Идель-Урал', excerpt: 'После захвата территории Казанской и Уфимской губерний большевиками эмигрировал в Финляндию.' },
                { claim: 'spoke at the Paris Peace Conference without result', locator: 'Biography', excerpt: 'at the Peace Conference he spoke for the political rights of people living in the Idel Ural region, though he was not able to produce a positive result with his speech' },
                { claim: 'moved to Turkey in 1925; professor of legal history', locator: 'Biography', excerpt: 'In 1925, Arsal moved to Turkey, where among other things he worked as a lecturer and later as professor of legal history and philosophy in universities of Ankara and Istanbul' },
                { claim: 'Turkish MP 1931–1935, 1935–1939, 1950–1954', source: S.maksRU, locator: 'В Турции', excerpt: 'Трижды был членом турецкого парламента, в 1931—1935, 1935—1939 и 1950—1954 гг.' },
                { claim: 'died in Istanbul in 1957', locator: 'Biography', excerpt: 'He died in 1957 in Istanbul.' },
            ],
        },
        activities: [
            { functionId: 'political-leadership', affiliationId: null, startYear: 1918, endYear: 1918, primary: true, source: S.maksRU, claim: 'Chairman of the Milli Idare, head of the Idel-Ural State (no catalog affiliation)', locator: 'Штат Идель-Урал', excerpt: '5 января 1918 года Садри Максуди был избран председателем Милли Идарэ' },
            { functionId: 'legislature', affiliationId: 'russian-empire', startYear: 1907, endYear: 1912, source: S.maksRU, claim: 'Member of the Second and Third State Dumas for Kazan province', locator: 'преамбула', excerpt: 'Член Государственной Думы второго и третьего созывов от Казанской губернии.' },
            { functionId: 'organizing', affiliationId: null, startYear: 1906, endYear: 1917, source: S.maksRU, claim: 'Member of the Central Committee of Ittifaq al-Muslimin (no catalog affiliation)', locator: 'Российский политик', excerpt: 'был избран в созданный в ходе 3-го Всероссийского мусульманского съезда (Нижний Новгород, август 1906) ЦК партии «Иттифак аль-Муслимин»' },
            { functionId: 'legislature', affiliationId: 'state-turkey', startYear: 1931, endYear: 1954, source: S.maksRU, claim: 'Member of the Turkish parliament for three terms', locator: 'В Турции', excerpt: 'Трижды был членом турецкого парламента, в 1931—1935, 1935—1939 и 1950—1954 гг.' },
            { functionId: 'scholarship', affiliationId: 'state-turkey', startYear: 1925, endYear: 1957, claim: 'Professor of legal history and philosophy in Ankara and Istanbul', locator: 'Biography', excerpt: 'later as professor of legal history and philosophy in universities of Ankara and Istanbul' },
        ],
        career: [
            ['1901–1906', '파리 대학 법학부 수학', 'Law studies at the University of Paris'],
            ['1906', '「이티파크 알무슬리민」 중앙위원', 'Member of the Central Committee of Ittifaq al-Muslimin'],
            ['1907–1912', '제2·3대 국가 두마 의원(카잔 현)', 'Member of the Second and Third State Dumas for Kazan province'],
            ['1917', '전러시아 무슬림 협의회 집행위원회 위원', 'Member of the executive committee of the All-Russian Muslim Council'],
            ['1918', '밀리 이다레 의장(이델-우랄 국가 수반)', 'Chairman of the Milli Idare (head of the Idel-Ural State)'],
            ['1925–1957', '앙카라·이스탄불 대학 법사학 교수', 'Professor of legal history in Ankara and Istanbul'],
            ['1931–1954', '튀르키예 국회의원(세 차례)', 'Member of the Turkish parliament (three terms)'],
        ],
    })),
    unaffiliated(person({
        id: 'mullanur-vakhitov', groupId: 'bolshevik',
        given: ['물라누르', 'Mullanur'], family: ['바히토프', 'Vakhitov'], nativeName: 'Мулланур Вахитов', years: '1885–1918',
        citizenship: { code: 'russia', label: { ko: '러시아 제국 → 소비에트 러시아', en: 'Russian Empire → Soviet Russia' } }, origin: null,
        epithet: ['카잔 무슬림 사회주의 위원회를 이끌고 소비에트 무슬림 업무 위원부 초대 의장이 된 타타르 혁명가',
            'Tatar revolutionary who led the Kazan Muslim Socialist Committee and became the first head of the Soviet Muslim Commissariat'],
        bio: ['1885년 상인 집안에서 태어났고, 출생지는 카잔과 페름 현 카자예보로 엇갈린다. 1905년 혁명에 참여했고, 상트페테르부르크 공과대학을 거쳐 1912년 정신신경학 연구소 법학부로 옮겨 미하일 프룬제 등과 만나고 무슬림 학생 서클을 조직했다. 2월 혁명 뒤 카잔에서 무슬림 사회주의 위원회를 이끌며 신문 「크즐 바이라크」를 냈고, 10월 카잔 군사혁명위원회 위원이 되었으며 제헌의회 의원으로 뽑혔다. 1918년 1월 레닌의 권유로 무슬림 업무 위원부(무스콤) 의장이 되어 불라크 너머 공화국 진압에 수병 부대를 보냈다. 7월 볼가 비상 식량 위원이 되었고, 8월 코무치 인민군이 카잔을 점령한 뒤 붙잡혀 처형되었다.',
            'Born in 1885 into a merchant family, in Kazan or in Kazaevo in Perm province according to different records, he took part in the 1905 revolution. After the St Petersburg Polytechnic he moved in 1912 to the law faculty of the Psychoneurological Institute, where he met Mikhail Frunze among others and organised a circle of Muslim students. After the February Revolution he led the Muslim Socialist Committee in Kazan and its newspaper Qızıl Bayraq, became a member of the Kazan Military Revolutionary Committee in October and was elected to the Constituent Assembly. In January 1918, on Lenin’s advice, he became head of the Muslim Commissariat (Muskom) and sent sailors to crush the Trans-Bulak Republic. Appointed extraordinary food commissar for the Volga in July, he was captured and executed after Komuch’s People’s Army took Kazan in August.'],
        fate: ['executed', '처형', 'Executed'],
        aliases: { ko: ['물라누르 와히토프'], en: ['Mullanur Waxitov', 'Mulla-Nur Vakhitov', 'Mullanur Mullazyanovich Vakhitov'] },
        sources: [S.vakhRU, S.vakh, S.muskom, S.idel],
        facts: {
            years: { claim: '1885–1918', locator: 'преамбула', excerpt: '10 августа 1885, Казаево, Кунгурский уезд — 19 августа 1918, Казань' },
            citizenship: { claim: 'Tatar revolutionary active in the Russian Revolution', source: S.vakh, locator: 'lead', excerpt: 'was a Tatar revolutionary active in the Russian Revolution' },
            bio: [
                { claim: 'born into a merchant family; birthplace disputed', locator: 'Биография', excerpt: 'Родился в семье торговца. Во многих источниках местом рождения значится деревня Казаево Пермской губернии.' },
                { claim: 'mother said he was born in Kazan', locator: 'Биография', excerpt: 'Однако мать Вахитова, Уммегульсум Мустафиевна Казакова, указывала, что сын родился в Казани' },
                { claim: 'student group led by Social Democrats, 1899', locator: 'Биография', excerpt: 'В 1899 году поступил в училище и присоединился к группе учащихся, которой руководили социал-демократы.' },
                { claim: 'entered the St Petersburg Polytechnic in 1907', source: S.vakh, locator: 'Early life', excerpt: 'In 1907, he entered economical department of St Petersburg Polytechnic Institute' },
                { claim: 'took part in the 1905–1907 revolution in Kazan', locator: 'Биография', excerpt: 'Участвовал в революции 1905—1907 годов в Казани.' },
                { claim: 'Psychoneurological Institute, met Frunze and others', locator: 'Биография', excerpt: 'В 1912 году перевёлся на юридический факультет Петербургского психоневрологического института, где встречался с Владимиром Бехтеревым, Михаилом Фрунзе, Яном Гамарником и Ларисой Рейснер.' },
                { claim: 'organised a circle of Muslim students', locator: 'Биография', excerpt: 'Организовал кружок студентов-мусульман.' },
                { claim: 'led the Muslim Socialist Committee and Qızıl Bayraq', locator: 'Биография', excerpt: 'После Февральской революции снова в Казани, где организовал Мусульманский социалистический комитет и руководил им.' },
                { claim: 'member of the Kazan VRK, October 1917', locator: 'Биография', excerpt: 'В октябре 1917 года стал членом казанского ВРК и участвует в установлении советской власти в городе.' },
                { claim: 'elected to the Constituent Assembly', locator: 'Биография', excerpt: 'Был избран членом Учредительного собрания.' },
                { claim: 'headed Muskom on Lenin’s advice, 17 January 1918', locator: 'Биография', excerpt: 'Там встречался с Лениным и по его совету 17 января 1918 года возглавил Комиссариат по делам мусульман Внутренней России.' },
                { claim: 'sent sailors against the Trans-Bulak Republic', locator: 'Биография', excerpt: 'Направил в Казань отряд матросов для ликвидации Забулачной республики' },
                { claim: 'extraordinary food commissar for the Volga, July 1918', locator: 'Биография', excerpt: 'В июле 1918 года был назначен чрезвычайным комиссаром по продовольствию в Поволжье.' },
                { claim: 'arrested and executed after Komuch took Kazan', locator: 'Биография', excerpt: 'После штурма Казани Народной армией КОМУЧа М. М. Вахитов был арестован и казнён.' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-soviet', startYear: 1918, endYear: 1918, primary: true, claim: 'Head of the Commissariat for the Muslim Affairs of Inner Russia (Muskom) under Narkomnats', locator: 'Биография', excerpt: 'по его совету 17 января 1918 года возглавил Комиссариат по делам мусульман Внутренней России' },
            { functionId: 'military', affiliationId: 'state-soviet', startYear: 1918, endYear: 1918, source: S.vakh, claim: 'Chairman of the Central Military Collegium attached to the People’s Commissariat for Military and Naval Affairs', locator: 'After the October Revolution', excerpt: "a chairman of Central Military collegium attached to People's Commissariat of Military and Navy affairs" },
            { functionId: 'economy', affiliationId: 'state-soviet', startYear: 1918, endYear: 1918, claim: 'Extraordinary food commissar for the Volga region', locator: 'Биография', excerpt: 'В июле 1918 года был назначен чрезвычайным комиссаром по продовольствию в Поволжье.' },
            { functionId: 'organizing', affiliationId: null, startYear: 1917, endYear: 1918, claim: 'Leader of the Kazan Muslim Socialist Committee and editor of Qızıl Bayraq (no catalog affiliation)', locator: 'Биография', excerpt: 'Вёл антивоенную и революционную пропаганду с помощью печатного органа МСК газеты «Красное знамя» (тат. Кызыл байрак).' },
        ],
        career: [
            ['1907', '상트페테르부르크 공과대학 경제학부 입학', 'Entered the economics department of the St Petersburg Polytechnic'],
            ['1912', '정신신경학 연구소 법학부, 무슬림 학생 서클 조직', 'Law faculty of the Psychoneurological Institute; organised a Muslim student circle'],
            ['1917', '카잔 무슬림 사회주의 위원회 지도, 카잔 군사혁명위원회 위원', 'Leader of the Kazan Muslim Socialist Committee; member of the Kazan Military Revolutionary Committee'],
            ['1918', '무슬림 업무 위원부(무스콤) 의장', 'Head of the Muslim Commissariat (Muskom)'],
            ['1918', '볼가 지역 비상 식량 위원', 'Extraordinary food commissar for the Volga region'],
        ],
    })),
    unaffiliated(person({
        id: 'noman-celebicihan', groupId: 'world-interwar',
        given: ['노만', 'Noman'], family: ['첼레비지한', 'Çelebicihan'], nativeName: 'Номан Челебиджихан', years: '1885–1918',
        citizenship: { code: 'russia', label: { ko: '러시아 제국', en: 'Russian Empire' } }, origin: null,
        epithet: ['크림 인민공화국 초대 의장이자 선거로 뽑힌 첫 크림 무프티, 크림 타타르 국가 가사를 쓴 시인',
            'First head of the Crimean People’s Republic, the first elected mufti of Crimea and the poet of the Crimean Tatar anthem'],
        bio: ['1885년 장코이 근처 비유크수나크 마을에서 이맘의 아들로 태어났다. 1908년 이스탄불로 가 법학과 신학을 배우며 「청년 타타르 작가 협회」와 비밀 조직 「바탄」(조국)을 만들었고, 1912년 크림으로 돌아왔다. 1917년 3월 크림 무슬림 집행위원회 의장이 되었고, 내무장관의 임명이 아닌 선거로 뽑힌 첫 크림 무프티가 되었다. 6월 반정부 선동 혐의로 체포되었다가 5천 명의 항의 서명으로 풀려났다. 쿠룰타이를 준비해 12월 크림 인민공화국 디렉토리 의장 겸 법무 국장이 되었으나, 1918년 1월 볼셰비키에게 체포되어 2월 23일 세바스토폴에서 재판 없이 수병들에게 살해되었다. 그의 시 「안트 엣켄멘」은 크림 타타르의 국가가 되었다.',
            'Born in 1885 in the village of Büyük Sonaq near Dzhankoy, the son of an imam, he went to Istanbul in 1908 to study law and theology, founded the Young Tatar Writers’ Association and the secret organisation Vatan (Homeland), and returned to Crimea in 1912. In March 1917 he became chairman of the Crimean Muslim Executive Committee and the first mufti of Crimea elected by delegates rather than appointed by the Minister of the Interior. Arrested in June for anti-government agitation, he was freed after a protest bearing 5,000 signatures. He prepared the Qurultay and in December became chairman and director of justice of the Directory of the Crimean People’s Republic, but was arrested by the Bolsheviks in January 1918 and killed without trial by sailors in Sevastopol on 23 February. His poem “Ant etkenmen” became the Crimean Tatar national anthem.'],
        fate: ['murdered', '살해', 'Murdered'],
        aliases: { ko: ['첼레비 첼레비예프', '노만 첼레비디지한'], en: ['Noman Chelebidjikhan', 'Noman Celebicihan', 'Chelebi Chelebiev', 'Noman Chelebijihan'] },
        sources: [S.celebiRU, S.celebi, S.cpr],
        facts: {
            years: { claim: '1885–1918', source: S.celebi, locator: 'lead', excerpt: '1885 – 23 February 1918' },
            citizenship: { claim: 'born in Taurida province of the Russian Empire', locator: 'преамбула', excerpt: 'близ Джанкоя, Перекопский уезд, Таврическая губерния' },
            bio: [
                { claim: 'born in Büyük Sonaq near Dzhankoy', source: S.celebi, locator: 'Biography', excerpt: 'Noman Çelebicihan was born in 1885, in the village of Büyük Sonaq, in Chonhar region of Crimea near the present-day city of Dzhankoy.' },
                { claim: 'son of an imam', locator: 'Биография', excerpt: 'Родился в семье Ибраима Челеби, имама мечети села Биюк-Сунак.' },
                { claim: 'studied law and theology in Istanbul', locator: 'Общественно-политическая деятельность в Турции', excerpt: 'В Стамбульском университете получил высшее юридическое и богословское образование.' },
                { claim: 'founded the Young Tatar Writers’ Association', source: S.celebi, locator: 'Biography', excerpt: 'One of the first organizations he founded, while a student in Constantinople, was "Yaş Tatar Yazıcılar Cıyını" (Young Tatar Writers\' Association).' },
                { claim: 'co-founder of Vatan', locator: 'Общественно-политическая деятельность в Турции', excerpt: 'Основатели: Номан Челебиджихан, Джафер Сейдамет, Абибулла Одабаш.' },
                { claim: 'returned to Crimea in 1912', locator: 'Общественно-политическая деятельность в Турции', excerpt: 'В 1912 году Номан Челебиджихан возвратился в Крым.' },
                { claim: 'law faculty of the Psychoneurological Institute, 1913', locator: 'Общественно-политическая деятельность в Турции', excerpt: 'В 1913 году поступил на юридический факультет Санкт-Петербургского института психоневрологии' },
                { claim: 'chairman of Musispolkom and first elected mufti', locator: 'Общественно-политическая деятельность в Крыму', excerpt: 'Одновременно он стал первым муфтием (временным) мусульман Крыма, который не назначался Министром внутренних дел, а был избран голосованием делегатов.' },
                { claim: 'arrested 23 June 1917, freed after 5,000 signatures', locator: 'Общественно-политическая деятельность в Крыму', excerpt: 'крымские татары выразили протест в защиту своего лидера, скрепив его 5 тысячами подписей' },
                { claim: 'chairman of the Directory and director of justice', locator: 'Общественно-политическая деятельность в Крыму', excerpt: 'Челебиджихан был избран председателем национального правительства — Совета директоров (Директории) и одновременно начальником его управления юстиции.' },
                { claim: 'arrested 26 January 1918', locator: 'Общественно-политическая деятельность в Крыму', excerpt: '26 января 1918 года он был арестован и заключен в Севастопольской тюрьме.' },
                { claim: 'arrested January 1918; killed without trial 23 February', locator: 'Общественно-политическая деятельность в Крыму', excerpt: '23 февраля этого же года в городе Севастополе он был без суда убит революционными матросами, а его тело было выброшено в Чёрное море.' },
                { claim: 'author of the Crimean Tatar anthem', locator: 'преамбула', excerpt: 'Известен также как автор стихотворения «Ant etkenmen» («Я поклялся»), которое стало национальным гимном крымских татар.' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: null, startYear: 1917, endYear: 1918, primary: true, claim: 'Chairman of the Directory of the Crimean People’s Republic (no catalog affiliation)', locator: 'преамбула', excerpt: 'первый председатель правительства Крымской Народной Республики' },
            { functionId: 'religion', affiliationId: null, startYear: 1917, endYear: 1918, claim: 'First elected mufti of the Muslims of Crimea, Lithuania, Poland and Belarus (no catalog affiliation)', locator: 'преамбула', excerpt: 'первый избранный временный муфтий мусульман Крыма, Литвы, Польши, Белоруссии' },
            { functionId: 'political-leadership', affiliationId: null, startYear: 1917, endYear: 1918, claim: 'Chairman of the Crimean Muslim Executive Committee and organiser of the Qurultay (no catalog affiliation)', locator: 'преамбула', excerpt: 'организатор I Курултая крымскотатарского народа' },
        ],
        career: [
            ['1908–1912', '이스탄불에서 법학·신학 수학, 「바탄」 결성', 'Studied law and theology in Istanbul; co-founded Vatan'],
            ['1913', '페테르부르크 정신신경학 연구소 법학부', 'Law faculty of the Psychoneurological Institute, St Petersburg'],
            ['1917', '크림 무슬림 집행위원회 의장, 크림 무프티', 'Chairman of the Crimean Muslim Executive Committee; mufti of Crimea'],
            ['1917–1918', '크림 인민공화국 디렉토리 의장 겸 법무 국장', 'Chairman and director of justice of the Directory of the Crimean People’s Republic'],
        ],
    })),
    unaffiliated(person({
        id: 'cafer-seydahmet', groupId: 'world-interwar',
        given: ['자페르', 'Cafer'], family: ['세이다흐메트', 'Seydahmet'], nativeName: 'Cafer Seydamet', years: '1889–1960',
        citizenship: { code: 'turkey', label: { ko: '러시아 제국 → 튀르키예', en: 'Russian Empire → Turkey' } }, origin: null,
        epithet: ['크림 인민공화국의 군사·외무를 맡고 망명지에서 크림 타타르 민족운동을 이끈 정치가',
            'Crimean Tatar politician who ran the military and foreign affairs of the Crimean People’s Republic and led the national movement in exile'],
        bio: ['1889년 얄타 군 키질타슈의 부유한 농민 집안에서 태어나 이스탄불 대학 법학부에서 노만 첼레비지한을 만났다. 1911년 『20세기의 억압받는 크림 타타르 민족』을 펴낸 뒤 체포를 피해 파리에서 공부했고, 1914년 돌아와 사관 학교를 거쳐 소위가 되었다. 1917년 「밀레트」를 잠시 편집했고, 쿠룰타이가 세운 디렉토리에서 군사·외무 국장이 되었다. 1918년 1월 볼셰비키에게 밀려 키이우로 피했고, 독일군 점령 뒤 술키에비치의 크림 지역 정부 외무장관으로 베를린에서 독립 승인을 구했다. 독일군 철수 뒤 이스탄불로 가 신문 「에멜」을 만들고 프로메테우스 운동을 지지했다. 1934년 성 「크르메르」를 얻었고 1960년 이스탄불에서 숨졌다.',
            'Born in 1889 into a family of wealthy peasants in Kizil-Tash in the Yalta district, he met Noman Çelebicihan at the law faculty of Istanbul University. After publishing The Oppressed Crimean Tatar Nation in the 20th Century in 1911 he escaped arrest by studying in Paris, and on his return in 1914 he went through cadet school and became an ensign. In 1917 he briefly edited Millet and became director of military and foreign affairs in the Directory set up by the Qurultay. Driven out by the Bolsheviks in January 1918, he fled to Kyiv; under the German occupation he became foreign minister of Sulkiewicz’s Crimean Regional Government and sought recognition of its independence in Berlin. After the German withdrawal he went to Istanbul, founded the newspaper Emel and supported Prometheism. He took the surname Kırımer in 1934 and died in Istanbul in 1960.'],
        fate: ['exile', '망명지에서 사망', 'Died in exile'],
        aliases: { ko: ['자페르 세이다메트', '자페르 세이다흐메트 크르메르', '자페르 크르메르'], en: ['Cafer Seydamet', 'Cafer Seydahmet Kırımer', 'Cafer Seydamet Qırımer', 'Jafer Seidamet', 'Dzhafer Seidamet'] },
        sources: [S.seyd, S.seydRU, S.cpr],
        facts: {
            years: { claim: '1889–1960', locator: 'lead', excerpt: '1 September 1889 – 3 April 1960' },
            citizenship: { claim: 'adopted a Turkish surname under the Surname Law; died in Istanbul', locator: 'Biography', excerpt: 'following the adoption of the Surname Law' },
            bio: [
                { claim: 'born in Kizil-Tash, Yalta district', source: S.seydRU, locator: 'преамбула', excerpt: '1 сентября 1889, Кизилташ, Ялтинский уезд, Таврическая губерния' },
                { claim: 'wealthy peasant family; Istanbul law faculty; met Çelebicihan', locator: 'Biography', excerpt: 'In Istanbul, he met Noman Çelebicihan, then also a student' },
                { claim: 'essay of 1911 and extradition attempts', locator: 'Biography', excerpt: "Following the publishing of this essay, the government of the Russian Empire began to seek Seydahmet's extradition." },
                { claim: 'studied in Paris', locator: 'Biography', excerpt: 'To avoid arrest, he travelled to Paris and enrolled at the University of Paris.' },
                { claim: 'cadet school and commission as ensign', source: S.seydRU, locator: 'Биография', excerpt: 'В 1914 году вернулся в Россию, окончил Юнкерское училище, выпущен в полк прапорщиком.' },
                { claim: 'chairman of the waqf commission of the Muslim Executive Committee, March 1917', source: S.seydRU, locator: 'Биография', excerpt: '25 марта 1917 года состоялось заседание Общекрымского мусульманского собрания, где он был избран временным председателем вакуфной комиссии Мусульманского исполкома.' },
                { claim: 'edited Millet; Directory member', locator: 'Biography', excerpt: 'He was a leading member of the Provisional Muslim Revolutionary Committee, and helped to edit the newspaper Millet, and served as a member of the Directory.' },
                { claim: 'Director of Foreign and Military Affairs', locator: 'Biography', excerpt: 'Following the declaration of the Crimean People\'s Republic, Seydahmet was appointed as Director of Foreign and Military Affairs.' },
                { claim: 'fled to Kyiv', locator: 'Biography', excerpt: 'Çelebicihan was killed, and Seydahmet fled north to Kyiv.' },
                { claim: 'foreign minister of the Crimean Regional Government; Berlin mission', source: S.seydRU, locator: 'Биография', excerpt: 'Вскоре он был отправлен с дипломатической миссией в Берлин, где добивался признания независимости правительства Сулькевича от украинского правительства гетмана П. П. Скоропадского.' },
                { claim: 'fled to Istanbul after the German withdrawal', locator: 'Biography', excerpt: "Following the German withdrawal from Crimea, however, Sulkiewicz's government fell, and Seydahmet fled Crimea for Istanbul." },
                { claim: 'founded Emel', locator: 'Biography', excerpt: 'In Istanbul, Seydahmet was an early supporter of Mustafa Kemal Atatürk, and founded a newspaper, named Emel.' },
                { claim: 'supporter of Prometheism', locator: 'Biography', excerpt: 'Seydahmet later became an active supporter of Prometheism.' },
                { claim: 'died in Istanbul, 3 April 1960', locator: 'Biography', excerpt: 'Cafer Seydahmet Kırımer died in Istanbul on 3 April 1960.' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: null, startYear: 1917, endYear: 1918, primary: true, claim: 'Director of Foreign and Military Affairs of the Crimean People’s Republic (no catalog affiliation)', locator: 'lead', excerpt: "He served as Prime Minister and Director of Foreign and Military Affairs in the Crimean People's Republic" },
            { functionId: 'diplomacy', affiliationId: null, startYear: 1918, endYear: 1918, claim: 'Foreign minister of the Crimean Regional Government (no catalog affiliation)', locator: 'Biography', excerpt: 'Seydahmet returned to the peninsula and was appointed Minister of Foreign Affairs in the new government.' },
            { functionId: 'political-leadership', affiliationId: null, startYear: 1917, endYear: 1960, claim: 'Founder and leader of Milliy Firqa (no catalog affiliation)', locator: 'lead', excerpt: "was one of the founders and leaders of Milliy Firqa and Crimean People's Republic" },
            { functionId: 'propaganda', affiliationId: null, startYear: 1918, endYear: 1960, claim: 'Founder of the émigré newspaper Emel (no catalog affiliation)', locator: 'Biography', excerpt: 'founded a newspaper, named Emel' },
        ],
        career: [
            ['1911', '『20세기의 억압받는 크림 타타르 민족』 출간', 'Published The Oppressed Crimean Tatar Nation in the 20th Century'],
            ['1914', '사관 학교 졸업, 소위로 임관', 'Graduated from cadet school; commissioned as an ensign'],
            ['1917–1918', '크림 인민공화국 디렉토리 군사·외무 국장', 'Director of military and foreign affairs, Directory of the Crimean People’s Republic'],
            ['1918', '크림 지역 정부 외무장관', 'Foreign minister of the Crimean Regional Government'],
            ['1918–1960', '이스탄불·유럽에서 크림 타타르 망명 운동 지도', 'Led the Crimean Tatar émigré movement from Istanbul and Europe'],
        ],
    })),
    unaffiliated(person({
        id: 'veli-ibraimov', groupId: 'bolshevik',
        given: ['벨리', 'Veli'], family: ['이브라이모프', 'Ibraimov'], nativeName: 'Вели Ибраимов', years: '1888–1928',
        citizenship: { code: 'soviet', label: { ko: '러시아 제국 → 소련', en: 'Russian Empire → Soviet Union' } }, origin: null,
        epithet: ['크림 자치 공화국 중앙집행위원회 의장으로 크림 타타르 자치를 밀다 처형된 민족 공산주의자',
            'Crimean Tatar national communist who pressed Crimean Tatar interests as head of the Crimean ASSR and was executed'],
        bio: ['1888년 바흐치사라이의 상인 집안에서 태어나 14살부터 신문 「테르지만」에서 일하며 이스마일 가스프린스키에게 배웠다. 1905년 혁명에 참여하고 1909~1912년 오스만 제국에 살았다. 1916년 크림 타타르 노동조합 의장, 1917년 쿠룰타이 대의원으로 밀리 피르카 좌파를 이끌었다. 1918년 볼셰비키에 들어가 1919~1920년 캅카스 전선 체카 특별부에서 일했다. 1920년 12월부터 크림을 기근 지역으로 인정하라고 요구했고, 1921~1924년 크림 자치 공화국 노농 감찰 인민위원을 지냈다. 1924년 크림 중앙집행위원회 의장이 되어 유대인 이주 계획에 맞섰으나, 1928년 살인 사건 관련 혐의로 처형되었고 1990년 복권되었다.',
            'Born in 1888 into a merchant family in Bakhchysarai, he worked from the age of 14 at the newspaper Terciman, where Ismail Gasprinsky tutored him. He took part in the 1905 revolution and lived in the Ottoman Empire in 1909–1912. In 1916 he chaired a Crimean Tatar labour union, and in 1917 he was a Qurultay delegate and led the left wing of Milliy Firqa. He joined the Bolsheviks in 1918 and served in the Cheka special department on the Caucasus front in 1919–1920. From December 1920 he called for Crimea to be recognised as a famine region, and in 1921–1924 he was People’s Commissar of the Workers’ and Peasants’ Inspection of the Crimean ASSR. As chairman of the Crimean Central Executive Committee from 1924 he opposed Jewish resettlement, but in 1928 he was executed on charges linked to a murder case; he was rehabilitated in 1990.'],
        fate: ['executed', '처형', 'Executed'],
        aliases: { ko: ['벨리 이브라히모프', '벨리 이브라기모프'], en: ['Veli İbraimov', 'Veli Ibrahimov', 'Veli Ibragimov'] },
        sources: [S.ibr, S.ibrRU],
        facts: {
            years: { claim: '1888–1928', locator: 'lead', excerpt: '1888 – 9 May 1928' },
            citizenship: { claim: 'Soviet politician, chairman of the CEC of the Crimean ASSR', locator: 'lead', excerpt: 'was a Crimean Tatar revolutionary and Soviet politician' },
            bio: [
                { claim: 'born in Bakhchysarai; merchant father', locator: 'Early life and career', excerpt: 'Veli İbraimov was born in the city of Bakhchysarai, Crimea, in 1888. His father, Ibraim, was a merchant' },
                { claim: 'left school at 12; worked at Terciman from 14, tutored by Gasprinsky', locator: 'Early life and career', excerpt: 'At the age of 14, he began working with his brother in the Terciman newspaper. They were personally tutored by Crimean Tatar political leader Ismail Gasprinsky' },
                { claim: 'lived in the Ottoman Empire 1909–1912', locator: 'Early life and career', excerpt: 'After partaking in the 1905 Russian Revolution, İbraimov left to live in the Ottoman Empire, living there from 1909 to 1912.' },
                { claim: 'president of a Crimean Tatar labour union, 1916', locator: 'Early life and career', excerpt: 'In 1916, he was president of a Crimean Tatar labour union.' },
                { claim: 'Qurultay delegate; led Milliy Firqa’s left wing', locator: 'Early life and career', excerpt: "He was a member of Milliy Firqa, and led the party's left wing." },
                { claim: 'joined the Bolsheviks in 1918; Cheka on the Caucasus front', source: S.ibrRU, locator: 'Во время Гражданской войны', excerpt: 'Со второй половины 1919 года и в 1920 году находился на Кавказском фронте в качестве сотрудника Особого отдела ВЧК.' },
                { claim: 'motion to declare Crimea a famine region, December 1920', locator: 'Early political career', excerpt: 'introduced a motion to do so in December 1920' },
                { claim: 'narkom RKI November 1921 – August 1924', source: S.ibrRU, locator: 'После установления советской власти', excerpt: 'С ноября 1921 года и по август 1924 года Ибраимов занимает пост наркома Рабоче-Крестьянской Инспекции (РКИ) Крымской АССР.' },
                { claim: 'head of the troika against banditism, 1922', source: S.ibrRU, locator: 'После установления советской власти', excerpt: '30 января 1922 года президиум Крымского областного комитета РКП(б) принял постановление о создании Чрезвычайной тройки по борьбе с бандитизмом, которую возглавил Вели Ибраимов.' },
                { claim: 'chairman of the CEC from August 1924; opposed Jewish resettlement', locator: 'Chairman of the Central Executive Committee', excerpt: 'In August 1924, İbraimov was appointed Chairman of the Central Executive Committee of the Crimean ASSR.' },
                { claim: 'opposed Jewish resettlement', locator: 'Chairman of the Central Executive Committee', excerpt: 'publicly standing against efforts to resettle Jews from Ukraine and Belarus as part of a planned Jewish autonomy in Crimea' },
                { claim: 'executed 9 May 1928', locator: 'Downfall and death', excerpt: 'On 9 May 1928, Abdulla and İbraimov were executed.' },
                { claim: 'suspected after the Cholak murder', locator: 'Downfall and death', excerpt: 'Immediately, İbraimov came under suspicion by Soviet police authorities.' },
                { claim: 'rehabilitated in 1990', locator: 'lead', excerpt: 'In 1990, he was rehabilitated by Soviet authorities due to lack of evidence.' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-soviet', startYear: 1924, endYear: 1928, primary: true, claim: 'Chairman of the Central Executive Committee of the Crimean ASSR', locator: 'lead', excerpt: 'He served as the second Chairman of the Central Executive Committee of the Crimean Autonomous Soviet Socialist Republic, serving from 1924 to 1928.' },
            { functionId: 'government', affiliationId: 'state-soviet', startYear: 1921, endYear: 1924, source: S.ibrRU, claim: 'People’s Commissar of the Workers’ and Peasants’ Inspection of the Crimean ASSR', locator: 'После установления советской власти', excerpt: 'С ноября 1921 года и по август 1924 года Ибраимов занимает пост наркома Рабоче-Крестьянской Инспекции (РКИ) Крымской АССР.' },
            { functionId: 'security', affiliationId: 'state-soviet', startYear: 1919, endYear: 1920, source: S.ibrRU, claim: 'Officer of the Cheka special department on the Caucasus front', locator: 'Во время Гражданской войны', excerpt: 'находился на Кавказском фронте в качестве сотрудника Особого отдела ВЧК' },
            { functionId: 'security', affiliationId: 'state-soviet', startYear: 1922, endYear: 1922, source: S.ibrRU, claim: 'Head of the Crimean emergency troika against banditism', locator: 'После установления советской власти', excerpt: 'Чрезвычайной тройки по борьбе с бандитизмом, которую возглавил Вели Ибраимов' },
            { functionId: 'political-leadership', affiliationId: 'soviet-party', relation: 'membership', startYear: 1918, endYear: 1928, claim: 'Member of the Russian Communist Party (Bolsheviks) from 1918', locator: 'lead', excerpt: 'joined the Russian Communist Party in 1918, and became a national communist authority within Crimea' },
            { functionId: 'organizing', affiliationId: null, startYear: 1916, endYear: 1917, claim: 'President of a Crimean Tatar labour union (no catalog affiliation)', locator: 'Early life and career', excerpt: 'In 1916, he was president of a Crimean Tatar labour union.' },
        ],
        career: [
            ['1916', '크림 타타르 노동조합 의장', 'Chairman of a Crimean Tatar labour union'],
            ['1917', '쿠룰타이 대의원, 밀리 피르카 좌파 지도', 'Qurultay delegate; leader of the left wing of Milliy Firqa'],
            ['1919–1920', '캅카스 전선 체카 특별부 요원', 'Cheka special department officer on the Caucasus front'],
            ['1921–1924', '크림 자치 공화국 노농 감찰 인민위원', 'People’s Commissar of the Workers’ and Peasants’ Inspection, Crimean ASSR'],
            ['1922', '크림 반유격대 비상 3인 위원회 책임자', 'Head of the Crimean emergency troika against banditism'],
            ['1924–1928', '크림 자치 공화국 중앙집행위원회 의장', 'Chairman of the Central Executive Committee of the Crimean ASSR'],
        ],
    })),
];

