// Person cards for the Soviet zone 1945–1949 event, second group (the youngest
// of the Ulbricht Group, the first CDU chairman, the SPD organiser who fled the
// SED, Schumacher's deputy, and the DWK chairman), see lib.js person().
// Excerpts are verbatim from the cited pages.
const { person } = require('../baltic-1940-1953-20261002/lib');

const EN = t => 'https://en.wikipedia.org/wiki/' + encodeURI(t);
const DE = t => 'https://de.wikipedia.org/wiki/' + encodeURI(t);
const S = {
    leonhard: EN('Wolfgang_Leonhard'),
    deLeonhard: DE('Wolfgang_Leonhard'),
    hermes: EN('Andreas_Hermes'),
    deHermes: DE('Andreas_Hermes'),
    deGniffke: DE('Erich_Gniffke'),
    ollenhauer: EN('Erich_Ollenhauer'),
    deOllenhauer: DE('Erich_Ollenhauer'),
    rau: EN('Heinrich_Rau'),
    deRau: DE('Heinrich_Rau'),
};

module.exports = [
    person({
        id: 'wolfgang-leonhard', groupId: 'world-cold-war',
        given: ['볼프강', 'Wolfgang'], family: ['레온하르트', 'Leonhard'], nativeName: 'Wolfgang Leonhard', years: '1921–2014',
        citizenship: 'germany', origin: 'germany',
        epithet: ['울브리히트 그룹의 막내로 귀국했다가 1949년 유고슬라비아로 탈출한 소련·동독 연구자',
            'Youngest member of the Ulbricht Group who fled to Yugoslavia in 1949 and became a leading Western scholar of Soviet communism'],
        bio: ['빈에서 블라디미르라는 이름으로 태어났다. 공산주의자인 어머니와 함께 1935년 소련으로 망명했으나 어머니는 1936년 체포되어 보르쿠타 수용소에서 12년을 보냈다. 코민테른 학교를 마치고 자유독일 방송의 아나운서가 되었고, 1945년 4월 30일 울브리히트 그룹의 일원으로 베를린에 돌아왔다. 공산당과 사회주의통일당 중앙위원회 선전선동부에서 일했고 1947년부터 당 대학에서 가르쳤다. 독일이 소련 체제를 그대로 따른다고 확신하게 되자 1949년 3월 프라하를 거쳐 유고슬라비아로 탈출했고, 1950년 서독으로 갔다. 1955년 회고록으로 널리 알려졌고, 1966~1987년 예일 대학에서 소련사를 가르쳤다.',
            'Born Vladimir Leonhard in Vienna, he went into Soviet exile with his Communist mother in 1935; she was arrested in 1936 and spent twelve years in the Vorkuta camps. After the Comintern school he became an announcer for Radio Free Germany, and on 30 April 1945 he returned to Berlin as a member of the Ulbricht Group. He worked in the agitation and propaganda department of the KPD and then SED Central Committee and from 1947 lectured at the party college. Convinced that Germany would replicate the Soviet system, he fled via Czechoslovakia to Yugoslavia in March 1949 and moved to West Germany in 1950. His 1955 memoir Die Revolution entlässt ihre Kinder became an international bestseller, and from 1966 to 1987 he taught Soviet history at Yale.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: [], en: ['Wladimir Leonhard'] },
        sources: [S.leonhard, S.deLeonhard],
        facts: {
            years: { claim: '1921–2014', locator: 'lead', excerpt: 'Wolfgang Leonhard (16 April 1921 – 17 August 2014) was a German political author and historian of the Soviet Union' },
            citizenship: { claim: 'German historian and publicist', source: S.deLeonhard, locator: 'Einleitung', excerpt: 'war ein deutscher Historiker und Publizist' },
            nationalOrigin: { claim: 'German Communist whose family fled Hitler’s Germany', locator: 'lead', excerpt: "A German Communist whose family had fled Hitler's Germany and who was educated in the Soviet Union" },
            bio: [
                { claim: 'Born Vladimir in Vienna', locator: 'Early life', excerpt: 'Wolfgang (originally Vladimir) Leonhard was born in Vienna' },
                { claim: 'Exile in the Soviet Union in 1935', source: S.deLeonhard, locator: 'Jugend- und Erwachsenenjahre in der Sowjetunion', excerpt: 'im Juni 1935 über Leningrad nach Moskau' },
                { claim: 'Mother arrested in 1936; twelve years in Vorkuta', locator: 'In the Soviet Union', excerpt: "Leonhard's mother was arrested by the secret police, NKVD, in October 1936, and had to do forced labour for the next 12 years, mainly in the camp of Vorkuta" },
                { claim: 'Comintern school', locator: 'In the Soviet Union', excerpt: "Leonhard's final exams at the Comintern school in the summer of 1943 coincided with the dissolution of the Comintern and the closure of the school." },
                { claim: 'Announcer at Radio Free Germany', locator: 'In the Soviet Union', excerpt: "made Leonhard an announcer at the Committee's radio station, \"Radio Free Germany\"" },
                { claim: 'Returned with the Ulbricht Group on 30 April 1945', source: S.deLeonhard, locator: 'Rückkehr nach Deutschland 1945', excerpt: 'Wladimir Leonhard kehrte am 30. April 1945 als 24-jähriger Jungfunktionär mit Walter Ulbricht in der so genannten Gruppe Ulbricht nach Berlin zurück' },
                { claim: 'Agitprop department of the KPD/SED Central Committee', source: S.deLeonhard, locator: 'Rückkehr nach Deutschland 1945', excerpt: 'Von Juli 1945 bis September 1947 war Wolfgang Leonhard in der Abteilung Agitation und Propaganda des ZK der KPD (ab 1946 ZK der SED) tätig.' },
                { claim: 'Lecturer at the party college from 1947', locator: 'In East Germany', excerpt: "In September 1947 he became a lecturer in the history department of the party's college Karl Marx." },
                { claim: 'Convinced Germany would replicate the Soviet system', locator: 'Escape to Yugoslavia', excerpt: 'This speech convinced Leonhard that Germany was not going to follow a different path to socialism, but would replicate the Soviet system.' },
                { claim: 'Fled to Yugoslavia via Czechoslovakia in March 1949', locator: 'Escape to Yugoslavia', excerpt: 'In March 1949, he fled to Yugoslavia via Czechoslovakia.' },
                { claim: 'West Germany in 1950', locator: 'lead', excerpt: 'first defecting to Yugoslavia and then moving to West Germany in 1950' },
                { claim: '1955 memoir an international bestseller', locator: 'In the West', excerpt: 'His 1955 memoir, Die Revolution entlässt ihre Kinder ("Child of the Revolution"), was translated into many languages and was an international bestseller.' },
                { claim: 'Taught at Yale 1966–1987', locator: 'In the West', excerpt: 'Professor Leonhard taught Soviet history and the history of international Communism at Yale from 1966 to 1987.' },
                { claim: 'Died after a long illness', locator: 'Death', excerpt: 'Leonhard died on August 17, 2014, at a hospital in Daun, Germany, from a long illness at the age of 93.' },
            ],
        },
        activities: [
            { functionId: 'propaganda', affiliationId: 'party-german-sed', startYear: 1945, endYear: 1949, primary: true, claim: 'Agitprop department of the KPD/SED Central Committee, then lecturer at the party college', source: S.deLeonhard, locator: 'Rückkehr nach Deutschland 1945', excerpt: 'Von Juli 1945 bis September 1947 war Wolfgang Leonhard in der Abteilung Agitation und Propaganda des ZK der KPD (ab 1946 ZK der SED) tätig.' },
            { functionId: 'education', affiliationId: 'party-german-sed', startYear: 1947, endYear: 1949, claim: 'Lecturer at the SED party college', locator: 'In East Germany', excerpt: "In September 1947 he became a lecturer in the history department of the party's college Karl Marx." },
            { functionId: 'propaganda', affiliationId: 'party-german-communist', startYear: 1943, endYear: 1945, claim: 'Announcer at Radio Free Germany of the National Committee', locator: 'In the Soviet Union', excerpt: "made Leonhard an announcer at the Committee's radio station, \"Radio Free Germany\"" },
        ],
        career: [
            ['1935', '어머니와 함께 소련으로 망명', 'Went into Soviet exile with his mother'],
            ['1943', '자유독일 방송 아나운서', 'Announcer at Radio Free Germany'],
            ['1945', '울브리히트 그룹의 일원으로 베를린 귀환', 'Returned to Berlin with the Ulbricht Group'],
            ['1947', '사회주의통일당 당 대학 강사', 'Lecturer at the SED party college'],
            ['1949', '유고슬라비아로 탈출', 'Fled to Yugoslavia'],
            ['1955', '회고록 출간', 'Published his memoir'],
            ['1966–1987', '예일 대학 교수', 'Professor at Yale'],
        ],
    }),
    person({
        id: 'andreas-hermes', groupId: 'world-cold-war',
        given: ['안드레아스', 'Andreas'], family: ['헤르메스', 'Hermes'], nativeName: 'Andreas Hermes', years: '1878–1964',
        citizenship: 'germany', origin: 'germany',
        epithet: ['바이마르 공화국 재무장관을 지내고 1945년 소련 점령지구 기독교민주연합을 세운 농업 정치가',
            'Weimar finance minister who founded the CDU in the Soviet zone in 1945 and was deposed for opposing the land reform'],
        bio: ['쾰른의 철도 노동자 집안에서 태어나 농학을 공부했고, 1911년부터 로마의 국제농업연구소에서 일했다. 1920년 가톨릭 중앙당 소속으로 식량장관이 되었고, 1922년부터 1923년 8월 쿠노 내각이 물러날 때까지 재무장관을 지냈다. 나치 집권 뒤 체포되었고 콜롬비아 정부의 경제 고문을 지냈다. 귀국한 뒤 괴르델러 일파와 이어져 7월 20일 사건 뒤 체포되었고, 1945년 1월 사형을 선고받았으나 아내가 집행을 늦춰 붉은 군대의 베를린 점령으로 살아남았다. 1945년 6월 베를린과 소련 점령지구 기독교민주연합의 첫 의장이 되었으나, 보상 없는 토지개혁을 비판해 12월 군정청에 의해 물러났다. 서독으로 옮겨 농민연맹 의장을 지내며 통일을 주장했다.',
            'The son of a Cologne railway worker, he studied agriculture and from 1911 worked at the International Institute of Agriculture in Rome. A member of the Catholic Centre Party, he became Minister of Food in 1920 and was Minister of Finance from 1922 until the Cuno cabinet resigned in August 1923. Arrested after the Nazis took power, he later served as an economic adviser to the government of Colombia. Back in Germany he joined the resistance around Goerdeler, was arrested after 20 July 1944 and sentenced to death in January 1945, but his wife delayed the execution until the Red Army took Berlin. On 26 June 1945 he became the first chairman of the CDU of Berlin and the Soviet zone; because he refused to agree to the land reform without compensation, SMAD deposed him in December. In the West he founded the German Farmers’ Association and argued for reunification.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: [], en: [] },
        sources: [S.hermes, S.deHermes],
        facts: {
            years: { claim: '1878–1964', locator: 'lead', excerpt: 'Andreas Hermes (16 July 1878 – 4 January 1964) was a German agricultural scientist and politician.' },
            citizenship: { claim: 'German politician (Centre Party, CDU)', source: S.deHermes, locator: 'Einleitung', excerpt: 'war ein deutscher Staatswissenschaftler und Politiker (Zentrum, CDU)' },
            nationalOrigin: { claim: 'Born in Cologne, son of a railway worker', locator: 'Early life', excerpt: 'Hermes was born on 16 July 1878 in Cologne, then part of the Prussian Rhine province, as the son of Andreas Hermes (1832–1884), a railway worker' },
            bio: [
                { claim: 'Studied agricultural science', locator: 'Early life', excerpt: 'Hermes studied agricultural science and philosophy at Bonn, Jena and Berlin.' },
                { claim: 'International Institute of Agriculture in Rome', locator: 'Early life', excerpt: 'In 1911 Hermes was appointed director of the agricultural department of the International Institute of Agriculture in Rome.' },
                { claim: 'Centre Party; Minister of Food 1920', locator: 'Weimar Republic', excerpt: 'He joined the Catholic Zentrum. In the first Müller cabinet Hermes became Reichsernährungsminister (Minister for Nutrition/Food) in March 1920.' },
                { claim: 'Minister of Finance until August 1923', locator: 'Weimar Republic', excerpt: 'He stayed in that office until the resignation of the cabinet of Wilhelm Cuno in August 1923.' },
                { claim: 'Arrested and sentenced in 1933', locator: 'Nazi Germany', excerpt: 'He was arrested, charged and, on 12 July, sentenced to four months in prison for his opposition to the Nazis.' },
                { claim: 'Adviser to the government of Colombia', locator: 'Nazi Germany', excerpt: 'There he worked as an economic advisor to the government in Bogotá from 1936 to 1939.' },
                { claim: 'Contacts with Goerdeler and the Kreisau Circle', locator: 'Nazi Germany', excerpt: 'From 1942, Hermes was in touch with members of the resistance like Carl Friedrich Goerdeler and the Kreisau Circle.' },
                { claim: 'Sentenced to death January 1945', locator: 'Nazi Germany', excerpt: 'Immediately after 20 July 1944 he was arrested and on 11 January 1945 sentenced to death' },
                { claim: 'Wife delayed execution until the Red Army took Berlin', locator: 'Nazi Germany', excerpt: 'However, his wife succeeded in delaying his execution until the Red Army occupied Berlin.' },
                { claim: 'First chairman of the CDU of Berlin and the Soviet zone', locator: 'Post-war', excerpt: 'On 26 June 1945 he was one of the founder-members and the first chairman of the Christlich-Demokratische Union (CDU) of Berlin and the Soviet-occupied zone.' },
                { claim: 'Forced out by SMAD over criticism of the land reform without compensation', source: S.deHermes, locator: 'Nachkriegszeit und Bonner Republik', excerpt: 'Im Dezember 1945 wurde er wegen seiner Kritik an der entschädigungslosen Bodenreform in der SBZ von der Sowjetischen Militäradministration zum Rücktritt als CDU-Vorsitzender gezwungen.' },
                { claim: 'Founded the German Farmers’ Association', locator: 'Post-war', excerpt: 'In 1948, he was elected president of the Deutscher Bauernverband, which he founded.' },
                { claim: 'Reunification, in opposition to Adenauer', locator: 'Post-war', excerpt: 'He founded the Gesellschaft für die Wiedervereinigung Deutschlands (Society for the Reunification of Germany) placing himself in opposition to the views of Konrad Adenauer.' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-germany', startYear: 1920, endYear: 1923, primary: true, claim: 'Reich Minister of Food, then Minister of Finance', source: S.deHermes, locator: 'Weimarer Republik', excerpt: 'Im darauffolgenden Jahr wurde er Reichsminister für Ernährung und Landwirtschaft, vom Oktober 1921 bis August 1923 leitete er das Reichsfinanzministerium.' },
            { functionId: 'political-leadership', affiliationId: 'party-german-cdu', startYear: 1945, endYear: 1945, claim: 'First chairman of the CDU of Berlin and the Soviet zone', locator: 'Post-war', excerpt: 'On 26 June 1945 he was one of the founder-members and the first chairman of the Christlich-Demokratische Union (CDU) of Berlin and the Soviet-occupied zone.' },
            { functionId: 'legislature', affiliationId: 'state-germany', startYear: 1928, endYear: 1933, claim: 'Member of the Reichstag for the Centre Party', locator: 'Weimar Republic', excerpt: 'In 1924 he was elected for the Zentrum to the Prussian Diet and in 1928 to the Reichstag.' },
        ],
        career: [
            ['1911–1914', '로마 국제농업연구소 부장', 'Department director at the International Institute of Agriculture, Rome'],
            ['1920', '독일 식량장관', 'Reich Minister of Food'],
            ['1922–1923', '독일 재무장관', 'Reich Minister of Finance'],
            ['1945', '나치 법정에서 사형 선고', 'Sentenced to death by a Nazi court'],
            ['1945', '소련 점령지구 기독교민주연합 의장, 12월 해임', 'Chairman of the CDU in the Soviet zone; deposed in December'],
            ['1948', '독일 농민연맹 의장', 'President of the German Farmers’ Association'],
        ],
    }),
    person({
        id: 'erich-gniffke', groupId: 'world-cold-war',
        given: ['에리히', 'Erich'], family: ['그니프케', 'Gniffke'], nativeName: 'Erich Gniffke', years: '1895–1964',
        citizenship: 'germany', origin: 'germany',
        epithet: ['동독 사회민주당을 재건하고 통합에 서명했으나 1948년 사회주의통일당을 탈당해 서쪽으로 간 조직가',
            'SPD organiser in the Soviet zone who signed the merger with the KPD, then left the SED in 1948 and fled west'],
        bio: ['엘빙의 조선소 노동자 집안에서 태어나 1913년 사회민주당에 들어갔고, 사무직 노조 간부로 브라운슈바이크에서 그로테볼과 함께 일했다. 나치 시기 사회민주당 저항 모임에 가담해 1938년 그로테볼과 함께 투옥되었다. 1945년 5월 그로테볼과 함께 베를린에서 사회민주당을 재건해 중앙위원회 위원이 되었고, 공산당과의 합의와 통합 선언에 사회민주당 쪽 첫 서명자로 이름을 올렸다. 1946년 사회주의통일당 중앙서기국원에 뽑혔으나 당의 스탈린화 속에 고립되었고, 1948년 9월 모든 직책에서 물러났다. 10월 「새로운 형태의 당」이 전체주의 독재로 이어질 것이라는 탈당 편지를 쓰고 서쪽으로 도피했다. 1964년 죽었다.',
            'The son of a shipyard worker in Elbing, he joined the SPD in 1913 and became a white-collar union official in Brunswick, where he worked closely with Otto Grotewohl. Under the Nazis he belonged to a Social Democratic resistance circle and was imprisoned with Grotewohl in 1938. In May 1945 he and Grotewohl rebuilt the SPD in Berlin; he sat on its Central Committee and was the first SPD signatory of the agreement with the KPD and of the unity declaration. Elected to the SED Central Secretariat in 1946, he was isolated as the party was Stalinised and in September 1948 was relieved of all functions. In October he wrote a letter of resignation warning that the “party of a new type” would lead to a totalitarian dictatorship, and fled to the West. He died in 1964.'],
        fate: ['natural', '심장마비', 'Heart attack'],
        aliases: { ko: [], en: [] },
        sources: [S.deGniffke],
        facts: {
            years: { claim: '1895–1964', locator: 'Einleitung', excerpt: 'Erich Walter Gniffke (* 14. Februar 1895 in Elbing; † 4. September 1964 in Bad Kissingen) war ein deutscher Politiker (SPD, SED).' },
            citizenship: { claim: 'German politician (SPD, SED)', locator: 'Einleitung', excerpt: 'war ein deutscher Politiker (SPD, SED)' },
            nationalOrigin: { claim: 'Born in West Prussia, son of a shipyard worker', locator: 'Biografie', excerpt: 'Erich Gniffke wurde in Westpreußen als Sohn eines Werftarbeiters geboren.' },
            bio: [
                { claim: 'Joined the SPD in 1913', locator: 'Biografie', excerpt: 'Als 18-Jähriger wurde er 1913 Mitglied der SPD.' },
                { claim: 'Union leader in Brunswick, close to Grotewohl', locator: 'Biografie', excerpt: '1929 wechselte er als Gewerkschaftsführer und Bezirksleiter nach Braunschweig.' },
                { claim: 'Worked closely with Grotewohl', locator: 'Biografie', excerpt: 'in dem er eng mit dem damaligen Vorsitzenden Otto Grotewohl zusammenarbeitete' },
                { claim: 'Social Democratic resistance; imprisoned with Grotewohl in 1938', locator: 'Biografie', excerpt: 'Gemeinsam mit diesem wurde er im August 1938 wieder im Rennelberg-Gefängnis inhaftiert.' },
                { claim: 'Rebuilt the SPD with Grotewohl in May 1945', locator: 'Biografie', excerpt: 'Unmittelbar nach der Befreiung vom Nationalsozialismus im Mai 1945 begann er gemeinsam mit Grotewohl in Berlin in der sowjetischen Besatzungszone mit dem Wiederaufbau der SPD.' },
                { claim: 'Member of the Central Committee', locator: 'Biografie', excerpt: 'Als sich der Gründerkreis im Juni als Zentralausschuss konstituierte, wurde er dort Mitglied.' },
                { claim: 'First SPD signatory of the agreements with the KPD', locator: 'Biografie', excerpt: 'stand jeweils seine Unterschrift als erste von Seiten der SPD' },
                { claim: 'Elected to the SED Central Secretariat', locator: 'Biografie', excerpt: 'Beim Vereinigungsparteitag am 21. und 22. April 1946 wurde Gniffke als eines von 14 Mitgliedern in das Zentralsekretariat der SED gewählt.' },
                { claim: 'Noticed the Stalinisation of the SED', locator: 'Biografie', excerpt: 'Während seiner Reisen in der SBZ bemerkte er schnell eine Stalinisierung der SED und dass Sozialdemokraten von Positionen entfernt wurden.' },
                { claim: 'Relieved of all functions 27 September 1948', locator: 'Biografie', excerpt: 'Am 27. September 1948 wurde er, mit Hinweis auf seine Arbeit im Volksrat, vom Zentralsekretariat aller Funktionen enthoben' },
                { claim: 'Resignation letter of 28 October 1948', locator: 'Biografie', excerpt: 'In dem Brief sah er voraus, dass die „Partei neuen Typus“ zur Vernichtung aller demokratischen Rechte und zu einer totalitären Diktatur führen werde.' },
                { claim: 'Fled to Frankfurt am Main', locator: 'Biografie', excerpt: 'Erich Gniffke flüchtete zuerst nach Frankfurt am Main.' },
                { claim: 'Died of a heart attack in 1964', locator: 'Biografie', excerpt: 'Er starb 1964 in Bad Kissingen an einem Herzinfarkt.' },
            ],
        },
        activities: [
            { functionId: 'organizing', affiliationId: 'party-german-spd', startYear: 1945, endYear: 1946, primary: true, claim: 'Organiser of the rebuilt SPD in the Soviet zone and member of its Central Committee', locator: 'Biografie', excerpt: 'Beim Aufbau der SPD spielte Gniffke wegen seines organisatorischen Talents eine wesentliche Rolle.' },
            { functionId: 'political-leadership', affiliationId: 'party-german-sed', startYear: 1946, endYear: 1948, claim: 'Member of the SED Central Secretariat', locator: 'Biografie', excerpt: 'Beim Vereinigungsparteitag am 21. und 22. April 1946 wurde Gniffke als eines von 14 Mitgliedern in das Zentralsekretariat der SED gewählt.' },
        ],
        career: [
            ['1913', '사회민주당 입당', 'Joined the SPD'],
            ['1938', '그로테볼과 함께 투옥', 'Imprisoned with Grotewohl'],
            ['1945', '사회민주당 중앙위원회 위원', 'Member of the SPD Central Committee'],
            ['1946', '사회주의통일당 중앙서기국원', 'Member of the SED Central Secretariat'],
            ['1948', '모든 직책에서 물러나고 탈당, 서쪽으로 도피', 'Relieved of all functions, left the SED and fled west'],
        ],
    }),
    person({
        id: 'erich-ollenhauer', groupId: 'world-cold-war',
        given: ['에리히', 'Erich'], family: ['올렌하우어', 'Ollenhauer'], nativeName: 'Erich Ollenhauer', years: '1901–1963',
        citizenship: 'germany', origin: 'germany',
        epithet: ['망명 사회민주당 간부로 돌아와 슈마허의 뒤를 이어 서독 사회민주당을 이끈 야당 지도자',
            'Exiled SPD functionary who succeeded Schumacher as SPD leader and leader of the West German opposition'],
        bio: ['마그데부르크에서 벽돌공의 아들로 태어나 1918년 사회민주당에 들어갔고, 사회주의 노동자 청년단을 이끌었다. 1933년 5월 당 집행부와 함께 프라하로 망명해 망명 사회민주당(소파데)을 꾸렸고, 파리와 리스본을 거쳐 런던에서 전쟁을 보냈다. 1946년 2월 귀국해 하노버의 슈마허 사무소에서 일했고, 그해 부의장이 되어 당 조직과 국제 관계를 맡았다. 1952년 슈마허가 죽자 당 의장, 원내대표, 야당 지도자가 되었다. 1953년과 1957년 총리 후보로 아데나워에게 졌고, 1959년 마르크스주의와 결별한 고데스베르크 강령을 뒷받침했다. 1963년 본에서 죽었다.',
            'Born in Magdeburg, the son of a bricklayer, he joined the SPD in 1918 and led the Socialist Workers’ Youth. In May 1933 he went into exile in Prague with the party executive, helped form the exiled SPD (Sopade), and by way of Paris and Lisbon spent the war in London. Returning in February 1946, he worked in Kurt Schumacher’s office in Hanover and that year became his deputy, running the party organisation and its international contacts. After Schumacher’s death in 1952 he became party chairman, parliamentary leader and leader of the opposition. He lost to Adenauer as candidate for chancellor in 1953 and 1957, and backed the 1959 Godesberg Programme, with which the SPD broke with Marxism. He died in Bonn in 1963.'],
        fate: ['natural', '폐색전증', 'Pulmonary embolism'],
        aliases: { ko: [], en: [] },
        sources: [S.ollenhauer, S.deOllenhauer],
        facts: {
            years: { claim: '1901–1963', locator: 'lead', excerpt: 'Erich Ollenhauer (27 March 1901 – 14 December 1963) was the leader of the Social Democratic Party of Germany (SPD) from 1952 until 1963.' },
            citizenship: { claim: 'German politician; SPD chairman and leader of the opposition', source: S.deOllenhauer, locator: 'Einleitung', excerpt: 'war ein deutscher Politiker. Er war von 1952 bis 1963 SPD-Parteivorsitzender und Fraktionsvorsitzender der SPD im Deutschen Bundestag und somit auch Oppositionsführer.' },
            nationalOrigin: { claim: 'Born in Magdeburg', locator: 'Early political career and exile', excerpt: 'Ollenhauer was born in Magdeburg' },
            bio: [
                { claim: 'Son of a bricklayer', source: S.deOllenhauer, locator: 'Familie und Ausbildung', excerpt: 'sein Vater Wilhelm war Maurer' },
                { claim: 'Joined the SPD in 1918', source: S.deOllenhauer, locator: 'Weimarer Republik', excerpt: 'Im Jahr 1918 trat Ollenhauer der SPD bei.' },
                { claim: 'Chairman of the Socialist Workers’ Youth from 1928', source: S.deOllenhauer, locator: 'Weimarer Republik', excerpt: 'Im Jahre 1928 übernahm er den Vorsitz und führte die SAJ als eine SPD-loyale Jugendorganisation.' },
                { claim: 'Exile in Prague; formed Sopade', source: S.deOllenhauer, locator: 'Zeit des Nationalsozialismus', excerpt: 'Dort bildeten sie mit Paul Hertz, Friedrich Stampfer und weiteren die SoPaDe.' },
                { claim: 'Via Lisbon to London', source: S.deOllenhauer, locator: 'Zeit des Nationalsozialismus', excerpt: 'Ein Jahr später gelangten die Ollenhauers nach London, wo sich die SoPaDe für die letzten Kriegsjahre eingerichtet hatte' },
                { claim: 'Returned February 1946; Schumacher’s office in Hanover', source: S.deOllenhauer, locator: 'Nachkriegszeit', excerpt: 'Ollenhauer kehrte im Februar 1946 nach Deutschland zurück. Er wurde Sekretär im SPD-Gründungsbüro von Kurt Schumacher in Hannover.' },
                { claim: 'Deputy leader in May 1946', locator: 'Early political career and exile', excerpt: 'In May the same year, he was voted deputy leader of the SPD, behind Kurt Schumacher.' },
                { claim: 'Took over Schumacher’s international contacts', source: S.deOllenhauer, locator: 'Nachkriegszeit', excerpt: 'übernahm dieser sämtliche internationalen Kontakte' },
                { claim: 'Party leader after Schumacher’s death in 1952', locator: 'Leadership of the SPD', excerpt: "After Schumacher's unexpected death in 1952, the SPD elected Ollenhauer as its leader." },
                { claim: 'Lost the 1953 and 1957 elections to Adenauer', locator: 'Leadership of the SPD', excerpt: "He ran as the SPD's candidate for Chancellor of Germany in the 1953 and 1957 German elections, both of which were lost to Konrad Adenauer's CDU." },
                { claim: 'Supported the Godesberg Programme, which broke with Marxism', source: S.deOllenhauer, locator: 'Nachkriegszeit', excerpt: 'Insbesondere sagte sich die SPD vom Marxismus los.' },
                { claim: 'Godesberg Programme backed by Ollenhauer', source: S.deOllenhauer, locator: 'Nachkriegszeit', excerpt: 'Das von den Reformern um Willy Brandt, Fritz Erler und Herbert Wehner forcierte und von Ollenhauer unterstützte Programm' },
                { claim: 'Died in Bonn of a pulmonary embolism', locator: 'Leadership of the SPD', excerpt: 'Ollenhauer died in Bonn on 14 December 1963 from pulmonary embolism.' },
            ],
        },
        activities: [
            { functionId: 'political-leadership', affiliationId: 'party-german-spd', startYear: 1952, endYear: 1963, primary: true, claim: 'SPD chairman', locator: 'lead', excerpt: 'Erich Ollenhauer (27 March 1901 – 14 December 1963) was the leader of the Social Democratic Party of Germany (SPD) from 1952 until 1963.' },
            { functionId: 'organizing', affiliationId: 'party-german-spd', startYear: 1946, endYear: 1952, claim: 'Deputy chairman under Schumacher, running party organisation', locator: 'lead', excerpt: 'He was a close ally of the chairman Kurt Schumacher, and worked on party organization.' },
            { functionId: 'legislature', affiliationId: 'state-germany', startYear: 1949, endYear: 1963, claim: 'Member of the Bundestag; leader of the opposition from 1952', locator: 'Early political career and exile', excerpt: 'Ollenhauer entered the Bundestag after the 1949 German federal elections.' },
        ],
        career: [
            ['1918', '사회민주당 입당', 'Joined the SPD'],
            ['1928', '사회주의 노동자 청년단 의장', 'Chairman of the Socialist Workers’ Youth'],
            ['1933', '프라하로 망명, 망명 사회민주당 집행부', 'Exile in Prague; member of the exiled SPD executive'],
            ['1946', '사회민주당 부의장', 'SPD deputy chairman'],
            ['1952–1963', '사회민주당 의장, 연방의회 야당 지도자', 'SPD chairman and leader of the opposition'],
        ],
    }),
    person({
        id: 'heinrich-rau', groupId: 'world-cold-war',
        given: ['하인리히', 'Heinrich'], family: ['라우', 'Rau'], nativeName: 'Heinrich Rau', years: '1899–1961',
        citizenship: 'east-germany', origin: 'germany',
        epithet: ['독일경제위원회 위원장으로 동독 정부의 전신을 이끌고 경제 정책을 맡은 공산주의자',
            'Communist who chaired the German Economic Commission, the forerunner of the GDR government, and led East German economic policy'],
        bio: ['슈투트가르트 근교 포이어바흐에서 태어나 보슈 공장의 금속 프레스공으로 일했고, 스파르타쿠스단과 독립사회민주당을 거쳐 1919년 공산당에 들어갔다. 1920년대 공산당 농업 정책을 이끌었다. 나치 집권 뒤 투옥되었다가 소련으로 망명했고, 스페인 내전에서 제11국제여단을 지휘했다. 프랑스에서 억류되어 1942년 게슈타포에 넘겨졌고, 마우트하우젠 수용소에서 해방을 맞았다. 1948년 3월 독일경제위원회 위원장이 되어 화폐개혁과 경제계획을 이끌었다. 동독 정치국원과 부총리, 국가계획위원회 위원장을 지냈고, 1953년 7월 정치국에서 울브리히트 교체를 권했으나 자리를 지켰다. 기계공업장관과 대외무역장관을 지내다 1961년 심장마비로 죽었다.',
            'Born in Feuerbach near Stuttgart, he worked as a metal presser at Bosch and passed through the Spartacists and the USPD into the KPD in 1919, becoming the party’s leading agricultural policy maker in the 1920s. Imprisoned after the Nazis came to power, he emigrated to the Soviet Union and in the Spanish Civil War commanded the XI International Brigade. Interned in France and handed to the Gestapo by Vichy in 1942, he was liberated at Mauthausen. In March 1948 he became chairman of the German Economic Commission (DWK), which carried out the eastern currency reform and the first plans. In the GDR he was a Politburo member, deputy prime minister and chairman of the State Planning Commission; at the Politburo session of 8 July 1953 he recommended replacing Ulbricht, yet kept his posts. Minister of Machine Construction and then of Foreign Trade, he died of a heart attack in 1961.'],
        fate: ['natural', '심장마비', 'Heart attack'],
        aliases: { ko: [], en: ['Heiner Rau'] },
        sources: [S.rau, S.deRau],
        facts: {
            years: { claim: '1899–1961', locator: 'lead', excerpt: 'Heinrich Gottlob "Heiner" Rau (2 April 1899 – 23 March 1961) was a German communist politician' },
            citizenship: { claim: 'Leading East German statesman', locator: 'lead', excerpt: 'and a leading East German statesman after World War II' },
            nationalOrigin: { claim: 'German communist born in Feuerbach near Stuttgart', locator: 'Early years until World War I', excerpt: 'Rau was born in Feuerbach, now a part of Stuttgart, in the German Kingdom of Württemberg' },
            bio: [
                { claim: 'Metal presser at Bosch', locator: 'Early years until World War I', excerpt: 'There he completed his training as metal presser and remained until autumn 1920' },
                { claim: 'Spartacists, USPD, KPD 1919', source: S.deRau, locator: 'Leben', excerpt: '1916 trat er der Spartakusgruppe, 1917 der USPD und 1919 der KPD bei.' },
                { claim: 'Leading KPD agricultural policy maker', locator: 'lead', excerpt: 'From 1920 onward, he was a leading agricultural policy maker of the Communist Party of Germany (KPD).' },
                { claim: 'Imprisoned, then exile in the USSR', locator: 'lead', excerpt: 'After his first imprisonment he emigrated in 1935 to the Soviet Union (USSR).' },
                { claim: 'Commander of the XI International Brigade', source: S.deRau, locator: 'Einleitung', excerpt: 'Im Spanischen Bürgerkrieg war er zeitweise Brigadekommandeur der XI. Internationalen Brigade.' },
                { claim: 'Handed to the Gestapo by Vichy in 1942', locator: 'lead', excerpt: 'In 1939, he was arrested in France, and was delivered by the Vichy regime back to Nazi Germany in 1942.' },
                { claim: 'Mauthausen camp uprising', locator: 'Imprisonment, International Brigades, World War II', excerpt: 'Afterwards he was sent to the Mauthausen Concentration Camp, where he remained until May 1945, when he participated in a camp rebellion as one of the organisers of a secret military camp organisation.' },
                { claim: 'DWK chairman from March 1948', locator: 'German Economic Commission', excerpt: 'In March 1948 Rau became chairman of the German Economic Commission (Deutsche Wirtschaftskommission or DWK), which during this period became the centralised administrative organisation for the Soviet Occupation Zone and the predecessor of the future East German government.' },
                { claim: 'Currency reform under Rau', locator: 'German Economic Commission', excerpt: 'the DWK under Rau\'s leadership, was forced to follow quickly with its own reform and issued an own currency too' },
                { claim: 'Half-year and two-year plans', locator: 'German Economic Commission', excerpt: 'It was followed by a likewise accepted two-year plan for 1949 and 1950.' },
                { claim: 'Politburo member and deputy prime minister from 1950', locator: '1949–1953', excerpt: 'in 1950 he became a full member of the Politburo as well as deputy chairman of the East German Council of Ministers' },
                { claim: 'Chairman of the State Planning Commission', locator: '1949–1953', excerpt: 'Between 1949 and 1950, Rau was Minister for Planning of the GDR and in 1950–1952 chairman of the National Planning Commission.' },
                { claim: 'Recommended replacing Ulbricht on 8 July 1953', locator: '1949–1953', excerpt: 'Rau made a recommendation that Ulbricht be replaced' },
                { claim: 'Kept most of his positions', locator: '1953–1961', excerpt: 'Unlike some other rebels in the leadership, Rau kept most of his positions.' },
                { claim: 'Minister of Foreign Trade 1955–1961', locator: 'Foreign trade and foreign policy', excerpt: 'Between 1955 and 1961 Rau served as Minister for Foreign Trade and Inter-German Trade.' },
                { claim: 'Died of a heart attack', locator: 'Death', excerpt: 'Rau, in poor health during his final years, died of a heart attack in East Berlin, in March 1961.' },
            ],
        },
        activities: [
            { functionId: 'economy', affiliationId: 'state-east-germany', startYear: 1948, endYear: 1961, primary: true, claim: 'DWK chairman, planning chief and economic minister', locator: 'lead', excerpt: 'He was a leading economic politician and diplomat of East Germany and led various ministries at different times.' },
            { functionId: 'political-leadership', affiliationId: 'party-german-sed', startYear: 1949, endYear: 1961, claim: 'SED Politburo candidate from 1949, full member from 1950', locator: '1949–1953', excerpt: 'Rau became a member of the newly established Central Committee of the SED and candidate member of its Politburo' },
            { functionId: 'military', affiliationId: 'spanish-republic', startYear: 1937, endYear: 1939, claim: 'Commissar, chief of staff and commander of the XI International Brigade', locator: 'Imprisonment, International Brigades, World War II', excerpt: 'he joined the XI International Brigade and participated in the civil war as political commissar, beginning in May 1937, then as chief of staff and finally commander of the brigade' },
            { functionId: 'agriculture', affiliationId: 'party-german-communist', startYear: 1920, endYear: 1933, claim: 'Head of the KPD Central Committee’s agricultural division', locator: 'Berlin', excerpt: 'In November 1920 Rau became a full-time party functionary and the secretary of the agricultural division of the Central Committee of the KPD in Berlin.' },
        ],
        career: [
            ['1919', '독일 공산당 입당', 'Joined the KPD'],
            ['1923', '공산당 중앙위원회 농업부장', 'Head of the KPD agricultural division'],
            ['1937–1938', '제11국제여단 지휘', 'Commander of the XI International Brigade'],
            ['1943–1945', '마우트하우젠 수용소', 'Mauthausen concentration camp'],
            ['1948–1949', '독일경제위원회 위원장', 'Chairman of the German Economic Commission'],
            ['1950–1961', '사회주의통일당 정치국원, 부총리', 'SED Politburo member; deputy prime minister'],
            ['1955–1961', '대외무역·독일내무역 장관', 'Minister of Foreign and Inter-German Trade'],
        ],
    }),
];
