// Person cards for the aftermath event (world-war-i-aftermath-1918-1923):
// Keynes, Cuno, Bauer, Curzon, İnönü, see lib.js person().
// Excerpts are verbatim from the cited pages.
const { person } = require('../baltic-1940-1953-20261002/lib');

const EN = t => 'https://en.wikipedia.org/wiki/' + encodeURI(t);
const S = {
    keynes: EN('John_Maynard_Keynes'),
    cuno: EN('Wilhelm_Cuno'),
    bauer: EN('Gustav_Bauer'),
    curzon: EN('George_Curzon,_1st_Marquess_Curzon_of_Kedleston'),
    inonu: EN('İsmet_İnönü'),
};

module.exports = [
    person({
        id: 'john-maynard-keynes', groupId: 'world-interwar',
        given: ['존 메이너드', 'John Maynard'], family: ['케인스', 'Keynes'], nativeName: 'John Maynard Keynes', years: '1883–1946',
        citizenship: 'uk', origin: 'uk',
        epithet: ['강화회의에 항의해 재무부를 떠나 배상의 해악을 경고한 영국 경제학자',
            'British economist who left the Treasury in protest at the peace treaty and warned of the damage reparations would do'],
        bio: ['케임브리지에서 태어나 킹스 칼리지에서 수학을 공부했다. 1915년 재무부에 들어가 연합국 간 신용 조건을 설계했다. 파리 강화회의에서는 독일의 배상액을 지불 능력을 넘지 않게 하려 했으나 고위 협상에서 대부분 밀려났고, 조약에 실망해 재무부를 떠났다. 1919년 『평화의 경제적 귀결』로 조약의 해악을 예측해 국제적 명성을 얻었다. 대공황 속에서 유효수요가 경제활동 수준을 정한다고 보고 재정·통화 정책으로 불황에 맞설 것을 주장했으며, 1936년 『일반이론』을 냈다. 1944년 브레턴우즈 협상에서 영국 대표단을 이끌었으나 미국안에 밀렸다. 1946년 심장마비로 죽었다.',
            'Born in Cambridge, he studied mathematics at King’s College. Entering the Treasury in 1915, he designed the terms of credit between Britain and its continental allies. At the Paris Peace Conference he tried to keep Germany’s reparations within its capacity to pay but was largely excluded from the high-level talks, and the treaty’s outcome led to his resignation from the Treasury. The Economic Consequences of the Peace (1919), predicting the treaty’s damaging effects, made him internationally famous. In the Depression he argued that aggregate demand determined the level of economic activity and called for fiscal and monetary policy against slumps, publishing The General Theory in 1936. He led the British delegation at Bretton Woods in 1944, where the American plan largely prevailed. He died of heart attacks in 1946.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: ['케인스 경'], en: ['Lord Keynes', 'John Maynard Keynes, 1st Baron Keynes'] },
        sources: [S.keynes],
        facts: {
            years: { claim: '1883–1946', locator: 'lead', excerpt: '5 June 1883 – 21 April 1946' },
            citizenship: { claim: 'English economist', locator: 'lead', excerpt: 'was an English economist' },
            nationalOrigin: { claim: 'Born in Cambridge, England', locator: 'Early life and education', excerpt: 'John Maynard Keynes was born in Cambridge, England, on 5 June 1883, to an upper-middle-class family.' },
            bio: [
                { claim: 'Mathematics at King’s College', locator: 'lead', excerpt: 'Keynes was educated at King\'s College at the University of Cambridge, where he graduated in 1904 with a B.A. in mathematics.' },
                { claim: 'Treasury from 1915; inter-Allied credit', locator: 'First World War', excerpt: 'In January 1915 Keynes took up an official government position at the Treasury. Among his responsibilities were the design of terms of credit between Britain and its continental allies during the war' },
                { claim: 'Sought to keep reparations payable', locator: 'Versailles peace conference', excerpt: 'Keynes\'s main interest had been in trying to prevent Germany\'s compensation payments being set so high it would traumatise innocent German people, damage the nation\'s ability to pay' },
                { claim: 'Excluded from the high-level talks', locator: 'Versailles peace conference', excerpt: 'were able to ensure that both Keynes himself and the Treasury were largely excluded from formal high-level talks concerning reparations' },
                { claim: 'Resigned from the Treasury', locator: 'Versailles peace conference', excerpt: 'the result of the conference was a treaty which disgusted Keynes both on moral and economic grounds and led to his resignation from the Treasury' },
                { claim: 'The Economic Consequences of the Peace', locator: 'Versailles peace conference', excerpt: 'Keynes\'s analysis on the predicted damaging effects of the treaty appeared in the highly influential book, The Economic Consequences of the Peace, published in 1919.' },
                { claim: 'International fame', locator: 'Versailles peace conference', excerpt: 'The Economic Consequences of the Peace gained Keynes international fame' },
                { claim: 'Aggregate demand and fiscal/monetary policy', locator: 'lead', excerpt: 'He argued that aggregate demand (total spending in the economy) determined the overall level of economic activity' },
                { claim: 'Fiscal and monetary policies against recessions', locator: 'lead', excerpt: 'Keynes advocated the use of fiscal and monetary policies to mitigate the adverse effects of economic recessions and depressions.' },
                { claim: 'General Theory 1936', locator: 'During the Great Depression', excerpt: 'Keynes\'s magnum opus, The General Theory of Employment, Interest and Money was published in 1936.' },
                { claim: 'Led the British delegation at Bretton Woods', locator: 'Second World War', excerpt: 'Keynes was heavily involved, as leader of the British delegation and chairman of the World Bank commission, in the mid-1944 negotiations that established the Bretton Woods system.' },
                { claim: 'American plan prevailed', locator: 'Second World War', excerpt: 'The US\'s greater negotiating strength, however, meant that the outcomes accorded more closely to the more conservative plans of Harry Dexter White.' },
                { claim: 'Died of heart attacks in 1946', locator: 'Death', excerpt: 'In 1946, Keynes suffered a series of heart attacks, which ultimately proved fatal.' },
            ],
        },
        activities: [
            { functionId: 'scholarship', affiliationId: 'state-uk', startYear: 1909, endYear: 1946, primary: true, claim: 'Economist whose writings founded Keynesian economics', locator: 'lead', excerpt: 'was an English economist whose writings are considered the basis for the school of thought known as Keynesian economics' },
            { functionId: 'economy', affiliationId: 'state-uk', startYear: 1915, endYear: 1919, claim: 'Treasury official in the First World War', locator: 'First World War', excerpt: 'In January 1915 Keynes took up an official government position at the Treasury.' },
            { functionId: 'diplomacy', affiliationId: 'state-uk', startYear: 1944, endYear: 1944, claim: 'Led the British delegation at Bretton Woods', locator: 'Second World War', excerpt: 'Keynes was heavily involved, as leader of the British delegation and chairman of the World Bank commission, in the mid-1944 negotiations that established the Bretton Woods system.' },
        ],
        career: [
            ['1915–1919', '재무부 관리', 'Treasury official'],
            ['1919', '파리 강화회의 재무부 대표, 사임', 'Treasury representative at the Paris Peace Conference; resigned'],
            ['1919', '『평화의 경제적 귀결』', 'The Economic Consequences of the Peace'],
            ['1936', '『고용, 이자 및 화폐의 일반이론』', 'The General Theory of Employment, Interest and Money'],
            ['1944', '브레턴우즈 회의 영국 대표단장', 'Head of the British delegation at Bretton Woods'],
        ],
    }),
    person({
        id: 'wilhelm-cuno', groupId: 'world-interwar',
        given: ['빌헬름', 'Wilhelm'], family: ['쿠노', 'Cuno'], nativeName: 'Wilhelm Cuno', years: '1876–1933',
        citizenship: 'germany', origin: 'germany',
        epithet: ['루르 점령에 소극적 저항으로 맞서다 초인플레이션 속에 물러난 무당파 총리',
            'Non-party chancellor who answered the Ruhr occupation with passive resistance and fell amid hyperinflation'],
        bio: ['튀링겐 줄의 관료 집안에서 태어나 법학을 공부했고, 재무부 관리로 1차 세계대전 초 독일의 식량 공급을 조직했다. 1917년 해운회사 함부르크-아메리카 노선에 들어가 사장이 되었다. 1922년 11월 의회 표결 없이 대통령령으로 바이마르 공화국 최초의 무당파 총리가 되어 「실무 내각」을 꾸렸다. 1923년 1월 프랑스·벨기에군이 루르를 점령하자 소극적 저항을 호소했고, 그 비용을 주로 돈을 찍어 대면서 초인플레이션이 시작되었다. 파업의 물결 속에 8월 사회민주당이 낸 불신임으로 물러났다. 1932년 히틀러의 경제 자문에 참여했고 1933년 1월 죽었다.',
            'Born to a civil servant’s family in Suhl, he studied law and, as a Treasury official, helped organise Germany’s food supply early in the First World War. In 1917 he joined the Hamburg America shipping line, which he went on to head. In November 1922 he was appointed chancellor by presidential decree without a Reichstag vote, the first Weimar chancellor who belonged to no party, and formed a “business ministry”. When French and Belgian troops occupied the Ruhr in January 1923 he called for passive resistance; paying for it, mostly by printing money, began the run-up to hyperinflation. Amid a wave of strikes his cabinet resigned in August in the face of a no-confidence vote initiated by the SPD. In 1932 he joined in advising Hitler on economics, and he died in January 1933.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: [], en: ['Wilhelm Carl Josef Cuno'] },
        sources: [S.cuno],
        facts: {
            years: { claim: '1876–1933', locator: 'lead', excerpt: '2 July 1876 – 3 January 1933' },
            citizenship: { claim: 'German businessman and politician', locator: 'lead', excerpt: 'was a German businessman and politician who was the chancellor of Germany from 1922 to 1923' },
            nationalOrigin: { claim: 'Born in Suhl to a civil servant', locator: 'Early life', excerpt: 'He was the son of the administrative civil servant August George Wilhelm Cuno' },
            bio: [
                { claim: 'Born in Suhl', locator: 'Early life', excerpt: 'Wilhelm Cuno was born on 2 July 1876 in Suhl' },
                { claim: 'Studied law', locator: 'Early life', excerpt: 'He studied law in Berlin and Heidelberg and was awarded a Juris Doctor.' },
                { claim: 'Treasury official; food supply in WWI', locator: 'lead', excerpt: 'Cuno helped organize Germany\'s food supply during the early years of World War I before he went to work for the Hamburg America shipping company in 1917' },
                { claim: 'Appointed by decree without a Reichstag vote', locator: 'Chancellor', excerpt: 'Cuno was appointed chancellor on 22 November 1922 by presidential decree and without a vote in the Reichstag. He was the first chancellor in the Weimar Republic who was not a member of a party.' },
                { claim: 'Business ministry', locator: 'lead', excerpt: 'he formed a "business ministry" made up primarily of men who were, like himself, political independents' },
                { claim: 'Passive resistance', locator: 'Chancellor', excerpt: 'The move, widely seen as illegal even outside Germany, caused the outraged Cuno government to call for passive resistance.' },
                { claim: 'Printing money began hyperinflation', locator: 'lead', excerpt: 'The payments, made possible primarily by printing money, began the runup to the German hyperinflation of 1923.' },
                { claim: 'Resigned in August 1923', locator: 'Chancellor', excerpt: 'A wave of strikes against the government began in August 1923. On 12 August 1923, Cuno and his cabinet resigned in the face of a vote of no-confidence initiated by the Social Democratic Party (SPD).' },
                { claim: 'Returned to HAPAG as director general', locator: 'Later life', excerpt: 'In 1926, he once again became its director general.' },
                { claim: 'Advised Hitler in 1932', locator: 'Later life', excerpt: 'In 1932, Cuno joined the industrialist Wilhelm Keppler to advise Adolf Hitler economically.' },
                { claim: 'Died January 1933', locator: 'Later life', excerpt: 'Cuno died suddenly on 3 January 1933 at Aumühle near Hamburg.' },
            ],
        },
        activities: [
            { functionId: 'political-leadership', affiliationId: 'state-germany', startYear: 1922, endYear: 1923, primary: true, claim: 'Chancellor of Germany 1922–1923', locator: 'lead', excerpt: 'was the chancellor of Germany from 1922 to 1923 for a total of 264 days' },
            { functionId: 'government', affiliationId: 'state-germany', startYear: 1907, endYear: 1916, claim: 'Treasury official; Imperial Grain Agency', locator: 'Early career', excerpt: 'Cuno was employed by the federal Treasury Department in 1907' },
            { functionId: 'industry', affiliationId: 'state-germany', startYear: 1917, endYear: 1933, claim: 'Hamburg America Line executive', locator: 'lead', excerpt: 'After his government resigned in August 1923, Cuno returned to the Hamburg America Line.' },
        ],
        career: [
            ['1915–1916', '제국 곡물청 책임자', 'Head of the Imperial Grain Agency'],
            ['1917', '함부르크-아메리카 노선 입사', 'Joined the Hamburg America Line'],
            ['1922–1923', '독일 총리', 'Chancellor of Germany'],
            ['1926', '함부르크-아메리카 노선 사장', 'Director general of the Hamburg America Line'],
        ],
    }),
    person({
        id: 'gustav-bauer', groupId: 'world-interwar',
        given: ['구스타프', 'Gustav'], family: ['바우어', 'Bauer'], nativeName: 'Gustav Bauer', years: '1870–1944',
        citizenship: 'germany', origin: 'germany',
        epithet: ['연합국의 최후통첩 아래 베르사유 조약을 받아들인 사회민주당 총리',
            'Social Democratic chancellor whose government accepted the Treaty of Versailles under an Allied ultimatum'],
        bio: ['동프로이센 다르케멘에서 태어나 변호사 사무원으로 일하다 사무직 노동조합을 세웠고, 1908~1918년 자유노동조합 총위원회 부의장을 지냈다. 1912년 사회민주당 제국의회 의원이 되었고 1918년 10월 막스 폰 바덴 내각의 노동장관이 되었다. 1919년 6월 샤이데만이 베르사유 조약에 항의해 사임하자, 조약을 비판해 왔으면서도 후임 총리를 맡아 조약 비준을 이끌었다. 재정 개혁과 사회보험 확대를 펼쳤으나, 1920년 3월 카프 폭동 때 반란군과 협상한 일로 정부가 물러났다. 뒤에 부총리 겸 재무장관을 지냈고, 바르마트 부패 사건으로 1925년 의원직을 내놓았다. 1944년 베를린에서 죽었다.',
            'Born in Darkehmen in the Province of Prussia, he worked as a lawyer’s clerk, co-founded the office employees’ union and was second chairman of the General Commission of Trade Unions from 1908 to 1918. Elected to the Reichstag for the SPD in 1912, he became labour secretary in Max von Baden’s cabinet in October 1918. When Scheidemann resigned in protest at the Treaty of Versailles in June 1919, Bauer, until then a vocal critic of the treaty, succeeded him and got it through the National Assembly. His government carried out tax reform and extended social insurance, but was forced out in March 1920 over the negotiations conducted with the Kapp putschists. He was later vice-chancellor and treasury minister, and the Barmat corruption scandal cost him his seat in 1925. He died in Berlin in 1944.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: [], en: ['Gustav Adolf Bauer'] },
        sources: [S.bauer],
        facts: {
            years: { claim: '1870–1944', locator: 'lead', excerpt: '6 January 1870 – 16 September 1944' },
            citizenship: { claim: 'German SPD leader and chancellor', locator: 'lead', excerpt: 'was a German Social Democratic Party leader and the chancellor of Germany from June 1919 to March 1920' },
            nationalOrigin: { claim: 'Born in Darkehmen, Province of Prussia', locator: 'Early life', excerpt: 'Bauer was born on 6 January 1870 in Darkehmen, near Königsberg in the Province of Prussia' },
            bio: [
                { claim: 'Lawyer’s clerk', locator: 'Early life', excerpt: 'he worked as an office assistant and then as head clerk for a lawyer at Königsberg' },
                { claim: 'Co-founded office employees’ union', locator: 'Early life', excerpt: 'In 1895, he became president of the Union of Office Employees of Germany, a white-collar union that he co-founded.' },
                { claim: 'Second chairman of the General Commission 1908–1918', locator: 'Early life', excerpt: 'In 1908, Bauer became the second chairman of the General Commission of Trade Unions in Berlin, a position he held until 1918.' },
                { claim: 'Reichstag 1912; labour secretary October 1918', locator: 'Imperial Germany and the revolutionary period', excerpt: 'In 1912, Bauer was elected to the Reichstag for the Social Democratic Party of Germany (SPD)' },
                { claim: 'Labour secretary in Max von Baden’s cabinet', locator: 'Imperial Germany and the revolutionary period', excerpt: 'In October 1918, he became state secretary (similar to a minister) in the Ministry of Labour in the cabinet of Max von Baden' },
                { claim: 'Succeeded Scheidemann despite criticising the treaty', locator: 'Chancellor', excerpt: 'Bauer accepted the position on 20 June, even though he had until then been a vocal critic of the Treaty.' },
                { claim: 'Got the treaty through the Assembly', locator: 'Chancellor', excerpt: 'The National Assembly approved the Treaty 237 to 138 on 23 June, and representatives of Bauer\'s government signed it on 28 June.' },
                { claim: 'Tax reform and social benefits', locator: 'Chancellor', excerpt: 'The Bauer cabinet was also responsible for a number of extensions of social benefits.' },
                { claim: 'Forced out after Kapp Putsch negotiations', locator: 'Chancellor', excerpt: 'the Bauer government was forced to resign on 27 March, mostly as a result of the negotiations conducted with Kapp and his fellow conspirators' },
                { claim: 'Vice-chancellor and treasury minister', locator: 'Post-chancellorship', excerpt: 'Bauer rejoined the government in the cabinet of Joseph Wirth (Centre Party) in May 1921 as minister of the treasury and vice-chancellor.' },
                { claim: 'Barmat scandal; lost seat 1925', locator: 'lead', excerpt: 'In 1925, he was forced to resign his seat in the Reichstag due to his involvement in the fraud and bribery of the Barmat scandal.' },
                { claim: 'Died 1944 in Berlin', locator: 'Later life', excerpt: 'Bauer died in Hermsdorf (Berlin Reinickendorf) on 16 September 1944.' },
            ],
        },
        activities: [
            { functionId: 'political-leadership', affiliationId: 'state-germany', startYear: 1919, endYear: 1920, primary: true, claim: 'Chancellor June 1919–March 1920', locator: 'lead', excerpt: 'the chancellor of Germany from June 1919 to March 1920' },
            { functionId: 'organizing', affiliationId: 'party-german-spd', startYear: 1895, endYear: 1918, claim: 'Trade union leader', locator: 'Early life', excerpt: 'In 1908, Bauer became the second chairman of the General Commission of Trade Unions in Berlin, a position he held until 1918.' },
            { functionId: 'legislature', affiliationId: 'party-german-spd', startYear: 1912, endYear: 1928, claim: 'SPD Reichstag deputy', locator: 'Imperial Germany and the revolutionary period', excerpt: 'In 1912, Bauer was elected to the Reichstag for the Social Democratic Party of Germany (SPD)' },
            { functionId: 'government', affiliationId: 'state-germany', startYear: 1921, endYear: 1922, claim: 'Vice-chancellor and treasury minister', locator: 'Post-chancellorship', excerpt: 'Bauer rejoined the government in the cabinet of Joseph Wirth (Centre Party) in May 1921 as minister of the treasury and vice-chancellor.' },
        ],
        career: [
            ['1908–1918', '노동조합 총위원회 부의장', 'Second chairman of the General Commission of Trade Unions'],
            ['1912', '제국의회 의원(사회민주당)', 'Reichstag deputy (SPD)'],
            ['1918', '노동장관', 'Labour secretary'],
            ['1919–1920', '독일 총리', 'Chancellor of Germany'],
            ['1921–1922', '부총리 겸 재무장관', 'Vice-chancellor and treasury minister'],
        ],
    }),
    person({
        id: 'george-curzon', groupId: 'world-interwar',
        given: ['조지', 'George'], family: ['커즌', 'Curzon'], nativeName: 'George Nathaniel Curzon', years: '1859–1925',
        citizenship: 'uk', origin: 'uk',
        epithet: ['인도 총독을 지내고 외무장관으로 커즌선과 로잔 조약 협상을 이끈 보수당 정치가',
            'Conservative viceroy of India and foreign secretary who gave his name to the Curzon Line and led the Allies at Lausanne'],
        bio: ['더비셔의 귀족 집안에서 태어나 이튼과 옥스퍼드를 거쳐 1885년 하원에 들어갔고, 러시아의 인도 위협을 경고하는 여행기를 썼다. 1899~1905년 인도 총독으로 행정 개혁을 폈지만, 1905년 벵골 분할로 민족주의를 갈라놓으려 했다는 비판을 받았고 재임 중 대기근이 겹쳤다. 1차 세계대전 중 로이드 조지의 전시 내각에 들어갔고, 1919년 10월 외무장관이 되어 소련-폴란드 경계안인 커즌선에 이름을 남겼다. 세브르 조약을 설계했고, 1922년 로잔 회의에서 연합국 수석 협상자로 튀르키예의 국경을 정했다. 1923년 총리 자리를 놓쳤고 1925년 죽었다.',
            'Born into an aristocratic Derbyshire family and educated at Eton and Oxford, he entered Parliament in 1885 and wrote travel books warning of a Russian threat to India. As Viceroy of India from 1899 to 1905 he pursued administrative reform, but his 1905 partition of Bengal was criticised as an attempt to divide Bengali nationalism, and a major famine coincided with his tenure. In the First World War he served in Lloyd George’s war cabinet; appointed Foreign Secretary in October 1919, he gave his name to the proposed Soviet-Polish boundary, the Curzon Line. He designed the Treaty of Sèvres and, as chief Allied negotiator at Lausanne in 1922, settled the borders of Turkey. Passed over for prime minister in 1923, he died in 1925.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: ['커즌 경'], en: ['Lord Curzon', 'Marquess Curzon', 'George Nathaniel Curzon'] },
        linkExpressions: [['ko', '커즌 경'], ['en', 'Lord Curzon']],
        sources: [S.curzon],
        facts: {
            years: { claim: '1859–1925', locator: 'lead', excerpt: '11 January 1859 – 20 March 1925' },
            citizenship: { claim: 'British statesman', locator: 'lead', excerpt: 'was a British statesman, Conservative politician, explorer and writer who served as Viceroy of India from 1899 to 1905 and Foreign Secretary from 1919 to 1924' },
            nationalOrigin: { claim: 'Aristocratic family in Derbyshire', locator: 'lead', excerpt: 'Curzon was born in Derbyshire into an aristocratic family and educated at Eton College and Balliol College, Oxford, before entering Parliament in 1885.' },
            bio: [
                { claim: 'Travel books on the Russian threat', locator: 'lead', excerpt: 'underlined the perceived Russian threat to British control of India' },
                { claim: 'Viceroy 1899', locator: 'Viceroy of India (1899–1905)', excerpt: 'In January 1899 Curzon was appointed as Viceroy of India.' },
                { claim: 'Administrative commissions', locator: 'Indian reform', excerpt: 'Within India, Curzon appointed a number of commissions to inquire into education, irrigation, police and other branches of administration' },
                { claim: 'Partition of Bengal to weaken nationalism', locator: 'Indian reform', excerpt: 'his intention was to divide Bengalis into religious and territorial grounds to weaken the growing nationalism' },
                { claim: 'Famine during his tenure', locator: 'Indian famine', excerpt: 'A major famine coincided with Curzon\'s time as viceroy in which 1 to 4.5 million people died.' },
                { claim: 'War cabinet of Lloyd George', locator: 'lead', excerpt: 'from late 1916 he was Leader of the House of Lords and served in the war cabinet of Prime Minister David Lloyd George' },
                { claim: 'Foreign Secretary; Curzon Line', locator: 'Policy under Lloyd George', excerpt: 'Curzon was appointed Foreign Secretary in October 1919. He gave his name to the British government\'s proposed Soviet-Polish boundary, the Curzon Line of December 1919.' },
                { claim: 'Designed the Treaty of Sèvres', locator: 'Policy under Lloyd George', excerpt: 'He designed the Treaty of Sèvres (10 August 1920) between the victorious Allies and the Ottoman Empire.' },
                { claim: 'Chief negotiator at Lausanne', locator: 'Policy under Lloyd George', excerpt: 'In 1922, he was the chief negotiator for the Allies of the Treaty of Lausanne, which officially ended the war with the Ottoman Empire and defined the borders of Turkey.' },
                { claim: 'Passed over for premiership 1923', locator: 'lead', excerpt: 'On Bonar Law\'s retirement as prime minister in 1923, Curzon was a contender for the office but was passed over in favour of Stanley Baldwin.' },
                { claim: 'Died 1925', locator: 'Death', excerpt: 'he died in London on 20 March 1925 at the age of 66' },
            ],
        },
        activities: [
            { functionId: 'diplomacy', affiliationId: 'state-uk', startYear: 1919, endYear: 1924, primary: true, claim: 'Foreign Secretary 1919–1924', locator: 'lead', excerpt: 'Foreign Secretary from 1919 to 1924' },
            { functionId: 'government', affiliationId: 'state-uk', startYear: 1899, endYear: 1905, claim: 'Viceroy of India', locator: 'lead', excerpt: 'served as Viceroy of India from 1899 to 1905' },
            { functionId: 'political-leadership', affiliationId: 'party-british-conservative', startYear: 1885, endYear: 1925, claim: 'Conservative politician', locator: 'lead', excerpt: 'was a British statesman, Conservative politician, explorer and writer' },
        ],
        career: [
            ['1885', '하원 의원', 'Member of Parliament'],
            ['1899–1905', '인도 총독', 'Viceroy of India'],
            ['1916', '전시 내각, 상원 원내대표', 'War cabinet; Leader of the House of Lords'],
            ['1919–1924', '외무장관', 'Foreign Secretary'],
            ['1922–1923', '로잔 회의 연합국 수석 협상자', 'Chief Allied negotiator at Lausanne'],
        ],
    }),
    person({
        id: 'ismet-inonu', groupId: 'world-interwar',
        given: ['이스메트', 'İsmet'], family: ['이뇌뉘', 'İnönü'], nativeName: 'İsmet İnönü', years: '1884–1973',
        citizenship: 'turkey', origin: null,
        epithet: ['로잔 조약을 협상하고 아타튀르크 뒤 튀르키예 2대 대통령이 된 군인·정치가',
            'Officer who negotiated the Treaty of Lausanne and succeeded Atatürk as Turkey’s second president'],
        bio: ['스미르나에서 태어난 오스만 장교로, 독립전쟁에서 대국민의회군 참모총장과 서부전선 사령관으로 1·2차 이뇌뉘 전투를 이겼다. 1922~1923년 로잔 회의의 튀르키예 수석 협상자로 커즌에 맞서며 세브르 조약을 로잔 조약으로 대체했다. 아타튀르크 아래 오래 총리를 지내며 세속화 개혁을 집행했고, 셰이크 사이드 반란 뒤 쿠르드인의 튀르크화를 밀어붙였으며 데르심 학살의 책임자로도 꼽힌다. 1938년 2대 대통령이 되어 「국가 지도자」 칭호를 받았고, 2차 세계대전에서 무장 중립을 지켰다. 1950년 선거 패배로 평화적으로 정권을 넘겼다. 1973년 죽었다.',
            'Born in Smyrna, an Ottoman officer, he won the First and Second Battles of İnönü in the War of Independence as chief of the General Staff and commander of the Western Front. As Turkey’s chief negotiator at Lausanne in 1922–1923 he faced down Curzon and replaced the Treaty of Sèvres with the Treaty of Lausanne. As prime minister for most of Atatürk’s presidency he carried out the secularising reforms; after the Sheikh Said revolt he pushed the Turkification of the Kurds, and he is considered one of those responsible for the Dersim massacre. Elected second president in 1938, he took the title “National Chief” and kept Turkey in armed neutrality in the Second World War. After defeat in the 1950 election he handed over power peacefully. He died in 1973.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: ['이스메트 파샤'], en: ['İsmet Pasha', 'Ismet Inonu', 'Mustafa İsmet İnönü'] },
        sources: [S.inonu],
        facts: {
            years: { claim: '1884–1973', locator: 'lead', excerpt: '24 September 1884 – 25 December 1973' },
            citizenship: { claim: 'Turkish politician and officer', locator: 'lead', excerpt: 'was a Turkish politician and military officer who served as the president of Turkey from 1938 to 1950' },
            bio: [
                { claim: 'Born in Smyrna', locator: 'Early life', excerpt: 'was born in 1884 in Smyrna (İzmir)' },
                { claim: 'Chief of General Staff; İnönü battles', locator: 'lead', excerpt: 'he served as the first chief of the General Staff from 1922 to 1924 for the regular Turkish army, during which he commanded forces during the First and Second Battles of İnönü' },
                { claim: 'Commander of the Western Front', locator: 'Turkish War of Independence', excerpt: 'he was appointed commander of the Western Front of the Army of the GNA' },
                { claim: 'Chief negotiator at Lausanne', locator: 'lead', excerpt: 'He secured recognition of the Turkish victory by the Allies and replacing the imposed Treaty of Sèvres with the Treaty of Lausanne.' },
                { claim: 'Faced down Curzon', locator: 'Chief negotiator in Mudanya and Lausanne', excerpt: 'After delivering his position, İsmet turned off his hearing aid during the speeches of British foreign secretary Lord Curzon.' },
                { claim: 'Executed Atatürk’s reforms as prime minister', locator: 'lead', excerpt: 'As prime minister for most of Atatürk\'s presidency, İnönü executed many of Atatürk\'s modernizing and nationalist reforms.' },
                { claim: 'Turkification after Sheikh Said', locator: 'Nationalist policy', excerpt: 'While dealing with the Sheikh Said revolt, İnönü proclaimed a Turkish nationalist policy and encouraged the Turkification of the non-Turkish population.' },
                { claim: 'Dersim massacre', locator: 'Nationalist policy', excerpt: 'İnönü is also considered one of the perpetrators of the Dersim massacre' },
                { claim: 'Second president; National Chief', locator: 'Prewar', excerpt: 'was unanimously elected the second president of the Republic of Turkey' },
                { claim: 'National Chief title', locator: 'lead', excerpt: 'was granted the official title of Millî Şef ("National Chief") by the parliament' },
                { claim: 'Armed neutrality', locator: 'lead', excerpt: 'Turkey was able to maintain an armed neutrality during World War II' },
                { claim: 'Peaceful transfer 1950', locator: 'lead', excerpt: '1950 saw a peaceful transfer of power to the Democrats when the CHP suffered defeat in the elections.' },
                { claim: 'Died 1973', locator: 'Death', excerpt: 'On 25 December 1973, İsmet İnönü died of a heart attack at the age of 89.' },
            ],
        },
        activities: [
            { functionId: 'political-leadership', affiliationId: 'state-turkey', startYear: 1938, endYear: 1950, primary: true, claim: 'President of Turkey 1938–1950', locator: 'lead', excerpt: 'served as the president of Turkey from 1938 to 1950' },
            { functionId: 'military', affiliationId: 'state-turkey', startYear: 1920, endYear: 1924, claim: 'Chief of the General Staff; İnönü battles', locator: 'lead', excerpt: 'he served as the first chief of the General Staff from 1922 to 1924 for the regular Turkish army, during which he commanded forces during the First and Second Battles of İnönü' },
            { functionId: 'diplomacy', affiliationId: 'state-turkey', startYear: 1922, endYear: 1923, claim: 'Chief negotiator at Lausanne', locator: 'Chief negotiator in Mudanya and Lausanne', excerpt: 'İnönü was appointed as the chief negotiator of the Turkish delegation, both for the Armistice of Mudanya and for the Treaty of Lausanne.' },
            { functionId: 'government', affiliationId: 'state-turkey', startYear: 1923, endYear: 1965, claim: 'Prime minister three times', locator: 'lead', excerpt: 'as its prime minister three times: from 1923 to 1924, 1925 to 1937, and 1961 to 1965' },
        ],
        career: [
            ['1921', '1·2차 이뇌뉘 전투', 'First and Second Battles of İnönü'],
            ['1922–1923', '로잔 회의 튀르키예 수석 협상자', 'Chief Turkish negotiator at Lausanne'],
            ['1923–1937', '총리(두 차례)', 'Prime minister (twice)'],
            ['1938–1950', '튀르키예 대통령', 'President of Turkey'],
            ['1961–1965', '총리', 'Prime minister'],
        ],
    }),
];
