// Person cards for the First World War and aftermath events (the Big Three
// besides Clemenceau, Renner and Stresemann), see lib.js person(). Excerpts are
// verbatim from the cited pages.
const { W, person } = require('../baltic-1940-1953-20261002/lib');

const E = t => W(encodeURI(t));
const S = {
    wilson: E('Woodrow_Wilson'),
    lloydGeorge: E('David_Lloyd_George'),
    orlando: E('Vittorio_Emanuele_Orlando'),
    renner: E('Karl_Renner'),
    stresemann: E('Gustav_Stresemann'),
};

module.exports = [
    person({
        id: 'woodrow-wilson', groupId: 'world-interwar',
        given: ['우드로', 'Woodrow'], family: ['윌슨', 'Wilson'], nativeName: 'Woodrow Wilson', years: '1856–1924',
        citizenship: 'usa', origin: 'usa',
        epithet: ['14개조와 국제연맹을 내걸었으나 상원 비준을 얻지 못한 미국 대통령',
            'US president whose Fourteen Points and League of Nations failed to win the Senate’s ratification'],
        bio: ['버지니아에서 태어나 프린스턴 대학교 총장과 뉴저지 주지사를 거쳐 1912년 대통령이 되었고, 취임 첫해 연방 관료 조직에 인종 분리를 들여왔다. 1917년 4월 독일의 무제한 잠수함전을 이유로 참전을 요청했고, 1918년 1월 14개조로 국제연맹과 민족자결의 구상을 내놓았다. 파리 강화회의에서 연맹 규약 기초를 이끌었지만 연맹을 위해 독일에 대한 여러 요구를 양보했다. 1919년 10월 뇌졸중으로 쓰러졌고 타협을 거부해 상원의 조약 비준이 무산되었다. 같은 시기 파머 습격의 「적색 공포」가 벌어졌다. 1919년 노벨 평화상을 받았고 1924년 죽었다.',
            'Born in Virginia, he was president of Princeton University and governor of New Jersey before winning the presidency in 1912, and in his first year imposed racial segregation across the federal bureaucracy. In April 1917 he asked Congress to declare war over unrestricted submarine warfare, and in January 1918 set out the Fourteen Points, with a League of Nations and self-determination. At the Paris Peace Conference he presided over the drafting of the League Covenant but conceded much to the other powers to get it. A stroke in October 1919 incapacitated him, and his refusal of a compromise sank the Senate’s ratification of the treaty. The Palmer Raids of the Red Scare came in the same years. He received the 1919 Nobel Peace Prize and died in 1924.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: ['토머스 우드로 윌슨'], en: ['Thomas Woodrow Wilson'] },
        sources: [S.wilson],
        facts: {
            years: { claim: '1856–1924', locator: 'lead', excerpt: 'Thomas Woodrow Wilson (December 28, 1856 – February 3, 1924) was the 28th president of the United States' },
            citizenship: { claim: '28th president of the United States', locator: 'lead', excerpt: 'was the 28th president of the United States, serving from 1913 to 1921' },
            nationalOrigin: { claim: 'born in Virginia, grew up in the American South', locator: 'lead', excerpt: 'Born in Staunton, Virginia, Wilson grew up in the Southern United States during the American Civil War and Reconstruction era.' },
            bio: [
                { claim: 'PhD at Johns Hopkins; president of Princeton', locator: 'lead', excerpt: 'After earning a PhD in history and political science from Johns Hopkins University, Wilson taught at several colleges prior to being appointed president of Princeton University' },
                { claim: 'governor of New Jersey 1911–1913', locator: 'lead', excerpt: 'Wilson served as the governor of New Jersey from 1911 to 1913' },
                { claim: 'segregation of the federal bureaucracy', locator: 'lead', excerpt: 'During his first year as president, Wilson authorized the widespread imposition of racial segregation inside the federal bureaucracy' },
                { claim: 'asked for war in April 1917 over submarine warfare', locator: 'lead', excerpt: 'In April 1917, Wilson asked Congress for a declaration of war against Germany in response to its policy of unrestricted submarine warfare that sank American merchant ships.' },
                { claim: 'Fourteen Points of 8 January 1918', locator: 'Fourteen Points', excerpt: 'On January 8, 1918, Wilson delivered a speech, known as the Fourteen Points, wherein he articulated his administration\'s long term war objectives.' },
                { claim: 'League, Poland, self-determination', locator: 'Fourteen Points', excerpt: 'Other points included the evacuation of occupied territory, the establishment of an independent Poland, and self-determination for the peoples of Austria-Hungary and the Ottoman Empire.' },
                { claim: 'chaired the Covenant committee', locator: 'Paris Peace Conference', excerpt: 'Wilson himself presided over the committee that drafted the Covenant of the League of Nations.' },
                { claim: 'conceded points for the League', locator: 'Paris Peace Conference', excerpt: 'However, in pursuit of his League of Nations, Wilson conceded several points to the other powers present at the conference. Germany was required to permanently cede territory, pay war reparations, relinquish all of her overseas colonies and dependencies and submit to military occupation in the Rhineland.' },
                { claim: 'stroke in October 1919', locator: 'Health collapses', excerpt: 'On October 2, 1919, Wilson suffered a serious stroke, leaving him paralyzed on his left side' },
                { claim: 'forced the Nay vote of 19 March 1920', locator: 'Ratification debate and defeat', excerpt: 'Wilson forced his supporters to vote Nay on March 19, 1920, thereby closing the issue.' },
                { claim: 'Palmer Raids, over 10,000 arrested', locator: 'Red Scare and Palmer Raids', excerpt: 'Attorney General Palmer from November 1919 to January 1920 launched the Palmer Raids to suppress radical organizations. Over 10,000 people were arrested and 556 aliens were deported, including Emma Goldman.' },
                { claim: '1919 Nobel Peace Prize', locator: 'Paris Peace Conference', excerpt: 'For his efforts towards creating a lasting world peace, Wilson was awarded the 1919 Nobel Peace Prize.' },
                { claim: 'died February 1924', locator: 'Post-presidency and death (1921–1924)', excerpt: 'He died on February 3, 1924, at the age of 67.' },
            ],
        },
        activities: [
            { functionId: 'political-leadership', affiliationId: 'state-usa', startYear: 1913, endYear: 1921, primary: true, claim: '28th president of the United States', locator: 'lead', excerpt: 'was the 28th president of the United States, serving from 1913 to 1921' },
            { functionId: 'diplomacy', affiliationId: 'state-usa', startYear: 1919, endYear: 1919, claim: 'attended the Paris Peace Conference and advocated the League of Nations', locator: 'lead', excerpt: 'After the Allied victory in November 1918, Wilson attended the Paris Peace Conference. Wilson successfully advocated for the establishment of a multinational organization, the League of Nations' },
            { functionId: 'government', affiliationId: 'state-usa', startYear: 1911, endYear: 1913, claim: 'governor of New Jersey', locator: 'lead', excerpt: 'Wilson served as the governor of New Jersey from 1911 to 1913' },
        ],
        career: [
            ['1902–1910', '프린스턴 대학교 총장', 'President of Princeton University'],
            ['1911–1913', '뉴저지 주지사', 'Governor of New Jersey'],
            ['1913–1921', '미국 대통령', 'President of the United States'],
            ['1918', '14개조 발표', 'Announced the Fourteen Points'],
            ['1919', '파리 강화회의, 국제연맹 규약 기초 위원회 의장', 'Paris Peace Conference; chaired the League Covenant committee'],
        ],
    }),
    person({
        id: 'david-lloyd-george', groupId: 'world-interwar',
        given: ['데이비드', 'David'], family: ['로이드 조지', 'Lloyd George'], nativeName: 'David Lloyd George', years: '1863–1945',
        citizenship: 'uk', origin: { code: 'uk', label: { ko: '웨일스', en: 'Wales' } },
        epithet: ['대전 후반 영국을 이끌고 강화회의에서 독일에 대한 온건론을 편 자유당 총리',
            'Liberal prime minister who led Britain in the later war and argued for moderation towards Germany at the peace conference'],
        bio: ['맨체스터의 웨일스인 집안에서 태어나 급진 자유주의 웅변가로 이름을 얻었다. 재무장관으로 1909년 「인민 예산」과 국민보험법을 내 복지국가의 토대를 놓았다. 군수장관과 육군장관을 거쳐 1916년 12월 총리가 되었다. 파리 강화회의에서는 독일 경제를 무너뜨릴 막대한 배상에 반대하고 프랑스의 패권을 견제했다. 1921년 영국-소련 무역협정을 맺고 아일랜드 자유국 수립을 협상했으나 1922년 보수당이 연립에서 빠지자 사임했다. 1936년 히틀러를 만나 찬양하기도 했다. 1945년 죽었다.',
            'Born in Manchester to Welsh parents, he made his name as a radical Liberal orator. As chancellor of the exchequer he introduced the 1909 People’s Budget and the National Insurance Act, laying foundations of the welfare state. After serving as minister of munitions and secretary for war he became prime minister in December 1916. At the Paris Peace Conference he opposed reparations that would wreck the German economy and sought to check French dominance. In 1921 he concluded the Anglo-Soviet Trade Agreement and negotiated the creation of the Irish Free State, but resigned in 1922 when the Conservatives left the coalition. In 1936 he met Hitler and praised him. He died in 1945.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: [], en: ['1st Earl Lloyd-George of Dwyfor'] },
        sources: [S.lloydGeorge],
        facts: {
            years: { claim: '1863–1945', locator: 'lead', excerpt: 'David Lloyd George, 1st Earl Lloyd-George of Dwyfor (17 January 1863 – 26 March 1945)' },
            citizenship: { claim: 'Prime Minister of the United Kingdom 1916–1922', locator: 'lead', excerpt: 'was Prime Minister of the United Kingdom from 1916 to 1922' },
            nationalOrigin: [
                { claim: 'born to Welsh parents', locator: 'Early life', excerpt: 'to Welsh parents William George and Elizabeth Lloyd George' },
                { claim: 'Welsh as first language', locator: 'Early life', excerpt: 'He was raised with Welsh as his first language' },
            ],
            bio: [
                { claim: 'radical Liberal orator, Welsh devolution', locator: 'lead', excerpt: 'Lloyd George gained a reputation as an orator and proponent of a Welsh blend of radical Liberal ideas that included support for Welsh devolution, the disestablishment of the Church of England in Wales, equality for labourers and tenant farmers, and reform of land ownership.' },
                { claim: 'People\'s Budget 1909', locator: 'lead', excerpt: 'he proposed taxes on land ownership and high incomes in the 1909 People\'s Budget, which the Conservative-dominated House of Lords rejected' },
                { claim: 'welfare state', locator: 'lead', excerpt: 'His budget was enacted in 1910, with the National Insurance Act 1911 and other measures helping to establish the modern welfare state.' },
                { claim: 'Munitions, War, prime minister December 1916', locator: 'lead', excerpt: 'In 1915, Lloyd George became Minister of Munitions and expanded artillery shell production for the war. In 1916, he was appointed Secretary of State for War' },
                { claim: 'replaced Asquith; small war cabinet', locator: 'lead', excerpt: 'Asquith proved ineffective as prime minister and was replaced by Lloyd George in December 1916.  He centralised authority by creating a smaller war cabinet.' },
                { claim: 'clashed at Paris; opposed crushing reparations', locator: 'Paris 1919', excerpt: 'Lloyd George represented Britain at the Paris Peace Conference, clashing with French Prime Minister Georges Clemenceau, US President Woodrow Wilson, and Italian Prime Minister Vittorio Orlando.' },
                { claim: 'did not want to destroy the German economy', locator: 'Paris 1919', excerpt: 'He did not want to utterly destroy the German economy and political system—as Clemenceau demanded—with massive reparations.' },
                { claim: 'plebiscite in Upper Silesia', locator: 'Paris 1919', excerpt: 'Instead of handing over Upper Silesia (2,073,000 people), and the southern part of East Prussia (720,000 people) to Poland as was planned before, the plebiscite was organised.' },
                { claim: 'Anglo-Soviet Trade Agreement 1921', locator: 'Foreign policy crises', excerpt: 'In 1921, Lloyd George successfully concluded the Anglo-Soviet Trade Agreement.' },
                { claim: 'Irish Free State; resigned 1922', locator: 'lead', excerpt: 'which lasted until Lloyd George negotiated independence for the Irish Free State in 1921' },
                { claim: 'Carlton Club; resigned', locator: 'lead', excerpt: 'The Carlton Club meeting decided the Conservatives should end the coalition and contest the next election alone. Lloyd George resigned as prime minister' },
                { claim: 'pro-German after 1923', locator: 'Support for Nazi Germany', excerpt: 'Lloyd George was consistently pro-German after 1923, in part due to his growing conviction that Germany had been treated unfairly at Versailles.' },
                { claim: 'met Hitler 1936, "the greatest living German"', locator: 'Support for Nazi Germany', excerpt: 'In September 1936, he visited Germany to talk with Hitler. Hitler said he was pleased to have met "the man who won the war"; Lloyd George was moved, and called Hitler "the greatest living German".' },
                { claim: 'died of cancer March 1945', locator: 'Death', excerpt: 'Lloyd George died of cancer at the age of 82 on 26 March 1945' },
            ],
        },
        activities: [
            { functionId: 'political-leadership', affiliationId: 'state-uk', startYear: 1916, endYear: 1922, primary: true, claim: 'Prime Minister of the United Kingdom', locator: 'lead', excerpt: 'was Prime Minister of the United Kingdom from 1916 to 1922' },
            { functionId: 'economy', affiliationId: 'state-uk', startYear: 1908, endYear: 1915, claim: 'Chancellor of the Exchequer', locator: 'lead', excerpt: 'After H. H. Asquith succeeded to the premiership in 1908, Lloyd George replaced him as Chancellor of the Exchequer.' },
            { functionId: 'industry', affiliationId: 'state-uk', startYear: 1915, endYear: 1916, claim: 'Minister of Munitions', locator: 'lead', excerpt: 'In 1915, Lloyd George became Minister of Munitions and expanded artillery shell production for the war.' },
            { functionId: 'diplomacy', affiliationId: 'state-uk', startYear: 1919, endYear: 1919, claim: 'represented Britain at the Paris Peace Conference', locator: 'Paris 1919', excerpt: 'Lloyd George represented Britain at the Paris Peace Conference' },
            { functionId: 'legislature', affiliationId: 'state-uk', startYear: 1890, endYear: 1945, claim: 'MP for Caernarvon Boroughs for 55 years', locator: 'lead', excerpt: 'He won an 1890 by-election to become the Member of Parliament for Caernarvon Boroughs, and was continuously re-elected to the seat for 55 years.' },
        ],
        career: [
            ['1890', '하원의원(카나번 버러스)', 'MP for Caernarvon Boroughs'],
            ['1908–1915', '재무장관', 'Chancellor of the Exchequer'],
            ['1915–1916', '군수장관', 'Minister of Munitions'],
            ['1916', '육군장관', 'Secretary of State for War'],
            ['1916–1922', '영국 총리', 'Prime Minister of the United Kingdom'],
            ['1919', '파리 강화회의 영국 대표', 'British representative at the Paris Peace Conference'],
        ],
    }),
    person({
        id: 'vittorio-emanuele-orlando', groupId: 'world-interwar',
        given: ['비토리오 에마누엘레', 'Vittorio Emanuele'], family: ['오를란도', 'Orlando'], nativeName: 'Vittorio Emanuele Orlando', years: '1860–1952',
        citizenship: 'italy', origin: 'italy',
        epithet: ['카포레토 뒤 총리로 승전을 이끌었으나 강화회의에서 영토 요구를 이루지 못한 정치가',
            'Italian prime minister who led the country to victory after Caporetto but failed to win its territorial claims at the peace conference'],
        bio: ['팔레르모에서 태어나 이름난 법학 교수가 되었고, 1897년부터 하원의원으로 활동한 자유주의자였다. 1917년 10월 카포레토 패전으로 정부가 무너지자 총리가 되어 카도르나를 해임하고 군을 재정비했으며, 1918년 비토리오 베네토 승리로 「승리의 총리」라 불렸다. 강화회의에서 런던 조약이 약속한 달마티아와 피우메를 요구했으나 얻지 못해 1919년 4월 회의를 떠났고 6월 사임했다. 「불구의 승리」는 무솔리니가 일어선 배경이 되었다. 처음엔 무솔리니를 지지했으나 1924년 마테오티 살해 뒤 결별했다. 1952년 로마에서 죽었다.',
            'Born in Palermo, he became a renowned law professor and from 1897 sat in the Chamber of Deputies as a Liberal. When the government fell after the defeat at Caporetto in October 1917 he became prime minister, dismissed Cadorna and rebuilt the army, and the victory of Vittorio Veneto in 1918 earned him the name “Premier of Victory”. At the peace conference he demanded Dalmatia, promised by the Treaty of London, and Fiume, obtained neither, walked out in April 1919 and resigned in June. The “mutilated victory” helped Mussolini’s rise. He at first supported Mussolini but broke with him after the murder of Matteotti in 1924. He died in Rome in 1952.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: [], en: ['Vittorio Orlando'] },
        sources: [S.orlando],
        facts: {
            years: { claim: '1860–1952', locator: 'lead', excerpt: '19 May 1860 – 1 December 1952' },
            citizenship: { claim: 'Italian statesman, prime minister 1917–1919', locator: 'lead', excerpt: 'was an Italian statesman, who served as the prime minister of Italy from October 1917 to June 1919' },
            nationalOrigin: { claim: 'born in Palermo, Sicily', locator: 'Early life and career', excerpt: 'Orlando was born in Palermo, Sicily.' },
            bio: [
                { claim: 'law professor; deputy from 1897; aligned with Giolitti', locator: 'Early life and career', excerpt: 'Orlando taught law at the University of Palermo and was recognized as an eminent jurist. In 1897, he was elected in the Italian Chamber of Deputies' },
                { claim: 'aligned with Giolitti', locator: 'Early life and career', excerpt: 'He aligned himself with Giovanni Giolitti' },
                { claim: 'prime minister after Caporetto', locator: 'Prime minister', excerpt: 'After the Italian military disaster in World War I at Caporetto on 25 October 1917, which led to the fall of the Boselli government, Orlando became prime minister' },
                { claim: 'fired Cadorna, appointed Diaz', locator: 'Prime minister', excerpt: 'Orlando\'s first act as head of the government was to fire General Luigi Cadorna and appoint the well-respected General Armando Diaz in his place.' },
                { claim: 'Premier of Victory', locator: 'Prime minister', excerpt: 'The fact that Italy recovered and ended up on the winning side in 1918 earned for Orlando the title "Premier of Victory."' },
                { claim: 'claimed Fiume and Dalmatia, received neither', locator: 'Paris Peace Conference', excerpt: 'Italy ended up claiming both and received neither, running up against Wilson\'s policy of national self-determination.' },
                { claim: 'Dalmatia promised in London Pact', locator: 'Prime minister', excerpt: 'Italy was promised significant territorial gains in Dalmatia.' },
                { claim: 'left the conference 24 April 1919', locator: 'Paris Peace Conference', excerpt: 'Orlando dramatically left the conference early on April 24, 1919.' },
                { claim: 'resigned 23 June; mutilated victory', locator: 'Paris Peace Conference', excerpt: 'Orlando resigned on 23 June 1919, following his inability to acquire Fiume for Italy in the peace settlement. The so-called "Mutilated victory" was one of the causes of the rising of Benito Mussolini.' },
                { claim: 'supported then broke with Mussolini over Matteotti', locator: 'Fascism and final years', excerpt: 'When Benito Mussolini seized power in 1922, Orlando initially tactically supported him, but broke with him over the murder of Giacomo Matteotti in 1924.' },
                { claim: 'Mafia accusations', locator: 'Controversies', excerpt: 'Other authors say that Orlando was connected to the Mafia and mafiosi from beginning to end of his long parliamentary career, but no court ever investigated the issue.' },
                { claim: 'Constituent Assembly 1946; died 1952 in Rome', locator: 'Fascism and final years', excerpt: 'In 1946, he was elected to the Constituent Assembly of Italy.' },
                { claim: 'died in Rome 1952', locator: 'Fascism and final years', excerpt: 'He died in 1952 in Rome.' },
            ],
        },
        activities: [
            { functionId: 'political-leadership', affiliationId: 'state-italy', startYear: 1917, endYear: 1919, primary: true, claim: 'Prime minister of Italy', locator: 'lead', excerpt: 'served as the prime minister of Italy from October 1917 to June 1919' },
            { functionId: 'diplomacy', affiliationId: 'state-italy', startYear: 1919, endYear: 1919, claim: 'one of the Big Four at the Paris Peace Conference', locator: 'Paris Peace Conference', excerpt: 'Orlando was one of the Big Four, the main Allied leaders and participants at the Paris Peace Conference in 1919' },
            { functionId: 'law', affiliationId: 'state-italy', startYear: 1907, endYear: 1909, claim: 'Minister of Justice', locator: 'Prime minister', excerpt: 'In 1907, he was appointed Minister of Justice, a role he retained until 1909.' },
            { functionId: 'legislature', affiliationId: 'state-italy', startYear: 1943, endYear: 1945, claim: 'provisional president of the Chamber of Deputies', locator: 'lead', excerpt: 'Orlando was the provisional president of the Chamber of Deputies between 1943 and 1945' },
        ],
        career: [
            ['1897–1925', '하원의원(파르티니코)', 'Deputy for Partinico'],
            ['1907–1909', '법무장관', 'Minister of Justice'],
            ['1916', '내무장관', 'Minister of the Interior'],
            ['1917–1919', '이탈리아 총리', 'Prime minister of Italy'],
            ['1919', '파리 강화회의 「4거두」', 'One of the Big Four at the Paris Peace Conference'],
            ['1946', '제헌의회 의원', 'Member of the Constituent Assembly'],
        ],
    }),
    person({
        id: 'karl-renner', groupId: 'world-interwar',
        given: ['카를', 'Karl'], family: ['레너', 'Renner'], nativeName: 'Karl Renner', years: '1870–1950',
        citizenship: 'austria', origin: { code: 'austria', label: { ko: '오스트리아 (모라비아의 독일계)', en: 'Austria (ethnic German from Moravia)' } },
        epithet: ['생제르맹 조약에 서명하고 1945년 제2공화국을 세운 오스트리아 사회민주당 지도자',
            'Austrian Social Democratic leader who signed the Treaty of Saint-Germain and founded the Second Republic in 1945'],
        bio: ['모라비아의 독일계 농가에서 태어나 빈에서 법학을 공부했고, 사회민주당에 들어가 1907년 제국의회 의원이 되었다. 민족 문제에서 「개인적 자치」를 내세운 오스트리아 마르크스주의 이론가로, 레닌과 스탈린의 비판을 받았다. 1918년 독일-오스트리아 공화국의 첫 총리가 되어 대연정을 이끌며 8시간 노동제 등을 도입했고, 생제르맹 조약으로 독일과의 합병 금지와 영토 상실을 받아들여야 했다. 1938년 합병을 지지했다. 1945년 4월 소련군의 지시로 임시정부를 세웠고 그해 대통령이 되었다. 1950년 빈에서 죽었다.',
            'Born to an ethnic German farming family in Moravia, he studied law in Vienna, joined the Social Democrats and entered the Imperial Council in 1907. An Austromarxist theorist of “personal autonomy” on the national question, he was criticised by Lenin and Stalin. In 1918 he became the first chancellor of German-Austria, leading a grand coalition that introduced the eight-hour day among other reforms, and had to accept the ban on union with Germany and the territorial losses of Saint-Germain. He supported the Anschluss in 1938. In April 1945, at Soviet direction, he formed a provisional government, and that year became president. He died in Vienna in 1950.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: [], en: [] },
        sources: [S.renner],
        facts: {
            years: { claim: '1870–1950', locator: 'lead', excerpt: 'Karl Renner (14 December 1870 – 31 December 1950)' },
            citizenship: { claim: 'Austrian politician and jurist', locator: 'lead', excerpt: 'was an Austrian politician and jurist of the Social Democratic Workers\' Party of Austria' },
            nationalOrigin: { claim: 'ethnic German family in Moravia', locator: 'Early life', excerpt: 'Renner was born the 18th child of an ethnic German family of poor wine-growers in Unter-Tannowitz' },
            bio: [
                { claim: 'studied law in Vienna', locator: 'Early life', excerpt: 'From 1890 to 1896 he studied law at the University of Vienna.' },
                { claim: 'joined SDAP 1896; Reichsrat from 1907', locator: 'Political career', excerpt: 'In 1896, he joined the Social Democratic Workers\' Party of Austria (SDAP), representing the party in the National Council (German: Reichsrat) from the 1907 elections until its dissolution in November 1918.' },
                { claim: 'Der Kampf with Bauer', locator: 'Political career', excerpt: 'he founded and edited the party\'s journal, Der Kampf, together with Otto Bauer and Adolf Braun' },
                { claim: 'personal autonomy; Austro-Marxism', locator: 'Political career', excerpt: 'On the nationality question, he upheld the so-called "personal autonomy"' },
                { claim: 'leader of Austro-Marxism', locator: 'Political career', excerpt: 'As a theorist he was reckoned as one of the leaders of Austro-Marxism.' },
                { claim: 'denounced by Lenin, criticised by Stalin', locator: 'Political beliefs and scholarly contributions', excerpt: 'His and Otto Bauer\'s ideas about the legal protection of cultural minorities were taken up by the Jewish Bund, but fiercely denounced by Vladimir Lenin. Joseph Stalin devoted a whole chapter to criticising Cultural National Autonomy in Marxism and the National Question.' },
                { claim: 'first State Chancellor of German-Austria', locator: 'First Republic', excerpt: 'Renner became the first head of government ("State Chancellor") of that newly established small German-speaking republic' },
                { claim: 'grand coalition; social reforms', locator: 'First Republic', excerpt: 'backed by a grand coalition of Social Democrats and Christian Social Party. A wide range of social reforms were introduced by Renner\'s government, including unemployment insurance, paid holidays, the eight-hour workday' },
                { claim: 'Saint-Germain delegation; losses', locator: 'First Republic', excerpt: 'He was the leader of the delegation that represented this new German-Austria in the negotiations of St. Germain' },
                { claim: 'accepted ban on union and territorial losses', locator: 'First Republic', excerpt: 'There Renner had to accept that this new Austria was prohibited any political association with Germany and he had to accept the loss of German-speaking South Tyrol and the German-speaking parts of Bohemia and Moravia where he himself was born' },
                { claim: 'welcomed the Anschluss', locator: 'First Republic', excerpt: 'he even welcomed the Anschluss in 1938' },
                { claim: 'Soviets instructed him to form a provisional government', locator: 'Relationship with Nazism and Communism', excerpt: 'On 20 April 1945, the Soviets, without asking their Western allies, instructed Renner to form a provisional government. Seven days later Renner\'s cabinet took office, declared the independence of Austria from Nazi Germany' },
                { claim: 'elected president 20 November 1945', locator: 'Post–World War II', excerpt: 'elected Renner as president on 20 November' },
                { claim: 'antisemitism', locator: 'Antisemitism', excerpt: 'stood out before and after the war due to vehement antisemitism' },
                { claim: 'died in Vienna 1950', locator: 'Post–World War II', excerpt: 'Karl Renner died in 1950 in Vienna' },
            ],
        },
        activities: [
            { functionId: 'political-leadership', affiliationId: 'state-austria', startYear: 1918, endYear: 1920, primary: true, claim: 'Chancellor and foreign minister of the first three coalition cabinets', locator: 'First Republic', excerpt: 'Renner was Chancellor of Austria of the first three coalition cabinets from 1918 until 1920 and at the same time Minister of Foreign Affairs' },
            { functionId: 'diplomacy', affiliationId: 'state-austria', startYear: 1919, endYear: 1919, claim: 'led the delegation at Saint-Germain', locator: 'First Republic', excerpt: 'He was the leader of the delegation that represented this new German-Austria in the negotiations of St. Germain' },
            { functionId: 'legislature', affiliationId: 'state-austria', startYear: 1931, endYear: 1933, claim: 'President of the National Council', locator: 'First Republic', excerpt: 'From 1931 to 1933, Renner was President of Parliament, the National Council of Austria.' },
            { functionId: 'government', affiliationId: 'state-austria', startYear: 1945, endYear: 1950, claim: 'head of the 1945 provisional government, then president', locator: 'lead', excerpt: 'was once again decisive in establishing the present Second Republic after the fall of Nazi Germany in 1945, becoming its first President after World War II' },
        ],
        career: [
            ['1896', '오스트리아 사회민주노동자당 입당', 'Joined the Social Democratic Workers’ Party of Austria'],
            ['1907–1918', '제국의회 의원', 'Member of the Reichsrat'],
            ['1918–1920', '독일-오스트리아(오스트리아) 총리 겸 외무장관', 'Chancellor and foreign minister of German-Austria (Austria)'],
            ['1919', '생제르맹 조약 협상 대표단장', 'Head of the delegation at Saint-Germain'],
            ['1931–1933', '국민의회 의장', 'President of the National Council'],
            ['1945', '임시정부 총리, 독립 선언', 'Head of the provisional government; declared independence'],
            ['1945–1950', '오스트리아 대통령', 'President of Austria'],
        ],
    }),
    person({
        id: 'gustav-stresemann', groupId: 'world-interwar',
        given: ['구스타프', 'Gustav'], family: ['슈트레제만', 'Stresemann'], nativeName: 'Gustav Stresemann', years: '1878–1929',
        citizenship: 'germany', origin: 'germany',
        epithet: ['1923년 총리로 소극적 저항을 끝내고 외무장관으로 로카르노 조약을 맺은 정치가',
            'Weimar chancellor who ended passive resistance in 1923 and, as foreign minister, concluded the Locarno treaties'],
        bio: ['베를린에서 태어나 1907년 국민자유당 의원이 되었고, 1차 세계대전 중에는 영토 병합과 무제한 잠수함전을 주장했다. 패전 뒤 독일인민당을 세웠고 점차 공화국을 받아들였다. 1923년 8월 총리 겸 외무장관이 되어 루르의 소극적 저항을 끝내고, 공산당이 들어간 작센·튀링겐 정부를 군대로 몰아냈으며, 렌텐마르크로 초인플레이션을 잡았다. 11월 불신임으로 물러났지만 죽을 때까지 외무장관으로 남아 도스안과 로카르노 조약, 국제연맹 가입을 이끌었고 1926년 노벨 평화상을 받았다. 1929년 뇌졸중으로 죽었다.',
            'Born in Berlin, he entered the Reichstag for the National Liberals in 1907 and during the war backed annexations and unrestricted submarine warfare. After the defeat he founded the German People’s Party and came to accept the republic. Chancellor and foreign minister from August 1923, he ended passive resistance in the Ruhr, used the army to remove the Saxon and Thuringian governments that included Communists, and halted hyperinflation with the Rentenmark. Ousted by a no-confidence vote in November, he remained foreign minister until his death, shaping the Dawes Plan, the Locarno treaties and entry into the League of Nations, and shared the 1926 Nobel Peace Prize. He died of a stroke in 1929.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: [], en: ['Gustav Ernst Stresemann'] },
        sources: [S.stresemann],
        facts: {
            years: { claim: '1878–1929', locator: 'lead', excerpt: '10 May 1878 – 3 October 1929' },
            citizenship: { claim: 'German statesman of the Weimar Republic', locator: 'lead', excerpt: 'was a German statesman during the Weimar Republic who served as chancellor of Germany from August to November 1923 and as foreign minister from 1923 to 1929' },
            nationalOrigin: { claim: 'born in Berlin', locator: 'Early years', excerpt: 'Stresemann was born on 10 May 1878 at 66 Köpenicker Straße in southeast Berlin' },
            bio: [
                { claim: 'father a beer bottler', locator: 'Early years', excerpt: 'His father worked as a beer bottler and distributor' },
                { claim: 'studied political economy at Berlin and Leipzig', locator: 'lead', excerpt: 'Stresemann attended the University of Berlin and Leipzig University, where he studied political economy, history and international law' },
                { claim: 'Reichstag 1907 National Liberal', locator: 'lead', excerpt: 'In 1907, he was elected to the Reichstag as a deputy for the National Liberal Party.' },
                { claim: 'wartime militarism and expansionism', locator: 'lead', excerpt: 'During World War I, he was a vocal advocate for German militarism and expansionism.' },
                { claim: 'annexation aims; submarine warfare', locator: 'First World War', excerpt: 'He believed that Germany would need to annex Belgium, parts of north-east France, "extensive" lands in Eastern Europe and the French protectorate in Morocco' },
                { claim: 'unrestricted submarine warfare', locator: 'First World War', excerpt: 'He was a vocal proponent of unrestricted submarine warfare.' },
                { claim: 'founded the DVP', locator: 'lead', excerpt: 'He founded the German People\'s Party (DVP) and, despite his own monarchist beliefs, came to grudgingly accept Weimar democracy' },
                { claim: 'DVP initially opposed the Republic', locator: 'Founding the German People\'s Party', excerpt: 'Initially, Stresemann and the DVP opposed the Weimar Republic and supported a restoration of the monarchy.' },
                { claim: 'Vernunftrepublikaner', locator: 'Foreign minister 1923–1929', excerpt: 'Stresemann was regarded as a Vernunftrepublikaner, (republican by reason)' },
                { claim: 'chancellor August 1923', locator: 'Chancellor 1923', excerpt: 'On 13 August 1923, Stresemann was appointed chancellor and foreign minister of a grand coalition government' },
                { claim: 'ended passive resistance 26 September', locator: 'Chancellor 1923', excerpt: 'On 26 September 1923, Stresemann announced the end to the passive resistance against the occupation of the Ruhr by the French and Belgians' },
                { claim: 'Reichsexekution against Saxony and Thuringia', locator: 'Chancellor 1923', excerpt: 'Stresemann used a Reichsexekution to send troops into the two states to remove the Communists from the governments' },
                { claim: 'Rentenmark', locator: 'Chancellor 1923', excerpt: 'The Stresemann government introduced a new currency, the Rentenmark, to end hyperinflation.' },
                { claim: 'resigned after confidence vote', locator: 'Chancellor 1923', excerpt: 'after he lost a confidence vote on 23 November 1923, Stresemann and his cabinet resigned' },
                { claim: 'remained foreign minister', locator: 'Foreign minister 1923–1929', excerpt: 'Stresemann remained as foreign minister in the government of his successor, Wilhelm Marx from the Centre Party, and for the rest of his life' },
                { claim: 'Dawes Plan, Locarno, League, Treaty of Berlin', locator: 'lead', excerpt: 'His first major diplomatic success was the 1924 Dawes Plan, which reduced Germany\'s overall reparations commitment. It was followed by the Locarno Treaties in 1925' },
                { claim: 'League admission; Treaty of Berlin', locator: 'lead', excerpt: 'led to Germany\'s admission to the League of Nations a year later. Stresemann also moved to improve relations with the Soviet Union through the 1926 Treaty of Berlin.' },
                { claim: 'Nobel Peace Prize 1926 with Briand', locator: 'Foreign minister 1923–1929', excerpt: 'Stresemann was co-winner with Aristide Briand of the 1926 Nobel Peace Prize for their work on Locarno.' },
                { claim: 'died after strokes hours after Young Plan vote', locator: 'Health decline and death', excerpt: 'He died of a series of strokes on 3 October 1929 at the age of 51' },
                { claim: 'hours after the Young Plan vote', locator: 'Health decline and death', excerpt: 'His death came just hours after convincing the Reichstag to accept the Young Plan.' },
            ],
        },
        activities: [
            { functionId: 'diplomacy', affiliationId: 'state-germany', startYear: 1923, endYear: 1929, primary: true, claim: 'foreign minister 1923–1929', locator: 'lead', excerpt: 'as foreign minister from 1923 to 1929' },
            { functionId: 'political-leadership', affiliationId: 'state-germany', startYear: 1923, endYear: 1923, claim: 'chancellor August–November 1923', locator: 'lead', excerpt: 'served as chancellor of Germany from August to November 1923' },
            { functionId: 'legislature', affiliationId: 'state-germany', startYear: 1907, endYear: null, claim: 'Reichstag deputy', locator: 'lead', excerpt: 'In 1907, he was elected to the Reichstag as a deputy for the National Liberal Party.' },
        ],
        career: [
            ['1907', '제국의회 의원(국민자유당)', 'Reichstag deputy (National Liberal Party)'],
            ['1917', '국민자유당 대표', 'Leader of the National Liberal Party'],
            ['1918', '독일인민당 창당', 'Founded the German People’s Party'],
            ['1923', '총리 겸 외무장관', 'Chancellor and foreign minister'],
            ['1923–1929', '외무장관', 'Foreign minister'],
            ['1925', '로카르노 조약', 'Locarno Treaties'],
            ['1926', '노벨 평화상', 'Nobel Peace Prize'],
        ],
    }),
];
