// Person cards for the First World War and its aftermath (queue A, second half):
// Mustafa Kemal, Ludendorff, Wilhelm II, Foch, Enver Pasha. See
// ../baltic-1940-1953-20261002/lib.js person(). Excerpts are verbatim from the cited pages.
const { W, person } = require('../baltic-1940-1953-20261002/lib');

const E = t => W(encodeURI(t));
const S = {
    kemal: E('Mustafa_Kemal_Atatürk'),
    ludendorff: E('Erich_Ludendorff'),
    wilhelm: E('Wilhelm_II'),
    foch: E('Ferdinand_Foch'),
    enver: E('Enver_Pasha'),
};

module.exports = [
    person({
        id: 'mustafa-kemal-ataturk',
        given: ['무스타파 케말', 'Mustafa Kemal'], family: ['아타튀르크', 'Atatürk'], nativeName: 'Mustafa Kemal Atatürk', years: '1881–1938',
        citizenship: 'turkey', origin: 'turkey',
        epithet: ['갈리폴리에서 이름을 얻고 국민운동을 이끌어 튀르키예 공화국을 세운 대통령',
            'Gallipoli commander who led the national movement and founded the Republic of Turkey as its first president'],
        bio: ['살로니카에서 태어나 청년 튀르크 운동에 가담했고, 1차 세계대전 때 갈리폴리 방어로 이름을 얻었다. 패전 뒤 1919년 5월 삼순에 상륙해 점령에 맞선 국민운동을 조직했고, 1920년 앙카라에 대국민의회를 열었다. 볼셰비키 정부의 금과 무기 지원을 받아 그리스군을 물리쳤고, 로잔 조약으로 승리를 인정받았다. 이 시기 아나톨리아의 아르메니아인·그리스인에 대한 인종 청소가 학살·추방·주민 교환으로 마무리되었다. 1922년 술탄제를 폐지하고 1923년 공화국의 초대 대통령이 되어 일당 체제 아래 세속화와 튀르크화 정책을 폈다. 1938년 죽었다.',
            'Born in Salonica, he joined the Young Turk movement and made his name defending Gallipoli in the First World War. After the defeat he landed at Samsun in May 1919 to organise the national movement against occupation, and in 1920 convened the Grand National Assembly in Ankara. With gold and arms from the Bolshevik government he defeated the Greek army, and the Treaty of Lausanne recognised the victory. In these years the ethnic cleansing of Anatolia’s Armenians and Greeks was completed through massacres, deportations and population exchange. He abolished the sultanate in 1922 and in 1923 became the first president of the republic, pursuing secularising reforms and Turkification under one-party rule. He died in 1938.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: ['케말 아타튀르크', '케말 파샤'], en: ['Kemal Atatürk', 'Mustafa Kemal Pasha', 'Kemal Pasha'] },
        linkExpressions: [['ko', '무스타파 케말'], ['en', 'Mustafa Kemal'], ['ko', '케말 아타튀르크'], ['en', 'Kemal Atatürk']],
        sources: [S.kemal],
        facts: {
            years: { claim: 'c. 1881 – 10 November 1938', locator: 'lead', excerpt: 'Mustafa Kemal Atatürk (c. 1881 – 10 November 1938) was a Turkish field marshal and statesman' },
            citizenship: { claim: 'Founder and first president of the Republic of Turkey', locator: 'lead', excerpt: 'was the founder of the Republic of Turkey and served as its first president from 1923 until his death in 1938' },
            nationalOrigin: { claim: 'Turkish field marshal and statesman', locator: 'lead', excerpt: 'was a Turkish field marshal and statesman' },
            bio: [
                { claim: 'born in Salonica; CUP and Young Turks', locator: 'lead', excerpt: 'Born in Salonica in the Ottoman Empire, Atatürk was early on persecuted for agitating against Sultan Abdul Hamid II\'s autocracy, joining opposition movements like the Committee of Union and Progress and the Young Turks.' },
                { claim: 'sidelined after denouncing the CUP leadership', locator: 'lead', excerpt: 'Atatürk denounced CUP leadership for encouraging a politicised military –and was subsequently sidelined–' },
                { claim: 'rose to prominence at Gallipoli', locator: 'lead', excerpt: 'He rose to prominence with his role in the Defence of Gallipoli during World War I.' },
                { claim: 'commanded the 19th Division at Gallipoli', locator: 'First World War (1914–1918)', excerpt: 'Mustafa Kemal was given the task of organizing and commanding the 19th Division attached to the Fifth Army during the Battle of Gallipoli.' },
                { claim: 'reached Samsun, organised a national movement', locator: 'Turkish War of Independence (1919–1923)', excerpt: 'On 19 May 1919, he reached Samsun. His first goal was the establishment of an organized national movement against the occupying forces.' },
                { claim: 'GNA opened in April 1920 with him as speaker', locator: 'Turkish War of Independence (1919–1923)', excerpt: 'On 23 April 1920, the GNA opened with Mustafa Kemal as the speaker' },
                { claim: 'Greek forces advancing from Smyrna, occupied May 1919', locator: 'Turkish War of Independence (1919–1923)', excerpt: 'the Greek forces advancing eastward from Smyrna (today known as İzmir) that they had occupied in May 1919' },
                { claim: 'Bolshevik gold and arms from autumn 1920', locator: 'Turkish War of Independence (1919–1923)', excerpt: 'were made possible by a steady supply of gold and armaments to the Kemalists from the Russian Bolshevik government from the autumn of 1920 onwards' },
                { claim: 'Sakarya 1921', locator: 'Turkish War of Independence (1919–1923)', excerpt: 'The ensuing Battle of the Sakarya was fought from 23 August–13 September 1921 and ended with the defeat of the Greeks.' },
                { claim: 'Dumlupınar 1922', locator: 'Turkish War of Independence (1919–1923)', excerpt: 'In August 1922, Mustafa Kemal launched an all-out attack on the Greek lines at Afyonkarahisar in the Battle of Dumlupınar' },
                { claim: 'Lausanne; ethnic cleansing of Armenians and Greeks', locator: 'lead', excerpt: 'During and after the war, the ethnic cleansing of Armenians and Greeks from Anatolia outside of Istanbul, including the Kars region invaded by the Kemalist armies, was largely completed via large-scale massacres, flight, expulsions, and the population exchange between Greece and Turkey.' },
                { claim: 'victory confirmed at Lausanne', locator: 'lead', excerpt: 'confirmed in the Treaty of Lausanne' },
                { claim: 'abolished the sultanate 1922, republic 1923', locator: 'lead', excerpt: 'His government subsequently proceeded to abolish the Ottoman sultanate in 1922 and proclaimed the Republic of Turkey in 1923.' },
                { claim: 'one-party regime', locator: 'lead', excerpt: 'By the mid-1920s, opponents to Atatürk\'s rule were suppressed as a one-party regime was cemented around him.' },
                { claim: 'Turkification', locator: 'lead', excerpt: 'His government carried out a policy of Turkification' },
                { claim: 'died of cirrhosis in 1938', locator: 'Death and state funeral', excerpt: 'He went to Istanbul for treatment, where he was diagnosed with cirrhosis.' },
                { claim: 'died 10 November 1938 in Dolmabahçe Palace', locator: 'Death and state funeral', excerpt: 'He died on 10 November 1938, at the age of 57, in the Dolmabahçe Palace.' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: 'state-turkey', startYear: 1915, endYear: 1922, claim: 'Gallipoli division commander, later commander in chief of the GNA forces', locator: 'Turkish War of Independence (1919–1923)', excerpt: 'On 5 August 1921, Mustafa Kemal was promoted to commander in chief of the forces by the GNA.' },
            { functionId: 'political-leadership', affiliationId: 'state-turkey', startYear: 1923, endYear: 1938, primary: true, claim: 'First president of the Republic of Turkey', locator: 'lead', excerpt: 'was the founder of the Republic of Turkey and served as its first president from 1923 until his death in 1938' },
        ],
        career: [
            ['1915', '갈리폴리 전투 제19사단장', 'Commander of the 19th Division at Gallipoli'],
            ['1919', '삼순 상륙, 국민운동 조직', 'Landed at Samsun and organised the national movement'],
            ['1920', '앙카라 대국민의회 의장', 'Speaker of the Grand National Assembly in Ankara'],
            ['1921–1922', '사카리아·둠루프나르 전투 승리', 'Victories at the Sakarya and Dumlupınar'],
            ['1923–1938', '튀르키예 공화국 초대 대통령', 'First president of the Republic of Turkey'],
        ],
    }),
    person({
        id: 'erich-ludendorff',
        given: ['에리히', 'Erich'], family: ['루덴도르프', 'Ludendorff'], nativeName: 'Erich Ludendorff', years: '1865–1937',
        citizenship: 'germany', origin: 'germany',
        epithet: ['힌덴부르크와 함께 독일의 전쟁을 지휘하고 전후 맥주홀 폭동에 가담한 장군',
            'General who directed Germany’s war with Hindenburg and later joined Hitler’s Beer Hall Putsch'],
        bio: ['포젠주의 평민 집안에서 태어나 참모본부에서 일했고, 1914년 리에주와 탄넨베르크로 이름을 얻었다. 1916년 8월 힌덴부르크와 함께 최고사령부를 넘겨받아 제1병참총감으로서 사실상의 군사독재 아래 전쟁을 지휘하고 힌덴부르크 계획을 밀어붙였다. 1918년 3월 미하엘 작전으로 춘계 공세를 열었으나 실패했고, 9월 즉각 휴전을 요구한 뒤 10월 해임되었다. 전후 비수설을 퍼뜨렸고 1920년 카프 폭동과 1923년 히틀러의 맥주홀 폭동에 가담했다. 1924~1928년 국가사회주의 자유운동 의원을 지냈다. 1937년 뮌헨에서 죽었다.',
            'Born to a commoner family in the Province of Posen, he served on the General Staff and won fame at Liège and Tannenberg in 1914. In August 1916 he and Hindenburg took over the Supreme Army Command; as First Quartermaster General he directed the war under a de facto military dictatorship and drove the Hindenburg Programme. His spring offensive, opened with Operation Michael in March 1918, failed; in September he demanded an immediate armistice and in October he was dismissed. After the war he spread the stab-in-the-back myth and took part in the Kapp Putsch of 1920 and Hitler’s Beer Hall Putsch of 1923. He sat in the Reichstag for the National Socialist Freedom Movement in 1924–1928 and died in Munich in 1937.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: [], en: ['Erich Friedrich Wilhelm Ludendorff'] },
        sources: [S.ludendorff],
        facts: {
            years: { claim: '9 April 1865 – 20 December 1937', locator: 'lead', excerpt: '9 April 1865 – 20 December 1937' },
            citizenship: { claim: 'Prussian-born German general and politician', locator: 'lead', excerpt: 'was a Prussian-born German general and politician' },
            nationalOrigin: { claim: 'German family descended from Pomeranian merchants', locator: 'Early life', excerpt: 'His father was descended from Pomeranian merchants' },
            bio: [
                { claim: 'non-noble family in the Province of Posen', locator: 'lead', excerpt: 'Ludendorff came from a non-noble family in Kruszewnia in the Prussian Province of Posen.' },
                { claim: 'Schlieffen Plan', locator: 'lead', excerpt: 'where he helped oversee the development of the Schlieffen Plan' },
                { claim: 'Liège and Tannenberg', locator: 'lead', excerpt: 'He achieved fame during World War I (1914–1918) for his central role in the German victories at Liège and Tannenberg in 1914.' },
                { claim: 'August 1916: Hindenburg head of OHL, himself First Quartermaster General', locator: 'lead', excerpt: 'By the end of August 1916, Ludendorff successfully lobbied for Hindenburg\'s appointment as head of the Supreme Army Command and his own promotion to the rank of First Quartermaster General.' },
                { claim: 'military dictatorship in all but name', locator: 'lead', excerpt: 'Once he and Hindenburg established a military dictatorship in all but name, Ludendorff directed Germany\'s entire military strategy and war effort for the rest of the conflict.' },
                { claim: 'Hindenburg Program', locator: 'The Home Front', excerpt: 'began by setting overambitious targets for military production in what they called the Hindenburg Program' },
                { claim: 'Operation Michael 21 March 1918', locator: 'Western Front (1918)', excerpt: 'The first attack, Operation Michael, was on 21 March 1918 near Cambrai.' },
                { claim: 'black day at Amiens', locator: 'Western Front (1918)', excerpt: 'To Ludendorff, it was the "black day in the history of the German Army".' },
                { claim: 'demanded an immediate armistice on 29 September', locator: 'Downfall', excerpt: 'On 29 September 1918, Ludendorff and Hindenburg suddenly told an incredulous Kaiser that they could not guarantee the integrity of the Western front "for two hours", and they must have an immediate armistice.' },
                { claim: 'Kaiser accepted his resignation', locator: 'Downfall', excerpt: 'The Kaiser called his commanders in, curtly accepting Ludendorff\'s resignation and then rejecting Hindenburg\'s.' },
                { claim: 'stab-in-the-back myth', locator: 'lead', excerpt: 'After the war, Ludendorff became a prominent nationalist leader and a promoter of the stab-in-the-back myth, which posited that Germany\'s defeat and the settlement reached at Versailles were the result of a treasonous conspiracy by Marxists, Freemasons and Jews.' },
                { claim: 'Kapp Putsch and Beer Hall Putsch; 1925 election', locator: 'lead', excerpt: 'He also took part in the failed 1920 Kapp Putsch and 1923 Beer Hall Putsch before unsuccessfully standing in the 1925 election for president.' },
                { claim: 'Reichstag for the NSFB 1924–1928', locator: 'Political career in the Republic', excerpt: 'In 1924, he was elected to the Reichstag as a representative of the NSFB (a coalition of the German Völkisch Freedom Party (DVFP) and members of the Nazi Party), serving until 1928.' },
                { claim: '1.1% in 1925', locator: 'Political career in the Republic', excerpt: 'but received only 1.1% of the vote' },
                { claim: 'died of liver cancer in Munich', locator: 'lead', excerpt: 'Following his death from liver cancer in Munich in 1937' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: 'state-germany', startYear: 1916, endYear: 1918, primary: true, claim: 'First Quartermaster General directing Germany’s war effort', locator: 'lead', excerpt: 'After his appointment as First Quartermaster General of the Great General Staff in 1916, Ludendorff oversaw virtually all decisions regarding Germany\'s strategy and war effort until the country\'s defeat in 1918.' },
            { functionId: 'legislature', affiliationId: 'state-germany', startYear: 1924, endYear: 1928, claim: 'Reichstag deputy for the NSFB', locator: 'Political career in the Republic', excerpt: 'In 1924, he was elected to the Reichstag as a representative of the NSFB (a coalition of the German Völkisch Freedom Party (DVFP) and members of the Nazi Party), serving until 1928.' },
        ],
        career: [
            ['1914', '리에주 공략, 탄넨베르크 승리', 'Liège and Tannenberg'],
            ['1916–1918', '제1병참총감', 'First Quartermaster General'],
            ['1918', '춘계 공세(미하엘 작전), 10월 해임', 'Spring offensive (Operation Michael); dismissed in October'],
            ['1920', '카프 폭동 가담', 'Took part in the Kapp Putsch'],
            ['1923', '맥주홀 폭동 가담', 'Took part in the Beer Hall Putsch'],
            ['1924–1928', '제국의회 의원(국가사회주의 자유운동)', 'Reichstag deputy (NSFB)'],
        ],
    }),
    person({
        id: 'wilhelm-ii',
        given: ['', ''], family: ['빌헬름 2세', 'Wilhelm II'], nativeName: 'Wilhelm II.', years: '1859–1941',
        citizenship: 'germany', origin: 'germany',
        epithet: ['7월 위기에 오스트리아를 지원하고 1918년 퇴위해 망명한 마지막 독일 황제',
            'Last German Emperor, who backed Austria-Hungary in the July Crisis and abdicated and fled in 1918'],
        bio: ['프로이센 왕세자와 영국 빅토리아 여왕의 맏딸 사이에서 태어나 1888년 황제가 되었고, 1890년 비스마르크를 해임했다. 1900년 의화단 진압군에게 훈족처럼 싸우라고 연설했고, 함대 증강과 모로코 개입으로 독일을 고립시켰다. 1914년 7월 위기 때 오스트리아-헝가리에 군사 지원을 보장했다. 전쟁 중에는 결정을 최고사령부에 넘겨 힌덴부르크와 루덴도르프의 군사독재가 섰다. 1918년 11월 9일 퇴위가 발표되자 네덜란드로 망명했고, 네덜란드는 베르사유 조약이 정한 그의 인도를 거부했다. 1941년 도른에서 죽었다.',
            'The son of the Prussian crown prince and Queen Victoria’s eldest daughter, he became emperor in 1888 and dismissed Bismarck in 1890. In 1900 he urged the troops sent against the Boxers to fight like Huns, and his naval build-up and Moroccan interventions isolated Germany. In the July Crisis of 1914 he assured Austria-Hungary of military support. In the war he left decisions largely to the Supreme Army Command, leading to the de facto military dictatorship of Hindenburg and Ludendorff. When his abdication was announced on 9 November 1918 he went into exile in the Netherlands, which refused to extradite him as the Treaty of Versailles provided. He died at Doorn in 1941.'],
        fate: ['exile', '망명지에서 사망', 'Died in exile'],
        aliases: { ko: ['카이저 빌헬름 2세', '황제 빌헬름 2세'], en: ['Kaiser Wilhelm II', 'William II, German Emperor', 'Friedrich Wilhelm Viktor Albert'] },
        linkExpressions: [['ko', '카이저 빌헬름 2세'], ['en', 'Kaiser Wilhelm II']],
        sources: [S.wilhelm],
        facts: {
            years: { claim: '27 January 1859 – 4 June 1941', locator: 'lead', excerpt: '27 January 1859 – 4 June 1941' },
            citizenship: { claim: 'Last German Emperor', locator: 'lead', excerpt: 'was the last German Emperor from 1888 until his abdication in 1918' },
            nationalOrigin: { claim: 'Prussian prince of the Hohenzollern dynasty', locator: 'lead', excerpt: 'Wilhelm was the son of Prince Frederick William and Victoria, Princess Royal' },
            bio: [
                { claim: 'eldest grandchild of Queen Victoria', locator: 'lead', excerpt: 'Through his mother, he was the eldest of the 42 grandchildren of Queen Victoria of the United Kingdom.' },
                { claim: 'became Kaiser in 1888', locator: 'lead', excerpt: 'Frederick died just 99 days later, and his son succeeded him as Kaiser Wilhelm II.' },
                { claim: 'dismissed Bismarck in 1890; New Course', locator: 'lead', excerpt: 'In March 1890, the young Kaiser dismissed longtime Chancellor Otto von Bismarck and assumed direct control over his nation\'s policies, embarking on a "New Course"' },
                { claim: 'Hun speech 1900', locator: 'Hun speech of 1900', excerpt: 'The Kaiser\'s farewell address to departing German soldiers commanded them, in the spirit of the Huns, to be merciless in battle.' },
                { claim: 'naval build-up and Morocco alienated Europe', locator: 'lead', excerpt: 'he and his government did much to alienate the German Empire from most of Europe by initiating a massive naval build-up, contesting French control of Morocco' },
                { claim: 'July Crisis guarantee to Austria-Hungary', locator: 'lead', excerpt: 'In 1914, his diplomatic brinksmanship culminated in the guarantee of his country\'s military support to Austria-Hungary during the July Crisis which ultimately plunged all of Europe into World War I.' },
                { claim: 'left decisions to the Supreme Army Command; military dictatorship', locator: 'lead', excerpt: 'By August 1916, his broad delegation of power gave rise to a de facto military dictatorship that dominated the country\'s policies in his place for the rest of the conflict.' },
                { claim: 'Prince Max announced his abdication on 9 November 1918', locator: 'Abdication and exile', excerpt: 'Chancellor Prince Max of Baden announced Wilhelm\'s abdication of both titles on 9 November 1918.' },
                { claim: 'exile in the Netherlands on 10 November', locator: 'Abdication and exile', excerpt: 'On 10 November, Wilhelm crossed the border by train and went into exile in the neutral Netherlands.' },
                { claim: 'Article 227; Dutch refused extradition', locator: 'Abdication and exile', excerpt: 'Article 227 expressly provided for the prosecution of Wilhelm "for a supreme offence against international morality and the sanctity of treaties", but the Dutch government refused to extradite him.' },
                { claim: 'died at Doorn in 1941', locator: 'Death', excerpt: 'Wilhelm died of a pulmonary embolism in Doorn, Netherlands, on 4 June 1941, at the age of 82' },
            ],
        },
        activities: [
            { functionId: 'monarchy', affiliationId: 'state-germany', startYear: 1888, endYear: 1918, primary: true, claim: 'German Emperor and King of Prussia 1888–1918', locator: 'lead', excerpt: 'was the last German Emperor from 1888 until his abdication in 1918' },
        ],
        career: [
            ['1888', '독일 황제·프로이센 국왕 즉위', 'German Emperor and King of Prussia'],
            ['1890', '비스마르크 해임, 「신노선」', 'Dismissed Bismarck; the “New Course”'],
            ['1914', '7월 위기 때 오스트리아-헝가리에 지원 보장', 'Guaranteed support to Austria-Hungary in the July Crisis'],
            ['1918', '11월 9일 퇴위 발표, 네덜란드 망명', 'Abdication announced on 9 November; exile in the Netherlands'],
        ],
    }),
    person({
        id: 'ferdinand-foch',
        given: ['페르디낭', 'Ferdinand'], family: ['포슈', 'Foch'], nativeName: 'Ferdinand Foch', years: '1851–1929',
        citizenship: 'france', origin: 'france',
        epithet: ['1918년 연합군 총사령관으로 반격을 이끌고 휴전 조건을 받아 낸 프랑스 원수',
            'French marshal who as Allied supreme commander in 1918 led the counter-offensive and dictated the armistice'],
        bio: ['타르브의 가톨릭 집안에서 태어났다. 1914년 마른 전투에서 제9군을 지휘해 이름을 얻었다. 1918년 3월 독일의 춘계 공세 앞에서 연합군 총사령관이 되어 프랑스·영국·미국군을 조율했고, 제2차 마른 전투 뒤 원수가 되어 전쟁을 끝낸 반격을 이끌었다. 11월 콩피에뉴에서 독일의 휴전 서명을 받았다. 강화회의에서 라인란트 분리를 주장했으나 15년 점령에 그치자 베르사유 조약이 너무 관대하다고 비판했다. 1920년 폴란드-소비에트 전쟁에서 폴란드에 조언해 폴란드 원수 칭호를 받았다. 1929년 파리에서 죽었다.',
            'Born into a Catholic family in Tarbes, he made his name commanding the Ninth Army at the Marne in 1914. Facing the German spring offensive in March 1918 he became Allied supreme commander, coordinating the French, British and American armies, and after the Second Battle of the Marne was made marshal and led the counter-offensive that ended the war. In November he received the German armistice at Compiègne. At the peace conference he called for separating the Rhineland, and when this was reduced to a fifteen-year occupation he criticised the Treaty of Versailles as too lenient. For his advice to Poland in the Polish-Soviet War of 1920 he was made a Marshal of Poland. He died in Paris in 1929.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: ['포슈 원수'], en: ['Marshal Foch', 'Ferdinand Jean Marie Foch'] },
        linkExpressions: [['ko', '포슈 원수'], ['en', 'Marshal Foch']],
        sources: [S.foch],
        facts: {
            years: { claim: '2 October 1851 – 20 March 1929', locator: 'lead', excerpt: '2 October 1851 – 20 March 1929' },
            citizenship: { claim: 'French general, Marshal of France', locator: 'lead', excerpt: 'was a French general, Marshal of France and a member of the Académie Française and Académie des Sciences' },
            nationalOrigin: { claim: 'born in Tarbes, south-western France', locator: 'Early life', excerpt: 'Ferdinand Foch was born in Tarbes, a municipality in the department of Hautes-Pyrénées, in southwestern France, into a modest, devout, middle-class Catholic family.' },
            bio: [
                { claim: 'Marne 1914, Ninth Army', locator: 'lead', excerpt: 'Foch\'s prestige soared as a result of the victory at the Marne, for which he was widely credited as a chief protagonist while commanding the French Ninth Army.' },
                { claim: 'cooperated with the British at Ypres and the Somme', locator: 'lead', excerpt: 'in which role he was required to cooperate with the British forces at Ypres and the Somme' },
                { claim: 'Commander-in-Chief of the Allied Armies 26 March 1918', locator: 'lead', excerpt: 'Foch was appointed "Commander-in-Chief of the Allied Armies" on 26 March 1918.' },
                { claim: 'coordinated the Allies, stopped the offensive, counter-attacked', locator: 'lead', excerpt: 'He successfully coordinated the French, British and American efforts, deftly handling his strategic reserves. He stopped the German offensive and launched a war-winning counterattack.' },
                { claim: 'Marshal after the Second Marne', locator: 'lead', excerpt: 'He played a decisive role in halting a renewed German advance on Paris in the Second Battle of the Marne, after which he was promoted to Marshal of France.' },
                { claim: 'accepted the armistice', locator: 'lead', excerpt: 'On 11 November 1918, Foch accepted the German request for an armistice.' },
                { claim: 'Rhine as the western military frontier', locator: 'Paris Peace Conference', excerpt: 'Henceforward the Rhine ought to be the Western military frontier of the German countries.' },
                { claim: 'Lloyd George and Wilson objected; fifteen-year occupation', locator: 'Paris Peace Conference', excerpt: 'However, the British Prime Minister David Lloyd George and the American President Woodrow Wilson objected to the detachment of the Rhineland from Germany so that the balance of power would not be too much in favour of France, but agreed to Allied military occupation for fifteen years, which Foch thought insufficient to protect France.' },
                { claim: 'Versailles “a capitulation, a treason”', locator: 'Paris Peace Conference', excerpt: 'Foch considered the Treaty of Versailles to be "a capitulation, a treason"' },
                { claim: 'too lenient on Germany', locator: 'lead', excerpt: 'He considered the Treaty of Versailles too lenient on Germany.' },
                { claim: 'Marshal of Poland for advice in the Polish–Soviet War', locator: 'Post-war career and legacy', excerpt: 'for his advice during the Polish–Soviet War of 1920, as well as his pressure on Germany during the Greater Poland Uprising, he was awarded the title of Marshal of Poland in 1923' },
                { claim: 'died in Paris 1929', locator: 'Post-war career and legacy', excerpt: 'Foch died of a heart attack, influenza, and pneumonia in Paris on 20 March 1929 at the age of 77.' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: 'state-france', startYear: 1918, endYear: 1918, primary: true, claim: 'Supreme Allied Commander on the Western Front in 1918', locator: 'lead', excerpt: 'He distinguished himself as Supreme Allied Commander on the Western Front during the First World War in 1918.' },
        ],
        career: [
            ['1914', '마른 전투 제9군 사령관', 'Commander of the Ninth Army at the Marne'],
            ['1918', '연합군 총사령관(3월 26일), 프랑스 원수(8월)', 'Allied commander-in-chief (26 March); Marshal of France (August)'],
            ['1918', '콩피에뉴 휴전', 'Armistice at Compiègne'],
            ['1923', '폴란드 원수', 'Marshal of Poland'],
        ],
    }),
    person({
        id: 'enver-pasha',
        given: ['', ''], family: ['엔베르 파샤', 'Enver Pasha'], nativeName: 'İsmail Enver Paşa', years: '1881–1922',
        citizenship: 'turkey', origin: { code: 'turkey', label: { ko: '튀르키예 (아버지 가가우즈계 또는 알바니아계, 어머니 타타르계)', en: 'Turkish (father Gagauz or Albanian, mother Tatar)' } },
        epithet: ['「세 파샤」의 전쟁장관으로 오스만을 참전시키고 아르메니아인 제노사이드를 주도한 군인',
            'War minister among the Three Pashas who took the Ottomans into the war and was a main perpetrator of the Armenian genocide'],
        bio: ['콘스탄티노플에서 태어나 통일진보위원회에 들어갔고 1908년 청년 튀르크 혁명의 영웅이 되었다. 1913년 쿠데타로 정부를 무너뜨리고 전쟁장관이 되어 탈라트·제말과 「세 파샤」로 제국을 다스렸다. 독일과의 동맹으로 오스만을 1차 세계대전에 끌어들였고, 1914년 12월 사르카미시에서 대군을 잃은 뒤 패배를 아르메니아인 탓으로 돌렸다. 아르메니아인·그리스인·아시리아인 제노사이드의 주요 가해자였다. 패전 뒤 달아나 궐석 사형을 선고받았다. 볼셰비키와 손잡았다가 1921년 중앙아시아에서 바스마치 반란군 편으로 넘어갔고, 1922년 붉은군대와 싸우다 죽었다.',
            'Born in Constantinople, he joined the Committee of Union and Progress and became a hero of the Young Turk Revolution of 1908. After the 1913 coup he became war minister and ruled the empire with Talat and Djemal as the Three Pashas. He took the Ottomans into the First World War in alliance with Germany, and after losing most of his army at Sarıkamış in December 1914 blamed the defeat on the Armenians. He was a main perpetrator of the Armenian, Greek and Assyrian genocides. After the defeat he fled and was sentenced to death in absentia. He worked with the Bolsheviks, then in 1921 in Central Asia went over to the Basmachi rebels, and was killed fighting the Red Army in 1922.'],
        fate: ['killed', '붉은군대와 싸우다 전사', 'Killed fighting the Red Army'],
        aliases: { ko: ['이스마일 엔베르', '엔베르 베이'], en: ['İsmail Enver', 'Ismail Enver', 'Enver Bey', 'Enver Paşa'] },
        linkExpressions: [['en', 'Enver Paşa'], ['en', 'İsmail Enver']],
        sources: [S.enver],
        facts: {
            years: { claim: '23 November 1881 – 4 August 1922', locator: 'lead', excerpt: '23 November 1881 – 4 August 1922' },
            citizenship: { claim: 'Ottoman Minister of War 1914–1918', locator: 'lead', excerpt: 'served as the Ottoman Empire\'s Minister of War from 1914 to 1918' },
            nationalOrigin: [
                { claim: 'Turkish military officer', locator: 'lead', excerpt: 'was a Turkish military officer, revolutionary, and convicted war criminal' },
                { claim: 'Father Gagauz or Albanian, mother Tatar', locator: 'Early life and career', excerpt: "Enver's father, Ahmed (c. 1860–1947), was either a Gagauz bridge-keeper in Monastir (Bitola), or an Albanian small town public prosecutor in the Balkans. His mother Ayşe Dilara was a Tatar." },
            ],
            bio: [
                { claim: 'born in Constantinople', locator: 'Early life and career', excerpt: 'İsmail Enver was born in Constantinople (Istanbul) on 23 November 1881.' },
                { claim: 'joined the CUP; Young Turk Revolution leader', locator: 'lead', excerpt: 'While stationed in Ottoman Macedonia, Enver joined the Committee of Union and Progress (CUP)' },
                { claim: 'hero of the revolution', locator: 'lead', excerpt: 'Along with Ahmed Niyazi, Enver was hailed as "hero of the revolution".' },
                { claim: 'stormed the Sublime Porte in January 1913', locator: 'Balkan Wars and 1913 coup', excerpt: 'On 23 January 1913, Enver and CUP leader Mehmed Talaat with a group of fifty Unionists stormed into the Sublime Porte and overthrew the government.' },
                { claim: 'Three Pashas; genocides', locator: 'lead', excerpt: 'Along with Talaat and Djemal, he was one of the Three Pashas that ruled the Ottoman Empire during World War I and one of the principal perpetrators of the Armenian, Greek, and Assyrian genocides.' },
                { claim: 'alliance with Germany; Ottoman entry into the war', locator: 'lead', excerpt: 'He initiated the formation of an alliance with Germany, and was instrumental in the Ottoman entry into World War I.' },
                { claim: 'Sarikamish; blamed Armenians', locator: 'lead', excerpt: 'Enver led a disastrous attack on Russian forces in the Battle of Sarikamish, after which he blamed Armenians for his defeat.' },
                { claim: 'army froze in the mountains', locator: 'Battle of Sarikamish, 1914', excerpt: 'a large portion of the 90,000-strong army froze to death in the Allahüekber Mountains or were killed by the Russians' },
                { claim: 'escaped on a German submarine', locator: 'Armistice and exile', excerpt: 'he escaped to Odessa by boarding a German submarine from Arnavutköy with seven other leaders of the CUP' },
                { claim: 'condemned to death in absentia', locator: 'Armistice and exile', excerpt: 'He was tried in absentia in the Turkish Courts-Martial of 1919–20 for crimes of "plunging the country into war without a legitimate reason, forced deportation of Armenians and leaving the country without permission" and condemned to death.' },
                { claim: 'met Bolshevik leaders in Moscow', locator: 'Armistice and exile', excerpt: 'He also met with Bolshevik leaders, including Georgy Chicherin, Radek, Grigory Zinoviev and Vladimir Lenin.' },
                { claim: 'Baku Congress of the Peoples of the East', locator: 'Armistice and exile', excerpt: 'Between 1 and 8 September 1920, he was in Baku for the Congress of the Peoples of the East' },
                { claim: 'sent to Bukhara, defected to the Basmachi', locator: 'Last years', excerpt: 'In November 1921 he was sent by Lenin to Bukhara in the Bukharan People\'s Soviet Republic to help suppress the Basmachi Revolt against the local pro-Moscow Bolshevik regime. Instead, however, he made secret contacts with some of the rebellion\'s leaders and, along with a small number of followers, defected to the Basmachi side.' },
                { claim: 'Red Army attack near Dushanbe, 4 August 1922', locator: 'Last years', excerpt: 'On 4 August 1922, as he allowed his troops to celebrate Eid al-Adha while retaining a guard of 30 men at his headquarters near the village of Ab-i-Derya near Dushanbe, the Red Army Bashkir cavalry brigade under the command of ethnic Armenian Yakov Melkumov (Hakob Melkumian), launched a surprise attack.' },
                { claim: 'killed in Bukhara fighting the Bolsheviks', locator: 'lead', excerpt: 'He attempted to realise his pan-Turkic ideals by leading the Basmachi Revolt against the Bolsheviks in Bukhara, where he was killed in 1922.' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: 'state-turkey', startYear: 1914, endYear: 1918, primary: true, claim: 'Ottoman War Minister and de facto commander-in-chief', locator: 'lead', excerpt: 'As war minister and de facto Commander-in-Chief, Enver was one of the most powerful figures in the Ottoman government.' },
        ],
        career: [
            ['1908', '청년 튀르크 혁명 지도자', 'Leader of the Young Turk Revolution'],
            ['1913', '내각 청사 습격 쿠데타', 'Raid on the Sublime Porte'],
            ['1914–1918', '오스만 전쟁장관', 'Ottoman War Minister'],
            ['1914', '사르카미시 전투 패배', 'Defeat at Sarıkamış'],
            ['1919–1920', '궐석 사형 선고', 'Sentenced to death in absentia'],
            ['1921–1922', '바스마치 반란 가담', 'Joined the Basmachi revolt'],
        ],
    }),
];
