// Person cards for the East German events (the 1953 uprising and its purge:
// Herrnstadt, Zaisser, Fechner, Wollweber, Matern), see lib.js person().
// Excerpts are verbatim from the cited pages.
const { person } = require('../baltic-1940-1953-20261002/lib');

const EN = t => 'https://en.wikipedia.org/wiki/' + encodeURI(t);
const DE = t => 'https://de.wikipedia.org/wiki/' + encodeURI(t);
const S = {
    herrnstadt: EN('Rudolf_Herrnstadt'),
    deHerrnstadt: DE('Rudolf_Herrnstadt'),
    zaisser: EN('Wilhelm_Zaisser'),
    deZaisser: DE('Wilhelm_Zaisser'),
    fechner: EN('Max_Fechner'),
    deFechner: DE('Max_Fechner'),
    wollweber: EN('Ernst_Wollweber'),
    deWollweber: DE('Ernst_Wollweber'),
    matern: EN('Hermann_Matern'),
    deMatern: DE('Hermann_Matern'),
};

module.exports = [
    person({
        id: 'rudolf-herrnstadt', groupId: 'world-cold-war',
        given: ['루돌프', 'Rudolf'], family: ['헤른슈타트', 'Herrnstadt'], nativeName: 'Rudolf Herrnstadt', years: '1903–1966',
        citizenship: 'east-germany', origin: { code: 'germany', label: { ko: '독일 (유대계)', en: 'German (Jewish family)' } },
        epithet: ['1953년 신노선을 함께 쓰고 울브리히트 퇴진을 꾀하다 숙청된 《노이에스 도이칠란트》 편집장',
            'Editor of Neues Deutschland who helped draft the 1953 New Course, moved against Ulbricht and was purged as a “faction”'],
        bio: ['글라이비츠의 유대계 부유한 집안에서 태어나 《베를리너 타게블라트》 특파원으로 일하며 소련 군사정보국(GRU) 요원이 되었다. 1939년 소련으로 망명해 자유독일 국민위원회의 기관지 편집장을 지냈다. 1945년 귀국해 《베를리너 차이퉁》을 이끌고 《노이에스 도이칠란트》 창간에 참여했으며, 그 편집장으로서 늘 모스크바의 노선을 따랐다. 1953년 6월 차이서와 함께 울브리히트에 맞섰고, 중앙위원회가 승인한 신노선을 함께 썼다. 봉기 뒤 집단지도를 제안했으나 7월 「반당 분파」로 몰려 중앙위원회에서 쫓겨났고, 1954년 1월 당에서 제명되었다. 메르제부르크의 문서고에서 일하다 1966년 죽었고, 1989년에야 복권되었다.',
            'Born into a wealthy Jewish family in Gleiwitz, he became a correspondent for the Berliner Tageblatt and an agent of Soviet military intelligence (GRU). Exiled in the Soviet Union from 1939, he edited the newspaper of the National Committee for a Free Germany. Back in Berlin in 1945 he ran the Berliner Zeitung and helped found Neues Deutschland, whose editor always followed Moscow’s line. In June 1953 he and Zaisser set themselves against Ulbricht, and he helped formulate the New Course approved by the Central Committee. After the uprising he proposed a collective leadership, but in July he was removed from the Central Committee for “anti-party factionalism” and in January 1954 expelled from the SED. He worked at the Central Archives in Merseburg, died in 1966 and was rehabilitated only in 1989.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: [], en: [] },
        sources: [S.herrnstadt, S.deHerrnstadt],
        facts: {
            years: { claim: '1903–1966', locator: 'lead', excerpt: 'Rudolf Herrnstadt (18 March 1903 – 28 August 1966) was a German journalist and communist politician.' },
            citizenship: { claim: 'GDR journalist and SED Central Committee member', locator: 'lead', excerpt: 'From 1950 to 1953 he was a member of the Central Committee (ZK) of the SED and a candidate for the Politburo of the SED.' },
            nationalOrigin: { claim: 'Jewish family in Gleiwitz', locator: 'Life', excerpt: 'Rudolf Herrnstadt came from a Jewish family in the Upper Silesian city of Gleiwitz (now Gliwice, Poland).' },
            bio: [
                { claim: 'Berliner Tageblatt correspondent; GRU agent', locator: 'lead', excerpt: 'worked for the Soviet military intelligence service Glawnoje Raswedywatelnoje Uprawlenije (GRU, "Main Administration for Intelligence"). As a foreign correspondent for the Berliner Tageblatt' },
                { claim: 'Exile in the USSR 1939; editor of Freies Deutschland', locator: 'lead', excerpt: 'He emigrated to the Soviet Union in 1939, days before the Invasion of Poland, where he was active in the fight against the Nazi state as editor-in-chief of the newspaper Freies Deutschland in the National Committee for a Free Germany' },
                { claim: 'Berliner Zeitung and founding of Neues Deutschland', locator: 'lead', excerpt: 'He was editor-in-chief of the Berliner Zeitung, initially in the Soviet occupation zone and from 1949 in the German Democratic Republic (GDR), and played a key role in founding the Berliner Verlag publishers and the left-wing newspaper Neues Deutschland' },
                { claim: 'Followed Moscow’s line as editor', locator: 'Politics', excerpt: 'As editor-in-chief, he always allowed Neues Deutschland to follow the line laid down by Moscow.' },
                { claim: 'With Zaisser against Ulbricht', locator: 'SED Reforms', excerpt: 'Herrnstadt now positioned himself together with the Minister for State Security Wilhelm Zaisser and leading party ideologist, as an opponent of Ulbricht.' },
                { claim: 'Helped formulate the New Course', locator: 'SED Reforms', excerpt: 'On 16 June 1953, the Central Committee approved the New Course, which Herrnstadt helped to formulate' },
                { claim: 'Collective leadership proposal', locator: 'Against Walter Ulbricht', excerpt: 'instead of the all-powerful General Secretary at the top, there was to be a collective leadership' },
                { claim: 'Lost his seats for factionalism', locator: 'Against Walter Ulbricht', excerpt: 'Herrnstadt lost his seats in the Politburo and Central Committee on 26 July 1953 for “anti-party factionalism”.' },
                { claim: 'Expelled January 1954', locator: 'Against Walter Ulbricht', excerpt: 'The SED expelled Herrnstadt on 23 January 1954.' },
                { claim: 'Central Archives in Merseburg', locator: 'Central archives', excerpt: 'On 1 October 1953, Herrnstadt took over management of the Central Archives in Merseburg.' },
                { claim: 'Rehabilitated 1989', locator: 'Rehabilitation', excerpt: 'On 29 November 1989, 23 years after his death, the ZPKK under Werner Eberlein rehabilitated Herrnstadt' },
            ],
        },
        activities: [
            { functionId: 'propaganda', affiliationId: 'party-german-sed', startYear: null, endYear: 1953, primary: true, claim: 'Editor-in-chief of Neues Deutschland until 1953', locator: 'lead', excerpt: 'In the same year, he also lost his position as editor-in-chief of Neues Deutschland.' },
            { functionId: 'political-leadership', affiliationId: 'party-german-sed', startYear: 1950, endYear: 1953, claim: 'SED Central Committee member and Politburo candidate', locator: 'lead', excerpt: 'From 1950 to 1953 he was a member of the Central Committee (ZK) of the SED and a candidate for the Politburo of the SED.' },
            { functionId: 'security', affiliationId: 'state-soviet', startYear: 1930, endYear: null, relation: 'service', claim: 'Recruited as a GRU agent in Prague', locator: 'Education', excerpt: 'His persistence brought him to the notice of Soviet military intelligence, who recruited him as a Red Army GRU agent and gave him the codename "Arbin".' },
        ],
        career: [
            ['1930', 'GRU 요원으로 포섭', 'Recruited as a GRU agent'],
            ['1943', '《자유 독일》 편집장', 'Editor-in-chief of Freies Deutschland'],
            ['1945', '《베를리너 차이퉁》 편집장', 'Editor-in-chief of the Berliner Zeitung'],
            ['1950–1953', '사회주의통일당 중앙위원·정치국 후보위원', 'SED Central Committee member and Politburo candidate'],
            ['1953', '「반당 분파」로 중앙위원회에서 축출', 'Removed from the Central Committee for “anti-party factionalism”'],
            ['1954', '당에서 제명', 'Expelled from the SED'],
            ['1989', '사후 복권', 'Posthumously rehabilitated'],
        ],
    }),
    person({
        id: 'wilhelm-zaisser', groupId: 'world-cold-war',
        given: ['빌헬름', 'Wilhelm'], family: ['차이서', 'Zaisser'], nativeName: 'Wilhelm Zaisser', years: '1893–1958',
        citizenship: 'east-germany', origin: 'germany',
        epithet: ['동독 초대 국가보안부 장관으로 1953년 울브리히트 퇴진을 꾀하다 숙청된 공산주의자',
            'First East German Minister for State Security, purged in 1953 after trying to replace Ulbricht'],
        bio: ['겔젠키르헨에서 헌병 하사의 아들로 태어나 교사가 되었고, 1920년 카프 폭동 때 루르 적군을 지휘했다. 소련 군사정보국(GRU) 요원과 코민테른 군사고문으로 중국 광저우 봉기 등에 관여했고, 스페인 내전에서는 「고메스」라는 이름으로 국제여단을 이끌었다. 1947년 귀국해 사회주의통일당에 들어갔고, 1950년 초대 국가보안부 장관과 정치국원이 되어 슈타지를 키웠다. 1953년 6월 봉기 뒤 헤른슈타트를 제1서기로 세우자고 제안했으나, 울브리히트가 흐루쇼프의 지지를 얻자 7월 장관직과 모든 직위를 잃고 당에서 제명되었다. 번역가로 지내다 1958년 동베를린에서 죽었고, 1990년 뒤에 복권되었다.',
            'Born in Gelsenkirchen to a gendarmerie sergeant’s family, he trained as a teacher and was a military leader of the Red Ruhr Army during the Kapp Putsch of 1920. As a GRU agent and Comintern military adviser he co-organised the Guangzhou Uprising in China, and in the Spanish Civil War, as “Gomez”, he led the International Brigades. He returned to Germany in 1947, joined the SED, and in 1950 became the first Minister for State Security and a Politburo member, building up the Stasi. After the uprising of June 1953 he moved to replace Ulbricht with Herrnstadt, but once Ulbricht had Khrushchev’s backing he lost his ministry and all his posts in July and was expelled from the party. He worked as a translator, died in East Berlin in 1958 and was rehabilitated after 1990.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: [], en: ['General Gomez'] },
        sources: [S.zaisser, S.deZaisser],
        facts: {
            years: { claim: '1893–1958', locator: 'lead', excerpt: 'Wilhelm Zaisser (20 June 1893 – 3 March 1958) was a German communist politician and statesman' },
            citizenship: { claim: 'First Minister for State Security of the GDR', locator: 'lead', excerpt: 'served as the founder and first Minister for State Security of the German Democratic Republic (East Germany) from 1950 to 1953' },
            nationalOrigin: { claim: 'German communist born in Gelsenkirchen', locator: 'lead', excerpt: 'was a German communist politician and statesman' },
            bio: [
                { claim: 'Born in Gelsenkirchen to a gendarmerie sergeant; teacher', locator: 'Early life', excerpt: 'Born in Gelsenkirchen, Westphalia in to the family of a gendarmerie sergeant, Zaisser studied to become a teacher from 1910 to 1913 in Essen.' },
                { claim: 'Red Ruhr Army leader during the Kapp Putsch', locator: 'Early life', excerpt: 'During the Kapp Putsch in 1920, he was a military leader of the fledgling Red Ruhr Army' },
                { claim: 'Comintern adviser in China; Guangzhou Uprising', locator: 'Career in Soviet Intelligence', excerpt: 'serving as a military advisor in China from 1927 to 1930 (co-organizing the Guangzhou Uprising alongside Heinz Neumann)' },
                { claim: 'Spain as “Gomez”', locator: 'Career in Soviet Intelligence', excerpt: 'In 1936, Zaisser traveled to the Second Spanish Republic under the covert identity of "Gomez."' },
                { claim: 'Led the International Brigades', locator: 'Career in Soviet Intelligence', excerpt: 'in 1937, he became leader of all the pro-Republican International Brigades operating in Spain' },
                { claim: 'Returned 1947 and joined the SED', locator: 'Government', excerpt: 'In 1947, Zaisser returned to Germany and joined the Socialist Unity Party (SED).' },
                { claim: 'Politburo and Ministry of State Security 1950', locator: 'Government', excerpt: 'In 1950, Zaisser gained membership in East Germany\'s Politburo and the Central Committee of the SED' },
                { claim: 'Built the Stasi', locator: 'Government', excerpt: 'Zaisser built the Stasi into a powerful organization' },
                { claim: 'Motion to replace Ulbricht with Herrnstadt', locator: 'Government', excerpt: 'Zaisser introduced a motion to replace Ulbricht with Rudolf Herrnstadt as First Secretary' },
                { claim: 'Removed once Ulbricht had Khrushchev’s support', locator: 'Government', excerpt: 'Once he knew he had the complete support of new Soviet Premier Nikita Khrushchev, Ulbricht removed Zaisser and all other critics of his leadership from the SED\'s ruling Politburo.' },
                { claim: 'Stripped of posts and expelled', locator: 'Government', excerpt: 'Zaisser was stripped of all his posts, expelled from the SED, and classified as an enemy of the people.' },
                { claim: 'Translator; died in East Berlin 1958', locator: 'Death and legacy', excerpt: 'Wilhelm Zaisser spent his final years working as a translator and at the Institute of Marxism and Leninism. He died in obscurity in East Berlin in 1958.' },
                { claim: 'Rehabilitated after 1990', locator: 'Death and legacy', excerpt: 'Only after the 1989 Peaceful Revolution and German Reunification in 1990, was Zaisser formally rehabilitated.' },
            ],
        },
        activities: [
            { functionId: 'security', affiliationId: 'state-east-germany', startYear: 1950, endYear: 1953, primary: true, claim: 'First Minister for State Security', locator: 'lead', excerpt: 'served as the founder and first Minister for State Security of the German Democratic Republic (East Germany) from 1950 to 1953' },
            { functionId: 'political-leadership', affiliationId: 'party-german-sed', startYear: 1950, endYear: 1953, claim: 'SED Politburo member', locator: 'Government', excerpt: 'In 1950, Zaisser gained membership in East Germany\'s Politburo and the Central Committee of the SED' },
            { functionId: 'military', affiliationId: 'spanish-republic', startYear: 1936, endYear: 1938, claim: 'Military adviser and International Brigades commander in Spain', locator: 'Career in Soviet Intelligence', excerpt: 'On behalf of the Soviets, Zaisser became a military advisor to the Spanish Republican Army' },
            { functionId: 'military', affiliationId: 'comintern', startYear: 1927, endYear: 1932, claim: 'Comintern military adviser in China and Czechoslovakia', locator: 'Career in Soviet Intelligence', excerpt: 'Starting in 1927, Zaisser worked almost exclusively for the Executive Committee of the Comintern' },
        ],
        career: [
            ['1920', '카프 폭동 때 루르 적군 지휘', 'Red Ruhr Army leader during the Kapp Putsch'],
            ['1927–1930', '코민테른 군사고문(중국)', 'Comintern military adviser in China'],
            ['1936–1938', '스페인 내전 국제여단 지휘(「고메스」)', 'International Brigades commander in Spain (“Gomez”)'],
            ['1950–1953', '동독 국가보안부 장관, 정치국원', 'GDR Minister for State Security; Politburo member'],
            ['1953', '모든 직위에서 해임, 당에서 제명', 'Stripped of all posts and expelled from the SED'],
        ],
    }),
    person({
        id: 'max-fechner', groupId: 'world-cold-war',
        given: ['막스', 'Max'], family: ['페히너', 'Fechner'], nativeName: 'Max Fechner', years: '1892–1973',
        citizenship: 'east-germany', origin: 'germany',
        epithet: ['파업 노동자 처벌에 반대했다가 1953년 해임·투옥된 동독 초대 법무장관',
            'First East German justice minister, dismissed and imprisoned in 1953 after opposing the prosecution of striking workers'],
        bio: ['베를린의 공구공 출신으로 1910년 사회민주당에 들어갔고 1928~1933년 프로이센 주의회 의원을 지냈다. 나치 시기 저항 단체에 가담해 두 차례 투옥되었다. 전후 사회민주당과 공산당의 강제 합당을 지지해 사회주의통일당 중앙위원이 되었고, 1949년 10월 동독 초대 법무장관이 되었다. 글라도프 일당 재판에서 사형이 가능하도록 성인 형법을 위법하게 적용하게 했다. 1953년 6월 30일 《노이에스 도이칠란트》 인터뷰에서 6월 17일 파업 참가자를 혐의만으로 처벌하지 않겠다고 밝혔다가 「국가와 당의 적」으로 몰려 해임·제명·체포되었고, 징역 8년을 선고받았다. 1956년 석방·사면되고 1958년 복당했으며, 1973년 죽었다.',
            'A toolmaker from Berlin, he joined the SPD in 1910 and sat in the Prussian Landtag from 1928 to 1933. Under the Nazis he took part in a resistance group and was twice imprisoned. After the war he supported the forced merger of the SPD and KPD, sat on the SED’s Central Committee, and in October 1949 became the GDR’s first Minister of Justice. In the trial of the Gladow gang he had adult criminal law applied unlawfully so that a death sentence was possible. In an interview with Neues Deutschland on 30 June 1953 he said that members of the 17 June strike leadership would not be punished on mere suspicion; denounced as an “enemy of the state and the party”, he was dismissed, expelled and arrested, and sentenced to eight years. Released and pardoned in 1956, readmitted to the party in 1958, he died in 1973.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: [], en: [] },
        sources: [S.fechner, S.deFechner],
        facts: {
            years: { claim: '1892–1973', locator: 'lead', excerpt: 'Max Fechner (27 July 1892 – 13 September 1973) was a German politician' },
            citizenship: { claim: 'GDR Minister of Justice 1949–1953', locator: 'lead', excerpt: 'was a German politician who served as Minister of Justice of East Germany from 1949 to 1953' },
            nationalOrigin: { claim: 'German politician born in Berlin', locator: 'Life and career', excerpt: 'Fechner was born in Berlin and was a trained tool maker.' },
            bio: [
                { claim: 'Toolmaker from Berlin', locator: 'Life and career', excerpt: 'Fechner was born in Berlin and was a trained tool maker.' },
                { claim: 'SPD 1910; Prussian Landtag 1928–1933', locator: 'Life and career', excerpt: 'He joined the SPD in 1910' },
                { claim: 'Prussian Landtag 1928–1933', locator: 'Life and career', excerpt: 'member of the Landtag of Prussia from 1928 to 1933' },
                { claim: 'Resistance; jailed twice', locator: 'Life and career', excerpt: 'Fechner participated in the social-democratic resistance group led by Franz Künstler, and was jailed in 1933–1934 and 1944–1945 by the Nazi regime.' },
                { claim: 'Supported the forced merger', source: S.deFechner, locator: 'Nachkriegszeit', excerpt: 'Im Zuge der Zwangsvereinigung von SPD und KPD zur SED gehörte er zu den Befürwortern der Vereinigung.' },
                { claim: 'SED Central Committee', locator: 'Life and career', excerpt: 'After the war, Fechner became a member of the SED, he was elected to its Executive Committee and Central Committee.' },
                { claim: 'Justice minister from October 1949', locator: 'Life and career', excerpt: 'was from October 1949 to July 1953 Minister of Justice of the newly created GDR' },
                { claim: 'Gladow trial: adult law applied unlawfully for a death sentence', source: S.deFechner, locator: 'Nachkriegszeit', excerpt: 'gegen die Ergebnisse des eigenen Gutachters völlig rechtswidrig Erwachsenenstrafrecht anwenden ließ, weil nur so das gewünschte Todesurteil möglich wurde' },
                { claim: 'Interview of 30 June 1953: no punishment on mere suspicion', source: S.deFechner, locator: 'Verhaftung', excerpt: 'Ohne Nachweis werde es keine Bestrafung von Angehörigen der Streikleitung und von Rädelsführern „auf bloßen Verdacht oder schweren Verdacht hin“ geben.' },
                { claim: 'Denounced, dismissed, expelled, arrested', locator: 'Life and career', excerpt: 'Consequently, he was denounced as an "enemy of the state and the party", lost his ministerial charge, was expelled from the SED and arrested.' },
                { claim: 'Sentenced to eight years', locator: 'Life and career', excerpt: 'he was sentenced to eight years of prison by the Supreme Court' },
                { claim: 'Released 1956, amnestied; readmitted 1958', locator: 'Life and career', excerpt: 'He was however released on 24 June 1956, and two days later amnestied. In June 1958, he was reinstated as a SED member.' },
                { claim: 'Died 1973', locator: 'Life and career', excerpt: 'He died, aged 81, in Schöneiche, Brandenburg in 1973.' },
            ],
        },
        activities: [
            { functionId: 'law', affiliationId: 'state-east-germany', startYear: 1949, endYear: 1953, primary: true, claim: 'GDR Minister of Justice', locator: 'Life and career', excerpt: 'was from October 1949 to July 1953 Minister of Justice of the newly created GDR' },
            { functionId: 'political-leadership', affiliationId: 'party-german-sed', startYear: 1946, endYear: 1953, claim: 'SED Executive and Central Committee member', locator: 'Life and career', excerpt: 'After the war, Fechner became a member of the SED, he was elected to its Executive Committee and Central Committee.' },
            { functionId: 'legislature', affiliationId: 'party-german-spd', relation: 'membership', startYear: 1928, endYear: 1933, claim: 'SPD deputy in the Prussian Landtag', locator: 'Life and career', excerpt: 'member of the Landtag of Prussia from 1928 to 1933' },
        ],
        career: [
            ['1910', '사회민주당 입당', 'Joined the SPD'],
            ['1928–1933', '프로이센 주의회 의원', 'Member of the Prussian Landtag'],
            ['1949–1953', '동독 법무장관', 'GDR Minister of Justice'],
            ['1953', '해임·제명·체포', 'Dismissed, expelled and arrested'],
            ['1956', '석방과 사면', 'Released and pardoned'],
            ['1958', '복당', 'Readmitted to the SED'],
        ],
    }),
    person({
        id: 'ernst-wollweber', groupId: 'world-cold-war',
        given: ['에른스트', 'Ernst'], family: ['볼베버', 'Wollweber'], nativeName: 'Ernst Wollweber', years: '1898–1967',
        citizenship: 'east-germany', origin: 'germany',
        epithet: ['전간기 반파시즘 파괴공작을 조직했고 1953~1957년 슈타지를 이끈 공산주의자',
            'Communist who ran an anti-fascist sabotage network before the war and headed the Stasi from 1953 to 1957'],
        bio: ['하노버주 뮌덴에서 태어나 1918년 수병 반란에 가담했고 1919년 공산당에 들어가 당 군사조직을 이끌었다. 1932~1933년 제국의회 의원을 지냈다. 망명 중 1936~1940년 「볼베버 동맹」을 조직해 파시스트 국가들의 선박에 21건의 파괴공작을 벌였고, 스페인 공화국군에 무기를 댔다. 1946년 귀국해 해운 행정을 맡았다. 1953년 7월 차이서가 물러나 국가보안부가 국가보안청으로 격하되자 그 수장이 되었고, 1955년 11월 다시 국가보안부 장관이 되었다. 울브리히트·호네커와 충돌하고 시르데반 편에 섰다가 1957년 물러났고, 1958년 「분파 활동」으로 중앙위원회에서 쫓겨났다. 1967년 동베를린에서 죽었다.',
            'Born in Münden in the Province of Hanover, he took part in the sailors’ revolt of 1918, joined the KPD in 1919 and led party military wings; he sat in the Reichstag in 1932–1933. In exile he organised the “Wollweber League” in 1936–1940, which carried out 21 known acts of sabotage against ships of fascist nations, and supplied arms to the Spanish Republicans. Back in Germany in 1946 he ran shipping administration. In July 1953, when Zaisser was removed and the Ministry for State Security was downgraded to a State Secretariat, he became its head, and in November 1955 Minister of State Security again. He clashed with Ulbricht and Honecker and sided with Schirdewan, resigned in 1957, and in 1958 was removed from the Central Committee for “factional activity”. He died in East Berlin in 1967.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: [], en: ['Ernst Friedrich Wollweber'] },
        sources: [S.wollweber, S.deWollweber],
        facts: {
            years: { claim: '1898–1967', locator: 'lead', excerpt: 'Ernst Friedrich Wollweber (29 October 1898 – 3 May 1967) was a German politician' },
            citizenship: { claim: 'GDR Minister of State Security', locator: 'lead', excerpt: 'was State Secretary of State Security from 1953 to 1955 and Minister of State Security of East Germany from 1955 to 1957' },
            nationalOrigin: { claim: 'German politician born in Münden, Hanover', locator: 'Biography', excerpt: 'Wollweber was born in Hannoversch Münden, Hanover on 29 October 1898.' },
            bio: [
                { claim: 'Sailors’ revolt of 1918; KPD 1919', locator: 'Biography', excerpt: 'In November 1918, Wollweber participated in the Wilhelmshaven mutiny' },
                { claim: 'Joined the KPD in 1919', locator: 'Biography', excerpt: 'joined the Communist Party of Germany in 1919' },
                { claim: 'Led KPD military wings', locator: 'Biography', excerpt: 'Two years later, Wollweber became a leader of the military wings of the KPD in Hesse-Waldeck, Thuringia, and Silesia.' },
                { claim: 'Reichstag 1932–1933', locator: 'Biography', excerpt: 'from 1932 to 1933 was a representative of the Reichstag' },
                { claim: 'Wollweber League, 21 acts of sabotage', locator: 'Biography', excerpt: 'The League conducted 21 known acts of sabotage against the ships of fascist nations sailing from Scandinavian and other northern European ports.' },
                { claim: 'Organised the league 1936–1940', locator: 'Biography', excerpt: 'From then to 1940, Wollweber organized the "Organisation Against Fascism and in Support of the USSR", better known as the Wollweber League.' },
                { claim: 'Arms to the Spanish Republicans', locator: 'Biography', excerpt: 'In 1937, Wollweber became a weapons supplier to the Republican forces in the Spanish Civil War.' },
                { claim: 'Returned 1946; shipping administration', locator: 'Biography', excerpt: 'A year later, he became leader of the central management for shipping' },
                { claim: 'Returned 1946 and joined the SED', locator: 'Biography', excerpt: 'After World War II, Wollweber returned to Germany and joined the Socialist Unity Party of Germany in 1946.' },
                { claim: 'Head of state security after Zaisser, downgraded', locator: 'Biography', excerpt: 'he became State Secretary of State Security (the Stasi) after Wilhelm Zaisser was removed from the post as Minister of State Security and the Stasi was downgraded to a State Secretariat' },
                { claim: 'Minister again November 1955', locator: 'Biography', excerpt: 'In November 1955, Wollweber was made Minister of State Security, after the Stasi had been restored to a ministry.' },
                { claim: 'Clashed with Ulbricht and Honecker; sided with Schirdewan', locator: 'Biography', excerpt: 'Wollweber had unwisely taken Schirdewan\'s side' },
                { claim: 'Forced to resign 1957', locator: 'Biography', excerpt: 'In 1957, Wollweber was forced to resign as head of the Stasi and was succeeded by his deputy, Erich Mielke.' },
                { claim: 'Removed from the Central Committee for factional activity, 1958', source: S.deWollweber, locator: 'Deutsche Demokratische Republik', excerpt: 'das ZK der SED schloss ihn zusammen mit Karl Schirdewan wegen „Fraktionstätigkeit“ aus' },
                { claim: 'Died in East Berlin 1967', source: S.deWollweber, locator: 'Einleitung', excerpt: '† 3. Mai 1967 in Ost-Berlin' },
            ],
        },
        activities: [
            { functionId: 'security', affiliationId: 'state-east-germany', startYear: 1953, endYear: 1957, primary: true, claim: 'State Secretary, then Minister of State Security', locator: 'lead', excerpt: 'was State Secretary of State Security from 1953 to 1955 and Minister of State Security of East Germany from 1955 to 1957' },
            { functionId: 'military', affiliationId: 'party-german-communist', relation: 'membership', startYear: 1923, endYear: 1924, claim: 'Leader of KPD military wings', locator: 'Biography', excerpt: 'Two years later, Wollweber became a leader of the military wings of the KPD in Hesse-Waldeck, Thuringia, and Silesia.' },
            { functionId: 'legislature', affiliationId: 'party-german-communist', relation: 'membership', startYear: 1932, endYear: 1933, claim: 'KPD Reichstag deputy', locator: 'Biography', excerpt: 'from 1932 to 1933 was a representative of the Reichstag' },
            { functionId: 'industry', affiliationId: 'state-east-germany', startYear: 1947, endYear: 1953, claim: 'Shipping administration and transport state secretary', locator: 'Biography', excerpt: 'in 1950, Undersecretary of State for the Ministry of Traffic in East Germany' },
        ],
        career: [
            ['1918', '수병 반란 가담', 'Took part in the sailors’ revolt'],
            ['1932–1933', '제국의회 의원(공산당)', 'KPD Reichstag deputy'],
            ['1936–1940', '「볼베버 동맹」 파괴공작 조직', 'Organised the Wollweber League sabotage network'],
            ['1953–1955', '국가보안청장(차관급)', 'State Secretary of State Security'],
            ['1955–1957', '국가보안부 장관', 'Minister of State Security'],
            ['1958', '중앙위원회에서 축출', 'Removed from the Central Committee'],
        ],
    }),
    person({
        id: 'hermann-matern', groupId: 'world-cold-war',
        given: ['헤르만', 'Hermann'], family: ['마테른', 'Matern'], nativeName: 'Hermann Matern', years: '1893–1971',
        citizenship: 'east-germany', origin: 'germany',
        epithet: ['당 중앙통제위원장으로 1953년 울브리히트 편에 선 사회주의통일당 정치국원',
            'SED Politburo member and chairman of the Central Party Control Commission who stood by Ulbricht in 1953'],
        bio: ['부르크에서 사회민주당원 노동자의 아들로 태어나 무두장이로 일했고, 1차 세계대전에 반대해 사회민주당을 떠났다. 독립사회민주당을 거쳐 공산당에 들어갔고 마그데부르크·동프로이센 지구 지도자를 지냈다. 1933년 체포되었다가 탈옥해 망명했고, 소련에서 자유독일 국민위원회에 참여했다. 1945년 아커만 그룹과 함께 돌아와 1946년까지 작센 공산당 제1서기를 지냈다. 1948년부터 죽을 때까지 사회주의통일당 중앙당통제위원회 위원장으로 당 규율을 맡았고 정치국원·인민의회 부의장을 지냈다. 1953년 봉기 뒤 정치국 다수가 울브리히트를 내치려 할 때 호네커와 함께 그의 편에 섰다. 1971년 동베를린에서 죽었다.',
            'Born in Burg, the son of a Social Democratic worker, he worked as a tanner and left the SPD when it voted for war loans. He went through the USPD into the KPD and led its Magdeburg and East Prussia districts. Arrested in 1933, he escaped and went into exile, joining the National Committee for a Free Germany in the Soviet Union. He returned in 1945 with Anton Ackermann’s group and until 1946 was first secretary of the KPD in Saxony. From 1948 until his death he chaired the SED’s Central Party Control Commission, responsible for party discipline, and was a Politburo member and vice-president of the People’s Chamber. After the 1953 uprising, when a Politburo majority wanted to remove Ulbricht, he and Honecker alone stayed loyal. He died in East Berlin in 1971.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: [], en: [] },
        sources: [S.matern, S.deMatern, S.herrnstadt],
        facts: {
            years: { claim: '1893–1971', locator: 'lead', excerpt: 'Hermann Matern (17 June 1893 – 24 January 1971) was a German communist politician' },
            citizenship: { claim: 'SED functionary in East Germany', locator: 'lead', excerpt: 'was a German communist politician and high ranking functionary of the Socialist Unity Party (SED) in East Germany' },
            nationalOrigin: { claim: 'German communist born in Burg', source: S.deMatern, locator: 'Einleitung', excerpt: 'Hermann Matern (* 17. Juni 1893 in Burg; † 24. Januar 1971 in Berlin) war ein deutscher kommunistischer Politiker.' },
            bio: [
                { claim: 'Son of a Social Democratic worker; tanner', locator: 'Early political activities', excerpt: 'Matern was the son of a social democratic worker and himself worked as a tanner.' },
                { claim: 'Left the SPD over war loans', locator: 'Early political activities', excerpt: 'He resigned from the SPD when the party accepted war loans.' },
                { claim: 'USPD then KPD', locator: 'Early political activities', excerpt: 'In 1918, he joined the Independent Social Democratic Party (USPD)' },
                { claim: 'Magdeburg and East Prussia district leader', locator: 'Early political activities', excerpt: 'he was transferred to serve as political leader of the East Prussia district until 1933' },
                { claim: 'Arrested 1933, escaped', locator: 'Arrest and exile', excerpt: 'After the rise of the Nazi regime, Matern was arrested in 1933. In September 1934 he managed to escape from the Stettin-Altdamm prison.' },
                { claim: 'National Committee for a Free Germany', locator: 'Arrest and exile', excerpt: 'In the spring of 1941 he moved to Moscow. He became a member of the National Committee for Free Germany.' },
                { claim: 'Returned with Ackermann’s group', locator: 'Return to Germany', excerpt: 'On 1 May 1945 Matern returned to Germany with Anton Ackermann\'s group.' },
                { claim: 'First secretary of the KPD in Saxony', locator: 'Return to Germany', excerpt: 'Until 1946 he was the first secretary of the district leadership of the KPD in Saxony.' },
                { claim: 'Chaired the Control Commission until his death', locator: 'lead', excerpt: 'From the nation\'s founding in 1949 until his death in 1971 he served as chairman of the Central Party Control Commission, deputy president of the Volkskammer' },
                { claim: 'ZPKK chairman from 1948; Politburo 1950', locator: 'Return to Germany', excerpt: 'was made chairman of the Central Party Control Commission (ZPKK) on 21 October 1948 and a member of the Politburo of the Central Committee of the SED in 1950' },
                { claim: 'Responsible for party discipline', source: S.herrnstadt, locator: 'SED Reforms', excerpt: 'Hermann Matern, who as chairman of the Central Party Control Commission (ZPKK) was responsible for internal party discipline' },
                { claim: 'Loyal to Ulbricht with Honecker in 1953', locator: 'Return to Germany', excerpt: 'only Matern and one other, Erich Honecker, remained loyal to Ulbricht' },
                { claim: 'Died in East Berlin 1971', locator: 'Death and legacy', excerpt: 'Matern died in East Berlin on 24 January 1971.' },
            ],
        },
        activities: [
            { functionId: 'political-leadership', affiliationId: 'party-german-sed', startYear: 1948, endYear: 1971, primary: true, claim: 'Chairman of the Central Party Control Commission; Politburo member', locator: 'Return to Germany', excerpt: 'was made chairman of the Central Party Control Commission (ZPKK) on 21 October 1948 and a member of the Politburo of the Central Committee of the SED in 1950' },
            { functionId: 'political-leadership', affiliationId: 'party-german-communist', relation: 'membership', startYear: 1945, endYear: 1946, claim: 'First secretary of the KPD in Saxony', locator: 'Return to Germany', excerpt: 'Until 1946 he was the first secretary of the district leadership of the KPD in Saxony.' },
            { functionId: 'legislature', affiliationId: 'state-east-germany', startYear: 1950, endYear: 1971, claim: 'Vice-president of the People’s Chamber', locator: 'lead', excerpt: 'deputy president of the Volkskammer, and leader of the SED in the Volkskammer' },
        ],
        career: [
            ['1918', '독립사회민주당 입당, 노동자·병사 평의회', 'Joined the USPD; workers’ and soldiers’ council'],
            ['1931–1933', '공산당 동프로이센 지구 지도자', 'KPD political leader in East Prussia'],
            ['1945–1946', '작센 공산당 제1서기', 'First secretary of the KPD in Saxony'],
            ['1948–1971', '사회주의통일당 중앙당통제위원장', 'Chairman of the SED Central Party Control Commission'],
            ['1950–1971', '정치국원', 'Politburo member'],
        ],
    }),
];
