// Person cards for the Soviet zone and GDR events (KPD/SED functionaries, the
// Western SPD and the zone's CDU leaders, SMAD's propaganda chief), see lib.js
// person(). Excerpts are verbatim from the cited pages.
const { person } = require('../baltic-1940-1953-20261002/lib');

const wiki = (lang, t) => `https://${lang}.wikipedia.org/wiki/` + encodeURI(t);
const S = {
    ackermann: wiki('en', 'Anton_Ackermann'),
    deAckermann: wiki('de', 'Anton_Ackermann'),
    schumacher: wiki('en', 'Kurt_Schumacher'),
    deSchumacher: wiki('de', 'Kurt_Schumacher'),
    kaiser: wiki('en', 'Jakob_Kaiser'),
    deKaiser: wiki('de', 'Jakob_Kaiser'),
    nuschke: wiki('en', 'Otto_Nuschke'),
    deNuschke: wiki('de', 'Otto_Nuschke'),
    tiulpanov: wiki('en', 'Sergei_Tiulpanov'),
    deTiulpanov: wiki('de', 'Sergei_Iwanowitsch_Tjulpanow'),
    ruTiulpanov: wiki('ru', 'Тюльпанов,_Сергей_Иванович'),
};

module.exports = [
    person({
        id: 'anton-ackermann', groupId: 'world-cold-war',
        given: ['안톤', 'Anton'], family: ['아커만', 'Ackermann'], nativeName: 'Anton Ackermann', years: '1905–1973',
        citizenship: 'east-germany', origin: 'germany',
        epithet: ['1945년 공산당 호소문을 쓰고 「독일 특유의 사회주의 길」을 내세운 동독 공산주의자',
            'German communist who drafted the KPD’s 1945 appeal and argued for a “special German road to socialism”'],
        bio: ['작센 탈하임의 양말공 집안에서 태어나 1926년 독일 공산당에 들어갔고, 모스크바 레닌 학교를 다녔다. 나치 집권 뒤 지하 활동과 망명을 거쳐 스페인 내전의 국제여단 정치학교를 이끌었고, 모스크바에서 자유독일 방송을 맡았다. 1945년 작센으로 파견된 공산당 선발 그룹을 이끌었고, 1945년 6월 11일 공산당 호소문 초안을 썼다. 1946년 프롤레타리아 독재 없이도 독일에서 사회주의를 세울 수 있다는 「독일 특유의 사회주의 길」을 내세웠으나, 1948년 티토-스탈린 결렬 뒤 이를 철회해야 했다. 외무차관과 대외정보기관 책임자를 지냈고, 1953년 차이서를 지지했다는 이유로 모든 직책에서 쫓겨났다. 1973년 암 투병 중 스스로 목숨을 끊었다.',
            'The son of a hosier from Thalheim in Saxony, he joined the KPD in 1926 and attended the International Lenin School in Moscow. After underground work and exile under the Nazis he directed a political school of the International Brigades in the Spanish Civil War, and in Moscow ran the “Free Germany” radio station. In 1945 he led the KPD group sent to Saxony and drafted the party’s appeal of 11 June 1945. In 1946 he argued that socialism could be built in Germany without a preceding dictatorship of the proletariat, a “special German road to socialism” he had to recant after Tito’s break with Stalin in 1948. He served as deputy foreign minister and first head of the GDR’s foreign intelligence service, and in 1953 was stripped of all posts for supporting Zaisser. Gravely ill with cancer, he took his own life in 1973.'],
        fate: ['suicide', '암 투병 중 자살', 'Suicide while ill with cancer'],
        aliases: { ko: [], en: ['Eugen Hanisch'] },
        sources: [S.ackermann, S.deAckermann],
        facts: {
            years: { claim: '1905–1973', locator: 'lead', excerpt: '25 November 1905 – 4 May 1973' },
            citizenship: { claim: 'German communist; leading KPD and SED functionary', locator: 'lead', excerpt: 'was a German communist politician who was a leading functionary of the Communist Party of Germany (KPD) and the Socialist Unity Party of Germany (SED)' },
            nationalOrigin: { claim: 'German politician born in Thalheim in the Erzgebirge', source: S.deAckermann, locator: 'Einleitung', excerpt: '* 25. Dezember 1905 in Thalheim/Erzgeb.; † 4. Mai 1973 in Ost-Berlin) war ein deutscher Politiker (KPD, SED)' },
            bio: [
                { claim: 'son of a hosier', locator: 'Weimar era', excerpt: 'Ackermann, the son of a hosier, also worked as a hosier and a labourer after completing elementary school.' },
                { claim: 'joined the KPD in 1926', locator: 'Weimar era', excerpt: 'In 1926 he joined the Communist Party of Germany.' },
                { claim: 'International Lenin School', locator: 'Weimar era', excerpt: 'From 1929 to 1931, Ackermann attended the International Lenin School in Moscow' },
                { claim: 'underground work 1933–1935 and exile in Prague', locator: 'Nazi era', excerpt: 'After the Nazis entered government, Ackermann worked illegally for the now-banned KPD in Berlin from 1933 to 1935' },
                { claim: 'International Brigades political school', locator: 'Nazi era', excerpt: 'In 1937, during the Spanish Civil War, Ackermann worked as director of the Political School of the International Brigades in Benicàssim.' },
                { claim: 'Free Germany radio', locator: 'Nazi era', excerpt: "From 1941 to 1945 he directed the 'Free Germany' radio station." },
                { claim: 'led the KPD initiative group in Saxony', source: S.deAckermann, locator: 'Sowjetische Besatzungszone', excerpt: 'Er leitete eine Initiativgruppe der KPD, um die Partei in Sachsen neu zu gründen.' },
                { claim: 'author of the draft of the KPD appeal of 11 June 1945', source: S.deAckermann, locator: 'Sowjetische Besatzungszone', excerpt: 'So war er Autor des Entwurfs und Mitunterzeichner des Aufrufs der KPD vom 11. Juni 1945.' },
                { claim: 'special German road without dictatorship of the proletariat', source: S.deAckermann, locator: 'Sowjetische Besatzungszone', excerpt: 'vertrat er die These, dass der Sozialismus in Deutschland ohne eine vorausgehende „Diktatur des Proletariats“ aufgebaut werden könne' },
                { claim: 'recanted after the Tito–Stalin split', source: S.deAckermann, locator: 'Sowjetische Besatzungszone', excerpt: 'Nachdem sich Jugoslawien unter Führung von Josip Broz Tito 1948 von Stalin losgesagt hatte, musste Ackermann seine These vom „besonderen deutschen Weg zum Sozialismus“ widerrufen.' },
                { claim: 'deputy foreign minister', locator: 'East Germany', excerpt: 'From 1949 to 1953, Ackermann was the Deputy Minister of Foreign Affairs.' },
                { claim: 'first head of the foreign intelligence service', locator: 'lead', excerpt: "He served as the first director of the Institute for Economic Research, East Germany's foreign intelligence service, from 1951 to 1952" },
                { claim: 'removed from all posts for supporting Zaisser', source: S.deAckermann, locator: 'DDR', excerpt: 'Weil er Wilhelm Zaisser unterstützte, wurde er bei dessen Sturz im September 1953 aller Ämter enthoben' },
                { claim: 'suicide while ill with cancer', locator: 'Death and Burial', excerpt: 'On 4 May 1973, Anton Ackermann, who was by then suffering terribly from cancer, committed suicide at the age of 67.' },
            ],
        },
        activities: [
            { functionId: 'political-leadership', affiliationId: 'party-german-communist', startYear: 1935, endYear: 1946, claim: 'KPD central committee and Politburo candidate from 1935; head of the Saxony group in 1945', locator: 'Nazi era', excerpt: "At the KPD's Brussels Conference in October 1935, he was elected to the Party's central committee and as a candidate member of the Politbüro." },
            { functionId: 'propaganda', affiliationId: 'party-german-sed', startYear: 1946, endYear: 1953, primary: true, claim: 'SED party executive and central secretariat; programme author; Politburo candidate from 1949', source: S.deAckermann, locator: 'Sowjetische Besatzungszone', excerpt: 'Auf dem Vereinigungsparteitag im April 1946 wurde Ackermann in Parteivorstand und Zentralsekretariat der SED gewählt' },
            { functionId: 'diplomacy', affiliationId: 'state-east-germany', startYear: 1949, endYear: 1953, claim: 'deputy foreign minister, briefly acting foreign minister in 1953', locator: 'East Germany', excerpt: 'After the arrest of his superior, Georg Dertinger, Ackermann briefly succeeded him as Minister.' },
            { functionId: 'security', affiliationId: 'state-east-germany', startYear: 1951, endYear: 1952, claim: 'first director of the foreign intelligence service', locator: 'lead', excerpt: "He served as the first director of the Institute for Economic Research, East Germany's foreign intelligence service, from 1951 to 1952" },
        ],
        career: [
            ['1926', '독일 공산당 입당', 'Joined the KPD'],
            ['1935', '공산당 중앙위원, 정치국 후보위원', 'KPD Central Committee member and Politburo candidate'],
            ['1945', '작센 파견 공산당 그룹 책임자, 6월 11일 호소문 초안', 'Head of the KPD group in Saxony; drafted the 11 June appeal'],
            ['1946', '사회주의통일당 중앙서기국원', 'Member of the SED Central Secretariat'],
            ['1949–1953', '외무차관', 'Deputy foreign minister'],
            ['1953', '모든 직책에서 해임', 'Removed from all posts'],
        ],
    }),
    person({
        id: 'kurt-schumacher', groupId: 'world-cold-war',
        given: ['쿠르트', 'Kurt'], family: ['슈마허', 'Schumacher'], nativeName: 'Kurt Schumacher', years: '1895–1952',
        citizenship: 'germany', origin: 'germany',
        epithet: ['나치 수용소에서 10년을 버티고 전후 서독 사회민주당을 이끌며 공산당과의 통합을 거부한 지도자',
            'SPD leader who survived ten years in Nazi camps and, after the war, refused the merger with the Communists'],
        bio: ['서프로이센 쿨름에서 태어나 1차 세계대전에서 오른팔을 잃었고, 1918년 사회민주당에 들어갔다. 뷔르템베르크 주의회와 제국의회 의원으로 나치에 맞섰다. 1933년 7월 체포되어 활동 포기 서약을 거부하고 10년 동안 여러 강제수용소에 갇혔다. 1945년 하노버에서 당을 재건했고, 소련 점령지구의 그로테볼이 내세운 공산당과의 통합을 거부하며 공산당을 「붉게 칠한 나치」라 불렀다. 1946년 당 의장, 1949년 연방의회 첫 야당 지도자가 되어 중공업 국유화와 통일 독일을 요구하며 아데나워의 서방 통합 정책에 맞섰다. 1952년 본에서 죽었다.',
            'Born in Kulm in West Prussia, he lost his right arm in the First World War and joined the SPD in 1918. As a member of the Württemberg Landtag and the Reichstag he fought the Nazis. Arrested in July 1933, he refused to sign a renunciation of political activity and spent ten years in concentration camps. In 1945 he rebuilt the party from Hanover, rejected the merger with the Communists urged by Otto Grotewohl in the Soviet zone, and called the KPD “red-painted Nazis”. Elected SPD chairman in 1946 and the Bundestag’s first leader of the opposition in 1949, he called for the nationalisation of heavy industry and a united Germany and opposed Adenauer’s integration with the West. He died in Bonn in 1952.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: [], en: ['Curt Ernst Carl Schumacher'] },
        sources: [S.schumacher, S.deSchumacher],
        facts: {
            years: { claim: '1895–1952', locator: 'lead', excerpt: '13 October 1895 – 20 August 1952' },
            citizenship: { claim: 'German politician; SPD chairman and first leader of the opposition', locator: 'lead', excerpt: 'was a German politician and resistance fighter against the Nazis' },
            nationalOrigin: { claim: 'German politician born in Culm, West Prussia', source: S.deSchumacher, locator: 'Einleitung', excerpt: '* 13. Oktober 1895 in Culm, Westpreußen; † 20. August 1952 in Bonn), war ein deutscher Politiker' },
            bio: [
                { claim: 'born in Kulm; lost his right arm in 1914', locator: 'Early life and career', excerpt: 'he was so badly wounded that his right arm had to be amputated' },
                { claim: 'joined the SPD in 1918', locator: 'Early life and career', excerpt: 'Inspired by Eduard Bernstein, Schumacher became a dedicated socialist and in 1918 joined the Social Democratic Party of Germany (SPD).' },
                { claim: 'Württemberg Landtag 1924', locator: 'Early life and career', excerpt: "Schumacher was elected to the state legislature, the Free People's State of Württemberg Landtag in 1924." },
                { claim: 'Reichstag 1930', locator: 'Early life and career', excerpt: 'In 1930, he was elected to the national legislature, the Reichstag.' },
                { claim: 'arrested July 1933; refused to sign', locator: 'Nazi regime', excerpt: 'Schumacher was arrested in July 1933, two weeks before the SPD was banned, and was severely beaten in prison.' },
                { claim: 'refused the renunciation', locator: 'Nazi regime', excerpt: 'unlike Fritz Bauer and seven other political prisoners, he refused to sign it' },
                { claim: 'ten years in concentration camps', locator: 'Nazi regime', excerpt: 'Schumacher spent the next ten years in Nazi concentration camps at Heuberg, Kuhberg, Flossenbürg, and Dachau.' },
                { claim: 'rebuilt the SPD from Hanover', locator: 'Postwar', excerpt: 'By May 1945, he was already reorganising the SPD in Hanover without the permission of the occupation authorities.' },
                { claim: 'rejected Grotewohl’s merger proposal', locator: 'Postwar', excerpt: 'Schumacher was as ardently anti-Communist as he was anti-Nazi, and rejected the proposal.' },
                { claim: '“red-painted Nazis”', locator: 'lead', excerpt: 'Schumacher described the KPD as "red-painted Nazis"' },
                { claim: 'SPD chairman 1946; first leader of the opposition 1949', locator: 'lead', excerpt: 'He was chairman of the Social Democratic Party of Germany from 1946 and the first Leader of the Opposition in the Bundestag in West Germany in 1949' },
                { claim: 'united socialist Germany; nationalisation of heavy industry', locator: 'Postwar', excerpt: 'Schumacher campaigned throughout 1948 and 1949 for a united socialist Germany and particularly for the nationalisation of heavy industry' },
                { claim: 'opposed European integration bodies', locator: '1949 federal election', excerpt: 'Schumacher opposed the emerging new organisations of European co-operation' },
                { claim: 'died in Bonn in 1952', source: S.deSchumacher, locator: 'Einleitung', excerpt: '† 20. August 1952 in Bonn' },
            ],
        },
        activities: [
            { functionId: 'political-leadership', affiliationId: 'party-german-spd', startYear: 1946, endYear: 1952, primary: true, claim: 'SPD chairman 1946–1952', source: S.deSchumacher, locator: 'Einleitung', excerpt: 'von 1946 bis 1952 Parteivorsitzender der SPD sowie von 1949 bis 1952 Oppositionsführer im Deutschen Bundestag' },
            { functionId: 'legislature', affiliationId: 'state-germany', startYear: 1930, endYear: 1933, claim: 'Reichstag deputy from 1930', locator: 'Early life and career', excerpt: 'In 1930, he was elected to the national legislature, the Reichstag.' },
            { functionId: 'legislature', affiliationId: 'state-germany', startYear: 1949, endYear: 1952, claim: 'First leader of the opposition in the Bundestag', locator: 'lead', excerpt: 'the first Leader of the Opposition in the Bundestag in West Germany in 1949; he served in both positions until his death' },
        ],
        career: [
            ['1918', '사회민주당 입당', 'Joined the SPD'],
            ['1930–1933', '제국의회 의원', 'Reichstag deputy'],
            ['1933–1943', '나치 강제수용소 수감', 'Held in Nazi concentration camps'],
            ['1946–1952', '사회민주당 의장', 'SPD chairman'],
            ['1949–1952', '연방의회 야당 지도자', 'Leader of the opposition in the Bundestag'],
        ],
    }),
    person({
        id: 'jakob-kaiser', groupId: 'world-cold-war',
        given: ['야코프', 'Jakob'], family: ['카이저', 'Kaiser'], nativeName: 'Jakob Kaiser', years: '1888–1961',
        citizenship: 'germany', origin: 'germany',
        epithet: ['소련 점령지구 기독교민주연합 대표였다가 군정청에 밀려나 서독 전독일문제 장관이 된 정치가',
            'Christian Democrat who led the CDU in the Soviet zone until SMAD removed him, then became West Germany’s minister for all-German affairs'],
        bio: ['바이에른 함멜부르크의 제본공 출신으로 가톨릭 노동조합 운동을 이끌었고, 중앙당 소속으로 1933년 제국의회 의원이 되었다. 나치에 맞선 저항운동에 가담해 1938년 게슈타포에 체포되었고, 1944년 7월 20일 암살 기도 뒤 숨어 지냈다. 전후 소련 점령지구에서 기독교민주연합을 함께 세우고 레머와 함께 대표를 맡았으며, 기독교 사회주의자로서 주요 산업의 국유화를 주장했다. 공산당을 비판한 끝에 1947년 12월 레머와 함께 소련 군정청에 의해 대표직에서 물러났고, 서베를린으로 옮겼다. 아데나워의 서방 통합에 맞서 중립 통일 독일을 바랐고, 1949~1957년 전독일문제 장관을 지냈다. 1961년 베를린에서 죽었다.',
            'A bookbinder from Hammelburg in Bavaria, he became a leader of the Catholic trade-union movement and was elected to the Reichstag for the Centre Party in 1933. He joined the resistance against the Nazis, was arrested by the Gestapo in 1938, and went into hiding after the 20 July 1944 plot. After the war he co-founded the CDU in the Soviet zone and became its co-chairman with Ernst Lemmer; as a Christian Socialist he called for the nationalisation of key industries. Critical of the Communists, he and Lemmer were removed as chairmen by the Soviet Military Administration in December 1947, and he moved to West Berlin. He opposed Adenauer’s Western integration in favour of a neutral, united Germany, and was minister for all-German affairs from 1949 to 1957. He died in Berlin in 1961.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: [], en: [] },
        sources: [S.kaiser, S.deKaiser],
        facts: {
            years: { claim: '1888–1961', locator: 'lead', excerpt: '8 February 1888 – 7 May 1961' },
            citizenship: { claim: 'German politician; Reichstag and Bundestag member, federal minister', locator: 'lead', excerpt: 'was a German politician and resistance leader during World War II' },
            nationalOrigin: { claim: 'born in Hammelburg, Lower Franconia, Bavaria', locator: 'Early life', excerpt: 'Kaiser was born on 8 February 1888 in Hammelburg, Lower Franconia, Kingdom of Bavaria.' },
            bio: [
                { claim: 'bookbinder; Catholic trade union leader', locator: 'Early life', excerpt: 'Following in his father\'s footsteps, Kaiser began a career as a bookbinder.' },
                { claim: 'leader of the Christian labour movement', locator: 'Early life', excerpt: 'he became a leader of the Christian labour movement during the Weimar Republic' },
                { claim: 'Centre Party; Reichstag 1933', locator: 'Weimar Republic', excerpt: 'He was elected to the Reichstag in 1933.' },
                { claim: 'joined the resistance; arrested 1938', locator: 'Resistance', excerpt: 'He was arrested by the Gestapo in 1938 under suspicion of treason, but he was released shortly thereafter.' },
                { claim: 'hid after the 20 July plot', locator: 'Resistance', excerpt: 'forced him to go into hiding for the remainder of World War II' },
                { claim: 'co-founder of the CDU in the Soviet zone', source: S.deKaiser, locator: 'Leben', excerpt: 'Nach dem Zweiten Weltkrieg gehörte Kaiser mit Andreas Hermes und Joseph Ersing zu den Mitbegründern der CDU in der sowjetischen Besatzungszone (SBZ).' },
                { claim: 'co-chairman with Lemmer', locator: 'Leader of the East German CDU', excerpt: 'In the same year he was elected co-chairman of the East German CDU (together with Ernst Lemmer).' },
                { claim: 'Christian Socialist; nationalisation', locator: 'Leader of the East German CDU', excerpt: 'Kaiser belonged to a group within the CDU called the Christian Socialists. They called for the nationalisation of some major industries.' },
                { claim: 'critical of the Communists', locator: 'Leader of the East German CDU', excerpt: 'he was critical of the Communist Party of Germany and its Soviet-supported leaders' },
                { claim: 'removed by SMAD in December 1947 with Lemmer', source: S.deKaiser, locator: 'Leben', excerpt: 'Im Dezember 1947 wurden er und Ernst Lemmer als Vorsitzende der Ost-CDU von der Sowjetischen Militäradministration abgesetzt.' },
                { claim: 'moved to West Berlin', locator: 'Member of the West German CDU', excerpt: 'In 1948, Kaiser was forced to leave East Berlin and he went to West Berlin' },
                { claim: 'neutral united Germany', locator: 'Member of the West German CDU', excerpt: 'Kaiser strongly believed in a neutral, united Germany, and hoped that Germany would be a bridge between the West and the East.' },
                { claim: 'died in Berlin 1961', locator: 'Personal life and death', excerpt: 'Kaiser died on 7 May 1961 in Berlin.' },
            ],
        },
        activities: [
            { functionId: 'political-leadership', affiliationId: 'party-german-cdu', startYear: 1945, endYear: 1947, claim: 'Co-founder and co-chairman of the CDU in the Soviet zone until removed by SMAD', source: S.deKaiser, locator: 'Leben', excerpt: 'Im Dezember 1947 wurden er und Ernst Lemmer als Vorsitzende der Ost-CDU von der Sowjetischen Militäradministration abgesetzt.' },
            { functionId: 'government', affiliationId: 'state-germany', startYear: 1949, endYear: 1957, primary: true, claim: 'First Federal Minister of All-German Affairs', locator: 'lead', excerpt: 'He was also the first Federal Minister of All-German Affairs, serving from 1949 until 1957.' },
            { functionId: 'organizing', affiliationId: 'party-german-cdu', startYear: 1949, endYear: 1958, claim: 'Chairman of the CDU social committees', source: S.deKaiser, locator: 'Leben', excerpt: 'Er gehört zu den Gründern der CDU-Sozialausschüsse, deren Vorsitzender er von 1949 bis 1958 war.' },
        ],
        career: [
            ['1933', '중앙당 제국의회 의원', 'Reichstag deputy for the Centre Party'],
            ['1938', '게슈타포에 체포', 'Arrested by the Gestapo'],
            ['1945–1947', '소련 점령지구 기독교민주연합 공동대표', 'Co-chairman of the CDU in the Soviet zone'],
            ['1947', '소련 군정청에 의해 해임', 'Removed by the Soviet Military Administration'],
            ['1949–1957', '서독 전독일문제 장관', 'Federal Minister of All-German Affairs'],
        ],
    }),
    person({
        id: 'otto-nuschke', groupId: 'world-cold-war',
        given: ['오토', 'Otto'], family: ['누슈케', 'Nuschke'], nativeName: 'Otto Nuschke', years: '1883–1957',
        citizenship: 'east-germany', origin: 'germany',
        epithet: ['카이저 뒤 동독 기독교민주연합을 이끌며 사회주의통일당 체제에 순응한 부총리',
            'Kaiser’s successor at the head of the East German CDU, who brought it into line with the SED as deputy prime minister'],
        bio: ['작센 프로보르크에서 태어나 언론인으로 일했고, 좌파 자유주의 정당을 거쳐 1918년 독일민주당 창당에 참여했으며 바이마르 국민의회와 프로이센 주의회 의원을 지냈다. 나치 집권 뒤 반대파에 섰고 1944년 암살 기도 뒤 숨어 지냈다. 1945년 소련 점령지구에서 기독교민주연합을 함께 세웠고, 1947년 카이저와 레머가 소련 군정청에 의해 해임되자 대표 대행을 거쳐 1948년 대표가 되었다. 독일인민평의회 공동의장으로 동독 헌법 초안에 참여했고, 1949년 부총리 겸 교회청장이 되었다. 사회주의통일당 정권을 충실히 지지하며 따르지 않는 당원을 밀어냈다. 1957년 죽었다.',
            'Born in Frohburg in Saxony, he worked as a journalist, moved through the left-liberal parties, helped found the German Democratic Party in 1918, and sat in the Weimar National Assembly and the Prussian Landtag. He joined the opposition after 1933 and went into hiding after the 1944 attempt on Hitler’s life. In 1945 he co-founded the CDU in the Soviet zone; when the Soviet authorities deposed Jakob Kaiser and Ernst Lemmer in 1947 he became acting chairman, and chairman in 1948. As a co-chairman of the German People’s Council he took part in drafting the GDR constitution, and in 1949 became deputy prime minister and head of the Church Office. A loyal supporter of the SED regime, he pushed out CDU members unwilling to follow the Communists. He died in 1957.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: [], en: ['Otto Gustav Nuschke'] },
        sources: [S.nuschke, S.deNuschke],
        facts: {
            years: { claim: '1883–1957', locator: 'lead', excerpt: '23 February 1883 – 27 December 1957' },
            citizenship: { claim: 'East German CDU chairman and deputy prime minister of the GDR', source: S.deNuschke, locator: 'Einleitung', excerpt: 'war ein deutscher Politiker und CDU-Vorsitzender in der Sowjetischen Besatzungszone bzw. der späteren DDR. Zudem war Nuschke ab 1949  stellvertretender Ministerpräsident der DDR.' },
            nationalOrigin: { claim: 'German politician born in Frohburg, Saxony', locator: 'lead', excerpt: 'Otto Nuschke (23 February 1883 – 27 December 1957) was a German politician. Nuschke was born in Frohburg in the Kingdom of Saxony.' },
            bio: [
                { claim: 'journalist', source: S.deNuschke, locator: 'Leben und Beruf', excerpt: '1910 wechselte Nuschke als Redakteur zum Berliner Tageblatt.' },
                { claim: 'co-founded the DDP; Weimar National Assembly; Prussian Landtag', locator: 'lead', excerpt: 'In 1918, Nuschke took part in establishing the German Democratic Party. In 1919, he was a delegate to the Weimar National Assembly' },
                { claim: 'Prussian Landtag 1921–1933', locator: 'lead', excerpt: 'from 1921 to 1933, he was a member of the Landtag of Prussia' },
                { claim: 'opposition after 1933; hiding after 1944', locator: 'lead', excerpt: "After the Nazis gained power in 1933, Nuschke joined the opposition. After the 1944 assassination attempt on Hitler's life, he went into hiding." },
                { claim: 'co-founder of the CDU in June 1945', locator: 'lead', excerpt: 'became one of the co-founders of the Christian Democratic Union (CDU) in June 1945' },
                { claim: 'acting chairman after Kaiser and Lemmer were deposed, chairman 1948', locator: 'lead', excerpt: 'In 1947, after the deposition of party chairmen Jakob Kaiser and Ernst Lemmer by the Soviet military authorities, Nuschke became acting chairman and after the party congress of 1948, party chairman.' },
                { claim: 'German People’s Council that drafted the GDR constitution', locator: 'lead', excerpt: "was chairman of the German People's Council (Deutscher Volksrat) that drafted the Constitution of the German Democratic Republic" },
                { claim: 'deputy prime minister and head of the Church Office', locator: 'lead', excerpt: 'Nuschke became Deputy Prime Minister and chief of the Church Office' },
                { claim: 'loyal supporter of the SED regime', locator: 'lead', excerpt: "Nuschke was a loyal supporter of the SED regime, and gradually pushed out those CDU members not willing to do the Communists' bidding." },
                { claim: 'died in 1957', source: S.deNuschke, locator: 'Einleitung', excerpt: '† 27. Dezember 1957 in Hennigsdorf' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-east-germany', startYear: 1949, endYear: 1957, primary: true, claim: 'Deputy prime minister of the GDR and head of the Church Office', locator: 'lead', excerpt: 'After the formal establishment of the German Democratic Republic, Nuschke became Deputy Prime Minister and chief of the Church Office.' },
            { functionId: 'legislature', affiliationId: 'state-east-germany', startYear: 1949, endYear: 1957, claim: 'Member of the (Provisional) People’s Chamber until his death', locator: 'lead', excerpt: 'In 1949 Nuschke became a member of the Provisional People\'s Chamber of the GDR.  He remained a member of parliament until his death.' },
        ],
        career: [
            ['1918', '독일민주당 창당 참여', 'Co-founder of the German Democratic Party'],
            ['1921–1933', '프로이센 주의회 의원', 'Member of the Prussian Landtag'],
            ['1945', '소련 점령지구 기독교민주연합 공동 창당', 'Co-founder of the CDU in the Soviet zone'],
            ['1948–1957', '동독 기독교민주연합 대표', 'Chairman of the East German CDU'],
            ['1949–1957', '동독 부총리 겸 교회청장', 'GDR deputy prime minister and head of the Church Office'],
        ],
    }),
    {
        ...person({
            id: 'sergei-tiulpanov', groupId: 'stalin-era',
            given: ['세르게이', 'Sergei'], family: ['튤파노프', 'Tiulpanov'], nativeName: 'Сергей Тюльпанов', years: '1901–1984',
            citizenship: 'soviet', origin: null,
            epithet: ['소련 군정청 선전국장으로 사회주의통일당 결성과 동독 소비에트화를 밀어붙인 장교',
                'Head of SMAD’s Propaganda Administration who drove the founding of the SED and the Sovietisation of eastern Germany'],
            bio: ['레닌그라드에서 교육받은 정치경제학자로 1927년 공산당에 들어갔다. 대숙청 때 몸을 숨겼고 부모는 탄압을 받았다. 독소전쟁 중 여러 전선 정치국의 제7부를 이끌었다. 1945년 10월부터 1949년 9월까지 소련 군정청 선전국(뒤의 정보국) 국장으로, 독일어에 능했고 울브리히트를 강하게 지지했다. 1946년 공산당과 사회민주당의 통합을 밀어붙였고, 1948년부터 소련식 별도 국가 수립을 추진했다. 스탈린이 그와 울브리히트의 급속한 사회주의화 구상을 지지하지 않는 것이 드러나며 입지를 잃었고, 1949년 방첩 기관의 고발 끝에 소환되었다. 그 뒤 레닌그라드 대학교 경제학 교수로 지냈다.',
                'An economist trained in Leningrad, he joined the Communist Party in 1927. He went into hiding during the Great Terror, and his parents were repressed. In the war he headed the 7th department of several fronts’ political administrations. From October 1945 to September 1949 he headed the Propaganda (later Information) Administration of the Soviet Military Administration in Germany; fluent in German, he strongly backed Walter Ulbricht. He pushed the 1946 merger of the KPD and SPD and from 1948 the development of a separate state on Soviet lines. He fell from favour as it became clear that Stalin did not support his and Ulbricht’s plans for rapid socialisation, and in 1949, after accusations from counter-intelligence, he was recalled. He later taught economics at Leningrad University.'],
            fate: ['natural', '자연사', 'Natural death'],
            aliases: { ko: [], en: ['Sergei Tyulpanov', 'Sergej Tjulpanow'] },
            sources: [S.tiulpanov, S.deTiulpanov, S.ruTiulpanov],
            facts: {
                years: [
                    { claim: 'born 3 October 1901', locator: 'lead', excerpt: '3 October 1901' },
                    { claim: 'died 16 February 1984 in Leningrad (English article gives 1987)', source: S.ruTiulpanov, locator: 'преамбула', excerpt: '3 октября 1901 — 16 февраля 1984, Ленинград' },
                    { claim: 'died 1984 in Leningrad', source: S.deTiulpanov, locator: 'Einleitung', excerpt: '† 16. Februar 1984 in Leningrad' },
                ],
                citizenship: { claim: 'Soviet economist and SMAD official', locator: 'lead', excerpt: 'was a Soviet economist and the director of the Propaganda Administration of the Soviet Military Administration in Germany' },
                bio: [
                    { claim: 'studied in Leningrad; joined the party in 1927', source: S.deTiulpanov, locator: 'Leben', excerpt: 'In der Roten Armee wurde Tjulpanow Berufsoffizier und trat 1927 der KPdSU bei.' },
                    { claim: 'hid during the Great Terror', source: S.deTiulpanov, locator: 'Leben', excerpt: 'Während des Großen Terrors 1937–38 versteckte er sich ein Jahr lang als Arbeiter auf einer Kolchose.' },
                    { claim: 'parents repressed', source: S.ruTiulpanov, locator: 'Биография', excerpt: 'в 1938 году был репрессирован отец, а в 1940 году — мать' },
                    { claim: 'wartime political departments of several fronts', source: S.deTiulpanov, locator: 'Leben', excerpt: '1941–45 war er Leiter der Politischen Abteilung an verschiedenen Frontabschnitten.' },
                    { claim: 'head of the Propaganda (later Information) Administration Oct 1945 – Sep 1949', source: S.ruTiulpanov, locator: 'Управление пропаганды СВАГ', excerpt: 'начальника Управления пропаганды (позднее переименовано в Управления информации)' },
                    { claim: 'dates of office', source: S.ruTiulpanov, locator: 'преамбула', excerpt: 'Начальник Управления пропаганды Советской военной администрации в Германии (5 октября 1945 года — 18 сентября 1949 года)' },
                    { claim: 'fluent German; supporter of Ulbricht and Sovietisation', locator: 'lead', excerpt: 'Tiulpanov spoke fluent German. He was a strong supporter of Walter Ulbricht and of the Sovietization of eastern Germany.' },
                    { claim: 'pushed the KPD–SPD merger and a separate state', source: S.deTiulpanov, locator: 'Leben', excerpt: 'Er forcierte 1946 die  Vereinigung von SPD und KPD zur SED und ab 1948 die Entwicklung eines eigenen Staatswesens auf dem Gebiet der SBZ nach sowjetischen Vorbildern.' },
                    { claim: 'fell from favour; Stalin did not support rapid socialism', locator: 'lead', excerpt: "fell from favor as it became clear that Joseph Stalin did not support his and Ulbricht's plans for the rapid establishment of socialism in eastern Germany" },
                    { claim: 'recalled after counter-intelligence accusations', source: S.ruTiulpanov, locator: 'Управление пропаганды СВАГ', excerpt: '18 сентября секретариат ЦК принял решение об отзыве Тюльпанова из Германии.' },
                    { claim: 'counter-intelligence material', source: S.ruTiulpanov, locator: 'Управление пропаганды СВАГ', excerpt: 'передал министру государственной безопасности В. С. Абакумову «компрометирующий» материал на Тюльпанова' },
                    { claim: 'Leningrad University economist', locator: 'lead', excerpt: 'Tiulpanov retired from the military in 1956 and dedicated the rest of his life to academia, first as vice-rector of Leningrad State University' },
                ],
            },
            activities: [
                { functionId: 'propaganda', affiliationId: 'state-soviet', startYear: 1945, endYear: 1949, primary: true, claim: 'Head of the SMAD Propaganda (Information) Administration', source: S.ruTiulpanov, locator: 'преамбула', excerpt: 'Начальник Управления пропаганды Советской военной администрации в Германии (5 октября 1945 года — 18 сентября 1949 года)' },
                { functionId: 'military', affiliationId: 'state-soviet', startYear: 1941, endYear: 1945, claim: 'Head of the 7th department of front political administrations', source: S.ruTiulpanov, locator: 'Великая Отечественная война', excerpt: 'В 1942—1945 годы — начальник 7-го Отдела Политического управления Юго-Западного, Сталинградского, Южного и 4-го Украинского фронтов.' },
                { functionId: 'scholarship', affiliationId: 'state-soviet', startYear: 1956, endYear: null, claim: 'Vice-rector of Leningrad University; head of the department of economics of modern capitalism from 1957', locator: 'lead', excerpt: 'first as vice-rector of Leningrad State University, and from 1957 dean of the department of economics of modern capitalism that he himself had founded' },
            ],
            career: [
                ['1927', '공산당 입당', 'Joined the Communist Party'],
                ['1942–1945', '여러 전선 정치국 제7부장', 'Head of the 7th department in front political administrations'],
                ['1945–1949', '소련 군정청 선전국(정보국) 국장', 'Head of SMAD’s Propaganda (Information) Administration'],
                ['1949', '독일에서 소환, 소장 진급', 'Recalled from Germany; promoted major general'],
                ['1957', '레닌그라드 대학교 현대 자본주의 경제학과장', 'Head of the department of economics of modern capitalism, Leningrad University'],
            ],
        }),
        patronymic: { ko: '이바노비치', en: 'Ivanovich' },
        cyrillicPatronymic: 'Иванович',
    },
];
