// Person cards for the 1953 East German uprising and the 1953–1956 crisis in
// Eastern Europe: the Soviet commandant of Berlin, the Polish security officer
// whose defection shook the Ministry of Public Security, and Kádár's minister
// of the armed forces. See lib.js person(). Excerpts are verbatim from the cited pages.
const { person } = require('../baltic-1940-1953-20261002/lib');

const wiki = (lang, t) => `https://${lang}.wikipedia.org/wiki/` + encodeURI(t);
const S = {
    ruDibrova: wiki('ru', 'Диброва,_Пётр_Акимович'),
    deDibrova: wiki('de', 'Pjotr_Akimowitsch_Dibrowa'),
    swiatlo: wiki('en', 'Józef_Światło'),
    plSwiatlo: wiki('pl', 'Józef_Światło'),
    munnich: wiki('en', 'Ferenc_Münnich'),
    huMunnich: wiki('hu', 'Münnich_Ferenc'),
    deMunnich: wiki('de', 'Ferenc_Münnich'),
};

module.exports = [
    {
        ...person({
            id: 'pyotr-dibrova', groupId: 'stalin-era',
            given: ['표트르', 'Pyotr'], family: ['디브로바', 'Dibrova'], nativeName: 'Пётр Диброва', years: '1901–1971',
            citizenship: 'soviet', origin: null,
            epithet: ['1953년 6월 17일 동베를린에 비상사태를 선포한 소련 지구 사령관',
                'Soviet commandant of Berlin who declared a state of emergency in East Berlin on 17 June 1953'],
            bio: ['폴타바 현의 농민 집안에서 태어나 1918년 붉은 군대에 들어가 내전에 참가했고, 본래 성 하일로를 1925년 디브로바로 바꾸었다. 정치장교로 일하다 1940년 발트 특별군관구 군사회의 위원이 되었고, 독소전쟁 초기의 패배로 북서부 전선 군사회의 위원에서 물러났다. 볼호프 전선의 제59군과 제2충격군 군사회의 위원을 거쳐 1944년 제145소총사단장으로 비텝스크-오르샤 작전과 리가 작전에 참가했다가 중상을 입었다. 1952년부터 1956년까지 베를린 소련 지구 사령관을 지냈고, 1953년 6월 17일 봉기 때 동베를린에 비상사태를 선포했다. 그 뒤 프룬제 군사아카데미에서 일하다 1960년 퇴역했고, 1971년 모스크바에서 죽었다.',
                'Born into a peasant family in Poltava Governorate, he joined the Red Army in 1918 and fought in the Civil War; in 1925 he changed his birth surname Khailo to Dibrova. A political officer, he became a member of the military council of the Baltic Special Military District in 1940 and was removed from the military council of the North-Western Front after the defeats at the start of the German–Soviet war. After serving on the military councils of the 59th Army and the 2nd Shock Army on the Volkhov Front, he commanded the 145th Rifle Division in 1944 in the Vitebsk–Orsha and Riga operations until he was badly wounded. From 1952 to 1956 he was commandant of the Soviet sector of Berlin, and during the uprising of 17 June 1953 he declared a state of emergency in East Berlin. He then worked at the Frunze Military Academy, retired in 1960 and died in Moscow in 1971.'],
            fate: ['natural', '사망', 'Died'],
            aliases: { ko: [], en: ['Pjotr Dibrowa', 'Pyotr Akimovich Dibrova'] },
            sources: [S.ruDibrova, S.deDibrova],
            facts: {
                years: { claim: '1901–1971', locator: 'преамбула', excerpt: '6 сентября 1901 — 30 сентября 1971, Москва' },
                citizenship: { claim: 'Soviet military commander, commandant of Berlin, major general', locator: 'преамбула', excerpt: 'советский военачальник. Участник Великой Отечественной войны, член Военного совета Северо-Западного фронта, член Военного совета 59-й и 2-й ударной армий Волховского фронта, командир 145-й стрелковой дивизии, комендант Берлина. Генерал-майор (1943).' },
                bio: [
                    { claim: 'born to a peasant family in Poltava Governorate', locator: 'Биография', excerpt: 'Родился в деревне Шамраевка Полтавской губернии (ныне — в Полтавском районе Полтавской области) в семье крестьянина. В Красной Армии с 1918 года.' },
                    { claim: 'joined the Red Army in 1918; Civil War', source: S.deDibrova, locator: 'Leben', excerpt: 'Er trat 1918 der Roten Armee bei und nahm am Russischen Bürgerkrieg teil.' },
                    { claim: 'changed his birth name Khailo to Dibrova in 1925', source: S.deDibrova, locator: 'Leben', excerpt: 'Seinen Geburtsnamen Chailo ließ er 1925 in Dibrowa ändern.' },
                    { claim: 'military council of the Baltic Special Military District from December 1940', locator: 'Биография', excerpt: 'С декабря 1940 — член Военного совета Прибалтийского особого военного округа.' },
                    { claim: 'removed from the North-Western Front military council after early defeats', locator: 'Великая Отечественная война', excerpt: 'однако в связи с неудачами начального периода войны был смещён с этого поста' },
                    { claim: '59th Army and 2nd Shock Army military councils, Volkhov Front', locator: 'Великая Отечественная война', excerpt: 'С 18 декабря 1941 года по 16 июня 1942 года — член Военного совета 59-й армии Волховского фронта, с 17 июня 1942 по 5 декабря 1942 год — член Военного совета 2-й ударной армии' },
                    { claim: 'commander of the 145th Rifle Division in the Vitebsk–Orsha and Riga operations', locator: 'Великая Отечественная война', excerpt: 'В апреле 1944 назначен командиром 145-й стрелковой дивизии. Вместе с ней участвовал в Витебско-Оршанской и Рижской операциях.' },
                    { claim: 'badly wounded in September 1944', locator: 'Великая Отечественная война', excerpt: '29 сентября 1944 года был тяжело ранен в левую руку' },
                    { claim: 'commandant of the Soviet sector of Berlin January 1952 – July 1956', locator: 'Послевоенный период', excerpt: 'С января 1952 по июль 1956 был комендантом советского сектора Берлина.' },
                    { claim: 'declared the state of emergency in East Berlin on 17 June 1953', source: S.deDibrova, locator: 'Leben', excerpt: 'verkündete beim Aufstand vom 17. Juni 1953 den Ausnahmezustand für Ost-Berlin' },
                    { claim: 'Frunze Military Academy; retired in 1960', locator: 'Послевоенный период', excerpt: 'Военной академии им. М. В. Фрунзе (Москва, июль 1956—1960). С 1960 года — в отставке.' },
                    { claim: 'died in Moscow', locator: 'преамбула', excerpt: '30 сентября 1971, Москва' },
                ],
            },
            activities: [
                { functionId: 'military', affiliationId: 'state-soviet', startYear: 1952, endYear: 1956, primary: true, claim: 'Commandant of the Soviet sector of Berlin', locator: 'Послевоенный период', excerpt: 'С января 1952 по июль 1956 был комендантом советского сектора Берлина.' },
                { functionId: 'military', affiliationId: 'state-soviet', startYear: 1941, endYear: 1944, claim: 'Military council member of the 59th Army and 2nd Shock Army; commander of the 145th Rifle Division', locator: 'Великая Отечественная война', excerpt: 'В апреле 1944 назначен командиром 145-й стрелковой дивизии.' },
                { functionId: 'education', affiliationId: 'state-soviet', startYear: 1946, endYear: 1960, claim: 'Course head at the Frunze Military Academy', locator: 'Послевоенный период', excerpt: 'Начальник курса военно-исторического факультета Военной академии им. М. В. Фрунзе (июнь 1946 — январь 1952).' },
            ],
            career: [
                ['1918', '붉은 군대 입대', 'Joined the Red Army'],
                ['1941–1942', '볼호프 전선 제59군·제2충격군 군사회의 위원', 'Military council of the 59th Army and 2nd Shock Army, Volkhov Front'],
                ['1943', '소장', 'Major general'],
                ['1944', '제145소총사단장', 'Commander of the 145th Rifle Division'],
                ['1952–1956', '베를린 소련 지구 사령관', 'Commandant of the Soviet sector of Berlin'],
                ['1953', '6월 17일 동베를린 비상사태 선포', 'Declared a state of emergency in East Berlin on 17 June'],
            ],
        }),
        patronymic: { ko: '아키모비치', en: 'Akimovich' },
        cyrillicPatronymic: 'Акимович',
    },
    person({
        id: 'jozef-swiatlo', groupId: 'world-cold-war',
        given: ['유제프', 'Józef'], family: ['시비아트워', 'Światło'], nativeName: 'Józef Światło', years: '1915–1994',
        citizenship: 'poland', origin: { code: 'poland', label: { ko: '폴란드 (유대계)', en: 'Poland (Jewish)' } },
        epithet: ['1953년 서방으로 망명해 폴란드 공안부의 고문과 숙청을 폭로한 제10국 부국장',
            'Deputy head of Poland’s security Department X whose 1953 defection and broadcasts exposed the ministry’s torture and purges'],
        bio: ['갈리치아 메디니의 유대인 가정에서 이자크 플라이슈파르브로 태어나 크라쿠프에서 제화공으로 일했고, 시온주의 단체를 거쳐 공산주의 청년동맹에서 활동했다. 1939년 독일군 포로가 되었다 탈출했으나 소련 내륙으로 끌려갔고, 1943년 결혼하며 아내의 성을 따랐다. 베를링 군의 정치장교를 거쳐 공안부에 들어가 국내군 체포와 1946년 국민투표 조작에 가담했다. 공안부 제10국 부국장으로 비에루트의 직접 지시를 받아 고무우카 등을 체포했다. 1953년 12월 5일 동베를린 출장 중 서베를린의 미군에 망명했고, 자유유럽방송으로 고문과 당내 투쟁을 폭로해 공안부 개편과 폴란드의 10월을 앞당겼다. 1994년 미국에서 죽었다.',
            'Born Izaak Fleischfarb into a Jewish family in Medyn in Galicia, he worked as a shoemaker in Kraków and moved from a Zionist group to the Communist Youth. Captured by the Germans in 1939, he escaped, only to be deported into the Soviet interior; in 1943 he married and took his wife’s surname. A political officer in Berling’s army, he joined the Ministry of Public Security, took part in arresting Home Army members and in falsifying the 1946 referendum, and as deputy director of its Department X arrested Gomułka and others on Bierut’s personal orders. On 5 December 1953, on official business in East Berlin, he defected to the US military mission in West Berlin. His revelations on Radio Free Europe about torture and the struggles inside the party led to the break-up of the ministry and contributed to the Polish October. He died in the United States in 1994.'],
        fate: ['natural', '사망', 'Died'],
        aliases: { ko: ['이자크 플라이슈파르브'], en: ['Izaak Fleischfarb', 'Jozef Swiatlo'] },
        sources: [S.swiatlo, S.plSwiatlo],
        facts: {
            years: { claim: '1915–1994', locator: 'lead', excerpt: '1 January 1915 – 2 September 1994' },
            citizenship: { claim: 'High-ranking official of the Polish Ministry of Public Security', locator: 'lead', excerpt: 'was a high-ranking official in the Ministry of Public Security of Poland (UB)' },
            nationalOrigin: { claim: 'Polish security official of Jewish origin', source: S.plSwiatlo, locator: 'wstęp', excerpt: 'polski wysoki funkcjonariusz Ministerstwa Bezpieczeństwa Publicznego pochodzenia żydowskiego' },
            bio: [
                { claim: 'born Izaak Fleischfarb into a Jewish family in Medyn, Galicia', locator: 'Biography', excerpt: 'into a Jewish family in Medyn village near Zbarazh in Galicia (now Ukraine)' },
                { claim: 'shoemaker in Kraków; Gordonia; Communist Youth from 1933', source: S.plSwiatlo, locator: 'Młodość', excerpt: 'W młodości działał w organizacji syjonistycznej Gordonia, a następnie od 1933 roku w Komunistycznym Związku Młodzieży Polski w Krakowie.' },
                { claim: 'worked as a shoemaker in Kraków', source: S.plSwiatlo, locator: 'Młodość', excerpt: 'pracował w Krakowie jako szewc' },
                { claim: 'captured by the Germans, escaped, deported east by the Soviets', locator: 'Biography', excerpt: 'Taken prisoner by the Germans, he escaped, only to be taken prisoner by the Red Army' },
                { claim: 'married in 1943 and took his wife’s surname', locator: 'Biography', excerpt: 'on 26 April 1943, he married Justyna Światło, taking her more Polish-sounding surname' },
                { claim: 'political officer in Berling’s army', locator: 'Biography', excerpt: "Berling's Army), becoming a political officer" },
                { claim: 'Home Army arrests and the 1946 referendum', locator: 'Biography', excerpt: 'He was involved in arresting hundreds of members of Polish underground organization, Armia Krajowa, its leadership (the Trial of the Sixteen) and falsifying of the 1946 Polish referendum.' },
                { claim: 'Department X; Bierut’s orders; arrested Gomułka', locator: 'Biography', excerpt: "He received orders personally from the First Secretary of the Polish United Workers' Party Bolesław Bierut, and arrested such notable people as politicians Władysław Gomułka and Marian Spychalski" },
                { claim: 'defected on 5 December 1953', locator: 'Defection to the West', excerpt: 'On 5 December 1953, the day after meeting the Stasi chief, Światło defected to the U.S. military mission in West Berlin.' },
                { claim: 'RFE broadcasts on torture and party struggles', locator: 'Aftermath', excerpt: "Światło detailed the torture of prisoners under interrogation and politically motivated executions and struggles inside the Polish United Workers' Party." },
                { claim: 'ministry broken up; contributed to the Polish October', locator: 'Aftermath', excerpt: "Światło's scandal contributed to the events of political liberalisation in Poland, known as the Polish October." },
                { claim: 'ministry broken up in late 1954', locator: 'Aftermath', excerpt: 'first the 10th Department and soon the entire Ministry was broken up and reorganised' },
                { claim: 'died 1994 in Stamford, Connecticut', source: S.plSwiatlo, locator: 'wstęp', excerpt: 'zm. 2 września 1994 w Stamford w stanie Connecticut' },
            ],
        },
        activities: [
            { functionId: 'security', affiliationId: 'state-poland', startYear: 1945, endYear: 1953, primary: true, claim: 'Officer of the Ministry of Public Security; first deputy director of Department X', source: S.plSwiatlo, locator: 'Kariera w organach bezpieczeństwa PRL', excerpt: 'Po przemianowaniu biura na departament jego dyrektorem został Fejgin, a Józef Światło objął stanowisko pierwszego wicedyrektora' },
            { functionId: 'military', affiliationId: 'state-poland', startYear: 1943, endYear: 1945, claim: 'Political officer in the 1st Kościuszko Division', locator: 'Biography', excerpt: "Światło eventually joined the Polish Forces in the East (Polish 1st Tadeusz Kościuszko Infantry Division, Berling's Army), becoming a political officer" },
        ],
        career: [
            ['1943', '베를링 군 정치장교', 'Political officer in Berling’s army'],
            ['1945', '공안부 입부', 'Joined the Ministry of Public Security'],
            ['1950', '공안부 제10국 제1부국장', 'First deputy director of Department X'],
            ['1953', '서베를린에서 미국으로 망명', 'Defected to the US in West Berlin'],
            ['1954', '자유유럽방송으로 폭로', 'Revelations on Radio Free Europe'],
        ],
    }),
    person({
        id: 'ferenc-munnich', groupId: 'world-cold-war',
        given: ['페렌츠', 'Ferenc'], family: ['뮌니히', 'Münnich'], nativeName: 'Münnich Ferenc', years: '1886–1967',
        citizenship: 'hungary', origin: { code: 'hungary', label: { ko: '헝가리 (독일계)', en: 'Hungary (German descent)' } },
        epithet: ['1956년 카다르와 함께 소련 개입을 지지하고 혁명 진압 뒤 총리가 된 헝가리 공산주의자',
            'Hungarian communist who backed Soviet intervention with Kádár in 1956 and became prime minister after the revolution was crushed'],
        bio: ['세레겔리에시의 독일계 가톨릭 집안에서 태어나 법학을 공부했고, 1차 세계대전 동부 전선에서 러시아군 포로가 되어 톰스크로 보내졌다. 그곳에서 볼셰비키에 가담해 국제 포로 부대를 이끌었고, 1918년 귀국해 헝가리 공산당 창당에 참여했으며 슬로바키아 평의회 공화국의 군사 인민위원을 지냈다. 1922~1936년 소련에서 살았고, 스페인 내전에서는 오토 플라터라는 이름으로 제11국제여단을 지휘했다. 전후 부다페스트 경찰청장과 외교관을 지냈다. 1956년 혁명 중 너지 정부의 내무장관이었으나 11월 카다르와 함께 모스크바에서 소련 무력 개입을 지지했고, 카다르 정부의 군·공안 장관으로 무장 경찰과 노동자 민병대 조직에 참여했으며 1958~1961년 총리를 지냈다.',
            'Born into a German Catholic family in Seregélyes, he studied law and was taken prisoner on the Eastern Front in 1915 and sent to Tomsk. There he joined the Bolsheviks and commanded an international POW unit; back in Hungary in 1918 he helped found the Hungarian Communist Party and was war commissar of the Slovak Soviet Republic. He lived in the Soviet Union from 1922 to 1936 and, under the name Otto Flatter, commanded the XI International Brigade in the Spanish Civil War. After the war he was Budapest’s chief of police and then a diplomat. In the 1956 revolution he was interior minister under Imre Nagy, but in November he went to Moscow with János Kádár and openly backed Soviet armed intervention. As minister of the armed forces and public security in Kádár’s government he helped organise the security regiments and the Workers’ Militia, and he was prime minister from 1958 to 1961.'],
        fate: ['natural', '사망', 'Died'],
        aliases: { ko: [], en: ['Otto Flatter'] },
        sources: [S.munnich, S.huMunnich, S.deMunnich],
        facts: {
            years: { claim: '1886–1967', locator: 'lead', excerpt: '18 November 1886 – 29 November 1967' },
            citizenship: { claim: 'Hungarian communist politician; prime minister 1958–1961', locator: 'lead', excerpt: "was a Hungarian Communist politician who served as Chairman of the Council of Ministers of the People's Republic of Hungary from 1958 to 1961" },
            nationalOrigin: { claim: 'Roman Catholic family of German origin, born in Seregélyes', source: S.huMunnich, locator: '1956-ig', excerpt: 'Münnich Ferenc a Fejér vármegyei Seregélyesen született, római katolikus német származású családban' },
            bio: [
                { claim: 'studied law', source: S.huMunnich, locator: '1956-ig', excerpt: 'Eperjesen és Kolozsvárott jogot tanult.' },
                { claim: 'captured 1915 and deported to Tomsk', locator: 'lead', excerpt: 'His unit was captured in October 1915 and were deported to a prisoner of war camp in Tomsk, Siberia.' },
                { claim: 'commanded an international POW unit for the Bolsheviks', locator: 'lead', excerpt: 'then served as a commander of an international POW unit fighting for the Bolsheviks' },
                { claim: 'returned 1918 to help form the Hungarian Communist Party', locator: 'lead', excerpt: 'returned to Hungary in September 1918 to help form the Hungarian Communist Party' },
                { claim: 'war commissar of the Slovak Soviet Republic', locator: 'lead', excerpt: 'then became a war commissar for the Slovak Soviet Republic' },
                { claim: 'lived in the Soviet Union 1922–1936', locator: 'lead', excerpt: 'Münnich resided in the Soviet Union from 1922-1936' },
                { claim: 'commanded the XI International Brigade as Otto Flatter', source: S.deMunnich, locator: 'Leben', excerpt: 'war zuletzt (unter dem Namen Otto Flatter) Kommandant der XI. Internationalen Brigade' },
                { claim: 'Budapest chief of police; diplomat 1949–1956', locator: 'lead', excerpt: 'returning to Hungary in 1945, where he served as the chief of police in Budapest. From 1949 to 1956 he held diplomatic posts in Helsinki, Sofia, Moscow, and Belgrade' },
                { claim: 'interior minister in Nagy’s second government, 27 Oct – 3 Nov 1956', source: S.huMunnich, locator: '1956-ig', excerpt: 'az 1956-os forradalom során október 27-étől november 3-ig Nagy Imre második kormányának belügyminiszteri tisztségét is viselte' },
                { claim: 'in Moscow with Kádár, 2–3 November 1956', source: S.huMunnich, locator: 'Kádárral Moszkvában', excerpt: 'Kádár Jánossal a nyilvánosság tudomása nélkül 1956. november 2-án és 3-án Moszkvában tárgyalt' },
                { claim: 'openly backed Soviet armed intervention', source: S.huMunnich, locator: 'Kádárral Moszkvában', excerpt: 'Münnich és Bata István nyíltan kiálltak a szovjet fegyveres beavatkozás szükségessége mellett' },
                { claim: 'minister of the armed forces and public security from 4 November', source: S.huMunnich, locator: 'A forradalom leverésekor és később', excerpt: 'Münnich november 4-étől a Kádár János vezette első Kádár-kormányban a fegyveres erők és a közbiztonsági ügyek minisztere' },
                { claim: 'organised the security regiments and the Workers’ Militia', source: S.huMunnich, locator: 'A forradalom leverésekor és később', excerpt: 'Részt vett a karhatalmi ezredek és a munkásőrség megszervezésében.' },
                { claim: 'prime minister 1958–1961', source: S.huMunnich, locator: 'A forradalom leverésekor és később', excerpt: 'A Kádár-kormány lemondását követően a Minisztertanács elnöke volt 1958 és 1961 között.' },
                { claim: 'died in Budapest in 1967', locator: 'lead', excerpt: 'Münnich died at 81 on 29 November 1967 in Budapest.' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-hungary', startYear: 1956, endYear: 1961, primary: true, claim: 'Minister of the armed forces and public security from November 1956; prime minister 1958–1961', locator: 'lead', excerpt: "After the Hungarian Revolution of 1956 Ferenc served as the minister for the armed forces and public security, and then as the Prime Minister from 1958 to 1961." },
            { functionId: 'political-leadership', affiliationId: 'party-hungarian-communist', startYear: 1918, endYear: 1919, claim: 'Founding member of the KMP; war commissar of the Slovak Soviet Republic', source: S.huMunnich, locator: '1956-ig', excerpt: 'Hazatérése után a Kommunisták Magyarországi Pártja egyik alapító tagja és a Szlovák Tanácsköztársaság hadügyi népbiztosa' },
            { functionId: 'military', affiliationId: 'state-spain', startYear: null, endYear: null, claim: 'Commander of the XI International Brigade in the Spanish Civil War', source: S.huMunnich, locator: '1956-ig', excerpt: 'majd mint a XI. nemzetközi brigád parancsnoka' },
            { functionId: 'security', affiliationId: 'state-hungary', startYear: 1946, endYear: 1949, claim: 'Budapest chief of police', source: S.huMunnich, locator: '1956-ig', excerpt: 'előbb Budapest rendőrfőkapitánya volt (1946–1949)' },
            { functionId: 'diplomacy', affiliationId: 'state-hungary', startYear: 1949, endYear: 1956, claim: 'Diplomatic posts in Helsinki, Sofia, Moscow and Belgrade', locator: 'lead', excerpt: 'From 1949 to 1956 he held diplomatic posts in Helsinki, Sofia, Moscow, and Belgrade' },
            { functionId: 'political-leadership', affiliationId: 'party-hungarian-socialist-workers', startYear: 1956, endYear: 1967, claim: 'Member of the MSZMP Central Committee', locator: 'lead', excerpt: 'member of the Central Committee from 1956 to 1967' },
        ],
        career: [
            ['1915', '러시아군 포로, 톰스크 수용', 'Captured by the Russians; held in Tomsk'],
            ['1918', '헝가리 공산당 창당 참여', 'Co-founder of the Hungarian Communist Party'],
            ['1919', '슬로바키아 평의회 공화국 군사 인민위원', 'War commissar of the Slovak Soviet Republic'],
            ['1936–1939', '스페인 내전 제11국제여단장', 'Commander of the XI International Brigade in Spain'],
            ['1946–1949', '부다페스트 경찰청장', 'Budapest chief of police'],
            ['1956', '너지 정부 내무장관, 카다르 정부 군·공안 장관', 'Interior minister under Nagy; minister of the armed forces and public security under Kádár'],
            ['1958–1961', '헝가리 총리', 'Prime minister of Hungary'],
        ],
    }),
];
