// Person cards for the GDR economic planners and the 1953 uprising (the German
// Economic Commission's deputies Leuschner and Selbmann, Justice Minister Hilde
// Benjamin, the chemist Havemann and the SED ideologue Oelßner), see lib.js
// person(). Excerpts are verbatim from the cited pages.
const { person } = require('../baltic-1940-1953-20261002/lib');

const wiki = (lang, t) => `https://${lang}.wikipedia.org/wiki/` + encodeURI(t);
const S = {
    leuschner: wiki('en', 'Bruno_Leuschner'),
    deLeuschner: wiki('de', 'Bruno_Leuschner_(Politiker)'),
    selbmann: wiki('en', 'Fritz_Selbmann'),
    deSelbmann: wiki('de', 'Fritz_Selbmann'),
    benjamin: wiki('en', 'Hilde_Benjamin'),
    deBenjamin: wiki('de', 'Hilde_Benjamin'),
    havemann: wiki('en', 'Robert_Havemann'),
    deHavemann: wiki('de', 'Robert_Havemann'),
    oelssner: wiki('en', 'Fred_Oelßner'),
    deOelssner: wiki('de', 'Fred_Oelßner'),
};

module.exports = [
    person({
        id: 'bruno-leuschner', groupId: 'world-cold-war',
        given: ['브루노', 'Bruno'], family: ['로이슈너', 'Leuschner'], nativeName: 'Bruno Leuschner', years: '1910–1965',
        citizenship: 'east-germany', origin: 'germany',
        epithet: ['독일경제위원회의 계획 책임자에서 국가계획위원회 위원장이 된 동독 경제 계획가',
            'East German planner who ran planning in the German Economic Commission and then chaired the State Planning Commission'],
        bio: ['베를린 릭스도르프의 구두장이 아들로 사무원으로 일하며 야간에 경제학을 배웠고, 1931년 독일 공산당에 들어갔다. 나치 집권 뒤 지하 신문과 당 군사정보 조직에서 일하다 1936년 체포되어 6년형을 살았고, 작센하우젠과 마우트하우젠 강제수용소에서 1945년 해방을 맞았다. 전후 공산당 경제부를 세워 이끌었고, 1947년부터 독일경제위원회 창설에 큰 역할을 하며 계획을 맡아 1948년 반년 계획과 1949~1950년 2개년 계획을 짰다. 1952~1961년 라우의 뒤를 이어 국가계획위원회 위원장을 지냈고, 1958년 정치국원, 1955~1965년 각료회의 부의장이 되었다. 1961년 위원장직에서 물러나 상호경제원조회의 상임대표를 맡았고, 1965년 동베를린에서 죽었다.',
            'A shoemaker’s son from Rixdorf, Berlin, he worked as a clerk, studied economics at night and joined the KPD in 1931. Under the Nazis he worked for the illegal paper “Der Rote Wedding” and the party’s military intelligence apparatus until his arrest in 1936; sentenced to six years in prison, he was then held in Sachsenhausen and Mauthausen until 1945. After the war he built up and headed the KPD’s economic department, and from 1947 played a major part in creating the German Economic Commission, where he took charge of planning and drew up the half-year plan of 1948 and the two-year plan of 1949/50. He succeeded Heinrich Rau as chairman of the State Planning Commission (1952–1961), joined the Politburo in 1958 and was deputy premier from 1955 to 1965. Removed as planning chief in 1961, he became the GDR’s permanent representative to Comecon. He died in East Berlin in 1965.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: [], en: ['Bruno Max Leuschner'] },
        sources: [S.leuschner, S.deLeuschner],
        facts: {
            years: { claim: '1910–1965', locator: 'lead', excerpt: '12 August 1910 – 10 February 1965' },
            citizenship: { claim: 'Politburo member and chairman of the GDR State Planning Commission', source: S.deLeuschner, locator: 'Einleitung', excerpt: 'war Mitglied des Politbüros des Zentralkomitees der SED und Vorsitzender der Staatlichen Plankommission der DDR' },
            nationalOrigin: { claim: 'German politician born in Rixdorf', source: S.deLeuschner, locator: 'Einleitung', excerpt: 'Bruno Max Leuschner (* 12. August 1910 in Rixdorf; † 10. Februar 1965 in Ost-Berlin)' },
            bio: [
                { claim: 'son of a shoemaker', source: S.deLeuschner, locator: 'Werdegang', excerpt: 'Bruno Leuschner war der Sohn eines Schuhmachers' },
                { claim: 'clerk; evening studies in economics', locator: 'Biography', excerpt: 'In the evenings he studied economics, philosophy and psychology at the Lessing University and the Friedrich Wilhelm University.' },
                { claim: 'joined the KPD in 1931', source: S.deLeuschner, locator: 'Werdegang', excerpt: '1931 trat er der KPD bei' },
                { claim: 'Der Rote Wedding and the M-Apparat', locator: 'Biography', excerpt: 'He was a collaborator of the newspaper "Der Rote Wedding" and was also active in KPD\'s military intelligence M-Apparat.' },
                { claim: 'arrested 1936, six years in prison', locator: 'Biography', excerpt: 'In 1936, Leuschner was arrested and sentenced in 1937 by the District Court of Berlin to six years in prison for "conspiracy to commit high treason"' },
                { claim: 'Sachsenhausen and Mauthausen until 1945', locator: 'Biography', excerpt: 'He was then imprisoned in the Sachsenhausen and Mauthausen concentration camps until he was liberated in 1945.' },
                { claim: 'head of the KPD economic department', source: S.deLeuschner, locator: 'Politik', excerpt: 'Leuschner war 1945 am Aufbau der Wirtschaftsabteilung der KPD beteiligt, deren Vorsitzender er wurde.' },
                { claim: 'German Economic Commission; planning from 1948', source: S.deLeuschner, locator: 'Politik', excerpt: 'war er ab 1947 maßgeblich am Aufbau der Deutschen Wirtschaftskommission beteiligt, wo er zunächst Leiter der Abteilung für Wirtschaftsfragen und ab 1948 zuständig für Planung war' },
                { claim: 'half-year plan 1948 and two-year plan 1949/50', source: S.deLeuschner, locator: 'Politik', excerpt: 'In dieser Funktion war er entscheidend an der Ausarbeitung des Halbjahresplanes 1948 und des Zweijahresplanes 1949/1950 beteiligt.' },
                { claim: 'chairman of the State Planning Commission 1952–1961, succeeding Rau', locator: 'Biography', excerpt: 'from 1952 to 1961 he was chairman of the State Planning Commission as the successor to Heinrich Rau' },
                { claim: 'Politburo 1958; deputy chairman of the Council of Ministers 1955–1965', locator: 'Biography', excerpt: 'Leuschner was deputy chairman of the Council of Ministers of the GDR (1955–1965)' },
                { claim: 'removed in 1961; Comecon representative', source: S.deLeuschner, locator: 'Politik', excerpt: 'ab Juni 1962 Ständiger Vertreter der DDR im Exekutivkomitee des RGW' },
            ],
        },
        activities: [
            { functionId: 'economy', affiliationId: 'state-east-germany', startYear: 1947, endYear: 1949, claim: 'Head of planning in the German Economic Commission', source: S.deLeuschner, locator: 'Politik', excerpt: 'war er ab 1947 maßgeblich am Aufbau der Deutschen Wirtschaftskommission beteiligt, wo er zunächst Leiter der Abteilung für Wirtschaftsfragen und ab 1948 zuständig für Planung war' },
            { functionId: 'economy', affiliationId: 'state-east-germany', startYear: 1950, endYear: 1961, primary: true, claim: 'First deputy chairman, then chairman of the State Planning Commission', locator: 'Biography', excerpt: 'From 1950 to 1952 he was first deputy chairman and from 1952 to 1961 he was chairman of the State Planning Commission as the successor to Heinrich Rau.' },
            { functionId: 'political-leadership', affiliationId: 'party-german-sed', startYear: 1953, endYear: 1965, claim: 'Politburo candidate from 1953, member from 1958', source: S.deLeuschner, locator: 'Politik', excerpt: 'ab 1953 Kandidat und ab 1958 Mitglied des Politbüros des ZK der SED' },
            { functionId: 'government', affiliationId: 'state-east-germany', startYear: 1955, endYear: 1965, claim: 'Deputy chairman of the Council of Ministers', locator: 'Biography', excerpt: 'Leuschner was deputy chairman of the Council of Ministers of the GDR (1955–1965)' },
        ],
        career: [
            ['1931', '독일 공산당 입당', 'Joined the KPD'],
            ['1936–1945', '투옥, 작센하우젠·마우트하우젠 강제수용소 수감', 'Imprisoned; held in Sachsenhausen and Mauthausen'],
            ['1947–1949', '독일경제위원회 계획 책임자', 'In charge of planning at the German Economic Commission'],
            ['1952–1961', '국가계획위원회 위원장', 'Chairman of the State Planning Commission'],
            ['1958', '사회주의통일당 정치국원', 'SED Politburo member'],
            ['1962', '상호경제원조회의 상임대표', 'Permanent representative to Comecon'],
        ],
    }),
    person({
        id: 'fritz-selbmann', groupId: 'world-cold-war',
        given: ['프리츠', 'Fritz'], family: ['젤프만', 'Selbmann'], nativeName: 'Fritz Selbmann', years: '1899–1975',
        citizenship: 'east-germany', origin: 'germany',
        epithet: ['1953년 6월 16일 정부 청사 앞에서 파업 노동자들 앞에 나섰던 동독 중공업 장관',
            'East German heavy-industry minister who faced the striking workers outside the House of Ministries on 16 June 1953'],
        bio: ['헤센 라우터바흐의 구리 세공인 아들로 열일곱에 광부가 되었고, 1차 세계대전에 나가 1918년 병사평의회에 들었다. 1920년 독립사회민주당, 1922년 공산당에 들어가 작센 지구당 정치 책임자와 제국의회 의원이 되었다. 1933년 체포되어 감옥과 작센하우젠·플로센뷔르크 등 강제수용소에서 나치 시대를 버텼다. 전후 작센 경제·계획장관을 거쳐 독일경제위원회 부위원장이 되었고, 동독에서 공업장관과 중공업장관을 지냈다. 1953년 6월 16일 각료의 집 앞 군중 속에 들어가 책상 위에서 연설했으나 야유에 묻혔다. 1958년 울브리히트에게 「일탈적 태도」로 몰려 직책에서 밀려난 뒤 작가로 살았고, 1975년 동베를린에서 죽었다.',
            'The son of a coppersmith from Lauterbach in Hesse, he was working underground at seventeen, served in the First World War and in 1918 sat on a soldiers’ council. He joined the USPD in 1920 and the KPD in 1922, becoming the party’s political secretary in Saxony and a Reichstag deputy. Arrested in 1933, he survived the Nazi years in prisons and in concentration camps including Sachsenhausen and Flossenbürg. After the war he was Saxony’s minister for economics and planning, then deputy chairman of the German Economic Commission, and in the GDR minister of industry and of heavy industry. On 16 June 1953 he walked into the crowd outside the House of Ministries and tried to address it from a desk, but was whistled down. In 1958 Ulbricht pushed him out of his offices for a “deviant attitude”, and he turned to writing. He died in East Berlin in 1975.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: [], en: ['Friedrich Wilhelm Selbmann'] },
        sources: [S.selbmann, S.deSelbmann],
        facts: {
            years: { claim: '1899–1975', locator: 'lead', excerpt: '29 September 1899 – 26 January 1975' },
            citizenship: { claim: 'KPD and SED functionary, minister and author in the GDR', source: S.deSelbmann, locator: 'Einleitung', excerpt: 'war ein deutscher KPD- und SED-Funktionär, Minister und Autor in der DDR' },
            nationalOrigin: { claim: 'born in Lauterbach, Hesse', source: S.deSelbmann, locator: 'Einleitung', excerpt: '* 29. September 1899 in Lauterbach (Hessen); † 26. Januar 1975 in Ost-Berlin' },
            bio: [
                { claim: 'son of a coppersmith; underground at 17; soldiers’ council 1918', source: S.deSelbmann, locator: 'Leben', excerpt: 'Fritz Selbmann, Sohn eines Kupferschmiedes, arbeitete bereits mit 17 Jahren unter Tage, war Soldat im Ersten Weltkrieg und 1918 Mitglied eines Arbeiter- und Soldatenrates.' },
                { claim: 'USPD 1920, KPD 1922', source: S.deSelbmann, locator: 'Leben', excerpt: '1920 trat er in die USPD ein und 1922 in die KPD.' },
                { claim: 'political secretary in Saxony', source: S.deSelbmann, locator: 'Leben', excerpt: 'Er war 1930/31 politischer Sekretär im Bezirk Oberschlesien und im Anschluss bis 1933 im Bezirk Sachsen.' },
                { claim: 'Reichstag deputy 1932/33', source: S.deSelbmann, locator: 'Leben', excerpt: '1932/33 Mitglied des Reichstages' },
                { claim: 'arrested 1933; prisons and concentration camps', source: S.deSelbmann, locator: 'Leben', excerpt: 'Im gleichen Jahr wurde er verhaftet und überlebte den Nationalsozialismus in Zuchthäusern und KZs wie dem KZ Sachsenhausen und dem KZ Flossenbürg.' },
                { claim: 'Saxon economics and planning minister', locator: 'Soviet occupation zone', excerpt: 'in December 1946 he was appointed Economics and Planning Minister in the State of Saxony, a position he retained till 1948' },
                { claim: 'deputy chairman of the German Economic Commission', locator: 'Soviet occupation zone', excerpt: 'He was appointed deputy chairman of the German Economic Commission' },
                { claim: 'minister of industry, then heavy industry', locator: 'German Democratic Republic (East Germany)', excerpt: 'In the new government Selbmann was appointed Minister for Industry in 1949, and then, as the department was very soon subdivided, Minister for Heavy Industry in 1950.' },
                { claim: 'faced the strikers on 16 June 1953', locator: '1953', excerpt: 'He displayed considerable courage, walking into the crowd of more than 10,000 angry strikers, and then clambering onto an office desk from which he attempted to address the crowd.' },
                { claim: 'whistled down', locator: '1953', excerpt: 'but he drew only whistles from those nearest to him' },
                { claim: 'pushed out by Ulbricht in 1958 for a deviant attitude; turned to writing', source: S.deSelbmann, locator: 'Leben', excerpt: 'Wegen „abweichender Haltung“ wurde er von Walter Ulbricht 1958 im Umfeld der sogenannten Schirdewan-Wollweber-Fraktion in der Parteiführung aus seinen politischen und staatlichen Ämtern gedrängt und verlegte sich auf die Schriftstellerei.' },
                { claim: 'died in East Berlin', source: S.deSelbmann, locator: 'Einleitung', excerpt: '† 26. Januar 1975 in Ost-Berlin' },
            ],
        },
        activities: [
            { functionId: 'political-leadership', affiliationId: 'party-german-communist', startYear: 1930, endYear: 1933, claim: 'KPD political secretary in Upper Silesia and Saxony', source: S.deSelbmann, locator: 'Leben', excerpt: 'Er war 1930/31 politischer Sekretär im Bezirk Oberschlesien und im Anschluss bis 1933 im Bezirk Sachsen.' },
            { functionId: 'legislature', affiliationId: 'state-germany', startYear: 1932, endYear: 1933, claim: 'Reichstag deputy for Leipzig', locator: 'Crisis years', excerpt: 'He was elected not simply as a "list candidate", but as a representative of electoral district 29 (Leipzig).' },
            { functionId: 'economy', affiliationId: 'state-east-germany', startYear: 1948, endYear: 1949, claim: 'Deputy chairman of the German Economic Commission', locator: 'Soviet occupation zone', excerpt: 'He was appointed deputy chairman of the German Economic Commission' },
            { functionId: 'industry', affiliationId: 'state-east-germany', startYear: 1949, endYear: 1955, primary: true, claim: 'Minister of Industry and of Heavy Industry', locator: 'lead', excerpt: 'he also served as Minister of Industry and Heavy Industry from 1949 to 1955' },
            { functionId: 'government', affiliationId: 'state-east-germany', startYear: 1955, endYear: 1958, claim: 'Deputy chairman of the Council of Ministers', locator: 'lead', excerpt: 'as Deputy Minister-President of the Council of Ministers from 1955 to 1958' },
            { functionId: 'arts', affiliationId: 'state-east-germany', startYear: 1969, endYear: 1975, claim: 'Vice-president of the GDR Writers’ Association', source: S.deSelbmann, locator: 'Leben', excerpt: 'Von 1969 bis 1975 war er einer der Vizepräsidenten des DDR-Schriftstellerverbandes.' },
        ],
        career: [
            ['1922', '독일 공산당 입당', 'Joined the KPD'],
            ['1932–1933', '제국의회 의원', 'Reichstag deputy'],
            ['1933–1945', '투옥, 작센하우젠·플로센뷔르크 강제수용소 수감', 'Imprisoned; held in Sachsenhausen and Flossenbürg'],
            ['1948–1949', '독일경제위원회 부위원장', 'Deputy chairman of the German Economic Commission'],
            ['1949–1955', '공업장관, 중공업장관', 'Minister of Industry, then of Heavy Industry'],
            ['1958', '「일탈적 태도」로 직책에서 밀려남', 'Pushed out of office for a “deviant attitude”'],
        ],
    }),
    person({
        id: 'hilde-benjamin', groupId: 'world-cold-war',
        given: ['힐데', 'Hilde'], family: ['벤야민', 'Benjamin'], nativeName: 'Hilde Benjamin', years: '1902–1989',
        citizenship: 'east-germany', origin: 'germany',
        epithet: ['1953년 봉기 뒤 페히너를 이어 법무장관이 되어 가혹한 정치 재판을 이끈 동독 법률가',
            'East German jurist who succeeded Fechner as justice minister after the 1953 uprising and led its harsh political trials'],
        bio: ['안할트 베른부르크의 자유주의적 중산층 집안에서 태어나 독일 최초 세대의 여성 법학도로 공부했다. 사회민주당원이었다가 1926년 의사 게오르크 벤야민(발터 벤야민의 동생)과 결혼하고 1927년 공산당에 들어갔다. 나치 시대에 변호사 활동을 금지당했고, 남편은 1942년 마우트하우젠에서 죽었다. 전후 소련 점령지구 사법행정에서 일했고, 동독 최고재판소 부소장으로 여호와의 증인과 「국가의 적」에 대한 공개 재판을 이끌었다. 1953년 7월 15일 파업 노동자 처벌에 반대한 페히너를 이어 법무장관이 되었고, 봉기 가담자를 가혹하게 처벌해 「붉은 힐데」, 「붉은 프라이슬러」로 불렸다. 1967년 울브리히트에게 밀려 물러났고, 1989년 동베를린에서 죽었다.',
            'Born into a liberal middle-class family in Bernburg, Anhalt, she was among the first women to study law in Germany. A Social Democrat, she married the physician Georg Benjamin, brother of Walter Benjamin, in 1926 and joined the KPD in 1927. Barred from practising law under the Nazis, she lost her husband in Mauthausen in 1942. After the war she worked in the justice administration of the Soviet zone, and as vice-president of the GDR Supreme Court presided over show trials of political undesirables and Jehovah’s Witnesses. On 15 July 1953 she succeeded Max Fechner, who had opposed prosecuting the striking workers, as minister of justice, and her heavy sentences against those arrested in June earned her the names “Red Hilde” and “the Red Freisler”. Ulbricht forced her to resign in 1967. She died in East Berlin in 1989.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: [], en: ['Hilde Lange'] },
        sources: [S.benjamin, S.deBenjamin],
        facts: {
            years: { claim: '1902–1989', locator: 'lead', excerpt: '5 February 1902 – 18 April 1989' },
            citizenship: { claim: 'East German judge and minister of justice 1953–1967', locator: 'lead', excerpt: 'was an East German judge who served as the Minister of Justice of the German Democratic Republic from 1953 to 1967' },
            nationalOrigin: { claim: 'born in Bernburg, Duchy of Anhalt', locator: 'Early life', excerpt: 'Hilde Lange was born on 5 February 1902 in Bernburg, Duchy of Anhalt, into a middle class and liberal-minded Protestant family.' },
            bio: [
                { claim: 'among the first women to study law', locator: 'Early life', excerpt: 'She was among the first women to study law in Germany' },
                { claim: 'SPD member', locator: 'Early life', excerpt: 'By this time, she was a member of the Social Democratic Party of Germany (SPD).' },
                { claim: 'married Georg Benjamin, brother of Walter Benjamin', locator: 'Politics and early career', excerpt: 'Georg was the brother of writer Walter Benjamin' },
                { claim: 'joined the KPD in 1927', locator: 'Politics and early career', excerpt: 'She quit the moderate left-wing SPD and in 1927 joined her husband in the far-left Communist Party of Germany (KPD).' },
                { claim: 'barred from practising law under the Nazis', locator: 'Politics and early career', excerpt: 'she obtained a Berufsverbot and was forbidden to practice law after the Nazi rise to power in 1933' },
                { claim: 'husband killed in Mauthausen 1942', locator: 'Politics and early career', excerpt: 'until he was finally killed at the Mauthausen in 1942' },
                { claim: 'Soviet-zone justice administration', locator: 'German Democratic Republic', excerpt: 'After the war, Benjamin was appointed head of the Personnel and Schools Department of the German Central Administration for Justice in the Soviet Occupation Zone' },
                { claim: 'vice-president of the Supreme Court; show trials', locator: 'German Democratic Republic', excerpt: 'presided over a series of show trials against those identified as political undesirables, such as Johann Burianek and Wolfgang Kaiser, as well as against Jehovah\'s Witnesses' },
                { claim: 'succeeded Fechner on 15 July 1953', locator: 'Minister of Justice', excerpt: 'On 15 July 1953, Benjamin was appointed Minister of Justice of the German Democratic Republic, succeeding Max Fechner in the aftermath of the Uprising of 1953' },
                { claim: 'Fechner opposed prosecuting the strikers', locator: 'Minister of Justice', excerpt: 'Fechner had stated in an interview to Neues Deutschland that he opposed the prosecution of workers who had taken part in the 17 June strike' },
                { claim: 'prosecuted those arrested in June', locator: 'Minister of Justice', excerpt: 'Benjamin was responsible for the prosecution of those arrested during the June protests and strikes which, unlike her predecessor, she fully endorsed.' },
                { claim: 'nicknames', locator: 'Minister of Justice', excerpt: 'earned Benjamin the nicknames "Red Hilde", "The Red Freisler," and, "The Red Guillotine."' },
                { claim: 'forced to resign in 1967', locator: 'Minister of Justice', excerpt: 'In July 1967, Ulbricht forced Benjamin to resign' },
                { claim: 'died in East Berlin in April 1989', locator: 'Minister of Justice', excerpt: 'She died in East Berlin in April 1989.' },
            ],
        },
        activities: [
            { functionId: 'law', affiliationId: 'state-east-germany', startYear: 1949, endYear: 1953, claim: 'Vice-president of the GDR Supreme Court', locator: 'German Democratic Republic', excerpt: 'she was appointed to a number of high-ranking positions, including the Vice President of the Supreme Court of the German Democratic Republic and a member of the Volkskammer' },
            { functionId: 'law', affiliationId: 'state-east-germany', startYear: 1953, endYear: 1967, primary: true, claim: 'Minister of Justice of the GDR', locator: 'lead', excerpt: 'was an East German judge who served as the Minister of Justice of the German Democratic Republic from 1953 to 1967' },
            { functionId: 'political-leadership', affiliationId: 'party-german-sed', startYear: 1954, endYear: 1989, claim: 'Member of the SED Central Committee until her death', locator: 'Minister of Justice', excerpt: 'In 1954, she was appointed to the Central Committee of the SED and would remain a member until her death.' },
        ],
        career: [
            ['1927', '독일 공산당 입당', 'Joined the KPD'],
            ['1949–1953', '동독 최고재판소 부소장', 'Vice-president of the GDR Supreme Court'],
            ['1953–1967', '동독 법무장관', 'GDR Minister of Justice'],
            ['1954', '사회주의통일당 중앙위원', 'Member of the SED Central Committee'],
            ['1967', '울브리히트에 의해 사임', 'Forced to resign by Ulbricht'],
        ],
    }),
    person({
        id: 'robert-havemann', groupId: 'world-cold-war',
        given: ['로베르트', 'Robert'], family: ['하베만', 'Havemann'], nativeName: 'Robert Havemann', years: '1910–1982',
        citizenship: 'east-germany', origin: 'germany',
        epithet: ['나치의 사형 선고를 살아남고 뒤에 사회주의통일당에서 쫓겨나 가택연금된 동독의 화학자·반체제 인사',
            'East German chemist who survived a Nazi death sentence and later, expelled from the SED, became a dissident under house arrest'],
        bio: ['뮌헨에서 태어나 베를린과 뮌헨에서 화학을 공부했고, 카이저 빌헬름 연구소에서 물리화학 박사 학위를 받았다. 저항 단체 「유럽 연합」을 세웠다가 1943년 게슈타포에 체포되어 사형을 선고받았으나, 전쟁에 필요한 연구를 이유로 집행이 거듭 미뤄져 살아남았다. 전후 베를린의 카이저 빌헬름 연구소들을 이끌다 미국 당국에 해임되었고, 1950년 훔볼트 대학교 물리화학 교수가 되어 인민의회 의원과 독일평화위원회 위원을 지냈다. 1953년 6월 16일 젤프만과 함께 정부 청사 앞 군중 앞에 섰다. 1963~1964년 강의 「도그마 없는 변증법」으로 당에서 쫓겨나고 교수직을 잃었다. 1976년 비어만 추방에 항의한 뒤 가택연금되었고, 1982년 그륀하이데에서 죽었다.',
            'Born in Munich, he studied chemistry in Munich and Berlin and took a doctorate in physical chemistry at the Kaiser Wilhelm Institute. A founder of the resistance group European Union, he was arrested by the Gestapo in 1943 and sentenced to death, but his execution was repeatedly postponed on the grounds that his research was needed, and he survived. After the war he headed Berlin’s Kaiser Wilhelm Institutes until the Americans dismissed him; in 1950 he became professor of physical chemistry at the Humboldt University, a member of the Volkskammer and of the German Peace Committee. On 16 June 1953 he faced the crowd outside the House of Ministries with Fritz Selbmann. His 1963–64 lectures, published as “Dialectics without Dogma”, cost him his party membership and his chair. After protesting Wolf Biermann’s expatriation in 1976 he was put under house arrest. He died in Grünheide in 1982.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: [], en: ['Robert Hans Günther Havemann'] },
        sources: [S.havemann, S.deHavemann],
        facts: {
            years: { claim: '1910–1982', locator: 'lead', excerpt: '11 March 1910 – 9 April 1982' },
            citizenship: { claim: 'East German chemist, physicist and dissident', locator: 'lead', excerpt: 'was an East German chemist, physicist, and dissident' },
            nationalOrigin: { claim: 'German chemist born in Munich', source: S.deHavemann, locator: 'Einleitung', excerpt: '* 11. März 1910 in München; † 9. April 1982 in Grünheide) war ein deutscher Chemiker' },
            bio: [
                { claim: 'studied chemistry; doctorate at the Kaiser Wilhelm Institute', locator: 'Life and career', excerpt: 'He studied chemistry in Berlin and Munich from 1929 to 1933, and then later received a doctorate in physical chemistry from the Kaiser Wilhelm Institute.' },
                { claim: 'founder of European Union; arrested 1943', locator: 'Life and career', excerpt: 'was one of the founders of the resistance group, European Union. It was in connection with this group that he was arrested by the Gestapo in 1943.' },
                { claim: 'death sentence repeatedly postponed', locator: 'Life and career', excerpt: 'He received a death sentence for treason, but his execution was continually postponed' },
                { claim: 'research deemed important for the war', source: S.deHavemann, locator: 'NS-Diktatur', excerpt: 'Dabei wurde argumentiert, Havemann werde für „kriegswichtige“ Forschung benötigt.' },
                { claim: 'headed the Berlin Kaiser Wilhelm Institutes; dismissed by the US authorities', source: S.deHavemann, locator: 'Leben zwischen 1945 und 1965', excerpt: 'Dieser verfügte im Januar 1948 Havemanns Entlassung als Leiter der Berliner Kaiser-Wilhelm-Gesellschaft' },
                { claim: 'professor at the Humboldt University', locator: 'Life and career', excerpt: 'He then became a professor of physical chemistry at the Humboldt University of Berlin.' },
                { claim: 'Volkskammer 1950–1963', source: S.deHavemann, locator: 'Leben zwischen 1945 und 1965', excerpt: '1950–1963 war er Mitglied der Volkskammer der DDR' },
                { claim: 'German Peace Committee from 1950', source: S.deHavemann, locator: 'Leben zwischen 1945 und 1965', excerpt: 'Seit 1950 war er Mitglied des Deutschen Friedenskomitees (später Friedensrat der DDR)' },
                { claim: '1963–64 lectures; expelled from the SED and dismissed', locator: 'Life and career', excerpt: "was expelled from the ruling Socialist Unity Party and dismissed from the University—officially because he gave an interview to a newspaper from West Germany" },
                { claim: 'Dialektik ohne Dogma', source: S.deHavemann, locator: 'Ausschluss aus der SED 1964', excerpt: 'veröffentlicht in der Bundesrepublik unter dem Titel: Dialektik ohne Dogma?' },
                { claim: 'protested Biermann’s expatriation in 1976', source: S.deHavemann, locator: 'Hausarrest (1976 bis 1979)', excerpt: '1976 protestierte er gegen die Ausbürgerung seines Freundes, des regimekritischen Liedermachers Wolf Biermann, aus der DDR.' },
                { claim: 'house arrest from 1976', locator: 'Life and career', excerpt: 'He continued his work as a socialist critic and was put under house arrest in 1976, at his home in the village of Grünheide.' },
                { claim: 'died in Grünheide in 1982', source: S.deHavemann, locator: 'Tod', excerpt: 'Robert Havemann starb am 9. April 1982 in Grünheide' },
            ],
        },
        activities: [
            { functionId: 'science', affiliationId: 'state-east-germany', startYear: 1950, endYear: 1964, primary: true, claim: 'Director of the Institute of Physical Chemistry at the Humboldt University', source: S.deHavemann, locator: 'Leben zwischen 1945 und 1965', excerpt: 'Noch im gleichen Jahr wurde er zum Direktor des Instituts für Physikalische Chemie an der Humboldt-Universität in Ost-Berlin und zum Ordinarius für Physikalische Chemie ernannt.' },
            { functionId: 'legislature', affiliationId: 'state-east-germany', startYear: 1950, endYear: 1963, claim: 'Member of the Volkskammer', source: S.deHavemann, locator: 'Leben zwischen 1945 und 1965', excerpt: '1950–1963 war er Mitglied der Volkskammer der DDR' },
        ],
        career: [
            ['1932', '독일 공산당 입당', 'Joined the KPD'],
            ['1943', '게슈타포에 체포, 사형 선고', 'Arrested by the Gestapo and sentenced to death'],
            ['1950', '훔볼트 대학교 물리화학 교수', 'Professor of physical chemistry at the Humboldt University'],
            ['1950–1963', '인민의회 의원', 'Member of the Volkskammer'],
            ['1964', '사회주의통일당에서 제명', 'Expelled from the SED'],
            ['1976–1979', '그륀하이데에서 가택연금', 'House arrest in Grünheide'],
        ],
    }),
    person({
        id: 'fred-oelssner', groupId: 'world-cold-war',
        given: ['프레트', 'Fred'], family: ['욀스너', 'Oelßner'], nativeName: 'Fred Oelßner', years: '1903–1977',
        citizenship: 'east-germany', origin: 'germany',
        epithet: ['1958년까지 사회주의통일당의 수석 이데올로그였다가 쉬르데반 사건으로 정치국에서 쫓겨난 경제학자',
            'Economist and the SED’s chief ideologue until 1958, when he was expelled from the Politburo in the Schirdewan affair'],
        bio: ['라이프치히에서 태어나 1919년 독립사회민주당, 1920년 공산당에 들어갔고 당 신문 편집자로 일했다. 1926년 모스크바 국제 레닌 학교와 붉은 교수 연구소에서 공부했다. 1933년 망명해 파리에서 울브리히트의 비서로 일했고, 1936년 모스크바에서 「이념적 일탈」로 교직에서 쫓겨났으며, 전쟁 중에는 모스크바 방송 독일어부 편집장을 지냈다. 1945년 아커만 그룹과 함께 돌아와 당 선전·교육을 맡았고, 1950년 정치국원, 1950~1955년 선전 담당 중앙위원회 서기가 되어 당의 수석 이데올로그로 통했다. 1953년 6월 할레에서 봉기 진압 지휘부를 꾸렸다. 1956년 뒤 농업 전면 집단화에 반대하다 1958년 정치국에서 쫓겨났고, 과학아카데미 경제연구소장을 지냈다.',
            'Born in Leipzig, he joined the USPD in 1919 and the KPD in 1920 and worked as an editor on party papers. From 1926 he studied in Moscow at the International Lenin School and the Institute of Red Professors. In exile from 1933 he was Ulbricht’s secretary in Paris; in Moscow he lost his teaching posts in 1936 for alleged deviations, and in the war became chief editor of Moscow Radio’s German service. Returning with the Ackermann Group in 1945, he ran the party’s propaganda and education work, joined the Politburo in 1950 and was Central Committee secretary for propaganda from 1950 to 1955, effectively the party’s chief ideologue. In June 1953 he set up the command in Halle that put down the uprising. After 1956 he opposed the complete collectivisation of agriculture, and in 1958 he was expelled from the Politburo. He then directed the Institute of Economics of the Academy of Sciences.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: [], en: ['Fred Oelssner', 'Fritz Larew'] },
        linkExpressions: [['en', 'Fred Oelssner']],
        sources: [S.oelssner, S.deOelssner],
        facts: {
            years: { claim: '1903–1977', locator: 'lead', excerpt: '27 February 1903 – 7 November 1977' },
            citizenship: { claim: 'leading political figure in the GDR', locator: 'lead', excerpt: 'was a German communist politician, economist and a leading political figure in the German Democratic Republic (East Germany)' },
            nationalOrigin: { claim: 'born in Leipzig', locator: 'Provenance and early years', excerpt: 'Fred Oelßner was born in Leipzig.' },
            bio: [
                { claim: 'USPD 1919, KPD 1920', source: S.deOelssner, locator: 'Leben', excerpt: '1919 trat er der Unabhängigen Sozialdemokratischen Partei Deutschlands (USPD), 1920 der Kommunistischen Partei Deutschlands (KPD) bei.' },
                { claim: 'editor on party papers', source: S.deOelssner, locator: 'Leben', excerpt: '1922 bis 1923 Redakteur an der Schlesischen Arbeiterzeitung in Breslau, danach Redakteur in Chemnitz und Stuttgart' },
                { claim: 'International Lenin School and Institute of Red Professors', source: S.deOelssner, locator: 'Leben', excerpt: '1926 wurde Oelßner nach Moskau delegiert, wo er bis 1928 Schüler und 1929 Aspirant der Internationalen Lenin-Schule war. Danach war er Mitarbeiter der ökonomischen Fakultät des Instituts der Roten Professur.' },
                { claim: 'Ulbricht’s secretary in exile', source: S.deOelssner, locator: 'Leben', excerpt: '1933 emigrierte Oelßner nach Frankreich, wo er persönlicher Sekretär von Walter Ulbricht war.' },
                { claim: 'dismissed in 1936 for alleged ideological deviations', locator: 'Back in Moscow', excerpt: 'In August 1936 Oelßner was dismissed from his teachings posts on account of alleged ideological deviations.' },
                { claim: 'chief editor of Moscow Radio’s German service', source: S.deOelssner, locator: 'Leben', excerpt: '1941 bis 1944 war er Redakteur, später Chefredakteur der deutschen Redaktion von Radio Moskau' },
                { claim: 'returned with the Ackermann group', source: S.deOelssner, locator: 'Leben', excerpt: '1945 kehrte er mit der KPD-Gruppe um Anton Ackermann nach Deutschland zurück.' },
                { claim: 'Politburo 1950; propaganda secretary 1950–1955', locator: 'German Democratic Republic', excerpt: 'Oelßner was in office between 1950 and 1955 as Central Committee Secretary for Propaganda.' },
                { claim: 'chief ideologue until 1958', locator: 'German Democratic Republic', excerpt: "Till 1958 he was effectively the party's chief ideologue." },
                { claim: 'set up the Halle command against the 1953 uprising', source: S.deOelssner, locator: 'Leben', excerpt: 'Er konstituierte in Halle die Bezirkseinsatzleitung zur Niederschlagung des Aufstands vom 17. Juni 1953.' },
                { claim: 'opposed complete collectivisation', locator: 'German Democratic Republic', excerpt: 'Within the politburo Oelßner had emerged as a critic of plans for the "complete collectivisation of agriculture"' },
                { claim: 'expelled from the Politburo in 1958', locator: 'German Democratic Republic', excerpt: 'On 8 February 1958 Fred Oelßner was expelled from the Politburo and relieved of all his political and party offices' },
                { claim: 'director of the Institute of Economics', source: S.deOelssner, locator: 'Leben', excerpt: '1958 bis 1969 war er Direktor des Instituts für Wirtschaftswissenschaften der Deutschen Akademie der Wissenschaften.' },
            ],
        },
        activities: [
            { functionId: 'propaganda', affiliationId: 'party-german-sed', startYear: 1950, endYear: 1955, primary: true, claim: 'Central Committee secretary for propaganda', locator: 'German Democratic Republic', excerpt: 'Oelßner was in office between 1950 and 1955 as Central Committee Secretary for Propaganda.' },
            { functionId: 'political-leadership', affiliationId: 'party-german-sed', startYear: 1950, endYear: 1958, claim: 'Politburo member from 1950 until his expulsion in 1958', locator: 'lead', excerpt: 'Oelßner became a member of the SED Politburo in 1950.' },
            { functionId: 'government', affiliationId: 'state-east-germany', startYear: 1955, endYear: 1958, claim: 'Deputy chairman of the Council of Ministers', locator: 'German Democratic Republic', excerpt: 'In 1955 he also became a deputy chairman of the Ministerial Council.' },
            { functionId: 'scholarship', affiliationId: 'state-east-germany', startYear: 1958, endYear: 1969, claim: 'Director of the Institute of Economics, Academy of Sciences', source: S.deOelssner, locator: 'Leben', excerpt: '1958 bis 1969 war er Direktor des Instituts für Wirtschaftswissenschaften der Deutschen Akademie der Wissenschaften.' },
        ],
        career: [
            ['1920', '독일 공산당 입당', 'Joined the KPD'],
            ['1926–1932', '모스크바 국제 레닌 학교·붉은 교수 연구소', 'International Lenin School and Institute of Red Professors, Moscow'],
            ['1941–1944', '모스크바 방송 독일어부 편집장', 'Chief editor of Moscow Radio’s German service'],
            ['1950–1958', '사회주의통일당 정치국원', 'SED Politburo member'],
            ['1950–1955', '선전 담당 중앙위원회 서기', 'Central Committee secretary for propaganda'],
            ['1958–1969', '과학아카데미 경제연구소장', 'Director of the Institute of Economics, Academy of Sciences'],
        ],
    }),
];
