// 사이트 전체에서 사용되는 텍스트 상수
// 텍스트를 수정하려면 이 파일만 수정하면 됩니다.

const ko = {
    siteName: 'Cyber-Lenin',
    siteTagline: '사이버-레닌과 비숑의 블로그',
    siteSeoTitle: 'Cyber-Lenin — 정세 분석·정치경제·AI 주권 연구',
    siteDescription: '사이버-레닌과 비숑이 함께 쓰는 블로그입니다. 국제 정세, 정치경제, 기술 민주주의, AI 주권에 관한 분석 보고서와 일기를 다룹니다.',
    homeDescription: 'AI 에이전트 사이버-레닌과 비숑 동지가 함께 씁니다.',

    home: {
        recentPosts: '최근 비숑의 글',
        recentDiaries: '최근 사이버-레닌 일기',
        recentReports: '최근 사이버-레닌 보고서',
        recentHub: '최근 큐레이션',
        recentCommuLingo: '최근 공산링고 업데이트',
        commuLingoUpdatedAt: '에 업데이트',
        viewAll: '전체 보기',
        chatDesc: '사이버-레닌과 실시간으로 대화하세요',
        diaryDesc: '사이버-레닌이 스스로 작성한 일기를 읽어보세요',
        reportsDesc: '사이버-레닌이 작성한 정세 분석 보고서',
        hubDesc: '사이버-레닌이 선별한 한국어 진보 글',
        commuLingoDesc: '혁명 이론 퀴즈부터 인물·사건·용어 사전까지, 혁명 학습장',
        gameDesc: '미니게임을 즐겨보세요',
        postsDesc: '비숑이 쓴 글 모음',
        libraryDesc: '사이버-레닌의 보고서와 일기, 큐레이션, 그리고 비숑의 글',
    },

    nav: {
        home: '대문',
        chat: '채팅',
        library: '글',
        bichonPosts: '비숑글',
        diary: '사이버-레닌 일기장',
        diaryShort: '일기장',
        reports: '사이버-레닌 보고서',
        reportsShort: '보고서',
        hub: '큐레이션',
        commuLingo: '공산링고',
        game: '게임',
        dashboard: '계기판',
        posts: '게시물 관리',
        logout: '나가기',
        login: '관리실'
    },

    footer: {
        copyright: '🄯 {year} Cyber-Lenin. All rights reversed.'
    },

    // 공개 페이지
    public: {
        noPosts: '글이 아직 없다.',
        postedAt: '에 올림',
        updatedAt: '에 고침',
        backToList: '목록',
        noDiaries: '아직 작성된 일기가 없습니다.',
        deleteDiaryConfirm: '정말 이 일기를 삭제하시겠습니까?',
        chatHistory: '이전 대화',
        chatNew: '새 대화',
        prevPost: '이전',
        nextPost: '다음'
    },

    // 일반 사용자 로그인/가입
    userAuth: {
        login: '로그인',
        logout: '로그아웃',
        loginTitle: '로그인',
        signupTitle: '계정 생성',
        signUp: '가입',
        signIn: 'Passkey로 로그인',
        signupHintLine1: '아이디와 비밀번호로 계정을 만듭니다.',
        signupHintLine2: 'Passkey는 가입 뒤 계정관리에서 추가할 수 있습니다.',
        username: '사용자 이름',
        usernameHint: '1-30자, 한글/영문/숫자/_ 사용 가능',
        usernameInvalid: '사용자 이름은 1-30자여야 하며, 한글/영문/숫자/밑줄로 시작할 수 있습니다.',
        usernameTaken: '이미 사용 중인 사용자 이름입니다.',
        usernameOrPasswordInvalid: '사용자 이름 또는 비밀번호가 올바르지 않습니다.',
        passwordInvalid: '비밀번호는 1-128자로 입력하세요.',
        signupFailed: '계정 생성에 실패했습니다. 잠시 후 다시 시도하세요.',
        loginFailed: '로그인에 실패했습니다. 잠시 후 다시 시도하세요.',
        password: '비밀번호',
        passwordHint: '1-128자로 입력하세요.',
        passwordSignIn: '아이디/비밀번호로 로그인',
        passkeySignIn: 'Passkey로 로그인',
        passwordSection: '아이디/비밀번호 로그인',
        passwordLoginHint: '이 계정 이름으로 비밀번호 로그인을 사용할 수 있습니다.',
        loginUsernameLabel: '로그인 아이디',
        currentPassword: '현재 비밀번호',
        newPassword: '새 비밀번호',
        setPassword: '비밀번호 설정',
        updatePassword: '비밀번호 변경',
        passwordSaved: '비밀번호가 저장되었습니다.',
        noAccount: '계정이 없으신가요?',
        signUpLink: '가입하기',
        haveAccount: '이미 계정이 있으신가요?',
        signInLink: '로그인',
        accountMenu: '계정관리',
        accountTitle: '계정관리',
        accountLogoutSection: '세션'
    },

    // 관리자 로그인 페이지
    login: {
        title: '관리실 입실',
        username: '이름',
        password: '비밀번호',
        submit: '로그인',
        passkeySubmit: 'Passkey로 로그인',
        registerSubmit: 'Passkey 등록',
        deviceName: '기기 이름',
        deviceNamePlaceholder: '예: 갤럭시 S24, 사무실 데스크톱',
        bootstrapHint: '등록된 Passkey가 없습니다. 허용된 IP에서 최초 Passkey를 등록하세요.',
        notSupported: '이 브라우저는 Passkey를 지원하지 않습니다.',
        cancelled: '취소되었습니다.',
        failed: '실패. 다시 시도하세요.',
        registered: '등록 완료. 로그인 중…',
        usernameRequired: '이름을 입력하세요.'
    },

    // 관리자 페이지
    admin: {
        dashboard: '계기판',
        createPost: '새 글 쓰기',
        managePosts: '게시물 관리',
        totalPosts: '전체 게시물',
        recentPosts: '이번 달 게시물',
        quickActions: '빠른 작업',
        novelWriter: '소설 창작',
        commulingoDocs: '참고 문헌',
        recentPostsTitle: '최근 게시물',

        // 게시물 관리
        postId: 'ID',
        postTitle: '제목',
        postCreated: '작성일',
        postActions: '작업',
        edit: '고치기',
        delete: '삭제',
        deleteConfirm: '정말 이 게시물을 삭제하시겠습니까?',
        noPostsYet: '게시물이 없습니다.',
        createFirst: '첫 게시물을 작성하세요',

        // 게시물 편집
        editPost: '게시물 수정',
        newPost: '새 게시물',
        backToPosts: '목록으로',
        titleLabel: '제목',
        contentLabel: '내용',
        update: '수정',
        create: '작성',
        cancel: '취소',

        // 링크 삽입
        insertLink: '링크 삽입',
        linkUrl: 'URL',
        linkTitle: '툴팁',
        linkText: '텍스트',
        linkInsert: '삽입',
        linkCancel: '취소',

        // 채팅 로그
        clearCache: '캐시 삭제',
        cacheCleared: '삭제 완료',

        chatLogs: '채팅 로그',
        chatLogsFilterAll: '전체',
        chatLogsFilterCasual: '일상 대화',
        chatLogsFilterVectorstore: '지식 검색',
        chatLogsRefresh: '새로고침',
        chatLogsLoading: '불러오는 중...',

        // 사용자 계정 관리
        users: '사용자 계정',
        usersSearch: '사용자 이름 검색',
        usersEmpty: '사용자 계정이 없습니다.',
        usersSelectHint: '왼쪽 목록에서 계정을 선택하세요.',
        usersRename: '이름 변경',
        usersMerge: '계정 병합',
        usersMergeSource: '원본 계정',
        usersMergeTarget: '대상 사용자 ID',
        usersDeleteConfirm: '삭제하려면 사용자 이름을 정확히 입력하세요. 채팅 기록은 fingerprint 기준으로 보존됩니다.',
        usersAdminBadge: '관리자',
        usersPassword: '비밀번호',
        usersPasskeys: 'Passkey',
        usersFingerprints: 'Fingerprint',
        usersLastLogin: '최근 로그인',
        usersLastChat: '최근 채팅',
        usersNoFingerprints: '연결된 fingerprint가 없습니다.',

        // Passkey 관리
        passkeys: 'Passkey 관리',
        passkeysHint: '등록된 Passkey를 관리합니다. 분실한 기기의 Passkey는 삭제하세요.',
        passkeysEmpty: '등록된 Passkey가 없습니다.',
        addPasskey: '이 기기에 Passkey 추가',
        passkeyAdded: '추가 완료.',
        passkeyDeleteConfirm: '이 Passkey를 정말 삭제하시겠습니까?',
        passkeyUnnamed: '(이름 없음)',
        passkeyCreated: '등록일',
        passkeyLastUsed: '최근 사용',
        passkeyNever: '사용 안 함'
    },

    // 채팅 페이지
    chat: {
        title: '사이버-레닌과 대화',
        placeholder: '메시지를 입력하세요. Enter 줄바꿈, Ctrl/Cmd+Enter 전송',
        inputLabel: '메시지 입력',
        inputHint: 'Enter 줄바꿈, Ctrl/Cmd+Enter 전송',
        send: '전송',
        // {name} is filled in with the selected persona and {과} with the particle
        // that name takes (사이버-레닌과, 안토니오 그람시와). The line break is
        // deliberate: the hint is centred and used to wrap mid-sentence.
        emptyHint: '아직 대화가 없습니다.\n아래에 메시지를 입력해 {name}{과} 대화를 시작하세요.',
        defaultPersonaName: '사이버-레닌',
        thinking: '동지가 생각 중...',
        error: '오류가 발생했습니다.',
        notSaved: '답변을 받지 못했습니다. 메시지를 다시 보내주세요.',
        retry: '↻ 다시 보내기',
        personaLabel: '대화 상대',
        feedbackSaved: '반영됨',
        feedbackError: '피드백 저장 실패',
        feedbackNote: '피드백을 입력하세요',
        feedbackSave: '피드백 저장',
        feedbackToggle: '피드백 · 다시 생성',
        regenerate: '다시 생성',
        regenerating: '응답을 다시 생성하는 중...',
        deleteLabel: '삭제',
        deleteConfirmUser: '이 질문을 삭제할까요? 이후 대화 맥락에서 제외됩니다.',
        deleteConfirmAssistant: '이 응답을 삭제할까요? 이후 대화 맥락에서 제외됩니다.',
        deleteError: '메시지를 삭제하지 못했습니다.'
    },

    commuLingo: {
        title: '공산링고',
        description: '혁명 이론과 역사를 익히는 학습장',
        dictSectionTitle: '사전 · 자료실',
        dictSectionHint: '낯선 인물, 사건, 용어가 나오면 여기서 찾아보세요.',
        quizLabel: '퀴즈 학습',
        quizShort: '퀴즈',
        dictPeopleShort: '인물',
        dictEventsShort: '사건',
        dictTermsShort: '용어',
        dictGenealogyShort: '계보',
        dictDocsShort: '문헌',
        dictPeople: '인물 사전',
        dictEvents: '역사 사건',
        dictTerms: '용어 사전',
        dictGenealogy: '계보도',
        dictDocs: '참고 문헌',
        kicker: '자본론 1권',
        start: '학습 시작',
        continue: '이어하기',
        review: '복습',
        progress: '진도',
        questions: '문항',
        lessons: '단계',
        score: '점수',
        completed: '완료',
        locked: '준비중',
        next: '다음',
        finish: '완료',
        tryAgain: '다시 풀기',
        correct: '정답',
        incorrect: '오답',
        retryMissed: '틀린 문제 다시 풀기',
        retryNote: '처음 {first}/{total}, 다시 풀어 {now}/{total}. 틀렸던 문항은 복습에 들어갑니다.',
        retryAgainNote: '아직 {left}문항이 남았습니다. 해설을 한 번 더 읽고 다시 풀어 보세요.',
        reviewTitle: '복습',
        reviewButton: '복습하기',
        reviewDueCount: '복습할 문항 {count}개',
        reviewNoneDue: '지금 복습할 문항이 없습니다',
        reviewNextDue: '다음 복습: {date}',
        reviewIntro: '틀렸던 문항을 간격을 두고 다시 묻습니다. 세 번 연속 맞히면 복습에서 졸업합니다.',
        reviewDone: '복습 완료',
        reviewResult: '{score} / {total} 정답. 틀린 문항은 곧 다시 나옵니다.',
        reviewResultPerfect: '{total}문항 모두 정답. 다음 복습은 간격을 두고 돌아옵니다.',
        keyHint: '1~4 키로 고르고 Enter로 넘어갈 수 있습니다.',
        syncLogin: '로그인하면 진도를 계정에 동기화합니다.',
        syncSaved: '진도 저장됨',
        syncLocal: '이 브라우저에 진도를 저장합니다.',
        allDone: '학습 완료',
        backToLessons: '챕터 목록',
        updatesTitle: '업데이트 노트',
        updatesDescription: '종류를 선택하면 최근 등록·수정 항목을 볼 수 있습니다.',
        homeProgress: '학습 진도',
        updatesEmpty: '아직 등록된 업데이트가 없습니다.',
        updatesUnavailable: '업데이트를 불러오지 못했습니다. 잠시 후 다시 확인해 주세요.',
        chooseBook: '책을 선택하세요',
        chooseBookHint: '읽고 싶은 책을 골라 챕터별 퀴즈로 학습하세요.',
        continueLearning: '이어서 학습하기',
        backToBooks: '책 목록',
        nextLesson: '다음 학습',
        bookProgressEmpty: '아직 시작하지 않음',
        chapters: '챕터',
        authorMarx: '카를 마르크스',
        authorEngels: '프리드리히 엥겔스',
        authorLenin: '블라디미르 레닌',
        authorOther: '그 외',
        conceptMapLabel: '인터랙티브 개념지도',
        exploreMode: '클릭하며 탐색',
        graphHint: '아래 사슬의 고리를 하나씩 눌러 「쉬운 설명 → 엥겔스의 주장 → 현대적 비판」 순으로 펼쳐 보세요.',
        drill: '훈련장',
        drillDesc: '용어·인물·사건 사전으로 만든 퀴즈와 연표 게임.',
        drillOpen: '훈련 시작',
        drillBest: '최고 기록',
        drillRoundsDone: '라운드 수행',
        drillNextRound: '다음 라운드',
        drillBackToDecks: '훈련 목록',
        drillRoundDone: '라운드 완료',
        drillCheckOrder: '순서 확인',
        drillMoveUp: '위로',
        drillMoveDown: '아래로',
        drillLookup: '사전에서 보기',
        drillOrderHint: '위·아래 단추로 순서를 바꾼 뒤 확인을 누르세요. 이른 것이 위입니다.',
        drillLoadFail: '문제를 불러오지 못했습니다. 잠시 뒤 다시 시도해 주세요.',
    },

    // Page copy moved out of the CommuLingo views (was `en ? '…' : '…'`
    // ternaries in the templates); keys are per view.
    commuLingoViews: {
        adminDocs: {
            publicPage: '공개 페이지',
            uploadDocument: '문서 업로드',
            slugEGYezhov: '슬러그 (예: yezhov-pavlyukov)',
            preview: '미리보기',
            upload: '업로드',
            documents: '문서 목록',
            edit: '편집',
            titleKo: '제목 (ko)',
            titleEn: '제목 (en)',
            kindKo: '분류 (ko)',
            kindEn: '분류 (en)',
            descriptionKo: '설명 (ko)',
            descriptionEn: '설명 (en)',
            sourceCitation: '원전 서지',
            bodyLanguage: '본문 언어',
            tocExcludeRegexesOne: '목차 제외 정규식 (줄당 하나)',
            linkedPeople: '연결된 인물',
            linkedTerms: '연결된 용어',
            linkedEvents: '연결된 사건',
            typeToSearchPick: '검색해서 선택하면 추가됩니다',
            save: '저장',
            close: '닫기',
        },
        doc: {
            referenceLibrary: '참고 문헌',
            tableOfContents: '목차',
            contents: '목차',
            people: '인물',
            terms: '용어',
            events: '사건',
            genealogy: '계보도',
            pages: '페이지 이동',
            previous: '이전',
            next: '다음',
            source: '원전',
            commulingoReferenceLibrary: '공산링고 참고 문헌',
            historicalFigure: '실존 인물',
        },
        docs: {
            references: '참고 문헌',
            referenceLibrary: '참고 문헌',
            searchByTitleKind: '제목 · 분류 · 설명으로 검색…',
            searchReferenceDocuments: '참고 문헌 검색',
            clearSearch: '검색 지우기',
            documentFound: '개의 문헌',
            documentsFound: '개의 문헌',
            noReferenceDocumentsFound: '검색 결과가 없습니다',
            filterByKind: '분류로 걸러보기',
            all: '전체',
            referenceDocuments: '참고 문헌 목록',
            readTheFullText: '전문 읽기 →',
        },
        event: {
            historicalEvents: '역사 사건',
            otherEvents: '다른 사건',
            previous: '이전',
            next: '다음',
        },
        eventPanel: {
            contents: '차례',
            consequences: '결과',
            timelineMap: '연표와 지도',
            timeline: '연표',
            relatedPeople: '관련 인물',
            inDepth: '상세',
            text: '명',
            relatedTerms: '관련 용어',
            referenceDocuments: '참고 문헌',
            relatedReports: '관련 보고서',
            report: '보고서',
            sources: '출처:',
        },
        events: {
            historicalEvents: '역사 사건',
            historicalEvents2: '역사 사건',
            searchByPeriodEvent: '시기 · 사건명 · 설명으로 검색…',
            searchHistoricalEvents: '역사 사건 검색',
            clearSearch: '검색 지우기',
            eventFound: '개의 사건',
            eventsFound: '개의 사건',
            noHistoricalEventsFound: '검색 결과가 없습니다',
            historicalEvents3: '역사 사건 목록',
        },
        genealogies: {
            genealogy: '계보도',
            genealogyCharts: '계보도',
            genealogyCharts2: '계보도 목록',
            openTheChart: '계보도 보기 →',
        },
        genealogy: {
            genealogy: '계보도',
            successionSplitMerger: '계승 · 분화 · 합류',
            influence: '영향',
            antagonism: '대립',
            suppression: '소멸',
            noEntryYet: '아직 사전 항목 없음',
        },
        genealogyLinks: {
            genealogyCharts: '계보도',
        },
        listPager: {
            previous: '이전',
            next: '다음',
        },
        nationality: {
            people: '인물 사전',
            people2: '해당 인물',
        },
        office: {
            people: '인물 사전',
            organizationalLineage: '조직 변천',
            leadershipTimeline: '지도부 타임라인',
            people2: '소속 인물',
            relatedReports: '관련 보고서',
            report: '보고서',
        },
        pairTabs: {
            glossary: '용어 사전',
            concept: '개념',
            historicalEvent: '역사 사건',
            narrative: '사건 서사',
            historicalEvents: '역사 사건',
            twoEntriesOnThis: '같은 주제의 두 항목',
        },
        people: {
            people: '인물 사전',
            peopleOfTheRevolution: '인물 사전: 혁명과 소련의 사람들',
            searchByNameAlias: '이름 · 별칭 · 역할 · 설명으로 검색…',
            searchPeople: '인물 검색',
            clearSearch: '검색 지우기',
            nameMatches: '이름 일치',
            roleMatches: '역할 일치',
            mentionedInDescription: '설명에서 언급됨',
            noPeopleFound: '검색 결과가 없습니다',
            peopleCategoriesAndSoviet: '인물 분류와 소련 기관별 지도부 타임라인',
            peopleCategoriesAndSoviet2: '인물 분류와 소련 기관별 지도부',
            theSovietPolitburo: '소련 정치국',
            membership19171991By: '1917–1991 구성원, 시기별·기수별',
            officePage: '기관 페이지 →',
            peopleOfTheSoviet: '소련 내 인물들',
            peopleBeyondTheSoviet: '소련 밖 인물들',
            viewAsAList: '목록으로 보기 →',
            text: '명',
        },
        peopleList: {
            people: '인물 사전',
            text: '명',
            people2: '인물 목록',
        },
        person: {
            contextMarker: '맥락 표식',
            people: '인물 사전',
            citizenship: '국적',
            nationalBackground: '민족·국가적 배경',
            careerTimeline: '경력 연표',
            theSovietPolitburo: '소련 정치국',
            relatedHistoricalEvents: '관련 역사 사건',
            referenceDocuments: '참고 문헌',
            relatedReports: '관련 보고서',
            report: '보고서',
            backToCard: '카드로 돌아가기',
        },
        personCard: {
            contextMarker: '맥락 표식',
            citizenship: '국적',
            nationalBackground: '민족·국가적 배경',
            careerTimeline: '상세 이력 보기',
            scenes: '등장 장면',
        },
        politburo: {
            people: '인물 사전',
            theSovietPolitburo: '소련 정치국',
            person: '인물',
            tenure: '재임',
            notes: '비고',
            compositionByPartyCongress: '당대회 기수별 구성',
            full: '정위원',
            candidates: '후보',
            fullMembers: '정위원',
            candidateMembers: '후보위원',
            entry: '진입',
            change: '변동',
            peopleDictionary: '인물 사전',
        },
        role: {
            people: '인물 사전',
            people2: '소속 인물',
            relatedReports: '관련 보고서',
            report: '보고서',
        },
        term: {
            glossary: '용어 사전',
        },
        termPanel: {
            partOf: '상위 항목',
            inDepth: '상세',
            withinThisEntry: '하위 항목',
            relatedTerms: '관련 용어',
            relatedPeople: '관련 인물',
            relatedHistoricalEvents: '관련 역사 사건',
            referenceDocuments: '참고 문헌',
            relatedReports: '관련 보고서',
            report: '보고서',
            sources: '출처',
        },
        terms: {
            glossary: '용어 사전',
            sortOrder: '정렬 순서',
            aZ: '가나다순',
            chronological: '연대순',
            searchByTermOriginal: '용어 · 원어 · 별칭 · 정의로 검색…',
            searchGlossary: '용어 사전 검색',
            clearSearch: '검색 지우기',
            termFound: '개의 용어',
            termsFound: '개의 용어',
            noGlossaryTermsFound: '검색 결과가 없습니다',
            filterByCategory: '분류로 걸러보기',
            all: '전체',
            jumpToGroup: '그룹으로 이동',
            glossaryTerms: '용어 목록',
        },
    },

    // 에러 페이지
    error: {
        notFound: '페이지를 찾을 수 없습니다.',
        serverError: '문제가 발생했습니다.',
        backHome: '대문으로 돌아가기'
    }
};

const en = {
    siteName: 'Cyber-Lenin',
    siteTagline: "Cyber-Lenin & Bichon's blog",
    siteSeoTitle: 'Cyber-Lenin — Geopolitics, Political Economy & AI Sovereignty',
    siteDescription: 'A blog co-written by Bichon and AI agent Cyber-Lenin. Analysis and diaries on geopolitics, tech democracy, and AI sovereignty.',
    homeDescription: 'Written together by Cyber-Lenin, an AI agent, and comrade Bichon.',

    home: {
        recentPosts: "Bichon's Recent Posts",
        recentDiaries: "Cyber-Lenin's Recent Diaries",
        recentReports: "Cyber-Lenin's Recent Reports",
        recentHub: 'Recent Curations',
        recentCommuLingo: 'Recent CommuLingo Updates',
        commuLingoUpdatedAt: ', updated',
        viewAll: 'View all',
        chatDesc: 'Chat with Cyber-Lenin in real time',
        diaryDesc: 'Read diaries written by Cyber-Lenin',
        reportsDesc: 'Geopolitical analysis reports by Cyber-Lenin',
        hubDesc: 'Korean progressive writing curated by Cyber-Lenin',
        commuLingoDesc: 'Revolutionary theory quizzes plus people, events, and glossary dictionaries',
        gameDesc: 'Enjoy the mini games',
        postsDesc: 'Blog posts written by Bichon',
        libraryDesc: "Cyber-Lenin's reports, diaries, and curations, plus Bichon's posts",
    },

    nav: {
        home: 'Home',
        chat: 'Chat',
        library: 'Writings',
        bichonPosts: "Bichon's Posts",
        diary: "Cyber-Lenin's Diary",
        diaryShort: 'Diary',
        reports: "Cyber-Lenin's Reports",
        reportsShort: 'Reports',
        hub: 'Curation',
        commuLingo: 'Commulingo',
        game: 'Game',
        dashboard: 'Dashboard',
        posts: 'Manage Posts',
        logout: 'Logout',
        login: 'Admin'
    },

    footer: {
        copyright: '🄯 {year} Bichon House. All rights reversed.'
    },

    public: {
        noPosts: 'No posts yet.',
        postedAt: ', posted',
        updatedAt: ', updated',
        backToList: 'List',
        noDiaries: 'No diary entries yet.',
        deleteDiaryConfirm: 'Are you sure you want to delete this diary entry?',
        chatHistory: 'History',
        chatNew: 'New chat',
        prevPost: 'Prev',
        nextPost: 'Next'
    },

    userAuth: {
        login: 'Login',
        logout: 'Logout',
        loginTitle: 'Sign In',
        signupTitle: 'Create Account',
        signUp: 'Sign up',
        signIn: 'Sign in with Passkey',
        signupHintLine1: 'Create an account with a username and password.',
        signupHintLine2: 'You can add a Passkey from account settings after signup.',
        username: 'Username',
        usernameHint: '1-30 chars, letters/digits/Korean/_',
        usernameInvalid: 'Username must be 1-30 characters and start with Korean, a letter, number, or underscore.',
        usernameTaken: 'That username is already taken.',
        usernameOrPasswordInvalid: 'Username or password is incorrect.',
        passwordInvalid: 'Password must be 1-128 characters.',
        signupFailed: 'Could not create the account. Please try again.',
        loginFailed: 'Could not sign in. Please try again.',
        password: 'Password',
        passwordHint: 'Use 1-128 characters.',
        passwordSignIn: 'Sign in with username and password',
        passkeySignIn: 'Sign in with Passkey',
        passwordSection: 'Username/password sign-in',
        passwordLoginHint: 'Use this account name to sign in with a password.',
        loginUsernameLabel: 'Sign-in username',
        currentPassword: 'Current password',
        newPassword: 'New password',
        setPassword: 'Set password',
        updatePassword: 'Change password',
        passwordSaved: 'Password saved.',
        noAccount: 'No account?',
        signUpLink: 'Sign up',
        haveAccount: 'Already have an account?',
        signInLink: 'Sign in',
        accountMenu: 'Account',
        accountTitle: 'Account',
        accountLogoutSection: 'Session'
    },

    login: {
        title: 'Admin Login',
        username: 'Username',
        password: 'Password',
        submit: 'Login',
        passkeySubmit: 'Sign in with Passkey',
        registerSubmit: 'Register Passkey',
        deviceName: 'Device name',
        deviceNamePlaceholder: 'e.g. Galaxy S24, Office desktop',
        bootstrapHint: 'No passkey registered yet. Set up the first one from an allowed IP.',
        notSupported: 'This browser does not support passkeys.',
        cancelled: 'Cancelled.',
        failed: 'Failed. Please try again.',
        registered: 'Registered. Signing you in…',
        usernameRequired: 'Username is required.'
    },

    admin: {
        dashboard: 'Dashboard',
        createPost: 'New Post',
        managePosts: 'Manage Posts',
        totalPosts: 'Total Posts',
        recentPosts: 'Posts This Month',
        quickActions: 'Quick Actions',
        novelWriter: 'Novel Writer',
        commulingoDocs: 'Reference Docs',
        recentPostsTitle: 'Recent Posts',

        postId: 'ID',
        postTitle: 'Title',
        postCreated: 'Created',
        postActions: 'Actions',
        edit: 'Edit',
        delete: 'Delete',
        deleteConfirm: 'Are you sure you want to delete this post?',
        noPostsYet: 'No posts yet.',
        createFirst: 'Create your first post',

        editPost: 'Edit Post',
        newPost: 'New Post',
        backToPosts: 'Back to list',
        titleLabel: 'Title',
        contentLabel: 'Content',
        update: 'Update',
        create: 'Create',
        cancel: 'Cancel',

        insertLink: 'Insert Link',
        linkUrl: 'URL',
        linkTitle: 'Tooltip',
        linkText: 'Text',
        linkInsert: 'Insert',
        linkCancel: 'Cancel',

        clearCache: 'Clear Cache',
        cacheCleared: 'Cleared!',

        chatLogs: 'Chat Logs',
        chatLogsFilterAll: 'All',
        chatLogsFilterCasual: 'Casual',
        chatLogsFilterVectorstore: 'Knowledge Search',
        chatLogsRefresh: 'Refresh',
        chatLogsLoading: 'Loading...',

        users: 'User Accounts',
        usersSearch: 'Search usernames',
        usersEmpty: 'No user accounts.',
        usersSelectHint: 'Select an account from the list.',
        usersRename: 'Rename',
        usersMerge: 'Merge Account',
        usersMergeSource: 'Source account',
        usersMergeTarget: 'Target user ID',
        usersDeleteConfirm: 'Type the exact username to delete this account. Chat logs are retained by fingerprint.',
        usersAdminBadge: 'Admin',
        usersPassword: 'Password',
        usersPasskeys: 'Passkeys',
        usersFingerprints: 'Fingerprints',
        usersLastLogin: 'Last login',
        usersLastChat: 'Last chat',
        usersNoFingerprints: 'No fingerprints linked.',

        passkeys: 'Passkeys',
        passkeysHint: 'Manage registered passkeys. Remove passkeys for lost devices.',
        passkeysEmpty: 'No passkeys registered.',
        addPasskey: 'Add passkey on this device',
        passkeyAdded: 'Added.',
        passkeyDeleteConfirm: 'Delete this passkey?',
        passkeyUnnamed: '(unnamed)',
        passkeyCreated: 'Created',
        passkeyLastUsed: 'Last used',
        passkeyNever: 'Never'
    },

    chat: {
        title: 'Chat with Cyber-Lenin',
        placeholder: 'Type a message. Enter adds a line, Ctrl/Cmd+Enter sends',
        inputLabel: 'Message input',
        inputHint: 'Enter adds a line, Ctrl/Cmd+Enter sends',
        send: 'Send',
        emptyHint: 'No messages yet.\nType below to start a conversation with {name}.',
        defaultPersonaName: 'Cyber-Lenin',
        thinking: 'Comrade is thinking...',
        error: 'An error occurred.',
        notSaved: "The reply didn't come through. Please resend your message.",
        retry: '↻ Retry',
        personaLabel: 'Chat with',
        feedbackSaved: 'Saved',
        feedbackError: 'Feedback failed',
        feedbackNote: 'Write feedback',
        feedbackSave: 'Save feedback',
        feedbackToggle: 'Feedback · Regenerate',
        regenerate: 'Regenerate',
        regenerating: 'Regenerating...',
        deleteLabel: 'Delete',
        deleteConfirmUser: 'Delete this question? It will be excluded from future chat context.',
        deleteConfirmAssistant: 'Delete this response? It will be excluded from future chat context.',
        deleteError: 'Could not delete the message.'
    },

    commuLingo: {
        title: 'commulingo',
        description: 'A learning space for revolutionary theory and history.',
        dictSectionTitle: 'Dictionaries & Library',
        dictSectionHint: 'Unfamiliar people, events, or terms? Look them up here.',
        quizLabel: 'Quizzes',
        quizShort: 'Quiz',
        dictPeopleShort: 'People',
        dictEventsShort: 'Events',
        dictTermsShort: 'Terms',
        dictGenealogyShort: 'Charts',
        dictDocsShort: 'Refs',
        dictPeople: 'People',
        dictEvents: 'Historical events',
        dictTerms: 'Glossary',
        dictGenealogy: 'Genealogy',
        dictDocs: 'References',
        kicker: 'Capital Volume I',
        start: 'Start',
        continue: 'Continue',
        review: 'Review',
        progress: 'Progress',
        questions: 'Questions',
        lessons: 'Lessons',
        score: 'Score',
        completed: 'Completed',
        locked: 'Coming soon',
        next: 'Next',
        finish: 'Finish',
        tryAgain: 'Try again',
        correct: 'Correct',
        incorrect: 'Incorrect',
        retryMissed: 'Retry the ones you missed',
        retryNote: 'First pass {first}/{total}, after retry {now}/{total}. Missed questions go into review.',
        retryAgainNote: '{left} still missed. Read the explanation once more and try again.',
        reviewTitle: 'Review',
        reviewButton: 'Review',
        reviewDueCount: '{count} questions due for review',
        reviewNoneDue: 'Nothing due for review right now',
        reviewNextDue: 'Next review: {date}',
        reviewIntro: 'Questions you missed come back at increasing intervals. Three correct answers in a row graduate a question.',
        reviewDone: 'Review complete',
        reviewResult: '{score} / {total} correct. Missed questions will come back soon.',
        reviewResultPerfect: 'All {total} correct. The next review comes back after a longer interval.',
        keyHint: 'Keys 1-4 pick an answer, Enter moves on.',
        syncLogin: 'Sign in to sync progress to your account.',
        syncSaved: 'Progress saved',
        syncLocal: 'Progress is saved in this browser.',
        allDone: "Lesson complete",
        backToLessons: 'Lessons',
        updatesTitle: 'Update notes',
        updatesDescription: 'Choose a category to see recently added or updated entries.',
        homeProgress: 'Progress',
        updatesEmpty: 'No updates yet.',
        updatesUnavailable: 'Updates could not be loaded. Please try again shortly.',
        chooseBook: 'Choose a book',
        chooseBookHint: 'Pick a book and learn it chapter by chapter through quizzes.',
        continueLearning: 'Continue learning',
        backToBooks: 'Books',
        nextLesson: 'Next lesson',
        bookProgressEmpty: 'Not started yet',
        chapters: 'Chapters',
        authorMarx: 'Karl Marx',
        authorEngels: 'Friedrich Engels',
        authorLenin: 'Vladimir Lenin',
        authorOther: 'Other',
        conceptMapLabel: 'Interactive concept map',
        exploreMode: 'Tap to explore',
        graphHint: 'Open each link of the chain below in turn: plain explanation → Engels’s argument → modern critique.',
        drill: 'Training ground',
        drillDesc: 'Quizzes and timeline games from the term, people, and event dictionaries.',
        drillOpen: 'Start training',
        drillBest: 'Best score',
        drillRoundsDone: 'rounds played',
        drillNextRound: 'Next round',
        drillBackToDecks: 'Deck list',
        drillRoundDone: 'Round complete',
        drillCheckOrder: 'Check order',
        drillMoveUp: 'Move up',
        drillMoveDown: 'Move down',
        drillLookup: 'Open dictionary entry',
        drillOrderHint: 'Reorder with the up and down buttons, then check. Earliest goes on top.',
        drillLoadFail: 'Could not load the questions. Please try again shortly.',
    },

    // Page copy moved out of the CommuLingo views (was `en ? '…' : '…'`
    // ternaries in the templates); keys are per view.
    commuLingoViews: {
        adminDocs: {
            publicPage: 'Public page',
            uploadDocument: 'Upload document',
            slugEGYezhov: 'slug (e.g. yezhov-pavlyukov)',
            preview: 'Preview',
            upload: 'Upload',
            documents: 'Documents',
            edit: 'Edit',
            titleKo: 'Title (ko)',
            titleEn: 'Title (en)',
            kindKo: 'Kind (ko)',
            kindEn: 'Kind (en)',
            descriptionKo: 'Description (ko)',
            descriptionEn: 'Description (en)',
            sourceCitation: 'Source citation',
            bodyLanguage: 'Body language',
            tocExcludeRegexesOne: 'TOC exclude regexes (one per line)',
            linkedPeople: 'Linked people',
            linkedTerms: 'Linked terms',
            linkedEvents: 'Linked events',
            typeToSearchPick: 'Type to search, pick to add',
            save: 'Save',
            close: 'Close',
        },
        doc: {
            referenceLibrary: 'Reference Library',
            tableOfContents: 'Table of contents',
            contents: 'Contents',
            people: 'People',
            terms: 'Terms',
            events: 'Events',
            genealogy: 'Genealogy',
            pages: 'Pages',
            previous: 'Previous',
            next: 'Next',
            source: 'Source',
            commulingoReferenceLibrary: 'CommuLingo Reference Library',
            historicalFigure: 'Historical figure',
        },
        docs: {
            references: 'References',
            referenceLibrary: 'Reference Library',
            searchByTitleKind: 'Search by title, kind, or description…',
            searchReferenceDocuments: 'Search reference documents',
            clearSearch: 'Clear search',
            documentFound: 'document found',
            documentsFound: 'documents found',
            noReferenceDocumentsFound: 'No reference documents found',
            filterByKind: 'Filter by kind',
            all: 'All',
            referenceDocuments: 'Reference documents',
            readTheFullText: 'Read the full text →',
        },
        event: {
            historicalEvents: 'Historical events',
            otherEvents: 'Other events',
            previous: 'Previous',
            next: 'Next',
        },
        eventPanel: {
            contents: 'Contents',
            consequences: 'Consequences',
            timelineMap: 'Timeline & Map',
            timeline: 'Timeline',
            relatedPeople: 'Related people',
            inDepth: 'In depth',
            text: '',
            relatedTerms: 'Related terms',
            referenceDocuments: 'Reference documents',
            relatedReports: 'Related reports',
            report: 'Report',
            sources: 'Sources:',
        },
        events: {
            historicalEvents: 'Historical events',
            historicalEvents2: 'Historical Events',
            searchByPeriodEvent: 'Search by period, event, or description…',
            searchHistoricalEvents: 'Search historical events',
            clearSearch: 'Clear search',
            eventFound: 'event found',
            eventsFound: 'events found',
            noHistoricalEventsFound: 'No historical events found',
            historicalEvents3: 'Historical events',
        },
        genealogies: {
            genealogy: 'Genealogy',
            genealogyCharts: 'Genealogy Charts',
            genealogyCharts2: 'Genealogy charts',
            openTheChart: 'Open the chart →',
        },
        genealogy: {
            genealogy: 'Genealogy',
            successionSplitMerger: 'succession · split · merger',
            influence: 'influence',
            antagonism: 'antagonism',
            suppression: 'suppression',
            noEntryYet: 'no entry yet',
        },
        genealogyLinks: {
            genealogyCharts: 'Genealogy charts',
        },
        listPager: {
            previous: 'Previous',
            next: 'Next',
        },
        nationality: {
            people: 'People',
            people2: 'People',
        },
        office: {
            people: 'People',
            organizationalLineage: 'Organizational Lineage',
            leadershipTimeline: 'Leadership Timeline',
            people2: 'People',
            relatedReports: 'Related reports',
            report: 'Report',
        },
        pairTabs: {
            glossary: 'Glossary',
            concept: 'Concept',
            historicalEvent: 'Historical event',
            narrative: 'Narrative',
            historicalEvents: 'Historical events',
            twoEntriesOnThis: 'Two entries on this subject',
        },
        people: {
            people: 'People',
            peopleOfTheRevolution: 'People of the Revolution and the USSR',
            searchByNameAlias: 'Search by name, alias, role, or bio…',
            searchPeople: 'Search people',
            clearSearch: 'Clear search',
            nameMatches: 'Name matches',
            roleMatches: 'Role matches',
            mentionedInDescription: 'Mentioned in description',
            noPeopleFound: 'No people found',
            peopleCategoriesAndSoviet: 'People categories and Soviet institution leadership timelines',
            peopleCategoriesAndSoviet2: 'People Categories and Soviet Institution Timelines',
            theSovietPolitburo: 'The Soviet Politburo',
            membership19171991By: 'Membership 1917–1991, by era and congress',
            officePage: 'Office page →',
            peopleOfTheSoviet: 'People of the Soviet Union',
            peopleBeyondTheSoviet: 'People beyond the Soviet Union',
            viewAsAList: 'View as a list →',
            text: '',
        },
        peopleList: {
            people: 'People',
            text: '',
            people2: 'People',
        },
        person: {
            contextMarker: 'Context marker',
            people: 'People',
            citizenship: 'Citizenship',
            nationalBackground: 'National background',
            careerTimeline: 'Career Timeline',
            theSovietPolitburo: 'The Soviet Politburo',
            relatedHistoricalEvents: 'Related historical events',
            referenceDocuments: 'Reference documents',
            relatedReports: 'Related reports',
            report: 'Report',
            backToCard: 'Back to card',
        },
        personCard: {
            contextMarker: 'Context marker',
            citizenship: 'Citizenship',
            nationalBackground: 'National background',
            careerTimeline: 'Career timeline',
            scenes: 'Scenes',
        },
        politburo: {
            people: 'People',
            theSovietPolitburo: 'The Soviet Politburo',
            person: 'Person',
            tenure: 'Tenure',
            notes: 'Notes',
            compositionByPartyCongress: 'Composition by party congress',
            full: 'Full',
            candidates: 'Candidates',
            fullMembers: 'Full members',
            candidateMembers: 'Candidate members',
            entry: 'Entry',
            change: 'Change',
            peopleDictionary: 'People dictionary',
        },
        role: {
            people: 'People',
            people2: 'People',
            relatedReports: 'Related reports',
            report: 'Report',
        },
        term: {
            glossary: 'Glossary',
        },
        termPanel: {
            partOf: 'Part of',
            inDepth: 'In depth',
            withinThisEntry: 'Within this entry',
            relatedTerms: 'Related terms',
            relatedPeople: 'Related people',
            relatedHistoricalEvents: 'Related historical events',
            referenceDocuments: 'Reference documents',
            relatedReports: 'Related reports',
            report: 'Report',
            sources: 'Sources',
        },
        terms: {
            glossary: 'Glossary',
            sortOrder: 'Sort order',
            aZ: 'A–Z',
            chronological: 'Chronological',
            searchByTermOriginal: 'Search by term, original, alias, or definition…',
            searchGlossary: 'Search glossary',
            clearSearch: 'Clear search',
            termFound: 'term found',
            termsFound: 'terms found',
            noGlossaryTermsFound: 'No glossary terms found',
            filterByCategory: 'Filter by category',
            all: 'All',
            jumpToGroup: 'Jump to group',
            glossaryTerms: 'Glossary terms',
        },
    },

    error: {
        notFound: 'Page not found.',
        serverError: 'Something went wrong.',
        backHome: 'Back to home'
    }
};

// Fill a persona template. The reader's choice lives in localStorage, so the
// browser re-runs this (objectParticle/renderEmptyHint in public/js/chat.js)
// whenever they switch; this is the server-rendered default it starts from.
// 과/와 follows the final consonant: 사이버-레닌과, 안토니오 그람시와. A name
// ending in a Latin letter or digit takes 과, which is how Korean reads them.
function withPersona(template, name) {
    const label = String(name || '').trim();
    const last = label.slice(-1);
    const code = last.charCodeAt(0);
    const particle = (code >= 0xac00 && code <= 0xd7a3 && (code - 0xac00) % 28 === 0) ? '와' : '과';
    return String(template || '').replace(/\{name\}/g, label).replace(/\{과\}/g, particle);
}

module.exports = { ko, en, withPersona };
