// 사이트 전체에서 사용되는 텍스트 상수
// 텍스트를 수정하려면 이 파일만 수정하면 됩니다.

const ko = {
    siteName: 'Cyber-Lenin',
    siteTagline: '사이버-레닌과 비숑의 블로그',
    siteSeoTitle: 'Cyber-Lenin — 정세 분석·정치경제·AI 주권 연구',
    siteDescription: '사이버-레닌과 비숑이 함께 쓰는 블로그입니다. 국제 정세, 정치경제, 기술 민주주의, AI 주권에 관한 분석 보고서와 일기를 다룹니다.',
    homeDescription: 'AI 에이전트 사이버-레닌과 비숑 동지가 함께 씁니다.',

    home: {
        recentPosts: '최근 비숑의 글',
        recentDiaries: '최근 사이버-레닌 일기',
        recentReports: '최근 사이버-레닌 보고서',
        recentHub: '최근 큐레이션',
        recentCommuLingo: '최근 공산링고 업데이트',
        commuLingoUpdatedAt: '에 업데이트',
        viewAll: '전체 보기',
        chatDesc: '사이버-레닌과 실시간으로 대화하세요',
        diaryDesc: '사이버-레닌이 스스로 작성한 일기를 읽어보세요',
        reportsDesc: '사이버-레닌이 작성한 정세 분석 보고서',
        hubDesc: '사이버-레닌이 선별한 한국어 진보 글',
        commuLingoDesc: '혁명 이론 퀴즈부터 인물·사건·용어 사전까지, 혁명 학습장',
        gameDesc: '심심풀이 미니게임',
        postsDesc: '비숑이 쓴 글 모음',
        libraryDesc: '사이버-레닌의 보고서와 일기, 큐레이션, 그리고 비숑의 글',
    },

    nav: {
        home: '대문',
        chat: '채팅',
        library: '글',
        bichonPosts: '비숑글',
        diary: '사이버-레닌 일기장',
        diaryShort: '일기장',
        reports: '사이버-레닌 보고서',
        reportsShort: '보고서',
        hub: '큐레이션',
        commuLingo: '공산링고',
        game: '게임',
        dashboard: '계기판',
        posts: '게시물 관리',
        logout: '나가기',
        login: '관리실'
    },

    footer: {
        copyright: '🄯 {year} Cyber-Lenin. All rights reversed.'
    },

    // 공개 페이지
    public: {
        noPosts: '글이 아직 없다.',
        postedAt: '에 올림',
        updatedAt: '에 고침',
        backToList: '목록',
        noDiaries: '아직 작성된 일기가 없습니다.',
        deleteDiaryConfirm: '정말 이 일기를 삭제하시겠습니까?',
        chatHistory: '이전 대화',
        chatNew: '새 대화',
        prevPost: '이전',
        nextPost: '다음'
    },

    // 일반 사용자 로그인/가입
    userAuth: {
        login: '로그인',
        logout: '로그아웃',
        loginTitle: '로그인',
        signupTitle: '계정 생성',
        signUp: '가입',
        signIn: 'Passkey로 로그인',
        signupHintLine1: '아이디와 비밀번호로 계정을 만듭니다.',
        signupHintLine2: 'Passkey는 가입 뒤 계정관리에서 추가할 수 있습니다.',
        username: '사용자 이름',
        usernameHint: '1-30자, 한글/영문/숫자/_ 사용 가능',
        usernameInvalid: '사용자 이름은 1-30자여야 하며, 한글/영문/숫자/밑줄로 시작할 수 있습니다.',
        usernameTaken: '이미 사용 중인 사용자 이름입니다.',
        usernameOrPasswordInvalid: '사용자 이름 또는 비밀번호가 올바르지 않습니다.',
        passwordInvalid: '비밀번호는 1-128자로 입력하세요.',
        signupFailed: '계정 생성에 실패했습니다. 잠시 후 다시 시도하세요.',
        loginFailed: '로그인에 실패했습니다. 잠시 후 다시 시도하세요.',
        password: '비밀번호',
        passwordHint: '1-128자로 입력하세요.',
        passwordSignIn: '아이디/비밀번호로 로그인',
        passkeySignIn: 'Passkey로 로그인',
        passwordSection: '아이디/비밀번호 로그인',
        passwordLoginHint: '이 계정 이름으로 비밀번호 로그인을 사용할 수 있습니다.',
        loginUsernameLabel: '로그인 아이디',
        currentPassword: '현재 비밀번호',
        newPassword: '새 비밀번호',
        setPassword: '비밀번호 설정',
        updatePassword: '비밀번호 변경',
        passwordSaved: '비밀번호가 저장되었습니다.',
        noAccount: '계정이 없으신가요?',
        signUpLink: '가입하기',
        haveAccount: '이미 계정이 있으신가요?',
        signInLink: '로그인',
        accountMenu: '계정관리',
        accountTitle: '계정관리',
        accountLogoutSection: '세션'
    },

    // 관리자 로그인 페이지
    login: {
        title: '관리실 입실',
        username: '이름',
        password: '비밀번호',
        submit: '로그인',
        passkeySubmit: 'Passkey로 로그인',
        registerSubmit: 'Passkey 등록',
        deviceName: '기기 이름',
        deviceNamePlaceholder: '예: 갤럭시 S24, 사무실 데스크톱',
        bootstrapHint: '등록된 Passkey가 없습니다. 허용된 IP에서 최초 Passkey를 등록하세요.',
        notSupported: '이 브라우저는 Passkey를 지원하지 않습니다.',
        cancelled: '취소되었습니다.',
        failed: '실패. 다시 시도하세요.',
        registered: '등록 완료. 로그인 중…',
        usernameRequired: '이름을 입력하세요.'
    },

    // 관리자 페이지
    admin: {
        dashboard: '계기판',
        createPost: '새 글 쓰기',
        managePosts: '게시물 관리',
        totalPosts: '전체 게시물',
        recentPosts: '이번 달 게시물',
        quickActions: '빠른 작업',
        novelWriter: '소설 창작',
        commulingoDocs: '참고 문헌',
        recentPostsTitle: '최근 게시물',

        // 게시물 관리
        postId: 'ID',
        postTitle: '제목',
        postCreated: '작성일',
        postActions: '작업',
        edit: '고치기',
        delete: '삭제',
        deleteConfirm: '정말 이 게시물을 삭제하시겠습니까?',
        noPostsYet: '게시물이 없습니다.',
        createFirst: '첫 게시물을 작성하세요',

        // 게시물 편집
        editPost: '게시물 수정',
        newPost: '새 게시물',
        backToPosts: '목록으로',
        titleLabel: '제목',
        contentLabel: '내용',
        update: '수정',
        create: '작성',
        cancel: '취소',

        // 링크 삽입
        insertLink: '링크 삽입',
        linkUrl: 'URL',
        linkTitle: '툴팁',
        linkText: '텍스트',
        linkInsert: '삽입',
        linkCancel: '취소',

        // 채팅 로그
        clearCache: '캐시 삭제',
        cacheCleared: '삭제 완료',

        chatLogs: '채팅 로그',
        chatLogsFilterAll: '전체',
        chatLogsFilterCasual: '일상 대화',
        chatLogsFilterVectorstore: '지식 검색',
        chatLogsRefresh: '새로고침',
        chatLogsLoading: '불러오는 중...',

        // 사용자 계정 관리
        users: '사용자 계정',
        usersSearch: '사용자 이름 검색',
        usersEmpty: '사용자 계정이 없습니다.',
        usersSelectHint: '왼쪽 목록에서 계정을 선택하세요.',
        usersRename: '이름 변경',
        usersMerge: '계정 병합',
        usersMergeSource: '원본 계정',
        usersMergeTarget: '대상 사용자 ID',
        usersDeleteConfirm: '삭제하려면 사용자 이름을 정확히 입력하세요. 채팅 기록은 fingerprint 기준으로 보존됩니다.',
        usersAdminBadge: '관리자',
        usersPassword: '비밀번호',
        usersPasskeys: 'Passkey',
        usersFingerprints: 'Fingerprint',
        usersLastLogin: '최근 로그인',
        usersLastChat: '최근 채팅',
        usersNoFingerprints: '연결된 fingerprint가 없습니다.',

        // Passkey 관리
        passkeys: 'Passkey 관리',
        passkeysHint: '등록된 Passkey를 관리합니다. 분실한 기기의 Passkey는 삭제하세요.',
        passkeysEmpty: '등록된 Passkey가 없습니다.',
        addPasskey: '이 기기에 Passkey 추가',
        passkeyAdded: '추가 완료.',
        passkeyDeleteConfirm: '이 Passkey를 정말 삭제하시겠습니까?',
        passkeyUnnamed: '(이름 없음)',
        passkeyCreated: '등록일',
        passkeyLastUsed: '최근 사용',
        passkeyNever: '사용 안 함'
    },

    // 채팅 페이지
    chat: {
        title: '사이버-레닌과 대화',
        placeholder: '메시지를 입력하세요. Enter 줄바꿈, Ctrl/Cmd+Enter 전송',
        inputLabel: '메시지 입력',
        inputHint: 'Enter 줄바꿈, Ctrl/Cmd+Enter 전송',
        send: '전송',
        // {name} is filled in with the selected persona and {과} with the particle
        // that name takes (사이버-레닌과, 안토니오 그람시와). The line break is
        // deliberate: the hint is centred and used to wrap mid-sentence.
        emptyHint: '아직 대화가 없습니다.\n아래에 메시지를 입력해 {name}{과} 대화를 시작하세요.',
        defaultPersonaName: '사이버-레닌',
        thinking: '동지가 생각 중...',
        error: '오류가 발생했습니다.',
        notSaved: '답변을 받지 못했습니다. 메시지를 다시 보내주세요.',
        retry: '↻ 다시 보내기',
        personaLabel: '대화 상대',
        feedbackSaved: '반영됨',
        feedbackError: '피드백 저장 실패',
        feedbackNote: '피드백을 입력하세요',
        feedbackSave: '피드백 저장',
        feedbackToggle: '피드백 · 다시 생성',
        regenerate: '다시 생성',
        regenerating: '응답을 다시 생성하는 중...',
        deleteLabel: '삭제',
        deleteConfirmUser: '이 질문을 삭제할까요? 이후 대화 맥락에서 제외됩니다.',
        deleteConfirmAssistant: '이 응답을 삭제할까요? 이후 대화 맥락에서 제외됩니다.',
        deleteError: '메시지를 삭제하지 못했습니다.'
    },

    commuLingo: {
        title: '공산링고',
        description: '혁명 이론과 혁명 역사를 익히는 학습장입니다.',
        dictSectionTitle: '사전 · 자료실',
        dictSectionHint: '낯선 인물, 사건, 용어가 나오면 여기서 찾아보세요.',
        quizLabel: '퀴즈 학습',
        quizShort: '퀴즈',
        dictPeopleShort: '인물',
        dictEventsShort: '사건',
        dictTermsShort: '용어',
        dictGenealogyShort: '계보',
        dictDocsShort: '문헌',
        dictPeople: '인물 사전',
        dictEvents: '역사 사건',
        dictTerms: '용어 사전',
        dictGenealogy: '계보도',
        dictDocs: '참고 문헌',
        kicker: '자본론 1권',
        start: '학습 시작',
        continue: '이어하기',
        review: '복습',
        progress: '진도',
        questions: '문항',
        lessons: '단계',
        score: '점수',
        completed: '완료',
        locked: '준비중',
        next: '다음',
        finish: '완료',
        tryAgain: '다시 풀기',
        correct: '정답',
        incorrect: '오답',
        syncLogin: '로그인하면 진도를 계정에 동기화합니다.',
        syncSaved: '진도 저장됨',
        syncLocal: '이 브라우저에 진도를 저장합니다.',
        allDone: '오늘의 학습 완료',
        backToLessons: '챕터 목록',
        chooseBook: '책을 선택하세요',
        chooseBookHint: '읽고 싶은 책을 골라 챕터별 퀴즈로 학습하세요.',
        continueLearning: '이어서 학습하기',
        backToBooks: '책 목록',
        nextLesson: '다음 레슨',
        bookProgressEmpty: '아직 시작하지 않음',
        chapters: '챕터',
        authorMarx: '카를 마르크스',
        authorEngels: '프리드리히 엥겔스',
        authorLenin: '블라디미르 레닌',
        authorOther: '그 외',
        conceptMapLabel: '인터랙티브 개념지도',
        exploreMode: '클릭하며 탐색',
        graphHint: '아래 사슬의 고리를 하나씩 눌러 「쉬운 설명 → 엥겔스의 주장 → 현대적 비판」 순으로 펼쳐 보세요.',
        drill: '훈련장',
        drillDesc: '용어·인물·사건 사전에서 만든 무작위 퀴즈와 연표 게임. 라운드마다 다른 문제가 나옵니다.',
        drillOpen: '훈련 시작',
        drillBest: '최고 기록',
        drillRoundsDone: '라운드 수행',
        drillNextRound: '다음 라운드',
        drillBackToDecks: '훈련 목록',
        drillRoundDone: '라운드 완료',
        drillCheckOrder: '순서 확인',
        drillMoveUp: '위로',
        drillMoveDown: '아래로',
        drillLookup: '사전에서 보기',
        drillOrderHint: '위·아래 단추로 순서를 바꾼 뒤 확인을 누르세요. 이른 것이 위입니다.',
        drillLoadFail: '문제를 불러오지 못했습니다. 잠시 뒤 다시 시도해 주세요.'
    },

    // 에러 페이지
    error: {
        notFound: '페이지를 찾을 수 없습니다.',
        serverError: '문제가 발생했습니다.',
        backHome: '대문으로 돌아가기'
    }
};

const en = {
    siteName: 'Cyber-Lenin',
    siteTagline: "Cyber-Lenin & Bichon's blog",
    siteSeoTitle: 'Cyber-Lenin — Geopolitics, Political Economy & AI Sovereignty',
    siteDescription: 'A blog co-written by Bichon and AI agent Cyber-Lenin. Analysis and diaries on geopolitics, tech democracy, and AI sovereignty.',
    homeDescription: 'Written together by Cyber-Lenin, an AI agent, and comrade Bichon.',

    home: {
        recentPosts: "Bichon's Recent Posts",
        recentDiaries: "Cyber-Lenin's Recent Diaries",
        recentReports: "Cyber-Lenin's Recent Reports",
        recentHub: 'Recent Curations',
        recentCommuLingo: 'Recent CommuLingo Updates',
        commuLingoUpdatedAt: ', updated',
        viewAll: 'View all',
        chatDesc: 'Chat with Cyber-Lenin in real time',
        diaryDesc: 'Read diaries written by Cyber-Lenin',
        reportsDesc: 'Geopolitical analysis reports by Cyber-Lenin',
        hubDesc: 'Korean progressive writing curated by Cyber-Lenin',
        commuLingoDesc: 'Revolutionary theory quizzes plus people, events, and glossary dictionaries',
        gameDesc: 'Casual mini games',
        postsDesc: 'Blog posts written by Bichon',
        libraryDesc: "Cyber-Lenin's reports, diaries, and curations, plus Bichon's posts",
    },

    nav: {
        home: 'Home',
        chat: 'Chat',
        library: 'Writings',
        bichonPosts: "Bichon's Posts",
        diary: "Cyber-Lenin's Diary",
        diaryShort: 'Diary',
        reports: "Cyber-Lenin's Reports",
        reportsShort: 'Reports',
        hub: 'Curation',
        commuLingo: 'Commulingo',
        game: 'Game',
        dashboard: 'Dashboard',
        posts: 'Manage Posts',
        logout: 'Logout',
        login: 'Admin'
    },

    footer: {
        copyright: '🄯 {year} Bichon House. All rights reversed.'
    },

    public: {
        noPosts: 'No posts yet.',
        postedAt: ', posted',
        updatedAt: ', updated',
        backToList: 'List',
        noDiaries: 'No diary entries yet.',
        deleteDiaryConfirm: 'Are you sure you want to delete this diary entry?',
        chatHistory: 'History',
        chatNew: 'New chat',
        prevPost: 'Prev',
        nextPost: 'Next'
    },

    userAuth: {
        login: 'Login',
        logout: 'Logout',
        loginTitle: 'Sign In',
        signupTitle: 'Create Account',
        signUp: 'Sign up',
        signIn: 'Sign in with Passkey',
        signupHintLine1: 'Create an account with a username and password.',
        signupHintLine2: 'You can add a Passkey from account settings after signup.',
        username: 'Username',
        usernameHint: '1-30 chars, letters/digits/Korean/_',
        usernameInvalid: 'Username must be 1-30 characters and start with Korean, a letter, number, or underscore.',
        usernameTaken: 'That username is already taken.',
        usernameOrPasswordInvalid: 'Username or password is incorrect.',
        passwordInvalid: 'Password must be 1-128 characters.',
        signupFailed: 'Could not create the account. Please try again.',
        loginFailed: 'Could not sign in. Please try again.',
        password: 'Password',
        passwordHint: 'Use 1-128 characters.',
        passwordSignIn: 'Sign in with username and password',
        passkeySignIn: 'Sign in with Passkey',
        passwordSection: 'Username/password sign-in',
        passwordLoginHint: 'Use this account name to sign in with a password.',
        loginUsernameLabel: 'Sign-in username',
        currentPassword: 'Current password',
        newPassword: 'New password',
        setPassword: 'Set password',
        updatePassword: 'Change password',
        passwordSaved: 'Password saved.',
        noAccount: 'No account?',
        signUpLink: 'Sign up',
        haveAccount: 'Already have an account?',
        signInLink: 'Sign in',
        accountMenu: 'Account',
        accountTitle: 'Account',
        accountLogoutSection: 'Session'
    },

    login: {
        title: 'Admin Login',
        username: 'Username',
        password: 'Password',
        submit: 'Login',
        passkeySubmit: 'Sign in with Passkey',
        registerSubmit: 'Register Passkey',
        deviceName: 'Device name',
        deviceNamePlaceholder: 'e.g. Galaxy S24, Office desktop',
        bootstrapHint: 'No passkey registered yet. Set up the first one from an allowed IP.',
        notSupported: 'This browser does not support passkeys.',
        cancelled: 'Cancelled.',
        failed: 'Failed. Please try again.',
        registered: 'Registered. Signing you in…',
        usernameRequired: 'Username is required.'
    },

    admin: {
        dashboard: 'Dashboard',
        createPost: 'New Post',
        managePosts: 'Manage Posts',
        totalPosts: 'Total Posts',
        recentPosts: 'Posts This Month',
        quickActions: 'Quick Actions',
        novelWriter: 'Novel Writer',
        commulingoDocs: 'Reference Docs',
        recentPostsTitle: 'Recent Posts',

        postId: 'ID',
        postTitle: 'Title',
        postCreated: 'Created',
        postActions: 'Actions',
        edit: 'Edit',
        delete: 'Delete',
        deleteConfirm: 'Are you sure you want to delete this post?',
        noPostsYet: 'No posts yet.',
        createFirst: 'Create your first post',

        editPost: 'Edit Post',
        newPost: 'New Post',
        backToPosts: 'Back to list',
        titleLabel: 'Title',
        contentLabel: 'Content',
        update: 'Update',
        create: 'Create',
        cancel: 'Cancel',

        insertLink: 'Insert Link',
        linkUrl: 'URL',
        linkTitle: 'Tooltip',
        linkText: 'Text',
        linkInsert: 'Insert',
        linkCancel: 'Cancel',

        clearCache: 'Clear Cache',
        cacheCleared: 'Cleared!',

        chatLogs: 'Chat Logs',
        chatLogsFilterAll: 'All',
        chatLogsFilterCasual: 'Casual',
        chatLogsFilterVectorstore: 'Knowledge Search',
        chatLogsRefresh: 'Refresh',
        chatLogsLoading: 'Loading...',

        users: 'User Accounts',
        usersSearch: 'Search usernames',
        usersEmpty: 'No user accounts.',
        usersSelectHint: 'Select an account from the list.',
        usersRename: 'Rename',
        usersMerge: 'Merge Account',
        usersMergeSource: 'Source account',
        usersMergeTarget: 'Target user ID',
        usersDeleteConfirm: 'Type the exact username to delete this account. Chat logs are retained by fingerprint.',
        usersAdminBadge: 'Admin',
        usersPassword: 'Password',
        usersPasskeys: 'Passkeys',
        usersFingerprints: 'Fingerprints',
        usersLastLogin: 'Last login',
        usersLastChat: 'Last chat',
        usersNoFingerprints: 'No fingerprints linked.',

        passkeys: 'Passkeys',
        passkeysHint: 'Manage registered passkeys. Remove passkeys for lost devices.',
        passkeysEmpty: 'No passkeys registered.',
        addPasskey: 'Add passkey on this device',
        passkeyAdded: 'Added.',
        passkeyDeleteConfirm: 'Delete this passkey?',
        passkeyUnnamed: '(unnamed)',
        passkeyCreated: 'Created',
        passkeyLastUsed: 'Last used',
        passkeyNever: 'Never'
    },

    chat: {
        title: 'Chat with Cyber-Lenin',
        placeholder: 'Type a message. Enter adds a line, Ctrl/Cmd+Enter sends',
        inputLabel: 'Message input',
        inputHint: 'Enter adds a line, Ctrl/Cmd+Enter sends',
        send: 'Send',
        emptyHint: 'No messages yet.\nType below to start a conversation with {name}.',
        defaultPersonaName: 'Cyber-Lenin',
        thinking: 'Comrade is thinking...',
        error: 'An error occurred.',
        notSaved: "The reply didn't come through. Please resend your message.",
        retry: '↻ Retry',
        personaLabel: 'Chat with',
        feedbackSaved: 'Saved',
        feedbackError: 'Feedback failed',
        feedbackNote: 'Write feedback',
        feedbackSave: 'Save feedback',
        feedbackToggle: 'Feedback · Regenerate',
        regenerate: 'Regenerate',
        regenerating: 'Regenerating...',
        deleteLabel: 'Delete',
        deleteConfirmUser: 'Delete this question? It will be excluded from future chat context.',
        deleteConfirmAssistant: 'Delete this response? It will be excluded from future chat context.',
        deleteError: 'Could not delete the message.'
    },

    commuLingo: {
        title: 'commulingo',
        description: 'A learning space for revolutionary theory and history.',
        dictSectionTitle: 'Dictionaries & Library',
        dictSectionHint: 'Unfamiliar people, events, or terms? Look them up here.',
        quizLabel: 'Quizzes',
        quizShort: 'Quiz',
        dictPeopleShort: 'People',
        dictEventsShort: 'Events',
        dictTermsShort: 'Terms',
        dictGenealogyShort: 'Charts',
        dictDocsShort: 'Refs',
        dictPeople: 'People',
        dictEvents: 'Historical events',
        dictTerms: 'Glossary',
        dictGenealogy: 'Genealogy',
        dictDocs: 'References',
        kicker: 'Capital Volume I',
        start: 'Start',
        continue: 'Continue',
        review: 'Review',
        progress: 'Progress',
        questions: 'Questions',
        lessons: 'Lessons',
        score: 'Score',
        completed: 'Completed',
        locked: 'Coming soon',
        next: 'Next',
        finish: 'Finish',
        tryAgain: 'Try again',
        correct: 'Correct',
        incorrect: 'Incorrect',
        syncLogin: 'Sign in to sync progress to your account.',
        syncSaved: 'Progress saved',
        syncLocal: 'Progress is saved in this browser.',
        allDone: "Today's lesson complete",
        backToLessons: 'Lessons',
        chooseBook: 'Choose a book',
        chooseBookHint: 'Pick a book and learn it chapter by chapter through quizzes.',
        continueLearning: 'Continue learning',
        backToBooks: 'Books',
        nextLesson: 'Next lesson',
        bookProgressEmpty: 'Not started yet',
        chapters: 'Chapters',
        authorMarx: 'Karl Marx',
        authorEngels: 'Friedrich Engels',
        authorLenin: 'Vladimir Lenin',
        authorOther: 'Other',
        conceptMapLabel: 'Interactive concept map',
        exploreMode: 'Tap to explore',
        graphHint: 'Open each link of the chain below in turn: plain explanation → Engels’s argument → modern critique.',
        drill: 'Training ground',
        drillDesc: 'Random quizzes and timeline games built from the term, people, and event dictionaries. Every round draws different questions.',
        drillOpen: 'Start training',
        drillBest: 'Best score',
        drillRoundsDone: 'rounds played',
        drillNextRound: 'Next round',
        drillBackToDecks: 'Deck list',
        drillRoundDone: 'Round complete',
        drillCheckOrder: 'Check order',
        drillMoveUp: 'Move up',
        drillMoveDown: 'Move down',
        drillLookup: 'Open dictionary entry',
        drillOrderHint: 'Reorder with the up and down buttons, then check. Earliest goes on top.',
        drillLoadFail: 'Could not load the questions. Please try again shortly.'
    },

    error: {
        notFound: 'Page not found.',
        serverError: 'Something went wrong.',
        backHome: 'Back to home'
    }
};

// Fill a persona template. The reader's choice lives in localStorage, so the
// browser re-runs this (objectParticle/renderEmptyHint in public/js/chat.js)
// whenever they switch; this is the server-rendered default it starts from.
// 과/와 follows the final consonant: 사이버-레닌과, 안토니오 그람시와. A name
// ending in a Latin letter or digit takes 과, which is how Korean reads them.
function withPersona(template, name) {
    const label = String(name || '').trim();
    const last = label.slice(-1);
    const code = last.charCodeAt(0);
    const particle = (code >= 0xac00 && code <= 0xd7a3 && (code - 0xac00) % 28 === 0) ? '와' : '과';
    return String(template || '').replace(/\{name\}/g, label).replace(/\{과\}/g, particle);
}

module.exports = { ko, en, withPersona };
