// Person cards for the siberia-far-east-1918-1922 event (civil war in Siberia
// and the Far East), see lib.js person(). Excerpts are verbatim from the cited
// pages. Tryapitsyn's 1920 Okhotsk Front command belonged to the army of the Far
// Eastern Republic, which has no catalog affiliation, so that activity stays
// unresolved.
const { W, person } = require('../lib');

const E = t => W(encodeURI(t));
const RU = t => 'https://ru.wikipedia.org/wiki/' + encodeURI(t);
const S = {
    graves: E('William_S._Graves'),
    ruGraves: RU('Грейвс,_Уильям_Сидней'),
    aef: E('American_Expeditionary_Force,_Siberia'),
    kalmykov: E('Ivan_Kalmykov'),
    ruKalmykov: RU('Калмыков,_Иван_Павлович'),
    shchetinkin: E('Pyotr_Shchetinkin'),
    ruShchetinkin: RU('Щетинкин,_Пётр_Ефимович'),
    tryapitsyn: E('Yakov_Tryapitsyn'),
    ruTryapitsyn: RU('Тряпицын,_Яков_Иванович'),
};

const unaffiliated = card => ({
    ...card,
    activities: card.activities.map(a => (a.affiliationId ? a : { ...a, affiliationStatus: 'unresolved', relation: 'unresolved' })),
});
const withPatronymic = (card, ko, en, native) => ({ ...card, patronymic: { ko, en }, cyrillicPatronymic: native });

module.exports = [
    person({
        id: 'william-s-graves', groupId: 'world-interwar',
        given: ['윌리엄 S.', 'William S.'], family: ['그레이브스', 'Graves'], nativeName: 'William Sidney Graves', years: '1865–1940',
        citizenship: 'usa', origin: 'usa',
        epithet: ['1918~1920년 미국 시베리아 원정군을 이끌며 러시아 내전에 엄격한 중립을 지킨 장군',
            'General who led the American Expeditionary Force in Siberia in 1918–1920 and kept it strictly neutral in the Russian Civil War'],
        bio: ['1865년 텍사스에서 침례교 목사의 아들로 태어나 1889년 웨스트포인트를 졸업했고, 필리핀-미국 전쟁에 참전한 뒤 육군 참모본부에서 일했다. 1918년 윌슨 대통령의 직접 명령으로 미국 시베리아 원정군을 맡아 9월 블라디보스토크에 도착했다. 정치적 중립을 지키라는 명령에 따라 철도 운행과 체코슬로바키아 군단의 철수에 집중했고, 콜차크 쪽을 도우라는 압력을 거부했다. 세묘노프와 칼미코프 병사들의 살인과 약탈, 일본의 동시베리아 병합 의도를 비판했다. 마지막 미군은 1920년 4월 1일 떠났다. 1928년 퇴역해 회고록 『미국의 시베리아 모험』을 냈고, 1940년 뉴저지에서 숨졌다.',
            'Born in Texas in 1865, the son of a Baptist minister, he graduated from West Point in 1889, fought in the Philippine–American War and served on the Army General Staff. In 1918 he was given the American Expeditionary Force in Siberia on the direct orders of President Wilson and reached Vladivostok in September. Ordered to stay strictly apolitical, he concentrated on keeping the railway running and on the evacuation of the Czechoslovak Legion, and refused pressure to help Kolchak’s Whites. He condemned the killing and robbery committed by the soldiers of Semyonov and Kalmykov and suspected Japan of planning to annex eastern Siberia. The last American soldiers left on 1 April 1920. He retired in 1928, wrote the memoir America’s Siberian Adventure, and died in New Jersey in 1940.'],
        fate: ['natural', '자연사', 'Natural death'],
        aliases: { ko: ['윌리엄 시드니 그레이브스', '윌리엄 그레이브스'], en: ['William Sidney Graves', 'William Graves'] },
        sources: [S.graves, S.ruGraves, S.aef, S.kalmykov],
        facts: {
            years: { claim: '1865–1940', locator: 'lead', excerpt: 'March 27, 1865 – February 27, 1940' },
            citizenship: { claim: 'United States Army officer', locator: 'lead', excerpt: 'was a United States Army officer who commanded American forces in Siberia' },
            nationalOrigin: { claim: 'born in Texas to a Southern Baptist minister', locator: 'Early life and education', excerpt: 'He was born on March 27, 1865, in Mount Calm, Texas, to the Reverend Andrew Carrol, a Southern Baptist minister and Evelyn Bennett.' },
            bio: [
                { claim: 'born in Texas, son of a Baptist minister', locator: 'Early life and education', excerpt: 'He was born on March 27, 1865, in Mount Calm, Texas, to the Reverend Andrew Carrol, a Southern Baptist minister' },
                { claim: 'graduated from West Point in 1889', locator: 'Early life and education', excerpt: 'ultimately graduated forty-second in a class of forty-nine on June 12, 1889' },
                { claim: 'served in the Philippine–American War 1899–1902', source: S.ruGraves, locator: 'Биография', excerpt: 'В 1899—1902 участвовал в филиппино-американской войне.' },
                { claim: 'assistant chief of the Army General Staff', locator: 'Military career', excerpt: 'He was the assistant chief of the Army General Staff.' },
                { claim: 'sent to Siberia in 1918 on Wilson’s direct orders', locator: 'Military career', excerpt: 'he was given command of the 8th Division and sent to Siberia under direct orders from President Woodrow Wilson' },
                { claim: 'arrived in Siberia in September 1918', source: S.aef, locator: 'History', excerpt: 'Although General Graves did not arrive in Siberia until September 4, 1918' },
                { claim: 'ordered to remain strictly apolitical', locator: 'Military career', excerpt: 'His orders were to remain strictly apolitical amidst a politically turbulent situation.' },
                { claim: 'kept the railway operating', locator: 'Military career', excerpt: 'he settled on the idea of making sure the Trans-Siberian railroad stayed operational' },
                { claim: 'mission to help the Czechoslovak Legion evacuate, not to fight the Bolsheviks', source: S.aef, locator: 'History', excerpt: 'General Graves believed their mission in Siberia was to provide protection for American-supplied property and to help the Czechoslovak Legion evacuate Russia, and that it did not include fighting against the Bolsheviks' },
                { claim: 'refused pressure to help Kolchak', locator: 'Military career', excerpt: 'His troops did not intervene in the Russian Civil War despite strong pressure brought on him to help the White army of Admiral Kolchak.' },
                { claim: 'condemned the killings by Semyonov’s and Kalmykov’s soldiers', source: S.kalmykov, locator: 'Russian Civil War', excerpt: 'Semeonoff and Kalmikoff soldiers, under the protection of Japanese troops, were roaming the country like wild animals, killing and robbing the people' },
                { claim: 'suspected Japan of planning to annex eastern Siberia', locator: 'Military career', excerpt: 'He also believed that the Japanese had plans to annex part of Eastern Siberia' },
                { claim: 'last US soldiers left on 1 April 1920', locator: 'Military career', excerpt: 'The last U.S. soldiers left Siberia on April 1, 1920.' },
                { claim: 'retired in 1928 and wrote America’s Siberian Adventure', locator: 'Military career', excerpt: 'retired from the army in 1928.  He then wrote a book about his time in Siberia, entitled America\'s Siberian Adventure 1918-20.' },
                { claim: 'died in New Jersey in 1940', locator: 'Death', excerpt: 'Graves died on February 27, 1940, in Shrewsbury, New Jersey.' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: 'state-usa', startYear: 1918, endYear: 1920, primary: true, claim: 'Commander of the American Expeditionary Force, Siberia', locator: 'lead', excerpt: 'commanded American forces in Siberia during the Siberian Expedition, part of the Allied Intervention in Russia' },
            { functionId: 'military', affiliationId: 'state-usa', startYear: 1889, endYear: 1928, claim: 'United States Army officer from West Point graduation to retirement', locator: 'Military career', excerpt: 'retired from the army in 1928' },
        ],
        career: [
            ['1889', '웨스트포인트 졸업', 'Graduated from West Point'],
            ['1899–1902', '필리핀-미국 전쟁 참전', 'Served in the Philippine–American War'],
            ['1909', '워싱턴 육군 참모본부 근무', 'Assigned to the General Staff in Washington'],
            ['1918', '준장 진급, 제8사단장', 'Promoted brigadier general; commander of the 8th Division'],
            ['1918–1920', '미국 시베리아 원정군 사령관', 'Commander of the American Expeditionary Force, Siberia'],
            ['1928', '퇴역', 'Retired from the army'],
        ],
    }),
    withPatronymic(person({
        id: 'ivan-kalmykov', groupId: 'old-regime',
        given: ['이반', 'Ivan'], family: ['칼미코프', 'Kalmykov'], nativeName: 'Иван Калмыков', years: '1890–1920',
        citizenship: 'russia', origin: 'russia',
        epithet: ['1918년 하바롭스크를 점령하고 재판 없는 총살과 약탈로 악명을 떨친 우수리 카자크 아타만',
            'Ataman of the Ussuri Cossacks who took Khabarovsk in 1918 and became notorious for shootings without trial and plunder'],
        bio: ['1890년 테레크주 그로즈니 지역에서 태어나 트빌리시 사관학교를 졸업했고, 1914년 우수리 카자크 연대로 옮겨 제1차 세계대전에서 성 게오르기 무기를 받았다. 1918년 1월 우수리 카자크군 아타만으로 뽑혀 볼셰비키와 싸웠고, 9월 5일 하바롭스크를 점령해 수비대장이 되었다. 그해 하바롭스크에서는 재판 없는 대량 총살이 잇따랐고, 그의 부대의 약탈·살인·강간은 콜차크를 비롯한 백군 지도자들의 분노를 샀다. 1920년 2월 하바롭스크 국립은행 지점의 금을 일본군 사령부에 몰래 넘기고 중국으로 건너갔다가 중국 당국에 체포되었고, 9월 초 탈주하다 사살되었다.',
            'Born in the Grozny district of the Terek Region in 1890, he graduated from the military school in Tbilisi, transferred to the Ussuri Cossack Regiment in 1914 and won the Sword of St. George in the First World War. Elected ataman of the Ussuri Cossack Host in January 1918, he fought the Bolsheviks and on 5 September took Khabarovsk, becoming head of its garrison. Mass shootings without trial followed in Khabarovsk that year, and the robbery, murder and rape committed by his men outraged White leaders, Kolchak first among them. In February 1920 he secretly handed the gold of the Khabarovsk branch of the State Bank to the Japanese command and crossed into China, where the Chinese authorities arrested him; in early September he was shot while trying to escape.'],
        fate: ['killed', '탈주 중 사살', 'Shot while escaping'],
        aliases: { ko: ['아타만 칼미코프'], en: ['Ataman Kalmykov'] },
        sources: [S.kalmykov, S.ruKalmykov],
        facts: {
            years: { claim: '1890–1920', locator: 'lead', excerpt: 'September 5, 1890 – September 1920' },
            citizenship: { claim: 'Ataman of the Ussuri Cossacks and White general', locator: 'lead', excerpt: 'was an Ataman of the Ussuri Cossacks and General associated with the Anti-Bolshevik White Movement during the Russian Civil War' },
            nationalOrigin: { claim: 'son of a Kharkov trader and a Terek Cossack mother', source: S.ruKalmykov, locator: 'Биография', excerpt: 'Мать Ивана Калмыкова — местная терская казачка Калмыкова.' },
            bio: [
                { claim: 'born in the Grozny district of the Terek Region in 1890', locator: 'Youth', excerpt: 'Ivan Kalmykov was born in the District of Grozny in the Terek Region on September 5, 1890.' },
                { claim: 'graduated from the military school in Tbilisi', source: S.ruKalmykov, locator: 'Биография', excerpt: 'По окончании Тифлисского Великого князя Михаила Николаевича военного училища по 1-му разряду' },
                { claim: 'transferred to the Ussuri Cossack Regiment in 1914', locator: 'Youth', excerpt: 'on January 20, 1914, he was transferred to the Ussuri Cossack Regiment' },
                { claim: 'Sword of St. George in the First World War', locator: 'World War I', excerpt: 'During the war he received four awards, including the Order of St. Vladimir and the Sword of St. George' },
                { claim: 'elected ataman of the Ussuri Cossack Host in January 1918', source: S.ruKalmykov, locator: 'Гражданская война', excerpt: '31.1.1918 г. на 4-м круге Уссурийского казачьего войска избран атаманом' },
                { claim: 'took Khabarovsk on 5 September 1918 and headed its garrison', locator: 'Russian Civil War', excerpt: 'on 5 September 1918 at the head of the Special Ussuri Cossack Detachment, he occupied Khabarovsk. On September 17, he took over as head of the Khabarovsk Garrison.' },
                { claim: 'mass shootings without trial in Khabarovsk in September 1918', source: S.ruKalmykov, locator: 'Гражданская война', excerpt: 'В сентябре 1918 года в Хабаровске имело место несколько массовых расстрелов без суда и следствия.' },
                { claim: 'his soldiers’ crimes outraged White leaders, Kolchak first', locator: 'Russian Civil War', excerpt: 'Kalmykov became infamous for the number of robberies, murders, and wanton rape and looting committed by his soldiers, which aroused the indignation of many leaders in the White Movement, first among them Admiral Kolchak himself.' },
                { claim: 'handed the Khabarovsk State Bank gold to the Japanese command', locator: 'Russian Civil War', excerpt: 'Kalmykov seized 622 kg/1372 lb of gold from the Khabarovsk branch of the State Bank, secretly transferring it as a loan to the Japanese command.' },
                { claim: 'left Khabarovsk for China in February 1920', locator: 'Russian Civil War', excerpt: 'the Ussuri Cossack detachment left Khabarovsk on February 13 and transferred the Ussuri Host to the Chinese territory over the ice' },
                { claim: 'arrested by the Chinese military authorities', locator: 'Death', excerpt: 'on March 8, the Ataman was arrested by the Chinese military authorities' },
                { claim: 'shot while trying to escape in early September 1920', locator: 'Death', excerpt: 'At the beginning of September 1920, the Ataman, escorted by the convoy to Jilin once again attempted to flee from the city, wounded the Chinese officer, and was subsequently shot and killed by the Chinese soldiers during the escape attempt.' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: 'russian-white', startYear: 1918, endYear: 1920, primary: true, claim: 'Ataman of the Ussuri Cossack Host and White general', locator: 'Russian Civil War', excerpt: 'promoted to him the rank of Major-General and elected him the Military Ataman of the Ussuri Cossack Army' },
            { functionId: 'military', affiliationId: 'russian-empire', startYear: 1914, endYear: 1917, claim: 'Officer of the Ussuri Cossack Regiment in the First World War', locator: 'World War I', excerpt: 'He took part in the First World War, holding the rank of Centurion (сотник) from 1915, then Captain (Подпоручик) from 1917, in the Ussuri Cossack Regiment.' },
        ],
        career: [
            ['1914', '우수리 카자크 연대로 전속', 'Transferred to the Ussuri Cossack Regiment'],
            ['1918', '우수리 카자크군 아타만 선출', 'Elected ataman of the Ussuri Cossack Host'],
            ['1918', '하바롭스크 점령, 하바롭스크 수비대장', 'Took Khabarovsk; head of the Khabarovsk garrison'],
            ['1918', '소장 진급, 우수리 카자크군 군사 아타만', 'Promoted major general; military ataman of the Ussuri Cossack Host'],
            ['1920', '우수리 집단군 사령관, 중국으로 퇴각', 'Commander of the Ussuri group of forces; retreated into China'],
        ],
    }), '파블로비치', 'Pavlovich', 'Павлович'),
    withPatronymic(person({
        id: 'pyotr-shchetinkin', groupId: 'bolshevik',
        given: ['표트르', 'Pyotr'], family: ['셰틴킨', 'Shchetinkin'], nativeName: 'Пётр Щетинкин', years: '1884–1927',
        citizenship: 'soviet', origin: 'russia',
        epithet: ['예니세이현의 파르티잔군을 이끌고 1921년 몽골에서 운게른을 넘겨받은 시베리아 파르티잔 지휘관',
            'Siberian partisan commander who led the partisan army of Yeniseysk Province and took custody of Ungern in Mongolia in 1921'],
        bio: ['1884년 랴잔현의 농민 가정에서 태어나 목수로 일했고, 1906년 징집되어 아친스크의 제29 시베리아 소총연대에서 복무했다. 제1차 세계대전에서 성 게오르기 십자 훈장 네 개를 모두 받아 장교가 되었고 1917년 이등대위에 올랐다. 1918년 3월 러시아 공산당(볼셰비키)에 입당했고, 아친스크가 백군에 넘어가자 지하로 들어가 1919년 1월 파르티잔 활동을 시작했다. 다른 파르티잔 부대와 합친 파르티잔군의 참모장으로 타이가를 700킬로미터 행군해 9월 미누신스크를 차지했다. 1921년 8월 그의 부대가 몽골에서 운게른을 넘겨받았다. 그 뒤 시베리아 국경수비대 참모장을 지냈고, 몽골 군사 고문으로 있던 1927년 울란바토르에서 숨졌다. 사인은 출처마다 엇갈린다.',
            'Born to a peasant family in Ryazan Province in 1884, he worked as a carpenter, was drafted in 1906 and served in the 29th Siberian Rifle Regiment at Achinsk. In the First World War he won all four classes of the Cross of St. George, was commissioned and by 1917 was a staff captain. He joined the Russian Communist Party (Bolsheviks) in March 1918; when Achinsk fell to the Whites he went underground and opened partisan operations in January 1919. As chief of staff of a partisan army formed by merging his detachment with another, he marched 700 kilometres south through the taiga and took Minusinsk in September. In August 1921 his detachment took custody of Ungern in Mongolia. He later served as chief of staff of the Siberian border troops, and died in Ulaanbaatar in 1927 while a military adviser in Mongolia; sources differ on the cause of death.'],
        fate: ['natural', '사인 논란', 'Cause of death disputed'],
        aliases: { ko: ['티무르 바토르', '표트르 예료민'], en: ['Timur Bator', 'Pyotr Yeryomin'] },
        sources: [S.shchetinkin, S.ruShchetinkin],
        facts: {
            years: { claim: '1884–1927', locator: 'lead', excerpt: 'December 21, 1884 (or January 2, 1885) – September 30, 1927' },
            citizenship: { claim: 'leader of the Soviet partisan movement in Siberia', locator: 'lead', excerpt: 'was a Russian staff captain who became one of the leaders of the Soviet partisan movement in Siberia during the Russian Civil War' },
            nationalOrigin: { claim: 'born to a Russian peasant family in Ryazan Oblast', locator: 'Early life', excerpt: 'Shchetinkin was born to a peasant family in 1884 in Chufilovo Village, present day Spas-Klepiki, Ryazan Oblast.' },
            bio: [
                { claim: 'born to a peasant family in 1884', locator: 'Early life', excerpt: 'Shchetinkin was born to a peasant family in 1884 in Chufilovo Village' },
                { claim: 'worked as a carpenter', locator: 'Early life', excerpt: 'As a young man he worked as a carpenter with his father.' },
                { claim: 'drafted in 1906, 29th Siberian Rifle Regiment at Achinsk', locator: 'Military', excerpt: 'In 1906 he was drafted into the army and served in the 29th Siberian Rifle Regiment in Achinsk.' },
                { claim: 'all four Crosses of St. George, commissioned', locator: 'Military', excerpt: 'as a bearer of all four classes of the Cross of St. George, was promoted to ensign' },
                { claim: 'staff captain in 1917', locator: 'Military', excerpt: 'In 1917 he became a staff captain.' },
                { claim: 'joined the Communist Party in March 1918', locator: 'Guerrilla activity in the Civil War', excerpt: 'He joined the Russian Communist Party in March 1918.' },
                { claim: 'went underground after Achinsk fell to the Whites', locator: 'Guerrilla activity in the Civil War', excerpt: 'After the fall of Achinsk to White Russian forces, Shchetinkin went underground' },
                { claim: 'partisan detachment began operations on 5 January 1919', source: S.ruShchetinkin, locator: '1918—1920', excerpt: 'организовал партизанский отряд, который 5 января 1919 года приступил к активным действиям' },
                { claim: 'chief of staff of the merged partisan army', locator: 'Guerrilla activity in the Civil War', excerpt: 'Shchetinkin became chief of staff of the partisan army' },
                { claim: '700-km march through the taiga, Minusinsk taken in September 1919', source: S.ruShchetinkin, locator: '1918—1920', excerpt: 'Совершив 700-километровый переход через тайгу на юг, партизанские силы в сентябре 1919 года заняли Минусинск.' },
                { claim: 'his detachment took Ungern in August 1921', source: S.ruShchetinkin, locator: '1921—1927', excerpt: '19 августа 1921 года отряд под командованием Щетинкина, входивший в состав 35-го кавалерийского полка РККА, захватил барона Унгерна, взятого в плен монгольским князем Бишерельту-гуном.' },
                { claim: 'chief of staff of the Siberian border troops 1922–1926', source: S.ruShchetinkin, locator: '1921—1927', excerpt: 'С октября 1922 до 1926 года — начальник штаба пограничных войск Сибирского пограничного округа.' },
                { claim: 'military adviser in Mongolia from 1926', source: S.ruShchetinkin, locator: '1921—1927', excerpt: 'В августе 1926 года приглашён правительством Монгольской народной республики в качестве военного советника и инструктора' },
                { claim: 'died in Ulaanbaatar in 1927', locator: 'Later career', excerpt: 'He died 30 September 1927 in Ulaanbaatar.' },
                { claim: 'sources differ on the cause of death', locator: 'Later career', excerpt: 'Sources differ on his cause of death' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: 'state-soviet', startYear: 1918, endYear: 1920, primary: true, claim: 'Red Guard commander and partisan leader in Yeniseysk Province, then commander of the Yenisei Rifle Division', locator: '1918—1920', source: S.ruShchetinkin, excerpt: 'вскоре Щетинкин был назначен командиром сформированной из партизан Енисейской стрелковой дивизии' },
            { functionId: 'military', affiliationId: 'state-soviet', startYear: 1921, endYear: 1921, claim: 'Commanded the Red Army expeditionary detachment in Mongolia', locator: 'Mongolia', excerpt: 'In 1921 Shchetinkin commanded the Red Army expeditionary detachment' },
            { functionId: 'security', affiliationId: 'state-soviet', startYear: 1922, endYear: 1926, claim: 'OGPU plenipotentiary office in Siberia and chief of staff of the Siberian border troops', locator: '1921—1927', source: S.ruShchetinkin, excerpt: 'С октября 1922 до 1926 года — начальник штаба пограничных войск Сибирского пограничного округа.' },
            { functionId: 'military', affiliationId: 'russian-empire', startYear: 1906, endYear: 1917, claim: 'Soldier and officer of the Imperial Russian Army', locator: 'Military', excerpt: 'In 1906 he was drafted into the army and served in the 29th Siberian Rifle Regiment in Achinsk.' },
        ],
        career: [
            ['1906', '징집, 제29 시베리아 소총연대 복무', 'Drafted; served in the 29th Siberian Rifle Regiment'],
            ['1917', '이등대위', 'Staff captain'],
            ['1918', '러시아 공산당(볼셰비키) 입당, 아친스크 적위대 지휘관', 'Joined the Russian Communist Party (Bolsheviks); Red Guard commander at Achinsk'],
            ['1919', '파르티잔군 부사령관 겸 참모장', 'Deputy commander and chief of staff of the partisan army'],
            ['1920', '예니세이 소총 사단장', 'Commander of the Yenisei Rifle Division'],
            ['1921', '몽골 원정 부대 지휘관', 'Commander in the Red Army expedition to Mongolia'],
            ['1922–1926', '시베리아 국경수비대 참모장', 'Chief of staff of the Siberian border troops'],
            ['1926–1927', '몽골 인민공화국 군사 고문', 'Military adviser to the Mongolian People’s Republic'],
        ],
    }), '예피모비치', 'Yefimovich', 'Ефимович'),
    withPatronymic(unaffiliated(person({
        id: 'yakov-tryapitsyn', groupId: 'bolshevik',
        given: ['야코프', 'Yakov'], family: ['트랴피친', 'Tryapitsyn'], nativeName: 'Яков Тряпицын', years: '1897–1920',
        citizenship: 'soviet', origin: 'russia',
        epithet: ['1920년 니콜라옙스크나아무레를 점령했다가 주민과 포로를 처형하고 불태운 극동의 파르티잔 지휘관',
            'Far Eastern partisan commander who took Nikolayevsk-on-Amur in 1920, then executed its prisoners and burned the town'],
        bio: ['1897년 블라디미르현 무롬군의 농민 가정에서 태어나 기관사 조수로 일했다. 1916년 징집되어 제1차 세계대전에서 준위까지 올랐고 성 게오르기 십자 훈장을 두 번 받았다. 1918년 적위대에 들어가 사마라 봉기 진압에 참여했고, 1919년 연해주에서 자기 파르티잔 부대를 꾸렸다. 11월 35명으로 니콜라옙스크나아무레로 진군을 시작해 니콜라옙스크 전선 사령관이 되었고, 1920년 2월 도시에 들어간 뒤 3월 일본 수비대와의 전투에서 이겼다. 5월 말 일본 원군이 다가오자 남은 포로를 모두 처형하고 도시를 불태웠다. 7월 케르비에서 참모들과 함께 체포되어 즉석 재판 끝에 9일 총살되었다.',
            'Born to a peasant family in Murom district, Vladimir Province, in 1897, he worked as an assistant locomotive machinist. Drafted in 1916, he rose to ensign in the First World War and was twice awarded the Cross of St. George. He joined the Red Guard in 1918, took part in suppressing the Samara rising, and in 1919 formed his own partisan detachment in Primorye. In November he set out for Nikolayevsk-on-Amur with 35 fighters and became commander of the Nikolayevsk Front; he entered the town in February 1920 and won the fighting with the Japanese garrison in March. As a Japanese relief force approached at the end of May he executed all the remaining prisoners and burned the town. In July he was arrested at Kerbi with his staff and, after an improvised trial, shot on the 9th.'],
        fate: ['executed', '총살', 'Executed by shooting'],
        aliases: { ko: [], en: ['Yakov Tryapitsin'] },
        sources: [S.tryapitsyn, S.ruTryapitsyn],
        facts: {
            years: { claim: '1897–1920', locator: 'lead', excerpt: '(25 April 1897 – 9 July 1920)' },
            citizenship: { claim: 'Russian and Soviet military figure', locator: 'lead', excerpt: 'was a Russian and Soviet military and political figure' },
            nationalOrigin: { claim: 'born to a Russian peasant family in Vladimir Province', locator: 'Early life and career', excerpt: 'Yakov Ivanovich Tryapitsin was born on 25 April 1897 in the village of Savasleyka in the Muromsky District of the Vladimir Province of the Russian Empire, in the family of a peasant' },
            bio: [
                { claim: 'born in Murom district to a peasant family', locator: 'Early life and career', excerpt: 'in the village of Savasleyka in the Muromsky District of the Vladimir Province of the Russian Empire, in the family of a peasant' },
                { claim: 'assistant locomotive machinist', locator: 'Early life and career', excerpt: 'In 1915 he entered the work of an assistant to the machinist on a locomotive' },
                { claim: 'enlisted in 1916', locator: 'Early life and career', excerpt: 'In the summer of 1916, he was enlisted in the Kexholm Regiment of the Imperial Russian Army.' },
                { claim: 'ensign, twice awarded the Cross of St. George', locator: 'Early life and career', excerpt: 'rose to the rank of Ensign (Praporshchik), and was twice awarded the Cross of St. George' },
                { claim: 'joined the Red Guard in 1918', locator: 'Early life and career', excerpt: 'upon returning to Russia, he joined the Red Guard' },
                { claim: 'suppression of the Samara insurrection', locator: 'Early life and career', excerpt: 'He subsequently participated in the suppression of the Samara insurrection from June to October 1918.' },
                { claim: 'organized his own partisan detachment in 1919', locator: 'Partisan commander', excerpt: 'he left to the river Iman, where he organized his own Partisan detachment' },
                { claim: 'set out for Nikolayevsk with 35 fighters on 10 November 1919', locator: 'Partisan commander', excerpt: 'on 10 November 1919, a detachment of Tryapitsyn consisting of 35 initial fighters began their march from Vyatka to Nikolayevsk-on-Amur' },
                { claim: 'commander of the Nikolayevsk Front', locator: 'Command of the Nikolayevsk Front', excerpt: 'The staff of the Red Army headquarters of the Nikolayevsk Front included Yakov I. Tryapitsyn as front commander' },
                { claim: 'entered the town after the February 1920 agreement', locator: 'Command of the Nikolayevsk Front', excerpt: 'The Japanese were forced to sign an agreement on neutrality, on the basis of which parts of the Red Army entered the city.' },
                { claim: 'won the March fighting with the Japanese', locator: 'Far Eastern Command', excerpt: 'The fighting lasted several days and ended with the victory of the Red Army.' },
                { claim: 'executed the remaining prisoners and burned the town in late May', locator: 'Nikolayevsk incident and death', excerpt: 'In late May, as a Japanese relief expedition approached, Tryapitsyn ordered the evacuation of all Red Army soldiers, staff, and Soviet personnel from the city, and subsequently executed all of the remaining prisoners and burned the town to the ground.' },
                { claim: 'arrested at Kerbi on 7 July 1920 with his staff', source: S.ruTryapitsyn, locator: 'Заговор и гибель', excerpt: '7 июля 1920 г. у таёжного поселка Керби Я. И. Тряпицын, вместе со всем штабом, командирами полков и работниками органов Советской власти в Сахалинской области, в результате заговора были арестованы' },
                { claim: 'shot on 9 July after an improvised trial', locator: 'Nikolayevsk incident and death', excerpt: 'presided over a brief improvised trial in which Tryapitsin, his staff, regimental commanders, and the Chief of Staff of the Okhotsk Front, Nina Lebedeva, were condemned to death and subsequently shot on 9 July' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: 'state-soviet', startYear: 1918, endYear: 1920, primary: true, claim: 'Red Guard, partisan commander and commander of the Nikolayevsk Front of the Red Army', locator: 'lead', excerpt: 'he subsequently joined the Red Guards, and was appointed the Commander of the Nikolayevsk Front and the Nikolayevsk Military District of the Red Army of the Russian SFSR' },
            { functionId: 'military', affiliationId: null, startYear: 1920, endYear: 1920, claim: 'Commander of the Okhotsk Front of the People’s Revolutionary Army of the Far Eastern Republic', locator: 'Far Eastern Command', excerpt: 'according to the order No. 66 of the Commander-in-Chief of the People\'s Revolutionary Army, he was appointed Commander of the Okhotsk Front' },
            { functionId: 'military', affiliationId: 'russian-empire', startYear: 1916, endYear: 1918, claim: 'Soldier and ensign of the Imperial Russian Army', locator: 'Early life and career', excerpt: 'In the summer of 1916, he was enlisted in the Kexholm Regiment of the Imperial Russian Army.' },
        ],
        career: [
            ['1916–1918', '러시아 제국군 복무, 준위', 'Served in the Imperial Russian Army; ensign'],
            ['1918', '적위대 입대, 사마라 봉기 진압 참여', 'Joined the Red Guard; fought the Samara rising'],
            ['1919', '연해주 파르티잔 부대 지휘관', 'Commander of a partisan detachment in Primorye'],
            ['1920', '붉은 군대 니콜라옙스크 전선 사령관', 'Commander of the Nikolayevsk Front of the Red Army'],
            ['1920', '극동공화국 인민혁명군 오호츠크 전선 사령관', 'Commander of the Okhotsk Front of the Far Eastern Republic’s People’s Revolutionary Army'],
        ],
    })), '이바노비치', 'Ivanovich', 'Иванович'),
];
