// Glossary terms for the siberia-far-east-1918-1922 event (2026-10-04).
// Built with lib.js term(); see BRIEF2.md for sources and spelling rules.
// None of these bodies still exists, so no ongoing() wrapper is needed.
const { term } = require('../lib');

const E = t => 'https://en.wikipedia.org/wiki/' + encodeURI(t);
const RU = t => 'https://ru.wikipedia.org/wiki/' + encodeURI(t);
const S = {
    japan: E('Japanese_intervention_in_Siberia'),
    siberian: E('Siberian_intervention'),
    aef: E('American_Expeditionary_Force,_Siberia'),
    ruGraves: RU('Грейвс,_Уильям_Сидней'),
    nikolayevsk: E('Nikolayevsk_incident'),
    ruNikolayevsk: RU('Николаевский_инцидент'),
    priamurye: E('Provisional_Priamurye_Government'),
    ruPriamurye: RU('Приамурский_земский_край'),
    tryapitsyn: E('Yakov_Tryapitsyn'),
    ruTryapitsyn: RU('Тряпицын,_Яков_Иванович'),
    volochayevka: E('Battle_of_Volochayevka'),
    ruVolochayevka: RU('Волочаевская_операция'),
};
const EVENTS = ['siberia-far-east-1918-1922', 'civil-war'];

module.exports = [
    term({
        id: 'japanese-siberian-intervention', ko: '일본의 시베리아 출병', en: 'Japanese intervention in Siberia', category: 'international',
        period: '1918–1922', startYear: 1918, endYear: 1922,
        definition: ['1918년부터 1922년까지 일본 제국 육군이 체코슬로바키아 군단 구출과 연합국 군수물자 보호를 명분으로 러시아 연해주와 시베리아에 군대를 보낸 군사 개입. 미국은 7천 명을 요청했고 일본 정부는 1만 2천 명 파병을 결정했지만, 실제로는 7만 명이 넘는 병력이 들어가 치타 동쪽의 항구와 주요 도시를 모두 점령했다. 다른 연합국이 1920년 물러난 뒤에도 남았다가 1922년 10월 25일 블라디보스토크에서 철수했고, 북사할린 점령은 1925년까지 이어졌다.',
            'The military intervention of 1918–1922 in which the Imperial Japanese Army sent troops into the Russian Maritime Provinces and Siberia, ostensibly to rescue the Czechoslovak Legion and guard Allied war supplies. The United States asked for 7,000 men and the Japanese government agreed to 12,000, but more than 70,000 eventually went in and occupied every port and major town east of Chita. The army stayed on after the other Allies left in 1920, withdrew from Vladivostok on 25 October 1922, and held northern Sakhalin until 1925.'],
        body: ['1918년 2월 일본 육군 참모본부와 육군성은 「시베리아 계획위원회」를 만들어, 제정 붕괴를 틈타 시베리아를 떼어 내 완충국을 세우면 러시아의 위협에서 벗어날 수 있는지 검토했다. 같은 해 1월 일본 해군은 영국 군함보다 먼저 전함 이와미와 아사히를 블라디보스토크에 보냈다. 7월 윌슨 대통령이 체코슬로바키아 군단 구출을 위한 2만 5천 명 규모 연합군의 일부로 7천 명을 요청하자, 데라우치 마사타케 내각은 의회의 격론 끝에 1만 2천 명을 보내되 일본 단독 지휘 아래 두기로 했다. 대규모 상륙은 8월 8일 시작되어 그달 말까지 1만 8천 명이 블라디보스토크에, 6천 명이 만주를 거쳐 만저우리에 들어갔고, 8월 18일 오타니 기쿠조 장군이 연합군 전체의 지휘를 맡았다. 11월 초에는 7만 명이 넘었다. 일본군은 바이칼호 서쪽으로는 가지 않았고, 연해주의 항구와 치타 동쪽의 주요 도시를 차지한 채 그리고리 세묘노프의 특별만주부대를 후원했다. 1920년까지 미쓰비시·미쓰이 같은 재벌이 블라디보스토크·하바롭스크·니콜라옙스크나아무레·치타에 사무소를 열었고, 민간인 정착민도 5만 명 넘게 들어왔다.\n\n1920년 다른 연합국이 블라디보스토크에서 물러난 뒤에도 일본군은 조선과 만주에 가까운 곳으로 공산주의가 번지는 것을 우려해 남았다. 그러나 1920년 공고타 협정으로 자바이칼에서 철수해야 했고, 이는 그해 10월 세묘노프 정권의 몰락으로 이어졌다. 일본은 니콜라옙스크 사건을 이유로 북사할린을 점령했고, 블라디보스토크의 프리아무르 임시정부를 군사적으로 지원했다. 미국과 영국의 외교 압력, 그리고 인명과 비용 때문에 커진 국내 반대 속에 가토 도모사부로 내각은 1922년 6월 24일 철수를 발표했고, 마지막 병사가 10월 25일 블라디보스토크를 떠났다. 북사할린의 일본군은 1925년 1월 일소 기본조약 체결 뒤 5월에야 물러났다. 일본 쪽 사망자는 영어 문헌에 따라 전투와 질병을 합쳐 약 5천 명, 또는 전사 1,399명과 병사 1,717명이며, 비용은 9억 엔이 넘었다. 의회는 군부가 파병 규모를 속이고 기밀비를 유용했으며 잔학 행위 소문이 돌던 운게른 같은 인물을 지원했다고 공격했고, 출병은 전시의 단결을 무너뜨려 군과 정부, 그리고 군 내부 파벌의 다툼을 불러왔다.',
            'In February 1918 the Japanese Army General Staff and the Army Ministry set up a "Siberia Planning Committee" to explore whether the Tsarist collapse offered a chance to free Japan from any future Russian threat by detaching Siberia as an independent buffer state. That January the navy had raced the battleships Iwami and Asahi to Vladivostok ahead of a British cruiser. When President Wilson asked in July for 7,000 Japanese troops as part of a 25,000-strong coalition to rescue the Czechoslovak Legion, the Terauchi Masatake cabinet, after heated debate in the Diet, agreed to send 12,000 but under Japanese command alone. Large-scale landings began on 8 August; by the end of the month 18,000 men had arrived at Vladivostok and another 6,000 had moved through Manchuria to Manzhouli, and on 18 August General Otani Kikuzo took command of all the Allied forces. By early November there were more than 70,000. The Japanese refused to go west of Lake Baikal; they held the ports of the Maritime Provinces and the main towns east of Chita and backed Grigory Semyonov’s Special Manchurian Detachment. By 1920 zaibatsu such as Mitsubishi and Mitsui had opened offices in Vladivostok, Khabarovsk, Nikolayevsk-on-Amur and Chita, bringing more than 50,000 civilian settlers.\n\nWhen the other Allies left Vladivostok in 1920, the Japanese stayed, chiefly for fear of communism spreading so close to Korea and Manchuria. The Gongota Agreement of 1920, however, obliged them to evacuate Transbaikalia, which brought down Semyonov’s regime that October. Japan occupied northern Sakhalin in retaliation for the Nikolayevsk incident and gave military support to the Provisional Priamur Government in Vladivostok. Under diplomatic pressure from the United States and Britain and growing domestic opposition to the human and economic cost, the Kato Tomosaburo cabinet announced the withdrawal on 24 June 1922, and the last soldiers left Vladivostok on 25 October. The troops on northern Sakhalin left only in May 1925, after the Soviet–Japanese Basic Convention of January 1925. Japanese deaths are given in English sources either as some 5,000 from combat and illness or as 1,399 killed and 1,717 dead of disease, and the cost exceeded 900 million yen. The Diet accused the army of misrepresenting the size of the force, misappropriating secret funds and backing figures such as Ungern, whose atrocities had reached the press; the intervention tore Japan’s wartime unity apart, setting the army against the government and reviving factional strife within the army.'],
        aliases: { ko: ['시베리아 출병'], en: ['Japanese Siberian Intervention', 'Shiberia Shuppei'] },
        people: ['woodrow-wilson', 'grigory-semyonov', 'roman-von-ungern-sternberg', 'yakov-tryapitsyn', 'william-s-graves'],
        events: EVENTS,
        sources: [S.japan, S.siberian],
        locator: 'lead; Japanese participation; Effects on Japanese politics',
    }),
    term({
        id: 'american-expeditionary-force-siberia', ko: '미국 시베리아 원정군', en: 'American Expeditionary Force, Siberia', category: 'international',
        period: '1918–1920', startYear: 1918, endYear: 1920,
        definition: ['1918년부터 1920년까지 러시아 극동에 파견된 미국 육군 부대. 윌리엄 S. 그레이브스 소장이 지휘했고 병력은 7,950명(다른 집계로 8,763명)이었다. 윌슨 대통령은 체코슬로바키아 군단 구출과 미국이 보낸 군수물자·철도 차량 보호를 명분으로 내세웠고, 부대는 시베리아 횡단 철도의 일부 구간을 지키다가 1920년 4월 1일 마지막 병력이 떠났다.',
            'The United States Army force sent to the Russian Far East in 1918–1920. Commanded by Major General William S. Graves, it numbered 7,950 officers and men (8,763 by another count). President Wilson’s stated aims were to rescue the Czechoslovak Legion and to protect the military supplies and rolling stock the United States had sent to Russia; the force guarded sections of the Trans-Siberian Railway until its last soldiers left on 1 April 1920.'],
        body: ['윌슨이 파병을 결정한 이유는 군사적인 것만큼 외교적인 것이기도 했다. 시베리아 횡단 철도에 발이 묶인 4만 명의 체코슬로바키아 군단을 구출하고, 미국이 러시아에 보낸 대량의 군수물자와 철도 차량을 지키며, 러시아인 스스로의 자치와 자위 노력을 「안정시킨다」는 것이었다. 윌슨은 카자크 약탈자나 일본군이 철도와 자원 지대의 혼란을 이용하지 못하게 하려 했다. 원정군은 미 육군 제27·제31 보병연대와 제8사단 출신 지원병으로 이루어졌다. 첫 3천 명이 1918년 8월 15~21일 블라디보스토크에 내렸고, 그레이브스는 9월 4일에야 도착했다. 연합국 철도 협정에 따라 미군은 블라디보스토크에서 우수리스크까지, 그리고 베르흐네우딘스크 부근 구간을 지켰고, 철도 운영을 위해 미국인으로 러시아 철도 봉사단을 꾸렸다.\n\n그레이브스는 임무가 미국 물자를 보호하고 군단의 철수를 돕는 데 그치며 볼셰비키와 싸우는 것은 포함되지 않는다고 보았다. 그는 「러시아 내정 불간섭」과 「완전 중립」을 선언했고, 더 적극적인 개입을 바라는 영국·프랑스·일본 지휘관들과 자주 부딪혔다. 미군 구역에서는 붉은 파르티잔을 막지 않았고 수찬 탄광 노동자들의 집회도 허용했다. 러시아어 문헌은 그 결과 연해주에 수천 명 규모의 붉은 세력이 자랐고, 일본 쪽에 기운 아타만 세묘노프가 그레이브스를 붉은 쪽 지원자로 비난했다고 쓴다. 병사들의 생활은 비참했다. 연료와 탄약, 식량이 모자랐고, 수랭식 기관총은 얼어붙었다. 19개월 동안 189명이 죽었다. 미국 문헌은 이 개입이 모든 기준에서 실패했다고 평가한다. 동부 전선은 되살아나지 않았고 물자도 지키지 못했으며 비공산주의 정부도 세워지지 않았고, 군단의 철수조차 원정군과는 별 관계가 없었다. 미 육군 참모총장 페이턴 마치는 러시아 원정을 「군사적 범죄」라고 불렀다.',
            'Wilson’s reasons were as much diplomatic as military: to rescue the 40,000 men of the Czechoslovak Legion held up along the Trans-Siberian Railroad, to protect the large stocks of military supplies and rolling stock the United States had sent to Russia, and to "steady any efforts at self-government or self defense" by the Russians themselves. He also wanted to keep Cossack marauders and the Japanese military from exploiting the chaos along the railway and in the resource-rich regions it crossed. The force drew on the US Army’s 27th and 31st Infantry Regiments and volunteers from the 8th Division. The first 3,000 men landed at Vladivostok between 15 and 21 August 1918; Graves arrived only on 4 September. Under the inter-Allied railway agreement the Americans guarded the line from Vladivostok to Ussuriysk and a section near Verkhneudinsk, and a Russian Railway Service Corps of American personnel was formed to run the railway.\n\nGraves held that the mission was to protect American property and help the Legion leave, not to fight the Bolsheviks. He proclaimed "non-interference in Russia’s internal affairs" and "complete neutrality", and clashed repeatedly with British, French and Japanese commanders who wanted a more active intervention. In the American zone the troops left the Red partisans alone and allowed meetings of the Suchan coal miners; Russian-language sources say a Red force of several thousand grew up in Primorye as a result, and that the pro-Japanese ataman Semyonov accused Graves of aiding the Reds. Conditions for the soldiers were miserable: fuel, ammunition and food ran short and water-cooled machine guns froze. In 19 months 189 men died. American sources judge that by every measure the intervention failed: the Eastern Front was not restored, the supplies were not saved, no non-Communist government took root, and even the Legion’s extrication owed little to Graves’s small force. Army Chief of Staff Peyton C. March called the Russian expeditions "a military crime".'],
        aliases: { ko: [], en: ['AEF Siberia', 'AEF in Siberia'] },
        people: ['william-s-graves', 'woodrow-wilson', 'grigory-semyonov', 'ivan-kalmykov'],
        events: EVENTS,
        sources: [S.aef, S.ruGraves, S.siberian],
        locator: 'lead; History; Results',
    }),
    term({
        id: 'nikolayevsk-incident', ko: '니콜라옙스크 사건', en: 'Nikolayevsk incident', category: 'repression',
        period: '1920', startYear: 1920, endYear: 1920,
        definition: ['1920년 아무르강 하구의 니콜라옙스크나아무레에서 야코프 트랴피친이 이끈 파르티잔 부대가 일본 수비대와 거류민, 그리고 수천 명의 러시아 주민을 죽이고 도시를 불태운 사건. 좁게는 3월 일본군과의 전투 뒤인 5월 하순 일본인 포로와 남은 수감자를 처형한 일을 가리키며, 일본은 이 사건을 북사할린 점령의 명분으로 삼았다.',
            'The mass killings of 1920 at Nikolayevsk-on-Amur, at the mouth of the Amur, in which partisans under Yakov Tryapitsyn killed the Japanese garrison and residents and thousands of Russian inhabitants and burned the town. In the narrow sense it refers to the execution of Japanese prisoners and the remaining detainees in late May, after the March fighting with the Japanese; Japan used the incident to justify its occupation of northern Sakhalin.'],
        body: ['1918년 9월부터 일본군이 주둔한 니콜라옙스크에는 1920년 초 일본 제14사단의 수비대 350명과 일본 민간인 약 450명, 백군 약 300명이 있었다. 1920년 1월 트랴피친의 파르티잔(러시아어 문헌은 3천 명)이 도시를 포위했고, 외곽의 츠니라흐 요새를 차지해 포격을 시작했다. 2월 28일 휴전에 따라 파르티잔이 입성했지만, 곧 미리 만든 명단에 따라 부유층과 유력자를 체포하고 처형하기 시작했다. 3월 12일 새벽 일본군이 파르티잔 지휘부를 기습해 전투가 벌어졌고, 15일 남은 일본군이 항복할 때까지 수비대 대부분이 전사했다. 5월 하순 일본 원군이 다가오자 트랴피친의 지휘부는 주민을 케르비로 소개하고, 수감되어 있던 일본인 포로 129명과 수감자들을 처형한 뒤 도시와 요새를 폭파하고 불태웠다. 러시아어 문헌에 따르면 주거용 건물 1,165채 가운데 35채만 남았다. 7월 7일 트랴피친과 참모들은 케르비에서 체포되어 9일 총살되었다.\n\n희생자 수는 지금도 엇갈린다. 영어 문헌이 인용한 사할린주 당국의 추산은 굶주림과 궁핍으로 죽은 사람을 포함해 지역 전체에서 적어도 1만~1만 5천 명이 사라졌다는 것이고, 재판 판결과 볼셰비키 문서는 주민의 절반이 죽었다고 적었다. 당시 일본은 일본인 희생을 부풀리고 수천 명의 러시아인 희생은 언급하지 않아, 이 사건은 오랫동안 「일본인 학살」로 잘못 알려졌다. 1920년대부터 1950년대까지 소련은 사건의 본질을 제네바 협약을 어긴 일본인 포로 처형으로 보고, 모든 책임을 「아나키스트」로 규정된 트랴피친 개인에게 돌렸다. 오늘날 여러 역사가는 도시 전체를 불태우고 수천 명을 죽인 이 일을 그 전쟁에서 유례가 없는 잔혹 행위로 본다. 일본은 사건을 이유로 북사할린을 점령해 1925년까지 머물렀는데, 러시아어 문헌은 점령이 5월의 처형보다 앞선 1920년 4월 22일에 시작되었다고 지적한다.',
            'Occupied by Japanese troops since September 1918, Nikolayevsk held at the start of 1920 a garrison of 350 men from the Japanese 14th Division, about 450 Japanese civilians and some 300 White troops. In January 1920 Tryapitsyn’s partisans (3,000 according to Russian-language sources) besieged the town, took the Chnyrrakh fortress on its outskirts and began shelling. Under a truce of 28 February the partisans entered, but they soon began arresting and executing the wealthy and influential from lists drawn up in advance. Before dawn on 12 March the Japanese attacked the partisan headquarters; in the fighting that followed most of the garrison was killed before the last Japanese surrendered on the 15th. In late May, as a Japanese relief force approached, Tryapitsyn’s command evacuated the inhabitants to Kerbi, executed the 129 Japanese prisoners and the other detainees, and blew up and burned the town and the fortress. Russian-language sources say only 35 of 1,165 residential buildings survived. On 7 July Tryapitsyn and his staff were arrested at Kerbi, and they were shot on the 9th.\n\nThe death toll is still disputed. The Sakhalin authorities, as cited in English-language sources, put losses across the region at no fewer than 10,000–15,000, counting those who died of hunger and privation; the trial verdict and Bolshevik documents spoke of half the population killed. At the time Japan exaggerated its own losses and left out the thousands of Russians killed, so the incident was long misremembered as a "massacre of the Japanese". From the 1920s to the 1950s the Soviet Union treated its essence as the shooting of Japanese prisoners in breach of the Geneva Convention and laid all the blame on Tryapitsyn, who was branded an "anarchist". Many historians today regard the burning of a whole town and the killing of thousands as cruelty without parallel in that war. Japan used the incident to occupy northern Sakhalin, where it stayed until 1925, although Russian-language sources point out that the occupation began on 22 April 1920, before the May executions.'],
        aliases: { ko: ['니콜라옙스크 학살'], en: ['Nikolaevsk incident', 'Nikolayevsk massacre'] },
        people: ['yakov-tryapitsyn'],
        events: EVENTS,
        sources: [S.nikolayevsk, S.ruNikolayevsk, S.tryapitsyn, S.ruTryapitsyn, S.japan],
        locator: 'lead; Massacre; Number of victims; Historiography',
    }),
    term({
        id: 'provisional-priamurye-government', ko: '프리아무르 임시정부', en: 'Provisional Priamurye Government', category: 'party-state',
        period: '1921–1922', startYear: 1921, endYear: 1922,
        definition: ['1921년 5월 블라디보스토크의 백군 쿠데타로 세워져 1922년 10월까지 연해주 남부를 다스린 반볼셰비키 정권. 스피리돈·니콜라이 메르쿨로프 형제가 이끌었고 일본군의 보호에 기댔으며, 소비에트 쪽은 극동공화국에 맞선 이 정권을 「검은 완충국」이라 불렀다. 1922년 여름 미하일 디테릭스가 실권을 쥐고 이름을 프리아무르 젬스키 크라이로 바꿨으나, 일본군 철수와 함께 무너졌다.',
            'The anti-Bolshevik regime set up by a White coup in Vladivostok in May 1921, which ruled southern Primorye until October 1922. Led by the brothers Spiridon and Nikolai Merkulov and dependent on Japanese protection, it was called the "Black Buffer" by the Soviet side, in contrast to the Far Eastern Republic. In the summer of 1922 Mikhail Diterikhs took power and renamed it the Priamurye Zemsky Krai, but it collapsed with the Japanese withdrawal.'],
        body: ['1921년 5월 26일 블라디보스토크에서 백군 반란군이 볼셰비키 바실리 안토노프가 이끌던 연해주 젬스트보 정부를 무너뜨렸다. 극동공화국을 인정하던 그 정부를 대신해 권력은 극동 비사회주의 단체 대회로 넘어갔고, 대회가 프리아무르 임시정부를 뽑았다. 쿠데타의 주력은 블라디미르 카펠 군대의 잔존 부대인 카펠레프치였고, 정권의 군대는 카펠과 아타만 그리고리 세묘노프의 옛 부대로 이루어진 백군 극동군이었다. 최고 대표 기관은 인민의회였다. 정부를 이끈 메르쿨로프 형제는 둘 다 옛 국가 두마 의원이었는데, 스피리돈은 영어 문헌에 따르면 농업부 관료 출신이었고 러시아어 문헌에 따르면 변호사였으며, 니콜라이는 상인이었다. 일본과 미국의 영사단이 정권을 지지했고, 일본은 연해주에 주둔한 병력으로 군사적 뒷받침도 했다. 같은 해 세묘노프가 프리아무르에서 권력을 잡으려 했지만 일본의 지원을 얻지 못해 물러났고, 카펠레프치와 세묘노프 쪽은 서로를 경멸했다. 쿠데타 직후부터 연해주에서는 볼셰비키를 중심으로 한 파르티잔 운동이 다시 번졌다.\n\n정권은 점차 하바롭스크와 블라디보스토크 북쪽의 스파스크까지 영역을 넓혔다. 그러나 파르티잔 운동을 누르지 못했고, 1922년 겨울과 봄 하바롭스크 일대에서 극동공화국 인민혁명군에 패하자 메르쿨로프 정부는 그해 여름 물러났다. 7월 23일 콜차크의 장군이었던 디테릭스가 정부 수반과 총사령관을 겸한 통치자가 되었다. 같은 7월 소집된 프리아무르 젬스키 소보르는 차르 타도를 회개하자고 호소하며 니콜라이 니콜라예비치 대공을 차르로 선포했고, 디테릭스는 영역을 프리아무르 젬스키 크라이로, 군대를 젬스카야 라티로 고쳐 불렀다. 젬스카야 라티는 9월 1일 공세에 나섰지만 10월에 거의 전멸했다. 일본군이 철수하는 가운데 10월 25일 인민혁명군이 블라디보스토크에 들어갔고, 그 직전 사조노프가 이끈 시베리아 지역주의자들이 내건 이른바 「벽보 정부」도 아무 일을 하지 못했다. 영어 문헌은 아나톨리 페펠랴예프가 장악했던 아얀-마이스키 지역이 1923년 6월 항복한 것을 러시아 내전의 끝으로 본다.',
            'On 26 May 1921 White insurgents in Vladivostok overthrew the Primorye zemstvo government headed by the Bolshevik Vasily Antonov, which recognised the Far Eastern Republic. Power passed to a congress of non-socialist organisations of the Far East, which elected the Provisional Priamurye Government. The coup was carried out by the Kappelevtsy, remnants of Vladimir Kappel’s army, and the regime’s forces, the White Far Eastern Army, were drawn from the former troops of Kappel and of Ataman Grigory Semyonov; its highest representative body was a People’s Assembly. The Merkulov brothers who led it had both sat in the State Duma; Spiridon was, according to English sources, a former official of the Ministry of Agriculture and, according to Russian sources, a lawyer, while Nikolai was a merchant. The Japanese and American consular corps backed the regime, and Japan supported it militarily with the troops it had stationed in Primorye. Semyonov tried to take power in Priamurye later in 1921 but got no Japanese backing and withdrew; the Kappelevtsy and Semyonov’s men despised each other. Almost immediately after the coup a partisan movement, led above all by the Bolsheviks, revived across Primorye.\n\nThe regime gradually extended its territory to Khabarovsk and to Spassk, north of Vladivostok. But it could not master the partisans, and after its troops were beaten by the Far Eastern Republic’s People’s Revolutionary Army around Khabarovsk in the winter and spring of 1922, the Merkulov government resigned that summer. On 23 July Diterikhs, one of Kolchak’s generals, became ruler, combining the posts of head of government and commander-in-chief. The Priamurye Zemsky Sobor, convened that July, called on Russians to repent for the overthrow of the Tsar and proclaimed Grand Duke Nikolai Nikolayevich tsar; Diterikhs renamed the territory the Priamurye Zemsky Krai and the army the Zemskaya Rat. The Zemskaya Rat went on the offensive on 1 September but was all but destroyed in October. As the Japanese withdrew, the People’s Revolutionary Army entered Vladivostok on 25 October; the so-called "placard government" of Siberian regionalists under Sazonov, set up at the last moment, achieved nothing. English sources treat the surrender of the Ayano-Maysky district, held by Anatoly Pepelyayev, in June 1923 as the end of the Russian Civil War.'],
        aliases: { ko: ['검은 완충국', '프리아무르 젬스키 크라이'], en: ['Provisional Priamur Government', 'Priamurye Zemsky Krai', 'Black Buffer'] },
        people: ['mikhail-diterikhs', 'grigory-semyonov', 'vladimir-kappel', 'anatoly-pepelyayev'],
        events: EVENTS,
        sources: [S.priamurye, S.ruPriamurye, S.siberian],
        locator: 'lead; History; Ликвидация «Чёрного буфера»',
    }),
    term({
        id: 'battle-of-volochayevka', ko: '볼로차옙카 전투', en: 'Battle of Volochayevka', category: 'international',
        period: '1922', startYear: 1922, endYear: 1922,
        definition: ['1922년 2월 하바롭스크 서쪽 아무르 철도의 볼로차옙카역 부근에서 바실리 블류헤르가 지휘한 극동공화국 인민혁명군이 빅토린 몰차노프의 백군 진지를 돌파한 전투. 2월 10일 첫 공격은 실패했지만 12일 두 번째 공격으로 이윤코란 언덕을 차지했고, 백군은 하바롭스크를 버리고 연해주로 물러났다. 이 승리로 전략적 주도권이 인민혁명군으로 넘어갔다.',
            'The battle of February 1922 near Volochayevka station on the Amur Railway, west of Khabarovsk, in which the Far Eastern Republic’s People’s Revolutionary Army under Vasily Blyukher broke through the White positions held by Viktorin Molchanov. The first assault on 10 February failed, but a second on the 12th took Iyun-Koran hill, and the Whites abandoned Khabarovsk and fell back into Primorye. The victory passed the strategic initiative to the People’s Revolutionary Army.'],
        body: ['1921년 11월 일본의 지원을 받은 백군이 블라디보스토크에서 철도와 우수리강을 따라 북진해 하바롭스크를 점령했다. 12월 28일 하바롭스크 서쪽 110킬로미터 지점에서 처음 저지된 백군은 볼로차옙카로 물러나 진지를 쌓았다. 아무르강과 툰구스카강 사이 18킬로미터에 걸친 방어선의 중심은 평원을 내려다보는 이윤코란 언덕이었고, 사람 키 높이의 참호와 얼음 방벽, 숨긴 기관총좌, 5~6겹의 철조망이 둘러쳐졌다. 인민혁명군은 공격 전 현지 파르티잔과 공산당원 1천 명으로 보충되었다. 영어 문헌에 따르면 병력은 7,600명에 기관총 수백 정, 야포 30문, 경전차 두 대였고, 백군은 4,950명에 포 13문이었다. 러시아어 문헌은 인스카야 집단군이 언덕을 공격하는 동안 자바이칼 집단군이 남쪽으로 돌아 백군 후방을 위협하는 작전이었다고 쓴다.\n\n2월 10일 영하 30도의 혹한과 깊은 눈 속에서 시작된 첫 공격은 실패했다. 장갑열차를 쓸 수 없고 포병도 뒤처진 채 보병이 전차 두 대의 지원만 받으며 걸어서 돌격했고, 철조망을 끊을 도구가 모자라 병사들은 총검과 군도, 개머리판으로 철사를 끊었다. 러시아어 문헌에 따르면 인민혁명군은 전사·부상·동상으로 480명을 잃었고 전차 두 대도 모두 잃었다. 블류헤르는 하루 동안 부대를 재편해 12일 오전 8시 철도를 따라 다시 공격했고, 장갑열차의 지원 속에 정오 무렵 볼로차옙카를 완전히 차지했다. 같은 날 자바이칼 집단군은 몰차노프의 예비대를 깨뜨렸다. 지친 인민혁명군은 백군을 포위하지 못했고, 하바롭스크는 영어 문헌에 따르면 2월 13일, 러시아어 문헌에 따르면 14일 싸움 없이 넘어갔다. 이 전투는 내전 가요 「골짜기와 언덕을 넘어」의 가사 「스파스크의 돌격의 밤들, 볼로차옙카의 날들」로 기억되며, 1928년 전장에 기념관과 박물관이 세워졌다.',
            'In November 1921 White forces backed by Japan advanced north from Vladivostok along the railway and the Ussuri River and took Khabarovsk. Checked for the first time on 28 December, 110 kilometres west of Khabarovsk, they fell back to Volochayevka and dug in. The 18-kilometre line between the Amur and Tunguska rivers centred on Iyun-Koran hill, which commanded the open plain, and was fortified with full-depth trenches, ice ramparts, hidden machine-gun nests and five or six rows of barbed wire. Before the attack the People’s Revolutionary Army was reinforced with local partisans and 1,000 Communists. English sources give it 7,600 men with hundreds of machine guns, 30 field guns and two light tanks, against 4,950 Whites with 13 guns. Russian sources describe a plan in which the Inskaya group stormed the hill while the Transbaikal group swung south to threaten the White rear.\n\nThe first assault, launched on 10 February in −30 °C cold and deep snow, failed. The infantry attacked on foot with only the two tanks in support, unable to use the armoured trains and with the artillery left behind, and with too few tools the men cut the wire with bayonets and sabres and beat it down with rifle butts. According to Russian sources the People’s Revolutionary Army lost 480 men killed, wounded and frozen, and both tanks. Blyukher regrouped for a day and attacked again along the railway at 8 a.m. on the 12th, and with armoured-train support Volochayevka was fully taken by about noon. The same day the Transbaikal group routed Molchanov’s reserve. The exhausted Reds could not encircle the Whites, and Khabarovsk fell without a fight on 13 February according to English sources, or the 14th according to Russian ones. The battle is remembered in the civil-war song "Through Valleys and over Hills" with the line "the storming nights of Spassk, the days of Volochayevka", and a memorial and museum were opened on the battlefield in 1928.'],
        aliases: { ko: ['볼로차옙카 작전'], en: ['Volochayevka operation', 'Battle of Volochaevka'] },
        people: ['vasily-blyukher', 'postyshev'],
        events: EVENTS,
        sources: [S.volochayevka, S.ruVolochayevka],
        locator: 'lead; Battle; Ход сражения; Памятники',
    }),
];
