// Person cards for the central-asia-1917-1924 event (revolution and war in
// Central Asia, with the Soviet Republic of Gilan), see lib.js person().
// Excerpts are verbatim from the cited pages. Bodies with no catalog
// affiliation (the Jungle movement and the Gilan republic, the Alash party and
// Alash Orda, the Basmachi, the Emirate of Bukhara, the Khanate of Khiva) stay
// unresolved. Collections proposed in the hand-off report, not here.
const { person } = require('../lib');

const E = t => 'https://en.wikipedia.org/wiki/' + encodeURI(t.replace(/ /g, '_'));
const RU = t => 'https://ru.wikipedia.org/wiki/' + encodeURI(t.replace(/ /g, '_'));
const UZ = t => 'https://uz.wikipedia.org/wiki/' + encodeURI(t.replace(/ /g, '_'));
const S = {
    kuchik: E('Mirza Kuchik Khan'),
    kuchikRu: RU('Мирза Кучек-хан'),
    jungle: E('Jungle Movement of Gilan'),
    pssr: E('Persian Socialist Soviet Republic'),
    gilanRu: RU('Гилянская советская социалистическая республика'),
    bukeikhanov: E('Alikhan Bukeikhanov'),
    bukeikhanovRu: RU('Букейханов, Алихан Нурмухамедович'),
    ibrahim: E('Ibrahim Bek'),
    ibrahimRu: RU('Ибрагим-бек'),
    alimKhan: E('Sayyid Mir Muhammad Alim Khan'),
    alimKhanRu: RU('Сеид Алим-хан'),
    alimKhanUz: UZ('Said Olimxon'),
    kolesov: RU('Колесов, Фёдор Иванович'),
    kolesovUz: UZ('Kolesov voqeasi'),
    kokand: E('Turkestan Autonomy'),
    junaid: E('Junaid Khan (Basmachi leader)'),
    junaidRu: RU('Джунаид-хан'),
    junaidUz: UZ('Junaydxon'),
};

const unaffiliated = card => ({
    ...card,
    activities: card.activities.map(a => (a.affiliationId ? a : { ...a, affiliationStatus: 'unresolved', relation: 'unresolved' })),
});

const BUKHARA = { code: 'uzbekistan', label: { ko: '부하라 에미르국', en: 'Emirate of Bukhara' } };

module.exports = [
    unaffiliated(person({
        id: 'mirza-kuchik-khan', groupId: 'world-interwar',
        given: ['미르자', 'Mirza'], family: ['쿠착 칸', 'Kuchik Khan'], nativeName: 'میرزا كوچک خان', years: '1880–1921',
        citizenship: 'iran', origin: 'iran',
        epithet: ['길란의 정글리 운동을 이끌고 1920년 길란 소비에트 공화국을 선포한 이란의 혁명가',
            'Iranian revolutionary who led the Jungle movement of Gilan and proclaimed the Soviet Republic of Gilan in 1920'],
        bio: ['1880년 라슈트에서 길란 상인의 아들로 태어나 이란 입헌혁명에 가담했고, 1909년 테헤란을 점령한 입헌파 부대의 하급 지휘관이었다. 1914~1915년 길란의 숲에서 정글리 운동을 일으켜 지방 자치, 중앙정부의 부패 척결, 외세 간섭 중단과 토지 개혁을 요구했다. 1920년 소비에트 함대가 엔젤리에 들어오자 내정 불간섭을 조건으로 손잡고 6월 5일 길란 소비에트 공화국을 선포해 그 수반이 되었으나, 토지 재분배를 거부해 공산주의자들과 갈라섰다. 1921년 5월 정부 수반으로 돌아왔지만 소련이 지원을 끊은 뒤 레자 칸의 정부군에 패했고, 탈레시 산지로 달아나다 동상으로 숨졌다. 잘린 머리는 라슈트에 내걸렸다.',
            'Born in Rasht in 1880, the son of a Gilani merchant, he joined the Iranian Constitutional Revolution and in 1909 was a junior commander of the constitutionalist force that took Tehran. In 1914–1915 he launched the Jungle movement in the forests of Gilan, demanding provincial autonomy, an end to central government corruption and foreign interference, and land reform. When a Soviet flotilla entered Enzeli in 1920 he agreed to cooperate on condition of non-interference, proclaimed the Soviet Republic of Gilan on 5 June and became its head, but split with the communists over his refusal to redistribute land. He returned as head of government in May 1921, but after the Soviets withdrew their support he was defeated by Reza Khan’s government troops and died of frostbite while fleeing into the Talesh mountains. His severed head was displayed in Rasht.'],
        fate: ['killed', '도피 중 동사', 'Froze to death while fleeing'],
        aliases: { ko: ['미르자 쿠체크 칸', '미르자 쿠치크 칸', '쿠체크 칸'], en: ['Mirza Kuchak Khan', 'Mirza Kuchek Khan', 'Mirza Koochek Khan', 'Kuchak Khan', 'Kuchek Khan'] },
        sources: [S.kuchik, S.kuchikRu, S.jungle, S.pssr, S.gilanRu],
        facts: {
            years: { claim: '1880–1921', locator: 'lead', excerpt: 'October 12, 1880 – December 2, 1921' },
            citizenship: { claim: 'Iranian revolutionary, head of the Gilan republic', locator: 'lead', excerpt: 'was an Iranian revolutionary leader and the president of the Gilan Socialist Soviet Republic' },
            nationalOrigin: { claim: 'born in Rasht to a Gilani merchant', locator: 'Early life', excerpt: 'in the city of Rasht in northern Iran in 1880. His father was a merchant from Gilan.' },
            bio: [
                { claim: 'took part in the Constitutional Revolution and was wounded', locator: 'Political activities', excerpt: 'He was injured during the Constitutionalist war' },
                { claim: 'junior commander in the 1909 capture of Tehran', locator: 'Political activities', excerpt: 'Mirza Kuchak Khan was one of the lower ranked commanders of the force that invaded the capital from the North' },
                { claim: 'uprising began in 1914 and lasted until 1921', locator: 'lead', excerpt: 'This uprising started in 1914 and remained active against internal and foreign enemies until 1921' },
                { claim: 'Jungle movement launched in October 1915 with Kuchik Khan among its founders', locator: 'Origins and beliefs (1915)', source: S.jungle, excerpt: 'and Mirza Kuchik Khan, an experienced activist in the pro-democracy and nationalist Constitutional Revolution, among others, collectively launched the Jangal movement in the forests of Kasma, Gilan.' },
                { claim: 'demands of the movement', locator: 'Origins and beliefs (1915)', source: S.jungle, excerpt: 'They demanded autonomous status for the province, an end to central government corruption, an end to foreign interference in affairs of local peoples, and land reform.' },
                { claim: 'conditions for cooperation with the Soviets', locator: 'Socialist Republic of Gilan', excerpt: 'Mirza Kuchak Khan agreed to cooperate with the Soviet revolutionaries on some conditions including the announcement of the Socialist Republic of Gilan (also known as The Red Republic of the Jungle) under his leadership and lack of any direct intervention by the Soviets in the internal affairs of the republic.' },
                { claim: 'republic proclaimed on 5 June 1920', locator: 'Resumption of hostilities and Gilan SSR (1918–20)', source: S.jungle, excerpt: 'The 11th Army captured Rasht on the 4 June and the Jangalis subsequently proclaimed the Socialist Soviet Republic of Gilan on 5 June.' },
                { claim: 'appointed head of the republic', locator: 'История', source: S.gilanRu, excerpt: 'Главой республики был назначен Кучек-хан' },
                { claim: 'no land redistribution, split with the communists', locator: 'Declaration of the republic', source: S.pssr, excerpt: 'The republic did not redistribute land to poor peasants, to the dismay of the more radical forces of the Jangal movement.' },
                { claim: 'returned to head the government in May 1921', locator: 'Падение республики', source: S.gilanRu, excerpt: 'Кучек-хан, опиравшийся на помещиков и духовенство, вновь возглавил правительство республики в мае 1921 году.' },
                { claim: 'Soviets withdrew support; defeated by Reza Khan', locator: 'Socialist Republic of Gilan', excerpt: 'the Soviets decided not to further support the Socialist Republic of Gilan and as a result the government forces led by colonel Reza Khan (the future Reza Shah) overran the dispersed forces of the Jungle Republic.' },
                { claim: 'died of frostbite in the Talesh mountains', locator: 'Mirza\'s death', excerpt: 'left alone in Talesh mountains around "Masal", both died of frostbite.' },
                { claim: 'head displayed in Rasht', locator: 'Mirza\'s death', excerpt: 'his head was displayed in Rasht' },
            ],
        },
        activities: [
            { functionId: 'political-leadership', affiliationId: null, startYear: 1914, endYear: 1921, primary: true, claim: 'Founder and leader of the Jungle movement, no catalog affiliation', locator: 'lead', excerpt: 'He was the founder of a revolutionary movement based in the forests of Gilan in northern Iran that became known as the Nehzat-e Jangal (The Jungle Movement).' },
            { functionId: 'government', affiliationId: null, startYear: 1920, endYear: 1921, source: S.kuchikRu, claim: 'Head of the provisional government of the Gilan republic, no catalog affiliation', locator: 'Биография', excerpt: 'С июня по июль 1920 года и с мая по сентябрь 1921 года стоял во главе временного правительства этого государственного образования' },
        ],
        career: [
            ['1909', '입헌파 부대 하급 지휘관으로 테헤란 점령에 참가', 'Junior commander in the constitutionalist capture of Tehran'],
            ['1914–1921', '길란 정글리 운동 지도자', 'Leader of the Jungle movement of Gilan'],
            ['1920', '길란 소비에트 공화국 임시정부 수반', 'Head of the provisional government of the Soviet Republic of Gilan'],
            ['1921', '길란 공화국 임시정부 수반 복귀', 'Again head of the provisional government of the Gilan republic'],
        ],
    })),
    unaffiliated(person({
        id: 'alikhan-bukeikhanov', groupId: 'bolshevik',
        given: ['알리칸', 'Alikhan'], family: ['부케이하노프', 'Bukeikhanov'], nativeName: 'Әлихан Бөкейхан', years: '1866–1937',
        citizenship: { code: 'soviet', label: { ko: '러시아 제국 → 소련', en: 'Russian Empire → Soviet Union' } }, origin: 'kazakhstan',
        epithet: ['알라시 당을 세우고 1917~1920년 알라시 오르다 정부를 이끈 카자흐 정치가',
            'Kazakh politician who founded the Alash party and led the Alash Orda government in 1917–1920'],
        bio: ['1866년(1870년 설도 있다) 세미팔라틴스크주에서 태어나 옴스크 기술학교와 상트페테르부르크 임업대학을 마쳤고, 아바이 쿠난바예프의 첫 전기를 썼다. 1905년 입헌민주당(카데트)에 들어가 1906년 국가 두마 의원이 되었고, 비보르크 호소문에 서명해 투옥된 뒤 1917년까지 사마라에서 유형 생활을 했다. 1917년 임시정부의 투르가이주 위원이 되었으나 카자흐 자치 문제로 카데트와 갈라서 알라시 당을 세웠고, 그해 알라시 오르다 정부 의장으로 뽑혔다. 1919년 말까지 시베리아의 백군 정부들 편에 섰다가 소비에트 권력과 타협했고, 모스크바에서 출판 일을 하다 1937년 총살되었다. 1989년 복권되었다.',
            'Born in Semipalatinsk Oblast in 1866 (some sources say 1870), he graduated from the Omsk Technical School and the Saint Petersburg Forestry Institute and wrote the first biography of Abay Kunanbayev. He joined the Constitutional Democrats (Kadets) in 1905, entered the State Duma in 1906 and, after signing the Vyborg Manifesto, was imprisoned and then lived in exile in Samara until 1917. Appointed the Provisional Government’s commissioner for Turgay Oblast in 1917, he broke with the Kadets over Kazakh autonomy, founded the Alash party and that year was elected head of the Alash Orda government. He sided with the White governments of Siberia until late 1919, then came to terms with Soviet power, worked in publishing in Moscow and was shot in 1937. He was rehabilitated in 1989.'],
        fate: ['executed', '총살', 'Executed by shooting'],
        aliases: { ko: ['알리한 부케이하노프', '알리한 보케이하노프', '얼리한 뵈케이한'], en: ['Alikhan Bokeikhanov', 'Alikhan Bokeikhan', 'Älihan Bökeihan'] },
        sources: [S.bukeikhanov, S.bukeikhanovRu],
        facts: {
            years: { claim: '1866–1937', locator: 'lead', excerpt: '5 March 1866 – 27 September 1937' },
            citizenship: { claim: 'born in the Russian Empire, died in the USSR', locator: 'преамбула', source: S.bukeikhanovRu, excerpt: 'Токраунская волость, Каркаралинский уезд, Семипалатинская область, Российская империя — 27 сентября 1937, Бутырская тюрьма, Москва, СССР' },
            nationalOrigin: { claim: 'born into a Kazakh family', locator: 'Early life', excerpt: 'Alikhan Bukeikhanov was born into a Kazakh Muslim family on 5 March 1866' },
            bio: [
                { claim: 'born 1866 or 1870 in Semipalatinsk Oblast', locator: 'Происхождение и детство', source: S.bukeikhanovRu, excerpt: 'Алихан Букейханов родился 5 марта 1866 или 1870 года в ауле № 7 Токраунской волости Каркаралинского уезда, Семипалатинской области.' },
                { claim: 'Omsk Technical School and Forestry Institute', locator: 'Early life', excerpt: 'Bukeikhanov graduated from the Russian-Kazakh School and Omsk Technical School in 1890. He later studied at the Saint Petersburg Forestry Institute, where he graduated from the Faculty of Economics in 1894.' },
                { claim: 'first biographer of Abay', locator: 'Early life', excerpt: 'Bukeikhanov was the first biographer of Abay Kunanbayev' },
                { claim: 'joined the Kadets in 1905', locator: 'Political life', excerpt: 'In 1905, Bukeikhanov\'s political activism began when he joined the Constitutional Democratic Party.' },
                { claim: 'Duma 1906, Vyborg petition', locator: 'Political life', excerpt: 'He was elected to the State Duma of the Russian Empire as a member of that party in 1906 and signed the Vyborg petition to protest the dissolution of the Duma by the tsar.' },
                { claim: 'three months in prison for the Vyborg appeal', locator: 'Депутат Государственной думы', source: S.bukeikhanovRu, excerpt: 'За подписание воззвания в конце 1907 года приговорён вместе с другими подписантами к 3 месяцам тюрьмы' },
                { claim: 'exile in Samara 1908–1917', locator: 'Political life', excerpt: 'In 1908, he was arrested again and exiled in Samara until 1917.' },
                { claim: 'commissioner of Turgay Oblast, March 1917', locator: 'Author of the idea of the First Kazakh Republic', excerpt: 'On 19 March 1917, he was appointed as the Provisional Government Commissioner of Turgay Oblast.' },
                { claim: 'broke with the Kadets over Kazakh autonomy', locator: 'С 1917 года', source: S.bukeikhanovRu, excerpt: 'Но его пути с кадетами разошлись после Февральской революции, поскольку он перестал находить поддержку среди них в самом главном вопросе — предоставление автономии казахскому народу' },
                { claim: 'founder of the Alash party', locator: 'преамбула', source: S.bukeikhanovRu, excerpt: 'Основатель и один из лидеров партии «Алаш».' },
                { claim: 'elected head of the Alash Orda government in 1917', locator: 'Author of the idea of the First Kazakh Republic', excerpt: 'After the October Revolution, he was elected in 1917 as president of the Alash Orda government of Alash Autonomy.' },
                { claim: 'with the Siberian governments until late 1919', locator: 'С 1917 года', source: S.bukeikhanovRu, excerpt: 'В гражданской войне Букейханов и алашординцы были по «ту сторону баррикад» вместе с сибирскими правителями почти до конца 1919 года' },
                { claim: 'publishing work in Moscow 1922–1927', locator: 'С 1917 года', source: S.bukeikhanovRu, excerpt: 'С 1922 по 1927 годы был литературным сотрудником Казахской секции Центрального издательства народов СССР в Москве.' },
                { claim: 'sentenced and shot on 27 September 1937', locator: 'С 1917 года', source: S.bukeikhanovRu, excerpt: '27 сентября 1937 года осужден ВКВС за принадлежность к «террористической организации» и в тот же день расстрелян' },
                { claim: 'rehabilitated in 1989', locator: 'Political life', excerpt: 'It was not until 1989 that the Soviet authorities rehabilitated him.' },
            ],
        },
        activities: [
            { functionId: 'political-leadership', affiliationId: null, startYear: 1917, endYear: 1920, primary: true, claim: 'Leader of the Alash party and the Alash Orda government, no catalog affiliation', locator: 'lead', excerpt: 'who led the Alash party and the provisional government of Alash Orda from 1917 to 1920' },
            { functionId: 'political-leadership', affiliationId: 'russian-kadets', relation: 'membership', startYear: 1905, endYear: 1917, source: S.bukeikhanovRu, claim: 'Member of the Constitutional Democratic Party 1905–1917', locator: 'Член партии кадетов', excerpt: 'С 1905 по 1917 год Букейханов являлся членом и сторонником Конституционно-демократической партии (партии кадетов).' },
        ],
        career: [
            ['1895–1897', '옴스크 카자흐 아동 학교 수학 교사', 'Mathematics teacher at the Omsk school for Kazakh children'],
            ['1906', '제1대 국가 두마 의원', 'Member of the First State Duma'],
            ['1908–1917', '사마라 유형', 'Exile in Samara'],
            ['1917', '러시아 임시정부 투르가이주 위원', 'Provisional Government commissioner for Turgay Oblast'],
            ['1917–1920', '알라시 오르다 정부 의장', 'Head of the Alash Orda government'],
            ['1922–1927', '소련 중앙민족출판사 카자흐 분과 문학 편집원', 'Literary staff member of the Kazakh section of the Central Publishing House of the Peoples of the USSR'],
        ],
    })),
    unaffiliated(person({
        id: 'ibrahim-bek', groupId: 'world-interwar',
        given: ['', ''], family: ['이브라힘 벡', 'Ibrahim Bek'], nativeName: 'Ibrohimbek Laqay', years: '1889–1931',
        citizenship: BUKHARA, origin: { code: 'uzbekistan', label: { ko: '우즈베크인 (로카이 부족)', en: 'Uzbek (Lakai tribe)' } },
        epithet: ['부하라 에미르의 복위를 내걸고 동부 부하라에서 싸운 로카이 부족 출신의 바스마치 지도자',
            'Lakai tribal chief who fought for the restoration of the Emir of Bukhara as the leading Basmachi commander in eastern Bukhara'],
        bio: ['1889년 무렵 부하라 에미르국 코크타시 마을에서 우즈베크 로카이 부족 장로의 막내아들로 태어났다. 1920년 부족의 벡이 되어 에미르 사이드 알림 칸을 섬겼고, 에미르가 망명한 뒤 그의 복위를 내걸고 동부 부하라의 여러 부족을 모아 바스마치를 이끌었다. 이슬람 보수주의를 내세워 자디드를 대열에서 몰아냈고, 엔베르 파샤를 의심해 한때 체포했다. 1926년 아프가니스탄으로 물러난 뒤에도 국경 너머로 습격을 이어 갔고, 그곳에서 아프가니스탄 정부군과도 싸웠다. 1931년 6월 소련 영내의 카피르니간강을 건너다 사로잡혀 타슈켄트로 압송되었고, 8월 31일 총살되었다. 2021년 우즈베키스탄 대법원이 복권했다.',
            'Born around 1889 in the village of Koktash in the Emirate of Bukhara, the youngest son of an elder of the Uzbek Lakai tribe, he became bek of his tribe in 1920 and entered the service of Emir Said Alim Khan. After the emir fled he rallied the tribes of eastern Bukhara and led the Basmachi in the name of the emir’s restoration. Championing Islamic conservatism, he drove the Jadids from the movement’s ranks and was so suspicious of Enver Pasha that he once arrested him. After withdrawing to Afghanistan in 1926 he kept raiding across the border and also fought Afghan government troops. Captured while crossing the Kafirnigan River on Soviet territory in June 1931, he was taken to Tashkent and shot on 31 August. Uzbekistan’s Supreme Court rehabilitated him in 2021.'],
        fate: ['executed', '총살', 'Executed by shooting'],
        aliases: { ko: ['이브라힘 벡 로카이', '이브라김 베크', '이브로힘벡'], en: ['Ibrahim Bek Lakai', 'Ibrahimbek Chaqabayev', 'Ibragim-bek'] },
        sources: [S.ibrahim, S.ibrahimRu],
        facts: {
            years: { claim: '1889–1931', locator: 'lead', excerpt: '1889 – 31 August 1931' },
            citizenship: { claim: 'subject of the Emirate of Bukhara', locator: 'Biography', excerpt: 'Ibrahim Bek was born around 1889 in the Emirate of Bukhara.' },
            nationalOrigin: { claim: 'Uzbek of the Lakai tribe', locator: 'Biography', excerpt: 'He hailed from the Lakai tribe, a group of Uzbeks distinguished by their tribal and regional identity.' },
            bio: [
                { claim: 'son of the elder of Koktash, of the Uzbek Lakai tribe', locator: 'Биография', source: S.ibrahimRu, excerpt: 'Родился в семье аксакала (старосты) кишлака Кокташ Чакобая, происходившего из узбекского племени локай' },
                { claim: 'youngest son', locator: 'Биография', source: S.ibrahimRu, excerpt: 'Ибрагим-бек был младшим из сыновей.' },
                { claim: 'became bek of his tribe in 1920 and served the emir', locator: 'Биография', source: S.ibrahimRu, excerpt: 'В 1920 году, став беком своего племени, поступил на службу к эмиру Бухары Сейид Алим-хану' },
                { claim: 'united the tribes against the Bolsheviks', locator: 'Биография', source: S.ibrahimRu, excerpt: 'Ибрагим-бек достиг определённых военных успехов, объединяя разнородные племена (до половины всех басмачей региона)' },
                { claim: 'fought for the restoration of the emir 1921–1925', locator: 'Биография', source: S.ibrahimRu, excerpt: 'В 1921—1925 годы Ибрагим-бек возглавил вооружённую борьбу за возвращение на престол свергнутого эмира Бухары Сеида Алим-хана.' },
                { claim: 'Islamic conservative ideology', locator: 'Biography', excerpt: 'Unlike secular, nationalist, or pan-Turkist factions within the Basmachi movement, Ibrahim Bek presented an Islamic conservative ideology' },
                { claim: 'expelled the Jadids', locator: 'Biography', excerpt: 'Ibrahim Bek eventually expelled the jadids from within the Basmachi ranks and actively fought against Enver Pasha.' },
                { claim: 'suspicious of Enver Pasha, arrested him', locator: 'Биография', source: S.ibrahimRu, excerpt: 'Ибрагим-бек отнёсся к нему с подозрением и даже взял под арест.' },
                { claim: 'withdrew to Afghanistan by June 1926', locator: 'Ставка в Афганистане', source: S.ibrahimRu, excerpt: 'к июню 1926 года был разгромлен и вынужден снова отступить в Афганистан' },
                { claim: 'raids from Afghanistan', locator: 'Biography', excerpt: 'Between 1926 and 1931, Ibrahim Bek led raids into Uzbekistan and Tajikistan.' },
                { claim: 'fought Afghan government forces', locator: 'Сражения с регулярными формированиями афганской армии', source: S.ibrahimRu, excerpt: 'Одновременно вёл почти непрерывные боевые действия с боевыми отрядами пуштунов, направленными против него новым правителем Афганистана Надир-шахом.' },
                { claim: 'captured crossing the Kafirnigan on 23 June 1931', locator: 'Пленение и казнь', source: S.ibrahimRu, excerpt: 'В бою 23 июня 1931 года Ибрагим-бек был пленён специальным отрядом ОГПУ под командованием Мукума Султанова во время переправы через реку Кафирниган' },
                { claim: 'taken to Tashkent', locator: 'Пленение и казнь', source: S.ibrahimRu, excerpt: 'Под конвоем был доставлен в Ташкент' },
                { claim: 'shot after sentencing', locator: 'Пленение и казнь', source: S.ibrahimRu, excerpt: 'Сразу же после оглашения приговора был расстрелян.' },
                { claim: 'rehabilitated in 2021', locator: 'Реабилитация', source: S.ibrahimRu, excerpt: 'Среди реабилитированных — курбаши Ибрагимбек Чакабоев.' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: null, startYear: 1920, endYear: 1931, primary: true, claim: 'Basmachi commander, no catalog affiliation', locator: 'lead', excerpt: 'was an Uzbek leader in the Basmachi movement, a liberation movement in Central Asia, which fought against the Red Army' },
        ],
        career: [
            ['1920', '로카이 부족의 벡, 부하라 에미르 휘하 복무', 'Bek of the Lakai tribe in the service of the Emir of Bukhara'],
            ['1921–1925', '에미르 복위를 위한 동부 부하라 무장 투쟁 지휘', 'Led the armed struggle in eastern Bukhara for the emir’s restoration'],
            ['1926–1931', '아프가니스탄을 근거지로 소련 영내 습격', 'Raids into Soviet territory from bases in Afghanistan'],
        ],
    })),
    unaffiliated(person({
        id: 'said-alim-khan', groupId: 'world-interwar',
        given: ['사이드', 'Said'], family: ['알림 칸', 'Alim Khan'], nativeName: 'Said Olimxon', years: '1880–1944',
        citizenship: BUKHARA, origin: { code: 'uzbekistan', label: { ko: '우즈베크인 (망기트 왕조)', en: 'Uzbek (Manghit dynasty)' } },
        epithet: ['1920년 붉은 군대에 쫓겨 아프가니스탄으로 망명한 부하라 에미르국의 마지막 에미르',
            'Last Emir of Bukhara, driven into exile in Afghanistan by the Red Army in 1920'],
        bio: ['1880년 부하라에서 에미르 압둘아하드 칸의 아들로 태어나 열세 살에 상트페테르부르크로 보내져 니콜라이 사관학교에서 3년간 통치와 군사를 배웠고, 돌아와 나사프와 카르마나의 총독을 지냈다. 1911년 망기트 왕조의 12대이자 마지막 에미르가 되었다. 즉위 초에는 뇌물과 자의적 징세를 금하는 개혁을 내걸었으나 곧 전통파의 손을 들었고, 1917년 이후 청년부하라인 등 개혁파를 탄압했다. 1918년 3월 콜레소프가 이끈 볼셰비키의 공격을 물리쳤지만, 1920년 8월 말 부하라 작전 중 두샨베를 거쳐 카불로 달아났다. 망명지에서 영국과 손잡고 권력을 되찾으려 했고 바스마치를 지원했다고도 하며, 1944년 카불에서 숨졌다.',
            'Born in Bukhara in 1880, the son of Emir Abdulahad Khan, he was sent at thirteen to Saint Petersburg, where he spent three years at the Nicholas Cadet Corps studying government and military affairs, and on his return governed Nasaf and Karmana. In 1911 he became the twelfth and last emir of the Manghit dynasty. He began his reign with reforms against bribery and unauthorised taxation, but soon sided with the traditionalists, and after 1917 he repressed the reformers, the Young Bukharans among them. He repulsed the Bolshevik attack led by Kolesov in March 1918, but during the Bukhara operation at the end of August 1920 he fled via Dushanbe to Kabul. In exile he cooperated with the British in the hope of regaining power and is said to have supported the Basmachi; he died in Kabul in 1944.'],
        fate: ['exile', '망명지에서 사망', 'Died in exile'],
        aliases: { ko: ['사이드 미르 무함마드 알림 칸', '무함마드 알림 칸', '세이드 알림 칸'], en: ['Sayyid Mir Muhammad Alim Khan', 'Mohammed Alim Khan', 'Seyid Alim Khan'] },
        sources: [S.alimKhan, S.alimKhanRu, S.alimKhanUz],
        facts: {
            years: { claim: '1880–1944 (en: died 28 April, ru: 5 May 1944)', locator: 'lead', excerpt: '3 January 1880 – 28 April 1944' },
            citizenship: { claim: 'ruler of the Emirate of Bukhara', locator: 'lead', excerpt: 'was the last emir of the Uzbek Manghit dynasty, rulers of the Emirate of Bukhara in Central Asia' },
            nationalOrigin: { claim: 'Uzbek, of the Manghit dynasty', locator: 'преамбула', source: S.alimKhanRu, excerpt: 'Представитель узбекского рода и династии Мангытов.' },
            bio: [
                { claim: 'son of Emir Abdulahad Khan', locator: 'Биография', source: S.alimKhanRu, excerpt: 'Его отцом был тогдашний эмир Бухары — Сеид Абдулахад-хан' },
                { claim: 'sent to Saint Petersburg at thirteen', locator: 'Early life', excerpt: 'At the age of thirteen, Alim Khan was sent by his father Emir Abdulahad Khan to Saint Petersburg for three years to study government and modern military techniques.' },
                { claim: 'Nicholas Cadet Corps', locator: 'Ранние годы', source: S.alimKhanRu, excerpt: 'Был принят на учёбу в Санкт-Петербургский Николаевский кадетский корпус' },
                { claim: 'governor of Nasaf and Karmana', locator: 'Early life', excerpt: 'he was appointed governor of the Nasef region for the next twelve years. He was then transferred to the northern province of Karmana' },
                { claim: 'twelfth and last emir', locator: 'преамбула', source: S.alimKhanRu, excerpt: 'последний, 12-й, эмир Бухарского эмирата' },
                { claim: 'early reforms against bribery and unauthorised taxes', locator: 'Reign', excerpt: 'He initially announced a rejection of personal gifts and prohibited officials from soliciting bribes or imposing unauthorized taxes.' },
                { claim: 'traditionalists prevailed', locator: 'Reign', excerpt: 'The power struggle between traditionalists and reformists concluded with the traditionalists gaining control' },
                { claim: 'repressed the reformers after 1917', locator: 'Свержение', source: S.alimKhanRu, excerpt: 'После начала революции 1917 года в Российской империи и манифестаций в Бухаре эмир обрушился на сторонников демократических реформ (см. младобухарцы) с репрессиями.' },
                { claim: 'Bolshevik attack of March 1918 failed', locator: 'Reign', excerpt: 'The majority of Bukharans did not support an invasion and the ill-equipped and ill-disciplined Bolshevik army fled back to the Soviet stronghold at Tashkent.' },
                { claim: 'fled via Dushanbe to Kabul, died 1944', locator: 'Deposition and death', excerpt: 'the Emir Alim Khan fled, first to his base at Dushanbe (in present-day Tajikistan), and then finally to Kabul, Afghanistan, where he died in 1944.' },
                { claim: 'cooperated with Britain to regain power', locator: 'преамбула', source: S.alimKhanRu, excerpt: 'Сотрудничал с Британской империей в надежде вернуть власть и возродить эмират.' },
                { claim: 'reportedly supported the Basmachi', locator: 'Свержение', source: S.alimKhanRu, excerpt: 'В эмиграции зарабатывал себе на жизнь торговлей каракулем; по некоторым данным, поддерживал басмачество.' },
            ],
        },
        activities: [
            { functionId: 'monarchy', affiliationId: null, startYear: 1911, endYear: 1920, primary: true, claim: 'Emir of Bukhara, no catalog affiliation', locator: 'lead', excerpt: 'reigned from 3 January 1911 to 30 August 1920' },
        ],
        career: [
            ['1896', '러시아 정부로부터 부하라 왕세자로 확인받음', 'Confirmed by the Russian government as Crown Prince of Bukhara'],
            ['1911–1920', '부하라 에미르', 'Emir of Bukhara'],
            ['1920–1944', '아프가니스탄 망명', 'Exile in Afghanistan'],
        ],
    })),
    person({
        id: 'fyodor-kolesov', groupId: 'bolshevik',
        given: ['표도르', 'Fyodor'], family: ['콜레소프', 'Kolesov'], nativeName: 'Фёдор Колесов', years: '1891–1940',
        citizenship: 'soviet', origin: null,
        epithet: ['1917~1918년 투르키스탄 소브나르콤 의장으로 코칸트 자치국을 무너뜨리고 부하라를 공격한 볼셰비키',
            'Bolshevik chairman of the Turkestan Sovnarkom in 1917–1918 who crushed the Kokand Autonomy and attacked Bukhara'],
        bio: ['1891년 우랄스크에서 태어나 오렌부르크와 타슈켄트에서 철도 사무원으로 일했다. 1917년 볼셰비키에 들어가 타슈켄트 소비에트 집행위원이 되었고, 제2차 전러시아 소비에트 대회에서 전러시아 중앙집행위원으로 뽑혔으며, 11월 타슈켄트 무장봉기를 조직했다. 1917년 11월부터 1918년 11월까지 투르키스탄 소브나르콤 의장으로서 무슬림을 최고 권력 기관에 들일 수 없다며 연립을 거부했고, 아슈하바드와 코칸트의 자치 시도를 무력으로 진압했다. 1918년 3월 청년부하라인과 함께 부하라 에미르를 무너뜨리려다 실패해 물러났다. 1923~1928년 극동 국민경제최고회의 의장을 지냈고, 뒤에 건축가로 일하다 1940년 모스크바에서 숨졌다.',
            'Born in Uralsk in 1891, he worked as a railway clerk in Orenburg and Tashkent. He joined the Bolsheviks in 1917, sat on the executive committee of the Tashkent Soviet, was elected to the All-Russian Central Executive Committee at the Second Congress of Soviets and helped organise the armed rising in Tashkent in November. As chairman of the Turkestan Sovnarkom from November 1917 to November 1918 he rejected a coalition, declaring that Muslims could not be admitted to the supreme organ of power, and put down by force the bids for autonomy in Ashgabat and Kokand. In March 1918 he tried with the Young Bukharans to overthrow the Emir of Bukhara and had to retreat. He chaired the Far Eastern Council of the National Economy in 1923–1928, later worked as an architect and died in Moscow in 1940.'],
        fate: ['natural', '사망', 'Died'],
        aliases: { ko: [], en: ['Fedor Kolesov'] },
        sources: [S.kolesov, S.kokand, S.kolesovUz],
        facts: {
            years: { claim: '1891–1940', locator: 'преамбула', excerpt: '20 мая (1 июня) 1891, Уральск, — 29 июля 1940, Москва' },
            citizenship: { claim: 'Soviet statesman and party official', locator: 'преамбула', excerpt: 'советский государственный и партийный деятель' },
            bio: [
                { claim: 'railway clerk in Orenburg and Tashkent', locator: 'Биография', excerpt: 'Работал конторщиком на железной дороге в Оренбурге, а с 1916 года — в Ташкенте.' },
                { claim: 'party member from 1917', locator: 'преамбула', excerpt: 'Член Коммунистической партии с 1917.' },
                { claim: 'Tashkent Soviet executive committee', locator: 'Биография', excerpt: 'С сентября 1917 член Исполкома Ташкентского совета' },
                { claim: 'Second Congress of Soviets, elected to VTsIK', locator: 'Биография', excerpt: 'делегат 2-го Всероссийского съезда Советов  в Петрограде в октябре 1917 года, где был избран членом ВЦИК' },
                { claim: 'organiser of the November rising in Tashkent', locator: 'Биография', excerpt: 'а также один из организаторов вооруженного восстания против власти представителей временного правительства в Ташкенте в ноябре 1917 года.' },
                { claim: 'chairman of the Turkestan Sovnarkom, Nov 1917–Nov 1918', locator: 'Биография', excerpt: 'С ноября 1917 года по ноябрь 1918 года Ф. И. Колесов являлся председателем Совета Народных комиссаров (СНК) Туркестанской АССР' },
                { claim: 'rejected a coalition with Muslims', locator: 'Establishment', source: S.kokand, excerpt: 'Fyodor Kolesov, president of the Sovnarkom, firmly rejected the offer, stating that "the inclusion of Muslims in the organ of supreme regional power is unacceptable at the present time".' },
                { claim: 'commanded the troops that crushed autonomy in Ashgabat and Kokand', locator: 'Биография', excerpt: 'В этот период он лично командовал войсками, подавившими попытки создания автономии в Ашхабаде,' },
                { claim: 'led the Red Guard units at Kagan, March 1918', locator: 'Voqealar rivoji', source: S.kolesovUz, excerpt: 'Mart oyining birinchi kunlarida Xalq Komissarlari Kengashi raisi F. I. Kolesov boshchiligidagi Qizil gvardiya boʻlinmalari Kogonda toʻplandi' },
                { claim: 'retreated towards Samarkand and Tashkent', locator: 'Voqealar rivoji', source: S.kolesovUz, excerpt: 'Keyingi kurashning befoydaligini anglagan Kolesov qoʻshinlar bilan birga Kogon aholisini (asosan yevropaliklardan iborat) evakuatsiya qilib, Samarqand-Toshkent yoʻnalishi boʻyicha chekinishga qaror qilgan.' },
                { claim: 'chairman of the Far Eastern VSNKh 1923–1928', locator: 'Биография', excerpt: 'В 1923 — 1928 годах Ф. И. Колесов был председателем ВСНХ Дальнего Востока' },
                { claim: 'studied architecture, then worked as an architect', locator: 'Биография', excerpt: 'В 1929 — 1933 годах он учился в Московском архитектурном институте и в аспирантуре Академии архитектуры, затем работал архитектором.' },
                { claim: 'died in Moscow in 1940', locator: 'Биография', excerpt: 'Скончался 29 июля 1940 г. в своей квартире в Москве' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: 'state-soviet', startYear: 1917, endYear: 1918, primary: true, claim: 'Chairman of the Council of People\'s Commissars of Turkestan', locator: 'Биография', excerpt: 'С ноября 1917 года по ноябрь 1918 года Ф. И. Колесов являлся председателем Совета Народных комиссаров (СНК) Туркестанской АССР' },
            { functionId: 'military', affiliationId: 'state-soviet', startYear: 1918, endYear: 1918, claim: 'Personally commanded the troops that suppressed the autonomies in Ashgabat and Kokand and attacked Bukhara', locator: 'Биография', excerpt: 'В этот период он лично командовал войсками, подавившими попытки создания автономии в Ашхабаде,' },
            { functionId: 'economy', affiliationId: 'state-soviet', startYear: 1923, endYear: 1928, claim: 'Chairman of the Far Eastern Supreme Council of the National Economy', locator: 'Биография', excerpt: 'В 1923 — 1928 годах Ф. И. Колесов был председателем ВСНХ Дальнего Востока' },
        ],
        career: [
            ['1917', '타슈켄트 소비에트 집행위원, 전러시아 중앙집행위원', 'Member of the Tashkent Soviet executive committee and of the All-Russian Central Executive Committee'],
            ['1917–1918', '투르키스탄 소브나르콤 의장', 'Chairman of the Turkestan Sovnarkom'],
            ['1919', '제8차 러시아 공산당 대회 대의원', 'Delegate to the Eighth Congress of the Russian Communist Party'],
            ['1923–1928', '극동 국민경제최고회의 의장', 'Chairman of the Far Eastern Supreme Council of the National Economy'],
            ['1929–1933', '모스크바 건축대학·건축아카데미 수학', 'Studied at the Moscow Architectural Institute and the Academy of Architecture'],
        ],
    }),
    unaffiliated(person({
        id: 'junaid-khan', groupId: 'world-interwar',
        given: ['', ''], family: ['주나이드 칸', 'Junaid Khan'], nativeName: 'Jüneýit han', years: '1857–1938',
        citizenship: { code: 'uzbekistan', label: { ko: '히바 칸국', en: 'Khanate of Khiva' } },
        origin: { code: 'turkmenistan', label: { ko: '투르크멘인 (요무트 부족)', en: 'Turkmen (Yomut tribe)' } },
        epithet: ['1918~1920년 히바 칸국의 실권을 쥐고 소비에트 권력과 싸운 투르크멘 요무트 부족 지도자',
            'Yomut Turkmen chief who held real power in the Khanate of Khiva in 1918–1920 and fought Soviet rule for more than a decade'],
        bio: ['1857년(1862년 설도 있다) 투르크멘 요무트 부족 지도자의 아들로 태어나 마을의 재판관(카지)과 물 관리인(미라브)을 지냈고, 1912~1916년 투르크멘 봉기로 이름을 얻었다. 1918년 1월 히바의 칸 아스판디야르에게 군 총사령관으로 임명되었으나 칸을 암살하고 그 숙부 사이드 압둘라를 허수아비 칸으로 세워 실권을 쥐었다. 1918년 11월 페트로알렉산드롭스크를 포위했고 1919년 콜차크 정부와 연락했으나, 1920년 초 붉은 군대에 패해 카라쿰 사막으로 물러났다. 이후 호레즘 인민소비에트공화국과 투르크멘 SSR을 거듭 침공해 1924년 1월에는 히바를 포위했다. 페르시아와 아프가니스탄으로 망명해 1938년 헤라트 근처에서 숨졌다.',
            'Born in 1857 (some sources say 1862), the son of a Yomut Turkmen chief, he served as a village judge (kazi) and water distributor (mirab) and made his name in the Turkmen uprisings of 1912–1916. Appointed commander of the armed forces of Khiva by Asfandiyar Khan in January 1918, he had the khan assassinated, installed the khan’s uncle Sayyid Abdullah as a puppet and took real power. He besieged Petro-Alexandrovsk in November 1918 and in 1919 opened contact with Kolchak’s government, but in early 1920 the Red Army defeated him and he retreated into the Karakum desert. He then repeatedly invaded the Khorezm People’s Soviet Republic and the Turkmen SSR, besieging Khiva in January 1924. He went into exile in Persia and Afghanistan and died near Herat in 1938.'],
        fate: ['exile', '망명지에서 사망', 'Died in exile'],
        aliases: { ko: ['무하메트 구르반', '무하메트쿠르반 세르다르'], en: ['Muhammet Gurban', 'Muhammet-Kurban Serdar'] },
        sources: [S.junaid, S.junaidRu, S.junaidUz],
        facts: {
            years: { claim: '1857 (or 1862)–1938', locator: 'lead', excerpt: '(b.1857/62–1938)' },
            citizenship: { claim: 'commander and de facto ruler of the Khanate of Khiva', locator: 'lead', excerpt: 'became the Chief of the Armed Forces and later the de facto and last ruler of the Khanate of Khiva' },
            nationalOrigin: { claim: 'Turkmen of the Yomut tribe', locator: 'преамбула', source: S.junaidRu, excerpt: 'По национальности туркмен из племени йомудов.' },
            bio: [
                { claim: 'born 1857 or 1862, son of a Yomut chief', locator: 'Biography before 1917', excerpt: 'Born in 1857 (according to other sources in 1862), Junaid Khan was the son of Khojibay, a powerful leader of the Yomut (Turkmen) tribe of Junaids and a wealthy man.' },
                { claim: 'village judge and water distributor', locator: 'Biography before 1917', excerpt: 'which allowed him to become first kazi (judge) in the village, and later a water distributor (mirab).' },
                { claim: 'rose in the Turkmen uprisings of 1912–1916', locator: 'lead', excerpt: 'Gaining authority during the Turkmen uprisings of 1912-1916' },
                { claim: 'appointed commander of the armed forces in January 1918', locator: 'Rise to power in Khiva', excerpt: 'In January 1918, Asfandiyar Khan appointed Muhammet-Kurban as the commander of the armed forces of the Khanate' },
                { claim: 'assassinated the khan and installed his uncle as puppet', locator: 'lead', excerpt: 'Junaid arranged Isfandiyar\'s assassination and later enthroned the murdered Khan\'s uncle Sayid Abdullah as a puppet ruler, while himself becoming the real master of the Khanate.' },
                { claim: 'besieged Petro-Alexandrovsk on 24 November 1918', locator: 'Первая война против советской власти в Туркестане', source: S.junaidRu, excerpt: '24 ноября Джунаид-хан, сумев собрать до 4000 всадников и 6000 так называемых «олджинцев» («трофейщиков»), осадил Петроалександровск.' },
                { claim: 'contact with Kolchak in September 1919', locator: 'Вторая война против советской власти', source: S.junaidRu, excerpt: 'В сентябре 1919 года Джунаид-хан устанавливает прямую связь с правительством Колчака.' },
                { claim: 'defeated in early 1920, retreated to the Karakum', locator: 'Clashes with the Red Army', excerpt: 'By early February 1920, the Khivan army under Junaid Khan was completely defeated and Junaid Khan retreated to Karakum desert.' },
                { claim: 'besieged Khiva in January 1924', locator: 'Продолжение борьбы', source: S.junaidRu, excerpt: 'В январе его отряд один за одним захватывает города Ташауз, Мангит, Шават, Газават, Ханки и Хазарасп, после чего начинает осаду Хивы и Новоургенча.' },
                { claim: 'invaded the Turkmen SSR in 1931', locator: 'Продолжение борьбы', source: S.junaidRu, excerpt: 'В апреле уже сам Джунаид-хан во главе нескольких басмаческих отрядов вторгается на территорию Красноводского района.' },
                { claim: 'fled to Persia and Afghanistan, died 1938', locator: 'Clashes with the Red Army', excerpt: 'finally fled first to Persia and then to Afghanistan where he eventually died in 1938.' },
                { claim: 'died near Herat', locator: 'lead', source: S.junaidUz, excerpt: '1938, Hirot atrofi, Afgʻoniston' },
            ],
        },
        activities: [
            { functionId: 'military', affiliationId: null, startYear: 1918, endYear: 1931, primary: true, claim: 'Commander of the Khivan forces and Basmachi leader, no catalog affiliation', locator: 'Rise to power in Khiva', excerpt: 'In January 1918, Asfandiyar Khan appointed Muhammet-Kurban as the commander of the armed forces of the Khanate' },
            { functionId: 'government', affiliationId: null, startYear: 1918, endYear: 1920, source: S.junaidRu, claim: 'De facto ruler of Khiva, no catalog affiliation', locator: 'преамбула', excerpt: 'фактический (последний) правитель Государства Хорезм' },
        ],
        career: [
            ['1912–1916', '투르크멘 봉기 지도자', 'Leader in the Turkmen uprisings'],
            ['1918', '히바 칸국 군 총사령관', 'Commander of the armed forces of the Khanate of Khiva'],
            ['1918–1920', '히바 칸국의 실질적 통치자', 'De facto ruler of the Khanate of Khiva'],
            ['1920–1931', '카라쿰·페르시아·아프가니스탄을 근거지로 한 바스마치 지도자', 'Basmachi leader operating from the Karakum, Persia and Afghanistan'],
        ],
    })),
];
