// Glossary terms for the central-asia-1917-1924 event (2026-10-04), built with
// lib.js term(). Not made: national-delimitation-central-asia-1924 — the
// existing term national-delimitation already covers the 1924 Central Asian
// delimitation (alias 중앙아시아 민족 획정 / Central Asian delimitation); jadidism exists.
//
// Original names (term.original):
//   kokand-autonomy                    ru Кокандская автономия; uz Turkiston Muxtoriyati (Qo'qon muxtoriyati)
//   basmachi-movement                  ru Басмачество; uz Босмачи (bosmachi)
//   alash-orda                         kk Алаш Орда (Алаш автономиясы); ru Алаш-Орда
//   bukharan-peoples-soviet-republic   ru Бухарская Народная Советская Республика; uz Buxoro Xalq Sovet Respublikasi
//   khorezm-peoples-soviet-republic    ru Хорезмская Народная Советская Республика; uz Xorazm Xalq Sovet Respublikasi
//   persian-socialist-soviet-republic  fa جمهوری شوروی سوسیالیستی ایران; ru Гилянская Советская Социалистическая Республика
//   turkkomissiya                      ru Туркестанская комиссия ВЦИК и СНК РСФСР (Турккомиссия)
const { term } = require('../lib');

const E = t => 'https://en.wikipedia.org/wiki/' + encodeURI(t.replace(/ /g, '_'));
const RU = t => 'https://ru.wikipedia.org/wiki/' + encodeURI(t.replace(/ /g, '_'));
const S = {
    kokand: E('Turkestan Autonomy'),
    kokandRu: RU('Кокандская автономия'),
    basmachi: E('Basmachi movement'),
    basmachiRu: RU('Басмачество'),
    ibrahimRu: RU('Ибрагим-бек'),
    alash: E('Alash Autonomy'),
    alashRu: RU('Алаш-Орда'),
    bukeikhanov: E('Alikhan Bukeikhanov'),
    bpsr: E("Bukharan People's Soviet Republic"),
    bukharaOp: E('Bukhara operation (1920)'),
    khorezm: E("Khorezm People's Soviet Republic"),
    khorezmRu: RU('Хорезмская народная советская республика'),
    khivaOpRu: RU('Хивинская операция (1919—1920)'),
    junaidRu: RU('Джунаид-хан'),
    pssr: E('Persian Socialist Soviet Republic'),
    gilanRu: RU('Гилянская советская социалистическая республика'),
    jungle: E('Jungle Movement of Gilan'),
    eliavaRu: RU('Элиава, Шалва Зурабович'),
    tassrRu: RU('Туркестанская Автономная Социалистическая Советская Республика'),
    kuibyshevRu: RU('Куйбышев, Валериан Владимирович'),
};

module.exports = [
    term({
        id: 'kokand-autonomy', ko: '코칸트 자치국', en: 'Kokand Autonomy', category: 'nationalities', period: '1917–1918', startYear: 1917, endYear: 1918,
        definition: ['1917년 12월 10일(구력 11월 27일) 코칸트에서 열린 제4차 임시 전무슬림 지역 대회가 선포해 1918년 2월 22일까지 존속한 투르키스탄의 자치 정부. 공식 이름은 투르키스탄 자치국으로, 제헌의회가 최종 형태를 정할 때까지 연방 러시아 공화국 안의 자치를 내걸고 러시아인 정착민이 이끈 타슈켄트 소비에트에 맞섰다. 타슈켄트 소비에트 군대가 코칸트를 포격해 점령하면서 무너졌다.',
            'The autonomous government of Turkestan proclaimed in Kokand on 10 December 1917 (27 November O.S.) by the Fourth Extraordinary All-Muslim Regional Congress, which lasted until 22 February 1918. Officially the Turkestan Autonomy, it claimed autonomy within a federal Russian republic until a constituent assembly could settle the region’s final form, and challenged the Tashkent Soviet, which was led by Russian settlers. It collapsed when the Tashkent Soviet’s troops shelled and took Kokand.'],
        body: ['2월 혁명 뒤 투르키스탄에서는 자디드가 중심인 슈로이 이슬로미야와 샤리아를 앞세운 보수적 울라모 자미야티가 생겨났다. 1917년 11월 타슈켄트를 장악한 소비에트는 소브나르콤을 세웠지만, 의장 표도르 콜레소프는 「현 시점에서 무슬림을 최고 권력 기관에 들이는 것은 받아들일 수 없다」며 무슬림 대회의 연립 제안을 거절했다. 이에 무슬림 정치 세력은 타슈켄트 소비에트의 손이 닿지 않는 페르가나 분지의 상업 중심지 코칸트에 약 250명이 모여 자치를 선언했다. 첫 총리는 카자흐인 무하메잔 티니슈파예프였고, 1918년 1월 초 무스타파 쇼카이가 뒤를 이었다. 원주민 다수가 지지해 나망간·사마르칸트 등지에서 수천 명, 타슈켄트에서 6만 명이 모인 집회가 열렸다. 그러나 자치국은 세금을 걷지 못해 300만 루블의 차입금과 기부금에 기댔고, 소비에트 군이 국립은행 코칸트 지점에서 자치국 계좌를 포함한 800만 루블을 압수하자 내분이 깊어졌다. 군대는 약 2,000명으로 장교도 훈련된 병사도 없어 코칸트 민병대장 에르가시에게 의존했다. 남동연맹의 알렉산드르 두토프, 알라시 자치국, 부하라 에미르와 손잡으려던 시도는 모두 실패했고, 민족 인민위원 이오시프 스탈린은 승인 요청에 투르키스탄의 노동자들이 힘이 있다면 타슈켄트의 인민위원부를 「무력으로」 해산하라고 답했다.\n\n1918년 1월 중순 제4차 지역 소비에트 대회는 자치국을 불법화하고 그 구성원의 체포를 결의했다. 1월 두토프의 철도 봉쇄가 풀려 무기가 타슈켄트에 들어오면서 군사력의 격차는 결정적이 되었다. 2월 11일 밤 자치국 쪽 무장대가 후다야르 칸 궁전과 코칸트 소비에트 본부를 점거하자 타슈켄트 소비에트는 계엄을 선포하고 콘스탄틴 오시포프의 부대를 보냈다. 포격이 시작되자 정부는 쇼카이 내각과 강경파로 갈라졌고, 2월 18일 총사령관 에르가시가 정변으로 권력을 쥐었다. 그가 19일 항복 최후통첩을 거부하자 소비에트 군은 도시를 집중 포격했고, 22일 구시가 대표단이 무장 해제와 소비에트 권력 인정에 동의했다. 점령된 도시는 약탈당했고 주민 학살이 벌어졌는데, 영어 출처들도 희생자를 1만 명 이상에서 최대 2만 5천 명까지로 다르게 적는다. 자치국 지지자들은 즉결 처형되거나 체포되었고, 소비에트 정부의 식량 징발이 기근을 낳았다. 에르가시가 1918년 여름 시작한 무장 저항은 바스마치 운동으로 번졌고, 자치국은 그 뒤 소비에트 정부에 대한 저항의 상징이 되었다.',
            'After the February Revolution Turkestan saw the rise of the Shuroi Islomiya, dominated by Jadids, and of the conservative Ulamo Jamiyati, which put sharia first. The Soviet that seized Tashkent in November 1917 set up a Sovnarkom, but its chairman Fyodor Kolesov rejected a Muslim congress’s offer of a coalition, declaring that “the inclusion of Muslims in the organ of supreme regional power is unacceptable at the present time”. Muslim political forces then met in Kokand, the commercial centre of the Fergana Valley beyond the Tashkent Soviet’s reach, where some 250 delegates declared autonomy. The first prime minister was the Kazakh Mukhamedzhan Tynyshpaev, succeeded in early January 1918 by Mustafa Shokay. Most of the native population supported the government: rallies thousands strong were held in Namangan, Samarkand and elsewhere, and 60,000 gathered in Tashkent. Yet the Autonomy could not tax and lived on a 3-million-ruble loan and donations, and its internal quarrels deepened when Soviet forces seized 8 million rubles, its own account included, from the Kokand branch of the State Bank. Its army of about 2,000 had no officers or trained men and relied on Ergash, the Kokand militia chief. Attempts to join forces with Alexander Dutov’s South-Eastern Union, the Alash Autonomy and the Emir of Bukhara all failed, and People’s Commissar for Nationalities Joseph Stalin answered a plea for recognition by saying that the workers of Turkestan should disperse the Tashkent commissariat “by force” if they had the power.\n\nIn mid-January 1918 the Fourth Regional Congress of Soviets outlawed the Autonomy and ordered the arrest of its members. Once Dutov’s railway blockade was lifted in January and arms reached Tashkent, the military imbalance became decisive. When forces on the Autonomy’s side seized the Palace of Khudayar Khan and the Kokand Soviet’s headquarters on the night of 11 February, the Tashkent Soviet declared martial law and sent troops under Konstantin Osipov. Under shelling the government split between Shokay’s cabinet and the hardliners, and on 18 February the commander-in-chief Ergash seized power in a coup. When he rejected an ultimatum to surrender on the 19th, Soviet forces shelled the city heavily, and on the 22nd a delegation from the old city agreed to disarm and recognise Soviet authority. The captured city was sacked and its inhabitants massacred; even the English-language sources differ on the toll, from more than 10,000 to as many as 25,000. Supporters of the Autonomy were summarily executed or arrested, and Soviet food requisitioning caused a famine. The armed resistance Ergash began in the summer of 1918 grew into the Basmachi movement, and the Autonomy became a symbol of resistance to Soviet rule.'],
        aliases: { ko: ['투르키스탄 자치국', '투르키스탄 자치정부', '코칸트 자치정부'], en: ['Turkestan Autonomy', 'Kokand Autonomous Government', 'Turkiston Muxtoriyati'] },
        people: ['mustafa-shokay', 'fyodor-kolesov', 'stalin', 'alexander-dutov'],
        events: ['central-asia-1917-1924', 'civil-war'],
        sources: [S.kokand, S.kokandRu, S.basmachi], locator: 'lead; Background; Establishment; Influence over Turkestan; Issues governing Turkestan; Invasion and dissolution; Aftermath and legacy — ru: преамбула — Basmachi movement: lead',
    }),
    term({
        id: 'basmachi-movement', ko: '바스마치 운동', en: 'Basmachi movement', category: 'nationalities', period: '1918–1934', startYear: 1918, endYear: 1934,
        definition: ['1918년부터 1930년대 초까지 투르키스탄·부하라·히바 등 중앙아시아에서 러시아와 소비에트 지배에 맞선 무슬림 무장 저항을 아우르는 이름. 「바스마치」는 우즈베크어로 「습격자, 도적」을 뜻하며, 소비에트 역사학은 이를 반혁명 부르주아 민족주의 운동으로 규정했다. 1916년 징발 반대 봉기에 뿌리를 두고 1918년 코칸트 학살 뒤 페르가나에서 본격화했으며, 영어 출처는 1934년에 끝났다고 본다.',
            'The collective name for the Muslim armed resistance to Russian and Soviet rule in Central Asia—Turkestan, Bukhara and Khiva—from 1918 into the early 1930s. “Basmachi” is Uzbek for “raiders” or “bandits”, and Soviet historiography branded the movement an anti-Soviet, counter-revolutionary, bourgeois-nationalist one. Rooted in the anti-conscription revolt of 1916, it took off in Fergana after the Kokand massacre of 1918; the English-language source considers it to have ended by 1934.'],
        body: ['러시아 지배 아래 페르가나 분지는 대규모 면화 산지로 바뀌어 빚진 농민과 땅 없는 농촌 무산자가 늘었고, 1916년 무슬림 징발이 중앙아시아 봉기를 불렀다. 1918년 2월 붉은 군대가 코칸트 자치국을 무너뜨리고 최대 2만 5천 명을 학살하자, 코칸트 민병대장 에르가시가 「이슬람군 최고 지도자」를 자처하며 들고일어났다. 국유화와 곡물 수입 단절로 기근이 닥치자 사람들이 대거 합류했고, 마다민 벡 같은 쿠르바시(무장대 지휘관)가 이끈 바스마치는 페르가나 분지의 넓은 지역과 투르키스탄 곳곳을 장악했다. 1920년 부하라 에미르가 쫓겨난 뒤에는 동부 부하라가 새 중심이 되어, 로카이 부족의 이브라힘 벡이 에미르 사이드 알림 칸의 이름으로 부족들을 이끌었고, 1922년에는 히소르에서 서부 파미르에 이르는 동부 부하라 대부분이 바스마치의 손에 있었다. 1921년 11월 소비에트 측이 보낸 전 오스만 장관 엔베르 파샤가 바스마치로 넘어가 범튀르크·범이슬람 국가를 꿈꾸며 지휘권을 쥐려 했으나, 지도자들은 그를 적대했고 그는 1922년 8월 전사했다. 히바와 투르크멘 땅에서는 주나이드 칸이 따로 싸웠다.\n\n소비에트 당국은 압도적 군사력과 양보를 함께 썼다. 샤리아(이슬람법)를 다시 인정하고 코란 학교와 와크프(종교 기부 재산) 토지를 되살렸으며, 무슬림 농민 의용 민병대 「붉은 막대」를 만들었으며, 이 지역 소비에트 군대의 15~25%가 무슬림이었다고 추산된다. 1923년 초 페르가나의 주요 무장대가 격파되었고, 1926년 가을까지 바스마치는 중앙아시아 대부분에서 무너졌다. 아프가니스탄으로 물러난 이브라힘 벡은 집단화에 대한 반발을 업고 다시 침입했으나 1931년 사로잡혀 총살되었다. 소비에트 공식 설명은 1931~1932년에 조직된 세력이 사라졌다고 하며, 마지막 대규모 집단은 1933년 카라쿰 사막에서 격파되었다. 평가는 크게 엇갈린다. 소련 붕괴 뒤 중앙아시아 국가들은 이를 민족해방 운동으로 다시 썼고 우즈베크 역사가 라자보프는 코칸트 자치국·자디드와 한 흐름으로 보았지만, 옥스퍼드의 알렉산더 모리슨은 페르가나의 바스마치에게 뚜렷한 정치 목표가 없었다고 반박한다. 영어 출처는 이 운동이 민족해방 운동도 민족주의 운동도 아닌, 러시아 지배를 몰아내려는 일시적 부족 연합이었다고 평가한다.',
            'Under Russian rule the Fergana Valley had been turned into a major cotton-growing region, multiplying indebted farmers and a landless rural proletariat, and the conscription of Muslims in 1916 set off the Central Asian revolt. When the Red Army destroyed the Kokand Autonomy in February 1918 and massacred as many as 25,000 people, the Kokand militia chief Ergash took up arms as self-styled “Supreme Leader of the Islamic Army”. As nationalisations and the loss of grain imports brought famine, recruits poured in, and Basmachi bands under kurbashi (commanders) such as Madamin Bek seized large parts of the Fergana Valley and much of Turkestan. After the Emir of Bukhara was driven out in 1920, eastern Bukhara became the new centre: Ibrahim Bek of the Lakai tribe led the tribes in the name of Emir Said Alim Khan, and in 1922 most of eastern Bukhara, from Hisor to the western Pamirs, was in Basmachi hands. Enver Pasha, the former Ottoman minister sent by the Soviets in November 1921, went over to the Basmachi and tried to take command in pursuit of a pan-Turkic and pan-Islamic state, but the leaders were hostile to him and he was killed in August 1922. In Khiva and the Turkmen lands Junaid Khan fought a war of his own.\n\nThe Soviet authorities combined overwhelming force with concessions. They reinstated sharia law and restored Koran schools and waqf (religious endowment) lands, created a volunteer militia of Muslim peasants, the “Red Sticks”, and an estimated 15–25 per cent of Soviet troops in the region were Muslim. The main bands in Fergana were beaten in early 1923, and by the autumn of 1926 the Basmachi had been largely crushed across Central Asia. Ibrahim Bek, who had withdrawn to Afghanistan, invaded again on the back of resistance to collectivisation but was captured and shot in 1931. The official Soviet account dates the end of the movement as an organised force to 1931–1932, and the last large group was destroyed in the Karakum desert in 1933. Assessments diverge sharply. After the Soviet collapse the Central Asian states recast the movement as a national liberation struggle, and the Uzbek historian Rajabov treated it as one current with the Kokand Autonomy and the Jadids, while Alexander Morrison of Oxford counters that the Fergana Basmachi had no clear political aims. The English-language source judges that it was neither a national liberation movement nor a nationalist one but a temporary tribal alliance aimed at removing Russian rule.'],
        aliases: { ko: ['바스마치', '바스마치 봉기', '바스마치 반란'], en: ['Basmachi', 'Basmachi revolt', 'Basmachi rebellion', 'Basmachestvo'] },
        people: ['ibrahim-bek', 'enver-pasha', 'said-alim-khan', 'junaid-khan', 'frunze'],
        events: ['central-asia-1917-1924', 'civil-war'],
        sources: [S.basmachi, S.basmachiRu, S.ibrahimRu, S.bpsr], locator: 'lead; Background; Kokand autonomy and the start of hostilities; Defeat of the movement; 1930; Aftermath — ru: преамбула; Ибрагим-бек: Биография — Bukharan People’s Soviet Republic: Bukharan People’s Soviet Republic',
    }),
    term({
        id: 'alash-orda', ko: '알라시 오르다', en: 'Alash Orda', category: 'nationalities', period: '1917–1920', startYear: 1917, endYear: 1920,
        definition: ['1917년 12월 오렌부르크의 제2차 전카자흐 대회가 세운 카자흐 자치국 알라시와 그 임시 인민평의회(정부). 알리칸 부케이하노프가 의장을 맡고 세미팔라틴스크를 수도로 삼아 러시아 공화국 안의 민족 자치를 추구했으며, 내전기 대부분을 백군 쪽 정부들과 손잡았다. 1919년 소비에트 권력과 타협한 뒤 1920년 3월 5일 키르기스 지역 혁명위원회에 의해 폐지되었다.',
            'The Kazakh autonomy of Alash, founded by the Second All-Kazakh Congress in Orenburg in December 1917, and its provisional People’s Council, or government. Chaired by Alikhan Bukeikhanov, with its capital at Semipalatinsk, it sought national autonomy within the Russian republic and for most of the Civil War sided with the White governments. After coming to terms with Soviet power in 1919, it was abolished by the Revolutionary Committee for the Kirghiz Territory on 5 March 1920.'],
        body: ['부케이하노프를 비롯한 카자흐 지식인들은 1905년부터 입헌민주당(카데트)과 함께 활동했으나, 부케이하노프는 2월 혁명 뒤 카데트가 카자흐 자치를 지지하지 않자 갈라섰다. 1917년 4월 부케이하노프와 아흐메트 바이투르시노프 등이 오렌부르크에서 소집한 카자흐 대회는 옛 정권이 빼앗은 땅을 원주민에게 돌려주고 새 정착민을 내보내며, 지역 학교를 원주민에게 넘기고 1916년의 징발을 끝내라고 요구했다. 러시아어 출처에 따르면 7월의 제1차 전카자흐 대회가 알라시 당을 세웠다. 「알라시」는 카자흐의 세 주즈를 아우르는 말로, 카자흐와 같은 뜻으로 쓰인다. 10월 혁명 뒤 구력 1917년 12월 5~13일(신력 18~26일) 열린 제2차 대회는 자치국 알라시를 세우고 25명의 인민평의회 알라시 오르다를 뽑았는데, 10석은 비카자흐인에게 돌아갔다. 부케이하노프의 주장으로 자치의 공식 선포는 상황을 지켜보며 미뤄졌고, 수도 세미팔라틴스크는 알라시칼라라는 이름을 얻었다. 1918년 초 지도자들은 붉은 군대를 피해 초원으로 숨어야 했다.\n\n체코슬로바키아 군단의 반란 뒤 초원 대부분이 반볼셰비키 세력의 손에 들어가자, 알라시 오르다는 1918년 6월 11일 영토 안의 소비에트 법령을 모두 무효로 선언하고 오렌부르크의 알렉산드르 두토프, 사마라의 제헌의회 의원 위원회(코무치), 옴스크 정부와 손잡았다. 6월에는 카자흐 기병대가 세미팔라틴스크에 들어왔다. 코무치는 9월 초 알라시 자치를 공식 승인했지만, 11월 4일 우파 집정부는 모든 자치를 폐지했고 곧 권력을 잡은 알렉산드르 콜차크는 민족 자치에 단호히 반대했다. 백군에게 외면당한 지도자들은 1919년 봄부터 소비에트 정부와 교섭했고, 투르가이에서 바이투르시노프 지지자들이 먼저 소비에트 권력을 인정한 데 이어 바이투르시노프가 다른 지도자들에게 백군과 결별하라고 설득했고, 서부 지부도 1919년 12월 10일 소비에트 권력을 인정했다. 알라시 오르다는 1920년 3월 폐지되었고, 그해 8월 키르기스(카자흐) 자치 사회주의 소비에트 공화국이 세워졌다. 볼셰비키와의 타협은 뒤에 버려졌고, 「알라시 오르다 민족주의자」라는 낙인은 카자흐 지식인 탄압의 근거가 되어 부케이하노프는 1937년 총살되었다.',
            'Kazakh intellectuals, Bukeikhanov among them, had worked with the Constitutional Democrats (Kadets) since 1905, but after the February Revolution Bukeikhanov broke with the Kadets when they would not support Kazakh autonomy. In April 1917 a Kazakh congress convened in Orenburg by Bukeikhanov, Akhmet Baitursynov and others demanded that lands confiscated by the old regime be returned to the native population and the new settlers expelled, that local schools be handed over to natives, and that the conscription of 1916 be ended. According to the Russian-language source, the First All-Kazakh Congress in July founded the Alash party. “Alash” names the union of the three Kazakh jüz and is used as a synonym for Kazakh. After the October Revolution the Second Congress, held on 5–13 December 1917 O.S. (18–26 December N.S.), created the autonomy of Alash and elected a 25-member People’s Council, the Alash Orda, with ten seats reserved for non-Kazakhs. At Bukeikhanov’s urging the formal proclamation of autonomy was postponed while the situation was studied, and the capital, Semipalatinsk, was renamed Alash-kala. In early 1918 the leaders had to hide in the steppe from the Red Army.\n\nAfter the revolt of the Czechoslovak Legion put most of the steppe in anti-Bolshevik hands, the Alash Orda declared all Soviet decrees on its territory void on 11 June 1918 and allied itself with Alexander Dutov in Orenburg, the Committee of Members of the Constituent Assembly (Komuch) in Samara and the government in Omsk. In June a Kazakh cavalry detachment entered Semipalatinsk. Komuch formally recognised the Alash autonomy in early September, but on 4 November the Ufa Directory abolished all autonomies, and Alexander Kolchak, who seized power soon afterwards, was firmly opposed to national autonomy. Cold-shouldered by the Whites, the leaders began talks with the Soviet government in the spring of 1919; Baitursynov’s supporters in Turgay recognised Soviet power first, Baitursynov urged the other leaders to break with the Whites, and the western branch recognised Soviet power on 10 December 1919. The Alash Orda was abolished in March 1920, and in August the Kirghiz (Kazakh) Autonomous Socialist Soviet Republic was founded. The compromise with the Bolsheviks was later discarded, and the label “Alash Orda nationalist” became grounds for the repression of the Kazakh intelligentsia; Bukeikhanov was shot in 1937.'],
        aliases: { ko: ['알라시 자치국', '알라시 자치정부', '알라시 오르다 정부'], en: ['Alash Autonomy', 'Alash-Orda', 'Alash Horde'] },
        people: ['alikhan-bukeikhanov', 'alexander-dutov', 'alexander-kolchak'],
        events: ['central-asia-1917-1924', 'civil-war'],
        sources: [S.alash, S.alashRu, S.bukeikhanov], locator: 'lead; Ethnonym; History; Government — ru: преамбула; Флаг; Отношения с белыми; Роспуск и сотрудничество с Колчаком; Переговоры с большевиками — Alikhan Bukeikhanov: Author of the idea of the First Kazakh Republic; ru Букейханов: С 1917 года',
    }),
    term({
        id: 'bukharan-peoples-soviet-republic', ko: '부하라 인민소비에트공화국', en: 'Bukharan People’s Soviet Republic', category: 'party-state', period: '1920–1924', startYear: 1920, endYear: 1924,
        definition: ['1920년 9월 붉은 군대와 청년부하라인이 에미르 사이드 알림 칸을 몰아낸 옛 부하라 에미르국 땅에 10월 8일 선포된 소비에트 공화국. 파이줄라 호자예프가 이끈 인민나지르(장관)회의가 정부를 맡았고, 사유재산과 이슬람 원칙을 인정한 과도기의 「인민」 공화국이었다. 1924년 9월 19일 부하라 사회주의 소비에트 공화국으로 이름을 바꾼 뒤, 10월 27일 민족 경계 획정으로 해체되어 대부분 우즈베크 SSR에 들어갔다.',
            'The Soviet republic proclaimed on 8 October 1920 in the lands of the former Emirate of Bukhara, after the Red Army and the Young Bukharans had driven out Emir Said Alim Khan in September. Governed by the Council of People’s Nazirs (ministers) under Faizulla Khodzhayev, it was a transitional “people’s” republic that recognised private property and Islamic principles. Renamed the Bukharan Socialist Soviet Republic on 19 September 1924, it was dissolved in the national delimitation of 27 October 1924, most of its territory going to the Uzbek SSR.'],
        body: ['부하라의 개혁은 범튀르크주의와 자디드 개혁 사상, 볼셰비키 공산주의의 영향을 받은 청년부하라인이 이끌었다. 1918년 3월 이들의 요청으로 표도르 콜레소프가 부하라로 진격했으나, 러시아 측 출처에 따르면 에미르는 볼셰비키 대표단을 죽이고 성전을 부추겨 수천 명의 러시아인이 죽고 많은 청년부하라인이 처형되었다. 1920년 8월 3일 볼셰비키와 청년부하라인은 공동 행동에 합의했고, 16일 차르주이에서 열린 부하라 공산당 제4차 대회가 에미르 타도를 결의했으며, 25일 러시아 공산당 정치국이 이를 승인했다. 28일 밤 차르주이 봉기와 함께 미하일 프룬제의 붉은 군대가 공격을 시작했다. 152mm 요새포를 포함한 중포가 성벽 가까이 놓여 1만 2천 발의 포탄이 쏟아졌고, 에미르는 31일 1,000명의 병력과 함께 동부 부하라의 두샨베로 달아났다. 9월 2일 도시가 함락되었을 때 에미르의 성채 아르크는 포격과 공습으로 폐허가 되었고 민간인 수백 명이 죽었다. 9월 14일 무히트디노프가 이끄는 전부하라 혁명위원회가 세워졌고, 10월 8일 공화국이 선포되었다.\n\n소비에트 용어로 이 공화국은 사회주의 소비에트 공화국으로 가는 과도기인 「프롤레타리아와 농민의 혁명적 민주주의 독재」였다. 1921년 9월 25일의 헌법은 1918년 러시아 헌법과 달리 토지와 생산 수단의 사유를 허용하고 비프롤레타리아에게도 선거권을 주었으며(에미르의 친족과 옛 관리, 대지주는 제외), 제26조는 어떤 법도 이슬람의 기본 원칙에 어긋날 수 없다고 정했다. 마을이 스스로 대표를 뽑는 아크사칼 제도도 유지되었다. 엘리트의 언어인 페르시아어 대신 우즈베크어가 국어가 되었고, 교육 나지르 압두라우프 피트라트는 많은 학생을 독일 등 유럽 대학에 보냈다. 국기는 망치와 낫에 초승달을 더했다. 공산당원은 선포 두 주 만에 1만 4천 명으로 불었다가 거듭된 제명으로 1922년 1,000명으로 줄었다. 1922년 동부 부하라 대부분이 바스마치의 손에 있었고, 1923년부터 모스크바는 스탈린 등을 앞세워 부하라 정부를 「부르주아 민족주의」로 몰아 정부와 당을 대대적으로 숙청했다. 면적 18만 2천㎢, 인구 220만여 명의 공화국은 1924년 서부가 우즈베크 SSR(아무다리야 남안은 투르크멘 SSR)로, 동부가 타지크 자치 공화국으로 나뉘었다. 자디드 출신의 호자예프는 우즈베크 SSR의 첫 지도자가 되었으나 1930년대에 숙청되어 처형되었다.',
            'Reform in Bukhara was led by the Young Bukharans, who drew on pan-Turkism, the Jadid reform movement and Bolshevik communism. When Fyodor Kolesov marched on Bukhara at their request in March 1918, the emir, according to a Russian source, killed the Bolshevik delegation and incited a holy war in which thousands of Russians were killed and many Young Bukharans executed. On 3 August 1920 the Bolsheviks and the Young Bukharans agreed to act together; on the 16th the Fourth Congress of the Bukharan Communist Party, meeting in Chardzhou, resolved to overthrow the emir, and on the 25th the Politburo of the Russian Communist Party confirmed the orders. On the night of the 28th, as Chardzhou rose, Mikhail Frunze’s Red Army attacked. Heavy guns including 152-mm fortress pieces were brought close to the walls and 12,000 shells fired, and on the 31st the emir fled with 1,000 men to Dushanbe in eastern Bukhara. When the city fell on 2 September the emir’s citadel, the Ark, lay in ruins from shelling and air attack, and hundreds of civilians had been killed. An All-Bukharan Revolutionary Committee under Mukhitdinov was formed on 14 September, and the republic was proclaimed on 8 October.\n\nIn Soviet terminology the republic was a “revolutionary-democratic dictatorship of the proletariat and the peasantry”, a transitional stage on the way to a Socialist Soviet Republic. Its constitution of 25 September 1921, unlike the Russian constitution of 1918, allowed private ownership of land and the means of production and gave non-proletarians the vote (except the emir’s relatives, former officials and large landowners), and Article 26 laid down that no law could contradict the fundamental principles of Islam. The aksakal system, in which villages chose their own representatives, was kept. Uzbek became the state language in place of Persian, the language of the elite, and the education nazir Abdurauf Fitrat sent many students to European universities, especially in Germany. The flag added a crescent to the hammer and sickle. Party membership swelled to 14,000 two weeks after the proclamation but was cut to 1,000 by 1922 through repeated expulsions. In 1922 most of eastern Bukhara was held by the Basmachi, and from 1923 Moscow, with Stalin among the accusers, charged the Bukharan government with “bourgeois nationalism” and purged the government and party wholesale. The republic, 182,000 square kilometres in area with more than 2.2 million people, was divided in 1924: the west went to the Uzbek SSR (the south bank of the Amu Darya to the Turkmen SSR) and the east to the Tajik Autonomous Republic. Khodzhayev, despite his Jadid background, became the first leader of the Uzbek SSR, but was purged and executed in the 1930s.'],
        aliases: { ko: ['부하라 인민공화국', '부하라 인민소비에트 공화국', '부하라 사회주의 소비에트 공화국'], en: ['Bukharan People\'s Soviet Republic', 'Bukharan People’s Republic', 'Bukharan People\'s Republic', 'Bukharan PSR', 'Bukharan Socialist Soviet Republic', 'Bukharan SSR'] },
        people: ['faizulla-khodzhayev', 'said-alim-khan', 'fyodor-kolesov', 'frunze', 'kuibyshev', 'georgy-zinoviev', 'enver-pasha', 'stalin'],
        events: ['central-asia-1917-1924', 'civil-war', 'ussr-formation'],
        sources: [S.bpsr, S.bukharaOp], locator: 'lead; History; Young Bukharans; Bukharan People’s Soviet Republic; Bukharan Socialist Soviet Republic; Geography of partition — Bukhara operation (1920): The Battle; Aftermath',
    }),
    term({
        id: 'khorezm-peoples-soviet-republic', ko: '호레즘 인민소비에트공화국', en: 'Khorezm People’s Soviet Republic', category: 'party-state', period: '1920–1924', startYear: 1920, endYear: 1924,
        definition: ['1920년 2월 2일 칸이 퇴위한 히바 칸국을 이어 4월 26일 제1차 호레즘 쿠릴타이가 선포한 소비에트 공화국. 수도는 히바였고, 사유재산을 인정한 헌법 아래 1920년 9월 러시아와의 조약으로 독립을 인정받았다. 1923년 10월 호레즘 사회주의 소비에트 공화국이 되었으며, 1924년 10월 27일 민족 경계 획정으로 우즈베크 SSR·투르크멘 SSR·카라칼파크 자치주에 나뉘어 들어갔다.',
            'The Soviet republic proclaimed by the First Khorezm Kurultai on 26 April 1920 as successor to the Khanate of Khiva, whose khan had abdicated on 2 February. With Khiva as its capital and a constitution that preserved private property, it was recognised as independent by a treaty with Russia in September 1920. It became the Khorezm Socialist Soviet Republic in October 1923, and in the national delimitation of 27 October 1924 it was divided among the Uzbek SSR, the Turkmen SSR and the Karakalpak Autonomous Oblast.'],
        body: ['히바 칸국에서는 1918년 투르크멘 요무트 부족 지도자 주나이드 칸이 칸 아스판디야르를 죽이고 허수아비 칸 사이드 압둘라를 앞세워 실권을 쥐었다. 그의 독재에 맞선 청년히바인은 주나이드에게 반대하는 투르크멘 지도자들과 손잡고 투르크코미시야에 도움을 청했고, 사실상 이 지역의 최고 권력이던 위원회는 군사 원정을 승인하고 대표 스칼로프를 보냈다. 붉은 군대는 1919년 12월 25일 아무다리야를 건넜고 1920년 1월 22~23일 주나이드의 근거지 베디르켄트를 점령했다. 스칼로프의 설득으로 사이드 압둘라는 2월 2일 퇴위 선언문에 서명했고, 청년히바인 술탄무라도프를 의장으로 투르크멘 지도자 두 명과 성직자·시민 대표가 참여한 임시정부가 섰다. 스칼로프는 히바가 러시아 「날개 아래서」 살 것이라는 전 칸의 말을 전하며, 실권은 러시아 대표부가 쥘 것이라고 보고했다. 4월 26일 블라디미르 레닌을 명예 의장으로 뽑은 쿠릴타이는 공화국을 선포하고, 토지와 생산 수단의 사유를 인정하고 착취 계급 일부에게도 선거권을 주는 헌법을 채택했다. 칸국 밖에서 만들어진 호레즘 공산당은 1920년 4월 당원이 600명에 그쳤다.\n\n1920년 9월 13일 러시아와 맺은 조약은 호레즘의 완전한 독립을 인정했다. 처음에는 샤리아 법정과 옛 방식의 학교, 와크프, 부족 장로(아크사칼)가 유지되었지만, 바이와 성직자, 우파 청년히바인의 저항이 이어졌고 주나이드는 1920년 9월과 1924년 1월 등 거듭 침입해 히바를 포위하기도 했다. 1922년 초 호레즘 공산당은 러시아 공산당에 편입되었고, 1923년 3월 투르키스탄·부하라·호레즘의 경제 통합으로 중앙아시아 경제회의가 생겼다. 면화 재배 면적은 1922년 8,740ha에서 1923년 3만 2,776ha로 늘었다. 1923년 10월 제4차 전호레즘 소비에트 대회는 공화국을 호레즘 사회주의 소비에트 공화국으로 바꾸었다. 면적 6만 2,200㎢의 이 나라 인구는 영어 출처로 60만여 명, 러시아어 출처로 약 80만 명이었고, 우즈베크인이 60%를 넘고 투르크멘인이 약 29%였다. 정부 관리들은 경계 획정에 강하게 반대했지만 굴복할 수밖에 없었고, 제5차 대회(1924년 9월 29일~10월 2일)가 자진 해체를 의결했다.',
            'In the Khanate of Khiva the Yomut Turkmen chief Junaid Khan had killed Asfandiyar Khan in 1918 and taken real power behind a puppet khan, Sayyid Abdullah. The Young Khivans, opponents of his dictatorship, joined Turkmen chiefs hostile to Junaid and appealed to the Turkkomissiya, which, as the de facto supreme authority in the region, sanctioned a military expedition and sent its envoy Skalov. The Red Army crossed the Amu Darya on 25 December 1919 and on 22–23 January 1920 took Junaid’s seat at Bedirkend. Persuaded by Skalov, Sayyid Abdullah signed a manifesto of abdication on 2 February, and a provisional government took office under the Young Khivan Sultan-Muradov with two Turkmen chiefs and representatives of the clergy and townspeople. Skalov passed on the former khan’s remark that Khiva would live “under your wing” and reported that real power would lie with the Russian mission. On 26 April the Kurultai, which elected Vladimir Lenin its honorary chairman, proclaimed the republic and adopted a constitution that recognised private ownership of land and the means of production and gave the vote to part of the exploiting classes. The Khorezm Communist Party, founded outside the khanate, had only 600 members in April 1920.\n\nA treaty with Russia on 13 September 1920 recognised Khorezm’s full independence. Sharia courts, old-method schools, waqf and tribal elders (aksakals) were kept at first, but the bais, the clergy and the right-wing Young Khivans resisted, and Junaid invaded again and again, in September 1920 and in January 1924, when he besieged Khiva. In early 1922 the Khorezm Communist Party was admitted to the Russian Communist Party, and in March 1923 the economic union of Turkestan, Bukhara and Khorezm created the Central Asian Economic Council. The area under cotton rose from 8,740 hectares in 1922 to 32,776 in 1923. In October 1923 the Fourth All-Khorezm Congress of Soviets turned the state into the Khorezm Socialist Soviet Republic. The country covered 62,200 square kilometres, with a population of over 600,000 according to the English-language source and about 800,000 according to the Russian-language one; more than 60 per cent were Uzbeks and about 29 per cent Turkmens. Its officials fervently opposed the delimitation but were forced to concede, and the Fifth Congress (29 September–2 October 1924) voted for the republic’s self-dissolution.'],
        aliases: { ko: ['호레즘 인민공화국', '호레즘 인민소비에트 공화국', '호레즘 사회주의 소비에트 공화국'], en: ['Khorezm People\'s Soviet Republic', 'Khorezm People’s Republic', 'Khorezm People\'s Republic', 'Khorezm Socialist Soviet Republic', 'Khorezm SSR'] },
        people: ['junaid-khan', 'lenin'],
        events: ['central-asia-1917-1924', 'civil-war', 'ussr-formation'],
        sources: [S.khorezmRu, S.khorezm, S.khivaOpRu, S.junaidRu], locator: 'ru: преамбула; Расположение и география; История — en: lead; Geography — ru Хивинская операция: преамбула; Ход операции; Результаты — ru Джунаид-хан: Продолжение борьбы',
    }),
    term({
        id: 'persian-socialist-soviet-republic', ko: '길란 소비에트 공화국', en: 'Soviet Republic of Gilan', category: 'international', period: '1920–1921', startYear: 1920, endYear: 1921,
        definition: ['1920년 6월 5일 이란 북부 길란주의 라슈트에서 미르자 쿠착 칸의 정글리 운동이 붉은 군대의 지원을 받아 선포한 소비에트 공화국. 국제적으로 승인받지 못했고, 1921년 6월 페르시아 사회주의 소비에트 공화국으로 이름을 바꿨다. 소련이 이란 정부와 우호 조약을 맺고 군대를 거둔 뒤 공산주의자와 쿠착 칸 세력의 내분 속에 1921년 9월 끝났다.',
            'The Soviet republic proclaimed in Rasht, in the northern Iranian province of Gilan, on 5 June 1920 by Mirza Kuchik Khan’s Jungle movement with the support of the Red Army. Never recognised internationally, it was renamed the Persian Socialist Soviet Republic in June 1921. After Soviet Russia concluded a treaty of friendship with the Iranian government and withdrew its troops, it came to an end in September 1921 amid fighting between the communists and Kuchik Khan’s followers.'],
        body: ['길란의 숲에서 1914~1915년 시작된 정글리(잔갈리) 운동은 지방 자치와 외세 간섭 중단, 토지 개혁을 요구하며 영국과 이란 정부에 맞서 왔다. 1920년 5월 18일 표도르 라스콜니코프와 그리고리 오르조니키제가 이끈 소비에트 카스피 함대가 데니킨의 백군이 끌고 간 함선을 되찾으려 엔젤리에 들어오자, 영국 수비대는 저항 없이 만질로 물러났다. 종교와 페르시아 민족주의 배경 때문에 망설이던 쿠착 칸은 자신이 공화국을 이끌고 소비에트가 내정에 직접 간섭하지 않는다는 조건으로 볼셰비키와 손잡았다. 6월 4일 정글리 부대가 라슈트를 차지했고 이튿날 공화국이 선포되었다. 쿠착 칸이 수반을, 세예드 자파르 피셰바리가 외무 인민위원을 맡았고, 혁명군사평의회와 페르시아 붉은 군대가 꾸려졌다. 그러나 공화국은 빈농에게 땅을 나눠 주지 않았고, 바쿠의 아달라트당에서 자라난 페르시아 공산당과 쿠착 칸 사이에 곧 갈등이 일었다. 러시아어 출처에 따르면 1920년 8월 공화국 군대는 테헤란을 바라보며 이웃 잔잔주로 진격했다가 이란군에 격퇴되었다.\n\n쿠착 칸은 6월 9일 충돌을 피해 라슈트를 떠났고, 정글리 운동 문서에 따르면 7월 31일 정변으로 밀려났다. 이름뿐인 에흐산올라 칸 정부의 실권은 소비에트 위원 아부코프에게 있었고, 반종교 선전과 지주 재산 강탈 같은 급진 조치와 몰려든 피란민은 중간층의 등을 돌리게 했다. 1920년 9월 러시아 정부는 이란에서의 군사 작전을 접고 국왕 정부와 협상하기로 했고, 1921년 2월 26일 소련-페르시아 우호 조약에 따라 소비에트 군대는 4월부터 철수해 9월 8일 모두 떠났다. 테헤란 주재 소비에트 대사 표도르 로트시테인은 카즈빈으로 향하던 에흐산올라 칸 부대의 소비에트 장교들에게 명령을 따르지 말라고 전했다. 1921년 5월 다시 정부를 맡은 쿠착 칸은 9월 29일 공산당 지도자 헤이다르 칸 아무오글루를 죽였고, 내전 속에 정부군이 라슈트를 차지했다. 쿠착 칸은 산으로 달아나다 얼어 죽었다. 붕괴 원인을 두고 코스로 샤케리는 세계 혁명에서 소비에트 국가의 안전으로 옮겨 간 모스크바의 정책 전환을, 카이한 네자드는 공산주의자와 비공산주의자 사이의 내분을 먼저 꼽는다.',
            'The Jungle (Jangali) movement, launched in the forests of Gilan in 1914–1915, had fought the British and the Iranian government, demanding provincial autonomy, an end to foreign interference and land reform. On 18 May 1920 the Soviet Caspian flotilla under Fyodor Raskolnikov and Grigory Ordzhonikidze entered Enzeli to recover the ships taken there by Denikin’s Whites, and the British garrison fell back to Manjil without resistance. Kuchik Khan, hesitant because of his religious and Persian nationalist background, joined the Bolsheviks on condition that he would lead the republic and that the Soviets would not interfere directly in its internal affairs. The Jangalis took Rasht on 4 June and proclaimed the republic the next day. Kuchik Khan became its head and Seyyed Jafar Pishevari commissar for foreign affairs, and a Revolutionary Military Council and a Persian Red Army were formed. But the republic did not distribute land to poor peasants, and conflict soon broke out between Kuchik Khan and the Communist Party of Persia, which had grown out of the Baku-based Edalat party. According to the Russian-language source, the republic’s army advanced into neighbouring Zanjan province with an eye on Tehran in August 1920 but was driven back by Iranian troops.\n\nKuchik Khan left Rasht on 9 June to avoid a clash, and according to the article on the Jungle movement he was ousted in a coup on 31 July. Real power in the nominal government of Ehsanollah Khan lay with the Soviet commissar Abukov, and radical measures such as anti-religious propaganda and extortion from landlords, together with a flood of refugees, alienated the middle classes. In September 1920 the Russian government decided to wind up its military operation in Iran and negotiate with the Shah’s government, and under the Russo-Persian Treaty of Friendship of 26 February 1921 Soviet troops began leaving in April and were gone by 8 September. The Soviet envoy in Tehran, Fyodor Rothstein, told the Soviet officers in Ehsanollah Khan’s force heading for Qazvin not to obey his orders. Kuchik Khan, who had taken charge of the government again in May 1921, killed the communist leader Heydar Khan Amu-oghli on 29 September, and amid the civil war government troops took Rasht. Fleeing into the mountains, Kuchik Khan froze to death. On the causes of the collapse, Cosroe Chaqueri points to Moscow’s shift from world revolution to the security of the Soviet state, while Kayhan Nejad puts the infighting between communists and non-communists first.'],
        aliases: { ko: ['길란 사회주의 소비에트 공화국', '페르시아 사회주의 소비에트 공화국', '페르시아 소비에트 사회주의 공화국', '길란 공화국'], en: ['Persian Socialist Soviet Republic', 'Persian Soviet Socialist Republic', 'Socialist Soviet Republic of Gilan', 'Gilan Republic', 'Gilan Soviet Republic'] },
        people: ['mirza-kuchik-khan', 'fyodor-raskolnikov', 'ordzhonikidze', 'yakov-blumkin', 'fyodor-rothstein', 'chicherin', 'lev-karakhan'],
        events: ['central-asia-1917-1924', 'civil-war'],
        sources: [S.pssr, S.gilanRu, S.jungle], locator: 'lead; Background and history; Declaration of the republic; Coup d\'état; Historical analysis — ru: преамбула; Предыстория; История; Падение республики — Jungle Movement of Gilan: Resumption of hostilities and Gilan SSR (1918–20); Fall of the Gilan SSR (1920–21)',
    }),
    term({
        id: 'turkkomissiya', ko: '투르크코미시야', en: 'Turkkomissiya', category: 'party-state', period: '1919–1920', startYear: 1919, endYear: 1920,
        definition: ['1919년 2월 러시아 소브나르콤이 투르키스탄 문제를 맡기려 만든 특별 위원회로, 정식 이름은 전러시아 중앙집행위원회·러시아 소브나르콤 투르키스탄 위원회다. 1919년 10월부터 볼셰비키 중앙위원회의 권한까지 위임받아 투르키스탄 공화국의 당과 국가를 지도하며 사실상 이 지역의 최고 권력으로 활동했고, 1920년 8월 해산되어 볼셰비키 중앙위원회 투르키스탄 뷰로가 그 일을 이었다.',
            'A special commission set up by the Russian Sovnarkom in February 1919 to handle Turkestan affairs, formally the Turkestan Commission of the All-Russian Central Executive Committee and the Sovnarkom of the RSFSR. From October 1919, holding powers delegated by the Bolshevik Central Committee as well, it directed the party and state of the Turkestan republic and acted in effect as the supreme authority in the region; it was dissolved in August 1920, and the Turkestan Bureau of the Bolshevik Central Committee took over its work.'],
        body: ['위원회는 1919년 2월 12일 그루지야 볼셰비키 샬바 엘리아바를 의장으로 만들어졌다. 그러나 투르키스탄은 내전의 전선에 막혀 러시아 중앙과 끊겨 있었고 길은 콜차크의 백군이 쥐고 있었기 때문에, 위원회는 사마라와 오렌부르크에 머물렀고 콜차크의 공세 속에 활동을 잠시 접었다. 1919년 8월 투르키스탄 전선이 생기고 붉은 군대가 투르키스탄에서 승리를 거둔 뒤, 10월부터 위원회는 당 지도를 맡아 본격적으로 활동했다. 발레리안 쿠이비셰프는 1919년 10월부터 1920년 8월까지 전러시아 중앙집행위원회·소브나르콤·볼셰비키 중앙위원회의 투르키스탄 문제 담당 부의장이자 투르키스탄 전선 혁명군사평의회 위원이었다. 위원회의 주도로 1919년 말 투르키스탄 공화국의 주(州) 구획과 주 소비에트 기관이 되살아났고, 1920년 1월 투르키스탄 공산당 창설에 직접 관여했으며, 3월에는 얀 루주타크를 의장으로 투르키스탄 소브나르콤을 다시 세웠다. 1920년 2~12월 투르크코미시야 앞으로만 국민경제용 화물 614량이 도착했고, 투르키스탄은 면화·양모·과일을 중앙에 보냈다. 히바의 청년히바인과 투르크멘 지도자들이 도움을 청하자 위원회는 군사 원정을 승인하고 대표 스칼로프를 보내 1920년 2월 칸의 퇴위를 이끌어 냈다.\n\n위원회와 투르키스탄 공산당 지역위원회는 정착민의 「대국 쇼비니즘」과 당내 민족주의 경향을 함께 상대했다. 투라르 리스쿨로프가 이끈 무슬림 뷰로 쪽은 투르키스탄 소비에트 공화국을 「튀르크 공화국」으로, 투르키스탄 공산당을 「튀르크 공산당」으로 바꾸고, 비무슬림 붉은 군대 부대를 철수시켜 원주민만으로 군대를 꾸리자고 요구했다. 볼셰비키 중앙위원회는 1920년 3월 8일 「투르키스탄 자치에 관한 규정」으로 당의 이름과 투르키스탄이 「러시아 연방의 자치 공화국」이라는 지위를 재확인하고, 국방·대외 관계·철도·우편·재정을 연방 정부에 남겼다. 5월 모스크바에 간 리스쿨로프 등의 대표단은 당의 민족 정책에 어긋난다는 이유로 거부당했고, 7월 볼셰비키 중앙위원회 투르키스탄 뷰로가 만들어졌다. 위원회는 1920년 8월 해산되었고, 9월 제9차 투르키스탄 소비에트 대회는 「민족 일탈파」를 규탄하고 새 헌법을 채택했다.',
            'The commission was created on 12 February 1919 with the Georgian Bolshevik Shalva Eliava as chairman. But Turkestan was cut off from central Russia by the Civil War front, the routes were held by Kolchak’s Whites, and so the commission stopped in Samara and then Orenburg and suspended its work during Kolchak’s offensive. After the Turkestan Front was formed in August 1919 and the Red Army won its victories in Turkestan, the commission took up its work in earnest from October, charged with leading the party. Valerian Kuibyshev served from October 1919 to August 1920 as deputy chairman for Turkestan affairs of the All-Russian Central Executive Committee, the Sovnarkom and the Bolshevik Central Committee and as a member of the Turkestan Front’s Revolutionary Military Council. On its initiative the provincial divisions of the Turkestan republic and their Soviet organs were restored at the end of 1919; it took a direct part in founding the Communist Party of Turkestan in January 1920, and in March it re-established the Turkestan Sovnarkom under Jānis Rudzutaks. Between February and December 1920 the Turkkomissiya alone received 614 wagons of goods for the economy, while Turkestan sent cotton, wool and fruit to the centre. When the Young Khivans and Turkmen chiefs asked for help, the commission sanctioned a military expedition and sent its envoy Skalov, who brought about the khan’s abdication in February 1920.\n\nThe commission and the regional committee of the Communist Party of Turkestan fought both the “great-power chauvinism” of the settlers and nationalist tendencies within the party. The Muslim Bureau led by Turar Ryskulov demanded that the Turkestan Soviet Republic be renamed a “Turkic Republic” and the Communist Party of Turkestan a “Turkic Communist Party”, that non-Muslim Red Army units be withdrawn and that an army be formed of natives alone. In its “Regulation on the autonomy of Turkestan” of 8 March 1920 the Bolshevik Central Committee reaffirmed the party’s name and Turkestan’s status as an “autonomous republic of the RSFSR”, reserving defence, foreign relations, railways, posts and finance to the federal government. A delegation including Ryskulov that went to Moscow in May was rebuffed as contrary to the party’s nationalities policy, and in July the Turkestan Bureau of the Bolshevik Central Committee was set up. The commission was dissolved in August 1920, and in September the Ninth Congress of Soviets of Turkestan condemned the “national deviationists” and adopted a new constitution.'],
        aliases: { ko: ['투르키스탄 위원회', '투르크 위원회'], en: ['Turkestan Commission', 'Turkkomissiia', 'Turkkomissia'] },
        people: ['kuibyshev', 'rudzutak', 'turar-ryskulov'],
        events: ['central-asia-1917-1924', 'civil-war'],
        sources: [S.eliavaRu, S.tassrRu, S.kuibyshevRu, S.khivaOpRu], locator: 'ru Элиава: Гражданская война — ru Туркестанская АССР: Помощь РСФСР; Борьба с политическими противниками; Внутриполитическая борьба в КПТ; 9-й съезд Советов Туркестана — ru Куйбышев: Гражданская война — ru Хивинская операция: преамбула; Результаты',
    }),
];
