// Person cards for the bessarabia-1917-1924 event (revolution in Bessarabia and
// union with Romania, 1917–1924), see lib.js person(). Excerpts are verbatim
// from the cited pages (en/ro/ru Wikipedia as fetched 2026-10-04).
// Bodies with no catalog affiliation (Sfatul Țării, the Moldavian Democratic
// Republic and its Council of Directors General, the National Moldavian Party,
// the newspaper Cuvânt moldovenesc) stay unresolved; state-moldova covers only
// the state from 1991.
// Native names: the four Bessarabian politicians in Romanian (Latin script),
// Klyushnikov in Russian Cyrillic without the patronymic. The four carry
// Romanian citizenship with Moldovan origin (born in present-day Moldova);
// Klyushnikov, born in Ryazan Governorate, Soviet citizenship with Russian origin.
const { W, person } = require('../lib');

const E = t => W(encodeURI(t));
const RU = t => 'https://ru.wikipedia.org/wiki/' + encodeURI(t);
const RO = t => 'https://ro.wikipedia.org/wiki/' + encodeURI(t);
const S = {
    inculet: E('Ion_Inculeț'),
    inculetRU: RU('Инкулец,_Ион_Константинович'),
    mdr: E('Moldavian_Democratic_Republic'),
    mdrRU: RU('Молдавская_демократическая_республика'),
    sfat: E('Sfatul_Țării'),
    sfatRU: RU('Сфатул_Цэрий'),
    union: E('Union_of_Bessarabia_with_Romania'),
    erhan: E('Pantelimon_Erhan'),
    erhanRO: RO('Pantelimon_Erhan'),
    erhanRU: RU('Ерхан,_Пантелеймон_Васильевич'),
    halippa: E('Pan_Halippa'),
    halippaRO: RO('Pantelimon_Halippa'),
    pelivan: E('Ion_Pelivan'),
    pelivanRO: RO('Ion_Pelivan'),
    klyush: E('Andrey_Klyushnikov'),
    klyushRU: RU('Клюшников,_Андрей_Иванович'),
    tatar: E('Tatarbunary_Uprising'),
};

const unaffiliated = card => ({
    ...card,
    activities: card.activities.map(a => (a.affiliationId ? a : { ...a, affiliationStatus: 'unresolved', relation: 'unresolved' })),
});

module.exports = [
    unaffiliated(person({
        id: 'ion-inculet', groupId: 'world-interwar',
        given: ['이온', 'Ion'], family: ['인쿨레츠', 'Inculeț'], nativeName: 'Ion Inculeț', years: '1884–1940',
        citizenship: 'romania', origin: 'moldova',
        epithet: ['스파툴 처리이 의장으로 몰다비아 민주공화국을 이끌고 루마니아 합병을 성사시킨 베사라비아 정치가',
            'Bessarabian politician who presided over Sfatul Țării and the Moldavian Democratic Republic and saw through its union with Romania'],
        bio: ['1884년 베사라비아 러제니의 농민 집안에서 태어나 키시너우 신학교와 상트페테르부르크 대학을 마치고 기상 관측소 물리학자로 일했다. 2월 혁명 뒤 사회혁명당에 들어가 페트로그라드 소비에트 의원이 되었고, 케렌스키가 그를 러시아 임시정부의 베사라비아 대표로 보냈다. 처음에는 베사라비아가 러시아에 남아야 한다고 했으나, 스파툴 처리이 의장이자 몰다비아 민주공화국 대통령으로서 1918년 4월 루마니아와의 합병 결의를 이끌었다. 합병 뒤 베사라비아 담당 국무장관이 되었고, 1923년 자기 계파를 이끌고 국민자유당에 들어가 보건·내무·통신 장관과 각료회의 부의장을 지냈다. 1940년 심장마비로 숨졌다.',
            'Born to a peasant family in Răzeni, Bessarabia, in 1884, he graduated from the Chișinău seminary and Saint Petersburg University and worked as a physicist at the Meteorological Observatory. After the February Revolution he joined the Socialist Revolutionary Party and sat in the Petrograd Soviet, and Kerensky sent him to Bessarabia as the Provisional Government’s representative. At first he said Bessarabia should remain part of Russia, but as president of Sfatul Țării and of the Moldavian Democratic Republic he steered the vote for union with Romania in April 1918. After the union he became Minister of State for Bessarabia; in 1923 he took his wing of the Bessarabian Peasants’ Party into the National Liberal Party, and he later served as minister of health, of the interior and of communications and as vice-president of the Council of Ministers. He died of a heart attack in 1940.'],
        fate: ['natural', '심장마비', 'Heart attack'],
        aliases: { ko: ['이온 콘스탄틴 인쿨레츠', '이온 건두'], en: ['Ion C. Inculeț', 'Ion Constantin Inculeț', 'Ion Inculet', 'Ion Gându'] },
        sources: [S.inculet, S.inculetRU, S.mdr, S.sfatRU],
        facts: {
            years: { claim: '1884–1940', locator: 'lead', excerpt: '5 April [O.S. 24 March] 1884 – 18 November 1940' },
            citizenship: { claim: 'Bessarabian and Romanian politician', locator: 'lead', excerpt: 'was a Bessarabian and Romanian politician' },
            nationalOrigin: { claim: 'born in Răzeni, Bessarabia', locator: 'Biography', excerpt: 'Ion Inculeț was born on 5 April 1884 in Răzeni village' },
            bio: [
                { claim: 'born to a peasant family', locator: 'Biography', excerpt: 'in the family of Constantin and Maria Inculeț (née Ionaș), who were peasants' },
                { claim: 'graduated from the Chișinău seminary in 1905', locator: 'Education', excerpt: 'He graduated from the seminary in June 1905' },
                { claim: 'graduated from Saint Petersburg University in 1911', locator: 'Education', excerpt: 'he graduated from the university in 1911 with a first-class diploma' },
                { claim: 'physicist at the Meteorological Observatory', locator: 'Early career', excerpt: 'worked as a physicist at the Meteorological Observatory' },
                { claim: 'joined the Socialist Revolutionary Party in 1917', locator: 'February Revolution and Petrograd', excerpt: 'who was a supporter of socialist ideas, joined the Socialist Revolutionary Party' },
                { claim: 'deputy of the Petrograd Soviet for the SRs', source: S.inculetRU, locator: 'Биография', excerpt: 'был депутатом Петроградского совета от партии эсэров' },
                { claim: 'sent by Kerensky as Provisional Government representative', source: S.inculetRU, locator: 'Биография', excerpt: '25 мая 1917 года Ион Инкулец был назначен Александром Керенским представителем Временного правительства в Бессарабии.' },
                { claim: 'said Bessarabia should remain part of Russia', locator: 'February Revolution and Petrograd', excerpt: 'stating that Bessarabia should remain part of Russia' },
                { claim: 'president of Sfatul Țării and of the Republic', source: S.mdr, locator: 'Leadership', excerpt: 'Ion Inculeț, the president of the Sfatul Țării and President of the Republic' },
                { claim: 'prepared the union vote with Marghiloman', locator: 'President of the Moldavian Democratic Republic', excerpt: 'to prepare for the vote on approving the Union of Bessarabia with Romania' },
                { claim: 'Minister of State for Bessarabia after the union', locator: 'Minister for Bessarabia', excerpt: "was appointed Minister of State for Bessarabia to Romania's Council of Ministers under Marghiloman" },
                { claim: 'his wing of the party joined the National Liberal Party in 1923', locator: 'After the Union', excerpt: 'In 1923, his wing of the party joined the National Liberal Party.' },
                { claim: 'later ministerial posts', locator: 'After the Union', excerpt: 'Ion Inculeț was minister of Bessarabia, minister of public health, minister of interior, minister of communications and the vice-president of the Council of Ministers in the Government of Romania' },
                { claim: 'died of a heart attack in 1940', locator: 'Personal life', excerpt: 'Inculeț died from a heart attack on 18 November 1940' },
            ],
        },
        activities: [
            { functionId: 'legislature', affiliationId: null, startYear: 1917, endYear: 1918, primary: true, claim: 'President of Sfatul Țării, the assembly of the Moldavian Democratic Republic (no catalog affiliation)', locator: 'lead', excerpt: 'He served as President of the Country Council of the Moldavian Democratic Republic' },
            { functionId: 'government', affiliationId: 'russian-provisional-government', startYear: 1917, endYear: 1917, claim: 'Assistant Government Commissioner of Bessarabia for the Provisional Government', locator: 'February Revolution and Petrograd', excerpt: 'He was then appointed Assistant Government Commissioner of Bessarabia.' },
            { functionId: 'political-leadership', affiliationId: 'russian-sr', relation: 'membership', startYear: 1917, endYear: 1917, claim: 'Member of the Socialist Revolutionary Party, expelled in late 1917', locator: 'February Revolution and Petrograd', excerpt: 'who was a supporter of socialist ideas, joined the Socialist Revolutionary Party' },
            { functionId: 'government', affiliationId: 'state-romania', startYear: 1918, endYear: 1920, claim: 'Minister of State for Bessarabia in the Romanian Council of Ministers', locator: 'Minister for Bessarabia', excerpt: "was appointed Minister of State for Bessarabia to Romania's Council of Ministers under Marghiloman" },
            { functionId: 'government', affiliationId: 'state-romania', startYear: 1933, endYear: 1937, claim: 'Minister of the Interior of Romania under Duca and Tătărescu', locator: 'Various ministries and Duca', excerpt: 'Following this, Duca appointed Inculet as Minister of the Interior.' },
        ],
        career: [
            ['1915', '상트페테르부르크 기상 관측소 물리학자', 'Physicist at the Meteorological Observatory, Saint Petersburg'],
            ['1917', '페트로그라드 소비에트 의원(사회혁명당)', 'Member of the Petrograd Soviet (Socialist Revolutionary Party)'],
            ['1917', '러시아 임시정부의 베사라비아 판무관 대리', 'Assistant Government Commissioner of Bessarabia'],
            ['1917–1918', '스파툴 처리이 의장, 몰다비아 민주공화국 대통령', 'President of Sfatul Țării and of the Moldavian Democratic Republic'],
            ['1918–1920', '루마니아 베사라비아 담당 국무장관', 'Romanian Minister of State for Bessarabia'],
            ['1927–1928', '루마니아 보건·사회보호 장관', 'Romanian Minister of Health and Social Protection'],
            ['1933', '루마니아 내무장관(두카 내각)', 'Romanian Minister of the Interior (Duca cabinet)'],
            ['1936', '루마니아 각료회의 부의장', 'Vice-President of the Romanian Council of Ministers'],
        ],
    })),
    unaffiliated(person({
        id: 'pantelimon-erhan', groupId: 'world-interwar',
        given: ['판텔리몬', 'Pantelimon'], family: ['에르한', 'Erhan'], nativeName: 'Pantelimon Erhan', years: '1884–1971',
        citizenship: 'romania', origin: 'moldova',
        epithet: ['몰다비아 민주공화국의 첫 정부인 총국장 위원회를 이끌며 토지개혁을 앞세운 베사라비아 사회혁명당원',
            'Bessarabian Socialist Revolutionary who headed the first government of the Moldavian Democratic Republic and put land reform first'],
        bio: ['1884년 베사라비아 터너타리에서 태어나 키시너우 신학교와 상트페테르부르크 대학 문학부를 마치고 교사로 일했다. 사회혁명당원으로 1917년 케렌스키의 권유를 받아 인쿨레츠와 함께 베사라비아에 돌아왔고, 현 농민 소비에트 의장과 러시아 제헌의회 의원으로 뽑혔다. 1917년 12월 몰다비아 민주공화국의 첫 정부인 총국장 위원회 의장 겸 농업 총국장이 되어 토지개혁을 앞세웠다. 공화국 이름을 다수 민족의 이름으로 짓자는 그의 주장이 이겼고, 루마니아군 도입 안을 표결에 부쳤으나 지주들이 군대로 토지개혁을 막을까 염려해 주둔에 항의하기도 했다. 합병에 찬성했지만 친러시아적이라는 비난 속에 물러났고, 뒤에 루마니아 상원의원을 지냈다. 1940년 부쿠레슈티로 피해 1971년 숨졌다.',
            'Born in Tănătari, Bessarabia, in 1884, he graduated from the Chișinău seminary and the Faculty of Letters in Saint Petersburg and taught. A Socialist Revolutionary, he returned to Bessarabia in 1917 with Inculeț at Kerensky’s urging and was elected chairman of the governorate peasants’ soviet and to the Russian Constituent Assembly. In December 1917 he became President of the Council of Directors General, the Moldavian Democratic Republic’s first government, and Director General for Agriculture, putting land reform first. His view that the republic should bear the majority people’s name prevailed; he put the entry of Romanian troops to a vote, yet protested their presence, fearing they would be used to block land reform. He voted for union but resigned amid charges of a pro-Russian stance, and later sat in the Romanian Senate. He fled to Bucharest in 1940 and died there in 1971.'],
        fate: ['natural', '사망', 'Died'],
        aliases: { ko: [], en: [] },
        sources: [S.erhan, S.erhanRO, S.erhanRU, S.mdrRU],
        facts: {
            years: { claim: '1884–1971', locator: 'lead', excerpt: 'Pantelimon Erhan (1884 – April/May 1971)' },
            citizenship: { claim: 'became a Romanian citizen after the union', source: S.erhanRU, locator: 'lead', excerpt: 'После её вхождения в состав Румынии стал гражданином Румынии.' },
            nationalOrigin: { claim: 'born in Tănătari, Bessarabia', locator: 'Biography', excerpt: 'Pantelimon Erhan was born in 1884 in Tănătari, Căușeni District.' },
            bio: [
                { claim: 'graduated from the Chișinău seminary and the Faculty of Letters in Saint Petersburg', source: S.erhanRO, locator: 'Biografie', excerpt: 'Este absolvent al Seminarului Teologic din Chișinău și Facultății de Litere din Sankt Petersburg' },
                { claim: 'returned to Bessarabia with Inculeț at Kerensky’s urging', source: S.erhanRO, locator: 'Biografie', excerpt: 'Se întoarce, la îndemnul președintelui Guvernului Provizoriu Al. Kerenski, în Basarabia, impreună cu Ion C. Inculeț' },
                { claim: 'member of the Socialist Revolutionary Party', source: S.erhanRO, locator: 'Biografie', excerpt: 'Membru al Partidului Socialist-Revoluționar.' },
                { claim: 'chairman of the governorate Soviet of Peasants’ Deputies', source: S.erhanRU, locator: 'Биография', excerpt: 'В 1917 году избран председателем Бессарабского губернского Совета крестьянских депутатов.' },
                { claim: 'elected to the Russian Constituent Assembly', locator: 'Prime minister', excerpt: 'Pantelimon Erhan was elected in the Russian Constituent Assembly' },
                { claim: 'President of the Council of Directors General and Director General for Agriculture', locator: 'Prime minister', excerpt: 'with Pantelimon Erhan as President of the Council of Directors General and Director General for Agriculture' },
                { claim: 'land reform the government’s cornerstone', locator: 'Prime minister', excerpt: 'Agrarian reform was a cornerstone priority of the Moldavian Democratic Republic government.' },
                { claim: 'his view on the republic’s name prevailed', source: S.mdrRU, locator: 'Провозглашение', excerpt: 'Но победила точка зрения П. Ерхана' },
                { claim: 'put the entry of Romanian troops to a vote', source: S.mdrRU, locator: 'Политическая ситуация в республике', excerpt: 'П. Ерхан поставил на голосование вопрос о необходимости ввода румынских войск' },
                { claim: 'protested the Romanian troops’ presence over land reform', locator: 'Prime minister', excerpt: 'they feared that the Romanian government, dominated by large land owners, could use the troops to prevent the envisaged agrarian reform' },
                { claim: 'voted for union; later senator', locator: 'Prime minister', excerpt: 'Erhan voted for the union of Bessarabia with Romania and was later elected in the Senate of Romania.' },
                { claim: 'resigned after charges of a pro-Russian stance', source: S.erhanRO, locator: 'Biografie', excerpt: 'acuzații în urma cărora și-a dat demisia, de atitudine pro-rusă și anti-unionistă' },
                { claim: 'fled to Bucharest in 1940', source: S.erhanRO, locator: 'Biografie', excerpt: 'pentru ca din 1940 să se refugieze la București' },
                { claim: 'died in Bucharest in 1971', locator: 'Biography', excerpt: 'He died in April or May 1971 in Bucharest.' },
            ],
        },
        activities: [
            { functionId: 'government', affiliationId: null, startYear: 1917, endYear: 1918, primary: true, claim: 'First prime minister of the Moldavian Democratic Republic (no catalog affiliation)', locator: 'Prime minister', excerpt: 'He was the first prime minister of the Moldavian Democratic Republic' },
            { functionId: 'political-leadership', affiliationId: 'russian-sr', relation: 'membership', startYear: 1917, endYear: 1918, claim: 'Member of the Socialist Revolutionary Party until his expulsion', source: S.erhanRO, locator: 'Biografie', excerpt: 'Membru al Partidului Socialist-Revoluționar.' },
            { functionId: 'education', affiliationId: 'state-romania', startYear: 1918, endYear: null, claim: 'Director general of education in Bessarabia after the union', source: S.erhanRO, locator: 'Biografie', excerpt: 'După Unire a fost director general al Învățământului în Basarabia' },
            { functionId: 'legislature', affiliationId: 'state-romania', startYear: null, endYear: null, claim: 'Member of the Romanian Senate', locator: 'Prime minister', excerpt: 'was later elected in the Senate of Romania' },
        ],
        career: [
            ['1917', '베사라비아 현 농민 소비에트 의장', 'Chairman of the Bessarabian Governorate Soviet of Peasants’ Deputies'],
            ['1917', '러시아 제헌의회 의원', 'Member of the Russian Constituent Assembly'],
            ['1917–1918', '몰다비아 민주공화국 총국장 위원회 의장 겸 농업 총국장', 'President of the Council of Directors General and Director General for Agriculture'],
            ['1918', '베사라비아 교육 총국장', 'Director General of Education in Bessarabia'],
        ],
    })),
    unaffiliated(person({
        id: 'pan-halippa', groupId: 'world-interwar',
        given: ['판', 'Pan'], family: ['할리파', 'Halippa'], nativeName: 'Pan Halippa', years: '1883–1979',
        citizenship: 'romania', origin: 'moldova',
        epithet: ['스파툴 처리이 부의장·의장으로 베사라비아의 루마니아 합병 운동을 이끈 언론인·정치가',
            'Journalist and politician who, as vice-president and later president of Sfatul Țării, led the movement for Bessarabia’s union with Romania'],
        bio: ['1883년 베사라비아 쿠볼타의 가난한 농민 집안에서 태어나 키시너우 신학교를 마치고 유리예프 대학에 들어갔으나 사회혁명당원이라 1905년 혁명 뒤 학업을 그만두었고, 잡지에 「깨어나라, 루마니아인이여!」를 실었다가 수배되어 이아시로 피해 1908~1912년 이아시 대학에서 공부했다. 1913년 신문 「몰도바의 말」을 펴내 합병을 주장했고, 1917년 몰도바 민족당 창당에 참여했다. 스파툴 처리이 부의장을 거쳐 의장이 되었다. 합병 뒤 베사라비아 담당 장관 등을 지내고 국민농민당에 들어갔으며, 1924년에는 루마니아 정부가 베사라비아를 「지옥」으로 만들었다고 비판했다. 1950년 체포되어 소련에서 25년 강제노동형을 받았고 1957년까지 갇혀 있다가 1979년 숨졌다.',
            'Born to poor peasants in Cubolta, Bessarabia, in 1883, he graduated from the Chișinău seminary and entered the University of Yuryev, but as a Socialist Revolutionary had to quit after the 1905 revolution. Sought by the Tsarist authorities after printing the hymn “Deșteaptă-te, române!”, he took refuge in Iași and studied there in 1908–1912. From 1913 he published the newspaper Cuvânt moldovenesc in Chișinău, writing unceasingly for union, and in 1917 he founded the Moldovan National Party. He was elected first vice-president, then president of Sfatul Țării. After 1918 he served as minister for Bessarabia and in other posts and joined the National Peasants’ Party; in 1924 he accused the Romanian government of turning Bessarabia into an “inferno”. Arrested in 1950, he was sentenced in the Soviet Union to 25 years’ hard labour, was held until 1957 and died in 1979.'],
        fate: ['natural', '사망', 'Died'],
        aliases: { ko: ['판텔리몬 할리파'], en: ['Pantelimon Halippa'] },
        sources: [S.halippa, S.halippaRO, S.union, S.sfatRU],
        facts: {
            years: { claim: '1883–1979', locator: 'lead', excerpt: '13 August [O.S. 1 August] 1883 – 30 April 1979' },
            citizenship: { claim: 'Bessarabian-born Romanian politician', locator: 'lead', excerpt: 'was a Bessarabian-born Romanian journalist and politician' },
            nationalOrigin: { claim: 'born in Cubolta, Bessarabia', locator: 'Biography', excerpt: 'Halippa was born to the poor peasants Nicolae and Paraschiva Halippa in Cubolta' },
            bio: [
                { claim: 'enrolled at the University of Yuryev after the seminary', locator: 'Education', excerpt: 'After graduating from seminary in 1904, he enrolled in the Faculty of Physics and Medicine of the University of Yuryev' },
                { claim: 'forced to quit as an SR member', locator: 'Education', excerpt: 'he was forced to quit university, because he was a member of the Socialist Revolutionary Party' },
                { claim: 'printed “Deșteaptă-te, române!” and was sought by the authorities', locator: 'Education', excerpt: 'which caused the Tsarist authorities to seek his arrest' },
                { claim: 'studied at the University of Iași, 1908–1912', locator: 'Education', excerpt: 'Taking refuge in Iași, he enrolled in the Faculty of Letters and Philosophy of the University of Iași, where he took classes from 1908 to 1912.' },
                { claim: 'published Cuvânt moldovenesc from 1913', locator: 'Education', excerpt: 'Returning to Chișinău in 1913, he published, together with Nicolae Alexandri and with the assistance of Vasile Stroescu, the newspaper Cuvânt moldovenesc' },
                { claim: 'wrote for union', locator: 'Education', excerpt: 'He wrote unceasingly in favour of union with Romania.' },
                { claim: 'founded the Moldovan National Party in 1917', locator: 'Political activity', excerpt: 'in 1917 he founded the Moldovan National Party' },
                { claim: 'vice-president, then president of Sfatul Țării', locator: 'Political activity', excerpt: 'he was elected first vice-president, then president of Sfatul Țării' },
                { claim: 'minister for Bessarabia, 1919–1920', locator: 'Political activity', excerpt: 'Minister and Secretary of State for Bessarabia (1919–1920)' },
                { claim: 'member of the National Peasants’ Party', locator: 'Political activity', excerpt: "He was a member of the National Peasants' Party after its founding in 1926." },
                { claim: 'called Bessarabia an “inferno” in 1924', source: S.union, locator: 'Greater Romania', excerpt: 'In 1924, Pan Halippa, a strong supporter of the Union in 1918, criticized the Romanian government for transforming Bessarabia into an "inferno"' },
                { claim: 'arrested in 1950', locator: 'Political activity', excerpt: 'In 1950 he was arrested and imprisoned without trial at Sighet prison' },
                { claim: 'sentenced to 25 years’ hard labour', locator: 'Political activity', excerpt: "sentenced to 25 years' hard labour in Siberia" },
                { claim: 'held at Aiud until 1957', locator: 'Political activity', excerpt: 'he was held at Aiud until 1957' },
                { claim: 'died in Bucharest in 1979', locator: 'Death', excerpt: 'He died in Bucharest in 1979 at the age of 95' },
            ],
        },
        activities: [
            { functionId: 'legislature', affiliationId: null, startYear: 1917, endYear: 1918, primary: true, claim: 'Vice-president, then president of Sfatul Țării (no catalog affiliation)', locator: 'Political activity', excerpt: 'he was elected first vice-president, then president of Sfatul Țării' },
            { functionId: 'political-leadership', affiliationId: 'russian-sr', relation: 'membership', startYear: 1905, endYear: null, claim: 'Member of the Socialist Revolutionary Party as a student', locator: 'Education', excerpt: 'because he was a member of the Socialist Revolutionary Party' },
            { functionId: 'propaganda', affiliationId: null, startYear: 1913, endYear: 1917, claim: 'Publisher and director of the newspaper Cuvânt moldovenesc (no catalog affiliation)', locator: 'Education', excerpt: 'the newspaper Cuvânt moldovenesc, which he directed after April 1917' },
            { functionId: 'political-leadership', affiliationId: null, startYear: 1917, endYear: null, claim: 'Founder of the Moldovan National Party (no catalog affiliation)', locator: 'Political activity', excerpt: 'in 1917 he founded the Moldovan National Party' },
            { functionId: 'government', affiliationId: 'state-romania', startYear: 1919, endYear: 1933, claim: 'Romanian minister for Bessarabia and of public works', locator: 'Political activity', excerpt: 'Minister and Secretary of State for Bessarabia (1919–1920), Minister of Public Works (1927)' },
            { functionId: 'legislature', affiliationId: 'state-romania', startYear: 1918, endYear: 1934, claim: 'Senator and deputy in the Romanian parliament', locator: 'Political activity', excerpt: 'senator and deputy in parliament (1918–1934)' },
        ],
        career: [
            ['1908–1912', '이아시 대학 문학·철학부 수학', 'Studies at the Faculty of Letters and Philosophy, University of Iași'],
            ['1913', '신문 「몰도바의 말」 창간', 'Launches the newspaper Cuvânt moldovenesc'],
            ['1917', '몰도바 민족당 창당', 'Founds the Moldovan National Party'],
            ['1917–1918', '스파툴 처리이 부의장, 이어 의장', 'Vice-president, then president of Sfatul Țării'],
            ['1919–1920', '루마니아 베사라비아 담당 장관 겸 국무장관', 'Romanian Minister and Secretary of State for Bessarabia'],
            ['1927', '루마니아 공공사업 장관', 'Romanian Minister of Public Works'],
            ['1950–1957', '체포·투옥(시게트, 소련 강제노동, 아이우드)', 'Arrest and imprisonment (Sighet, Soviet hard labour, Aiud)'],
        ],
    })),
    unaffiliated(person({
        id: 'ion-pelivan', groupId: 'world-interwar',
        given: ['이온', 'Ion'], family: ['펠리반', 'Pelivan'], nativeName: 'Ion Pelivan', years: '1876–1954',
        citizenship: 'romania', origin: 'moldova',
        epithet: ['몰다비아 민주공화국의 외무 총국장으로 루마니아 합병에 앞장선 베사라비아 민족운동의 고참 활동가',
            'Veteran of the Bessarabian national movement who, as foreign minister of the Moldavian Democratic Republic, championed union with Romania'],
        bio: ['1876년 베사라비아 러제니에서 태어나 1898년 키시너우 신학교를, 1903년 도르파트 대학 법학부를 마쳤다. 학생 단체를 만들었다가 체포되었고, 벌치에서 판사 대리로 일하며 그 도시 최초의 민족주의 단체를 꾸렸다. 1917년 몰도바 민족당에 참여했고, 스파툴 처리이 의장 선거에서 처음 과반을 얻었으나 자리는 인쿨레츠에게 돌아갔다. 1917~1918년 에르한·추구레아누 정부의 외무 총국장으로 이아시의 셰르바초프에게 군사 지원을 청했고 합병 운동에 앞장섰다. 합병 직후 바이다보에보드 정부의 법무장관을 지냈고 파리·런던·제네바에서 합병의 국제 승인을 위해 활동했으며, 국민당과 국민농민당 의원을 지냈다. 1950년 공산 당국에 체포되어 1954년 시게트 감옥에서 숨졌다.',
            'Born in Răzeni, Bessarabia, in 1876, he graduated from the Chișinău seminary in 1898 and in law from the University of Dorpat in 1903. Arrested as a student for founding an association of Bessarabian students, he later worked as a deputy judge in Bălți and created the town’s first national group. He joined the National Moldavian Party in 1917 and initially won a majority for president of Sfatul Țării, but the post went to Inculeț. As foreign minister in the Erhan and Ciugureanu cabinets in 1917–1918 he sought military aid from Shcherbachev in Iași and campaigned for union. He then served as Minister of Justice under Vaida-Voevod, worked in Paris, London and Geneva for recognition of the union and sat in parliament for the National Party and the National Peasants’ Party. Arrested by the communist authorities in 1950, he died in Sighet Prison in 1954.'],
        fate: ['natural', '옥사', 'Died in prison'],
        aliases: { ko: ['이온 게오르게 펠리반'], en: ['Ion Gheorghe Pelivan'] },
        sources: [S.pelivan, S.pelivanRO, S.inculet, S.sfat],
        facts: {
            years: { claim: '1876–1954', locator: 'lead', excerpt: 'April 1, 1876 – January 25, 1954' },
            citizenship: { claim: 'Romanian politician', locator: 'lead', excerpt: 'was a Romanian politician' },
            nationalOrigin: { claim: 'born in Răzeni, Bessarabia', locator: 'lead', excerpt: 'He was born in Răzeni, Bessarabia' },
            bio: [
                { claim: 'seminary 1898, law degree from Tartu 1903', locator: 'lead', excerpt: 'He graduated in 1898 from the Theological Seminary of Chișinău and in 1903 he received a law degree from the University of Tartu.' },
                { claim: 'arrested as a student for founding a Bessarabian students’ association', source: S.pelivanRO, locator: 'Biografie', excerpt: 'În perioada studenției a fost arestat și închis, pentru că a fondat o asociație a studenților basarabeni.' },
                { claim: 'deputy judge in Bălți and founder of its first national group', source: S.pelivanRO, locator: 'Biografie', excerpt: 'A fost locțiitor de judecător al orașului Bălți și creatorul primei grupări naționale din acest oraș' },
                { claim: 'member of the National Moldavian Party', source: S.sfat, locator: 'Prelude and organization', excerpt: 'Pan Halippa (a renowned socialist), Onisifor Ghibu, Daniel Ciugureanu, Ion Pelivan' },
                { claim: 'initially won a majority for president of Sfatul Țării', source: S.inculet, locator: 'President of the Sfatul Țării', excerpt: 'Pelivan had initially received a majority of the votes' },
                { claim: 'foreign minister in the Erhan and Ciugureanu cabinets', locator: 'lead', excerpt: 'During 1917–1918, Pelivan served as Foreign Minister of the Moldavian Democratic Republic in the Pantelimon Erhan Cabinet and the Daniel Ciugureanu Cabinet.' },
                { claim: 'sought military aid from Shcherbachev in Iași', source: S.inculet, locator: 'President of the Moldavian Democratic Republic', excerpt: 'Ion Pelivan sought military aid from a leader of the White Movement' },
                { claim: 'campaigned for union with Romania', source: S.pelivanRO, locator: 'Biografie', excerpt: 'a militat activ pentru unirea acesteia cu România' },
                { claim: 'Minister of Justice in the Vaida-Voevod government', source: S.pelivanRO, locator: 'Biografie', excerpt: 'Imediat după unire, a fost ministru al justiției în guvernul condus de Alexandru Vaida-Voievod.' },
                { claim: 'sent to Paris, London and Geneva for recognition of the union', source: S.pelivanRO, locator: 'Biografie', excerpt: 'Ion Pelivan a contribuit la recunoașterea internațională a unirii Basarabiei cu România, fiind trimis la Paris, Londra și Geneva.' },
                { claim: 'National Party and National Peasants’ Party deputy and senator', source: S.pelivanRO, locator: 'Biografie', excerpt: 'În perioada interbelică a făcut parte din Partidul Național Român, apoi din Partidul Național Țărănesc, fiind ales de mai multe ori deputat și senator în Parlamentul României.' },
                { claim: 'arrested in 1950, died in Sighet Prison in 1954', locator: 'lead', excerpt: 'He was arrested in May 1950 by the Romanian communist authorities and sent to Sighet Prison in Sighetu Marmației, where he died in 1954.' },
            ],
        },
        activities: [
            { functionId: 'diplomacy', affiliationId: null, startYear: 1917, endYear: 1918, primary: true, claim: 'Foreign minister (Director General for Foreign Affairs) of the Moldavian Democratic Republic (no catalog affiliation)', locator: 'lead', excerpt: 'Pelivan served as Foreign Minister of the Moldavian Democratic Republic in the Pantelimon Erhan Cabinet and the Daniel Ciugureanu Cabinet' },
            { functionId: 'law', affiliationId: 'state-romania', startYear: 1919, endYear: 1920, claim: 'Minister of Justice in the Vaida-Voevod government', source: S.pelivanRO, locator: 'Biografie', excerpt: 'a fost ministru al justiției în guvernul condus de Alexandru Vaida-Voievod' },
            { functionId: 'legislature', affiliationId: 'state-romania', startYear: null, endYear: null, claim: 'Deputy and senator in the Romanian parliament', source: S.pelivanRO, locator: 'Biografie', excerpt: 'fiind ales de mai multe ori deputat și senator în Parlamentul României' },
        ],
        career: [
            ['1903', '도르파트 대학 법학부 졸업', 'Law degree, University of Dorpat'],
            ['1917–1918', '몰다비아 민주공화국 외무 총국장', 'Director General for Foreign Affairs of the Moldavian Democratic Republic'],
            ['1919–1920', '루마니아 법무장관(바이다보에보드 내각)', 'Romanian Minister of Justice (Vaida-Voevod cabinet)'],
            ['1927–1936', '아스트라 협회 베사라비아 지부장', 'Head of the Bessarabian branch of ASTRA'],
            ['1950–1954', '시게트 감옥 수감', 'Imprisoned in Sighet Prison'],
        ],
    })),
    person({
        id: 'andrei-klyushnikov', groupId: 'bolshevik',
        given: ['안드레이', 'Andrei'], family: ['클류시니코프', 'Klyushnikov'], nativeName: 'Андрей Клюшников', years: '1892–1924',
        citizenship: 'soviet', origin: 'russia',
        epithet: ['네닌이라는 가명으로 남부 베사라비아에 혁명위원회를 조직하고 타타르부나리 봉기를 이끈 코민테른 요원',
            'Comintern agent known as Nenin who built revolutionary committees in southern Bessarabia and led the Tatarbunary Uprising'],
        bio: ['본명은 바실리 수로프이고 네닌·니닌으로 알려졌다. 1892년 랴잔현의 한 마을에서 태어나 페트로그라드 푸틸로프 공장에서 일했고, 군 의무병으로 제1차 세계대전 때 루마니아 전선에서 복무했다. 전쟁 뒤 볼셰비키에 합류했고, 1922년 5월부터 코민테른 요원으로 남부 베사라비아의 소련 직속 당위원회를 이끌며 카훌·이즈마일·아케르만 3개 군에 혁명위원회를 꾸렸다. 봉기가 시작되면 붉은 군대가 돕는다고 참가자들을 독려했고, 1924년 9월 15~16일 밤 타타르부나리에서 우크라이나 소비에트 공화국에 속하는 몰다비아 소비에트 공화국을 선포했다. 진압 때 영어 문서에 따르면 달아나다 헌병의 총에, 러시아어 문서에 따르면 마지막 전투에서 죽었다. 이름은 1967년에야 밝혀졌다.',
            'Born Vasily Surov and known as Nenin or Ninin, he was born in 1892 in a village of Ryazan Governorate, worked at the Putilov plant in Petrograd and, qualified as a military medical assistant, served on the Romanian Front in the First World War. After the war he joined the Bolsheviks, and from May 1922, as a Comintern agent, he led the Soviet-controlled party committee in southern Bessarabia, organising revolutionary committees in Cahul, Ismail and Cetatea Albă counties. He urged the participants to count on the Red Army once the rising began, and on the night of 15–16 September 1924 at Tatarbunary he proclaimed a Moldavian Soviet Republic as part of the Ukrainian SSR. In the suppression he was mortally wounded by a gendarme while fleeing, according to English Wikipedia, or fell in the last battle, according to Russian Wikipedia. His identity was established only in 1967.'],
        fate: ['killed', '전사', 'Killed in action'],
        aliases: { ko: ['네닌', '니닌', '바실리 수로프'], en: ['Nenin', 'Ninin', 'Vasily Surov', 'Andrey Klyushnikov'] },
        sources: [S.klyush, S.tatar, S.klyushRU],
        facts: {
            years: { claim: '1892–1924', locator: 'lead', excerpt: 'commonly known as Nenin or Ninin; 1892-1924' },
            citizenship: { claim: 'Soviet Bolshevik', locator: 'lead', excerpt: 'was a Soviet Bolshevik who took an important role in the Tatarbunary Uprising' },
            nationalOrigin: { claim: 'born in Ryazan Governorate', locator: 'lead', excerpt: 'Born in the village of Kuki (Sapozhkovsky Uyezd, Ryazan Governorate, part of the then Russian Empire)' },
            bio: [
                { claim: 'real name Vasily Surov', locator: 'lead', excerpt: 'whose real name was Vasily Surov' },
                { claim: 'worked at the Putilov plant', locator: 'lead', excerpt: 'he moved to Petrograd and worked at the Putilov plant' },
                { claim: 'military medical assistant on the Romanian Front', locator: 'lead', excerpt: 'During the First World War he provided medical care on the Romanian Front.' },
                { claim: 'joined the Bolsheviks after the war', locator: 'lead', excerpt: 'After the War he got involved in the Bolshevik movement' },
                { claim: 'led the Southern Bessarabian committee from May 1922 as a Comintern agent', source: S.tatar, locator: 'Local preparations', excerpt: 'In Southern Bessarabia, a Soviet Party Committee was created in May 1922 and the leaders were two Comintern agents' },
                { claim: 'revolutionary committees in three counties', source: S.tatar, locator: 'Local preparations', excerpt: 'members organized revolutionary committees in the three counties of Southern Bessarabia' },
                { claim: 'promised Red Army support', source: S.tatar, locator: 'Local preparations', excerpt: 'Nenin encouraged the participants to be bold and to count on support of the Soviet Army once the rebellion starts.' },
                { claim: 'proclaimed the Moldavian Soviet Republic', locator: 'lead', excerpt: 'he led a military uprising in and around the town of Tatarbunary proclaiming the Moldavian Soviet Republic as part of the Ukraine SSR' },
                { claim: 'mortally wounded by a gendarme while fleeing', source: S.tatar, locator: 'Romanian reaction', excerpt: 'Nenin ran towards the Black Sea marshes, but was surprised by a gendarme who mortally wounded him.' },
                { claim: 'killed in the last battle near Galilești', source: S.klyushRU, locator: 'Биография', excerpt: 'в котором погиб руководитель восстания Андрей Иванович Клюшников' },
                { claim: 'identity established in 1967', source: S.klyushRU, locator: 'lead', excerpt: 'Его имя благодаря активной краеведческой деятельности было установлено в 1967 году.' },
            ],
        },
        activities: [
            { functionId: 'organizing', affiliationId: 'comintern', relation: 'service', startYear: 1922, endYear: 1924, primary: true, claim: 'Comintern agent leading the Soviet party committee in southern Bessarabia', source: S.tatar, locator: 'Local preparations', excerpt: 'the leaders were two Comintern agents' },
            { functionId: 'military', affiliationId: 'comintern', relation: 'service', startYear: 1924, endYear: 1924, claim: 'Coordinator of the Comintern-planned rising in Bessarabia (Tatarbunary)', source: S.tatar, locator: 'Preparations', excerpt: 'Andrei Klyushnikov, also known as Nenin, was responsible for coordinating the action' },
        ],
        career: [
            ['1922–1924', '남부 베사라비아 혁명위원회(소련 직속 당위원회) 지도', 'Leader of the Soviet party committee in southern Bessarabia'],
            ['1924', '타타르부나리 봉기 지도', 'Leader of the Tatarbunary Uprising'],
        ],
    }),
];
