// 베사라비아의 혁명과 루마니아 합병 (1917.03–1924.10)
const E = t => 'https://en.wikipedia.org/wiki/' + encodeURI(t);
const RU = t => 'https://ru.wikipedia.org/wiki/' + encodeURI(t);
const P = (lat, lng, ko, en) => ({ kind: 'point', lat, lng, label: { ko, en } });
const S = {
  union: E('Union_of_Bessarabia_with_Romania'),
  mdr: E('Moldavian_Democratic_Republic'),
  sfat: E('Sfatul_Țării'),
  bess: E('Bessarabia'),
  gov: E('Bessarabia_Governorate'),
  khotyn: E('Khotyn_Uprising'),
  bender: E('Bender_Uprising'),
  bssr: E('Bessarabian_Soviet_Socialist_Republic'),
  tatar: E('Tatarbunary_Uprising'),
  massr: E('Moldavian_Autonomous_Soviet_Socialist_Republic'),
  rumch: E('Rumcherod'),
  paris: E('Treaty_of_Paris_(1920)'),
  question: E('Bessarabian_question'),
  moldovenism: E('Moldovenism'),
  inculet: E('Ion_Inculeț'),
  erhan: E('Pantelimon_Erhan'),
  halippa: E('Pan_Halippa'),
  pelivan: E('Ion_Pelivan'),
  klyush: E('Andrey_Klyushnikov'),
  kotovsky: E('Grigory_Kotovsky'),
  yakir: E('Iona_Yakir'),
  rakovsky: E('Christian_Rakovsky'),
  mdrRU: RU('Молдавская_демократическая_республика'),
  sfatRU: RU('Сфатул_Цэрий'),
  rumchRU: RU('Румчерод'),
  benderRU: RU('Бендерское_восстание'),
  khotynRU: RU('Хотинское_восстание'),
  annexRU: RU('Бессарабия_в_составе_Румынии'),
  tatarRU: RU('Татарбунарское_восстание'),
  massrRU: RU('Молдавская_Автономная_Советская_Социалистическая_Республика'),
};

module.exports = {
  sections: [
    {
      heading: { ko: "1917년의 베사라비아: 제국의 주에서 자치 요구로 {moldova russia}", en: "Bessarabia in 1917: from imperial province to the demand for autonomy {moldova russia}" },
      paragraphs: [
        {
          ko: "프루트강과 드네스트르강 사이의 베사라비아는 1812년 부쿠레슈티 조약으로 몰다비아 공국의 동쪽 절반이 러시아 제국에 넘어가면서 생긴 땅이다. 처음에는 상당한 자치를 누리는 주였지만 1828년 자치가 폐지되고 베사라비아현이 되었다. 19세기 동안 우크라이나인·러시아인·불가리아인·가가우스인·유대인·독일인 이주민이 들어와 1920년 무렵에는 슬라브계만 인구의 5분의 1을 넘었고, 1860년대 이후 학교와 교회에서 루마니아어가 금지되었다. 그 결과는 동화보다 문맹이었다. 1897년 글을 읽을 줄 아는 사람은 남성 18%, 여성 4%에 지나지 않았다. 제1차 세계대전에는 베사라비아 사람 30만 명이 러시아군에 동원되었다. 러시아어 위키백과가 전하는 20세기 초 인구 구성은 몰도바인이 다수였고 우크라이나인 약 20%, 유대인 11%, 러시아인 약 8%, 불가리아인 5%, 가가우스인 4%였다. 북쪽 끝 호틴 일대는 우크라이나인이 다수였을 가능성이 크고, 남쪽 부자크도 몰도바인이 적은 지역이었다. 이 구성이 1917~1924년의 모든 갈등에 지역마다 다른 색을 입혔다.",
          en: "Bessarabia, the land between the Prut and the Dniester, came into being in 1812, when the Treaty of Bucharest handed the eastern half of the Principality of Moldavia to the Russian Empire. At first an oblast with wide autonomy, it lost its self-government in 1828 and became the Bessarabia Governorate. Through the nineteenth century Ukrainian, Russian, Bulgarian, Gagauz, Jewish and German settlers arrived, so that by about 1920 Slavs alone made up more than a fifth of the population, and from the 1860s Romanian was banned in schools and in church. The result was illiteracy rather than assimilation: in 1897 only 18% of men and 4% of women could read. In the First World War 300,000 Bessarabians were mobilised into the Russian army. According to Russian Wikipedia, at the start of the century Moldavians were the majority, with about 20% Ukrainians, 11% Jews, about 8% Russians, 5% Bulgarians and 4% Gagauz. The Hotin district in the far north probably had a Ukrainian majority, and the southern Budjak had few Moldavians as well. That mix gave every conflict of 1917–1924 a different colour in each district.",
          sources: [S.union, S.gov, S.mdrRU],
        },
        {
          ko: "2월 혁명 뒤 베사라비아현 지사는 권한을 현 젬스트보 의장 콘스탄틴 미미에게 넘겼고, 미미는 러시아 임시정부의 판무관이 되었다. 마을마다 교사와 지식인이 이끄는 위원회가 생겼고, 4월 키시너우의 협동조합 대회는 정치·행정·교육·종교·경제 자치와 「스파툴 처리이」(나라의 평의회)라는 입법기관을 요구했다. 같은 달 귀족부터 사회주의자까지 아우른 몰도바 민족당이 바실레 스트로에스쿠를 당수로 세워졌고, 판 할리파와 이온 펠리반도 여기에 참여했다. 6월 교사 대회는 수업 언어를 러시아어에서 루마니아어로 바꾸고 라틴 문자를 쓰기로 했는데, 자신들은 「루마니아인」이 아니라 「몰도바인」이라며 항의한 이들도 있었다. 이 정체성 논쟁은 이후 내내 이어졌다. 7월 우크라이나 중앙 라다가 베사라비아를 우크라이나의 일부로 주장하자, 미미가 소집한 대표단과 몰도바 군인위원회, 그리고 오데사에 생긴 룸체로드가 일제히 항의했고 라다는 주장을 거두었다.",
          en: "After the February Revolution the governor handed his powers to Constantin Mimi, chairman of the governorate zemstvo, who became Commissar of the Russian Provisional Government. Committees led by teachers and intellectuals appeared in nearly every village, and in April a congress of cooperatives in Chișinău demanded political, administrative, educational, religious and economic autonomy and a legislature called Sfatul Țării, the Council of the Country. The same month the National Moldavian Party was founded under Vasile Stroescu, uniting nobles and socialists alike; Pan Halippa and Ion Pelivan were among its members. In June a teachers' congress voted to switch teaching from Russian to Romanian and to adopt the Latin alphabet, though some delegates protested that they were not \"Romanians\" but \"Moldavians\", a quarrel over identity that never went away. When the Ukrainian Central Rada claimed Bessarabia in July, a delegation convened by Mimi, the Moldavian soldiers' committees and the Rumcherod in Odessa all protested, and the Rada withdrew its claim.",
          sources: [S.sfat, S.mdr, S.moldovenism],
        },
        {
          ko: "혁명을 거리로 끌고 간 것은 군인과 농민이었다. 1917년 봄 오데사·키예프·세바스토폴과 루마니아 전선의 이아시 등에 「몰도바 군인 혁명위원회」가 생겼고, 5월 2일 오데사에서는 베사라비아 출신 병사 1만여 명이 모여 자치와 몰도바인 부대 편성을 요구했다. 루마니아 전선 총사령관 드미트리 셰르바초프는 5월 30일 몰도바인만으로 된 코호르트 16개를 만들어 베사라비아 9개 군에 배치하도록 허락했다. 무너지는 러시아군의 탈영병 무리가 약탈과 살인을 일삼았고, 10월이면 연대 전체가 무장 강도떼가 되기도 했다. 농민은 젬스트보와 러시아 임시정부의 결정을 기다리지 않았다. 10월 14~15일 키시너우의 제1차 전베사라비아 농민대회는 땅이 무질서하게 점거되고 있다고 보고했고, 각지의 농민위원회와 소비에트는 지주 영지를 나누어 가졌다. 이 대회에서 미미 대신 이온 인쿨레츠가 판무관으로 추대되었는데, 이는 케렌스키가 계획한 인사였다. 11월 2~9일 키시너우에 모인 몰도바 군인 대회는 대의원 9천 명이 30만 병사를 대표한다고 주장하며 베사라비아의 자치를 선언하고 스파툴 처리이 구성을 정했다.",
          en: "Soldiers and peasants carried the revolution into the streets. In spring 1917 \"Moldavian Revolutionary Committees of Soldiers\" appeared in Odessa, Kiev, Sevastopol and on the Romanian Front at Iași, and on 2 May more than 10,000 Bessarabian soldiers met in Odessa to demand autonomy and Moldavian units. On 30 May General Dmitry Shcherbachov, commander of the Romanian Front, allowed sixteen cohorts of Moldavian soldiers to be formed and stationed in Bessarabia's nine districts. Bands of deserters from the collapsing Russian army looted and killed, and by October whole regiments had turned into gangs. Peasants did not wait for the zemstvos or the Provisional Government. The First General Congress of Peasants of All Bessarabia, meeting in Chișinău on 14–15 October, reported that the land was being seized in disorder, as peasant committees and soviets divided up the estates. The congress also voted Ion Inculeț in as Commissar in place of Mimi, a move planned by Kerensky. From 2 to 9 November a Moldavian soldiers' congress in Chișinău, whose 9,000 delegates claimed to speak for 300,000 soldiers, proclaimed Bessarabia's autonomy and laid down the make-up of Sfatul Țării.",
          sources: [S.sfat, S.mdr, S.inculet, S.mdrRU],
        },
      ],
    },
    {
      heading: { ko: "스파툴 처리이와 몰다비아 민주공화국(1917.12) {moldova}", en: "Sfatul Țării and the Moldavian Democratic Republic (December 1917) {moldova}" },
      paragraphs: [
        {
          ko: "스파툴 처리이는 1917년 12월 4일 키시너우에서 문을 열었다. 의원은 선거가 아니라 단체별 선출로 채워졌다. 처음 120석으로 정했다가 135석, 다시 150석으로 늘렸는데, 최종적으로 몰도바 군인 대회 44명, 몰도바 농민 소비에트 30명, 도시·젬스트보 21명, 정당 10명, 협동조합·노조·문화단체 16명, 소수민족 조직 29명이었다. 민족별로는 몰도바인 105명, 우크라이나인 15명, 유대인 13명, 러시아인 6명, 불가리아인 3명 등이었다. 의장은 사회혁명당원 이온 인쿨레츠, 부의장은 판 할리파였다. 인쿨레츠는 페트로그라드 대학 강사로 케렌스키가 보낸 사람이었고, 처음에는 베사라비아가 러시아에 남아야 한다고 말했다. 처음 과반을 얻은 것은 고참 민족운동가 이온 펠리반이었지만, 소수민족 의원들이 혁명과 러시아 민주공화국을 지지하는 인물을 원했고 러시아 국가 권위와의 연결도 필요해 인쿨레츠로 바뀌었다고 한다. 영어 위키백과가 인용한 당대 서술은 이 의회가 평시라면 대표 기관으로 인정받기 어려운 「주로 임명된」 기구였지만 무정부 상태에서 실제 통치 기관이 되었다고 평했다.",
          en: "Sfatul Țării opened in Chișinău on 4 December 1917. Its members were chosen by organisations rather than elected. Planned at 120 seats, it grew to 135 and then 150: in the end 44 came from the Moldavian soldiers' congress, 30 from the soviet of Moldavian peasants, 21 from towns and zemstvos, 10 from parties, 16 from cooperatives, unions and cultural societies, and 29 from minority organisations. By nationality there were 105 Moldavians, 15 Ukrainians, 13 Jews, 6 Russians, 3 Bulgarians and others. The Socialist Revolutionary Ion Inculeț became president and Pan Halippa vice-president. Inculeț, a lecturer at Petrograd University sent by Kerensky, had at first said that Bessarabia should stay in Russia. The veteran nationalist Ion Pelivan had initially won a majority, but minority deputies wanted someone loyal to the revolution and the Russian Democratic Republic, and a link to Russian state authority was useful, so the choice shifted to Inculeț. A contemporary account quoted by English Wikipedia judged the body \"mainly appointive\", not a representative assembly by normal standards, but a genuine governing organ amid the anarchy.",
          sources: [S.sfat, S.inculet, S.mdrRU],
        },
        {
          ko: "12월 15일 스파툴 처리이는 베사라비아를 「몰다비아 인민공화국」으로 선포하고 「단일한 러시아 연방민주공화국」의 동등한 일원이라고 했다. 이름을 두고 「베사라비아 공화국」 안도 나왔지만, 다수 민족의 이름을 붙여야 한다는 판텔리몬 에르한의 주장이 이겼다. 선언은 인민의회를 보통선거로 소집할 때까지 스파툴 처리이가 권력을 맡고, 땅을 일하는 사람들에게 나누는 토지법을 만들며, 8시간 노동제와 임금 인상, 사형 폐지, 모든 민족의 권리 보장을 약속했다. 실제로는 정부가 소비에트 정부의 토지 법령을 무효로 하고 모든 토지를 「입법 절차」까지 자기 관리 아래 두었다고 러시아어 문서는 쓴다. 12월 스파툴 처리이는 에르한을 의장 겸 농업 담당으로 하는 9인 총국장 위원회를 정부로 뽑았다. 몰도바인 7명, 우크라이나인 1명, 유대인 1명이었고 외무는 이온 펠리반이 맡았다. 러시아어 문서에 따르면 페트로그라드 소비에트와 소브나르콤이 새 공화국을 인정했다. 루마니아 쪽 서술은 대표단을 만난 레닌이 「여러분은 자결권이 있다」고 답했다고 전한다.",
          en: "On 15 December Sfatul Țării proclaimed Bessarabia the Moldavian People's Republic, an equal member of \"a single Russian Federative Democratic Republic\". A \"Bessarabian Republic\" was proposed, but Pantelimon Erhan carried the argument that the state should bear the name of its largest people. The declaration promised that Sfatul Țării would hold power until a people's assembly was elected by universal suffrage, that a land law would give the land to those who worked it, and it pledged an eight-hour day and higher wages, abolition of the death penalty and rights for all nationalities. In practice, Russian Wikipedia notes, the government declared the Soviet Decree on Land void and placed all land under its own administration pending legislation. In December Sfatul Țării elected a nine-member Council of Directors General, with Erhan as chairman and director for agriculture: seven Moldavians, one Ukrainian and one Jew, with Ion Pelivan for foreign affairs. According to Russian Wikipedia the Petrograd Soviet and Sovnarkom recognised the new republic; Romanian accounts report that Lenin told a delegation, \"You have every right to self-determination.\"",
          sources: [S.sfat, S.mdr, S.erhan, S.mdrRU, S.sfatRU],
        },
        {
          ko: "그러나 새 공화국은 영토를 장악하지 못했다. 벤데르의 사회혁명당·사회민주당·노조 합동회의는 10월 혁명 직후 소비에트 권력을 인정했고, 키시너우 소비에트도 곧 뒤따랐다. 적위대가 생기고 정치범이 풀려났으며, 농민위원회는 총국장 위원회의 관리를 마을에 들이지 않았다. 몰도바인 부대 병사들은 농민 운동 진압에 나서기를 거부했고, 명목상 스파툴 처리이에 속한 부대 대부분이 볼셰비키 영향 아래 들어갔다. 국방 담당 테오도르 코조카루가 병으로 물러난 뒤 게르만 펀테아 중위가 부대 편성을 맡아 1918년 1월 초까지 기병 2개·보병 1개 연대와 코호르트 16개가 꾸려졌지만, 병사 일리에 카터러우가 부대를 이끌고 마을을 약탈하다 체포되는 사건으로 신망이 떨어졌다. 정부는 12월 이아시에 대표를 보내 협상국과 루마니아에 군사 지원을 청했고, 펠리반은 셰르바초프에게 도움을 구했다. 러시아어 문서에 따르면 12월 28일(구력) 에르한이 농민파 회의에서 루마니아군 도입 안을 표결에 부쳐 38표로 통과시켰고, 사회주의 블록은 항의하며 스파툴 처리이를 떠났다. 펀테아는 몰도바 병사들이 「루마니아인이 혁명으로 얻은 땅을 빼앗으러 온다」며 분노했다고 증언했다.",
          en: "The new republic, however, did not control its territory. A joint meeting of SRs, Social Democrats and trade unions in Bender recognised Soviet power soon after the October Revolution, and the Chișinău soviet soon followed. Red Guards were formed, political prisoners freed, and peasant committees kept the Council of Directors' officials out of the villages. Moldavian soldiers refused to put down the peasant movement, and most units nominally under Sfatul Țării fell under Bolshevik influence. When the military director Teodor Cojocaru fell ill, Lieutenant Gherman Pântea took over, and by early January 1918 there were two cavalry regiments, an infantry regiment and sixteen cohorts, but their name suffered when the soldier Ilie Catărău used his men to loot villages and had to be arrested. In December the government sent envoys to Iași to ask the Entente and Romania for troops, and Pelivan sought help from Shcherbachov. According to Russian Wikipedia, on 28 December (Old Style) Erhan put the entry of Romanian troops to a vote in the peasant faction, which passed it with 38 votes, and the socialist bloc walked out of Sfatul Țării in protest. Pântea recalled that Moldavian soldiers were furious that \"the Romanians would come to take away the land won in the revolution\".",
          sources: [S.mdrRU, S.annexRU, S.sfat, S.mdr, S.inculet],
        },
      ],
    },
    {
      heading: { ko: "1918년 1~3월: 룸체로드와 루마니아군의 진입 {moldova romania soviet ukraine}", en: "January–March 1918: the Rumcherod and the Romanian advance {moldova romania soviet ukraine}" },
      paragraphs: [
        {
          ko: "룸체로드는 루마니아 전선·흑해 함대·오데사 주 소비에트 중앙집행위원회의 약칭으로, 1917년 5~6월 오데사의 대회에서 생겼다. 처음에는 사회혁명당과 멘셰비키가 다수였으나, 니콜라이 크릴렌코의 지시로 해산된 뒤 1917년 12월 23일~1918년 1월 5일 열린 제2차 대회가 180명의 새 룸체로드를 뽑았다. 볼셰비키 70명, 좌파 사회혁명당 55명, 농민 단체 23명, 기타 32명이었고 의장은 블라디미르 유돕스키였다. 새 룸체로드는 소비에트 정부를 인정하고 오데사 소비에트 공화국의 최고기관이 되었다. 키시너우에서는 룸체로드의 전선부(프론토트델)가 활동을 시작해 루마니아군 진입에 맞설 준비를 했다. 키시너우 태생의 이오나 야키르도 1917년 볼셰비키에 가입해 현 소비에트와 혁명위원회에 참여했다. 1918년 1월 중순 프론토트델과 볼셰비키 쪽 병사들이 키시너우를 장악했고, 스파툴 처리이 의원들은 몸을 피했다. 러시아어 문서는 1월 19일 라즈델나야 쪽에서 들어오던 트란실바니아 의용병 부대를 룸체로드 부대와 넘어간 몰도바 부대가 무장해제해 오데사로 보냈다고 쓴다.",
          en: "The Rumcherod, short for the Central Executive Committee of the Soviets of the Romanian Front, Black Sea Fleet and Odessa Oblast, was created at a congress in Odessa in May–June 1917. At first SRs and Mensheviks dominated it, but after it was dissolved on Nikolai Krylenko's order, a second congress held from 23 December 1917 to 5 January 1918 elected a new Rumcherod of 180 members: 70 Bolsheviks, 55 Left SRs, 23 from peasant organisations and 32 others, chaired by Vladimir Yudovsky. The new body recognised the Soviet government and became the supreme organ of the Odessa Soviet Republic. In Chișinău its Front Section, the Frontotdel, began preparing resistance to a Romanian entry. Iona Yakir, a native of Chișinău, had joined the Bolsheviks in 1917 and sat on the governorate soviet and the revolutionary committee. In mid-January 1918 the Frontotdel and pro-Bolshevik soldiers took control of Chișinău, and members of Sfatul Țării went into hiding. Russian Wikipedia records that on 19 January a detachment of Transylvanian volunteers approaching from Razdelnaya was disarmed by Rumcherod troops and Moldavian units that had changed sides, and sent to Odessa.",
          sources: [S.rumch, S.rumchRU, S.mdr, S.yakir, S.mdrRU],
        },
        {
          ko: "루마니아의 이온 브러티아누 정부는 협상국의 승인을 받아 개입을 결정했다. 루마니아군은 1월 23일 프루트강을 건넜고, 에르네스트 브로슈테아누 장군의 제11보병사단이 1월 26일 키시너우에 들어왔다. 그 사이 압박을 받은 인쿨레츠와 에르한은 루마니아군 철수를 요청하는 전보를 이아시에 보냈지만 무시되었다. 벌치 일대에서는 한때 스파툴 처리이에 충성했던 아나톨리에 포파 대위가 루마니아군에 맞섰고, 야키르의 작은 부대도 저항했으나 정규군에 밀렸다. 러시아어 문서에 따르면 볼흐라드에서는 루마니아군이 제6군 병사 대회를 기습했고, 키시너우에서는 현 농민대회 간부단 다섯 명이 반루마니아 혐의로 총살되었으며, 1월 31일 모인 베사라비아 소비에트 대회 의장 루드네프와 대의원 45명도 처형되었다고 한다. 소비에트 러시아와 소비에트 우크라이나는 루마니아와 관계를 끊었다. 남쪽에서는 아나키스트 아나톨리 젤레즈냐코프가 다뉴브 하구의 빌코베 방어를 조직했다. 영어 문서에 따르면 볼셰비키 포함들이 1월 27일부터 루마니아군을 며칠 붙잡아 두었으나 2월 3일 빌코베가 떨어졌다.",
          en: "Ion I. C. Brătianu's Romanian government, with Entente approval, decided to intervene. Romanian troops crossed the Prut on 23 January, and General Ernest Broșteanu's 11th Infantry Division entered Chișinău on 26 January. Under pressure in the meantime, Inculeț and Erhan had wired Iași asking for the Romanian army to be withdrawn, but were ignored. Around Bălți Captain Anatolie Popa, once loyal to Sfatul Țării, fought the Romanians, and Yakir's small force resisted but was overwhelmed by the regular army. According to Russian Wikipedia, Romanian troops surprised a congress of Sixth Army soldiers at Bolgrad; in Chișinău five members of the presidium of the gubernial peasant congress were shot as anti-Romanian, and Rudnev, chairman of a Bessarabian congress of soviets that met on 31 January, was executed together with 45 delegates. Soviet Russia and Soviet Ukraine broke off relations with Romania. In the south the anarchist Anatoly Zheleznyakov organised the defence of Vylkove at the mouth of the Danube; according to English Wikipedia, Bolshevik gunboats held up the Romanians for several days from 27 January, but Vylkove fell on 3 February.",
          sources: [S.sfat, S.mdr, S.inculet, S.yakir, S.mdrRU],
        },
        {
          ko: "가장 큰 싸움은 드네스트르강 다리를 지키는 요새 도시 벤데르(티기나)에서 벌어졌다. 그리고리 보리소프가 이끈 벤데르 지휘부와 룸체로드 전선부, 자무르 연대 병사와 노동자 부대가 시를 지켰다. 러시아어 문서는 루마니아군이 2월 초 일단 시에 들어왔다가 강 건너에서 온 지원군에 밀려났고, 2월 7일 결국 점령한 뒤 기관차 차고 앞에 주민 약 3천 명을 모아 추위 속에 세워 두고 약 500명을 총살했다고 쓴다. 루마니아 쪽에 가까운 영어 문서는 5일간의 전투 끝에 루마니아군이 141명을 잃고 이겼으며 대포 800문을 노획했다고 쓴다. 한편 우크라이나의 붉은 군대 집단군 사령관 미하일 무라비요프는 하루 만에 병력 3천 명을 철도로 드네스트르강에 보내 루마니아군의 도하를 막았다. 협상국의 압력 속에 루마니아의 알렉산드루 아베레스쿠가 3월 5일, 소비에트 쪽의 크리스티안 라콥스키·유돕스키·무라비요프 등이 3월 9일 「러시아-루마니아 분쟁 청산 의정서」에 서명했다. 루마니아군이 두 달 안에 베사라비아에서 철수하고 질서는 지역 민병대가 맡는다는 내용이었다.",
          en: "The heaviest fighting came at Bender (Tighina), the fortress town guarding the Dniester bridge, defended by a Bender headquarters under Grigory Borisov together with the Rumcherod Front Section, soldiers of the Zaamursky regiments and workers' detachments. Russian Wikipedia writes that the Romanians first entered the town in early February, were driven out by reinforcements from across the river, and finally took it on 7 February, after which about 3,000 residents were herded in front of the locomotive depot and kept in the cold, and some 500 defenders were shot. English Wikipedia, closer to the Romanian account, describes a five-day battle won by the Romanians at a cost of 141 dead, with 800 guns captured. Meanwhile Mikhail Muravyov, commanding the Red Army group of forces in Ukraine, rushed 3,000 men to the Dniester by rail in a single day and blocked a Romanian crossing. Under Entente pressure Alexandru Averescu signed for Romania on 5 March, and Christian Rakovsky, Yudovsky, Muravyov and others for the Soviet side on 9 March, a protocol to liquidate the Russo-Romanian conflict: Romanian troops were to leave Bessarabia within two months and order was to pass to local militia.",
          sources: [S.benderRU, S.mdrRU, S.sfat, S.rumchRU, S.rakovsky],
        },
        {
          ko: "의정서는 지켜지지 않았다. 같은 3월 5일 루마니아는 부프테아에서 독일·오스트리아와 예비 강화에 서명했고, 영어 문서에 따르면 비밀 합의로 독일은 독일군의 우크라이나 통과를 대가로 루마니아의 베사라비아 합병을 허락했다. 우크라이나로 밀고 들어온 독일·오스트리아군이 오데사를 점령하자 라콥스키와 룸체로드는 물러날 수밖에 없었다. 룸체로드는 미콜라이우·로스토프나도누를 거쳐 4월 예이스크로 옮겨 갔다가 5월 활동을 멈추었다. 러시아어 문서는 의정서 서명 직후 루마니아군이 아케르만을 점령해 베사라비아 전역을 장악했다고 쓴다. 북쪽 호틴군은 3월 오스트리아-헝가리군이 차지했고, 5월 알렉산드루 마르길로만 정부의 강화로 호틴군 일부를 포함한 600제곱킬로미터가 오스트리아령 부코비나에 넘어갔다. 그사이 스파툴 처리이는 2월 6일 만장일치로 몰다비아 민주공화국의 독립을 선언했다. 우크라이나 인민공화국이 독립을 선포해 소비에트 러시아와의 연결이 끊겼다는 것이 이유였고, 선언문은 「형제 루마니아군」이 철도와 곡물 창고만 지키러 왔을 뿐이라고 주민을 안심시켰다. 총국장 위원회는 다니엘 추구레아누의 각료회의로 바뀌었다.",
          en: "The protocol was never honoured. On the same 5 March Romania signed a preliminary peace with Germany and Austria at Buftea, and according to English Wikipedia a secret agreement let Romania annex Bessarabia in return for free passage of German troops to Ukraine. As German and Austrian forces swept into Ukraine and took Odessa, Rakovsky and the Rumcherod had to retreat; the Rumcherod moved via Mykolaiv and Rostov-on-Don to Yeysk in April and ceased to function in May. Russian Wikipedia says that right after the protocol Romanian troops took Akkerman and completed their hold on Bessarabia. The northern Hotin district was occupied by Austro-Hungarian troops in March, and Alexandru Marghiloman's peace in May ceded 600 square kilometres, including part of Hotin, to Austrian Bukovina. Meanwhile, on 6 February, Sfatul Țării unanimously declared the independence of the Moldavian Democratic Republic, citing the Ukrainian People's Republic's declaration of independence, which had cut Bessarabia off from Soviet Russia; the declaration reassured the population that the \"brotherly Romanian troops\" had come only to guard railways and grain stores. The Council of Directors was replaced by a Council of Ministers under Daniel Ciugureanu.",
          sources: [S.bess, S.rumch, S.rakovsky, S.khotyn, S.mdrRU, S.sfat],
        },
      ],
    },
    {
      heading: { ko: "1918년의 두 차례 합병 결의와 소비에트 러시아의 불인정 {moldova romania}", en: "The two union votes of 1918 and Soviet non-recognition {moldova romania}" },
      paragraphs: [
        {
          ko: "합병은 이아시에서 먼저 정해졌다. 인쿨레츠와 추구레아누는 3월 이아시를 오가며 루마니아 정부와 협의했고, 러시아어 문서에 따르면 4월 2일 두 사람은 루마니아가 협상국과 동맹국의 동의를 얻어 베사라비아를 합병하려 한다는 통보를 받았으며, 5일 「조건부 합병」안을 넘겨받았다. 인쿨레츠는 프랑스 공사 생토레르에게서 빨리 진행하라는 요청도 받았다. 지주가 장악한 벌치·소로카·오르헤이 군의회가 가장 먼저 합병을 청원했는데, 좌파 인민주의자가 다수인 스파툴 처리이의 급진 토지개혁보다 왕정이 낫다고 보았기 때문이다. 마르길로만 총리가 키시너우에 온 가운데 4월 9일 표결이 열렸다. 러시아어 문서는 의사당이 기관총을 갖춘 루마니아군에 둘러싸여 있었고 표결이 비밀이 아니라 공개 호명으로 진행되었다고 쓴다. 독일·불가리아·가가우스 의원들은 기권을 선언했고, 농민파의 치간코와 러시아 문화연맹의 그레쿨로프는 주민투표로만 정할 수 있다고 주장했다. 결과는 찬성 86, 반대 3, 기권 36, 불참 13이었다. 찬성에는 몰도바인 83명이, 기권에는 우크라이나인 8명·러시아인 6명·불가리아인 5명과 몰도바인 11명이 있었다.",
          en: "The union was decided in Iași first. Inculeț and Ciugureanu shuttled there in March, and according to Russian Wikipedia they were told on 2 April that Romania, with the consent of both the Entente and the Central Powers, meant to annex Bessarabia, and on 5 April were handed a plan for a \"conditional union\". The French envoy Saint-Aulaire also urged Inculeț to move quickly. The landowner-dominated county councils of Bălți, Soroca and Orhei were first to petition for union, preferring the monarchy to the radical land reform of a Sfatul Țării dominated by left-wing populists. With Prime Minister Marghiloman in Chișinău, the vote was held on 9 April. Russian Wikipedia writes that the building was surrounded by Romanian troops with machine guns and that the vote was by open roll call rather than secret ballot. German, Bulgarian and Gagauz deputies announced their abstention, and Tsyganko of the peasant faction and Grekulov of the Russian Cultural League argued that only a referendum could decide the question. The result was 86 for, 3 against, 36 abstentions and 13 absent; 83 Moldavians voted for, while the abstainers included 8 Ukrainians, 6 Russians, 5 Bulgarians and 11 Moldavians.",
          sources: [S.mdrRU, S.inculet, S.union, S.sfat],
        },
        {
          ko: "4월 9일의 합병은 조건부였다. 스파툴 처리이가 토지개혁을 하고 루마니아 정부가 이를 받아들이며, 베사라비아는 민주적으로 선출된 자체 의회를 가진 자치 지역으로 남아 지방 예산과 젬스트보·시의회를 통제하고 지방 행정관을 임명한다는 것이 핵심이었다. 그 밖에 징병은 지역 단위로 하고, 지방 법률과 행정은 지역 대표의 동의 없이는 바꿀 수 없으며, 소수민족의 권리를 존중하고, 베사라비아 대표 두 명이 루마니아 정부에 들어가며, 모든 선거는 직접·평등·비밀·보통선거로 하고, 언론·신앙의 자유를 헌법으로 보장하며, 혁명 중 정치적 범죄를 사면한다는 조항이 붙었다. 페르디난드 1세는 그날 밤 이아시에서 조건을 포함한 합병 법령에 서명했다. 인쿨레츠는 의장직을 내놓고 루마니아 정부의 베사라비아 담당 국무장관이 되었고, 의장에는 콘스탄틴 스테레가 뽑혔다. 그 뒤 4~6월 키시너우 철도 노동자와 베사라비아 전역의 철도 노동자가 파업했고, 벤데르·운게니·오크니차에서는 무기고가 불타거나 폭파되었다고 러시아어 문서는 쓴다. 마르길로만은 훗날 합병이 루마니아에서 결정되었다고 인정했다.",
          en: "The union of 9 April was conditional. Sfatul Țării would carry out a land reform which the Romanian government would accept, and Bessarabia would remain autonomous with its own democratically elected diet, which would vote local budgets, control zemstvos and town councils, and appoint the local administration. Further clauses provided for territorial conscription; no change to local laws and administration without local representatives' consent; respect for minority rights; two Bessarabian ministers in the Romanian government; direct, equal, secret and universal suffrage in all elections; constitutional freedom of speech and belief; and an amnesty for political offences committed during the revolution. That night in Iași Ferdinand I signed the decree of union with its conditions. Inculeț left the chair to become Romania's Minister of State for Bessarabia, and Constantin Stere was elected president of the diet. In April–June, Russian Wikipedia records, railwaymen struck first in Chișinău and then across Bessarabia, and munitions depots were burned or blown up at Bender, Ungheni and Ocnița. Marghiloman later admitted that the union had been decided in Romania.",
          sources: [S.union, S.sfat, S.inculet, S.mdrRU],
        },
        {
          ko: "조건은 여덟 달 만에 사라졌다. 루마니아 의회가 1918년 11월 토지개혁을 승인하자, 부코비나가 무조건 합병을 선언한 바로 그날 몰도바 블록 지도부는 나머지 조건도 버리자고 촉구했다. 러시아어 문서는 표결 전 베사라비아 총판무관 버이토이아누 장군이 의원들을 불러 자치 포기를 설득했다고 쓴다. 12월 9~10일 밤 열린 회의는 공고되지 않았고 정족수도 채우지 못했다. 영어 문서에 따르면 125명 가운데 44명만 출석해 모두 찬성했고, 이들은 조건 2·3항, 즉 자치 의회와 지방 행정권을 폐기하고 무조건 합병을 선언한 뒤 스파툴 처리이를 해산하기로 했다. 미국 학자 찰스 킹은 이 표결을 정당하지 않다고 본다. 출석하지 않은 다수 의원은 자치 회복을 요구하는 각서를 보냈지만 받아들여지지 않았다. 1919년 가을 베사라비아에서는 루마니아 제헌의회 선거가 치러졌고, 12월 20일 그 의원들이 트란실바니아·부코비나와 함께 합병 법령을 비준했다. 소비에트 러시아는 베사라비아가 1918년 이전에 루마니아에 속한 적이 없고 합병은 점령군 아래에서 강요되었다며 이를 인정하지 않았고, 1940년까지 소련 지도에는 베사라비아가 점령지로 표시되었다.",
          en: "The conditions lasted eight months. Once the Romanian parliament had approved the land reform in November 1918, the leaders of the Moldavian Bloc, on the very day Bukovina declared its unconditional union, urged the diet to drop the other conditions too. Russian Wikipedia writes that before the vote General Văitoianu, Romania's general commissioner for Bessarabia, summoned the deputies and pressed them to give up autonomy. The session on the night of 9–10 December was not publicly announced and lacked a quorum: according to English Wikipedia only 44 of 125 members attended, all voting in favour. They scrapped conditions two and three, the autonomous diet and local administrative powers, declared the union unconditional and voted to dissolve Sfatul Țării. The American scholar Charles King regards the vote as illegitimate. Many absent deputies sent a memorandum demanding the restoration of autonomy, to no effect. In autumn 1919 Bessarabia elected members of the Romanian Constituent Assembly, who on 20 December ratified the union acts along with those of Transylvania and Bukovina. Soviet Russia refused to recognise the union, arguing that Bessarabia had never been Romanian before 1918 and that the vote had been imposed under military occupation; until 1940 Soviet maps marked Bessarabia as occupied territory.",
          sources: [S.sfat, S.union, S.bess, S.mdrRU, S.annexRU],
        },
        {
          ko: "합병에 대한 반응은 민족과 정치 진영에 따라 갈렸다. 4월 9일 기권한 독일인 의원 알렉산더 뢰슈는 공동체의 위임이 없다고 했지만, 1919년 3월 7일 타루티노에서 열린 베사라비아 독일인 이주민 대회는 만장일치로 합병을 받아들이며 각 민족이 자기 언어로 교육받고 재판받을 권리를 보장한 스파툴 처리이의 결정을 근거로 들었다. 우크라이나 중앙 라다는 루마니아의 「합병」에 항의했다. 루마니아 정부는 회신에서 베사라비아는 합병된 것이 아니라 스파툴 처리이의 결정으로 「모국과 통합」했으며, 우크라이나가 브레스트리토프스크 강화 때 베사라비아를 요구하지 않았고 1918년 1월 19일 루마니아의 코안더 장군에게 반대하지 않는다고 밝혔다고 반박했다. 반대 운동은 오히려 백군 쪽에서 강했다. 차르 시대 베사라비아에서 가장 힘 있던 인물 알렉산드르 크루펜스키, 전 키시너우 시장 알렉산드르 시미트, 전 법무 총국장 미하일 사벤코 등은 오데사에 「베사라비아 방위위원회」를 꾸려 파리 강화회의에 각서를 보내고, 프랑스 여론을 향해 베사라비아가 루마니아군에 점령되었다고 호소했다. 이 활동은 뒤에 볼셰비키의 베사라비아 소비에트 공화국 선포로 대체되었다.",
          en: "Reactions to the union divided along national and political lines. Alexander Loesch, the German deputy who abstained on 9 April, said he had no mandate from his community, but on 7 March 1919 a congress of Bessarabia's German colonists at Tarutino unanimously accepted the union, citing Sfatul Țării's guarantee of every nationality's right to be educated and judged in its own language. The Ukrainian Central Rada protested against Romania's \"annexation\". The Romanian government replied that Bessarabia had not been annexed but had declared \"union with the motherland\" by a decision of Sfatul Țării, that Ukraine had raised no claim to Bessarabia at Brest-Litovsk, and that on 19 January 1918 it had told the Romanian general Coandă it would not object. Opposition was stronger on the White side. Alexander Krupensky, the most powerful man in Tsarist Bessarabia, the former Chișinău mayor Alexander Schmidt and the former justice director Mihail Savenco formed a \"Committee for the Defence of Bessarabia\" in Odessa, which sent a memorandum to the Paris Peace Conference and appealed to French opinion, portraying Bessarabia as under Romanian military occupation. Their campaign was later supplanted by the Bolsheviks' proclamation of a Bessarabian Soviet Republic.",
          sources: [S.sfat],
        },
      ],
    },
    {
      heading: { ko: "1919년: 호틴 봉기와 벤데르 봉기 {moldova ukraine romania}", en: "1919: the Khotyn and Bender uprisings {moldova ukraine romania}" },
      paragraphs: [
        {
          ko: "호틴군은 베사라비아 북쪽 끝, 부코비나와 포딜리아 사이에 있었고 우크라이나인 마을이 다수였다. 1918년 10월 22일 호틴 젬스트보는 다수결로 러시아와의 재통합을 청했고, 11월 10일 오스트리아군이 떠난 자리에 클레안테 다비도글루 장군의 루마니아군이 들어왔다. 루마니아군은 시 주변에 출입 금지 구역을 두고 식량을 징발하고 무기를 거두었으며, 다비도글루는 「베사라비아는 영원히 루마니아 땅」이라고 선언하며 반대하는 사람은 포딜리아로 떠나라고 했다. 땅을 지주에게 돌려주거나 값을 치르게 한 토지 입법도 농민을 자극했다. 1919년 1월 7일 무렵부터 농민 게릴라가 움직였고, 1월 19일 드네스트르강 건너 우크라이나 인민공화국 쪽에서 훈련된 무장대가 넘어와 마을들을 장악했으며, 1월 23일 호틴시에서 봉기가 일어나 루마니아 수비대를 몰아냈다. 봉기군은 카먄치포딜스키에서 꾸려진 「베사라비아 디렉토리아」를 정부로 내세웠고, 「베사라비아 인민군」은 2천 명에서 3만 명으로 불어났다고 한다. 러시아어 문서는 봉기가 약 100개 마을에 퍼졌다고 쓴다.",
          en: "Hotin County lay at the northern tip of Bessarabia between Bukovina and Podolia, with mostly Ukrainian villages. On 22 October 1918 its zemstvo voted by majority for reunion with Russia, and on 10 November, as the Austrians left, General Cleante Davidoglu's Romanian troops moved in. They enforced an exclusion zone around the town, requisitioned food and collected weapons, and Davidoglu proclaimed Bessarabia \"Romanian land today and forever\", telling dissenters to leave for Podolia. Land legislation that returned land to owners or made peasants pay for it added to the anger. Peasant guerrillas were active from about 7 January 1919; on 19 January trained partisans crossed the Dniester from the territory of the Ukrainian People's Republic and took a string of villages, and on 23 January Khotyn itself rose and drove out the Romanian garrison. The rebels proclaimed a \"Bessarabian Directorate\", formed in Kamianets-Podilskyi, as their government, and their \"Bessarabian People's Army\" reportedly grew from 2,000 to 30,000 men. Russian Wikipedia says the revolt spread to about 100 villages.",
          sources: [S.khotyn, S.khotynRU],
        },
        {
          ko: "봉기의 성격은 처음부터 섞여 있었다. 우크라이나 농민이 중심이었고, 몰도바인 무리와 우크라이나 인민군 탈영 카자크, 지역 볼셰비키, 그리고 의용군 자금으로 티라스폴에서 게릴라를 훈련한 백군 계열 「베사라비아 구원위원회」의 주라리 대령까지 얽혀 있었다. 디렉토리아 안에서도 우크라이나 인민공화국에 붙을 「소부코비나 공화국」파와 사실상 소비에트 러시아로 이어질 「베사라비아 민주공화국」파가 갈렸다. 디렉토리아는 호틴 시장을 체포하고 사흘 안에 150만 루블을 내라고 했는데, 부담은 주로 유대인 주민에게 돌아갔다. 우크라이나 인민공화국 지도부는 루마니아와 싸울 여유가 없어 공식적으로 개입을 금지했지만, 일부 부대가 도왔다는 주장도 있다. 한편 소비에트 우크라이나 정부 수반 크리스티안 라콥스키는 1월 25일 베사라비아와 부코비나에 대한 권리를 선언했다. 루마니아군은 증원을 받아 1월 28~30일 반격했고, 2월 1일 봉기군을 드네스트르강 너머로 몰아냈다. 다비도글루는 저항하는 마을을 완전히 파괴해도 좋다는 명령을 받은 상태였다.",
          en: "The rising was mixed from the start. Ukrainian peasants formed its core, alongside groups of Moldavians, Cossack deserters from the Ukrainian People's Army, local Bolsheviks and Colonel Zhurari of the White \"Committee for the Salvation of Bessarabia\", who had trained guerrillas at Tiraspol with Volunteer Army money. The Directorate itself split between advocates of a \"Republic of Little Bukovina\" open to the Ukrainian People's Republic and of a \"Bessarabian Democratic Republic\" that would in effect have extended Soviet Russia. It arrested Khotyn's mayor and demanded 1.5 million roubles within three days, a burden that fell mainly on the town's Jews. The leaders of the Ukrainian People's Republic, who could not afford a war with Romania, formally forbade intervention, though some say units helped. On 25 January Christian Rakovsky, head of the Soviet Ukrainian government, asserted a claim to Bessarabia and Bukovina. Reinforced Romanian troops counter-attacked on 28–30 January and by 1 February had pushed the rebels back over the Dniester. Davidoglu had orders to crush resistance \"with the greatest violence, including the complete destruction\" of rebel villages.",
          sources: [S.khotyn],
        },
        {
          ko: "진압은 피해 수치부터 다툼거리다. 루마니아 군 문서를 인용한 루마니아 역사가 스터네스쿠는 봉기 측 사망을 300~400명으로 보았고, 다른 루마니아 군 기록은 마을 7곳을 불태우고 5천 명까지 죽였다고 했다. 우크라이나 역사가 포틸차크는 마을 22곳 파괴와 희생자 1만 1천 명, 그 가운데 철도원 165명과 비무장 민간인 500명의 처형을 집계하면서 1만 5천 명 이상이라는 추정은 과장일 것이라고 보았다. 1만 1천 명이라는 숫자는 1925년 국제적색구원회가 처음 퍼뜨린 것이다. 루마니아군 손실은 전사 159명을 포함해 369명이었다. 영국 해군 장교 맥래런은 약탈과 구타, 네더버우치 농민 53명의 총살을 보고했지만, 호틴 시장과 랍비들은 루마니아군이 질서를 되찾았다고 증언했다. 루마니아 장군들 가운데서도 이온 안토네스쿠는 무차별 살해가 루마니아를 「야만인의 나라」로 보이게 한다고 비판했다. 농민 약 5만 명과 무장 봉기군 4천~1만 명이 드네스트르강을 건너 달아났다. 2월 초에는 프랑스군에 티라스폴에서 밀려난 그리고리 코톱스키의 부대가 강을 건너 벤데르에서 루마니아 병사들을 몰아냈다가 프랑스·루마니아 연합군에 격퇴되었다.",
          en: "The repression is disputed starting with the numbers. The Romanian historian Stănescu, citing Romanian military documents, put rebel dead at 300–400; other Romanian army records boasted of seven villages burned and up to 5,000 insurgents killed. The Ukrainian historian Potylchak counts 22 villages destroyed and 11,000 victims, including the execution of 165 railwaymen and 500 unarmed civilians, while judging estimates of 15,000 or more probably exaggerated; the figure of 11,000 was first publicised by International Red Aid in 1925. Romanian losses were 369, including 159 killed. The British naval officer McLaren reported looting, beatings and the shooting of 53 peasants at Nedăbăuți, but Khotyn's mayor and rabbis testified that the Romanians had restored order. Among Romanian generals, Ion Antonescu criticised the random killings as making Romania look like a \"country of savages\". About 50,000 peasants and 4,000–10,000 armed rebels fled across the Dniester. In early February Grigory Kotovsky's Bolsheviks, pushed out of Tiraspol by French troops, crossed the river and briefly chased Romanian soldiers out of Bender before a French–Romanian force drove them back.",
          sources: [S.khotyn, S.kotovsky],
        },
        {
          ko: "1919년 봄 볼셰비키는 베사라비아를 되찾을 길을 공식화했다. 5월 5일 오데사의 제2차 지역 볼셰비키 협의회는 「임시 노동자·농민 망명정부」를 선포했고, 5월 11일 티라스폴에서 러시아 사회주의 연방 소비에트 공화국의 자치 일부로 베사라비아 소비에트 사회주의 공화국이 세워졌다. 의장은 이반 크리보루코프, 외무 담당은 미하일 부조르 등이었지만 베사라비아 영토는 한 뼘도 다스리지 못했다. 5월 초 블라디미르 안토노프-옵세옌코는 호틴을 거쳐 「베사라비아를 해방」하는 작전을 검토했고, 루마니아 정부에는 철군을 요구하는 최후통첩이 무선으로 전달되었다. 그러나 5월 8일 니키포르 흐리호리우의 반란과 데니킨의 공세로 원정은 불가능해졌다. 그런데도 5월 27일 벤데르에서 철도 노동자 중심의 봉기가 일어났다. 그리고리 보리소프가 이끈 봉기군과 강을 건너온 우크라이나 제3군 소속 약 150명이 역·우체국·전신국과 철교를 장악했고, 일부 프랑스 병사는 중립을 지키거나 넘어왔다. 그러나 그날 저녁 루마니아군과 알제리인 프랑스 식민지군이 봉기를 진압했고 적어도 150명이 처형되었다. 베사라비아 소비에트 정부는 9월 데니킨군이 오데사를 차지하자 해산되었다.",
          en: "In spring 1919 the Bolsheviks formalised their claim. On 5 May the Second Regional Bolshevik Conference in Odessa proclaimed a \"Provisional Workers' and Peasants' Government in exile\", and on 11 May the Bessarabian Soviet Socialist Republic was set up at Tiraspol as an autonomous part of the RSFSR, with Ivan Krivorukov as chairman and Mihail Bujor among its commissars for foreign affairs; it never governed any part of Bessarabia. In early May Vladimir Antonov-Ovseenko weighed a march to \"free Bessarabia\" through Khotyn, and ultimatums demanding withdrawal were radioed to the Romanian government. But Nykyfor Hryhoriv's mutiny on 8 May and Denikin's offensive made a campaign impossible. A rising went ahead in Bender anyway on 27 May: rebels led by Grigory Borisov, mostly railwaymen, together with about 150 men of the Third Ukrainian Soviet Army who had crossed the river, seized the station, post office, telegraph and the railway bridge, while some French soldiers stayed neutral or joined them. That evening Romanian troops and French colonial Algerian units crushed the rising, and at least 150 rebels were executed. The Bessarabian Soviet government was disbanded in September after Denikin's army took Odessa.",
          sources: [S.bssr, S.bender, S.benderRU, S.khotyn],
        },
      ],
    },
    {
      heading: { ko: "루마니아의 베사라비아: 토지개혁, 비상통치, 파리 의정서 {moldova romania}", en: "Romanian Bessarabia: land reform, emergency rule and the Paris treaty {moldova romania}" },
      paragraphs: [
        {
          ko: "베사라비아의 토지개혁은 1918~1919년 스파툴 처리이가 입법했지만 루마니아 정부의 압력으로 본래 계획에서 크게 바뀌었다. 스파툴 처리이는 땅을 농민에게 무상으로 나누려 했으나, 구왕국 대지주들의 압력으로 옛 소유자에게 보상하는 방식이 되었다. 구왕국이나 트란실바니아보다는 급진적이어서 보상금이 낮고 수용 면제 한도가 작았지만, 혁명기에 농민이 스스로 나눈 땅까지 되돌렸기 때문에 불만을 샀다. 1917년 대지주가 가진 150만 데샤티나(농지의 40%) 가운데 38.6%가 농민에게 분배되었고, 약 3분의 1은 옛 주인에게 돌아갔으며, 나머지는 국유지가 되어 상당 부분이 루마니아군 장교·관리·성직자에게 주어졌다. 1918년 합병에 찬성한 의원들은 각자 50헥타르를 받았다. 1인당 6헥타르가 목표였지만 농가의 3분의 2 이상이 5헥타르 미만을 받았고, 1931년에도 36만 7,800가구가 땅이 없었다. 농민은 받은 땅값을 20년 동안 갚아야 했고 국가 지원과 신용은 거의 없었다. 집행은 1930년대 초까지 끌었다. 영국·프랑스·이탈리아 국적 옛 소유자에게는 합병 승인을 얻으려 우대 보상이 약속되었다.",
          en: "Bessarabia's land reform was legislated by Sfatul Țării in 1918–1919 but changed considerably under Romanian pressure. Sfatul Țării had meant to give land to the peasants free; pressure from the Old Kingdom's great landowners brought compensation for former owners. The reform was more radical than in the Old Kingdom or Transylvania, with lower payments and lower exemption limits, but it also reversed some of the land seizures peasants had made during the revolution, which caused resentment. Of the 1.5 million desyatinas (40% of farmland) held by large landowners in 1917, 38.6% went to peasants, about a third was restored to its owners, and the rest became state property, much of it later awarded to Romanian army officers, officials and clergy. Deputies who had voted for union in 1918 received 50 hectares each. The target was 6 hectares per person, but more than two-thirds of households got less than 5, and in 1931 367,800 families were still landless. Peasants had to pay for their land over twenty years with little state support or credit, and implementation dragged on into the early 1930s. To win recognition of the union, Romania promised preferential compensation to former owners with British, French and Italian citizenship.",
          sources: [S.bess, S.union],
        },
        {
          ko: "통치 방식은 합병의 의미를 바꾸었다. 네덜란드 학자 빔 반 뫼르스에 따르면 베사라비아는 국경 충돌과 농민·소수민족의 동요를 이유로 오랫동안 비상사태와 군정 아래 있었고, 볼셰비키 선전을 막기 위한 엄격한 검열이 시행되었다. 자치를 맡던 젬스트보는 1920년대 초 폐지되었고, 그와 함께 교육·보건 서비스도 줄었다. 찰스 킹은 부패하고 고압적인 루마니아 관리가 특히 이 지역에 많았고, 비밀경찰 시구란차가 소수민족을 폭넓게 감시하며 드네스트르강 건너에서 온 난민과 베사라비아 학생을 볼셰비키 첩자로 의심했다고 쓴다. 러시아인은 「위장한 볼셰비키」로 취급되어 교회와 도서관이 문을 닫거나 루마니아화되었고, 그 결과 주민 사이에 「통합되었다기보다 점령당했다」는 감각이 퍼졌다. 호틴군에서는 1923년 군수가 돼지를 모조리 사들여 부코비나에 판 혐의로 조사를 받을 정도였다. 1924년 판 할리파는 루마니아 정부가 베사라비아를 「지옥」으로 만들어 몰도바 민족이 차르 체제 때보다 더 고통받는다고 비판했다. 한편 1919년 11월 선거의 투표율은 72.2%였고, 몰도바 역사가 아나톨 페트렌쿠는 이 시기 베사라비아가 다당제 민주주의를 누렸다고 본다.",
          en: "The manner of rule changed what union meant. According to the Dutch scholar Wim van Meurs, Bessarabia long remained under a state of emergency and military administration, justified by border incidents and unrest among peasants and minorities, with strict censorship against Bolshevik propaganda. The zemstvos that had run local affairs were abolished in the early 1920s, and education and health services shrank with them. Charles King writes that corrupt and heavy-handed Romanian administrators were especially common in the region, and that the Siguranța secret police kept the minorities under wide surveillance, treating refugees from across the Dniester and Bessarabian students as potential Bolshevik agents. Russians were regarded as \"Bolsheviks in disguise\", their churches and libraries closed or Romanianised, and locals came to feel that Bessarabia had been \"occupied by Romania rather than united with\" it. In Hotin the prefect was investigated in 1923 for buying up every pig in the county and selling them in Bukovina. In 1924 Pan Halippa accused the government of turning Bessarabia into an \"inferno\" where the Moldavian people suffered more than under the Tsars. On the other hand, turnout in the November 1919 elections was 72.2%, and the Moldovan historian Anatol Petrencu holds that Bessarabia enjoyed multi-party democracy in this period.",
          sources: [S.bess, S.union, S.khotyn],
        },
        {
          ko: "드네스트르강은 전쟁이 끝난 뒤에도 조용하지 않았다. 1919년 여름 루마니아 정부는 베사라비아 백군 장교들이 데니킨의 남러시아군에 입대하도록 허락했지만, 백군 역시 베사라비아를 러시아 땅으로 여겼다. 데니킨은 베사라비아 구원위원회 사람들에게 우크라이나 인민공화국을 먼저 끝낸 뒤 베사라비아 장악을 돕겠다고 약속했고, 베사라비아 탈환을 위한 제14보병사단 편성도 시작되었다. 백군이 이 목적으로 모은 1,200만 루블은 1920년 2월 티라스폴을 싸움 없이 되찾은 코톱스키와 붉은 군대가 압수했다. 그 뒤로는 소비에트 쪽 공작이 이어졌다. 1920년 6월 루마니아 외교 전문은 호틴군에서 붉은 군대 모병원 200명이 활동한다고 했고, 같은 해 10월부터는 우크라이나 공산당의 국외 공작 기관 자코르도트가 소규모 유격대를 조직해 드네스트르강을 건너 치고 빠지는 공격을 벌였다. 1921년에는 관리와 성직자가 살해되었고, 1919년 진압 뒤 보복을 조직했다는 지주 모샨의 저택이 습격당해 가족 여러 명이 죽었다. 루마니아 쪽은 1919년 봉기 참가자를 여러 해 동안 기소했는데, 1925~1926년에는 봉기 당시 베사라비아에 없었던 농민이 헌병대의 조작 진술로 5년형을 받았다가 재심에서 풀려나는 일도 있었다.",
          en: "The Dniester stayed restless after the fighting ended. In summer 1919 the Romanian government let Bessarabian White officers enlist in Denikin's Armed Forces of South Russia, but the Whites too regarded Bessarabia as Russian. Denikin promised members of the Salvation Committee to help them take Bessarabia once he had finished off the Ukrainian People's Republic, and a 14th Infantry Division began forming for its recovery. The 12 million roubles the Whites collected for the purpose were seized by Kotovsky and the Red Army, which retook Tiraspol without a fight in February 1920. Soviet subversion followed. A Romanian diplomatic cable of June 1920 claimed 200 Red Army recruiters were active in Hotin County, and from October the Ukrainian Communist Party's foreign-infiltration office, Zakordot, organised small guerrilla units for hit-and-run raids across the Dniester. In 1921 officials and clergymen were murdered, and the manor of the landowner Moșan, accused of organising reprisals after 1919, was attacked and several of his family killed. Romania prosecuted 1919 rebels for years; in 1925–1926 a peasant sentenced to five years on fabricated gendarmerie testimony proved at retrial that he had not even been in Bessarabia during the revolt.",
          sources: [S.khotyn],
        },
        {
          ko: "국제적 승인은 끝내 완결되지 않았다. 파리 강화회의의 루마니아 영토위원회에서 미국·영국·프랑스·이탈리아 대표가 유일하게 의견을 모은 문제가 베사라비아의 루마니아 귀속이었다. 1920년 10월 28일 영국·프랑스·이탈리아·일본은 루마니아와 파리 의정서에 서명하고, 「지리·민족·역사·경제의 관점에서 합병이 충분히 정당하다」며 루마니아의 주권을 인정했다. 그러나 일본이 비준하지 않아 의정서는 발효되지 못했다. 미국은 러시아가 회의에 대표되지 않았다는 이유로 서명을 거부했고, 정치·경제 관계를 유지하면서도 베사라비아를 루마니아 영토가 아니라 루마니아가 점령한 땅으로 다루었다. 러시아 사회주의 연방 소비에트 공화국과 소비에트 우크라이나 대표는 11월 1일 자신들이 빠진 채 맺어진 베사라비아 관련 합의는 아무 효력도 없으며 다른 정부들이 맺은 조약에 구속되지 않는다고 선언했다. 코펜하겐·바르샤바·제노바 등에서 소련과 루마니아는 여러 차례 만났지만 합의하지 못했고, 1918년의 룸체로드 협정을 누가 먼저 어겼는지도 두 나라 역사가들이 오래 다투었다.",
          en: "International recognition was never completed. In the Paris Peace Conference's Territorial Commission on Romanian Affairs, the only Romanian question on which the American, British, French and Italian delegates agreed was that Bessarabia should belong to Romania. On 28 October 1920 Britain, France, Italy and Japan signed the Treaty of Paris with Romania, recognising its sovereignty because \"from the geographical, ethnographical, historical and economic point of view the union of Bessarabia with Romania is fully justified\". Japan, however, never ratified it, so the treaty never entered into force. The United States refused to sign because Russia had not been represented, and while keeping political and economic ties it treated Bessarabia as territory under Romanian occupation rather than as part of Romania. On 1 November representatives of the RSFSR and Soviet Ukraine declared that no agreement on Bessarabia concluded without them had any force and that they were in no way bound by a treaty signed by other governments. Soviet and Romanian envoys met repeatedly, in Copenhagen, Warsaw, Genoa and elsewhere, without agreement, and historians of both countries long argued over who first broke the 1918 agreement with the Rumcherod.",
          sources: [S.union, S.paris, S.bess, S.annexRU, S.tatar],
        },
      ],
    },
    {
      heading: { ko: "1924년: 빈 회담 결렬과 타타르부나리 봉기 {moldova soviet romania}", en: "1924: the Vienna talks and the Tatarbunary Uprising {moldova soviet romania}" },
      paragraphs: [
        {
          ko: "1924년 3월 27일부터 4월 2일까지 빈에서 소련과 루마니아가 관계 정상화를 위해 마주 앉았다. 루마니아는 새로 생긴 소련을 승인하지 않았고 두 나라 사이에는 외교 관계가 없었다. 소련 대표단은 니콜라이 크레스틴스키가 이끌었고, 막심 리트비노프가 베사라비아 주민투표 안을 내놓았다. 루마니아 대표단은 소련 어디에서도 주민투표가 열린 적이 없다며 레프 트로츠키를 인용해 반박했고, 베사라비아의 성격은 루마니아적이며 주민이 이미 여러 번 자결권을 행사했으니 주민투표 제안은 「무익하고 모욕적」이라고 했다. 4월 2일 루마니아는 제안을 거부하고 협상을 끝냈다. 러시아어 문서에 따르면 4월 6일 모스크바에서 외무인민위원부 쪽은 『프라우다』에 「주민투표 때까지 베사라비아를 소련의 떼어 낼 수 없는 일부로 여기겠다」고 밝혔다. 루마니아는 7월 28일 왕령으로 공산당을 금지했다. 앞서 1923년 12월 발칸 공산주의 연방 제6차 회의는 루마니아가 1918년 러시아의 약점을 틈타 다른 민족의 땅을 차지했다고 규탄했다.",
          en: "From 27 March to 2 April 1924 Soviet and Romanian delegations met in Vienna to normalise relations. Romania had not recognised the new USSR and the two had no diplomatic ties. Nikolay Krestinsky led the Soviet delegation, and Maxim Litvinov proposed a plebiscite in Bessarabia. The Romanian delegation retorted, citing Leon Trotsky, that no plebiscite had ever been held anywhere in the Soviet Union, and argued that Bessarabia was Romanian in character and its people had repeatedly exercised self-determination, making a plebiscite \"futile and offending\". On 2 April Romania rejected the proposal and broke off talks. According to Russian Wikipedia, on 6 April the foreign commissariat told Pravda in Moscow, \"Until a plebiscite we will regard Bessarabia as an inalienable part of the Soviet Union.\" On 28 July a royal decree banned the Romanian Communist Party. In December 1923 the sixth conference of the Balkan Communist Federation had already condemned Romania for seizing other peoples' lands in 1918 while Russia was weak.",
          sources: [S.tatar, S.tatarRU, S.bess],
        },
        {
          ko: "봉기는 이미 준비되고 있었다. 1922년 5월 남부 베사라비아에 소련 직속 당위원회가 생겼는데, 코민테른 요원인 안드레이 클류시니코프(가명 네닌)와 니콜라이 시시만이 지역 활동가 세 명과 함께 이끌었고 루마니아 공산당이 아니라 오데사의 특별 센터를 통해 직접 지휘를 받았다. 이들은 카훌·이즈마일·아케르만 3개 군의 마을 25곳과 카훌·이즈마일시에 혁명위원회와 20~30명 규모의 무장대를 꾸렸고, 스트루모크와 네루샤이에 수류탄 3천 개, 소총 1천 정, 기관총 7정 등을 쌓아 두었다. 1924년 8월 8일 코민테른의 발칸 공산주의 연방 서기 바실 콜라로프가 주재한 회의는 루마니아를 다섯 구역으로 나누어 9월 중순 봉기를 일으킨다는 계획을 세웠다. 계획은 1921년 토지개혁에 대한 농민의 불만과 1924년 여름 가뭄으로 남부 베사라비아에 든 기근에 기댔다. 러시아어 문서에 따르면 국경 맞은편에서 기병 군단을 지휘하던 그리고리 코톱스키는 미하일 프룬제에게 「기병의 일격」으로 문제를 풀자고 제안했다. 클류시니코프는 봉기가 시작되면 붉은 군대가 도우러 온다고 참가자들을 독려했다.",
          en: "A rising was already being prepared. In May 1922 a party committee directly under Soviet control was set up in southern Bessarabia, led by the Comintern agents Andrey Klyushnikov (alias Nenin) and Nikolai Shishman with three local activists, and taking orders not from the Romanian Communist Party but from a special centre in Odessa. They organised revolutionary committees with armed squads of 20–30 men in 25 villages and the towns of Cahul and Ismail across the three counties of Cahul, Ismail and Cetatea Albă, and stockpiled 3,000 grenades, 1,000 rifles, seven machine guns and more at Strumok and Nerushai. On 8 August 1924 a meeting chaired by Vasil Kolarov, secretary of the Balkan Communist Federation, drew up a Comintern plan dividing Romania into five zones for risings in mid-September, counting on peasant anger at the 1921 land reform and the famine that the summer drought of 1924 had brought to southern Bessarabia. According to Russian Wikipedia, Grigory Kotovsky, commanding a cavalry corps across the border, proposed to Mikhail Frunze to settle the matter with \"a dashing cavalry raid\". Klyushnikov told the participants that the Red Army would come to their aid once the rising began.",
          sources: [S.tatar, S.tatarRU, S.klyush],
        },
        {
          ko: "9월 11일 배를 타고 온 30명이 흑해 연안 니콜라예우카 마을을 습격해 촌장과 헌병 두 명을 죽였다. 지도자 몇 명이 체포되자 네닌은 일정을 앞당겼고, 9월 15~16일 밤 무장대가 타타르부나리 면사무소를 점령해 우크라이나 소비에트 공화국에 속하는 「몰다비아 소비에트 공화국」을 선포했다. 면 서기와 헌병대장, 루마니아 병사 두 명 등이 죽었고, 네닌은 주민을 모아 붉은 군대가 드네스트르강을 건넜다고 연설했다. 봉기군은 4천~6천 명으로 대부분 우크라이나인과 러시아인이었고, 루마니아인·불가리아인·독일인 주민은 거의 가담하지 않았다. 사라타의 독일인 의용병 40명이 먼저 맞섰고, 루마니아 제3군단의 포병과 해병, 다뉴브 함대가 투입되었다. 18일 새벽 루마니아군은 포격 끝에 타타르부나리를 함락했다. 클류시니코프는 달아나다 헌병의 총에 죽었다. 영어 문서는 1,600명이 체포되고 3천 명이 죽었다고 쓰고, 러시아어 문서는 3천 명 넘게 죽었으며 루마니아군이 19일 화학 포탄까지 썼다고 쓴다. 1925년의 「500인 재판」에는 489명이 기소되었고 85명이 유죄를 받았다.",
          en: "On 11 September thirty men landing by boat raided the Black Sea village of Nikolaievca and killed the mayor and two gendarmes. When several leaders were arrested, Nenin brought the timetable forward, and on the night of 15–16 September armed groups seized the town hall of Tatarbunary and proclaimed a \"Moldavian Soviet Republic\" as part of Soviet Ukraine. The town secretary, the gendarmerie chief, two Romanian soldiers and others were killed, and Nenin told the assembled residents that the Red Army had crossed the Dniester. The rebels numbered 4,000–6,000, mostly Ukrainians and Russians; Romanians, Bulgarians and Germans hardly joined. Forty German volunteers from Sarata were the first to fight them, followed by artillery and marines of the Romanian Third Army Corps and the Danube flotilla. At dawn on 18 September Romanian troops stormed Tatarbunary after shelling it. Klyushnikov was shot by a gendarme as he fled. English Wikipedia says 1,600 people were arrested and 3,000 died; Russian Wikipedia says more than 3,000 died and that the Romanians used chemical shells when they took the town on the 19th. At the 1925 \"Trial of the 500\", 489 people were prosecuted and 85 convicted.",
          sources: [S.tatar, S.tatarRU, S.klyush],
        },
      ],
    },
    {
      heading: { ko: "타타르부나리 이후와 몰다비아 자치 공화국 수립(1924.10) {moldova soviet ukraine}", en: "After Tatarbunary: the Moldavian ASSR (October 1924) {moldova soviet ukraine}" },
      paragraphs: [
        {
          ko: "타타르부나리는 루마니아 안팎에 오래 흔적을 남겼다. 「500인 재판」은 1925년 8월 24일부터 12월 2일까지 103일 동안 제3군단 군사법정에서 열렸다. 피고 대부분이 루마니아어를 몰라 통역을 거쳐야 했고, 정부 서류는 약 7만 쪽에 이르렀다. 피고 가운데 루마니아인은 9명뿐이었고 유죄를 받은 85명 가운데에는 한 명도 없었다. 가장 무거운 형은 봉기 지도자 유스틴 바티시체프의 종신 강제노동으로, 뒤에 16년으로 줄었다. 재판은 국제적 관심을 끌어 로맹 롤랑, 폴 랑주뱅, 시어도어 드라이저, 알베르트 아인슈타인 등이 피고를 옹호했고, 앙리 바르뷔스는 직접 루마니아에 와 재판을 지켜본 뒤 『사형집행인들』을 썼다. 당국도 대응이 지나쳤음을 인정했지만 루마니아는 국제적으로 「소수민족의 감옥」이라는 이름을 얻었다. 1924년 12월 의회를 통과한 세 번째 머르제스쿠법은 공산당을 사실상 금지해 당원 대부분이 체포되었는데, 그 다수는 루마니아인이 아니었다. 봉기 참가자 다수는 드네스트르강을 건너 몰다비아 자치 공화국의 주라 마을에 정착해 환대받았지만, 1937~1938년 대숙청 때 큰 고통을 겪었다.",
          en: "Tatarbunary left a long mark inside and outside Romania. The \"Trial of the 500\" ran for 103 days, from 24 August to 2 December 1925, before the Third Army Corps military court. Most defendants spoke no Romanian and needed interpreters, and the government's file ran to some 70,000 pages. Only nine defendants were Romanians, and none of the 85 convicted. The heaviest sentence, life at hard labour for the rebel leader Iustin Batishchev, was later cut to 16 years. The trial drew international attention: Romain Rolland, Paul Langevin, Theodore Dreiser, Albert Einstein and others spoke up for the defendants, and Henri Barbusse travelled to Romania to watch the proceedings and then wrote The Hangmen. The authorities admitted their response had been disproportionate, but Romania became known abroad as a \"prison of minorities\". The third Mârzescu Law, passed in December 1924, banned the Communist Party in practice and led to the arrest of almost all its members, most of them non-Romanians. Many participants in the rising fled across the Dniester to the village of Jura in the Moldavian ASSR, where they were well received, but suffered greatly in the Great Purge of 1937–1938.",
          sources: [S.tatar],
        },
        {
          ko: "봉기가 진압된 직후 드네스트르강 동쪽에서 새 공화국이 생겼다. 1924년 2월 코톱스키와 루마니아 출신 볼셰비키 등 10명은 러시아 공산당과 우크라이나 공산당 중앙위원회에 각서를 보내, 드네스트르강 왼쪽 기슭에 몰도바인 50만~80만 명이 살고 있으며 몰다비아 공화국이 베사라비아 문제를 푸는 강력한 정치·선전 수단이 될 것이라고 주장했다. 외무인민위원 게오르기 치체린은 이것이 루마니아의 베사라비아 주장을 오히려 강화하고 「루마니아 배외주의」를 자극할 것이라고 반대했다. 우크라이나 공산당 정치국은 3월 7일 신중론을 냈다가 4월 18일 몰도바인 수가 부풀려졌다며 자치가 부적절하다고 결론지었지만, 모스크바는 이를 무시했다. 러시아 공산당 중앙위원회는 7월 29일 우크라이나 공화국 안에 몰다비아 자치 공화국을 만들라고 지시했고, 10월 12일 전우크라이나 중앙집행위원회가 이를 결정했다. 공식 수도는 「일시적으로 점령된 키시너우」였고 임시 수도는 발타였다. 러시아어 문서가 전하는 1926년 인구조사에서 우크라이나인은 48.5%, 몰도바인은 30.1%였다.",
          en: "Right after the rising was crushed a new republic appeared east of the Dniester. In February 1924 Kotovsky and nine others, including Bolsheviks from Romania, sent a memorandum to the Central Committees of the Russian and Ukrainian Communist Parties claiming that 500,000–800,000 Moldavians lived on the left bank of the Dniester and that a Moldavian republic would be a powerful political and propaganda instrument in the Bessarabian question. Foreign Commissar Georgy Chicherin objected that it would only strengthen Romania's position on Bessarabia and stir up \"Romanian chauvinism\". The Ukrainian party Politburo counselled caution on 7 March and on 18 April, finding the Moldavian numbers inflated, judged autonomy inappropriate, but Moscow ignored it. On 29 July the Russian party's Central Committee ordered an autonomous Moldavian republic to be created within Ukraine, and on 12 October the All-Ukrainian Central Executive Committee decreed it. Its official capital was the \"temporarily occupied city of Chișinău\"; the provisional capital was Balta. In the 1926 census reported by Russian Wikipedia, Ukrainians made up 48.5% of the population and Moldavians 30.1%.",
          sources: [S.massr, S.massrRU, S.kotovsky],
        },
      ],
    },
    {
      heading: { ko: "평가: 루마니아·소련·몰도바 역사학의 서로 다른 시각 {moldova romania}", en: "Assessments: Romanian, Soviet and Moldovan historiography {moldova romania}" },
      paragraphs: [
        {
          ko: "루마니아 역사학은 대체로 1918년의 합병을 민족 자결의 정당한 행사로 본다. 스파툴 처리이가 주권을 대표했고, 베사라비아는 1812년 차르 러시아가 몰다비아에서 빼앗은 땅이며, 루마니아군은 무정부 상태를 끝내려 들어왔을 뿐이라는 것이다. 영국 역사가 버나드 뉴먼은 표결이 베사라비아 주민의 지배적 의사를 대표했다는 데 의심의 여지가 거의 없다고 했다. 이 시각에서 1919년과 1924년의 봉기는 외부의 작품이다. 루마니아 역사가 게오르게 I. 브러티아누는 드네스트르강 건너에서 보낸 공산주의 유격대가 조직하지 않은 봉기는 하나도 없었다고 썼고, 미국 학자 클라크는 타타르부나리를 「밖에서 꾸민 공산주의 습격」이라 불렀다. 루마니아의 비공산계 사회주의자 일리에 모스코비치조차 1925년 제3인터내셔널의 선동가들이 농민의 목숨을 가지고 놀았다고 비판했다. 다만 당시 루마니아 야당 신문과 변호사 콘스탄틴 코스타포루는 타타르부나리를 가혹하고 무능한 행정이 낳은 재앙으로 보았고, 정부가 공산주의 공포를 부풀려 계엄을 전국으로 넓히려 한다고 비판했다.",
          en: "Romanian historiography generally treats the union of 1918 as a legitimate act of national self-determination: Sfatul Țării embodied sovereignty, Bessarabia was land Tsarist Russia had taken from Moldavia in 1812, and the Romanian army came only to end anarchy. The British historian Bernard Newman thought there was little doubt that the vote represented the prevailing wish in Bessarabia. On this view the uprisings of 1919 and 1924 were the work of outsiders. The Romanian historian Gheorghe I. Brătianu wrote that not one uprising took place in Bessarabia that was not organised by communist partisans sent from across the Dniester, and the American scholar Clark called Tatarbunary \"a Communist raid, engineered from without\". Even the non-communist Romanian socialist Ilie Moscovici wrote in 1925 that agents provocateurs of the Third International had toyed with peasants' lives. Yet Romanian opposition papers and the lawyer Constantin Costa-Foru saw Tatarbunary as a disaster rooted in harsh and incompetent administration, and accused the government of inflating the communist scare to extend martial law to the whole country.",
          sources: [S.union, S.khotyn, S.tatar],
        },
        {
          ko: "소련 역사학은 정반대 서사를 썼다. 베사라비아는 1918년 이전에 루마니아에 속한 적이 없고, 스파툴 처리이의 표결은 루마니아군의 총구 아래 이루어졌으며, 이후 22년은 「점령」이었다는 것이다. 봉기들은 「베사라비아 노동자의 영웅적 투쟁」이자 계급 갈등의 표현으로 그려졌다. 1925년 라콥스키가 처음 호틴 봉기를 소련의 영웅 서사에 넣었고, 소련 저자들은 피란민 5만 명을 사상자 5만 명으로 바꾸어 쓰기도 했다. 그러나 이 서사도 한결같지 않았다. 1950년대 초 몰다비아 교과서는 호틴과 타타르부나리를 「약하고 고립되고 준비가 부족했던」 봉기로 썼다가 1960년대에 「대봉기」로 고쳤다. 소련 저술은 백군 「구원위원회」의 역할을 지웠다. 네덜란드 학자 반 뫼르스는 호틴 봉기에 소련이 개입한 증거가 없고 지역적 운동이었다고 보며, 루마니아 군사사가 마드제아루도 볼셰비키 사주설은 사실이 아니라고 했다. 반대로 반 뫼르스는 타타르부나리가 빈 회담 결렬과 몰다비아 자치 공화국 선포 사이에 너무 정확히 맞물려 크렘린이 몰랐을 리 없다고 본다.",
          en: "Soviet historiography told the opposite story: Bessarabia had never been Romanian before 1918, Sfatul Țării voted at the point of Romanian guns, and the next 22 years were an \"occupation\". The uprisings were depicted as the \"heroic struggle of the Bessarabian workers\" and an expression of class conflict. Rakovsky first placed Khotyn in the Soviet pantheon in 1925, and Soviet authors later turned 50,000 refugees into 50,000 casualties. Yet even this narrative shifted: early-1950s Moldavian textbooks called Khotyn and Tatarbunary \"weak, isolated, ill-prepared\" revolts, before 1960s works rewrote Khotyn as a \"major revolt\". Soviet writing erased the role of the White Salvation Committee. The Dutch scholar van Meurs sees no documented Soviet role at Khotyn and regards it as a local movement, and the Romanian military historian Madgearu likewise calls the Bolshevik-instigation thesis counterfactual. Conversely, van Meurs considers Tatarbunary too neatly timed between the failure of the Vienna talks and the proclamation of the Moldavian ASSR for the Kremlin not to have been involved.",
          sources: [S.khotyn, S.tatar, S.bess, S.annexRU],
        },
        {
          ko: "몰도바와 서방 학계는 다른 질문을 던진다. 찰스 킹은 베사라비아의 봉기들을 근대판 「자크리」, 곧 농민 반란으로 보며, 1918년 11월의 무조건 합병 표결은 정족수 미달로 정당하지 않다고 판단한다. 서방 연구자들은 토지개혁이 땅의 분배만 바꾸었을 뿐 농업 정책은 바꾸지 못했고, 베사라비아로의 발령이 징벌로 여겨질 만큼 행정이 불안정하고 부패했다고 지적한다. 우크라이나·러시아 저자들은 타타르부나리의 원인으로 경제 위기, 1921년 토지 정책, 1923~1924년 가뭄과 기근, 가혹한 행정을 꼽는다. 몰도바 역사가 로타리는 봉기 구호가 「소비에트 권력 만세」, 「소비에트 우크라이나와의 통합」처럼 사회적이기보다 정치적이었다고 지적한다. 1991년 이후 몰도바 역사학은 몰도바 국가성을 앞세워 루마니아 시기의 근대화를 부정하는 흐름과, 베사라비아의 루마니아적 성격을 전제로 통합과 근대화를 강조하는 흐름으로 갈라졌다. 몰다비아 자치 공화국에서 시작된 「몰도바어」 별도 표준화와 키릴 문자 정책은 이 논쟁에 언어 문제까지 얹어 놓았다. 스베틀라나 수베이커는 전간기 베사라비아 서술이 저자의 정치적 소속에 따라 루마니아 지배의 합법성을 다투는 데 쏠렸다고 평한다.",
          en: "Moldovan and Western scholarship asks different questions. Charles King treats the Bessarabian revolts as modern jacqueries, peasant risings, and judges the November 1918 vote for unconditional union illegitimate for lack of a quorum. Western researchers note that the land reform changed the distribution of land but not agricultural policy, and that the administration was so unstable and corrupt that a posting to Bessarabia was regarded as a punishment. Ukrainian and Russian authors point to the economic crisis, the 1921 agrarian policy, the drought and famine of 1923–1924 and harsh administration as causes of Tatarbunary. The Moldovan historian Ludmila Rotari notes that the rebels' slogans, such as \"Long live Soviet power\" and \"Union with Soviet Ukraine\", were political rather than social. Since 1991 Moldovan historiography has split between a current that stresses Moldovan statehood and denies any modernisation under Romania, and one that starts from Bessarabia's Romanian character and stresses integration and modernisation. The separate standardisation of a \"Moldavian language\" and the Cyrillic policy begun in the Moldavian ASSR added language to the dispute. Svetlana Suveică observes that writing on interwar Bessarabia has been driven by authors' political affiliations, mostly to argue for or against the legality of Romanian rule.",
          sources: [S.tatar, S.union, S.bess, S.moldovenism, S.massr],
        },
      ],
    },
  ],
  timeline: [
    ["1917.04.19–04.20", "협동조합 대회의 자치 요구", "Cooperatives' congress demands autonomy", "키시너우의 제1차 베사라비아 협동조합 대회가 자치와 입법기관 스파툴 처리이 창설을 요구했다.", "The First Congress of Cooperatives of Bessarabia in Chișinău demanded autonomy and a legislature called Sfatul Țării.", "moldova", P(47.0105, 28.8638, "키시너우", "Chișinău")],
    ["1917.10.14–10.15", "제1차 전베사라비아 농민대회", "First All-Bessarabian Peasants' Congress", "농민대회가 토지 점거 실태를 보고하고, 미미 대신 이온 인쿨레츠를 판무관으로 추대했다.", "The peasants' congress reported widespread land seizures and voted Ion Inculeț in as Commissar in place of Mimi.", "moldova", P(47.0105, 28.8638, "키시너우", "Chișinău")],
    ["1917.11.02–11.09", "몰도바 군인 대회", "Moldavian Soldiers' Congress", "대의원 9천 명이 베사라비아의 자치를 선언하고 스파툴 처리이 구성을 정했다.", "Some 9,000 delegates proclaimed Bessarabia's autonomy and set the make-up of Sfatul Țării.", "moldova", P(47.0105, 28.8638, "키시너우", "Chișinău")],
    ["1917.12.04", "스파툴 처리이 개원", "Sfatul Țării opens", "베사라비아의 첫 의회가 문을 열고 인쿨레츠를 의장으로 뽑았다.", "Bessarabia's first assembly opened and elected Inculeț its president.", "moldova", P(47.0105, 28.8638, "키시너우", "Chișinău")],
    ["1917.12.15", "몰다비아 민주공화국 선포", "Moldavian Democratic Republic proclaimed", "스파툴 처리이가 러시아 연방민주공화국의 일원인 몰다비아 인민공화국을 선포했다.", "Sfatul Țării proclaimed a Moldavian People's Republic within a Russian Federative Democratic Republic.", "moldova"],
    ["1918.01.23", "루마니아군, 프루트강 도하", "Romanian troops cross the Prut", "협상국의 승인 아래 루마니아군이 베사라비아로 들어왔다.", "With Entente approval, Romanian troops entered Bessarabia.", ["romania", "moldova"]],
    ["1918.01.26", "루마니아군, 키시너우 입성", "Romanians enter Chișinău", "브로슈테아누 장군의 제11보병사단이 키시너우에 들어오고 볼셰비키 쪽 부대는 벤데르로 물러났다.", "General Broșteanu's 11th Infantry Division entered Chișinău; pro-Soviet troops fell back on Bender.", ["romania", "moldova"], P(47.0105, 28.8638, "키시너우", "Chișinău")],
    ["1918.02.03", "빌코베 함락", "Fall of Vylkove", "볼셰비키 포함들이 며칠 버텼으나 다뉴브 하구의 빌코베가 루마니아군에 떨어졌다.", "After Bolshevik gunboats held out for several days, Vylkove at the Danube mouth fell to the Romanians.", ["romania", "soviet"], P(45.4028, 29.5867, "빌코베", "Vylkove")],
    ["1918.02.06", "독립 선언", "Declaration of independence", "스파툴 처리이가 만장일치로 몰다비아 민주공화국의 독립을 선언했다.", "Sfatul Țării unanimously declared the Moldavian Democratic Republic independent.", "moldova"],
    ["1918.02.07", "벤데르 함락", "Fall of Bender", "러시아어 문서에 따르면 며칠의 공방 끝에 루마니아군이 벤데르를 점령하고 수비대원 약 500명을 총살했다.", "According to Russian Wikipedia, the Romanians took Bender after days of fighting and shot some 500 defenders.", ["romania", "soviet"], P(46.8316, 29.4769, "벤데르", "Bender")],
    ["1918.03.05–03.09", "아베레스쿠-라콥스키 의정서", "Averescu–Rakovsky protocol", "루마니아군이 두 달 안에 베사라비아에서 철수한다는 의정서에 양측이 서명했으나 지켜지지 않았다.", "Both sides signed a protocol requiring Romanian troops to leave Bessarabia within two months; it was never honoured.", ["romania", "soviet"]],
    ["1918.04.09", "조건부 합병 결의", "Conditional union vote", "스파툴 처리이가 찬성 86, 반대 3, 기권 36으로 자치를 조건으로 루마니아와의 합병을 결의했다.", "Sfatul Țării voted 86 to 3 with 36 abstentions for union with Romania on condition of autonomy.", ["moldova", "romania"], P(47.0105, 28.8638, "키시너우", "Chișinău")],
    ["1918.12.10", "무조건 합병과 스파툴 처리이 해산", "Unconditional union; Sfatul Țării dissolved", "정족수에 못 미친 44명이 자치 조건을 폐기하고 의회 해산을 결의했다.", "Forty-four deputies, short of a quorum, dropped the autonomy conditions and voted to dissolve the diet.", ["moldova", "romania"], P(47.0105, 28.8638, "키시너우", "Chișinău")],
    ["1919.01.23", "호틴 봉기", "Khotyn Uprising", "드네스트르강 건너에서 온 무장대와 농민이 호틴에서 루마니아 수비대를 몰아냈다. 2월 1일까지 진압되었다.", "Partisans from across the Dniester and local peasants drove the Romanian garrison out of Khotyn; the rising was crushed by 1 February.", ["moldova", "ukraine", "romania"], P(48.5069, 26.4917, "호틴", "Khotyn")],
    ["1919.05.11", "베사라비아 소비에트 공화국", "Bessarabian Soviet Republic", "5일 오데사에서 선포된 망명정부가 티라스폴에서 러시아 연방의 자치 공화국으로 세워졌다.", "The government-in-exile proclaimed in Odessa on 5 May was set up at Tiraspol as an autonomous republic of the RSFSR.", "soviet", P(46.8403, 29.6433, "티라스폴", "Tiraspol")],
    ["1919.05.27", "벤데르 봉기", "Bender Uprising", "철도 노동자와 붉은 군대 약 150명이 시를 장악했으나 그날 저녁 진압되었고 적어도 150명이 처형되었다.", "Railwaymen and some 150 Red Army men took the town but were crushed that evening; at least 150 were executed.", ["moldova", "soviet", "romania"], P(46.8316, 29.4769, "벤데르", "Bender")],
    ["1919.12.20", "루마니아 제헌의회의 비준", "Ratification by the Romanian Constituent Assembly", "베사라비아에서 뽑힌 의원들이 다른 지방 대표와 함께 합병 법령을 비준했다.", "Deputies elected in Bessarabia ratified the union acts with those of the other provinces.", "romania"],
    ["1920.10.28", "파리 의정서", "Treaty of Paris", "영국·프랑스·이탈리아·일본이 루마니아의 베사라비아 주권을 인정했으나 일본의 미비준으로 발효되지 않았다.", "Britain, France, Italy and Japan recognised Romanian sovereignty over Bessarabia; Japan never ratified and the treaty never took effect.", "romania"],
    ["1920.11.01", "소비에트 쪽의 불인정 성명", "Soviet non-recognition statement", "러시아 연방과 소비에트 우크라이나가 자신들이 빠진 베사라비아 합의는 효력이 없다고 선언했다.", "The RSFSR and Soviet Ukraine declared any Bessarabian agreement made without them void.", ["soviet", "ukraine"]],
    ["1924.03.27–04.02", "빈 회담 결렬", "Vienna talks collapse", "소련의 베사라비아 주민투표 제안을 루마니아가 거부하고 협상을 끝냈다.", "Romania rejected a Soviet proposal for a plebiscite in Bessarabia and broke off the talks.", ["soviet", "romania"]],
    ["1924.09.15–09.18", "타타르부나리 봉기", "Tatarbunary Uprising", "클류시니코프가 이끈 봉기군이 「몰다비아 소비에트 공화국」을 선포했으나 루마니아군이 사흘 만에 진압했다.", "Rebels led by Klyushnikov proclaimed a \"Moldavian Soviet Republic\"; the Romanian army crushed them within three days.", ["moldova", "romania", "soviet"], P(45.8381, 29.6125, "타타르부나리", "Tatarbunary")],
    ["1924.10.12", "몰다비아 자치 공화국 수립", "Moldavian ASSR established", "전우크라이나 중앙집행위원회가 드네스트르강 동쪽에 몰다비아 자치 공화국을 세웠다. 임시 수도는 발타였다.", "The All-Ukrainian Central Executive Committee created the Moldavian ASSR east of the Dniester, with Balta as provisional capital.", ["soviet", "ukraine"], P(47.9381, 29.6125, "발타", "Balta")],
  ],
  people: [
    ['ion-inculet', 'leader', '스파툴 처리이 의장', 'President of Sfatul Țării', '케렌스키가 보낸 판무관으로 스파툴 처리이 의장과 몰다비아 민주공화국 대통령을 지냈고, 1918년 4월 합병 결의를 이끈 뒤 루마니아 정부의 베사라비아 담당 국무장관이 되었다.', 'Sent by Kerensky as commissar, he presided over Sfatul Țării and the Moldavian Democratic Republic, steered the April 1918 union vote and then became Romania\'s Minister of State for Bessarabia.', 'moldavian-council'],
    ['pantelimon-erhan', 'leader', '총국장 위원회 의장', 'Chairman of the Council of Directors General', '1917년 12월 몰다비아 민주공화국 첫 정부를 이끌며 토지개혁을 우선 과제로 삼았다. 러시아어 문서에 따르면 루마니아군 도입 안을 표결에 부쳤고, 1918년 합병에 찬성했다.', 'Headed the Moldavian Democratic Republic\'s first government from December 1917 with land reform as its priority; according to Russian Wikipedia he put the entry of Romanian troops to a vote, and he voted for union in 1918.', 'moldavian-council'],
    ['pan-halippa', 'participant', '스파툴 처리이 부의장·의장', 'Vice-president, later president, of Sfatul Țării', '몰도바 민족당 창당에 참여하고 몰다비아 민주공화국 선포문을 낭독했으며, 합병 운동을 이끌었다. 1924년에는 루마니아 정부가 베사라비아를 「지옥」으로 만들었다고 비판했다.', 'A founder of the National Moldavian Party, he read out the proclamation of the Moldavian Democratic Republic and led the union movement; in 1924 he accused the Romanian government of turning Bessarabia into an \"inferno\".', 'moldavian-council'],
    ['ion-pelivan', 'participant', '몰다비아 민주공화국 외무 총국장', 'Director General for Foreign Affairs', '몰도바 민족당의 고참 활동가로 에르한·추구레아누 정부에서 외교를 맡았고, 이아시의 셰르바초프에게 군사 지원을 청했다.', 'A veteran of the National Moldavian Party, he handled foreign affairs in the Erhan and Ciugureanu governments and sought military aid from Shcherbachov in Iași.', 'moldavian-council'],
    ['andrei-klyushnikov', 'leader', '타타르부나리 봉기 지도자', 'Leader of the Tatarbunary Uprising', '가명 네닌. 1922년부터 남부 베사라비아의 혁명위원회를 조직했고, 1924년 9월 타타르부나리에서 몰다비아 소비에트 공화국을 선포했다가 도주 중 헌병의 총에 죽었다.', 'Known as Nenin, he organised revolutionary committees in southern Bessarabia from 1922, proclaimed a Moldavian Soviet Republic at Tatarbunary in September 1924 and was shot by a gendarme while fleeing.', 'soviet-forces'],
    ['iona-yakir', 'participant', '베사라비아 볼셰비키', 'Bessarabian Bolshevik', '키시너우 출신으로 1917년 볼셰비키에 가입해 현 소비에트와 혁명위원회에 참여했고, 1918년 루마니아군 진입에 맞서 볼셰비키 저항을 이끌었으나 밀려났다.', 'A native of Chișinău, he joined the Bolsheviks in 1917, sat on the governorate soviet and revolutionary committee, and led Bolshevik resistance to the Romanian entry in 1918 before being overwhelmed.', 'soviet-forces'],
    ['anatoly-zheleznyakov', 'participant', '빌코베 방어 지휘', 'Organiser of the defence of Vylkove', '러시아어 문서에 따르면 1918년 1~2월 다뉴브 하구 빌코베의 방어를 조직했다.', 'According to Russian Wikipedia, he organised the defence of Vylkove at the mouth of the Danube in January–February 1918.', 'soviet-forces'],
    ['mikhail-muravyov', 'participant', '남부 소비에트군 지휘관', 'Commander of Soviet forces in the south', '1918년 병력 3천 명을 드네스트르강에 급파해 루마니아군의 도하를 막았고, 3월 9일 루마니아와의 분쟁 청산 의정서에 서명했다.', 'In 1918 he rushed 3,000 men to the Dniester to stop a Romanian crossing and on 9 March signed the protocol liquidating the conflict with Romania.', 'soviet-forces'],
    ['christian-rakovsky', 'leader', '소비에트 쪽 협상 대표·우크라이나 정부 수반', 'Soviet negotiator; head of the Soviet Ukrainian government', '1918년 룸체로드 부대를 이끌고 3월 9일 아베레스쿠와의 의정서에 서명했다. 1919년 1월 소비에트 우크라이나의 베사라비아·부코비나 권리를 선언했다.', 'Directed Rumcherod forces in 1918 and signed the 9 March protocol with Averescu; in January 1919 asserted Soviet Ukraine\'s claim to Bessarabia and Bukovina.', 'soviet-forces'],
    ['grigory-kotovsky', 'participant', '베사라비아 출신 붉은 군대 지휘관', 'Bessarabian-born Red commander', '1919년 2월 벤데르에 들어가 루마니아 병사들을 몰아냈다가 격퇴되었고, 1924년 몰다비아 자치 공화국 창설 각서를 주도했다.', 'Briefly drove Romanian soldiers out of Bender in February 1919 before being repelled, and in 1924 led the memorandum that launched the Moldavian ASSR.', 'soviet-forces'],
    ['antonov-ovseenko', 'participant', '우크라이나 전선 사령관', 'Commander of the Ukrainian Front', '1919년 5월 호틴을 거쳐 「베사라비아를 해방」하는 작전을 검토했으나 보급 부족 등으로 단념했다.', 'In May 1919 he weighed a march to \"free Bessarabia\" through Khotyn but was dissuaded by supply problems and Romanian successes elsewhere.', 'soviet-forces'],
    ['krestinsky', 'leader', '빈 회담 소련 대표단장', 'Head of the Soviet delegation at Vienna', '1924년 3~4월 빈에서 루마니아와의 관계 정상화 회담에 소련 대표단을 이끌었다.', 'Led the Soviet delegation at the March–April 1924 Vienna talks with Romania.', 'soviet-forces'],
    ['litvinov', 'participant', '소련 외교관', 'Soviet diplomat', '빈 회담에서 베사라비아 주민투표 안을 내놓았으나 루마니아가 거부했다.', 'Proposed a plebiscite in Bessarabia at the Vienna talks, which Romania rejected.', 'soviet-forces'],
    ['vasil-kolarov', 'participant', '발칸 공산주의 연방 서기', 'Secretary of the Balkan Communist Federation', '1924년 8월 8일 루마니아를 다섯 구역으로 나누어 9월 중순 봉기를 일으키는 코민테른 계획 회의를 주재했다.', 'On 8 August 1924 chaired the meeting that drew up the Comintern plan for risings in five zones of Romania in mid-September.', 'soviet-forces'],
    ['chicherin', 'witness', '외무인민위원', 'People\'s Commissar for Foreign Affairs', '몰다비아 자치 공화국 창설이 루마니아의 베사라비아 주장을 강화할 뿐이라며 반대했다.', 'Opposed the creation of the Moldavian ASSR, arguing it would only strengthen Romania\'s position on Bessarabia.', 'soviet-forces'],
    ['frunze', 'participant', '부군사인민위원', 'Deputy People\'s Commissar for Military Affairs', '1924년 코톱스키와 함께 몰다비아 자치 공화국 창설을 추진했다. 러시아어 문서에 따르면 코톱스키는 그에게 베사라비아에 대한 기병 습격을 제안했다.', 'Promoted the founding of the Moldavian ASSR with Kotovsky in 1924; according to Russian Wikipedia Kotovsky proposed a cavalry raid on Bessarabia to him.', 'soviet-forces'],
  ],
  notes: [
    "엇갈린 수치·날짜:",
    "- 스파툴 처리이 개원: en Sfatul·ru Sfatul 1917.12.04(구력 11.21), en Union 12.03(구력 11.20). 본문은 12월 4일.",
    "- 총국장 위원회 선출: en MDR·en Sfatul 12.21(구력 12.08), en Erhan 12.07(구력 11.24), ru 7(20) 12월. 본문은 날짜 없이 「12월」.",
    "- 볼셰비키의 키시너우 장악: en MDR 1918.01.14(구력 1.1, 프론토트델 진입), en Sfatul 01.18(구력 1.5). 본문은 「1월 중순」.",
    "- 벤데르 전투(1918): en Sfatul 「1월 20~25일 5일간, 루마니아군 141명 전사, 대포 800문 노획」(신·구력 불명), ru MDR 1.29 첫 공격 → 2.2 입성·축출 → 2.7 점령, 약 500명 총살(「검은 담장」). 본문은 두 서술을 출처별로 병기, 연표는 ru의 2.7.",
    "- 루드네프와 대의원 45명 처형, 현 농민대회 간부 5명 총살, 볼흐라드 기습: ru MDR만의 서술(소련 시기 문헌 기반). 본문에서 「러시아어 문서에 따르면」으로 처리.",
    "- 합병 결의(4.9) 기권: en Union·en Sfatul 36, ru MDR 38(본문 표결 줄), ru 원문 다른 곳 36. 본문은 36. en Sfatul은 「14개 특권」이라 하면서 11개만 나열 — 본문은 11개 조건.",
    "- 무조건 합병 표결 출석: en 44/125, ru MDR 45, ru 「Бессарабия в составе Румынии」 36. 날짜 en Sfatul 12.09 회의·12.10 법령, ru MDR 11.25~26(구력 표기 불명). 본문은 44명, 「12월 9~10일 밤」.",
    "- 1919 제헌의회 선거 상원 의석: en Union 35, en Bessarabia(페트렌쿠) 37. 본문에서 의석 수는 생략.",
    "- 호틴 봉기 희생: 루마니아 군 문서 300~400 / 5,000, 포틸차크 11,000(과장 추정 15,000+), 국제적색구원회 1925년 11,000, 소련 저자 「5만 사상자」(원래 피란민 5만). 루마니아군 손실 369(전사 159).",
    "- 타타르부나리: en 「1,600명 체포, 3,000명 사망」, ru 「3천 명 넘게 사망」, 함락일 en 9.18 / ru 9.19(화학 포탄 사용은 ru만). 500인 재판: en 489명 기소, 287명 재판, 85명 유죄.",
    "- 몰다비아 자치 공화국 인구: ru 1926 우크라이나인 48.5%·몰도바인 30.1%, en 「3분의 1 미만」. en Bessarabia는 자치 공화국을 드네스트르강 「west bank」라 오기 — 본문은 동쪽(왼쪽 기슭).",
    "- 레닌과 스파툴 처리이 대표단의 면담은 en Sfatul이 「is said to have replied」로 전하는 루마니아 쪽 서술. 소브나르콤의 몰다비아 공화국 인정은 ru만. 레닌은 인물 행에 넣지 않음.",
    "- 4월 6일 『프라우다』 성명: ru 「заместитель М. Литвинова」(리트비노프의 대리인). 본문은 「외무인민위원부 쪽」으로 씀.",
    "- 구력/신력: 1918년 2월 14일 이전 날짜는 영어 문서가 병기한 신력을 썼다. ru 문서의 1918년 1~2월 날짜 일부는 표기 방식이 섞여 있어 연표에는 en과 일치하는 것만 넣음.",
    "표기:",
    "- 루마니아어(국립국어원 루마니아어 표기법): Inculeț 인쿨레츠(ț=ㅊ), Erhan 에르한, Halippa 할리파, Pelivan 펠리반, Pantelimon 판텔리몬, Ciugureanu 추구레아누(ci+모음의 i 묵음), Pântea 펀테아(â=어), Broșteanu 브로슈테아누(자음 앞 ș=슈), Brătianu 브러티아누(사이트 기존 표기와 일치), Văitoianu 버이토이아누, Marghiloman 마르길로만, Averescu 아베레스쿠(사이트 기존), Davidoglu 다비도글루, Catărău 카터러우, Costa-Foru 코스타포루, Bălți 벌치, Chișinău 키시너우(사이트 기존). Sfatul Țării는 지시대로 「스파툴 처리이」(원음에 가까운 표기는 「스파툴 처리이」).",
    "- 러시아어: Klyushnikov 클류시니코프, Yudovsky 유돕스키, Borisov 보리소프, Shcherbachov 셰르바초프, Krivorukov 크리보루코프.",
    "링크 위험:",
    "- 「빈 회담」이 용어 「빈 중재」(vienna-awards)나 「빈 국제연합」으로 잘못 링크되지 않는지 확인.",
    "- 「벤데르」가 오스타프 벤데르(일프·페트로프 카드 본문) 쪽으로 링크될 가능성은 낮지만 확인.",
    "- 「발칸 공산주의 연방」이 용어 「발칸 연방」(balkan-federation)에 부분 일치할 수 있음.",
    "- 「몰다비아 자치 공화국」은 코톱스키 카드 장면 제목 「몰다비아 자치공화국 수립 주도」와 띄어쓰기가 다름.",
        "새 카드 후보(지시 목록 밖): 다니엘 추구레아누(몰다비아 민주공화국 2대 총리), 콘스탄틴 스테레(합병 뒤 스파툴 처리이 의장), 클레안테 다비도글루(호틴 진압 지휘), 그리고리 보리소프(벤데르 1918·1919 지휘), 블라디미르 유돕스키(룸체로드 의장), 게르만 펀테아(국방 총국장, 뒤에 오데사 시장).",
  ],
};
