// Glossary terms for the bessarabia-1917-1924 event (2026-10-04), built with
// lib.js term(). Facts come from the en/ru Wikipedia pages listed in each
// term's sources (fetched 2026-10-04). Dates are New Style.
//
// original (원어명):
//   sfatul-tarii                       Sfatul Țării (ru. Сфатул Цэрий)
//   moldavian-democratic-republic      Republica Democratică Moldovenească (ru. Молдавская демократическая республика)
//   rumcherod                          Румчерод — Центральный исполнительный комитет Советов Румынского фронта,
//                                      Черноморского флота и Одесской области
//   khotyn-uprising-1919               ro. Revolta (Răscoala) de la Hotin; uk. Хотинське повстання (ru. Хотинское восстание)
//   tatarbunary-uprising-1924          ro. Răscoala de la Tatarbunar; uk. Татарбунарське повстання (ru. Татарбунарское восстание)
//   moldavian-assr-1924                Молдавская Автономная Советская Социалистическая Республика (МАССР)
//   union-of-bessarabia-with-romania   Unirea Basarabiei cu România (ru. Присоединение Бессарабии к Румынии)
//
// Sfatul Țării is written 스파툴 처리이 (국립국어원 루마니아어 표기). The bare
// 몰다비아 공화국 / Moldavian Republic is left out of the aliases because the
// Moldavian SSR and present-day Moldova share it; the bare 빈 회담, 호틴 and
// 타타르부나리 stay unlinked.
const { term } = require('../lib');

const E = t => 'https://en.wikipedia.org/wiki/' + encodeURI(t);
const RU = t => 'https://ru.wikipedia.org/wiki/' + encodeURI(t);
const S = {
    sfat: E('Sfatul_Țării'),
    sfatRU: RU('Сфатул_Цэрий'),
    mdr: E('Moldavian_Democratic_Republic'),
    mdrRU: RU('Молдавская_демократическая_республика'),
    union: E('Union_of_Bessarabia_with_Romania'),
    annexRU: RU('Бессарабия_в_составе_Румынии'),
    rumch: E('Rumcherod'),
    rumchRU: RU('Румчерод'),
    khotyn: E('Khotyn_Uprising'),
    tatar: E('Tatarbunary_Uprising'),
    tatarRU: RU('Татарбунарское_восстание'),
    massr: E('Moldavian_Autonomous_Soviet_Socialist_Republic'),
    massrRU: RU('Молдавская_Автономная_Советская_Социалистическая_Республика'),
};

module.exports = [
    term({
        id: 'sfatul-tarii', ko: '스파툴 처리이', en: 'Sfatul Țării', category: 'nationalities', period: '1917–1918', startYear: 1917, endYear: 1918,
        definition: ['1917년 2월 혁명 뒤 베사라비아의 군인·농민·도시·소수민족 단체들이 대표를 보내 구성한 지역 의회. 이름은 「나라의 평의회」라는 뜻이다. 1917년 12월 4일 키시너우에서 열려 몰다비아 민주공화국을 선포하고 정부를 뽑았으며, 1918년 2월 독립을, 4월 9일 자치를 조건으로 한 루마니아와의 합병을 결의했다. 1918년 12월 정족수에 못 미친 회의에서 자치 조건을 버리고 해산했다.',
            'The regional assembly formed in Bessarabia after the February Revolution of 1917 from delegates of soldiers’, peasants’, urban and minority organizations; the name means “Council of the Country”. Opened in Chișinău on 4 December 1917, it proclaimed the Moldavian Democratic Republic and elected its government, declared independence in February 1918 and on 9 April voted for union with Romania on condition of autonomy. In December 1918 a meeting short of a quorum renounced the conditions and the assembly was dissolved.'],
        body: ['자치 의회 요구는 1917년 4월 키시너우의 협동조합 대회에서 처음 나왔고, 11월 몰도바 군인 대회가 베사라비아의 자치를 선언하며 의회 구성을 정했다. 의원은 보통선거가 아니라 단체별로 선출되었다. 처음 120석으로 정했다가 135석, 다시 150석으로 늘렸으며, 몰도바 군인 대회 44명, 몰도바 농민 소비에트 30명, 도시·젬스트보 21명, 정당 10명, 협동조합·노조·문화단체 16명, 소수민족 조직 29명이 배정되었다. 민족별로는 몰도바인 105명, 우크라이나인 15명, 유대인 13명, 러시아인 6명, 불가리아인 3명 등이었다. 의장은 사회혁명당원 이온 인쿨레츠, 부의장은 판 할리파였다. 처음 과반을 얻은 사람은 고참 민족운동가 이온 펠리반이었지만, 혁명을 지지하는 인물을 원한 소수민족 의원들과 러시아 국가 권위와의 연결을 고려해 인쿨레츠로 바뀌었다. 영어 위키백과가 인용한 당대 서술은 이 의회가 평시라면 대표 기관으로 인정받기 어려운 「주로 임명된」 기구였으나 무정부 상태에서 실제 통치 기관이 되었다고 평했다.\n\n스파툴 처리이는 1917년 12월 15일 몰다비아 민주공화국을 선포하고 판텔리몬 에르한이 이끄는 총국장 위원회를 정부로 뽑았다. 러시아어 문서에 따르면 12월 말 에르한이 농민파 회의에서 루마니아군 도입 안을 표결에 부쳐 통과시켰고, 사회주의 블록은 항의하며 의회를 떠났다. 루마니아군이 키시너우에 들어온 뒤인 1918년 2월 6일 독립을 선언했고, 4월 9일 찬성 86, 반대 3, 기권 36, 불참 13으로 조건부 합병을 결의했다. 러시아어 문서는 표결 때 의사당이 루마니아군에 둘러싸여 있었고 공개 호명으로 진행되었다고 쓴다. 합병 뒤 인쿨레츠가 루마니아 정부에 들어가자 콘스탄틴 스테레가 의장이 되었다. 11월 토지개혁안이 승인된 뒤 12월 9~10일 밤 회의에는 125명 가운데 44명만 출석해 나머지 조건을 모두 버리고 의회 해산을 결의했다. 미국 학자 찰스 킹은 이 표결을 정당하지 않다고 보며, 루마니아 역사학은 스파툴 처리이를 베사라비아 자결의 기관으로, 소련 역사학은 점령군 아래의 기구로 그렸다.',
            'The demand for an autonomous assembly was first raised at the Chișinău cooperatives’ congress of April 1917, and in November the Moldavian Soldiers’ Congress proclaimed Bessarabian autonomy and set the assembly’s make-up. Members were chosen by organizations rather than by general election. The original 120 seats grew to 135 and then 150: 44 for the Moldavian Soldiers’ Congress, 30 for the Moldavian peasants’ soviet, 21 for towns and zemstvos, 10 for parties, 16 for cooperatives, trade unions and cultural bodies and 29 for minority organizations. By nationality there were 105 Moldavians, 15 Ukrainians, 13 Jews, 6 Russians and 3 Bulgarians, among others. The Socialist Revolutionary Ion Inculeț was elected president and Pan Halippa vice-president. The veteran national activist Ion Pelivan had first won a majority, but the post went to Inculeț because minority deputies wanted a supporter of the revolution and because his office linked the assembly to Russian state authority. A contemporary account quoted by English Wikipedia judged it a “mostly appointed” body that would hardly pass as representative in normal times but became the effective government amid anarchy.\n\nOn 15 December 1917 Sfatul Țării proclaimed the Moldavian Democratic Republic and elected the Council of Directors General under Pantelimon Erhan as its government. According to Russian Wikipedia, in late December Erhan put the entry of Romanian troops to a vote in the peasant faction and it passed, while the socialist bloc walked out in protest. After the Romanian army had entered Chișinău the assembly declared independence on 6 February 1918, and on 9 April it voted for conditional union by 86 votes to 3, with 36 abstentions and 13 absent. Russian Wikipedia writes that the building was surrounded by Romanian troops and the vote taken by open roll call. When Inculeț joined the Romanian government, Constantin Stere became president. After the land reform was approved in November, only 44 of 125 members attended the session on the night of 9–10 December, which dropped all the other conditions and dissolved the assembly. The American scholar Charles King considers that vote illegitimate; Romanian historiography has presented Sfatul Țării as the organ of Bessarabian self-determination, Soviet historiography as a body acting under an occupying army.'],
        aliases: { ko: [], en: ['Sfatul Tarii', 'Country Council of Bessarabia', 'National Council of Bessarabia'] },
        people: ['ion-inculet', 'pan-halippa', 'pantelimon-erhan', 'ion-pelivan'],
        events: ['bessarabia-1917-1924', 'civil-war'],
        sources: [S.sfat, S.sfatRU, S.union, S.annexRU], locator: 'lead; Prelude and organization; Composition; Union with Romania (en Sfatul Țării); ru Сфатул Цэрий; en Union of Bessarabia with Romania (Greater Romania); ru Бессарабия в составе Румынии',
    }),
    term({
        id: 'moldavian-democratic-republic', ko: '몰다비아 민주공화국', en: 'Moldavian Democratic Republic', category: 'nationalities', period: '1917–1918', startYear: 1917, endYear: 1918,
        definition: ['1917년 12월 15일 베사라비아의 스파툴 처리이가 러시아 연방민주공화국의 일원으로 선포한 공화국. 1918년 2월 6일 독립을 선언했고, 4월 9일 자치를 조건으로 루마니아 왕국과 합병해 법적으로 끝났다. 의회는 스파툴 처리이, 정부는 총국장 위원회(독립 뒤 각료회의)였으며, 대통령은 이온 인쿨레츠, 총리는 판텔리몬 에르한·다니엘 추구레아누·페트루 카자쿠가 차례로 맡았다.',
            'The republic proclaimed on 15 December 1917 by Sfatul Țării of Bessarabia as a member of the Russian Federative Democratic Republic. It declared independence on 6 February 1918 and legally ended on 9 April when it entered a conditional union with the Kingdom of Romania. Its legislature was Sfatul Țării and its government the Council of Directors General (renamed the Council of Ministers after independence); Ion Inculeț was president, and Pantelimon Erhan, Daniel Ciugureanu and Petru Cazacu served in turn as prime minister.'],
        body: ['공화국 이름을 두고 「베사라비아 공화국」 안도 나왔지만, 다수 민족의 이름을 붙여야 한다는 판텔리몬 에르한의 주장이 이겼다. 선언은 보통선거로 인민의회를 소집할 때까지 스파툴 처리이가 권력을 맡고, 땅을 일하는 사람에게 넘기며, 8시간 노동제와 사형 폐지, 모든 민족의 권리를 보장한다고 약속했다. 12월 뽑힌 9인 총국장 위원회는 몰도바인 7명, 우크라이나인 1명, 유대인 1명으로 에르한이 의장 겸 농업, 이온 펠리반이 외무를 맡았다. 러시아어 문서에 따르면 페트로그라드 소비에트와 소브나르콤이 새 공화국을 인정했다. 그러나 공화국은 영토를 장악하지 못했다. 무너지는 러시아군 병사들이 무정부 상태를 키웠고, 토지 문제 결정이 늦어지자 농민들은 지주 영지를 스스로 나누었으며, 명목상 의회에 속한 부대 대부분이 볼셰비키 영향 아래 들어갔다. 1918년 1월 14일에는 룸체로드의 전선부가 수도 키시너우에 들어왔다.\n\n의회의 민족주의 세력이 군사 지원을 청하자 루마니아군이 1월 23일 국경을 넘어 며칠 만에 수도를 차지했고, 한때 의회에 충성했던 아나톨리에 포파 대위 같은 몰도바인 지휘관들도 이에 맞섰다. 루마니아군이 장악한 가운데 2월 6일 공화국은 독립을 선언했고, 우크라이나 인민공화국의 독립으로 러시아와의 연결이 끊겼다는 것이 이유였다. 총국장 위원회는 추구레아누의 각료회의로 바뀌었다. 4월 9일 스파툴 처리이는 지방 자치와 자체 입법·행정기관 유지를 조건으로 루마니아와의 합병을 결의했고, 이것으로 공화국은 법적으로 끝났다. 영어 위키백과는 그 짧은 역사를 러시아 안의 자치기, 독립기, 루마니아와의 연방기로 나눈다. 12월 비밀 회의가 모든 조건을 버린 것은 사실상 루마니아의 병합이었다고 영어 위키백과는 쓴다. 공화국의 국가는 루마니아의 「깨어나라, 루마니아인이여!」였다.',
            'In the debate over the name a “Bessarabian Republic” was proposed, but Pantelimon Erhan’s view that the republic should bear the name of the majority people prevailed. The declaration promised that Sfatul Țării would hold power until a people’s assembly was elected by universal suffrage, that land would pass to those who worked it, and that the eight-hour day, the abolition of the death penalty and the rights of all nationalities would be guaranteed. The nine-member Council of Directors General elected in December had seven Moldavians, one Ukrainian and one Jew, with Erhan as chairman and director for agriculture and Ion Pelivan for foreign affairs. According to Russian Wikipedia, the Petrograd Soviet and the Sovnarkom recognized the new republic. Yet the republic never controlled its territory. Retreating soldiers of the disintegrating Russian army spread anarchy, peasants divided the landlords’ estates themselves while the assembly delayed on land, and most army units nominally subject to it came under Bolshevik influence. On 14 January 1918 the Front Section of the Rumcherod entered the capital, Chișinău.\n\nAfter the nationalist faction of the assembly asked for military help, the Romanian army crossed the border on 23 January and took the capital within days, resisted even by Moldavian commanders once loyal to the assembly, such as Captain Anatolie Popa. With Romanian troops in control the republic declared independence on 6 February, on the grounds that Ukrainian independence had cut it off from Russia, and the Council of Directors General became Ciugureanu’s Council of Ministers. On 9 April Sfatul Țării voted for union with Romania on condition of local autonomy and the survival of its own legislative and executive bodies, which legally ended the republic. English Wikipedia divides its brief history into autonomy within Russia, independence and federation with Romania, and writes that the secret December meeting that dropped all conditions effectively amounted to annexation by Romania. The republic’s anthem was the Romanian “Deșteaptă-te, române!”.'],
        aliases: { ko: ['몰다비아 인민공화국'], en: ["Moldavian People's Republic", 'Republica Democratică Moldovenească'] },
        people: ['ion-inculet', 'pantelimon-erhan', 'ion-pelivan', 'pan-halippa'],
        events: ['bessarabia-1917-1924', 'civil-war', 'ukraine-1917-1921'],
        sources: [S.mdr, S.mdrRU, S.sfat], locator: 'lead; History (Summarized, Detailed); Leadership (en Moldavian Democratic Republic); ru Молдавская демократическая республика; en Sfatul Țării (declaration)',
    }),
    term({
        id: 'rumcherod', ko: '룸체로드', en: 'Rumcherod', category: 'party-state', period: '1917–1918', startYear: 1917, endYear: 1918,
        definition: ['루마니아 전선·흑해 함대·오데사 주 소비에트 중앙집행위원회의 러시아어 약칭. 1917년 5~6월 오데사의 제1차 전선·주 소비에트 대회에서 생겨 헤르손·베사라비아·타브리다현과 포딜리아·볼히니아현 일부를 관할한다고 주장했다. 1917년 12월 볼셰비키와 좌파 사회혁명당 다수로 다시 구성되어 오데사 소비에트 공화국의 최고기관이 되었고, 1918년 초 루마니아군의 베사라비아 진입에 맞서다 5월 활동을 멈추었다.',
            'The Russian abbreviation for the Central Executive Committee of the Soviets of the Romanian Front, the Black Sea Fleet and Odessa Oblast. Created at the First Congress of Front and Oblast Soviets in Odessa in May–June 1917, it claimed authority over the Kherson, Bessarabia and Taurida governorates and parts of Podolia and Volhynia. Re-elected in December 1917 with a Bolshevik and Left SR majority, it became the highest authority of the Odessa Soviet Republic, fought the Romanian entry into Bessarabia in early 1918 and ceased to function in May.'],
        body: ['첫 룸체로드는 우파 사회혁명당원 로르드키파니제를 의장으로 했고, 러시아 임시정부와 전쟁 지속을 지지한 사회혁명당과 멘셰비키가 다수였다. 이들은 10월 혁명에 적대적이었고, 소브나르콤의 총사령관 니콜라이 크릴렌코의 지시로 1917년 12월 16일 해산되었다. 1917년 12월 23일부터 1918년 1월 5일까지 오데사에서 열린 제2차 대회는 소비에트 권력을 인정하고 180명의 새 룸체로드를 뽑았다. 볼셰비키 70명, 좌파 사회혁명당 55명, 농민 단체 23명, 기타 32명이었고, 의장은 페트로그라드 볼셰비키 위원회 출신 블라디미르 유돕스키였다. 기관지는 1917년 7월부터 1918년 3월까지 나온 「혁명의 목소리」였다. 러시아어 문서는 룸체로드가 1917년 12월~1918년 1월 우크라이나 남서부와 몰다비아의 소비에트 권력 수립에 큰 역할을 했다고 쓴다.\n\n1918년 1~3월 룸체로드는 몰다비아 민주공화국 안의 친소비에트 세력을 무력으로 지원했다. 그 전선부(프론토트델)가 1월 키시너우에 들어갔고, 루마니아군이 들어오자 이에 맞서 싸웠다. 소브나르콤 위원단과 함께 루마니아 정부와 협상해, 루마니아 쪽은 3월 5일, 소비에트 쪽은 3월 9일 분쟁 청산 의정서에 서명했다. 소비에트 쪽 서명자는 크리스티안 라콥스키, 브라셰반, 유돕스키, 미하일 무라비요프였고 루마니아 쪽은 알렉산드루 아베레스쿠였다. 의정서는 루마니아군이 두 달 안에 베사라비아에서 철수하고 소비에트 러시아에 적대 행위를 하지 않는다고 정했지만 발효되지 못했다. 루마니아는 같은 3월 5일 동맹국과 베사라비아 양도를 조건으로 한 조약에 서명했고, 독일·오스트리아군이 진격하자 룸체로드는 미콜라이우, 로스토프나도누를 거쳐 4월 예이스크로 옮겨 갔다가 5월 활동을 멈추었다. 유돕스키는 모스크바로 갔다.',
            'The first Rumcherod, chaired by the right SR Lordkipanidze, had a majority of SRs and Mensheviks who supported the Provisional Government and the continuation of the war. Hostile to the October Revolution, it was dissolved on 16 December 1917 on the order of Nikolai Krylenko, the Sovnarkom’s commander-in-chief. The Second Congress, held in Odessa from 23 December 1917 to 5 January 1918, recognized Soviet power and elected a new Rumcherod of 180: 70 Bolsheviks, 55 Left SRs, 23 representatives of peasant organizations and 32 others, with Vladimir Yudovsky, formerly of the Petrograd Bolshevik committee, as chairman. Its newspaper, Golos revolyutsii (Voice of the Revolution), appeared from July 1917 to March 1918. Russian Wikipedia credits it with a large part in establishing Soviet power in south-western Ukraine and Moldavia in December 1917–January 1918.\n\nFrom January to March 1918 the Rumcherod gave military support to the pro-Soviet forces in the Moldavian Democratic Republic; its Front Section (Frontotdel) entered Chișinău in January and fought the incoming Romanian troops. Together with a Sovnarkom collegium it negotiated with the Romanian government a protocol settling the conflict, signed by the Romanian side on 5 March and the Soviet side on 9 March — by Christian Rakovsky, Brashevan, Yudovsky and Mikhail Muravyov for the Soviets and Alexandru Averescu for Romania. Romania undertook to withdraw from Bessarabia within two months and to take no hostile action against Soviet Russia, but the agreement never took effect: on the same 5 March Romania had signed a treaty with the Central Powers that included the transfer of Bessarabia. As the German and Austrian armies advanced, the Rumcherod moved to Mykolaiv, Rostov-on-Don and in April to Yeysk, and in May 1918 it ceased to function; Yudovsky went to Moscow.'],
        aliases: { ko: ['루마니아 전선·흑해 함대·오데사 주 소비에트 중앙집행위원회'], en: ['Central Executive Committee of the Soviets of the Romanian Front, Black Sea Fleet and Odessa Oblast'] },
        people: ['christian-rakovsky', 'mikhail-muravyov', 'nikolai-krylenko'],
        events: ['bessarabia-1917-1924', 'civil-war', 'ukraine-1917-1921'],
        sources: [S.rumch, S.rumchRU], locator: 'lead; Overview (en Rumcherod); История (ru Румчерод)',
    }),
    term({
        id: 'khotyn-uprising-1919', ko: '호틴 봉기', en: 'Khotyn Uprising', category: 'nationalities', period: '1919', startYear: 1919, endYear: 1919,
        definition: ['1919년 1월 7일부터 2월 1일까지 베사라비아 북쪽 끝 호틴군에서 우크라이나 농민을 중심으로 일어난 루마니아 지배 반대 봉기. 드네스트르강 건너 우크라이나 인민공화국 쪽에서 온 무장대가 1월 23일 호틴시를 장악해 「디렉토리아」를 세웠으나, 클레안테 다비도글루 장군의 루마니아군이 2월 1일까지 진압했다. 희생자 수는 출처에 따라 수백 명에서 1만 1천 명 이상까지 크게 엇갈린다.',
            'An insurrection against Romanian rule in Hotin County, the far-northern tip of Bessarabia, from 7 January to 1 February 1919, led mainly by Ukrainian peasants. Partisans who crossed the Dniester from the territory of the Ukrainian People’s Republic took Khotyn on 23 January and formed a “Directorate”, but the Romanian army under General Cleante Davidoglu crushed the revolt by 1 February. Casualty figures range from a few hundred to more than 11,000 depending on the source.'],
        body: ['호틴군은 부코비나와 포딜리아 사이에 있었고, 1900년 무렵이면 우크라이나인이 다수였을 가능성이 크다. 역사가 니콜라에 엔치우에 따르면 1918년 우크라이나인만 사는 마을이 121곳, 루마니아인만 사는 마을이 52곳, 혼합 마을이 16곳이었다. 1918년 10월 22일 호틴 젬스트보는 다수결로 러시아와의 재통합을 청했고, 11월 오스트리아군이 떠난 자리에 다비도글루의 루마니아군이 들어왔다. 봉기에는 우크라이나 농민 외에 우크라이나 인민군을 이탈한 카자크, 몰도바인 무리, 지역 볼셰비키와 백군 계열이 얽혀 있었다. 봉기 지도부인 디렉토리아는 파리 강화회의를 앞두고 호틴군이나 베사라비아 전체의 지위를 바꾸려 했지만, 우크라이나 인민공화국 지지파와 볼셰비키 지지파로 갈려 있었다. 디렉토리아는 호틴 시장을 체포하고 사흘 안에 150만 루블을 내라고 했는데, 부담은 주로 유대인 주민에게 돌아갔다. 우크라이나 인민공화국은 공식적으로 개입을 부인했고, 비밀 지원 여부는 지금도 논쟁거리다.\n\n진압의 피해는 출처마다 다르다. 루마니아 군 기록에는 반란 마을 7곳을 불태우고 봉기군을 최대 5천 명까지 죽였다는 것이 있고, 우크라이나 역사가 포틸차크는 마을 22곳 파괴와 희생자 1만 1천 명, 그 가운데 철도원 165명과 비무장 민간인 500명의 처형을 집계하면서 1만 5천 명 이상이라는 추정은 과장일 것이라고 보았다. 1만 1천 명이라는 숫자는 1925년 국제적색구원회가 처음 퍼뜨린 것이다. 루마니아군 손실은 전사 159명을 포함해 369명이었다. 이온 안토네스쿠를 비롯한 루마니아 장군들도 민간인 무차별 살해가 루마니아를 「야만인의 나라」로 보이게 한다고 비판했다. 농민 약 5만 명과 무장 봉기군 4천~1만 명이 드네스트르강을 건너 달아났고, 참가자 일부는 그리고리 코톱스키의 벤데르 습격에 합류했다. 루마니아와 소련 역사학은 모두 볼셰비키의 역할을 강조했지만, 네덜란드 학자 빔 반 뫼르스 등은 이를 지역적 봉기로 본다.',
            'Hotin County lay between Bukovina and Podolia, and by 1900 Ukrainians were likely a majority of its population; according to the historian Nicolae Enciu, in 1918 it had 121 all-Ukrainian villages, 52 all-Romanian and 16 mixed. On 22 October 1918 the Hotin zemstvo voted by majority for the county’s reunification with Russia, and in November Davidoglu’s Romanian troops replaced the departing Austrians. Besides Ukrainian peasants, the rising drew in Cossack deserters from the Ukrainian People’s Army, groups of Moldovans, local Bolsheviks and White Russians. The Directorate that led it aimed to change the status of the county, or of all Bessarabia, ahead of the Paris Peace Conference, but was divided into pro-UNR and pro-Bolshevik factions. It arrested Khotyn’s mayor and ordered the town to pay 1.5 million rubles within three days, a burden that fell mostly on its Jews. The UNR formally disowned the revolt; whether it covertly supported it remains disputed.\n\nThe toll of the repression varies by source. Romanian army records speak of seven rebel villages burned and as many as 5,000 insurgents killed; the Ukrainian historian Potylchak counts 22 villages destroyed and 11,000 victims, including the arbitrary execution of 165 railwaymen and 500 unarmed civilians, while judging estimates of 15,000 and more probably exaggerated. The figure of 11,000 was first publicized by International Red Aid in 1925. Romanian losses were 369, including 159 killed in action. Romanian generals, Ion Antonescu among them, criticized the random killing of civilians as giving Romania the image of a “country of savages”. Some 50,000 peasants and 4,000 to 10,000 armed rebels fled across the Dniester, and some veterans joined Grigory Kotovsky’s raid on Tighina. Romanian and Soviet historiography alike stressed the Bolsheviks’ role, which scholars such as Wim van Meurs dispute, seeing a local revolt.'],
        aliases: { ko: [], en: ['Hotin Uprising', 'Revolta de la Hotin'] },
        people: ['grigory-kotovsky', 'christian-rakovsky', 'ion-antonescu'],
        events: ['bessarabia-1917-1924', 'ukraine-1917-1921', 'civil-war'],
        sources: [S.khotyn], locator: 'lead; Background; Uprising; Repression; Aftermath and legacy (en Khotyn Uprising)',
    }),
    term({
        id: 'tatarbunary-uprising-1924', ko: '타타르부나리 봉기', en: 'Tatarbunary Uprising', category: 'international', period: '1924', startYear: 1924, endYear: 1924,
        definition: ['1924년 9월 15~18일 루마니아령 남부 베사라비아의 타타르부나리 일대에서 일어난 친소비에트 무장 봉기. 코민테른이 짠 루마니아 봉기 계획의 일부로, 안드레이 클류시니코프(네닌)가 이끈 혁명위원회가 우크라이나 소비에트 공화국에 속하는 「몰다비아 소비에트 공화국」을 선포했으나 루마니아 제3군단에 사흘 만에 진압되었다. 이듬해의 「500인 재판」은 국제적 관심을 끌었다.',
            'A pro-Soviet armed rising in and around Tatarbunary in Romanian-ruled southern Bessarabia on 15–18 September 1924. Part of a Comintern plan for revolt in Romania, it was led by a revolutionary committee under Andrei Klyushnikov (Nenin), which proclaimed a “Moldavian Soviet Republic” as part of the Ukrainian SSR, and was crushed by the Romanian Third Army Corps within three days. The “Trial of the 500” that followed drew international attention.'],
        body: ['1924년 3~4월 빈 회담에서 소련의 베사라비아 주민투표 제안이 거부된 뒤, 코민테른 집행위원회는 7월 20일 각국 공산당에 「러시아 프롤레타리아가 루마니아의 전쟁 위협을 받고 있다」고 알렸다. 8월 8일 발칸 공산주의 연방 서기 바실 콜라로프가 주재한 회의는 루마니아를 다섯 구역으로 나누어 9월 중순 봉기를 일으키는 계획을 세웠고, 1921년 토지개혁에 대한 농민의 불만과 1924년 여름 가뭄으로 남부 베사라비아에 든 기근에 기댔다. 현지에서는 1922년 5월 클류시니코프와 니콜라이 시시만 두 코민테른 요원이 이끄는 소련 직속 당위원회가 카훌·이즈마일·아케르만 3개 군의 마을 25곳과 두 도시에 혁명위원회와 무장대를 꾸리고 무기를 쌓아 두었다. 9월 11일 니콜라예우카 습격 뒤 지도자들이 체포되자 네닌은 일정을 앞당겼다. 9월 15~16일 밤 무장대가 타타르부나리 면사무소를 점령해 공화국을 선포했고, 봉기군은 4천~6천 명으로 대부분 우크라이나인과 러시아인이었다. 루마니아인·불가리아인·독일인 주민은 거의 가담하지 않았다.\n\n루마니아군은 9월 18일 포격 끝에 타타르부나리를 함락했고(러시아어 문서는 19일, 화학 포탄 사용을 주장), 다뉴브 함대도 진압에 나섰다. 클류시니코프는 달아나다 죽었다. 영어 위키백과는 1,600명이 체포되고 3천 명이 죽었다고, 러시아어 위키백과는 3천 명 넘게 죽었다고 쓴다. 1925년 8월 24일부터 12월 2일까지 103일 동안 열린 「500인 재판」에서는 489명이 기소되어 287명이 재판을 받았고 85명이 유죄를 받았는데, 루마니아인은 피고 가운데 9명뿐이었고 유죄자 가운데는 없었다. 로맹 롤랑, 시어도어 드라이저, 알베르트 아인슈타인 등이 피고를 옹호했고, 앙리 바르뷔스는 재판을 지켜본 뒤 『사형집행인들』을 써 루마니아는 「소수민족의 감옥」이라는 이름을 얻었다. 루마니아 당국과 비공산계 사회주의자 일리에 모스코비치, 미국 학자 클라크는 밖에서 꾸민 공산주의 습격으로 보았고, 반 뫼르스는 빈 회담 결렬과 몰다비아 자치 공화국 선포 사이의 시점으로 보아 크렘린의 관여를 확신한다. 우크라이나·러시아 저자들은 경제 위기와 기근, 가혹한 행정을 원인으로 꼽는다.',
            'After Romania rejected the Soviet proposal of a plebiscite in Bessarabia at the Vienna talks of March–April 1924, the Comintern Executive told the communist parties on 20 July that “the Russian proletariat is threatened with war from Romania”. On 8 August a meeting chaired by Vasil Kolarov, secretary of the Balkan Communist Federation, drew up a plan for risings in five zones of Romania by mid-September, counting on peasant resentment of the 1921 land reform and on the famine caused in southern Bessarabia by the drought of summer 1924. On the ground, a Soviet-controlled party committee led from May 1922 by two Comintern agents, Klyushnikov and Nicolai Shishman, had set up revolutionary committees and armed detachments in 25 villages and two towns of Cahul, Ismail and Cetatea Albă counties and stockpiled arms. When leaders were arrested after a raid on Nikolaievca on 11 September, Nenin brought the plan forward. On the night of 15–16 September armed groups seized Tatarbunary town hall and proclaimed the republic; the rebels, 4,000–6,000 strong, were mainly Ukrainians and Russians, with little support from the Romanian, Bulgarian and German populations.\n\nRomanian troops stormed Tatarbunary after shelling it on 18 September (Russian Wikipedia gives the 19th and alleges chemical shells), with the Danube Fleet joining the suppression, and Klyushnikov was killed while fleeing. English Wikipedia reports 1,600 arrested and 3,000 dead, Russian Wikipedia more than 3,000 dead. In the “Trial of the 500”, held for 103 days from 24 August to 2 December 1925, 489 were prosecuted, 287 tried and 85 convicted; only nine defendants and none of the convicted were Romanians. Romain Rolland, Theodore Dreiser and Albert Einstein, among others, spoke for the defendants, and Henri Barbusse attended the trial and wrote The Hangmen, which helped earn Romania the name of a “minorities’ prison”. The Romanian authorities, the non-communist socialist Ilie Moscovici and the American scholar Clark saw a communist raid engineered from without; van Meurs judges its timing between the failed Vienna talks and the proclamation of the Moldavian ASSR too precise for the Kremlin not to have been involved, while Ukrainian and Russian authors stress economic crisis, famine and harsh administration.'],
        aliases: { ko: ['타타르부나르 봉기'], en: ['Tatarbunar Uprising', 'Tatar-Bunar rebellion', 'Răscoala de la Tatarbunar'] },
        people: ['andrei-klyushnikov', 'vasil-kolarov', 'grigory-kotovsky', 'litvinov', 'krestinsky'],
        events: ['bessarabia-1917-1924'],
        sources: [S.tatar, S.tatarRU], locator: 'lead; Background; Plan begins; Aftermath; Different views (en Tatarbunary Uprising); ru Татарбунарское восстание',
    }),
    term({
        id: 'moldavian-assr-1924', ko: '몰다비아 자치 소비에트 사회주의 공화국', en: 'Moldavian Autonomous Soviet Socialist Republic', category: 'nationalities', period: '1924–1940', startYear: 1924, endYear: 1940,
        definition: ['1924년 10월 12일 우크라이나 소비에트 사회주의 공화국 안에 드네스트르강 왼쪽 기슭을 영토로 세워진 자치 공화국. 루마니아에 넘어간 베사라비아에 대한 소련의 주장을 뒷받침하고 그곳에 친소비에트 정서를 퍼뜨리려는 목적이 있었다. 공식 수도는 「일시적으로 점령된 키시너우」로 정했다. 1940년 8월 2일 소련이 베사라비아를 병합해 몰다비아 소비에트 사회주의 공화국을 세우면서 해체되었다.',
            'The autonomous republic created inside the Ukrainian SSR on the left bank of the Dniester on 12 October 1924. It was meant to bolster the Soviet claim to Bessarabia, lost to Romania, and to spread pro-Soviet feeling there; its official capital was the “temporarily occupied” Chișinău. It was dissolved on 2 August 1940, when the Soviet Union, having annexed Bessarabia, formed the Moldavian SSR.'],
        body: ['1924년 2월 그리고리 코톱스키와 루마니아 출신 볼셰비키 등 10명은 러시아 공산당과 우크라이나 공산당 중앙위원회에 각서를 보내, 드네스트르강 왼쪽 기슭에 몰도바인 50만~80만 명이 살고 있으며 몰다비아 공화국이 베사라비아 문제를 푸는 강력한 정치·선전 수단이 될 것이라고 주장했다. 외무인민위원 게오르기 치체린은 이것이 루마니아의 베사라비아 주장을 오히려 강화하고 「루마니아 배외주의」를 자극할 것이라며 반대했다. 우크라이나 공산당 정치국은 3월 7일 신중론을 냈다가 4월 18일 몰도바인 수가 부풀려졌다며 자치가 부적절하다고 결론지었지만, 모스크바는 이를 무시했다. 러시아 공산당 중앙위원회가 7월 29일 자치 공화국 창설을 지시했고, 10월 12일 전우크라이나 중앙집행위원회가 이를 결정했다. 3월에 네 개 구의 자치주로 시작한 영토는 몰도바인이 2.52%에 불과한 발타 등을 더해 11개 구, 7,516제곱킬로미터가 되었다. 임시 수도는 발타였다가 1929년 티라스폴로 옮겨졌다. 1926년 인구조사에서 몰도바인은 30.1%로 우크라이나인 48.5%보다 적었다.\n\n공화국은 빠르게 공업화되었지만 숙련 노동력이 부족해 다른 공화국에서 우크라이나인과 러시아인이 들어왔고, 1928년 산업 노동자 1만 4,300명 가운데 몰도바인은 약 600명이었다. 1925년 기근을 겪었고, 집단화는 우크라이나보다 빨라 1931년 여름 완료되었으며 약 2천 가구가 카자흐스탄으로 추방되었다. 1932~1933년 기근 때는 많은 주민이 드네스트르강을 건너 도망치려 했고, 1932년 2월 23일 올러네슈티 부근에서 40명이 총에 맞아 죽었다. 공화국은 몰도바인이 루마니아인과 다른 민족이라는 주장을 앞세워 키릴 문자로 쓰는 별도의 「몰도바어」 표준을 만들었고, 1932년 라틴 문자로 바꾸었다가 1938년 다시 키릴 문자로 돌아갔다. 1937년 대숙청 때 많은 지식인이 「인민의 적」, 「부르주아 민족주의자」로 몰려 처형되었다. 1940년 6월 소련이 베사라비아를 점령한 뒤, 8월 2일 베사라비아 여섯 개 군과 자치 공화국 서쪽 일부를 합쳐 몰다비아 소비에트 사회주의 공화국이 세워졌다.',
            'In February 1924 Grigory Kotovsky and nine other Bolshevik activists, several of them from Romania, sent a memorandum to the Central Committees of the Russian and Ukrainian Communist Parties arguing that 500,000 to 800,000 Moldavians lived on the left bank of the Dniester and that a Moldavian republic would be a powerful political and propaganda factor in solving the Bessarabian question. The People’s Commissar for Foreign Affairs, Georgy Chicherin, objected that it would only strengthen Romania’s position on Bessarabia and stir up “Romanian chauvinism”. The Politburo of the Ukrainian party counselled prudence on 7 March and on 18 April, finding the Moldavian figures inflated, judged autonomy inappropriate, but Moscow ignored it. The Russian party’s Central Committee ordered the republic’s creation on 29 July, and the All-Ukrainian Central Executive Committee enacted it on 12 October. Begun in March as an autonomous oblast of four districts, it grew to 11 districts and 7,516 km², taking in areas such as Balta, which was only 2.52% Moldavian. The provisional capital was Balta, moved to Tiraspol in 1929. In the 1926 census Moldavians made up 30.1% of the population against 48.5% Ukrainians.\n\nThe republic was industrialized quickly, but for lack of skilled labour Ukrainians and Russians migrated in from other republics; in 1928 only about 600 of 14,300 industrial workers were Moldavians. It went through a famine in 1925, and collectivization, faster than in Ukraine, was complete by summer 1931, with about 2,000 families deported to Kazakhstan. In the famine of 1932–1933 many tried to flee across the Dniester, and near Olănești on 23 February 1932 forty people were shot. The republic promoted the view that Moldavians were distinct from Romanians, creating a separate “Moldavian” standard written in Cyrillic; it switched to the Latin script in 1932 and back to Cyrillic in 1938. In the Great Purge of 1937 many intellectuals were condemned as enemies of the people or bourgeois nationalists and executed. After the Soviet occupation of Bessarabia in June 1940, the Moldavian SSR was formed on 2 August from six Bessarabian counties and the western part of the autonomous republic.'],
        aliases: { ko: ['몰다비아 자치 공화국', '몰다비아 자치공화국'], en: ['Moldavian ASSR', 'Moldavian Autonomous Republic'] },
        people: ['grigory-kotovsky', 'chicherin'],
        events: ['bessarabia-1917-1924', 'ukraine-1917-1921'],
        sources: [S.massr, S.massrRU], locator: 'lead; Creation; Geography; History; Promotion of Moldavian identity; Disbanding (en Moldavian ASSR); ru МАССР (Население)',
    }),
    term({
        id: 'union-of-bessarabia-with-romania', ko: '베사라비아의 루마니아 합병', en: 'Union of Bessarabia with Romania', category: 'international', period: '1918', startYear: 1918, endYear: 1918,
        definition: ['1918년 4월 9일 스파툴 처리이가 몰다비아 민주공화국을 루마니아 왕국과 합치기로 한 결의와 그에 이은 병합 과정. 처음에는 베사라비아의 자치와 토지개혁 등을 조건으로 했으나, 1918년 12월 정족수에 못 미친 회의가 토지개혁 외의 조건을 버렸고 1919년 12월 루마니아 제헌의회가 비준했다. 1920년 파리 의정서로 영국·프랑스·이탈리아가 인정했지만 의정서는 발효되지 않았고, 소비에트 러시아와 미국은 인정하지 않았다.',
            'The vote of Sfatul Țării on 9 April 1918 to unite the Moldavian Democratic Republic with the Kingdom of Romania, and the annexation that followed. At first conditional on Bessarabian autonomy, land reform and other guarantees, it was made unconditional in December 1918 by a meeting short of a quorum that dropped all conditions except land reform, and ratified by the Romanian Constituent Assembly in December 1919. Britain, France and Italy recognized it in the Treaty of Paris of 1920, which never came into force, and Soviet Russia and the United States never recognized it.'],
        body: ['합병 결의는 루마니아군이 베사라비아를 장악한 가운데 이루어졌다. 대지주가 장악한 벌치·소로카·오르헤이 군의회가 좌파 인민주의자가 다수인 스파툴 처리이의 급진 토지개혁보다 왕정이 낫다며 먼저 합병을 청원했고, 몰도바 지도자 다니엘 추구레아누와 이온 인쿨레츠는 이아시에서 루마니아 정부와 협의했다. 4월 9일 표결은 찬성 86, 반대 3, 기권 36(대부분 비루마니아인), 불참 13이었고, 법이 요구한 주민투표는 열리지 않았다. 러시아어 위키백과는 의사당이 기관총을 갖춘 루마니아군에 둘러싸여 있었고 공개 호명으로 표결했다고 쓴다. 조건은 토지개혁 실시, 민주적으로 선출된 자체 의회를 가진 자치, 지방 예산·젬스트보·시의회 통제와 지방 행정관 임명, 지역 단위 징병, 소수민족 권리 존중, 루마니아 정부에 베사라비아 대표 두 명 참여, 직접·평등·비밀·보통선거, 언론·신앙의 자유, 혁명기 정치범 사면 등 11개였다. 당시 루마니아 총리 알렉산드루 마르길로만은 훗날 합병이 루마니아에서 결정되었다고 인정했다.\n\n1918년 11월 토지개혁이 승인되자 스파툴 처리이는 나머지 조건을 모두 없애는 동의를 통과시켰는데, 125명 가운데 44명만 참여해 모두 찬성한 이 표결은 정족수 미달로 정당하지 않다는 평가를 받는다. 의회는 곧 해산되었고 옛 의원들의 항의는 받아들여지지 않았다. 1919년 가을 베사라비아에서 하원의원 90명과 상원의원 35명이 뽑혔고, 12월 20일 이들이 트란실바니아·부코비나 대표와 함께 합병 법령을 비준했다. 파리 강화회의에서 미국·영국·프랑스·이탈리아 대표가 루마니아에 관해 유일하게 합의한 것이 베사라비아 귀속이었지만, 1920년 10월 28일 파리 의정서는 일본이 비준하지 않아 발효되지 못했고 미국은 러시아가 대표되지 않았다며 서명을 거부했다. 소비에트 러시아는 합병이 점령군 아래에서 강요되었다며 인정하지 않았고, 1940년 6월 26일 최후통첩으로 베사라비아를 넘겨받았다. 영국 역사가 버나드 뉴먼은 표결이 베사라비아 주민의 지배적 의사를 대표했다고 보았다. 오늘날 루마니아와 몰도바의 통합 지지자들은 구력 표결 날짜인 3월 27일을 합병 기념일로 지킨다.',
            'The union vote was taken with the Romanian army in control of Bessarabia. The county councils of Bălți, Soroca and Orhei, dominated by large landowners who preferred the royal government to the radical land reform of a Sfatul Țării dominated by left-wing populists, were the first to petition for union, and the Moldavian leaders Daniel Ciugureanu and Ion Inculeț negotiated with the Romanian government in Iași. The vote on 9 April was 86 for, 3 against, 36 abstaining (mostly non-Romanians) and 13 absent, and the national referendum required by law was not held; Russian Wikipedia writes that the building was surrounded by Romanian troops with machine guns and the vote was taken by open roll call. The eleven conditions included land reform; autonomy with a democratically elected diet of its own; control of local budgets, zemstvos and town councils and appointment of local administrators; territorial conscription; respect for minority rights; two Bessarabian ministers in the Romanian government; direct, equal, secret and universal suffrage; freedom of speech and belief; and an amnesty for political offences committed during the revolution. The Romanian prime minister of the day, Alexandru Marghiloman, later admitted that the union had been decided in Romania.\n\nAfter the land reform was approved in November 1918, Sfatul Țării passed a motion removing all the other conditions; only 44 of its 125 members took part, all voting for, and the vote has been judged illegitimate for lack of a quorum. The assembly was soon dissolved and the protests of former deputies were rejected. In the autumn of 1919 Bessarabia elected 90 deputies and 35 senators, who on 20 December ratified the union acts together with the representatives of Transylvania and Bukovina. At the Paris Peace Conference the only Romanian question on which the American, British, French and Italian representatives agreed was that Bessarabia should belong to Romania, but the Treaty of Paris of 28 October 1920 never came into force because Japan failed to ratify it, and the United States refused to sign because Russia was not represented. Soviet Russia rejected the union as imposed under military occupation and took Bessarabia by the ultimatum of 26 June 1940. The British historian Bernard Newman held that the vote represented the prevailing wish in Bessarabia. Supporters of unification in Romania and Moldova today commemorate 27 March, the Old Style date of the vote, as the day of the union.'],
        aliases: { ko: ['베사라비아의 루마니아 통합', '베사라비아와 루마니아의 통합'], en: ['Unirea Basarabiei cu România'] },
        people: ['ion-inculet', 'pan-halippa', 'pantelimon-erhan', 'ion-pelivan'],
        events: ['bessarabia-1917-1924', 'civil-war'],
        sources: [S.union, S.annexRU], locator: 'lead; The Union Act; Greater Romania (en Union of Bessarabia with Romania); ru Бессарабия в составе Румынии',
    }),
];
